### ISSUE TITLE
NoRecordException interface improvement

### ISSUE THREAD

**Issue by diguida** [cms-sw/cmssw#10308]
Dear FWK experts,
with the deployment of the "frozen GT", an issue appeared during MWGR (events with timestamp 0 by TCDS where crashing in prompt reco due to the ECAL laser corrections being served with timestamp-based IOV starting from 1) is now becoming more important.

I am referring to the fact that the `NoRecordException` reports a record as missing.

````
----- Begin Fatal Exception 22-Jul-2015 14:55:35 CEST-----------------------

An exception of category 'NoRecord' occurred while

   [0] Processing run: 194533 lumi: 329 event: 461582793

   [1] Running path 'L1RePack_step'

   [2] Calling event method for module L1GlobalTriggerRawToDigi/'unpackGtDigis'

Exception Message:

No "L1MuTriggerScalesRcd" record found in the EventSetup.

 Please add an ESSource or ESProducer that delivers such a record.

----- End Fatal Exception -------------------------------------------------
````

Actually, the associated tag in the GT is loaded from the Database, but no "valid" validity interval is associated (i.e. run, lumi and timestamp are set to 0) by the `CondDBESSource::setIntervalFor` call.

We would like to request either to add in this exception the check on the validity interval in EDM, or to create a new kind of exception, e.g. `NoValidityIntervalForRecordException` thrown when such a failure occurs.

I am glad to help in the code implementation.

@mmusich @ggovi this is something you might want to comment.

**Comment by Dr15Jones** [comment]
Could you explain further your statement "add in this exception the check on the validity interval in EDM"?

**Comment by Dr15Jones** [comment]
By "add in this exception the check on the validity interval in EDM" do you mean have the exception include the value of ```IOVSyncValue```?

**Comment by diguida** [comment]
@Dr15Jones that's correct.
At this point, I'd prefer to have really two kinds of exceptions:

1. `NoRecordException` stays as it is, as it assumes the Record is not in the `EventSetup`;
1. NoValidityIntervalForRecordException is a new kind of exception, and is thrown when the `IOVSyncValue` returned by `setIntervalFor` call is invalid; this will therefore print also the value of `IOVSyncValue`.

Do you want `CondDBESSource::setIntervalFor` make this check and throw? Is it enough?

**Comment by Dr15Jones** [comment]
We don't want an exception to happen in ```CondDBESSource::setIntervalFor``` since you could have a Record which is not valid for an interval but is also not requested by any module.

The strategy I suggest is
1) addd the ```IOVSyncValue``` to the exception message now since it is easy
2) follow up with a better exception which distinguishes this case. 

2) Is more difficult since the ```EventSetup``` only contains those Records which have valid IOVs and has no knowledge of all the possible Records that ESSources have registered. The ```EventSetupProvider``` does have that information so a bit of work can make the info accessible at the time of ```EventSetup::get<>``` call.

**Comment by Dr15Jones** [comment]
Why do you wish to have a new exception type rather than making sure the exception message states the reason the Record isn't available (i.e. no valid IOV)? Do you want to try to catch the no valid IOV case but not the no Record case?

**Comment by Dr15Jones** [comment]
See #10328

**Comment by diguida** [comment]
@Dr15Jones thanks for your replies.
It seems to me a good strategy. Concerning

> 1. add the `IOVSyncValue` to the exception message now since it is easy

I was not able to find the `IOVSyncValue` where the exception is thrown: I gave a quick look to the code, but with more careful check will do it :-)

> 2. follow up with a better exception which distinguishes this case. Is more difficult since the `EventSetup` only contains those Records which have valid IOVs and has no knowledge of all the possible Records that `ESSources` have registered. The `EventSetupProvider` does have that information so a bit of work can make the info accessible at the time of `EventSetup::get<>` call.

This will allow me to distinguish the following case: no valid IOV for a Record available in the `EventSetup`.

**Comment by diguida** [comment]
ah thanks for the PR!

**Comment by ggovi** [comment]
@Dr15Jones

what are the other possible reasons causing the NoRecordException ( else than no IOV available )?

**Comment by Dr15Jones** [comment]
You could actually have forgotten to put in an ESSource which delivers that Record. That was the case I was anticipating and hence why the present exception message mentions that as a possible remedy.

**Comment by ggovi** [comment]
Ah, yes of course this is the main case.  The aim is to distinguish these two cases, so I guess it's ok.

**Comment by diguida** [comment]
@Dr15Jones @ggovi 
As a summary: the `NoRecordException` is thrown every time one of the following faults occur:

1. No `ESProducer` creates a Record and make it available in the `EventSetup`;
2. No `ESSource` delivers a Record to the `EventSetup`;
3. No valid `IOVSyncValue` for a Record is provided in the `EventSetup`.

With #10328 we can now distinguish all of these cases in the exception message. This is already an improvement. Thanks for making this in a PR.

The next step is to actually distinguish 1 and 2 with `NoRecordException`, and 3 with `NoValidityIntervalForRecordException`. The latter, in fact, would allow us to better figure out cases when a Record is in the `EventSetup` (so the `ESSource` or the `ESProducer` serve it), but the validity interval cannot be set. In the GlobalTag terminology, the condition record is loaded, but the actual payload cannot be consumed by a module due to a missing IOV in the tag.

Is this ok?

**Comment by Dr15Jones** [comment]
But do you really need a new exception, ```NoValidityIntervalForRecordException``` or do we just make the instance of ```NoRecordException``` have in its message either
a) "Add the needed ESProducer or ESSource" or
b) "The Record is being delivered by an ESSource or ESProducer but there exists no valid IOV"

depending on what is causing the Record not to be available?

**Comment by diguida** [comment]
From the point of view of AlCa, i.e. the provider of the conditions, it is better to have these cases separated. If the GT does not hold a record is quite different than having a module unable to set the  validity for it.
OTOH, I understand your point: from the FWK side (i.e. the consumer of the conditions), it is a variation of the same failure, i.e. the `EventSetup` is unable to serve a Record because it not present there.
Your solution looks as a nice tradeoff: same exception (so the FWK counts this as a missing Record in the `EventSetup`), but different messages giving a hint for the possible cause.

Thanks a lot.

P.S.: just to see if I am still failing to see your point of view: the new exception could be useful at the level of the `EventSetupProvider`, having the knowledge of all the possible Records that `ESSources` have registered or `ESProducers` have created...

**Comment by Dr15Jones** [comment]
See #10462

**Comment by diguida** [comment]
Thanks!
I think this solves our issue!

**Comment by Dr15Jones** [comment]
assign core

**Comment by Dr15Jones** [comment]
+1
