### ISSUE TITLE
fatal: destination path already exists error

### ISSUE THREAD

**Issue by ravijanjam** [cms-sw/cmssw#11025]
Hi, 

I am trying to get the HeavyIonsAnalysis package, I get the error as shown below. 
[rjanjam@lxplus0130 src]$ git cms-addpkg HeavyIonsAnalysis.Configuration
No release tags specified, using default CMSSW_5_3_20.
fatal: destination path '/afs/cern.ch/user/r/rjanjam/CMSSW_5_3_20/src' already exists and is not an empty directory.

Any help appreciated !

**Comment by davidlt** [comment]
Your `./src` directory already contains some content before local GIT repository was created, thus `git cms-addpkg` will abort.

You should execute `git cms-init` before you put anything in `./src`.
