### ISSUE TITLE
please update watchlist of govoni (new GEN convener)

### ISSUE THREAD

**Issue by covarell** [cms-sw/cmssw#11057]
@govoni
It should contain all packages:
GeneratorInterface/*

**Comment by davidlt** [comment]
@govoni do you approve?

**Comment by degano** [comment]
@govoni ping?

**Comment by govoni** [comment]
+1

**Comment by smuzaffar** [comment]
assign core
@covarell , sorry for coming back to this very late. Is this still needed?

**Comment by covarell** [comment]
Yes please! govoni is GEN convener since September 2015!!!

**Comment by govoni** [comment]
Hello @smuzaffar ,

could you please add Efe Yazgan to the list as well? He's becoming GEN convener in September. I guess, by the way, that Luca Perrozzi is already there?

pietro

**Comment by smuzaffar** [comment]
efeyazgan is already added as L2 of GEN https://github.com/cms-sw/cms-bot/pull/868
