### ISSUE TITLE
How to rebase ...

### ISSUE THREAD

**Issue by dinardo** [cms-sw/cmssw#11426]
Dear experts,
I found myself several times in the situation where my pull requests required to be rebased.
Unfortunately from your documentation I'm not able to understand a standard procedure to
rebase my CMSSW code. 
Can you please explain to me exactly what's the procedure to rebase ?
Let's say I wrote the code into
CMSSW_7_6_0_patch0/src/Package/mycode.cc
I receive the request to rebase it. What do I do exactly ?
Many thanks,
- Mauro.

**Comment by slava77** [comment]
Here is my first attempt. If someone can make corrections or suggestions, please do.

if you still have your old working area with all packages checked out (preferred starting point):
```
#replace XXX with the release or IB name 
git fetch official-cmssw CMSSW_XXX:CMSSW_XXX
git checkout branchUsedToMakePR 
git checkout -b branchUsedToMakePR-rebX 
# if just new development showed up in main release: 
#    XXX is the head (as 7_6_X)  or an IB with the new change (easier for integration)
# https://cmssdt.cern.ch/SDT/html/showIB.html to see which IB has a conflicting change
git rebase CMSSW_XXX
#or for something with more complex merges included:
# e.g. you did a git cms-merge-topic yourname:branchUsedToMakePR 
#     and then pushed to github and see all the extra merges not from you
#     [aside: don't use cms-merge-topic of old branch before rebasing]
#     YYY will be the current release where you did the merge-topic
git rebase --onto=CMSSW_XXX CMSSW_YYY
# test: push your *rebX branch and check in github web "compare" interface if it looks clean
git push my-cmssw branchUsedToMakePR-rebX
## Now, it's good to checkout a new CMSSW_XXX area and compile and test new version there
# only after the test do a force push to update the original PR
git push my-cmssw -f branchUsedToMakePR-rebX:branchUsedToMakePR
#note that if you closed the PR before doing this force push, 
#    then github wouldn't let it be reopened 
```

if your old test release area is lost
```
git cms-init
git fetch official-cmssw CMSSW_XXX:CMSSW_XXX
git fetch my-cmssw branchUsedToMakePR:branchUsedToMakePR-rebX
#here, YYY is for the release you used to make your original
git cms-sparse-checkout CMSSW_YYY branchUsedToMakePR-rebX
git checkout branchUsedToMakePR-rebX
#pick one as in the case above
# git rebase CMSSW_XXX or another kind of rebase
# ...
```

**Comment by dinardo** [comment]
Hi Slava,
this is useful from the practical point of view for my current problem,
but, in order to avoid to ask this question again for a slightly different case,
it would be better if you can please explain it exactly point by point.

For example: in your first instruction, why shall I need to write CMSSW_XXX:CMSSW_XXX ?
What's "official-cmssw" ? Is a branch ? Is a tag ?
What's difference between branch and tag ?
What's the meaning of -f in here ?
git push my-cmssw -f branchUsedToMakePR-rebX:branchUsedToMakePR
The ":" has a specific meaning ? What is it ?
Many thanks, but as long as the "users" do not understand these commands
and how git works there will always be these questions.
By the way, talking to other "users" (aka "not software experts") about git
they found difficult to understand the mechanism. My point is that I think
you guys should update these instructions: http://cms-sw.github.io/tutorial.html
Many thanks for your patience.
- Mauro.

**Comment by dinardo** [comment]
Hi again,
I'm trying your suggestions and they do not work.
I've checked out a brand new CMSSW version namely: CMSSW_7_6_0_pre2
From in there I did:
git fetch official-cmssw CMSSW_7_6_X:CMSSW_7_6_X
git checkout my-new-feature_76
git checkout -b my-new-feature_76-rebase
git rebase --onto=CMSSW_7_6_X CMSSW_7_6_0_pre2
And I get the following message:

[dinardo@lxplus0072 src]$ git rebase --onto=CMSSW_7_6_X CMSSW_7_6_0_pre2
First, rewinding head to replay your work on top of it...
Applying: Removed ShiftFillLast for static histogram X range
Using index info to reconstruct a base tree...
M	DQM/BeamMonitor/plugins/Vx3DHLTAnalyzer.cc
M	DQM/BeamMonitor/plugins/Vx3DHLTAnalyzer.h
<stdin>:19: trailing whitespace.
/* 
<stdin>:146: trailing whitespace.
		  
<stdin>:152: trailing whitespace.
	      
<stdin>:170: trailing whitespace.
		  
<stdin>:179: trailing whitespace.
		  
warning: squelched 20 whitespace errors
warning: 25 lines add whitespace errors.
Falling back to patching base and 3-way merge...
Auto-merging DQM/BeamMonitor/plugins/Vx3DHLTAnalyzer.h
CONFLICT (content): Merge conflict in DQM/BeamMonitor/plugins/Vx3DHLTAnalyzer.h
Auto-merging DQM/BeamMonitor/plugins/Vx3DHLTAnalyzer.cc
CONFLICT (content): Merge conflict in DQM/BeamMonitor/plugins/Vx3DHLTAnalyzer.cc
Failed to merge in the changes.
Patch failed at 0001 Removed ShiftFillLast for static histogram X range
The copy of the patch that failed is found in:
   /afs/cern.ch/user/d/dinardo/CMSSW_7_6_0_pre2/src/.git/rebase-apply/patch

When you have resolved this problem, run "git rebase --continue".
If you prefer to skip this patch, run "git rebase --skip" instead.
To check out the original branch and stop rebasing, run "git rebase --abort".

What do you suggest to do now ?
Many thanks,
- Mauro.

**Comment by slava77** [comment]
Hi Mauro

Is your "my-new-feature_76" from 760pre2 on github somewehere?
Please give a link.

**Comment by dinardo** [comment]
Hi Slava,
here it is:
https://github.com/dinardo/cmssw/tree/my-new-feature_76
- Mauro.

**Comment by slava77** [comment]
Hi Mauro, I updated the details a bit (above).
Hopefully commands are more clear.

For more details on git commands (more so about non-cms commands), there is a manual or google.
"git command --help" will give details.

In your specific case, the two files you have in your branch ( DQM/BeamMonitor/plugins/Vx3DHLTAnalyzer.cc  DQM/BeamMonitor/plugins/Vx3DHLTAnalyzer.h) have a few hundred lines of differences 
- a. comparing 760pre2 with your changes
- b. comparing 760pre2 with 76X
Not surprisingly, you will have to figure out which changes are "better" yours here in 760pre2 branch or what somebody else added.

**Comment by dinardo** [comment]
Hi Slava,
many thanks. The person that is making the changes to those files is just me.
Any way, I would like force to use the new version of both files.
Fortunately I have a copy of the modified files !!! That I copied over the files in which git find conflicts.
Then I do for example:
git add DQM/BeamMonitor/plugins/Vx3DHLTAnalyzer.cc
and then git rebase --continue
I did it two times for the two files.
At the second time I get the following erro message:
[dinardo@lxplus0073 src]$ git rebase --continue
Applying: Removed ShiftFillLast for static histogram X range
Applying: Removed ShitFillLast because it generates confusion in shifters
Using index info to reconstruct a base tree...
M	DQM/BeamMonitor/plugins/Vx3DHLTAnalyzer.cc
<stdin>:11: trailing whitespace.
      
warning: 1 line adds whitespace errors.
Falling back to patching base and 3-way merge...
No changes -- Patch already applied.

What should I do now ?
Many thanks,
- Mauro.

**Comment by slava77** [comment]
On 9/23/15 9:33 AM, Mauro wrote:
> Falling back to patching base and 3-way merge...
> No changes -- Patch already applied.
> 
> What should I do now ?


you are done with rebase

follow the rest of the steps (test in a recent release and so on)

>
