### ISSUE TITLE
Add comparison operations to edm::RefToBase<>

### ISSUE THREAD

**Issue by Dr15Jones** [cms-sw/cmssw#11692]
Use the product ID and index to allow comparisons.

**Comment by Dr15Jones** [comment]
%core-pending

**Comment by Dr15Jones** [comment]
assign core

**Comment by smuzaffar** [comment]
@Dr15Jones , any update?

**Comment by Dr15Jones** [comment]
Not yet

**Comment by smuzaffar** [comment]
@Dr15Jones , is it still on todo list or should we close it?

**Comment by makortel** [comment]
Technically `RefToBase` is missing `operator<()` while `Ref` and `Ptr` both have that. But it seems to me that this feature would not really be needed (also given that we'd really dream to get rid of `RefToBase`)

**Comment by smuzaffar** [comment]
> But it seems to me that this feature would not really be needed (also given that we'd really dream to get rid of RefToBase)

@makortel , do you want to keep this issue open then?

**Comment by makortel** [comment]
-core

**Comment by makortel** [comment]
@cmsbuild, please close
