### ISSUE TITLE
[UBSAN] DataFormats/Math/interface/approx_exp.h

### ISSUE THREAD

**Issue by davidlt** [cms-sw/cmssw#11753]
This was detected with GCC 4.9.3 UBsan. Triggered 8 times in the matrix. Affects only two workflows: 500205.0 and 50207.0. Step3 in both cases on 1st event.

Two different issues:

```
DataFormats/Math/interface/approx_exp.h:180:3: runtime error: signed integer overflow: -2147483648 + -1 cannot be represented in type 'int'
DataFormats/Math/interface/approx_exp.h:188:31: runtime error: signed integer overflow: 2147483647 + 127 cannot be represented in type 'int'
```

Both happens twice per step.

**Comment by davidlt** [comment]
@slava77 @cvuosalo could you take care of this? Again, I can test patches with UBSan before merging.

@VinInn might be interesting to you.

**Comment by VinInn** [comment]
don't touch.
I know the issue of signed integer overflow in the standard w/r/t reality in x86_64 architectures.
It should be considered a feature.
If we change in unsigned int vectorization is affected.
and this function is supposed to produce silently NaN: again because of vectorization.

**Comment by davidlt** [comment]
What about any other architectures than x86_64 and a different compiler? E.g. I see differences between GCC and Clang in left shifting negative numbers.

**Comment by VinInn** [comment]
@davidIt a good reason to use only GCC on x86_64!
Given the current situation we have to target code.
So please start to add ifdef wherever needed to preserve optimization for GCC on x86_64 and
revert to standard on all other toolchains and architectures.

**Comment by smuzaffar** [comment]
closing it as there are new issues to track ubsan issues.
