### ISSUE TITLE
info in the documentation

### ISSUE THREAD

**Issue by govoni** [cms-sw/cmssw#12099]
to whom it may concern, 

when I read this page:

http://cms-sw.github.io/tutorial-forward-port.html

I see that the doc says:

"First of all lets create an area for the latest / greatest CMSSW available:"

to know what's the latest/greatest I would do "scram list cmssw".
When I do it, I get a lot of different flavors of cmssw_7_XY, but I know that I am making pull-requests in the cmssw_8_ZK.

How can I discover (possibly with scram) what's the current latest/greatest CMSSW available?
IT would be useful to add this info to the man page.

**Comment by Dr15Jones** [comment]
Try doing ```scram list -a CMSSW```

**Comment by govoni** [comment]
Thanks it works.
