### ISSUE TITLE
locally clone a PR into a new CMSSW release

### ISSUE THREAD

**Issue by govoni** [cms-sw/cmssw#12108]
Hello,

I made a pull-request: 

https://github.com/cms-sw/cmssw/pull/12101#issuecomment-151404791

and I would like to "download" it (clone I guess?) into a new CMSSW release for further tests, from my personal my-cmssw.
How can I do it, making sure I just clone the two cmssw packages involved in the pull-request?

**Comment by davidlange6** [comment]
git cms-merge-topic 12101
(which will also run checkdeps so you may get more than your two packages)

**Comment by davidlt** [comment]
You can also do `git cms-merge-topic <github_user>:<branch_name>`

Does this solve your problem and we can close this issue?

**Comment by govoni** [comment]
@davidlange6 @davidlt thanks for the info.
Actually, I simply copied the folders from one release to the other, since for some reasons the cms-merge-topic was dumping in the CMSSW_7_1_20 a lot of packages which were not touched by my modifications.
