### ISSUE TITLE
Obtain the dependencies between modules given a configuration

### ISSUE THREAD

**Issue by Dr15Jones** [cms-sw/cmssw#12125]
Starting from a python configuration, one wants to be able to obtain the dependencies between modules based on what data the modules consume. The information should be available in the form of a text dump.

**Comment by Dr15Jones** [comment]
@fwyzard @lgray please check that this captures the feature you requested. Also, it would be useful to add concrete use cases for the feature.

**Comment by wmtan** [comment]
@fwyzard @lgray @Dr15Jones
PR #12234 implements this feature

**Comment by smuzaffar** [comment]
cms-bot?

**Comment by Dr15Jones** [comment]
assign core

**Comment by Dr15Jones** [comment]
+1
