### ISSUE TITLE
Allow the use of logical OR on Paths

### ISSUE THREAD

**Issue by Dr15Jones** [cms-sw/cmssw#12120]
When building up the sequence of modules on a Path, presently the modules are connected via logical AND. The HLT (and potentially other users) would find it useful to allow also connection via logical OR.

**Comment by Dr15Jones** [comment]
@fwyzard please review

**Comment by Dr15Jones** [comment]
assign core

**Comment by smuzaffar** [comment]
@Dr15Jones , is it still on to do list or should we close this issue?

**Comment by fwyzard** [comment]
This is now supported using the `PathStatusFilter` module.

**Comment by smuzaffar** [comment]
thanks, I am closing this issue then
