### ISSUE TITLE
Allow Paths to depend on other Paths

### ISSUE THREAD

**Issue by Dr15Jones** [cms-sw/cmssw#12123]
It would be useful to allow a Path to only run based on the success or failure of other Paths in the job.

This could be used as an alternative way of handling EndPaths rather than having the OutputModules look at Path results. By using Path dependencies instead of internals of OutputModules the framework could improve its scheduling ability.

**Comment by Dr15Jones** [comment]
@fwyzard please review. It would also be helpful if you could give an additional concrete use case for the feature.

**Comment by Dr15Jones** [comment]
assign core

**Comment by fwyzard** [comment]
I think this has been implemented in CMSSW 9.3.x and later, right ?

**Comment by Dr15Jones** [comment]
This was implemented in #19052 which says it was in the 9_3_X branch

**Comment by Dr15Jones** [comment]
+1

**Comment by Dr15Jones** [comment]
Related to issue #16003

**Comment by Dr15Jones** [comment]
@fwyzard thanks for pointing out this was accomplished.
