### ISSUE TITLE
libdir for python missing

### ISSUE THREAD

**Issue by HeinAtCERN** [cms-sw/cmssw#12139]
Dear cmssw authors,
for some experimentation I needed a more recent version of numpy then what is shipped with cmssw. When trying to ``pip install numpy --target=/mydir/installs/python``, I got an error from the linker: 

    gcc -pthread -shared -L/cvmfs/cms.cern.ch/slc6_amd64_gcc491/external/expat/2.0.1-cms/lib -L/cvmfs/cms.cern.ch/slc6_amd64_gcc491/external/bz2lib/1.0.5-cms/lib -L/cvmfs/cms.cern.ch/slc6_amd64_gcc491/external/db4/4.4.20-cms/lib -L/cvmfs/cms.cern.ch/slc6_amd64_gcc491/external/gdbm/1.10-cms/lib -L/cvmfs/cms.cern.ch/slc6_amd64_gcc491/external/openssl/0.9.8e__1.0.1-cms/lib -L/cvmfs/cms.cern.ch/slc6_amd64_gcc491/external/zlib/1.2.8-cms/lib -L/cvmfs/cms.cern.ch/slc6_amd64_gcc491/external/sqlite/3.7.17-cms/lib /cvmfs/cms.cern.ch/slc6_amd64_gcc491/external/ncurses/5.9-cms/lib/libncurses.a /cvmfs/cms.cern.ch/slc6_amd64_gcc491/external/readline/6.2-cms/lib/libreadline.a build/temp.linux-x86_64-2.7/numpy/core/src/dummymodule.o -L. -Lbuild/temp.linux-x86_64-2.7 -lm -lpython2.7 -o build/lib.linux-x86_64-2.7/numpy/core/_dummy.so
    /cvmfs/cms.cern.ch/slc6_amd64_gcc491/external/gcc/4.9.1-cms/bin/../lib/gcc/x86_64-redhat-linux-gnu/4.9.1/../../../../x86_64-redhat-linux-gnu/bin/ld: cannot find -lpython2.7

I could make the install run with this command, (adding the python libdir by hand):
``pip install vispy --target=/mydir/installs/python --global-option=build_ext --global-option="-L/cvmfs/cms.cern.ch/slc6_amd64_gcc491/external/python/2.7.6-cms/lib/"``

My request is: could you make the ``cmsenv`` command add the python library directory automatically to where it is needed? I see that there are a lot of directories given to gcc..

Best, -H

**Comment by davidlange6** [comment]
I don’t see how we could do this for an arbitrary command (pip in this case).

**Comment by davidlt** [comment]
I have no idea how one would correctly use pip inside CMSSW environment. This is not tested, not supported.

If you need a new version of numpy, get PKGTOOLS/CMSDIST and use PKGTOOLS/cmsBuild to build a new RPM. Then use `scram setup` to import into CMSSW environment. This is the standard way of dealing with CMS packages.

Maybe it relies on `python-config`. I cannot say much without looking into it.

**Comment by HeinAtCERN** [comment]
Ok, thanks. I though there might have been an obvious way on adding the specific library path, since anything that links against libpython2.7 needs it, not just packages that are compiled through pip (so it was not about pip itself).

But now that you've put it this way: I actually thought that my pip installation was from cmssw, but it's not. pip is very useful, wouldn't you like to include it in cmssw?

Thanks again.

**Comment by davidlt** [comment]
Yes, it could be useful for people who wants more Python packages in CMSSW environment. It would require some heavy testing. You also have to remember that CMSSW is installed at read-only locations. Thus you would always need to install it at custom places.

**Comment by HeinAtCERN** [comment]
That's understandable, thanks a lot for the explanations.
