### ISSUE TITLE
Allow PoolSource to modify the run number on each luminosity block to support run dependent MC

### ISSUE THREAD

**Issue by Dr15Jones** [cms-sw/cmssw#12233]
1) add a parameter to PoolSource (or base class) named ‘setRunNumberForEachLumi’ which is a cms.vuint32 which is a container of run numbers to assign to each lumi in the job. This list must contain at least as many entries as there are lumis in the job.

2) Follow the original run dependent MC mechanism where we have the python class ‘RandomRunSource’ which is given the ‘run number to probability’ values and then uses them to assign the run numbers and then sets the appropriate parameter for the EmptySource. This time we’d make a RandomRunPoolSource which takes the same information plus the number of values to ‘throw’ (i.e. max # of lumis the job is likely to see) and uses that to fill the vint32 for setRunNumberForEachLumi of PoolSource.

**Comment by Dr15Jones** [comment]
@davidlange6 is this what you had in mind?

**Comment by smuzaffar** [comment]
cms-bot is going to recognize cmssw issues too

**Comment by Dr15Jones** [comment]
assign core

**Comment by wmtan** [comment]
@Dr15Jones  PR #12753 implements the solution for this issue in CMSSW_8_0_X.

**Comment by Dr15Jones** [comment]
@wmtan Is this one finished? If so, could you add the pull request number to this topic thread?

**Comment by wmtan** [comment]
@Dr15Jones This one was finished weeks ago with PR #12753, as was indicated three weeks ago.

**Comment by Dr15Jones** [comment]
+1
Sorry about missing the earlier comment.
