### ISSUE TITLE
Add davix to the externals for CMSSW

### ISSUE THREAD

**Issue by davidlange6** [cms-sw/cmssw#12377]
@smuzaffar @degano - could you have a look at adding davix to the externals.

https://dmc.web.cern.ch/projects/davix/home#source

there should be a 0.6 release soon, but presumably we can get the spec file created based on 0.4.

**Comment by smuzaffar** [comment]
@iahmad-khan is working on it now

**Comment by smuzaffar** [comment]
this is available in 80X IBs

**Comment by smuzaffar** [comment]
assign externals

**Comment by smuzaffar** [comment]
+1

**Comment by smuzaffar** [comment]
close
