### ISSUE TITLE
watchlist for OlivierBondu

### ISSUE THREAD

**Issue by OlivierBondu** [cms-sw/cmssw#12559]
Hi,

could I be added to the watchlist for all packages in 
[`RecoLocalTracker/*`](https://github.com/cms-sw/cmssw/tree/CMSSW_8_0_X/RecoLocalTracker)

except for 
`RecoLocalTracker/SiPixelClusterizer`
and `RecoLocalTracker/SiPixelRecHits`

Thanks,
Olivier (SiStrip local reco contact)

**Comment by degano** [comment]
@OlivierBondu done in cms-sw/cms-bot#581
