### ISSUE TITLE
Difference between afs and cvmfs mirrors for CMSSW_GIT_REFERENCE

### ISSUE THREAD

**Issue by ferriff** [cms-sw/cmssw#12655]
Dear all, [1]

I am working with CMSSW on a machine outside CERN that has both cvmfs and afs access. Everything works fine by appropriately setting CMSSW_GIT_REFERENCE [2].

However, if I set it to the cvmfs option, after a generic cmsrel + git cms-init I get a working directory of >400 MB, while if I set it to the afs option the working directory is only about 11 MB. The latter seems a much more suitable option to minimize local space, but it is much slower (even with <40 times data transferred).

Is this expected or did I overlook something? Can one use cvmfs ending up with the 11 MB of the afs option?

Any insight is appreciated.

Thanks and cheers,
Federico

[1] landed here from https://cms-sw.github.io/faq.html
[2] cmvfs: /cvmfs/cms.cern.ch/cmssw.git
      afs: /afs/cern.ch/cms/git-cmssw-mirror/cmssw.git

**Comment by ferriff** [comment]
Ping? :) should I send the "issue" to an hn (and in case can you suggest the most appropriate?).
Thanks and cheers,
Federico

**Comment by Dr15Jones** [comment]
Assign core

**Comment by Dr15Jones** [comment]
@smuzaffar Could you find someone to look into this?

**Comment by smuzaffar** [comment]
@degano , can you please check this? my guess is that cvfms one is not being automatically updated.

**Comment by smuzaffar** [comment]
I see there are two cmssw git directories in cvmfs.
1. /cvmfs/cms.cern.ch/cmssw.git  
  this was last updated on 18 FEB 2014
2. /cvmfs/cms.cern.ch/cmssw.git.daily 
  This one look newer.

@ferriff , can you try setting CMSSW_GIT_REFERENCE to /cvmfs/cms.cern.ch/cmssw.git.daily  and let us know it this improves the working directory size?

I have asked Bockjoo Kim  tell us the correct ref.

**Comment by ferriff** [comment]
Great, that improves hugely: the size of the directory is about 9.7 MB.
If Bockjoo Kim confirms that this is the good reference, you may wish to update the instructions: https://cms-sw.github.io/advanced-usage.html
Thanks!!
Federico

**Comment by smuzaffar** [comment]
Bockjoo just confirmed that /cvmfs/cms.cern.ch/cmssw.git.daily is the right one. We will update the instructions, thanks

**Comment by smuzaffar** [comment]
@iahmad-khan , can you please update https://cms-sw.github.io/advanced-usage.html

**Comment by ferriff** [comment]
Great, thank you!

**Comment by iahmad-khan** [comment]
repo name updated

**Comment by smuzaffar** [comment]
+1
thanks @iahmad-khan

**Comment by smuzaffar** [comment]
close
