### ISSUE TITLE
Make LoggedErrorSummary work properly unscheduled 

### ISSUE THREAD

**Issue by Dr15Jones** [cms-sw/cmssw#12699]
The producer which gets all the error messages for a given Event is not guaranteed to be called after all other producers have run. Therefore it is not guaranteed to capture all the all error messages associated to a given Event.

**Comment by Dr15Jones** [comment]
assign core

**Comment by smuzaffar** [comment]
@Dr15Jones , @makortel has this been fixed/implemented?

**Comment by makortel** [comment]
This was addressed in https://github.com/cms-sw/cmssw/pull/20189 (as far as `core` is concerned), and has also been followed up in https://github.com/cms-sw/cmssw/issues/19828

**Comment by makortel** [comment]
+1
