### ISSUE TITLE
Make MixingModule/DataMixer thread efficient

### ISSUE THREAD

**Issue by Dr15Jones** [cms-sw/cmssw#12694]
Allow multiple primary events to run concurrently while using the mixing system.

**Comment by Dr15Jones** [comment]
assign core

**Comment by Dr15Jones** [comment]
@dan131riley this is just meant to keep track of what work Core is doing

**Comment by Dr15Jones** [comment]
@dan131riley Can you remind me which pull request made the change? I'd like to reference it before closing this issue.

**Comment by dan131riley** [comment]
@Dr15Jones

PR#12998

https://github.com/cms-sw/cmssw/pull/12998

**Comment by Dr15Jones** [comment]
+1
