### ISSUE TITLE
Remove circular python dependencies in FWCore/ParameterSet

### ISSUE THREAD

**Issue by Dr15Jones** [cms-sw/cmssw#12696]
In FWCore/ParameterSet/python the modules ```Config``` depends on ```Utilities``` which depends on ```Config```

**Comment by Dr15Jones** [comment]
assign core

**Comment by wmtan** [comment]
@Dr15Jones PR #12838 fixes this in a trivial way. The circular dependency was bogus.

**Comment by Dr15Jones** [comment]
+1
