### ISSUE TITLE
Allow simulation to create new Runs on each LuminosityBlock boundary

### ISSUE THREAD

**Issue by Dr15Jones** [cms-sw/cmssw#12701]
In order to support run dependent monte carlo processing in a finer grain manner, we would like to be able to change the Run number on LuminosityBlock boundaries. This would happen while reading a GEN or GEN+SIM file.

**Comment by Dr15Jones** [comment]
assign core

**Comment by Dr15Jones** [comment]
@wmtan when you get the final pull request, please link it to this issue.

**Comment by Dr15Jones** [comment]
Same as #12233

**Comment by wmtan** [comment]
PR #12001 implemented the fix for issue #12233, which is a duplicate of this issue
