### ISSUE TITLE
Allow multiple SubProcesses per Process

### ISSUE THREAD

**Issue by Dr15Jones** [cms-sw/cmssw#12700]
Allow one Process (or SubProcess) to contain multiple SubProcesses. This was requested by David Lange in order to better support skimming.

**Comment by Dr15Jones** [comment]
assign core

**Comment by Dr15Jones** [comment]
@wmtan this was completed, correct? If so, could you associate the pull request to this issue? Thanks.

**Comment by wmtan** [comment]
Yes, this was done in CMSSW_8_0_X by PR #12001

**Comment by Dr15Jones** [comment]
+1
