### ISSUE TITLE
Need release notes for CMSSW_7_6_2

### ISSUE THREAD

**Issue by davidlange6** [cms-sw/cmssw#12739]
the automated ones failed.

**Comment by davidlange6** [comment]
assign core

**Comment by smuzaffar** [comment]
looking in to it

**Comment by smuzaffar** [comment]
+1
This is now fix. release-note script in cms-bot was failing if there was an indirect merged PR number and it was not able to find it on github

**Comment by smuzaffar** [comment]
https://github.com/cms-sw/cms-bot/commit/cf36c70bf39a6bb966e8e7f8e30a6b5dfde1d4a4 should fix this issue
