### ISSUE TITLE
Process dump python psets first [or how to modify outputCommands from ConfigBuilder]

### ISSUE THREAD

**Issue by slava77** [cms-sw/cmssw#12842]
Context: DataProcessing-like configuration building is done with an instance of cms.Process and then manipulations by ConfigBuilder, the final configuration is made by Process::dumpPython call (there is no intermediate text config file like for configurations made by cmsDriver).

Symptoms: process instance made by ConfigBuilder in python can not have its output module outputCommands modified. (Note that customization works in python text config files.)
More explicitly, say, for the event content defined by RECOEventContent, it is possible to modify the RECOEventContent PSet by just calling process.someOuput.RECOEventContent.remove(something), but it will have no effect on the output modules creaded by ConfigBuilder.
By default the python output module objects made by ConfigBuilder have the content of outputCommands inlined immediately, which looses the relationship with the original PSet. This behavior can be changed by ```  inlineEventContent = False``` option:
it overrides the __dict__["dumpPython"]  for outputCommands and leaves e.g. ```process.someOutput.outputCommands = RECOEventContent.outputCommands``` unchanged (not inlined). After this modification the process.dumpPython will leave ```process.someOutput.outputCommands = RECOEventContent.outputCommands``` as is and the dumped python is not runnable.

Proposed solution: change the order of dumps in Process::dumpPython
https://github.com/cms-sw/cmssw/blob/CMSSW_7_6_3/FWCore/ParameterSet/python/Config.py#L708
Put the self.psets and self.vpsets (and maybe more) first, so that they can be interpreted inside the modules using the psets.

**Comment by slava77** [comment]
assign core

**Comment by slava77** [comment]
looks like I can't assign issues to categories (at least not to core)

**Comment by Dr15Jones** [comment]
assign core

**Comment by Dr15Jones** [comment]
@slava77 can you provide a simple example of a configuration that when one does ```process.dumpPython()``` the resultant output is unrunnable?

**Comment by slava77** [comment]
in CMSSW_7_5_6 (just because I had a test setup there) 
- pick  slava77:CMSSW_7_5_6/sign636/dataProcessingOutputs and compile
- run the following to produce what comes out from Process::dumpPython call somewhere inside the DataProcessing setup
 ``` python Configuration/DataProcessing/test/RunPromptReco.py  --scenario ppRun2 --global-tag  75X_dataRun2_v3  --lfn /whatever --reco --dqmio  --alcareco TkAlMuonIsolated ```
- ``` cmsRun RunPromptRecoCfg.py ``` : as is it will produce an error
```
python encountered the error: <type 'exceptions.AttributeError'>
'Process' object has no attribute 'ALCARECOEventContent'
```
- you can edit RunPromptRecoCfg.py manually by moving the *EventContent PSets from the end to the beginning or by picking the change from slava77:CMSSW_7_5_6/sign636/dataProcessingOutputs-wPythonDump https://github.com/cms-sw/cmssw/compare/CMSSW_7_5_6...slava77:CMSSW_7_5_6/sign636/dataProcessingOutputs-wPythonDump (recompilation in this case will take a while)

Hope this makes it easier to follow.

**Comment by Dr15Jones** [comment]
Maybe posting the part of the configuration which is trying to access ```ALCARECOEventContent``` would be sufficient.

**Comment by slava77** [comment]
I copied the config to ~slava77/public/py/RunPromptRecoCfg_issue12842.py on lxplus

**Comment by Dr15Jones** [comment]
It took a while but I at least tracked down exactly what was happening. In Configuration/Applications/python/ConfigBuilder.py we have the following code

```python
		if not self._options.inlineEventContent and hasattr(self.process,theStreamType+"EventContent"):
				def doNotInlineEventContent(instance,label = "cms.untracked.vstring(process."+theStreamType+"EventContent.outputCommands)"):
					return label
				outputModule.outputCommands.__dict__["dumpPython"] = doNotInlineEventContent
```

What this code does is remove the ```Core``` approved standard member fuction ```dumpPython``` for the instance of the class held by ```outputModule.outputCommands``` and replaces it with the function ```doNotInlineEventContent```. As far as I can tell there are no tests that such behavior should ever work.

@davidlange6 Is this really a behavior you want us to support?

**Comment by Dr15Jones** [comment]
At the Core meeting we decided to have ```Process.dumpPython``` write all known PSets first. This allows the code to work but does not address what I consider a very poor behaviour inside ConfigBuilder.py.

**Comment by Dr15Jones** [comment]
#12870 makes the requested change

**Comment by Dr15Jones** [comment]
+1
