### ISSUE TITLE
Refactor framework code to use propagate_const

### ISSUE THREAD

**Issue by Dr15Jones** [cms-sw/cmssw#12840]
By using propagate_const throughout the framework code we can more easily reason about the const correctness of the code.

**Comment by Dr15Jones** [comment]
assign core

**Comment by Dr15Jones** [comment]
@wmtan you might find this one interesting

**Comment by wmtan** [comment]
@Dr15Jones Yes. Unless you have a higher priority, I can do this next.

**Comment by Dr15Jones** [comment]
Thread safety for Events is the highest priority so any of the issues related to that would be good. I know you enjoy refactoring so I just wanted to be sure you saw this one.

**Comment by Dr15Jones** [comment]
@wmtan is this finished or are there still 'hard' changes waiting?

**Comment by wmtan** [comment]
@Dr15Jones There are still somewhere between 300 and 400 non-const non-mutable pointer data members in core software that may be candidates for propagate_const.

**Comment by smuzaffar** [comment]
@Dr15Jones , any idea if this was completed?

**Comment by Dr15Jones** [comment]
I don't think it is complete. We may have abandoned it however.

@makortel FYI

**Comment by smuzaffar** [comment]
@makortel , should we close this issue then?

**Comment by makortel** [comment]
I guess it would be unlikely for us to return to this topic because of this issue, so let's close it.

**Comment by smuzaffar** [comment]
closing it as suggested
