### ISSUE TITLE
Use consumes information to setup Views

### ISSUE THREAD

**Issue by Dr15Jones** [cms-sw/cmssw#12850]
Use the consumes information to find which View types we need to deal with and then only add entries for those types into the Principals.

**Comment by Dr15Jones** [comment]
assign core

**Comment by wmtan** [comment]
This issue is addressed by PR #13430 , whic uses the type information from the consumes information to control what gets inserted into the lookup tables not just for views, but for all products.

**Comment by Dr15Jones** [comment]
+1
