### ISSUE TITLE
Provide a way to validate PSets of plugins within modules

### ISSUE THREAD

**Issue by Dr15Jones** [cms-sw/cmssw#12853]
Many modules use the plugin architecture to load their own helper classes. They do this by passing part of their PSet to the factory to instantiate the proper object. We need a standard way of validating those parts of the PSet which are used by a plugin.

**Comment by Dr15Jones** [comment]
assign core

**Comment by Dr15Jones** [comment]
We can make 'sub-plugin' validation work if

1) Configuration
If all the configuration options, including the plugin type are contained within one PSet that is defined within the module's configuration: e.g.
```python
foo = cms.EDProducer("FooProd", 
                     pluginDescription = cms.PSet(type = cms.string("BarHelper"),
                                                  value = cms.int32(5) )
``` 

2) The plugin adds a static method `void fillPSetDescription(ParameterSetDescription&)`. E.g.
```C++
void BarHelper::fillPSetDescription(ParameterSetDescription& iPSD) {
   iPSD.add<int>("value", 5);
}
```

3) The module adds a `edm::PluginDescription` node to its `fillDescriptions` call. E.g.
```C++
void FooProd::fillDescriptions(ConfigurationDescriptions& oDesc) {
   //specify how to get the plugin validation
   ParameterSetDescription pluginDesc;
    //'type' is the label to the string containing which plugin to load
   pluginDesc.addNode(edm::PluginDescription<HelperFactory>("type") );

   ParameterSetDescription desc;
   desc.add<ParameterSetDescription>("pluginDescription", pluginDesc);

   oDesc.addDefault(desc);
}
```

4) register the original factory using a different CPP macro
```C++
EDM_REGISTER_VALIDATED_PLUGINFACTORY(HelperFactory, "HelperFactory");
```

5) register all plugins for the factory using a different CPP macro
```C++
DEFINE_EDM_VALIDATED_PLUGIN(HelperFactory, BarHelper, "BarHelper");
```

**Comment by Dr15Jones** [comment]
Under the hood, the two new CPP macros are generating another plugin factory. This factory is used to access the `fillPSetDescription` static function of the plugin. This second factory is used by `edm::PluginDescription<>` to load the correct plugin and then validate the PSet.

This design will support both the validation of the configuration as well as generation of the cfi file if a default plugin type is specified. This design does not support the `edmPluginHelp` system since each factory is a new type unknown to the executable.

**Comment by makortel** [comment]
Some random thoughts on a couple of (possible) use cases

1. Two EDModules using the same plugin (factory), but want different default parameters for the plugin.
   * Not easy to achieve from `fillDescriptions()` side, so basically the other module needs to have the parameters set in its `cfi` file. Copy-paste can be minimized by generating the `cfi` with a different name (as we already do for modifier/era customizations) and then clone that in the "real" cfi, e.g. along
```python
# fooProducer_cfi
from Package.SubPackage.fooProducerDefault_cfi import fooProducerDefault as _fooProducerDefault
fooProducer = _fooProducerDefault.clone(
    pluginPSet = dict(
       someParameter = 5,
    )
)
```

2. Two (or more) EDModules use the same plugin (factory), want to use the same default parameters, but some of the parameters are customized with modifier/era. I suppose in this case one would have to copy the plugin parameters to a `cfi` file with a `PSet`, apply the modifier/era customizations there, and then import the `PSet` to the EDModule `cfi` file. A bit awkward, but can be done.

**Comment by fwyzard** [comment]
Hi @Dr15Jones,
in general I like the idea and approach.

IIRC, many modules already store the name of the plugin they want to load in the plugin PSet itself.
However, many other store the name of the plugin as an external parameter, and only its configuration in a dedicated PSet, e.g.
```python
fooProd = cms.EDProducer("FooProd",
    plugin = cms.string("BarHelper"),
    pluginDescription = cms.PSet(
        value = cms.int32(5)
    )
)
```
To minimise the work of porting the existing modules to the new infrastructure, would it make sense to review which of the two approaches is more widespread, before deciding which one to support ?

In fact I was a bit confused by the fact that you declare the `PluginDescription` outside of the PSet, but then expect the plugin to be specified inside the PSet ? 

About:
>This design does not support the `edmPluginHelp` system since each factory is a new type unknown to the executable.

would it be possible to have some support for it, making use of the fact that the `EDProducer` declares the factory type in the call to `pluginDesc.addNode(edm::PluginDescription<HelperFactory>(...))` ?
For example, the available plugins of the given type is known at run time, so `edmPluginHelp` could print the type and the list of plugins. And optionally also the configuration of the available plugins ?

**Comment by Dr15Jones** [comment]
Implemented in #24622

**Comment by Dr15Jones** [comment]
@fwyzard in the implementation I was able to make `edmPluginHelp` dump all the configurations for the plugins used by a given module. One cannot use `edmPluginHelp` to dump the configuration of just a user defined plugin. It only works by specifying a module making use of the plugin.

**Comment by Dr15Jones** [comment]
@fwyzard 
> In fact I was a bit confused by the fact that you declare the PluginDescription outside of the PSet, but then expect the plugin to be specified inside the PSet ?

In the ParameterSet description system, all PSets are described by their own `edm::ParameterSetDescription` object. The internals of the PSet are specified by nodes added to the `edm::ParameterSetDescription`. By treating the `edm::PluginDescription` as a node describing multiple parameters rather than a PSet itself, all the interfaces using `edm::ParameterSetDescription` could be reused. For example, when describing the validation of a VPSet, that code takes a `edm::ParameterSetDescription` object. Therefore the plugin description system already works for a VPSet of plugin descriptions.

**Comment by makortel** [comment]
I went through the uses of 136 plugin factories (that I found) with git grep. Of them
* 69 were used such that the plugin name was inside the plugin `PSet`
* 19 were used such that the plugin name came outside the plugin `PSet`
   * 1 was used in both ways (and is counted in both categories)
* 27 had no `PSet` parameter (plugin name comes from a `string` parameter)
* 7 were not used
   * this is based on grepping on the typedef/using name of the factory, so has some false positives
* 19 were more complex, examples below
   * following pattern where the plugin name comes from outside of the `PSet`, but not in a `string` (and a variation where there is a mapping in C++ from the name in configuration to the actual type name)
```python
PSet(
    plugins = cms.vstring("pluginName1", "pluginName2", "pluginName3"),
    pluginName1 = cms.PSet( <configuration for pluginName1> ),
    pluginName2 = cms.PSet( <configuration for pluginName2> ),
    pluginName3 = cms.PSet( <configuration for pluginName3> ),
)
```
*
   * complex inferring logic of the plugin type
     * in some cases mapping from a parameter to the plugin name
   * hardcoded plugin name
   * pass same `PSet` to multiple plugin creation calls, each time with a different plugin name read from the `PSet'
   * a `PSet` with "extra" parameters (that the plugin doesn't use) is passed to the plugin
   * no `PSet` passed to the plugin, but in fact an attempt to perform the plugin validation with another plugin factory and hierarchy of plugins

**Comment by makortel** [comment]
+1
