### ISSUE TITLE
scram run tests should clearly show if test passes or fails

### ISSUE THREAD

**Issue by Dr15Jones** [cms-sw/cmssw#12868]
At the moment whether a test run by scram passes or fails is not consistently shown in the log files. Different tests print (or fail to print) their success. We should have scram output to the log whether the executable returns a 0 (a success) or a different value (a failure). This would allow one to ```grep``` a log to find exactly which tests fail.

**Comment by Dr15Jones** [comment]
assign core

**Comment by Dr15Jones** [comment]
@smuzaffar this would save me a lot of effort when looking at log files

**Comment by smuzaffar** [comment]
Normally we grep for 'had ERRORS' as scram prints a message like this
```
---> test <test-name> had ERRORS
```
after each failed tests. What else you want to see @Dr15Jones

**Comment by Dr15Jones** [comment]
I guess I would hope to see
```
---> test <test-name> succeeded
```

**Comment by Dr15Jones** [comment]
What I'd like to be able to do is run ```tail -f``` on a ```scram b runtests``` output and pipe that to grep to see what tests have finished and what status they had. So being able to do 
```
scram b -j 12 runtests >& test.log &
tail -f test.log | grep '---> test'
```
would work.

**Comment by smuzaffar** [comment]
@Dr15Jones , I shall update the build rules to print the following for tests passed
```
---> test <test-name> succeeded
```

**Comment by smuzaffar** [comment]
this is now done in CMSSW_8_0_X

**Comment by smuzaffar** [comment]
+1
