### ISSUE TITLE
remove canDeleteEarly feature of the framework

### ISSUE THREAD

**Issue by Dr15Jones** [cms-sw/cmssw#12932]
A long time ago we added a feature that let one say an Event data product could be deleted before the end of processing of the Event. No configuration outside of the framework unit tests make use of this feature. 
This feature is dangerous since it requires exact knowledge of each module which may use the data product so the product is not deleted before those modules are run. For modules just getting the container directly the `consumes` call would be able to verify this. However, this fails if the container is associated with a `Ref` like instance. In that case we have no way to find such `Ref`s nor know what modules might use them. When run with multiple threads such a `Ref` could be dereferenced at the exact same time the framework decides to delete the object.

**Comment by Dr15Jones** [comment]
assign core

**Comment by slava77** [comment]
In HI processing (likely also in HL-LHC pileup environment) the total memory used often has a large fraction (about a half, maybe) consumed by transient products. If we could use the canDeleteEarly feature there in a safe way, we could save on some needed resources.

**Comment by smuzaffar** [comment]
@Dr15Jones , do we still want to remove this feature? Looks like it is now used in many places outside FW ( https://github.com/cms-sw/cmssw/search?q=canDeleteEarly&type=code )

**Comment by Dr15Jones** [comment]
@makortel

**Comment by makortel** [comment]
I think this issue can be closed in favor of https://github.com/cms-sw/cmssw/issues/16481 .

**Comment by smuzaffar** [comment]
closing it in favor of #16481
