### ISSUE TITLE
Make merge interface of Principal only called by Sources

### ISSUE THREAD

**Issue by Dr15Jones** [cms-sw/cmssw#12946]
When putting data into the Run or LuminosityBlock Principal we call 'putOrMerge'. However, we should never be merging code coming from a Producer.

**Comment by Dr15Jones** [comment]
assign core

**Comment by smuzaffar** [comment]
@Dr15Jones , was https://github.com/cms-sw/cmssw/pull/33230 suppose to address this issue too?

**Comment by Dr15Jones** [comment]
Yes
