### ISSUE TITLE
Remove setting of ProcessHistory in ProductHolderBase

### ISSUE THREAD

**Issue by Dr15Jones** [cms-sw/cmssw#12968]
The ProductHolders do not need to hold onto the `edm::ProcessHistory` describing the history of the entire job. The only reason we appear to do it is `edm::Provenance` class has it just so one can call `getProcessConfiguration` which then allows one to get the `ParameterSet` for the module that made the data product. This would speed up setup of the Principal since we would not be looping through all ProductHolders and giving them this pointer.

One possible way forward would be to  make `edm::Provenance` something that is made on the stack and internally the `ProductHolders` use a different more minimal class.

`edm::Provenance` is not stored so we can do what we need to the internals without worry.

**Comment by Dr15Jones** [comment]
assign core

**Comment by smuzaffar** [comment]
@Dr15Jones , @makortel I see that `ProductHolders ` was refactored here https://github.com/cms-sw/cmssw/pull/13698 . Is this still an open issue?
