### ISSUE TITLE
Do not allow ROOT to use rootlogon.C from edmCheckClassVersion

### ISSUE THREAD

**Issue by Dr15Jones** [cms-sw/cmssw#13017]
We have seen that a user's rootlogon.C file interfered with library loading from edmCheckClassVersion. We should see if there is a way to guarantee that rootlogon.C is not called by that executable.

**Comment by Dr15Jones** [comment]
assign core

**Comment by Dr15Jones** [comment]
@pcanal Any ideas what could be done?

**Comment by pcanal** [comment]
@Dr15Jones You can pass the '-n' option when creating the TApplication or TRint object.

**Comment by Dr15Jones** [comment]
Turns out the problem is actually with .rootlogon.C

**Comment by Dr15Jones** [comment]
#13113

**Comment by smuzaffar** [comment]
#13147 should also fix the edmCheckClassTransients script

**Comment by Dr15Jones** [comment]
+1
