### ISSUE TITLE
Add tests to jenkings

### ISSUE THREAD

**Issue by mverzett** [cms-sw/cmssw#13104]
Dear Release Managers,

with PR #13101 I introduced few unit tests to check that the code used by the SiStrip calibration and local reconstruction group does not break under upstream code changes.

I do not expect the code to break under very common circumstances but, as an example, the requirement of the consumes<>() mechanism in all ED modules in 8.0.X indeed broke the code at runtime.

In order to avoid these and other changes pass unobserved I would like to add [this script](https://github.com/CMSTrackerDPG/cmssw/blob/newStripSW_v2/CalibTracker/SiStripCommon/test/run_tests.sh) to the list of tests that are run by jenkins. Would it be possible? 

Cheers

**Comment by slava77** [comment]
@mverzett 
you should add these tests (assuming they are very short) to the unit tests (edit the BuildFile) in the package where you want the tests to be run.
All full builds of the release and all PR tests with code in your package or in packages it depends on will have these tests running.
https://github.com/cms-sw/cmssw/blob/CMSSW_8_0_X/PhysicsTools/PatAlgos/test/BuildFile.xml

Please try to minimize the amount of overhead and get only the integration test (1 event, probably) and maybe more analyzers combined in one cmsRun where appropriate.

**Comment by mverzett** [comment]
OK, I will implement it as you suggested. How do I test that I implemented it correctly? ```scram test``` in the proper sub-package?

**Comment by slava77** [comment]
On 1/28/16 6:10 AM, Mauro Verzetti wrote:
> OK, I will implement it as you suggested. How do I test that I
> implemented it correctly? |scram test| in the proper sub-package?

scram b runtests

**Comment by mverzett** [comment]
Hi @slava77 ,
I implemented as you suggested (one python cfg running everything, on 3 events). Two questions:
  * Should I add some printout information before/after?
  * The running script will be a binary per se, does not need to be compiled, which keyword should I use in the Buildfile? The example you sent me uses a .cpp script

Thank you again

**Comment by slava77** [comment]
I think that the example from PatAlgos applies directly here. The runtestPhysicsToolsPatAlgos.cpp is just a placeholder, the rest is the "shellName TestDirectoryName scriptNameInTheTestDir" are somewhat intuitive
```xml
<environment>
  <bin   file="runtestPhysicsToolsPatAlgos.cpp">
    <flags   TEST_RUNNER_ARGS=" /bin/bash PhysicsTools/PatAlgos/test runtests.sh"/>
    <use   name="FWCore/Utilities"/>
  </bin>
</environment>
```
