### ISSUE TITLE
Update CLHEP version in 80x

### ISSUE THREAD

**Issue by davidlange6** [cms-sw/cmssw#13102]
@civanch should make a request

**Comment by davidlange6** [comment]
assign simulation

**Comment by civanch** [comment]
A new issue for externals is created: https://github.com/cms-externals/clhep/issues/1 which requires making a new branch for cms-externals/clhep 
@degano , likely you can do this? Or I have to do PR with this new branch inside clhep?

**Comment by civanch** [comment]
+1
done long ago
