### ISSUE TITLE
MulticoreRunLumiEventChecker should use std::thread

### ISSUE THREAD

**Issue by Dr15Jones** [cms-sw/cmssw#13111]
`MulticoreRunLumiEventChecker`is right now using `boost::thread`. This should be switched to using `std::thread`.

**Comment by Dr15Jones** [comment]
assign core

**Comment by smuzaffar** [comment]
@Dr15Jones , I see that `MulticoreRunLumiEventChecker` was dropped in  https://github.com/cms-sw/cmssw/pull/19417 .  So can we close this issue now?
