### ISSUE TITLE
Sort module timing report by time spent in the module

### ISSUE THREAD

**Issue by Dr15Jones** [cms-sw/cmssw#13195]
The _Module Summary_ part of the timing report lists the modules in the order in which they happen to have been added to the internal schedule. This order has no significance to a user. @VinInn suggested that the report should be sorted by decreasing time spent in a module. This would allow one to quickly see which modules are taking the most time.

**Comment by Dr15Jones** [comment]
assign core

**Comment by slava77** [comment]
Grouping by dependence order would be more natural, something that's predictable from parsing the python.
Grouping by time spent or by incidental execution order is all random and seems of a limited use.

**Comment by Dr15Jones** [comment]
I can see ordering by timing making it easy for someone looking at the job as a whole and trying to access what is taking all the time.

I can see ordering by module label to make it easy to find a particular module of interest.

**Comment by wmtan** [comment]
This issue should be solved by PR #13225
