### ISSUE TITLE
warning (eventually error) generated by CLHEP

### ISSUE THREAD

**Issue by VinInn** [cms-sw/cmssw#13236]
this code

```
// On some compilers the static instance of the HepRandom generator
// needs to be created explicitly in the client code (i.e. here).

static const int HepRandomGenActive = HepRandom::createInstance();
```

produce a warning 
/afs/cern.ch/cms/slc7_amd64_gcc530/external/clhep/2.2.0.4/include/CLHEP/Random/Randomize.h:70:18: warning: 'CLHEP::HepRandomGenActive' defined but not used [-Wunused-variable]
 static const int HepRandomGenActive = HepRandom::createInstance();

please ask to be fixed

**Comment by VinInn** [comment]
```
#include "Randomize.hh"               // Include from 'global'
```

is most probably not needed in
/afs/cern.ch/cms/slc7_amd64_gcc530/external/geant4/10.00.p03/include/Geant4/G4SteppingManager.hh:62,

removing it will most probably cause havoc in G4....

**Comment by smuzaffar** [comment]
assign externals

**Comment by smuzaffar** [comment]
@VinInn , warning has been avoided in CLHEP 2.4.0.0 by using `__attribute__((unused))`

```
#if __GNUC__
static const int HepRandomGenActive __attribute__((unused)) = HepRandom::createInstance();
#else
static const int HepRandomGenActive = HepRandom::createInstance();
#endif
```

**Comment by smuzaffar** [comment]
+externals
this has been fixed in clhep.
