### ISSUE TITLE
new FWLite dependencies

### ISSUE THREAD

**Issue by smuzaffar** [cms-sw/cmssw#13254]
#13204 brings in extra FWLite dependencies e.g

DataFormats/HGCRecHit
Geometry/HGCalGeometry

for which many other Geometry packages are needed. Either dependency chain should be cleaned up or please update https://github.com/cms-sw/cmsdist/blob/IB/CMSSW_8_0_X/stable/fwlite_build_set.file

**Comment by smuzaffar** [comment]
assign visualization

**Comment by osschar** [comment]
I guess we should add DataFormats/HGCRecHit to the fwlite_build_set.file (unless it pulls in extra non-fwlite stuff, that is).

Fireworks/Geometry is not part of fwlite so addition of Geometry/HGCalGeometry is not a problem.

**Comment by smuzaffar** [comment]
I have not checked but looks like they do bring in a lot other packages too.

**Comment by osschar** [comment]
Looking at  DataFormats/HGCRecHit/BuildFile.xml and dependencies it seems DataFormats/ForwardDetId is the missing one. This in turn requires FWCore/Utilities and DataFormats/DetId which are both already part of fwlite.

**Comment by alja** [comment]
Looking at the commit #13204 only DataFormats/HGCRecHit package is needed in FWLite pacakge Fireworks/Calo. 

The package  Fireworks/Geometry is not part of FWLite. This is the one that has dependency to Geometry/HGCalGeometry. 

I'm on a family leave till February 29th. I will double check this when I come back.

**Comment by smuzaffar** [comment]
https://github.com/cms-sw/cmssw/pull/13316#issuecomment-187155600 has fixed the fwlite dependency. following packages were missing
```
DataFormats/ForwardDetId
DataFormats/HGCRecHit
```

**Comment by alja** [comment]
Thanks!
I guess this issue can be closed.

**Comment by alja** [comment]
+1
