### ISSUE TITLE
Allow Services to know if cmsRun is ending abnormally

### ISSUE THREAD

**Issue by Dr15Jones** [cms-sw/cmssw#13289]
Add an additional activity which is called if cmsRun is shutting down because of an exception. The JobReport service is already informed but other services may also need that information. Therefore a general purpose activity is more appropriate.

**Comment by Dr15Jones** [comment]
assign core

**Comment by bbockelm** [comment]
#13288 was a duplicate of this.

**Comment by Dr15Jones** [comment]
available in #5165
