### ISSUE TITLE
IB QA tests regenerates .pyc files for release

### ISSUE THREAD

**Issue by smuzaffar** [cms-sw/cmssw#13304]
IBs are installed in read/write volumes of AFS and the way IB unit tests are run (by creating src symlink pointing to $CMSSW_RELEASE_BASE/src) means if either .pyc file is missing in release or .pyc file has a older timestamp than the corresponding .py file then it will be re-generated during the unit tests.

We should make sure that IB installation is read-only and QA tests should not create symlink back to $CMSSW_RELEASE_BASE/src

**Comment by smuzaffar** [comment]
assign core

**Comment by smuzaffar** [comment]
unit test procedur has been updated to not create symlink but instead copy the sources from github.
This is still not enough. RelVals, addon tests still runs under cmsbuild user which has the write permission to the AFS installation. We need to use different users for installation and build/test

**Comment by davidlange6** [comment]
can we take away the write permission after doing the install?

**Comment by davidlt** [comment]
I don't think we have permissions to modify AFS permissions to block cmsbuild from modifying AFS. What if we try to remove write permissions (u-w,g-w, etc) of all files we install? Still wouldn't be a bullet proof as cmsbuild could never that back, but maybe it's enough?

Or it's easier to negotiate additional user with CERN IT?

**Comment by smuzaffar** [comment]
agree, it would be much easier to get and use a new service account.

**Comment by davidlt** [comment]
I probably agree on that, but remember that we need to change AFS permissions for volumes for cmsbuild account. I think permissions are per AFS volumes, is that correct?

**Comment by smuzaffar** [comment]
No, even worst, per directory. Once we have a new user (if agree, I am going to discuss this in todays Core Sw meeting) we allow it to have write permissions. I or Andreas P., should be able to grant the permission.
