### ISSUE TITLE
closed PR's appear in "PR pending plot"

### ISSUE THREAD

**Issue by franzoni** [cms-sw/cmssw#13403]
Hello,

in this useful plot: http://cms-sw.github.io/stats/pending-prs.html

there's pull requests counted as "pending" which are instead closed ( 9713) or merged (e.g. 10178 10176 9750).

Cheers,
Giovanni

**Comment by smuzaffar** [comment]
@franzoni , thanks for pointing this out. We are looking in to it

**Comment by smuzaffar** [comment]
assign core

**Comment by smuzaffar** [comment]
+1
this should be fixed now. Let me know if you still see any inconsistencies
