### ISSUE TITLE
ProvenanceCheckerOutputModule should only get products for which it is 'consumes'

### ISSUE THREAD

**Issue by Dr15Jones** [cms-sw/cmssw#13443]
ProvenanceCheckerOutputModule directly interacts with the `ProductHolderBase` and bypasses any `consumes` specifications.

**Comment by Dr15Jones** [comment]
assign core

**Comment by Dr15Jones** [comment]
GetProductCheckerOutputModule appears to have the same problem.

Both stem from the fact that the OutputModule is given direct access to the Principal class.

**Comment by smuzaffar** [comment]
@Dr15Jones , @makortel is it still the case, if not then can we close the issue?
