### ISSUE TITLE
[CondTools/SiPixel] Fix warning found by gcc 5.3.0

### ISSUE THREAD

**Issue by degano** [cms-sw/cmssw#13575]
Please fix the warning found here: https://cmssdt.cern.ch/SDT/cgi-bin/buildlogs/slc6_amd64_gcc530/CMSSW_8_1_X_2016-03-02-1100/CondTools/SiPixel

```
warning: comparison of constant '2' with boolean expression is always false [-Wbool-compare]
   else if(insertnoisypixelsindb_==2){
```

As the intended behavior is not clear from the context.

**Comment by smuzaffar** [comment]
assign db

**Comment by smuzaffar** [comment]
closing as this has been fix
