### ISSUE TITLE
Output Modules should enforce consumes interface, and not directly use Principals

### ISSUE THREAD

**Issue by wmtan** [cms-sw/cmssw#13599]
Output modules currently have direct access to EventPrincipal, RunPrincipal, and LuminosityBlockPrincipal. Calls to getByLabel() or getForOutput() functions of Principal bypass the consumes interface, so missing consumes calls will not be detected. Fix output modules to not access principals directly, and to use getByToken for all reading of data.

**Comment by Dr15Jones** [comment]
assign core

**Comment by wmtan** [comment]
@Dr15Jones Pull request #13600 implements the solution to this issue.

**Comment by smuzaffar** [comment]
+1
fixed via https://github.com/cms-sw/cmssw/pull/13600
