### ISSUE TITLE
Move from EventPrincipal to edm::Event the check putting the same product twice

### ISSUE THREAD

**Issue by Dr15Jones** [cms-sw/cmssw#13622]
Right now the check that an event product is not being put in the event multiple times is done in the Principal. This causes problems with multi-threading (particularly when a product is deleted early). However, the only way the same product could be put across multiple modules is
- a module gets the product, does a const cast on it and then stuffs it in an `std::own_ptr` or `std::unique_ptr`.
- The modules are communicating via a global

Both of these violate our rules and would lead to multi deletes.

The most likely reason for the same product being put into the event is if it is done within the module which makes the product. (This can happen when using a `std::own_ptr`.) Therefore doing the check only within a module should be sufficient to catch the accidental case.

**Comment by Dr15Jones** [comment]
assign core

**Comment by Dr15Jones** [comment]
The check is done on the address for the `edm::WrapperBase` and not the actual _product_ class put into the event. Since the framework always behind the scenes creates a new `edm::WrapperBase` for items put by an `EDProducer` that means the only source could trigger this check. Since the source doesn't use the `edm::Event` there is no reason to put the check there.

For now it looks like the best solution is just to remove the check all together since it has extremely limited utility.

**Comment by smuzaffar** [comment]
@Dr15Jones , can we close this?

**Comment by Dr15Jones** [comment]
It looks like the check was removed entirely. So I guess it can be closed?
