### ISSUE TITLE
Make EarlyDeleteHelper thread-safe

### ISSUE THREAD

**Issue by Dr15Jones** [cms-sw/cmssw#13629]
The EarlyDeleteHelper deals with the case where an event product is supposed to be deleted before the end of the event. When we allow multiple threads per event this code will need to take that into account.

**Comment by Dr15Jones** [comment]
assign core

**Comment by Dr15Jones** [comment]
#13727

**Comment by Dr15Jones** [comment]
+1

**Comment by smuzaffar** [comment]
@Dr15Jones , can we close this?

**Comment by Dr15Jones** [comment]
It can be closed
