### ISSUE TITLE
Do not call Event::getAllProvenance if one does not need the per event provenance

### ISSUE THREAD

**Issue by Dr15Jones** [cms-sw/cmssw#13624]
It appears that most (if not all) calls to Event::getAllProvenance just want the stable job information (e.g. module labels) for the products that maybe available in the event. Therefore we should add a new method which gives access to just the `edm::BranchDescription` information.

The reason we want to avoid `Event::getAllProvenance` type calls is ones we start to use multiple-threads per event the _available_ provenance can change during the call and can change from one job to another using the same configuration and processing the same event.

**Comment by Dr15Jones** [comment]
assign core

**Comment by wmtan** [comment]
@Dr15Jones PR #13722 solves this issue.

**Comment by smuzaffar** [comment]
+1
