### ISSUE TITLE
deltaR.h

### ISSUE THREAD

**Issue by andreypz** [cms-sw/cmssw#13657]
Hi, 
I just have a couple simple questions about this: 
DataFormats/Math/interface/deltaR.h

 * In the file it includes DataFormats/Math/interface/deltaPhi.h but the deltaPhi is not used in any method. Am I missing something?
 * Then, in multiple places there are comments not to use deltaR but use deltaR2 instead. Why is that? I always use deltaR.

Thanks,
Andrey

**Comment by Dr15Jones** [comment]
I suggest asking these questions in the CMS physics tools hypernews. Issues are normally used to report code problems or request new features.
