### ISSUE TITLE
Error in multi-threaded calls to TH2::DoProfile

### ISSUE THREAD

**Issue by bouril** [cms-sw/cmssw#13669]
Integration Build CMSSW_8_1_THREADED_X_2016-03-08-2300

test 140.2 PhotonJets_Pt_10_13_HI

Error 35584 in step 3   in TH2::DoProfile

step1: das_client.py--cache .../das-cache.file --query 'file dataset=/RelValPhotonJets_Pt_10_13_HI/CMSSW_7_6_0_pre6-76X_mcRun2_HeavyIon_v4-v1/GEN-SIM site=T2_CH_CERN' | sort -u > step1_dasquery.log 2>&1
step2: cmsDriver.py step2 --conditions auto:run2_mc_hi --scenario HeavyIons -n 2 --era Run2_HI --eventcontent FEVTDEBUGHLT -s DIGI:pdigi_valid,L1,DIGI2RAW,HLT:HIon --datatier GEN-SIM-DIGI-RAW-HLTDEBUG --beamspot NominalHICollision2015 --customise Validation/Performance/TimeMemorySummary.customiseWithTimeMemorySummary --customise FWCore/Concurrency/dropNonMTSafe.dropNonMTSafe --prefix 'timeout --signal SIGTERM 7200 ' --filein filelist:step1_dasquery.log --fileout file:step2.root --suffix "-j JobReport2.xml " --nThreads 4 > step2_PhotonJets_Pt_10_13_HI+PhotonJets_Pt_10_13_HIINPUT+DIGIHI+RECOHI+HARVESTHI.log 2>&1
step3: cmsDriver.py step3 --conditions auto:run2_mc_hi -s RAW2DIGI,L1Reco,RECO,VALIDATION,DQM -n 2 --era Run2_HI --eventcontent RECOSIM,MINIAODSIM,DQM --runUnscheduled --scenario HeavyIons --datatier GEN-SIM-RECO,MINIAODSIM,DQMIO --beamspot NominalHICollision2015 --customise Validation/Performance/TimeMemorySummary.customiseWithTimeMemorySummary --customise FWCore/Concurrency/dropNonMTSafe.dropNonMTSafe --prefix 'timeout --signal SIGTERM 7200 ' --filein file:step2.root --fileout file:step3.root --suffix "-j JobReport3.xml " --nThreads 4 > step3_PhotonJets_Pt_10_13_HI+PhotonJets_Pt_10_13_HIINPUT+DIGIHI+RECOHI+HARVESTHI.log 2>&1

Error log:
=======

 ################################################################### 
 # WARNING: this module is deprecated.                             # 
 # Please use CondCore.CondDB.CondDB_cfi.py                        # 
 ################################################################### 
L1TRawToDigi Sequence configured for Stage-1 (2015) trigger. 
L1TReco Sequence configured for Stage-1 (2015) trigger. 
WARNING:  L1Trigger/L1TCommon/python/caloStage1LegacyFormatDigis_cfi.py has been deprecated...
WARNING:  please use L1Trigger/L1TCalorimeter/python/caloStage1LegacyFormatDigis_cfi.py
# Conditions read from  CMS_CONDITIONS  via FrontierProd 
%MSG-i ThreadSetup:  (NoModuleName) 09-Mar-2016 11:10:39 CET pre-events
setting # threads 4
%MSG
DQMStore: histogram collation is enabled
09-Mar-2016 11:10:46 CET  Initiating request to open file file:step2.root
09-Mar-2016 11:10:47 CET  Successfully opened file file:step2.root
Begin processing the 1st record. Run 1, Event 1352, LumiSection 10 at 09-Mar-2016 11:12:18.773 CET
Begin processing the 2nd record. Run 1, Event 1351, LumiSection 10 at 09-Mar-2016 11:12:18.774 CET
%MSG-w EcalDQM:  EcalDQMonitorTask:ecalMonitorTask 09-Mar-2016 11:12:34 CET  Run: 1 Event: 1352
Ecal Monitor Source::runOnCollection: EBReducedRecHit does not exist
%MSG
%MSG-w EcalDQM:  EcalDQMonitorTask:ecalMonitorTask 09-Mar-2016 11:12:34 CET  Run: 1 Event: 1351
Ecal Monitor Source::runOnCollection: EBReducedRecHit does not exist
%MSG
%MSG-w EcalDQM:  EcalDQMonitorTask:ecalMonitorTask 09-Mar-2016 11:12:34 CET  Run: 1 Event: 1351
Ecal Monitor Source::runOnCollection: EEReducedRecHit does not exist
%MSG
%MSG-w EcalDQM:  EcalDQMonitorTask:ecalMonitorTask 09-Mar-2016 11:12:35 CET  Run: 1 Event: 1352
Ecal Monitor Source::runOnCollection: EEReducedRecHit does not exist
%MSG
%MSG-e HotlineDQM:  HotlineDQM:hotlineDQM_HT 09-Mar-2016 11:12:37 CET  Run: 1 Event: 1351
invalid collection: PFMET

%MSG
%MSG-e HotlineDQM:  HotlineDQM:hotlineDQM_HT 09-Mar-2016 11:12:37 CET  Run: 1 Event: 1352
invalid collection: PFMET

%MSG
%MSG-e HotlineDQM:  HotlineDQM:hotlineDQM_HT_Tight 09-Mar-2016 11:12:37 CET  Run: 1 Event: 1352
invalid collection: PFMET

%MSG
%MSG-e HotlineDQM:  HotlineDQM:hotlineDQM_Photon 09-Mar-2016 11:12:37 CET  Run: 1 Event: 1352
invalid collection: PFMET

%MSG
%MSG-e HotlineDQM:  HotlineDQM:hotlineDQM_Photon_Tight 09-Mar-2016 11:12:37 CET  Run: 1 Event: 1352
invalid collection: PFMET

%MSG
%MSG-e HotlineDQM:  HotlineDQM:hotlineDQM_Muon 09-Mar-2016 11:12:37 CET  Run: 1 Event: 1352
invalid collection: PFMET

%MSG
%MSG-e HotlineDQM:  HotlineDQM:hotlineDQM_Muon_Tight 09-Mar-2016 11:12:37 CET  Run: 1 Event: 1352
invalid collection: PFMET

%MSG
%MSG-e HotlineDQM:  HotlineDQM:hotlineDQM_MET 09-Mar-2016 11:12:37 CET  Run: 1 Event: 1352
invalid collection: PFMET

%MSG
%MSG-e HotlineDQM:  HotlineDQM:hotlineDQM_MET_Tight 09-Mar-2016 11:12:37 CET  Run: 1 Event: 1352
invalid collection: PFMET

%MSG
%MSG-e HotlineDQM:  HotlineDQM:hotlineDQM_PFMET 09-Mar-2016 11:12:37 CET  Run: 1 Event: 1352
invalid collection: PFMET

%MSG
%MSG-e HotlineDQM:  HotlineDQM:hotlineDQM_PFMET_Tight 09-Mar-2016 11:12:37 CET  Run: 1 Event: 1352
invalid collection: PFMET

%MSG
%MSG-e HotlineDQM:  HotlineDQM:hotlineDQM_HT_Tight 09-Mar-2016 11:12:37 CET  Run: 1 Event: 1351
invalid collection: PFMET

%MSG
%MSG-e HotlineDQM:  HotlineDQM:hotlineDQM_Photon 09-Mar-2016 11:12:37 CET  Run: 1 Event: 1351
invalid collection: PFMET

%MSG
%MSG-e HotlineDQM:  HotlineDQM:hotlineDQM_Photon_Tight 09-Mar-2016 11:12:37 CET  Run: 1 Event: 1351
invalid collection: PFMET

%MSG
%MSG-e HotlineDQM:  HotlineDQM:hotlineDQM_Muon 09-Mar-2016 11:12:37 CET  Run: 1 Event: 1351
invalid collection: PFMET

%MSG
%MSG-e HotlineDQM:  HotlineDQM:hotlineDQM_Muon_Tight 09-Mar-2016 11:12:37 CET  Run: 1 Event: 1351
invalid collection: PFMET

%MSG
%MSG-e HotlineDQM:  HotlineDQM:hotlineDQM_MET 09-Mar-2016 11:12:37 CET  Run: 1 Event: 1351
invalid collection: PFMET

%MSG
%MSG-e HotlineDQM:  HotlineDQM:hotlineDQM_MET_Tight 09-Mar-2016 11:12:37 CET  Run: 1 Event: 1351
invalid collection: PFMET

%MSG
%MSG-e HotlineDQM:  HotlineDQM:hotlineDQM_PFMET 09-Mar-2016 11:12:37 CET  Run: 1 Event: 1351
invalid collection: PFMET

%MSG
%MSG-e HotlineDQM:  HotlineDQM:hotlineDQM_PFMET_Tight 09-Mar-2016 11:12:37 CET  Run: 1 Event: 1351
invalid collection: PFMET

%MSG
%MSG-w BSFitter:  AlcaBeamMonitor:AlcaBeamMonitor@endLumi  09-Mar-2016 11:12:39 CET Run: 1 Lumi: 10
need at least 150 tracks to run beamline fitter.
%MSG

A fatal system signal has occurred: segmentation violation
The following is the call stack containing the origin of the signal.

Thread 5 (Thread 0x7f23fbeff700 (LWP 30045)):
#0  0x000000371be0f37d in waitpid () from /lib64/libpthread.so.0
#1  0x00007f240ea12b27 in edm::service::cmssw_stacktrace_fork() () from /cvmfs/cms-ib.cern.ch/week1/slc6_amd64_gcc493/cms/cmssw/CMSSW_8_1_THREADED_X_2016-03-08-2300/lib/slc6_amd64_gcc493/pluginFWCoreServicesPlugins.so
#2  0x00007f240ea13462 in edm::service::InitRootHandlers::stacktraceHelperThread() () from /cvmfs/cms-ib.cern.ch/week1/slc6_amd64_gcc493/cms/cmssw/CMSSW_8_1_THREADED_X_2016-03-08-2300/lib/slc6_amd64_gcc493/pluginFWCoreServicesPlugins.so
#3  0x00007f2411373ac0 in execute_native_thread_routine () from /cvmfs/cms-ib.cern.ch/2016-11/slc6_amd64_gcc493/external/gcc/4.9.3/lib64/libstdc++.so.6
#4  0x000000371be07aa1 in start_thread () from /lib64/libpthread.so.0
#5  0x000000371b6e893d in clone () from /lib64/libc.so.6
Thread 4 (Thread 0x7f231abff700 (LWP 31479)):
#0  0x000000371b6e5199 in syscall () from /lib64/libc.so.6
#1  0x00007f241141c0c2 in tbb::internal::futex_wait (comparand=2, futex=0x7f240ff4512c) at ../../include/tbb/machine/linux_common.h:60
#2  tbb::internal::binary_semaphore::P (this=0x7f240ff4512c) at ../../src/tbb/semaphore.h:206
#3  rml::internal::thread_monitor::commit_wait (c=<synthetic pointer>, this=0x7f240ff45120) at ../../src/rml/include/../server/thread_monitor.h:259
#4  tbb::internal::rml::private_worker::run (this=0x7f240ff45100) at ../../src/tbb/private_server.cpp:282
#5  0x00007f241141c0e9 in tbb::internal::rml::private_worker::thread_routine (arg=<optimized out>) at ../../src/tbb/private_server.cpp:228
#6  0x000000371be07aa1 in start_thread () from /lib64/libpthread.so.0
#7  0x000000371b6e893d in clone () from /lib64/libc.so.6
Thread 3 (Thread 0x7f231a1fe700 (LWP 31480)):
#0  0x000000371b6e5199 in syscall () from /lib64/libc.so.6
#1  0x00007f241141c0c2 in tbb::internal::futex_wait (comparand=2, futex=0x7f240ff451ac) at ../../include/tbb/machine/linux_common.h:60
#2  tbb::internal::binary_semaphore::P (this=0x7f240ff451ac) at ../../src/tbb/semaphore.h:206
#3  rml::internal::thread_monitor::commit_wait (c=<synthetic pointer>, this=0x7f240ff451a0) at ../../src/rml/include/../server/thread_monitor.h:259
#4  tbb::internal::rml::private_worker::run (this=0x7f240ff45180) at ../../src/tbb/private_server.cpp:282
#5  0x00007f241141c0e9 in tbb::internal::rml::private_worker::thread_routine (arg=<optimized out>) at ../../src/tbb/private_server.cpp:228
#6  0x000000371be07aa1 in start_thread () from /lib64/libpthread.so.0
#7  0x000000371b6e893d in clone () from /lib64/libc.so.6
Thread 2 (Thread 0x7f23197fd700 (LWP 31481)):
#0  0x000000371b6e5199 in syscall () from /lib64/libc.so.6
#1  0x00007f241141c0c2 in tbb::internal::futex_wait (comparand=2, futex=0x7f240ff450ac) at ../../include/tbb/machine/linux_common.h:60
#2  tbb::internal::binary_semaphore::P (this=0x7f240ff450ac) at ../../src/tbb/semaphore.h:206
#3  rml::internal::thread_monitor::commit_wait (c=<synthetic pointer>, this=0x7f240ff450a0) at ../../src/rml/include/../server/thread_monitor.h:259
#4  tbb::internal::rml::private_worker::run (this=0x7f240ff45080) at ../../src/tbb/private_server.cpp:282
#5  0x00007f241141c0e9 in tbb::internal::rml::private_worker::thread_routine (arg=<optimized out>) at ../../src/tbb/private_server.cpp:228
#6  0x000000371be07aa1 in start_thread () from /lib64/libpthread.so.0
#7  0x000000371b6e893d in clone () from /lib64/libc.so.6
Thread 1 (Thread 0x7f2410ff5b80 (LWP 29412)):
#0  0x000000371b6df113 in poll () from /lib64/libc.so.6
#1  0x00007f240ea132c4 in full_read.constprop () from /cvmfs/cms-ib.cern.ch/week1/slc6_amd64_gcc493/cms/cmssw/CMSSW_8_1_THREADED_X_2016-03-08-2300/lib/slc6_amd64_gcc493/pluginFWCoreServicesPlugins.so
#2  0x00007f240ea1352c in edm::service::InitRootHandlers::stacktraceFromThread() () from /cvmfs/cms-ib.cern.ch/week1/slc6_amd64_gcc493/cms/cmssw/CMSSW_8_1_THREADED_X_2016-03-08-2300/lib/slc6_amd64_gcc493/pluginFWCoreServicesPlugins.so
#3  0x00007f240ea136ab in sig_dostack_then_abort () from /cvmfs/cms-ib.cern.ch/week1/slc6_amd64_gcc493/cms/cmssw/CMSSW_8_1_THREADED_X_2016-03-08-2300/lib/slc6_amd64_gcc493/pluginFWCoreServicesPlugins.so
#4  <signal handler called>
#5  0x00007f23bbc81000 in ?? ()
#6  0x00007f2411b03551 in TList::FindObject(char const*) const () from /cvmfs/cms-ib.cern.ch/week1/slc6_amd64_gcc493/cms/cmssw/CMSSW_8_1_THREADED_X_2016-03-08-2300/external/slc6_amd64_gcc493/lib/libCore.so
#7  0x00007f2411a0210a in TROOT::FindObject(char const*) const () from /cvmfs/cms-ib.cern.ch/week1/slc6_amd64_gcc493/cms/cmssw/CMSSW_8_1_THREADED_X_2016-03-08-2300/external/slc6_amd64_gcc493/lib/libCore.so
#8  0x00007f240a0b1858 in TH2::DoProfile(bool, char const*, int, int, char const*) const () from /cvmfs/cms-ib.cern.ch/week1/slc6_amd64_gcc493/cms/cmssw/CMSSW_8_1_THREADED_X_2016-03-08-2300/external/slc6_amd64_gcc493/lib/libHist.so
#9  0x00007f23d090d189 in MuonTrackValidatorBase::doProfileX(TH2*, MonitorElement*) () from /cvmfs/cms-ib.cern.ch/week1/slc6_amd64_gcc493/cms/cmssw/CMSSW_8_1_THREADED_X_2016-03-08-2300/lib/slc6_amd64_gcc493/pluginValidationRecoMuonPlugins.so
#10 0x00007f23d08fc311 in MuonTrackValidator::endRun(edm::Run const&, edm::EventSetup const&) () from /cvmfs/cms-ib.cern.ch/week1/slc6_amd64_gcc493/cms/cmssw/CMSSW_8_1_THREADED_X_2016-03-08-2300/lib/slc6_amd64_gcc493/pluginValidationRecoMuonPlugins.so
#11 0x00007f24127295eb in edm::stream::EDAnalyzerAdaptorBase::doStreamEndRun(edm::StreamID, edm::RunPrincipal const&, edm::EventSetup const&, edm::ModuleCallingContext const*) () from /cvmfs/cms-ib.cern.ch/week1/slc6_amd64_gcc493/cms/cmssw/CMSSW_8_1_THREADED_X_2016-03-08-2300/lib/slc6_amd64_gcc493/libFWCoreFramework.so
#12 0x00007f241271b21d in edm::WorkerT<edm::stream::EDAnalyzerAdaptorBase>::implDoStreamEnd(edm::StreamID, edm::RunPrincipal const&, edm::EventSetup const&, edm::ModuleCallingContext const*) () from /cvmfs/cms-ib.cern.ch/week1/slc6_amd64_gcc493/cms/cmssw/CMSSW_8_1_THREADED_X_2016-03-08-2300/lib/slc6_amd64_gcc493/libFWCoreFramework.so
#13 0x00007f241265d079 in decltype ({parm#1}()) edm::convertException::wrap<bool edm::Worker::doWork<edm::OccurrenceTraits<edm::RunPrincipal, (edm::BranchActionType)2> >(edm::OccurrenceTraits<edm::RunPrincipal, (edm::BranchActionType)2>::MyPrincipal const&, edm::EventSetup const&, edm::StreamID, edm::ParentContext const&, edm::OccurrenceTraits<edm::RunPrincipal, (edm::BranchActionType)2>::Context const*)::{lambda()#1}>(bool edm::Worker::doWork<edm::OccurrenceTraits<edm::RunPrincipal, (edm::BranchActionType)2> >(edm::OccurrenceTraits<edm::RunPrincipal, (edm::BranchActionType)2>::MyPrincipal const&, edm::EventSetup const&, edm::StreamID, edm::ParentContext const&, edm::OccurrenceTraits<edm::RunPrincipal, (edm::BranchActionType)2>::Context const*)::{lambda()#1}) () from /cvmfs/cms-ib.cern.ch/week1/slc6_amd64_gcc493/cms/cmssw/CMSSW_8_1_THREADED_X_2016-03-08-2300/lib/slc6_amd64_gcc493/libFWCoreFramework.so
#14 0x00007f241265d2c0 in bool edm::Worker::doWork<edm::OccurrenceTraits<edm::RunPrincipal, (edm::BranchActionType)2> >(edm::OccurrenceTraits<edm::RunPrincipal, (edm::BranchActionType)2>::MyPrincipal const&, edm::EventSetup const&, edm::StreamID, edm::ParentContext const&, edm::OccurrenceTraits<edm::RunPrincipal, (edm::BranchActionType)2>::Context const*) () from /cvmfs/cms-ib.cern.ch/week1/slc6_amd64_gcc493/cms/cmssw/CMSSW_8_1_THREADED_X_2016-03-08-2300/lib/slc6_amd64_gcc493/libFWCoreFramework.so
#15 0x00007f241265d4aa in decltype ({parm#1}()) edm::convertException::wrap<void edm::Path::processOneOccurrence<edm::OccurrenceTraits<edm::RunPrincipal, (edm::BranchActionType)2> >(edm::OccurrenceTraits<edm::RunPrincipal, (edm::BranchActionType)2>::MyPrincipal const&, edm::EventSetup const&, edm::StreamID const&, edm::OccurrenceTraits<edm::RunPrincipal, (edm::BranchActionType)2>::Context const*)::{lambda()#1}>(void edm::Path::processOneOccurrence<edm::OccurrenceTraits<edm::RunPrincipal, (edm::BranchActionType)2> >(edm::OccurrenceTraits<edm::RunPrincipal, (edm::BranchActionType)2>::MyPrincipal const&, edm::EventSetup const&, edm::StreamID const&, edm::OccurrenceTraits<edm::RunPrincipal, (edm::BranchActionType)2>::Context const*)::{lambda()#1}) () from /cvmfs/cms-ib.cern.ch/week1/slc6_amd64_gcc493/cms/cmssw/CMSSW_8_1_THREADED_X_2016-03-08-2300/lib/slc6_amd64_gcc493/libFWCoreFramework.so
#16 0x00007f241265d68a in void edm::Path::processOneOccurrence<edm::OccurrenceTraits<edm::RunPrincipal, (edm::BranchActionType)2> >(edm::OccurrenceTraits<edm::RunPrincipal, (edm::BranchActionType)2>::MyPrincipal const&, edm::EventSetup const&, edm::StreamID const&, edm::OccurrenceTraits<edm::RunPrincipal, (edm::BranchActionType)2>::Context const*) () from /cvmfs/cms-ib.cern.ch/week1/slc6_amd64_gcc493/cms/cmssw/CMSSW_8_1_THREADED_X_2016-03-08-2300/lib/slc6_amd64_gcc493/libFWCoreFramework.so
#17 0x00007f241265d9a4 in decltype ({parm#1}()) edm::convertException::wrap<void edm::StreamSchedule::processOneStream<edm::OccurrenceTraits<edm::RunPrincipal, (edm::BranchActionType)2> >(edm::OccurrenceTraits<edm::RunPrincipal, (edm::BranchActionType)2>::MyPrincipal&, edm::EventSetup const&, bool)::{lambda()#1}>(void edm::StreamSchedule::processOneStream<edm::OccurrenceTraits<edm::RunPrincipal, (edm::BranchActionType)2> >(edm::OccurrenceTraits<edm::RunPrincipal, (edm::BranchActionType)2>::MyPrincipal&, edm::EventSetup const&, bool)::{lambda()#1}) () from /cvmfs/cms-ib.cern.ch/week1/slc6_amd64_gcc493/cms/cmssw/CMSSW_8_1_THREADED_X_2016-03-08-2300/lib/slc6_amd64_gcc493/libFWCoreFramework.so
#18 0x00007f241265df49 in void edm::StreamSchedule::processOneStream<edm::OccurrenceTraits<edm::RunPrincipal, (edm::BranchActionType)2> >(edm::OccurrenceTraits<edm::RunPrincipal, (edm::BranchActionType)2>::MyPrincipal&, edm::EventSetup const&, bool) () from /cvmfs/cms-ib.cern.ch/week1/slc6_amd64_gcc493/cms/cmssw/CMSSW_8_1_THREADED_X_2016-03-08-2300/lib/slc6_amd64_gcc493/libFWCoreFramework.so
#19 0x00007f241264a97e in edm::EventProcessor::endRun(statemachine::Run const&, bool) () from /cvmfs/cms-ib.cern.ch/week1/slc6_amd64_gcc493/cms/cmssw/CMSSW_8_1_THREADED_X_2016-03-08-2300/lib/slc6_amd64_gcc493/libFWCoreFramework.so
#20 0x00007f241262dcbc in statemachine::HandleRuns::endRun(statemachine::Run const&, bool) () from /cvmfs/cms-ib.cern.ch/week1/slc6_amd64_gcc493/cms/cmssw/CMSSW_8_1_THREADED_X_2016-03-08-2300/lib/slc6_amd64_gcc493/libFWCoreFramework.so
#21 0x00007f241262dd6c in statemachine::HandleRuns::finalizeRun(bool) () from /cvmfs/cms-ib.cern.ch/week1/slc6_amd64_gcc493/cms/cmssw/CMSSW_8_1_THREADED_X_2016-03-08-2300/lib/slc6_amd64_gcc493/libFWCoreFramework.so
#22 0x00007f2412636c09 in boost::statechart::simple_state<statemachine::HandleRuns, statemachine::HandleFiles, statemachine::NewRun, (boost::statechart::history_mode)0>::exit_impl(boost::intrusive_ptr<statemachine::HandleRuns>&, boost::intrusive_ptr<boost::statechart::detail::node_state_base<std::allocator<void>, boost::statechart::detail::rtti_policy> >&, bool) () from /cvmfs/cms-ib.cern.ch/week1/slc6_amd64_gcc493/cms/cmssw/CMSSW_8_1_THREADED_X_2016-03-08-2300/lib/slc6_amd64_gcc493/libFWCoreFramework.so
#23 0x00007f2412636cda in boost::statechart::simple_state<statemachine::HandleLumis, statemachine::HandleRuns, statemachine::FirstLumi, (boost::statechart::history_mode)0>::exit_impl(boost::intrusive_ptr<statemachine::HandleLumis>&, boost::intrusive_ptr<boost::statechart::detail::node_state_base<std::allocator<void>, boost::statechart::detail::rtti_policy> >&, bool) () from /cvmfs/cms-ib.cern.ch/week1/slc6_amd64_gcc493/cms/cmssw/CMSSW_8_1_THREADED_X_2016-03-08-2300/lib/slc6_amd64_gcc493/libFWCoreFramework.so
#24 0x00007f2412637d6f in boost::statechart::simple_state<statemachine::HandleEvent, statemachine::HandleLumis, boost::mpl::list<mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na>, (boost::statechart::history_mode)0>::exit_impl(boost::intrusive_ptr<boost::statechart::detail::leaf_state<std::allocator<void>, boost::statechart::detail::rtti_policy> >&, boost::intrusive_ptr<boost::statechart::detail::node_state_base<std::allocator<void>, boost::statechart::detail::rtti_policy> >&, bool) () from /cvmfs/cms-ib.cern.ch/week1/slc6_amd64_gcc493/cms/cmssw/CMSSW_8_1_THREADED_X_2016-03-08-2300/lib/slc6_amd64_gcc493/libFWCoreFramework.so
#25 0x00007f2412632a4b in boost::statechart::detail::safe_reaction_result boost::statechart::simple_state<statemachine::HandleFiles, statemachine::Machine, statemachine::FirstFile, (boost::statechart::history_mode)0>::transit_impl<statemachine::EndingLoop, statemachine::Machine, boost::statechart::detail::no_transition_function>(boost::statechart::detail::no_transition_function const&) [clone .isra.535] () from /cvmfs/cms-ib.cern.ch/week1/slc6_amd64_gcc493/cms/cmssw/CMSSW_8_1_THREADED_X_2016-03-08-2300/lib/slc6_amd64_gcc493/libFWCoreFramework.so
#26 0x00007f2412632c5d in boost::statechart::detail::reaction_result boost::statechart::simple_state<statemachine::HandleFiles, statemachine::Machine, statemachine::FirstFile, (boost::statechart::history_mode)0>::local_react_impl_non_empty::local_react_impl<boost::mpl::list4<boost::statechart::transition<statemachine::Run, statemachine::Error, boost::statechart::detail::no_context<statemachine::Run>, &boost::statechart::detail::no_context<statemachine::Run>::no_function>, boost::statechart::transition<statemachine::File, statemachine::Error, boost::statechart::detail::no_context<statemachine::File>, &boost::statechart::detail::no_context<statemachine::File>::no_function>, boost::statechart::transition<statemachine::Stop, statemachine::EndingLoop, boost::statechart::detail::no_context<statemachine::Stop>, &boost::statechart::detail::no_context<statemachine::Stop>::no_function>, boost::statechart::transition<statemachine::Restart, statemachine::Error, boost::statechart::detail::no_context<statemachine::Restart>, &boost::statechart::detail::no_context<statemachine::Restart>::no_function> >, boost::statechart::simple_state<statemachine::HandleFiles, statemachine::Machine, statemachine::FirstFile, (boost::statechart::history_mode)0> >(boost::statechart::simple_state<statemachine::HandleFiles, statemachine::Machine, statemachine::FirstFile, (boost::statechart::history_mode)0>&, boost::statechart::event_base const&, void const*) [clone .isra.550] () from /cvmfs/cms-ib.cern.ch/week1/slc6_amd64_gcc493/cms/cmssw/CMSSW_8_1_THREADED_X_2016-03-08-2300/lib/slc6_amd64_gcc493/libFWCoreFramework.so
#27 0x00007f241263827a in boost::statechart::simple_state<statemachine::HandleRuns, statemachine::HandleFiles, statemachine::NewRun, (boost::statechart::history_mode)0>::react_impl(boost::statechart::event_base const&, void const*) () from /cvmfs/cms-ib.cern.ch/week1/slc6_amd64_gcc493/cms/cmssw/CMSSW_8_1_THREADED_X_2016-03-08-2300/lib/slc6_amd64_gcc493/libFWCoreFramework.so
#28 0x00007f241263675c in boost::statechart::simple_state<statemachine::HandleLumis, statemachine::HandleRuns, statemachine::FirstLumi, (boost::statechart::history_mode)0>::react_impl(boost::statechart::event_base const&, void const*) () from /cvmfs/cms-ib.cern.ch/week1/slc6_amd64_gcc493/cms/cmssw/CMSSW_8_1_THREADED_X_2016-03-08-2300/lib/slc6_amd64_gcc493/libFWCoreFramework.so
#29 0x00007f2412638a30 in boost::statechart::simple_state<statemachine::HandleEvent, statemachine::HandleLumis, boost::mpl::list<mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na>, (boost::statechart::history_mode)0>::react_impl(boost::statechart::event_base const&, void const*) () from /cvmfs/cms-ib.cern.ch/week1/slc6_amd64_gcc493/cms/cmssw/CMSSW_8_1_THREADED_X_2016-03-08-2300/lib/slc6_amd64_gcc493/libFWCoreFramework.so
#30 0x00007f241265708a in boost::statechart::state_machine<statemachine::Machine, statemachine::Starting, std::allocator<void>, boost::statechart::null_exception_translator>::process_event(boost::statechart::event_base const&) () from /cvmfs/cms-ib.cern.ch/week1/slc6_amd64_gcc493/cms/cmssw/CMSSW_8_1_THREADED_X_2016-03-08-2300/lib/slc6_amd64_gcc493/libFWCoreFramework.so
#31 0x00007f241264724b in edm::EventProcessor::runToCompletion() () from /cvmfs/cms-ib.cern.ch/week1/slc6_amd64_gcc493/cms/cmssw/CMSSW_8_1_THREADED_X_2016-03-08-2300/lib/slc6_amd64_gcc493/libFWCoreFramework.so
#32 0x000000000040cf41 in main::{lambda()#1}::operator()() const ()
#33 0x000000000040b486 in main ()

A fatal system signal has occurred: segmentation violation

**Comment by dan131riley** [comment]
This should be fixed by https://sft.its.cern.ch/jira/browse/ROOT-8217

**Comment by Dr15Jones** [comment]
assign core

**Comment by Dr15Jones** [comment]
+1
