### ISSUE TITLE
Put a wait when lots of messages are being sent

### ISSUE THREAD

**Issue by Dr15Jones** [cms-sw/cmssw#13760]
If the number of outstanding messages exceeds some limit, make the sending thread wait. This is needed to avoid memory explosions as seen https://hypernews.cern.ch/HyperNews/CMS/get/recoDevelopment/1430.html

**Comment by Dr15Jones** [comment]
assign core

**Comment by Dr15Jones** [comment]
@davidlange6 @slava77 There are several ways I could do this. If too many messages are coming simultaneously then when it hits a threshhold

1. I can have the sending threads wait which slows us down or

1. I can start throwing away messages until I can get all the pending messages out

I like the latter since it avoids stalling threads but it does mean losing messages.

Do you have suggestions?

**Comment by slava77** [comment]
Maybe a threshold for 1 and a (higher) threshold for 2?

When I looked at the events with mt4 I have seen that processing in one module on one of the streams would stop for ~x100 or worse longer than it takes to process an event in a single thread.
Sequentially with 1 thread each module completed event processing within 1.5-2.5 secs.

**Comment by davidlange6** [comment]
for context, what is “lots”?

**Comment by Dr15Jones** [comment]
I'd think 'lots' could be 100? I'd certainly think more than 10.

**Comment by Dr15Jones** [comment]
> Maybe a threshold for 1 and a (higher) threshold for 2?

Exceeding the threshold for 1 means the threads would pause and would therefore not add more items to output. This would mean we'd never reach a threshold for 2.

> When I looked at the events with mt4 I have seen that processing in one module on one of the streams would stop for ~x100 or worse longer than it takes to process an event in a single thread.
Sequentially with 1 thread each module completed event processing within 1.5-2.5 secs.

Right, the one module being slowed down is the one where the thread is trying to process all the print requests from all the other threads.

**Comment by Dr15Jones** [comment]
Actually, 10 messages would already be pretty excessive. The design was meant to be used in a cituation where messages are very infrequent so that even 1 message from another thread should be rare.

**Comment by Dr15Jones** [comment]
+1
The solution we used was to discard messages if the buffer exceeded a certain limit. This aptimizes for concurrency over messaging completeness.
