### ISSUE TITLE
Twisted imports in runMETCorrectionsAndUncertainties

### ISSUE THREAD

**Issue by riga** [cms-sw/cmssw#13761]
The RunMETCorrectionsAndUncertainties tool in PatUtils [1] uses wrong imports of the jetUpdaters in PatAlgos [2], e.g. `patJetCorrFactorsUpdated` instead of `updatedPatJetCorrFactors`.

This bug occurred in 7_6_4.

[1] https://github.com/cms-sw/cmssw/blob/CMSSW_7_6_X/PhysicsTools/PatUtils/python/tools/runMETCorrectionsAndUncertainties.py#L1195
[2] https://github.com/cms-sw/cmssw/blob/CMSSW_7_6_X/PhysicsTools/PatAlgos/python/producersLayer1/jetUpdater_cff.py

**Comment by riga** [comment]
Ok, this seems to be already fixed in 8_X_X. Will this fix be backported to 7_6_X?

**Comment by slava77** [comment]
@zdemirag @mariadalfonso  please take a note.
@riga it may be more effective to discuss this in hn-cms-physTools

**Comment by zdemirag** [comment]
@riga the plan is to back port the 80X to 76X.

**Comment by mmarionncern** [comment]
@riga @slava77 
This issue is fixed in the PR #13865 . 
A full backport of the updated version of the MET tool from 8XY is too complicated to set in place in 76X (and would break a lot of CMSSW rules such as changes in the production sequence content)

**Comment by smuzaffar** [comment]
closing as it is fixed by #13865
