### ISSUE TITLE
Consider forking boost serialization

### ISSUE THREAD

**Issue by Dr15Jones** [cms-sw/cmssw#13788]
The conditions use of boost serialization keeps us from being able to migrate to new versions of boost (becuase they require forward compatibility and boost only guarantees backwards compatibility). We should look into forking boost serialization and then moving the code to a new namespace. The conditions code would then only use the new namespace.

**Comment by Dr15Jones** [comment]
assign db

**Comment by Dr15Jones** [comment]
assign core

**Comment by davidlange6** [comment]
I agree - but can we confirm that keeping the serialization part static would be sufficient?

**Comment by Dr15Jones** [comment]
First thing would be to determine how much of boost is used by boost serialization. Then see if those other parts have to be forked or if we can just get them from the regular boost.

**Comment by davidlange6** [comment]
Right - @ggovi perhaps can report on this at a future core meeting?

**Comment by ggovi** [comment]
@Dr15Jones
It is not obvious that it will be feasible ( boost/serialization has a library, not only header files ):
- the change of namespace could be tricky, depending on how many nested files are involved
- the whole consistency is not ensured if we go for the static fork

It will probably require the validation of every boost version change... Do we really need to go for it? As far as I know, until now the few requests have been solved with the appropriate release management ( change in the readers first, then change in the writers ). 

To have a first glance of the usage, we reference the headers in this file:
CondFormats/​Serialization/​interface/​Serializable.h
while in this one we use the 'plugin' for portable archives:
CondFormats/​Serialization/​interface/​Archive.h

**Comment by davidlt** [comment]
There is one issue we are solving for GCC 6.0.0 in upstream Boost for 1.61.0 release. This will be trivial to back port to the current version of Boost, but who knows how complicated that will be in the future. We had discussions in the past (1 year ago?) that a permanent solution needs to be found for CondDB so that we are not locked to a specific version of Boost.

Boost is modular. Thus, I think, one can mix modules from different versions of Boost, but I don't advice this.

**Comment by ggovi** [comment]
@davidlt 
@all...
I'm currently implementing a protection in our conditon upload service, which should prevent the storage of payloads serialized with boost version > the one in use by the service. This should allow to have the latest greatest CMSSW with a boost version higher then the one in use by the 'production' readers ( presumably running an earlier CMSSW ).  
This will imply that the conditions will be produced with the same release the readers are using. Is this sufficient for establishing a workable release management, allowing boost updates?

**Comment by davidlange6** [comment]
lets not use @ all - it doesn’t do what you think..

how does one then transition to a new “production” release using the new boost version?

**Comment by ggovi** [comment]
the transition requires the back-port of the boost upgrade to the 'reader's CMSSW releases - tipically the earliest is the one in use by HLT.   So:

- latest greatest move to new boost
- after the required validation ( for HLT ), the change is ported ( unless HLT is moving )

This is actually the simpler scenario, we may need to consider if other 'readers' need to be supported...

**Comment by davidlange6** [comment]
> On Mar 22, 2016, at 12:44 PM, ggovi <notifications@github.com> wrote:
> 
> the transition requires the back-port of the boost upgrade to the 'reader's CMSSW releases - tipically the earliest is the one in use by HLT. So:
> 
> 	• latest greatest move to new boost
> 	• after the required validation ( for HLT ), the change is ported ( unless HLT is moving )
> This is actually the simpler scenario, we may need to consider if other 'readers' need to be supported…

I don’t think that solution works long term - unlike the 74x transition, when we had only a few, and not very old, releases to worry about, releases still used by physics using conddb2 will start to get very old in the coming years. [eg, no conddb2 release was used widely by run 1 analysis when we transitioned previously, so the transition was pretty simple]

**Comment by ggovi** [comment]
ok, I'm currently discussing a refined proposal with the AlCa conveners.
I guess we will have to iterate on this.

**Comment by smuzaffar** [comment]
For sure we are not going to fork boost serialization, do we need to keep this issue open?

**Comment by ggovi** [comment]
Shall we close this issue?

**Comment by smuzaffar** [comment]
yes we should.
