### ISSUE TITLE
ConfigBuilder: make --hltProcess to act on patTrigger settings

### ISSUE THREAD

**Issue by slava77** [cms-sw/cmssw#13806]
--hltProcess  XXX option doesn't modify patTrigger settings.
This can be applied in prepare_PAT step

**Comment by slava77** [comment]
assign operations reco

**Comment by slava77** [comment]
I guess I can't asign issues

**Comment by Dr15Jones** [comment]
assign reco, operations

**Comment by Dr15Jones** [comment]
assign reco

**Comment by Dr15Jones** [comment]
assign reconstruction

**Comment by smuzaffar** [comment]
fixed for 90X IBs
