### ISSUE TITLE
Properly handle tests in CommonTool/Utils

### ISSUE THREAD

**Issue by Dr15Jones** [cms-sw/cmssw#13936]
The unit test testCommonToolsUtil is actually disabled for standard testing. We need to understand why this was done and find a solution to run the tests that can be run and remove those that can't.

**Comment by Dr15Jones** [comment]
@smuzaffar You were the one who disabled the test but the git comment doesn't say way.

**Comment by Dr15Jones** [comment]
assign core

**Comment by smuzaffar** [comment]
@Dr15Jones , do not remember exactly why but there were few tests which were hanging in IBs (waiting for input) and I had disabled them. 

I tested locally now and it works, so  we can enable it to see how it goes in IB

**Comment by Dr15Jones** [comment]
After turning it back on, if the problem happens again then we should split the problematic test out to its own executable.

**Comment by smuzaffar** [comment]
It is re-enabled https://github.com/cms-sw/cmssw/pull/14000 and looks good in the IB https://cmssdt.cern.ch/SDT/cgi-bin/buildlogs/slc6_amd64_gcc530/CMSSW_8_1_X_2016-04-11-1100/unitTestLogs/CommonTools/Utils

**Comment by smuzaffar** [comment]
+1
