### ISSUE TITLE
Request for an external Package  SLHCUpgradeSimulations/Geometry

### ISSUE THREAD

**Issue by boudoul** [cms-sw/cmssw#14038]
As requested in the PR #13923 , could the two files from this PR namely : 
1) SLHCUpgradeSimulations/Geometry/data/PhaseII/Flat/PixelSkimmedGeometry.txt
https://github.com/boudoul/cmssw/blob/workflowsp2_81X_localreco/SLHCUpgradeSimulations/Geometry/data/PhaseII/Flat/PixelSkimmedGeometry.txt
2)   SLHCUpgradeSimulations/Geometry/data/PhaseII/Tilted/PixelSkimmedGeometry.txt
https://github.com/boudoul/cmssw/blob/workflowsp2_81X_localreco/SLHCUpgradeSimulations/Geometry/data/PhaseII/Tilted/PixelSkimmedGeometry.txt

be moved to external ?
Thanks a lot

**Comment by smuzaffar** [comment]
@degano , can you please take care of it?

**Comment by smuzaffar** [comment]
assign externals

**Comment by degano** [comment]
@boudoul @smuzaffar Done here: https://github.com/cms-sw/cmsdist/pull/2249.
