### ISSUE TITLE
watchlist for sdevissc

### ISSUE THREAD

**Issue by sdevissc** [cms-sw/cmssw#14045]
Hello, 

Could it be possible to be on the watchlist for all packages in SimTracker/* ?

Thanks

Simon (strip simu contact)

**Comment by smuzaffar** [comment]
assign core
@iahmad-khan , can you please take care of it

**Comment by iahmad-khan** [comment]
done here
https://github.com/cms-sw/cms-bot/pull/661

**Comment by smuzaffar** [comment]
+1
thanks @iahmad-khan
