### ISSUE TITLE
[FWCore] Feature request: Python script to generate C++ fillDescriptions code from config

### ISSUE THREAD

**Issue by kpedro88** [cms-sw/cmssw#14105]
In general, it's easier to write a Python config for a producer than to write the corresponding fillDescriptions C++ code. There are some not-quite-obvious rules for fillDescriptions (https://twiki.cern.ch/twiki/bin/view/CMSPublic/SWGuideConfigurationValidationAndHelp) that could be automatically followed by a Python script taking a Python config as input.

I recently encountered a use case for such a script in #13861, where I added half a dozen psets to the config for HcalHardcodeCalibrations. I ended up writing a very limited Python script to make just the lines that I needed. It would be nice to have a general-purpose tool with all the rules encoded. It would also make it easier for contributors to update the numerous producers without fillDescriptions that end up needing it when a config gets changed.

attn: @Dr15Jones

**Comment by Dr15Jones** [comment]
assign core

**Comment by kpedro88** [comment]
Apparently [edmPythonConfigToCppValidation](https://github.com/cms-sw/cmssw/blob/master/FWCore/ParameterSet/scripts/edmPythonConfigToCppValidation) exists and I never knew about.

So this can be closed, but #18425 should be addressed at some point.
