### ISSUE TITLE
Please add dmitrijus among those who can sign for DQM

### ISSUE THREAD

**Issue by deguio** [cms-sw/cmssw#14206]
thanks,
F.

@vanbesien @dmitrijus

**Comment by davidlt** [comment]
This, issue or pull request should be created against cms-bot repository.

@davidlange6 does this kind of request requires ACK from someone? Otherwise I can go ahead and make the change.

**Comment by davidlt** [comment]
assign core

**Comment by davidlange6** [comment]
yes it does - its good for me (which is to say, already discussed), so it can go ahead.

**Comment by davidlt** [comment]
Done: https://github.com/cms-sw/cms-bot/commit/4d9ade43301d9d0fd2c772132c0d042c374ecdb0

**Comment by deguio** [comment]
thanks!
F.
