### ISSUE TITLE
Make Event::triggerResultsByName work with consumes

### ISSUE THREAD

**Issue by Dr15Jones** [cms-sw/cmssw#14216]
The function `Event::triggerResultsByName` was never made compatible with `consumes`.

**Comment by Dr15Jones** [comment]
assign core

**Comment by Dr15Jones** [comment]
@wddgit here is the issue related to https://hypernews.cern.ch/HyperNews/CMS/get/swDevelopment/3330.html

**Comment by Dr15Jones** [comment]
@wddgit please add a comment to this issue which references your pull request

**Comment by wddgit** [comment]
Pull request #14262 implements the consumes migration for triggerResultsByName.

**Comment by Dr15Jones** [comment]
+1
