### ISSUE TITLE
[GCC 6] ROOT6 dictionaries are missing "new_" and "newArray_" wrappers for std::pair in dictionary

### ISSUE THREAD

**Issue by davidlt** [cms-sw/cmssw#14219]
This is a tracking ticket for https://sft.its.cern.ch/jira/browse/ROOT-8138

We have a number of failures in unit test and RelVals due to not properly generated dictionary  for anything `std::pair` related. This seems to happen due to recent GNU C++ Standard Library improvement based for C++11 and above standards.

Simply put, seems that ROOT cannot find a proper default constructor to use, thus not generating needed wrappers in the dictionary.

**Comment by Dr15Jones** [comment]
assign core

**Comment by davidlt** [comment]
Partially fixed, but still does not work with user defined classes in `std::pair`. This causes a unit test and a few workflows to fail.

**Comment by smuzaffar** [comment]
+1
this has been fixed
