### ISSUE TITLE
Notification request

### ISSUE THREAD

**Issue by cbernet** [cms-sw/cmssw#14235]
Hello, 

Could you please add me to the list of the persons to be notified of pull requests to 

    DataFormats/ParticleFlowReco/
    DataFormats/ParticleFlowCandidate/
    RecoParticleFlow/* 

Thanks, 

Colin

**Comment by slava77** [comment]
@cbernet 
you can also make a PR to cms-bot repo with changes in 
https://github.com/cms-sw/cms-bot/blob/master/watchers.yaml

**Comment by cbernet** [comment]
Thanks Slava, will do now, so closing this one. 
I would suggest to add this piece of information to the FAQ: 
http://cms-sw.github.io/faq.html#how-do-i-receive-notifications-about-pull-requests-for-a-given-package--subsystem

**Comment by smuzaffar** [comment]
@cbernet , I shall update the FAQ soon.
