### ISSUE TITLE
[externals] davix 0.4 outdated

### ISSUE THREAD

**Issue by radziej** [cms-sw/cmssw#14231]
In CMSSW_8_X the davix library has been added. However, it is not the latest version of davix 0.6, which you can see here: https://dmc.web.cern.ch/projects/davix/home
The installed, old 0.4 version results in a crash when calling the following command:

gfal-ls srm://grid-srm.physik.rwth-aachen.de:8443/srm/managerv2?SFN=/pnfs/physik.rwth-aachen.de/cms/store/user/radziej/PxlSkim/CMSSW_7_6_v1.0/ZToMuMu_M_120_200_13TeV_PH/ZToMuMu_NNPDF30_13TeV-powheg_M_120_200/76X_mcRun2_asymptotic_v12/160120_111540/0000/

Traceback (most recent call last):
  File "/usr/bin/gfal-ls", line 28, in <module>
    sys.exit(Gfal2Shell().main(sys.argv))
  File "/usr/lib/python2.6/site-packages/gfal2_util/shell.py", line 71, in main
    return inst.execute(command_func)
  File "/usr/lib/python2.6/site-packages/gfal2_util/base.py", line 141, in execute
    self.context = gfal2.creat_context()
gfal2.GError: Unable to open the /usr/lib64/gfal2-plugins//libgfal_plugin_http.so plugin specified in the plugin directory, failure : /usr/lib64/libdavix_copy.so.0: undefined symbol: _ZNK5Davix13RequestParams11getCopyModeEv

**Comment by davidlt** [comment]
I would like to re-iterate that we don't provide ABI/API 100% packages with what is provided within distribution. `gfal` is for data transfers between sites IIRC. Why is that executed within CMSSW environment?

**Comment by radziej** [comment]
Because it is part of submitting an analysis to the T2 computing grid. For example checking and creating the necessary directory structure.

**Comment by davidlt** [comment]
Is this CRAB3? IIRC, the official guide says that one should use a separate terminal without CMSSW environment (or at least that was the idea).

**Comment by radziej** [comment]
It is part of our local script. You do your IO instructions with `gfal` and then use `glite` to submit the jobs.
I suppose one could disentangle all these scripts and call them manually in the right order, but is there any argument for keeping the old `davix` version? It is more than 2 years old.

**Comment by davidlt** [comment]
@radziej depends how it's being used and who is the maintainer for the package. Still, we cannot replace it any release CMSSW version. We can only make such change in newer releases.

@iahmad-khan who requested for `davix` external in CMSSW?

I am still a bit puzzled here. According to the error message you provided it tried to load `/usr/lib64/gfal2-plugins//libgfal_plugin_http.so` (which we don't provide) and it tried to use `/usr/lib64/libdavix_copy.so.0` (which we don't provide). I see absolute paths being used here and none of them point to CMSSW. It looks like you are failing to use a local davix version. Could you verify (by debugging) this?

**Comment by smuzaffar** [comment]
@davidlt , it was requested by @bbockelm (https://github.com/cms-sw/cmssw/issues/12363#issuecomment-155547371 , https://github.com/cms-sw/cmssw/issues/12377)

**Comment by radziej** [comment]
Yes. It is trying to call a local library, which in turn should load the davix library. Most of this is local, but since sourcing CMSSW puts its libraries in the front of LD_LIBRARY_PATH (which it has to, obviously), /usr/lib64/libdavix.so.0.6.0 is replaced by the CMSSW version.

To test this theory, one can call the following, which works fine:

LD_PRELOAD=/usr/lib64/libdavix.so.0.6.0 gfal-ls srm://grid-srm.physik.rwth-aachen.de:8443/srm/managerv2?SFN=/pnfs/physik.rwth-aachen.de/cms/store/user/radziej/PxlSkim/CMSSW_7_6_v1.0/ZToMuMu_M_120_200_13TeV_PH/ZToMuMu_NNPDF30_13TeV-powheg_M_120_200/76X_mcRun2_asymptotic_v12/160120_111540/0000/

**Comment by davidlt** [comment]
@bbockelm what are your thoughts on bumping this external, e.g. in `CMSSW_8_1_X` and `CMSSW_8_0_X`?

**Comment by bbockelm** [comment]
Hi,

No problem from my side in a version bump (assuming the relevant ROOT IO plugin still builds fine).

FWIW - there's no expectation that grid commands work from within the CMSSW environment.  If they have worked historically, that's just a bit of luck.

Brian

**Comment by davidlt** [comment]
@bbockelm thanks

@iahmad-khan can you give it a try?

**Comment by davidlt** [comment]
assign core

**Comment by smuzaffar** [comment]
@bbockelm , I see that we have davix=OFF for root  ( https://github.com/cms-sw/cmsdist/blob/IB/CMSSW_8_1_X/gcc530/root.spec#L111 )

**Comment by iahmad-khan** [comment]
https://github.com/cms-sw/cmsdist/pull/2268

**Comment by bbockelm** [comment]
@smuzaffar - ah, probably about time to enable that.  I thought we already had :/

**Comment by smuzaffar** [comment]
@iahmad-khan , can you please update root spec to enable it

**Comment by iahmad-khan** [comment]
https://github.com/cms-sw/cmsdist/pull/2268/commits/3870a0e9a67645e510c1ed89b1b6c732b38e644a

**Comment by radziej** [comment]
Thanks for updating the library! Will there also be a pull request for 8_0_X?

**Comment by smuzaffar** [comment]
assign externals

**Comment by smuzaffar** [comment]
+externals
davix was up dated to 0.6.4 in 8.0.X
