### ISSUE TITLE
GeomDetLess should move out of Geometry/TrackerGeometryBuilder

### ISSUE THREAD

**Issue by Dr15Jones** [cms-sw/cmssw#14252]
The file DataFormats/TrackerRecHit2D/interface/TrackingRecHitLessFromGlobalPosition.h is dependent on GeomDetLess which causes an unwanted dependency on Geometry/TrackerGeometryBuilder with a DataFormats package. However, GeomDetLess does not depend on anything in Geometry/TrackerGeometryBuilder and instead only depends on items in DataFormats and Geometry/CommonDetUnit [which is an allowed DataFormats dependency].
Therefore GeomDetLess should be moved to a package which does not cause unnecessary dependencies.

**Comment by Dr15Jones** [comment]
assign reconstruction

**Comment by slava77** [comment]
+1

fixed in #14455 (merged May 14)
