### ISSUE TITLE
Missed formulas in CommonTools/Utils/src/FormulaEvaluator.cc

### ISSUE THREAD

**Issue by kodolova** [cms-sw/cmssw#14430]
Hello,
For jet energy corrections we need function TMath:Erf 
and Landau function.
Could you add?
               cheers,
                                      Olga

**Comment by Dr15Jones** [comment]
@kodolova Could you give us an example formula we can use for testing which involves the new functions?

**Comment by kodolova** [comment]
F.e. : F= 2*TMath::Erf(4*(x-1))  -> for Erf
         F=2*TMath::Landau(2*(x-1)) -> For Landau

**Comment by Dr15Jones** [comment]
#14494

**Comment by slava77** [comment]
@Dr15Jones @kodolova 
this still open old issue can be closed
