### ISSUE TITLE
Context in multiple exceptions in threaded IB

### ISSUE THREAD

**Issue by wddgit** [cms-sw/cmssw#14440]
Investigate and understand the following behavior. Possibly we could
improve this.

In the threaded IBs, sometimes there is an initial exception that comes out
with the expected context:

std::bad_alloc exception
----- Begin Fatal Exception 09-May-2016 19:33:16 CEST-----------------------
An exception of category 'BadAlloc' occurred while
   [0] Processing run: 1 lumi: 1 event: 2
   [1] Running path 'L1simulation_step'
   [2] Calling event method for module L1TGlobalProducer/'simGtStage2Digis'
Exception Message:
A std::bad_alloc exception was thrown.
The job has probably exhausted the virtual memory available to the process.
----- End Fatal Exception -------------------------------------------------

Then subsequent exception(s) print out with the context information (the
"occurred while" part) missing. We guess these are exceptions from other
threads.

%MSG-w ProductNotFound:  TriggerResultsFilter:hltBtagTriggerSelection  09-May-2016 19:33:38 CEST Run: 1 Event: 4
An exception of category 'ProductNotFound' occurred.
Exception Message:
Principal::getByToken: Found zero products matching all criteria
Looking for type: L1GlobalTriggerReadoutRecord
Looking for module label: gtDigis
Looking for productInstanceName: 

%MSG

First noticed in the following IB. (I expect this link will fail to work soon. I do not think
we save this IB information for a long time.)

https://cmssdt.cern.ch/SDT/cgi-bin/buildlogs/slc6_amd64_gcc530/CMSSW_8_1_THREADED_X_2016-05-09-1100/pyRelValMatrixLogs/run/250407.0_NuGun_UP15+FS_NuGun_UP15_PRMXUP15_PU25+HARVESTUP15FS+MINIAODMCUP15FS/step1_NuGun_UP15+FS_NuGun_UP15_PRMXUP15_PU25+HARVESTUP15FS+MINIAODMCUP15FS.log

**Comment by Dr15Jones** [comment]
assign core

**Comment by smuzaffar** [comment]
+1
closing it as we have not see this error in IBs for a long time now
