### ISSUE TITLE
urllib2 errors in 81X and 80X

### ISSUE THREAD

**Issue by kpedro88** [cms-sw/cmssw#14459]
I have been noticing errors like this from das_client in 81X and 80X:
```
  File "/cvmfs/cms.cern.ch/slc6_amd64_gcc530/cms/cmssw/CMSSW_8_1_0_pre4/external/slc6_amd64_gcc530/bin/das_client.py", line 448, in <module>
    main()
  File "/cvmfs/cms.cern.ch/slc6_amd64_gcc530/cms/cmssw/CMSSW_8_1_0_pre4/external/slc6_amd64_gcc530/bin/das_client.py", line 346, in main
    jsondict = get_data(host, query, idx, limit, debug, thr, ckey, cert)
  File "/cvmfs/cms.cern.ch/slc6_amd64_gcc530/cms/cmssw/CMSSW_8_1_0_pre4/external/slc6_amd64_gcc530/bin/das_client.py", line 253, in get_data
    fdesc = opener.open(req)
  File "/cvmfs/cms.cern.ch/slc6_amd64_gcc530/external/python/2.7.11-ikhhed/lib/python2.7/urllib2.py", line 431, in open
    response = self._open(req, data)
  File "/cvmfs/cms.cern.ch/slc6_amd64_gcc530/external/python/2.7.11-ikhhed/lib/python2.7/urllib2.py", line 449, in _open
    '_open', req)
  File "/cvmfs/cms.cern.ch/slc6_amd64_gcc530/external/python/2.7.11-ikhhed/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/cvmfs/cms.cern.ch/slc6_amd64_gcc530/external/python/2.7.11-ikhhed/lib/python2.7/urllib2.py", line 1240, in https_open
    context=self._context)
  File "/cvmfs/cms.cern.ch/slc6_amd64_gcc530/external/python/2.7.11-ikhhed/lib/python2.7/urllib2.py", line 1197, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:591)>
```

Specific releases tried include: 8_1_0_pre4, 8_0_7_patch2.

Any das_client command can produce the error, e.g.:
```
das_client.py --query="dataset=/*/RunIISpring16MiniAODv1*/MINIAODSIM"
```

The exact same command works fine in 7_4_15.

**Comment by davidlt** [comment]
You computer lacks CERN CA certificates, thus it cannot verify cmsweb.cern.ch certificate. Install `CERN-CA-certs` or/and run `fetch-crl`.

**Comment by kpedro88** [comment]
"My computer" in this case is cmslpc at Fermilab. Should I ask the cluster administrators to handle this centrally?

**Comment by davidlt** [comment]
Technically we should handle this via WLCG and make this package installed everywhere. @davidlange6 I guess, it comes installed by default if you run SLC/CC.

It doesn't hurt if you ask them to install it.

**Comment by kpedro88** [comment]
@davidlt Here is a list of CERN certificates installed on cmslpc:
```
ls -lt /etc/grid-security/certificates/ | grep CERN
lrwxrwxrwx 1 root root    20 Apr 12 19:26 16d09bf5.0 -> CERN-LCG-IOTA-CA.pem
lrwxrwxrwx 1 root root    31 Apr 12 19:26 16d09bf5.signing_policy -> CERN-LCG-IOTA-CA.signing_policy
lrwxrwxrwx 1 root root    15 Apr 12 19:26 4339b4bc.0 -> CERN-GridCA.pem
lrwxrwxrwx 1 root root    26 Apr 12 19:26 4339b4bc.signing_policy -> CERN-GridCA.signing_policy
lrwxrwxrwx 1 root root    15 Apr 12 19:26 5168735f.0 -> CERN-GridCA.pem
lrwxrwxrwx 1 root root    26 Apr 12 19:26 5168735f.signing_policy -> CERN-GridCA.signing_policy
lrwxrwxrwx 1 root root    15 Apr 12 19:26 b4278411.0 -> CERN-Root-2.pem
lrwxrwxrwx 1 root root    22 Apr 12 19:26 b4278411.namespaces -> CERN-Root-2.namespaces
lrwxrwxrwx 1 root root    26 Apr 12 19:26 b4278411.signing_policy -> CERN-Root-2.signing_policy
lrwxrwxrwx 1 root root    15 Apr 12 19:26 c2a48ab6.0 -> CERN-Root-2.pem
lrwxrwxrwx 1 root root    22 Apr 12 19:26 c2a48ab6.namespaces -> CERN-Root-2.namespaces
lrwxrwxrwx 1 root root    26 Apr 12 19:26 c2a48ab6.signing_policy -> CERN-Root-2.signing_policy
lrwxrwxrwx 1 root root    20 Apr 12 19:26 c7cad089.0 -> CERN-LCG-IOTA-CA.pem
lrwxrwxrwx 1 root root    31 Apr 12 19:26 c7cad089.signing_policy -> CERN-LCG-IOTA-CA.signing_policy
-rw-r--r-- 1 root root    83 Mar 31 15:12 CERN-Root-2.crl_url
-rw-r--r-- 1 root root   584 Mar 31 15:12 CERN-Root-2.info
-rw-r--r-- 1 root root   774 Mar 31 15:12 CERN-Root-2.namespaces
-rw-r--r-- 1 root root  2370 Mar 31 15:12 CERN-Root-2.pem
-rw-r--r-- 1 root root   362 Mar 31 15:12 CERN-Root-2.signing_policy
-rw-r--r-- 1 root root    79 Mar 31 15:12 CERN-GridCA.crl_url
-rw-r--r-- 1 root root   599 Mar 31 15:12 CERN-GridCA.info
-rw-r--r-- 1 root root  3341 Mar 31 15:12 CERN-GridCA.pem
-rw-r--r-- 1 root root   269 Mar 31 15:12 CERN-GridCA.signing_policy
-rw-r--r-- 1 root root    85 Mar 31 15:12 CERN-LCG-IOTA-CA.crl_url
-rw-r--r-- 1 root root   604 Mar 31 15:12 CERN-LCG-IOTA-CA.info
-rw-r--r-- 1 root root  3357 Mar 31 15:12 CERN-LCG-IOTA-CA.pem
-rw-r--r-- 1 root root   387 Mar 31 15:12 CERN-LCG-IOTA-CA.signing_policy
```

Are there more certificates we need to install? Or do we need some environment setting to point to them correctly?

**Comment by davidlt** [comment]
```
$ repoquery -l CERN-CA-certs
/etc/openldap/cacerts/157753a5.0
/etc/openldap/cacerts/1d879c6c.0
/etc/openldap/cacerts/2eb756e6.0
/etc/openldap/cacerts/3bae64c4.0
/etc/openldap/cacerts/3c58f906.0
/etc/openldap/cacerts/4339b4bc.0
/etc/openldap/cacerts/46117fcc.0
/etc/openldap/cacerts/5168735f.0
/etc/openldap/cacerts/7e0370f0.0
/etc/openldap/cacerts/995b6462.0
/etc/openldap/cacerts/AddTrustExternalCARoot.pem
/etc/openldap/cacerts/CERN-bundle.pem
/etc/openldap/cacerts/CERN_Certification_Authority.pem
/etc/openldap/cacerts/CERN_Grid_Certification_Authority.pem
/etc/openldap/cacerts/CERN_Root_CA.pem
/etc/openldap/cacerts/CERN_Root_Certification_Authority_2.pem
/etc/openldap/cacerts/CERN_Trusted_Certification_Authority.pem
/etc/openldap/cacerts/VeriSignClass3SecureServerCA-G3.pem
/etc/openldap/cacerts/b2a87ac7.0
/etc/openldap/cacerts/b4278411.0
/etc/openldap/cacerts/c2a48ab6.0
/etc/openldap/cacerts/d254cc30.0
/etc/pki/tls/certs/157753a5.0
/etc/pki/tls/certs/1d879c6c.0
/etc/pki/tls/certs/1d879c6c.signing_policy
/etc/pki/tls/certs/2eb756e6.0
/etc/pki/tls/certs/2eb756e6.signing_policy
/etc/pki/tls/certs/3bae64c4.0
/etc/pki/tls/certs/3bae64c4.signing_policy
/etc/pki/tls/certs/3c58f906.0
/etc/pki/tls/certs/4339b4bc.0
/etc/pki/tls/certs/4339b4bc.signing_policy
/etc/pki/tls/certs/46117fcc.0
/etc/pki/tls/certs/5168735f.0
/etc/pki/tls/certs/5168735f.signing_policy
/etc/pki/tls/certs/7e0370f0.0
/etc/pki/tls/certs/995b6462.0
/etc/pki/tls/certs/995b6462.signing_policy
/etc/pki/tls/certs/AddTrustExternalCARoot.crt
/etc/pki/tls/certs/AddTrustExternalCARoot.pem
/etc/pki/tls/certs/CERN-bundle.crt
/etc/pki/tls/certs/CERN-bundle.pem
/etc/pki/tls/certs/CERN_Certification_Authority.crt
/etc/pki/tls/certs/CERN_Certification_Authority.pem
/etc/pki/tls/certs/CERN_Certification_Authority.signing_policy
/etc/pki/tls/certs/CERN_Grid_Certification_Authority.crt
/etc/pki/tls/certs/CERN_Grid_Certification_Authority.pem
/etc/pki/tls/certs/CERN_Grid_Certification_Authority.signing_policy
/etc/pki/tls/certs/CERN_Root_CA.crt
/etc/pki/tls/certs/CERN_Root_CA.pem
/etc/pki/tls/certs/CERN_Root_CA.signing_policy
/etc/pki/tls/certs/CERN_Root_Certification_Authority_2.crt
/etc/pki/tls/certs/CERN_Root_Certification_Authority_2.pem
/etc/pki/tls/certs/CERN_Root_Certification_Authority_2.signing_policy
/etc/pki/tls/certs/CERN_Trusted_Certification_Authority.crt
/etc/pki/tls/certs/CERN_Trusted_Certification_Authority.pem
/etc/pki/tls/certs/CERN_Trusted_Certification_Authority.signing_policy
/etc/pki/tls/certs/VeriSignClass3SecureServerCA-G3.crt
/etc/pki/tls/certs/VeriSignClass3SecureServerCA-G3.pem
/etc/pki/tls/certs/b2a87ac7.0
/etc/pki/tls/certs/b2a87ac7.signing_policy
/etc/pki/tls/certs/b4278411.0
/etc/pki/tls/certs/b4278411.signing_policy
/etc/pki/tls/certs/c2a48ab6.0
/etc/pki/tls/certs/c2a48ab6.signing_policy
/etc/pki/tls/certs/d254cc30.0
/etc/pki/tls/certs/d254cc30.signing_policy
/usr/sbin/cern-import-certs-java
/usr/share/pki/ca-trust-source/anchors/CERN-bundle.crt
/usr/share/pki/ca-trust-source/anchors/CERN_Certification_Authority.crt
/usr/share/pki/ca-trust-source/anchors/CERN_Grid_Certification_Authority.crt
/usr/share/pki/ca-trust-source/anchors/CERN_Root_CA.crt
/usr/share/pki/ca-trust-source/anchors/CERN_Root_Certification_Authority_2.crt
/usr/share/pki/ca-trust-source/anchors/CERN_Trusted_Certification_Authority.crt
```

OpenSSL will look for certificates in `/etc/pki/tls/certs/`.

**Comment by holzman** [comment]
From a glance, this looks like an issue with urllib2 relying on the default SSL context and only looking in /etc/pki/tls/certs for certificates rather than /etc/grid-security-certificates.

**Comment by davidlt** [comment]
You could try using SSL_CERT_DIR environment variable, e.g.

export SSL_CERT_DIR='/etc/pki/tls/certs:/etc/grid-security/certificates'

or just

export SSL_CERT_DIR='/etc/grid-security/certificates'

for testing, but it would break everything else.

david

**Comment by belforte** [comment]
but why anything like this should be dependent on CMSSW version ?
is das_cly too much fragile ?

**Comment by holzman** [comment]
AFAICT, it's not strictly CMSSW but the version of urllib2 that CMS ships along with CMSSW. Only in more recent versions is the server certificate verified. (So this issue has been hiding for a long time in plain sight...)

**Comment by belforte** [comment]
DAS access is currenlty done w/o authentication, could it find a switch to disable server verification as well and sort this thing at the time the access protocol is changed ?
It is not good that we put something in CMSSW which may or may not work depending on some non mandatory setup of the site.
(I got interested becasue effectively we now rely on CMSSW for CRAB client as well, and that needs a secure connection to CMSWEB).

**Comment by davidlt** [comment]
What changed is the Python. Now (finally) host verification was enabled, which is a big win for security. Now it verifies that cmsweb.cern.ch is a trusted host and not a hacked location on the web. This fully relies on OpenSSL, which we ship with CMSSW (but should remove in my opinion). It by default look in default location, i.e. `/etc/pki/tls/certs`. Now all SLC distributions come with CERN-CA-certs installed. I don't even know if `/etc/grid-security/certificates` location contains required certificates (I think, the purpose of this package is different). I can speculate, that system OpenSSL does not know about `/etc/grid-security/certificates` either. Now one should be able to test that with SSL_CERT_DIR environment variable.

Alternatively, months ago, I did have a patch for DAS client to disable host verification to preserve old behaviour, but we agreed with Valentin that it's a wrong approach. PR: https://github.com/dmwm/DAS/pull/4243

I think, the following questions could be added:
- Does `/etc/grid-security/certificates` contain the right certificates? (needs checking)
- If yes, does grid software suppose to use it, i.e. DAS should look at certificates in `/etc/grid-security/certificates`?

@vkuznet,
What's your opinion?

**Comment by vkuznet** [comment]
David,
you posses question in a wrong way. Our tools does not directly use
certificates, but our dependencies or python libraries, e.g. urllib2, etc. do.

Therefore it is not a question about DAS/DBS/whatever and rather a question
of correct python library behavior. Since we need to use OpenSSL for our
purpose we compile python with its support.

According to this PEP: http://legacy.python.org/dev/peps/pep-0476/
"...
This PEP proposes to enable verification of X509 certificate signatures, as
well as hostname verification for Python's HTTP clients by default, subject to
opt-out on a per-call basis. This change would be applied to Python 2.7, Python
3.4, and Python 3.5.
..."

and current urllib2 library (from 2.7.11)
https://docs.python.org/2/library/urllib2.html
invokes HTTPS connection from
https://docs.python.org/2/library/httplib.html#httplib.HTTPSConnection
which
"...
This class now performs all the necessary certificate and hostname checks by
default. To revert to the previous, unverified, behavior
ssl._create_unverified_context() can be passed to the context parameter."

Therefore certificate verification has been changed to be enabled by default in
python 2.7 and 3.x

Do we like it or not is a different story, but I think it is good to stick with
a standard and security measures.

I don't really know which location urllib2 module uses to read certificates.
But, I agree with David proposal that we should test where urllib2 (not DAS)
reads certificates:
/etc/grid-security/certificates
/etc/pki/tls/certs
and/or SSL_CERT_DIR env.

Once identified we should check that WLCG nodes have it in place otherwise
we need to add SSL_CERT_DIR to our environment.

BTW, DBS APIs require verification by default, see
https://github.com/dmwm/DBS/blob/master/Client/src/python/dbs/apis/dbsClient.py#L140

So, we'll have many places where it "should be fixed" and fix should be done
at a node level rather tweaking/hacking our software stack.

Valentin.

**Comment by davidlt** [comment]
I don't know what uses `/etc/grid-security/certificates` and what content it holds until someone points me to function requirements documents of WN and grid software interface (which probably doesn't exist). A quick look at system OpenSSL configuration (lxplus) and it doesn't know anything about `/etc/grid-security/certificates` either.

I am only saying that DAS should configure SSL context to include `/etc/grid-security/certificates` only if the document exist which tells that software which runs in the grid is suppose to load certificates from `/etc/grid-security/certificates`. In that case it does have to follow this requirement.

The first thing is to check if `/etc/grid-security/certificates` ships the required certificate (maybe it doesn't, who knows).

Here is a quick test with a Docker and plain CentOS 7.2 (CMSSW prerequisites installed + lcg-CA package).
```
sudo docker run -it -v /cvmfs:/cvmfs --rm --name test_cert centos:7 bash

[root@08d6e9c75c2c CMSSW_8_0_8_patch1]# das_client --query="dataset=/*/RunIISpring16MiniAODv1*/MINIAODSIM"
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/slc7_amd64_gcc530/cms/das_client/v02.05.00/bin/das_client.py", line 448, in <module>
    main()
  File "/cvmfs/cms.cern.ch/slc7_amd64_gcc530/cms/das_client/v02.05.00/bin/das_client.py", line 346, in main
    jsondict = get_data(host, query, idx, limit, debug, thr, ckey, cert)
  File "/cvmfs/cms.cern.ch/slc7_amd64_gcc530/cms/das_client/v02.05.00/bin/das_client.py", line 253, in get_data
    fdesc = opener.open(req)
  File "/cvmfs/cms.cern.ch/slc7_amd64_gcc530/external/python/2.7.11/lib/python2.7/urllib2.py", line 431, in open
    response = self._open(req, data)
  File "/cvmfs/cms.cern.ch/slc7_amd64_gcc530/external/python/2.7.11/lib/python2.7/urllib2.py", line 449, in _open
    '_open', req)
  File "/cvmfs/cms.cern.ch/slc7_amd64_gcc530/external/python/2.7.11/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/cvmfs/cms.cern.ch/slc7_amd64_gcc530/external/python/2.7.11/lib/python2.7/urllib2.py", line 1240, in https_open
    context=self._context)
  File "/cvmfs/cms.cern.ch/slc7_amd64_gcc530/external/python/2.7.11/lib/python2.7/urllib2.py", line 1197, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:591)>
[root@08d6e9c75c2c CMSSW_8_0_8_patch1]# export SSL_CERT_DIR='/etc/pki/tls/certs:/etc/grid-security/certificates'
[root@08d6e9c75c2c CMSSW_8_0_8_patch1]# das_client --query="dataset=/*/RunIISpring16MiniAODv1*/MINIAODSIM"

Showing 1-10 out of 2343 results, for more results use --idx/--limit options

/ADDGravToGG_MS-4000_NED-2_KK-4_M-500To1000_13TeV-sherpa/RunIISpring16MiniAODv1-PUSpring16RAWAODSIM_80X_mcRun2_asymptotic_2016_v3-v1/MINIAODSIM
/ADDGravToGG_MS-4000_NED-4_KK-1_M-1000To2000_13TeV-sherpa/RunIISpring16MiniAODv1-PUSpring16RAWAODSIM_80X_mcRun2_asymptotic_2016_v3-v1/MINIAODSIM
/ADDGravToGG_MS-4000_NED-4_KK-1_M-2000To4000_13TeV-sherpa/RunIISpring16MiniAODv1-PUSpring16RAWAODSIM_80X_mcRun2_asymptotic_2016_v3-v1/MINIAODSIM
/ADDGravToGG_MS-4000_NED-4_KK-1_M-200To500_13TeV-sherpa/RunIISpring16MiniAODv1-PUSpring16RAWAODSIM_80X_mcRun2_asymptotic_2016_v3-v1/MINIAODSIM
/ADDGravToGG_MS-4000_NED-4_KK-1_M-500To1000_13TeV-sherpa/RunIISpring16MiniAODv1-PUSpring16RAWAODSIM_80X_mcRun2_asymptotic_2016_v3-v1/MINIAODSIM
/ADDGravToGG_MS-4500_NED-2_KK-1_M-1000To2000_13TeV-sherpa/RunIISpring16MiniAODv1-PUSpring16RAWAODSIM_80X_mcRun2_asymptotic_2016_v3-v1/MINIAODSIM
/ADDGravToGG_MS-4500_NED-2_KK-1_M-2000To3000_13TeV-sherpa/RunIISpring16MiniAODv1-PUSpring16RAWAODSIM_80X_mcRun2_asymptotic_2016_v3-v1/MINIAODSIM
/ADDGravToGG_MS-4500_NED-2_KK-1_M-3000To4500_13TeV-sherpa/RunIISpring16MiniAODv1-PUSpring16RAWAODSIM_80X_mcRun2_asymptotic_2016_v3-v1/MINIAODSIM
/ADDGravToGG_MS-4500_NED-2_KK-1_M-500To1000_13TeV-sherpa/RunIISpring16MiniAODv1-PUSpring16RAWAODSIM_80X_mcRun2_asymptotic_2016_v3-v1/MINIAODSIM
/ADDGravToGG_MS-4500_NED-2_KK-4_M-1000To2000_13TeV-sherpa/RunIISpring16MiniAODv1-PUSpring16RAWAODSIM_80X_mcRun2_asymptotic_2016_v3-v1/MINIAODSIM
[root@08d6e9c75c2c CMSSW_8_0_8_patch1]#
```
So, we do have a good certificate in `/etc/grid-security/certificates`.

I had CERN CentOS VM in which I removed CERN-CA-certs package and it doesn't have lcg-CA installed and to surprise it still worked. Maybe CERN certificates were still left in CA bundle itself. Didn't not investigate.

**Comment by belforte** [comment]
may I summarise like this ?
/etc/grid-security/certificates --> for GSSI (aka globus)
/etc/pki... --> for OpenSSL (aka plain https, nothing to do with globus and grid)
FNAL has a misconfiguration
The need for the CERN CA to be listed in /etc/pki/... has never been made clear. 

default linux distributions likely comes ready to trust Verisign & C. but not CERN. And this is a very general issue which clearly many people worry about (e.g. I see some CERN https servers are now signed via COMODO) but is way over what I can talk about.

**Comment by vkuznet** [comment]
David,
it is a general issue, not specific to DAS per-se. That's why I don't see it in
DAS context. Yes, DAS one of the first tools to show it up to end-users, but it
has nothing to with DAS.

I rather prefer that cmsenv or similar will setup generic environment variable
for *ALL* python based tools which potentially will subject of this issue.

Valentin.

**Comment by davidlt** [comment]
That's a good summary and explains some things.

The `HEP_OSlibs` packages does not require `CERN-CA-certs` package to be installed. Thankfully it's is actually provided by the same repository. You can clearly see it from http://linuxsoft.cern.ch/cern/centos/7/cern/x86_64/Packages/

Thus we should seek to get a dependency established here. In CERN distributions looks like `CERN-CA-certs` comes by default.

If one would want to use `SSL_CERT_DIR` now (because it's quicker) then it should be done in job submission software piece, which already sets a number of things in environment before launching CMSSW. The true solution is getting the dependency in `HEP_OSlibs`.

**Comment by davidlt** [comment]
I just read https://twiki.cern.ch/twiki/bin/view/LCG/CentOS7DependencyRPM and adding CERN-CA-certs as a dependency does not seem to be the option.

**Comment by kpedro88** [comment]
@davidlt is there any progress on resolving this problem?

**Comment by davidlt** [comment]
Nothing from my side. Fastest option is to ask for `CERN-CA-certs` package to be installed (for admins it's just a few lines in their puppet/ansible/chef/etc configuration) or set `SSL_CERT_DIR` environment variable e.g. in CRAB3. CRAB3 allows writing your own bash script to launch `cmsRun`.

**Comment by vkuznet** [comment]
Hi,
on my side I adjusted das client to read from SSL context and provide ability
to specify capath. The code is in github, and I asked Shahzad to provide me
instruction how to update CMSSW area, but so far didn't heard from him.
Valentin.

**Comment by belforte** [comment]
@davidlt I do not thing it is CRAB3 duty to make local sites trust CERN CA's for SSL usage. If SSL_CERT_DIR env. var. needs to be defined, it is for the site to do, or to put CERN CA's in /etc/pki/....
By the way, I look forward for CRAB3 client setup to be part of scram, like it is currently for das_cli.

**Comment by davidlt** [comment]
@belforte I wasn't suggesting that it's "CRAB3 duty". I am only suggesting a possible workaround (from user level), which means you don't need to wait until the actual resolution.

@smuzaffar could we deploy a new DAS into CMS common area on CVMFS and AFS?

**Comment by belforte** [comment]
@davidlt do you mean (FNAL) user can do this to solve ?
export SSL_CERT_DIR=/etc/grid-security/certificates
iif so we can write a FAQ (but maybe @kpedro88 can get it put in FNAL's login ?)

@vkuznet will new DAS version free (FNAL) users from the need to do that ?

**Comment by basilschneider** [comment]
I've been using
`export SSL_CERT_DIR=/etc/grid-security/certificates`
for a while now on the FNAL servers and didn't have any issues any more since then.

**Comment by vkuznet** [comment]
Stefano,
the CAPATH is node/OS dependent and we can't be 100% free. But I added
as one of the T3 users suggested the ability to pass capath to das client
and make it default to X509_CERT_DIR. We tested setup on T3 and everything was
working fine.
Valentin.

**Comment by belforte** [comment]
Maybe whatever whoever sets x509_cert_dir could set SSL one and save you the hassle? 
Sent from Stefano's mobile 
On Jun 24, 2016 13:52, Valentin Kuznetsov <notifications@github.com> wrote:Stefano,
the CAPATH is node/OS dependent and we can't be 100% free. But I added
as one of the T3 users suggested the ability to pass capath to das client
and make it default to X509_CERT_DIR. We tested setup on T3 and everything was
working fine.
Valentin.

**Comment by kpedro88** [comment]
At first I was wary of resetting SSL_CERT_DIR because of @davidlt's comment "but it would break everything else." But now I'm using `setenv SSL_CERT_DIR '/etc/pki/tls/certs:/etc/grid-security/certificates'` and things seem to be fine.

@belforte, I sadly have no power over cmslpc global environment settings, or this would have been resolved a long time ago.

**Comment by belforte** [comment]
who has it ? Lisa ? Burt ? Dave M. ? Does any of them read this ?

> @belforte <https://github.com/belforte>, I sadly have no power over cmslpc global environment
> settings, or this would have been resolved a long time ago.

**Comment by holzman** [comment]
FWIW, I forwarded this to Dave Mason.

- B

**Comment by vkuznet** [comment]
A new DAS client is available on cvmfs: /cvmfs/cms.cern.ch/common/das_client
it points to new version /cvmfs/cms.cern.ch/slc7_amd64_gcc530/cms/das_client/v03.01.00/bin/das_client.py
which implements proper SSLContext as well as points to /etc/grid-security/certificates CA's by default. Therefore I'd suggest we close the ticket.
