### ISSUE TITLE
An exception of category 'BadAlloc'  CMSSW_8_1_THREADED_X_2016-05-18-2300

### ISSUE THREAD

**Issue by bouril** [cms-sw/cmssw#14573]
Integration Build CMSSW_8_1_THREADED_X_2016-05-18-2300

An exception of category 'BadAlloc' (only for threaded)

10621.0 TenMuE_0_200  and 4 more similar

https://cmssdt.cern.ch/SDT/cgi-bin/buildlogs/slc6_amd64_gcc530/CMSSW_8_1_THREADED_X_2016-05-18-2300/pyRelValMatrixLogs/run/10621.0_TenMuE_0_200+TenMuE_0_200_pythia8_2023tilted_GenSimFull+DigiFull_2023tilted+RecoFullLocal_2023tilted/step2_TenMuE_0_200+TenMuE_0_200_pythia8_2023tilted_GenSimFull+DigiFull_2023tilted+RecoFullLocal_2023tilted.log

----- Begin Fatal Exception 19-May-2016 04:43:51 CEST-----------------------
An exception of category 'BadAlloc' occurred while
   [0] Processing run: 1 lumi: 1 event: 4
   [1] Running path 'digitisation_step'
   [2] Calling event method for module MixingModule/'mix'
Exception Message:
A std::bad_alloc exception was thrown.
The job has probably exhausted the virtual memory available to the process.
----- End Fatal Exception -------------------------------------------------
cmsRun: /build/cmsbuild/jenkins-workarea/workspace/build-any-ib/w/tmp/BUILDROOT/6a3f1a49141bbe9416d3d7632281cf95/opt/cmssw/slc6_amd64_gcc530/cms/cmssw/CMSSW_8_1_THREADED_X_2016-05-18-2300/src/SimCalorimetry/CaloSimAlgos/interface/CaloTDigitizer.h:99: void CaloTDigitizer<Traits, runHelper>::run(CaloTDigitizer<Traits, runHelper>::DigiCollection&, CLHEP::HepRandomEngine*) [with Traits = HcalUpgradeDigitizerTraits; runHelper = CaloTDigitizerQIE8Run; CaloTDigitizer<Traits, runHelper>::DigiCollection = edm::SortedCollection<HcalUpgradeDataFrame>]: Assertion `theDetIds->size() != 0' failed.

**Comment by Dr15Jones** [comment]
10621.0 is failing in the standard non-threaded CMSSW_8_1_X_2016-05-18-2300 build as well with the exception
```
%MSG-e HGCDigitizer:  MixingModule:mix 19-May-2016 03:35:04 CEST Run: 1 Event: 1
 @ accumulate : can't find HGCHitsHEback collection of g4SimHits
%MSG
----- Begin Fatal Exception 19-May-2016 03:35:48 CEST-----------------------
An exception of category 'StdException' occurred while
   [0] Processing run: 1 lumi: 1 event: 1
   [1] Running path 'digitisation_step'
   [2] Calling event method for module MixingModule/'mix'
Exception Message:
A std::exception was thrown.
vector::reserve
----- End Fatal Exception -------------------------------------------------
```
Which I would interpret as a memory related error.

**Comment by slava77** [comment]
Try to see if #14572 helps

**Comment by smuzaffar** [comment]
this has been fixed.
