### ISSUE TITLE
Remove oracle-env package from CMSSW

### ISSUE THREAD

**Issue by davidlt** [cms-sw/cmssw#14577]
Antanas reported that `tnsnames.ora` bundled within CMSSW is causing issues due to being out-of-date for years (server hostnames changed). People have to use the official packages, i.e. `oracle-instantclient-tnsnames.ora` provided by CERN. This is harming our users who need to use Oracle from CMSSW environment.

This is not the first time I complained about this. CERN Security already pinged us for removing it from CMSSW. This was discussed back in 2015 October.

**Comment by smuzaffar** [comment]
this has been fix https://github.com/cms-sw/cmsdist/commit/d2d2b9515eafa808692fd07a53fe58217a3aa332#diff-a07de4debbc762bb825a8ab8af65e285
