### ISSUE TITLE
backspace does not work in python terminal (80X, 81X)

### ISSUE THREAD

**Issue by kpedro88** [cms-sw/cmssw#14575]
In recent versions of CMSSW, the result of pressing backspace does not show up correctly in python terminals. The build(s) of python in 80X and 81X might have some improper key binding or could be missing readline support. I've noticed the same behavior in gdb, probably with the same underlying cause.

@smuzaffar, could you check on this?

**Comment by smuzaffar** [comment]
assign external
@kpedro88 , I noticed that on lxplus6 backspace works correctly but on lxplus7 it behaves strangely.
We will look in to it.

**Comment by davidlt** [comment]
Should be solved on GCC 6.1.1 branch with removal of nurses and readline from CMSSW.

**Comment by kpedro88** [comment]
@davidlt is there any possibility to solve it in the GCC 5.3.0 versions of CMSSW?

@smuzaffar on cmslpc-sl6, it works for CMSSW_7, but not in CMSSW_8.

**Comment by davidlt** [comment]
@kpedro88 yes, but that would require a massive recompilation. Which should be fine for 8_1_X.

**Comment by davidlt** [comment]
What I did for GCC 6.1.1 branch is to remove what is completely not needed because every machine (Fedora/SLC/RHEL/CentOS) are bound to have those packages.
https://github.com/cms-sw/cmsdist/commit/a044823259f2ee570d7ed1057741982b849c3d66#diff-be7420f998fbf70e2ad93c00c0df0861
https://github.com/cms-sw/cmsdist/commit/6d720929fb0998329ffb15c280dbbb4e62779db4#diff-3557a42f80fd8c508f2c10858fc87c9c
Because we never guarantee ABI/API compatibility these are creating a painful issues. Most of them are actually just to build RPM.

You can even remove more, e.g. there is no point in having our of OpenSSL which is always with security holes.

**Comment by kpedro88** [comment]
@davidlt a fix in 81X would be great. A fix in 80X would also be great, since many people will be using it for 2016 analysis for a long time, but I understand if it's not feasible at this point in the branch's lifetime...

**Comment by kpedro88** [comment]
@davidlt is this ever going to be fixed? It has not gotten less irritating over time.

**Comment by davidlt** [comment]
@kpedro88 it should be fixed in slc6_amd64_gcc600, can you verify that?

**Comment by kpedro88** [comment]
@davidlt yes, I see that it works now in the latest IB with slc6_amd64_gcc600. Is it possible to fix the production architecture version as well?

**Comment by davidlt** [comment]
@kpedro88 don't have the answer right now. @smuzaffar could you put `5.7-4.20090207` version into DEVEL branch to check if that would resolve the issue?

**Comment by iahmad-khan** [comment]
@davidlt shahzad is away untill Friday. 
Which spec file you are referring to be changed?  [5.7-4.20090207]

**Comment by davidlt** [comment]
@iahmad-khan `ncurses`, but not `ncurses-bootstrap` (leave it as-is).

**Comment by iahmad-khan** [comment]
@davidlt there is a version number 5.7 there , 5.7-4.20090207 is not there, should i use 5.7?

**Comment by davidlt** [comment]
There is, look at "patch date releases".
They used to be here: ftp://invisible-island.net/ncurses/current
But 5 version is probably under a different directory now.

**Comment by kpedro88** [comment]
@davidlt @iahmad-khan it would be good to fix this before 8_1_0 comes out...

**Comment by iahmad-khan** [comment]
@davidlt i couldn't find the version  5.7-4.20090207  from the given source.

**Comment by davidlt** [comment]
@iahmad-khan use SRPM. E.g., `yumdownloader --source <package>` to fetch SRPM, then standard `rpmbuild` to extract sources.

**Comment by davidlt** [comment]
or `rpm2archive` to convert SRPM to a tarball and unpack it to get sources.

**Comment by iahmad-khan** [comment]
Yes , after doing that , i see that it is actually version 5.7 with some patches , but it has some build-requires as well , gpm-devel,  pkgconfig which are not in cmsdist.

**Comment by kpedro88** [comment]
@davidlt @iahmad-khan any further progress on fixing this?

**Comment by kpedro88** [comment]
@davidlt @iahmad-khan ping

**Comment by mverzett** [comment]
For the record, it seems that the backspace error propagates to other command line utilities like sqlite3. It might be worth checking those too.

**Comment by kpedro88** [comment]
@davidlt @iahmad-khan only one prerelease left to fix this for 81X...

**Comment by smuzaffar** [comment]
@kpedro88 , Ijaz is on vacation and will come back mid of next week. 
@degano , can you please check what @davidlt did for gcc600 branch and get it in for gcc530?

**Comment by smuzaffar** [comment]
this is fixed for latest IBs. @kpedro88 can you please confirm if it works on cmslpc-slc6 machines?

**Comment by kpedro88** [comment]
@smuzaffar backspacing in python terminal (and gdb terminal) now works in `CMSSW_8_1_X_2016-10-03-1100` on cmslpc-sl6.

Is there any hope of getting this fix backported to 80X?

**Comment by smuzaffar** [comment]
We can but it rebuilds nearly 100 externals. @davidlange6 what do you think?

**Comment by mverzett** [comment]
@smuzaffar , any updates on the possible backport?

**Comment by smuzaffar** [comment]
@mverzett , sorry I should have updated the status here.
It has been backported (https://github.com/cms-sw/cmsdist/pull/2553) to 80X IBs and it should be part of 8_0_21.

**Comment by smuzaffar** [comment]
+externals
80X: https://github.com/cms-sw/cmsdist/pull/2553
81X: https://github.com/cms-sw/cmsdist/pull/2540
