### ISSUE TITLE
turn off optimizations in scram

### ISSUE THREAD

**Issue by kpedro88** [cms-sw/cmssw#14576]
When I run:
```
scram b USER_CXXFLAGS="-g -Og"
```
I get an error message from gmake:
```
gmake: *** unknown output-sync type 'g'.  Stop.
```
The same happens when I use `-O0`. Somehow, scram is not passing this option to the right place. gmake should not care about this option...

This used to work once upon a time, but is definitely broken in 81X. It would be nice to restore this functionality since useful values are often "optimized out" with default settings, reducing the utility of gdb for debugging.

**Comment by davidlt** [comment]
Do: `USER_CXXFLAGS=".." scram b`

**Comment by kpedro88** [comment]
For tcsh this needs to be `env USER_CXXFLAGS=".." scram b`, but then it works. Thanks.

**Comment by slava77** [comment]
or
``` scramv1 b  USER_CXXFLAGS=-g  USER_CXXFLAGS+=-O0 ```
