### ISSUE TITLE
Enable deterministic seeding in RandomServiceHelper

### ISSUE THREAD

**Issue by ericvaandering** [cms-sw/cmssw#14609]
There is a method populate() in RandomServiceHelper: https://github.com/cms-sw/cmssw/blame/CMSSW_8_1_X/IOMC/RandomEngine/python/RandomServiceHelper.py#L200

We'd like to have an equivalent method for deterministically setting the seeds. The signature would be similar but allow the user to specify the initial seed for the python random number service. I think a new method is needed rather than overloading the current method since the current method uses the *args trick, so we'd need to change the signature.

This would be helpful for WMAgent since right now if we want to modify the seeds in a deterministic fashion, we modify the RandomNumberService itself. But this is not robust since we don't know where all the seeds are (in fact, I suspect its currently broken).

The master python seed we will pass to CMSSW will likely be HASH(workflow_name) + job_number

**Comment by Dr15Jones** [comment]
assign core

**Comment by smuzaffar** [comment]
@ericvaandering , is this feature still needed?

**Comment by ericvaandering** [comment]
You can ask @amaltaro but I would guess if it hasn't been done in 7 years it can be closed.

**Comment by smuzaffar** [comment]
ok, so lets close this issue.
@amaltaro , feel free to open a new one if this feature is still needed
