### ISSUE TITLE
Timing out CMSSW_8_1_X_2016-05-21-1100 IB RelVal jobs

### ISSUE THREAD

**Issue by Dr15Jones** [cms-sw/cmssw#14607]
We had several IB RelVal jobs fail in CMSSW_8_1_X_2016-05-21-1100 because they took longer than two hours. E.g.

https://cmssdt.cern.ch/SDT/cgi-bin/buildlogs/slc6_amd64_gcc530/CMSSW_8_1_X_2016-05-21-1100/pyRelValMatrixLogs/run/25209.0_QCD_FlatPt_15_3000HS_13+QCD_FlatPt_15_3000HS_13INPUT+DIGIUP15_PU25+RECOUP15_PU25+HARVESTUP15_PU25/step3_QCD_FlatPt_15_3000HS_13+QCD_FlatPt_15_3000HS_13INPUT+DIGIUP15_PU25+RECOUP15_PU25+HARVESTUP15_PU25.log

However, looking at the log from the three step 3  jobs I found two very bad items:
1) excessive time between opening a file and for first event [24 minutes]:

```
21-May-2016 16:26:02 CEST  Initiating request to open file file:step2.root
21-May-2016 16:26:07 CEST  Successfully opened file file:step2.root
21-May-2016 16:28:42 CEST  Initiating request to open file root://eoscms.cern.ch//eos/cms/store/relval/CMSSW_8_1_0_pre2/RelValMinBias_13/GEN-SIM/80X_mcRun2_asymptotic_v10_gs810pre2-v1/00000/26310425-C2FD-E511-98C6-0025905B85DE.root
21-May-2016 16:28:46 CEST  Successfully opened file root://eoscms.cern.ch//eos/cms/store/relval/CMSSW_8_1_0_pre2/RelValMinBias_13/GEN-SIM/80X_mcRun2_asymptotic_v10_gs810pre2-v1/00000/26310425-C2FD-E511-98C6-0025905B85DE.root
Begin processing the 1st record. Run 1, Event 4, LumiSection 1 at 21-May-2016 16:52:39.127 CEST
```

2) excessive memory usage

```
MemoryReport> Peak virtual size 4128.87 Mbytes
```

**Comment by smuzaffar** [comment]
closing it as we do not see these error any more in IBs.
