### ISSUE TITLE
'git cms-addpkg' is  not working on local user interface

### ISSUE THREAD

**Issue by jha2** [cms-sw/cmssw#14673]
Hello, 
   I am not able to use the tool 'git cms-addpkg'  from the local user interface at the Purdue Tier-2.  However, I am able to use this tool "git cms-addpkg"  from CERN lxplus user interface.  The error while using the tool 'git cms-addpkg'  is following 

"""
# Authorization with github
[jha2@hep tmp]$ ssh -T git@github.com
Warning: untrusted X11 forwarding setup failed: xauth key data not generated
Warning: No xauth data; using fake authentication data for X11 forwarding.
Hi jha2! You've successfully authenticated, but GitHub does not provide shell access.
[jha2@hep tmp]$

[jha2@hep tmp]$ source /cvmfs/cms.cern.ch/cmsset_default.sh
[jha2@hep tmp]$ scramv1 project CMSSW_8_0_1
WARNING: Release CMSSW_8_0_1 is not available for architecture slc6_amd64_gcc472.
         Developer's area is created for available architecture slc6_amd64_gcc493.
[jha2@hep tmp]$ cd CMSSW_8_0_1/src
[jha2@hep src]$ eval `scramv1 runtime -sh`
[jha2@hep src]$ git cms-addpkg PhysicsTools/PatExamples
No release tags specified, using default CMSSW_8_0_1.
fatal: No such remote or remote group: origin
[jha2@hep src]$ 

"""

Do we have to setup additional environment variable while using git  on local user interface ?

Thanks,
Manoj

**Comment by davidlange6** [comment]
just of config your setup - Did you set up your git repository on your remote node just as you did on lxplus? 
(eg, git config….)

**Comment by davidlange6** [comment]
to translate the start of my message - "just to confirm…"

**Comment by jha2** [comment]
I setup the git on remote node (hep) exactly as on lxplus.  Following output may help:

"""
[jha2@hep src]$ git config --list
user.name=Manoj
user.email=Manoj.Jha@cern.ch
user.github=jha2
color.ui=auto
[jha2@hep src]$

[jha2@hep src]$ ssh -T git@github.com
Enter passphrase for key '/home/jha2/.ssh/id_rsa': 
Warning: untrusted X11 forwarding setup failed: xauth key data not generated
Warning: No xauth data; using fake authentication data for X11 forwarding.
Hi jha2! You've successfully authenticated, but GitHub does not provide shell access.
[jha2@hep src]$

"""

**Comment by smuzaffar** [comment]
can you run cms-addpkg in debug mode e.g
git cms-addpkg -d PhysicsTools/PatExamples
and send me the output

**Comment by davidlt** [comment]
There only place where "origin" is being used as remote is your local repository cache.
```
129 # if using a personal reference repository, update it from the official one
130 if [ -e $CMSSW_GIT_REFERENCE/create-`whoami` ]; then
131   (cd $CMSSW_GIT_REFERENCE ;  git remote update origin 2>$VERBOSE_STREAM >$VERBOSE_STREAM)
132 fi
```

If you haven't modified `CMSSW_GIT_REFERENCE` environment variable then it should be `~/.cmsgit-cache`. Look at that directory and see `config` file. Verify that it contains "origin" remote.

Or simply delete `~/.cmsgit-cache` and do `git cms-init` and see if it works afterwards.

**Comment by jha2** [comment]
After deleting ~/.cmsgit-cache and doing 'git cms-init', things are working perfectly.  Ticket can be closed now. 
Thanks,
Manoj
