### ISSUE TITLE
using namespace in header file

### ISSUE THREAD

**Issue by smuzaffar** [cms-sw/cmssw#14762]
We would like to enable the Code Rule Checks for PR testing and reject PR if it has using namespace in header file (modified in the PR).

**Comment by smuzaffar** [comment]
assign dqm
can you please review #14761

**Comment by smuzaffar** [comment]
assign l1
can you please review #14732

**Comment by dmitrijus** [comment]
+1
Signed the PR

**Comment by smuzaffar** [comment]
#14732 is merged also.
