### ISSUE TITLE
watchlist for Tracker DQM packages 

### ISSUE THREAD

**Issue by fioriNTU** [cms-sw/cmssw#14821]
Hi,

I would like to be in the watchlist for the following packages (basically all Tracker DQM ones):

DQM/SiPixelCommon
DQM/SiPixelMonitorClient
DQM/SiPixelMonitorCluster
DQM/SiPixelMonitorDigi
DQM/SiPixelMonitorRawData
DQM/SiPixelMonitorRecHit
DQM/SiPixelMonitorTrack
DQM/SiPixelPhase1Clusters
DQM/SiPixelPhase1Common
DQM/SiPixelPhase1Config/python
DQM/SiPixelPhase1Digis
DQM/SiPixelPhase1RecHits
DQM/SiPixelPhase1TrackClusters
DQM/SiPixelPhase1TrackEfficiency
DQM/SiPixelPhase1TrackResiduals
DQM/SiStripCommon
DQM/SiStripHistoricInfoClient
DQM/SiStripMonitorClient
DQM/SiStripMonitorCluster
DQM/SiStripMonitorDigi
DQM/SiStripMonitorHardware
DQM/SiStripMonitorPedestals
DQM/SiStripMonitorSummary
DQM/SiStripMonitorTrack
DQM/TrackerCommon
DQM/TrackerMonitorTrack
DQM/TrackingMonitor
DQM/TrackingMonitorClient
DQM/TrackingMonitorSource

Thanks in advance.

**Comment by fioriNTU** [comment]
Can you tell me if this is the standard procedure to watch packages or if I can do something myself to speed up things? Having this issue solved would save me tons of mails.

Thanks.

**Comment by davidlange6** [comment]
assign core
@smuzaffar @degano @iahmad-khan

**Comment by davidlange6** [comment]
@fioriNTU you can also just make a pull request for
https://github.com/cms-sw/cms-bot/blob/master/watchers.yaml

**Comment by iahmad-khan** [comment]
Fixed in https://github.com/cms-sw/cms-bot/pull/712

**Comment by smuzaffar** [comment]
+1
