### ISSUE TITLE
Invalid include path in CommonTools/Utils/interface/normalizedPhi.h

### ISSUE THREAD

**Issue by riga** [cms-sw/cmssw#14870]
Hi all,

I think that there are some broken include paths, e.g. in [CommonTools/Utils/interface/normalizedPhi.h](https://github.com/cms-sw/cmssw/blob/CMSSW_8_1_X/CommonTools/Utils/interface/normalizedPhi.h):

```c++
#include "DataFormats/Math/include/normalizedPhi.h"
```

which should be

```c++
#include "DataFormats/Math/interface/normalizedPhi.h"
```

I couldn't check yet, but maybe there are more broken includes. This should be backported to 80X as well.

Cheers,
Marcel

**Comment by smuzaffar** [comment]
Thanks @riga for spotting this. I guess no code in cmssw is including CommonTools/Utils/interface/normalizedPhi.h that is why we do not get compilation errors.

**Comment by slava77** [comment]
we should just remove this file, as well as deltaPhi.h and deltaR.h in the same directory

**Comment by smuzaffar** [comment]
Looks like there is some external code which uses it
https://github.com/search?q=+CommonTools%2FUtils%2Finterface%2FnormalizedPhi.h&type=Code&utf8=%E2%9C%93

I guess that code works in 76X and earlier releases but same code fails for 8XX releases.

**Comment by riga** [comment]
Yep, that's exactly what we observed when transitioning to 80X.

**Comment by slava77** [comment]
@smuzaffar 
I couldn't find an example in your search that wasn't just a copy of CommonTools/Utils package (sombody's forks?)

**Comment by slava77** [comment]
the CommonTools/Utils/src/normalizedPhi.cc was removed in 80X
https://github.com/cms-sw/cmssw/pull/12843
if somebody's setup put's back an old (pre-80X) version of CommonTools/Utils on top of 80X or later release, they are on their own.

**Comment by smuzaffar** [comment]
agree @slava77 
@riga, right approch should be that you update your code to include DataFormats/Math/interface/normalizedPhi.h instead of  CommonTools/Utils/interface/normalizedPhi.h

**Comment by slava77** [comment]
@riga 
which file did you have including CommonTools/Utils/interface/normalizedPhi.h?
If it happened to be CommonTools/Utils/src/normalizedPhi.cc, then your setup is likely malformed.

**Comment by riga** [comment]
Turned out that CommonTools/Utils/interface/normalizedPhi.h was included in the code base of one of our subgroups, I'll just tell them to use DataFormats/Math/interface/normalizedPhi.h instead.

Thanks for the input!
