### ISSUE TITLE
Add CMSSW configuration (multi-threading) information into FrameworkJobReport

### ISSUE THREAD

**Issue by davidlt** [cms-sw/cmssw#14890]
I was looking into CMSSW generated job reports (XML) and I couldn't notice any information about it's configuration.

We are using the following Python file to enable multi-threading in CMSSW: https://github.com/cms-sw/cmssw/blob/CMSSW_8_1_X/FWCore/Concurrency/python/dropNonMTSafe.py

The following options are listed:
- `numberOfThreads`
- `sizeOfStackForThreadsInKB`
- `numberOfStreams`

Could we have this available in job reports, which later are harvested for monitoring?

I find that current CMS Dashboard does not contain information on how many threads CMSSW is using. It's something that HEPiX Benchmarking Working Group would like to know. What dashboard provides is `NCores` currently filled only by WMCore-based software, CRAB3 doesn't do it. It contains max possible numbers of cores (slot size?), but it does not mean that CMSSW is running with that amount of threads.

**Comment by davidlt** [comment]
assign core

**Comment by Dr15Jones** [comment]
number of threads and number of streams are reported in #16565
