### ISSUE TITLE
Change PluginFactory to return a std::unique_ptr

### ISSUE THREAD

**Issue by Dr15Jones** [cms-sw/cmssw#14914]
The present implementation of PluginFactory returns a bare pointer to the newly created item. This should be changed to a std::unique_ptr to help enforce proper memory management.

**Comment by Dr15Jones** [comment]
assign core

**Comment by smuzaffar** [comment]
@Dr15Jones @makortel , is PluginFactory still reruning a bare pointer ?

**Comment by makortel** [comment]
This one has been done, in https://github.com/cms-sw/cmssw/pull/27097

**Comment by makortel** [comment]
+1
