### ISSUE TITLE
[Error] Warning: IO rule for class HcalDetId data member: DetId::id_ was specified as a target in the rule but doesn't seem to appear in target class

### ISSUE THREAD

**Issue by davidlt** [cms-sw/cmssw#14919]
This fails `DataFormats/HcalDetId` dictionary. 

```
Selected class -> HcalElectronicsId for ROOT: HcalElectronicsId
Selected class -> HcalFrontEndId for ROOT: HcalFrontEndId
Selected class -> HcalDetId for ROOT: HcalDetId
Selected class -> HcalTrigTowerDetId for ROOT: HcalTrigTowerDetId
Selected class -> HcalOtherDetId for ROOT: HcalOtherDetId
Selected class -> HcalCalibDetId for ROOT: HcalCalibDetId
Selected class -> HcalZDCDetId for ROOT: HcalZDCDetId
Selected class -> HcalDcsDetId for ROOT: HcalDcsDetId
Selected class -> HcalCastorDetId for ROOT: HcalCastorDetId
Selected class -> CastorElectronicsId for ROOT: CastorElectronicsId
Selected class -> std::vector<HcalElectronicsId, std::allocator<HcalElectronicsId> > for ROOT: vector<HcalElectronicsId>
Selected class -> std::vector<HcalFrontEndId, std::allocator<HcalFrontEndId> > for ROOT: vector<HcalFrontEndId>
Selected class -> std::vector<CastorElectronicsId, std::allocator<CastorElectronicsId> > for ROOT: vector<CastorElectronicsId>
Warning: IO rule for class HcalDetId data member: DetId::id_ was specified as a target in the rule but doesn't seem to appear in target class
```

All warnings are being treated as errors.

```
  8   <class name="HcalDetId" ClassVersion="12">
  9    <version ClassVersion="12" checksum="1604420376"/>
 10    <version ClassVersion="11" checksum="1604420376"/>
 11    <version ClassVersion="10" checksum="193306378"/>
 12    <ioread sourceClass = "HcalDetId" version="[-11]" targetClass="HcalDetId" source="uint32_t DetId::id_;" target="DetId::id_">
 13     <![CDATA[
 14       newFromOld(onfile.rawId());
 15     ]]>
 16    </ioread>
 17   </class>
```

**Comment by davidlt** [comment]
@kpedro88 @bsunanda

Caused by #12883

**Comment by davidlt** [comment]
assign simulation

**Comment by davidlt** [comment]
ping^1

**Comment by bsunanda** [comment]
@davidlt Could you please specify what is wrong - for older version (11 or before) the id_ of the parent class need to be modified by the method newForm. There is a change in the internal format. What needs to be changed for that?

**Comment by davidlt** [comment]
Here is the most recent reply from ROOT team regarding this:

In

  <ioread sourceClass = "HcalDetId" version="[-11]" targetClass="HcalDetId" source="uint32_t DetId::id_;" target="DetId::id_">

The user attempt to specifiy a source **and** a target that are in another (base) class.

Can the rule be applied to DetId or does the 'fix' to the base class member needs to only be done if the actual class is a HcalDetId?  If it is the later we need to find a different solution as currently the base class' StreamerInfo (that actually does the DetId is completely independent from the derived class).

I.e. I think that
```
   <ioread sourceClass = "DetId" version="[-11]" targetClass="DetId" source="uint32_t id_;" target="id_">
    <![CDATA[
      newFromOld(onfile.rawId());
    ]]>
```
would work but might be applied too often.

Note that the following might work, i.e. setting a rule for the derived class that do not have any specific target (and thus ought to be scheduled last).
```
 <ioread sourceClass = "HcalDetId" version="[-11]" targetClass="HcalDetId" source="uint32_t id_;" target="">
  <![CDATA[
      newFromOld(onfile.rawId());
    ]]>
  </ioread>
```
Cheers,
Philippe.

**Comment by bsunanda** [comment]
Hi

How can one schedule it last? Clearly we cannot take the first solution - DetId is base class for too many detectors. Cheers

Sunanda
________________________________

**Comment by davidlt** [comment]
@bsunanda the last example does this by not specifying target rule. Could you try the last example and see if it resolves the issue (warning is gone) and functions as expected?

**Comment by davidlange6** [comment]
-   <ioread sourceClass = "HcalDetId" version="[-11]" targetClass="HcalDetId" source="uint32_t DetId::id_;" target="DetId::id_">
+   <ioread sourceClass = "HcalDetId" version="[-11]" targetClass="HcalDetId" source="uint32_t id_;" target="">

DataFormatsHcalDetId/a/DataFormatsHcalDetId_xr.cc: In function 'void ROOT::read_HcalDetId_0(char*, TVirtualObject*)':
DataFormatsHcalDetId/a/DataFormatsHcalDetId_xr.cc:174:25: error: 'struct ROOT::read_HcalDetId_0(char*, TVirtualObject*)::HcalDetId_Onfile' has no member named 'rawId'
       newFromOld(onfile.rawId());
                         ^
DataFormatsHcalDetId/a/DataFormatsHcalDetId_xr.cc:174:32: error: 'newFromOld' was not declared in this scope
       newFromOld(onfile.rawId());
                                ^

**Comment by Dr15Jones** [comment]
@pcanal it appears your suggestion in the io rule would not compile. Any further suggestions?

**Comment by pcanal** [comment]
Indeed, onfile would only have the data members and no functions.  What is the (intended) implementation of rawId() ?

**Comment by davidlange6** [comment]
underneath rawId() calls a ~10 line function.

https://github.com/cms-sw/cmssw/pull/12883/files#diff-b00a80a07cdb7f12fbc8dfc44090f94eR150

that all needs to be copied in?

**Comment by Dr15Jones** [comment]
```rawId()``` is accessing a value stored in the base class 
https://github.com/cms-sw/cmssw/blob/0397259dd747cee94b68928f17976224c037057a/DataFormats/DetId/interface/DetId.h#L43

So I guess the question is could we do
 ```
_id = HcalDetId::newForm(onfile._id)
```
?
Note that _id is a member of the base class DetId but the IO rule is only for the derived class HcalDetId.

**Comment by davidlange6** [comment]
right - I was confused earlier…let me try

**Comment by davidlange6** [comment]
ok, but then newFromOld() gets called… we need to avoid that too?

**Comment by pcanal** [comment]
> ok, but then newFromOld() gets called… we need to avoid that too?

That depends.  Does the 'value' needs to be transformed/changed in addition to be moved?

Also since the new data member is in the base class (and because we intentionally did not list it in the target), it needs to be set via the object pointer.  So something *like*

   newobj->SetId( TransformOldIdIntoNewId( onfile._id) );

**Comment by smuzaffar** [comment]
any update for this? We need to fix this for ROOT6 IBs which are broken now

**Comment by Dr15Jones** [comment]
There is a fix for the ROOT6 builds in #16256 the regular build is #16275

**Comment by Dr15Jones** [comment]
assign core

**Comment by smuzaffar** [comment]
+1
