### ISSUE TITLE
Crash in DetectPatterns(ZonesOutput) from libL1TriggerL1TMuonEndCap.so  8_1_THREADED_X_2016-06-18-1100

### ISSUE THREAD

**Issue by bouril** [cms-sw/cmssw#14940]
CMSSW_8_1_THREADED_X_2016-06-18-1100

1314.0 WpM_13    crash in 
DetectPatterns(ZonesOutput) from libL1TriggerL1TMuonEndCap.so

BEFORE (start of log)  there is a warning:
L1Trigger/L1TGlobal/python/StableParameters_cff.py is deprecated, please use GlobalParameters_cff.py instead.

https://cmssdt.cern.ch/SDT/cgi-bin/buildlogs/slc6_amd64_gcc530/CMSSW_8_1_THREADED_X_2016-06-18-1100/pyRelValMatrixLogs/run/1314.0_WpM_13+WpM_13INPUT+DIGIUP15+RECOUP15+HARVESTUP15/step2_WpM_13+WpM_13INPUT+DIGIUP15+RECOUP15+HARVESTUP15.log

Thread 4 (Thread 0x7f43d9fff700 (LWP 23585)):
#0  0x00000032b68df283 in poll () from /lib64/libc.so.6
#1  0x00007f447c899da4 in full_read.constprop () from /cvmfs/cms-ib.cern.ch/week1/slc6_amd64_gcc530/cms/cmssw/CMSSW_8_1_THREADED_X_2016-06-18-1100/lib/slc6_amd64_gcc530/pluginFWCoreServicesPlugins.so
#2  0x00007f447c89a00a in edm::service::InitRootHandlers::stacktraceFromThread() () from /cvmfs/cms-ib.cern.ch/week1/slc6_amd64_gcc530/cms/cmssw/CMSSW_8_1_THREADED_X_2016-06-18-1100/lib/slc6_amd64_gcc530/pluginFWCoreServicesPlugins.so
#3  0x00007f447c89a18b in sig_dostack_then_abort () from /cvmfs/cms-ib.cern.ch/week1/slc6_amd64_gcc530/cms/cmssw/CMSSW_8_1_THREADED_X_2016-06-18-1100/lib/slc6_amd64_gcc530/pluginFWCoreServicesPlugins.so
#4  <signal handler called>
#5  0x00007f4465493c1e in DetectPatterns(ZonesOutput) () from /cvmfs/cms-ib.cern.ch/week1/slc6_amd64_gcc530/cms/cmssw/CMSSW_8_1_THREADED_X_2016-06-18-1100/lib/slc6_amd64_gcc530/libL1TriggerL1TMuonEndCap.so
#6  0x00007f4465494811 in Patterns(std::vector<ZonesOutput, std::allocator<ZonesOutput> >) () from /cvmfs/cms-ib.cern.ch/week1/slc6_amd64_gcc530/cms/cmssw/CMSSW_8_1_THREADED_X_2016-06-18-1100/lib/slc6_amd64_gcc530/libL1TriggerL1TMuonEndCap.so
#7  0x00007f443782f24a in L1TMuonEndCapTrackProducer::produce(edm::Event&, edm::EventSetup const&) () from /cvmfs/cms-ib.cern.ch/week1/slc6_amd64_gcc530/cms/cmssw/CMSSW_8_1_THREADED_X_2016-06-18-1100/lib/slc6_amd64_gcc530/pluginL1TriggerL1TMuonEndCapPlugins.so
#8  0x00007f4480ce5cc1 in edm::EDProducer::doEvent(edm::EventPrincipal const&, edm::EventSetup const&, edm::ActivityRegistry*, edm::ModuleCallingContext const*) () from /cvmfs/cms-ib.cern.ch/week1/slc6_amd64_gcc530/cms/cmssw/CMSSW_8_1_THREADED_X_2016-06-18-1100/lib/slc6_amd64_gcc530/libFWCoreFramework.so
#9  0x00007f4480cbf1ff in edm::WorkerT<edm::EDProducer>::implDo(edm::EventPrincipal const&, edm::EventSetup const&, edm::ModuleCallingContext const*) () from /cvmfs/cms-ib.cern.ch/week1/slc6_amd64_gcc530/cms/cmssw/CMSSW_8_1_THREADED_X_2016-06-18-1100/lib/slc6_amd64_gcc530/libFWCoreFramework.so
#10 0x00007f4480c716ec in decltype ({parm#1}()) edm::convertException::wrap<bool edm::Worker::doWork<edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1> >(edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::MyPrincipal const&, edm::EventSetup const&, edm::StreamID, edm::ParentContext const&, edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::Context const*)::{lambda()#1}>(bool edm::Worker::doWork<edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1> >(edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::MyPrincipal const&, edm::EventSetup const&, edm::StreamID, edm::ParentContext const&, edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::Context const*)::{lambda()#1}) () from /cvmfs/cms-ib.cern.ch/week1/slc6_amd64_gcc530/cms/cmssw/CMSSW_8_1_THREADED_X_2016-06-18-1100/lib/slc6_amd64_gcc530/libFWCoreFramework.so
#11 0x00007f4480c718b2 in bool edm::Worker::doWork<edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1> >(edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::MyPrincipal const&, edm::EventSetup const&, edm::StreamID, edm::ParentContext const&, edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::Context const*) () from /cvmfs/cms-ib.cern.ch/week1/slc6_amd64_gcc530/cms/cmssw/CMSSW_8_1_THREADED_X_2016-06-18-1100/lib/slc6_amd64_gcc530/libFWCoreFramework.so
#12 0x00007f4480cae43e in decltype ({parm#1}()) edm::convertException::wrap<void edm::Path::processOneOccurrence<edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1> >(edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::MyPrincipal const&, edm::EventSetup const&, edm::StreamID const&, edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::Context const*)::{lambda()#1}>(void edm::Path::processOneOccurrence<edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1> >(edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::MyPrincipal const&, edm::EventSetup const&, edm::StreamID const&, edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::Context const*)::{lambda()#1}) () from /cvmfs/cms-ib.cern.ch/week1/slc6_amd64_gcc530/cms/cmssw/CMSSW_8_1_THREADED_X_2016-06-18-1100/lib/slc6_amd64_gcc530/libFWCoreFramework.so
#13 0x00007f4480cae6f2 in void edm::Path::processOneOccurrence<edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1> >(edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::MyPrincipal const&, edm::EventSetup const&, edm::StreamID const&, edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::Context const*) () from /cvmfs/cms-ib.cern.ch/week1/slc6_amd64_gcc530/cms/cmssw/CMSSW_8_1_THREADED_X_2016-06-18-1100/lib/slc6_amd64_gcc530/libFWCoreFramework.so
#14 0x00007f4480caeb15 in void edm::StreamSchedule::processOneEvent<edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1> >(edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::MyPrincipal&, edm::EventSetup const&, bool)::{lambda()#1}::operator()() const () from /cvmfs/cms-ib.cern.ch/week1/slc6_amd64_gcc530/cms/cmssw/CMSSW_8_1_THREADED_X_2016-06-18-1100/lib/slc6_amd64_gcc530/libFWCoreFramework.so
#15 0x00007f4480caee0b in decltype ({parm#1}()) edm::convertException::wrap<void edm::StreamSchedule::processOneEvent<edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1> >(edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::MyPrincipal&, edm::EventSetup const&, bool)::{lambda()#1}>(void edm::StreamSchedule::processOneEvent<edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1> >(edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::MyPrincipal&, edm::EventSetup const&, bool)::{lambda()#1}) () from /cvmfs/cms-ib.cern.ch/week1/slc6_amd64_gcc530/cms/cmssw/CMSSW_8_1_THREADED_X_2016-06-18-1100/lib/slc6_amd64_gcc530/libFWCoreFramework.so
#16 0x00007f4480caf07f in void edm::StreamSchedule::processOneEvent<edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1> >(edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::MyPrincipal&, edm::EventSetup const&, bool) () from /cvmfs/cms-ib.cern.ch/week1/slc6_amd64_gcc530/cms/cmssw/CMSSW_8_1_THREADED_X_2016-06-18-1100/lib/slc6_amd64_gcc530/libFWCoreFramework.so
#17 0x00007f4480d0d2a2 in edm::EventProcessor::processEvent(unsigned int) () from /cvmfs/cms-ib.cern.ch/week1/slc6_amd64_gcc530/cms/cmssw/CMSSW_8_1_THREADED_X_2016-06-18-1100/lib/slc6_amd64_gcc530/libFWCoreFramework.so
#18 0x00007f4480d0db1a in edm::EventProcessor::processEventsForStreamAsync(unsigned int, std::atomic<bool>*) () from /cvmfs/cms-ib.cern.ch/week1/slc6_amd64_gcc530/cms/cmssw/CMSSW_8_1_THREADED_X_2016-06-18-1100/lib/slc6_amd64_gcc530/libFWCoreFramework.so
#19 0x00007f4480d140a4 in edm::StreamProcessingTask::execute() () from /cvmfs/cms-ib.cern.ch/week1/slc6_amd64_gcc530/cms/cmssw/CMSSW_8_1_THREADED_X_2016-06-18-1100/lib/slc6_amd64_gcc530/libFWCoreFramework.so
#20 0x00007f447fa3b9b5 in tbb::internal::custom_scheduler<tbb::internal::IntelSchedulerTraits>::local_wait_for_all (this=0x7f442d953e00, parent=..., child=<optimized out>) at ../../src/tbb/custom_scheduler.h:463
#21 0x00007f447fa351a4 in tbb::internal::arena::process (this=this@entry=0x7f447e37f780, s=...) at ../../src/tbb/arena.cpp:156
#22 0x00007f447fa34264 in tbb::internal::market::process (this=0x7f447e3a7c00, j=...) at ../../src/tbb/market.cpp:502
#23 0x00007f447fa30736 in tbb::internal::rml::private_worker::run (this=0x7f447e1c6100) at ../../src/tbb/private_server.cpp:275
#24 0x00007f447fa30989 in tbb::internal::rml::private_worker::thread_routine (arg=<optimized out>) at ../../src/tbb/private_server.cpp:228
#25 0x00000032b6c07aa1 in start_thread () from /lib64/libpthread.so.0
#26 0x00000032b68e8aad in clone () from /lib64/libc.so.6

**Comment by Dr15Jones** [comment]
assign core

**Comment by Dr15Jones** [comment]
@dan131riley

**Comment by Dr15Jones** [comment]
@dan131riley I believe #14941 fixes this?

**Comment by dan131riley** [comment]
Yes, this is the crash that #14941 fixes.

-dan

**Comment by Dr15Jones** [comment]
+1
