### ISSUE TITLE
Adding Phase2 workflows to PR tests

### ISSUE THREAD

**Issue by kpedro88** [cms-sw/cmssw#14975]
I would like to add Phase2 workflows to the PR tests. I just checked that they are working in the latest IB CMSSW_8_1_X_2016-06-24-1100.

Currently we have 3 geometries/scenarios: LReco, GReco, and tilted. The corresponding WF numbers are 110xx, 106xx, 112xx. (PU workflows can be ignored for now while geometries are changing rapidly.)

Is it possible to have tests for all of them?

Which physics process should we choose?

attn: @davidlange6, @slava77, @boudoul

**Comment by slava77** [comment]
Please pick at most two.

**Comment by slava77** [comment]
@kpedro88 
also, the workflows should be visible in regular matrix (not the one -w upgrade)

**Comment by kpedro88** [comment]
Okay, I guess we should choose LReco (to include HGCal) and GReco (to have the full workflow). tilted should be identical to GReco except for the tracker geometry; we just have to be vigilant about propagating any geometry XML changes.

I don't know how to make upgrade workflows visible in the regular matrix. Any help would be appreciated...

**Comment by kpedro88** [comment]
It actually turned out to be pretty easy when I realized @boudoul did most of the hard work in #14731. Thanks!

Discussion can be continued in #14977.
