### ISSUE TITLE
Issue with FormulaEvaluator

### ISSUE THREAD

**Issue by aminnj** [cms-sw/cmssw#15105]
@Dr15Jones

CMSSW FormulaEvaluator disagrees with C/TFormula in 8_0_12, 8_0_10_patch2, and CMSSW_8_1_DEVEL_X_2016-07-03-0000 (which should be patched for something related to this previously)

Test script illustrating problem (recipe at the top):
http://uaf-6.t2.ucsd.edu/~namin/dump/test_formula.C

This is urgently needed for L2 JEC for ICHEP. The gaussian part (specifically, -[4]*(log10(x)-[5])*(log10(x)-[5]) is the source of the disagreement).

**Comment by Dr15Jones** [comment]
Using ` -[4]*((log10(x)-[5])*(log10(x)-[5]))` does work. This matches closer to what formulas were originally used.

**Comment by Dr15Jones** [comment]
Using `-1*[4]*(log10(x)-[5])*(log10(x)-[5])` also works.

**Comment by Dr15Jones** [comment]
So I have determined that the expression `-[4]*(log10(x)-[5])*(log10(x)-[5])` when parsed by the FormulaEvaluator is losing one of the `(log10(x)-[5])` from the calculation.

**Comment by kpedro88** [comment]
@Dr15Jones thanks for taking a look quickly. It seems like this could point to a bug, but since there are alternative forms that work, @aminnj, could you use one of those in the meantime?

**Comment by aminnj** [comment]
Thanks for such a quick response! I will just go ahead and redistribute JEC text files with -1*[4] instead of [4], since I've also verified that it works.

**Comment by Dr15Jones** [comment]
I have found the bug and will be making a bug fix (it is only a change of using a different member data for a function call :( )

**Comment by Dr15Jones** [comment]
See #15106

**Comment by Dr15Jones** [comment]
assign core

**Comment by Dr15Jones** [comment]
The CMSSW_8_0_X version is #15107.

**Comment by Dr15Jones** [comment]
+1
