### ISSUE TITLE
Remove template instantiating code from classes.h files

### ISSUE THREAD

**Issue by wddgit** [cms-sw/cmssw#15123]
With ROOT 6, the ROOT experts tell us it is no longer necessary to
have code in the classes.h files that causes template instances to
be explicitly instantiated. The only thing we need in those files is
the "#include" lines. We needed this code for ROOT 5. Removing
those lines simplifies our code and it also helps speed things up and
use less memory when using a ROOT script or pyROOT in a way that
causes the dictionary libraries to be loaded. Note that there are some
other files with slightly different names that serve the same purpose as
the classes.h files that also need the same modification.

**Comment by Dr15Jones** [comment]
assign core

**Comment by smuzaffar** [comment]
+1
https://github.com/cms-sw/cmssw/pull/25826 addresses this
