### ISSUE TITLE
subscribe to CMSSW packages

### ISSUE THREAD

**Issue by mariadalfonso** [cms-sw/cmssw#15161]
This is a response to the HN post:
https://hypernews.cern.ch/HyperNews/CMS/get/git/43/1.html

I'd like to watch the following subdirs:

RecoLocalCalo/HcalRecProducers
RecoLocalCalo/HcalRecAlgos
DataFormats/HcalRecHit
DataFormats/HcalDigi
DataFormats/HcalDetId
CalibCalorimetry/HcalAlgos/
SimCalorimetry/HcalSimAlgos/
SimCalorimetry/HcalSimProducers

**Comment by smuzaffar** [comment]
assign core
@iahmad-khan , can you please take care of it?

**Comment by smuzaffar** [comment]
+1
done here https://github.com/cms-sw/cms-bot/pull/726
