### ISSUE TITLE
Failing tests due to missing files at T2_CH_CERN

### ISSUE THREAD

**Issue by ghellwig** [cms-sw/cmssw#15188]
Since ~yesterday we experience test failures because files have been removed from T2_CH_CERN that are needed for the matrix tests.

For instance the following query in 1000.0 and 1001.0 gives empty results as is expected since the files seem to be gone:
```
file dataset=/MinimumBias/Run2011A-v1/RAW run=165121 site=T2_CH_CERN
```

FYI @davidlange6 @smuzaffar

**Comment by davidlt** [comment]
We had a high number of GEN-SIM data removed from T2_CH_CERN and most of it is not available in HDDs in Europe. We have already requested a good fraction of that data to be transferred back to T2_CH_CERN, but it will take time.

**Comment by ghellwig** [comment]
But this is not GEN-SIM, i.e. do we have a separate issue here?

**Comment by mmusich** [comment]
indeed:

```
$ das_client.py --limit=0 --query='block dataset=/MinimumBias/Run2011A-v1/RAW run=165121 '
/MinimumBias/Run2011A-v1/RAW#f6f3c7cc-7fbf-11e0-b519-003048caaace

$ das_client.py --limit=0 --query='site block=/MinimumBias/Run2011A-v1/RAW#f6f3c7cc-7fbf-11e0-b519-003048caaace '
T2_US_Caltech
T2_FR_GRIF_IRFU
T1_US_FNAL_MSS
T1_US_FNAL_Disk
T1_US_FNAL_Buffer
T0_CH_CERN_MSS
T0_CH_CERN_Export
```

**Comment by mmusich** [comment]
This is seriously blocking PR integration. Can we bring it back to T2 ASAP?

**Comment by franzoni** [comment]
@davidlt 
there's a dedicated pool of relvals in phedex which is IB specific, can you make sure that whichever re-transfer you've commanded is into that pool (so to avoid DDM or other deletions to create this situation again ?) 

@hengne @fabozzi 
can you please take care of checking what needs be retransferred back to CERN ? It's not only gen-sim minssing, as @ghellwig reports, it's also RAW inputs to "classic" relval workflows

**Comment by davidlt** [comment]
Yeah, most of data was GEN-SIM, but not all. Majority if that is being transferred under "IB RelVals". This data wasn't part of "IB RelVals" otherwise we would have got an email on deletion request.

**Comment by fabozzi** [comment]
I have requested transfer of 
/MinimumBias/Run2011A-v1/RAW#f6f3c7cc-7fbf-11e0-b519-003048caaace
to T2_CH_CERN

**Comment by ghellwig** [comment]
Thanks @fabozzi the block is back at T2_CH_CERN
Shall I close this issue or is further action needed, e.g. some protection against accidental deletion?

**Comment by mmusich** [comment]
Hi @fabozzi, 
I keep getting errors in  #15174
```
----- Begin Fatal Exception 14-Jul-2016 16:50:03 CEST-----------------------
An exception of category 'FallbackFileOpenError' occurred while
   [0] Constructing the EventProcessor
   [1] Constructing input source of type PoolSource
   [2] Calling RootFileSequenceBase::initTheFile()
   [3] Calling StorageFactory::open()
   [4] Calling XrdFile::open()
Exception Message:
Failed to open the file 'root://xrootd-cms.infn.it//store/relval/CMSSW_8_0_0/RelValTTbar_13/GEN-SIM-RECO/80X_mcRun2_asymptotic_v4-v1/10000/1C687FB0-7BD9-E511-AFED-0CC47A78A4BA.root'
   Additional Info:
      [a] XrdCl::File::Open(name='root://eoscms.cern.ch//eos/cms/store/relval/CMSSW_8_0_0/RelValTTbar_13/GEN-SIM-RECO/80X_mcRun2_asymptotic_v4-v1/10000/1C687FB0-7BD9-E511-AFED-0CC47A78A4BA.root', flags=0x10, permissions=0660) => error '[ERROR] Server responded with an error: [3011] Unable to open file /eos/cms/store/relval/CMSSW_8_0_0/RelValTTbar_13/GEN-SIM-RECO/80X_mcRun2_asymptotic_v4-v1/10000/1C687FB0-7BD9-E511-AFED-0CC47A78A4BA.root; No such file or directory
' (errno=3011, code=400). No additional data servers were found.
      [b] Last URL tried: root://eoscms.cern.ch:1094//eos/cms/store/relval/CMSSW_8_0_0/RelValTTbar_13/GEN-SIM-RECO/80X_mcRun2_asymptotic_v4-v1/10000/1C687FB0-7BD9-E511-AFED-0CC47A78A4BA.root?tried=
      [c] Problematic data server: eoscms.cern.ch:1094
      [d] Disabled source: eoscms.cern.ch:1094
      [e] Input file root://eoscms.cern.ch//eos/cms/store/relval/CMSSW_8_0_0/RelValTTbar_13/GEN-SIM-RECO/80X_mcRun2_asymptotic_v4-v1/10000/1C687FB0-7BD9-E511-AFED-0CC47A78A4BA.root could not be opened.
Fallback Input file root://xrootd-cms.infn.it//store/relval/CMSSW_8_0_0/RelValTTbar_13/GEN-SIM-RECO/80X_mcRun2_asymptotic_v4-v1/10000/1C687FB0-7BD9-E511-AFED-0CC47A78A4BA.root also could not be opened.
Original exception info is above; fallback exception info is below.
      [f] XrdCl::File::Open(name='root://xrootd-cms.infn.it//store/relval/CMSSW_8_0_0/RelValTTbar_13/GEN-SIM-RECO/80X_mcRun2_asymptotic_v4-v1/10000/1C687FB0-7BD9-E511-AFED-0CC47A78A4BA.root', flags=0x10, permissions=0660) => error '[ERROR] Server responded with an error: [3011] No servers are available to read the file.
' (errno=3011, code=400). No additional data servers were found.
      [g] Last URL tried: root://cms-xrd-transit.cern.ch:1094//store/relval/CMSSW_8_0_0/RelValTTbar_13/GEN-SIM-RECO/80X_mcRun2_asymptotic_v4-v1/10000/1C687FB0-7BD9-E511-AFED-0CC47A78A4BA.root?tried=+1098xrdcmsglobal011098xrdcmsglobal02.cern.ch,+1213cmsxrootd1.fnal.gov1213xrootd.unl.edu,+1213xrootd.ba.infn.it,
      [h] Problematic data server: cms-xrd-transit.cern.ch:1094
      [i] Disabled source: cms-xrd-transit.cern.ch:1094
----- End Fatal Exception -------------------------------------------------
```
apparently due to missing block at Tier2:
`/RelValTTbar_13/CMSSW_8_0_0-80X_mcRun2_asymptotic_v4-v1/GEN-SIM-RECO#f8ba9fec-da12-11e5-a23c-02163e016cc2`

I've opened a phedex transfer request:

https://cmsweb.cern.ch/phedex/prod/Request::View?request=737475

could you please approve it?

**Comment by mmusich** [comment]
For the record the VOC approved it. Re-trying once again.

**Comment by smuzaffar** [comment]
Both 
/RelValTTbar_13/CMSSW_8_0_0-80X_mcRun2_asymptotic_v4-v1/GEN-SIM-RECO#f8ba9fec-da12-11e5-a23c-02163e016cc2
/MinimumBias/Run2011A-v1/RAW#f6f3c7cc-7fbf-11e0-b519-003048caaace

and under IB RelVal and available at CERN. Can we close this issue?

**Comment by mmusich** [comment]
Hi @smuzaffar I guess so, thanks!
