### ISSUE TITLE
Proposal: Allow way to specify groups of modules to work as a Task in unscheduled

### ISSUE THREAD

**Issue by Dr15Jones** [cms-sw/cmssw#15193]
The way scheduled processing jobs are configured is we load configurations into the job containing many modules and many `Sequences`. These sequences are put into `Paths` and then at the last step we put `Paths` in a `Schedule` to declare which Paths (and therefore which modules) we actually want to run. This leaves many modules and `Sequences` in the `Process` which are not meant to be used.

The unscheduled was intended to work different. The unscheduled configuration was intended only to contain those modules that are supposed to be run. However, unscheduled did allow extra `Paths` to be declared which are not intended to be used by the job (i.e. are not used in the `Schedule`). 

Given that the vast majority of our configuration files were created with scheduled execution in mind, the requirement to only load modules needed for a `Process` is an unrealistic constraint.

It appears that when developers create `Sequences` they are actually trying to describe a _task_ they want to accomplish. They then compose larger scale _tasks_ from lower level _tasks_. 

I propose building on this observation by adding a `Task` class to the configuration language. The `Task` would contain an unordered set of `EDProducers`, `EDFilters`, `ESProducers`, `ESSources`, `Services` and others `Tasks`. A `Task` can be attached to a `Path` or `EndPath`. The framework would then only instantiate those modules declared in the `Paths`/`EndPaths` (as well as their attached Tasks) which were actually being used in the job (i.e. declared in the `Schedule` if one is defined).

This would mean we would no longer have to 'switch on' unscheduled since the presence of modules in a `Task` would declare what needs to be run unscheduled.

The function `convertToUnscheduled` would simply rewrite the `Paths` and `EndPaths` keeping the `EDFilters` and `EDAnalyzers` on the `Path` or `EndPaths` but move all `EDProducers` to a new `Task` which is attached to the proper `Path` or `EndPath`. This would mean you could call `convertToUnscheduled` twice and you'd still get the same configuration back (which is not true now).

Another benefit of the `Task` system would be to unify the configuration of the `EventSetup` system and the `Event` system. This would also allow us to avoid creating unneeded `EventSetup` components in the job.

**Comment by Dr15Jones** [comment]
@slava77 Would this solve the problem you were having dealing with unscheduled?

**Comment by Dr15Jones** [comment]
@makortel Since you've had lots of experience with the configuration system, I was wondering what your thoughts on this proposal are?

**Comment by Dr15Jones** [comment]
assign core

**Comment by Dr15Jones** [comment]
@fwyzard How might this proposal affect HLT configurations?

**Comment by slava77** [comment]
On 7/13/16 8:13 AM, Chris Jones wrote:
> @slava77 <https://github.com/slava77> Would this solve the problem you
> were having dealing with unscheduled?

It sounds like it will.
Thank you.

**Comment by makortel** [comment]
@Dr15Jones Interesting idea. I have three questions/thoughts for starters:

1. `Task` would store `EDFilters` in unordered set. What would dictate their order of execution? I believe the order of filters is an important property (e.g. in HLT)
2. I guess one point would be to collect all `ESProducers` etc. needed by the EDModules in a `Task` to the same `Task`. Although it would mean "more work" when defining the `Tasks`, I think it would be for good. Currently finding where exactly a specific `ESProducer`/`Service`/etc needed by an EDModule is defined can be tedious.
3. For cloning/eras a `Task` would have the same level of customizability, right?

**Comment by Dr15Jones** [comment]
> Task would store EDFilters in unordered set. What would dictate their order of execution? I believe the order of filters is an important property (e.g. in HLT)

If an `EDFilter` were on a `Task` it would be there because only its data product is needed but not its filter decision. Unfortunately we have many `EDFilters` which really should be `EDProducers`. This is just a way to accomodate them.

> I guess one point would be to collect all ESProducers etc. needed by the EDModules in a Task to the same Task. Although it would mean "more work" when defining the Tasks, I think it would be for good. Currently finding where exactly a specific ESProducer/Service/etc needed by an EDModule is defined can be tedious.

One could specify a `Task` only containing `ESModules` and then associate that `Task` to a `Task` defining `EDModule` activities.

> For cloning/eras a Task would have the same level of customizability, right?

Yes. A `Task` is pretty much the same as a `Sequence` except the ordering is not enforced. (And a `Task` can not be put *into* a `Path` it can only be *associated to* a `Path`.)

**Comment by makortel** [comment]
> > Task would store EDFilters in unordered set. What would dictate their order of execution? I believe the order of filters is an important property (e.g. in HLT)
> 
> If an EDFilter were on a Task it would be there because only its data product is needed but not its filter decision. Unfortunately we have many EDFilters which really should be EDProducers. This is just a way to accomodate them.

Aa, so the `Task` would not be a replacement of the `Sequence`, but a separate abstraction for modules not needing explicit execution order (which would continue to be served with `Sequence`). Would the filter decision of an `EDFilter` in a `Task` be ignored? Could one associate a `Task` to a `Sequence` too?

**Comment by Dr15Jones** [comment]
Correct, `Sequences` would still be around but hopefully eventually not containing `EDProducers` anymore. 

The filter decision of an `EDFilter` would be ignored since that is how an unscheduled `EDFilter` is handled now. 

I was thinking one could associate a `Task` to a `Sequence` as well.

**Comment by wddgit** [comment]
PR #17801 resolves this issue and implemented the Task feature. I think this issue can be closed

**Comment by Dr15Jones** [comment]
+1

**Comment by fwyzard** [comment]
Is this something we have also in (or are going to backport to) 9.2.x ?

**Comment by Dr15Jones** [comment]
@fwyzard it is in 9_2 already.

**Comment by fwyzard** [comment]
Thanks.
.A
