### ISSUE TITLE
LHEReader valgrind Report

### ISSUE THREAD

**Issue by ianna** [cms-sw/cmssw#15291]
valgrind reports the following issues while running 512.0 workflow:

– Invalid read of size 1 - reported 8 times at begin job
– Invalid read of size 8 - reported 5 times at end job
– Memory loss in using transcode and serialisation

https://indico.cern.ch/event/559661/contributions/2258177/attachments/1315640/1970784/Xerces_31_Migration_Status_26.07.2016.pdf

**Comment by Dr15Jones** [comment]
assign generators

**Comment by govoni** [comment]
@mkirsano please add also Alexander, I cannot find his github ID

**Comment by govoni** [comment]
@ agrohsje

**Comment by govoni** [comment]
@agrohsje

**Comment by perrozzi** [comment]
the memory leak should be fixed by https://github.com/cms-sw/cmssw/pull/15673
