### ISSUE TITLE
Unit tests failing in CondCore/ORA

### ISSUE THREAD

**Issue by smuzaffar** [cms-sw/cmssw#15390]
Many unit tests in CondCore/ORA are failing with error message

```
CORAL/RelationalPlugins/oracle Error ORA-28001: the password has expired (authenticating)
### TEST testORA_1 ERROR: Connection on "oracle://cms_orcoff_prep/CMS_COND_UNIT_TESTS" cannot be established ( CORAL : "ConnectionPool::getSessionFromNewConnection" from "CORAL/Services/ConnectionService" )
```

see the full log here
https://cmssdt.cern.ch/SDT/cgi-bin/buildlogs/slc6_amd64_gcc530/CMSSW_8_1_X_2016-08-08-1100/unitTestLogs/CondCore/ORA

@ggovi , any idea?

**Comment by smuzaffar** [comment]
assign db

**Comment by smuzaffar** [comment]
@ggovi , can you please fix unit tests for 81X?

**Comment by ggovi** [comment]
@smuzaffar 
This looks like the consequence of a general problem ( CondCore/ORA is not relevant anyhow, since it is no longer used ):

cd CMSSW_8_1_X_2016-08-16-2300/src
cmsenv
echo $TNS_ADMIN

gives 

/etc/

which is obviously not the right place for the tnsnames.ora required by CMS

**Comment by smuzaffar** [comment]
ah right, yes we have dropped the oracle-env from cmssw (which was providing the tnsname.ora). 
So what do you suggest .... should we drop CondCore/ORA or disable tests of this package?

**Comment by ggovi** [comment]
we can drop the CondCore/ORA package, but we still need the oracle-env for other packages - I guess...

**Comment by smuzaffar** [comment]
@ggovi , I checked in CMSSW_8_1_0_pre5 where TNS_ADMIN points to /cvmfs/cms.cern.ch/slc6_amd64_gcc530/cms/oracle-env/29/etc and still these ORA tests fail there.
