### ISSUE TITLE
Deprecated datasets/blocks used in IBs

### ISSUE THREAD

**Issue by smuzaffar** [cms-sw/cmssw#15409]
@davidlange6 , we have following 9 datasets which have been marked as deprecated in DBS but we are using them in various IBs.

```
  Block: /DoubleElectron/Run2012C-ZElectron-PromptSkim-v3/RAW-RECO#1c209a6c-dadb-11e1-bc27-003048c9c3fe
    Releases: CMSSW_5_3_X
  Block: /DoubleElectron/Run2012D-ZElectron-PromptSkim-v1/RAW-RECO#d23d85dc-339e-11e2-b7ab-00155dffff9d
    Releases: CMSSW_5_3_X
  Block: /SingleElectron/Run2012B-WElectron-13Jul2012-v1/USER#9d0bcb5e-d7cc-11e1-9819-003048f02c8a
    Releases: CMSSW_7_1_X,CMSSW_7_4_X,CMSSW_7_5_X,CMSSW_7_6_X,CMSSW_8_0_X,CMSSW_8_1_X
  Block: /SingleElectron/Run2012B-WElectron-PromptSkim-v1/USER#3b8138ba-a9f0-11e1-9de3-003048c9c3fe
    Releases: CMSSW_5_3_X
  Block: /SingleElectron/Run2012C-WElectron-PromptSkim-v3/USER#9df32e52-da7b-11e1-bc27-003048c9c3fe
    Releases: CMSSW_5_3_X,CMSSW_7_1_X,CMSSW_7_4_X,CMSSW_7_5_X,CMSSW_7_6_X,CMSSW_8_0_X,CMSSW_8_1_X
  Block: /SingleElectron/Run2012D-WElectron-PromptSkim-v1/USER#17a3e51a-3d1a-11e2-ba58-00155dffff9d
    Releases: CMSSW_5_3_X
  Block: /SingleElectron/Run2012D-WElectron-PromptSkim-v1/USER#e215d26e-331e-11e2-b7aa-00155dffff9d
    Releases: CMSSW_7_1_X,CMSSW_7_4_X,CMSSW_7_5_X,CMSSW_7_6_X,CMSSW_8_0_X
  Block: /SingleMu/Run2012D-ZMu-PromptSkim-v1/RAW-RECO#0115dd24-3ce0-11e2-ba58-00155dffff9d
    Releases: CMSSW_5_3_X
  Block: /SingleMu/Run2012D-ZMu-PromptSkim-v1/RAW-RECO#4cbf9c30-331f-11e2-b7aa-00155dffff9d
    Releases: CMSSW_7_1_X,CMSSW_7_4_X,CMSSW_7_5_X,CMSSW_7_6_X,CMSSW_8_0_X
```

do we have any updated datasets to replace these?

**Comment by davidlt** [comment]
@smuzaffar could you also fetch information which workflow/unit test/step it is?

**Comment by davidlange6** [comment]
these all look like data processing tests in runTheMatrix.
eg
https://github.com/cms-sw/cmssw/search?utf8=✓&q=%2FSingleElectron%2FRun2012B-WElectron-13Jul2012-v1%2FUSER<https://github.com/cms-sw/cmssw/search?utf8=%E2%9C%93&q=/SingleElectron/Run2012B-WElectron-13Jul2012-v1/USER>

On Aug 10, 2016, at 11:51 AM, davidlt <notifications@github.com<mailto:notifications@github.com>> wrote:


@smuzaffar<https://github.com/smuzaffar> could you also fetch information which workflow/unit test/step it is?

**Comment by davidlange6** [comment]
On Aug 10, 2016, at 11:44 AM, Malik Shahzad Muzaffar <notifications@github.com<mailto:notifications@github.com>> wrote:


@davidlange6<https://github.com/davidlange6> , we have following 9 datasets which have been marked as deprecated in DBS but we are using them in various IBs.

  Block: /DoubleElectron/Run2012C-ZElectron-PromptSkim-v3/RAW-RECO#1c209a6c-dadb-11e1-bc27-003048c9c3fe
    Releases: CMSSW_5_3_X
  Block: /DoubleElectron/Run2012D-ZElectron-PromptSkim-v1/RAW-RECO#d23d85dc-339e-11e2-b7ab-00155dffff9d
    Releases: CMSSW_5_3_X


these previous two can be replaced by a block from

/DoubleElectron/Run2012D-ZElectron-22Jan2013-v1/RAW-RECO<https://cmsweb.cern.ch/das/request?input=dataset%3D%2FDoubleElectron%2FRun2012D-ZElectron-22Jan2013-v1%2FRAW-RECO&instance=prod%2Fglobal>


  Block: /SingleElectron/Run2012B-WElectron-13Jul2012-v1/USER#9d0bcb5e-d7cc-11e1-9819-003048f02c8a
    Releases: CMSSW_7_1_X,CMSSW_7_4_X,CMSSW_7_5_X,CMSSW_7_6_X,CMSSW_8_0_X,CMSSW_8_1_X

  Block: /SingleElectron/Run2012B-WElectron-PromptSkim-v1/USER#3b8138ba-a9f0-11e1-9de3-003048c9c3fe
    Releases: CMSSW_5_3_X


these previous two can be replaced by a block from

/SingleElectron/Run2012B-WElectron-22Jan2013-v1/USER<https://cmsweb.cern.ch/das/request?input=dataset%3D%2FSingleElectron%2FRun2012B-WElectron-22Jan2013-v1%2FUSER&instance=prod%2Fglobal>



  Block: /SingleElectron/Run2012C-WElectron-PromptSkim-v3/USER#9df32e52-da7b-11e1-bc27-003048c9c3fe
    Releases: CMSSW_5_3_X,CMSSW_7_1_X,CMSSW_7_4_X,CMSSW_7_5_X,CMSSW_7_6_X,CMSSW_8_0_X,CMSSW_8_1_X


no replacement it seems. Time to delete this from the relval matrix



  Block: /SingleElectron/Run2012D-WElectron-PromptSkim-v1/USER#17a3e51a-3d1a-11e2-ba58-00155dffff9d
    Releases: CMSSW_5_3_X
  Block: /SingleElectron/Run2012D-WElectron-PromptSkim-v1/USER#e215d26e-331e-11e2-b7aa-00155dffff9d
    Releases: CMSSW_7_1_X,CMSSW_7_4_X,CMSSW_7_5_X,CMSSW_7_6_X,CMSSW_8_0_X


/SingleElectron/Run2012D-WElectron-PromptSkim-v1/USER<https://cmsweb.cern.ch/das/request?input=dataset%3D%2FSingleElectron%2FRun2012D-WElectron-PromptSkim-v1%2FUSER&instance=prod%2Fglobal>


  Block: /SingleMu/Run2012D-ZMu-PromptSkim-v1/RAW-RECO#0115dd24-3ce0-11e2-ba58-00155dffff9d
    Releases: CMSSW_5_3_X
  Block: /SingleMu/Run2012D-ZMu-PromptSkim-v1/RAW-RECO#4cbf9c30-331f-11e2-b7aa-00155dffff9d
    Releases: CMSSW_7_1_X,CMSSW_7_4_X,CMSSW_7_5_X,CMSSW_7_6_X,CMSSW_8_0_X


/SingleMu/Run2012D-ZMu-PromptSkim-v1/RAW-RECO<https://cmsweb.cern.ch/das/request?input=dataset%3D%2FSingleMu%2FRun2012D-ZMu-PromptSkim-v1%2FRAW-RECO&instance=prod%2Fglobal>


best for these is to find the run number we are using and take the corresponding block. do you have the full logs for these offending datasets?




do we have any updated datasets to replace these?

**Comment by smuzaffar** [comment]
these are only used in step2 on workflow 4.58, 4.67, 4.68, 4.76, 4.77, 4.78
