### ISSUE TITLE
update externals from devel to mainstream

### ISSUE THREAD

**Issue by davidlange6** [cms-sw/cmssw#15602]
Hi all

please update 
jemalloc, scikit-learn, numpy, matplotlib, cmake from devel to the mainstream 81x.

**Comment by davidlange6** [comment]
assign core
@smuzaffar @iahmad-khan

**Comment by iahmad-khan** [comment]
@davidlange6 yes , i am looking into it.

**Comment by smuzaffar** [comment]
this is done
