### ISSUE TITLE
Please make a CMSSW_8_0_18_patchX branch

### ISSUE THREAD

**Issue by davidlange6** [cms-sw/cmssw#15604]
based on the current 80x queue. 
Thanks

**Comment by davidlange6** [comment]
assign core

**Comment by smuzaffar** [comment]
sorry @davidlange6 , I overlooked this issue. https://github.com/cms-sw/cmssw/tree/CMSSW_8_0_18_patchX is available now. Let me know if this contains extra changes which should not be included.

**Comment by Dr15Jones** [comment]
@davidlange6 @smuzaffar can this be closed now?

**Comment by smuzaffar** [comment]
+1
yes this can be cloed now
