### ISSUE TITLE
RootEmbeddedFileSequence retry issues

### ISSUE THREAD

**Issue by dan131riley** [cms-sw/cmssw#15653]
Per this HN thread:

https://hypernews.cern.ch/HyperNews/CMS/get/edmFramework/3674/1/1/1/1/1/1/2.html

RootEmbeddedFileSequence only partially respects skipBadFiles--it skips bad files on the initial file input, but when RootEmbeddedFileSequence::readOneRandom() moves to a new file it throws an exception on the first failure instead of retrying:

https://github.com/cms-sw/cmssw/blob/CMSSW_8_1_X/IOPool/Input/src/RootEmbeddedFileSequence.cc#L249

In addition, using the number of files in the list as the retry count doesn't make much sense for a random selection, and also doesn't make sense if retries are being cause by a systemic problem like a site issue.  For production use of retries the retry count should be configurable.

**Comment by Dr15Jones** [comment]
assign core

**Comment by smuzaffar** [comment]
@Dr15Jones , @makortel was this every addressed?

**Comment by makortel** [comment]
Seems to me that this has not been addressed yet.

**Comment by dan131riley** [comment]
No, it hasn't...I need to get my OmniFocus discipline back and clean up some of these old bits
