### ISSUE TITLE
Remove from cms-sw/generators watch and approval

### ISSUE THREAD

**Issue by covarell** [cms-sw/cmssw#15729]
Since my GEN convenership term ended, can I ask you to remove my username (@covarell) from cms-sw/generators watch and approval rights? thanks

**Comment by smuzaffar** [comment]
done https://github.com/cms-sw/cms-bot/commit/750132a444669036d9a67675db5cd599f11421a8#diff-417e11b1e1850b8ae8144113fab3075e
