### ISSUE TITLE
Update GSL Version

### ISSUE THREAD

**Issue by aperloff** [cms-sw/cmssw#15739]
It appears that the GSL version used for slc6_amd64_gcc530 (i.e. CMSSW_8_1_0_pre9) is 1.16, which came out on 7/19/2013. This is quite old and there was a new version, 2.2.1, released on 8/31/2016. Could this be added as a planned update of the external packages?

**Comment by smuzaffar** [comment]
assign externals

**Comment by smuzaffar** [comment]
done here https://github.com/cms-sw/cmsdist/pull/2506

**Comment by smuzaffar** [comment]
+1
