### ISSUE TITLE
Report CPU usage to HTCondor reporting service

### ISSUE THREAD

**Issue by bbockelm** [cms-sw/cmssw#15763]
The HTCondor reporting service's initial implementation didn't include CPU usage information - it was considered redundant as HTCondor also measured CPU usage of the entire job.

*However*, WMAgent can package multiple invocations of `cmsRun` into a single HTCondor job: this means we can't differentiate the CPU usage from each step without digging up the individual step FJR or stdout.

Hence, we should add CPU usage and model information to the existing `CondorStatusService`.

**Comment by Dr15Jones** [comment]
assign core
