### ISSUE TITLE
Automatically account for CPU usage of child processes

### ISSUE THREAD

**Issue by bbockelm** [cms-sw/cmssw#15764]
While the TimingServiceBase allows generators that are fork/exec'd to explicitly report out-of-process CPU usage, it seems that no one is currently doing this.

Accordingly, we should automatically add the CPU usage of children via the `getrusage(RUSAGE_CHILDREN, ...)` call.

**Comment by Dr15Jones** [comment]
assign core

**Comment by smuzaffar** [comment]
+core
fixed by #15767
