### ISSUE TITLE
unrunnable configuration after dumpPython with sequence containing empty sequence

### ISSUE THREAD

**Issue by slava77** [cms-sw/cmssw#15786]
```
> I frequently see problems processing configuration with empty sequences
>
> E.g.
>
> seqIncludesMany = cms.Sequence(A)
>
> tempSeq = cms.Sequence()
> #{many other calls which may change tempSeq
> seqIncludesMany+= tempSeq
>
> If the tempSeq is never changed,
> after process.dumpPython it will result " (A+)"
> This can not run.
>
> A config pre-dumpPython runs.
>
> Should this be fixed in FWCore in PSet or should we use a different
> coding pattern?
```

Seems to me we should fix it. Could you make an issue?

A simple test is

```
>>> import FWCore.ParameterSet.Config as cms
>>> s = cms.Sequence()
>>> a = cms.EDProducer("A")
>>> s2 = cms.Sequence(a)
>>> s2 += s
>>> process = cms.Process("DUMP")
>>> process.a = a
>>> process.s2 = s2
>>> process.dumpPython()
```

original ref
https://hypernews.cern.ch/HyperNews/CMS/get/edmFramework/3675/1.html

**Comment by slava77** [comment]
80X is already affected by this and will prevent switching T0 to run on the most recent 80X.
If the time scale for the fix in framework is significant, I can apply a fix to one specific case that has a problem.

**Comment by Dr15Jones** [comment]
assign core

**Comment by Dr15Jones** [comment]
@wddgit

**Comment by slava77** [comment]
... actually, I'm not 100% sure about the effect on T0.

The locally generated T0 data processing test configs have a problem ("recoinator" script calls .dumpPython).

I'm not sure what happens in the guts of WMAgent which generates the actual T0 configs (CMSSW passes python cms.Process object to the external code) to make the .pkl files.
Quite likely it's the same mechanism though.

**Comment by wddgit** [comment]
@Dr15Jones Which releases should I submit a pull request to?  Do we have pull request from 8_0_X automatically also submitted to 8_1_X?

**Comment by Dr15Jones** [comment]
Do both 8_1_X and 8_0_X and in the 8_0_X say it is a back port.

**Comment by wddgit** [comment]
#15791 and #15790 should fix this. I only tested this within the Core code though. @slava77 let us know if this does not fix the actual problem case.

**Comment by slava77** [comment]
@wddgit 
it looks like your fix addressed the empty sequence issue.

... I will need to open another issue though, it looks like we have another case of "nothing" creating problems.

**Comment by slava77** [comment]
the issue for the problem in 81X, next in row after the "++" problem is fixed is
https://github.com/cms-sw/cmssw/issues/15792

**Comment by wddgit** [comment]
OK. Good. Recommend we close this issue. I will read 15792 now. (PRs #15791 and #15790)

**Comment by slava77** [comment]
closing as resolved
