### ISSUE TITLE
Inconsistency between RECO and ALCA paths for workflow 25.0

### ISSUE THREAD

**Issue by Dr15Jones** [cms-sw/cmssw#15806]
The improved algorithm for finding inconsistent module/Path dependency found the following problem in step3 of workflow 25.0
```
ecalDigis after alcaElectronTracksReducer [path pathALCARECOEcalUncalWElectron], alcaElectronTracksReducer consumes generalTracks, generalTracks consumes preDuplicateMergingGeneralTracks, preDuplicateMergingGeneralTracks consumes earlyGeneralTracks, earlyGeneralTracks consumes initialStepTracks, initialStepTracks consumes offlineBeamSpot, offlineBeamSpot after castorreco [path reconstruction_step], castorreco after zdcreco [path reconstruction_step], zdcreco after horeco [path reconstruction_step], horeco after hfreco [path reconstruction_step], hfreco after hbheprereco [path reconstruction_step], hbheprereco after ecalPreshowerRecHit [path reconstruction_step], ecalPreshowerRecHit after ecalTPSkim [path reconstruction_step], ecalTPSkim consumes ecalDigis
```

Ultimately the problem is the ALCA path `pathALCARECOEcalUncalWElectron` includes `ecalDigis` and the path `reconstruction_step` (the loop then comes back around `alcaElectronTracksReducer` on path `pathALCARECOEcalUncalWElectron` needs `generalTracks` which come from `reconstruction_step`). 

Now in practice, this workflow functions because the path `raw2digi_step` also has `ecalDigis`.  However, if just `reconstruction_step` and `pathALCARECOEcalUncalWElectron` were run in a job then the upcoming changes to the threaded framework would have a problem (which the new inconsistency finding algorithm would catch).

So two questions
1. why are modules from the `raw2digi_step` included in `pathALCARECOEcalUncalWElectron` and can they be removed?
2. If "no" is the answer to 1., then is it safe to reorder the items in the `pathALCARECOEcalUncalWElectron` so they could be consistent with actual dependency order in `reconstruction_step`?

**Comment by Dr15Jones** [comment]
assign alca

**Comment by Dr15Jones** [comment]
assign reconstruction

**Comment by Dr15Jones** [comment]
assign core

**Comment by mmusich** [comment]
@shervin86

**Comment by slava77** [comment]
On 9/10/16 8:12 AM, Chris Jones wrote:
> The improved algorithm for finding inconsistent module/Path dependency
> found the following problem in step3 of workflow 25.0
> 
> |ecalDigis after alcaElectronTracksReducer [path
> pathALCARECOEcalUncalWElectron], alcaElectronTracksReducer consumes
> generalTracks, generalTracks consumes preDuplicateMergingGeneralTracks,
> preDuplicateMergingGeneralTracks consumes earlyGeneralTracks,
> earlyGeneralTracks consumes initialStepTracks, initialStepTracks
> consumes offlineBeamSpot, offlineBeamSpot after castorreco [path
> reconstruction_step], castorreco after zdcreco [path
> reconstruction_step], zdcreco after horeco [path reconstruction_step],
> horeco after hfreco [path reconstruction_step], hfreco after hbheprereco
> [path reconstruction_step], hbheprereco after ecalPreshowerRecHit [path
> reconstruction_step], ecalPreshowerRecHit after ecalTPSkim [path
> reconstruction_step], ecalTPSkim consumes ecalDigis |
> 
> Ultimately the problem is the ALCA path |pathALCARECOEcalUncalWElectron|
> includes |ecalDigis| and the path |reconstruction_step| (the loop then
> comes back around |alcaElectronTracksReducer| on path
> |pathALCARECOEcalUncalWElectron| needs |generalTracks| which come from
> |reconstruction_step|).
> 
> Now in practice, this workflow functions because the path
> |raw2digi_step| also has |ecalDigis|. However, if just
> |reconstruction_step| and |pathALCARECOEcalUncalWElectron| were run in a
> job then the upcoming changes to the threaded framework would have a
> problem (which the new inconsistency finding algorithm would catch).
> 
> So two questions
> 1. why are modules from the |raw2digi_step| included in
> |pathALCARECOEcalUncalWElectron| and can they be removed?
> 2. If "no" is the answer to 1., then is it safe to reorder the items in
> the |pathALCARECOEcalUncalWElectron| so they could be consistent with
> actual dependency order in |reconstruction_step|?
> 

I think some ALCA paths are prepared to be able to run independently
with RAW inputs.
So, naturally, each of this kind will have a raw2digi on the path.
This behavior should be preserved if you reorder modules in pathALCA.

reco workflows are built from "steps" of the cmsDriver/ConfigBuilder
and they are each implemented as a cms.Path.
However, they are not independent and every following "step" of
cmsDriver/ConfigBuilder
is expected to have the earlier one to run before it.
So, reconstruction_step=cms.Path needs products from raw2digi_step=cms.Path
The ordering is handled by cms.Schedule

I guess, technically, it's the raw2digi and reco that are not
self-consistent.

**Comment by Dr15Jones** [comment]
But the way pathALCA is made one could not efficiently run it on a file already containing the digis since the path design forces rerunning of that digi.
Seems to me like one should have two different ALCA paths, standalone ones and ones meant to be used with other steps.

**Comment by Dr15Jones** [comment]
Yes, I agree that the real underlying problem is raw2digi and reco are not self-contained paths.

**Comment by Dr15Jones** [comment]
fixed by #15806

**Comment by slava77** [comment]
@Dr15Jones your "fixed by" message is circular

**Comment by Dr15Jones** [comment]
+1

**Comment by mmusich** [comment]
+1 
fixed via: https://github.com/cms-sw/cmssw/pull/15808
