### ISSUE TITLE
Invalid tool in latest IB?

### ISSUE THREAD

**Issue by kpedro88** [cms-sw/cmssw#15816]
When I call `scram b` in `CMSSW_8_1_X_2016-09-12-1100`, I get a warning:
```
****WARNING: Invalid tool madgraph5amcatnlo. Please fix herwigpp file.
```

Just wanted to make sure it wasn't overlooked.

@davidlange6 @smuzaffar

**Comment by smuzaffar** [comment]
assign externals

**Comment by smuzaffar** [comment]
https://github.com/cms-sw/cmsdist/commit/f238d1ea7384465851fecd0409c5352cedfa197d should fix it for next IB

**Comment by kpedro88** [comment]
@smuzaffar I no longer see the warning in `CMSSW_8_1_X_2016-09-12-2300`, thanks.
