### ISSUE TITLE
packages / subsystems to watch

### ISSUE THREAD

**Issue by gouskos** [cms-sw/cmssw#15822]
DataFormats/RecoCandidate
DataFormats/PatCandidates
DataFormats/METReco
RecoMET
JetMETCorrections
/PhysicsTools/PatAlgos/
/PhysicsTools/PatUtils/

**Comment by smuzaffar** [comment]
done here https://github.com/cms-sw/cms-bot/pull/745

**Comment by smuzaffar** [comment]
assign externals

**Comment by smuzaffar** [comment]
+1
