### ISSUE TITLE
WatchList for L1 Track Trigger related packages

### ISSUE THREAD

**Issue by sviret** [cms-sw/cmssw#15929]
Hi,

I would like to be in the watchlist for the following packages:

DataFormats/L1TrackTrigger
L1Trigger/TrackTrigger
L1Trigger/TrackFindingAM
SLHCUpgradeSimulations/Configuration

Thanks
Seb

**Comment by boudoul** [comment]
Hello - Can this issue be considered ? Thanks

**Comment by davidlange6** [comment]
assign core

**Comment by davidlange6** [comment]
@iahmad-khan
