### ISSUE TITLE
Needs for CMSSW_8_0_21 (MC DIGI-RECO release)

### ISSUE THREAD

**Issue by davidlange6** [cms-sw/cmssw#15931]
My plans for 8_0_21 are below - please comment here for other pieces are needed for MC prod

CMSSW_8_0_X (as of 2016-09-21-1100) plus

#15360 (merged 2016-09-22-2300)
#15381 (merged 2016-09-22-2300)
#15556  (implies new processing era due to alca data format change)
#15637 (merged 2016-09-21-2300)
#15685 (merged 2016-09-22-2300)
#15689  (needs updating)
#15701 (merged 2016-09-21-2300)
#15776 (needs 81x relvals)
#15829 (merged 2016-09-22-2300)
#15836 (merged 2016-09-21-2300)
#15873 (merged 2016-09-22-2300)
#15881 (merged 2016-09-21-2300)
#15892 (merged 2016-09-21-2300)

**Comment by Martin-Grunewald** [comment]
Needed by TSG as soon as possible:
#15836 
#15904 
#15923 
(also all backports from 81X)

**Comment by davidlange6** [comment]
#15512 
#15530 
were requested in the ORP last week.

**Comment by civanch** [comment]
#15960 would be useful
