### ISSUE TITLE
TrackClusterRemover is not multi-thread per Event safe

### ISSUE THREAD

**Issue by Dr15Jones** [cms-sw/cmssw#15961]
CMSSW_8_1_DEVEL_X_2016-09-20-2300 contains the implementation which allows the framework to run Paths in parallel within an Event. In addition, these changes allowed all EDProducers on Paths to be moved off when switching to unscheduled (since the framework properly handles dependencies between scheduled and unscheduled modules).

In the IB RelVals we are getting many failures from the assert:

```
cmsRun: /build/cmsbld/jenkins-workarea/workspace/build-any-ib/w/slc6_amd64_gcc530/cms/cmssw/CMSSW_8_1_DEVEL_X_2016-09-20-2300/src/DataFormats/Common/interface/ContainerMask.h:76: edm::ContainerMask<T>::ContainerMask(const edm::RefProd<PROD>&, const std::vector<bool>&) [with T = edmNew::DetSetVector<SiStripCluster>]: Assertion `iMask.size() == ContainerMaskTraits<T>::size(m_prod.product())' failed.
```

Running this in the debugger I find

```
#3  0x0000003feec2b7d0 in __assert_fail () from /lib64/libc.so.6
#4  0x00007fff98d007b7 in edm::ContainerMask<edmNew::DetSetVector<SiStripCluster> >::ContainerMask(edm::RefProd<edmNew::DetSetVector<SiStripCluster> > const&, std::vector<bool, std::allocator<bool> > const&) ()
   from /cvmfs/cms-ib.cern.ch/week1/slc6_amd64_gcc530/cms/cmssw-patch/CMSSW_8_1_DEVEL_X_2016-09-21-2300/lib/slc6_amd64_gcc530/pluginRecoLocalTrackerSubCollectionProducers.so
#5  0x00007fff98d3990e in (anonymous namespace)::TrackClusterRemover::produce(edm::StreamID, edm::Event&, edm::EventSetup const&) const ()
   from /cvmfs/cms-ib.cern.ch/week1/slc6_amd64_gcc530/cms/cmssw-patch/CMSSW_8_1_DEVEL_X_2016-09-21-2300/lib/slc6_amd64_gcc530/pluginRecoLocalTrackerSubCollectionProducers.so
#6  0x00007ffff7d4a7b9 in edm::global::EDProducerBase::doEvent(edm::EventPrincipal const&, edm::EventSetup const&, edm::ActivityRegistry*, edm::ModuleCallingContext const*) ()
   from /cvmfs/cms-ib.cern.ch/week1/slc6_amd64_gcc530/cms/cmssw-patch/CMSSW_8_1_DEVEL_X_2016-09-21-2300/lib/slc6_amd64_gcc530/libFWCoreFramework.so
#7  0x00007ffff7cbd342 in edm::WorkerT<edm::global::EDProducerBase>::implDo(edm::EventPrincipal const&, edm::EventSetup const&, edm::ModuleCallingContext const*) ()
   from /cvmfs/cms-ib.cern.ch/week1/slc6_amd64_gcc530/cms/cmssw-patch/CMSSW_8_1_DEVEL_X_2016-09-21-2300/lib/slc6_amd64_gcc530/libFWCoreFramework.so
```

The relevant pieces of code are

```
https://github.com/cms-sw/cmssw/blob/b6c342230bc53b972850a57ef60a321514a259f7/RecoLocalTracker/SubCollectionProducers/src/TrackClusterRemover.cc#L141
```

and

```
https://github.com/cms-sw/cmssw/blob/b6c342230bc53b972850a57ef60a321514a259f7/RecoLocalTracker/SubCollectionProducers/src/TrackClusterRemover.cc#L204
```

The value of `dataSize` can change as one runs because of `LazyGetter` within the `edmNew::DetSetVector`. So the failure happens because another module has updated the internal cache of `edmNew::DetSetVector` while `TrackClusterRemover` was running. 

I think the problem is `edm::ContainerMask` assumes the container it is masking has a fixed value for `ContainerMaskTraits<T>::size(m_prod.product())` which for `edmNew::DetSetVector` is `dataSize()` which changes over time. However, the change is always to extend so it would be OK to relax the check to be `iMask.size() <= ContainerMaskTraits<T>::size(m_prod.product())` and then in the call to `ContainerMask::mask` if the index passed is greater than or equal to `m_max.size()` it just returns `false` (i.e. not maksed out).

**Comment by Dr15Jones** [comment]
assign reconstruction

**Comment by Dr15Jones** [comment]
assign core

**Comment by slava77** [comment]
@rovere @VinInn 
please comment if the solution is OK from your point of view

**Comment by Dr15Jones** [comment]
I tested the change in my own area and it does solve the problem.

**Comment by Dr15Jones** [comment]
See #15964

**Comment by Dr15Jones** [comment]
+1

**Comment by slava77** [comment]
@Dr15Jones 
should this be closed now?
the fix is in the release since a while now 
https://github.com/cms-sw/cmssw/commit/f39e5882df8aef401d13423933265580bd0dcbc2

**Comment by Dr15Jones** [comment]
@slava77 I think we were just waiting for a reconstruction approval.

**Comment by slava77** [comment]
+1

it's apparently fixed
