### ISSUE TITLE
LHE run info merging problems

### ISSUE THREAD

**Issue by slava77** [cms-sw/cmssw#15999]
See details in
https://hypernews.cern.ch/HyperNews/CMS/get/prep-ops/3234/1/1/1/1/1/1/1/2/1/1/1.html

it looks like 

``` LHERunInfoProduct_externalLHEProducer__LHE```
wouldn't merge after the output size runs over 2GB.
The job memory doesn't blow up too much, but the output process hangs in 100% CPU
```

**Comment by slava77** [comment]
@Dr15Jones @perrozzi @efeyazgan 
I can't recall now if this was resolved.
Is it still worth to keep the issue open?

**Comment by perrozzi** [comment]
should be solved by these pr
https://github.com/cms-sw/cmssw/pulls?utf8=%E2%9C%93&q=is%3Apr+is%3Aclosed+perrozzi+lheruninfoproduct+

**Comment by smuzaffar** [comment]
looks like this has been fixed by https://github.com/cms-sw/cmssw/pulls?utf8=%E2%9C%93&q=is%3Apr+is%3Aclosed+perrozzi+lheruninfoproduct+ PRs
