### ISSUE TITLE
Feature: Have Paths put PathResults object into the Event

### ISSUE THREAD

**Issue by Dr15Jones** [cms-sw/cmssw#16003]
When a Path finishes, we should put a PathResults object into the Event where the label matches the Path's name. This could be used to
- have a Path start after another Path has ended
- make the generation of TriggerResults more natural (the module that makes TriggerResults just waits for all PathResults to be created)
- allow OutputModules to only waitfor the Paths they are interested in to finish rather than having to wait for TriggerResults in order to start prefetching.

**Comment by Dr15Jones** [comment]
assign core

**Comment by wddgit** [comment]
PR #19052 should resolve this issue and I think it can be closed.

**Comment by Dr15Jones** [comment]
+1
