### ISSUE TITLE
TriggerSummaryProducerAOD reads too much when run in fastsim?

### ISSUE THREAD

**Issue by Dr15Jones** [cms-sw/cmssw#16015]
When running step1 of workflow 135.1 I found that the module type `TriggerSummaryProducerAOD` with label `hltTriggerSummaryAOD` requests data from 2626 different modules, some of which are on EndPaths. The dependence on modules in EndPaths leads to an unrunnable schedule for the new changes to the threaded framework.

The `TriggerSummaryProducerAOD` is doing the equivalent of a `getMany` which appears to be requesting data products it does not really want.

**Comment by Dr15Jones** [comment]
assign hlt

**Comment by Dr15Jones** [comment]
The full list of dependencies is can be found at https://www.dropbox.com/s/kzibz32hk81g49n/AODTrigSumReads.log?dl=0

**Comment by Dr15Jones** [comment]
Some of the items (not sure if it is all) being requested from EndPaths are
```
    CorrectedPFMETProducer/'pfMetT0pc'
    CorrectedPFMETProducer/'PfMetT1'
    CorrectedPFMETProducer/'PfMetT0pcT1'
```
which comes from the EndPath `validation_step`.

**Comment by Dr15Jones** [comment]
I believe the problem is `TriggerSummaryProducerAOD` assumes it is being in a process that only contains the HLT step, and not one that has other steps included. The configuration is
```
>>> process.hltTriggerSummaryAOD
cms.EDProducer("TriggerSummaryProducerAOD",
    processName = cms.string('@')
)
```
Which is saying use the process name of this process. Therefore it tries to get all the data products for the types it knows which are made in this process. But what it really wants to do is to only get the data products associated to the HLT step. From inspection it looks like all HLT related modules have labels with the prefix _hlt_ . If that is true, we could change `TriggerSummaryProducerAOD` to only get data products which have the proper process name AND come from modules whose label's begin with `hlt`.

**Comment by Martin-Grunewald** [comment]
@Dr15Jones 

Indeed, ```TriggerSummaryProducerAOD``` and its friend ```TriggerSummaryProducerRAW``` are only interested in ```HLT``` products and those module producer labels start with ```hlt``.
Unfortunately, the HLT step does not always run with process name ```HLT```, and some 
configs (HLT DQM or HLT validation?) outside HLT also configure module labels starting with ```hlt```.

**Comment by Dr15Jones** [comment]
This is addressed by #16043

**Comment by fwyzard** [comment]
Hi Chris,
as a more permanent fix, I would suggest something like
  - we add a parameter called `input` or `modulesToRead` or whatever, of type `vstring` or `VInputTag` ;
  - we set the default to `"hlt*"` ;
  - we modify your new code to look for modules that match by glob pattern any of the expressions in the new parameter, and read only those.

In this way we should achieve the same result, but we keep the flexibility to pick up also modules that do not follow the same naming convention, for example in a customise() call.

**Comment by Dr15Jones** [comment]
The pull request has been brought back in #16046

**Comment by Dr15Jones** [comment]
I changed the implementation to allow two different patterns to be used

1. a list of patterns for which a module label must match at least one of
1. a list of patterns which will reject a module label 

rejection trumps matching.

This way we get Andrea's request for patterns to match and still deal with Martin's concern that some non HLT modules begin with 'hlt' for their labels. That allows the match to be "hlt*" and the rejection to be "hltSomethingWeDoNotWant".

**Comment by Dr15Jones** [comment]
#16046 was merged and solved the problem.
