### ISSUE TITLE
HLT paths need to be updated to handle concurrently running paths

### ISSUE THREAD

**Issue by Dr15Jones** [cms-sw/cmssw#16063]
The CMSSW workflows involving the HLT require that some paths preceed other paths in the processing order. The two explicit cases are 'HLTriggerFirstPath' and 'HLTriggerFinalPath'.  However, now that we are moving to having paths run concurrently in the threaded framework, the implicit ordering no longer holds.

However, when running paths concurrently, the framework will honor data dependencies between paths and properly schedule modules to only run once their data products (which could be coming from another path) are available. Therefore one can use data dependencies between modules to enforce Path processing order. It is also likely that the reason for the path processing order was because of data dependencies (i.e. the TriggerSummary\* modules) and now the framework automatically will enforce the needed ordering.

**Comment by Dr15Jones** [comment]
assign hlt

**Comment by Dr15Jones** [comment]
assign core

**Comment by Dr15Jones** [comment]
The `HLTriggerFirstPath` is defined as the following:
```
modules on path HLTriggerFirstPath:
  generator
  hltGtStage2Digis
  hltCaloStage2Digis
  hltGmtStage2Digis
  hltGtStage2ObjectMap
  hltDummyConditions
  hltGetRaw
  hltBoolFalse
```
The first 5 modules are actually common to all HLT paths so can be ignored. The `hltDummyConditions` is
```
process.hltDummyConditions = cms.EDFilter( "HLTBool", result = cms.bool( True ) )
```
which appears to be there only to replace `hltGetConditions` from the actual HLT menu. I believe that module only does work on Run and Lumi boundaries anyway so when it is run during event processing shouldn't matter.

`hltGetRaw` is an `HLTGetRaw` EDAnalyzer which does as its name implies, forces the reading of the raw data from the source. I believe this is done so that timing measurements do not penalize the first module which reads the data as being slow. Unfortunately, this mechanism will no longer do what is intended with concurrent path processing. There are two ways I see to achieve the same goal
 1. The service system now explicitly is told that we are temporarily leaving a module and are calling the source to retrieve data. If the timing measurements we make per module use that information then the module would not appear to run slower becuase of the data request. This would do away with the need for the `hltGetRaw` module all together.
 1. We could replace the `hltGetRaw` module with an EDProducer named `rawDataCollector` which would read `rawDataCollector` using the `skipCurrentProcess` mechanism and then copy the data into a new `RawDataCollection`. All further modules would then just read the copied data. This would guarantee that the timing for reading from the source would only be accounted for in `rawDataCollector`.

**Comment by Dr15Jones** [comment]
For the `hltGetRaw` I had completely forgotten that the `RawDataCollection` is already being prefetched from the source so the time for the read is now never 'charged' to any specific module. Therefore I believe there is no longer a need for `hltGetRaw` .

**Comment by fwyzard** [comment]
hi Chris,
is the latter true also when using the DAQ source to read .frd files ?

.Andrea

**Comment by Dr15Jones** [comment]
Prefetching happens regardless of the type of source. Does the DAQ source even implement the DelayedReader? If it doesn't, then even without prefetching the DAQ source would always have gotten the data before a module was run.

**Comment by fwyzard** [comment]
OK, thanks. We'll check the impact on the HLT timing both online and
offline, and remove it if there is no difference.

Ciao,
.Andrea

**Comment by Dr15Jones** [comment]
Let me know if there was a difference since it is supposed to work as I described it :).

**Comment by Martin-Grunewald** [comment]
@Dr15Jones 
In any case I wonder because some product may not be produced because it is in a path which bails out on a filter before the producer module in question. Then the summary should NOT pack this up, ie, should NOT somehow (re)request running the corresponding producer.
The summary modules should really run last!

**Comment by Dr15Jones** [comment]
@Martin-Grunewald the framework properly handles this case. Modules waiting for data are signaled when
 1 the module which produces the data has finished running or
 1 all paths have skipped the module producing the data

for the latter case, when the data is requested from the Event one will get an invalid Handle just like before.

**Comment by makortel** [comment]
Is this issue still relevant?

**Comment by fwyzard** [comment]
Re-reading the discussion and description, I think not.

**Comment by makortel** [comment]
+1

Thanks for checking!
