### ISSUE TITLE
Improve unit test coverage for multiple threads per event

### ISSUE THREAD

**Issue by Dr15Jones** [cms-sw/cmssw#16123]
Need to extend the testing to have a much more complete coverage of the ability to have concurrent modules processing the same event.

**Comment by Dr15Jones** [comment]
assign core

**Comment by Dr15Jones** [comment]
FWCore/Framework/test/Event_t.cpp should test concurrent calls to Event methods.

**Comment by Dr15Jones** [comment]
The test in FWCore/Framework/test which checks early delete from event should be extended to test using multiple threads per event.

**Comment by Dr15Jones** [comment]
SubProcesses should be tested with multiple threads

**Comment by Dr15Jones** [comment]
Need to test unscheduled processing

**Comment by Dr15Jones** [comment]
Need to test path dependency (including early path termination).

**Comment by smuzaffar** [comment]
@Dr15Jones , can we close this issue now?

**Comment by Dr15Jones** [comment]
Given our experience, yes.

**Comment by Dr15Jones** [comment]
+1
