### ISSUE TITLE
Check TrajectoryMeasurement for thread-safety problems

### ISSUE THREAD

**Issue by Dr15Jones** [cms-sw/cmssw#16166]
The class TrajectoryMeasurement
http://cmslxr.fnal.gov/source/TrackingTools/PatternTools/interface/TrajectoryMeasurement.h

uses a mutable `theLayer` and contains member data of type `TrajectoryStateOnSurface`
http://cmslxr.fnal.gov/source/TrackingTools/TrajectoryState/interface/TrajectoryStateOnSurface.h#0017

which inherits from `ProxyBase11`
http://cmslxr.fnal.gov/source/TrackingTools/TrajectoryState/interface/ProxyBase11.h

which is basically a wrapper around the `shared_ptr` of `BasicTrajectoryState` which is full of mutables
http://cmslxr.fnal.gov/source/TrackingTools/TrajectoryState/interface/BasicTrajectoryState.h#0320

This came up because we are seeing a crash in `DeDxEstimatorProducer` which is using a `edm::Ref<TrajectoryMeasurement>` .

**Comment by Dr15Jones** [comment]
assign reconstruction

**Comment by Dr15Jones** [comment]
assign core

**Comment by Dr15Jones** [comment]
@gartung this did not show up in the static analyzer

**Comment by slava77** [comment]
@VinInn @rovere 
please take a look and comment
Thank you.

**Comment by gartung** [comment]
@Dr15Jones I have to check but I think the data class names bloom filter has not been updated in a long time and this class may not be in it.

**Comment by VinInn** [comment]
TrajectoryMeasurement is a time critical class used in pattern recognition and fitting.
It cannot be made persistent.
DeDxEstimatorProducer is a low priority producer.
Besides that using a edmRef to access a "TrajectoryMeasurement" is a huge overkill (as a simple pointer is enough), I think that the implementation of the DeDxEstimator need to be reviewed 
as I suspect more a violation of edm rules (modification of an object in the event...)

**Comment by VinInn** [comment]
I am afraid this is a more generalized problem affecting clients of TrajectoryStateOnSurface stored in the event. For various (good) reasons a "TrajectoryStateOnSurface" may endup in the event not fully filled. If concurrent clients request any of the "not-filled" components a race may occur.
Protecting from races TrajectoryStateOnSurface may imply serious overhead in time-critical part of tracking. The alternative is to clone TSOS in clients using  unsharedData()  ... 
(or to fully reimplement tracking and all TSOS clients separating concerns)

**Comment by Dr15Jones** [comment]
Unfortunately, this is a very big problem since we already have the capability in CMSSW_8_1 of using multiple threads for one Event. That means we already have the potential for the race condition.

**Comment by VinInn** [comment]
for a test you can add a "mutex" and protect check...() and create() methods in
TrackingTools/TrajectoryState/src/BasicTrajectoryState.cc
pre-empting is not an option (creating errors has a huge impact, and often there is no need)

**Comment by Dr15Jones** [comment]
It would be really useful if someone could create a configuration which would easily show a performance problem if the classes in question are changed. That would allow me to try different solutions and give measurements on the effect.

**Comment by VinInn** [comment]
The config is TrackerOnly  @makortel can instruct you how to generate it for our usual ttbar workflow
or just copy
/afs/cern.ch/work/i/innocent/public/data/tkDQM.py
and input data
JetHT_Run279685_raw.root

we can try to "preempt' only the trajectory stored in the event (Tracking does not use those!)
let's find all producers of "vector<Trajectory>" (most probably just TrackProducer) and make sure all check() and create are called!
here
http://cmslxr.fnal.gov/dxr/CMSSW_8_0_5/source/RecoTracker/TrackProducer/src/KfTrackProducerBase.cc#52
take .back() iterate over the TrajectoryMeasurements and "fill" the three states

**Comment by Dr15Jones** [comment]
If we force the updates before sending the data out, does it then make sense to make the methods non-const and the data non-mutable?

**Comment by VinInn** [comment]
The main use of TSOS is internal to tracking and propagation where it make much sense to avoid unnecessary computations...
It is stored in the event for DQM and few other consumers (some could just migrate to reco::Track)
In my mind most of those usage is mainly historical and often wha needed is just a couple of parameters (such as trajState.localDirection(); or  trajState.localMomentum().mag() (sic) )
I much more in favor to remove any TSOS from the event than change TSOS at this point in time...

**Comment by makortel** [comment]
> The config is TrackerOnly @makortel can instruct you how to generate it for our usual ttbar workflow

For 2016: step3 of `runTheMatrix.py -l 1325.1` (or `10024.1` for 2017). It is just standard reconstruction up to tracking (and limited/special DQM+VALIDATION).

**Comment by VinInn** [comment]
I instrumented the TSOS and, as expected, it is not modified in the DeDxEstimatorProducer
so the problem is elsewhere  (accessing the event?, copying a shared_ptr?, hardware issue?)

**Comment by Dr15Jones** [comment]
@VinInn thanks for doing a more detailed check.

**Comment by Dr15Jones** [comment]
#16229 is related to this issue.

**Comment by VinInn** [comment]
#17098 should remove the symptoms ....

**Comment by Dr15Jones** [comment]
+1

**Comment by Dr15Jones** [comment]
@cvuosalo,@slava77 ping.
I'm assuming this change was satisfactory for this issue.
