### ISSUE TITLE
collection of PRs for a possible re-miniAOD of 2016 data in 80X after 23Sept2016 (used in 03Feb2017 re-miniAOD)

### ISSUE THREAD

**Issue by slava77** [cms-sw/cmssw#16177]
issue to keep track of PRs that change miniAOD event content and aiming for a potential re-miniAOD in 80X of 2016 data and MC. There remains a possibility for the legacy rereco. The time scale is around March 2017.

### Included in data re-miniAOD (03Feb2017) CMSSW_8_0_26_patch1
- #17296 [signed]  ECAL / EGM: Remake ECAL cluster using modified rechits. Remake superclusters. Update electron/photon objects. Update PAT objects.
    - configuration switch is needed to enable  (enabling by default affects data and MC)
- #17308 [under review] Muon+JetMET part of the re-miniAOD fix 
    - configuration switch is needed to enable (enabling by default affects data and MC)

### In case of full data and MC re-miniAOD
- https://github.com/cms-sw/cmssw/pull/16174 "Fix for Puppi MET and MET significance compatibility between AOD and miniAOD"

### In case of data only re-miniAOD (after 03Feb2017)
- #17282 [signed] CTPPS: miniAOD 
    - changes default behavior, but applies only to data

**Comment by ferencek** [comment]
Inclusion of v4 training for the double b tagger for AK8 jets (for CA15 jets staying with v3 training for now). PR does not yet exist but there exists an 80X recipe that can easily be turned into a PR. However, before making a PR will need to propagate the new training file to externals.

**Comment by rafaellopesdesa** [comment]
Related to the mitigation of the ECAL gain switch problem:

   * #17296 - ECAL / EGM: Remake ECAL cluster using modified rechits. Remake superclusters. Update electron/photon objects. Update PAT objects.

**Comment by slava77** [comment]
@ferencek regarding https://github.com/cms-sw/cmssw/issues/16177#issuecomment-273555446
changing training from v3 to v4 will lead to changes in both data and MC.
The early Feb re-miniAOD is for data.
If a re-miniAOD of both data and MC happens before legacy rereco, this feature will be considered

**Comment by ferencek** [comment]
@slava77, ok, so for now I will then postpone backporting https://github.com/cms-sw/cmssw/pull/17294 until we know what the situation will be with the re-miniAOD of both data and MC.

**Comment by slava77** [comment]
I have updated the PR description with a note on 03Feb2017 re-miniAOD and for now intend to keep the issue open to preserve tracking of other requests that didn't make it to 03Feb2017.
https://cms-pdmv.cern.ch/pmp/historical?r=03Feb2017

**Comment by slava77** [comment]
Moving to https://github.com/cms-sw/cmssw/issues/17603
