### ISSUE TITLE
Limit the number of staging requests from CMSSW

### ISSUE THREAD

**Issue by bbockelm** [cms-sw/cmssw#16356]
We have a reasonable-looking optimization where CMSSW will issue an asynchronous staging request to the storage system that it will access a file relatively soon:

https://github.com/cms-sw/cmssw/blob/CMSSW_8_1_X/Utilities/XrdAdaptor/plugins/XrdStorageMaker.cc#L79

Since CMS sites should no longer have jobs running against the HSM, this mostly serves as a hint to systems like Xrootd (which may have to spend some effort to locate a file - it's best if the redirector can do this asynchronously instead of stalling CMSSW).

An intrepid CRAB3 user was able to generate a few tens of thousands of jobs, each of which had nearly 100,000 files listed for the PoolSource.  If all jobs succeeded, that would have resulted in billions of staging requests.

CMSSW should silently cut off the stage in requests after some reasonable limit (perhaps 30 input files)?

**Comment by Dr15Jones** [comment]
assign core

**Comment by bbockelm** [comment]
@Dr15Jones - could you assign this one to me?  I don't have necessary permissions in GH...

**Comment by Dr15Jones** [comment]
@bbockelm I don't have the rights to assign.
@davidlange6 @smuzaffar can either of you assign this issue?

**Comment by smuzaffar** [comment]
is this still an open issue ?

**Comment by bbockelm** [comment]
No -- I believe this was fixed long ago.
