### ISSUE TITLE
edmPickEvents.py does not use proxy certificate for DAS

### ISSUE THREAD

**Issue by davidlt** [cms-sw/cmssw#16383]
We recently got a complaint that `edmPickEvents.py` doesn't work in CMSSW_8_0_22 (latest build) even if you did `voms-proxy-init --rfc --voms cms` before.

DAS CLI will check for certificates and CA bundle paths, but sadly this doesn't happen if one uses as API. One needs to set `ckey`, `cert` and `capath` into `das_client.get_data(..)` manually.

While looking at DAS seems that one can do `ckey=das_client.x509(), cert=das_client.x509()`

Thus:

```
diff --git a/PhysicsTools/Utilities/scripts/edmPickEvents.py b/PhysicsTools/Utilities/scripts/edmPickEvents.py
index 6771946..305a874 100755
--- a/PhysicsTools/Utilities/scripts/edmPickEvents.py
+++ b/PhysicsTools/Utilities/scripts/edmPickEvents.py
@@ -87,7 +87,7 @@ def getFileNames (event):
     files = []
     # Query DAS
     query = "file dataset=%(dataset)s run=%(run)i lumi=%(lumi)i | grep file.name" % event
-    jsondict = das_client.get_data('https://cmsweb.cern.ch', query, 0, 0, False)
+    jsondict = das_client.get_data('https://cmsweb.cern.ch', query, 0, 0, False, ckey=das_client.x509(), cert=das_client.x509())
     status = jsondict['status']
     if status != 'ok':
         print "DAS query status: %s"%(status)
```

Kinda works for me. I don't get anymore:

```
    <h2>Authorisation required</h2>
    <p>The site you requested is protected and requires you to authenticate</p><p><a href='/auth/trouble'>Diagnose certificate problems</a></p>
```

**Comment by davidlt** [comment]
Looks like this was fixed in CMSSW_8_1_X, but it a different way: https://github.com/cms-sw/cmssw/commit/a113d4ad022ebd6321d6452fb7b97adf815e4a3f#diff-02b86102c14143cf16a0ea33d43f9f8d

**Comment by smuzaffar** [comment]
this is fixed
