### ISSUE TITLE
MuonTrackingRegionBuilder::fillDescriptions() is confusing

### ISSUE THREAD

**Issue by makortel** [cms-sw/cmssw#16525]
While preparing #16202 that makes `TrackingRegionBuilder`s `EDProducers`, I noticed two issues with `MuonTrackingRegionBuilder::fillDescriptions()`:

1. Very likely the function is not called by any `EDModule` and hence not by the framework. The function is called by `L3MuonTrajectoryBuilder::fillDescriptions()`, which itself is not called by anybody.
2. The way the parameter description is filled is confusing. The function adds two `PSet`s, "MuonTrackingRegionBuilder" and "hltMuonTrackingRegionBuilder" to the argument `PSet`.
     * According to @slava77 (https://github.com/cms-sw/cmssw/pull/16202/files#r87031837), the intention was to make two `PSet`s, one with defaults for offline and another for online. 
     * Currently `fillDescriptions()` does not support generating standalone `PSet`s (AFAIK)
     * To be able to generate two separate configurations, `fillDescriptions()` would need to take `edm::ConfigurationDescriptions&` as an argument. But even then the `fillDescriptions()` would generate configurations for full `EDModule`(s).

@slava77 @HuguesBrun @BenjaminRS @fwyzard

**Comment by makortel** [comment]
If we proceed in the way of #16202, i.e. make `TrackingRegionBuilder`s `EDProducer`s, to me the most straightforward way to implement the intention would be

1. Add (e.g.) `MuonTrackingRegionBuilder::fillDescriptionsOffline(edm::ParameterSetDescription&)` and `MuonTrackingRegionBuilder::fillDescriptionsHLT(edm::ParameterSetDescription&)` which fill the offline or HLT `PSet`
2. Add `MuonTrackingRegionBuilder::fillDescriptions(edm::ConfigurationDescriptions&)`, which calls both variants above to generate configurations for two `EDProducer`s (one for offline and another for HLT)
3. `HIMuonTrackingRegionProducer::fillDescriptions(edm::ConfigurationDescriptions&)` calls `MuonTrackingRegionBuilder::fillDescriptionsOffline(edm::ParameterSetDescription&)` (which is called `fillDescriptions2()` in #16202 
4. Migrate all clients of `MuonTrackingRegionBuilder` to read the `TrackingRegion`s from `edm::Event`

I don't think there is much to do in practice for now (until #16202 and a subsequent PR migrating all HLT tracking use cases + a function in `customizeHLTforCMSSW.py` have been merged), except I could make the modifications of 1-3 already in #16202. Effectively I already took out the offline part to a separate function.

**Comment by BenjaminRS** [comment]
Hi @makortel thanks for the information, however I would need some time to review and look back at this code and understand the suggestions.
Thanks,
Benjamin

**Comment by fwyzard** [comment]
Hi Matti,
if you do 4. , does it still make sense to have 1. , or do we just rely on the standard `fillDescriptions` ?

**Comment by makortel** [comment]
@fwyzard The steps 1-3 are necessary for 4 (and can be done already now in #16202).

In #16202 I'm making the region-`EDProducer`s (they're actually instantiations of a template) such that they completely re-use the existing `TrackingRegionBuilder`s (actually the only way to support both "current" and "new" without copy-paste). The `EDProducer`'s (standard) `fillDescriptions` will call the `fillDescriptions` of the `TrackingRegionBuilder`.

**Comment by smuzaffar** [comment]
@makortel , have we already addressed this? do we need to keep this open?

**Comment by makortel** [comment]
assign reconstruction

**Comment by makortel** [comment]
> have we already addressed this? do we need to keep this open?

I was too quick in assigning reconstruction, by quick look it seems that the situation was improved in https://github.com/cms-sw/cmssw/pull/17925.
