### ISSUE TITLE
environment variable for SITECONF

### ISSUE THREAD

**Issue by smuzaffar** [cms-sw/cmssw#16557]
@Dr15Jones , @bbockelm 
Currently , SiteLocalConfigService searches for SITECONF in CMS_PATH
https://github.com/cms-sw/cmssw/blob/86088d61d757bad0e55addda14859c5ea6108d84/FWCore/Services/src/SiteLocalConfigService.cc#L110

And for IBs test, we are changing CMS_PATH to point to a different directory so that cmsRun can pick our SITECONF (instead of T2_CH_CERN)

Can we update it to first look for CMS_SITECONF_PATH (or something similar) env variable and if not set then fall back to CMS_PATH?

**Comment by smuzaffar** [comment]
assign core

**Comment by bbockelm** [comment]
What are the backward compatibility concerns of having new releases read from a different SITECONF than old releases?

**Comment by smuzaffar** [comment]
You are right, old releases will be getting SITECONF via CMS_PATH. I am assuming that no one should be setting the new CMS_SITECONF_PATH env and those who know it (e.g. cmssw IBs) can set it to override the default (of course this change needs to go in all release cycles 53X and above).

Another solution is to make use of CMS_LOCAL_SITE CVMFS variable so that all our VMs (where we run IBs tests) can set it to something different but then we can not use lxplus machines for running tests.

**Comment by smuzaffar** [comment]
If env variable (which I also do not like) , may be we can override the path via ParameterSet passed to this service https://github.com/cms-sw/cmssw/blob/86088d61d757bad0e55addda14859c5ea6108d84/FWCore/Services/src/SiteLocalConfigService.cc#L79

**Comment by Dr15Jones** [comment]
I'd much prefer passing something to the Service explicitly in the configuration.

**Comment by bbockelm** [comment]
Ah - sorry, I had assumed you already eliminated the ParameterSet method for some other reason.

If that's an option, I'd definitely recommend it!
