### ISSUE TITLE
Tune NHitCuts_byTrackAlgo[5] for HGCal

### ISSUE THREAD

**Issue by kpedro88** [cms-sw/cmssw#16914]
In #16797, it was found that the algo `reco::TrackBase::muonSeededStepInOut` was relying on an out-of-bounds value ~32700 for `PFTrackAlgoTools::nHitCut()` in the HGCal config. Using the supposedly-correct value of 3 resulted in losing most endcap muons. For now, the nonsense value 32700 has been set in the HGCal config, but it should be tuned to a more realistic value that gives the desired performance.

**Comment by davidlange6** [comment]
assign reconstruction

**Comment by kpedro88** [comment]
Yes, as far as I know. [RecoParticleFlow/PFTracking/python/hgcalTrackCollection_cfi.py](https://github.com/cms-sw/cmssw/blob/master/RecoParticleFlow/PFTracking/python/hgcalTrackCollection_cfi.py) has not been modified or tuned since this was posted.

**Comment by kpedro88** [comment]
@hatakeyamak can you add this to the list of things to check for PF?

**Comment by hatakeyamak** [comment]
OK. Will try with @bendavid

**Comment by kpedro88** [comment]
resolved by #31681
