### ISSUE TITLE
subscribing to package

### ISSUE THREAD

**Issue by fcouderc** [cms-sw/cmssw#17058]
Hi, 
I d like to subscribe to the following packages

CondFormats/EgammaObjects
CondFormats/EcalObjects
CondCore/EgammaPlugins

DataFormats/EgammaCandidates
DataFormats/EgammaReco
DataFormats/EgammaTrackReco
DataFormats/GsfTrackReco
DataFormats/RecoCandidate

EgammaAnalysis/ElectronTools
EgammaAnalysis/CSA07Skims
EgammaAnalysis/Configuration
EgammaAnalysis/ElectronIDESSources
EgammaAnalysis/PhotonIDProducers

RecoEcal/Configuration
RecoEcal/EgammaClusterAlgos
RecoEcal/EgammaClusterProducers
RecoEcal/EgammaCoreTools

RecoEgamma/Configuration
RecoEgamma/EgammaElectronAlgos
RecoEgamma/EgammaElectronProducers
RecoEgamma/EgammaHFProducers
RecoEgamma/EgammaIsolationAlgos
RecoEgamma/EgammaMCTools
RecoEgamma/EgammaPhotonAlgos
RecoEgamma/EgammaPhotonProducers
RecoEgamma/EgammaTools
RecoEgamma/ElectronIdentification
RecoEgamma/Examples
RecoEgamma/PhotonIdentification
RecoEgamma/EgammaHLTAlgos
RecoEgamma/EgammaHLTProducers

DQMOffline/EGamma
Validation/RecoEgamma

THanks

Fabrice

**Comment by smuzaffar** [comment]
@fcouderc, please make a PR with your changes for https://github.com/cms-sw/cms-bot/blob/master/watchers.yaml
