### ISSUE TITLE
Two copies of L1TMuonEndcapParamsRcd.h/cc with different captilizations

### ISSUE THREAD

**Issue by ericvaandering** [cms-sw/cmssw#17061]
The file L1TMuonEndcapParamsRcd.h and corresponding cc file exist in Endcap and EndCap varieties. 

I noticed this because when checking out on a Mac, git is not particularly happy with the situation. @Dr15Jones advised me to open an issue on this.

**Comment by Dr15Jones** [comment]
assign db

**Comment by Dr15Jones** [comment]
assign alca

**Comment by Dr15Jones** [comment]
assign l1

**Comment by Dr15Jones** [comment]
Having two files in the same directory whose names only differ based on capitalization is against CMS coding policy. [It causes problems when checking out code on macOS plus it is just confusing.]

**Comment by ericvaandering** [comment]
This is still out there....

**Comment by smuzaffar** [comment]
@ggovi , @pohsun, @tlampen, @tocheng, @christopheralanwest

The unused L1TMuonEndcapParamsRcd.h file was removed by https://github.com/cms-sw/cmssw/pull/23759 but that caused massive failure https://github.com/cms-sw/cmssw/issues/23873 . In https://github.com/cms-sw/cmssw/pull/23876 we reverted the change. Can you please check if this is still needed? Is it time to remove unused Endcap?

**Comment by christopheralanwest** [comment]
@smuzaffar The problem in #23873 is that records of type `L1TMuonEndcapParamsRcd` are present in nearly all data GTs and all 2017 and later MC GTs:

https://cms-conddb.cern.ch/cmsDbBrowser/search/Prod/L1TMuonEndcapParams

It is necessary to have a definition in CMSSW for every record contained in a global tag. Therefore, to avoid crashing these workflows, we would need to remove `L1TMuonEndcapParamsRcd` from the 36 relevant queues and update autoCond with new GTs for these queues. Once code that defines `L1TMuonEndcapParamsRcd` is removed, it will no longer be possible to read older GTs that contain payloads of this record type.

**Comment by christopheralanwest** [comment]
+1

This is resolved by PR #30109.

**Comment by ggovi** [comment]
+1

**Comment by ggovi** [comment]
This issue can be closed.

**Comment by mulhearn** [comment]
4.5 years!

**Comment by tvami** [comment]
+alca

**Comment by tvami** [comment]
@rekovic please sign this issue so it can be closed
or @qliphy @perrotta @ericvaandering if you can close it without the L1 signature, please do so
