### ISSUE TITLE
Adding external dependency

### ISSUE THREAD

**Issue by mverzett** [cms-sw/cmssw#17085]
Dear admins,

What is the correct procedure to request the addition of a new external package dependency? In the BTV we would like to include a new tagger based on deep neural networks and we made a working implementation based on [lwtnn](https://github.com/lwtnn/lwtnn). The implementation has been tested to be working with by [brutally porting the package inside CMSSW](https://github.com/mverzett/cmssw/tree/DeepFlavour-from-CMSSW_8_0_21/RecoBTag/LWTNN), but this of course was only for testing and development purposes. 
Let me know what is the best way to proceed.

Thanks,
Mauro

**Comment by mverzett** [comment]
@slava77 , I was told by @arizzi to ask you, and I assumed you would be mentioned by the bot. Since is not the case I do it here :).

**Comment by davidlange6** [comment]
Hi @mverzett  - could you open an issue in the cms-sw/cmsdist repo with what you know about
a) what version you want (ok, there is just one choice currently..)
b) how to build (looks like it is just make; make install)

and indeed discuss with @slava77 to be sure that reco group supports the request.
@iahmad-khan

**Comment by mverzett** [comment]
[Done](https://github.com/cms-sw/cmsdist/issues/2749)

**Comment by slava77** [comment]
@mverzett what is the strategy to support reading this new NN through cond DB?
IMO, the last thing we need is more files and more kinds of parsers loaded during cmsRun.

**Comment by arizzi** [comment]
Hi Slava,
right now the POG supports this tagger for Moriond with a twiki recipe
downloading the code from a private repo, suggesting -u to avoid compiling
dependencies and with payloads from wget.

It is a XPOG priority to avoid this twiki proliferation (but we understand
PAGs needs for ultimate performance)

I'd say we start to include the code and the parsed data and we layout a
plan for conDB migration.
 does it sound good to you?



Il 21 dic 2016 15:14, "Slava Krutelyov" <notifications@github.com> ha
scritto:

**Comment by slava77** [comment]
On 12/22/16 11:30 AM, arizzi wrote:
> Hi Slava,
> right now the POG supports this tagger for Moriond with a twiki recipe
> downloading the code from a private repo, suggesting -u to avoid compiling
> dependencies and with payloads from wget.
> 
> It is a XPOG priority to avoid this twiki proliferation (but we understand
> PAGs needs for ultimate performance)
> 
> I'd say we start to include the code and the parsed data and we layout a
> plan for conDB migration.
> does it sound good to you?
> 

OK.
I guess I will see if there are performance showstoppers when a PR using
this in standard CMSSW workflows shows up.

**Comment by mverzett** [comment]
@slava77 any update on the integration of the external? 
Thanks

**Comment by slava77** [comment]
On 1/6/17 7:32 AM, Mauro Verzetti wrote:
> @slava77 <https://github.com/slava77> any update on the integration of
> the external?
> Thanks
> 

I posted a message on the cmsdist variant of this external request

**Comment by smuzaffar** [comment]
closing it as external lwtnn is now in release
