### ISSUE TITLE
PFTracking GoodSeedProducer correct use of outer momentum

### ISSUE THREAD

**Issue by slava77** [cms-sw/cmssw#17149]
RecoParticleFlow/PFTracking/plugins/GoodSeedProducer.cc

see notes in https://github.com/cms-sw/cmssw/pull/17098#pullrequestreview-14329711

```diff
-	  float oPTOB=1.f/Tj[i].lastMeasurement().updatedState().globalMomentum().mag();
+	  float oPTOB=1.f/std::sqrt(Tk[i].innerMomentum().mag2()); // FIXME the original code was buggy should be outerMomentum...
```

@bachtis @lgray please check and prepare a PR after #17098 is merged

@VinInn @arizzi @gpetruc 

@Dr15Jones @smuzaffar  please assign to reco
[I wish that category managers could actually assign issues at least to their own areas]

**Comment by Dr15Jones** [comment]
assign reconstruction

**Comment by slava77** [comment]
@arizzi @gpetruc 
please comment if we should do anything here or if there is someone to follow up

**Comment by smuzaffar** [comment]
@slava77 , can we close this now?

**Comment by slava77** [comment]
ehm, thank you for checking.
Given the way it entered the CMSSW without reprieve in the last two years, I think that the issue can be counted as resolved.
IIRC, it made sense to be from the start, it was more of a matter to get a formal confirmation for the right thing to do.

**Comment by slava77** [comment]
+1
