### ISSUE TITLE
Remove use of __gnu_cxx::hash_* from CMSSW

### ISSUE THREAD

**Issue by Dr15Jones** [cms-sw/cmssw#17169]
Doing `git grep __gnu_cxx::hash_` turns up many hits in CMSSW. These should all be replaced with the C++ standard `std::unordered_*`.

This causes a problem compiling with clang and using clang's native std headers.

**Comment by Dr15Jones** [comment]
assign core

**Comment by Dr15Jones** [comment]
assign reconstruction

**Comment by smuzaffar** [comment]
https://github.com/cms-sw/cmssw/pull/18293 fixes some of these.

**Comment by slava77** [comment]
+1

looking at CMSSW_11_0_X_2019-05-23-1100, there is nothing left in reco

only CalibTracker/SiStripQuality/interface/SiStripQualityHistos.h and DQMServices/Core/interface/DQMNet.h still have this

**Comment by smuzaffar** [comment]
+core 
https://github.com/cms-sw/cmssw/pull/18293 and https://github.com/cms-sw/cmssw/pull/43118 have fixed the last remaining use of  __gnu_cxx::hash_
