### ISSUE TITLE
Broken output when using python's warnings module

### ISSUE THREAD

**Issue by jolange** [cms-sw/cmssw#17200]
When using python's `warnings` module, the output of `warnings.warn()` contains some seemingly random characters at the end. I have completely reduced a configuration (`test_cfg.py`) to
```
import warnings
warnings.warn("this is a warning")
```
i.e. not even containing a process object. Executing this gives:
```
$ cmsRun test_cfg.py 
cmsRun:2: UserWarning: this is a warning
  � 
      )L��"E
----- Begin Fatal Exception 18-Jan-2017 11:54:00 CET-----------------------
An exception of category 'ConfigFileReadError' occurred while
   [0] Processing the python configuration file named test_cfg.py
Exception Message:
python encountered the error: <type 'exceptions.NameError'>
name 'process' is not defined
----- End Fatal Exception -------------------------------------------------
```
The strange characters are the same in every execution and on different machines, but depend on the string passed to `warn()`. They also depend on the length of the python file: adding comments *before* the `warn()` changes the output.
You can also add a process object + input source to get rid of the exceptions/errors, but the random characters still appear.
Executing this with pure python leads to the expected output:
```
$ python test_cfg.py 
test_cfg.py:2: UserWarning: this is a warning
  warnings.warn("this is a warning")
```

Adding a `print warnings` shows that the same path is used by `cmsRun` and pure python:
```
<module 'warnings' from '/cvmfs/cms.cern.ch/slc6_amd64_gcc530/external/python/2.7.11-ikhhed/lib/python2.7/warnings.pyc'>
```

I'm using `CMSSW_8_0_20_patch1` and also tested this in `CMSSW_7_6_3_patch2`.

For this case it might not be an important issue, but I don't know what the cause of this behavior could imply for important modules. What is `cmsRun` doing on top of python that could cause this?

**Comment by Dr15Jones** [comment]
I tried the same thing using `CMSSW_9_0_0_pre2` and my output is just fine
```
----- Begin Fatal Exception 18-Jan-2017 09:05:38 CST-----------------------
An exception of category 'ConfigFileReadError' occurred while
   [0] Processing the python configuration file named test_warn_cfg.py
Exception Message:
python encountered the error: <type 'exceptions.NameError'>
name 'process' is not defined
----- End Fatal Exception -------------------------------------------------
```

**Comment by jolange** [comment]
I can confirm that. While trying to find the first version in which the problem does not occur, I realized that the problem seems to be present **only in patch versions**. Unfortunately the two versions I tried initially (see above) are patches. The non-patch versions (`CMSSW_7_6_3`, `CMSSW_8_0_20`) produce normal output. I also tried this with a 81X patch (`CMSSW_8_1_X_2017-01-08-2300`) and the problem exists there, too.

**Comment by smuzaffar** [comment]
Looks like we still have this behaviour in patch releases. I will check why it happens in patch releases only.

**Comment by smuzaffar** [comment]
Reason for this is that cmssw-toolfile (which is only used in patch releases) adds CMSSW/bin/arch in to PYTHONPATH. This allows python to find the executable which started the python interpretor and somehow ends up in printing extra chars [a], [b]. We do not need CMSSW/bin/arch in PYTHONPATH, 

https://github.com/cms-sw/cmsdist/pull/5901 should resolve this issue.



[a] CMSSW Patch release:
1. cmsRun is reachable via PYTHONPATH
```
echo $PYTHON27PATH | tr ':' '\n' | xargs -i ls '{}/cmsRun' 2>/dev/null
.../CMSSW_11_2_X_2020-05-29-1100/bin/slc7_amd64_gcc820/cmsRun
```

2. For python warnings, when python was able to find the executable then it printed extra chars
```
stat("...python/2.7.15-bcolbf2/lib/python27.zip/cmsRun", 0x7ffee5afb950) = -1 ENOENT (No such file or directory)
stat("...python/2.7.15-bcolbf2/lib/python2.7/cmsRun", 0x7ffee5afb950) = -1 ENOENT (No such file or directory)
stat("...python/2.7.15-bcolbf2/lib/python2.7/plat-linux2/cmsRun", 0x7ffee5afb950) = -1 ENOENT (No such file or directory)
stat("...python/2.7.15-bcolbf2/lib/python2.7/lib-tk/cmsRun", 0x7ffee5afb950) = -1 ENOENT (No such file or directory)
stat("...python/2.7.15-bcolbf2/lib/python2.7/lib-old/cmsRun", 0x7ffee5afb950) = -1 ENOENT (No such file or directory)
stat("...python/2.7.15-bcolbf2/lib/python2.7/lib-dynload/cmsRun", 0x7ffee5afb950) = -1 ENOENT (No such file or directory)
stat("...python/2.7.15-bcolbf2/lib/python2.7/site-packages/cmsRun", 0x7ffee5afb950) = -1 ENOENT (No such file or directory)
stat("dev/CMSSW_11_2_X_2020-05-29-2300/python/cmsRun", 0x7ffee5afb950) = -1 ENOENT (No such file or directory)
stat("dev/CMSSW_11_2_X_2020-05-29-2300/lib/slc7_amd64_gcc820/cmsRun", 0x7ffee5afb950) = -1 ENOENT (No such file or directory)
stat(".../cms/cmssw-patch/CMSSW_11_2_X_2020-05-29-2300/python/cmsRun", 0x7ffee5afb950) = -1 ENOENT (No such file or directory)
stat(".../cms/cmssw-patch/CMSSW_11_2_X_2020-05-29-2300/lib/slc7_amd64_gcc820/cmsRun", 0x7ffee5afb950) = -1 ENOENT (No such file or directory)
stat(".../cms/cmssw/CMSSW_11_2_X_2020-05-29-1100/bin/slc7_amd64_gcc820/cmsRun", {st_mode=S_IFREG|0755, st_size=244824, ...}) = 0
open(".../cms/cmssw/CMSSW_11_2_X_2020-05-29-1100/bin/slc7_amd64_gcc820/cmsRun", O_RDONLY) = 5
```

[b] CMSSW Full Release
1. cmsRun is not reachable via PYTHONPATH
```
echo $PYTHON27PATH | tr ':' '\n' | xargs -i ls '{}/cmsRun' 2>/dev/null
```

2. As cmsRun was not found , so python just prints the executable name `.cmsRun` 
```
stat(".../py2-enum34/1.1.10-bcolbf/lib/python2.7/site-packages/cmsRun", 0x7ffed3115f10) = -1 ENOENT (No such file or directory)
stat(".../py2-setuptools-scm/3.5.0-bcolbf/lib/python2.7/site-packages/cmsRun", 0x7ffed3115f10) = -1 ENOENT (No such file or directory)
stat(".../py2-numpy/1.16.6-bcolbf/lib/python2.7/site-packages/cmsRun", 0x7ffed3115f10) = -1 ENOENT (No such file or directory)
stat(".../py2-six/1.14.0-bcolbf/lib/python2.7/site-packages/cmsRun", 0x7ffed3115f10) = -1 ENOENT (No such file or directory)
stat(".../py2-pip/9.0.3-bcolbf2/lib/python2.7/site-packages/cmsRun", 0x7ffed3115f10) = -1 ENOENT (No such file or directory)
stat(".../py2-setuptools/41.2.0-bcolbf2/lib/python2.7/site-packages/cmsRun", 0x7ffed3115f10) = -1 ENOENT (No such file or directory)
stat("./cmsRun", 0x7ffed3115f10)        = -1 ENOENT (No such file or directory)
write(2, "cmsRun:2: UserWarning: this is a"..., 41cmsRun:2: UserWarning: this is a warning
) = 41
close(4)                                = 0
munmap(0x7fb906393000, 4096)            = 0
```

**Comment by jolange** [comment]
Nice to see this finally addressed after three years (although I'm no longer using CMSSW).

Thanks for looking into this!
