### ISSUE TITLE
Replacing std::auto_ptr (deprecated in C++11, removed in C++17)

### ISSUE THREAD

**Issue by davidlt** [cms-sw/cmssw#17257]
In CMSSW we still continue to have `std::auto_ptr` used, which was deprecated in C++11. Like many other things, this is finally removed in C++17 standard. GCC 7 will the first GCC version to provide a full C++17 language support (minus the bugs) and CMSSW_9_0_X is compiled with C++17 support since GCC 6. GCC 7 enabled C++17 more widely, e.g., ROOT itself (and anything that uses `root-config` is also compiled with C++17). In addition to that Cling is also running in C++17 mode.

`libc++` already plans to remove `std::auto_ptr` support, but GNU guys don't plan to follow the plan (not yet). Things like `std::auto_ptr`,  old `<functional>`, `random_shuffle()` will be kept in C++17 mode for backwards compatibility. I think (hope) this will be finally removed one C++17 is marked as default C++standard, but earliest it could happen would be GCC 8. I haven't seen community discussing this question yet.

Still we should start cleaning up CMSSW to meet C++17 standard requirements. Especially if we have people who attempt to compile CMSSW stack with `libc++` instead of `libstdc++`. I did that once on macOS and found that CMSSW needs some cleanup to avoid GNU specific things.

**Comment by davidlange6** [comment]
looks like we have about ~1200 auto_ptr declarations...

**Comment by smuzaffar** [comment]
we are down to less than 20 now.

**Comment by smuzaffar** [comment]
All remaining `std::auto_ptr`  are fixed now
