### ISSUE TITLE
apply ECAL gain-switch mitigation, bad muon and JET-MET from #17308 to 90X

### ISSUE THREAD

**Issue by slava77** [cms-sw/cmssw#17362]
@rafaellopesdesa @gpetruc @davidlange6 @mmarionncern @Sam-Harper 
following the discussion in the Tuesday ORP meeting,
the proposal is to provide  in 90X functionality similar or equivalent to what was done for 80X in the combined PR #17308 

Please post your progress  notes towards this goal here.
Detailed discussion should probably happen off this list.

@davidlange6 @Dr15Jones please assign this to reconstruction

**Comment by Sam-Harper** [comment]
I would like to understand the reasoning for this request.

**Comment by gpetruc** [comment]
the idea is that the code to re-do e/gamma objects after changing rechits,
or to re-do jetmet objects after changing pfcandidates, may be useful in
the future even if the specific usecase of the gain switch will be fixed in
the rereco.

**Comment by Dr15Jones** [comment]
assign reconstruction

**Comment by slava77** [comment]
+1

this was resolved in #18165 in April 2017
