### ISSUE TITLE
ImportError: pycurl

### ISSUE THREAD

**Issue by ianna** [cms-sw/cmssw#17483]
Using recent IB CMSSW_9_0_X_2017-02-09-2300:
```
~/bin/uploadConditions.py GeometryFileExtended2017.db 
Traceback (most recent call last):
  File "/afs/cern.ch/user/y/yana/bin/uploadConditions.py", line 40, in <module>
    import pycurl
ImportError: pycurl: libcurl link-time ssl backend (openssl) is different from compile-time ssl backend (none/other)
```

**Comment by davidlange6** [comment]
that is likely caused by me. will investigate

**Comment by smuzaffar** [comment]
@davidlange6 , @iahmad-khan  is looking in to it and I think he already has a fix.

**Comment by davidlange6** [comment]
ok, i think I know what to do too - so I can cross check what @iahmad-khan does

**Comment by smuzaffar** [comment]
@ianna  and @ggovi   cms-sw/cmsdist#2817 shiould fix pycurl

**Comment by smuzaffar** [comment]
assign externals

**Comment by smuzaffar** [comment]
+externals

**Comment by ianna** [comment]
@smuzaffar and @davidlange6 - thanks!
