### ISSUE TITLE
update PFHBHERecHitCreatorMaxSample to use new aux field formats in phase-1 HBHE

### ISSUE THREAD

**Issue by slava77** [cms-sw/cmssw#17529]
@igv4321 @bachtis 

In case PFHBHERecHitCreatorMaxSample is still needed, it should be updated to handle different formatting (8-bit) and possibly also react somehow to plan-1 merged depth hits.
The other option is to remove this code.

@Dr15Jones please assign to reco.
This is a low priority work though.

**Comment by Dr15Jones** [comment]
assign reconstruction

**Comment by slava77** [comment]
@igv4321 @deguio @mariadalfonso 
I was checking some old issues and I wanted to check if this one is still on the radar (or if it was addressed already).

**Comment by slava77** [comment]
@hatakeyamak @bendavid 
it looks like this PF code was not updated.
Is it still needed or should we just delete it?

**Comment by hatakeyamak** [comment]
It looks to me that it's not used at all. I am preparing a PR to remote it.

**Comment by hatakeyamak** [comment]
I think this issue is now resolved. The cleanup PR is already merged.

**Comment by slava77** [comment]
+1

this is available since 11_0_0_pre5
