### ISSUE TITLE
Issue with dictionary generation in Cling (ROOT 6.08.04)

### ISSUE THREAD

**Issue by aperloff** [cms-sw/cmssw#17528]
I have been developing some code for CMSSW. I was originally developing the code in CMSSW_8_1_0_pre16 and recently switched to CMSSW_9_0_0_pre4 (tested also in the latest IB). The code compiles just fine in 81X, but does not compile in 90X. There is some problem with Cling during dictionary generation. I've attached a file containing the scram messages as well as a temporary dictionary file generated by Cling.

Do you know why this is occurring or if there is a problem with the version of ROOT in CMSSW_9_0_X?

Thanks,
Alexx

[scram_message.txt](https://github.com/cms-sw/cmssw/files/778254/scram_message.txt)
[CondFormatsJetMETObjects_xr.cc_tmp.txt](https://github.com/cms-sw/cmssw/files/778253/CondFormatsJetMETObjects_xr.cc_tmp.txt)

**Comment by aperloff** [comment]
I forgot to say that the code I'm working on is located at https://github.com/aperloff/cmssw/tree/bin-lookup-JetCorrectorParameters, in case that helps. I'm going to do a pull request once this issue is resolved.

**Comment by Dr15Jones** [comment]
@pcanal

**Comment by Dr15Jones** [comment]
assign core

**Comment by pcanal** [comment]
We recently added support for std::tuple.  Apparently in this case, it fails to find one of the type of the tuple.  Reading the code, I am not sure where this tuple might comes from.  I see there their are tuples in JetCorrectorParametersHelper but I do not see how it connects to one of the classes with a dictionary.   Shortest mean to solution might be to have a reproducer with a debug build of ROOT.

**Comment by aperloff** [comment]
All of the tuples in JetCorrectorParametersHelper are supposed to be transient. Is there a build of CMSSW that includes a debug build of ROOT that I could test this on?

**Comment by aperloff** [comment]
Hi all, just checking in to see if there was any movement on this. I never heard back if there was a version of CMSSW with a debug build of ROOT.

**Comment by aperloff** [comment]
With @Dr15Jones  help I found a workaround to my problem. I haven't exactly solved the initial issue, but the code I was writing is no longer affected. I'm therefore going to close this issue.
