### ISSUE TITLE
HCAL Plan-1: HcalNoiseInfoProducer.cc to look at all merged digis

### ISSUE THREAD

**Issue by slava77** [cms-sw/cmssw#17593]
https://github.com/cms-sw/cmssw/pull/17581#pullrequestreview-22972210
introduced with 
https://github.com/cms-sw/cmssw/pull/17581

@bsunanda @kpedro88

**Comment by Dr15Jones** [comment]
assign reconstruction

**Comment by slava77** [comment]
@kpedro88 @igv4321 @bsunanda 
is this issue still relevant?
this is related to https://github.com/cms-sw/cmssw/pull/17581#pullrequestreview-22972210

**Comment by slava77** [comment]
@deguio @mariadalfonso @bsunanda 
do we know or can assume to have all the plan-1 use cases to be addressed?
I wanted to check before closing this.
Please advise.
Thank you.

**Comment by deguio** [comment]
@jaehyeok

**Comment by deguio** [comment]
I've talked quickly with @jaehyeok and we couldn't think of anything pending in terms of HcalNoiseInfoProducer for the uncollapsed or collapsed scenario. so this one can be closed.
thanks.

**Comment by slava77** [comment]
+1

based on https://github.com/cms-sw/cmssw/issues/17593#issuecomment-431942495 from Oct 2018
