### ISSUE TITLE
Replace Depricated Module: Warning from CondCore

### ISSUE THREAD

**Issue by ianna** [cms-sw/cmssw#17601]
Most of the relvals produce the following message:
```
 ##################################################################### 
 # WARNING: the module CondCore.DBCommon.CondDBCommon is deprecated. # 
 # Please import CondCore.CondDB.CondDB_cfi                          # 
 ##################################################################### 
```
Deprecated file fragment is used in http://cmslxr.fnal.gov/search?_filestring=&_string=CondDBCommon

**Comment by davidlange6** [comment]
assign simulation

(I’ve already explained the reason to them)

**Comment by civanch** [comment]
PR #17607 should address the issue

**Comment by ianna** [comment]
@davidlange6 - PR #17607 was not merged.
