### ISSUE TITLE
900pre5 wrong dictionary placement in SimTracker/TrackTriggerAssociation/src/classes_def.xml 

### ISSUE THREAD

**Issue by slava77** [cms-sw/cmssw#17673]
https://cmssdt.cern.ch/SDT/cgi-bin/showDupDict.py//slc6_amd64_gcc530/www/wed/9.0-wed-11/CMSSW_9_0_X_2017-03-01-1100/testLogs/dupDict-lostDefs.log

- ``` TrackingAnalysis : edm::Ptr< TrackingParticle > ``` should be in SimDataFormats/TrackingAnalysis as suggested in the log
- ``` TrackingAnalysis : vector< edm::Ptr< TrackingParticle > > ``` should be in SimDataFormats/TrackingAnalysis as suggested in the log
- everything else should probably stay in this package (it uses TrackingParticle from SimDataFormats/TrackingAnalysis and TTCluster or TTStub from  DataFormats/L1TrackTrigger. The TrackingAnalysis could probably be made dependent on L1TrackTrigger, but it may be excessive)

@kpedro88 @rekovic @smuzaffar

**Comment by kpedro88** [comment]
@sviret this looks like a lingering issue from #16303

**Comment by sviret** [comment]
@kpedro88 , the trackingParticle move has been made in #16331, but the PR has not been merged yet. For the rest I agree it should stay i TrackTriggerAssociation package, as these are objects only related to this package.
