### ISSUE TITLE
Calling G4DecayPhysics::ConstructParticle is not thread safe

### ISSUE THREAD

**Issue by Dr15Jones** [cms-sw/cmssw#17802]
After changing the framework to have streamBeginRun use multiple threads, the fast simulation began to fail with a G4 exception
```
-------- EEEE ------- G4Exception-START -------- EEEE -------

*** ExceptionHandler is not defined ***
*** G4Exception : PART012
      issued by : G4VDecayChannel::FillParent()
Can not fill parent: parent does not exist
*** Fatal Exception ***
-------- EEEE -------- G4Exception-END --------- EEEE -------
```

The traceback for the error was
```
#2  0x00007fffcd9c2b4a in G4Exception(char const*, char const*, G4ExceptionSeverity, char const*) ()
   from /cvmfs/cms-ib.cern.ch/week0/slc6_amd64_gcc530/cms/cmssw-patch/CMSSW_9_1_X_2017-03-05-2300/external/slc6_amd64_gcc530/lib/libG4global.so
#3  0x00007fffcd7555a5 in G4ParticleTable::Insert(G4ParticleDefinition*) () from /cvmfs/cms-ib.cern.ch/week0/slc6_amd64_gcc530/cms/cmssw-patch/CMSSW_9_1_X_2017-03-05-2300/external/slc6_amd64_gcc530/lib/libG4particles.so
#4  0x00007fffcd74e7a3 in G4ParticleDefinition::G4ParticleDefinition(G4String const&, double, double, double, int, int, int, int, int, int, G4String const&, int, int, int, bool, double, G4DecayTable*, bool, G4String const&, int, double) () from /cvmfs/cms-ib.cern.ch/week0/slc6_amd64_gcc530/cms/cmssw-patch/CMSSW_9_1_X_2017-03-05-2300/external/slc6_amd64_gcc530/lib/libG4particles.so
#5  0x00007fffcd717149 in G4Gamma::Definition() () from /cvmfs/cms-ib.cern.ch/week0/slc6_amd64_gcc530/cms/cmssw-patch/CMSSW_9_1_X_2017-03-05-2300/external/slc6_amd64_gcc530/lib/libG4particles.so
#6  0x00007fffcd716d73 in G4BosonConstructor::ConstructParticle() () from /cvmfs/cms-ib.cern.ch/week0/slc6_amd64_gcc530/cms/cmssw-patch/CMSSW_9_1_X_2017-03-05-2300/external/slc6_amd64_gcc530/lib/libG4particles.so
#7  0x00007fffcd4cc770 in G4DecayPhysics::ConstructParticle() () from /cvmfs/cms-ib.cern.ch/week0/slc6_amd64_gcc530/cms/cmssw-patch/CMSSW_9_1_X_2017-03-05-2300/external/slc6_amd64_gcc530/lib/libG4physicslists.so
#8  0x00007fffcdfb6905 in FastHFShowerLibrary::initHFShowerLibrary(edm::EventSetup const&) ()
   from /cvmfs/cms-ib.cern.ch/week0/slc6_amd64_gcc530/cms/cmssw-patch/CMSSW_9_1_X_2017-03-05-2300/lib/slc6_amd64_gcc530/libFastSimulationShowerDevelopment.so
#9  0x00007fffce0d94a7 in FamosManager::setupGeometryAndField(edm::Run const&, edm::EventSetup const&) ()
   from /cvmfs/cms-ib.cern.ch/week0/slc6_amd64_gcc530/cms/cmssw-patch/CMSSW_9_1_X_2017-03-05-2300/lib/slc6_amd64_gcc530/pluginFastSimulationEventProducer.so
#10 0x00007ffff7d553de in edm::stream::ProducingModuleAdaptorBase<edm::stream::EDProducerBase>::doStreamBeginRun(edm::StreamID, edm::RunPrincipal const&, edm::EventSetup const&, edm::ModuleCallingContext const*) ()
```

Working my way down the call chain, I found a series of singletons
https://github.com/cms-externals/geant4/blob/e04275a38d2c2ad2ac2954a9c06e08e5e544f30f/source/physics_lists/constructors/decay/src/G4DecayPhysics.cc#L82
https://github.com/cms-externals/geant4/blob/e04275a38d2c2ad2ac2954a9c06e08e5e544f30f/source/particles/bosons/src/G4BosonConstructor.cc#L60

which lead the this race condition
https://github.com/cms-externals/geant4/blob/e04275a38d2c2ad2ac2954a9c06e08e5e544f30f/source/particles/bosons/src/G4Gamma.cc#L51

because G4Gamma::theInstance is a regular non-thread local static
https://github.com/cms-externals/geant4/blob/e04275a38d2c2ad2ac2954a9c06e08e5e544f30f/source/particles/bosons/include/G4Gamma.hh#L53
And the G4ParticleTable is also a regular non-thread local static
https://github.com/cms-externals/geant4/blob/cms/4.10.00.p02/source/particles/management/include/G4ParticleTable.hh#L240

OscarMTProducer avoids the problem becuase it initializes the PhysicsList in its 'master' thread. However, if other CMS code calls `G4DecayPhysics::ConstructParticle` then it could conflict. The places outside of OscarMTProducer which call the routine are:
https://github.com/cms-sw/cmssw/blob/09c3fce6626f70fd04223e7dacebf0b485f73f54/FastSimulation/MaterialEffects/src/NuclearInteractionFTFSimulator.cc#L219
https://github.com/cms-sw/cmssw/blob/09c3fce6626f70fd04223e7dacebf0b485f73f54/FastSimulation/ShowerDevelopment/src/FastHFShowerLibrary.cc#L62

**Comment by Dr15Jones** [comment]
assign simulation

**Comment by Dr15Jones** [comment]
A workaround for the problem was added to #17749.

**Comment by civanch** [comment]
#17749 resolve the problem of Geant4 particle initialisation in FastHFShowerLibrary

**Comment by civanch** [comment]
+1
