### ISSUE TITLE
make plugin factory report which plugin was loaded in load exception

### ISSUE THREAD

**Issue by slava77** [cms-sw/cmssw#17938]
Example can be found in #17794

```
   [1] Constructing module: class=PFRecHitProducer label='hltParticleFlowRecHitECALUnseeded'
Exception Message:
unable to load $CMSSW_BASE/lib/slc6_amd64_gcc530/poisoned/plugin-poisoned-RecoParticleFlowPFClusterProducerPlugins.so because $CMSSW_BASE/lib/slc6_amd64_gcc530/poisoned/plugin-poisoned-RecoParticleFlowPFClusterProducerPlugins.so: cannot open shared object file: No such file or directory
```
in this case, with ``` process.add_(cms.Service("PrintLoadingPlugins")) ``` one can see that the failed operation is ``` Getting> 'PFRecHitFactory' PFEBRecHitCreator ```

It would help to have the name of the attempted loaded plugin in the exception message.

**Comment by Dr15Jones** [comment]
assign core

**Comment by smuzaffar** [comment]
@Dr15Jones , has this been implemented?

**Comment by smuzaffar** [comment]
+core
thaks to @guitargeek, this has been implement in https://github.com/cms-sw/cmssw/pull/27908
