### ISSUE TITLE
Remove requirement on HLT from workflows

### ISSUE THREAD

**Issue by davidlange6** [cms-sw/cmssw#18014]
Following up from the ORP on 14 March, @fwyzard has suggested that components in CMS workflows be updated so that the fake HLT menus could be removed altogether. We agreed to investigate and discuss in the 28 March ORP what timescale is possible. Definitively affected are analysis (minor as far as I'm aware) and dqm (offline/validation). Likely there are other issues I'm not aware of.

Please post any findings you wish to share also to this issue.

**Comment by davidlange6** [comment]
assign dqm

**Comment by davidlange6** [comment]
assign analysis

**Comment by davidlange6** [comment]
assign pdmv

**Comment by davidlange6** [comment]
just to kick this issue along, here is the first problem

egin processing the 1st record. Run 1, Event 1, LumiSection 1 at 25-Apr-2017 14:55:27.113 CEST
----- Begin Fatal Exception 25-Apr-2017 14:55:35 CEST-----------------------
An exception of category 'ProductNotFound' occurred while
   [0] Processing  Event run: 1 lumi: 1 event: 1 stream: 0
   [1] Running path 'prevalidation_step'
   [2] Calling method for module MultiTrackValidator/'hltTrackValidator'
Exception Message:
Principal::getByToken: Found zero products matching all criteria
Looking for type: reco::BeamSpot
Looking for module label: hltOnlineBeamSpot
Looking for productInstanceName: 

   Additional Info:
      [a] If you wish to continue processing events after a ProductNotFound exception,
add "SkipEvent = cms.untracked.vstring('ProductNotFound')" to the "options" PSet in the configuration.

**Comment by davidlange6** [comment]
and all the printouts that indicate problems that came before the crash

%MSG-w GenericTriggerEventFlag:   BPHMonitor:DoubleMu4_JpsiTrk_Displaced_BPHMonitoring@streamBeginRun  25-Apr-2017 14:55:23 CEST Run: 1 Stream: 0
Label BPHDQMTrigger not found in DB for 'AlCaRecoTriggerBitsRcd'
%MSG
%MSG-w GenericTriggerEventFlag:   BPHMonitor:DoubleMu4_3_Jpsi_Displaced_BPHMonitoring@streamBeginRun  25-Apr-2017 14:55:23 CEST Run: 1 Stream: 0
Label BPHDQMTrigger not found in DB for 'AlCaRecoTriggerBitsRcd'
%MSG
%MSG-w GenericTriggerEventFlag:   BPHMonitor:Dimuon10_Jpsi_Barrel_BPHMonitoring@streamBeginRun  25-Apr-2017 14:55:23 CEST Run: 1 Stream: 0
Label BPHDQMTrigger not found in DB for 'AlCaRecoTriggerBitsRcd'
%MSG
%MSG-w GenericTriggerEventFlag:   BPHMonitor:Dimuon20_Jpsi_BPHMonitoring@streamBeginRun  25-Apr-2017 14:55:23 CEST Run: 1 Stream: 0
Label BPHDQMTrigger not found in DB for 'AlCaRecoTriggerBitsRcd'
%MSG
%MSG-e HLTConfigProvider:   TopSingleLeptonHLTOfflineDQM:SingleTopSingleElectronHLTOfflineDQM@streamBeginRun  25-Apr-2017 14:55:26 CEST Run: 1 Stream: 0
Auto-discovery of processName failed!
%MSG
%MSG-w TopSingleLeptonHLTOfflineDQM:   TopSingleLeptonHLTOfflineDQM:SingleTopSingleElectronHLTOfflineDQM@streamBeginRun  25-Apr-2017 14:55:26 CEST Run: 1 Stream: 0
Config extraction failure with process name 

%MSG
%MSG-e HLTConfigProvider:   TopSingleLeptonHLTOfflineDQM:SingleTopSingleMuonHLTOfflineDQM@streamBeginRun  25-Apr-2017 14:55:26 CEST Run: 1 Stream: 0
Auto-discovery of processName failed!
%MSG
%MSG-w TopSingleLeptonHLTOfflineDQM:   TopSingleLeptonHLTOfflineDQM:SingleTopSingleMuonHLTOfflineDQM@streamBeginRun  25-Apr-2017 14:55:26 CEST Run: 1 Stream: 0
Config extraction failure with process name 

%MSG
%MSG-e HLTConfigProvider:   TopSingleLeptonHLTOfflineDQM:topSingleElectronHLTOfflineDQM@streamBeginRun  25-Apr-2017 14:55:26 CEST Run: 1 Stream: 0
Auto-discovery of processName failed!
%MSG
%MSG-w TopSingleLeptonHLTOfflineDQM:   TopSingleLeptonHLTOfflineDQM:topSingleElectronHLTOfflineDQM@streamBeginRun  25-Apr-2017 14:55:26 CEST Run: 1 Stream: 0
Config extraction failure with process name 

%MSG
%MSG-e HLTConfigProvider:   TopSingleLeptonHLTOfflineDQM:topSingleMuonHLTOfflineDQM@streamBeginRun  25-Apr-2017 14:55:26 CEST Run: 1 Stream: 0
Auto-discovery of processName failed!
%MSG
%MSG-w TopSingleLeptonHLTOfflineDQM:   TopSingleLeptonHLTOfflineDQM:topSingleMuonHLTOfflineDQM@streamBeginRun  25-Apr-2017 14:55:26 CEST Run: 1 Stream: 0
Config extraction failure with process name 

%MSG
%MSG-e HLTConfigProvider:   TopDiLeptonHLTOfflineDQM:ElecMuonHLTOfflineDQM@streamBeginRun  25-Apr-2017 14:55:26 CEST Run: 1 Stream: 0
Auto-discovery of processName failed!
%MSG
%MSG-w TopSingleLeptonHLTOfflineDQM:   TopDiLeptonHLTOfflineDQM:ElecMuonHLTOfflineDQM@streamBeginRun  25-Apr-2017 14:55:26 CEST Run: 1 Stream: 0
Config extraction failure with process name 

%MSG
%MSG-e HLTConfigProvider:   TopDiLeptonHLTOfflineDQM:DiElectronHLTOfflineDQM@streamBeginRun  25-Apr-2017 14:55:26 CEST Run: 1 Stream: 0
Auto-discovery of processName failed!
%MSG
%MSG-w TopSingleLeptonHLTOfflineDQM:   TopDiLeptonHLTOfflineDQM:DiElectronHLTOfflineDQM@streamBeginRun  25-Apr-2017 14:55:26 CEST Run: 1 Stream: 0
Config extraction failure with process name 

%MSG
%MSG-e HLTConfigProvider:   TopDiLeptonHLTOfflineDQM:DiMuonHLTOfflineDQM@streamBeginRun  25-Apr-2017 14:55:26 CEST Run: 1 Stream: 0
Auto-discovery of processName failed!
%MSG
%MSG-w TopSingleLeptonHLTOfflineDQM:   TopDiLeptonHLTOfflineDQM:DiMuonHLTOfflineDQM@streamBeginRun  25-Apr-2017 14:55:26 CEST Run: 1 Stream: 0
Config extraction failure with process name 

%MSG

**Comment by davidlange6** [comment]
mostly for @dmitrijus

**Comment by davidlange6** [comment]
you would have to go back in your inbox to understand at this point, dqm ignored this request from the ORP for 1.5 years...

**Comment by jfernan2** [comment]
+1
Please let me know if this issue is still valid
Thanks

**Comment by tvami** [comment]
+analysis
 * seems to me that this issue was resolved

**Comment by smuzaffar** [comment]
looks like this issue has been addressed. I am closing it but let me know if you want to keep it open

**Comment by makortel** [comment]
I don't think the real issue was solved, as far as I can tell many of the runTheMatrix workflows still have fake HLT menu.
