### ISSUE TITLE
support for gcc5 for 2016 MC production

### ISSUE THREAD

**Issue by perrozzi** [cms-sw/cmssw#18175]
As detailed in the talk during the O&C week https://indico.cern.ch/event/624140/contributions/2533506/attachments/1438011/2212147/Long_GENComputingReport_2017_04_03.pdf
we would like to have a CMSSW version supporting gcc5 for 2016 MC production.
From what I understood during the discussion, this should be relatively straightforward
or even already available in CMSSW 80x. Main differences with respect to CMSSW 71x currently used would be the GEANT version.
@kdlong @vciulli @bendavid @govoni can comment further

**Comment by davidlange6** [comment]
indeed the real request is a gcc530 release. 

So, 80x works out of the box except that generator requests haven't gone into 80x for some time now. So, GEN would need to look at what updates are needed. And otherwise some validation/comparison is needed to ensure sanity.

We can have a quick look at 71x in gcc530, but that may fail quickly.

**Comment by perrozzi** [comment]
I see some ongoing tests here https://github.com/cms-sw/cmsdist/pull/2936 (thanks!)

**Comment by perrozzi** [comment]
Follow up from today's ORP: tests in 71X so far positive but next step is to make ROOT 5 and gcc compatible, which is not straightforward. Workaround should be available but not guaranteed to work, timescale for an update ~2 weeks. 
If that fails the alternative is to move to 80X which requires some work, so some discussion will be needed before to do that.

**Comment by perrozzi** [comment]
hi, any news on this?

**Comment by perrozzi** [comment]
Hi, I must admit that after today's ORP I still don't understand why is not possible to define a set of environment variables that can be reliably used to produce LHE text events from gridpack in a CMSSW-independent way.
I guess that the fact that we use cvmfs is not by chance, is really to ensure that each worker node can pick up the desired CMSSW release and related packages.
I can hardly imagine that this paradigm, i.e. stop using cvmfs to distribute software, will change in the "near" future. I assume that many (many) things apart from the gridpack production could be affected...

So, even if cvmfs was not designed for a purpose like this, I humbly (and naively and stubbornly, I admit) ask to consider this as a valuable option. To agree on a way to ensure such a possibility.
This will only be useful for the 71x case but also for future productions.
For instance, recent 90x Relvals show that gridpacks produced with gcc5 fail when CMSSW supporting gcc6 is used... We could find ourself in the situation to be forced to (re-)produce tens of thousands of gridpacks per year.
Or what if the MC authors silently change their compiler settings (as is happening now with POWHEG) in 1y from now and things we will need to do another forward-/back-porting as suggested for 71x-->80x?
What if some settings needed for a MC only appear in a CMSSW version posterior to the CMSSW version used for DIGI-RECO? We trigger a complete re-reco?
All these scenarios, in my opinion, are scary and would force the limited GEN manpower resources to focus only technical aspects at the expenses of ensuring the highest physics accuracy in the generation
(which I believe should be our first goal, thanks to the giudance and wise vision of computing).

Can we please have a dedicated discussion, as advocated today during the ORP?

Thanks a lot in advance for your patience.
Luca

**Comment by smuzaffar** [comment]
Do we still need to keep this issue open?

**Comment by davidlange6** [comment]
I don’t think so

On May 29, 2020, at 11:56 AM, Malik Shahzad Muzaffar <notifications@github.com<mailto:notifications@github.com>> wrote:



Do we still need to keep this issue open?
