### ISSUE TITLE
towards a solution of the LHERunInfoProduct duplication 

### ISSUE THREAD

**Issue by perrozzi** [cms-sw/cmssw#18213]
As discussed again during the O&C week, there is a long standing issue with the duplication of LHERunInfoProduct https://indico.cern.ch/event/624140/contributions/2533506/attachments/1438011/2212245/lheruninfoproduct_memory_usage.pdf
The issue has been identified and a solution example has been implemented [1] but some discussion is needed, hence this github issue.

The LHERunInfoProduct is basically a collection header blocks consisting of vectors of strings. Some of these blocks gets duplicated when merging two edm files, in case any difference is found between the two corresponding vectors. A list of blocks that are explicitly checked can be found here:
https://github.com/perrozzi/cmssw/blob/0f0aee2627b4d24ab98e0900413ba73338d86041/SimDataFormats/GeneratorProducts/src/LHERunInfoProduct.cc#L209

1) For aMC@NLO in NLO mode, no issue seem to be present
2) For aMC@NLO in LO mode 2 blocks are always duplicated: first the MGRunCard header carrying a string with the initialization seed (iseed) for each file, second the MGGenerationInfo which contains luminosity related information computed on the events in each file, therefore subject to statistical fluctuations
3) For POWHEG the block that gets duplicated has no name (empty string), also in this case because it carries a string with the initialization seed (iseed)

It is trivial to fix aMC@NLO in LO mode, see [1] for MGRunCard, it can be trivially extended to MGRunCard and with some care also to POWHEG (there might be multiple headers without name).

The main question is: which information do we want to keep and why? I was not involved in the original implementation, so I am not aware of possible sublties. I can say that the LHERunInfoProduct can be very useful to check the LHE datacard settings and the order of LHE weights. Unless we merge different processes in a single dataset I personally don't even see the point of checking the different headers, because the events come from the same gridpack/production. The only exception is likely the production of private LHE files to be injected in the system (mass scans or other parameter variations that go into a single dataset).

A fix to this LHERunInfoProduct naturally occurs when using the multi-gridpack SUSY-like scan machinery, which produces events and stores info at lumi-level, but can't still be used widely because of other issues.

Another thing that might be good to implement is a solution to read existing files, for example dropping "duplicates" (i.e. differing for seeds only or similar) on the fly when opening the files. This requires other input for me to proceed.

Let me reference people that would be good to have involved in the discussion:
@bendavid @vciulli @qliphy @lenzip @mkirsano @kdlong @govoni @kpedro88 
(please add anybody else potentially interested)

If computing has comments, please let us know.

Thanks
Luca

[1] https://github.com/cms-sw/cmssw/compare/CMSSW_7_1_X...perrozzi:LHERunInfoProduct?expand=1

**Comment by perrozzi** [comment]
(adding @covarell too)

**Comment by perrozzi** [comment]
Ciao, anybody willing to comment? I am progressing on this but I have no clue of the reason for certain choices and the code might become involved without an historical perspective.

**Comment by bbockelm** [comment]
Hi @perrozzi -

I also don't know the full history here, but I can bring one piece in to the puzzle.

Effectively, offline does not handle run mergeable products correctly.  There were several long discussions on the topic in the April 2016 O&C meeting.  The ultimate conclusion was that there was a very high cost to actually manage the batch system jobs so merging run products was done properly.

To the best of our knowledge, the only offline use of run products appeared to be LHE info.  The LHE run products don't need a full set of the functionality.

@Dr15Jones proposed that we effectively eliminate general purpose run products.  In place, the options were:
1.  Actually eliminate the run product completely.  Use lumi products (this might be too large an expansion of file size for this use case; not clear).
2.  Only allow idempotent merging.  That is, if the same run product was merged multiple times, the result would be the same.
   - An example of an idempotent operation would be the union of sets.
   - An example of a non-idempotent operation would be a count of events seen from the run.

Apologies - seems that this comment is too high-level / strategic to answer your specific questions. However, it's probably useful to know that run info products are seen as a bit problematic and would be quite useful to collaborate with Chris to make sure your new code is future-proof.

Thanks a bunch!

Brian

**Comment by perrozzi** [comment]
Hi Brian,
thanks for the feedback. In the meanwhile I implemented this
https://github.com/cms-sw/cmssw/pull/18846
feel free to comment

ciao
luca

**Comment by perrozzi** [comment]
https://github.com/cms-sw/cmssw/pull/18846 merged
