### ISSUE TITLE
CondCore/CondDB/test/testConnectionPool.cpp accessing obsolete squid service

### ISSUE THREAD

**Issue by DrDaveD** [cms-sw/cmssw#18246]
CondCore/CondDB/test/testConnectionPool.cpp has a hardcoded frontier configuration, proxyconfigurl=http://cmst0frontier.cern.ch/t0.pac, and that is now obsolete and will soon be decomissioned.  The new proxyconfigurl is http://grid-wpad/wpad.dat, but more importantly, why is that connect string hardcoded there at all?  It should be using the local configuration from site-local-config.xml like everything else.  

Please look at this at high priority, or these tests will start failing soon.

**Comment by davidlange6** [comment]
assign db

**Comment by DrDaveD** [comment]
@ggovi  Please look at this with high priority.  The t0.pac interface will soon be decomissioned and I assume all tests running this code will start breaking.

**Comment by ggovi** [comment]
@DrDaveD 
Thanks for the warning.  Addressed by 
https://github.com/cms-sw/cmssw/pull/18376
https://github.com/cms-sw/cmssw/pull/18377
https://github.com/cms-sw/cmssw/pull/18378
Concerning the need to have the full string in the test: here we validate the code parsing and decoding various connection string supported. The explicit frontier connection string, although discouraged, is supported.

**Comment by DrDaveD** [comment]
Thanks, @ggovi.  Do you know if this test is run only on the latest code?  Or is it also run on old code?  Clearly it has to be run only at CERN since a CERN configuration is hard-coded.

**Comment by ggovi** [comment]
I found this test  in 80X, 90X and 91X ( not in 71X ). Any other release cycle to check?

**Comment by DrDaveD** [comment]
It's good to hear that it doesn't go back to very old code.  I just hope that people aren't using it for older released versions in those release cycles, but instead are only using it with the latest integration builds.

**Comment by ggovi** [comment]
+1
