### ISSUE TITLE
Use edm::one modules to access PoolDBOutputService

### ISSUE THREAD

**Issue by Dr15Jones** [cms-sw/cmssw#18340]
The `PoolDBOutputService` appears to be properly thread safe by using a `std::mutex`. However, since the framework will still schedule multiple modules to run concurrently where those modules would then be fighting over the mutex lock and therefore some of them would stall. If, instead, the modules would be declared `edm::one` modules and would declare a `SharedResource` on the `PoolDBOutputService`, the framework would schedule only one module to talk to the service at a time and could run other modules concurrently which do not need the service.

Such a change is made easier because many of the modules that use the `PoolDBOutputService` appear to be templated classes: `BoostIODBWriter<>`, `ConditionDBWriter<>` and `DummyCondDBWriter<>`.

**Comment by Dr15Jones** [comment]
assign alca

**Comment by tvami** [comment]
unassign alca
assign db
* I think this needs a DB signature, not AlCa

**Comment by tvami** [comment]
assign db

**Comment by tvami** [comment]
With Giacomo leaving CMS, I looked into this issue. I understand of the current status is that most of the work was actually done by @mmusich  in https://github.com/cms-sw/cmssw/pull/40793 for `ConditionDBWriter`. I gave a try to resolve the problem in the remaining two files in the PR https://github.com/cms-sw/cmssw/pull/41094

**Comment by tvami** [comment]
+db
