### ISSUE TITLE
DQMMonitoringService is not thread-safe

### ISSUE THREAD

**Issue by Dr15Jones** [cms-sw/cmssw#18358]
The DQMMonitoringService has several thread-safety issues:

- It increments an event count per lumi in a non-thread safe manner-
- Its implementation does not support having multiple luminosity blocks being processed simultaneously.

**Comment by Dr15Jones** [comment]
assign dqm

**Comment by dmitrijus** [comment]
This is used exclusively in online DQM and online DQM never processes multiple luminosity blocks at the same time. And never multithread, I don't think the input source is thread-safe either.

It runs "on line" - the current lumisection is always the latest one available.

I will see what I can do, a few locks would not hurt.

**Comment by fioriNTU** [comment]
+1 

not a real issue for Online as in the comment above
