### ISSUE TITLE
switching to puppi candidate based tagging for puppi jets

### ISSUE THREAD

**Issue by slava77** [cms-sw/cmssw#18426]
related to the discussion in #18317 

a check should be done with latest higher PU samples to check the btag performance on puppi jets using current default pfCands vs puppiCands.
If the gain is positive as it's already clearly seen in phase-2, the change should be applied to all eras instead of just phase-2

**Comment by slava77** [comment]
assign reconstruction

**Comment by slava77** [comment]
@ferencek @imarches

**Comment by ferencek** [comment]
After some discussion within the BTV POG, we decided to switch the b tagging input for Puppi jets from PF candidates to Puppi candidates for all eras. Given the fact that ak4 Puppi jets are not yet the default jet collection, we can run a non-default b tagging setup on these jets and monitor it more easily.

This change is implemented in #18666 (92X) and #18667 (91X).

**Comment by slava77** [comment]
+1

fixed in  #18666
