### ISSUE TITLE
unsupported command line arguments to clang

### ISSUE THREAD

**Issue by fwyzard** [cms-sw/cmssw#18433]
Running clang-tidy complains with
```
warning: argument unused during compilation: '--param vect-max-version-for-alias-checks=50' [clang-diagnostic-unused-command-line-argument]
warning: argument unused during compilation: '-Wa,--compress-debug-sections' [clang-diagnostic-unused-command-line-argument]
```

It is easy to suppress them with `-checks=-clang-diagnostic-unused-command-line-argument` , but it might be better to remove them from the arguments passed to clang altogether.

**Comment by fwyzard** [comment]
On the `slc6_amd64_gcc700` branch, I get also
```
error: unknown argument: '-fno-aggressive-loop-optimizations' [clang-diagnostic-error]
```
which (being an error rather than a warning) is more of a problem.

**Comment by VinInn** [comment]
why we have added '-fno-aggressive-loop-optimizations' to gcc 7?

**Comment by smuzaffar** [comment]
this should be fixed now. clang compiler tools should have removed these flags
