### ISSUE TITLE
Items needed but not yet signed for pre3

### ISSUE THREAD

**Issue by davidlange6** [cms-sw/cmssw#18449]
For upgrade (muon tdr validation release)
#17843 (needs L1 signature)
#18387 (code/config organization issues to be solved)
#18373 (needs small update from author)
#18236 (but not essential)

Please add others remaining and issues to be resolved before they can be signed here.

**Comment by boudoul** [comment]
hi @davidlange6 , it would be great to have : 
#18421  (ugrade signed, needs sim signature) 
for the tracker TDR - Thanks

**Comment by kpedro88** [comment]
@davidlange6 thanks - one more item is modifications to aging.py for HCAL aging scenarios, which I can hopefully submit today (just Python, so it should be easy to test and review). Not sure if ECAL aging conditions will arrive for pre3, but we can put these in global tags to use for production even if they come late.

**Comment by Martin-Grunewald** [comment]
#18428 - this feature is long awaited!

**Comment by slava77** [comment]
Here are other pending non-technical PRs that require reco signature

- #18283 CTPPS updates for 2017
    - essentially ready; important for 910
- #18233 PCC automation
    - needs review after recent updates; the goal is to use this in PCL or something similar in AlCa workflows. 
- #18321 muon arbitration
    - essentially ready; affects muons and downstream objects
- #18330 DA clusterizer updates
    - under discussion; affects tracking (through use of vertexing), vertexing and downstream objects
- #18430 tau MVA updates
    - needs review; affects tau discriminants saved in AOD

**Comment by kpedro88** [comment]
#18452 is the aforementioned HCAL aging followup PR

**Comment by kpedro88** [comment]
#18456 also needed

**Comment by davidlange6** [comment]
ECAL aging conditions

**Comment by kpedro88** [comment]
>ECAL aging conditions

If they don't come in time, we can consider making a patch to the upgrade production release to set them in aging.py.

**Comment by davidlange6** [comment]
#18283, #18321, #18330 are the essential ones

**Comment by rekovic** [comment]
For L1T:
#18489 (essential)
#18428 (highly desired-long waited)
#18085

**Comment by davidlange6** [comment]
Update on remaining items.  can we finish these today?
#18321 
#18330
#18456

**Comment by slava77** [comment]
reco perspective:

On 4/27/17 4:40 AM, David Lange wrote:
> Update on remaining items. can we finish these today?
> #18321 <https://github.com/cms-sw/cmssw/pull/18321>
- looks like today will be conclusive to signoff

> #18330 <https://github.com/cms-sw/cmssw/pull/18330>
- signed already

> #18456 <https://github.com/cms-sw/cmssw/pull/18456>
- will be signed for reco purpose, (ignoring somewhat odd choices made
at digi level)

**Comment by slava77** [comment]
The three PRs are now signed by reco
#18321
#18330
#18456

**Comment by kpedro88** [comment]
#18503 should be considered if possible - if too late, we can apply it as a patch for the phase2 production release

**Comment by kpedro88** [comment]
I guess #18199 somehow missed this list.

Also #18513 is a bug fix for #18503 (pretty simple, can be applied as a patch if necessary).

#18488 came very late...

**Comment by davidlange6** [comment]
Ah yes 18199 got dropped. I haven't looked at it since the last rearrangement.

Cheers,
David


On 28 Apr 2017, at 15:40, Kevin Pedro <notifications@github.com<mailto:notifications@github.com>> wrote:


I guess #18199<https://github.com/cms-sw/cmssw/pull/18199> somehow missed this list.

Also #18513<https://github.com/cms-sw/cmssw/pull/18513> is a bug fix for #18503<https://github.com/cms-sw/cmssw/pull/18503> (pretty simple, can be applied as a patch if necessary).

#18488<https://github.com/cms-sw/cmssw/pull/18488> came very late...
