### ISSUE TITLE
switching phase-0 deepNN b-taggers to phase-1 training

### ISSUE THREAD

**Issue by slava77** [cms-sw/cmssw#18443]
#18315 has left out the phase-0 deepNN b-taggers using old (apparently 80X-based) training.
Based on discussion in that PR, more effort is needed to check the behavior for this data taking period.

An unwanted side-effect includes complications in configuration.

**Comment by slava77** [comment]
assign reconstruction

@mverzett @imarches

**Comment by slava77** [comment]
@mverzett @kskovpen 
in RecoBTag/Combined/python/pfDeepCSVJetTags_cfi.py in  106X we are still using RecoBTag/Combined/data/DeepFlavourNoSL.json for Run1 and 2016

I wanted to check if this is still a correct choice even for the UL rereco.
Please clarify.
Thank you.

**Comment by mverzett** [comment]
@slava77 , yes, for Phase0 detector configuration is still the correct model to use.
Thanks for the thorough checks!

**Comment by slava77** [comment]
I'm closing this as obsolete or "will not fix" case.
