### ISSUE TITLE
Excessive (or not?) files open in cmsRun jobs

### ISSUE THREAD

**Issue by davidlange6** [cms-sw/cmssw#18688]
Running an 8 core reco job (1325, step3), I notice we at times have the following files open multiple times (at once):

Up to _24_ file handles at one time:
data-RecoMuon-MuonIdentification/V01-12-01/RecoMuon/MuonIdentification/data/MuID_templates_muons_lowPt_3_1_norm.root
data-RecoMuon-MuonIdentification/V01-12-01/RecoMuon/MuonIdentification/data/MuID_templates_pions_lowPt_3_1_norm.root

Up to _8_ file handles at one time:
data-RecoParticleFlow-PFProducer/V15-00-00/RecoParticleFlow/PFProducer/data/allX0histos.root

Up to _4_ file handles at one time 
the log file for the job

Can these be reduced? (the root files should all be read only accesses)

@smuzaffar @davidlt

**Comment by davidlange6** [comment]
assign core

**Comment by davidlange6** [comment]
I looked at the muon case - instead of keeping files open, it seems that they could be opened, the histograms kept and the files closed.

TFile muonFile(MuonfileName_.c_str(),"READ");
pion_em_etaEmi  = (TH2D*) pion_templates.Get("em_etaEmi");
pion_em_etaEmi->SetDirectory(0)
muonFile.Close()

(and then a delete pion_em_etaEmi would be needed)

**Comment by davidlange6** [comment]
of course this still opens the files 24 times which other solutions could also avoid

**Comment by davidlange6** [comment]
same statements can be made for allX0histos.root

**Comment by smuzaffar** [comment]
looks like 1325.0 only once have opened over 200 files. Our kibana has all the details
https://cmskibana-dev.cern.ch/_plugin/kibana/#dashboard/temp/AVv3PNH6L4W9VqGCeGgT 
looks like all the 2502nn workflows are open way too many files.

**Comment by davidlange6** [comment]
I'm trying 250202. (I would have thought 252nn would be worse...)

**Comment by davidlange6** [comment]
hi @smuzaffar - i don't really see big differences

i see the previous list plus a number of files that get opened just once (I realize I need to update my script to look at how long each file is open for). not sure how to get to hundreds, so my monitoring must be missing some file opens (proc=psutil.Process(pid=int(p)) files=proc.open_files())

1 /cvmfs/cms-ib.cern.ch/nweek-02471/share/cms/data-RecoJets-JetProducers/V05-10-20/RecoJets/JetProducers/data/pileupJetId_80XvarFix_Eta2p75to3_BDT.weights.xml.gz
1 /cvmfs/cms-ib.cern.ch/nweek-02471/share/cms/data-L1Trigger-L1TGlobal/V00-00-07/L1Trigger/L1TGlobal/data/Luminosity/startup/UGT_BASE_RS_ALGOBX_MASK_V1.xml
1 /cvmfs/cms-ib.cern.ch/nweek-02471/share/cms/data-L1Trigger-L1TMuon/V01-00-08/L1Trigger/L1TMuon/data/omtf_config/Patterns_0x0003.xml
1 /cvmfs/cms-ib.cern.ch/nweek-02471/share/cms/data-DataFormats-PatCandidates/V01-00-01/DataFormats/PatCandidates/data/CovarianceParameterization_version0.root
1 /cvmfs/cms-ib.cern.ch/nweek-02471/share/cms/data-RecoEgamma-ElectronIdentification/V01-00-07/RecoEgamma/ElectronIdentification/data/Spring16_HZZ_V1/electronID_mva_Spring16_HZZ_V1_EB2_5.weights.xml
1 /cvmfs/cms-ib.cern.ch/nweek-02471/share/cms/data-RecoEgamma-ElectronIdentification/V01-00-07/RecoEgamma/ElectronIdentification/data/TMVA_BDTSoftElectrons_7Feb2014.weights.xml
1 /cvmfs/cms-ib.cern.ch/nweek-02471/slc6_amd64_gcc530/cms/cmssw/CMSSW_9_2_X_2017-05-10-1100/src/Geometry/CMSCommonData/data/rotations.xml [strange, seems like a bug]
1 /cvmfs/cms-ib.cern.ch/nweek-02471/share/cms/data-RecoBTag-Combined/V01-00-04/RecoBTag/Combined/data/DeepFlavourNoSL.json

**Comment by slava77** [comment]
@jhgoh please take a look at 
https://github.com/cms-sw/cmssw/issues/18688#issuecomment-300756096
this was on the list of things to fix since late 2015 (see for "MuID_templates_muons_lowPt_3_1_norm.root, MuID_templates_pions_lowPt_3_1_norm.root" in your old inbox)

**Comment by davidlange6** [comment]
ok, @smuzaffar means 254nn - which with 8 threads die quickly with too many files open:)

**Comment by davidlange6** [comment]
ok, thats easy

4 /cvmfs/cms-ib.cern.ch/nweek-02471/share/cms/data-FastSimulation-MaterialEffects/V04-02-08/FastSimulation/MaterialEffects/data/NuclearInteractionsVal_piminus_E1000.root
4 /cvmfs/cms-ib.cern.ch/nweek-02471/share/cms/data-FastSimulation-MaterialEffects/V04-02-08/FastSimulation/MaterialEffects/data/NuclearInteractionsVal_piplus_E50.root
4 /cvmfs/cms-ib.cern.ch/nweek-02471/share/cms/data-FastSimulation-MaterialEffects/V04-02-08/FastSimulation/MaterialEffects/data/NuclearInteractionsVal_piplus_E3.root
4 /cvmfs/cms-ib.cern.ch/nweek-02471/share/cms/data-FastSimulation-MaterialEffects/V04-02-08/FastSimulation/MaterialEffects/data/NuclearInteractionsVal_K0L_E1.root
4 /cvmfs/cms-ib.cern.ch/nweek-02471/share/cms/data-FastSimulation-MaterialEffects/V04-02-08/FastSimulation/MaterialEffects/data/NuclearInteractionsVal_n_E500.root
4 /cvmfs/cms-ib.cern.ch/nweek-02471/share/cms/data-FastSimulation-MaterialEffects/V04-02-08/FastSimulation/MaterialEffects/data/NuclearInteractionsVal_Kminus_E4.root
4 /cvmfs/cms-ib.cern.ch/nweek-02471/share/cms/data-FastSimulation-TrackingRecHitProducer/V01-00-02/FastSimulation/TrackingRecHitProducer/data/NewPixelResolutionBarrelEdge38T.root
4 /cvmfs/cms-ib.cern.ch/nweek-02471/share/cms/data-FastSimulation-MaterialEffects/V04-02-08/FastSimulation/MaterialEffects/data/NuclearInteractionsVal_piplus_E200.root
4 /cvmfs/cms-ib.cern.ch/nweek-02471/share/cms/data-FastSimulation-MaterialEffects/V04-02-08/FastSimulation/MaterialEffects/data/NuclearInteractionsVal_Kminus_E20.root
4 /cvmfs/cms-ib.cern.ch/nweek-02471/share/cms/data-FastSimulation-MaterialEffects/V04-02-08/FastSimulation/MaterialEffects/data/NuclearInteractionsVal_Kminus_E9.root
4 /cvmfs/cms-ib.cern.ch/nweek-02471/share/cms/data-FastSimulation-MaterialEffects/V04-02-08/FastSimulation/MaterialEffects/data/NuclearInteractionsVal_nbar_E12.root
4 /cvmfs/cms-ib.cern.ch/nweek-02471/share/cms/data-FastSimulation-MaterialEffects/V04-02-08/FastSimulation/MaterialEffects/data/NuclearInteractionsVal_n_E700.root
4 /cvmfs/cms-ib.cern.ch/nweek-02471/share/cms/data-FastSimulation-MaterialEffects/V04-02-08/FastSimulation/MaterialEffects/data/NuclearInteractionsVal_n_E2.root
4 /cvmfs/cms-ib.cern.ch/nweek-02471/share/cms/data-FastSimulation-MaterialEffects/V04-02-08/FastSimulation/MaterialEffects/data/NuclearInteractionsVal_Kminus_E30.root
4 /cvmfs/cms-ib.cern.ch/nweek-02471/share/cms/data-FastSimulation-MaterialEffects/V04-02-08/FastSimulation/MaterialEffects/data/NuclearInteractionsVal_n_E50.root
4 /cvmfs/cms-ib.cern.ch/nweek-02471/share/cms/data-FastSimulation-MaterialEffects/V04-02-08/FastSimulation/MaterialEffects/data/NuclearInteractionsVal_K0L_E7.root
4 /cvmfs/cms-ib.cern.ch/nweek-02471/share/cms/data-FastSimulation-MaterialEffects/V04-02-08/FastSimulation/MaterialEffects/data/NuclearInteractionsVal_Kminus_E15.root
......
........
.......


aack

**Comment by jhgoh** [comment]
@slava77 starting now.

**Comment by davidlange6** [comment]
so the fastsim files could just be combined into bigger files with multiple trees. they are small

or we can read things into memory 

of course these files are probably 10 years old:)

**Comment by davidlange6** [comment]
this will deal with the fastsim file explosion
#18700

**Comment by davidlange6** [comment]
@dr15jones - do you have any designs avoiding the root file open per thread? Do we need to move all of that to ESProducers  and pass around the TH1Fs,TTrees,etc?

**Comment by slava77** [comment]
On 5/11/17 8:50 AM, David Lange wrote:
> @Dr15Jones <https://github.com/dr15jones> - do you have any designs
> avoiding the root file open per thread? Do we need to move all of that
> to ESProducers and pass around the TH1Fs,TTrees,etc?

There is GlobalCache

**Comment by Dr15Jones** [comment]
@slava77 is correct that GlobalCache is meant to handle that. However, one can only share items which are actually thread-safe (not just thread-friendly). TTrees are definitely not thread safe.

**Comment by davidlange6** [comment]
const TH1Fs?

**Comment by Dr15Jones** [comment]
> const TH1Fs?
Most likely?

**Comment by smuzaffar** [comment]
looks like this issue was resolved by https://github.com/cms-sw/cmssw/pull/18696 and https://github.com/cms-sw/cmssw/pull/18700 . @davidlange6 , @slava77 any objection on closing this issue?

**Comment by slava77** [comment]
+1

> Running an 8 core reco job (1325, step3), I notice we at times have the following files open multiple times (at once):
> 
> Up to _24_ file handles at one time:
> data-RecoMuon-MuonIdentification/V01-12-01/RecoMuon/MuonIdentification/data/MuID_templates_muons_lowPt_3_1_norm.root
> data-RecoMuon-MuonIdentification/V01-12-01/RecoMuon/MuonIdentification/data/MuID_templates_pions_lowPt_3_1_norm.root
> 

these were addressed in #18696 

> Up to _8_ file handles at one time:
> data-RecoParticleFlow-PFProducer/V15-00-00/RecoParticleFlow/PFProducer/data/allX0histos.root
> 

this was removed in #24863
