### ISSUE TITLE
Reco python setup times

### ISSUE THREAD

**Issue by davidlange6** [cms-sw/cmssw#18800]
fwiw, the cffs/cfis that take longest to import in a step3 MC job are these (the number is a time spent doing things other than importing other modules)

Validation.RecoTrack.TrackValidation_cff 462.200
DQM.TrackingMonitorSource.TrackingSourceConfig_Tier0_cff 284.100
DQMOffline.Trigger.TrackingMonitoring_cff 280.800
RecoTauTag.Configuration.HPSPFTaus_cff 203.100
JetMETCorrections.Configuration.JetCorrectorsAllAlgos_cff 190.400
Validation.RecoMuon.muonValidation_cff 138.600
CalibCalorimetry.HcalPlugins.Hcal_Conditions_forGlobalTag_cff 131.600
JetMETCorrections.Configuration.JetCorrectionServicesAllAlgos_cff 125.100
DQM.SiStripMonitorClient.SiStripSourceConfigTier0_cff 102.700
L1Trigger.L1TCaloLayer1.simCaloStage2Layer1Digis_cfi 102.400

[but the bigger fish in the python start up time are the various customize functions run it seems...]

**Comment by davidlange6** [comment]
https://github.com/cms-sw/cmssw/pull/18808

**Comment by smuzaffar** [comment]
@davidlange6 , was https://github.com/cms-sw/cmssw/pull/18808 enough to address this issue? can we close this now?

**Comment by davidlange6** [comment]
there are recent threads about slow startup times... but this one seems old enough not to be worth following further
