### ISSUE TITLE
new (to me) warnings from ThroughputService

### ISSUE THREAD

**Issue by davidlange6** [cms-sw/cmssw#18850]
Hi @fwyzard 

not urgent...

I noticed these in step2 workflows of a recent IB. I don't understand why these would happen from the code. 

DQMStore: WARNING: attempt to remove non-existent monitor element 'throughput_retired' in 'HLT/Throughput'
DQMStore: WARNING: attempt to remove non-existent monitor element 'throughput_sourced' in 'HLT/Throughput'

**Comment by fwyzard** [comment]
I'll take a look, but not too soon :-(

**Comment by fwyzard** [comment]
How do I assign it to myself ?

**Comment by Dr15Jones** [comment]
I think we only assign categories, not people

**Comment by Dr15Jones** [comment]
The first cmsbot message of this thread gives a link to the commands one can give http://cms-sw.github.io/cms-bot-cmssw-issues.html

**Comment by fwyzard** [comment]
I get the same warnings in 9.2.0 for the FastTimerService:
```
DQMStore: WARNING: attempt to remove non-existent monitor element 'event allocated' in 'HLT/TimerService'
DQMStore: WARNING: attempt to remove non-existent monitor element 'event allocated_byls' in 'HLT/TimerService'
DQMStore: WARNING: attempt to remove non-existent monitor element 'event deallocated' in 'HLT/TimerService'
DQMStore: WARNING: attempt to remove non-existent monitor element 'event deallocated_byls' in 'HLT/TimerService'
...
```
Did anything change with the way DQM or DQMSaver handle histograms between 9.1.x and 9.2.x ?

**Comment by Dr15Jones** [comment]
I think around that time the DQMStore was changed to try to catch cases where DQM modules failed to set the directory to which they were putting their histograms.

**Comment by davidlange6** [comment]
I had the same thought - the PR was #18562

**Comment by Dr15Jones** [comment]
I have a theory as to what might have happened. The `FastTimerService` calls the `pwd` method from DQM which ultimately just returns the member data of `DQMStore`. If another thread called a module which was talking directly to the `DQMStore` without going through the `IBooker` or `IGetter` interface, it could change the value of the member data without taking the lock. Then when `FastTimerService` calls `pwd` it would get the wrong answer.

**Comment by fwyzard** [comment]
Mhm, that would not explain why David is seeing the message for the `ThroughputService` - which does not call `pwd()`:
```c++
    // define a callback that can book the histograms
    auto bookTransactionCallback = [&, this] (DQMStore::IBooker & booker) {
      booker.setCurrentFolder(m_dqm_path);
      stream.sourced_events = booker.book1D("throughput_sourced",  "Throughput (sourced events)",   bins, 0., range)->getTH1F();
      stream.sourced_events ->SetXTitle("time [s]");
      stream.sourced_events ->SetYTitle(y_axis_title.c_str());
      stream.retired_events = booker.book1D("throughput_retired",  "Throughput (retired events)",   bins, 0., range)->getTH1F();
      stream.retired_events ->SetXTitle("time [s]");
      stream.retired_events ->SetYTitle(y_axis_title.c_str());
    };
```

**Comment by Dr15Jones** [comment]
assign hot

**Comment by Dr15Jones** [comment]
assign hlt

**Comment by smuzaffar** [comment]
@davidlange6 , do you still see these warnings?

**Comment by davidlange6** [comment]
I have no idea…sorry

On May 28, 2020, at 7:58 PM, Malik Shahzad Muzaffar <notifications@github.com<mailto:notifications@github.com>> wrote:



@davidlange6<https://github.com/davidlange6> , do you still see these warnings?

**Comment by smuzaffar** [comment]
sreaching in all runTheMatrix logs does not show any occurrence of DQMStore: WARNING:` . 
I am closing this issue, please open a new open if you again see such warnings.

[a]
```
> find . -name '*.log' | wc -l
8623
> grep -Ri 'DQMStore: WARNING:' . | wc -l
0
```
