### ISSUE TITLE
EvFDaqDirector::getStreamMergeType not thread-safe

### ISSUE THREAD

**Issue by Dr15Jones** [cms-sw/cmssw#18902]
The function EvFDaqDirector::getStreamMergeType is called by both  HLTriggerJSONMonitoring and  L1TriggerJSONMonitoring stream modules during global begin Run. This member function does a lookup and then possible updates an internal `std::map`. Now that we can run multiple modules concurrently at global begin Run, this can lead to a crash.

I suggest changing the `std::map<std::string,std::string>` to be a `tbb::concurrent_hash_map` which can support simultaneous lookup and insertion.

**Comment by Dr15Jones** [comment]
assign reconstruction, daq

**Comment by mommsen** [comment]
@srecko, can you please have a look into this?

Thanks,
Remi

**Comment by smorovic** [comment]
@smorovic is the right address :)
I switched to tbb concurrent hash map in #21658

**Comment by perrotta** [comment]
@Dr15Jones : I think this has been solved already, and it can be closed. Correct?

**Comment by Dr15Jones** [comment]
@perrotta we normally close an issue once the assigned parties have signed off on it.

**Comment by mommsen** [comment]
+1
This issue has been addressed by @smorovic in #21658

**Comment by perrotta** [comment]
+1
