### ISSUE TITLE
watch request for a few packages

### ISSUE THREAD

**Issue by seemasharmafnal** [cms-sw/cmssw#18914]
I would like to watch the following subdirs:
CondFormats/JetMETObjects
CondFormats/*
RecoParticleFlow/*
DQMOffline/JetMET
DataFormats/JetReco
DataFormats/METReco
JetMETCorrections/*
PhysicsTools/PatAlgos
PhysicsTools/PatUtils
PhysicsTools/RecoAlgos
RecoJets/*
RecoMET/*
Validation/RecoJets
Validation/RecoMET

It seems to be an old one but creating this issue to watch packages selectively following the message https://hypernews.cern.ch/HyperNews/CMS/get/git/43/1.html

Thanks & regards,
Seema

**Comment by smuzaffar** [comment]
@seemasharmafnal , please submit your changes for https://github.com/cms-sw/cms-bot/blob/master/watchers.yaml

**Comment by seemasharmafnal** [comment]
Okay. Done.
