### ISSUE TITLE
BPix hits on Track Missing 

### ISSUE THREAD

**Issue by ianna** [cms-sw/cmssw#18911]
I do not see BPIX rec hits associated with reco track [1], but I do see FPIX rechits [2]. This is from step3.root produced with:
```
cmsrel CMSSW_9_2_X_2017-05-21-2300
cd CMSSW_9_2_X_2017-05-21-2300/src/
cmsenv
runTheMatrix.py -w upgrade -l 10007.0  --command='-n 10 --geometry Extended2017Plan1' -t 6
```
[1]
![screenshot 2017-05-23 14 36 56](https://cloud.githubusercontent.com/assets/1390682/26402381/652eab76-408a-11e7-8e7b-66afdff88154.png)
[2]
![screenshot 2017-05-23 14 38 01](https://cloud.githubusercontent.com/assets/1390682/26402384/69327586-408a-11e7-9326-a90b6fb4138b.png)

**Comment by ianna** [comment]
@rovere - please, let me know if you've found the solution.

@veszpv and @slava77 - FYI

**Comment by Dr15Jones** [comment]
assign reconstruction

**Comment by slava77** [comment]
why is this reconstruction?
it seems like the question is to validation

**Comment by slava77** [comment]
it seems like the question is to ~validation~ visualization

**Comment by Dr15Jones** [comment]
@ianna which L2 do you want assigned?

**Comment by rovere** [comment]
Ciao all,
I guess we understood the issue and track it back being GEN-SIM made with autocond and re-reco made using local XML files that, most likely, have the new mapping.
We can close this, but the definitive answer will not come before monday.
M.

**Comment by ianna** [comment]
@slava77 - visualisation uses exactly the same workflow as reconstruction. If it does not show hits on track, it means they will not be there in any analysis.

**Comment by slava77** [comment]
On 5/26/17 11:13 PM, Ianna Osborne wrote:
> @slava77 <https://github.com/slava77> - visualisation uses exactly the
> same workflow as reconstruction. If it does not show hits on track, it
> means they will not be there in any analysis.
> 

Thank you for the clarification.
It looks like the issue is being fixed (Marco's comment)
