### ISSUE TITLE
(follow up to #18645) update the egmPhotonIsolation to run on miniAOD inputs

### ISSUE THREAD

**Issue by slava77** [cms-sw/cmssw#18948]
see notes in https://github.com/cms-sw/cmssw/pull/18645#issuecomment-303185939 and the following discussion

**Comment by slava77** [comment]
assign reconstruction

**Comment by slava77** [comment]
@ikrav @ishvetso 
please clarify on the status of the update to resolve this issue
Thank you.

**Comment by ikrav** [comment]
Ivan prepared a branch with a solution. However, we are also discussing 
right now the alternative solution that doesn’t compute isolation at all, and 
which simply relies on the isolation values stored in the photon object. Not
sure which one is the way to go, for various reasons.

Ilya

**Comment by slava77** [comment]
+1

this is essentially resolved by #26485
