### ISSUE TITLE
rebase instructions do not work

### ISSUE THREAD

**Issue by clelange** [cms-sw/cmssw#18999]
I was trying to follow the rebase instructions listed at http://cms-sw.github.io/tutorial-resolve-conflicts.html#rebase-the-unmergeable-branch
After setting up the latest IB for `CMSSW_9_1_X` I wanted to get the branch that I intend to rebase using
`git cms-checkout-topic -u user:branch`
but get
`git: 'cms-checkout-topic' is not a git command. See 'git --help'.`
Doing a `git cms-init` didn't help either. Is this command not supported anymore? If so, what are the new instructions?

**Comment by Dr15Jones** [comment]
Did you do a `cmsenv` In your work area first?

**Comment by clelange** [comment]
Yes, I did:
```
[clange@lxplus048]~% cd work/HGCal/testing/CMSSW_9_1_X_2017-05-29-1100/src
[clange@lxplus048]~/work/HGCal/testing/CMSSW_9_1_X_2017-05-29-1100/src% cmsenv
[clange@lxplus048]~/work/HGCal/testing/CMSSW_9_1_X_2017-05-29-1100/src% git cms-checkout-topic -u CMS-HGCAL:91X
git: 'cms-checkout-topic' is not a git command. See 'git --help'.
```

I guess `cms-checkout-topic` has been removed at some point?

**Comment by clelange** [comment]
Browsing through the repository, it seems as if the symbolic link (https://github.com/cms-sw/cms-git-tools/blob/master/git-cms-checkout-topic) by @kpedro88 does not do what it's supposed to do? It points to `cms-merge-topic`, so is that what one is supposed to do (including the unsafe option)?

**Comment by kpedro88** [comment]
Currently `cms-checkout-topic` is only included in DEVEL IBs. To access it, you should do:
```
source /cvmfs/cms-ib.cern.ch/week0/cmsset_default.csh
```
(or `.sh` if you use Bash shell)

@smuzaffar, can you give an ETA when the new tool will be available globally?

**Comment by smuzaffar** [comment]
@kpedro88 , it is part of normal IBs too so it will be part of next CMSSW_9_2_1 release.
We have to wait for cmssw 921 which will get it deployed globally.

**Comment by clelange** [comment]
OK, thanks, @kpedro88, the additional sourcing did it. I leave it to you to close this ticket whenever this is globally available (or if you want to update the instructions until then).

**Comment by smuzaffar** [comment]
this is now available via your default cms environment.
