### ISSUE TITLE
Remove GEM from era Run2_2017

### ISSUE THREAD

**Issue by dildick** [cms-sw/cmssw#19069]
@ianna @kpedro88 GEM needs to be removed from Run2_2017. https://github.com/cms-sw/cmssw/blob/CMSSW_9_2_X/Configuration/Eras/python/Era_Run2_2017_cff.py

Instead there should be `Run2_2017_GEM_SliceTest` or so, specific for GEM studies. One of my colleagues ran into this while running a simulation for Run-2 trigger studies.

Here is the command he used
<PRE>
cmsDriver.py DisplacedMuJet_Run2_cfi -s DIGI,L1,DIGI2RAW --datatier SIM-DIGI-RAW --conditions auto:run2_mc --eventcontent RAWSIM --era Run2_2017 --filein file:out_sim.root --fileout file:out_raw.root -n 10 --no_exec
</PRE>

and the error he got
<PRE>
cmsRun DisplacedMuJet_Run2_cfi_DIGI_L1_DIGI2RAW.py
L1TCalorimeter Sequence configured for Stage-2 (2016) trigger.
L1TMuon Sequence configured for Stage-2 (2016) trigger.
L1TGlobal Sequence configured for Stage-2 (2016) trigger.
L1TCalorimeter Conditions configured for Stage-2 (2016) trigger.
L1TMuon Conditions configured for Stage-2 (2016) trigger.
L1TGlobal Conditions configured for Stage-2 (2016) trigger.
L1Trigger/L1TGlobal/python/StableParameters_cff.py is deprecated, please use GlobalParameters_cff.py instead.
L1TDigiToRaw Sequence configured for Stage-2 (2016) trigger.
01-Jun-2017 17:44:03 CEST  Initiating request to open file file:out_sim.root
01-Jun-2017 17:44:07 CEST  Successfully opened file file:out_sim.root
Begin processing the 1st record. Run 1, Event 1, LumiSection 1 at 01-Jun-2017 17:44:29.028 CEST
----- Begin Fatal Exception 01-Jun-2017 17:44:49 CEST-----------------------
An exception of category 'NoRecord' occurred while
   [0] Processing  Event run: 1 lumi: 1 event: 1 stream: 0
   [1] Running path 'L1simulation_step'
   [2] Calling method for module CSCTriggerPrimitivesProducer/'simCscTriggerPrimitiveDigis'
   [3] Using EventSetup component GEMGeometryESModule/'' to make data GEMGeometry/'' in record MuonGeometryRecord
   [4] While getting dependent Record from Record MuonGeometryRecord
Exception Message:
No "GEMRecoGeometryRcd" record found in the EventSetup for synchronization value
Run: 1 LuminosityBlock: 1 Event: 0 Time: 1
 Please add an ESSource or ESProducer that delivers such a record.
----- End Fatal Exception -------------------------------------------------
Another exception was caught while trying to clean up files after the primary fatal exception.
01-Jun-2017 17:44:49 CEST  Closed file file:out_sim.root

=============================================
</PRE>

@lpernie FYI

**Comment by kpedro88** [comment]
@dildick this is not an Era issue. Your colleague is using `auto:run2_mc` with `Run2_2017` Era. These things do not go together.

If he wants to study older Run2, he should use the `Run2_2016` Era. If he wants to study 2017, he should use a 2017 GT, e.g. `auto:phase1_2017_realistic`.

**Comment by dildick** [comment]
Ok. Thanks.
