### ISSUE TITLE
interestingGedEgammaIsoESDetId is using non-existent inputs particleFlowClusterECALRemade

### ISSUE THREAD

**Issue by slava77** [cms-sw/cmssw#19113]
The ESDetId selector probably is missing some inputs. It is currently configured to use particleFlowClusterECALRemade, which do not exist.
This should be cleaned up.

@Sam-Harper @kmcdermo @fcouderc

**Comment by slava77** [comment]
assign reconstruction

**Comment by Sam-Harper** [comment]
Agreed.

**Comment by slava77** [comment]
@Sam-Harper 
it looks like this issue is still open/pending a resolution

**Comment by slava77** [comment]
> @Sam-Harper
> it looks like this issue is still open/pending a resolution

**Comment by jpata** [comment]
Looks like this is still an issue https://github.com/cms-sw/cmssw/blob/6d2f66057131baacc2fcbdd203588c41c885b42c/RecoEgamma/EgammaIsolationAlgos/python/interestingEgammaIsoDetIdsSequence_cff.py#L104

and the `interestingGedEgammaIsoESDetId` is still running in step3.

**Comment by jpata** [comment]
+reconstruction
- addressed in https://github.com/cms-sw/cmssw/pull/38036

**Comment by jpata** [comment]
@cmsbuild please close
