### ISSUE TITLE
Updates needed for singularity invocation script

### ISSUE THREAD

**Issue by DrDaveD** [cms-sw/cmssw#19183]
OSG tickets [SOFTWARE-2769](https://jira.opensciencegrid.org/browse/SOFTWARE-2769) and [SOFTWARE-2770](https://jira.opensciencegrid.org/browse/SOFTWARE-2770) should also be done for CMS.

**Comment by fwyzard** [comment]
Reading the referenced tickets, how is this a CMSSW issue ?

(also, albeit outside the scope of this issue, why do we need to keep reinventing wheels instead of using existing third-party technology ?)

**Comment by DrDaveD** [comment]
Come to think of it I guess this is wmagent or crab.  Do you know where their ticketing systems are?

Eventually this will be incorporated into glideinWMS but for now now the early adopters have their own implementation.

**Comment by DrDaveD** [comment]
I guess nobody here can answer my question.  Closing the issue.
