### ISSUE TITLE
Deprecation of specialized T**DetId 

### ISSUE THREAD

**Issue by mmusich** [cms-sw/cmssw#19398]
This is a campaign for Deprecating `T(IB|OB|ID|EC)DetId` types in view of having those removed from release, (not to be used again by copy-paste, since those break phase-II code). Namely:
   * `DataFormats/SiStripDetId/interface/T(IB|OB|ID|EC)DetId.h`

This will also take care of `(PXB|PXF)DetId` if this happens to be in the same package.
The basic solution is to access the information through `TrackerTopology` instead,  namely:
   * `DataFormats/TrackerCommon/interface/TrackerTopology.h`

that is accessible via the `edm::EventSetup`.
Working twiki: https://twiki.cern.ch/twiki/bin/viewauth/CMS/SiStripLocalReco_notesSiStripSubDetIdToTrackerTopologyMigration

Working team: Strip Local Reco Team @pieterdavid @OlivierBondu @alesaggio @vidalm 

Attn: @dimattia @boudoul

**Comment by pieterdavid** [comment]
One of the next items on our list is the migration of `TrackingTools/GsfTracking/src/DebugHelpers.h` (and the same code that is copied in `TrackingTools/TrackFitters/src/KFTrajectoryFitter.cc` and `TrackingTools/TrackFitters/src/KFTrajectorySmoother.cc`) to `TrackerTopology`. We noticed that passing on a `TrackerTopology` pointer from everywhere these objects are constructed, we would end up changing quite a bit of code (see the diff in https://github.com/pieterdavid/cmssw/compare/removeSiStripSubDetId_920p3...pieterdavid:removeSiStripSubDetId_GsfAndKFTrajectoryFitterAndSmoother_920p3 for a first version) - all pretty straightforward changes, but we were wondering if this is worth it only to keep debug helpers (that need to be compile-time enabled with `EDM_ML_DEBUG`) working.
Should we go ahead with this, or would another solution be preferred?

**Comment by mmusich** [comment]
@slava77 @VinInn could you please advice on https://github.com/cms-sw/cmssw/issues/19398#issuecomment-310374634 ? 
Thanks!

**Comment by VinInn** [comment]
another solution is preferred: no overhead for anything in EDM_ML_DEBUG outside EDM_ML_DEBUG

**Comment by mmusich** [comment]
what about removing `TrackingTools/GsfTracking/src/DebugHelpers.h` completely?

**Comment by VinInn** [comment]
btw thanks for factorizing out the debug...
I prefer to just remove the details depending from the topology, just print the detid...
please do not percolate tracker into TrackingTools...

DebugHelpers.h  is needed, just simplify and please use it also elsewhere if you can
(moveit in a better place)

**Comment by pieterdavid** [comment]
https://github.com/cms-sw/cmssw/pull/22282 closes this issue (as originally defined).
In the process we also looked into the situation for removing the pixel equivalents `PXBDetId` and `PXFDetId`, some input (especially about `PixelBarrelName` and `PixelEndcapName`) would be needed for that, idem for `SiStripDetId`, which also has some (potentially) unsafe methods - see [the twiki page](https://twiki.cern.ch/twiki/bin/viewauth/CMS/SiStripLocalReco_notesSiStripSubDetIdToTrackerTopologyMigration) for more information.

**Comment by mmusich** [comment]
https://github.com/cms-sw/cmssw/commit/ffd5bb3bbabd8340717b9c967f4f166918cb3da8 closes the issue
