### ISSUE TITLE
Issues related to applying clang-tidy to CMSSW

### ISSUE THREAD

**Issue by davidlange6** [cms-sw/cmssw#19513]
Anchor for PRs, requests, discussion

Last discussion we decided to experiment with any clang-tidy tool receiving at least 4 positive votes and no negative votes on CMSSW. The first step was to try and run each tool to let everyone see what effect it will have.

**Comment by davidlange6** [comment]
#19514 is the first experiment - for "modernize-use-nullptr"

**Comment by davidlange6** [comment]
but something has clearly gone wrong with my script - look for nullptrnullptr, which is presumably coming from a race condition - I'm trying to process one release area by subsystem using 8 threads. it seems I need to be more patient than that

**Comment by davidlange6** [comment]
ok, I've found a better script  but managed to corrupt my area in the process. It looks like modernize-use-nullptr touches ~3k files. Hopefully I'll have a PR later today for comments (and then for more tools tomorrow)

**Comment by davidlange6** [comment]
And following up on information discussed in the last meeting - the list of survey results is:

https://docs.google.com/spreadsheets/d/1TaMjsEonAtrYT_ddEGpvan0ADkPGtQPHHR3n4WjCI-Y/edit#gid=445834628

(in particular the "sorted" tab) We did not discuss options for any of the tools we decided to evaluate for enabling.

Aside from this we discussed:
 1) being sure to socialize choices made. Last week I learned Atlas started down a similar path but didn't converge (yet).
 2) we talked again about pre-commit hooks. The worry about not being able to commit "early-and-often" came up. No one knew a way around this, so we thought to enforce only at the PR stage (which is needed regardless) via jenkins)

**Comment by davidlange6** [comment]
Hi all
Please have a look and comment on
#19529 #19528 

will try to get through the rest this week

**Comment by davidlange6** [comment]
for modernize-use-override, @slava77 comments "probably keep the "virtual" specifier if it's already there. Even though it's redundant, it was our code rule 3.26."

**Comment by davidlange6** [comment]
more PRs (some of them small!)

#19550, #19551, #19552, #19553, #19554 #19555 #19556 

the change to  L1TriggerConfig/GMTConfigProducers/src/L1MuGMTParametersOnlineProducer.cc seems to be a bug,  we've gotten around it, but not in these PRs.

misc-sizeof-expression and misc-sizeof-container apparently didn't do anything. (tbc)

**Comment by davidlange6** [comment]
hi all
I got through the tools with >=5 votes and made PRs for any tool that had >0 lines of changes. The wc of git diff for each of the tools I tried is below

403 1601 22505 clangTidyTest12-boost-use-to-string
0 0 0 clangTidyTest12-clang-analyzer-core.CallAndMessage
0 0 0 clangTidyTest12-clang-analyzer-core.UndefinedBinaryOperatorResult
0 0 0 clangTidyTest12-clang-analyzer-core.uninitialized.ArraySubscript
0 0 0 clangTidyTest12-clang-analyzer-core.uninitialized.Assign
0 0 0 clangTidyTest12-clang-analyzer-core.uninitialized.Branch
0 0 0 clangTidyTest12-clang-analyzer-core.uninitialized.UndefReturn
0 0 0 clangTidyTest12-clang-analyzer-cplusplus.NewDelete
0 0 0 clangTidyTest12-clang-analyzer-deadcode.DeadStores
0 0 0 clangTidyTest12-misc-sizeof-container
0 0 0 clangTidyTest12-misc-sizeof-expression
1745 7114 85488 clangTidyTest12-misc-string-compare
67 215 3552 clangTidyTest12-misc-uniqueptr-reset-release
0 0 0 clangTidyTest12-misc-use-after-move
14553 32766 507247 clangTidyTest12-modernize-deprecated-headers
185034 827412 9083197 clangTidyTest12-modernize-loop-convert
360 1258 20028 clangTidyTest12-modernize-make-shared
0 0 0 clangTidyTest12-modernize-make-unique
19311 65731 732650 clangTidyTest12-modernize-redundant-void-arg
8730 27997 416641 clangTidyTest12-modernize-replace-auto-ptr
9064 35452 409971 clangTidyTest12-modernize-use-bool-literals
27465 96759 1415630 clangTidyTest12-modernize-use-emplace
9063 33451 430742 clangTidyTest12-modernize-use-equals-delete
117281 473942 5241847 clangTidyTest12-modernize-use-nullptr
173931 659449 7752712 clangTidyTest12-modernize-use-override
0 0 0 clangTidyTest12-performance-implicit-cast-in-loop
7821 32960 427573 clangTidyTest12-performance-unnecessary-copy-initialization
50792 203104 2596359 clangTidyTest12-performance-unnecessary-value-param
21746 104084 1169527 clangTidyTest12-readability-avoid-const-params-in-decls
31177 130496 1553509 clangTidyTest12-readability-container-size-empty
623 2042 25503 clangTidyTest12-readability-delete-null-pointer
0 0 0 clangTidyTest12-readability-redundant-declaration
6537 27124 409363 clangTidyTest12-readability-redundant-string-cstr
0 0 0 clangTidyTest12-readability-simplify-boolean-expr
1072 3390 42846 clangTidyTest12-readability-static-definition-in-anonymous-namespace
13 32 411 clangTidyTest12-readability-uniqueptr-delete-release

**Comment by smuzaffar** [comment]
@davidlange6 , I guess we can close this now.
