### ISSUE TITLE
Improvements to L1 Offline DQM - part 3

### ISSUE THREAD

**Issue by tapperad** [cms-sw/cmssw#19593]
Here is a list of requested changes to:

cmssw/DQMOffline/L1Trigger/src/L1TStage2CaloLayer2Offline.cc

The variable ETMHF should be added to the package in the same way as ETM.

The L1 quantity is extracted using the type: l1t::EtSum::EtSumType::kMissingEtHF

The corresponding Reco collection is "caloMet"

Cheers,
Alex.

**Comment by Dr15Jones** [comment]
assign dqm, l1

**Comment by tapperad** [comment]
Hi, this issue should be assigned to @kreczko please.

**Comment by thomreis** [comment]
Hi @tapperad @kreczko has this been resolved with the merged PRs? Can it be closed?

**Comment by kreczko** [comment]
@thomreis yes

**Comment by thomreis** [comment]
+1
This could be closed.

**Comment by dmitrijus** [comment]
+1
