### ISSUE TITLE
Improvements to L1 Offline DQM - part 2

### ISSUE THREAD

**Issue by tapperad** [cms-sw/cmssw#19592]
Here is a list of requested changes to:

cmssw/DQMOffline/L1Trigger/src/L1TStage2CaloLayer2Offline.cc

The default Reco MET collection should be changed to "caloMetBE" and the recoETT should be taken from the "caloMetBE" collection with the getter sumEt().

Cheers
Alex.

**Comment by tapperad** [comment]
assign kreczko

**Comment by Dr15Jones** [comment]
assign dqm, l1

**Comment by tapperad** [comment]
Hi, this issue should be assigned to @kreczko please.

**Comment by thomreis** [comment]
Hi @tapperad @kreczko has this been resolved with the merged PRs?

**Comment by kreczko** [comment]
@thomreis yes

**Comment by thomreis** [comment]
+1

**Comment by dmitrijus** [comment]
+1
