### ISSUE TITLE
Improvements to L1 offline DQM - part 1

### ISSUE THREAD

**Issue by tapperad** [cms-sw/cmssw#19590]
Here is a list of requested changes to:

cmssw/DQMOffline/L1Trigger/src/L1TStage2CaloLayer2Offline.cc

For the recoHTT and recoMHT we want to restrict the |eta| of the jets to < 2.5.

In the hardware the eta ranges and jet Et thresholds are set separately for HT and MHT (though they are currently the same value). Going forward it may be good to allow the same functionality in the DQM code i.e. separate configurable thresholds for eta range and Et threshold each for HT and MHT.

Cheers,
Alex.

**Comment by Dr15Jones** [comment]
assign dqm, l1

**Comment by tapperad** [comment]
Hi, this issue should be assigned to @kreczko please.

**Comment by thomreis** [comment]
Hi @tapperad @kreczko has this been resolved with the merged PRs?

**Comment by kreczko** [comment]
@thomreis yes

**Comment by thomreis** [comment]
+1
This could be closed.

**Comment by dmitrijus** [comment]
+1
