### ISSUE TITLE
Assign CTPPS packages to categories

### ISSUE THREAD

**Issue by kpedro88** [cms-sw/cmssw#19666]
I recently noticed messages from @cmsbuild regarding CTPPS packages without categories:
```
CondTools/CTPPS
FastSimulation/CTPPSFastGeometry
FastSimulation/CTPPSFastTrackingProducer
FastSimulation/CTPPSRecHitProducer
FastSimulation/CTPPSSimHitProducer
```

The relevant developer(s) should follow the instructions to assign these packages to categories for future code reviews:
> Please create a PR for https://github.com/cms-sw/cms-bot/blob/master/categories.py to assign category

It looks like these packages were introduced in #18021 and #18359, so @sandrofonseca, @malbouis, please take a look at this.

**Comment by kpedro88** [comment]
@sandrofonseca, @malbouis another reminder

**Comment by kpedro88** [comment]
@sandrofonseca, @malbouis why is this not done yet?

**Comment by sandrofonseca** [comment]
Hi Kevin,

My apologies, I had forgotten completely it.

I already opened PR for CT-PPS FastSimulation packages also you can found
in this link: https://github.com/cms-sw/cms-bot/pull/918

Best regards,
Sandro


Dr. Sandro Fonseca de Souza
__________________________________
Universidade do Estado do Rio de Janeiro - UERJ/IF/DFNAE
524 São Francisco Xavier Street,3rd Floor,Office 3016A, Maracanã, Rio de
Janeiro,
Brazil.
ZIP Code: 20559-900
Phone: +552123340623
Brazilian Mobile: +5521982359943
Swiss Mobile:+41762079804
WhatsApp:+5521982359943
Skype Name: sandro_fonseca
MSN: sandrofonsecauerj@hotmail.com
C.Lattes:http://lattes.cnpq.br/4560612419350680
Home page: http://www.fis.uerj.br
------------------------------------------------
CERN - European Laboratory for Particle Physics
CH - 1211 Geneva 23
Tel:74949 (from outside: +41 22 76 74949 )
Office: 32 4-C14 Mailbox: J19910
email: sfonseca@cern.ch
Linkedin profile:
http://ch.linkedin.com/pub/sandro-fonseca-de-souza/29/85a/480

**Comment by kpedro88** [comment]
@sandrofonseca `CondTools/CTPPS` still needs a category assignment

**Comment by sandrofonseca** [comment]
HI Kevin,

 I am cc'ing my colleague Helena who is the responsible person for it.

Cheers,
Sandro


Dr. Sandro Fonseca de Souza
__________________________________
Universidade do Estado do Rio de Janeiro - UERJ/IF/DFNAE
524 São Francisco Xavier Street,3rd Floor,Office 3016A, Maracanã, Rio de
Janeiro,
Brazil.
ZIP Code: 20559-900
Phone: +552123340623
Brazilian Mobile: +5521982359943
Swiss Mobile:+41762079804
WhatsApp:+5521982359943
Skype Name: sandro_fonseca
MSN: sandrofonsecauerj@hotmail.com
C.Lattes:http://lattes.cnpq.br/4560612419350680
Home page: http://www.fis.uerj.br
------------------------------------------------
CERN - European Laboratory for Particle Physics
CH - 1211 Geneva 23
Tel:74949 (from outside: +41 22 76 74949 )
Office: 32 4-C14 Mailbox: J19910
email: sfonseca@cern.ch
Linkedin profile:
http://ch.linkedin.com/pub/sandro-fonseca-de-souza/29/85a/480

**Comment by kpedro88** [comment]
@sandrofonseca ping (not sure of Helena's username)

**Comment by kpedro88** [comment]
@sandrofonseca how is it possible that this is still not done?

**Comment by sandrofonseca** [comment]
For CTPPS FastSimulation packages was done in this PR below:

https://github.com/cms-sw/cms-bot/pull/918

Concerning DB CT-PPS category, I suggest that you should contact Helena:
@malbouis


Dr. Sandro Fonseca de Souza
__________________________________
Universidade do Estado do Rio de Janeiro - UERJ/IF/DFNAE
524 São Francisco Xavier Street,3rd Floor,Office 3016A, Maracanã, Rio de
Janeiro,
Brazil.
ZIP Code: 20559-900
Phone: +552123340623
Brazilian Mobile: +5521982359943
Swiss Mobile:+41762079804
WhatsApp:+5521982359943
Skype Name: sandro_fonseca
MSN: sandrofonsecauerj@hotmail.com
C.Lattes:http://lattes.cnpq.br/4560612419350680
Home page: http://www.fis.uerj.br
------------------------------------------------
CERN - European Laboratory for Particle Physics
CH - 1211 Geneva 23
Tel:74949 (from outside: +41 22 76 74949 )
Office: 32 4-C14 Mailbox: J19910
email: sfonseca@cern.ch
Linkedin profile:
http://ch.linkedin.com/pub/sandro-fonseca-de-souza/29/85a/480

**Comment by malbouis** [comment]
Hi,

Can you please point me to instructions on how to do it?

Thanks.

**Comment by kpedro88** [comment]
Here are the instructions given by the bot:
```
Please create a PR for https://github.com/cms-sw/cms-bot/blob/master/categories_map.py to assign category
```

**Comment by malbouis** [comment]
Doesn't really look like instructions to me. 🤔😜
Thanks anyways.

**Comment by kpedro88** [comment]
To make a pull request:
1. make a fork of https://github.com/cms-sw/cms-bot (click the "fork" button at the top right)
2. make a local copy of the repository: `git clone git@github.com:malbouis/cms-bot.git`
3. make a new branch and edit the categories_map.py file:
```
cd cms-bot
git checkout -b addCTPPS
[edit categories_map.py]
git commit -a -m "add CTPPS db package"
git push origin addCTPPS
```
4. Submit a pull request: https://github.com/cms-sw/cms-bot/compare/master...malbouis:addCTPPS?expand=1

This whole process should take 5 minutes. It is unbelievable that this issue has been pending for almost a year.
