### ISSUE TITLE
edmWriteConfigs writing duplicate and conflicting cfi files

### ISSUE THREAD

**Issue by wddgit** [cms-sw/cmssw#19690]
This problem is caused by modules that do not properly implement the
fillDescriptions function. In the case that was originally reported on
the swDevelopment hypernews on 10 July 2017, a module plugin inherited
from another module plugin. The base class plugin defined fillDescriptions and
included a module label (which causes cfi file generation). The inherited class
did not define fillDescriptions and so used the same fillDescriptions function as
the base class. This is one way to cause the problem. One could also
explicitly give the same module label twice. I am adding code to edmWriteConfigs
that will detect and report such errors as an exception in the build that occur
within the same invocation of edmWriteConfigs.  This is finding some number
of such errors that already exist in the CMSSW code base. The job checking
this is running at the moment and will take a while before I know how many.

**Comment by Dr15Jones** [comment]
assign core

**Comment by wddgit** [comment]
@fwyzard I added the -x or --plugin feature into edmWriteConfig. I will submit it with the other new code in a separate commit in the same PR. @Martin-Grunewald.

**Comment by wddgit** [comment]
Here is the full list of errors I found with the new check. I modified ConfigurationDescriptions.h and I think that pulled in all the packages that could be affected by this. This includes the four I already mentioned. I will start looking at these in the half an hour I have before I head home, but if anyone wants to volunteer to fix them that would be great (4 have HLT in the name). There were also 3 in Core code that I fixed earlier today.

ERROR cfiWrite ShmStreamConsumer module label = "EvFOutputModule"
ERROR cfiWrite DQMFileSaverPB module label = "saver"
ERROR cfiWrite PatJetConstituentSelector module label = "JetConsituentSelector"
ERROR cfiWrite MiniAODJetConstituentSelector module label = "JetConsituentSelector"
ERROR cfiWrite SubjetFilterJetProducer module label = "VirtualJetProducer"
ERROR cfiWrite HTTTopJetProducer module label = "FastjetJetProducer"
ERROR cfiWrite CMSInsideOutJetProducer module label = "VirtualJetProducer"
ERROR cfiWrite SubEventGenJetProducer module label = "VirtualJetProducer"
ERROR cfiWrite HLTPhoTagAndProbeOfflineSource module label = "hltTagAndProbeOfflineSource"
ERROR cfiWrite HLTElePhoTagAndProbeOfflineSource module label = "hltTagAndProbeOfflineSource"
ERROR cfiWrite HLTMuEleTagAndProbeOfflineSource module label = "hltTagAndProbeOfflineSource"
ERROR cfiWrite HLTMuTagAndProbeOfflineSource module label = "hltTagAndProbeOfflineSource"

**Comment by wddgit** [comment]
There is one weakness in the test I added. It would detect if two plugins in the same library were trying to write cfi files with the same name. But if there were two such plugins in the same package but not in the same plugin library, this check would miss the problem. In many cases, where there is more than one plugin library in the same package, they are all test libraries except for one. Given how rare this is and that it should be more rare for tests, my first thought is that it is not worth the effort of pursuing these. My best idea would be to add additional printout to the build log (every cfi filename) and scan the build log with a script that detects duplicate cfi filenames. Unless someone asks me to I am not planning on doing this.

**Comment by Martin-Grunewald** [comment]
Dear David,

It would be great if you could fix all of them and then turn on exception failures such that newly submitted code in PRs gets fixed by the developers themselves - ie, can it be hooked to jenkins tests?

If the filename is the same but they are in different plugin directories, that would be OK for ConfDB parsing, as then there would not be any overwriting.
What would not be OK would be same or different filename in same or different directories but containing the same plugin class name and  different parameters. That would need safeguarding as then for that plugin we'd get ordering-dependent ambiguity on what are its parameters.

**Comment by wddgit** [comment]
Dear Martin,

By design, ConfigurationDescriptions allows the same plugin class to have multiple descriptions, one for each module label plus optionally one default description. For each module label a cfi file is generated. And these different descriptions are allowed to have completely different parameters, not just different parameter values. If I read your last comment correctly, this is a problem for ConfDB. I am not sure what to say about that, but if that is a problem then some discussion is needed. Can ConfDB itself detect this situation?

The problem I was trying to address was different cfi files in the same directory having the same file name and one overwriting the other. Different packages have different cfipython subdirectories, so there would be no problems with plugins in different packages. Within a package, my new check would detect problems within the same library, which should get all the inheritance related problems and single plugin problems. The only ones my new check would fail to find would be two plugins that are not related by inheritance, in the same package but not the same plugin library, and which use the same module label for a ParameterSetDescription. With any luck those might be rare enough for there to be none.

I will start making fixes for the problems the new test identified (except for HTTTopJetProducer which I can see was fixed and the fix was already merged). And as soon as I have fixes for them, I will submit this PR. Even if there is more work to do, this will move things forward.

**Comment by Martin-Grunewald** [comment]
Hmm, ConfDB allows for each plugin only one so-called template == list ot top level parameters (fixing name and type but not value). If during parsing several are found for the same plugin, it either takes the first found, or a big OR. It is still OK if the different ones are in different files because we can specify a preferred cfi file by its filename.

**Comment by wddgit** [comment]
Then we should be OK, because the cfi filenames should be different. The module label is in the autogenerated cfi filename.

**Comment by Martin-Grunewald** [comment]
OK!

**Comment by wddgit** [comment]
@smuzaffar Is there a way to force the PR tests to do a complete build when I submit the PR. I probably caught all the problems by changing ConfigurationDescriptions.h and pulling in the packages depending on it (700+ packages), but I think it might be possible to miss something if someone organized their code in an unusual way.

**Comment by wddgit** [comment]
@smuzaffar I figured out how to force a full build manually in a local working area so I do not need to do it with the PR any more. Not difficult, I just had not ever done it before. I am still curious if there already exists some way to do it with the PR testing, but I am not asking you to implement anything new. I will probably submit the tomorrow morning after this build completes.

**Comment by wddgit** [comment]
This should be resolved by PR #19729

**Comment by Dr15Jones** [comment]
+1
