### ISSUE TITLE
LogWarning OutOfBounds: in  TrackProducer or TrackRefitter

### ISSUE THREAD

**Issue by slava77** [cms-sw/cmssw#19805]
```
%MSG-w OutOfBounds:  TrackProducer:highPtTripletStepTracks  18-Jul-2017 18:53:25 CEST Run: 299042 Event: 17210114
Prob Q outside the bounds of the quality word. Defaulting to Prob=0. Prob = 1 QualityWord = 267
```
in this case I was looking at reco processing of 
/store/data/Run2017B/JetHT/RAW/v1/000/299/042/00000/1046825C-D368-E711-A36B-02163E011DF9.root
Here it appears in about 10% of the events.

From the logs of past tests I see that it appears also since at least 80X, e.g. in CMSSW_8_0_28 wf 136.771.

If the warning is not essential, perhaps it's time to demote to LogInfo?

@makortel @rovere @VinInn

**Comment by slava77** [comment]
assign reconstruction

**Comment by VinInn** [comment]
I think you have to enquire with DPG
https://cmssdt.cern.ch/lxr/source/DataFormats/TrackerRecHit2D/interface/SiPixelRecHitQuality.h#0084

**Comment by slava77** [comment]
@veszpv @boudoul please take not of this LogWarning
Thank you.

**Comment by VinInn** [comment]
we need to verify if #20904 fixes this as well

**Comment by perrotta** [comment]
@VinInn : I quickly run the same

**Comment by perrotta** [comment]
@VinInn : I quickly run the same 136.783 workflow which shows that warning at step3 for event 90 (Run 297557, Event 109105292, LumiSection 74), see
https://cmssdt.cern.ch/SDT/cgi-bin/buildlogs/slc7_aarch64_gcc700/CMSSW_9_4_X_2017-10-15-0000/pyRelValMatrixLogs/run/136.783_RunJetHT2017B+RunJetHT2017B+HLTDR2_2017+RECODR2_2017reHLT_skimJetHT_Prompt+HARVEST2017/step3_RunJetHT2017B+RunJetHT2017B+HLTDR2_2017+RECODR2_2017reHLT_skimJetHT_Prompt+HARVEST2017.log
and I verified that the warning is not there any more.

Ok, low stat check, but it seems that  #20904 can also fix this issue...

**Comment by VinInn** [comment]
a cure for all pains...

**Comment by slava77** [comment]
just to not that the logwarning is still present in 10_3_X
the issuing code is DataFormats/TrackerRecHit2D/interface/SiPixelRecHitQuality.h
e.g. in 10_3_0_pre5 in wf 136.731
```
%MSG-w OutOfBounds:  TrackProducer:mergedDuplicateTracks  06-Oct-2018 21:39:20 CEST Run: 274199 Event: 38618538
Prob Q outside the bounds of the quality word. Defaulting to Prob=0. Prob = 1 QualityWord = 16383
```

@tsusa please tag [@] someone in the pixel community who may address or explain this

**Comment by tsusa** [comment]
@pmaksim1 could you please have a look at this LogWarning issue?

**Comment by pmaksim1** [comment]
I'll look into it later today, but this code hasn't changed in O(10) years...

**Comment by pmaksim1** [comment]
@slava77 @VinInn @tsusa @perotta 
Coming back to this... The error message comes from somebody trying to set probabilityQ() which is garbage.  So, I need to look at the stack trace -- I'd like to run the whole job in gdb and see who calls this with the offending value and why.  (Namely, the problem is upstream of this function -- don't shoot the messenger...)

So can I simply run workflow 136.731 in 10_3_0_pre5 and I'll eventually see it?  (A clear example may help me get faster to gdb...)  Thanks!

**Comment by slava77** [comment]
In 10_6_0
workflow 
```
Begin processing the 105th record. Run 320822, Event 54320731, LumiSection 35
...
%MSG-w OutOfBounds:  TrackProducer:lowPtTripletStepTracks  16-May-2019 02:41:29 CEST Run: 320822 Event: 54320731
Prob Q outside the bounds of the quality word. Defaulting to Prob=0. Prob = 1 QualityWord = 0
```

@pmaksim1 please check or pass it to somebody

**Comment by pmaksim1** [comment]
@slava77 Which workflow was this?  (Would help me set up the job with the gdb.)

**Comment by pmaksim1** [comment]
Is it one of the matrix ones?

**Comment by slava77** [comment]
> @slava77 Which workflow was this? (Would help me set up the job with the gdb.)

sorry, I was supposed to say "workflow 136.889"

**Comment by smuzaffar** [comment]
looks like this warnings still present in many `134.*` and `136.*` workflows [a]

**Comment by smuzaffar** [comment]
Looks like this has been fixed , I do not see this LogWarning any more in any workflow.
