### ISSUE TITLE
close the CMSSW_9_2_3_patchX branch

### ISSUE THREAD

**Issue by fwyzard** [cms-sw/cmssw#19879]
Hi,
to avoid confusing the developers, would it make sense to close the CMSSW_9_2_3_patchX branch ?
Is it even possible ?

.A

**Comment by davidlange6** [comment]
its as closed as we can make it aside from a) deleting the branch or b) automating some nasty note when a PR is made. @smuzaffar do we lose any history by deleting the branch?

**Comment by smuzaffar** [comment]
@davidlange6 , I see that both https://github.com/cms-sw/cmssw/tree/CMSSW_9_2_3_patchX branch and https://github.com/cms-sw/cmssw/tree/CMSSW_9_2_3_patch2 tag use the same commit so deleting this branch should not lose any history

**Comment by smuzaffar** [comment]
CMSSW_9_2_3_patchX  branch is delete. CMSSW_9_2_3_patch2 tag can be used to create a new branch if needed.
