### ISSUE TITLE
provide functionality to count missing hits from inactive [pixel] detectors beyond the extremes of the trajectory

### ISSUE THREAD

**Issue by slava77** [cms-sw/cmssw#19940]
#19881 has (finally) introduced a check for inactive components "badComponents" during filling the secondary (missing inner and outer) hit patterns, in addition to already available check for the full measurement det inactive.
For pixels a some fraction of inactive dets  was set only in the "badComponents" (bad ROCs from SiPixelQualityFromDbRcd).
So, analysis/ID selections relying on missing inner hits were inadvertently developed in part by counting actual inactive subdetectors as missing hits.

This issue is to add information to the hitPattern to be able to independently count inactive layers beyond the extremes of the trajectory (saved in the missing_inner and missing_outer parts)
and not interfere with the missing hits/layer functionality originally designed to ignore inactive areas.

@arizzi @gpetruc @VinInn @makortel @rovere

**Comment by slava77** [comment]
assign reconstruction

**Comment by VinInn** [comment]
Please add beyond the extremes of the trajectory
Those inside a trajectory are already accounted for.
a possibility (somehow backward incompatible) is to add a "hit type" to the MISSING_INNER/OUTER
category.
This will require some changes to the interface and implementation of HitPattern and most probably major changes in client code (including MiniAOD packing I suspect)

**Comment by slava77** [comment]
title and description were updated

**Comment by VinInn** [comment]
addressed in #20938
