### ISSUE TITLE
Broken ROOT python bindings in 93X?

### ISSUE THREAD

**Issue by mverzett** [cms-sw/cmssw#19945]
Dear experts,

in the latest 93X IB and pre-releases I encountered a problem with one of my [debugging scripts](https://gitlab.cern.ch/mverzett/URNtuples/blob/Moriond17/Utilities/scripts/inspect_edObject.py).

The script crashes with the following error:
```
[mverzett@lxplus076 src]$ python inspect.py ../../CMSSW_9_3_X_2017-07-20-2300/src/patTuple_updateJets_fromMiniAOD.root 'vector<pat::Jet>' selectedUpdatedPatJets
Traceback (most recent call last):
  File "inspect.py", line 23, in <module>
    import ROOT
  File "/cvmfs/cms.cern.ch/slc6_amd64_gcc630/lcg/root/6.10.01/lib/ROOT.py", line 150, in <module>
    import inspect
  File "/afs/cern.ch/work/m/mverzett/CMSSW_9_3_0_pre2/src/inspect.py", line 25, in <module>
    from DataFormats.FWLite import Events, Handle
  File "/cvmfs/cms.cern.ch/slc6_amd64_gcc630/cms/cmssw/CMSSW_9_3_0_pre2/python/DataFormats/FWLite/__init__.py", line 10, in <module>
    ROOT.gSystem.Load("libFWCoreFWLite")
AttributeError: 'module' object has no attribute 'gSystem'
```

Even more strangely, if I try to call the python shell from the same directory and import ROOT I get
```
[mverzett@lxplus076 src]$ python
Python 2.7.11 (default, Apr 28 2017, 13:50:27)
[GCC 6.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import ROOT
usage: [-h] [--pick PICK] file handle label
: error: too few arguments
```

Like root is still running my script and wanting the same input arguments as my script. If I run the same commands in an empty directory there is no problem

```
[mverzett@lxplus076 dummy]$ python
Python 2.7.11 (default, Apr 28 2017, 13:50:27)
[GCC 6.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import ROOT
>>> ROOT.gSystem
<ROOT.TUnixSystem object ("Unix") at 0xb96080>
>>> ROOT.gSystem.Load("libFWCoreFWLite")
0
>>>
```

Has this issue already been reported? Do you know the cause of it?
Thanks

Mauro

**Comment by davidlange6** [comment]
Hi Mauro
I don't really see how to reproduce the problem.

[dlange@lxplus043 dlange]$ scram p CMSSW_9_3_X_2017-07-27-2300
[dlange@lxplus043 dlange]$ python
Python 2.7.11 (default, Apr 28 2017, 13:50:27) 
[GCC 6.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import ROOT
>>> 

any recipe you can provide?

**Comment by mverzett** [comment]
@davidlange6 
thanks for looking into this. Here is a recipe to reproduce the problem

```
scram p CMSSW_9_3_X_2017-07-27-2300
cd CMSSW_9_3_X_2017-07-27-2300
cmsenv
cp /afs/cern.ch/user/m/mverzett/public/inspect.py .
#the following command crashes because of gSystem
./inspect.py ../../CMSSW_9_3_X_2017-07-20-2300/src/patTuple_updateJets_fromMiniAOD.root 'vector<pat::Jet>' selectedUpdatedPatJets
```

Then calling python and importing ROOT in the same directory gives that weird error. I tried to log off/in again and got the same result even without calling inspect in advance and got the same result, hence I do not believe is my script messing up the environment.

**Comment by davidlange6** [comment]
Thanks - indeed I reproduce - the fix looks to be to give your script a different name. "inspect" is a name of a common python package.

**Comment by mverzett** [comment]
@davidlange6 indeed that's the cause. 
Thanks for pointing it out and sorry for the false alarm.
