### ISSUE TITLE
Optimize reducedEalRecHits for HI 

### ISSUE THREAD

**Issue by perrotta** [cms-sw/cmssw#20076]
@mandrenguyen 
@jainshilpi @Sam-Harper 

It was noticed in https://github.com/cms-sw/cmssw/pull/19927#issuecomment-320280028 that the reduced Ecal recHits take significantly longer in HI reconstruction that in pp one. Extracting from that list:

added      +1.62%         0.00 ms/ev ->      215.38 ms/ev reducedEcalRecHitsEB
added      +0.28%         0.00 ms/ev ->        36.92 ms/ev reducedEcalRecHitsEE
added      +0.11%         0.00 ms/ev ->        14.42 ms/ev reducedEcalRecHitsES

Also the following EGamma modules are eating a non negligible fraction of the CPU:

   added      +0.02%         0.00 ms/ev ->         2.53 ms/ev interestingGamIsoDetIdEB
   added      +0.02%         0.00 ms/ev ->         2.64 ms/ev interestingGamIsoDetIdEE
   added      +0.20%         0.00 ms/ev ->       26.57 ms/ev interestingGedGamIsoDetIdEB
   added      +0.04%         0.00 ms/ev ->         4.97 ms/ev interestingGedGamIsoDetIdEE
   added      +0.04%         0.00 ms/ev ->         5.77 ms/ev interestingEcalDetIdPFEB
   added      +0.02%         0.00 ms/ev ->         2.85 ms/ev interestingEcalDetIdPFEE

(those times were computed running a wf 140.53, re-reco of 2015 HI data,  on cmsdev02). 

All those modules, while new for the HI reconstruction, are already running in current pp reco.
As computed by @slava77, the total time for these modules in PU35 is 19 ms/evt (total reco is ~16 s). Even with PU75, they are only at 38 ms (of the total reco of 53 s here).

It may be expected that there is some larger electron fakerate in HI events, and this will inevitably affect those timings. Due to that, some optimization of the parameters or of the code itself could be envisaged before some large HI production is started. 

I will try to run  a profile on these jobs in the next days, and post here the output.
But if there are already ideas or suggestions to mitigate it they are all welcome.

**Comment by perrotta** [comment]
assign reconstruction

**Comment by Sam-Harper** [comment]
Hmm, that does seem excessive. Perhaps we need to tighten the selection criteria for what is "interesting" for HI

**Comment by smuzaffar** [comment]
was there any process on this?

**Comment by Sam-Harper** [comment]
No. Not to my knowledge

**Comment by smuzaffar** [comment]
is this still an open issue @perrotta ?

**Comment by perrotta** [comment]
> is this still an open issue @perrotta ?

Let @mandrenguyen decide: he being both a HI expert and the current reco convener, Matt can judge best if there is some optimization still possible in those reducedEcalRecHits

**Comment by mandrenguyen** [comment]
In the last profiling we ran of 140.56 in 12_5_0 i see that these reduced ECAL rechits take about  0.1% of the reconstruction time combined.  Not sure this warrants any further investigation.

**Comment by mandrenguyen** [comment]
+1
