### ISSUE TITLE
Add "hasTrackDetails()" to Fix PackedCandidate in TrackAndVertexUnpacker.cc 

### ISSUE THREAD

**Issue by weishi10141993** [cms-sw/cmssw#20105]
This issue is discussed in: https://github.com/cms-sw/cmssw/issues/19151#issuecomment-307418069
and in:
https://github.com/cms-sw/cmssw/pull/19025#issuecomment-306699120

I saw experts have made changes in some source files, like: https://github.com/cms-sw/cmssw/commit/9dc159582b473fa35975c8f5c62610a47ae2dcd0

Would it be possible to add "hasTrackDetails()" in https://github.com/cms-sw/cmssw/blob/d9f776583c484ede14ec73b52d87e72864daa970/PhysicsTools/PatAlgos/plugins/TrackAndVertexUnpacker.cc#L86-L99
since PackedCandidate "lostTracks" and "packedPFCandidates" is also used in this?

**Comment by slava77** [comment]
assign analysis

**Comment by slava77** [comment]
@weishi10141993 
if you are reasonably familiar with the code already, may I suggest that you make the PR with changes.
This should expedite the update (also considering that it is August).

**Comment by weishi10141993** [comment]
I've tested the change on my local machine and made the PR: https://github.com/cms-sw/cmssw/pull/20114

**Comment by smuzaffar** [comment]
@weishi10141993 , looks like this was resolved by https://github.com/cms-sw/cmssw/pull/20197 .  Can we close this?

**Comment by weishi10141993** [comment]
Sure.
