### ISSUE TITLE
How to apply code style suggestion in git-diff.patch

### ISSUE THREAD

**Issue by dildick** [cms-sw/cmssw#20135]
The CMSSW code style was updated recently. The bot is checking each PR and makes a suggestion such as: https://cmssdt.cern.ch/SDT/jenkins-artifacts/pr-code-checks/PR-19990/64/git-diff.patch. Is there a way to have the bot apply them after a command e.g. `@cmsbuild apply-code-syle-patch`? If that is not possible, is there an easy way for users to apply the suggestion?

**Comment by Dr15Jones** [comment]
assign core

**Comment by smuzaffar** [comment]
@dildick , cms-bot can do the automatic apply of the patch but I am afraid then this will be abused and dev's might not run it before making the PR.

One can apply the patch by doing the following
```
CMS_VER=`scram list -c CMSSW_9_3_X | tail -1 | awk '{print $2}'`
scram project  $CMSVER
cd $CMSVER/src
cmsenv
git cms-checkout-topic <PR>
scram build code-checks
scram build
scram build runtests
#and run any other tests needed
git push my-cmssw <branch-used-to-make-pr>
```

Current idea is that, devs, after making their changes run 'scram build code-checks' and compile and test the final changes before making a PR.

**Comment by fwyzard** [comment]
if the patches were on a publicly accessible page, one could just do

wget -q -O - https://cmssdt.cern.ch/SDT/jenkins-artifacts/pr-code-checks/PR-19990/64/git-diff.patch | patch -p1

**Comment by dildick** [comment]
@smuzaffar I just tried it out. I think `scram build code-checks` is just fine. Thanks!

**Comment by smuzaffar** [comment]
patches are now accessible publicly via  https://cmssdt.cern.ch/SDT/code-checks/.... 
cms-bot is updated to mention the new url.
