### ISSUE TITLE
review or confirm OOT photon reco selections in HI

### ISSUE THREAD

**Issue by slava77** [cms-sw/cmssw#20165]
@kmcdermo @mandrenguyen @Sam-Harper in case there is a continued use case for OOT photons in HI reco, it may be worth to check the selections. IIUC, they appeared in HI "for free" as a result of updates to default photon sequences. However, the HI reco overrides some thresholds and selections which may have missed possibly needed changes for OOT photons.

I noticed some changes in connection with
https://github.com/cms-sw/cmssw/pull/20045#issuecomment-322235006
The ootPhotonCore in HI has 8 GeV threshold while the ootPhotons have 10 GeV. 
There may be more.

**Comment by slava77** [comment]
assign reconstruction

**Comment by kmcdermo** [comment]
@slava77 , I really cannot say what HI might need with ootPhotons, and as mentioned in the PR by Marco, they came for "free" when we were developing them.  I guess this is more of a question for the EGM in coordination with the HI experts.

**Comment by Sam-Harper** [comment]
I think this is more of a question to the HI experts, at least for the initial recommendations. So I will wait for their input and comments.

**Comment by mandrenguyen** [comment]
We expect negligible OOT PU, when for data in which the HI reco sequence is invoked.  Does that help to clarify?

**Comment by Sam-Harper** [comment]
So I think this is rapidly concluding as "nobody really cares about OOT photons in HI". So we can either disable the production if it is costing diskspace/cpu in HI or leave as is.

**Comment by mandrenguyen** [comment]
Disable seems to make sense.

**Comment by slava77** [comment]
On 8/16/17 12:44 AM, Matthew Nguyen wrote:
> We expect negligible OOT PU, when for data in which the HI reco sequence
> is invoked. Does that help to clarify?

the main target for this ootPhoton reco is not OOT PU from 25 ns away or
more,
the target is primarily photons that could be reconstructed with times
about 3ns and more.
The regular PF reco rejects ECAL hits with large times.
The oot photon reco  targets long-lived particles
(and for some background studies it also gives access to the negative
tail of the reco photon phase space, as from beam halo or similar)

**Comment by mandrenguyen** [comment]
Beam background studies certainly sound potentially useful.  I did a small test and these collections appear to be both fast to produce and light in terms of output size, so there appears to be no serious constraint on that front.  In general we are trying to figure out how to tune thresholds for the egamma sequences.  See the hypernews thread from @ttrk :  https://hypernews.cern.ch/HyperNews/CMS/get/egamma/1959.html   Incidentally, I'm at CERN until next Wednesday, in case any of the relevant egamma experts have a few mins to discuss.

**Comment by kmcdermo** [comment]
I am also at CERN to join any discussions on these objects.

**Comment by mandrenguyen** [comment]
@Sam-Harper Are you also at CERN and available for a coffee length chat next week?

**Comment by Sam-Harper** [comment]
Yes I am but I'm on call so will not be around in the mornings most likely. Tuesday afternoon?

**Comment by mandrenguyen** [comment]
great!  @ttrk can join as well. Either during 1-2PM or anytime after about 3PM should work.

**Comment by mandrenguyen** [comment]
Does 3PM in the B40 lobby work?

**Comment by Sam-Harper** [comment]
ah so the run meeting is at 15:00. I can do anytime after 13:30 as long I finish by 15:00

**Comment by mandrenguyen** [comment]
@ttrk has a talk at 14:00.  Are you free at all after the run meeting?

**Comment by Sam-Harper** [comment]
yes

**Comment by mandrenguyen** [comment]
Just shoot us a message when you're free and we'll head over.  We're sitting in a workshop, but we can skip out.

**Comment by mandrenguyen** [comment]
It looks like we didn't manage to discuss today.  I leave tomorrow at 2PM.  Any chance we can discuss before that?

**Comment by Sam-Harper** [comment]
Yes sorry, p5 emergency came up and its only just resolved. I dont think we will be able to discuss because unfortunately I'm on call and things like this come up so I cant reliably commit to a meeting tomorrow either. 

There is the possibility of 13:15 ish tomorrow but again something could come up.

**Comment by mandrenguyen** [comment]
understood.  If you manage to avoid an emergency tomorrow give us a holler.

**Comment by Sam-Harper** [comment]
So I'm free for a chat at 13:30 in B40.

**Comment by ttrk** [comment]
good. we are in B40 now.

**Comment by slava77** [comment]
@ttrk @Sam-Harper @mandrenguyen 
please clarify if there were any action items following the meeting in August.
Thank you.

**Comment by ttrk** [comment]
@slava77 There is no particular use case for OOT photons in HI reco.

**Comment by slava77** [comment]
On 10/24/17 3:00 PM, Kaya Tatar wrote:
> @slava77 <https://github.com/slava77> There is no particular use case
> for OOT photons in HI reco.

Is it just a result of the current physics program scope?
I can imagine some models of enhanced or even just different production
in HI collisions can lead to some interest.

Anyhow, the differences in thresholds are not conceptually different.
So, the current default should probably work.

**Comment by ttrk** [comment]
As of now these objects do not have a use case for HI analysis and probably will not have for the near future.

**Comment by slava77** [comment]
closing as "not an issue"
