### ISSUE TITLE
cmsDriver.py is calling convertToUnscheduled at the wrong time

### ISSUE THREAD

**Issue by Dr15Jones** [cms-sw/cmssw#20203]
Looking at the results of 
```
cmsDriver.py step3 --conditions auto:phase1_2017_realistic -n 10 --era Run2_2017 --eventcontent AODSIM,MINIAODSIM,DQM --runUnscheduled -s RAW2DIGI,L1Reco,RECO,EI,PAT,DQM:@common+@miniAODDQM --datatier AODSIM,MINIAODSIM,DQMIO --customise SimGeneral/DataMixingModule/customiseForPremixingInput.customiseForPreMixingInput --customise Validation/Performance/TimeMemorySummary.customiseWithTimeMemorySummary --filein file://step2.root --fileout step3.root --nThreads=4 --no_exec
```

I found that 
```
# Automatic addition of the customisation function from PhysicsTools.PatAlgos.slimming.miniAOD_tools
from PhysicsTools.PatAlgos.slimming.miniAOD_tools import miniAOD_customizeAllMC 

#call to customisation function miniAOD_customizeAllMC imported from PhysicsTools.PatAlgos.slimming.miniAOD_tools
process = miniAOD_customizeAllMC(process)
```

was being called after
```
# End of customisation functions
#do not add changes to your config after this point (unless you know what you are doing)
from FWCore.ParameterSet.Utilities import convertToUnscheduled
process=convertToUnscheduled(process)
```

Unfortunately the `miniAOD_customizeAllMC` injects more Paths and/or EndPaths which contain EDProducers which, in turn, never get moved to Tasks.

**Comment by davidlange6** [comment]
> On Aug 17, 2017, at 3:00 PM, Chris Jones <notifications@github.com> wrote:
> 
> Looking at the results of
> 
> cmsDriver.py step3 --conditions auto:phase1_2017_realistic -n 10 --era Run2_2017 --eventcontent AODSIM,MINIAODSIM,DQM --runUnscheduled -s RAW2DIGI,L1Reco,RECO,EI,PAT,DQM:@common+@miniAODDQM --datatier AODSIM,MINIAODSIM,DQMIO --customise SimGeneral/DataMixingModule/customiseForPremixingInput.customiseForPreMixingInput --customise Validation/Performance/TimeMemorySummary.customiseWithTimeMemorySummary --filein file://step2.root --fileout step3.root --nThreads=4 --no_exec
> 
> I found that
> 
> # Automatic addition of the customisation function from PhysicsTools.PatAlgos.slimming.miniAOD_tools
> from PhysicsTools.PatAlgos.slimming.miniAOD_tools import miniAOD_customizeAllMC 
> 
> #call to customisation function miniAOD_customizeAllMC imported from PhysicsTools.PatAlgos.slimming.miniAOD_tools
> process = miniAOD_customizeAllMC(process)
> 
> was being called after
> 
> # End of customisation functions
> #do not add changes to your config after this point (unless you know what you are doing)
> from FWCore.ParameterSet.Utilities import convertToUnscheduled
> process=convertToUnscheduled(process)
> 
> Unfortunately the miniAOD_customizeAllMC injects more Paths and/or EndPaths which contain EDProducers which, in turn, never get moved to Tasks.
> 

these facts are all correct but it was a feature not a bug.why is this "wrong"?

**Comment by Dr15Jones** [comment]
Doing a 'partial' convert to unschedule can lead to unrunnable scheduled. We were testing breaking the very large EndPaths (mostly containing DQM modules) into many EndPaths each with only one module. After doing so we were getting unrunnable module ordering problems like
```
An exception of category 'ScheduleExecutionFailure' occurred while
  [0] Calling beginJob
Exception Message:
Unrunnable schedule
Module run order problem found: 
reconstruction_step after recoTauPileUpVertices [path reconstruction_step], 
<cut list of modules on reconstruction_step path>
 mvaElectrons after electronsWithPresel [path reconstruction_step], electronsWithPresel consumes ecalDrivenGsfElectrons, 
<cut list of unscheduled modules connected via consumes calls>
 pfDisplacedTrackerVertex consumes particleFlowDisplacedVertex, particleFlowDisplacedVertex after @EndPathStart [path particleFlowDisplacedVertex_endpath], @EndPathStart consumes TriggerResults, TriggerResults consumes reconstruction_step
Running in the threaded framework would lead to indeterminate results.
Please change order of modules in mentioned Path(s) to avoid inconsistent module ordering.
```
The problem stemmed from `particleFlowDisplacedVertex` being made 'unscheduled' in reconstruction but later being added to an EndPath by later customise functions.

Before adding Tasks, we had to avoid calling `convertToUnscheduled` on any configuration fragment that assumed the system was already `unscheduled`. Now with Tasks, that is no longer the case and we can call `convertToUnscheduled` at the very end (or even call it multiple times).

**Comment by makortel** [comment]
> very large EndPaths (mostly containing DQM modules)

I have the impression that many of the DQM modules do not need to be on an EndPath.

**Comment by Dr15Jones** [comment]
The idea was most (if not all) of the DQM modules are independent of each other and can be run in parallel. In order to do that with the framework, one can put the modules on their own EndPath or Paths.

**Comment by davidlange6** [comment]
thats true if you mean the DQMEDAnalyzers (or whatever their name is) - but thats not true of all modules on the dqm sequences (unfortunately!!) in general
