### ISSUE TITLE
Backport request: adding reduced gsf tracks collection to miniAOD

### ISSUE THREAD

**Issue by andreypz** [cms-sw/cmssw#20341]
Dear cmssw maintainers,
May I request you to make a backport of PR #19964 to whatever version of CMSSW is to be used for legacy re-miniAOD of 2016 data.

CC: @gpetruc @arizzi

**Comment by gpetruc** [comment]
Hi Andrey,

the re-miniAOD will be done with 9_4_X, so there's no need of backports.

Giovanni

**Comment by andreypz** [comment]
Ok, thanks.
In that case I close this issue.
