### ISSUE TITLE
fix-code-checks-yaml.py fails in 9_3_0_pre5

### ISSUE THREAD

**Issue by makortel** [cms-sw/cmssw#20377]
I have a case in 9_3_0_pre5 where `scram b code-checks` fails with
```
Working on tmp/slc6_amd64_gcc630/code-checks/DQM/TrackingMonitor/src/TrackBuildingAnalyzer.cc.yaml
Traceback (most recent call last):
  File ".../CMSSW_9_3_0_pre5/config/SCRAM/fix-code-checks-yaml.py", line 23, in <module>
    for d in obj["Diagnostics"]:
TypeError: 'NoneType' object is not iterable
config/SCRAM/GMake/Makefile.coderules:46: recipe for target 'code-checks-apply' failed
```

The yaml file contains
```
$ cat ../tmp/slc6_amd64_gcc630/code-checks/DQM/TrackingMonitor/src/TrackBuildingAnalyzer.cc.yaml 
---
MainSourceFile:  /afs/cern.ch/work/m/mkortela/tracking/dqm/CMSSW_9_3_0_pre5/src/DQM/TrackingMonitor/src/TrackBuildingAnalyzer.cc
Diagnostics:     
...
```
so apparently the empty `Diagnostics:` gets translated as `None`. Is this an indication of a problem in the program producing the yaml file, or should `fix-code-checks-yaml.py` be fixed to properly handle this case?

**Comment by makortel** [comment]
The context is #20378, and the failure is visible in the log
https://cmssdt.cern.ch/SDT/code-checks/PR-20378/500/code-checks.log

**Comment by smuzaffar** [comment]
assign core
@makortel , thanks for reporting it. I can reproduce this and soon provide a fix for next IBs (today's 23h).

**Comment by makortel** [comment]
I presume the fix is working (didn't bother to test myself) so I close the issue.
