### ISSUE TITLE
Improper patch by code-checks

### ISSUE THREAD

**Issue by makortel** [cms-sw/cmssw#20435]
In CMSSW_9_3_0_pre5 `scram b code-checks` made the following change
```
// collseed = Handle<View<T>>
-    if ((*collseed).size()>0){
+    if (!*collseed.empty()){
```
which doesn't compile because "Handle does not have member 'empty'". I think the checks should have preserved the parentheses, i.e.
```
-    if ((*collseed).size()>0){
+    if (!(*collseed).empty()){
```

**Comment by smuzaffar** [comment]
assign core

thanks @makortel for reporting this. Looks like they have a fix for this in release_50 (we are using release_40) https://github.com/llvm-mirror/clang-tools-extra/commit/5325f7e3c8941232d79913dc2806d13b2c994291#diff-3dad0ce6b4154fbfff0a7b658e5d7c7b

I will try to cherry-pick this fix in our release_40 to avoid this.

**Comment by ghellwig** [comment]
@smuzaffar sorry for hijacking this issue, but did you have a look at another code-checks "issue" which I [mentioned in one PR](https://github.com/cms-sw/cmssw/pull/20433#issuecomment-328065055)?

**Comment by smuzaffar** [comment]
ah did not noticed that. Looks like checks had broken then line here
https://github.com/cms-sw/cmssw/pull/20433/commits/9f57c6768c4045d2a7f6c4da672df3a7ff5c5e10#diff-616cc1e4006d02189e27f55aafb4c9a8R1446
I will check if they have fix for that too otheriwise open an issue for clang-tidy

**Comment by ghellwig** [comment]
thanks!

**Comment by smuzaffar** [comment]
@ghellwig ,  this https://github.com/cms-sw/cmssw/commit/9f57c6768c4045d2a7f6c4da672df3a7ff5c5e10#diff-616cc1e4006d02189e27f55aafb4c9a8R1446 is due to bug in our build rules. I will update the rule to avoid this.

**Comment by ghellwig** [comment]
@smuzaffar thank you

**Comment by smuzaffar** [comment]
+externals
@makortel and @ghellwig, both of these issues should be fixed in latest 94X IBs.

**Comment by makortel** [comment]
Thanks @smuzaffar!
