### ISSUE TITLE
Propagate Era changes in pickled processes

### ISSUE THREAD

**Issue by kpedro88** [cms-sw/cmssw#20481]
When a relval or production job fails, the `PSet.pkl` and `PSet.py` files are provided (see e.g. #20458). One can dump the `PSet.py` file to see what modules and settings are in the process.

However, if the fix for the problem is an Era-dependent change, it will not get propagated to the process, since `PSet.pkl` contains an already-constructed process object. Even though the process object may have been originally created with a Era or list of Eras/modifiers, the modifier changes aren't reapplied based on the local CMSSW being used.

Is there any way to propagate Era-dependent changes in this case?

If not, I suppose we'll need to request that original cmsRun configs or cmsDriver commands are obtainable for production debugging.

Related: it would be nice to print the Era information in `edmConfigDump`. Right now, it doesn't appear that there's any way to know what Era (if any) was used in a pickled process.

**Comment by Dr15Jones** [comment]
assign core

**Comment by Dr15Jones** [comment]
I do not believe it is realistically possible to preserve `cms.Modifier`s (ie. "eras") across pickle/unpickle. As far as I can tell, the pickling processes effectively copies the orginal objects. The eras work by sharing the exact same object across all the python modules. After pickling, that connection to the original era is gone.

**Comment by kpedro88** [comment]
Okay, will close and follow up with ops
