### ISSUE TITLE
Running Clang tidy checks-all on Sim packages - summary

### ISSUE THREAD

**Issue by ianna** [cms-sw/cmssw#20510]
1. Wrong conversion. Here is what is changed:
```
-  if ((*m_trksForThisEvent).size() == 0 && idsave.size() == 0) { return; }
+  if (*m_trksForThisEvent->empty() && idsave.empty()) { return; }
```
this gives compilation error:
```
/build/yana/CLANG/SIM/CMSSW_9_4_X_2017-09-13-1100/src/SimG4Core/Application/src/SimTrackManager.cc: In member function 'void SimTrackManager::cleanTracksWithHistory()':
/build/yana/CLANG/SIM/CMSSW_9_4_X_2017-09-13-1100/src/SimG4Core/Application/src/SimTrackManager.cc:308:34: error: invalid type argument of unary '*' (have 'bool')
   if (*m_trksForThisEvent->empty() && idsave.empty()) { return; }
                                  ^
```
2. The header files are not modified, but the warning is issued:
```
/build/yana/CLANG/SIM/CMSSW_9_4_X_2017-09-13-1100/src/SimCalorimetry/CaloSimAlgos/interface/CaloTDigitizer.h:92:12: warning: converting integer literal to bool, use bool literal instead [modernize-use-bool-literals]
    assert(0);
           ^
```
and
```
/build/yana/CLANG/SIM/CMSSW_9_4_X_2017-09-13-1100/src/SimGeneral/MixingModule/interface/DigiAccumulatorMixMod.h:95:5: warning: deleted member function should be public [modernize-use-equals-delete]
    DigiAccumulatorMixMod(DigiAccumulatorMixMod const&) = delete; // stop default
    ^
```

**Comment by smuzaffar** [comment]
@ianna , For your issue (1), I do not see this behaviour. 
- In CMSSW_9_4_X_2017-09-10-2300 relase (where this bug, removal of braces, exists in clang-tidy)  I see that braces were removed but do not see dot being replace with `->`
```
-  if ((*m_trksForThisEvent).size() == 0 && idsave.size() == 0) { return; }
+  if (*m_trksForThisEvent.empty() && idsave.empty()) { return; }
```

- in latest IB i.e. CMSSW_9_4_X_2017-09-13-2300 which has the bug fix for this check, I get
```
-  if ((*m_trksForThisEvent).size() == 0 && idsave.size() == 0) { return; }
+  if ((*m_trksForThisEvent).empty() && idsave.empty()) { return; }
```

**Comment by ianna** [comment]
@smuzaffar - thanks! I run it with an earlier IB.

**Comment by smuzaffar** [comment]
@ianna , for your issue (2), looks like modernize-use-bool-literals check does not fix the code if it is in macro. They have an option  to control it in llvm 5.0 ( https://github.com/llvm-mirror/clang-tools-extra/commit/b1070ce8444b93b58b8cca09e4d887034182871d#diff-7d3ce71e39ae1d05b7415f489e87f69d ). I can cherry pick the change in our llvm 4.0 or we wait for llvm 5.0 to be integrated in our IBs.

**Comment by ianna** [comment]
@smuzaffar - thanks, I think, we can wait
