### ISSUE TITLE
Items needed for XeXe run processing with 92X

### ISSUE THREAD

**Issue by slava77** [cms-sw/cmssw#20654]
Current release deployment schedule may work best if the XeXe pilot run data taking can be done with 92X release.
Please provide a list of PRs that need a backport from 93X/94X in this thread.

@mandrenguyen @abaty

**Comment by slava77** [comment]
assign reconstruction,dqm,alca,hlt

I've been somewhat liberal in category assignment.
Perhaps less will be needed in the end.

**Comment by mandrenguyen** [comment]
Assuming we will run the heavy-ion reco sequence I see the following PRs that should be backported:
#19089
#19475
#19927 
#19943 
#20024 
#20482

**Comment by abaty** [comment]
Let me add these two small ones to the list:
#19486
#20303

**Comment by slava77** [comment]
@mandrenguyen @abaty 
To speed up integration in 92X, I suggest to make combined PRs in cases there are overlaps between files or other logical dependence.
It is easier to test and merge in the production environment of 92X.

**Comment by davidlange6** [comment]
as we need to close things out in hopes of getting something for the tier0 to test over the weekend. Is anything missing aside from

a) sign and backport of #20749 
b) addition of a scenario to Configuration/DataProcessing

?

**Comment by mandrenguyen** [comment]
No, AFAIK

**Comment by slava77** [comment]
the run is over. Necessary PRs were included in CMSSW_9_2_13.
