### ISSUE TITLE
Use GBRForest in MuonMvaEstimator and SoftMuonMvaEstimator

### ISSUE THREAD

**Issue by slava77** [cms-sw/cmssw#20700]
this is to follow up on 
https://github.com/cms-sw/cmssw/pull/20612#discussion_r141703307

MuonMvaEstimator
can be moved to use GBRForest for MVA evaluation instead of using TMVAReader directly, which consumes much more memory.

@drkovalskyi

**Comment by slava77** [comment]
assign reconstruction

**Comment by drkovalskyi** [comment]
Will review and test it when we have final training for 94X production.

**Comment by slava77** [comment]
> Will review and test it when we have final training for 94X production.

@drkovalskyi 
I just wanted to check on this if it's time to advance with the GBRForest implementation.
What is the status of the training.

**Comment by slava77** [comment]
the same now applies to SoftMuonMvaEstimator introduced with #22419

**Comment by slava77** [comment]
@drkovalskyi @folguera 
The soft mu MVA takes up 8 MB of memory and it's instantiated per stream
https://slava77sk.web.cern.ch/slava77sk/reco/cgi-bin/igprof-navigator/CMSSW_10_1_X_2018-03-06-1100-sign1005.136.8311.IgProf.1.MEM_LIVE/825

Please bump up this issue on your priority list, especially if you are planning to deploy any more muon ID MVAs on a few months time scale.

The last I recall is that TMVA::Reader is not thread safe and can not be used in a global cache.
@Dr15Jones do you know if this situation has changed?

One thread-safe alternative is GBRForest proposed in this issue.

**Comment by Dr15Jones** [comment]
@slava77 

> The last I recall is that TMVA::Reader is not thread safe and can not be used in a global cache.
@Dr15Jones do you know if this situation has changed?

I do not know if that has changed. It seems unlikely.

**Comment by slava77** [comment]
+1

this was resolved in #22963 and is available in 10_2_X (from Apr 18) in 10_2_0_pre2
