### ISSUE TITLE
Follow up to TRK POG code review for PixelFed25 #20151

### ISSUE THREAD

**Issue by slava77** [cms-sw/cmssw#20703]
Several changes were proposed in review of #20151 for the TRK POG code
https://github.com/cms-sw/cmssw/pull/20151#pullrequestreview-56368041
These are expected to be followed up by the TRK POG developers

@makortel @VinInn

**Comment by slava77** [comment]
assign reconstruction

**Comment by makortel** [comment]
Addressed in #20891.

**Comment by slava77** [comment]
There are still a few items left from review of #20151 :
- performance improvement in https://github.com/cms-sw/cmssw/pull/20151#discussion_r133424137 in RecoTracker/MeasurementDet/plugins/TkPixelMeasurementDet.cc 
- a map instead of vector of vectors https://github.com/cms-sw/cmssw/pull/20151#discussion_r142120834 in RecoTracker/MeasurementDet/src/TkMeasurementDetSet.h 

Are these in the POG or DPG hands?
@makortel @VinInn  @veszpv @boudoul

**Comment by makortel** [comment]
> * performance improvement in https://github.com/cms-sw/cmssw/pull/20151#discussion_r133424137 in RecoTracker/MeasurementDet/plugins/TkPixelMeasurementDet.cc

The time spent in TkPixelMeasurementDet::hasBadComponents() is insignificant (~0.02 % of `CkfTrackCandidateMakerBase::produceBase()` in run 300811), so we prefer to leave that as part of larger reorganization of the ROC position information.

> * a map instead of vector of vectors https://github.com/cms-sw/cmssw/pull/20151#discussion_r142120834 in RecoTracker/MeasurementDet/src/TkMeasurementDetSet.h

For some reason the link doesn't go to the specific comment, but I presume you refer to `PxMeasurementDetSet::badFEDChannelPositionsSet_` (that was vector of unique_ptrs). That was changed to `unordered_map` in #20891 (even if it has negligible impact on larger scale as noted in the PR description).

**Comment by slava77** [comment]
+1

Addressed in #20891.

@makortel thank you for the clarifications on other items
