### ISSUE TITLE
FastjetJetProducer missing input candidate collection bad behavior in 94X

### ISSUE THREAD

**Issue by aperloff** [cms-sw/cmssw#20977]
Hello,

There seems to be a problem with FastjetJetProducer/VirtualJetProducer that cropped up between CMSSW 93X and 94X. In 93X when you used a MiniAOD file as input to produce the ak4PFJets as defined in [1] you get an error that says something about looking for PackedPFCandidates under the label "particleFlow." This is the expected behavior as the candidate collection for MiniAOD is called "packedPFCandidates." Obviously there is no error if using a GEN-SIM-RECO/AODSIM file or if you change the name of the input collection when using MiniAOD. In 94X this behavior has changed. When using an AODSIM file everything proceeds as normal. Same for if you use a MiniAOD file and change the input collection name. However, if you use a MiniAOD file and don't change the name, so it's still looking for "particleFlow," the code does not fail nor does it warn the user. Instead you get a vector of reco::PFJets, one for each event, but none of the jet contents are filled (i.e. area, pt, eta, etc.). When trying to draw these quantities you get an empty histogram.

To me this seems like dangerous behavior. Either the code should warn the user that this might happen, or there should be a failure when it doesn't find the input collection.

I've tested this on CMSSW_9_3_2 and CMSSW_9_4_X_2017-10-15-1100.

Cheers,
Alexx

[1]
RecoJets.JetProducers.ak4PFJets_cfi

**Comment by slava77** [comment]
assign reconstruction

@rappoccio @ahinzmann 
please take a look

**Comment by ahinzmann** [comment]
Maybe this if clause needs an "else through exception":
https://github.com/cms-sw/cmssw/blob/master/RecoJets/JetProducers/plugins/VirtualJetProducer.cc#L381

**Comment by rappoccio** [comment]
@ahinzmann that should work.

**Comment by slava77** [comment]
+1

fixed in #20981 which is merged since CMSSW_9_4_X_2017-10-23-1800 and is available in 9_4_0_pre3
