### ISSUE TITLE
TestPhiMemoryImage fails in CLANG IBs (wrong bit shifting)

### ISSUE THREAD

**Issue by mrodozov** [cms-sw/cmssw#21001]
We were after a unit test fail namely:
https://cmssdt.cern.ch/SDT/cgi-bin/buildlogs/slc6_amd64_gcc630/CMSSW_9_4_CLANG_X_2017-10-23-2300/unitTestLogs/L1Trigger/L1TMuonEndCap

which persists for some time now and which fails with assertion:

https://github.com/cms-sw/cmssw/blob/master/L1Trigger/L1TMuonEndCap/test/unittests/TestPhiMemoryImage.cpp#L77 (fails on line 100)
When we printed out the compared values of the bit shifting, we noticed that they are not what would be expected:
```
if (i == 0)
{
std::cout << std::hex << word0 << " " 
 << 64-i << " " 
 << ( word0 >> (64-i) ) 
 << std::endl;
 CPPUNIT_ASSERT_EQUAL(image.get_word(0, 0), (word0 << i) | (word0 >> (64-i)));
}
```
we've got 
>> Clang -> 11111111 40 40b100 , TestPhiMemoryImage.cpp:105:Assertion (dies)
>> GCC -> 11111111 40 0, OK  (works)
Explanation might be that ( word0 >> (64-i) ) part leads to undefined behavior (@davidlt)
https://stackoverflow.com/questions/18918256/is-right-shift-undefined-behavior-if-the-count-is-larger-than-the-width-of-the-t

implementations of used methods:
 https://github.com/cms-sw/cmssw/commits/master/L1Trigger/L1TMuonEndCap/src/PhiMemoryImage.cc
@smuzaffar @davidlange6 @rekovic @mulhearn

**Comment by rekovic** [comment]
Adding developers in the thread @jiafulow @abrinke1

**Comment by jiafulow** [comment]
I'm sorry for the bug. I'll look into this as soon as possible. Thanks.

**Comment by jiafulow** [comment]
Hi,

Thanks for the really useful info about the bug in right shift undefined behavior. Otherwise it would have taken me longer to figure this out. The bug only happens in the unit test itself, in particular lines 100, 104 and 108, because of the `x >> 64` operation. The actual tests on the functions `PhiMemoryImage::rotl()` and `PhiMemoryImage::rotr()`, on lines 116-127, work correctly. 

So I think this can be fixed by:

```diff
diff --git a/L1Trigger/L1TMuonEndCap/test/unittests/TestPhiMemoryImage.cpp b/L1Trigger/L1TMuonEndCap/test/unittests/TestPhiMemoryImage.cpp
index d74145d4e96..fda57031f22 100644
--- a/L1Trigger/L1TMuonEndCap/test/unittests/TestPhiMemoryImage.cpp
+++ b/L1Trigger/L1TMuonEndCap/test/unittests/TestPhiMemoryImage.cpp
@@ -97,15 +97,15 @@ void TestPhiMemoryImage::test_rotation()
     image.rotl(i);
 
     if (i == 0)
-      CPPUNIT_ASSERT_EQUAL(image.get_word(0, 0), (word0 << i) | (word0 >> (64-i)));
+      CPPUNIT_ASSERT_EQUAL(image.get_word(0, 0), (word0 << i));
     else if (i < 64)
       CPPUNIT_ASSERT_EQUAL(image.get_word(0, 0), (word0 << i) | (word2 >> (64-i)));
     else if (i == 64)
-      CPPUNIT_ASSERT_EQUAL(image.get_word(0, 0), (word2 << (i-64)) | (word2 >> (128-i)));
+      CPPUNIT_ASSERT_EQUAL(image.get_word(0, 0), (word2 << (i-64)));
     else if (i < 128)
       CPPUNIT_ASSERT_EQUAL(image.get_word(0, 0), (word2 << (i-64)) | (word1 >> (128-i)));
     else if (i == 128)
-      CPPUNIT_ASSERT_EQUAL(image.get_word(0, 0), (word1 << (i-128)) | (word1 >> (192-i)));
+      CPPUNIT_ASSERT_EQUAL(image.get_word(0, 0), (word1 << (i-128)));
     else if (i < 192)
       CPPUNIT_ASSERT_EQUAL(image.get_word(0, 0), (word1 << (i-128)) | (word0 >> (192-i)));
     else
```

After the fix, `scram b runtests` gives me successful output:

```
===== Test "TestPhiMemoryImage" ====
Running ....

OK (4)

---> test TestPhiMemoryImage succeeded
 
^^^^ End Test TestPhiMemoryImage ^^^^
Package L1Trigger/L1TMuonEndCap: Running test TestTrackTools
 
===== Test "TestTrackTools" ====
Running ....

OK (4)

---> test TestTrackTools succeeded
 
^^^^ End Test TestTrackTools ^^^^
>> Tests for package L1Trigger/L1TMuonEndCap ran.
```

Should I submit a pull request, or will someone be able to take care of this? 

Thanks,
Jia Fu

**Comment by mrodozov** [comment]
Just to clarify - did you compiled and tested it with clang as it was present only there, if yes then - yes just put the changes in a PR and then we could close the issue. Thanks for the prompt response

**Comment by jiafulow** [comment]
I used the release CMSSW_9_4_CLANG_X_2017-10-23-2300 . In that release, the compiler has been set to Clang. I was able to reproduce the error and fix it with the above changes. I will make a PR to the CMSSW_9_4_X referencing this issue.

**Comment by mrodozov** [comment]
I confirm the test is passing with the changes in #21054 , closing the issue.
