### ISSUE TITLE
CMSSW tool conf has unneeded external dependencies

### ISSUE THREAD

**Issue by gartung** [cms-sw/cmssw#21011]
I am trying to build CMSSW and its dependencies with spack on linux. I am starting with the set of dependencies needed to link CMSSW libraries and then moving onto the set of dependencies needed for the runtime environment. I have found a few dependencies that seem outdate or no longer needed. Google perftools which provides tcmalloc is the first. The spec for Google perftools just produces an empty library. The only place it is used in CMSSW is to link cmsRunTC. Both should be removed.

**Comment by gartung** [comment]
@Dr15Jones @davidlange6 @smuzaffar

**Comment by gartung** [comment]
https://github.com/cms-sw/cmsdist/pull/3514
https://github.com/cms-sw/cmssw/pull/20972

**Comment by smuzaffar** [comment]
@gartung , as @davidlt mentioned here https://github.com/cms-sw/cmssw/pull/20972#issuecomment-339306632 , we have a updated version of this as https://github.com/cms-sw/cmsdist/commits/IB/CMSSW_9_4_X/gcc700/gperftools.spec . We will back port it to gcc630 too.
