### ISSUE TITLE
Uninitialized memory in RPC simulation

### ISSUE THREAD

**Issue by kpedro88** [cms-sw/cmssw#21036]
Recently some irreproducibility in PR tests was observed and suspected to be related to the RPC simulation (see #20934). I ran valgrind on workflow 20434.0 in IB CMSSW_9_4_X_2017-10-25-1100, corresponding to the observation of the problem.

Valgrind found one issue:
https://github.com/cms-sw/cmssw/blob/dafc5c35984c65580d90edf772e7c2d0f9cb153d/SimMuon/RPCDigitizer/src/RPCSimModelTiming.cc#L99
`eledig` is a boolean member variable of the class that is never initialized.

@bapavlov @dildick please check this and fix ASAP. (I can't tell how the variable should be initialized, if it is still needed.)

attn: @slava77 @davidlange6

**Comment by slava77** [comment]
assign simulation

it looks like the implementation of RPCSimModelTiming configuration is incomplete: eledig is present in other models and is initialized, but not in this one.

**Comment by bapavlov** [comment]
It was a part of "last minute" changes implemented in the muon system. The default values of  eledig should be false. I'll implement the fix asap.

**Comment by kpedro88** [comment]
resolved by #21044
