### ISSUE TITLE
DQMFileSaverPB is not concurrent Runs safe

### ISSUE THREAD

**Issue by Dr15Jones** [cms-sw/cmssw#21200]
The module DQMFileSaverPB is an  edm::global:: but uses non-thread safe mutables:
https://github.com/cms-sw/cmssw/blob/8be445ac6fd9983d69156199d4d1fd3350f05d92/DQMServices/FileIO/plugins/DQMFileSaverPB.h#L33

This code will not be thread safe once we switch to allowing concurrent runs. An easy way to fix this would be to use a RunCache to hold the two values.

**Comment by Dr15Jones** [comment]
assign dqm

**Comment by fioriNTU** [comment]
+1

@Dr15Jones if I understand properly, this issue is related to a module running in Online which is not thread safe. However the Online code runs in single thread, so there should be no practical issue

**Comment by davidlange6** [comment]
probably its then best to change the module type to something more appropriate... (in case you eventually realize that nThreads>1 is useful for increasing throughput online - that seems likely to happen in the next years after all)
