### ISSUE TITLE
C++ String Formatting (and future)

### ISSUE THREAD

**Issue by davidlt** [cms-sw/cmssw#21281]
String formatting in C++ is a complicated task. For simple things one can use `iostream` facilities, which have been slightly improved over C++11/14/17. Sadly in most cases people will shift towards C facilities for formatting string (e.g. `printf` and friends). This usually will required managing buffers, ensuring that buffers are not overflowed, checking if we manage to print full content to buffer, etc. In most cases people don't check and this creates issues were we can damage memory, or just segfault.

Something was proposed in C++ Library Evaluation is http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2017/p0645r0.html which was well received.

Which is based on `libfmt`:
- http://fmtlib.net/latest/index.html
- https://github.com/fmtlib/fmt

Full story and comparison (C, C++, various C++ frameworks): https://www.youtube.com/watch?v=ptba_AqFYCM

E.g.,
- LLVM is implementing similar string formatting: http://llvm.org/docs/ProgrammersManual.html#formatting-strings-the-formatv-function
- Facebook folly library: https://github.com/facebook/folly/blob/master/folly/docs/Format.md

You probably already noticed that proposed string formatting is the same in Python and Rust:
- Python: https://docs.python.org/2/library/string.html#format-examples
- Rust: https://doc.rust-lang.org/std/fmt/

Few times a year I ran in situations were using C or C++ existing string formatting facilities seems like too cumbersome for a simple tasks. Yes, even in C++, especially if formatting is really something you want to do.

 I suggest we add `libfmt` into CMSSW and hopefully in next 3-6 years it (or major parts of it) is in C++ Standard Library. See also compile-time and run-time performance (youtube recording). It is designed to be fast in both cases.

**Comment by smuzaffar** [comment]
`libfmt`  is part of cmssw distribution and uses by various systems ( https://cmssdt.cern.ch/lxr/search?%21v=CMSSW_12_1_X_2021-09-15-2300&_filestring=&_string=fmt )
