### ISSUE TITLE
Include MXNet as an external

### ISSUE THREAD

**Issue by makortel** [cms-sw/cmssw#21314]
Following up my presentation in the O&C week reco meeting ([link](https://indico.cern.ch/event/625239/#11-tensorflow-in-production-ap)) this issue is to track the inclusion of Apache MXNet ([link](https://mxnet.incubator.apache.org/)) as CMSSW external.

I have not taken a very in-depth view on MXNet myself, but learned recently that @gouskos et al are using it for a boosted jet tagger with plans to integrate the tagger to CMSSW at some point.

**Comment by davidlange6** [comment]
assign core

**Comment by davidlange6** [comment]
the python interface looks simple to add as we already have openblas and graphviz (I think). The C++ interface is less well documented at this point. (but it looks to exist)

**Comment by hqucms** [comment]
There is a pretty light-weighted [C API](https://github.com/apache/incubator-mxnet/blob/master/include/mxnet/c_predict_api.h) for prediction (i.e., neural net evaluation). One just needs to include this header and link to `libmxnet.so`, e.g., in this [example](https://github.com/apache/incubator-mxnet/blob/master/example/image-classification/predict-cpp).

I briefly tried building MXNet with the following options and the resulting library (~40MB) seems working fine with CMSSW.

```bash
ADD_LDFLAGS = -L/cvmfs/cms.cern.ch/slc6_amd64_gcc530/external/OpenBLAS/0.2.19-mlhled2/lib
ADD_CFLAGS = -I/cvmfs/cms.cern.ch/slc6_amd64_gcc530/external/OpenBLAS/0.2.19-mlhled2/include
USE_OPENCV = 0
USE_OPENMP = 0
USE_BLAS = openblas
```

**Comment by davidlange6** [comment]
Good to know - i find pypi only has wheels - so probably the the thing to do is follow the approach we have for tensorflow to pick up all the interfaces we need eventually (:()

**Comment by hqucms** [comment]
Hi @davidlange6 

AFAIK MXNet should be a lot easier to deal with than tensorflow (at least we don't need extra dependencies such as bazel). And basically the C prediction API (one header + one library) is the only thing we need for CMSSW to evaluate the neural networks. The python API is more for training, but there GPU is really needed and things become hardware/CUDA version dependent, so I am not sure if it needs to be shipped with CMSSW.

**Comment by hqucms** [comment]
Just wondering: is there any update on this?

**Comment by gouskos** [comment]
Dear @davidlange6 , @makortel , all; 

Did you have the chance to check the details of including for MXNET in CMSSW?
The tagger is approved within Jet/MET and the BTV groups and we would like to include it CMSSW.
Do you have any suggestions on how to proceed?

Thank you!

**Comment by davidlange6** [comment]
I didn't yet - I'll try to get that back on the todo list

**Comment by gouskos** [comment]
thank you @davidlange6

**Comment by makortel** [comment]
Hi @davidlange6, any progress yet?

**Comment by davidlange6** [comment]
Not from m my side

Cheers,
David


On 19 Apr 2018, at 10:42, Matti Kortelainen <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi @davidlange6<https://github.com/davidlange6>, any progress yet?

**Comment by slava77** [comment]
This is to remind that there is a continuing interest in having this external supported (IIUC, the use case is still the same and the only one so far)

**Comment by hqucms** [comment]
I wrote a spec file to compile mxnet with pkgtools:
https://github.com/hqucms/cmsdist/blob/mxnet/IB/CMSSW_10_2_X/gcc630/mxnet-predict.spec
https://github.com/hqucms/cmsdist/blob/mxnet/IB/CMSSW_10_2_X/gcc630/mxnet-predict-toolfile.spec

Please let me know if there is anything else I can help.

**Comment by davidlange6** [comment]
go ahead and make a pull request if this is the piece that is desired at first. I had looked instead at the python api....

**Comment by hqucms** [comment]
OK, I will make a PR now. Sorry for the confusion, @davidlange6

**Comment by slava77** [comment]
@makortel 
I propose to close this.
We now have mxnet in 94X, 102X, and later releases.

**Comment by makortel** [comment]
Agree.
