### ISSUE TITLE
Duplicate header for fed_trailer.h

### ISSUE THREAD

**Issue by davidlt** [cms-sw/cmssw#21312]
While looking at output for validateJR comparison tests I noticed that we have two headers for the same (?) thing:
- https://github.com/cms-sw/cmssw/blob/master/EventFilter/FEDInterface/interface/fed_trailer.h#L22
- https://github.com/cms-sw/cmssw/blob/master/DataFormats/FEDRawData/src/fed_trailer.h#L31

ROOT Cling run-time complaint about struct redefinition: `error: redefinition of 'fedh_struct'`

The one in `DataFormats/FEDRawData` was done 12 years ago and commit mentioned that it should be temporary. The one in `EventFilter/FEDInterface` seems to be a better rewrite of old stuff.

**Comment by davidlt** [comment]
Ah, I already have filled a bug report for this back in 2016: https://github.com/cms-sw/cmssw/issues/14353

**Comment by mommsen** [comment]
This issue has been addressed with #21690 and could be closed.
