### ISSUE TITLE
silence CTPPSIncludeAlignments

### ISSUE THREAD

**Issue by VinInn** [cms-sw/cmssw#21425]
please silence CTPPSIncludeAlignments
%MSG
>> CTPPSIncludeAlignments::PrepareSequence(Measured)
>> CTPPSIncludeAlignments::PrepareSequence(Real)
	first=      -inf, last=      +inf: alignment blocks=1
>> CTPPSIncludeAlignments::PrepareSequence(Misaligned)

**Comment by Dr15Jones** [comment]
assign geometry

**Comment by slava77** [comment]
assign geometry

@fabferro @forthommel please take a look and pass to someone if you can not fix it.
Thank you.

**Comment by fabferro** [comment]
I'll open a PR asap aimed to CMSSW_10

**Comment by fabferro** [comment]
Please see PR#21435

**Comment by forthommel** [comment]
Many thanks for your fast reaction, @fabferro !
