### ISSUE TITLE
HLTExoticaValidator makes excessive copies of edm::ParameterSet

### ISSUE THREAD

**Issue by makortel** [cms-sw/cmssw#21445]
I was profiling the memory of ttbar+PU50 (with matrix workflow 10024.0 step3) for other reasons while I noticed that `HLTExoticaValidator` constructor is holding 1.5 MB (/stream) of copies of `edm::ParameterSet`.

Problematic pieces of code are
* `HLTExoticaValidator` holding a copy of the input `ParameterSet` without any need
https://github.com/cms-sw/cmssw/blob/63e59e6fb76ddfd550cf382a88f07c605f45843c/HLTriggerOffline/Exotica/src/HLTExoticaValidator.cc#L23
   * **Suggestion**: remove the member `_pset`
* The `ParameterSet` is passed to `HLTExoticaSubAnalysis` (here one could also use range-for, and `emplace_back` to avoid a copy of `HLTExoticaSubAnalysis`)
https://github.com/cms-sw/cmssw/blob/63e59e6fb76ddfd550cf382a88f07c605f45843c/HLTriggerOffline/Exotica/src/HLTExoticaValidator.cc#L36-L39
which also stores the `ParameterSet` as a member
https://github.com/cms-sw/cmssw/blob/63e59e6fb76ddfd550cf382a88f07c605f45843c/HLTriggerOffline/Exotica/src/HLTExoticaSubAnalysis.cc#L31
only this time the member `_pset` is used after the constructor (see next bullet). There is also some "conditional parsing+editing" of the `_pset` along
https://github.com/cms-sw/cmssw/blob/63e59e6fb76ddfd550cf382a88f07c605f45843c/HLTriggerOffline/Exotica/src/HLTExoticaSubAnalysis.cc#L71-L74
   * **Suggestion**: Get all parameters that are needed later in the constructor, and store them to member variable(s) (e.g. one member variable per parameter or group into a struct)
* From `HLTExoticaSubAnalysis` the `ParameterSet` is passed to `HLTExoticaPlotter` in `HLTExoticaSubAnalysis::beginRun()`
https://github.com/cms-sw/cmssw/blob/63e59e6fb76ddfd550cf382a88f07c605f45843c/HLTriggerOffline/Exotica/src/HLTExoticaSubAnalysis.cc#L376
which only gets parameter values in its constructor
   * **Suggestion**: store these parameters e.g. in a struct in the constructor of `HLTExoticaSubAnalysis` and pass that struct to `HLTExoticaPlotter` constructor.

**Comment by Dr15Jones** [comment]
assign dqm

**Comment by dmitrijus** [comment]
+1

It was discovered and fixed in parallel.
It is merged in master, the PR to 94x should be merged soon enough.

https://its.cern.ch/jira/browse/CMSCOMPPR-1606

**Comment by dmitrijus** [comment]
https://github.com/cms-sw/cmssw/pull/21387
