### ISSUE TITLE
HLTHiggsValidator makes excessive copies of edm::ParameterSet

### ISSUE THREAD

**Issue by makortel** [cms-sw/cmssw#21452]
I was profiling the memory of ttbar+PU50 (with matrix workflow 10024.0 step3) for other reasons while I noticed that `HLTHiggsValidator` is holding 900 kB (/stream) of copies of edm::ParameterSet.

Problematic pieces of code are
* `HLTHiggsValidator` holding a copy of the input `ParameterSet` without any need
https://github.com/cms-sw/cmssw/blob/63e59e6fb76ddfd550cf382a88f07c605f45843c/HLTriggerOffline/Higgs/src/HLTHiggsValidator.cc#L25
* The constructor passes the `pset_` to `HLTHiggsSubAnalysis` constructor, which also stores it as a member
https://github.com/cms-sw/cmssw/blob/63e59e6fb76ddfd550cf382a88f07c605f45843c/HLTriggerOffline/Higgs/src/HLTHiggsSubAnalysis.cc#L35
in order to pass it further to `HLTHiggsPlotter` in `HLTHiggsSubAnalysis::beginRun`
https://github.com/cms-sw/cmssw/blob/63e59e6fb76ddfd550cf382a88f07c605f45843c/HLTriggerOffline/Higgs/src/HLTHiggsSubAnalysis.cc#L289

I'd suggest to read all parameters that are needed beyond the constructor to member variables, storing the ones that are needed for `HLTHiggsSubAnalysis`/`HLTHiggsPlotter` to a struct.

**Comment by Dr15Jones** [comment]
assign dqm

**Comment by dmitrijus** [comment]
+1

It was discovered and fixed in parallel.
It is merged in master, the PR to 94x should be merged soon enough.

https://its.cern.ch/jira/browse/CMSCOMPPR-1606

**Comment by dmitrijus** [comment]
https://github.com/cms-sw/cmssw/pull/21387
