### ISSUE TITLE
Remove try/catch in OmtfLinkMappingRpc

### ISSUE THREAD

**Issue by kpedro88** [cms-sw/cmssw#21465]
A try/catch block was included in the new class https://github.com/cms-sw/cmssw/blob/master/EventFilter/L1TRawToDigi/src/OmtfLinkMappingRpc.cc (introduced in #20859). It is called hundreds (thousands?) of times in an event, which is both incredibly inefficient and incredibly frustrating when trying to debug a real exception afterward (`catch throw` in gdb does not distinguish between caught and uncaught exceptions). This try/catch block needs to be replaced with something sensible ASAP.

**Comment by kpedro88** [comment]
assign l1

**Comment by kpedro88** [comment]
@rekovic ping

**Comment by rekovic** [comment]
@kpedro88 
A fix is available.  Will make a PR later today.

**Comment by rekovic** [comment]
@kpedro88 
10_1_X  fix is in https://github.com/cms-sw/cmssw/pull/22191
