### ISSUE TITLE
Excessive output from DTTSPhi::addTracoT

### ISSUE THREAD

**Issue by Dr15Jones** [cms-sw/cmssw#21620]
When looking at output from analysis jobs, we came across a job that had an unknown number (but extremely large) of messages of
```
DTTSPhi::addTracoT: preview not present in TRACO trigger or its code=0  trigger not added!
```

Looking at the code in question, one can see it is using std::cout, which is not thread-safe
https://github.com/cms-sw/cmssw/blob/a1a699103d53ed00ae87f2a2578dd7e4b6bd0b5b/L1Trigger/DTTriggerServerPhi/src/DTTSPhi.cc#L183

This code should be changed to use the `MessageLogger` and to limit the number of times it gets printed.

**Comment by Dr15Jones** [comment]
assign l1

**Comment by smuzaffar** [comment]
@cms-sw/l1-l2 , can you please look in to this . Code in question is https://github.com/cms-sw/cmssw/blob/master/L1Trigger/DTTriggerServerPhi/src/DTTSPhi.cc#L180-L182 and I see there are many other `std::cout` statements?

**Comment by cecilecaillol** [comment]
Fixed in https://github.com/cms-sw/cmssw/pull/37522

**Comment by cecilecaillol** [comment]
+l1
