### ISSUE TITLE
Handling of fopen write error in reco::details::loadTMVAWeights

### ISSUE THREAD

**Issue by kreczko** [cms-sw/cmssw#21628]
We recently encountered random segmentation faults in our cluster when running CMSSW jobs in the cluster. It was suggested that it might be due to write permissions in the `/tmp` folder and caused by `reco::details::loadTMVAWeights` in https://github.com/cms-sw/cmssw/blob/fee77f4c558f3b592a0bab04f1a8c1475db9e2c1/CommonTools/Utils/src/TMVAZipReader.cc#L84

In order to better catch such problems in the future, would it be possible to add a meaningful error message when that happens? E.g.

```c++
FILE *theActualFile = fopen(weight_file_name.c_str(), "w");
if (theActualFile != NULL){
  // write xml
  fputs(c, theActualFile);
  fputs("\n", theActualFile);
  fclose(theActualFile);
} else {
  throw cms::Exception("InvalidFile")
        << "Error while writing file = " << weight_file_name << " !!\n"
}
```

If the above solution is OK, I can make a PR.

**Comment by Dr15Jones** [comment]
assign reconstruction, analysis

**Comment by slava77** [comment]
On 12/1/17 6:46 AM, Luke Kreczko wrote:
> If the above solution is OK, I can make a PR.
> 

this looks reasonable to me.
Please proceed with a PR.

**Comment by kreczko** [comment]
@slava77 PR has been created (#21638)

**Comment by perrotta** [comment]
+1
- #21638 just merged in 10_0_X
