### ISSUE TITLE
Remove couts from HTXSRivetProducer

### ISSUE THREAD

**Issue by Dr15Jones** [cms-sw/cmssw#21640]
HTXSRivetProducer is a stream module which is calling `std::cout`. `std::cout` is not thread safe and should be replaced with calls to the MessageLogger.

**Comment by Dr15Jones** [comment]
assign generator

**Comment by Dr15Jones** [comment]
assign gen

**Comment by Dr15Jones** [comment]
assign generators

**Comment by perrozzi** [comment]
https://github.com/cms-sw/cmssw/pull/21696 https://github.com/cms-sw/cmssw/pull/21490

**Comment by perrozzi** [comment]
+1
