### ISSUE TITLE
CSCGEMMotherboardME11 has non-const function statics

### ISSUE THREAD

**Issue by Dr15Jones** [cms-sw/cmssw#21670]
`CSCGEMMotherboardME11` is called from the global module `CSCTriggerPrimitivesProducer` but has two non-const statics:
https://github.com/cms-sw/cmssw/blob/78a797a46a83721d8571bcf954088127f010a183/L1Trigger/CSCTriggerPrimitives/src/CSCGEMMotherboardME11.cc#L590

This is a thread safety problem. It should be possible to make both statics `const` or, better yet, do not make them `static` anyway since the use of `static` here most likely is slower.

**Comment by Dr15Jones** [comment]
This problem was introduced in #20509

**Comment by Dr15Jones** [comment]
assign l1, simulation, upgrade

**Comment by dildick** [comment]
@Dr15Jones I'll fix it to `const int`

**Comment by kpedro88** [comment]
+1

**Comment by thomreis** [comment]
+1

**Comment by smuzaffar** [comment]
fixed
