### ISSUE TITLE
Tracking open items for 1000pre3

### ISSUE THREAD

**Issue by davidlange6** [cms-sw/cmssw#21749]
out of the PRs noted at the release meeting, these PRs are still open 

Items that missed pre3 (or at last its first candidate build)
#21739 - needs updates from @civanch - not urgent
#21733 - now passes tests
#21657 - rebased now 
#21474 - second review from @davidlange6 done - some old comments were still pending. Looks like the hardwired hardware maps are still in flux. Will be for pre4

now integrated
#21697 - needs updates from @tstreble 
#21683  - @davidlange6 review done - comments pending
#21692 - we didn't discuss this one - but seems straightforward...
#21664 - @davidlange6 review done - comments pending (or maybe addressed already.. will look again after reco signoff)

now delayed
#21717 
@abdoulline

**Comment by abdoulline** [comment]
#21657 has been updated...

**Comment by davidlange6** [comment]
in addition the 2300 IBs had lots of problems in HCAL DQM.

https://cmssdt.cern.ch/SDT/cgi-bin/buildlogs/slc7_amd64_gcc630/CMSSW_10_0_X_2017-12-19-2300/pyRelValMatrixLogs/run/4.17_RunMinBias2011A+RunMinBias2011A+HLTD+RECODR1reHLT+HARVESTDR1reHLT+SKIMDreHLT/step4_RunMinBias2011A+RunMinBias2011A+HLTD+RECODR1reHLT+HARVESTDR1reHLT+SKIMDreHLT.log

[not obvious to me how this escaped the PR testing..] Presumably related to #21730?

**Comment by abdoulline** [comment]
...Matrix results look OK for this IB 
https://cmssdt.cern.ch/SDT/jenkins-artifacts/ib-baseline-tests/CMSSW_10_0_X_2017-12-19-2300/slc6_amd64_gcc630/-GenuineIntel/matrix-results/

**Comment by civanch** [comment]
#21739 is updated

**Comment by deguio** [comment]
I'm running more runTheMatrix tests on top of:
`CMSSW_10_0_X_2017-12-19-2300`
at the moment I wasn't able to reproduce the problem. 
`runTheMatrix.py -l 4.6`
completed correctly (including harvesting) for 100 events and 9 LS

**Comment by deguio** [comment]
#21683 was updated

**Comment by tstreble** [comment]
#21697 was updated

**Comment by davidlange6** [comment]
new vs old gen-sim?
anyway it is reproducible for me

cd CMSSW_10_0_X_2017-12-19-2300
runTheMatrix.py -l 136.731 -t 4

#6  0x00007fa1be862ff4 in MonitorElement::getBinContent(int) const () from /cvmfs/cms-ib.cern.ch/week1/slc6_amd64_gcc630/cms/cmssw-patch/CMSSW_10_0_X_2017-12-19-2300/lib/slc6_amd64_gcc630/libDQMServicesCore.so
#7  0x00007fa1abba9cca in hcaldqm::DigiRunSummary::endLuminosityBlock (this=0x7fa1ab8ca800, ib=..., ig=..., lb=..., es=...) at /build/dlange/CMSSW_10_0_X_2017-12-19-2300/src/DQM/HcalTasks/src/DigiRunSummary.cc:110

**Comment by deguio** [comment]
@davidlange6 
interesting. I ran 136.831 and 25202.0 single thread and I didn't see problems.
let me try with -t 4

**Comment by deguio** [comment]
indeed enabling multithread makes the crash pop up also with:
`runTheMatrix.py -l 4.6 -t 4`
do I understand correctly that this is the reason why no crashes were observed in the PR tests?

**Comment by davidlange6** [comment]
Yes - must be ( can not be gen-sim recycling as data workflows have problems too)

**Comment by deguio** [comment]
I tested the last working IB: CMSSW_10_0_X_2017-12-19-1100+21730
and I don't see crashes.
will do the same with a couple of other PRs while @DryRun  is also looking into the problem.

**Comment by Dr15Jones** [comment]
I think I may know why we get the failure. #21652 changed some `DQMAnalyzers` to _global_ modules. Such a change causes a problem if the histograms made by the `DQMAnalyzers` is then 'consumed' by a `DQMHarvester` which is a 'one' module. The problem is both _global_ and _one_ modules are both run at 'global end Run/Lumi' transition. Since the framework does not know there is a dependency between the `DQMAnalyzer` and the `DQMHarvester`, the framework will run them concurrently. So when the `DQMHarvester` tries to get the histogram from the DQMStore, that histogram may not be there yet.

So why did this work before? Originally, all `DQMAnalyzers` were _stream_ modules. _Stream_ modules run at stream end Run/Lumi which always finish before the frameworks goes on to global end Run/Lumi. That guaranteed the needed ordering between `DQMAnalyzers` and `DQMHarvester`.

**Comment by deguio** [comment]
ha. interesting.
but here the crash is in the harvesting step where all the dqm modules should be `DQMEDharvesters` so I'm not sure. will look more into it.

@fwyzard

**Comment by Dr15Jones** [comment]
@deguio the failures I am looking at are running the DQMHarvester in a non-harvest job: see WF 4.6 which is running the following components:
```
cmsDriver.py step2 --conditions auto:run1_data -s RAW2DIGI,L1Reco,RECO,EI,PAT,ALCA:SiStripCalZeroBias+SiStripCalMinBias+TkAlMinBias+EcalESAlign,DQM:@standardDQM+@ExtraHLT+@miniAODDQM --process reRECO --data --eventcontent RECO,MINIAOD,DQM --runUnscheduled --scenario pp --datatier RECO,MINIAOD,DQMIO --inputCommands "keep *","drop *_*_*_RECO" --customise Validation/Performance/TimeMemorySummary.customiseWithTimeMemorySummary --prefix '/build/cmsbld/jenkins-workarea/workspace/ib-run-relvals/cms-bot/monitor_workflow.py timeout --signal SIGTERM 7200 ' -n 100 --filein filelist:step1_dasquery.log --lumiToProcess step1_lumiRanges.log --fileout file:step2.root --suffix "-j JobReport2.xml " --nThreads 4 
```

**Comment by deguio** [comment]
hi @Dr15Jones 
for WF 4.6 what is see is a crash in step3 (harvesting) when running
`runTheMatrix.py -l 4.6 -t 4 `

I confirm that the crash was triggered by the merging of #21652
the problem comes from the fact that the ME are not there so the harvesting is crashing when trying to access root objects that don't exist.
MEs are missing from the previous step only when running multithread.

**Comment by fwyzard** [comment]
> I think I may know why we get the failure. #21652 changed some DQMAnalyzers to global modules. Such a change  causes a problem if the histograms made by the DQMAnalyzers is then 'consumed' by a DQMHarvester which is a 'one' module. The problem is both global and one modules are both run at 'global end Run/Lumi' transition. Since the framework does not know there is a dependency between the DQMAnalyzer and the DQMHarvester, the framework will run them concurrently. So when the DQMHarvester tries to get the histogram from the DQMStore, that histogram may not be there yet.

But, the 'global' DQM EDAnalyzer should not need to run anything in the 'global end Run' transition.
anyway, I'll have  a look, of course.

**Comment by fwyzard** [comment]
By the way, does anyone know why this was not spotted by the tests of  #21652 ?

**Comment by deguio** [comment]
I thin because the jenkins tests run single thread.

**Comment by Dr15Jones** [comment]
@deguio for WF 4.6, where are the histograms produced for the histograms being read by the DQMHarvester HcalOfflineHarvesting?

**Comment by DryRun** [comment]
Hi @Dr15Jones , the histogram in question is Hcal/RunInfo/NumberOfEvents, which is created here: https://github.com/cms-sw/cmssw/blob/83781ad02b866e4ca0652bccf555692e9c6eb939/DQM/HcalTasks/plugins/DigiTask.cc#L543.

**Comment by Dr15Jones** [comment]
I have another theory as to what caused the problem. There are two different phases in the framework as a lumi is ending. There is the 'global end lumi' phase and the 'write lumi' phase. The 'write lumi' phase is only seen by the OutputModules and is when they "write the lumi to output'. So the change in #21652 deletes some histograms at 'end of global end lumi' which is before 'write lumi' gets called. Therefore if the deleted histograms were supposed to be saved to the file, they would be missing.

**Comment by fwyzard** [comment]
Ah... OK, I didn't know there was a lumi-related phase after the `postGlobalEndLumi`.
Is there any way for a `Service` to be told ?

**Comment by Dr15Jones** [comment]
NOTE: The only reason storing lumi histograms to the output file from a non-stream module works is because 'global end lumi' and 'write lumi' are run in that order. If there were a 'data dependency' between the modules generating the histograms and the OutputModule writing the histograms (i.e. changing DQMAnalyzers to EDProducers) then we would not have to rely on obscure synchronizations between internal framework phases.

**Comment by Dr15Jones** [comment]
@fwyzard we do not at present have such a Service call back (which is one reason I keep forgetting about that 'write' phase). I'd really like to get rid of the seperate 'write' phase, but that would require changing all the DQM system to use 'data dependencies'.

**Comment by fwyzard** [comment]
Even if that were the case, how would the `DQMStore` know to delete the histograms *after* they have been saved ?

**Comment by Dr15Jones** [comment]
I'd be OK with moving the Service callbacks for 'end of global end lumi' and 'end of global end run' to be after their respective 'write' phase has finished.

**Comment by fwyzard** [comment]
I still cannot picture how the data dependency would work, because the DQM modules need to "consume" event-based data and "produce" lumi- or run-based data.

Anyway, possible workarounds for pre3:
  - revert the change about the deletion of the histograms
  - temporarily move the deletion from `postGlobalEndLumi` to `preGlobalBeginLumi`

**Comment by fwyzard** [comment]
See #21752 for the latter.

**Comment by fwyzard** [comment]
See #21753 for the former.

**Comment by slava77** [comment]
#21717 track NN selections will take longer due to some regressions in comparisons. So, most likely for pre4 only.

**Comment by davidlange6** [comment]
so we are at J+4 hours already.. i think we can manage waiting until 700 cern time tomorrow morning instead of ~now - it seems this would help the mahi PR at least.

**Comment by deguio** [comment]
thanks @davidlange6 @slava77 
for the record: I've opened PR#21756 rebasing the #21657 from @matz-e

**Comment by lpernie** [comment]
Hello @davidlange6 ,
together with PR #21756 , there is another PR( #21758 ) that should be included in pre3 if possible. As explained in the description this PR included some TAGs for HCAL that were left outside in the 2018 realistic GT.

**Comment by lpernie** [comment]
We are experiencing 'DAS Error' in both the PR. I assume this is a temporary glitch, I will re-trigger the tests.
