### ISSUE TITLE
RelVals failing in IB due to missing input premixing datasets

### ISSUE THREAD

**Issue by fabiocos** [cms-sw/cmssw#21824]
@prebello Your fix in #21819 has indeed adjusted the Pyquen workflows. Also the newly introduced workflows for 2018 seem to work (apart fo some DAS problems). 

Anyway there are some new failures in step 2 
https://cms-sw.github.io/relvalLogDetail.html#slc6_amd64_gcc630;CMSSW_10_0_X_2018-01-10-2300
for the pre-existing 250200.0  250200.1 250200.2 25020X.0 X = 2 to 7 workflows, apparently all due again to missing input files. 
For instance for 250200.0 das searches for non-existent files:
das_client.py --limit=0 --query="file dataset=/RelValPREMIXUP15_PU25/CMSSW_10_0_0_pre2-PU25ns_100X_mc2017_realistic_v1-v1/GEN-SIM-DIGI-RAW"
Looking into the das list there are no such PREMIX datasets so far for 10_0_X:
das_client.py --limit=0 --query="dataset dataset=/RelValPREMIXUP15_PU25/*/GEN-SIM-DIGI-RAW" | grep 10_0
gives no result. I guess that the problem comes from using in the workflow labeled as 2015
https://github.com/cms-sw/cmssw/blob/master/Configuration/PyReleaseValidation/python/relval_steps.py#L1245
the value based on 10_0
https://github.com/cms-sw/cmssw/blob/master/Configuration/PyReleaseValidation/python/relval_steps.py#L499
instead of keeping here an older existing version.

**Comment by fabiocos** [comment]
assign pdmv

**Comment by fabozzi** [comment]
fixed in #21831

**Comment by fabozzi** [comment]
#21831 has passed tests

**Comment by fabozzi** [comment]
+1
