### ISSUE TITLE
reco::FormulaEvaluator segFaults if function string is not hard-coded/pre-defined

### ISSUE THREAD

**Issue by kirschen** [cms-sw/cmssw#21851]
Dear experts,

in preparation for a new JEC-release, the parametrization has been extended by a TMath::Exp-expression. However, the the reco::FormulaEvaluator segFaults with this extension.

After inspecting 
https://github.com/cms-sw/cmssw/blob/master/CommonTools/Utils/src/FormulaEvaluator.cc#L562-L575
and following, it seems like any new function needs to be announced to the reco::FormulaEvaluator, i.e. if we are to introduce any new function, we should inject it to  reco::FormulaEvaluator as early as possible. For now, we replaced "TMath::Exp" by "exp" in our parametrization to make it work.

Would it be possible to catch "undefined" parametrizations instead of segfaulting to make it obvious what goes wrong? Maybe just replace the return in
https://github.com/cms-sw/cmssw/blob/master/CommonTools/Utils/src/FormulaEvaluator.cc#L660
by an error?

Thanks,
Henning for the JERC-group

FYI: Previous "JetMET"-issues with reco::FormulaEvaluator e.g. #16716 (@Dr15Jones @slava77 )

**Comment by slava77** [comment]
@kirschen 
I think that an error here is reasonable.
Would you like to submit a pull request for this?

**Comment by slava77** [comment]
@kirschen 
please clarify if you have a plan to make a PR with the change proposed by you when the issue was opened.
Thank you.

**Comment by kirschen** [comment]
Hi, sorry for the delay. Yes, I can take care of the small PR throwing an exception if none of the predefined functions are found in the next couple of days.

**Comment by kirschen** [comment]
Will link it here, then.

**Comment by slava77** [comment]
@kirschen 
I wanted to check on the status of that small PR.
Please update.
Thank you.

**Comment by kirschen** [comment]
Issue is more generically resolved with this PR:
https://github.com/cms-sw/cmssw/pull/22354

that gives a useful exception with the initial expression reported here
`kirschen@lxplus067 src $ root jec_issue_Dec2017.C
root [0]
Processing jec_issue_Dec2017.C...
terminate called after throwing an instance of 'cms::Exception'
what(): An exception of category 'FormulaEvaluatorParseError' occurred.
Exception Message:
While parsing '[2]([3]([4]+[5]TMath::Log(max([0],min([1],x))))1./([6]+[7]100./3.(TMath::Max(0.,1.03091-0.051154pow(x,-0.154227))-TMath::Max(0.,1.03091-0.051154TMath::Power(208.,-0.154227)))+[8]0.021(-1.+1./(1.+TMath::Exp(-(TMath::Log(x)-5.030)/0.395)))))' could not parse beyond '[2]([3]([4]+[5]TMath::Log(max([0],min([1],x))))1./([6]+[7]100./3.(TMath::Max(0.,1.03091-0.051154pow(x,-0.154227))-TMath::Max(0.,1.03091-0.051154TMath::Power(208.,-0.154227)))+[8]0.021(-1.+1./(1.+'`

**Comment by perrotta** [comment]
+1
- Solved with #22354, see https://github.com/cms-sw/cmssw/issues/21851#issuecomment-369918408

**Comment by perrotta** [comment]
@kirschen : you can close this issue

**Comment by kirschen** [comment]
Thanks, all!
