### ISSUE TITLE
IB crash in wf 140.52 140.54 related to PR 21433

### ISSUE THREAD

**Issue by fabiocos** [cms-sw/cmssw#21858]
A new crash (SIGSEV) has appeared in two HI wf (140.52 and 140.54) apparently related to the integration of PR 21433, as it happens in the SiStripMonitorCluster module. In a single-threaded test:

#0  0x000000345d6df383 in poll () from /lib64/libc.so.6
#1  0x00007f5a3df10464 in full_read.constprop () from /cvmfs/cms-ib.cern.ch/nweek-02507/slc6_amd64_gcc630/cms/cmssw/CMSSW_10_0_X_2018-01-14-1100/lib/slc6_amd64_gcc630/pluginFWCoreServicesPlugins.so
#2  0x00007f5a3df10c8a in edm::service::InitRootHandlers::stacktraceFromThread() () from /cvmfs/cms-ib.cern.ch/nweek-02507/slc6_amd64_gcc630/cms/cmssw/CMSSW_10_0_X_2018-01-14-1100/lib/slc6_amd64_gcc630/pluginFWCoreServicesPlugins.so
#3  0x00007f5a3df11cf5 in sig_dostack_then_abort () from /cvmfs/cms-ib.cern.ch/nweek-02507/slc6_amd64_gcc630/cms/cmssw/CMSSW_10_0_X_2018-01-14-1100/lib/slc6_amd64_gcc630/pluginFWCoreServicesPlugins.so
#4  <signal handler called>
#5  0x00007f5a103f5c5f in SiStripMonitorCluster::analyze(edm::Event const&, edm::EventSetup const&) () from /mnt/cms/orp/probdue/CMSSW_10_0_X_2018-01-15-1100/lib/slc6_amd64_gcc630/pluginDQMSiStripMonitorCluster.so
#6  0x00007f5a4ca2831a in edm::stream::EDAnalyzerAdaptorBase::doEvent(edm::EventPrincipal const&, edm::EventSetup const&, edm::ActivityRegistry*, edm::ModuleCallingContext const*) () from /cvmfs/cms-ib.cern.ch/nweek-02507/slc6_amd64_gcc630/cms/cmssw/CMSSW_10_0_X_2018-01-14-1100/lib/slc6_amd64_gcc630/libFWCoreFramework.so
#7  0x00007f5a4c9dd532 in edm::WorkerT<edm::stream::EDAnalyzerAdaptorBase>::implDo(edm::EventPrincipal const&, edm::EventSetup const&, edm::ModuleCallingContext const*) () from /cvmfs/cms-ib.cern.ch/nweek-02507/slc6_amd64_gcc630/cms/cmssw/CMSSW_10_0_X_2018-01-14-1100/lib/slc6_amd64_gcc630/libFWCoreFramework.so
#8  0x00007f5a4c8ed117 in decltype ({parm#1}()) edm::convertException::wrap<bool edm::Worker::runModule<edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1> >(edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::MyPrincipal const&, edm::EventSetup const&, edm::StreamID, edm::ParentContext const&, edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::Context const*)::{lambda()#1}>(bool edm::Worker::runModule<edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1> >(edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::MyPrincipal const&, edm::EventSetup const&, edm::StreamID, edm::ParentContext const&, edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::Context const*)::{lambda()#1}) () from /cvmfs/cms-ib.cern.ch/nweek-02507/slc6_amd64_gcc630/cms/cmssw/CMSSW_10_0_X_2018-01-14-1100/lib/slc6_amd64_gcc630/libFWCoreFramework.so
#9  0x00007f5a4c8ed303 in bool edm::Worker::runModule<edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1> >(edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::MyPrincipal const&, edm::EventSetup const&, edm::StreamID, edm::ParentContext const&, edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::Context const*) () from /cvmfs/cms-ib.cern.ch/nweek-02507/slc6_amd64_gcc630/cms/cmssw/CMSSW_10_0_X_2018-01-14-1100/lib/slc6_amd64_gcc630/libFWCoreFramework.so
#10 0x00007f5a4c8ed68b in std::__exception_ptr::exception_ptr edm::Worker::runModuleAfterAsyncPrefetch<edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1> >(std::__exception_ptr::exception_ptr const*, edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::MyPrincipal const&, edm::EventSetup const&, edm::StreamID, edm::ParentContext const&, edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1>::Context const*) () from /cvmfs/cms-ib.cern.ch/nweek-02507/slc6_amd64_gcc630/cms/cmssw/CMSSW_10_0_X_2018-01-14-1100/lib/slc6_amd64_gcc630/libFWCoreFramework.so
#11 0x00007f5a4c8ef109 in edm::Worker::RunModuleTask<edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1> >::execute() () from /cvmfs/cms-ib.cern.ch/nweek-02507/slc6_amd64_gcc630/cms/cmssw/CMSSW_10_0_X_2018-01-14-1100/lib/slc6_amd64_gcc630/libFWCoreFramework.so
#12 0x00007f5a4b53d42c in tbb::internal::custom_scheduler<tbb::internal::IntelSchedulerTraits>::local_wait_for_all (this=0x7f5a4a347200, parent=..., child=<optimized out>) at ../../src/tbb/custom_scheduler.h:509
#13 0x00007f5a4c99f00e in edm::EventProcessor::readAndProcessEvents() () from /cvmfs/cms-ib.cern.ch/nweek-02507/slc6_amd64_gcc630/cms/cmssw/CMSSW_10_0_X_2018-01-14-1100/lib/slc6_amd64_gcc630/libFWCoreFramework.so
#14 0x00007f5a4c9a9ec9 in edm::EventProcessor::runToCompletion() () from /cvmfs/cms-ib.cern.ch/nweek-02507/slc6_amd64_gcc630/cms/cmssw/CMSSW_10_0_X_2018-01-14-1100/lib/slc6_amd64_gcc630/libFWCoreFramework.so
#15 0x000000000040e7c2 in main::{lambda()#1}::operator()() const ()
#16 0x000000000040d17a in main ()

Current Modules:

Module: SiStripMonitorCluster:SiStripMonitorCluster (crashed)

A fatal system signal has occurred: segmentation violation
Segmentation fault (core dumped)

@ocolegro, @dmitrijus Could you please have a look and provide a fix?

**Comment by smuzaffar** [comment]
ping

**Comment by dmitrijus** [comment]
Investigating...

**Comment by fabiocos** [comment]
@ocolegro, @dmitrijus, @Dr15Jones as discussed at the ORP and Core Software meeting, I revert the PR pending a fix for the problem, which will have to be resubmitted

**Comment by fabiocos** [comment]
#21866 fixes the crashes, so reverting to the old code does not seem needed.
