### ISSUE TITLE
features needed for 94X for XeXe processing

### ISSUE THREAD

**Issue by fabiocos** [cms-sw/cmssw#21889]
HI community is requesting urgently a 9_4_3 build for the XeXe MC campaign. 

#21761 is requested.

@mandrenguyen Please list all the other necessary PRs for this campaign, or confirm that there is none

**Comment by mandrenguyen** [comment]
The list of other needed requests is as follows:  {}

**Comment by fabiocos** [comment]
#21841 integrated as well

changes in vtx smearing name and parameters are claimed to be harmless as they were not used in production so far.
