### ISSUE TITLE
Possible needs for MWGR1 beyond 10_0_0 

### ISSUE THREAD

**Issue by fabiocos** [cms-sw/cmssw#21928]
10_0_0 integrated already 2018 scenarios for the T0. On the basis of the first replay test and other PRs, I see possibly needed:

#21926 trivial fix to prevent skims from crashing
#21914 DQM fix, ok but would be better to avoid hardcoded magic numbers (set it as a parameter)
#21907 Is this the end of the story GT-wise?
#21917 simple fix...
#21923 temporary fix changing the default behaviour, online use only? Follow up with #21355

**Comment by fabiocos** [comment]
assign dqm, alca, reconstruction

**Comment by Martin-Grunewald** [comment]
#21908

**Comment by fabiocos** [comment]
after the ORP of 23 January and before CMSSW_10_0_X_2018-01-23-2300 the following PRs were integrated:

#21907 #21908 #21913 #21914 #21917 #21926 

According to the discussion no patch on top of 10_0_0 was deemed as necessary, and the replay at T0 (apart for skims) was successful.

**Comment by fabiocos** [comment]
PR #21881 was integrated before CMSSW_10_0_X_2018-01-24-1100
