### ISSUE TITLE
Include cuda-api-wrappers as an external

### ISSUE THREAD

**Issue by makortel** [cms-sw/cmssw#21954]
We would like to get cuda-api-wrappers (https://github.com/eyalroz/cuda-api-wrappers, "Thin C++-flavored wrappers for the CUDA runtime API") included in CMSSW as an external. In addition of making the code more C++-like, it greatly simplifies certain things (like passing lambda or `std::function` as a callback for asynchronous processing).

@fwyzard @felicepantaleo @VinInn @vkhristenko @diguida

**Comment by fwyzard** [comment]
how do I assign this to myself ?

**Comment by diguida** [comment]
@makortel thanks for creating the issue. I was writing to @smuzaffar privately about this...

@fwyzard this could be an useful exercise for me to re-gain confidence on CMSSW development and start working deeply with CUDA. Would be ok for you to support me?

**Comment by diguida** [comment]
@menasce this is something you might want to watch as well.

**Comment by fwyzard** [comment]
@smuzaffar could you grant me the permissions to fork into cms-externals ?

**Comment by smuzaffar** [comment]
@fwyzard , I have forked the repo and you have write rights to cms-externals now.

**Comment by fwyzard** [comment]
Done with cms-sw/cmsdist#3691 for 10.1.x and cms-sw/cmsdist#3692 for 10.0.x .

**Comment by fwyzard** [comment]
@diguida, sorry, I've been in a rush all day, and unable to get in touch with you.

What I have done is
  - follow the instructions for building a new externals at https://twiki.cern.ch/twiki/bin/view/CMS/SDTExternalsWithCMSSW
  - copy the spec files for a simple cmake-based external (e.g. xrootd.spec and xrootd-toolfile.spec) to cuda-api-wrappers.spec and cuda-api-wrappers-toolfile.spec 
  - test building the cuda-api-wrappers package locally, and update the spec files accordingly

Some things to keep in mind for the future:
  - cuda-api-wrappers builds as a static library (`libcuda-api-wrappers.a`), so one needs to `%define keep_archives true`
  - cuda-api-wrappers does not have a `make install` target, so one needs to copy the header and library files by hand (not the .cpp files, though)
  - I found an error while building the examples, and made a PR to the author to fix it - the current HEAD already contains the fix

**Comment by fwyzard** [comment]
Possible improvements for the future:
  - add a `make install` target to the upstream software
  - add a BuildFile.xml to build the cuda-api-wrappers examples within CMSSW

**Comment by diguida** [comment]
@fwyzard no problem. Thanks a lot for the pointers to up-to-date instructions and the steps followed by you! I have seen the PR you did to the base repo, now I will check you PR to CMSDIST.

**Comment by makortel** [comment]
Both cmsdist PRs have been merged and the external seems to work, so I close the issue.
