### ISSUE TITLE
SimG4Core/Geometry unit test failure in 10_1_X 

### ISSUE THREAD

**Issue by fabiocos** [cms-sw/cmssw#21952]
One SimG4Core/Geometry unit test is failing in 10_1_X, where Geant4 10.04 + VECGEOM has been set as default:

https://cmssdt.cern.ch/SDT/cgi-bin/buildlogs/slc6_amd64_gcc630/CMSSW_10_1_X_2018-01-24-2300/unitTestLogs/SimG4Core/Geometry

The failure seems to happen here

https://github.com/cms-sw/cmssw/blob/master/SimG4Core/Geometry/test/Cons_.cpp#L51

@civanch @bsunanda @ianna Could you please check and provide a fix?

**Comment by fabiocos** [comment]
I see that the issue is already discussed in #21887

assign simulation geometry

**Comment by ianna** [comment]
assign geometry

**Comment by civanch** [comment]
The fix in pending in #21898 - precision lost in the last digit in computation of mass of  G4Cone.

**Comment by fabiocos** [comment]
It should be fixed by #21898 , now merged
