### ISSUE TITLE
Set dedicated L1 DQM efficiency sequences according to PD

### ISSUE THREAD

**Issue by fabiocos** [cms-sw/cmssw#21963]
The change in PR #21754 implies that efficiencies are computed by dedicated sequences for electrons and tau/muons. RelVals need to be adapted accordingly.

@thomreis @dmitrijus Could you please provide the suggested modification to 

https://github.com/cms-sw/cmssw/blob/master/Configuration/PyReleaseValidation/python/relval_steps.py

to add explicitly the electron and muon sequences where needed?

A similar customisation should be propagated to the T0 configuration

**Comment by thomreis** [comment]
Yes this is correct.

For the T0 configuration @L1TEgamma should be added to the SingleElectron configuration here https://github.com/dmwm/T0/blob/master/etc/ProdOfflineConfiguration.py#L571
@L1TMuon should be added to the SingleMuon configuration here https://github.com/dmwm/T0/blob/master/etc/ProdOfflineConfiguration.py#L586
These are the 2017 datasets but I assume there will be a corresponding configuration for the 2018 datasets.
I did not see a special customisation for the express stream but the two sequences could also run there.

For the RelVal steps configuration I need to go through the file and look for which workflows the two sequences need to run.

**Comment by fabiocos** [comment]
@thomreis can we finalize this move by this week? Otherwise better to temporarily reintegrate the old sequence definition in L1TMon, until this is not done

**Comment by thomreis** [comment]
@fabiocos yes, I will work on it this week.
Shall I make a PR for the dmwm/T0 myself or who is responsible for the autoDQM file there?

**Comment by thomreis** [comment]
Hi @fabiocos I am running some matrix tests at the moment to see if my changes to relval_steps.py have the desired effect.
I had in mind to run for RECODR2_2016 and RECODR2_2017 steps with the corresponding harvesting steps HARVESTDR2 and HARVEST2017. This would mean that the modules are running on more datasets than needed but apart from the skims there is no distinction between datasets for the DQM and harvesting step.

**Comment by dmitrijus** [comment]
assign dqm

**Comment by dmitrijus** [comment]
assign pdmv

**Comment by thomreis** [comment]
Changes for RelVal configuration in PR #22160

**Comment by fabiocos** [comment]
@thomreis @fabozzi @prebello The PR with the update of the L1 sequences has been merged, I expect to see in the validation of 10_1_0_pre2 a confirmation that the new functionality is now fully working
