### ISSUE TITLE
Clean CSCMotherboard code (follow up of #21933)

### ISSUE THREAD

**Issue by fabiocos** [cms-sw/cmssw#22074]
#21933 provides a temporary fix for a bug duplicating ALCTs and CLCTs in the event. The fix is sub-optimal as it implies passing copies of the digis to the correlateLCTs function. The code should be cleaned in order to avoid performance penalties.

@dildick did you check it perhaps? It would be advisable to fix this by 10_1_X

**Comment by fabiocos** [comment]
assign l1

**Comment by dildick** [comment]
@fabiocos I will propose a solution soon. How much time do I have before 10_1_X closes?

**Comment by dildick** [comment]
@tahuang1991 FYI
