### ISSUE TITLE
Testing wf 1325.7 on PRs (nanoAOD)

### ISSUE THREAD

**Issue by fabiocos** [cms-sw/cmssw#22070]
The wf 1325.7 is included in the short matrix used for PR tests, but:

1) it is not part of the comparison list. @slava77 is it possible to add it in the cms-bot list?

2) when I try on cmsdev15 to manually run it (in the 10_1_X IB) I fail in downloading the input files, as they look to be only at FNAL and not on T2_CH_CERN:

13:16 cmsdev15 680> dasgoclient --limit 0 --query 'site dataset=/RelValTTbar_13/CMSSW_9_4_0_pre3-PU25ns_94X_mc2017_realistic_v4-v1/MINIAODSIM'
T1_US_FNAL_Buffer
T1_US_FNAL_Disk
T1_US_FNAL_MSS

I see anyway that the cms-bot test is working:

https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-22037/25760/runTheMatrix-results/1325.7_TTbar_13_94XNanoAODINPUT+TTbar_13_94XNanoAODINPUT+NANOEDMMC2017/

@smuzaffar how is cms-bot managing this?

**Comment by fabiocos** [comment]
@slava77 it looks like that a harvesting step is not present, so anyway no output to compare for the time being...

**Comment by smuzaffar** [comment]
@fabiocos , in IBs we use SITECONF from `/cvmfs/cms-ib.cern.ch` where we have configured xrootd global re-director allow us to acces files from `T1_US_FNAL_Disk`
