### ISSUE TITLE
Timeout in wf 250206.18 (IB 2018-01-31-1100)

### ISSUE THREAD

**Issue by fabiocos** [cms-sw/cmssw#22089]
A timeout problem has been observed in wf 250206.18

https://cmssdt.cern.ch/SDT/cgi-bin/buildlogs/slc6_amd64_gcc630/CMSSW_10_1_X_2018-01-31-1100/pyRelValMatrixLogs/run/250206.18_ZMM_13UP18+ZMM_13UP18INPUT+DIGIPRMXUP18_PU25+RECOPRMXUP18_PU25+HARVESTUP18_PU25/step3_ZMM_13UP18+ZMM_13UP18INPUT+DIGIPRMXUP18_PU25+RECOPRMXUP18_PU25+HARVESTUP18_PU25.log

@Dr15Jones the diagnosis by Chris is that it could only have been caused by a bug in the recent framework change. The hypothesis is an exception happened in an unusual place in the code which lead to some of the TBB tasks to not be launched and therefore the system never thought it was done. 

The problem seems rare enough that no code revert is needed, pending a fix for it.

**Comment by fabiocos** [comment]
@Dr15Jones there was any further understanding of this issue? I do not recall to have seen it again

**Comment by Dr15Jones** [comment]
Since it has never reoccurred (even trying to run the same workflow using the same release) there is no further progress. I did attempt to look through the entire code path and I made some minor changes.

**Comment by fabiocos** [comment]
I close the issue as we haven't seen this problema again. We will reopen it in case.
