### ISSUE TITLE
features needed for 10_0_2

### ISSUE THREAD

**Issue by fabiocos** [cms-sw/cmssw#22139]
List of PR requested to finalize 10_0_2 for DR processing of 2018 MC preproduction.

List received by February 6:

#22002 HCAL, HLT (merged)
#22088 HCAL
#22117 HCAL, HLT (merged)
#22111 HCAL (merged)
#22036 HCAL
#22123 HLT (merged)
#21947 HLT

**Comment by fabiocos** [comment]
#22087 is needed for the final HE scale setting
@arunhep @lpernie the test in 10_1_X is failing, could you please check?

**Comment by fabiocos** [comment]
@Dr15Jones @smuzaffar for the AlcaBeamMonitor crashes, we have already integrated #21996 .
I assume that we need to backport https://github.com/cms-sw/cmsdist/pull/3686 . I do not recall other mitigation actions, do you?

**Comment by fabiocos** [comment]
@franzoni

**Comment by arunhep** [comment]
@fabiocos 
>#22087 is needed for the final HE scale setting

I think you meant to say https://github.com/cms-sw/cmssw/pull/22078 

> @arunhep @lpernie the test in 10_1_X is failing, could you please check?

it was because of some temporary file missing. retriggered the tests. Should be fine

**Comment by smuzaffar** [comment]
@fabiocos , cmsdist PR with updated root is here https://github.com/cms-sw/cmsdist/pull/3718

**Comment by fwyzard** [comment]
@fabiocos , please consider

#22107 Various updates to CMSSW that are not directly related to GPU development (10.0.x)
  - both changes are trivial, but being in CondFormats and DataFormats they bring in plenty of dependency in the developer's area

#21947 Instrument cmssw for nvidia nvprof/nvvm (10.0.x)
  - new functionality, useful for profiling both CPU and GPU modules

#22113 work around clang-tidy multi-line YAML issues (10.0.x backport)
  - this makes it easier for people to run clang-tidy within CMSSW, as it will pick the actual flags we are using instead of the default ones

**Comment by fabiocos** [comment]
@arunhep @lpernie is the situation with GT clarified? Tracking differences are observed also in the 10_1_X PR (#22075 already integrated, and I see some of them in #22137). I repeated a test after the last IB and results look basically the same.

**Comment by fabiocos** [comment]
#22153 (pileup scenario for 2018) has been merged as well

**Comment by fabiocos** [comment]
Relevant missing pieces to close 10_0_2:

#22088 merged in 10_1_X, if ok merge it in 10_0_X, @thomreis @rekovic L1 signature needed
#22036 merged already in 10_1_X, it could be merged in 10_0_X, @dmitrijus @jfernan2  DQM signature needed
#22078 @franzoni  situation to be clarified (likely the last relevant piece missing to begin the DR MC preproduction).

**Comment by arunhep** [comment]
@fabiocos I am trying to run tests with more events and also with different GTs to factorize the updates. I will report the outcome in the PR itself.

**Comment by deguio** [comment]
#22159 contains the updated configuration for HCAL regional reco at HLT.
thanks to @silviodonato

**Comment by fabiocos** [comment]
#22036, #22088 and #22159 have been signed and integrated (and 10_1_X is in sync). We need to converge on the GT, after that I consider that all the crucial needs for 10_0_2 have been integrated and the release is ready to be built (if we get a clean IB as expected).

**Comment by Dr15Jones** [comment]
@fabiocos I do not know of any other changes we have for AlcaBeamMonitor.
