### ISSUE TITLE
HardwareSortingMethods slice the objects passed to it

### ISSUE THREAD

**Issue by Dr15Jones** [cms-sw/cmssw#22151]
The methods `SortJets`, `SortEGammas` and `SortTaus` are passed in a container of classes inheriting from `L1Candidate`. Each function then copies those objects to containers of `L1Candidate` which slices the object such that all the extra member data from the original objects are lost. Those containers are manipulated and finally they copy those `L1Candidate` objects to objects of the original type.

The correct solution would be to change all the helper functions used by the `Sort*` methods to be templated functions so that the original type can be preserved throughout the calculation.

**Comment by Dr15Jones** [comment]
assign l1

**Comment by Dr15Jones** [comment]
#22150 solves this but is not the best solution.

**Comment by smuzaffar** [comment]
@Dr15Jones , I am closing this as #22150 is merged. Feel free to open a new one if improvement can be done on top of  #22150
