### ISSUE TITLE
Avoid calling TClass::GetClass for all setRefCoreStreamer calls

### ISSUE THREAD

**Issue by Dr15Jones** [cms-sw/cmssw#22168]
The clall to `TClass::GetClass` in `setRefCoreStreamer` is meant to do a lazy evaluation for putting our own custom Streamers into ROOT. At present, the custom streamers are just there to customize the writing. The reading is customized by an IO rule. Setting the Streamer at read is probably historic, from the time before the IO rules.

It would probably be possible to move the actually change of the Streamers to the PoolOutputModule's constructor (since the custom Streamers are only needed for writing, not reading). The call to `EDProductGetter::switchProductGetter(...)` would have to remain to keep the IO rule functional.

**Comment by Dr15Jones** [comment]
assign core

**Comment by bbockelm** [comment]
In the discussion with Philippe, the only case where we may not want the streamer set globally if a particular object would need to be serialized differently on output versus input (for example, if we wanted to use a custom streamer for `edm::Ref` on read but write out `edm::Ref` in a ntuple that can be read by bare ROOT.

We didn't think this applied to CMSSW, but felt it was reasonable to point out.

**Comment by wddgit** [comment]
PR #22249 should address this issue and when/if merged allow us to close it.

**Comment by wddgit** [comment]
PR #22249 was merged and this issue should be closed.

**Comment by Dr15Jones** [comment]
+1
