### ISSUE TITLE
Crash in wf 1325.5 caused by PR 22131

### ISSUE THREAD

**Issue by fabiocos** [cms-sw/cmssw#22207]
After the integration of #22131 a reproducible crash is observed in the IB in wf 1325.5, see

https://cmssdt.cern.ch/SDT/cgi-bin/buildlogs/slc6_amd64_gcc630/CMSSW_10_1_X_2018-02-14-0000/pyRelValMatrixLogs/run/1325.5_TTbar_13_reminiaodINPUT+TTbar_13_reminiaodINPUT+REMINIAOD_mc2016+HARVESTDR2_REMINIAOD_mc2016/step2_TTbar_13_reminiaodINPUT+TTbar_13_reminiaodINPUT+REMINIAOD_mc2016+HARVESTDR2_REMINIAOD_mc2016.log

@gpetruc could you please have a look?

**Comment by fabiocos** [comment]
@perrotta @slava77 @rekovic FYI

**Comment by gpetruc** [comment]
Uhm, apparently the MC event believes to be using prescale column 1 (read from the event), while the prescale table (retrieved from the event setup has only one column), so the thing crashes.
I can put a protection like in https://github.com/cms-sw/cmssw/blob/master/L1Trigger/L1TGlobal/src/L1TGlobalUtil.cc#L157-L164 but it would be better to understand upstream why this is happening.

**Comment by rekovic** [comment]
attn @apana

**Comment by slava77** [comment]
assign l1

**Comment by slava77** [comment]
Notably, 1325.5 is "--era Run2_2016,run2_miniAOD_80XLegacy"
the input is a file made in 80X release.

If the column choice was different there and is a property of the 80X data, then the run2_miniAOD_80XLegacy modifier can be used to pick a more appropriate value.

**Comment by slava77** [comment]
assign reconstruction

**Comment by slava77** [comment]
@gpetruc 
given that we were "happy" running on 1325.5 with the older setting of ReadPrescalesFromFile, perhaps you can modify
that value for run2_miniAOD_80XLegacy and we will have the wf running

**Comment by gpetruc** [comment]
On Wed, Feb 14, 2018 at 3:44 PM, Slava Krutelyov <notifications@github.com>
wrote:

> @gpetruc <https://github.com/gpetruc>
> given that we were "happy" running on 1325.5 with the older setting of
> ReadPrescalesFromFile, perhaps you can modify
> that value for run2_miniAOD_80XLegacy and we will have the wf running
>

we were happy in the sense of "no crashes", but it's not clear to me if we
were reading any sensible value for the L1 prescales.

Giovanni

**Comment by slava77** [comment]
> we were happy in the sense of "no crashes", but it's not clear to me if we were reading any sensible value for the L1 prescales.

right. If this lingers unanswered for more than a day, I'd rather we restore running in 1325.5 around Feb 15

**Comment by apana** [comment]
Hi Slava, Giovanni,

Sorry, I was offline most of the day and only now saw this issue.  I'm looking into it and will report back later today.

**Comment by fabiocos** [comment]
@apana I agree with Slava, either this we have a solution by today, or better to revert the change until it is provided.

**Comment by apana** [comment]
Hi Fabio,

I want to take a little time and make sure I fully investigate the
situation. I also don't want to hold up the release cycle so please feel
free to go ahead and revert the change. I'll try to come up with a proper
fix in the next day or so.

-Len

**Comment by gpetruc** [comment]
If this is the only failing workflow, I'll then temporarily reset the parameter to false in the `run2_miniAOD_80XLegacy` era.

Giovanni

**Comment by gpetruc** [comment]
done in https://github.com/cms-sw/cmssw/pull/22239

**Comment by fabiocos** [comment]
@gpetruc @apana thanks, this is the only wf suffering a crash from the original PR by Giovanni, I think the best thing is finding a proper solution with calm. I will integrate the temporary solution by Giovanni, and when we have the fix from L1 we can just remove it.

**Comment by fabiocos** [comment]
@apana I understand #22314 is meant to fix this issue, right?

**Comment by apana** [comment]
Hi Fabio,

Yes.  BTW, we should also remove the temporary fix for this crash
which was made in PR #22239 ( it sets ReadPrescalesFromFile to True in
run2_miniAOD_80XLegacy workflows).  I probably should have added that
to my PR, but wasn't sure. Please let me know if you would like me to
do that now.

-Len

**Comment by fabiocos** [comment]
@apana @gpetruc I have just made #22338 to go back to the original proposal by Giovanni

**Comment by fabiocos** [comment]
The issue looks closed with the last PR merge.
