### ISSUE TITLE
Some clean up needed in CondFormats/GEMObjects

### ISSUE THREAD

**Issue by perrotta** [cms-sw/cmssw#22234]
Please take the following into account before planning further developments in this package:
- ME0ROmap.h and GEMROmap.h are identical, apart the DetID class: do you plan to template them, in order to easen the maintenance of that classes?
- This is even more true for the GEMDeadStrips/ME0DeadStrips and GEMMaskedStrips/ME0MaskedStrips classes, which are exactly identical and don't even need to be templated.
  - By the way, the file ```CondFormats/GEMObjects/src/GEMMaskStrips.cc``` must be renamed ```CondFormats/GEMObjects/src/GEMMaskedStrips.cc```
  - Again: are those classes still needed? If not, just remove them
- Also ME0Emap.h and GEMEmap.h are almost identical and could be more conveniently templated, with some extra effort (GEMDetId::maxStationId can be restricted to 1 in ME0)

@jshlee @slava77 @kpedro88 @hyunyong

**Comment by perrotta** [comment]
assign db

**Comment by dildick** [comment]
Hi Andrea, you bring up a good point. A lot of the code between ME0 and GEM is shared. The GEM DPG group is looking into options to merge the ME0 entirely into the GEM system.

**Comment by perrotta** [comment]
#21681 finally managed to combine previous "GEM" and "ME0" classes into single "GEM" ones, with great simplification and improved manageability of the whole structure. Also the few fixes requested here were implemented in that PR. This does not mean that the work on GEM packer/unpacker and GEMObjects can be considered as concluded: however that PR completely achieve the code cleaning that is requested in this issue. Therefore, I assume it can be closed now.
