### ISSUE TITLE
Crash in EcalDAQ_O2O_test

### ISSUE THREAD

**Issue by fabiocos** [cms-sw/cmssw#22230]
The test EcalDAQ_O2O_test in CondTools/Ecal is crashing in the IB for all architectures since CMSSW_10_1_X_2018-02-14-2300 apparently after the inclusion of #22198 affecting it:

https://cmssdt.cern.ch/SDT/cgi-bin/buildlogs/slc6_amd64_gcc630/CMSSW_10_1_X_2018-02-14-2300/unitTestLogs/CondTools/Ecal

This causes a number of PR tests to fails as well. But the test was running smoothly at the time of integration of #22198 .

**Comment by fabiocos** [comment]
@ggovi @smuzaffar do you see anything changed in the test infrastructure that could cause this? The file .netrc mentioned in the crash report is not part of the PR itself.

**Comment by ggovi** [comment]
@fabiocos 
yes the .netrc has been accidentally overwritten, we are fixing it.

**Comment by smuzaffar** [comment]
@fabiocos , @ggovi , net .netrc has been deployed on all build nodes

**Comment by smuzaffar** [comment]
this is fixed now
