### ISSUE TITLE
Fix the FastSim input MinBias for PU samples

### ISSUE THREAD

**Issue by fabiocos** [cms-sw/cmssw#22232]
The FastSim code migration made before 10_1_0_pre1 build with #20666 is breaking the existing relVal wf with PU because the old MinBias files are incompatible, content-wise, with the new code (different collection name because of different producer name).
10_1_0_pre1 FastSim files should replace the old ones in PyReleaseValidation to prevent crashes.

**Comment by fabiocos** [comment]
assign pdmv

**Comment by fabiocos** [comment]
Dear PdmV experts, when do you expect we can have the files and the corresponding fix in the IB?

**Comment by prebello** [comment]
Dear @fabiocos 
The requested input 
/RelValMinBiasFS_13_ForMixing/CMSSW_10_1_0_pre1-100X_mcRun2_asymptotic_v2_FastSim-v1/GEN-SIM-RECO
is announced. 
It will be tested in the latest IB to open PR with FastSim and GENSIM string updates in 10_1_X, all by tomorrow (Friday).

**Comment by fabiocos** [comment]
@prebello excellent, thanks, as soon as tests are fine please post a PR, so as we can have running wfs hopefully by the week-end

**Comment by prebello** [comment]
Dear @fabiocos please consider to merge #22255 and #22256 together. Thank you

**Comment by fabiocos** [comment]
@prebello they are now both merged
