### ISSUE TITLE
Undefined behaviour in MixCollection

### ISSUE THREAD

**Issue by makortel** [cms-sw/cmssw#22266]
I believe there is undefined behaviour in `MixCollection<T>` (a utility class to iterate over `CrossingFrame<T>`s).

`MixCollection<T>` defines an iterator, `MixCollection<T>::MixItr`. Internally `MixItr` holds two `std::vector<const T*>::const_iterator`'s that mark the beginning and end of iteration for some signal or pileup collection of a single `CrossingFrame<T>`
https://github.com/cms-sw/cmssw/blob/22ead21fa3e5f03c679d51276af2b2358f12a61c/SimDataFormats/CrossingFrame/interface/MixCollection.h#L97-L98
(`CrossingFrame<T>` internally has two `vector`s to hold the signal products and pileup products
https://github.com/cms-sw/cmssw/blob/22ead21fa3e5f03c679d51276af2b2358f12a61c/SimDataFormats/CrossingFrame/interface/CrossingFrame.h#L157-L161
). When `MixItr` reaches the end of a single underlying `vector`, it updates its iterators to those of the "next collection in line" in
https://github.com/cms-sw/cmssw/blob/22ead21fa3e5f03c679d51276af2b2358f12a61c/SimDataFormats/CrossingFrame/interface/MixCollection.h#L238
(the entire logic is too long to be "included" here).

This means that when iterating over a single `MixCollection<T>`, the `MixItr` iternal iterators point to different `vector`s. The `MixItr::operator!=()` is defined as an inequality of the two internal iterators
https://github.com/cms-sw/cmssw/blob/22ead21fa3e5f03c679d51276af2b2358f12a61c/SimDataFormats/CrossingFrame/interface/MixCollection.h#L81
, but comparing iterators of different container objects is undefined behaviour.

This approach has also another, more practical drawback. If it happens that the memory allocated for `pileups_` is just before `signals_`, then (in our production architecture in practice at least) `pileups_.end() == signals_.begin()` and thus `MixCollection<T>::begin() == MixCollection<T>::end()` 
https://github.com/cms-sw/cmssw/blob/22ead21fa3e5f03c679d51276af2b2358f12a61c/SimDataFormats/CrossingFrame/interface/MixCollection.h#L270-L281
and no iteration takes place.

**Comment by Dr15Jones** [comment]
assign simulation

**Comment by makortel** [comment]
I realized the issue while investigating https://github.com/cms-sw/cmssw/pull/22069#issuecomment-364043741.

Minimal fix is in #22270.

The `MixCollection<T>::MixItr` has more room for improvement though, e.g. post-fix `operator++()` is implemented (incorrectly) as the pre-fix operator, but I leave it up to a discussion whether those should be addressed as well.
