### ISSUE TITLE
Several RelVal wf crashing after #22290 integration

### ISSUE THREAD

**Issue by fabiocos** [cms-sw/cmssw#22449]
Starting with CMSSW_10_1_X_2018-03-03-1100 after the integration of #22290 several relval workflows (mostly for 2016) are failing in all architectures. The problem is reproducible and due to the change in the GT (tested for 136.773).

**Comment by fabiocos** [comment]
assign alca

**Comment by lpernie** [comment]
Hi @Martin-Grunewald ,
I see [1] after running "runTheMatrix.py -i 136.773".
Do you have any suggestion on this?

[1] %MSG-w L1TObjectsTiming:  L1TObjectsTiming:l1tObjectsTiming@beginRun  04-Mar-2018 19:26:33 CET Run: 283877
Algo "L1_FirstCollisionInTrain" not found in the trigger menu L1Menu_Collisions2016_v10. Could not retrieve algo bit number.

**Comment by lpernie** [comment]
Seems to me that there is a problem in 101X_dataRun2_PromptLike_v4.
Not sure why, but the difference [1] with old GT show more difference that is should.
I now created **101X_dataRun2_PromptLike_v5**, that should solve the problem.

[1]https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/101X_dataRun2_PromptLike_v4/100X_dataRun2_PromptLike_v1

**Comment by fabiocos** [comment]
@lpernie as far as I can see not all the wfs have the same problem, this PR is fixing most of them, but for 134.813 and 136.733 for instance the issue is different and not removed by your fix:

----- Begin Fatal Exception 05-Mar-2018 13:44:34 CET-----------------------
An exception of category 'NoRecord' occurred while
   [0] Processing  Event run: 272133 lumi: 82 event: 1453074 stream: 2
   [1] Prefetching for module L1TdeStage2EMTF/'l1tdeStage2Emtf'
   [2] Calling method for module L1TMuonEndCapTrackProducer/'valEmtfStage2Digis'
Exception Message:
No "L1TMuonEndCapForestRcd" record found in the EventSetup.n
 Please add an ESSource or ESProducer that delivers such a record.
----- End Fatal Exception -------------------------------------------------

**Comment by rekovic** [comment]
@lpernie @fabiocos 
It looks like GT `101X_dataRun2_PromptLike_v5` 
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/101X_dataRun2_PromptLike_v5/100X_dataRun2_PromptLike_v1
does contain the needed "L1TMuonEndCapForestRcd" and solves the problem. 

Should this PR be closed then?

**Comment by lpernie** [comment]
@rekovic , yes, indeed it as been added.

**Comment by fabiocos** [comment]
@lpernie @rekovic as soon as we get the results of the last IB, where the fix has been deployed, if they are positive as I expect we can close this issue
