### ISSUE TITLE
Allow extra workflows in PR test comparisons

### ISSUE THREAD

**Issue by makortel** [cms-sw/cmssw#22454]
Sometimes it would be useful to be able to produce comparisons for ("extra") workflows that are not run for IB baseline by default. E.g. with #22416 one would have to manually run premixing stage2 workflows for IB and IB+PR to convince oneself that there are no changes.

**Comment by makortel** [comment]
Let me also copy-paste relevant comment from @kpedro88 https://github.com/cms-sw/cmssw/pull/22416#issuecomment-369949629

> It seems possible in principle. We would need to designate a separate list of "additional" baseline workflows, and only generate comparisons for them if the workflow was requested in the PR tests... @slava77 @smuzaffar what do you think?

**Comment by davidlange6** [comment]
But that approach naively means generating baselines for all workflows... instead if a baseline for a workflow is missing, it could just be generated on demand for the specific test request (and made available only for that request). At worst this doubles the resources needed compared to what is done now.

**Comment by kpedro88** [comment]
@davidlange6 yes, I meant that we could generate baselines on demand. But it seems like we might want to keep track of which additional baselines have been generated, in case someone wants to compare the same workflow in a different PR. Maybe this won't happen too often.

**Comment by davidlange6** [comment]
ok, i understood differently - whether caching baseline results is worth the extra complexity is probably up to the code implementer/maintainer..

**Comment by fabiocos** [comment]
as the baseline is the IB, and it changes every 12 hours, I assume that caching makes sense only if this feature is heavily used (and at present extra workflows do not seem to be run very often as far as I can see...)

**Comment by makortel** [comment]
assign core

**Comment by tvami** [comment]
Let me second this initiative, for example it would have been very nice for 35441
