### ISSUE TITLE
 Add a warning or error if multiple plugins produce the same _cfi.py file

### ISSUE THREAD

**Issue by fwyzard** [cms-sw/cmssw#22474]
With the use of `fillDescriptions()` and `edmWriteConfigs` to generate _cfi.py files, it is possible that different plugins in the same package will try to create a _cfi.py file with the same name.

The most common source of the problem is if somebody writes a new plugin, starting from an existing one, that implemented its `fillDescriptions()` with an explicit module label, e.g.
```
MyPlugin::fillDescriptions(edm::ConfigurationDescriptions& descriptions)
{
    edm::ParameterSetDescription desc;
    ...
    descriptions.add("myPlugin", desc);
}
```

If the user forget to change the `descriptions.add("myPlugin", desc);` line to use a different label, both plugins will try to create the file `myPlugin_cfi.py`.

Would it be possible for `edmWriteConfigs` to catch such cases, and raise a warning or an error ?

**Comment by smuzaffar** [comment]
assign core

**Comment by wddgit** [comment]
@fwyzard  I think I fixed this already in PR #19729 that I think went into 9_3_X. Have you tried this with a release past 9_3_X and still see the problem? If so, I will take another look and see what I missed.

**Comment by fwyzard** [comment]
Mhm, I had it on my list of issues, but since this long ago... buy maybe I was still using 9.2.x.
I'll give it a try with 10.1.x and let you know.

**Comment by makortel** [comment]
@wddgit What happens in a case where for some package `plugins/BuildFile.xml` declares two plugin libraries, and they contain (different) EDModule classes whose `fillDescriptions()` generate the same name?

**Comment by smuzaffar** [comment]
@makortel , yes that is also a bug. scram is going to blindly override. I will add a protection against this.

**Comment by wddgit** [comment]
@makortel Yes, that will still be a problem. The check I added only looks for duplicates in one invocation of the edmWriteConfig executable and one invocation only handles one library. It does not know anything about the cfi files of other libraries.

**Comment by Dr15Jones** [comment]
@wddgit @smuzaffar can this now be closed?

**Comment by smuzaffar** [comment]
assign externals
no, this is not yet resolved. So please leave it open

**Comment by smuzaffar** [comment]
+externals
Build Rules has been fixed to avoid duplicate _cfi.py files generatd via different plugins of a same package
