### ISSUE TITLE
Add a warning or error if multiple files compile to the same .o file

### ISSUE THREAD

**Issue by fwyzard** [cms-sw/cmssw#22472]
Source files in the same directory with the same base name are compiled by SCRAM into an intermediate .o file with the same name.
For example
```
src/Subsystem/Package/test/naming.cc
src/Subsystem/Package/test/naming.cpp
```
all end up built as
```
tmp/slc7_amd64_gcc630/src/Subsystem/Package/test/testNaming/naming.o
```

This is then caught because (assuming `test.cpp` has `main()` and `test.cc` has some worker code) it causes a link error.

A more subtle problem happens if
```
src/Subsystem/Package/src/plugin.cc
src/Subsystem/Package/src/plugin.cpp
```
or, less unlikely
```
src/Subsystem/Package/src/plugin.cc
src/Subsystem/Package/src/plugin.cu
```
implement two different plugins (e.g. `Plugin` and `PluginGPU`).
In this case the compilation will likely succeed, but it will be incomplete, with a missing plugin (which one will depend on the compilation order).

Would it be possible to SCRAM to notice when different source files may end up compiled into the same .o file, and issue a warning or error ?

**Comment by smuzaffar** [comment]
assign externals

**Comment by smuzaffar** [comment]
@fwyzard , we can update build rules to generate filename.o e.g. plugin.cc.o and plugin.cu.o to avoid this.

**Comment by fwyzard** [comment]
Sounds good - yes, that should fix the issue.

**Comment by smuzaffar** [comment]
@fwyzard , in CMSSW_10_2_X IBs, we now have new build rules (cmssw-config tag V05-07-00) where we create filename.ext.o instead of filename.o

**Comment by smuzaffar** [comment]
+externals
