### ISSUE TITLE
Fireworks: invalid reads in tree cache prefetching

### ISSUE THREAD

**Issue by alja** [cms-sw/cmssw#22516]
## valgrind report:
http://xrd-cache-1.t2.ucsd.edu/alja/valgrind.log.pcanal4

valgrind command:
 valgrind --num-callers=30 --log-file=valgrind.log.pcanal4 --freelist-vol=100000000  --error-limit=no  --track-origins=yes  cmsShow.exe  ~/run310178_ls0007_streamEvDOutput_dqmcluster.root

**Comment by alja** [comment]
@pcanal I could not include the ROOT suppressions . The *match-leak-kinds: possible* is not valid in valgrin in SLC:

alja@xrootd /data/cms/alja/CMSSW_10_0_2_FWLITE/src$ valgrind --num-callers=30 --freelist-vol=100000000  --error-limit=no  --track-origins=yes --suppressions=$ROOTSYS/etc/valgrind-root.supp cmsShow.exe --tree-cache-prefetch ~/run310178_ls0007_streamEvDOutput_dqmcluster.root
==125216== Memcheck, a memory error detector
==125216== Copyright (C) 2002-2012, and GNU GPL'd, by Julian Seward et al.
==125216== Using Valgrind-3.8.1 and LibVEX; rerun with -h for copyright info
==125216== Command: cmsShow.exe --tree-cache-prefetch /home/alja/run310178_ls0007_streamEvDOutput_dqmcluster.root
==125216==
location should be "...", or should start with "fun:" or "obj:"
==125216== FATAL: in suppressions file "/data/cms/alja/FW_REPO_10_0_2/slc6_amd64_gcc630/lcg/root/6.10.09-mmelna2//etc/valgrind-root.supp" near line 25:
==125216==    location should be "...", or should start with "fun:" or "obj:"
==125216== exiting now.

**Comment by pcanal** [comment]
> The match-leak-kinds: possible is not valid in valgrin in SLC:

Can you remove those lines from the file and retry?

**Comment by alja** [comment]
@pcanal http://xrd-cache-1.t2.ucsd.edu/alja/valgrind.log.pcanal5

**Comment by pcanal** [comment]
Can you remind me the ROOT version (so that I can align the line numbers)?

**Comment by alja** [comment]
@pcanal 
ROOT is 6.10/09                
From tag , 16 October 2017                      

here is the spec file:https://github.com/cms-sw/cmsdist/blob/IB/CMSSW_10_0_X/gcc630/root.spec

**Comment by Dr15Jones** [comment]
assign core

**Comment by Dr15Jones** [comment]
assign visualization

**Comment by smuzaffar** [comment]
@alja , is it still an open issue?

**Comment by alja** [comment]
@smuzaffar @osschar 
I don't know internals of TTreeCache pre-fetching and I also forgot its importance. The issue is more than 3 years old and the logs are lost. I have moved this issue to my git project so we don't forget about it.

**Comment by alja** [comment]
@smuzaffar One more reason to drop this issue is that remote web event display can be combined with xrootd data access that has cache enabled.
