### ISSUE TITLE
Catch case when produces<...,InRun> is called when module is not a Run producer

### ISSUE THREAD

**Issue by Dr15Jones** [cms-sw/cmssw#22514]
We should catch the cases where in the constructor of a module there is a `produces<..., [not event]>` call but that module does not have as a template argument the appropriate `Producer` class.

E.g. calling `produces<..., InRun>()` when the module does not declare `edm::BeginRunProducer` or `edm::EndRunProducer`.

**Comment by Dr15Jones** [comment]
assign core

**Comment by Dr15Jones** [comment]
@wddgit this was solved in #22560 ?

**Comment by wddgit** [comment]
Yes. We should close this issue.

**Comment by Dr15Jones** [comment]
+1
