### ISSUE TITLE
Old CMSSW release and GitHub problem

### ISSUE THREAD

**Issue by geonmo** [cms-sw/cmssw#22522]
Dear CMSSW Developer,

I found that the git commands were not working on old CMSSW release. (CMSSW_7_6_6)

Here is a log message when I tried git-clone.

```bash
> [geonmo@ui10 src]$ git clone https://github.com/geonmo/manageTools.git
Cloning into 'manageTools'...
fatal: unable to access 'https://github.com/geonmo/manageTools.git/': error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version
```

I guess that this error was occurred due to a version of embedded git program.

Could you let me know how to solve this?

Regards,

**Comment by smuzaffar** [comment]
closing it, please reopen a new one of you still have such problem

**Comment by Martin-Grunewald** [comment]
However, checking out the PR seems to work fine in the PR tests: https://github.com/cms-sw/cmssw/pull/40031
So what is the magic used?
