### ISSUE TITLE
Next 9_3_X release for L1T Phase2

### ISSUE THREAD

**Issue by kpedro88** [cms-sw/cmssw#22554]
PRs to include:
* #22190 Enable TrackTriggerAssociatorClustersStubs in L1TrackTrigger sequence
* #22480 [Backport] HGCAL trigger updates - 1
* #22487 [Backport] HGCAL trigger updates - 2
* #22479 Using dasgoclient for das queries in runTheMatrix (93X)
* https://github.com/cms-sw/cmsdist/pull/3815 Update L1Trigger-L1THGCal to tag 05 (93X)

Currently waiting on #22387 to be merged in 10_1_X.

attn: @fabiocos @rekovic

**Comment by kpedro88** [comment]
assign upgrade,l1

**Comment by fabiocos** [comment]
@kpedro88 #22387 has been merged for the Sunday night IB

**Comment by rekovic** [comment]
@kpedro88 
Thanks for keeping creating this issue that lists and keeps track of needed PRs for L1T Phase2.
I have also kept track and status of the needed PRs on our L1T Phase-2 twiki
https://twiki.cern.ch/twiki/bin/view/CMSPublic/SWGuideL1TPhase2Instructions#Descritipon

@fabiocos 
Ideally I would also like the EventContent PR https://github.com/cms-sw/cmssw/pull/22415 also kept track of at https://github.com/cms-sw/cmssw/issues/22483 fixed and back-ported.  If not resolved by Tuesday ORP meeting, I would like to go with what we have merged so far (all listed in this issue) and build a 9_3_6 release.

**Comment by rekovic** [comment]
updated twiki
https://twiki.cern.ch/twiki/bin/view/CMSPublic/SWGuideL1TPhase2Instructions#Descritipon

**Comment by kpedro88** [comment]
Add to the list:
https://github.com/cms-sw/cmsdist/pull/3839

**Comment by kpedro88** [comment]
Another:
#22588

**Comment by kpedro88** [comment]
And:
#22591 
(needs #22415 merged in master first)

**Comment by kpedro88** [comment]
Also:
#22608 
(needs #22607 merged in master first)

**Comment by kpedro88** [comment]
+1
see #22666

**Comment by imarches** [comment]
If still possible this could be included:

https://github.com/cms-sw/cmssw/pull/22723

**Comment by kpedro88** [comment]
We will make 9_3_8 with https://github.com/cms-sw/cmsdist/pull/3862, so it might be able to go in as well.

**Comment by imarches** [comment]
Thanks @kpedro88 not urgent for this release cycle, but in case possible even better
