### ISSUE TITLE
Huge  log for phase2 workflows 

### ISSUE THREAD

**Issue by boudoul** [cms-sw/cmssw#22582]
Greetings,
The phase2 workflows (2023D21, 2023D17 etc...) are still exhibiting very long logs which make testing (and actually scrutinizing the logs ) very complicated . There is below a copy paste of a (small) fraction of the logs  - Looks like it is on thePFTrackProducer:pfTrack .  Could someone investigate if those are harmless and eventually fix or take actions ? I seem to remember a previous open issue on this but I'm not sure (and can't find it actually) .

Reducing the phase2 logs would be very appreciated . Thank you. 

%MSG-w PFTrackTransformer:  PFTrackProducer:pfTrack 12-Mar-2018 01:16:30 CET  Run: 1 Event: 10
KF TRACK Reco track charge = 1, type = 1, Pt = 8.37763, P = 97.0849
	R0 = 0.010947 Z0 = -1.50682
	number of tracker measurements = 0
	number of points total = 4
Traj point id = -1, layer = 0, Eta,Phi = -5.61786,-2.32022, X,Y = -0.00745722,-0.0080141, R,Z = 0.010947,-1.50682, E,Pt = 97.0849,8.37763
Traj point id = -1, layer = 1, Eta,Phi = -3.19199,-0.756139, X,Y = 1.81873,-1.71529, R,Z = 2.5,-30.3697, E,Pt = 97.085,8.37763
Traj point id = -1, layer = -1, Eta,Phi = 0,0, X,Y = 0,0, R,Z = 0,0, E,Pt = 0,0
Traj point id = -1, layer = -1, Eta,Phi = 0,0, X,Y = 0,0, R,Z = 0,0, E,Pt = 0,0
 PROPAGATION TO THE ECAL HAS FAILED
%MSG
%MSG-w PFTrackTransformer:  PFTrackProducer:pfTrack 12-Mar-2018 01:16:30 CET  Run: 1 Event: 10
KF TRACK Reco track charge = 1, type = 1, Pt = 8.37763, P = 97.0849
	R0 = 0.010947 Z0 = -1.50682
	number of tracker measurements = 0
	number of points total = 6
Traj point id = -1, layer = 0, Eta,Phi = -5.61786,-2.32022, X,Y = -0.00745722,-0.0080141, R,Z = 0.010947,-1.50682, E,Pt = 97.0849,8.37763
Traj point id = -1, layer = 1, Eta,Phi = -3.19199,-0.756139, X,Y = 1.81873,-1.71529, R,Z = 2.5,-30.3697, E,Pt = 97.085,8.37763
Traj point id = -1, layer = -1, Eta,Phi = 0,0, X,Y = 0,0, R,Z = 0,0, E,Pt = 0,0
Traj point id = -1, layer = -1, Eta,Phi = 0,0, X,Y = 0,0, R,Z = 0,0, E,Pt = 0,0
Traj point id = -1, layer = -1, Eta,Phi = 0,0, X,Y = 0,0, R,Z = 0,0, E,Pt = 0,0
Traj point id = -1, layer = -1, Eta,Phi = 0,0, X,Y = 0,0, R,Z = 0,0, E,Pt = 0,0
 PROPAGATION TO THE HCAL ENTRANCE HAS FAILED
%MSG
%MSG-w PFTrackTransformer:  PFTrackProducer:pfTrack 12-Mar-2018 01:16:30 CET  Run: 1 Event: 10
KF TRACK Reco track charge = 1, type = 1, Pt = 5.51758, P = 66.1883
	R0 = 0.0027203 Z0 = -1.56612
	number of tracker measurements = 0
	number of points total = 4
Traj point id = -1, layer = 0, Eta,Phi = -7.04876,-0.363833, X,Y = 0.00254223,-0.000968043, R,Z = 0.0027203,-1.56612, E,Pt = 66.1883,5.51758
Traj point id = -1, layer = 1, Eta,Phi = -3.22687,1.20216, X,Y = 0.900848,2.33205, R,Z = 2.5,-31.4513, E,Pt = 66.1884,5.51758
Traj point id = -1, layer = -1, Eta,Phi = 0,0, X,Y = 0,0, R,Z = 0,0, E,Pt = 0,0
Traj point id = -1, layer = -1, Eta,Phi = 0,0, X,Y = 0,0, R,Z = 0,0, E,Pt = 0,0
 PROPAGATION TO THE ECAL HAS FAILED
%MSG
%MSG-w PFTrackTransformer:  PFTrackProducer:pfTrack 12-Mar-2018 01:16:30 CET  Run: 1 Event: 10
KF TRACK Reco track charge = 1, type = 1, Pt = 5.51758, P = 66.1883
	R0 = 0.0027203 Z0 = -1.56612
	number of tracker measurements = 0
	number of points total = 6
Traj point id = -1, layer = 0, Eta,Phi = -7.04876,-0.363833, X,Y = 0.00254223,-0.000968043, R,Z = 0.0027203,-1.56612, E,Pt = 66.1883,5.51758
Traj point id = -1, layer = 1, Eta,Phi = -3.22687,1.20216, X,Y = 0.900848,2.33205, R,Z = 2.5,-31.4513, E,Pt = 66.1884,5.51758
Traj point id = -1, layer = -1, Eta,Phi = 0,0, X,Y = 0,0, R,Z = 0,0, E,Pt = 0,0
Traj point id = -1, layer = -1, Eta,Phi = 0,0, X,Y = 0,0, R,Z = 0,0, E,Pt = 0,0
Traj point id = -1, layer = -1, Eta,Phi = 0,0, X,Y = 0,0, R,Z = 0,0, E,Pt = 0,0
Traj point id = -1, layer = -1, Eta,Phi = 0,0, X,Y = 0,0, R,Z = 0,0, E,Pt = 0,0
 PROPAGATION TO THE HCAL ENTRANCE HAS FAILED
%MSG
%MSG-w PFTrackTransformer:  PFTrackProducer:uncleanedOnlyPfTrack  12-Mar-2018 01:16:30 CET Run: 1 Event: 10
KF TRACK Reco track charge = 1, type = 1, Pt = 8.37763, P = 97.0849
	R0 = 0.010947 Z0 = -1.50682
	number of tracker measurements = 0
	number of points total = 4
Traj point id = -1, layer = 0, Eta,Phi = -5.61786,-2.32022, X,Y = -0.00745722,-0.0080141, R,Z = 0.010947,-1.50682, E,Pt = 97.0849,8.37763
Traj point id = -1, layer = 1, Eta,Phi = -3.19199,-0.756139, X,Y = 1.81873,-1.71529, R,Z = 2.5,-30.3697, E,Pt = 97.085,8.37763
Traj point id = -1, layer = -1, Eta,Phi = 0,0, X,Y = 0,0, R,Z = 0,0, E,Pt = 0,0
Traj point id = -1, layer = -1, Eta,Phi = 0,0, X,Y = 0,0, R,Z = 0,0, E,Pt = 0,0
 PROPAGATION TO THE ECAL HAS FAILED
%MSG
%MSG-w PFTrackTransformer:  PFTrackProducer:uncleanedOnlyPfTrack  12-Mar-2018 01:16:30 CET Run: 1 Event: 10
KF TRACK Reco track charge = 1, type = 1, Pt = 8.37763, P = 97.0849
	R0 = 0.010947 Z0 = -1.50682
	number of tracker measurements = 0
	number of points total = 6
Traj point id = -1, layer = 0, Eta,Phi = -5.61786,-2.32022, X,Y = -0.00745722,-0.0080141, R,Z = 0.010947,-1.50682, E,Pt = 97.0849,8.37763
Traj point id = -1, layer = 1, Eta,Phi = -3.19199,-0.756139, X,Y = 1.81873,-1.71529, R,Z = 2.5,-30.3697, E,Pt = 97.085,8.37763
Traj point id = -1, layer = -1, Eta,Phi = 0,0, X,Y = 0,0, R,Z = 0,0, E,Pt = 0,0
Traj point id = -1, layer = -1, Eta,Phi = 0,0, X,Y = 0,0, R,Z = 0,0, E,Pt = 0,0
Traj point id = -1, layer = -1, Eta,Phi = 0,0, X,Y = 0,0, R,Z = 0,0, E,Pt = 0,0
Traj point id = -1, layer = -1, Eta,Phi = 0,0, X,Y = 0,0, R,Z = 0,0, E,Pt = 0,0
 PROPAGATION TO THE HCAL ENTRANCE HAS FAILED
%MSG
%MSG-w PFTrackTransformer:  PFTrackProducer:uncleanedOnlyPfTrack  12-Mar-2018 01:16:30 CET Run: 1 Event: 10

**Comment by Dr15Jones** [comment]
assign reconstruction, upgrade

**Comment by kpedro88** [comment]
These messages have been there forever. I suspect the underlying problem is the lack of effort to adapt ParticleFlow to the extended tracker and HGCal. This is an ongoing area of concern, so I am reluctant just to disable the messages and ignore the problem.

For private runs, you could suppress the messages in your config, following https://twiki.cern.ch/twiki/bin/view/CMSPublic/SWGuideMessageLoggerSetupExamples#Suppressing_Messages_From_Specif.

**Comment by VinInn** [comment]
maybe it can be shorted to just
PROPAGATION TO THE E/HCAL ENTRANCE HAS FAILED
the rest of the information seems pretty redundant at this point...

**Comment by hatakeyamak** [comment]
https://github.com/cms-sw/cmssw/pull/27131
should have addressed this, which is merged in CMSSW_11_0_0_preX.

**Comment by kpedro88** [comment]
@hatakeyamak thanks! To make sure I'm clear, your PR does two separate things:
1. reduces the warning messages from PF
2. allows (but does not enable) propagation to HF
Is that correct?

**Comment by hatakeyamak** [comment]
Yes, for 1.

For 2, now we can get extrapolation of tracks to HF surface, but we are not enabling links of tracks and HF clusters yet. Such PR is still in progress. Stay tuned.

**Comment by kpedro88** [comment]
+upgrade

**Comment by hatakeyamak** [comment]
We still have to deal with:

%MSG-e PFEGammaProducer:  PFEGammaProducer:particleFlowEGamma  13-Aug-2019 11:13:22 CDT Run: 1 Event: 1
PFBLOCKALGO BUG!!!! Found a SuperCluster in a block by itself!
%MSG

so we can keep this issue alive for now. I think it comes from SC from HGCAL, but the fact that HGCAL's PFClusters don't go into PFBlocks cause this message. If this can be confirmed, I think this can be addressed by (1) suppress this message when such SC comes from HGCAL, or (2) prevent SC from HGCAL from going into PFBLocks.

**Comment by hatakeyamak** [comment]
With the convergence of the above PR #27785 I think we can consider this issue is resolved.

**Comment by hatakeyamak** [comment]
Not sure who needs to sign it off to make it closed..

**Comment by kpedro88** [comment]
+upgrade

**Comment by hatakeyamak** [comment]
I guess reco also needs to sign it off.

**Comment by slava77** [comment]
+1

I checked PU200 wf 20634.0 (D41 ttbar): before this PR [in CMSSW_11_0_X_2019-09-04-1100] there are about 120 warnings per event ```PFBLOCKALGO BUG!!!! Found a SuperCluster in a block by itself!```. After this PR [in CMSSW_11_0_0_pre7] these warnings are gone.
There are no PF-related reco warnings based on a pattern.
