### ISSUE TITLE
Include workflow that uses pre-mixing in PR integration tests

### ISSUE THREAD

**Issue by christopheralanwest** [cms-sw/cmssw#22586]
Recently there have been two instances [1, 2] in which pre-mixing release validation has failed for the HCAL because the histograms needed for validation were entirely missing. It seems that this sort of problem could be caught easily in PR integration tests. Would it be possible to include a workflow that uses pre-mixing in the PR integration tests to ensure that such problems are identified prior to the release validation?

Attn: @kpedro88 @deguio @hatakeyamak 

[1] https://its.cern.ch/jira/browse/CMSLITDPG-249
[2] https://hypernews.cern.ch/HyperNews/CMS/get/relval/10038/29.html

**Comment by makortel** [comment]
I support the request as it would solve also my immediate need for #22454 (in the context of phase2 premixing development).

**Comment by makortel** [comment]
I suggest we add a combined stage1+stage2 workflow for 2018 in the PR tests once #22956 (which adds them) gets merged.
