### ISSUE TITLE
Use of edm::RandomNumberGenerator in Phase2TrackerDigitizer is not safe

### ISSUE THREAD

**Issue by makortel** [cms-sw/cmssw#22710]
`Phase2TrackerDigitizer` acquires `CLHEP::HepRandomEngine` from `edm::RandomNumberGenerator` service in `beginLuminosityBlock`
https://github.com/cms-sw/cmssw/blob/4d5e4d2323e0f1fdbb14113c97fa060cb6f0feea/SimTracker/SiPhase2Digitizer/plugins/Phase2TrackerDigitizer.cc#L98-L106
passes it to the member algorithm objects
https://github.com/cms-sw/cmssw/blob/4d5e4d2323e0f1fdbb14113c97fa060cb6f0feea/SimTracker/SiPhase2Digitizer/plugins/Phase2TrackerDigitizer.cc#L130-L133
which themselves store the engine as well as CLHEP distribution classes
https://github.com/cms-sw/cmssw/blob/4d5e4d2323e0f1fdbb14113c97fa060cb6f0feea/SimTracker/SiPhase2Digitizer/plugins/Phase2TrackerDigitizerAlgorithm.cc#L156-L161
which are then called for each event via `MixingModule::produce()`.

This pattern is bad in several ways: (quoting @wddgit )

> First in multithreaded mode, different events which may be processed on different streams simultaneously will have the same engine. The engines are not thread safe to be generating more than one random number at the same time. So this will create data races. It is OK to have different engines generating random numbers concurrently, but not one engine.
> 
> Second, every luminosity block gets an engine in the same state every time. So even if you get lucky and avoid the data races, then multiple events will end up getting the same sequence of random numbers and there will be some weird correlation between the events. I mean it would only affect this one module and the fact that the events are otherwise different might smear any effects out, but still this sounds bad for physics analysis using the simulation. It is hard to say exactly what it would do.
> 
> When we get to multiple concurrent luminosity blocks it probably breaks replay also.
> 
> The lumi engines should only be used in the lumi methods and only the one corresponding to the current lumi index. The event engines should only be used for events and the only the one corresponding to the current stream. 

The code needs to be fixed to acquire the `CLHEP::HepRandomEngine`'s in the per-event functions.

@boudoul @emiglior @Dr15Jones @wddgit

**Comment by boudoul** [comment]
Thanks @makortel for reporting, let me add @suchandradutta to make her aware of this issue

**Comment by suchandradutta** [comment]
I am looking into it and shall update the code accordingly

**Comment by kpedro88** [comment]
assign upgrade

**Comment by makortel** [comment]
Fixed in #22836.
