### ISSUE TITLE
Use of edm::RandomNumberGenerator in HGCDigiProducer

### ISSUE THREAD

**Issue by makortel** [cms-sw/cmssw#22712]
`HGCDigiProducer` (which is/can be a member variable of `MixingModule`, which itself is a `stream::EDProducer`) has a local "stream cache" for `CLHEP::HepRandomEngine`s.
https://github.com/cms-sw/cmssw/blob/301a35e206b6d2b8fe036ef003e7f00e772f3291/SimCalorimetry/HGCalSimProducers/plugins/HGCDigiProducer.cc#L47-L50
https://github.com/cms-sw/cmssw/blob/301a35e206b6d2b8fe036ef003e7f00e772f3291/SimCalorimetry/HGCalSimProducers/plugins/HGCDigiProducer.cc#L69-L81

A private e-mail thread with @Dr15Jones and @wddgit concludes that this construct should be safe, even if it is a bit weird.

The only benefit of this construct we could think of is being able to obtain the `CLHEP::HepRandomEngine` on O(1) time instead of O(log n) time.

I nevertheless decided to create an issue on this to understand why the cache is needed, and if we are happy with it or not.

**Comment by makortel** [comment]
@lgray It seems that this cache was created in your commit 9a538de0effffe85660de88a748796724037a78f of #11880. Do you have a recollection why the cache was needed?

**Comment by wddgit** [comment]
There are actually two separate questions.

1. Why do we need a vector of pointers instead of just one pointer in HGCProducer if there is already an HGCDigiProducer per stream? This was confusing to me and unless I am missing something unnecessary, although I know very little about the MixingModule.

2. Is it worth the effort to cache the pointer? This actually does improve performance slightly so maybe this is OK. It might also be a negligible improvement.

**Comment by makortel** [comment]
@wddgit I spotted the same pattern in many other classes within the MixingModule plugins, e.g.
https://github.com/cms-sw/cmssw/blob/285a1d8ec5a00469793b03dca3bc661e4af4a5ad/SimCalorimetry/CastorSim/plugins/CastorDigiProducer.cc#L166-L178
https://github.com/cms-sw/cmssw/blob/285a1d8ec5a00469793b03dca3bc661e4af4a5ad/SimCalorimetry/EcalSimProducers/src/EcalDigiProducer.cc#L631-L643
https://github.com/cms-sw/cmssw/blob/285a1d8ec5a00469793b03dca3bc661e4af4a5ad/SimCalorimetry/HcalSimProducers/src/HcalDigiProducer.cc#L88-L100
https://github.com/cms-sw/cmssw/blob/285a1d8ec5a00469793b03dca3bc661e4af4a5ad/SimCalorimetry/HcalTestBeam/src/HcalTBDigiProducer.cc#L246-L258
https://github.com/cms-sw/cmssw/blob/285a1d8ec5a00469793b03dca3bc661e4af4a5ad/SimTracker/SiPixelDigitizer/plugins/SiPixelDigitizer.cc#L303-L315
https://github.com/cms-sw/cmssw/blob/285a1d8ec5a00469793b03dca3bc661e4af4a5ad/SimTracker/SiStripDigitizer/plugins/SiStripDigitizer.cc#L290-L302
https://github.com/cms-sw/cmssw/blob/285a1d8ec5a00469793b03dca3bc661e4af4a5ad/Validation/EcalDigis/src/EcalMixingModuleValidation.cc#L811-L823

so maybe the pattern in HGCDigiProducer is just copy-paste from elsewhere?

Then there is 
https://github.com/cms-sw/cmssw/blob/285a1d8ec5a00469793b03dca3bc661e4af4a5ad/Mixing/Base/src/PileUp.cc#L343-L349
which caches the random engine to a member variable. All these were added in commit 
6696e5d7ccf9 of #2392. If we now think the pattern could be improved, maybe we should just do it everywhere?

@Dr15Jones, could you remind me if an instance of a stream module is always run in the same stream (i.e. is the pattern of `PileUp::randomEngine()` safe)?

**Comment by Dr15Jones** [comment]
> @Dr15Jones, could you remind me if an instance of a stream module is always run in the same stream (i.e. is the pattern of PileUp::randomEngine() safe)?

An instance of a stream module is always run in the same stream.

**Comment by wddgit** [comment]
Looks like I created this pattern back in 2014. I did not remember
that.

After staring at CastorDigiProducer more, I cannot understand or remember
why I used a vector to cache the pointers in. If I understand this correctly,
the MixingModule is a stream module and each stream instance has its
own CastorDigiProducer so there is no reason for a vector with an entry
per stream. (And if there had been a reason for the vector, then the call
to the resize function would have been a date race. Sigh.) On the positive
side, it should work correctly and its performance should be OK.

Removing the vector in all these cases would be a good thing. It is confusing
to someone reading, maintaining or copying the code. The PileUp
class does not have this problem.

There is the separate issue of whether we should cache or not.
Probably back in 2014, I was trying to make it perform as fast
as possible and caching is probably faster. But I agree the
difference is likely negligible. I do not feel strongly about this either
way.

**Comment by wddgit** [comment]
Also note EcalMixingModuleValidation is a one type module. For that
type of module the vector is needed and correct.

**Comment by wddgit** [comment]
I found the reason it was coded that way. Back in 2014 the
MixingModule was a one module. In 2015 it was changed to
be a stream type module. Now I feel better about it ...

**Comment by makortel** [comment]
@wddgit Thanks for reminding of the history. Should we then migrate everything else than `EcalMixingModuleValidation` to the same caching pattern as in `PileUp`?

**Comment by wddgit** [comment]
That sounds like the best course to me. I see that Dan Riley did that for the PileUp class back in 2015.

I don't feel strongly about this though. If you or Chris advocate removing the caching entirely I would be happy with that also. It might be worth testing that we do not slow it down significantly if we remove the caching.

Matti, were you going to make this change? @Dr15Jones If you want me to do it, let me know and what its priority is compared to what I am currently working on.

**Comment by makortel** [comment]
@wddgit I talked briefly with @Dr15Jones and we felt as well to keep the caching (without strong feelings). I can take care of it at some point in the near future.

**Comment by makortel** [comment]
The cleanup is in #22874.
