### ISSUE TITLE
CMSSW_10_0_X wf 1020 fails in step5

### ISSUE THREAD

**Issue by fabiocos** [cms-sw/cmssw#22735]
The new wf 1020, introduced to monitor the AlCa PCC workflow, runs smoothly in CMSSW_10_1_X, but its backport into 10_0_X fails in step5:

https://cmssdt.cern.ch/SDT/cgi-bin/buildlogs/slc7_amd64_gcc630/CMSSW_10_0_X_2018-03-25-0000/pyRelValMatrixLogs/run/1020.0_AlCaLumiPixels2016H+AlCaLumiPixels2016H+TIER0EXPLP+ALCAEXPLP+ALCAHARVLP+TIER0PROMPTLP/step5_AlCaLumiPixels2016H+AlCaLumiPixels2016H+TIER0EXPLP+ALCAEXPLP+ALCAHARVLP+TIER0PROMPTLP.log

----- Begin Fatal Exception 25-Mar-2018 12:00:08 CEST-----------------------
An exception of category 'ProductNotFound' occurred while
   [0] Processing global end LuminosityBlock run: 283383 luminosityBlock: 1
   [1] Calling method for module RawPCCProducer/'ALCARECORawPCCProd'
Exception Message:
Principal::getByToken: Found zero products matching all criteria
Looking for type: reco::PixelClusterCounts
Looking for module label: alcaPCCProducerZeroBias
Looking for productInstanceName: alcaPCCZeroBias

----- End Fatal Exception -------------------------------------------------

As this backport is one of the main reasons for a CMSSW_10_0_5, its fix is important if a test of this wf in production should be done before the deployment of 10_1_X.

**Comment by fabiocos** [comment]
assign alca

**Comment by fabiocos** [comment]
@cerminar @franzoni @klute FYI

A first comparison of the differences between the backport and the master version did not show any obvious difference, apart for the way the sequence is defined (but the needed modules should be at the end all included anyway)

diff --git a/Calibration/LumiAlCaRecoProducers/python/ALCARECORawPCCProducer_cff.py b/Calibration/LumiAlCaRecoProducers/python/ALCARECORawPCCProducer_cff.py
index d46bd62ada7..82af696afdb 100644
--- a/Calibration/LumiAlCaRecoProducers/python/ALCARECORawPCCProducer_cff.py
+++ b/Calibration/LumiAlCaRecoProducers/python/ALCARECORawPCCProducer_cff.py
@@ -1,7 +1,7 @@
 import FWCore.ParameterSet.Config as cms
 
-from Calibration.LumiAlCaRecoProducers.ALCARECOAlCaPCCZeroBias_cff import ALCARECOZeroBiasHLT,siPixelDigisForLumiZB,siPixelClustersForLumiZB,alcaPCCProducerZeroBias
 
+from Calibration.LumiAlCaRecoProducers.ALCARECOAlCaPCCZeroBias_cff import seqALCARECOAlCaPCCZeroBias
 
 #Make sure that variables match in producer.cc and .h
 ALCARECORawPCCProd = cms.EDProducer("RawPCCProducer",
@@ -21,4 +21,4 @@ ALCARECORawPCCProd.RawPCCProducerParameters.modVeto.extend([302055684,302055688,
 
 
 
-seqALCARECORawPCCProducer = cms.Sequence(ALCARECOZeroBiasHLT + siPixelDigisForLumiZB + siPixelClustersForLumiZB + alcaPCCProducerZeroBias + ALCARECORawPCCProd)
+seqALCARECORawPCCProducer = cms.Sequence(seqALCARECOAlCaPCCZeroBias + ALCARECORawPCCProd)

**Comment by fabiocos** [comment]
The problem appears to be linked to the multithreading functionality of the framework as present in 10_0_X wrt 10_1_X. In single threaded mode it completes finding the product also in 10_0_X.

**Comment by Dr15Jones** [comment]
Can you run the job with the Tracer service on?

**Comment by Dr15Jones** [comment]
Try changing
https://github.com/cms-sw/cmssw/blob/3bf90a20a5536ddf2971dc6a330aa4c0c5aebfc4/Calibration/LumiAlCaRecoProducers/plugins/RawPCCProducer.cc#L89

Replacing edm::InLumi with edm::Transition::EndLuminosityBlock

**Comment by fabiocos** [comment]
@Dr15Jones I did already yesterday, and all the modules looked to run in the flow (verified also with some printout), here is the part before the exception

++++++++ finished: processing event for module: stream = 3 label = 'ALCARECOoutput_step' id = 5
++++++ finished: processing path 'ALCARECOoutput_step' : stream = 3
++++++++ finished: processing event for module: stream = 0 label = 'ALCARECOoutput_step' id = 5
++++++ finished: processing path 'ALCARECOoutput_step' : stream = 0
++++ finished: processing event : stream = 0 run = 283383 lumi = 1 event = 377860 time = 6342426558745204992
++++ starting: end lumi: stream = 0 run = 283383 lumi = 1 time = 6342426580220830208
++++ starting: end lumi: stream = 2 run = 283383 lumi = 1 time = 6342426580220830208
++++ starting: end lumi: stream = 3 run = 283383 lumi = 1 time = 6342426580220830208
++++ starting: end lumi: stream = 1 run = 283383 lumi = 1 time = 6342426580220830208
++++++ starting: end lumi for module: stream = 2 label = 'siPixelClustersForLumiZB' id = 8
++++++ starting: end lumi for module: stream = 1 label = 'siPixelClustersForLumiZB' id = 8
++++++ starting: end lumi for module: stream = 3 label = 'siPixelClustersForLumiZB' id = 8
++++++ finished: end lumi for module: stream = 2 label = 'siPixelClustersForLumiZB' id = 8
++++++ finished: end lumi for module: stream = 3 label = 'siPixelClustersForLumiZB' id = 8
++++++ finished: end lumi for module: stream = 1 label = 'siPixelClustersForLumiZB' id = 8
++++++ starting: end lumi for module: stream = 2 label = 'siPixelDigisForLumiZB' id = 7
++++++ starting: end lumi for module: stream = 3 label = 'siPixelDigisForLumiZB' id = 7
++++++ starting: end lumi for module: stream = 1 label = 'siPixelDigisForLumiZB' id = 7
++++++ finished: end lumi for module: stream = 2 label = 'siPixelDigisForLumiZB' id = 7
++++++ finished: end lumi for module: stream = 1 label = 'siPixelDigisForLumiZB' id = 7
++++++ finished: end lumi for module: stream = 3 label = 'siPixelDigisForLumiZB' id = 7
++++ finished: end lumi: stream = 2 run = 283383 lumi = 1 time = 6342426580220830208
++++ finished: end lumi: stream = 1 run = 283383 lumi = 1 time = 6342426580220830208
++++ finished: end lumi: stream = 3 run = 283383 lumi = 1 time = 6342426580220830208
++++++ starting: end lumi for module: stream = 0 label = 'siPixelDigisForLumiZB' id = 7
++++++ starting: end lumi for module: stream = 0 label = 'siPixelClustersForLumiZB' id = 8
++++++ finished: end lumi for module: stream = 0 label = 'siPixelClustersForLumiZB' id = 8
++++++ finished: end lumi for module: stream = 0 label = 'siPixelDigisForLumiZB' id = 7
++++ finished: end lumi: stream = 0 run = 283383 lumi = 1 time = 6342426580220830208
++++ starting: global end lumi: run = 283383 lumi = 1 time = 6342426558745067264
++++++ starting: global end lumi for module: label = 'MEtoEDMConverter' id = 12
++++++ starting: global end lumi for module: label = 'ALCARECOZeroBiasHLT' id = 6
++++++ finished: global end lumi for module: label = 'ALCARECOZeroBiasHLT' id = 6
++++++ starting: global end lumi for module: label = 'ALCARECORawPCCProd' id = 10
++++++ starting: global end lumi for module: label = 'alcaPCCProducerZeroBias' id = 9
++++++ finished: global end lumi for module: label = 'alcaPCCProducerZeroBias' id = 9
++++++ starting: global end lumi for module: label = 'ALCARECOoutput' id = 13
++++++ finished: global end lumi for module: label = 'ALCARECOoutput' id = 13
++++++ finished: global end lumi for module: label = 'MEtoEDMConverter' id = 12
++++++ finished: global end lumi for module: label = 'ALCARECORawPCCProd' id = 10
----- Begin Fatal Exception 26-Mar-2018 09:01:08 CEST-----------------------
An exception of category 'ProductNotFound' occurred while
   [0] Processing global end LuminosityBlock run: 283383 luminosityBlock: 1
   [1] Calling method for module RawPCCProducer/'ALCARECORawPCCProd'
Exception Message:
Principal::getByToken: Found zero products matching all criteria
Looking for type: reco::PixelClusterCounts
Looking for module label: alcaPCCProducerZeroBias
Looking for productInstanceName: alcaPCCZeroBias

----- End Fatal Exception -------------------------------------------------
++++ early termination of global lumi run = 283383 lumi = 1 : time = 6342426558745067264


I'll try your suggestion

**Comment by fabiocos** [comment]
@Dr15Jones your suggestion does not compile:

>> Compiling edm plugin /build/fabiocos/100X/test/fix/new/CMSSW_10_0_X_2018-03-25-2300/src/Calibration/LumiAlCaRecoProducers/plugins/RawPCCProducer.cc 
/build/fabiocos/100X/test/fix/new/CMSSW_10_0_X_2018-03-25-2300/src/Calibration/LumiAlCaRecoProducers/plugins/RawPCCProducer.cc: In constructor 'RawPCCProducer::RawPCCProducer(const edm::ParameterSet&)':
/build/fabiocos/100X/test/fix/new/CMSSW_10_0_X_2018-03-25-2300/src/Calibration/LumiAlCaRecoProducers/plugins/RawPCCProducer.cc:88:98: error: no matching function for call to 'RawPCCProducer::consumes(edm::InputTag&)'
     pccToken=consumes<reco::PixelClusterCounts, edm::Transition::EndLuminosityBlock>(PCCInputTag_);
                                                                                                  ^
In file included from /cvmfs/cms-ib.cern.ch/week1/slc6_amd64_gcc630/cms/cmssw-patch/CMSSW_10_0_X_2018-03-25-2300/src/FWCore/Framework/interface/ConsumesCollector.h:32:0,
                 from /build/fabiocos/100X/test/fix/new/CMSSW_10_0_X_2018-03-25-2300/src/Calibration/LumiAlCaRecoProducers/plugins/RawPCCProducer.cc:21:
/cvmfs/cms-ib.cern.ch/week1/slc6_amd64_gcc630/cms/cmssw-patch/CMSSW_10_0_X_2018-03-25-2300/src/FWCore/Framework/interface/EDConsumerBase.h:105:30: note: candidate: template<class ProductType, edm::BranchType B> edm::EDGetTokenT<T> edm::EDConsumerBase::consumes(const edm::InputTag&)
     EDGetTokenT<ProductType> consumes(edm::InputTag const& tag) {
                              ^~~~~~~~
/cvmfs/cms-ib.cern.ch/week1/slc6_amd64_gcc630/cms/cmssw-patch/CMSSW_10_0_X_2018-03-25-2300/src/FWCore/Framework/interface/EDConsumerBase.h:105:30: note:   template argument deduction/substitution failed:
/build/fabiocos/100X/test/fix/new/CMSSW_10_0_X_2018-03-25-2300/src/Calibration/LumiAlCaRecoProducers/plugins/RawPCCProducer.cc:88:98: error: could not convert template argument 'EndLuminosityBlock' to 'edm::BranchType'
     pccToken=consumes<reco::PixelClusterCounts, edm::Transition::EndLuminosityBlock>(PCCInputTag_);
                                                                                                  ^
In file included from /cvmfs/cms-ib.cern.ch/week1/slc6_amd64_gcc630/cms/cmssw-patch/CMSSW_10_0_X_2018-03-25-2300/src/FWCore/Framework/interface/ConsumesCollector.h:32:0,
                 from /build/fabiocos/100X/test/fix/new/CMSSW_10_0_X_2018-03-25-2300/src/Calibration/LumiAlCaRecoProducers/plugins/RawPCCProducer.cc:21:
/cvmfs/cms-ib.cern.ch/week1/slc6_amd64_gcc630/cms/cmssw-patch/CMSSW_10_0_X_2018-03-25-2300/src/FWCore/Framework/interface/EDConsumerBase.h:115:16: note: candidate: template<edm::BranchType B> edm::EDGetToken edm::EDConsumerBase::consumes(const edm::TypeToGet&, const edm::InputTag&)
     EDGetToken consumes(TypeToGet const& id, edm::InputTag const& tag) {
                ^~~~~~~~
/cvmfs/cms-ib.cern.ch/week1/slc6_amd64_gcc630/cms/cmssw-patch/CMSSW_10_0_X_2018-03-25-2300/src/FWCore/Framework/interface/EDConsumerBase.h:115:16: note:   template argument deduction/substitution failed:
/build/fabiocos/100X/test/fix/new/CMSSW_10_0_X_2018-03-25-2300/src/Calibration/LumiAlCaRecoProducers/plugins/RawPCCProducer.cc:88:98: error: wrong number of template arguments (2, should be 1)
     pccToken=consumes<reco::PixelClusterCounts, edm::Transition::EndLuminosityBlock>(PCCInputTag_);
                                                                                                  ^
config/SCRAM/GMake/Makefile.rules:2079: recipe for target 'tmp/slc6_amd64_gcc630/src/Calibration/LumiAlCaRecoProducers/plugins/RawPCCProducer/RawPCCProducer.o' failed

**Comment by fabiocos** [comment]
As a workaround I have prepared #22736 that forced the wf 1020 in 10_0_X to run single threaded, this is not the ultimate solution but allows some tests to be done in case (and prevents a wf to be systematically broken for the time being for a known reason).

**Comment by fabiocos** [comment]
The workaround has been updated with #22741 as the IB overwrites the naive protection added

**Comment by fabiocos** [comment]
This is now operational in CMSSW_10_0_5 (see https://github.com/cms-sw/cmssw/releases/tag/CMSSW_10_0_5 )

**Comment by cerminar** [comment]
@Dr15Jones is there any hint on the root cause of the problem?
Thanks.

**Comment by Dr15Jones** [comment]
> @Dr15Jones is there any hint on the root cause of the problem?

In CMSSW_10_0 (and before) there is a bug in how the code handles the case where a module asks for a Lumi product in begin Lumi (or during event processing) but the data product is not created until end Lumi. In those cases, one is supposed to get a 'product not found' until the endLumi. In CMSSW_10_0 this was done by setting the product as 'missing' and then resetting the Lumi at end Lumi to allow it to be found. Unfortunately, it looks like the 'reset' was incomplete such that if you asked for the data product without specifying the exact process name, the program would not wait for the module to be run but instead return immediately. [The technical problem is the `NoProcessProductResolver` needs to override `resetFailedFromThisProcess` and reset the `WaitingTaskList`]

In CMSSW_10_1 that whole code was changed to best accomodate concurrent Lumi processing (as well as allowing stream end Lumi to be running while other streams are still processing events).

**Comment by Dr15Jones** [comment]
#22778 fixes the problem in CMSSW_10_0_X (there is no need for a fix for 10_1).

**Comment by fabiocos** [comment]
@Dr15Jones thanks Chris, I merge the fix. We need to understand whether AlCA experts want to try the PCL with this fix or move to 10_1_X at this point.
