### ISSUE TITLE
Unable to use gdb on cmsRun w/ CMSSW_10_1_ROOT612_X builds

### ISSUE THREAD

**Issue by kpedro88** [cms-sw/cmssw#22742]
When I try to run `gdb` on `cmsRun` in the ROOT612 IBs:
```
cmsrel CMSSW_10_1_ROOT612_X_2018-03-25-2300
cd CMSSW_10_1_ROOT612_X_2018-03-25-2300/src
cmsenv
cmsDriver.py SingleElectronPt10_pythia8_cfi  --conditions auto:phase1_2018_realistic -n 10 --era Run2_2018 --eventcontent RAWSIM -s GEN --datatier GEN --beamspot Realistic25ns13TeVEarly2017Collision --geometry DB:Extended --no_exec --fileout file:step1.root
gdb cmsRun
run SingleElectronPt10_pythia8_cfi_GEN.py
```

I get the following error:
```
----- Begin Fatal Exception 26-Mar-2018 09:27:16 CDT-----------------------
An exception of category 'ConfigFileReadError' occurred while
   [0] Processing the python configuration file named SingleElectronPt10_pythia8_cfi_GEN.py
Exception Message:
python encountered the error: <type 'exceptions.ImportError'>
No module named FWCore.ParameterSet.Config
----- End Fatal Exception -------------------------------------------------
```

Obviously this error is not caused by my config, but seems like some python/gdb incompatibility. This problem doesn't occur in the normal 10_1_X builds. Does anyone know how to fix it?

**Comment by smuzaffar** [comment]
@kpedro88 , your commands works for me on cmsdev15.

**Comment by kpedro88** [comment]
I thought it was a problem with the ROOT612 IB because it works fine in 10_1_0_pre3, but I think it's rather the recent changes in `PYTHONPATH` etc. usage for externals (which show up in all recent IBs, but not pre3). This must cause some conflict with my environment.
