### ISSUE TITLE
GEM geometry needs to be fixed

### ISSUE THREAD

**Issue by fabiocos** [cms-sw/cmssw#22759]
The review of #22619 pointed out a problem with the 2018 GEM geometry. This has been fixed in the builder from DD #22730 but the corresponding payload in the DB should be fixed as well.

**Comment by fabiocos** [comment]
assign geometry,alca

**Comment by fabiocos** [comment]
@ianna @jshlee there should be a follow up of https://github.com/cms-sw/cmssw/pull/22619#issuecomment-375735180

**Comment by jshlee** [comment]
yes, it's in the works. Currently in discussion with alcadb.

**Comment by fabiocos** [comment]
@jshlee @ianna @lpernie @arunhep do I understand correctly that the GT part of 10_2_0_pre1/10_1_1 is NOT yet solving this issue? The updates to GEM geometry noted in #22834 are only for the upgrade as far as I can see...

**Comment by arunhep** [comment]
@fabiocos 
the fixed geometry in the PR #22834 entered into GTs for MC in 2018 and beyond.
Do we need to deploy it in earlier GTs as well?

**Comment by fabiocos** [comment]
@arunhep as we discussed, I was confised by the #22834 description as it was mentioning GEM for upgrade and not run2. But speaking with you I understand that it is effectively in also for 2018 so this issue can be closed.
