### ISSUE TITLE
Better handling of mergeable Run products for 'split' jobs

### ISSUE THREAD

**Issue by Dr15Jones** [cms-sw/cmssw#22846]
Lets say one has a ROOT file which contains a mergeable Run product which was formed by a job that saw LuminosityBlocks 1-10. Subsequently, we have two seperate jobs, each of which only process a fraction of the LuminosityBlocks in the original file. Say job 1 processes 1-5 while job two processes 6-10. If the files from these two jobs are then merged, the original mergeable Run product will be merged with its own two copies which is unlikely to give the correct result (e.g. for histograms this would cause double counting).

This situation could be improved by recording which LuminosityBlocks were used for a given process which created a mergeable Run product. Then in the previous example, the output file from each of the two intermediate jobs would record which LuminosityBlocks were NOT processed. So for job 1 it would record 6-10 and job 2 would record 1-5. Then during the merge job, if upon opening the second or subsequent file 
   * if the new file has another piece of the original mergeable Run product, it would NOT merge the product (since it is just a copy of what was already seen)
   * if the new file has the same Run but its mergeable Run products are originally from a different group of LuminosityBlocks then the framework would generate a new Run transition (even though it is technically part of the same Run). This will guarantee that once all pieces are re-assembled we will get the correct answer.

**Comment by Dr15Jones** [comment]
assign core

**Comment by Dr15Jones** [comment]
@wddgit did your work on mergeable Run products resolve this issue?

**Comment by wddgit** [comment]
@Dr15Jones Yes. I think it did resolve the issue and we can close it. See PR #23776. It was not fixed in exactly the same way as your original comments suggested and there were some limitations on how this works. I think the comments in the PR address discuss those things.

**Comment by wddgit** [comment]
Probably it is also useful to put a link to the new TWIKI section I wrote related to this:
https://twiki.cern.ch/twiki/bin/view/CMSPublic/SWGuidePerRunAndPerLumiBlockData#Merging_Run_and_Luminosity_Block

**Comment by Dr15Jones** [comment]
+1
