### ISSUE TITLE
HcalHitReconstructor Initialization

### ISSUE THREAD

**Issue by wddgit** [cms-sw/cmssw#22913]
In an igprof performance profile of test 25.0 step 3, HcalHitReconstructor shows up using roughly 0.25 seconds times the number of streams to initialize. Of the modules that scale as a function of stream, this is third highest in the profile (there are recent PRs already to improve the two higher cases).

Almost all the time is spent in the two similar lines that are calling the convolve function:

http://cmslxr.fnal.gov/source/CalibCalorimetry/HcalAlgos/src/HcalPulseShapes.cc#0386
http://cmslxr.fnal.gov/source/CalibCalorimetry/HcalAlgos/src/HcalPulseShapes.cc#0405

This time is all in evaluation of a math expression. There is a double loop that does a calculation every time including evaluation of log and exponential terms. Because of the number of iterations this expression is evaluated 10s of thousands of times. The output of the calculation is a vector with a few hundred elements.

The issue is that the output of the calculation is always the same for every stream, every module, and every process. This becomes more significant as we move to larger numbers of streams. I am currently working on how to improve this and have a few ideas (a GlobalCache, the EventSetup using a function to calculate it, put it in a database and use the EventSetup to read it, hard code the output vector values).

@slava77 @Dr15Jones  Any suggestions on how to proceed? How is this type of problem usually handled in RECO? I also have a choice to put as much of the related code as I can in this new cache or just deal with the minimal part of it that is taking almost all the time.

**Comment by slava77** [comment]
assign alca
[just because the code is in CalibCalorimetry subsystem]

@kpedro88 

@wddgit please share the results of the profiler run.
I have this somewhat old test as a reference
https://slava77sk.web.cern.ch/slava77sk/reco/cgi-bin/igprof-navigator/CMSSW_10_0_X_2017-12-17-2300-orig.step3.136.831.100.pp/3478
If I'm not mistaken, this indicates that there are 5 instances of HcalPulseShapes initialized per stream. It seems to me that HcalPulseShapes should be moved to the EventSetup.

**Comment by Dr15Jones** [comment]
If it is a static value, I would consider writing a simple program which would write out a '.cc' file containing code with the values hard-coded. I'd then check-in both the program and the .cc file.

**Comment by kpedro88** [comment]
This code is a mess, unfortunately. Turning it into an ESProduct makes sense conceptually, but would entail a lot of refactoring. I would prefer to avoid storing vectors of values because their provenance is inevitably lost over time. (That was the previous situation before I introduced the use of `convolve`; obviously I didn't think about the scaling with number of streams.)

We could try to solve the performance problem without rewriting all the code by doing something clever with magic statics...

attn: @abdoulline

**Comment by kpedro88** [comment]
Here is a magic static approach\*:
https://github.com/cms-sw/cmssw/compare/master...kpedro88:StaticPulseShapes

I ran igprof for WF 25.0 step3 (4 threads), here are the results. It seems quite effectively reduced to me.

Before:
```
            0.1  .........       0.13 / 0.26         SimpleHBHEPhase1Algo::SimpleHBHEPhase1Algo(int, int, float, float, bool, std::unique_ptr<PulseShapeFitOO
            0.1  .........       0.14 / 0.14         HBHEPulseShapeFlagSetter::Initialize() [3110]
            0.1  .........       0.26 / 0.50         HcalSimpleRecAlgo::HcalSimpleRecAlgo(bool, bool, float) [1517]
            0.2  .........       0.37 / 0.37         HcalPulseContainmentManager::HcalPulseContainmentManager(float) [1842]
[1117]      0.4       0.90       0.00 / 0.90       HcalPulseShapes::HcalPulseShapes()
            0.2  .........       0.45 / 0.45         HcalPulseShapes::computeSiPMShapeHE206() [1616]
            0.2  .........       0.44 / 0.44         HcalPulseShapes::computeSiPMShapeHE203() [1627]
            0.0  .........       0.01 / 0.01         HcalPulseShapes::computeHPDShape(float, float, float, float, float, float, float, float, HcalPulseShape&
```
After:
```
            0.0  .........       0.08 / 0.08         HcalPulseContainmentManager::HcalPulseContainmentManager(float) [3949]
[3954]      0.0       0.08       0.00 / 0.08       HcalPulseShapes::HcalPulseShapes()
            0.0  .........       0.04 / 0.04         HcalPulseShapes::computeSiPMShapeHE203() [6040]
            0.0  .........       0.04 / 0.04         HcalPulseShapes::computeSiPMShapeHE206() [6041]
```

\* initialization of a local static variable inside a function is guaranteed threadsafe by the C++11 standard

**Comment by Dr15Jones** [comment]
> * initialization of a local static variable inside a function is guaranteed threadsafe by the C++11 standard

but must be declared `const` so subsequent uses can not cause a change.

**Comment by kpedro88** [comment]
Right, thanks to @Dr15Jones for that reminder, it was the reason for the third commit in my branch.

**Comment by wddgit** [comment]
Kevin's approach seems reasonable to me. Much better than what we have now. @kpedro88 Can I assume you are going to submit the pull request for this and I can move on to the next item on my list?

@slava77 I put my latest igprof profile results here ~wdd/public/igprofResults. In test 10824.0, HcalHitReconstructor had one instance and 4 other modules of other types were using HcalPulseShapes. (In test 25.0, there were 2 instances of HcalHitReconstructor and 5 other modules of other types were using it.)

**Comment by kpedro88** [comment]
Yes, I'll submit a PR for this. Hopefully a more in-depth revision of this code can eventually be done by the HCAL software team.
