### ISSUE TITLE
Alternative to CLHEP System of Units Usage in CMSSW

### ISSUE THREAD

**Issue by ianna** [cms-sw/cmssw#22919]
Degrees[*] rather then radians[**] are used in Detector Description extensively for clarity. See:
https://cmssdt.cern.ch/lxr/ident?_i=deg
https://cmssdt.cern.ch/lxr/search?%21v=CMSSW_10_2_X_2018-04-09-2300&_filestring=xml&_string=deg

@Dr15Jones and @smuzaffar - what is an agreed proposed alternative? **_deg** user-defined literal (constexpr)?
```
// used as conversion
constexpr long double operator"" _deg ( long double deg )
{
    return deg*3.141592/180;
}
```

[*] a static constexpr **deg** from CLHEP:
https://gitlab.cern.ch/CLHEP/CLHEP/blob/master/Units/Units/SystemOfUnits.h

[**] the subject of phasing out CLHEP was brought up by @VinInn in https://github.com/cms-sw/cmssw/pull/22643#pullrequestreview-104793404

**Comment by fabiocos** [comment]
@VinInn @Dr15Jones @smuzaffar @ianna what is the proposed alternative to CLHEP, at least as far as table of constants is concerned?
A number of mathematical and physical constants are defined in ROOT::TMath, but what about the system of units? In principle it s just a set of numerical constants that can be encoded anywhere. Was a proposal discussed?

**Comment by VinInn** [comment]
I do not remember any "modern" (ie post C++17) discussion on the subject.
My main complain w/r/t the use of CLHEP style of system of units is that it implies multiplication (even divisions) at runtime and is limited to double.
As long as it is used to define other constexpr constants that's sort of ok. Unfortunately often we see it used even in tight loops where we clearly pay the whole penalty.

For what concern the use in xml, in my opinion it should be solved at parsing time and all variable used at runtime should be in CMS common standard units (or G4 ones if more appropriate)

user-defined literals are a possibility for literals: they should be properly defined in a sort of standard header following the std approach
see for instance
http://en.cppreference.com/w/cpp/numeric/complex/operator%22%22i

(and of course for pi one should use M_PI where the proper precision and rounding is guaranteed)

What puzzles me a bit is that besides this old post
https://www.codeproject.com/Articles/447922/Application-of-Cplusplus-User-Defined-Literals-t
one cannot find any other example of use of user-defined literals for scientific applications
(I would have expected boost to jump on it for instance)

**Comment by ianna** [comment]
Here is a proposed solution to replace CLHEP units in DD. Please, comment.

https://github.com/ianna/cmssw/blob/64be013f8c8c6d11109dc391e67ab66534d27c74/DetectorDescription/DDCMS/interface/DDUnits.h
https://github.com/ianna/cmssw/blob/64be013f8c8c6d11109dc391e67ab66534d27c74/DetectorDescription/DDCMS/test/DDUnits.cppunit.cc

**Comment by ianna** [comment]
+1
