### ISSUE TITLE
Fix CSC, RPC, and DT digi validation configurations for premixing

### ISSUE THREAD

**Issue by makortel** [cms-sw/cmssw#22957]
This issue tracks work to fix the inconsistency in CSC, RPC, and DT digi validation configuration files for premixing reported first here
https://hypernews.cern.ch/HyperNews/CMS/get/muon-performance/982.html

It turns out that the necessary signal+pileup SimDigi collections are not part of the FEVTDEBUGHLT event content. If we want to keep premixing stage2 workflows running, we have to

- [ ] 1. Add the necessary collections to FEVTDEBUGHLT event content
- [ ] 2. Wait for next RelVals to have a new pileup library with the fixed event content
- [ ] 3. Fix the validation configurations to use the proper input
- [ ] 4. Drop the signal-only SimDigi collections from FEVTDEBUGHLT event content

**Comment by kpedro88** [comment]
From my perspective, it's fine not to wait for a new relval premixing library.

We could modify the validation code just to skip some actions if the input handles aren't valid (instead of issuing a not found exception) to avoid failing workflows.

**Comment by makortel** [comment]
> We could modify the validation code just to skip some actions if the input handles aren't valid (instead of issuing a not found exception) to avoid failing workflows.

Good idea, that would work as a temporary workaround (even if in general I dislike such pattern if input is expected to always exist).

**Comment by fabiocos** [comment]
@makortel @kpedro88 I would prefer to avoid having for two weeks tests that are "known" to fail. We need to recall to revert the change as soon as the code transition is completed though.

**Comment by makortel** [comment]
Thanks @fabiocos. I'll then implement @kpedro88's suggestion https://github.com/cms-sw/cmssw/issues/22957#issuecomment-381182755 and update the plan in the description of this issue.

**Comment by makortel** [comment]
Nevermind, while preparing #22977 I realized that the event content to be updated is the output of DIGI step of stage2 workflow, which is always re-done in the matrix workflows. So everything I outlined in the description can be done consistently in one PR without breaking anything or adding temporary workarounds.

Sorry for the noise.
