### ISSUE TITLE
Validation of re-miniAOD and muon DQM

### ISSUE THREAD

**Issue by fabiocos** [cms-sw/cmssw#22981]
Following the comment https://github.com/cms-sw/cmssw/pull/22456#issuecomment-381269448 by @slava77 
The change in DQM in #22456 breaks the validation of muons for re-miniAOD, for instance wf 136.7611 . This was not noticed because it is a case that requires some statistics, and this wf is not part of the regular RelVal procedure.

An update is under discussion to allow the test of the reminiAOD of 2016, @parbol @drkovalskyi

**Comment by fabiocos** [comment]
@slava77 @jfernan2 I imagine that this issue is obsolete and may be removed. Do you confirm?

**Comment by slava77** [comment]
I think that this was fixed in #23015

**Comment by fabiocos** [comment]
@slava77 you are correct, thank you
