### ISSUE TITLE
RecHits for Totem Timing

### ISSUE THREAD

**Issue by nminafra** [cms-sw/cmssw#23023]
Hello,
I'm writing the rec hit producer for the Totem Timing. 
The existing class is CTPPSDiamondRecHit
https://github.com/cms-sw/cmssw/blob/master/DataFormats/CTPPSReco/interface/CTPPSDiamondRecHit.h

I can use a very similar class for the totem timing; however I can:
- keep the name CTPPSDiamondRecHit for both CTPPS and Totem Timing (it may introduce confusion)
- inherit CTPPSDiamondRecHit from a mother class CTPPSTimingRecHit (it will change the class version of CTPPSDiamondRecHit and add a new class for the Totem timing)

I'd go with the second solution, but I don't know the overhead in the review when changing existing classes.
@fabiocos @perrotta @slava77  what is your recommendation?

Thanks!

@forthommel

**Comment by slava77** [comment]
@nminafra 
what kind of changes do you expect compared to CTPPSDiamondRecHit?
If the interface can be identical, perhaps it's easier to just add a typedef CTPPSDiamondRecHit TotemTimingRecHit.

**Comment by nminafra** [comment]
Thanks @slava77, we considered it; however it requires anyway to change the class footprint without the added flexibility of having two classes, for instance if we want to extend the class in the future.
In our plan, CTPPSTimingRecHit would contain only position, time and errors, while inherited classes can have other info:
- HPTDC errors, OOTIndex for CTPPSDiamondRecHit
- Ampltude for TotemTimingRecHit

**Comment by forthommel** [comment]
Just going through these old issues. Might be a good candidate for closing after a couple years of production :)

**Comment by nminafra** [comment]
@forthommel Yes Sir!
