### ISSUE TITLE
Move GBRForest to a more central place

### ISSUE THREAD

**Issue by perrotta** [cms-sw/cmssw#23030]
Just to take note of the discussion started by @VinInn in https://github.com/cms-sw/cmssw/pull/22963#issuecomment-381311496, and the subsequent comments in the same thread, and follow up on it.

Now GBRForest stays in  "CondFormats/EgammaObjects/interface/GBRForest.h". However, that tool is not reserved for EGammObjects: therefore a more conveninent address should be found for it.

alca/db software coordinators can suggest on where to move it.

**Comment by perrotta** [comment]
assign alca, db

**Comment by christopheralanwest** [comment]
+alca

This was resolved by PR #32392.
