### ISSUE TITLE
Request to add @shervin86 as member of cms-analysis organisation

### ISSUE THREAD

**Issue by sethzenz** [cms-sw/cmssw#23060]
Can someone please add @shervin86 as a member of the cms-analysis organisation?  This is needed so he can be given administrative functions for the flashgg repository (Higgs to diphoton group analysis framework).

Tagging the owners: @smuzaffar @fcouderc @slava77 @vadler 

I am raising this as an issue here because that was the conclusion for the best way to make these requests when we last discussed it by email.

**Comment by smuzaffar** [comment]
@sethzenz , I have sent the invitation to @shervin86 to join the  https://github.com/orgs/cms-analysis/teams/higgsanalysis-flashgg-admin/members  team
