### ISSUE TITLE
numpy not found in slc6_amd64_gcc630 / CMSSW_9_3_0 

### ISSUE THREAD

**Issue by khurtado** [cms-sw/cmssw#23100]
If I setup `CMSSW_9_3_0` on `slc6_amd64_gcc630`, numpy can't be found:

```
export SCRAM_ARCH=slc6_amd64_gcc630
cmsrel CMSSW_9_3_0
cd CMSSW_9_3_0
cmsenv
$ python -c 'import numpy; print numpy.__file__'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named numpy
```
Looking into `PYTHONPATH`, the numpy version appended to it by default is:
```
/cvmfs/cms.cern.ch/slc6_amd64_gcc630/external/py2-numpy/1.12.1-mlhled2/lib/python2.7/site-packages
```

This directory doesn't have the `numpy` module directory in it as-is though, as opposed to other versions like 1.14, which is why `import numpy` doesn't work. It has `numpy-1.12.1-py2.7-linux-x86_64.egg` instead
```
$ ls /cvmfs/cms.cern.ch/slc6_amd64_gcc630/external/py2-numpy/1.12.1-mlhled2/lib/python2.7/site-packages
easy-install.pth  numpy-1.12.1-py2.7-linux-x86_64.egg  site.py  site.pyc
$ ls /cvmfs/cms.cern.ch/slc6_amd64_gcc630/external/py2-numpy/1.14.1-omkpbe2/lib/python2.7/site-packages/
numpy  numpy-1.14.1-py2.7.egg-info
```
Can this be fixed?

**Comment by davidlange6** [comment]
Do cmsenv to get the cms python not the slc6 one.

Cheers,
David


On 30 Apr 2018, at 23:15, cmsbuild <notifications@github.com<mailto:notifications@github.com>> wrote:


A new Issue was created by @khurtado<https://github.com/khurtado> Kenyi Hurtado.

@davidlange6<https://github.com/davidlange6>, @Dr15Jones<https://github.com/Dr15Jones>, @smuzaffar<https://github.com/smuzaffar>, @fabiocos<https://github.com/fabiocos> can you please review it and eventually sign/assign? Thanks.

cms-bot commands are listed here<http://cms-sw.github.io/cms-bot-cmssw-issues.html>

**Comment by khurtado** [comment]
@davidlange6 I'm doing cmsenv in my local release of course. You can check below my `CMSSW_BASE` and python is properly set to the proper cvmfs path, but numpy is not in the CMS/cvmfs environment (well, it is in PYTHONPATH, just not working for the reason in above)

```
$ echo $CMSSW_BASE
/home/khurtado/qqq/CMSSW_9_3_0
[khurtado@login CMSSW_9_3_0]$ which python
/cvmfs/cms.cern.ch/slc6_amd64_gcc630/cms/cmssw/CMSSW_9_3_0/external/slc6_amd64_gcc630/bin/python
[khurtado@login CMSSW_9_3_0]$ python -c 'import numpy; print numpy.__file__'
/usr/lib64/python2.6/site-packages/numpy/__init__.py
```

**Comment by davidlange6** [comment]
Could you send an actual recipe starting from a new long shell then? (930 is pretty much obsolete regardless)

Cheers,
David


On 30 Apr 2018, at 23:35, Kenyi Hurtado <notifications@github.com<mailto:notifications@github.com>> wrote:


@davidlange6<https://github.com/davidlange6> I'm doing cmsenv in my local release of course. You can check below my CMSSW_BASE and python is properly set to the proper cvmfs path, but numpy is not in the CMS/cvmfs environment (well, it is in PYTHONPATH, just not working for the reason in above)

$ echo $CMSSW_BASE
/home/khurtado/qqq/CMSSW_9_3_0
[khurtado@login CMSSW_9_3_0]$ which python
/cvmfs/cms.cern.ch/slc6_amd64_gcc630/cms/cmssw/CMSSW_9_3_0/external/slc6_amd64_gcc630/bin/python<http://cms.cern.ch/slc6_amd64_gcc630/cms/cmssw/CMSSW_9_3_0/external/slc6_amd64_gcc630/bin/python>
[khurtado@login CMSSW_9_3_0]$ python -c 'import numpy; print numpy.__file__'
/usr/lib64/python2.6/site-packages/numpy/__init__.py

**Comment by khurtado** [comment]
@davidlange6 
So, executing the script below in CMS Connect gave me the following output:

```
$ ./testnumpy.sh
/cvmfs/cms.cern.ch/slc6_amd64_gcc630/cms/cmssw/CMSSW_9_3_0/external/slc6_amd64_gcc630/bin/python
/usr/lib64/python2.6/site-packages/numpy/__init__.py
```

testnumpy.sh script:
```
#! /bin/bash
# testnumpy.sh

mkdir test; cd test
export SCRAM_ARCH=slc6_amd64_gcc630
cmsrel CMSSW_9_3_0
cd CMSSW_9_3_0
cmsenv
which python
python -c 'import numpy; print numpy.__file__'
```

**Comment by khurtado** [comment]
Ah, actually, executing it on `lxplus` works somehow. If I uninstall `numpy` from CMS Connect then it also works, which I find weird, because the he numpy version provided by the system is at the very end of the PYTHONPATH environment. I don't think I need to provide `numpy` outside cms though, so I will leave it like that and close this issue.
