### ISSUE TITLE
reduce duplicated code in PFJetIDSelectionFunctor

### ISSUE THREAD

**Issue by slava77** [cms-sw/cmssw#23131]
it looks like ```PFJetIDSelectionFunctor( edm::ParameterSet const & params )``` and ```PFJetIDSelectionFunctor( Version_t version, Quality_t quality )``` have about 200 lines of the same implementation which has to be maintained in a duplicate. This should be refactored.

@ahinzmann @rappoccio @zdemirag

**Comment by slava77** [comment]
assign reconstruction,analysis

**Comment by ahinzmann** [comment]
this can be closed since #23120 is merged

**Comment by slava77** [comment]
+1

this was resolved since a while
