### ISSUE TITLE
add a Run2018A workflow to the matrix

### ISSUE THREAD

**Issue by slava77** [cms-sw/cmssw#23130]
We have collected some data already and 2018 is different from 2017 to require occasional testing.
Please add a workflow (set) for 2018A.

**Comment by boudoul** [comment]
May I suggest a cosmic 2018 data WF too ?
Perhaps older cosmic data wf could be dropped.
Thank you.

**Comment by fabozzi** [comment]
A deployment of a new workflow should involve also Alca team for the availability of GT in autoCond.
Also, we would like to be adviced on a sensible run to be used in input

**Comment by slava77** [comment]
assign alca
to get a relevant GT

@sasharma6 (I'm not sure about the github token) please suggest what's good for a run number with collisions in 2018A.

**Comment by fabiocos** [comment]
@fabozzi @prebello I think it would be useful to have some Tier0 like workflows (as 1000, 1001) to have a fresh test of production workflows (for what is possible) before moving to Tier0 replays

**Comment by fabozzi** [comment]
@fabiocos: we do not really know anything about these T0 workflows and sequences. I add @mmusich in CC  just because in the history he is the last one to have made some commits on those

**Comment by vazzolini** [comment]
hello, at the moment we've only 2 runs good in 2018 data. 315489 ( in LS [1, 653], [672, 709]) and 315490 with very little LS [1, 24]. More are expected to arrive on wednesday. ciao Virginia(DC)

**Comment by slava77** [comment]
315489  early in the run has PU~35. This is pretty good.

**Comment by fabozzi** [comment]
Thank you for your feedbacks. Run 315489 was taken on May 1, so GT in autocond (102X_dataRun2_PromptLike_v1) should be OK, according to discussion with Alca team. I have started PR #23196 to deploy these relvals.

**Comment by fabozzi** [comment]
@arunhep @lpernie 
It seems there is a crash at the ALCARECO of step3 of the 2018 workflow here:
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-23196/27924/runTheMatrix-results/136.85_RunEGamma2018A+RunEGamma2018A+HLTDR2_2018+RECODR2_2018reHLT_skimEGamma_Prompt_L1TEgDQM+HARVEST2018_L1TEgDQM/

Can you give us some feedback on this?

**Comment by fabiocos** [comment]
#23196 has been merged, the test matrix in the bot should be updated. But at least for this part the issue has been addressed.

**Comment by christopheralanwest** [comment]
+1

**Comment by smuzaffar** [comment]
Run2018A workflows were added by #23196 , so closing this issue.
