### ISSUE TITLE
Unit test failure for FWCore/MessageService

### ISSUE THREAD

**Issue by fabiocos** [cms-sw/cmssw#23187]
Two unit tests from the FWCore/messageService package are failing since CMSSW_10_2_X_2018-05-10-1100, despite no explicit change in that code.  The failure happens after the update of jmalloc in cms-sw/cmsdist#3986 and the error messages reported (see https://cmssdt.cern.ch/SDT/cgi-bin/buildlogs/slc7_amd64_gcc630/CMSSW_10_2_X_2018-05-10-2300/unitTestLogs/FWCore/MessageService ) look related to this update:

===== Test "unitTestsGroup_1" ====
argument 0: unitTestsGroup_1
argument 1: /bin/bash
argument 2: FWCore/MessageService/test
argument 3: u1.sh
argument 4: u1t.sh
argument 5: u2.sh
argument 6: u2t.sh
argument 7: u6.sh
argument 8: u6t.sh
argument 9: u21.sh
shell is: /bin/bash
Current directory is: /build/cmsbld/jenkins/workspace/ib-run-qa/CMSSW_10_2_X_2018-05-10-2300
topdir is: /build/cmsbld/jenkins/workspace/ib-run-qa/CMSSW_10_2_X_2018-05-10-2300
testdir is: /build/cmsbld/jenkins/workspace/ib-run-qa/CMSSW_10_2_X_2018-05-10-2300/src/FWCore/MessageService/test
tmpdir is: /build/cmsbld/jenkins/workspace/ib-run-qa/CMSSW_10_2_X_2018-05-10-2300/tmp/slc7_amd64_gcc630
testbin is: /build/cmsbld/jenkins/workspace/ib-run-qa/CMSSW_10_2_X_2018-05-10-2300/test/slc7_amd64_gcc630
Running script: /build/cmsbld/jenkins/workspace/ib-run-qa/CMSSW_10_2_X_2018-05-10-2300/src/FWCore/MessageService/test/u1.sh
/build/cmsbld/jenkins/workspace/ib-run-qa/CMSSW_10_2_X_2018-05-10-2300/tmp/slc7_amd64_gcc630 /build/cmsbld/jenkins/workspace/ib-run-qa/CMSSW_10_2_X_2018-05-10-2300
<jemalloc>: Invalid conf pair: lg_chunk:18
<jemalloc>: Invalid conf pair: lg_dirty_mult:4
/build/cmsbld/jenkins/workspace/ib-run-qa/CMSSW_10_2_X_2018-05-10-2300
Running script: /build/cmsbld/jenkins/workspace/ib-run-qa/CMSSW_10_2_X_2018-05-10-2300/src/FWCore/MessageService/test/u1t.sh
/build/cmsbld/jenkins/workspace/ib-run-qa/CMSSW_10_2_X_2018-05-10-2300/tmp/slc7_amd64_gcc630 /build/cmsbld/jenkins/workspace/ib-run-qa/CMSSW_10_2_X_2018-05-10-2300
<jemalloc>: Invalid conf pair: lg_chunk:18
<jemalloc>: Invalid conf pair: lg_dirty_mult:4
/build/cmsbld/jenkins/workspace/ib-run-qa/CMSSW_10_2_X_2018-05-10-2300
Running script: /build/cmsbld/jenkins/workspace/ib-run-qa/CMSSW_10_2_X_2018-05-10-2300/src/FWCore/MessageService/test/u2.sh
/build/cmsbld/jenkins/workspace/ib-run-qa/CMSSW_10_2_X_2018-05-10-2300/tmp/slc7_amd64_gcc630 /build/cmsbld/jenkins/workspace/ib-run-qa/CMSSW_10_2_X_2018-05-10-2300
0a1,2
> <jemalloc>: Invalid conf pair: lg_chunk:18
> <jemalloc>: Invalid conf pair: lg_dirty_mult:4
The above discrepancies concern u2_cerr.mout
/build/cmsbld/jenkins/workspace/ib-run-qa/CMSSW_10_2_X_2018-05-10-2300
status = 256

---> test unitTestsGroup_1 had ERRORS

===== Test "unitTestsGroup_4" ====
argument 0: unitTestsGroup_4
argument 1: /bin/bash
argument 2: FWCore/MessageService/test
argument 3: u18.sh
argument 4: u19.sh
argument 5: u20.sh
argument 6: u20t.sh
shell is: /bin/bash
Current directory is: /build/cmsbld/jenkins/workspace/ib-run-qa/CMSSW_10_2_X_2018-05-10-2300
topdir is: /build/cmsbld/jenkins/workspace/ib-run-qa/CMSSW_10_2_X_2018-05-10-2300
testdir is: /build/cmsbld/jenkins/workspace/ib-run-qa/CMSSW_10_2_X_2018-05-10-2300/src/FWCore/MessageService/test
tmpdir is: /build/cmsbld/jenkins/workspace/ib-run-qa/CMSSW_10_2_X_2018-05-10-2300/tmp/slc7_amd64_gcc630
testbin is: /build/cmsbld/jenkins/workspace/ib-run-qa/CMSSW_10_2_X_2018-05-10-2300/test/slc7_amd64_gcc630
Running script: /build/cmsbld/jenkins/workspace/ib-run-qa/CMSSW_10_2_X_2018-05-10-2300/src/FWCore/MessageService/test/u18.sh
/build/cmsbld/jenkins/workspace/ib-run-qa/CMSSW_10_2_X_2018-05-10-2300/tmp/slc7_amd64_gcc630 /build/cmsbld/jenkins/workspace/ib-run-qa/CMSSW_10_2_X_2018-05-10-2300
<jemalloc>: Invalid conf pair: lg_chunk:18
<jemalloc>: Invalid conf pair: lg_dirty_mult:4
/build/cmsbld/jenkins/workspace/ib-run-qa/CMSSW_10_2_X_2018-05-10-2300
Running script: /build/cmsbld/jenkins/workspace/ib-run-qa/CMSSW_10_2_X_2018-05-10-2300/src/FWCore/MessageService/test/u19.sh
/build/cmsbld/jenkins/workspace/ib-run-qa/CMSSW_10_2_X_2018-05-10-2300/tmp/slc7_amd64_gcc630 /build/cmsbld/jenkins/workspace/ib-run-qa/CMSSW_10_2_X_2018-05-10-2300
<jemalloc>: Invalid conf pair: lg_chunk:18
<jemalloc>: Invalid conf pair: lg_dirty_mult:4
/build/cmsbld/jenkins/workspace/ib-run-qa/CMSSW_10_2_X_2018-05-10-2300
Running script: /build/cmsbld/jenkins/workspace/ib-run-qa/CMSSW_10_2_X_2018-05-10-2300/src/FWCore/MessageService/test/u20.sh
/build/cmsbld/jenkins/workspace/ib-run-qa/CMSSW_10_2_X_2018-05-10-2300/tmp/slc7_amd64_gcc630 /build/cmsbld/jenkins/workspace/ib-run-qa/CMSSW_10_2_X_2018-05-10-2300
0a1,2
> <jemalloc>: Invalid conf pair: lg_chunk:18
> <jemalloc>: Invalid conf pair: lg_dirty_mult:4
The above discrepancies concern u20_cerr.log
/build/cmsbld/jenkins/workspace/ib-run-qa/CMSSW_10_2_X_2018-05-10-2300
status = 256

---> test unitTestsGroup_4 had ERRORS

**Comment by Dr15Jones** [comment]
The unit test in question does a diff on the cout from a cmsRun job. The difference is the inclusion of 
```
<jemalloc>: Invalid conf pair: lg_chunk:18
<jemalloc>: Invalid conf pair: lg_dirty_mult:4
```
A quick google search on that term shows `Invalid conf pair` happens when jemalloc is passed, via the environment variable `MALLOC_CONF` configuration options it does not understand. That environment variable is set by CMS via

https://github.com/cms-sw/cmsdist/blob/IB/CMSSW_10_2_X/gcc630/jemalloc-toolfile.spec#L27

So it appears that the new version of jemalloc does not understand those options.

**Comment by Dr15Jones** [comment]
A litte more searching confirms that the option was removed in jemalloc 5

https://github.com/jemalloc/jemalloc/issues/1115

**Comment by fabiocos** [comment]
@Dr15Jones thanks, from the discussion in the jemalloc issue I see that other ways of treating VM are suggested, but our spec file as it is should in any case be changed...

**Comment by Dr15Jones** [comment]
assign core

**Comment by Dr15Jones** [comment]
+1

**Comment by fabiocos** [comment]
@Dr15Jones thanks, the problem was closed with the external update
