### ISSUE TITLE
Incompatibility between python 2.7 and C++17

### ISSUE THREAD

**Issue by fabiocos** [cms-sw/cmssw#23205]
During the test of #23194 a clang compilation failure has appeard, as seen in

https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-23194/27923/buildClang.log

>> Compiling edm plugin /build/cmsbld/jenkins/workspace/ib-any-integration/CMSSW_10_2_X_2018-05-12-1100/src/FWCore/Integration/test/HistProducer.cc 
In file included from /build/cmsbld/jenkins/workspace/ib-any-integration/CMSSW_10_2_X_2018-05-12-1100/src/FWCore/Framework/src/EventProcessor.cc:46:
In file included from /cvmfs/cms-ib.cern.ch/nweek-02523/slc6_amd64_gcc630/cms/cmssw-patch/CMSSW_10_2_X_2018-05-12-1100/src/FWCore/PythonParameterSet/interface/PythonProcessDesc.h:4:
In file included from /cvmfs/cms-ib.cern.ch/nweek-02523/slc6_amd64_gcc630/cms/cmssw-patch/CMSSW_10_2_X_2018-05-12-1100/src/FWCore/PythonParameterSet/interface/BoostPython.h:5:
In file included from /cvmfs/cms-ib.cern.ch/nweek-02523/slc6_amd64_gcc630/external/boost/1.63.0-omkpbe2/include/boost/python.hpp:11:
In file included from /cvmfs/cms-ib.cern.ch/nweek-02523/slc6_amd64_gcc630/external/boost/1.63.0-omkpbe2/include/boost/python/args.hpp:8:
In file included from /cvmfs/cms-ib.cern.ch/nweek-02523/slc6_amd64_gcc630/external/boost/1.63.0-omkpbe2/include/boost/python/detail/prefix.hpp:13:
In file included from /cvmfs/cms-ib.cern.ch/nweek-02523/slc6_amd64_gcc630/external/boost/1.63.0-omkpbe2/include/boost/python/detail/wrap_python.hpp:151:
In file included from /cvmfs/cms-ib.cern.ch/nweek-02523/slc6_amd64_gcc630/external/python/2.7.11-omkpbe2/include/python2.7/Python.h:85:
/cvmfs/cms-ib.cern.ch/nweek-02523/slc6_amd64_gcc630/external/python/2.7.11-omkpbe2/include/python2.7/unicodeobject.h:534:5: error: ISO C++17 does not allow 'register' storage class specifier [-Wregister]
    register PyObject *obj,     /* Object */
    ^~~~~~~~~
/cvmfs/cms-ib.cern.ch/nweek-02523/slc6_amd64_gcc630/external/python/2.7.11-omkpbe2/include/python2.7/unicodeobject.h:553:5: error: ISO C++17 does not allow 'register' storage class specifier [-Wregister]
    register PyObject *obj      /* Object */
    ^~~~~~~~~
/cvmfs/cms-ib.cern.ch/nweek-02523/slc6_amd64_gcc630/external/python/2.7.11-omkpbe2/include/python2.7/unicodeobject.h:575:5: error: ISO C++17 does not allow 'register' storage class specifier [-Wregister]
    register const wchar_t *w,  /* wchar_t buffer */
    ^~~~~~~~~
/cvmfs/cms-ib.cern.ch/nweek-02523/slc6_amd64_gcc630/external/python/2.7.11-omkpbe2/include/python2.7/unicodeobject.h:593:5: error: ISO C++17 does not allow 'register' storage class specifier [-Wregister]
    register wchar_t *w,        /* wchar_t buffer */
    ^~~~~~~~~
>> Compiling edm plugin /build/cmsbld/jenkins/workspace/ib-any-integration/CMSSW_10_2_X_2018-05-12-1100/src/FWCore/Integration/test/ThingExtSource.cc 
In file included from /build/cmsbld/jenkins/workspace/ib-any-integration/CMSSW_10_2_X_2018-05-12-1100/src/FWCore/Framework/src/EventProcessor.cc:46:
In file included from /cvmfs/cms-ib.cern.ch/nweek-02523/slc6_amd64_gcc630/cms/cmssw-patch/CMSSW_10_2_X_2018-05-12-1100/src/FWCore/PythonParameterSet/interface/PythonProcessDesc.h:4:
In file included from /cvmfs/cms-ib.cern.ch/nweek-02523/slc6_amd64_gcc630/cms/cmssw-patch/CMSSW_10_2_X_2018-05-12-1100/src/FWCore/PythonParameterSet/interface/BoostPython.h:5:
In file included from /cvmfs/cms-ib.cern.ch/nweek-02523/slc6_amd64_gcc630/external/boost/1.63.0-omkpbe2/include/boost/python.hpp:11:
In file included from /cvmfs/cms-ib.cern.ch/nweek-02523/slc6_amd64_gcc630/external/boost/1.63.0-omkpbe2/include/boost/python/args.hpp:8:
In file included from /cvmfs/cms-ib.cern.ch/nweek-02523/slc6_amd64_gcc630/external/boost/1.63.0-omkpbe2/include/boost/python/detail/prefix.hpp:13:
In file included from /cvmfs/cms-ib.cern.ch/nweek-02523/slc6_amd64_gcc630/external/boost/1.63.0-omkpbe2/include/boost/python/detail/wrap_python.hpp:151:
In file included from /cvmfs/cms-ib.cern.ch/nweek-02523/slc6_amd64_gcc630/external/python/2.7.11-omkpbe2/include/python2.7/Python.h:94:
/cvmfs/cms-ib.cern.ch/nweek-02523/slc6_amd64_gcc630/external/python/2.7.11-omkpbe2/include/python2.7/stringobject.h:173:5: error: ISO C++17 does not allow 'register' storage class specifier [-Wregister]
    register PyObject *obj,     /* string or Unicode object */
    ^~~~~~~~~
/cvmfs/cms-ib.cern.ch/nweek-02523/slc6_amd64_gcc630/external/python/2.7.11-omkpbe2/include/python2.7/stringobject.h:174:5: error: ISO C++17 does not allow 'register' storage class specifier [-Wregister]
    register char **s,          /* pointer to buffer variable */
    ^~~~~~~~~
/cvmfs/cms-ib.cern.ch/nweek-02523/slc6_amd64_gcc630/external/python/2.7.11-omkpbe2/include/python2.7/stringobject.h:175:5: error: ISO C++17 does not allow 'register' storage class specifier [-Wregister]
    register Py_ssize_t *len    /* pointer to length variable or NULL
    ^~~~~~~~~

The problem appears unrelated to the changes in the PR , but it has been put into evidence by the tests of the package involved.

**Comment by smuzaffar** [comment]
this has been addressed by patching python 2.7 to avoid register keyword

https://github.com/cms-externals/cpython/commit/583c0f2237aade97173702ac602b16f51eadde6d
