### ISSUE TITLE
HLTObjectsMonitor for "objects have different ID"

### ISSUE THREAD

**Issue by fabiocos** [cms-sw/cmssw#23200]
The LogWarning message from HLTObjectsMonitor for "objects have different ID" are a source of inflation of the LogError skim (after MemoryChecker), and for this reason #23185 proposes to downgrade it to LogInfo. 

Following the comment https://github.com/cms-sw/cmssw/pull/23185#issuecomment-388324906 it would be useful to fix the causes for these messages, and restore back the original severity level of them once the problems have been fixed.

**Comment by fabiocos** [comment]
assign hlt

**Comment by Martin-Grunewald** [comment]
assign dqm

**Comment by fabiocos** [comment]
@Martin-Grunewald @silviodonato @qliphy is the problem reported here still present?

**Comment by Martin-Grunewald** [comment]
Looks resolved to me...

**Comment by fabiocos** [comment]
I do still see the ```LogInfo```, it would be interesting to understand whether going back to a ```LogError``` is now feasible.

**Comment by missirol** [comment]
> I do still see the `LogInfo`, it would be interesting to understand whether going back to a `LogError` is now feasible.

I'm new to this issue, but my understanding is that going back to `LogError` is not a viable option.

The module mentioned in #23185 (i.e. `HLTHtMhtFilter`) adds by construction trigger objects of 2 different types [[1]](https://github.com/cms-sw/cmssw/blob/ff75956ff1b3cf2f1ccdda06e31f739fc447f798/HLTrigger/JetMET/src/HLTHtMhtFilter.cc#L104-L105) [[2]](https://github.com/cms-sw/cmssw/blob/ff75956ff1b3cf2f1ccdda06e31f739fc447f798/DataFormats/HLTReco/interface/TriggerTypeDefs.h#L85-L86).

This suggests that the check in the DQM module is ill-defined; it assumes a behaviour (i.e. a module returning trigger-objects of only one single type) that not all HLT modules have.

I would suggest to remove that message altogether to avoid further confusion (see #36126).

In any case (whether or not the `LogInfo` call is removed), I think this issue could be closed.

**Comment by fabiocos** [comment]
@perrotta @qliphy please note the follow-up of this discussion. Are you ok to close this issue, and possibly move further actions to a new one?

**Comment by missirol** [comment]
+hlt
