### ISSUE TITLE
Crashes observed in CMSSW_10_2_0_pre3 RelVals in HCAL DQM 

### ISSUE THREAD

**Issue by fabiocos** [cms-sw/cmssw#23259]
The title says it all, the module affected by the crash is Module: DigiPhase1Task:digiPhase1Task (crashed) for details see https://hypernews.cern.ch/HyperNews/CMS/get/recoDevelopment/1587/1/1.html

**Comment by fabiocos** [comment]
assign dqm

**Comment by fabiocos** [comment]
@DryRun could you please have a look into this?

**Comment by DryRun** [comment]
@fabiocos Certainly, I'm looking into this now. It's an old module from before my time that I didn't know was still in use, but it shouldn't take long to track down.

**Comment by fabiocos** [comment]
@DryRun as far as I can see the problem happens in

(gdb) up
#1  0x00007fffc0db7d5b in hcaldqm::Container1D::fill (this=this@entry=0x7fffc0c339d0, did=..., x=x@entry=157.59999999999999)
    at /build/fabiocos/102X/crash/CMSSW_10_2_0_pre3/src/DQM/HcalCommon/src/Container1D.cc:160
160                             _mes[_hashmap.getHash(did)]->Fill(_qx->getValue(x));
(gdb) up
#2  0x00007fffc0f8377d in DigiPhase1Task::_process (this=0x7fffc0c33000, e=...)
    at /build/fabiocos/102X/crash/CMSSW_10_2_0_pre3/src/DQM/HcalTasks/plugins/DigiPhase1Task.cc:351
351                     _cSumQ_SubdetPM.fill(did, sumQ);


Apparently there is something wrong with one DetId, printing did and sumQ before line 351:

did = (HE 28,63,7)
sumQ = 2072.7
did = (HE 28,65,7)
sumQ = 2883.1
did = 4e229bf0
sumQ = 157.6

Thread 1 "cmsRun" received signal SIGSEGV, Segmentation fault.
0x00007fffed4847e0 in MonitorElement::Fill(double) ()
   from /cvmfs/cms.cern.ch/slc6_amd64_gcc630/cms/cmssw/CMSSW_10_2_0_pre3/lib/slc6_amd64_gcc630/libDQMServicesCore.so
(gdb) up
#1  0x00007fffc0db7d5b in hcaldqm::Container1D::fill (this=this@entry=0x7fffc0c2e9d0, did=..., x=x@entry=157.59999999999999)
    at /build/fabiocos/102X/crash/CMSSW_10_2_0_pre3/src/DQM/HcalCommon/src/Container1D.cc:160
160                             _mes[_hashmap.getHash(did)]->Fill(_qx->getValue(x));
(gdb) print did
$1 = (const HcalDetId &) @0x7fffffff49b0: {<DetId> = {static kDetMask = 15, static kSubdetMask = 7, static kDetOffset = 28, static kSubdetOffset = 25, 
    id_ = 1310890992}, static kHcalPhiMask1 = 127, static kHcalPhiMask2 = 1023, static kHcalEtaOffset1 = 7, static kHcalEtaOffset2 = 10, 
  static kHcalEtaMask1 = 63, static kHcalEtaMask2 = 511, static kHcalZsideMask1 = 8192, static kHcalZsideMask2 = 524288, static kHcalDepthOffset1 = 14, 
  static kHcalDepthOffset2 = 20, static kHcalDepthMask1 = 31, static kHcalDepthMask2 = 15, static kHcalDepthSet1 = 114688, static kHcalDepthSet2 = 15728640, 
  static kHcalIdFormat2 = 16777216, static kHcalIdMask = -33554432, static Undefined = {<DetId> = {static kDetMask = 15, static kSubdetMask = 7, 
      static kDetOffset = 28, static kSubdetOffset = 25, id_ = 1090519040}, static kHcalPhiMask1 = 127, static kHcalPhiMask2 = 1023, 
    static kHcalEtaOffset1 = 7, static kHcalEtaOffset2 = 10, static kHcalEtaMask1 = 63, static kHcalEtaMask2 = 511, static kHcalZsideMask1 = 8192, 
    static kHcalZsideMask2 = 524288, static kHcalDepthOffset1 = 14, static kHcalDepthOffset2 = 20, static kHcalDepthMask1 = 31, static kHcalDepthMask2 = 15, 
    static kHcalDepthSet1 = 114688, static kHcalDepthSet2 = 15728640, static kHcalIdFormat2 = 16777216, static kHcalIdMask = -33554432, 
    static Undefined = <same as static member of an already seen type>}}
(gdb) print _hashmap.getHash(did)
$2 = 1326449665

**Comment by DryRun** [comment]
Hi @fabiocos , thanks for the investigation. The problematic DetIds are calibration channels, not real detector channels, which are included in QIE10/11DigiCollection by HcalUnpacker. The crash can be fixed by enforcing that the digis be HB/HE/HF: https://github.com/cms-sw/cmssw/pull/23262. It would be nice if HcalUnpacker did a better job of sorting things like this - something I'll consider for the future.

As I say in the PR comments, it's not entirely obvious to me why this crash is only occurring now, but this fix should have no impact on the intended behavior of the module (which is no longer used anyways, as far as I know).

**Comment by fabiocos** [comment]
I cross-checked that #23262 solves the problem, and it has been merged, so this issue can be closed
