### ISSUE TITLE
Build error in L1Trigger/CSCTriggerPrimitives

### ISSUE THREAD

**Issue by mrodozov** [cms-sw/cmssw#23299]
We are cleaning the build errors for gcc8 IB and there is an error in L1Trigger/CSCTriggerPrimitives namely: https://cmssdt.cern.ch/SDT/cgi-bin/buildlogs/slc7_amd64_gcc810/CMSSW_10_2_X_2018-05-22-2300/L1Trigger/CSCTriggerPrimitives
which is not easy to circumvent as we don't understand completely what it aims to do, so we would like to ask the devs to check it out. To setup and reproduce it go on lxplus7 and run this:

```
ssh lxplus7
scram -a slc7_amd64_gcc810 p CMSSW_10_2_X_2018-05-22-2300
cd CMSSW_10_2_X_2018-05-22-2300/
cmsenv
git-cms-addpkg L1Trigger/CSCTriggerPrimitives
scram b
```

We decided it would be better to ask the devs directly instead of trying to 'guess' what would be sufficient solution.

**Comment by smuzaffar** [comment]
assign l1

**Comment by smuzaffar** [comment]
Fix is available here https://github.com/cms-sw/cmssw/pull/23340
