### ISSUE TITLE
Failure in wf 250399 induced by the phase2 premixing code update #23065

### ISSUE THREAD

**Issue by fabiocos** [cms-sw/cmssw#23304]
After the merge of #23065 , the test workflow 250399.0 fails because of a configuration problem, see 

https://cmssdt.cern.ch/SDT/cgi-bin/buildlogs/slc6_amd64_gcc630/CMSSW_10_2_X_2018-05-23-2300/pyRelValMatrixLogs/run/250399.0_FS_PREMIXUP15_PU25+FS_PREMIXUP15_PU25/step1_FS_PREMIXUP15_PU25+FS_PREMIXUP15_PU25.log

The problems happens in

  File "/cvmfs/cms-ib.cern.ch/nweek-02525/slc6_amd64_gcc630/cms/cmssw/CMSSW_10_2_X_2018-05-23-2300/python/SimGeneral/MixingModule/caloTruthProducer_cfi.py", line 38, in <module>
    premix_stage1.toModify(caloParticles, premixStage1 = True)

due to

KeyError: 'Unknown parameter name premixStage1 specified while calling Modifier'

**Comment by fabiocos** [comment]
@makortel we should fix this before building pre4

**Comment by makortel** [comment]
I'll take a look.

**Comment by fabiocos** [comment]
@makortel the problem looks to originate here

https://cmssdt.cern.ch/lxr/source/SimGeneral/MixingModule/python/caloTruthProducer_cfi.py#0035

For fastsim the caloParticles PSet is empty, so the premixStage1 key is unknown in that case. A corresponding protection should be added for the fastsim case

**Comment by makortel** [comment]
Yes, I'm already testing a fix (which seems to work as it doesn't crash but I'd like the job to finish before a PR)

**Comment by fabiocos** [comment]
I think that just inverting the two toModify should do the job. I wait for your PR, I would like to merge it and then build pre4

**Comment by makortel** [comment]
Fixed in #23305.

**Comment by fabiocos** [comment]
@makortel thanks, the issues may be closed
