### ISSUE TITLE
Isolated ProductNotFound error in CMSSW_10_2_X_2018-05-22-2300

### ISSUE THREAD

**Issue by fabiocos** [cms-sw/cmssw#23311]
I note here an isolated and not reproducible ProductNotFound error that has happened in CMSSW_10_2_X_2018-05-22-2300 for wf 136.7802 step2

----- Begin Fatal Exception 23-May-2018 05:10:00 CEST-----------------------
An exception of category 'ProductNotFound' occurred while
   [0] Processing  Event run: 297227 lumi: 4 event: 299600 stream: 2
   [1] Running path 'dqmofflineOnPAT_step'
   [2] Calling method for module TopMonitor/'BTagMu_AK4DiJet20_Mu5'
Exception Message:
Principal::getByToken: Found zero products matching all criteria
Looking for type: std::vector<reco::Vertex>
Looking for module label: offlinePrimaryVertices
Looking for productInstanceName: 

   Additional Info:
      [a] If you wish to continue processing events after a ProductNotFound exception,
add "SkipEvent = cms.untracked.vstring('ProductNotFound')" to the "options" PSet in the configuration.

----- End Fatal Exception -------------------------------------------------

This error is not appearing for other architectures than slc6_amd64_gcc630, I did not manage to reproduce it and is not observed before or after that IB.

**Comment by Dr15Jones** [comment]
@fabiocos I had noticed it as well and have no idea. We've never seen any multi-threading-related problem like it before, though. We haven't changed any part of that system is several years so it seems unlikely. Perhaps valgrind might shed some light?

**Comment by Dr15Jones** [comment]
I took a quick look at the code, it appears the data product in question is set via a `mayConsumes`

https://github.com/cms-sw/cmssw/blob/4e9bfb8321fcc0527e0444192e29b0c7f02a7f32/DQMOffline/Trigger/plugins/TopMonitor.cc#L30

In principal, the framework is supposed to treat a `mayConsumes` the same as a `consumes` so that difference shouldn't matter.

The vertex is also only requested if a cut before hand succeeds
https://github.com/cms-sw/cmssw/blob/4e9bfb8321fcc0527e0444192e29b0c7f02a7f32/DQMOffline/Trigger/plugins/TopMonitor.cc#L544

It is possible that in all previous tests, that cut has always failed so we this code never asked for the vertex before.

**Comment by Dr15Jones** [comment]
I looked further into the job. The data product was supposed to come from the input file (not from a module begin run in the job). Inspecting the ROOT file, I do see that for the 76th event in the file there is a corresponding entry in the branch that is supposed to be read. So it should have worked.

One interesting thing I noticed, events 73, 74, 75 and 76 are all started at the same time because they are the first 4 events after a new LuminosityBlock. It is possible that the failure and the new LuminosityBlock being started are related (but never before seen).

**Comment by Dr15Jones** [comment]
assign core

**Comment by Dr15Jones** [comment]
Another interesting item I notice is there was another module which had an error but its exception is not show since the framework only shows one exception per stream. The module is `topElecMuonHLTMonitor`.

The only other modules run during the event that failed are: `egHLTOffDQMSource` (on EndPath), `egHLTOffDQMSource_HEP17` (on EndPath), `DQMOutput` (on EndPath), `DQMoutput_step` (FWK module), `dqmofflineOnPAT_step` (FWK module), `dqmoffline_step` (FWK module).

**Comment by Dr15Jones** [comment]
This happened again on the same workflow
https://cmssdt.cern.ch/SDT/cgi-bin/logreader/slc7_amd64_gcc700/CMSSW_10_2_X_2018-06-03-2300/pyRelValMatrixLogs/run/136.7802_RunHLTPhy2017B_AODextra+RunHLTPhy2017B_AODextra+DQMHLTonAODextra_2017+HARVESTDQMHLTonAOD_2017/step2_RunHLTPhy2017B_AODextra+RunHLTPhy2017B_AODextra+DQMHLTonAODextra_2017+HARVESTDQMHLTonAOD_2017.log#/

```
----- Begin Fatal Exception 04-Jun-2018 04:19:49 CEST-----------------------
An exception of category 'ProductNotFound' occurred while
   [0] Processing  Event run: 297227 lumi: 3 event: 222025 stream: 0
   [1] Running path 'dqmofflineOnPAT_step'
   [2] Calling method for module TopMonitor/'BTagMu_AK4DiJet20_Mu5'
Exception Message:
Principal::getByToken: Found zero products matching all criteria
Looking for type: std::vector<reco::Vertex>
Looking for module label: offlinePrimaryVertices
Looking for productInstanceName: 

   Additional Info:
      [a] If you wish to continue processing events after a ProductNotFound exception,
add "SkipEvent = cms.untracked.vstring('ProductNotFound')" to the "options" PSet in the configuration.

----- End Fatal Exception -------------------------------------------------
```

**Comment by Dr15Jones** [comment]
This happened again for the same workflow
https://cmssdt.cern.ch/SDT/cgi-bin/logreader/slc6_amd64_gcc700/CMSSW_10_2_X_2018-06-12-1100/pyRelValMatrixLogs/run/136.7802_RunHLTPhy2017B_AODextra+RunHLTPhy2017B_AODextra+DQMHLTonAODextra_2017+HARVESTDQMHLTonAOD_2017/step2_RunHLTPhy2017B_AODextra+RunHLTPhy2017B_AODextra+DQMHLTonAODextra_2017+HARVESTDQMHLTonAOD_2017.log#/

```
Begin processing the 49th record. Run 297227, Event 160500, LumiSection 2 on stream 3 at 12-Jun-2018 13:36:01.524 CEST
Begin processing the 50th record. Run 297227, Event 222025, LumiSection 3 on stream 0 at 12-Jun-2018 13:36:01.639 CEST
Begin processing the 51st record. Run 297227, Event 189925, LumiSection 3 on stream 2 at 12-Jun-2018 13:36:01.644 CEST
Begin processing the 52nd record. Run 297227, Event 195275, LumiSection 3 on stream 1 at 12-Jun-2018 13:36:01.644 CEST
Begin processing the 53rd record. Run 297227, Event 256800, LumiSection 3 on stream 3 at 12-Jun-2018 13:36:01.645 CEST
----- Begin Fatal Exception 12-Jun-2018 13:36:01 CEST-----------------------
An exception of category 'ProductNotFound' occurred while
   [0] Processing  Event run: 297227 lumi: 3 event: 256800 stream: 3
   [1] Running path 'dqmofflineOnPAT_step'
   [2] Calling method for module TopMonitor/'BTagMu_AK4DiJet20_Mu5'
Exception Message:
Principal::getByToken: Found zero products matching all criteria
Looking for type: std::vector&lt;reco::Vertex&gt;
Looking for module label: offlinePrimaryVertices
Looking for productInstanceName: 

   Additional Info:
      [a] If you wish to continue processing events after a ProductNotFound exception,
add "SkipEvent = cms.untracked.vstring('ProductNotFound')" to the "options" PSet in the configuration.

----- End Fatal Exception -------------------------------------------------
12-Jun-2018 13:36:03 CEST  Closed file root://eoscms.cern.ch//eos/cms/store/user/cmsbuild/store/data/Run2017B/HLTPhysics/AOD/PromptReco-v1/000/297/227/00000/2AF3A8A8-B358-E711-8FC6-02163E011C9E.root
```

Once again, it happens within the first 4 events of switching to a new lumi.

**Comment by Dr15Jones** [comment]
This happened in a different, but related workflow:
https://cmssdt.cern.ch/SDT/cgi-bin/logreader/slc7_amd64_gcc700/CMSSW_10_2_X_2018-06-12-1100/pyRelValMatrixLogs/run/136.7801_RunHLTPhy2017B_AOD+RunHLTPhy2017B_AOD+DQMHLTonAOD_2017+HARVESTDQMHLTonAOD_2017/step2_RunHLTPhy2017B_AOD+RunHLTPhy2017B_AOD+DQMHLTonAOD_2017+HARVESTDQMHLTonAOD_2017.log#/

```
Begin processing the 49th record. Run 297227, Event 160500, LumiSection 2 on stream 1 at 12-Jun-2018 16:31:44.153 CEST
Begin processing the 50th record. Run 297227, Event 222025, LumiSection 3 on stream 0 at 12-Jun-2018 16:31:44.561 CEST
Begin processing the 51st record. Run 297227, Event 189925, LumiSection 3 on stream 3 at 12-Jun-2018 16:31:44.563 CEST
Begin processing the 52nd record. Run 297227, Event 195275, LumiSection 3 on stream 2 at 12-Jun-2018 16:31:44.565 CEST
Begin processing the 53rd record. Run 297227, Event 256800, LumiSection 3 on stream 1 at 12-Jun-2018 16:31:44.566 CEST
Begin processing the 54th record. Run 297227, Event 230050, LumiSection 3 on stream 0 at 12-Jun-2018 16:31:44.646 CEST
Begin processing the 55th record. Run 297227, Event 187250, LumiSection 3 on stream 3 at 12-Jun-2018 16:31:44.715 CEST
----- Begin Fatal Exception 12-Jun-2018 16:31:44 CEST-----------------------
An exception of category 'ProductNotFound' occurred while
   [0] Processing  Event run: 297227 lumi: 3 event: 256800 stream: 1
   [1] Running path 'dqmoffline_step'
   [2] Calling method for module HLTMuonOfflineAnalyzer/'globalAnalyzerTnP'
Exception Message:
Principal::getByToken: Found zero products matching all criteria
Looking for type: edm::TriggerResults
Looking for module label: TriggerResults
Looking for productInstanceName: 
Looking for process: HLT
   Additional Info:
      [a] If you wish to continue processing events after a ProductNotFound exception,
add "SkipEvent = cms.untracked.vstring('ProductNotFound')" to the "options" PSet in the configuration.

----- End Fatal Exception -------------------------------------------------
12-Jun-2018 16:31:45 CEST  Closed file root://eoscms.cern.ch//eos/cms/store/user/cmsbuild/store/data/Run2017B/HLTPhysics/AOD/PromptReco-v1/000/297/227/00000/2AF3A8A8-B358-E711-8FC6-02163E011C9E.root
```

This happened when stream 1 was processing the first event that stream has seen for a new lumi.

The data product in question is also being read from the source.

**Comment by fabiocos** [comment]
@silviodonato I do not recall to have seen this since a while, did you notice it recently?

**Comment by silviodonato** [comment]
No, I didn't see that error recently.
