### ISSUE TITLE
Cleanup of GeneratorInterface/EvtGenInterface

### ISSUE THREAD

**Issue by smuzaffar** [cms-sw/cmssw#23334]
Headers files in https://github.com/cms-sw/cmssw/tree/master/GeneratorInterface/EvtGenInterface/interface/EvtGenUserModels/*.hh and https://github.com/cms-sw/cmssw/blob/master/GeneratorInterface/EvtGenInterface/interface/EvtGenInterface.h are only used by GeneratorInterface/EvtGenInterface/plugins. So we should move all these headers in GeneratorInterface/EvtGenInterface/plugins/EvtGenUserModels directory.

Currently this breaks the header-consistency check as proper dependency on `evtgen` is added in GeneratorInterface/EvtGenInterface.

**Comment by smuzaffar** [comment]
assign generator

**Comment by alberto-sanchez** [comment]
+1

**Comment by fabiocos** [comment]
@smuzaffar @alberto-sanchez I assume that this issue can be closed, after the merge of #23348

**Comment by alberto-sanchez** [comment]
I think so, thanks!
