### ISSUE TITLE
Use different return value for write failures

### ISSUE THREAD

**Issue by Dr15Jones** [cms-sw/cmssw#23509]
When a 'FileWriteError' exception is thrown, it is just a regular `cms::Exception`, therefore when the job ends it just returns the value for `OtherCMS` exception, not its own code.

Returning a unique code for 'FileWriteError' could be useful for the workflow management system.

**Comment by Dr15Jones** [comment]
This was first requested from the hypernews thread:
https://urldefense.proofpoint.com/v2/url?u=https-3A__hypernews.cern.ch_HyperNews_CMS_get_edmFramework_3833.html&d=DwIBAw&c=gRgGjJ3BkIsb5y6s49QqsA&r=HIUuPArZ6-xhVnE7rXib2Q&m=cHS4J6U4WD7c72x1FtYPsqqK_WGhk42q2uut05qNc48&s=WkqbJO_Z66a-59VA-uO-CcOmlTFfnY2JdsnHz22AMhM&e=

**Comment by Dr15Jones** [comment]
@belforte FYI

**Comment by Dr15Jones** [comment]
Switching to a unique `edm::Exception` for 'FileWriteError' is not as trivial as one could hope since there is helper function `throwStorageError` which is used by several pieces of code to throw an exception with 'FileWriteError' but is also used to throw exceptions with different strings.

In addition, the original request was for a specific 'out of storage space' error. Such may be able to be accommodated although it would require looking at the posix error code (assuming the storage interface returns such). The appropriate error number appears to be `ENOSPC` 
https://linux.die.net/man/3/errno

**Comment by belforte** [comment]
OK. I read as "too much pain for gain". Let's forget. Thanks anyhow. Maybe let's simply make sure that we have some clear way to report details about "generic exceptions". In the HN thread above I was reading stderr, maybe the exception messae is already in FJR (or could be?).

**Comment by Dr15Jones** [comment]
I was able to modify the system so that exceptions which were labelled `FileWriteError` now cause cmsRun to return with a unique code. However, that exception happens for any write problem.

A major complication for having a separate `FileWriteToFullFileSystemError` is we allow writing from xrootd and dcache. Looking at the documentation for both systems and I can't find a code they use to denote a full file system. Therefore the only consistent message I can give is `FileWriteError`.

**Comment by Dr15Jones** [comment]
@bbockelm FYI

**Comment by fabiocos** [comment]
@Dr15Jones @belforte this is now in the IB for possible checks

**Comment by belforte** [comment]
thanks, I have opened a WMCore issue to add this code to the list of known ones
https://github.com/dmwm/WMCore/issues/8647

**Comment by bbockelm** [comment]
While we allow writing to Xrootd and dCache, I don't believe this is done in practice at any site.

That said, I think having a file write error is a good enough approximation for now.

**Comment by Dr15Jones** [comment]
+1
