### ISSUE TITLE
Memory leaks in OMTF

### ISSUE THREAD

**Issue by kpedro88** [cms-sw/cmssw#23565]
While valgrinding something else, I noticed some memory leaks in OMTF code.

One source of leaks (~6MB) is in the L1 processor:
https://github.com/cms-sw/cmssw/blob/020159eb35d2bc1d11d7bd637e1f85bd2eb3c005/L1Trigger/L1TMuonOverlap/src/OMTFProcessor.cc#L89
https://github.com/cms-sw/cmssw/blob/020159eb35d2bc1d11d7bd637e1f85bd2eb3c005/L1Trigger/L1TMuonOverlap/src/OMTFProcessor.cc#L106

Another source of leaks (~1MB) comes from the emap in the packer:
https://github.com/cms-sw/cmssw/blob/2eb7907eaebf26cd9483ebac2ac51996003683b1/EventFilter/L1TRawToDigi/src/OmtfRpcPacker.cc#L20
https://github.com/cms-sw/cmssw/blob/2eb7907eaebf26cd9483ebac2ac51996003683b1/CondFormats/RPCObjects/interface/RPCEMap.h#L68

The code should be updated to include manual memory management or, ideally, use of smart pointers.

**Comment by kpedro88** [comment]
assign l1,db,reconstruction

**Comment by slava77** [comment]
@kpedro88 
what was the reason to assign this to reco?

**Comment by kpedro88** [comment]
1. The second leak shows up in the packer sequence (even though the source is CondFormats)
2. Reco L2s seem more likely to actually press someone to fix the code

**Comment by slava77** [comment]
which packer sequence?
EventFilter/L1TRawToDigi belongs to L1
please double-check https://github.com/cms-sw/cms-bot/blob/master/categories_map.py to confirm that the packages with affected code are in the reco category.
Thank you.

**Comment by thomreis** [comment]
@konec , @kbunkow please take note of this.

**Comment by kpedro88** [comment]
@slava77 you are right, I was thinking of the whole EventFilter subsystem as part of reco. Apologies.

**Comment by kpedro88** [comment]
unassign reconstruction

**Comment by konec** [comment]
Hi, thank you for finding these problems.
These leaks are not of key importance, because the objects are created only once per job i think. But of course I will fix it (and try to do it soon).

**Comment by konec** [comment]
It is now fixed in PR: https://github.com/cms-l1t-offline/cmssw/pull/710

**Comment by kpedro88** [comment]
Will this PR be submitted to the official repo?

**Comment by thomreis** [comment]
Yes. @rekovic plans to make a new master PR with this. And also a backport for 10_2_x.

**Comment by kpedro88** [comment]
Resolved by #24539
