### ISSUE TITLE
Python XRootD binding broken in CMSSW_10_2_*

### ISSUE THREAD

**Issue by piberger** [cms-sw/cmssw#23560]
Xrootd python bindings are broken for me since version 10.2, 

to reproduce:

    cmsenv
    python
    >>> import XRootD

CMSSW_10_2_0_pre4:
"ImportError: No module named XRootD"

CMSSW_10_1_0:
everything ok!

alternatively:

    from xrootdpyfs import XRootDPyFS

will yield the error: ImportError: No module named XRootD.client

anything I can do besides using the (slower) xrdfs program?

**Comment by Dr15Jones** [comment]
assign core

**Comment by smuzaffar** [comment]
@piberger , thanks for reporting this. Looks like it was broken when we did python2/3 updates. We will fix this for next 10_2_X IB. For now you can do
```
export PYTHON27PATH=$(scram tool tag xrootd XROOTD_BASE)/lib/python2.7/site-packages:${PYTHON27PATH}
```
to get it in PYTHON27PATH.

**Comment by smuzaffar** [comment]
This https://github.com/cms-sw/cmsdist/pull/4106 should fix the issue once merged.

**Comment by piberger** [comment]
@smuzaffar thanks for your quick help, your workaround with the PYTHON27PATH works for me!

**Comment by smuzaffar** [comment]
+core
