### ISSUE TITLE
[GCC 7] Fortran warnings in GeneratorInterface/AMPTInterface about used but uninitialized

### ISSUE THREAD

**Issue by smuzaffar** [cms-sw/cmssw#23573]
There are 5 compiler warnings about `used but uninitialized` variables in one fortran file https://github.com/cms-sw/cmssw/blob/master/GeneratorInterface/AMPTInterface/src/hipyset1.35.f

@mrodozov had contacted the developers few months ago but have not received any fix. We should get this fixed or hide before moving to GCC 7 as production compiler (to avoid having the new 'compilation-warnings' label for PR tests). 

Until we get a fix from the developer, should we hide it by dropping the `-Wuninitialized` flag for this fortran file only e.g. one can add the following in to BuildFile to apply the flag only for this file.
```
<architecture match="_gcc[7-9]">
  <flags REM_FFLAGS="-Wuninitialized" file="hipyset1.35.f"/>
</architecture>
```

[a]
https://cmssdt.cern.ch/SDT/cgi-bin/buildlogs/slc7_amd64_gcc700/CMSSW_10_2_X_2018-06-12-2300/GeneratorInterface/AMPTInterface

**Comment by smuzaffar** [comment]
assign generators
FYI, @kurtejung

**Comment by smuzaffar** [comment]
For ref I have adding the wraning message here as IB logs will go away in few days.
```
src/GeneratorInterface/AMPTInterface/src/hipyset1.35.f:14004:0:

         SIGH(NCHN)=FACHCQ*(WDTE(0,1)+WDTE(0,(5-KCHHC)/2)+WDTE(0,4))
 
  Warning: 'wdte[41]' may be used uninitialized in this function [-Wmaybe-uninitialized]
 src/GeneratorInterface/AMPTInterface/src/hipyset1.35.f:14004:0: Warning: 'wdte[164]' may be used uninitialized in this function [-Wmaybe-uninitialized]
src/GeneratorInterface/AMPTInterface/src/hipyset1.35.f:14004:0: Warning: 'wdte[_4917]' may be used uninitialized in this function [-Wmaybe-uninitialized]
src/GeneratorInterface/AMPTInterface/src/hipyset1.35.f:14011:0:

         SIGH(NCHN)=FACHCQ*(WDTE(0,1)+WDTE(0,(5-KCHHC)/2)+WDTE(0,4))
 
  Warning: 'wdte[_4942]' may be used uninitialized in this function [-Wmaybe-uninitialized]
 src/GeneratorInterface/AMPTInterface/src/hipyset1.35.f:14018:0:

         SIGH(NCHN)=FACHCQ*(WDTE(0,1)+WDTE(0,(5-KCHHC)/2)+WDTE(0,4))
 
  Warning: 'wdte[_4968]' may be used uninitialized in this function [-Wmaybe-uninitialized]
 src/GeneratorInterface/AMPTInterface/src/hipyset1.35.f:14025:0:

         SIGH(NCHN)=FACHCQ*(WDTE(0,1)+WDTE(0,(5-KCHHC)/2)+WDTE(0,4))
 
  Warning: 'wdte[_4992]' may be used uninitialized in this function [-Wmaybe-uninitialized]
 src/GeneratorInterface/AMPTInterface/src/hipyset1.35.f:7409:0:

       IF(IVAR.EQ.1) IOFF=0
 
  Warning: 'ioff' may be used uninitialized in this function [-Wmaybe-uninitialized]
```

**Comment by alberto-sanchez** [comment]
hi @kurtejung, are you looking into this?

**Comment by kurtejung** [comment]
hi @alberto-sanchez - I left CMS a few months ago and am no longer the responsible for this package.   I'll ping the HIN conveners and ask who the new person in charge of the package is and list them here. Thanks.

**Comment by wouf** [comment]
Please check #23815

**Comment by alberto-sanchez** [comment]
+1
