### ISSUE TITLE
FWCore/ParameterSet headers check error

### ISSUE THREAD

**Issue by mrodozov** [cms-sw/cmssw#23598]
I'm trying to finish the headers work regarding #15248. We still have few headers with errors in FWCore/ParameterSet 
https://cmssdt.cern.ch/SDT/jenkins-artifacts/check_headers/CMSSW_10_2_X_2018-06-14-2300/slc6_amd64_gcc630/headers_with_error.log 
Could you please have a look, to cover completely FWCore ?
To reproduce the error just checkout FWCore/ParameterSet  and run it with
`scram b -j $nthreads -k check-headers`
Cheers,
M.

**Comment by fabiocos** [comment]
assign core

**Comment by Dr15Jones** [comment]
@wddgit could you take a look at this?

**Comment by Dr15Jones** [comment]
See #23626

**Comment by Dr15Jones** [comment]
+1
