### ISSUE TITLE
Test EcalIntercalibConstants_O2O_test failing in recent IBs

### ISSUE THREAD

**Issue by fabiocos** [cms-sw/cmssw#23606]
Since the build of Friday 15 June evening, one of the unit tests in CondTools/Ecal, namely EcalIntercalibConstants_O2O_test , is failing with the output

%MSG
----- Begin Fatal Exception 18-Jun-2018 00:13:24 CEST-----------------------
An exception of category 'ConditionDatabase' occurred while
   [0] Calling endJob for module EcalIntercalibConstantsPopConBTransitionAnalyzer/'popConEcalIntercalibConstants'
Exception Message:
Tag "EcalIntercalibConstants_0T" has not been found in the database. from IOVProxy::load 
----- End Fatal Exception -------------------------------------------------

There is a number of connection failures reported earlier, like

[2018-06-18 00:12:55,685] INFO: Connecting to pro [frontier://PromptProd/CMS_CONDITIONS]
warn  [frontier.c:1014]: Request 1 on chan 1 failed at Mon Jun 18 00:13:00 2018: -9 [fn-socket.c:125]: connect to 2001:1458:301:d2::100:2 timed out after 5 seconds
warn  [frontier.c:1114]: Trying next proxy cmsmeyproxy.cern.ch[2001:1458:301:7f::100:1a] with same server cmsfrontier.cern.ch
[2018-06-18 00:13:01,165] INFO: Connecting to EcalIntercalibConstants_V1_hlt_O2OTEST.db [sqlite:///EcalIntercalibConstants_V1_hlt_O2OTEST.db]
[2018-06-18 00:13:01,271] ERROR: There is no tag, global tag or (unique) payload named EcalIntercalibConstants_0 in the database.
[2018-06-18 00:13:02,053] INFO: Connecting to pro [frontier://PromptProd/CMS_CONDITIONS]
warn  [frontier.c:1014]: Request 1 on chan 1 failed at Mon Jun 18 00:13:07 2018: -9 [fn-socket.c:125]: connect to 2001:1458:301:d2::100:2 timed out after 5 seconds
warn  [frontier.c:1114]: Trying next proxy cmsmeyproxy.cern.ch[2001:1458:301:7f::100:1a] with same server cmsfrontier.cern.ch

that could be related to this. Anyway the problem seems unrelated from possible changes in CMSSW itself.

**Comment by fabiocos** [comment]
assign db

**Comment by ggovi** [comment]
@depasse 
Hello Pierre, can you please have a look?
Thanks!

**Comment by depasse** [comment]
Hi,

why "There is no tag, global tag or (unique) payload named EcalIntercalibConstants_0 in the database."
It is "EcalIntercalibConstants_0T" .

The switching Bon/Boff process has well worked recently, see  : 
O2O Run Log Job Name: EcalIntercalibConstants_hlt, Start Time: 2018-06-15 15:45:11.618702
,with  the tag EcalIntercalibConstants_0T.

N.B. 
There is a tag EcalIntercalibConstants_0T_v2 with the same last payload if needed.  It was created due to the boost serializer problem  (mails from 11 April 2017).  Change was done for 3.8T -> 3.8T_v2 but not for 0T.

**Comment by ggovi** [comment]
@depasse 
Hi Pierre, this is a TEST. it has nothing to do with the production O2O. You can find the source in:
https://github.com/cms-sw/cmssw/blob/master/CondTools/Ecal/test/EcalIntercalibConstants_O2O_test.sh

**Comment by depasse** [comment]
Hi Giacomo,

you have to change L3 : EcalIntercalibConstants_0   by EcalIntercalibConstants_0T

L3  : conddb --yes copy EcalIntercalibConstants_0 --destdb EcalIntercalibConstants_V1_hlt_O2OTEST.db

**Comment by ggovi** [comment]
@depasse 
Ok thanks. Pretty strange that it was working before. Can you please prepare the PR?

**Comment by depasse** [comment]
May I create a new PR or is it possible to use the present number (and how ?) Thanks.

**Comment by ggovi** [comment]
@depasse 
I guess it's better to  create a new PR and then reference it here with one more comment.

**Comment by depasse** [comment]
New PR to correct this : "Correction of a tag name" #23610

**Comment by ggovi** [comment]
@depasse 
thanks a lot! I guess this issue can be closed.

**Comment by fabiocos** [comment]
@depasse as this is failing in 10_1_X as well, could you please make a backport there?

**Comment by depasse** [comment]
Sure but I don't know how to do it. Could you indicate me how to proceed or a link to a document that explains.  Thanks.

**Comment by boudoul** [comment]
Dear @depasse, @fabiocos , @ggovi 
In order to speed up the process, I made myself the backport  :  it is here :  #23622
[I made exactly the same change as @depasse] 

I can show at my next visit in Lyon to Pierre how to do it
