### ISSUE TITLE
Fix premixing for HGCal v9 geometry

### ISSUE THREAD

**Issue by makortel** [cms-sw/cmssw#23624]
The HGCal v9 geometry #23545 uses new DetId's (`HGCSiliconDetId`, `HGCScintillatorDetId`) that use also the subdet-part (i.e. 28 bits in total) of the DetId for subdet-specific data. This is incompatible with how the `PHGCSimAccumulator` currently packs the subdet-specific data by taking the 27 lowest bits
https://github.com/cms-sw/cmssw/blob/3001e850a307d3a1e10f3d862f26cad0c3785e20/DataFormats/HGCDigi/interface/PHGCSimAccumulator.h#L14-L16

Simplest would be to extend the aforementioned `DetIdSize` from 32 bits to 64 bits and let ROOT handle the compression of the 31 zero bits. If this turns out to have too large size increase, more involved optimizations can be tested as well.

@kpedro88 @mdhildreth

**Comment by kpedro88** [comment]
assign simulation,upgrade

**Comment by kpedro88** [comment]
@makortel have you had any time to work on this?

**Comment by kpedro88** [comment]
@makortel okay, let's go for the trivial solution first, and then we can improve it later depending on how well the compression works.

**Comment by makortel** [comment]
Addressed in #24610.
