### ISSUE TITLE
Duplication of parameter declarations in SiStrip tracker DIGI

### ISSUE THREAD

**Issue by fabiocos** [cms-sw/cmssw#23634]
During the review of #23621 I commented about the evident duplication of parameters between 

https://cmssdt.cern.ch/lxr/source/SimGeneral/MixingModule/python/SiStripSimParameters_cfi.py
and
https://cmssdt.cern.ch/lxr/source/SimTracker/SiStripDigitizer/python/SiStripDigiSimLink_cfi.py

It would seem appropriate to have a common PSet definition that is then imported in both configurations, avoiding duplications that are error prone. The problem was not introduced by the mentioned PR, it just enlarged it, and given the 10_2_X deadline I preferred to move forward anyway. But I open this issue to keep track of the request of code cleaning and follow it

**Comment by fabiocos** [comment]
assign simulation

**Comment by makortel** [comment]
It looks to me that the `SiStripDigiSimLink_cfi.py` and the `DigiSimLinkProducer` it refers to are both completely unused, so easiest would be to just remove them.

**Comment by fabiocos** [comment]
After the merge of #23644 this issue can be closed
