### ISSUE TITLE
Missing SiPixel2DTemplateDBObjectRcd in test wf 11224.0 11224.6

### ISSUE THREAD

**Issue by fabiocos** [cms-sw/cmssw#23666]
The integration of #23596 is causing crashes in the the tests 11224.0 and 11224.6 with the exception

----- Begin Fatal Exception 23-Jun-2018 17:56:05 CEST-----------------------
An exception of category 'NoRecord' occurred while
   [0] Processing  Event run: 1 lumi: 1 event: 2 stream: 3
   [1] Running path 'digitisation_step'
   [2] Calling method for module MixingModule/'mix'
Exception Message:
No "SiPixel2DTemplateDBObjectRcd" record found in the EventSetup.n
 Please add an ESSource or ESProducer that delivers such a record.
----- End Fatal Exception -------------------------------------------------

**Comment by fabiocos** [comment]
assign alca

**Comment by arunhep** [comment]
@fabiocos this should fix this : https://github.com/cms-sw/cmssw/pull/23667
it got overlooked.. sorry about that.

**Comment by arunhep** [comment]
+1

**Comment by fabiocos** [comment]
Fixed by #23667
