### ISSUE TITLE
How to test a PR with two extra PRs?

### ISSUE THREAD

**Issue by jfernan2** [cms-sw/cmssw#23709]
Dear managers,

according to cms-bot commands:

http://cms-sw.github.io/cms-bot-cmssw-cmds.html

to test a PR with two extra PRs, the command would be (e.g.):

@cmsbuild please test #23686,23257

However, I have tried several combinations on the above sentence (two # no ","  space in between,...) without success (no test triggered) on:

https://github.com/cms-sw/cmssw/pull/23707#issuecomment-400983294

https://github.com/cms-sw/cmssw/pull/23706#issuecomment-400986426

Any hint of what am I missing?

Thanks in advance,
Javi

**Comment by smuzaffar** [comment]
@jfernan2 , the following should have worked
```
@cmsbuild please test with #23686,#23257
```
I am looking in to it

**Comment by smuzaffar** [comment]
`@cmsbuild please test with #23686,#23257` works. I think initially you had used `@cmsbuild please test with #23686,23257` (i.e. without 2nd #) which is correct according to  http://cms-sw.github.io/cms-bot-cmssw-cmds.html but cms-bot is actually looking for 2nd `#` that is why it did not recognize your first comment. After that you edited the comment but as github webhooks are not triggered when one modifies a comment that is why cms-bot did not see your updated comment.

I have updated the documentation http://cms-sw.github.io/cms-bot-cmssw-cmds.html and force cms-bot to checked your PR #23706. tests are running now

**Comment by jfernan2** [comment]
@smuzaffar Can you force #23707 to read the comment again? Thanks

**Comment by smuzaffar** [comment]
you can do it yourself by adding anew comment to that PR (this will trigger the bot to re-read) :-)
