### ISSUE TITLE
Validation/Geometry module: Empty plots on Material Budget scripts 

### ISSUE THREAD

**Issue by vargasa** [cms-sw/cmssw#23734]
`Validation/Geometry/test/MaterialBudget.py` does not extract the content from `matbdg_Tracker.root` file for 2D Histograms `x_vs_z_vs_R`, `l_vs_z_vs_R`. There are some notable differences in some other plots like `l_vs_eta_vs_phi_bw`, `x_vs_z_vs_Rsum` between 10* release and 8* release that need to be addressed

Reproduce the empty plots by running:

```
cd Validation/Geometry/python
cmsRun single_neutrino_cfg.py 
mv single_neutrino_random.root ../test/ && cd ../test/
cmsRun runP_Tracker_cfg.py
mkdir Images && mkdir Figures 
python MaterialBudget.py -s -d Tracker
```

Differences between 10* and 8* releases for the Material Budget plots are shown here:

https://docs.google.com/presentation/d/1jMY1vEe3ZDCUYfbYDP5jy7VvrV2FMaMwUUj4oWDnrxE/edit

Context:
https://twiki.cern.ch/twiki/bin/viewauth/CMS/TrackerMaterialBudgetValidation

I have been working on a solution for this issue and soon will be doing a pull request

**Comment by boudoul** [comment]
Dear @vargasa , could you please let us know the motivation for opening an issue in cmssw - Maybe we can chat directly one of these days to adress it - Thanks.

**Comment by vargasa** [comment]
This is the expected behavior when using `"SAME"` when drawing a [TH2F on top of an empty one](https://root-forum.cern.ch/t/same-option-use-on-th2f-draw/29630/), but as I commented before we can safely remove the `frame` object

**Comment by vargasa** [comment]
Issue fixed on `10_3_0_pre4`
