### ISSUE TITLE
FWCore.PythonUtilities.LumiList  broken in CMSSW_10_2_0_pre6?

### ISSUE THREAD

**Issue by mmusich** [cms-sw/cmssw#23774]
Dear all,
it seems that this statement:
```
lumi_list = LumiList.LumiList(filename ='/afs/cern.ch/cms/CAF/CMSCOMM/COMM_DQM/certification/Collisions18/13TeV/DCSOnly/json_DCSONLY.txt').getVLuminosityBlockRange()
```

doesn't work anymore in `CMSSW_10_2_0_pre6`.

A simpe reproducer is here:

```python
import FWCore.ParameterSet.Config as cms

process = cms.Process("Demo")
process.load("FWCore.MessageService.MessageLogger_cfi")
process.maxEvents = cms.untracked.PSet( input = cms.untracked.int32(10) )

import FWCore.PythonUtilities.LumiList as LumiList

process.source = cms.Source("PoolSource",
                            fileNames = cms.untracked.vstring('file:/afs/cern.ch/cms/Tutorials/TWIKI_DATA/TTJets_8TeV_53X.root')
                            )

lumi_list = LumiList.LumiList(filename ='/afs/cern.ch/cms/CAF/CMSCOMM/COMM_DQM/certification/Collisions18/13TeV/DCSOnly/json_DCSONLY.txt').getVLuminosityBlockRange()
process.source.lumisToProcess = lumi_list

process.Tracer = cms.Service("Tracer")

```

This results in:

```
----- Begin Fatal Exception 11-Jul-2018 09:49:25 CEST-----------------------
An exception of category 'ConfigFileReadError' occurred while
   [0] Processing the python configuration file named ConfFile_cfg.py
Exception Message:
python encountered the error: <type 'exceptions.AttributeError'>
'unicode' object has no attribute 'cppID'
----- End Fatal Exception -------------------------------------------------
```

I've tested in other (pre-)releases and it seems to work up to `CMSSW_10_2_0_pre5`

**Comment by davidlange6** [comment]
hi @mmusich - this config works ok for me in pre6 (but I see the set of lumis in the file read in is {} at this moment.

**Comment by fabiocos** [comment]
@mmusich I confirm what @davidlange6 finds, the cfg runs smoothly up to the end

**Comment by mmusich** [comment]
@fabiocos and @davidlange6 , thanks for checking - indeed it does now, but it didn't early this morning.
I don't know if it is related to any intervention on the file I was trying to open at the time. 
Another worrying point is that the DCS json has suddenly become empty, but that's up to data certification to clarify...

**Comment by boudoul** [comment]
Weird.. can you report to data certification HN please  ? Thanks

**Comment by mmusich** [comment]
Hi @boudoul, done [here](https://hypernews.cern.ch/HyperNews/CMS/get/offline-dqm/797.html).
Anyway I am assuming the code in cmssw is working properly and the problem lied elsewhere, so I am closing the issue.

**Comment by mmusich** [comment]
@fabferro made me notice that in `CMSSW_10_2_0` one can see agin the problem, running the same recipe I reported above, and now (as I speak 1 Aug 2018, 3:12 GVA time) the file I am trying to access is not empty:
```
$ less  /afs/cern.ch/cms/CAF/CMSCOMM/COMM_DQM/certification/Collisions18/13TeV/DCSOnly/json_DCSONLY.txt | wc -l
3795

```

**Comment by fabferro** [comment]
Yes, I'm also having the same problem with a config file of my own, but always coming from a json file.
I'm using 10_2_1 with slc6_amd64_gcc700 architecture.

**Comment by fabferro** [comment]
Yes, I'm also having the same problem with a config file of my own, but always coming from a json file.
I'm using 10_2_1 with slc6_amd64_gcc700 architecture.

**Comment by ericvaandering** [comment]
I'll try to take a look at this as I wrote it originally.

**Comment by Dr15Jones** [comment]
I can reproduce a similar problem directly in python
```python
import FWCore.PythonUtilities.LumiList as LumiList
lumi_list = LumiList.LumiList(filename ='/afs/cern.ch/cms/CAF/CMSCOMM/COMM_DQM/certification/Collisions18/13TeV/DCSOnly/json_DCSONLY.txt').getVLuminosityBlockRange()
print lumi_list
```

**Comment by ericvaandering** [comment]
The source of this problem is the code following https://github.com/cms-sw/cmssw/commit/1c7e3fe48cd3c71887aea76f04337fdbc4152328#diff-970bf0eb3f50feb58cf09f89833b6398L908 

This entire commit is doomed to fail on python2. Python2 has two kinds of strings, *unicode* and *str*. They share a base class called *basestr*. Python3 only has one kind of string called *str*

So in python2, this check is now doing a check against a subclass, not the base class. And for some reason LumiList is generating unicode. But lots of other things could be too.

There is a safer way to do this which is to use the appropriate futurize fixer which fakes a different base class for the python2 case. It's still trouble in some cases, but at least it's better. Maybe you have to run the builtins fixer first? http://python-future.org/automatic_conversion.html#separating-text-from-bytes

**Comment by mmusich** [comment]
I checked that #24168 solves the problem @fabferro FYI.
I am closing the issue.
