### ISSUE TITLE
Residual GEN-only failing test workflows

### ISSUE THREAD

**Issue by fabiocos** [cms-sw/cmssw#23780]
After the revision of the Powheg gridpacks in #23751 and the further fix #23778 (fixing the forgotten wf. 554) by @covarell , we are left with 3 wfs failing for gcc700 architectures: 562, 1360.0, 25210.0 .

They are all based on Madgraph gridpacks, and in all cases the ExternalLHCProducer configuration does not specify a different environment to be used. As these gridpacks need libgfortran.3, they fail because this library is no more available in the gcc700 distribution. Adding, as for other gridpacks, a 7_1_X environment, causes them to run smoothly. So this is not a gcc700 build probnlem but again a configuration problem (in the present way of managing these gridpacks).

@efeyazgan @alberto-sanchez could you please check and fix it? There is no principle reason why we keep getting these failures.

**Comment by fabiocos** [comment]
assign generators

**Comment by fabiocos** [comment]
@alberto-sanchez @efeyazgan is someone taking care of this? Not a top priority, but it is annoying to run tests that are known a priori to be broken...

**Comment by fabiocos** [comment]
@efeyazgan @alberto-sanchez any news here?

**Comment by qliphy** [comment]
@fabiocos  I think  @Saptaparna will give an update soon

**Comment by Saptaparna** [comment]
@fabiocos Updating the gridpacks to the following:
/cvmfs/cms.cern.ch/phys_generator/gridpacks/2017/13TeV/madgraph/V5_2.4.2/exo_diboson/Spin_2/BulkGraviton_ZZ_inclu_narrow_M1200_slc6_amd64_gcc481_CMSSW_7_1_30_tarball.tar.xz

for workflow: 562

and to

/cvmfs/cms.cern.ch/phys_generator/gridpacks/slc6_amd64_gcc481/13TeV/madgraph/V5_2.4.2/tt012j_5f_ckm_NLO_FXFX/v5/tt012j_5f_ckm_NLO_FXFX_tarball.tar.xz

for workflows 1360 and 25210 will fix the issues. I will now make a PR.

**Comment by Saptaparna** [comment]
Created PR that reflects updated path for the gridpacks: https://github.com/cms-sw/cmssw/pull/24183

**Comment by alberto-sanchez** [comment]
PR #24268 resolve this issue

**Comment by alberto-sanchez** [comment]
+1
