### ISSUE TITLE
BPHMonitor causing crashes in IB RelVals

### ISSUE THREAD

**Issue by Dr15Jones** [cms-sw/cmssw#23787]
The BPHMonitor is crashing the workflow 136.86. In all cases we get the log message
```
%MSG-e Root_Error:  BPHMonitor:Dimuon0_HLT_OS TUnixSystem::DispatchSignals()  13-Jul-2018 09:54:37 CEST Run: 315489 Event: 12105717
floating point exception
%MSG
%MSG-e Root_Error:  BPHMonitor:Dimuon0_L3TnP_Jpsi  TUnixSystem::DispatchSignals() 13-Jul-2018 09:54:38 CEST  Run: 315489 Event: 11978417
floating point exception
%MSG
%MSG-e Root_Error:  BPHMonitor:Dimuon0_HLT_OS1 TUnixSystem::DispatchSignals()  13-Jul-2018 09:54:38 CEST Run: 315489 Event: 12002034
floating point exception
%MSG
%MSG-e Root_Error:  BPHMonitor:Dimuon0_Jpsi_OS TUnixSystem::DispatchSignals()  13-Jul-2018 09:54:39 CEST Run: 315489 Event: 12125304
floating point exception
%MSG
```
Which then appears to trigger ROOT's signal handler which then attempts to call 'exit' on multiple threads concurrently which ultimately leads to a crash.

**Comment by Dr15Jones** [comment]
From googling, it appears that if one calls `std::__gcd(a,0)` it will cause a floating point exception on some compilers. So the probably line causing the problem is

https://github.com/cms-sw/cmssw/pull/23738/files#diff-42c75a5176b7504671fd5b71aef014daR1187

Where this call is probably returning 0
https://github.com/cms-sw/cmssw/pull/23738/files#diff-42c75a5176b7504671fd5b71aef014daR1185

**Comment by aboletti** [comment]
Yes, that is a case for which we should have added a control check (@anigamova ). It is curious that in our tests it never appeared.
Should we create an additional PR with an value check, or the merged PR will be reverted and we will need to re-open it with this fixed?

**Comment by Dr15Jones** [comment]
I suggest making a new pull request and tell the bot to run the failing workflow as part of the test.

**Comment by fabiocos** [comment]
@aboletti I need to revert this PR, as we are already tight for 10_2_0. In the meanwhile please provide a revised version with the fix inside, and test it on the failing workflows, as @Dr15Jones suggests

**Comment by Dr15Jones** [comment]
@dan131riley FYI

**Comment by fabiocos** [comment]
@Dr15Jones @aboletti for the time being I revert the PR in #23788 waiting for a fixed replacement to be tested and deployed with more calm

**Comment by smuzaffar** [comment]
looks like this has been fixed. Open a new one if needed.
