### ISSUE TITLE
Migrate legacy modules in DIGI jobs

### ISSUE THREAD

**Issue by davidlange6** [cms-sw/cmssw#23861]
These modules limit our threading performance in DIGI jobs. Could they be migrated to non-legacy types?

MEtoEDMConverter
ecalPacker
siPixelRawData
simEmtfDigis
cscpacker
simDtTriggerPrimitiveDigis
simOmtfDigis
simCaloStage2Digis

**Comment by Dr15Jones** [comment]
See #24052

**Comment by davidlange6** [comment]
Thanks @dr15jones!

**Comment by Dr15Jones** [comment]
See #24057

**Comment by Dr15Jones** [comment]
See #24105

**Comment by Dr15Jones** [comment]
See #24121

**Comment by Dr15Jones** [comment]
See #24145

**Comment by Dr15Jones** [comment]
See #24148 

This is the last one that is showing up as stalling in my testing. `simBmtfDigis` is still stalling, but it is a `one` module with a shared resource so nothing that can be done.

When running the job using `convertToUnscheduled`, I find the following modules are never run:
DMHcalTTPDigis, MEtoEDMConverter, hltFEDSelector, hltOnlineBeamSpot, hltScalersRawToDigi, hltTriggerSummaryRAW, omtfStage2Raw, simHcalTriggerPrimitiveDigis, simMuonGEMPadDigiClusters
