### ISSUE TITLE
Massive failure for "Unable to find plugin 'L1TMuonEndcapParamsRcd@NewProxy' in category 'CondProxyFactory'"

### ISSUE THREAD

**Issue by fabiocos** [cms-sw/cmssw#23873]
In CMSSW_10_3_X_2018-07-19-1100 there is a generalized failure of the IB with the error

----- Begin Fatal Exception 19-Jul-2018 16:40:12 CEST-----------------------
An exception of category 'PluginNotFound' occurred while
   [0] Constructing the EventProcessor
   [1] Constructing ESSource: class=PoolDBESSource label='GlobalTag'
Exception Message:
Unable to find plugin 'L1TMuonEndcapParamsRcd@NewProxy' in category 'CondProxyFactory'. Please check spelling of name.
----- End Fatal Exception -------------------------------------------------

which looks connected with the merge of #23759 , where the L1TMuonEndcapParamsRcd data format has been removed because unused, as replaced by L1TMuonEndCapParamsRcd .

**Comment by fabiocos** [comment]
assign l1

**Comment by fabiocos** [comment]
@rekovic the old format is no more needed, but is this still required for old GTs?

@lpernie @arunhep FYI

**Comment by fabiocos** [comment]
@ggovi FYI

**Comment by rekovic** [comment]
@fabiocos Thanks.
Can you please point me to the log files, so I can identify which workflow(s) crashed, to be able to identify which GT needs to be updated.  

Attn @lpernie @arunhep As Fabio mentioned, we will probably need to update a GT responsible for the crash. Please stay put.

**Comment by fabiocos** [comment]
@rekovic there are more than 400 wfs crashing

https://cmssdt.cern.ch/SDT/html/cmssdt-ib/#/relVal/CMSSW_10_3/2018-07-19-2300?selectedArchs=slc6_amd64_gcc700&selectedFlavors=X&selectedStatus=failed

just pick your favourite one :-)

We verified with @smuzaffar that this went unnoticed because of a weakness in scram (essentially the old plugin from the release was anyway used).

So this PR is referring to online L1 O2O operations, but the cond format is widely used in regular production workflows. I revert temporarily the PR to let the IB clean, then you may propose a revised version of it, we will need to ensure that the test is properly working

**Comment by arunhep** [comment]
looking for the associated global tags containing the removed L1TMuonEndcapParamsRcd, I found thousands of them in the past and also in 10.2.X. I don't think we can just remove the condFormat without knowing where it is consumed.
Only easy solution is what @fabiocos already implemented is to put it back.

**Comment by fabiocos** [comment]
@arunhep thank you for the confirmation, I think this was overlooked in the review and masked by a hole in the testing procedure. I suggest that @rekovic repropose the code update but keeps the old format active.

**Comment by fabiocos** [comment]
@rekovic are you planning to repropose a PR with the discarded code by keeping the old data format?

**Comment by fabiocos** [comment]
This issue was finally fixed, and it can be closed
