### ISSUE TITLE
Compiling *.py with python3

### ISSUE THREAD

**Issue by davidlange6** [cms-sw/cmssw#23970]
The FWCore subsystem is close to compiling all of its *py files with python3. It would be useful to start having the compilation for all packages run as part of IBs and summarized somewhere for experts to see (expecting to have lots of errors for some time...)  

I haven't thought about how technically to do this as we keep the *pyc files together with the source.. [do python3 first, delete all pyc and then proceed with python2?]

**Comment by davidlange6** [comment]
assign core

**Comment by smuzaffar** [comment]
+core
all python modules in cmssw now compile/run with python. For each IB we run python3 compilation ( see `Python3` link on IB page https://cmssdt.cern.ch/SDT/html/cmssdt-ib )
