### ISSUE TITLE
Disagreement between FormulaEvaluator and TFormula/python?

### ISSUE THREAD

**Issue by aminnj** [cms-sw/cmssw#24023]
Hi,

I'm trying to sort out a difference I see in JECs between two jets. I got to the point of comparing function evaluations with two different frameworks (CMSSW with FormulaEvaluator, and a standalone TFormula implementation).

I have an example script below that compares an L1 correction for a jet with (pt=157.2,area=0.5,rho=23.2) using the formula/parameters from `Fall17_17Nov2017_V6_MC_L1FastJet_AK4PFchs`. I tried 10_2 and 9_2_8 and see the same results in both.

The output is
```
formulaevaluator: 0.968545
tformula: 0.969361
python: 0.969361
```

I see a ~0.1% difference between formulaevaluator and tformula/python (the latter two agree). In playing with the numbers before delving into the implementations, I saw between 0.03 and 0.2% (roughly, but I don't remember what random values I put in to get those).

I'm wondering if this is small enough to be expected (rounding issues or fast approximations) or not. Also, I hope I'm not doing something stupid!

Thanks,
Nick

```cpp
#include "CondFormats/JetMETObjects/interface/SimpleJetCorrector.h"

void fevaltest() {

  gSystem->Load("libFWCoreFWLite.so");
  FWLiteEnabler::enable();

  double x[4] = { 157.2, 0.5, 23.2 };
  double par[3] = { 1.4, 0.453645, -0.015665 };

  TString formula = "max(0.0001,1-y*([1]*(z-[0])*(1+[2]*log(x/30.)))/x)";

  TString formula_forpy = "max(0.0001,1-[y]*([1]*([z]-[0])*(1+[2]*__import__('math').log([x]/30.)))/[x])";
  formula_forpy = formula_forpy.ReplaceAll("[x]","157.2") \
                  .ReplaceAll("[y]","0.5")
                  .ReplaceAll("[z]","23.2")
                  .ReplaceAll("[0]","1.4")
                  .ReplaceAll("[1]","0.453645")
                  .ReplaceAll("[2]","-0.015665");

  reco::FormulaEvaluator mFunc(formula.Data());
  float fe = mFunc.evaluate(reco::formula::ArrayAdaptor(x,3), reco::formula::ArrayAdaptor(par,3) );
  std::cout <<  "fe: " << fe <<  std::endl;

  TFormula f1("f1",formula);
  f1.SetParameter(0, par[0]);
  f1.SetParameter(1, par[1]);
  f1.SetParameter(2, par[2]);
  float tf = f1.Eval(x[0],x[1],x[2]);
  std::cout <<  "tf: " << tf <<  std::endl;

  TPython p;
  float py = p.Eval(formula_forpy);
  std::cout <<  "py: " << py <<  std::endl;

}
```

**Comment by kpedro88** [comment]
assign core
attn @aperloff (in case you remember something about this)

**Comment by davidlange6** [comment]
which release are you using?

**Comment by aminnj** [comment]
Edited them into the original post too late. I am using 9_2_8, but I tried going to 10_2_0_pre6 and see the same thing.

**Comment by Dr15Jones** [comment]
If I remember correctly, in the past the differences were very large, not a few fractions of a percent.

**Comment by Dr15Jones** [comment]
Looking at the test code, I see that all the tests are required to match to better than 1 part in a million:

https://github.com/cms-sw/cmssw/blob/f4ffc8bffbbfe88fffe91cf5dd8849ea5c6af621/CommonTools/Utils/test/testFormulaEvaluator.cc#L33

**Comment by Dr15Jones** [comment]
So I found that if I changed the expression to
```
max(0.0001,1-y/x*([1]*(z-[0])*(1+[2]*log(x/30.))))
```
i.e. I move the division by x earlier, then I get the expected answer. So definitely looks like a bug, not a rounding issue.

**Comment by aminnj** [comment]
Wanted to also see for myself if it was a rounding issue before you found the x division modification, so I plotted differences in pT-eta (also to see if it even matters at all) and for low pT, high eta jets, the correction rises to a few %. Even 100% in some rare circumstances where the max(0.0001, ...) gets triggered for FormulaEvaluator but not TFormula.

[clipped to 10%](http://uaf-10.t2.ucsd.edu/~namin/dump/issue_24023/plot_clipped.png) & [no range restriction](http://uaf-10.t2.ucsd.edu/~namin/dump/issue_24023/plot_unclipped.png)

**Comment by Dr15Jones** [comment]
So I have a fix. Based on what I found, the following will also fail `"2*(3*4*5)/6"`. The problem was how precendence order mixed with parenthesis. This is the first case where the operations inside the parenthesis have the same precidence order as those directly outside.

**Comment by Dr15Jones** [comment]
See #24049

**Comment by Dr15Jones** [comment]
So now the question is, to which release should the fix be backported?

**Comment by kpedro88** [comment]
@aminnj which JECs use this kind of expression? We want to stop making 10_1 releases as soon as possible, so the major question is whether it should be included in 9_4.

**Comment by aminnj** [comment]
Grepping through a bunch of text files for the L1 formulas, I see [1]. The formula changes between Summer2016 and Fall17. The Summer2016 syntax shows agreement between FormulaEvaluator and TFormula. I don't have my hands on anything newer than Fall17 V6 though.


[1]
```
Fall17_17Nov2017B_V6_DATA/Fall17_17Nov2017B_V6_DATA_L1FastJet_AK4PFchs.txt:{1         JetEta   3   JetPt   JetA    Rho    max(0.0001,1-y*([1]*(z-[0])*(1+[2]*log(x/30.)))/x)   Correction   L1FastJet}
Fall17_17Nov2017C_V6_DATA/Fall17_17Nov2017C_V6_DATA_L1FastJet_AK4PFchs.txt:{1         JetEta   3   JetPt   JetA    Rho    max(0.0001,1-y*([1]*(z-[0])*(1+[2]*log(x/30.)))/x)   Correction   L1FastJet}
Fall17_17Nov2017D_V6_DATA/Fall17_17Nov2017D_V6_DATA_L1FastJet_AK4PFchs.txt:{1         JetEta   3   JetPt   JetA    Rho    max(0.0001,1-y*([1]*(z-[0])*(1+[2]*log(x/30.)))/x)   Correction   L1FastJet}
Fall17_17Nov2017E_V6_DATA/Fall17_17Nov2017E_V6_DATA_L1FastJet_AK4PFchs.txt:{1         JetEta   3   JetPt   JetA    Rho    max(0.0001,1-y*([1]*(z-[0])*(1+[2]*log(x/30.)))/x)   Correction   L1FastJet}
Fall17_17Nov2017F_V6_DATA/Fall17_17Nov2017F_V6_DATA_L1FastJet_AK4PFchs.txt:{1         JetEta   3   JetPt   JetA    Rho    max(0.0001,1-y*([1]*(z-[0])*(1+[2]*log(x/30.)))/x)   Correction   L1FastJet}
Fall17_17Nov2017_V4_MC/Fall17_17Nov2017_V4_MC_L1FastJet_AK4PFchs.txt:{1               JetEta   3   JetPt   JetA    Rho    max(0.0001,1-y*([1]*(z-[0])*(1+[2]*log(x/30.)))/x)   Correction   L1FastJet}
Fall17_17Nov2017_V6_MC/Fall17_17Nov2017_V6_MC_L1FastJet_AK4PFchs.txt:{1               JetEta   3   JetPt   JetA    Rho    max(0.0001,1-y*([1]*(z-[0])*(1+[2]*log(x/30.)))/x)   Correction   L1FastJet}
Spring16_25nsV10BCD_DATA/Spring16_25nsV10BCD_DATA_L1FastJet_AK4PFchs.txt:{1           JetEta   3   Rho     JetPt   JetA   max(0.0001,1-z*([0]+([1]*x)*(1+[2]*log(y)))/y)       Correction   L1FastJet}
Spring16_25nsV10E_DATA/Spring16_25nsV10E_DATA_L1FastJet_AK4PFchs.txt:{1               JetEta   3   Rho     JetPt   JetA   max(0.0001,1-z*([0]+([1]*x)*(1+[2]*log(y)))/y)       Correction   L1FastJet}
Spring16_25nsV10F_DATA/Spring16_25nsV10F_DATA_L1FastJet_AK4PFchs.txt:{1               JetEta   3   Rho     JetPt   JetA   max(0.0001,1-z*([0]+([1]*x)*(1+[2]*log(y)))/y)       Correction   L1FastJet}
Spring16_25nsV10_MC/Spring16_25nsV10_MC_L1FastJet_AK4PFchs.txt:{1                     JetEta   3   Rho     JetPt   JetA   max(0.0001,1-z*([0]+([1]*x)*(1+[2]*log(y)))/y)       Correction   L1FastJet}
Spring16_25nsV10p2_DATA/Spring16_25nsV10p2_DATA_L1FastJet_AK4PFchs.txt:{1             JetEta   3   Rho     JetPt   JetA   max(0.0001,1-z*([0]+([1]*x)*(1+[2]*log(y)))/y)       Correction   L1FastJet}
Summer16_23Sep2016BCDV3_DATA/Summer16_23Sep2016BCDV3_DATA_L1FastJet_AK4PFchs.txt:{1   JetEta   3   Rho     JetPt   JetA   max(0.0001,1-z*([0]+([1]*x)*(1+[2]*log(y)))/y)       Correction   L1FastJet}
Summer16_23Sep2016BCDV4_DATA/Summer16_23Sep2016BCDV4_DATA_L1FastJet_AK4PFchs.txt:{1   JetEta   3   Rho     JetPt   JetA   max(0.0001,1-z*([0]+([1]*x)*(1+[2]*log(y)))/y)       Correction   L1FastJet}
Summer16_23Sep2016EFV3_DATA/Summer16_23Sep2016EFV3_DATA_L1FastJet_AK4PFchs.txt:{1     JetEta   3   Rho     JetPt   JetA   max(0.0001,1-z*([0]+([1]*x)*(1+[2]*log(y)))/y)       Correction   L1FastJet}
Summer16_23Sep2016EFV4_DATA/Summer16_23Sep2016EFV4_DATA_L1FastJet_AK4PFchs.txt:{1     JetEta   3   Rho     JetPt   JetA   max(0.0001,1-z*([0]+([1]*x)*(1+[2]*log(y)))/y)       Correction   L1FastJet}
Summer16_23Sep2016GV3_DATA/Summer16_23Sep2016GV3_DATA_L1FastJet_AK4PFchs.txt:{1       JetEta   3   Rho     JetPt   JetA   max(0.0001,1-z*([0]+([1]*x)*(1+[2]*log(y)))/y)       Correction   L1FastJet}
Summer16_23Sep2016GV4_DATA/Summer16_23Sep2016GV4_DATA_L1FastJet_AK4PFchs.txt:{1       JetEta   3   Rho     JetPt   JetA   max(0.0001,1-z*([0]+([1]*x)*(1+[2]*log(y)))/y)       Correction   L1FastJet}
Summer16_23Sep2016HV3_DATA/Summer16_23Sep2016HV3_DATA_L1FastJet_AK4PFchs.txt:{1       JetEta   3   Rho     JetPt   JetA   max(0.0001,1-z*([0]+([1]*x)*(1+[2]*log(y)))/y)       Correction   L1FastJet}
Summer16_23Sep2016HV4_DATA/Summer16_23Sep2016HV4_DATA_L1FastJet_AK4PFchs.txt:{1       JetEta   3   Rho     JetPt   JetA   max(0.0001,1-z*([0]+([1]*x)*(1+[2]*log(y)))/y)       Correction   L1FastJet}
Summer16_23Sep2016V3_MC/Summer16_23Sep2016V3_MC_L1FastJet_AK4PFchs.txt:{1             JetEta   3   Rho     JetPt   JetA   max(0.0001,1-z*([0]+([1]*x)*(1+[2]*log(y)))/y)       Correction   L1FastJet}
Summer16_23Sep2016V4_MC/Summer16_23Sep2016V4_MC_L1FastJet_AK4PFchs.txt:{1             JetEta   3   Rho     JetPt   JetA   max(0.0001,1-z*([0]+([1]*x)*(1+[2]*log(y)))/y)       Correction   L1FastJet}
Summer16_25nsV5_MC/Summer16_25nsV5_MC_L1FastJet_AK4PFchs.txt:{1                       JetEta   3   Rho     JetPt   JetA   max(0.0001,1-z*([0]+([1]*x)*(1+[2]*log(y)))/y)       Correction   L1FastJet}
```

**Comment by Dr15Jones** [comment]
Alternatively, the formulas could be changed from 
```y*([1]*(z-[0])*(1+[2]*log(x/30.)))/x```

to

```y*[1]*(z-[0])*(1+[2]*log(x/30.))/x```

or

```y/x*([1]*(z-[0])*(1+[2]*log(x/30.)))```

which are identical mathematically and avoid the bug in FormulaEvaluator.

**Comment by aperloff** [comment]
Changing this in the JEC side would require both a change in the text files from the git repo as well as the uploading of new payloads to the database and new global tags. I'm not sure which is easier, that or backporting the fix to CMSSW. Either way, the issue should be reported in a JetMET/JERC meeting if it hasn't already.

**Comment by karavdin** [comment]
Hi all,
We'll "fix" txt files for the next Fall17 JEC release. Please make sure issue is fixed in cmssw in 10_2 and if possible in 10_1. 
Anastasia (JERC convener)

**Comment by kpedro88** [comment]
@karavdin we are generally moving on from 10_1_X at this point, so I don't plan to merge further backports.

**Comment by karavdin** [comment]
@kpedro88, ok thank for the info.

**Comment by karavdin** [comment]
For completeness here is the list of JEC, which might be affected (only publicly released and or injected in GTs):
Summer16_07Aug2017_V11 for 2016 legacy (80_X, 94_X)
Fall17_17Nov2017_V6 for 2017 ReReco (94_X, 10_1_X)
Fall17_17Nov2017_V8 for 2017 ReReco (94_X, 10_X_X)
We'll create version with "fixed" txt files as soon as possible and request new GTs.

Many thanks to @aminnj for spotting it and @aperloff for pointing us to this discussion. And of course @Dr15Jones for the fix in cmssw.

Anastasia

**Comment by aminnj** [comment]
Hi all,

Thank you very much for the fix+follow up!

From the user's perspective, all that is needed to get fixed quantities that depend on L1 (e.g., corrected pfMET) is to re-run on miniAOD with the latest global tags when they are ready. Is this correct, or does something need to happen upstream first?

Thanks,
Nick

**Comment by karavdin** [comment]
Hi Nick, 
Yes, user will have to re-apply JEC on miniAOD and make sure all relevant things, like MET correction, are re-done. 

Cheers, 
Anastasia

**Comment by aminnj** [comment]
Thanks for the clarification, Anastasia

**Comment by slava77** [comment]
in https://github.com/cms-sw/cmssw/issues/24023#issuecomment-407806447
> clipped to 10% & no range restriction
@aminnj  please post also a version clipped at 5 or 3% (it looks like the discrepancy persists even for pt> 20 GeV.

Regarding https://github.com/cms-sw/cmssw/issues/24023#issuecomment-409100520
> Yes, user will have to re-apply JEC on miniAOD and make sure all relevant things, like MET correction, are re-done.
what is included in the recipe in this case? I'm trying to understand if the cost of rerunning is similar to rerunning miniAOD and if everything can even be [re]done consistently. IIRC jet PU ID depends on corrected jets as well as muon jet ptrel and MVA. What about the b-tags made in miniAOD (deep\*).

**Comment by kpedro88** [comment]
@slava77 
The JetMET POG provides a Python function `updateJetCollection()`. The operations to update the JECs are not too intensive in CPU. Similarly, there is a function `runMetCorAndUncFromMiniAOD()` to propagate the JECs to the MET, which is also not too CPU intensive.

I typically haven't worried about the other quantities you mentioned. The b-tagging uses uncorrected jet info, as far as I know.

**Comment by slava77** [comment]
IIUC, only corrected jets with pt> 10 GeV are saved in miniAOD.
Considering the size of the discrepancies in http://uaf-10.t2.ucsd.edu/%7Enamin/dump/issue_24023/plot_unclipped.png
is it obvious that we can even use jets in a consistent way with pt~< 20 GeV?

**Comment by kpedro88** [comment]
That's true. Generally, I think JetMET does not recommend use of very low pT jets in analysis. (It's also possible to recluster the packed PF candidates to get a full jet collection, modulo floating point differences, but this is certainly more CPU intensive than the other operations I mentioned in the previous comment. Though, much less CPU intensive than all the massive deep NNs that CMS is starting to recommend.)

**Comment by makortel** [comment]
> Though, much less CPU intensive than all the massive deep NNs that CMS is starting to recommend.

Just to check that I understood correctly, the inference of these NNs is slower than jet clustering?

**Comment by slava77** [comment]
On 8/1/18 6:33 AM, Matti Kortelainen wrote:
>     Though, much less CPU intensive than all the massive deep NNs that
>     CMS is starting to recommend.
> 
> Just to check that I understood correctly, the inference of these NNs is
> slower than jet clustering?
> 
> —

as an example from 136.8311:
- pfDeepFlavourJetTagsSlimmedDeepFlavour is 154 ms/ev
- ca8PFJetsCHSprunedForBoostedTaus is 48 ms/ev
- ak8PFJetsPuppi is 29 ms/ev
..
well
-  puppi and puppiNoLep add up to 340 ms/ev

**Comment by kpedro88** [comment]
Yep, that has been my observation. The [DeepAK8 presentation](https://indico.cern.ch/event/746010/contributions/3083337/attachments/1694525/2727184/deepAK8_cmssw_integration_RECOAT_20180727_hqu.pdf) from the last reco meeting compares DeepAK8, DeepDoubleB, and DeepFlavour, and they are all pretty slow.

@slava77 is that even after I reduced the puppi CPU usage?

**Comment by slava77** [comment]
> @slava77 is that even after I reduced the puppi CPU usage?

this was in CMSSW_10_2_0

**Comment by kpedro88** [comment]
Ah, I bet it includes puppi for AK4 jets (I usually just check for AK8 jets, there are fewer of those).

**Comment by kpedro88** [comment]
Never mind, puppi is run before the clustering, so it is indeed slower.

**Comment by aminnj** [comment]
Slava, I updated my comment above with some more zoomed in plots.

**Comment by slava77** [comment]
On 8/1/18 9:06 AM, Nick Amin wrote:
> Slava, I updated my comment above with some more zoomed in plots.
> 

Thanks, Nick.
from
http://uaf-10.t2.ucsd.edu/%7Enamin/dump/issue_24023/plot_pt25_eta2p5.png
IIUC, for pt>25 the discrepancy is within just 0.1%.

**Comment by Dr15Jones** [comment]
+1

**Comment by fabiocos** [comment]
the code integrated in 10_3_X/10_2_X is fixing the problem, and a corresponding fix is available for 9_4_X (although its integration breaking backward compatibility should be better made at the next JES update, if any)
