### ISSUE TITLE
StdException in HGCalSimHitValidation

### ISSUE THREAD

**Issue by fabiocos** [cms-sw/cmssw#24152]
In CMSSW_10_3_X_2018-07-31-2300 a reporducible StdException in HGCalSimHitValidation appears in workflow 24034.0

https://cmssdt.cern.ch/SDT/cgi-bin/logreader/slc6_amd64_gcc700/CMSSW_10_3_X_2018-07-31-2300/pyRelValMatrixLogs/run/24034.0_TTbar_14TeV+TTbar_14TeV_TuneCUETP8M1_2023D28_GenSimHLBeamSpotFull14+DigiFullTrigger_2023D28+RecoFullGlobal_2023D28+HARVESTFullGlobal_2023D28/step3_TTbar_14TeV+TTbar_14TeV_TuneCUETP8M1_2023D28_GenSimHLBeamSpotFull14+DigiFullTrigger_2023D28+RecoFullGlobal_2023D28+HARVESTFullGlobal_2023D28.log#/

----- Begin Fatal Exception 01-Aug-2018 09:36:51 CEST-----------------------
An exception of category 'StdException' occurred while
   [0] Processing  Event run: 1 lumi: 1 event: 2 stream: 2
   [1] Calling method for module HGCalSimHitValidation/'hgcalSimHitValidationHEB'
Exception Message:
A std::exception was thrown.
vector::_M_range_check: __n (which is 16) &gt;= this-&gt;size() (which is 16)
----- End Fatal Exception -------------------------------------------------

This problem is introduced by the merge of #24136 , that affects the HGCal validation package.

**Comment by fabiocos** [comment]
assign dqm,upgrade

**Comment by fabiocos** [comment]
@bsunanda your update seems to have a problem with geometry scenario D28, which is not tested by default during the PR scrutiny. Could you please have a look and provide a fix? I would like to avoid delaying 10_3_0_pre1 because of this issue

**Comment by bsunanda** [comment]
Hi Fabio

I am taking a look. We should try to resolve this as soon as possible. Regards

Sunanda
________________________________

**Comment by kpedro88** [comment]
@bsunanda I think this is the same problem I hacked around in some other validation modules:
https://github.com/cms-sw/cmssw/commit/e5bb5f9b177f232f66579109c4a5f294c7f8bbd5

I can propagate this hack to `HGCalSimHitValidation`, but we really need someone to take a deep look at the HGCal validation code for the new geometry.

**Comment by kpedro88** [comment]
See #24158

**Comment by bsunanda** [comment]
@fabiocos Hope PR #24160 will fix this issue. It is under test now

**Comment by fabiocos** [comment]
#24160 has been merged. As far as I can see this is a temporary solution, but for the short term it helps not to discard the whole development
