### ISSUE TITLE
Add ExternalWork-like mechanism for ESProducers

### ISSUE THREAD

**Issue by makortel** [cms-sw/cmssw#24185]
In general transferring EventSetup data to an accelerator device may be done asynchronously (this is the case with CUDA), so we could gain something if ESProducer itself could have two steps like in ExternalWork for EDProducers. Essentially the first step (acquire) would initiate the transfers to the device (or possibly kernels as well), and the second step (produce) would get run after the asynchronous work finishes, which then signals the framework that the ESProduct is ready to be consumed.

In the current CUDA prototype the asynchronous behavior is achieved by calling code passing CUDA stream to a wrapper ESProduct, which then queues the transfers to the CUDA stream. CUDA itself then guarantees that the transferred data is available for the first kernel queued after the transfers. The downside of this approach is that it requires checks and CPU-side synchronization (in the wrapper ESProduct) for the transfer to happen only once.

@Dr15Jones @wddgit

**Comment by Dr15Jones** [comment]
assign core

**Comment by fwyzard** [comment]
> In general transferring EventSetup data to an accelerator device may be done asynchronously (this is the case with CUDA), so we could gain something if ESProducer itself could have two steps like in ExternalWork for EDProducers. Essentially the first step (acquire) would initiate the transfers to the device (or possibly kernels as well), and the second step (produce) would get run after the asynchronous work finishes, which then signals the framework that the ESProduct is ready to be consumed.

I think I understand the proposal, but I do not understand one part: what would the framework do between the "ES-aquire" and "ES-produce" method calls ?
AFAIK, an ESProducer is requested to update its product only when the new one is needed, and as soon as it is needed (whenever an e.g. EDProducer gets it).
Unless the same EDProducer is trying to get multiple ESProducts, what available tasks would be available at the same time ?

**Comment by makortel** [comment]
To me the current "GPU wrapper" layer in GPU ESProducts feels a bit nuisance, so I'd like to remove it (or at least to explore what that would require). But then there would be no way to pass a CUDA stream to the piece of code transferring the data from CPU to GPU (unless we make the `EventSetup` itself aware of CUDA). So the next simplest would be for ESProducer to transfer the data (to all devices). Currently it would have to `cudaStreamSynchronize()` before returning the product. If the transfers take long, framework could do some other work in between.

I guess my pondering above essentially requires using unified memory for CUDA ESProducts. With manual memory management I don't have good ideas how to avoid the wrapper layer (without making the `EventSetup` system inherently CUDA aware).

**Comment by makortel** [comment]
It occurred to me (some time ago already) that this feature is actually not really needed. We can just queue the transfers to all devices (in separate streams) from the ESProducer and use similar CUDA event + `cudaStreamWaitEvent()` trick in the consumers as we do with `cms::cuda::Product`. (and I have a private prototype)

I'll however leave the issue open until the support actually lands to CMSSW master.

**Comment by makortel** [comment]
https://github.com/cms-sw/cmssw/pull/39428 revives the interest in this feature. While my earlier comment in https://github.com/cms-sw/cmssw/issues/24185#issuecomment-582027769 still technically holds, the downside of that approach is that every consuming module has to check for the completion of the data transfer on every event, which is against the design principle of the EventSetup system that the consumer can access the data products without any further checks.

**Comment by makortel** [comment]
Done in https://github.com/cms-sw/cmssw/pull/40798.

**Comment by makortel** [comment]
Really done in https://github.com/cms-sw/cmssw/pull/41001

**Comment by makortel** [comment]
+core
