### ISSUE TITLE
Switch UUID generation to random

### ISSUE THREAD

**Issue by bbockelm** [cms-sw/cmssw#24181]
The current UUID generation technique:

https://github.com/cms-sw/cmssw/blob/09c3fce6626f70fd04223e7dacebf0b485f73f54/FWCore/Utilities/src/Guid.cc#L29

causes the UUID to be based on the MAC address and a relatively fine-grained timestamp, assuming a lot of the randomness comes from the MAC.

Unfortunately, Docker reuses the same MAC for containers -- meaning that all worker nodes at FNAL and all worker nodes at Nebraska appear have the same MAC.  Thus, the only randomness in the system is from the 100ns-accuracy timestamp.

As more sites switch to Docker, we are seeing non-unique GUIDs more often.  Can we switch to using `uuid_generate_random` from libuuid?

(If so, I'd like to request a backport to all active branches)

Issue originally came up here: https://github.com/dmwm/WMCore/issues/8714

**Comment by kpedro88** [comment]
assign core

**Comment by Dr15Jones** [comment]
See ##24246

**Comment by bbockelm** [comment]
@Dr15Jones - assuming that passes unit tests, what branches should we backport to?

**Comment by fabiocos** [comment]
@Dr15Jones @bbockelm we are about to start a massive production campaign with 10_2_X, so a backport there would be for sure beneficial

**Comment by bbockelm** [comment]
@Dr15Jones - work seems done, no?  Can we close out this ticket?

**Comment by Dr15Jones** [comment]
+1

**Comment by Dr15Jones** [comment]
@bbockelm only you can close this

**Comment by bbockelm** [comment]
Ah, didn't realize that.  Closing now.
