### ISSUE TITLE
Create a product alias functionality with ordered fallback mechanism

### ISSUE THREAD

**Issue by makortel** [cms-sw/cmssw#24188]
One way to incorporate chains of algorithms using accelerators would be to
* one EDProducer for each algorithm for each device type, and
   * e.g. a CPU producer, CUDA producer, FPGA producer
* organize these producers into Paths per device type with the first module being an EDFilter deciding whether the algorithms for that device type should run or not
    * e.g. one Path for CPU, one Path for CUDA, one Path for FPGA etc, for that chain of modules

In order to keep the downstream (e.g. DQM) unaware on the details how an event product was produced, we'd need something that conditionally aliases a product label to the actual producer that was run. Example:
```python
process.fooCPU = cms.EDProducer("FooProducerCPU")
process.fooCUDA = cms.EDProducer("FooProducerCUDA")
process.foo = # something creating an alias to fooCUDA if it was produced, otherwise to fooCPU
```
(the mechanism of how either `fooCUDA` or `fooCPU` runs is to be discussed elsewhere)

Existing constructs that might be used (and some reasons why they don't work well)
* EDAlias
   * can create an alias from `foo` to `bar`, but not from `foo` to "one of these possibilities"
   * can not be easily extended to support ordered list while keeping the same configuration interface (as the keyword arguments get delivered via `dict`)
* EDProducer
   * requires a separate EDProducer implementation for each product type (leading to lots of boilerplate)
   * requires copying (performance impact)
   * implies prefetching of all inputs

What the new construct would have to do
* create an alias as EDAlias does (no copies)
* take the alias-to as an ordered list
   * take the first item, try to prefetch, if succeeds (i.e. product is found), create the alias to that
   * if prefetch didn't succeed, try the next item etc.
   * if none of the prefetches succeeded, lead to `ProductNotFound` exception to be thrown
* as indicated in above, it would make life easier elsewhere if unnecessary prefetching could be avoided

Below is a sketch of how the configuration could look like (enhancing the EDAlias syntax)
```python
process.foo = cms.EDFallback(
    cms.PSet(fooCUDA = cms.VPSet(cms.PSet(type="SiPixelClusteredmNewDetSetVector"))),
    cms.PSet(fooCPU = cms.VPSet(cms.PSet(type="SiPixelClusteredmNewDetSetVector")))
)
```
(suggestions how make it less ugly are welcome)

@Dr15Jones @wddgit

**Comment by makortel** [comment]
I don't know if it is possible, or if there would be any dangerous implications, but from user side the configuration would greatly simplify if the product instance label and the product type could be omitted. The configuration could then be simply something along
```python
process.foo = cms.EDFallback("fooCUDA", "fooCPU")
```

I can imagine that a case where `fooCUDA` and `fooCPU` would produce different sets of products, this simplification could lead to "interesting" behaviour.

**Comment by Dr15Jones** [comment]
assign core

**Comment by fwyzard** [comment]
How would the new system deal with the cases where on different paths (e.g. CUDA vs CPU) different modules produce different combinations of products ?
E.g., on the CPU we might have
  - `unpacker` module producing uncalibrated rechits (type `RecHits`, name `unpacker`, empty label)
  - `calbrator` module producing calibrated rechits (type `RecHits`, name `calibrator`, empty label)
  - `tracker` module producing tracks (type `Tracks`, name `tracker`, empty label) and filtered tracks (type `Tracks`, name `tracker`, label `filtered`)
while on the GPU we might have
  - a `gpuUnpacker` producing both uncalibrated (type `RecHits`, name `gpuUnpacker`, empty label) and calibrated (type `RecHits`, name `unpacker`, label `calibrated`) rechits
  - a `gpuTracker` producing tracks (type `Tracks`, name `gpuTracker`, empty label)
  - a `gpuTrackFilter` producing filtered tracks (type `Tracks`, name `gpuTrackFilter`, empty label)

?

The aliasing mechanism would need to be able to map
  - `gpuUnpacker` --> `unpacker`
  - `gpuUnpacker:calibrated` --> `calbrator`
  - `gpuTracker` --> `tracker`
  - `gpuTrackFilter` --> `tracker::filtered`

.

**Comment by fwyzard** [comment]
If we want to minimise the impact on the existing configurations, it is likely we do not want to rename the CPU modules. In this case the construct that creates the alias cannot have the same name as the original label. That is, the example above is more  likely to be
```
process.foo = cms.EDProducer("FooProducer")
process.fooCUDA = cms.EDProducer("FooProducerCUDA")
process.fooAlternative = # something creating an alias from "fooCUDA" to "foo" if it was produced
```

It could help keep the configurations readable if the alternatives could be put in a `Path` or `Task` as well:
```
process.runOnGPU = # something that decides whether to run on the GPU or not

process.foo = cms.EDProducer("FooProducer")
process.path = cms.Path( ~ process.runOnGPU + process.foo )

process.fooCUDA = cms.EDProducer("FooProducerCUDA")
process.fooAlternative = # something creating an alias from "fooCUDA" to "foo" if it was produced
process.pathCUDA = cms.Path( process.runOnGPU + process.fooCUDA + process.fooAlternative )
```

**Comment by fwyzard** [comment]
An other possibility could be to allow an `EDProducer` to set up the aliases itself.
That is, in the examples above, we could have `fooCUDA` ask the framework to make (some of) its products available under a different name (`foo`).

**Comment by fwyzard** [comment]
The main problem I see with all these approaches is that the decision whether to set the alias / alternative or not, would depend on a decision done at the event level (based on an EDFilter result, or checking if a collection has been produced).

Can the event model support this ?

**Comment by makortel** [comment]
@fwyzard

> If we want to minimise the impact on the existing configurations, it is likely we do not want to rename the CPU modules

I agree that would be nice. By "minimising impact" do you refer to the case of cloning modules, or do you have something else in mind?

> That is, in the examples above, we could have `fooCUDA` ask the framework to make (some of) its products available under a different name (`foo`).

So we'd need the framework to allow a module (or other "entity") to insert a product with label differing from the module/entity label in the configuration. I don't know how deep changes would be needed, maybe @Dr15Jones could comment?

Purely from the configuration side I'm concerned on how to find all modules/entities that contribute to a product label `foo` (by `git grep`, from the output of `edmConfigDump`, and from the output of `edmProvDump`).

Anyway, I fully agree that it is this coupling ("product label" = "module label") which is causing problems. And not only in the context of GPUs, but at some level already with
* replacing an EDProducer with a selector EDProducer: product label stays the same, but all downstream cloners have to change their source of cloning
* `mix` vs `mixData` for digi products in premixing

**Comment by makortel** [comment]
@fwyzard 
> The main problem I see with all these approaches is that the decision whether to set the alias / alternative or not, would depend on a decision done at the event level (based on an EDFilter result, or checking if a collection has been produced).

The dynamic nature of the decision (of the device type, e.g. GPU vs CPU) does indeed cause some headache. My feeling is that whether or not we really need it is a somewhat strategic decision. And even if ditching it would make this specific issue irrelevant, I'm not sure if it would save us from all configuration headache.

I mean, if we choose the device type at configuration level, an obvious candidate for that is the `cms.Modifier`. But that won't really help for the cloning issue, as very likely the legacy CPU producer and the "fromCUDA" producer have different configuration parameters, so all the cloners would anyway have to be migrated to be aware of the CPU+CUDA alternatives.

> Can the event model support this ?

Could you be more specific?

One potential problem I see is in the product ID. AFAIK the current `EDAlias` has the same product ID as the "aliased-to" product. So what would happen if the alias has two possible sources? Does the product ID change from event to event? Or does the aliasing create a new product ID that is the same for all events?

**Comment by makortel** [comment]
Superseded by #25439.
