### ISSUE TITLE
Add a mechanism to execute a Task conditionally

### ISSUE THREAD

**Issue by makortel** [cms-sw/cmssw#24190]
One way to organize modules using accelerators to mutually exclusive chains (e.g. CPU, CUDA, FPGA) with dynamic decision on which chain to execute is to create a Path for each chain with a filter at the beginning doing the decision (see also #24188). A downside of inserting EDProducers in Paths is that they will be always run (unless the filter decides otherwise) even if there are no modules asking for their output products. And possibly worse, with `convertToUnscheduled()` the EDProducers are removed from the Paths leading them to get run regardless of the filter decision.

One way to circumvent the aforementioned issues would be to add an ability to a Task to be executed only if a given Path(s) has succeeded. In that case, only the filter would be left in the Path, and the EDProducers would be organized in Tasks (one Task per chain, i.e. e.g. CPU, CUDA, FPGA) that depend on the decision of the Path. These tasks would then be included in other (unconditional) Tasks and eventually get associated to one of the "top-level" Paths (e.g. `reconstruction_step`).

@Dr15Jones @wddgit

**Comment by Dr15Jones** [comment]
assign core

**Comment by makortel** [comment]
> In principle, the EDProducers on a path could still run on demand (based on their dependencies).

My understanding is that EDProducers on a path are not run on demand, but always (unless there is a failing filter preceding it/them). So unless that is changed, we need something else.

**Comment by makortel** [comment]
Superseded by #25439.

**Comment by Dr15Jones** [comment]
+1
