### ISSUE TITLE
How to deal with arbitrary Paths in cff files in cmsDriver/ConfigBuilder?

### ISSUE THREAD

**Issue by makortel** [cms-sw/cmssw#24193]
One prototype for including accelerator algorithms that we are exploring in patatrack (https://github.com/cms-patatrack/cmssw/pull/100) would require defining Paths in `cff` configuration files (see also #24188 and #24190). This approach clashes with the cmsDriver/ConfigBuilder configuration generation. Those insert an explicit `cms.Schedule` in the final configuration file that then dictates which Paths are run.

If we start to add Paths in intermediate `cff` configs, we need to somehow communicate the existence of these Paths to ConfigBuilder so that it can add them to the `Schedule`. (easiest would be to just hardcode them in ConfigBuilder).

Alternative would be to remove the explicit `cms.Schedule` from the configuration and thus run all Paths that are defined. Obviously this implies rewriting the parts of ConfigBuilder dealing with `Schedule` (especially for Alca and Skims), and possibly some cleanup/reorganization of some configuration fragments.

In the unscheduled, dependence-driven mindset dropping the explicit `Schedule` would feel more natural.

@Dr15Jones @wddgit

**Comment by Dr15Jones** [comment]
assign core

**Comment by fwyzard** [comment]
I have been writing for a while  how to try and support this with the use of a `ProcessFragment`, when my laptop badly crashed :-(

So, quick summary:
  - if the cff files put their configuration in a `ProcessFragment` instead of their top level namespace, they can define also a Schedule
  - process.extend should be taught to merge a Schedule instead of replacing it

**Comment by makortel** [comment]
@fwyzard Thanks for the suggestion, I'd like to learn a bit more how it would work with `ProcessFragment`.

How is `ProcessFragment` dealt with by `process.load('Foo.Foo.foo_cff')` if the fragment is defined in the `foo_cff` (or in a file imported by it)? Does the `process` get automatically extended by the fragment?

**Comment by makortel** [comment]
Superseded by #25439.

**Comment by Dr15Jones** [comment]
+1
