### ISSUE TITLE
GCC 8 Compiler Warning in DTSpyHelper.cc

### ISSUE THREAD

**Issue by wddgit** [cms-sw/cmssw#24231]
While working to fix the many compiler warnings we get with the new GCC 8 compiler, I've run into one where I need some help to resolve it. It looks to me like this is in alca code (so I am including the people I think are the alca L2's here, sorry if I am wrong)

@arunhep 
@tocheng
@pohsun

The problem is in file DTCommissioning/plugins/DTSpyHelper.cc in function DTCtcp::WaitData. My first observation is this function is not called by anything in the CMSSW repository. Can I simply delete the function?

This is the warning from the GCC 8 compiler:

  /build/cmsbld/jenkins/workspace/build-any-ib/w/tmp/BUILDROOT/9b728734df95b8581c635a0b1c07f7a1/opt/cmssw/slc7_amd64_gcc810/cms/cmssw/CMSSW_10_3_X_2018-08-05-2300/src/IORawData/DTCommissioning/plugins/DTSpyHelper.cc:189:28: warning: passing argument 2 to restrict-qualified parameter aliases with argument 4 [-Wrestrict]
       int retva = select (1,&rfds,nullptr,&rfds,&tv);

The problem is that arguments 2 and 4 are the same address, but this is a C function and those arguments are declared 'restricted' (a C keyword not in C++). Two restricted pointers are not allowed to point at the same memory, so I can see this is incorrect and a bug. But I am not familiar with this C function or this part of CMSSW. I don't know what the code is trying to do or how to test any changes I might make. Is there an expert on this code around who could help? If you can give me advice on how to proceed I am happy to make the change and submit the pull request.

**Comment by wddgit** [comment]
After staring at this some  I can see that DTCtcp::WaitData is not only not called by anything in the repository, but it appears to me to be full of nonsense. It couldn't ever have worked. It calls FD_SET(sock,&rfds) before select but then it calls FD_ISSET(0,&rfds) after select. The file descriptors don't even match, sock is probably not 0. If I am understanding the documentation I am reading related to this, this is just totally wrong. I will submit a PR deleting the function. Assuming the PR is approved, we can also close this issue. In the extremely unlikely event someone is actually using the function outside the repository, their build will fail and they can fix this.

**Comment by lpernie** [comment]
Hello @wddgit ,
. Thanks for trying to address the issue with #24249 
. Let me add @ptraczyk , that I think is the real expert about DTs. I think he can add more insight about the real scope of that method
We can further discuss on #24249

**Comment by ptraczyk** [comment]
Hi
I'll check with DT experts if anyone can comment. I work mostly with reco
code, not sure what this piece of CMSSW is supposed to be doing

**Comment by wddgit** [comment]
PR #24249 takes care of this. Closing this issue.
