### ISSUE TITLE
Fix cross product for gcc #24205 breaks slc7_aarch64_gcc700

### ISSUE THREAD

**Issue by fabiocos** [cms-sw/cmssw#24273]
The integration of #24205 causes a failure in the compilation in the slc7_aarch64_gcc700 architecture IBs, as reported by @Dr15Jones https://github.com/cms-sw/cmssw/pull/24205#pullrequestreview-144648418 , see for instance

https://cmssdt.cern.ch/SDT/cgi-bin/buildlogs/slc7_aarch64_gcc700/CMSSW_10_3_X_2018-08-12-2300/DataFormats/Math

**Comment by kpedro88** [comment]
+1
