### ISSUE TITLE
flood of "Electron ID handle not valid " in Top DQM

### ISSUE THREAD

**Issue by slava77** [cms-sw/cmssw#24376]
e.g. in wf 136.85
https://cmssdt.cern.ch/SDT/jenkins-artifacts/ib-baseline-tests/CMSSW_10_3_X_2018-08-22-2300/slc6_amd64_gcc700/-GenuineIntel/matrix-results/136.85_RunEGamma2018A+RunEGamma2018A+HLTDR2_2018+RECODR2_2018reHLT_skimEGamma_Prompt_L1TEgDQM+HARVEST2018_L1TEgDQM/step3_RunEGamma2018A+RunEGamma2018A+HLTDR2_2018+RECODR2_2018reHLT_skimEGamma_Prompt_L1TEgDQM+HARVEST2018_L1TEgDQM.log

```
Begin processing the 2nd record. Run 315489, Event 47708809, LumiSection 78 on stream 0 at 23-Aug-2018 04:54:24.737 CEST
...
%MSG-w TopMonitor:  TopMonitor:mu12TrkIsoVVLEle23CaloIdLTrackIdLIsoVLDZ_muleg  23-Aug-2018 04:54:30 CEST Run: 315489 Event: 47708809
Electron ID handle not valid 
```
there are about 30 such messages per event.

@Sam-Harper you may know a solution

**Comment by slava77** [comment]
assign dqm

**Comment by davidlange6** [comment]
already discussed in #24155 which was merged regardless.

**Comment by slava77** [comment]
> already discussed in #24155 which was merged regardless.

ok, that points to the history of the problem, not to a solution, IIUC

**Comment by davidlange6** [comment]
I guess it points to one solution:) - but right, not a good solution

**Comment by Sam-Harper** [comment]
all fixed now: https://github.com/cms-sw/cmssw/pull/24379

**Comment by fabiocos** [comment]
@Sam-Harper thank you for fixing the issue, that unfortunately is not the only one with the PR that introduced originally the problem. I assume that this issue can be closed, while the fix should be back-ported into 10_2_X

**Comment by schneiml** [comment]
@slava77 sounds like this should be closed.

**Comment by slava77** [comment]
ok, closing.
