### ISSUE TITLE
flood of Warning: algoBit >= prescaleFactorsAlgoTrig.size()  from L1TGlobal in 2016 workflows

### ISSUE THREAD

**Issue by slava77** [cms-sw/cmssw#24377]
e.g. in 2016B SinglePh job wf 136.731 in the reco step
https://cmssdt.cern.ch/SDT/jenkins-artifacts/ib-baseline-tests/CMSSW_10_3_X_2018-08-22-2300/slc6_amd64_gcc700/-GenuineIntel/matrix-results/136.731_RunSinglePh2016B+RunSinglePh2016B+HLTDR2_2016+RECODR2_2016reHLT_skimSinglePh_HIPM+HARVESTDR2/step3_RunSinglePh2016B+RunSinglePh2016B+HLTDR2_2016+RECODR2_2016reHLT_skimSinglePh_HIPM+HARVESTDR2.log

```
%MSG-w L1TGlobal:  L1TGlobalProducer:valGtStage2Digis 23-Aug-2018 04:44:01 CEST  Run: 274199 Event: 38626099

Warning: algoBit >= prescaleFactorsAlgoTrig.size() 
```
is repeated about 80 times per event

**Comment by slava77** [comment]
assign l1

**Comment by thomreis** [comment]
@apana do you know why this would show up in 2016 workflows?

**Comment by apana** [comment]
Hi @thomreis.  No I don't, but I'll look into it.  Thanks for letting me know.

-Len

**Comment by thomreis** [comment]
Hi @apana did you find out what was going on here?

**Comment by apana** [comment]
Hi @thomreis,

I'm sorry, I had forgotten about this issue.  I'll look into it now.

**Comment by slava77** [comment]
ping
a recent example from matrix workflow 136.731
 https://cmssdt.cern.ch/SDT/jenkins-artifacts/ib-baseline-tests/CMSSW_11_1_X_2020-04-25-1100/slc7_amd64_gcc820/-GenuineIntel/matrix-results/136.731_RunSinglePh2016B+RunSinglePh2016B+HLTDR2_2016+RECODR2_2016reHLT_skimSinglePh_HIPM+HARVESTDR2/step3_RunSinglePh2016B+RunSinglePh2016B+HLTDR2_2016+RECODR2_2016reHLT_skimSinglePh_HIPM+HARVESTDR2.log

**Comment by thomreis** [comment]
Looks like it comes from these lines:
https://cmssdt.cern.ch/lxr/source/L1Trigger/L1TGlobal/src/GlobalBoard.cc#0899
and
https://cmssdt.cern.ch/lxr/source/L1Trigger/L1TGlobal/src/GlobalBoard.cc#0927

**Comment by slava77** [comment]
ping
a recent example is in
https://cmssdt.cern.ch/SDT/jenkins-artifacts/ib-baseline-tests/CMSSW_11_2_X_2020-07-21-1100/slc7_amd64_gcc820/-GenuineIntel/matrix-results/136.731_RunSinglePh2016B+RunSinglePh2016B+HLTDR2_2016+RECODR2_2016reHLT_skimSinglePh_HIPM+HARVESTDR2/step3_RunSinglePh2016B+RunSinglePh2016B+HLTDR2_2016+RECODR2_2016reHLT_skimSinglePh_HIPM+HARVESTDR2.log

**Comment by slava77** [comment]
@cms-sw/l1-l2 
re-tagging l1, in case the initial list in L1 changed since 2018

**Comment by cavana** [comment]
@slava77, just to update, I am now looking at this (long reported) issue.  Thank you for the recent example to help reproduce the problem.

**Comment by cecilecaillol** [comment]
@cavana Any update on this? :)

**Comment by cecilecaillol** [comment]
+l1

**Comment by tvami** [comment]
@cmsbuild , please close
 * seems the issue is gone https://github.com/cms-sw/cmssw/issues/24377#issuecomment-1348163124
