### ISSUE TITLE
Problem with large TMVA XML weight files in CRAB and GBRForest without ROOT

### ISSUE THREAD

**Issue by guitargeek** [cms-sw/cmssw#24395]
Hello,

doing some BDT experiments, I ended up with a `BDT.weights.xml` file for my electron MVA that was 21M large. I wanted to use it in the Egamma Tag and Probe tree producer, which worked fine offline, but failed consistently in CRAB:
```
== CMSSW: ----- Begin Fatal Exception 26-Aug-2018 18:53:57 UTC-----------------------
== CMSSW: An exception of category 'FatalRootError' occurred while
== CMSSW:    [0] Constructing the EventProcessor
== CMSSW:    [1] Constructing module: class=ElectronMVAValueMapProducer label='electronMVAValueMapProducer'
== CMSSW:    Additional Info:
== CMSSW:       [a] Fatal Root Error: @SUB=TXMLEngine::ParseFile
== CMSSW: Invalid identifier for node attribute, line 150514
== CMSSW:
== CMSSW: ----- End Fatal Exception -------------------------------------------------
```
This error message can be traced back to here:

https://github.com/root-project/root/blob/master/io/xml/src/TXMLEngine.cxx#L2229
https://github.com/root-project/root/blob/master/tmva/tmva/src/MethodBase.cxx#L1429

I'm a bit confused that I get the error on CRAB, while not getting it locally with cmsenv? Is there a difference between the ROOT environments? How can I set this `xmlenginebuffersize`?

Anyway since I couldn't figure it out but really wanted to get this tree producer running last night I reimplemented the GBRForest without ROOT, but with the tinyxml2 library [1]. That works very well for me and I wanted to ask here if there is any desire to do something like that also in CMSSW master.

[1] https://github.com/guitargeek/cmssw/blob/Fall17V3/CondFormats/EgammaObjects/interface/GBRForest.h

**Comment by Dr15Jones** [comment]
assign reconstruction

**Comment by slava77** [comment]
@Dr15Jones @guitargeek 

do I understand correctly that you had a working version for local running by modifying xmlenginebuffersize?

**Comment by slava77** [comment]
assign core

we still have some non-GBRForest TMVAs in production.
It would be good to understand if the ```xmlenginebuffersize``` limit can be appropriately modified,
in case the non-GBRForest TMVAs hit the limit.

**Comment by guitargeek** [comment]
No, I don't know how to do that @slava77. An implementation without TMVA was the obvious, sustainable and most fun solution do me. But I think it's no problem for current production. If the buffer max size is not hit in the current production workflow right now, is also won't in the future (as long as the weight files won't change). Or maybe I misunderstood the problem you want to solve?

**Comment by slava77** [comment]
I'm missing a direct connection to  #24432.
there are TMVA use cases that do not use GBRForest.
They are not changed/modified by #24432.
It sounds like we may have a problem if these will need an update and that update will have a larger training.

**Comment by guitargeek** [comment]
Ah ok sorry I get it now. Yes, I agree it would be good to know how to adjust the `maxbuffersize` in that case.

**Comment by guitargeek** [comment]
Fixed from 10_3_X on with https://github.com/cms-sw/cmssw/pull/24432 by just not using TMVA anymore.

Fix backported to 10_2_X in https://github.com/cms-sw/cmssw/pull/26170.
