### ISSUE TITLE
Crash in express due to DQM sequences updated in 24155 (10_3_X) and 24156 (backport into 10_2_X)

### ISSUE THREAD

**Issue by fabiocos** [cms-sw/cmssw#24444]
A crash in the CMSSW_10_2_4 T0 replay is reported for express https://hypernews.cern.ch/HyperNews/CMS/get/tier0-Ops/1978/1/1.html .
This is the consequence of backporting #24155 before fixing the problem that was already seen at review level https://github.com/cms-sw/cmssw/pull/24155#issuecomment-413131664 .

**Comment by fabiocos** [comment]
assign dqm

**Comment by fabiocos** [comment]
@mtosi @schneiml I think that a follow-up of the problems originally reported and apparently not addressed so far is unavoidable at this point. Either the sequences are adjusted so as to add the needed collection, or the crashing module is removed

**Comment by fabiocos** [comment]
Initially addressed by #24449 (10_3_X) and #24445 (10_2_X)

**Comment by fabiocos** [comment]
Diagnosis of the problem, cross-checked with @perrotta : ak8PFJetsPuppiSoftDrop is run in 

https://cmssdt.cern.ch/lxr/source/PhysicsTools/PatAlgos/python/slimming/applySubstructure_cff.py

called by

https://cmssdt.cern.ch/lxr/source/PhysicsTools/PatAlgos/python/slimming/miniAOD_tools.py

which is applied in ConfigBuilder if miniAOD is part of the steps:

https://cmssdt.cern.ch/lxr/source/Configuration/Applications/python/ConfigBuilder.py#0653

Prompt is running the miniAOD tools

https://cmssdt.cern.ch/lxr/source/Configuration/DataProcessing/python/Reco.py#0083

Express is not

https://cmssdt.cern.ch/lxr/source/Configuration/DataProcessing/python/Reco.py#0125

**Comment by mtosi** [comment]
!!!
I'm going to move this module out
sorry, but I did not realize the collection comes from tehe miniAOD !!!!!
(the developers have been instructed to rely *only* on collection available
in AOD .....)
  mia

**Comment by fabiocos** [comment]
#24445 protects against possible crashes
