### ISSUE TITLE
Request to add users to cms-analysis organisation

### ISSUE THREAD

**Issue by sethzenz** [cms-sw/cmssw#24469]
Can someone please add these users as members of the cms-analysis organisation? @malcles @simonepigazzini @abenagli

This is needed so they can be given administrative functions for the flashgg repository (Higgs to diphoton group analysis framework).

I am raising this as an issue here because that was the conclusion for the best way to make these requests when we last discussed it by email. Tagging the cms-analysis owners: @smuzaffar @fcouderc @slava77 @vadler  @agrohsje

**Comment by fabiocos** [comment]
@smuzaffar was this issue ever addressed?

**Comment by fabiocos** [comment]
@simonepigazzini so I assume this issue might be closed

**Comment by simonepigazzini** [comment]
yes it can of course, but I have no rights to do that.
