### ISSUE TITLE
HI test during TS2 (September 18): needed back-ports to 10_2_X

### ISSUE THREAD

**Issue by fabiocos** [cms-sw/cmssw#24472]
This issue is meant to collect information about the PRs to be back-ported from 10_3_X to 10_2_X for the special test for HI to be performed during TS2 (planned for September 18).

The plan is to merge the code in a dedicated build to be used only for this test (and its preparation/validation), not interfering with the regular pp data taking.

**Comment by slava77** [comment]
On 9/6/18 10:24 AM, Marco Musich wrote:
> @fabiocos
> @slava77
> I have been slightly confused by the thread ongoing on the d'ORP mailing
> list. Can you clarify where the backport of #24339
> has to go? Just the plain regular 10_2_X branch?
> Thanks.


I suggest that you make a backport to the regular 10_2_X.
Fabio can change the target branch if/when the special integration
branch becomes available.
This way you can port and test in an existing release (e.g. 10_2_4 as a
base).

**Comment by fabiocos** [comment]
@mmusich @slava77 yes, indeed, please put everything in the regular 10_2_X, depending on the need I may move to other branches if really needed

**Comment by mmusich** [comment]
@fabiocos the backport to 10.2.X is at https://github.com/cms-sw/cmssw/pull/24482

**Comment by fabiocos** [comment]
@slava77 #24477 has been merged, thank you for the backport
