### ISSUE TITLE
L1T DQM exception in CMSSW_10_2_5

### ISSUE THREAD

**Issue by fabiocos** [cms-sw/cmssw#24551]
During the replay of CMSSW_10_2_5 a problem has been reported https://hypernews.cern.ch/HyperNews/CMS/get/tier0-Ops/1999/1/1/1/1/1.html 
that looks due to a exception in the L1T DQM code, looking at the log file in /store/unmerged/data/logs/prod/2018/9/14/PromptReco_Run322602_SingleMuon/Reco/0000/3/eabb2f8a-9a0c-4582-b2cd-ee1a2ff79088-3-3-logArchive.tar.gz

----- Begin Fatal Exception 14-Sep-2018 18:09:30 CEST-----------------------
An exception of category 'ProductNotFound' occurred while
   [0] Processing  Event run: 322602 lumi: 28 event: 53396591 stream: 5
   [1] Calling method for module L1TMuonDQMOffline/'l1tMuonDQMOfflineEmu'
Exception Message:
Principal::getByToken: Found zero products matching all criteria
Looking for type: BXVector<l1t::Muon>
Looking for module label: simGmtStage2Digis
Looking for productInstanceName: 

----- End Fatal Exception -------------------------------------------------

There are several L1T DQM updated compared to CMSSW_10_2_4_patch1, the one that is likely the related to this issue is #24291 , as there is an updated in the missing input collection:

https://github.com/cms-sw/cmssw/pull/24291/files#diff-f2f1885926c709e7fd6e009c7d455576

Anyway I am surprised by the fact that this failure is not seen at all in RelVals, and a Configuration/DataProcessing test does not produce it either. Apparently the DQM sequences probed in tests and those used at Tier0 do not match, to be investigated.

As a working release is urgently needed for the HI tests next week, either a fix to the sequence is urgently provided, or I can put a temporary protection in the code skipping the event if the collection is missing (but this is clearly not the real solution).

**Comment by fabiocos** [comment]
assign l1,dqm

**Comment by fabiocos** [comment]
@thomreis could you please provide urgently feedback?

**Comment by fabiocos** [comment]
@thomreis just retrieve the tarball /store/unmerged/data/logs/prod/2018/9/14/PromptReco_Run322602_SingleMuon/Reco/0000/3/eabb2f8a-9a0c-4582-b2cd-ee1a2ff79088-3-3-logArchive.tar.gz
and expand the PSet.py using edmConfigDump. We have seen issues with express, whose sequence is not well reproduced by relvals, but I am more surprised to see this in prompt

**Comment by fabiocos** [comment]
@thomreis the event content after the standard repacking indeed is not having the emulator output:

Type                      Module                   Label     Process   
-----------------------------------------------------------------------
GlobalObjectMapRecord     "hltGtStage2ObjectMap"   ""        "HLT"     
edm::TriggerResults       "TriggerResults"         ""        "HLT"     
trigger::TriggerEvent     "hltTriggerSummaryAOD"   ""        "HLT"     
FEDRawDataCollection      "rawDataCollector"       ""        "LHC"     

I will revert #24291 and you may look at the issue in detail and decide what to do

**Comment by fabiocos** [comment]
@thomreis could you please propose a revision of this code? We need to update it also in 10_3_X...

**Comment by thomreis** [comment]
Hi @fabiocos 
I have added explicit L1T emulator sequence to the offline DQM code in PR #24578 
How could this be tested with T0 like conditions?

**Comment by thomreis** [comment]
10_2_X version of the fix would be #24582

**Comment by thomreis** [comment]
+1
