### ISSUE TITLE
Inconsistent geometry in RelVal 11624

### ISSUE THREAD

**Issue by fabiocos** [cms-sw/cmssw#24686]
@ianna reports about a problem with the geometry settings in relval wf 11624, see https://hypernews.cern.ch/HyperNews/CMS/get/simDevelopment/1869.html

The workflow is for 2019, and the geometry scenario is Extended2019 , but the GT used auto:phase1_2019_realistic contains a 2018 snapshot. This should be fixed in a consistent way

**Comment by fabiocos** [comment]
assign alca,pdmv,geometry

**Comment by ianna** [comment]
GEM geometry in 2018 (left) vs 2019 (right) scenario:
![screenshot 2018-09-27 16 48 37](https://user-images.githubusercontent.com/1390682/46154426-6bc78480-c275-11e8-9115-849d3673439c.png)
Note, the grey disk on the left is made of "ME free space", e.g. Air.

**Comment by ianna** [comment]
@zhenhu - indeed, that's the problem: 
The following specifies 2019 geometry scenario built from XML (GEM description on the right snapshot):
```
'Geom' : 'Extended2019'
```
while the GT contains 2018 GEM reco geometry (left snapshot):
```
'GT' : 'auto:phase1_2019_realistic'
```

**Comment by kpedro88** [comment]
Yes, we need to update the 2019 GT.

**Comment by ianna** [comment]
@kpedro88 - should it be 2019 scenario in 2019 GT? If yes, I'll upload the tag tomorrow so that it could be added to the GT PR before pre5 is closed. The label will be "Extended" as it is a default geometry in the GT.

**Comment by kpedro88** [comment]
@ianna yes, it should be 2019 scenario/geometry in the 2019 GT. I think it was originally cloned from the 2018 GT and not updated consistently.

**Comment by lpernie** [comment]
Hello @ianna , if  you queue the new geometry to the 2019 queue and I will update the GT

**Comment by tocheng** [comment]
Hello @zhenhu , just want to make sure that PdmV doesn't need updated GT to be in CMSSW_10_3_0_pre5.

**Comment by ianna** [comment]
@lpernie - Please, use XMLFILE_Geometry_103YV5_Extended2019_mc with a label "Extended". The test GT queue is:
103X_postLS2_design_Candidate_2018_10_01_09_56_24

**Comment by ianna** [comment]
FYI, there is a modification for run 3 to exclude GEM:
https://cmssdt.cern.ch/lxr/source/Configuration/Eras/python/Era_Run3_cff.py

When a modifier for run 3 is added to the GeometryRecoDB_cff to include GEM reco geometry from DB, the mixing module complains that:
```
01-Oct-2018 12:35:10 CEST  Successfully opened file file:step1.root
----- Begin Fatal Exception 01-Oct-2018 12:35:19 CEST-----------------------
An exception of category 'NoRecord' occurred while
   [0] Processing  stream begin Run run: 1 stream: 0
   [1] Calling method for module MixingModule/'mix'
Exception Message:
No "EcalSimPulseShapeRcd" record found in the EventSetup.n
 Please add an ESSource or ESProducer that delivers such a record.
----- End Fatal Exception -------------------------------------------------
Another exception was caught while trying to clean up files after the primary fatal exception.
``` 
Since the EcalSimPulseShapeRcd record in a GT, it looks like there are some other modifications missing for run3 era which require XML geometry.

**Comment by ianna** [comment]
@lpernie - FYI, a GT update is requested https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/3963.html

**Comment by zhenhu** [comment]
> Hello @zhenhu , just want to make sure that PdmV doesn't need updated GT to be in CMSSW_10_3_0_pre5.

we do not need it. It's not in our regular relval list.

**Comment by tocheng** [comment]
> FYI, there is a modification for run 3 to exclude GEM:
> https://cmssdt.cern.ch/lxr/source/Configuration/Eras/python/Era_Run3_cff.py
> 
> When a modifier for run 3 is added to the GeometryRecoDB_cff to include GEM reco geometry from DB, the mixing module complains that:
> 
> ```
> 01-Oct-2018 12:35:10 CEST  Successfully opened file file:step1.root
> ----- Begin Fatal Exception 01-Oct-2018 12:35:19 CEST-----------------------
> An exception of category 'NoRecord' occurred while
>    [0] Processing  stream begin Run run: 1 stream: 0
>    [1] Calling method for module MixingModule/'mix'
> Exception Message:
> No "EcalSimPulseShapeRcd" record found in the EventSetup.n
>  Please add an ESSource or ESProducer that delivers such a record.
> ----- End Fatal Exception -------------------------------------------------
> Another exception was caught while trying to clean up files after the primary fatal exception.
> ```
> 
> Since the EcalSimPulseShapeRcd record in a GT, it looks like there are some other modifications missing for run3 era which require XML geometry.

@ianna , could this be due to this PR #24415 was not merged at that time?

**Comment by ianna** [comment]
@tocheng - yes, it could be related.

Another issue is how to add the GEM geometry producer from DB. The scenarios before 2017 do not have GEM, the 2017 and later do. However, having both modifies as follows does not work for 2017 since the latter removes the first:

```
def _loadGeometryESProducers( theProcess ) :
   theProcess.load('Geometry.GEMGeometryBuilder.gemGeometryDB_cfi')

from Configuration.Eras.Modifier_run2_GEM_2017_cff import run2_GEM_2017
modifyGeometryConfiguration_cff_ = run2_GEM_2017.makeProcessModifier( _loadGeometryESProducers )

from Configuration.Eras.Modifier_run3_GEM_cff import run3_GEM
modifyGeometryConfiguration_cff_ = run3_GEM.makeProcessModifier( _loadGeometryESProducers )

```

**Comment by kpedro88** [comment]
@ianna `run2_GEM_2017` is the modifier for the slice test. `run3_GEM` is the modifier for the full GEM that will be installed next year. Why do you think there is a problem with how the Run3 Era is set up?

**Comment by ianna** [comment]
@kpedro88 - the above fragment does not work when it is tested on the 10042.0 workflow:
```
01-Oct-2018 16:40:54 CEST  Initiating request to open file file:step1.root
01-Oct-2018 16:40:56 CEST  Successfully opened file file:step1.root
----- Begin Fatal Exception 01-Oct-2018 16:41:07 CEST-----------------------
An exception of category 'NoProxyException' occurred while
   [0] Processing  stream begin Run run: 1 stream: 0
   [1] Calling method for module GEMPadDigiClusterProducer/'simMuonGEMPadDigiClusters'
Exception Message:
No data of type "GEMGeometry" with label "" in record "MuonGeometryRecord"
 Please add an ESSource or ESProducer to your job which can deliver this data.
----- End Fatal Exception -------------------------------------------------
```

**Comment by kpedro88** [comment]
@jshlee can you check if https://github.com/cms-sw/cmssw/issues/24686#issuecomment-425936031 should work in 2017?

**Comment by lpernie** [comment]
Hello.
> Please modify Configuration/AlCa/python/autoCond.py in this PR and change v2 with v3 in:
 . 103X_postLS2_design_v3
. 103X_postLS2_realistic_v3

> Also, since you are changing autocond, could you use 103X_upgrade2018_realistic_HI_v5 (instead of 103X_upgrade2018_realistic_HI_v4)? It contains the last 3 missing Tags from HCAL.
(If you prefer not mix conditions in this PR I can open a new one, but doing it here will simplify eventual conflicts.)

Question: the Tag XMLFILE_Geometry_103YV4_ExtendedDetailedCavern2018_mc should go also in 103X_upgrade2018_realistic_HI_Queue ? At the moment it is not.

**Comment by ianna** [comment]
@lpernie - Yes, please, it is queued.

**Comment by ianna** [comment]
@fabiocos - the https://github.com/cms-sw/cmssw/pull/24768 should fix this.

**Comment by ianna** [comment]
+1

**Comment by lpernie** [comment]
@ianna since I saw no change in autocond I did a PR:
#24782 
where you have the 2 LS2 GTs fixed, and the HI MC GT also completed with remaining HCAL GT and with the new geometry.

**Comment by ianna** [comment]
@lpernie - thanks! The 2019 GTs have consistent geometry now.

**Comment by lpernie** [comment]
+1

**Comment by fabiocos** [comment]
after the merge of #24782 this issue is solved and can be closed
