### ISSUE TITLE
DT reco geometry XML vs DB: norm vector differences

### ISSUE THREAD

**Issue by ianna** [cms-sw/cmssw#24776]
The DTRecoGeometryRcd record (DTRECO_Geometry_50YV3 tag) in GTs was produced with CMSSW_5_0_X. The same record (DTRECO_Geometry_103YV1 tag) produced with recent releases shows differences in a norm vector 
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/tags/DTRECO_Geometry_103YV1/DTRECO_Geometry_50YV3 

For example:
```
normVect  (-1,5.17598e-16,1.33963e-16)
```
vs
```
normVect  (-1,5.17598e-16,1.8941e-16)
```
To reproduce the results, please:
```
git cms-addpkg Validation/Geometry
./Validation/Geometry/test/dddvsdb/runDDDvsDBGeometryValidation.sh  auto:upgrade2019 GeometryExtended2019
```
@fabiocos, @lpernie - FYI

**Comment by Dr15Jones** [comment]
assign geometry

**Comment by ianna** [comment]
+1
