### ISSUE TITLE
Tracking configuration issue in 9_4_X

### ISSUE THREAD

**Issue by fabiocos** [cms-sw/cmssw#24783]
The merge of #24624, meant to backport the updates for fastsim in 9_4_X, has triggered a couple of IB failures, namely in the workflows 10024.4 and 10024.5 see

https://cmssdt.cern.ch/SDT/html/cmssdt-ib/#/relVal/CMSSW_9_4/2018-09-27-2300?selectedArchs=slc6_amd64_gcc630&selectedArchs=slc7_amd64_gcc630&selectedFlavors=X&selectedFlavors=AN_X&selectedStatus=failed

According to the traceback the problem is related to the reconstruction configuration (from 10024.4):

(...)
  File "/cvmfs/cms-ib.cern.ch/week0/slc6_amd64_gcc630/cms/cmssw-patch/CMSSW_9_4_X_2018-10-01-2300/python/FWCore/ParameterSet/Config.py", line 582, in load
    module = __import__(moduleName)
  File "/cvmfs/cms-ib.cern.ch/week0/slc6_amd64_gcc630/cms/cmssw-patch/CMSSW_9_4_X_2018-10-01-2300/python/Configuration/StandardSequences/Reconstruction_cff.py", line 8, in <module>
    from RecoTracker.Configuration.RecoTracker_cff import *
  File "/cvmfs/cms-ib.cern.ch/week0/slc6_amd64_gcc630/cms/cmssw-patch/CMSSW_9_4_X_2018-10-01-2300/python/RecoTracker/Configuration/RecoTracker_cff.py", line 5, in <module>
    from RecoTracker.IterativeTracking.iterativeTk_cff import *
  File "/cvmfs/cms-ib.cern.ch/week0/slc6_amd64_gcc630/cms/cmssw-patch/CMSSW_9_4_X_2018-10-01-2300/python/RecoTracker/IterativeTracking/iterativeTk_cff.py", line 4, in <module>
    from RecoTracker.IterativeTracking.InitialStepPreSplitting_cff import *
  File "/cvmfs/cms-ib.cern.ch/week0/slc6_amd64_gcc630/cms/cmssw-patch/CMSSW_9_4_X_2018-10-01-2300/python/RecoTracker/IterativeTracking/InitialStepPreSplitting_cff.py", line 176, in <module>
    from RecoTracker.IterativeTracking.InitialStep_cff import initialStepTrackRefsForJets, caloTowerForTrk, ak4CaloJetsForTrk
  File "/cvmfs/cms-ib.cern.ch/week0/slc6_amd64_gcc630/cms/cmssw-patch/CMSSW_9_4_X_2018-10-01-2300/python/RecoTracker/IterativeTracking/InitialStep_cff.py", line 139, in <module>
    CAHitQuadrupletGeneratorFactory = _hitSetProducerToFactoryPSet(initialStepHitQuadruplets).clone(SeedComparitorPSet = dict(ComponentName = "none")),
  File "/cvmfs/cms-ib.cern.ch/week0/slc6_amd64_gcc630/cms/cmssw-patch/CMSSW_9_4_X_2018-10-01-2300/python/FastSimulation/Tracking/SeedingMigration.py", line 20, in _hitSetProducerToFactoryPSet
    ret.ComponentName = cms.string(_map[producer._TypedParameterizable__type]);
KeyError: 'PixelQuadrupletEDProducer'

touched by the modification in

https://github.com/cms-sw/cmssw/blob/CMSSW_9_4_X/RecoTracker/IterativeTracking/python/InitialStep_cff.py#L139

**Comment by fabiocos** [comment]
assign reconstruction

@kpedro88 FYI

**Comment by kpedro88** [comment]
@makortel @pmaksim1 @ssekmen FYI

**Comment by pmaksim1** [comment]
I think @angirar may know more about this.

**Comment by makortel** [comment]
The workflows 10024.4 and .5 have been removed since 9_4_X as is the pixel quadruplet seeding algorithm they exercised, which is why the backport fails with these. I think we could either
* remove the workflows (they are not that interesting anymore), or
* "fix" the problem by e.g. adding `"PixelQuadrupletEDProducer": None` to 
https://github.com/cms-sw/cmssw/blob/f714f3c6e0720fe6e046acb6339440a2acf332e1/FastSimulation/Tracking/python/SeedingMigration.py#L11-L17
(or `"PixelQuadrupletEDProducer": "PixelQuadrupletGenerator"`, either way the algorithm won't work in FastSim without extra effort, which IMHO is not worth it)

**Comment by angirar** [comment]
@pmaksim1 Thank you for mentioning me, although to be honest I didn't know about these tracking specific workflows that existed in the IB test, especially because they are not FastSim workflows. I took a look at it and reproduced the failure from "10024.4" workflow. I tried what @makortel suggested i.e.  simply adding "PixelQuadrupletEDProducer": "None" to [cmssw/FastSimulation/Tracking/python/SeedingMigration.py](https://github.com/cms-sw/cmssw/blob/master/FastSimulation/Tracking/python/SeedingMigration.py#L17) and the error gets fixed. 
I agree with Matti that adding "PixelQuadrupletEDProducer" to FastSim tracking will take an effort which is totally uncalled for right now. So either I can create a PR as a fix to this issue or simply remove these workflows if they are of no interest anymore.

**Comment by ssekmen** [comment]
Thank you very much @angirar . @fabiocos please let us know what you think.

**Comment by fabiocos** [comment]
@makortel thank you, I believe that the second option mentioned, i.e. silence the producer for fastsim, is preferable. The workflows were present in 9_4_X and I would like to make as minimal modifications as possible to the non FatsSim part. Indeed the solution proposed by Matti works, and I will make a PR to get it in the release. My concern is to ensure that the tracking in regular data/fullsim is unchanged after this backport. As far as I can see dumping configurations in 136.799 for step3 a list of modules are present, but they should not enter in any used sequence. A quick comparison on 100 events show that the DQM output is "almost" equal, with some tiny differences, partly in the tracking histograms.

**Comment by fabiocos** [comment]
@makortel sorry, for my understanding: the workflows 10024.4 and 10024.5 are not running fastsim, but reco on fullsim. Could you please explain why the modification of the seeding code for fastsim interfere with the reconstruction in fullsim? Are we sure that only fastsim is updated by these PRs?

**Comment by makortel** [comment]
@fabiocos My proposed solution may only affect FastSim as the `_hitSetProducerToFactoryPSet()` function from `FastSimulation.Tracking.SeedingMigration` is only called in FastSim customizations, e.g.
https://github.com/cms-sw/cmssw/blob/f714f3c6e0720fe6e046acb6339440a2acf332e1/RecoTracker/IterativeTracking/python/InitialStep_cff.py#L130-L132

The reason why the failures are in FullSim instead is that this function is always executed (regardless of the eras). It takes the "hit set" EDProducer as an input, and translates that to a PSet for FastSim (a relic from the time of "new seeding framework" that moved from helper plugins to EDProducers for seeding internals). Specifically the C++ type of the EDProducer is used. The workflows 10024.4 and 10024.5 enable the modifier `trackingPhase1QuadProp`, which changes the type of `initialStepHitQuadruplets` EDProducer to `PixelQuadrupletEDProducer`
https://github.com/cms-sw/cmssw/blob/f714f3c6e0720fe6e046acb6339440a2acf332e1/RecoTracker/IterativeTracking/python/InitialStep_cff.py#L82-L83
which then causes the failure at the time when `_hitSetProducerToFactoryPSet(initialStepHitQuadruplets)` is called in
https://github.com/cms-sw/cmssw/blob/f714f3c6e0720fe6e046acb6339440a2acf332e1/RecoTracker/IterativeTracking/python/InitialStep_cff.py#L137-L139

In practice even FastSim is not really affected, as the FastSim is never run with `trackingPhase1QuadProp` modifier.

**Comment by fabiocos** [comment]
@makortel thank you for the detailed clarification. Your suggestion is implemented in #24798

**Comment by fabiocos** [comment]
The problem is solved with the merge of #24798 and this issue can be closed
