### ISSUE TITLE
cleanup exceptions used for error messaging in  EventFilter/SiStripRawToDigi

### ISSUE THREAD

**Issue by slava77** [cms-sw/cmssw#24825]
one example is https://github.com/cms-sw/cmssw/blob/CMSSW_10_3_0_pre5/EventFilter/SiStripRawToDigi/src/SiStripFEDBufferComponents.cc#L1507

```FEDChannel::cmMedian``` can throw and the calling code will catch and not rethrow https://github.com/cms-sw/cmssw/blob/CMSSW_10_3_0_pre5/EventFilter/SiStripRawToDigi/plugins/SiStripRawToDigiUnpacker.cc#L309

This is a good example of inappropriate use of exceptions.

A possible resolution to this issue will include appropriate passing of error return codes.

@alesaggio @OlivierBondu @pieterdavid

**Comment by slava77** [comment]
assign reconstruction

**Comment by pieterdavid** [comment]
With https://github.com/cms-sw/cmssw/pull/28756 merged I think this can be closed.

**Comment by smuzaffar** [comment]
fixed
