### ISSUE TITLE
IB wf 250204.18 keeps failing

### ISSUE THREAD

**Issue by fabiocos** [cms-sw/cmssw#24850]
After the recent update of input relval collections #24816 most of the previously failing workflows run smoothly, but for 250204.18. This workflow succeeds when run completely, but it fails if the input GEN-SIM is required (as in the IB), because the dataset seems missing in DAS:

10:39 cmsdev15 4575> dasgoclient --limit=10 --query "dataset dataset=/RelValQQH1352T_13/CMSSW_10_3_0_pre5-103X_upgrade2018_realistic_v7-v1/GEN-SIM"
/RelValQQH1352T_13/CMSSW_10_3_0_pre5-103X_upgrade2018_realistic_v7-v1/GEN-SIM
10:39 cmsdev15 4576> dasgoclient --limit=10 --query "site dataset=/RelValQQH1352T_13/CMSSW_10_3_0_pre5-103X_upgrade2018_realistic_v7-v1/GEN-SIM"
WARNING: No site records found in PhEDEx, will look-up original sites in DBS
10:40 cmsdev15 4577> 

@zhenhu @prebello @pgunnell could you please clarify whether this sample is still under production?

**Comment by fabiocos** [comment]
assign pdmv

**Comment by zhenhu** [comment]
Hi @fabiocos , the QQH1325 GEN-SIM was produced with "v2" in its name. 
But I have added the "v2" protection in #24816 already: 
https://github.com/cms-sw/cmssw/pull/24816/files#diff-819af2ec677272fddf1fef50e788a88bR2662
It worked fine for relval productions.

**Comment by zhenhu** [comment]
OK, so this versionOverrides function only works for noPU and PU workflows, but not for premix workflows

**Comment by zhenhu** [comment]
We can hard code the "v2" in L749 to temporarily fix this issue:
https://github.com/zhenhu/cmssw/blob/8f5f41e022fd8385eb43d82e9bb79bd5a55b00a0/Configuration/PyReleaseValidation/python/relval_steps.py#L749 
Or do you have any other suggestions?

**Comment by kpedro88** [comment]
@makortel can we make the premixing workflows check `versionOverrides`?

**Comment by makortel** [comment]
@kpedro88 Maybe. By quick look it does not look straightforward though, as (AFAICT) `versionOverrides` is used for the "upgrade-style" workflow definitions, while the premixing workflows in `relval_premix.py`, are defined in the "old style".

**Comment by makortel** [comment]
I suppose the alternatives would be to either make this piece to support `versionOverrides`
https://github.com/cms-sw/cmssw/blob/20277130d6f6591851e41629e181393fc2197fc2/Configuration/PyReleaseValidation/python/relval_steps.py#L625-L759
or, one way or another, recode `relval_premix.py` to use the "upgrade style" workflow definitions.

**Comment by fabiocos** [comment]
@zhenhu @prebello this seems to have been forgotten. It does not make sense to have a test that is constantly crashing since one month, so either we fix it or we remove it, do you agree?

**Comment by zhenhu** [comment]
Hi @fabiocos , 
This issue will be automatically fixed after we reproduced the GEMSIM files next time. For now, we can simply hack this line as 
```
steps['QQH1352T_13UP18INPUT']={'INPUT':InputInfo(dataSet='/RelValQQH1352T_13/CMSSW_10_3_0_pre5-103X_upgrade2018_realistic_v7-v2/GEN-SIM',location='STD')}
```
Is this ok for you?

**Comment by fabiocos** [comment]
@zhenhu I have tried a more general solution in #25245, please check that

**Comment by fabiocos** [comment]
fixed by the addition of an override mechanism for standard samples
