### ISSUE TITLE
-Ofast flags in CLANG IBs is causing undefined __[exp,log,pow,logf,logl]_finite symbols

### ISSUE THREAD

**Issue by smuzaffar** [cms-sw/cmssw#24935]
@VinInn, after updating LLVM to version 7.0.0, we noticed many errors like [a] in CLANG IBs.

I am able to avoid these by added `-fno-builtin` `CXXFLAGS` for llvm compiler only in various BuildFiles (see changere here https://github.com/smuzaffar/cmssw/commit/5114513909a1a09fa516b8cb934ce7c0ca4eb67d ). Do you think it is the right solution?

[a]
```
TrackingTools/GsfTools/src/TrackingToolsGsfTools/MultiTrajectoryStateMode.cc.o: In function `MultiTrajectoryStateMode::momentumFromModePPhiEta(TrajectoryStateOnSurface, Vector3DBase<float, GlobalTag>&) const':
MultiTrajectoryStateMode.cc:(.text+0x480f): undefined reference to `__exp_finite'
TrackingTools/GsfTools/src/TrackingToolsGsfTools/GaussianSumUtilities1D.cc.o: In function `GaussianSumUtilities1D::lnPdf(double const&) const':
GaussianSumUtilities1D.cc:(.text+0x2643): undefined reference to `__log_finite'
TrackingTools/GsfTools/src/TrackingToolsGsfTools/GaussianSumUtilities1D.cc.o: In function `GaussianSumUtilities1D::lnPdf(double, std::vector<double, std::allocator<double> > const&)':
GaussianSumUtilities1D.cc:(.text+0x27d7): undefined reference to `__log_finite'
TrackingTools/GsfTools/src/TrackingToolsGsfTools/GSUtilities.cc.o: In function `GSUtilities::mode() const':
GSUtilities.cc:(.text+0x85a): undefined reference to `__exp_finite'
GSUtilities.cc:(.text+0x86c): undefined reference to `__exp_finite'
GSUtilities.cc:(.text+0x881): undefined reference to `__exp_finite'
GSUtilities.cc:(.text+0x893): undefined reference to `__exp_finite'
GSUtilities.cc:(.text+0x9da): undefined reference to `__exp_finite'
TrackingTools/GsfTools/src/TrackingToolsGsfTools/GSUtilities.cc.o:GSUtilities.cc:(.text+0xca3): more undefined references to `__exp_finite' follow
clang-7: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by VinInn** [comment]
__exp_finite in libm, at least in cc7
nm -C /usr/lib64/libm.so | grep _finite
000000000002a3a0 t __GI___finite
0000000000035c60 t __GI___finitef
000000000003f140 t __GI___finitel
000000000000ae80 i __acos_finite
000000000002a910 T __acosf_finite
0000000000008a20 T __acosh_finite
000000000002abe0 T __acoshf_finite
0000000000035f40 T __acoshl_finite
0000000000035f20 T __acosl_finite
000000000000aeb0 i __asin_finite
000000000002acc0 T __asinf_finite
0000000000036020 T __asinl_finite
000000000000fc20 i __atan2_finite
000000000002af00 T __atan2f_finite
0000000000036270 T __atan2l_finite
000000000000fc60 T __atanh_finite
000000000002b140 T __atanhf_finite
0000000000036280 T __atanhl_finite
000000000000fd80 T __cosh_finite
000000000002b240 T __coshf_finite
0000000000036370 T __coshl_finite
000000000002a1b0 T __exp10_finite
0000000000035b70 T __exp10f_finite
000000000003ef70 T __exp10l_finite
0000000000026ce0 T __exp2_finite
0000000000032940 T __exp2f_finite
000000000003ba40 T __exp2l_finite
00000000000103e0 i __exp_finite
000000000002b340 T __expf_finite
00000000000364f0 T __expl_finite
000000000002a3a0 T __finite
0000000000035c60 T __finitef
000000000003f140 T __finitel
00000000000108e0 T __fmod_finite
000000000002b500 T __fmodf_finite
0000000000036570 T __fmodl_finite
00000000000163c0 T __gamma_r_finite
000000000002e620 T __gammaf_r_finite
0000000000038b50 T __gammal_r_finite
0000000000010ae0 T __hypot_finite
000000000002b6c0 T __hypotf_finite
0000000000036590 T __hypotl_finite
0000000000011030 T __j0_finite
000000000002b980 T __j0f_finite
00000000000369e0 T __j0l_finite
0000000000011880 T __j1_finite
000000000002c0d0 T __j1f_finite
0000000000037080 T __j1l_finite
0000000000011e00 T __jn_finite
000000000002c5f0 T __jnf_finite
00000000000374b0 T __jnl_finite
0000000000012500 T __lgamma_r_finite
000000000002caf0 T __lgammaf_r_finite
0000000000037b20 T __lgammal_r_finite
0000000000014740 T __log10_finite
000000000002d680 T __log10f_finite
0000000000038420 T __log10l_finite
0000000000026a90 T __log2_finite
0000000000032750 T __log2f_finite
000000000003ba10 T __log2l_finite
0000000000014700 i __log_finite
000000000002d3f0 T __logf_finite
00000000000383b0 T __logl_finite
0000000000015a40 i __pow_finite
000000000002d760 T __powf_finite
0000000000038450 T __powl_finite
0000000000015a70 T __remainder_finite
000000000002e2c0 T __remainderf_finite
00000000000388c0 T __remainderl_finite
0000000000016110 T __scalb_finite
000000000002e3d0 T __scalbf_finite
00000000000388e0 T __scalbl_finite
00000000000161b0 T __sinh_finite
000000000002e450 T __sinhf_finite
0000000000038970 T __sinhl_finite
00000000000163b0 T __sqrt_finite
000000000002e610 T __sqrtf_finite
0000000000038b40 T __sqrtl_finite
0000000000011320 T __y0_finite
000000000002bc30 T __y0f_finite
0000000000036c20 T __y0l_finite
0000000000011b20 T __y1_finite
000000000002c340 T __y1f_finite
0000000000037280 T __y1l_finite
0000000000012280 T __yn_finite
000000000002c970 T __ynf_finite
00000000000378f0 T __ynl_finite

**Comment by smuzaffar** [comment]
I tried linking libm explicitly but did not work. Note that we get these errors which compiling with clang++

**Comment by smuzaffar** [comment]
ah right, libm on slc6 does not contain these missing symbols. Is it acceptable to --no-build flag for llvm compiler on slc6 only?

**Comment by smuzaffar** [comment]
I made a PR https://github.com/cms-sw/cmssw/pull/24969 to make use of ofast-flag tool.

**Comment by XapaJIaMnu** [comment]
https://bugs.llvm.org/show_bug.cgi?id=45034
