### ISSUE TITLE
Merge of 24892 crashes workflow 148.0

### ISSUE THREAD

**Issue by fabiocos** [cms-sw/cmssw#24981]
Starting from CMSSW_10_4_X_2018-10-23-1100 the workflow 148 is crashing with the message

----- Begin Fatal Exception 23-Oct-2018 22:01:30 CEST-----------------------
An exception of category 'ProductNotFound' occurred while
   [0] Processing  Event run: 1 lumi: 1 event: 1 stream: 2
   [1] Running path 'Flag_trkPOG_logErrorTooManyClusters'
   [2] Prefetching for module LogErrorEventFilter/'logErrorTooManyClusters'
   [3] Prefetching for module LogErrorHarvester/'logErrorHarvester'
   [4] Calling method for module CentralityProducer/'hiCentrality'
Exception Message:
Principal::getByToken: Found zero products matching all criteria
Looking for type: std::vector&lt;reco::Track&gt;
Looking for module label: hiConformalPixelTracks
Looking for productInstanceName: 

   Additional Info:
      [a] If you wish to continue processing events after a ProductNotFound exception,
add "SkipEvent = cms.untracked.vstring('ProductNotFound')" to the "options" PSet in the configuration.

----- End Fatal Exception -------------------------------------------------

induced by the updates in #24892

**Comment by fabiocos** [comment]
assign reconstruction

**Comment by perrotta** [comment]
@YeonjuGo @mandrenguyen

**Comment by slava77** [comment]
it looks like the other problem is a broken express config
see https://github.com/cms-sw/cmssw/pull/25004#issuecomment-433205200

**Comment by fabiocos** [comment]
@slava77 the merge of #25011 should have fixed it
