### ISSUE TITLE
FWCore/Integration: Duplicate geneabted CFI files

### ISSUE THREAD

**Issue by smuzaffar** [cms-sw/cmssw#25057]
@Dr15Jones , we have duplicate generated cfi files[a]. With new build rules this will generate a build error.

[a]
https://github.com/cms-sw/cmssw/blob/02d4198c0b6615287fd88e9a8ff650aea994412e/FWCore/Integration/test/OtherThingAnalyzer.cc#L310

https://github.com/cms-sw/cmssw/blob/02d4198c0b6615287fd88e9a8ff650aea994412e/FWCore/Integration/test/ThingWithMergeProducer.cc#L191

**Comment by smuzaffar** [comment]
assign core

**Comment by Dr15Jones** [comment]
@wddgit could you fix this?

**Comment by wddgit** [comment]
Yes. I will take a look now.

**Comment by wddgit** [comment]
PR #25060 should fix this and this issue can be closed.

**Comment by Dr15Jones** [comment]
+1

**Comment by Dr15Jones** [comment]
@smuzaffar please close this one if the problem is now gone.
