### ISSUE TITLE
Clean up magic numbers in Geometry/HGCalGeometry and Geometry/HGCalCommonData

### ISSUE THREAD

**Issue by cvuosalo** [cms-sw/cmssw#25078]
HGCal geometry code contains magic numbers that should be replaced with constants. Some examples are:

Geometry/HGCalGeometry/src/HGCalGeometry.cc line 387
 float dy = 0.5*(rr.second+rr.first)*m_cellVec2[cellIndex].param()[11];

and Geometry/HGCalCommonData/src/HGCalGeomParameters.cc line 1029
 int  corners[6];

**Comment by fabiocos** [comment]
assign geometry,upgrade

**Comment by kpedro88** [comment]
@bsunanda are these all fixed now?

**Comment by bsunanda** [comment]
@kpedro88 There may be some more bugs according to Marco. Let me resolve this along with magic #'s

**Comment by kpedro88** [comment]
@bsunanda checking on this again

**Comment by bsunanda** [comment]
@kpedro88 Trying to submit a PR with some fixes. I am not sure if it cures all

**Comment by kpedro88** [comment]
@bsunanda @cvuosalo are these fixes complete?

**Comment by cvuosalo** [comment]
@kpedro88: I think the issue has been resolved well enough. Maybe @bsunanda would like to comment.

This issue can be closed, from my point of view.

**Comment by kpedro88** [comment]
+upgrade

**Comment by cvuosalo** [comment]
+1
