### ISSUE TITLE
non-reproducible/non-repeatable results in HGC sensitive material validation plots

### ISSUE THREAD

**Issue by slava77** [cms-sw/cmssw#25234]
Here is an example from 27434.0 from 
https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_10_4_X_2018-11-13-1100+25132/29377/
(left is the baseline CMSSW_10_4_X_2018-11-13-1100 and right is with a PR 25132 containing unrelated changes)

<img width="760" alt="wf27434_hgcsensitive" src="https://user-images.githubusercontent.com/4676718/48494883-9a78ca80-e7e3-11e8-891b-d6bc4ec43442.png">

**Comment by slava77** [comment]
assign upgrade

**Comment by kpedro88** [comment]
I am running valgrind to figure out the source of this.

**Comment by bsunanda** [comment]
Check PR #25257

**Comment by slava77** [comment]
it looks like the random differences in HGCalSimHitsV are gone now.
I'm closing this.
