### ISSUE TITLE
RawPPCProducer and concurrent LuminosityBlocks

### ISSUE THREAD

**Issue by Dr15Jones** [cms-sw/cmssw#25283]
I was hoping to convert RawPCCProducer into a edm::global module in order to support concurrent LuminosityBlock processing. I got very close but I was stopped because the module optionally writes out a text file. At begin LuminosityBlock it opens the file and starts a new line, then at end LuminosityBlock it finishes writing that line. Clearly, such semantics does not support concurrent LuminosityBlock processing. There are several possibilities

- remove the option to create the text file
- do not write during begin LuminosityBlock and instead write the entire line at end LuminosityBlock
- write two lines per LuminosityBlock, one line at begin and another at end

The choice on which of these options is the best depends on how the text file is used.

**Comment by Dr15Jones** [comment]
This is related to #25263

**Comment by Dr15Jones** [comment]
assign alca

**Comment by tocheng** [comment]
Hello,
I think it is ok to "do not write during begin LuminosityBlock and instead write the entire line at end LuminosityBlock".
Let me include the PCC expert to comment @capalmer85

**Comment by Dr15Jones** [comment]
The underlying problem is the framework can process several LuminosityBlocks concurrently, which means you could have two calls to `beginLuminosityBlock` before the first call to `endLuminosityBlock`.

**Comment by capalmer85** [comment]
Ok.  Great.  Yes, please move the code into endLuminosityBlock.  It doesn't need to be in beginLuminosityBlock.

**Comment by Dr15Jones** [comment]
See #25330
