### ISSUE TITLE
Memory leak from HepPDT::ParticleDataTable::particle

### ISSUE THREAD

**Issue by Dr15Jones** [cms-sw/cmssw#25291]
valgrind has found the following call to be leaking memory:

https://github.com/cms-sw/cmssw/blob/02d4198c0b6615287fd88e9a8ff650aea994412e/SimTracker/SiStripDigitizer/plugins/SiLinearChargeDivider.cc#L41

I traced the leak to line 28 of HeavyIonUnknownID::processUnknownID
http://lcgapp.cern.ch/project/simu/HepPDT/HepPDT.3.03.00/html/HeavyIonUnknownID_8cc-source.html

CMS specifies to use that class here
https://github.com/cms-sw/cmssw/blob/02d4198c0b6615287fd88e9a8ff650aea994412e/SimGeneral/HepPDTESSource/src/HepPDTESSource.cc#L16

**Comment by Dr15Jones** [comment]
assign simulation, generator

**Comment by kpedro88** [comment]
assign generators

**Comment by Dr15Jones** [comment]
A work around is in #25298

I did contact the original author of HepPDT with the problem.

**Comment by fabiocos** [comment]
@Dr15Jones your fix has been merged in CMSSW_10_4_X_2018-11-25-0000. Until an external update is possible, I assume this is the solution to this issue.

**Comment by Dr15Jones** [comment]
> @fabiocos  I assume this is the solution to this issue.

Yes
