### ISSUE TITLE
Flag_hcalLaserEventFilter is broken when running on of pre-10X data in 102X+ releases

### ISSUE THREAD

**Issue by slava77** [cms-sw/cmssw#25324]
Due to a missing  initialization for lasmonCharge_ in HcalNoiseSummary the hcalLaserEventFilter is expected to be broken when running on of pre-10X data in 102X+ releases.
- the missing initialization appeared with #21152 in 10_0_0_pre2
- the hcalLaserEventFilter enabled checks of lasmonCharge_ by default in #22974 in CMSSW_10_2_0_pre5

AFAIK, none of the miniAOD production is affected so far (since we've opted to use 94X for 2016, 2017 re-miniAOD before this became a problem).

@ahinzmann @zdemirag @eioannou 
please take a note, in case there are recipes for 102X+ releases for running on AOD/RECO produced in pre-10_0_X releases

**Comment by slava77** [comment]
assign reconstruction

**Comment by slava77** [comment]
This should be now resolved in PRs #25325 (104X),  #25326 (102X), and #25327 (103X).
The issue will remain open until the PRs are in the production releases.

**Comment by slava77** [comment]
@smuzaffar 
I wasn't really expecting an automated closing here ```cmsbuild closed this in #25325 31 minutes ago```
please clarify which magic words triggered closing of this issue.

As I mentioned in https://github.com/cms-sw/cmssw/issues/25324#issuecomment-441232222, I prefer to have this open until #25326 (102X), and #25327 (103X) are merged

**Comment by smuzaffar** [comment]
@slava77 , cms-bot should not close issue automatically, so no idea what had happened. I see that bot had merged #25325 but this should no close this issue. I will check in details later

**Comment by smuzaffar** [comment]
@slava77 , it was github which has closed the issue.
https://help.github.com/articles/closing-issues-using-keywords/

**Comment by slava77** [comment]
On 11/27/18 6:31 AM, Malik Shahzad Muzaffar wrote:
> @slava77
> , it was github which has closed the issue.
> https://help.github.com/articles/closing-issues-using-keywords/
> 
> —

OK, I should watch out what I write then.

**Comment by slava77** [comment]
I see that both #25326 and #25327 were merged.
I'm closing this issue.
