### ISSUE TITLE
testSSTGainPCL_fromRECO unit test failing in recent IBs

### ISSUE THREAD

**Issue by fabiocos** [cms-sw/cmssw#25336]
Since CMSSW_10_4_X_2018-11-23-1100 the unit test testSSTGainPCL_fromRECO in CalibTracker/SiStripChannelGain has started to fail, and this is true for 10_3_X, 10_2_X and 10_1_X 👍 

Using Dataset: /ZeroBias/Run2018A-SiStripCalMinBias-17Sep2018_pilot-v1/ALCARECO
----- Begin Fatal Exception 24-Nov-2018 17:03:23 CET-----------------------
An exception of category 'ConfigFileReadError' occurred while
   [0] Processing the python configuration file named /build/cmsbld/jenkins/workspace/ib-run-qa/CMSSW_10_4_X_2018-11-24-1100/src/CalibTracker/SiStripChannelGain/test/testSSTGain_PCL_FromRECO_cfg.py
Exception Message:
python encountered the error: &lt;type 'exceptions.ValueError'&gt;
No JSON object could be decoded
----- End Fatal Exception -------------------------------------------------
Failure running cmsRun testSSTGain_PCL_FromRECO_cfg.py 0: status 90
status = 23040

The problem is in the das query used inside this test at 

https://cmssdt.cern.ch/lxr/source/CalibTracker/SiStripChannelGain/test/testSSTGain_PCL_FromRECO_cfg.py#0031

as simply seen in

19:20 cmsdev15 1395> python
Python 2.7.14+ (default, Mar 28 2018, 11:00:06) 
[GCC 7.3.1 20180127] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import FWCore.ParameterSet.Config as cms
>>> import os
>>> import Utilities.General.cmssw_das_client as das_client
>>> query = "import Utilities.General.cmssw_das_client as das_client"
>>> query = "file dataset=/ZeroBias/Run2018B-SiStripCalMinBias-17Sep2018_pilot-v1/ALCARECO site=T2_CH_CERN | grep file.name"
>>> jsondict = das_client.get_data(query)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/cvmfs/cms-ib.cern.ch/week1/slc6_amd64_gcc700/cms/cmssw-patch/CMSSW_10_4_X_2018-11-24-1100/python/Utilities/General/cmssw_das_client.py", line 83, in get_data
    if not err: return loads(out)
  File "/cvmfs/cms-ib.cern.ch/week1/slc6_amd64_gcc700/external/python/2.7.14-omkpbe4/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/cvmfs/cms-ib.cern.ch/week1/slc6_amd64_gcc700/external/python/2.7.14-omkpbe4/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/cvmfs/cms-ib.cern.ch/week1/slc6_amd64_gcc700/external/python/2.7.14-omkpbe4/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

A dasgoclient query gives me:

19:21 cmsdev15 1396> dasgoclient --query "file dataset=/ZeroBias/Run2018B-SiStripCalMinBias-17Sep2018_pilot-v1/ALCARECO site=T2_CH_CERN | grep file.name"
ERRO[0000] unable to Http client                         Error="Get https://cms-rucio-authz.cern.ch/auth/x509: remote error: tls: unknown certificate"
/store/data/Run2018B/ZeroBias/ALCARECO/SiStripCalMinBias-17Sep2018_pilot-v1/100000/2092A313-0B8F-CC40-B74F-A2822E1CD1BB.root  
/store/data/Run2018B/ZeroBias/ALCARECO/SiStripCalMinBias-17Sep2018_pilot-v1/100000/8339BD51-D21F-0E4E-9F76-47C18689F633.root  
/store/data/Run2018B/ZeroBias/ALCARECO/SiStripCalMinBias-17Sep2018_pilot-v1/100000/3255D405-2799-D344-8678-E580892D4495.root  
/store/data/Run2018B/ZeroBias/ALCARECO/SiStripCalMinBias-17Sep2018_pilot-v1/100000/F8DDE703-0926-3142-9BDA-7D760DC2827C.root  
/store/data/Run2018B/ZeroBias/ALCARECO/SiStripCalMinBias-17Sep2018_pilot-v1/100000/42DF4743-61EC-3F4D-B6EE-7FF7168E7B35.root  
/store/data/Run2018B/ZeroBias/ALCARECO/SiStripCalMinBias-17Sep2018_pilot-v1/100000/D54C5FA8-0506-2D49-A0B9-CED9F22B090C.root  
/store/data/Run2018B/ZeroBias/ALCARECO/SiStripCalMinBias-17Sep2018_pilot-v1/100000/1811AFBB-BCDB-7F4C-BD70-33DEE1C5B778.root  
/store/data/Run2018B/ZeroBias/ALCARECO/SiStripCalMinBias-17Sep2018_pilot-v1/100000/2ECBD854-98BB-8A4B-9FA9-BE1D189C17AF.root  
/store/data/Run2018B/ZeroBias/ALCARECO/SiStripCalMinBias-17Sep2018_pilot-v1/100000/FB35E5D4-8F98-0145-90D5-FE01D2224FC4.root

**Comment by fabiocos** [comment]
@vkuznetv FYI

**Comment by fabiocos** [comment]
@vkuznet FYI

**Comment by pieterdavid** [comment]
CC @mdelcourt @dimattia (gain calibration experts), in case the problem is with the test rather than with the das query

**Comment by mmusich** [comment]
> CC @mdelcourt @dimattia (gain calibration experts), in case the problem is with the test rather than 

I think that's not the case. Supplying directly a file with this diff:
```diff
diff --git a/CalibTracker/SiStripChannelGain/test/testSSTGain_PCL_FromRECO_cfg.py b/CalibTracker/SiStripChannelGain/test/testSSTGain_PCL_FromRECO_cfg.py
index 9bec3fe76f2..acb6ce85cbd 100644
--- a/CalibTracker/SiStripChannelGain/test/testSSTGain_PCL_FromRECO_cfg.py
+++ b/CalibTracker/SiStripChannelGain/test/testSSTGain_PCL_FromRECO_cfg.py
@@ -80,14 +80,18 @@ process.maxEvents = cms.untracked.PSet(
     )
 
 
-INPUTFILES=getFileNames_das_client()
+#INPUTFILES=getFileNames_das_client()
+
+INPUTFILES=["/store/data/Run2018B/ZeroBias/ALCARECO/SiStripCalMinBias-17Sep2018_pilot-v1/100000/2092A313-0B8F-CC40-B74F-A2822E1CD1BB.root"]  
+        
 
 if len(INPUTFILES)==0: 
     print("** WARNING: ** According to a DAS query no suitable data for test is available. Skipping test")
     os._exit(0)
 
 myFiles = cms.untracked.vstring()
-myFiles.extend([INPUTFILES[0][0].replace("\"","")])
+#myFiles.extend([INPUTFILES[0][0].replace("\"","")])
+myFiles.extend(INPUTFILES)
 # Input source
 process.source = cms.Source("PoolSource",
                             fileNames = myFiles,

```

results in a successfully completed test. 

@fabiocos what is the policy about supplying source files to unit tests? Can we hardcode a LFN address in the configuration?

**Comment by vkuznet** [comment]
The DAS fix to remove rucio printouts is applied in this PR: https://github.com/cms-sw/cmsdist/pull/4533

**Comment by fabiocos** [comment]
@mmusich I do not see anything wrong with the test itself, actually it served the purpose of triggering an error induced by das. The only drawback is that its failure is not necessarily related only to the Strip Gain code. From the point of view of the problem this issue is solved and can be closed.

**Comment by mmusich** [comment]
@fabiocos OK, thanks, I am glad to hear it is useful.
