### ISSUE TITLE
List of blocked features affecting reco/miniAOD defaults in 94X and 102X

### ISSUE THREAD

**Issue by slava77** [cms-sw/cmssw#25365]
This issue is to keep track of features that are intended for 94X or 102X, but were blocked due to no-change policy violation in the context of RECO or miniAOD workflows.

In most cases, the changes can eventually be accepted if they can be controlled by configuration switches and if the new proposed feature can be enabled for an existing production process/era modifier.
Neither 102X nor 94X presently have a process/era modifier defined for a future re-miniAOD (due to no plans for such processing).

Features affecting only miniAOD
- ECAL bad calib filter update: #25186 (94X) and #25187 (102X) 
    - both can be controlled by a configuration change with a process/era modifier
- FormulaEvaluator fix: #24083 (94X, note this is already part of 102X)
    - this can not be controlled at the configuration level and will probably stay blocked until miniAODv3 campaigns are properly complete (whatever this means)

**Comment by slava77** [comment]
assign reconstruction

**Comment by kpedro88** [comment]
FormulaEvaluator fix: #24083 (94X, note this is already part of 102X)

**Comment by slava77** [comment]
> FormulaEvaluator fix: #24083 (94X, note this is already part of 102X)

Thanks.
I added it to the issue description

**Comment by peruzzim** [comment]
I would add to the list the DeepAK8 discriminators: #24505 @hqucms 
and remove #25187 that is superseded by #25459 (using the new run2_miniAOD_devel modifier)

**Comment by slava77** [comment]
closing now that 94X and 102X updates in reco and miniAOD are out of production scope
