### ISSUE TITLE
Remove hardcoded lastLayerEE, lastLayerFH in HGCal algorithms

### ISSUE THREAD

**Issue by kpedro88** [cms-sw/cmssw#25472]
Based on: https://github.com/cms-sw/cmssw/pull/25411#issuecomment-446176459

Examples where these values are hardcoded:
```
RecoLocalCalo/HGCalRecAlgos/interface/ClusterTools.h | 59 | static const int lastLayerEE = 28;
RecoLocalCalo/HGCalRecAlgos/interface/HGCal3DClustering.h | 88 | static const unsigned int lastLayerEE = 28;
RecoLocalCalo/HGCalRecAlgos/interface/HGCalDepthPreClusterer.h | 43 | static const unsigned int lastLayerEE = 28;
RecoLocalCalo/HGCalRecAlgos/interface/HGCalImagingAlgo.h | 165 | static const unsigned int lastLayerEE = 28;
```
```

RecoLocalCalo/HGCalRecAlgos/interface/HGCal3DClustering.h | 89 | static const unsigned int lastLayerFH = 40;
RecoLocalCalo/HGCalRecAlgos/interface/HGCalDepthPreClusterer.h | 44 | static const unsigned int lastLayerFH = 40;
RecoLocalCalo/HGCalRecAlgos/interface/HGCalImagingAlgo.h | 166 | static const unsigned int lastLayerFH = 40;
```

attn: @rovere @amartelli

**Comment by kpedro88** [comment]
assign upgrade, reconstruction

**Comment by slava77** [comment]
@kpedro88 
was there anything done on this topic?
```git grep "static [^$]* lastLayerEE"``` appears to return the same set as in the issue description using the latest IB CMSSW_11_0_X_2019-05-23-1100

**Comment by kpedro88** [comment]
No, nothing has been done on this topic, nor other pending HGCal cleanup issues.

**Comment by kpedro88** [comment]
Some of these moved to a separate package:
https://github.com/cms-sw/cmssw/blob/dda418599a177a85d76e161c366159746f9a66ae/RecoLocalCalo/HGCalRecProducers/interface/HGCalClusteringAlgoBase.h#L78
and RecoLocalCalo/HGCalRecProducers/plugins/HGCalCLUEAlgo.cc, RecoLocalCalo/HGCalRecProducers/plugins/HGCalImagingAlgo.cc

Also, there are some hardcoded values (not even constants) here:
https://github.com/cms-sw/cmssw/blob/921fbc5bf3a5d3e43f1a89bb621f5b2f03a388ed/RecoLocalCalo/HGCalRecAlgos/interface/HGCalRecHitSimpleAlgo.h#L53
