### ISSUE TITLE
Fastsim fails in CMSSW_10_2_8 

### ISSUE THREAD

**Issue by fabiocos** [cms-sw/cmssw#25513]
A failure in 2018 premix fastsim workflows has been reported by PdmV. For instance the workflow

ZEE_13TeV_TuneCUETP8M1_cfi --datamix PreMix --conditions auto:phase1_2017_realistic --pileup_input dbs:/RelValFS_PREMIXUP17_PU50/CMSSW_10_2_8-PU25ns_102X_mc2017_realistic_v5_FastSim-v1/PREMIX --fast -n 10 --era Run2_2017_FastSim --eventcontent FEVTDEBUGHLT,DQM --procModifiers premix_stage2 --relval 100000,500 -s GEN,SIM,RECOBEFMIX,DIGI:pdigi_valid,DATAMIX,L1,DIGI2RAW,L1Reco,RECO,VALIDATION --datatier GEN-SIM-DIGI-RECO,DQMIO --beamspot Realistic25ns13TeVEarly2017Collision -n 1 --fileout file:step1.root

fails with the message:

%MSG-e MissingProduct:  HybridClusterProducer:uncleanedHybridSuperClusters  18-Dec-2018 15:36:27 CET Run: 1 Event: 1
could not get a handle on the EcalRecHitCollection!
%MSG
----- Begin Fatal Exception 18-Dec-2018 15:36:27 CET-----------------------
An exception of category 'ProductNotFound' occurred while
   [0] Processing  Event run: 1 lumi: 1 event: 1 stream: 0
   [1] Running path 'datamixing_step'
   [2] Calling method for module PreMixingModule/'mixData'
   [3] Calling produce method for unscheduled module EcalRawToDigi/'ecalDigis'
   [4] Processing  Event run: 1 lumi: 1 event: 1 stream: 0
   [5] Running path 'datamixing_step'
   [6] Calling method for module PreMixingModule/'mixData'
   [7] Calling method for module PreMixingModule/'mixData' (probably inside some kind of mixing module)
   [8] Calling method for module EcalRawToDigi/'ecalDigis'
Exception Message:
Principal::getByToken: Found zero products matching all criteria
Looking for type: FEDRawDataCollection
Looking for module label: rawDataCollector
Looking for productInstanceName: 

   Additional Info:
      [a] If you wish to continue processing events after a ProductNotFound exception,
add "SkipEvent = cms.untracked.vstring('ProductNotFound')" to the "options" PSet in the configuration.

----- End Fatal Exception -------------------------------------------------

An update of the tests in runTheMatrix to better catch these problems has been discussed and proposed in #25490 .

@ssekmen any news after the original report of the problem?

**Comment by fabiocos** [comment]
assign fastsim

**Comment by makortel** [comment]
The (2016) FastSim premixing workflows seem to be working fine in 10_2_X IBs.

**Comment by makortel** [comment]
The 2016 FastSim workflows are using `GEN-SIM-DIGI-RAW` as the data tier of the premixing library, while the description quotes `PREMIX` for the attempted 2017. Digging from the history, FastSim indeed used `GEN-SIM-DIGI-RAW` prior to #24184 (that was merged in 10_3_X).

I suppose the fix would be to use `GEN-SIM-DIGI-RAW` as the premixing library format also for 2017 in 10_2_X.

**Comment by makortel** [comment]
Or maybe I spoke too fast, the data tier itself shouldn't have an effect.

**Comment by makortel** [comment]
How was the premixing library `RelValFS_PREMIXUP17_PU50/CMSSW_10_2_8-PU25ns_102X_mc2017_realistic_v5_FastSim-v1/PREMIX` produced?

**Comment by prebello** [comment]
HI @makortel  if you mean the cmsdriver, it is below

SingleNuE10_cfi --conditions auto:phase1_2017_realistic --pileup_input das:/RelValMinBiasFS_13_UP17_ForMixing/CMSSW_10_2_8-102X_mc2017_realistic_v5_FastSim-v1/GEN-SIM-RECO --fast --era Run2_2017_FastSim --eventcontent PREMIX --procModifiers premix_stage1 --relval 100000,500 -s GEN,SIM,RECOBEFMIX,DIGI --datatier PREMIX --pileup AVE_50_BX_25ns

**Comment by makortel** [comment]
Thanks @prebello. Comparing to 250399.0, that one includes `L1,DIGI2RAW` in the steps. Leaving `DIGI2RAW` out (since #24184 is not included in 10_2_X) leads to `rawDataCollector` not being produced and to the failure of this issue.
