### ISSUE TITLE
Alteration of a stored value

### ISSUE THREAD

**Issue by lucastorterotot** [cms-sw/cmssw#25528]
Dear cms devs,

I discovered that a value read from an EDM root file differs from the value computed at run time. Specifically, I have added a printout [here](https://github.com/lucastorterotot/cmssw/blob/from-CMSSW_9_4_11_cand1-bad_output_MET/RecoMET/METProducers/src/PFMETProducer.cc#L69-L70).

This printout gives `RAW MET -20.12624577188` when running CMSSW.
But when I open the output EDM file, `Events->Scan("recoPFMETs_RAWpfMET__TEST.obj.px()", "", "colsize=15 precision=13")` gives `-20.1262435878`.

You may find below a recipe to reproduce this difference. Would you know what is happening?

@cbernet and @GaelTouquet are working on the same analysis and may be interested.

```
cmsrel CMSSW_9_4_11_cand1
cd CMSSW_9_4_11_cand1/src
cmsenv
git cms-init --upstream-only

git cms-merge-topic lucastorterotot:from-CMSSW_9_4_11_cand1-bad_output_MET

scram b

cd JetMETCorrections/Type1MET/test/

# init voms to access input file
voms-proxy-init --rfc --voms cms

cmsRun failed_MET.py
```

**Comment by Dr15Jones** [comment]
@lucastorterotot although in memory we use doubles for `px()`, when we tell ROOT to store the values, we tell it to only store it as precise as a `float` and we tell it to only store the polar coordinates and calculate the cartesian ones when reading back those floats.:

https://github.com/cms-sw/cmssw/blob/master/DataFormats/Candidate/src/classes_def.xml#L6

**Comment by lucastorterotot** [comment]
Thanks @Dr15Jones for your quick answer. I though this double vs float precision mismatch would be less than 10^(-7), but maybe this is also due to the polar to cartesian coordinate switch.
