### ISSUE TITLE
random differences in wf 150.0

### ISSUE THREAD

**Issue by slava77** [cms-sw/cmssw#25570]
This is to follow up on random differences showing up in comparisons in jenkins tests in wf 150.0.

Several recent examples:
- #25567 using CMSSW_10_5_X_2018-12-27-1100 
- #25549 using CMSSW_10_5_X_2018-12-21-1100 and CMSSW_10_5_X_2018-12-25-1100
- #25560 using CMSSW_10_5_X_2018-12-21-1100
- #25536 using CMSSW_10_5_X_2019-01-01-2300
...
- #25620 using CMSSW_10_5_X_2019-01-09-1100 
    - #25620 was meant to fix at least some of the uninitialized value use cases
    - this PR was merged in time for CMSSW_10_5_X_2019-01-11-1100
...
- #25629 using CMSSW_10_5_X_2019-01-11-1100

**Comment by slava77** [comment]
assign reconstruction

**Comment by slava77** [comment]
Still no resolution.
Since @fabiocos asked for a valgrind command, here is what I'm using:

1. run wf 150.0 workflow out of the box (I use 10 events)
2. rerun the individual steps with valgrind 

valgrind command
``` valgrind --tool=memcheck --suppressions=$CMSSW_RELEASE_BASE/src/Utilities/ReleaseScripts/data/cms-valgrind-memcheck.supp --num-callers=20 --xml=yes --xml-file=valgrind-%p.xml --smc-check=all-non-file --track-origins=yes --leak-check=yes --freelist-vol=10000000000 --undef-value-errors=yes --expensive-definedness-checks=yes --malloc-fill=0xa5 --free-fill=0x5a cmsRunGlibC a.py >& a.log & ```

**Comment by fabiocos** [comment]
@slava77 after the merge of #25653 this issue becomes effectively obsolete

**Comment by slava77** [comment]
On 1/16/19 10:30 AM, Fabio Cossutti wrote:
> @slava77
> after the merge of #25653
> this issue becomes effectively obsolete
> 


Well, this is simply invisible for the standard short/jenkins tests, not
obsolete in the scope of available runTheMatrix.py workflows.

**Comment by slava77** [comment]
For some reason valgrind was not helpful here.
After some effort I managed to make repeatable non-reproducibilities and debugged this down to the same file as the known problem already reported in #21313

So, I'm closing this as a duplicate of #21313
