### ISSUE TITLE
Can't access 94X sample ecal/hcalPFClusterIso in 102X

### ISSUE THREAD

**Issue by aminnj** [cms-sw/cmssw#25573]
I'm trying to get a single analysis setup in 102X for various campaigns and found that when I try to read `ecalPFClusterIso` and `hcalPFClusterIso` from pat::Electron in a 102X (10_2_5) release from a 94X sample, I get only 0s. Reading them from a 102X sample is fine. Reading them in a 94X release from a 94X sample is of course also fine. 

I think this is due to https://github.com/cms-sw/cmssw/commit/33ce9c9ef35b6d10fedf6756b29801b006ec132c which moved accessors for this information into GsfElectron (so that older 94X code still compiles because the pat electron inherits from gsf). However, another later commit fills the new data members: https://github.com/cms-sw/cmssw/commit/b7409e13972ae9250911c7b5f3c85750918fe7b2. Unless I'm missing something, does this leave no way to get this information from a 94X sample in a 102X environment? (Maybe @Sam-Harper knows the answer already.)

A quick test:
```python
# /store/mc/RunIIFall17MiniAODv2/ttHToNonbb_M125_TuneCP5_13TeV-powheg-pythia8/MINIAODSIM/PU2017_12Apr2018_new_pmx_94X_mc2017_realistic_v14-v1/50000/00436CBC-6B70-E811-850C-00259075D70C.root
# this works and gives reasonable numbers when in 94X env, but gives only 0s in 102X env
Events.Scan("patElectrons_slimmedElectrons__PAT.obj.hcalPFClusterIso()")
# this works, but gives 0s in 102X env, and crashes in 94X env because the data member doesn't exist
Events.Scan("patElectrons_slimmedElectrons__PAT.obj.pfIsolationVariables().sumHcalClusterEt")
```

**Comment by slava77** [comment]
assign reconstruction,xpog

**Comment by Sam-Harper** [comment]
Hmm no idea why I never wrote an IO rule to do this. I though I had, possibly was having some problems with the fact that variable switches classes (from pat::Electron to reco::GsfElectron)

Done now: https://github.com/Sam-Harper/cmssw/tree/IORulesForPFClusIso_1025. Not entirely sure its 100% legit though, I feel if it was this easy I would have written it already...

@aminnj,  just git cms-merge-topic IORulesForPFClusIso_1025  in  a CMSSW 10_2_5 or greater release. Not extensively tested , the PF cluster isolation values are non-zero now but not actually validated yet to be the correct values so it is buyer beware. 

In a few days will submit a PR, guess we should get this backported to 10_2 as well I suppose.

**Comment by aminnj** [comment]
Hi Sam, that's great! I tried it out and I get values for the two branches that match what I get from 94X (when I use the scan statements above and also when I use a pat::Electron's ecalPFClusterIso() in an EDAnalyzer). Thanks for the quick response!

**Comment by aminnj** [comment]
I'll let Sam give a more complete answer, but for what it's worth, I discovered this originally when trying to calculate "HLT safe" cuts for the SUS RA5 electron ID, which I think in nanoAOD corresponds to:
https://github.com/cms-sw/cmssw/blob/3ebe268b47b1c848fca2aeb2a2379df02b46ebd5/PhysicsTools/NanoAOD/python/electrons_cff.py#L51
https://github.com/cms-sw/cmssw/blob/3ebe268b47b1c848fca2aeb2a2379df02b46ebd5/RecoEgamma/ElectronIdentification/python/Identification/cutBasedElectronHLTPreselecition_Summer16_V1_cff.py#L34

**Comment by Sam-Harper** [comment]
Its not used in any E/gamma supported ID and hence why it was missed. Otherwise we would have seen it. I mean we back port the fix and have a recipe in place. Its only the HLT safe ID which is not supported by E/gamma as its not that HLT safe.

**Comment by fabiocos** [comment]
Indeed this seems to be a show-stopper to the plan of pushing users towards 102X also for 94X sample analysis...

**Comment by Sam-Harper** [comment]
Also thinking about it, probably is a show stopper for 102X for 80X sample analysis (for other reasons). Anyways will try and submit all the PRs by next week. 102X, 103X, 104X and 105X.

**Comment by kpedro88** [comment]
@Sam-Harper 104X will only be used for Phase2, so you can probably skip that one.

**Comment by aminnj** [comment]
Hi Sam, as far as I understand, the IO rules will make 102X fully support 94X samples, but what are the other reasons for 80X?

**Comment by aminnj** [comment]
Makes sense. Thanks for the clarification.

**Comment by slava77** [comment]
@Sam-Harper 
please clarify on the status of making a PR with your fix.
Thank you.

**Comment by Sam-Harper** [comment]
Running the validation now. Takes about an hour or so. After that I'll submit all the PRs. So today. Thanks for the reminder.

**Comment by Sam-Harper** [comment]
Okay submitted now.

**Comment by slava77** [comment]
+1

pull requests with the fix were merged to 102X,103X,104X already.
The issue can be closed.

**Comment by peruzzim** [comment]
+xpog

the fix was merged in 102X and all subsequent releases
