### ISSUE TITLE
trigger muon matching failing for miniaod 10_2_x

### ISSUE THREAD

**Issue by alberto-sanchez** [cms-sw/cmssw#25590]
While looking at input file
/store/data/Run2018D/Charmonium/MINIAOD/PromptReco-v2/000/324/791/00000/F47432B9-3E0A-6947-AFF4-D64C0E2518EC.root 

I found that the trigger matching embedded to the slimmedMuons, fail for a couple of events in the 100 events processed.

Begin processing the 39th record. Run 324791, Event 1000624718, LumiSection 553 on stream 0 at 05-Jan-2019 18:44:52.744 CST
Trigger 430 of 686 : HLT_Dimuon18_PsiPrime_v14: PASS
*** muon     of pt    5.4, eta +2.32, phi +1.53 : relIso =  2.80 => matched
*** trigger object of pt 14.8916, eta 2.4043, phi 1.49121 dr = 0.0928332

The event has two muons, the other is matched correctly.

Begin processing the 85th record. Run 324791, Event 1001374420, LumiSection 553 on stream 0 at 05-Jan-2019 18:44:52.976 CST

Trigger 431 of 686 : HLT_Dimuon25_Jpsi_v14: PASS
*** muon     of pt   54.5, eta +0.06, phi -0.91 : relIso =  0.39 => matched
*** trigger object of pt 17.7715, eta 0.022583, phi -0.990479 dr = 0.087908

The event has 3 muons the other two are correctly matched.

So looks like the cut of deltaR < 0.1 is not enough

https://github.com/cms-sw/cmssw/blob/master/PhysicsTools/PatAlgos/plugins/PATMuonProducer.cc#L277

All the events matched correctly have deltaR values < 0.01, if I use in my code a deltaR < 0.01, at least all events in that file are  matched correctly.

I am using CMSSW_10_2_9.

**Comment by alberto-sanchez** [comment]
ping

**Comment by davidlange6** [comment]
assign hlt

(probably not the right forum for this question)

**Comment by missirol** [comment]
@alberto-sanchez , can this issue be closed, or is it still relevant?

**Comment by alberto-sanchez** [comment]
Not anymore, 10_6 (UL) and up look OK. to me. It can be closed.

**Comment by missirol** [comment]
please close

Okay, thanks!
