### ISSUE TITLE
migrate PPS data format interfaces to drop get prefix in member access methods

### ISSUE THREAD

**Issue by slava77** [cms-sw/cmssw#25690]
this is partly coming out from the discussion in #25465

@forthommel @jan-kaspar

**Comment by slava77** [comment]
assign reconstruction

**Comment by slava77** [comment]
On 1/17/19 7:26 AM, jan-kaspar wrote:
> Informing also @fabferro

> 
> What is the timescale - can this wait after the UL re-reco?
> 

I think that it better be "for UL rereco"
IIUC, almost all of your changes are already submitted as PRs under
review or merged.
This leaves enough time for this mostly technical migration to happen by
some time in April.

> What is the scope - strictly all data formats or only higher-level ones
> (e.g. those in miniAOD)?
> 

all

**Comment by jan-kaspar** [comment]
Somewhat related question - at some point we should like to consistently rename CTPPS to PPS. What would be your timescale recommendation wrt. the UL re-reco?

**Comment by forthommel** [comment]
Indeed, I was about to ask: shall we consider doing these two aesthetic changes in one go? In that sense, it would "allow to break" backward-compatibility of any consumer code and avoid a mixed API state.

**Comment by forthommel** [comment]
Hello @slava77 !
As referenced above, this should now be covered by #28252

**Comment by forthommel** [comment]
Can we safely assume this issue can now be closed with the merging of #28252?

**Comment by perrotta** [comment]
+1
- Fixed by #28252
