### ISSUE TITLE
Crash when reading new LS in LHE dataset and local file

### ISSUE THREAD

**Issue by srimanob** [cms-sw/cmssw#25708]
There are reports about issue on pLHE + GS central production at (*). I've tested and found that if I produce LHE file locally with LS 1 for all events, things run fine. If I start to assign events_per_LS, or using LHE datasets which are centrally produced, I will get crash after running at the new LS.

Do someone have hints? As I check, we have not produced pLHE + GS in central production since last year with 10_X_Y, I'm not sure when the problem started. I think we did not have also RelVals to read from pLHE datasets. Do we have something similar to the problem in release integration test?
It's not clear also why we survive this in wmLHEGS production which we use a lot.

I've put scripts which can reproduce the issue at
/afs/cern.ch/user/s/srimanob/public/ForLHECrashLumi 

+ PPS-RunIIFall18pLHE-00001-Lumi1.root ==> Root file produced with 1 LS for all events
+ PPS-RunIIFall18pLHE-00001-LumiMix.root ==> Root file produced with 100 events/LS
+ PPS-RunIIFall18GS-00001-Lumi1 ==> Script to run PPS-RunIIFall18pLHE-00001-Lumi1.root
+ PPS-RunIIFall18GS-00001-LumiMix ==> Script to run PPS-RunIIFall18pLHE-00001-LumiMix.root 
+ run-102.log ==> Error log

(*)
https://hypernews.cern.ch/HyperNews/CMS/get/prep-ops/6112.html 
https://hypernews.cern.ch/HyperNews/CMS/get/prep-ops/5962/2/1/1/1/1/1.html

**Comment by Dr15Jones** [comment]
Assign generators

**Comment by srimanob** [comment]
The problem seems to originate from
https://github.com/cms-sw/cmssw/blob/master/GeneratorInterface/Pythia8Interface/plugins/Pythia8Hadronizer.cc#L789-L794

fMasterGen->next() can't return properly. I can provide the protection there, but better if GEN expert can have a look and provide the fix which is meaning full in PYTHIA8 sense.

By the way, do GEN expert understands why initializeForExternalPartons needs to happen at every LS boundary? 

@pgunnell

**Comment by srimanob** [comment]
@fabiocos 
It seems this issue stays here very long, maybe because of change in Pythia. How does this issue has never been spot in the integration test? Do we have workflow that start from scratch to read LHE file with events_per_lumi defined or LHE datasets with few LS in the dataset?

**Comment by alberto-sanchez** [comment]
Dear @srimanob thanks for the looking on this. To be honest I am trying to figure out why this happen now and not before. My test have not succed, which means I have not understand quite yet the problem. If you already have a fix, please go ahead. Otherwise it will take more time, at least from my side.

**Comment by fabiocos** [comment]
@alberto-sanchez the crash happens here

https://github.com/cms-sw/cmssw/blob/master/GeneratorInterface/Pythia8Interface/plugins/LHAupLesHouches.cc#L101

when in the LHAupLesHouches setEvent method the map is cleared, it looks there is something wrong with the map infoPtr->eventAttributes , if I check its size before clearing it at the beginning of the new LS it looks strangely large (printing ->size() ).

BTW, I also notice this warning message

%MSG-w LogicError:  Pythia8HadronizerFilter:generator@beginRun  24-Jan-2019 18:20:16 CET Run: 1
::getByLabel: An attempt was made to read a Run product before endRun() was called.
The product is of type 'LHERunInfoProduct'.
The specified ModuleLabel was 'source'.
The specified productInstanceName was ''.

%MSG

**Comment by fabiocos** [comment]
@srimanob the changes directly touching generator's code in between 10_1_0_pre1 and _pre2 are for the addition of Dire and Vincia, which are separate components not used in the failing run for what I can see, and the more suspicious #22069 where LHEEventProduct management (constructor and "=" operator) are modified

**Comment by srimanob** [comment]
@fabiocos I agree with you. Nothing spots me what can be potential issue. But I can reproduce my test when 10_1_0_pre1 can work with pLHE. Anything on patch with pythia8?

**Comment by fabiocos** [comment]
@srimanob I think you refer to http://github.com/cms-sw/cmsdist/pull/3711 , this is the external Dire library, I doubt it enters in any way here. Or what else do you mean?

**Comment by srimanob** [comment]
I think you mean https://github.com/cms-sw/cmssw/pull/22069, not https://github.com/cms-sw/cmssw/pull/22609

**Comment by davidlange6** [comment]
> On Jan 28, 2019, at 2:28 PM, Fabio Cossutti <notifications@github.com> wrote:
> 
> @srimanob @alberto-sanchez as far as I can see in my tests, the code does not crash if one skips https://github.com/cms-sw/cmssw/blob/master/GeneratorInterface/Pythia8Interface/plugins/LHAupLesHouches.cc#L101
> and always reassign the new local map. After the reset of the class, the pointer to the old eventAttributes map is present, but apparently to something that does not behave as a proper map, and any operation on that fails (apart for size that shows an unreasonably big number). BTW it looks to me that in the LHAup base class the pointer infoPtr is not deleted in the destructor.
> 

and it shouldn't be - as infoPtr is not part of the derived class. anyone have a pointer to Pythia8::LHAup?

**Comment by kpedro88** [comment]
https://github.com/cms-externals/pythia8/blob/cms/230/include/Pythia8/LesHouches.h

**Comment by makortel** [comment]
I suspect the following could be happending (just based on browsing code, not tested)
1. `HadronizerFilter<HAD,DEC>::beginLuminosityBlockProduce()` calls `Pythia8Hadronizer::initializeForExternalPartons()` https://github.com/cms-sw/cmssw/blob/38440fe6d435b980776e75ebc045e2b7f2866a38/GeneratorInterface/Core/interface/HadronizerFilter.h#L389
2. `Pythia8Hadronizer::initializeForExternalPartons()` constructs `LHAupLesHouches` https://github.com/cms-sw/cmssw/blob/38440fe6d435b980776e75ebc045e2b7f2866a38/GeneratorInterface/Pythia8Interface/plugins/Pythia8Hadronizer.cc#L603
3. `Pythia8Hadronizer::initializeForExternalPartons()` calls `Pythia8::Pythia::init()` https://github.com/cms-sw/cmssw/blob/38440fe6d435b980776e75ebc045e2b7f2866a38/GeneratorInterface/Pythia8Interface/plugins/Pythia8Hadronizer.cc#L615
4. `Pythia8::Pythia::init()` calls `Pythia8::LHAup::setPtr()`, which sets the `infoPtr` to point to `Pythia8::Info` object that is a member of the `Pythia8::Pythia` object https://github.com/cms-externals/pythia8/blob/08f43c3a6110675bcd9a249f035abd5b751dab0b/src/Pythia.cc#L435
5. `Pythia8::Pythia::init()` calls `LHAupLesHouches::setInit()` https://github.com/cms-externals/pythia8/blob/08f43c3a6110675bcd9a249f035abd5b751dab0b/src/Pythia.cc#L500
6. `LHAupLesHouches::setInit()` constructs the `fEvAttributes` map if the pointer is `nullptr` https://github.com/cms-sw/cmssw/blob/38440fe6d435b980776e75ebc045e2b7f2866a38/GeneratorInterface/Pythia8Interface/plugins/LHAupLesHouches.cc#L46-L50
7. `LHAupLesHouches::setEvent()`  propagates the map to `infoPtr` in https://github.com/cms-sw/cmssw/blob/38440fe6d435b980776e75ebc045e2b7f2866a38/GeneratorInterface/Pythia8Interface/plugins/LHAupLesHouches.cc#L97-L100

Then comes the next lumi. The call chain is the same, except
* in point 2 the destructor of `LHAupLesHouches` is called, that deletes the `fEvAttributes` map https://github.com/cms-sw/cmssw/blob/38440fe6d435b980776e75ebc045e2b7f2866a38/GeneratorInterface/Pythia8Interface/plugins/LHAupLesHouches.h#L36
* in point 7, the `infoPtr->eventAttributes` is likely pointing to the address of the `fEvAttributes` map of the `LHAupLesHouches` of the previous lumi, leading to a segfault. At least I didn't find any other spot in Pythia8 or CMSSW that would set `infoPtr->eventAttributes`. And `infoPtr` itself is always pointing to the same object.

**Comment by alberto-sanchez** [comment]
I have tried to follow @makortel receipt. So in LHAupLesHouches::setEvent() I forced
infoPtr->eventAttributes = fEvAttributes;

doing this we are making sure it points to the current one, even across different LS

**Comment by srimanob** [comment]
Hi @alberto-sanchez @makortel 
Thanks a lot for working on this. I admit that now I am a bit lost. It's not clear to me, what exactly change between 10_1_0_pre1 and 10_1_0_pre2, and let this problem happens. What @makortel mentioned, is it not the same in 10_1_0_pre1? Thx.

**Comment by pgunnell** [comment]
Dear @alberto-sanchez, just to add to the discussion that the fix for this issue is needed for producing any pLHE+GS sample in the current MC campaign. The test we performed when submitting pLHE+GS in a task chain failed with the same error. For now, this is a show stopper for production.

**Comment by fabiocos** [comment]
In my understanding #25850 is effectively a workaround, as the infoPtr is not deleted and re-initialized at the LS boundary. But in principle it should work

**Comment by alberto-sanchez** [comment]
#25850 has been merged

**Comment by alberto-sanchez** [comment]
+1

**Comment by fabiocos** [comment]
@srimanob @efeyazgan @qliphy @alberto-sanchez I want to go back to this fix, that was not fully satisfactory, and I would like also to have a GEN workflow regularly testing this LS boundary. Could you please point me to an example building such an LHE input, from some production campaign for instance?

**Comment by srimanob** [comment]
@fabiocos 
Great to come back to this. Here are what we have in production where 2 steps has been handle separately:
https://cms-pdmv.cern.ch/mcm/public/restapi/requests/get_test/BPH-RunIIFall18pLHE-00004
https://cms-pdmv.cern.ch/mcm/public/restapi/requests/get_test/BPH-RunIIFall18GS-00065

**Comment by diemort** [comment]
Dear @srimanob @alberto-sanchez and all, I'm sorry for reviving this thread, but as the new PPS MC contact, I regret to say that I'm facing the same issue again. I've produced a local pLHE and now I'm trying to run GS step in 10_6_4 as a local test. I've noticed that a workaround has been merged in #25850, but was it propagated to 10_5_X+? Cheers, Gustavo.

**Comment by Dr15Jones** [comment]
@diemort can you post to this issue the relevant parts of the log (e.g. the traceback) for the failing job?

**Comment by diemort** [comment]
Dear @Dr15Jones, attached I send the traceback and below you find the beginning of the error message:

`[silveira@lxplus780 src]$ cmsRun AAMUMU_2pdiss_LPAIR_13TeV_GENSIM_cfg.py 
05-Nov-2019 01:17:52 CET  Initiating request to open file file:/afs/cern.ch/user/s/silveira/work/CTPPSMC/requests/generators/dileptons/SIM/pLHE/CMSSW_9_3_6/src/AAMUMU_2pdiss_LPAIR_13TeV_pLHE.root
05-Nov-2019 01:17:53 CET  Successfully opened file file:/afs/cern.ch/user/s/silveira/work/CTPPSMC/requests/generators/dileptons/SIM/pLHE/CMSSW_9_3_6/src/AAMUMU_2pdiss_LPAIR_13TeV_pLHE.root
%MSG-w LogicError:  Pythia8HadronizerFilter:generator@beginRun  05-Nov-2019 01:18:43 CET Run: 1
::getByLabel: An attempt was made to read a Run product before endRun() was called.
The product is of type 'LHERunInfoProduct'.
The specified ModuleLabel was 'source'.
The specified productInstanceName was ''.`

[failLHE.txt](https://github.com/cms-sw/cmssw/files/3806722/failLHE.txt)

**Comment by Dr15Jones** [comment]
From the log, the crash is
```
#5  0x00007faf3f0e8c15 in Pythia8::ProcessContainer::constructDecays(Pythia8::Event&) () from /cvmfs/cms.cern.ch/slc7_amd64_gcc700/cms/cmssw/CMSSW_10_6_4/external/slc7_amd64_gcc700/lib/libpythia8.so
#6  0x00007faf3f112747 in Pythia8::ProcessLevel::nextLHAdec(Pythia8::Event&) () from /cvmfs/cms.cern.ch/slc7_amd64_gcc700/cms/cmssw/CMSSW_10_6_4/external/slc7_amd64_gcc700/lib/libpythia8.so
#7  0x00007faf3f134e33 in Pythia8::Pythia::next() () from /cvmfs/cms.cern.ch/slc7_amd64_gcc700/cms/cmssw/CMSSW_10_6_4/external/slc7_amd64_gcc700/lib/libpythia8.so
#8  0x00007faf41f026fb in Pythia8Hadronizer::hadronize() () from /cvmfs/cms.cern.ch/slc7_amd64_gcc700/cms/cmssw/CMSSW_10_6_4/lib/slc7_amd64_gcc700/pluginGeneratorInterfacePythia8Filters.so
#9  0x00007faf41f37251 in edm::HadronizerFilter<Pythia8Hadronizer, gen::ExternalDecayDriver>::filter(edm::Event&, edm::EventSetup const&) () from 
```

**Comment by Dr15Jones** [comment]
In addition this crash happens on the first event
```
Begin processing the 1st record. Run 1, Event 1, LumiSection 1 on stream 0 at 05-Nov-2019 01:18:44.855 CET
```
so it can't be a problem related to LuminosityBlock traversal.

**Comment by diemort** [comment]
I see. It may be related to my input file, although it has been produced with the same generator. I'll double-check it.
