### ISSUE TITLE
Verify that uniqueness of named bins is not spoiling HLT monitoring

### ISSUE THREAD

**Issue by fabiocos** [cms-sw/cmssw#25702]
In order to migrate to the newest ROOT where histograms with named bins are merged via the bin's name, not the index, some code updates were proposed to the HLT monitoring code in #25569.
Although technically working, it would be useful to validate the output of this move, ensuring that the obtained histograms are correct according to the original design.

**Comment by fabiocos** [comment]
assign hlt

**Comment by Martin-Grunewald** [comment]
@mtosi @gennai

**Comment by fabiocos** [comment]
@Martin-Grunewald @silviodonato @qliphy is this issue stil present?

**Comment by Martin-Grunewald** [comment]
Looks resolved to me...

**Comment by fabiocos** [comment]
Not sure which validation was performed, anyway the class has evolved quite a lot since the time of this issue. @silviodonato @qliphy unless you have a different advice, but given the answer of @Martin-Grunewald I would close this PR

**Comment by silviodonato** [comment]
+1
