### ISSUE TITLE
kBT_Hex is not a member of TEveBoxSet

### ISSUE THREAD

**Issue by yamaguchi1024** [cms-sw/cmssw#25833]
Hi,

I am getting the error below while building CMSSW, it is something new which I think was introduced few days ago.
```
/build/yuka/genreflex/build-cmssw-tool-confv15/CMSSW_10_5_ROOT6_X_2019-01-30-2300/src/Fireworks/SimData/plugins/FWCaloParticleProxyBuilder.cc: In member function 'virtual void FWCaloParticleProxyBuilder::build(const CaloParticle&, unsigned int, TEveElement&, const FWViewContext*)':
/build/yuka/genreflex/build-cmssw-tool-confv15/CMSSW_10_5_ROOT6_X_2019-01-30-2300/src/Fireworks/SimData/plugins/FWCaloParticleProxyBuilder.cc:57:34: error: 'kBT_Hex' is not a member of 'TEveBoxSet'
    hex_boxset->Reset(TEveBoxSet::kBT_Hex, true, 64);
                                  ^~~~~~~
/build/yuka/genreflex/build-cmssw-tool-confv15/CMSSW_10_5_ROOT6_X_2019-01-30-2300/src/Fireworks/SimData/plugins/FWCaloParticleProxyBuilder.cc:151:25: error: 'class TEveBoxSet' has no member named 'AddHex'; did you mean 'AddBox'?
             hex_boxset->AddHex(TEveVector(centerX, centerY, corners[2]),
                         ^~~~~~
                         AddBox
```

Checking ROOT TEveBoxSet.h, kBT_Hex is indeed not a member of TEveBoxSet and AddHex neither. I thought the definition in cms fork of ROOT, but they also does not exist there. Could someone give me a bit of context of this code?

Thanks!
Yuka - ROOT developer

**Comment by yamaguchi1024** [comment]
@Mourtz could help me maybe?

**Comment by Mourtz** [comment]
Hex support was introduced in this commit/branch https://github.com/osschar/root/commit/5a6dd4f2d64bd0e7f565811464e070d751b0f771 a few months ago. 

@alja @osschar  any ideas?

**Comment by kpedro88** [comment]
assign visualization

**Comment by kpedro88** [comment]
Looks like the PR to upstream ROOT is still open: https://github.com/root-project/root/pull/2985

**Comment by osschar** [comment]
I need to make PRs similar to this https://github.com/cms-sw/root/pull/117 for cms version of root-6.14 and 6.16

**Comment by osschar** [comment]
@smuzaffar, which 6.14 and 6.16 branches of cms-sw/root should I make the PR against?

**Comment by yamaguchi1024** [comment]
Thanks all for help!

I see https://github.com/root-project/root/pull/2985 was merged into master.

**Comment by smuzaffar** [comment]
@osschar , all of cms-sw/root branches has the patch now. As root-project/root#2985 is merged, it would be nice to get this back ported to root 6.16 and 6.14

**Comment by smuzaffar** [comment]
@yamaguchi1024 , as root-project/root#2985 is merged so just rebase your cxxmodule root branch on top of root/master and this should fix CXXMODULE IBs.

**Comment by osschar** [comment]
Yess, Axel didn't want it in 6.16 even though it was still sort of on time (before release but after feature freeze).

Thanks Shahzad! :)

**Comment by yamaguchi1024** [comment]
I think we can close this issue. Thanks all for help!
