### ISSUE TITLE
MET Significance and Covariance Matrix discrepancy between AOD and MiniAOD

### ISSUE THREAD

**Issue by eioannou** [cms-sw/cmssw#25849]
There is a discrepancy in AOD and MiniAOD step for MET significance and covariance matrix values. The MET significance and covariance matrix should be equal for AOD and MiniAOD but they are not. The problem was spotted in hypernews:
https://hypernews.cern.ch/HyperNews/CMS/get/met/580/1.html

The AOD and MiniAOD use the same algorithm to calculate the met significance and covariance matrix values which is the METSignificance.cc (https://github.com/cms-sw/cmssw/blob/master/RecoMET/METAlgorithms/src/METSignificance.cc). However, the only difference between the AOD and MiniAOD is the collections which are used to calculate the MET significance and covariance matrix. In the AOD step, the collections which are used, are selectedPatMuons, selectedPatElectrons, and selectedPatPhotons and in the MiniAOD step, are slimmedMuons, slimmedElectrons, and slimmedPhotons. Those collections are used to calculate the sumEt which is used to compute the values of met significance and covariance, but the value of sumEt is computed differently between AOD and MiniAOD. 

The sumEt is computed differently between two steps, because, in the AOD step, the selectedPatLeptons collections contain a wrong number of source PF candidates  for each lepton. However, in the MiniAOD step, the slimmedLeptons collections have the correct number of source PF candidates for each lepton and the lepton contribution to the sumEt is computed correctly.

I would like to kindly ask experts for a possible solution on this issue.

Thanks in advance,
Emilios (MET Reco contact)

**Comment by Dr15Jones** [comment]
assign reconstruction

**Comment by slava77** [comment]
@eioannou 
please point to the code/configuration that computes the significance in AOD.
Your description mentions \*Pat\* objects, which apparently points to the classic PAT configuration (non-miniAOD).

**Comment by slava77** [comment]
assign analysis,xpog

this seems like not an issue for reco. The problematic place is apparently in the default PAT configuration which is not equal to miniAOD.

**Comment by eioannou** [comment]
> @eioannou
> please point to the code/configuration that computes the significance in AOD.
> Your description mentions *Pat* objects, which apparently points to the classic PAT configuration (non-miniAOD).

Hi @slava77,  the code/configuration that computes the significance in AOD, is called by metProducer_cfi.py  with the "computeSignificance" parameter:
https://github.com/cms-sw/cmssw/blob/34bf02b7fe2571e3be29cc161cf08a0b8edaed7d/PhysicsTools/PatAlgos/python/producersLayer1/metProducer_cfi.py#L50

This configuration calls the PATMETProducer which produces the patMET and computes the singificance and covariance matrix by calling the "getMETCovMatrix(iEvent, iSetup)" and "getSignificance(sigcov, amet)" functions:
https://github.com/cms-sw/cmssw/blob/34bf02b7fe2571e3be29cc161cf08a0b8edaed7d/PhysicsTools/PatAlgos/plugins/PATMETProducer.cc#L100-L104

The code which computes the significance and Covariance Matrix can be found in METSignificance.cc file:
https://github.com/cms-sw/cmssw/blob/34bf02b7fe2571e3be29cc161cf08a0b8edaed7d/RecoMET/METAlgorithms/src/METSignificance.cc#L49-L198

**Comment by eioannou** [comment]
Additionally, if one tries to print the number of Source Candidate Ptrs for each lepton at this part of the code:
https://github.com/cms-sw/cmssw/blob/34bf02b7fe2571e3be29cc161cf08a0b8edaed7d/RecoMET/METAlgorithms/src/METSignificance.cc#L70-L81
 the number of source candidates will be different between AOD and MiniAOD. This affects the computation of sumPt
https://github.com/cms-sw/cmssw/blob/34bf02b7fe2571e3be29cc161cf08a0b8edaed7d/RecoMET/METAlgorithms/src/METSignificance.cc#L102-L116

which will be used to compute the met significance and covariance matrix.
https://github.com/cms-sw/cmssw/blob/34bf02b7fe2571e3be29cc161cf08a0b8edaed7d/RecoMET/METAlgorithms/src/METSignificance.cc#L171-L172

**Comment by ahinzmann** [comment]
Adressed by #29385

**Comment by santocch** [comment]
please close
