### ISSUE TITLE
DD4Hep DT Geometry Builder: implement comments

### ISSUE THREAD

**Issue by fabiocos** [cms-sw/cmssw#25868]
In the review of #25842 a list fo comments was proposed to @ianna by @Dr15Jones and @cvuosalo . We agreed to merge the PR to simplify further work, and address all the comments in a second step. This issue should serve as a reminder for the follow-up.

**Comment by fabiocos** [comment]
assign geometry

**Comment by ianna** [comment]
@cvuosalo and @slomeo - please, have a look at the comments in #25897. They have to be addressed. One in particular: using smart pointers.

**Comment by ianna** [comment]
+1

done
