### ISSUE TITLE
DD Units Macro

### ISSUE THREAD

**Issue by ianna** [cms-sw/cmssw#25875]
are we using Apache/Drill?
https://drill.apache.org/docs/data-type-conversion/#convert_to-and-convert_from

there is also a convert_to (function) in boost...

I would strongly recommend to add say a "DD_" leader at least

anyhow excellent move just after releasing the new cams coding conventions....

_Originally posted by @VinInn in https://github.com/cms-sw/cmssw/pull/25857_

**Comment by ianna** [comment]
assign geometry

**Comment by cvuosalo** [comment]
Should `DetectorDescription/Core/interface/DDUnits.h` be moved to a more generic location, like `FWCore/Common/interface`? It may be needed by several packages.

**Comment by cvuosalo** [comment]
Units that could be added to the header file: _ns, _GeV, _TeV

**Comment by cvuosalo** [comment]
This issue is being addressed by #25967.

**Comment by ianna** [comment]
+1
