### ISSUE TITLE
Problem with GT 105X

### ISSUE THREAD

**Issue by fabiocos** [cms-sw/cmssw#25959]
After the merge of the new GT for 105X in #25929 some test workflows are failing in the IB for problems related to definition or lack of records:
1010.0 
----- Begin Fatal Exception 16-Feb-2019 02:51:37 CET-----------------------
An exception of category 'NoRecord' occurred while
   [0] Processing global begin Run run: 299149
   [1] Calling method for module ECALpedestalPCLworker/'ALCARECOEcalPedestals'
Exception Message:
No "EcalPedestalsRcd" record found in the EventSetup.n
 The Record is delivered by an ESSource or ESProducer but there is no valid IOV for the synchronizatio value.
 Please check 
   a) if the synchronization value is reasonable and report to the hypernews if it is not.
   b) else check that all ESSources have been properly configured. 
----- End Fatal Exception -------------------------------------------------
136.8642 and 136.8643
----- Begin Fatal Exception 16-Feb-2019 03:48:13 CET-----------------------
An exception of category 'EventSetupConflict' occurred while
   [0] Calling EventProcessor::runToCompletion (which does almost everything after beginJob and before endJob)
Exception Message:
two EventSetup Sources want to deliver type="CTPPSRPAlignmentCorrectionsData" label=""
 from record RPRealAlignmentRecord. The two providers are 
1) type="CTPPSRPAlignmentCorrectionsDataESSourceXML" label="ctppsRPAlignmentCorrectionsDataESSourceXML"
2) type="PoolDBESSource" label="GlobalTag"
Please either
   remove one of these Sources
   or find a way of configuring one of them so it does not deliver this data
   or use an es_prefer statement in the configuration to choose one.
----- End Fatal Exception -------------------------------------------------

See https://cmssdt.cern.ch/SDT/html/cmssdt-ib/#/relVal/CMSSW_10_5/2019-02-15-2300?selectedArchs=slc7_amd64_gcc700&selectedFlavors=X&selectedStatus=failed

**Comment by fabiocos** [comment]
assign alca

@tocheng could you please have a look? This is a show-stopper for 10_5_0_pre2

**Comment by fabiocos** [comment]
For the second problem I understand there is a conflict between the GT providing now the record and the XML source invoked in the reco sequence at

https://cmssdt.cern.ch/lxr/source/RecoCTPPS/Configuration/python/recoCTPPS_sequences_cff.py#0009

@slava77 @perrotta FYI

**Comment by tocheng** [comment]
@fabiocos , I think I know what happened to ECAL pedestal. It should be an IOV synchronization problem. For PPS alignment, I will do a further investiagation.

**Comment by tocheng** [comment]
@fabiocos, PR #25961 is submitted to fix the issue

**Comment by fabiocos** [comment]
#25961 indeed solves both the observed crashes, @tocheng thanks
