### ISSUE TITLE
Cleaning of test workflows in PyReleaseValidation

### ISSUE THREAD

**Issue by fabiocos** [cms-sw/cmssw#25981]
During the last update of relval input files a set of some 55 inputs were missing, and during the discussion with PdmV they were mentioned as potentially obsolete and not needed. In order to keep the IB functional they have been reproduced, but this triggers the question whether a review of the present set is needed, and some of these samples can be just dropped.

As of 2019-02-20 there are still two workflows failing in 10_5_X: 10826.0 and 250204.18 .
Furthermore, in 10_2_X there are still 10 failing workflows due to missing input properly defined: https://cmssdt.cern.ch/SDT/html/cmssdt-ib/#/relVal/CMSSW_10_2/2019-02-19-1100?selectedArchs=slc6_amd64_gcc700&selectedFlavors=X&selectedStatus=failed which should be fixed as well.

**Comment by fabiocos** [comment]
assign pdmv

**Comment by fabiocos** [comment]
@prebello @zhenhu on the short term we should try to fix the residual failures (most of those in master are gone, are the two remaining samples being produced? And what about the 10_2_X?).
Then it would be useful to start list what you considered obsolete

**Comment by zhenhu** [comment]
Hi @fabiocos , the residual failures will be fixed by #25955

**Comment by zhenhu** [comment]
Hi @fabiocos , the failures in 10_2_X fastsim will be fixed by #25998
