### ISSUE TITLE
bypassVersionCheck in merging

### ISSUE THREAD

**Issue by srimanob** [cms-sw/cmssw#26017]
Follow up on the report in
https://hypernews.cern.ch/HyperNews/CMS/get/comp-ops/4413.html

The issue seems to happen in merging step which need to set the bypassVersionCheck=true, same as in running config. Thanks @vlimant @amaltaro for suggestion.

We need a solution asap, to allow validation on HLT objects happen for ultra-legacy processing.

@Dr15Jones Could you please comment from framework side?

**Comment by Dr15Jones** [comment]
I commented on the original hypernews thread.

**Comment by srimanob** [comment]
Thx. Then I open the GH issue on wmcore, to add bypassversioncheck on merge step.
