### ISSUE TITLE
Circular dependency in L1 code (PR 25973) to be solved

### ISSUE THREAD

**Issue by fabiocos** [cms-sw/cmssw#26011]
The PR #25973 looks to introduce a circular dependency between tcdsDigis and rawDataCollector that causes two unit tests to fail in the IB (see e.g. https://cmssdt.cern.ch/SDT/cgi-bin/showBuildLogs.py/slc7_amd64_gcc700/www/sun/10.6-sun-00/CMSSW_10_6_X_2019-02-24-0000?utests ). #26003 temporarily reverts it, the addition of the new feature needs a revision to avoid this problem.

**Comment by fabiocos** [comment]
assign l1

@apana FYI

**Comment by apana** [comment]
Dear @fabiocos,

My apologies for taking so long to get back to this issue.  Unfortunately, it's been so long that the log file you pointed me to does not seem to exist anymore, so I don't know what tests failed.  Can you send me instructions on how to run the unit tests in the IB so I can find out which of the tests failed.

Sorry for the trouble

**Comment by fabiocos** [comment]
@apana the failing tests were testTauEmbeddingProducers  and testPhase2PixelNtuple , in TauAnalysis/MCEmbeddingTools and SLHCUpgradeSimulations/Geometry respectively. Just restore your update (```git revert 4024430f99b712ff83df34abc344c3e483d6a8f6``` on top of CMSSW_10_6_X and then recompile Configuration/StandardSequences and L1Trigger/L1TGlobal), and execute the two tests

**Comment by abrinke1** [comment]
Hi @apana ,
Any progress on this?
Andrew, @rekovic , @davignon

**Comment by apana** [comment]
Yes.  I hoping to put the PR in today.

**Comment by apana** [comment]
Hi Andrew. The PR that fixes the issues with the circular dependency has been submitted. It's #26378.  Apologies for the delay. @abrinke1, @fabiocos, @rekovic, @davignon

**Comment by abrinke1** [comment]
Thanks, @apana !

**Comment by peruzzim** [comment]
+xpog

after the revert, I understand this has been properly integrated in #26461

**Comment by fabiocos** [comment]
this issue seems to have been positively solved
