### ISSUE TITLE
Phase 2 geometry updates for L1 TDR

### ISSUE THREAD

**Issue by kpedro88** [cms-sw/cmssw#26071]
See https://github.com/cms-sw/cmssw/tree/master/Configuration/Geometry for geometry descriptions.

Reminder of MTD baseline: D35

- [ ] tracker: T14 (introduced in #25988)
- [ ] muon: M3 (incorporating change from #25701)
- [ ] HGCal: v10 (in preparation) -> C8 ?
- [ ] MTD: ETL modification to accommodate HGCal v10 -> I9 ?

**Comment by kpedro88** [comment]
assign upgrade,geometry,l1

**Comment by kpedro88** [comment]
attn: @fabiocos @boudoul @bsunanda @venturia @ghugo83 @bapavlov @lgray @rovere

**Comment by fabiocos** [comment]
@kpedro88 @lgray @pmeridian for MTD, we have used in production D35, but the chosen  baseline scenario for TDR corresponds to D38. Furthermore, the LYSO definition should be reviewed. Do we want to take the opportunity of a new campaign to test all this?

**Comment by pmeridian** [comment]
Yes I think it will be very useful

**Comment by kpedro88** [comment]
@fabiocos yes, if there are post-TDR updates, let's incorporate them.

**Comment by rekovic** [comment]
@kpedro88 

Is the plan still to do the L1T TDR MC production with the 10_5_X ?
If so then ,

* The latest PRs of HGC geometry by @bsunanda 
https://github.com/cms-sw/cmssw/pull/26078
https://github.com/cms-sw/cmssw/pull/26153
https://github.com/cms-sw/cmssw/pull/26089
https://github.com/cms-sw/cmssw/pull/26212

 * and the PR for RPC geometry
https://github.com/cms-sw/cmssw/pull/25701

need the backport in 10_5_X

**Comment by kpedro88** [comment]
@rekovic the timeline now lines up better with 10_6, so we will use the prereleases for validation and then have a production release.

**Comment by rekovic** [comment]
@kpedro88 
Thanks.

**Comment by kpedro88** [comment]
+upgrade
from my side this is complete (with some debugging still ongoing, but we have relvals and PR/IB tests with the new geometry + workflow)
