### ISSUE TITLE
Bug in Tau_genPartFlav

### ISSUE THREAD

**Issue by IzaakWN** [cms-sw/cmssw#26163]
Dear nanoAOD experts,

We have found some issues related to the gen matching of reconstructed tau objects to gen level muons, where "muon to tau fakes" (`Tau_genPartFlav` should be 2 or 4) are misassigned as "unmatched" or "jet to tau fakes" (`Tau_genPartFlav` = 0).

After discussing with the tau conveners, its seems that this is caused in two different places of the code:

1) https://github.com/cms-sw/cmssw/blob/master/PhysicsTools/NanoAOD/python/taus_cff.py#L165
All statuses of muons should be allowed. By excluding `status==1` muons, the case of a muon with FSR is excluded: `mcStatus = cms.vint32(1)` should become `mcStatus = cms.vint32()`.

2) https://github.com/cms-sw/cmssw/blob/master/PhysicsTools/NanoAOD/plugins/CandMCMatchTableProducer.cc#L93-L94
For prompt muons, and electrons, it is better to use `isPrompt()`, than `isPromptFinalState()`. We have found that sometimes the final `status==1` muon from a radiating muon can be far apart in DeltaR.

This issue was mostly visible in taus reconstructed as DM1, where tau is assumed to decay to one prong plus a neutral pion, where in the case of muons, the neutral pion is presumably coming from the radiated photon. I reported this issue in the Tau POG meeting here (slides 15-25):

https://indico.cern.ch/event/801245/contributions/3330577/attachments/1801702/2938928/Izaak_TauPOG_20190225_v0.pdf

By making both changes described above in a local nanoAOD setup, we seemed to have solved the issue.

Cheers,
Izaak

**Comment by Dr15Jones** [comment]
assign xpog, analysis

**Comment by peruzzim** [comment]
please follow up on cms-nanoAOD#309

**Comment by IzaakWN** [comment]
Just for reference: the PR to the `master-102X` branch of `cms-nanoAOD/cmssw`: https://github.com/cms-nanoAOD/cmssw/pull/305

**Comment by peruzzim** [comment]
+xpog

fix merged in nanoAOD integration repository, will come to upstream CMSSW with the next round of nanoAOD updates

**Comment by santocch** [comment]
+1
