### ISSUE TITLE
Issue with warning from GenEvent::delete_all_vertices when reading 10_6 in 9_4_13_UL1 in all events, but not if read from 10_5

### ISSUE THREAD

**Issue by srimanob** [cms-sw/cmssw#26204]
Hi,

While I'm testing the UL-HLT step with 10_6_0_pre2 and 9_4_13_UL1, I found this warning problem in all events. With the same configurations in 10_5_0, I don't see any warnings.

> Begin processing the 1st record. Run 1, Event 1, LumiSection 1 at 17-Mar-2019 14:47:25.726 CET
> GenEvent::delete_all_vertices strange result ... after deleting all vertices, 
> the particle and vertex maps aren't empty.
>   This probably indicates deeper problems or memory leak in the code.
> Number vtx,particle the event after deleting = 0  207
> Begin processing the 2nd record. Run 1, Event 2, LumiSection 1 at 17-Mar-2019 14:47:31.840 CET
> GenEvent::delete_all_vertices strange result ... after deleting all vertices, 
> the particle and vertex maps aren't empty.
>   This probably indicates deeper problems or memory leak in the code.
> Number vtx,particle the event after deleting = 0  1202

Issue can be reproduced by running from configurations dumped from following cmsDriver(s):
**CMSSW_10_6_0_pre2 or CMSSW_10_5_0**
`cmsDriver.py ZEE_13TeV_TuneCUETP8M1_cfi --conditions auto:phase1_2017_realistic -n 10 --era Run2_2017 --eventcontent FEVTDEBUG -s GEN,SIM --datatier GEN-SIM --beamspot Realistic25ns13TeVEarly2017Collision --python ZEE_13UP17.py --no_exec --fileout file:step1.root`

`cmsDriver.py step2 --conditions auto:phase1_2017_realistic --era Run2_2017 --eventcontent FEVTDEBUGHLT -s DIGI,L1,DIGI2RAW --datatier GEN-SIM-DIGI-RAW-HLTDEBUG --python DIGIPRMXUP17_NoHLT.py -n 10 --no_exec --filein file:step1.root --fileout file:step2.root`

**CMSSW_9_4_13_UL1**
`cmsDriver.py step3 --outputCommand 'keep *_mix_*_*','keep *_genPUProtons_*_*' --conditions auto:phase1_2017_realistic -s HLT:@relval2017 --datatier GEN-SIM-DIGI-RAW-HLTDEBUG --eventcontent FEVTDEBUGHLT --customise_commands 'process.source.bypassVersionCheck = cms.untracked.bool(True)' --era Run2_2017 --python ULHLT17.py -n 10 --no_exec --filein file:step2.root --fileout file:step3.root`

**Comment by fabiocos** [comment]
assign generator,core

**Comment by fabiocos** [comment]
assign generators

**Comment by fabiocos** [comment]
@Dr15Jones this is coming from #26053, if the input files are produced with CMSSW_10_6_0_pre1 they do not show these messages, just merging #26053 on top produces them.

**Comment by Dr15Jones** [comment]
@fabiocos 
I'm not suprised that this fails since the recent pull request drops storing of one of the data members

https://github.com/cms-sw/cmssw/pull/26053/files#diff-46a0c57e1c4b6ed23e683c384c08df4dR11

I would have expected reading the data back in CMSSW_10_5 would also cause the same problem.

**Comment by Dr15Jones** [comment]
@pcanal do you have any ideas if it would be at all possible to write a IO rule for a version greater than the one in a given release?

**Comment by Dr15Jones** [comment]
@fabiocos even if we could write a root IO in CMSSW_9_4 to read CMSSW_10_6 data, there is no promise that we will not be bitten by the bug we found in ROOT 6.12, 6.14.

**Comment by pcanal** [comment]
@Dr15Jones use ```version="[X-]``` where X is the 'first' version number to which the rule need to apply.

**Comment by Dr15Jones** [comment]
@pcanal I tried to create a rule in CMSSW_9_4 with `version="[11]"` but it is not being called.

**Comment by pcanal** [comment]
What is the version number on the file?  What is the version number in memory?

**Comment by Dr15Jones** [comment]
> What is the version number on the file? What is the version number in memory?

On file is 11, in the code for CMSSW_9_4 it is 10.

**Comment by Dr15Jones** [comment]
CMSSW_9_4 uses ROOT 6.10.08-elfike2

**Comment by pcanal** [comment]
this is fairly old for I/O rule support ...

**Comment by Dr15Jones** [comment]
Philippe and I appear to have come to a fix. This requires doing a very small change to CMSSW_10_6 which is incrementing a version number for `HepMC::GenParticle`. Then add a new iorule to CMSSW_9_4 which applies the needed change if that new version of `HepMC::GenParticle` is read. I've tested that combination of changes and it gets rid of the error message.

**Comment by Dr15Jones** [comment]
See #26210 and #26211 .

**Comment by fabiocos** [comment]
@Dr15Jones thanks, I'll check this

**Comment by srimanob** [comment]
Thx @Dr15Jones 
Should this be done also for 8_0?

**Comment by Dr15Jones** [comment]
@srimanob any old release that wants to read files made in CMSSW_10_6 containing those classes will need the change.
