### ISSUE TITLE
Dictionary duplication

### ISSUE THREAD

**Issue by fabiocos** [cms-sw/cmssw#26222]
#26116 was supposed to fix a problem of dictionary duplication, but caused failures in a list of unit tests. The fix #26213 proposed by @smuzaffar was rejected as it was implying to have the definition of a type in one package and the corresponding dictionary in another one, following the comment by @slava77 : 

_"It also looks pretty bad to have a Wrapper dictionary defined in SimDataFormats/TrackingAnalysis while the underlying object stays defined here in DataFormats/RecoCandidate."_

This issue is meant to keep track of the problem and agree on an alternative solution.

**Comment by fabiocos** [comment]
assign core,reconstruction

**Comment by smuzaffar** [comment]
https://github.com/cms-sw/cmssw/pull/26224 should fix this. If needed we are integrate itin DEVEL IBs first
