### ISSUE TITLE
DD4hep: DDG4 package is missing

### ISSUE THREAD

**Issue by ianna** [cms-sw/cmssw#26242]
Hi @smuzaffar, @mrodozov 

We need a DDG4 library:
```
https://github.com/AIDASoft/DD4hep/tree/master/DDG4
```
Should it be defined as a separate tool? dd4hep-g4?

Thanks,

Yana

**Comment by mrodozov** [comment]
I'm building it to see if we can keep it within the same package.

**Comment by smuzaffar** [comment]
@ianna , https://github.com/cms-sw/cmsdist/pull/4820 should address this.
