### ISSUE TITLE
Illegal parameter found in configuration, named skipEvents

### ISSUE THREAD

**Issue by chayanit** [cms-sw/cmssw#26333]
Dear experts,

I have been working on Relval code which taking LHE input stored at EOS and tested them by injection on batch system [*]. But it complained error about illegal parameter found in configuration. The parameter is named: 'skipEvents'. If you look into my cfg file, I don't have this parameter implemented in my code (https://cmsweb.cern.ch/couchdb/reqmgr_config_cache/36d1ae1a37132b62f4c937b3e4d9340f/configFile). But it seems this parameter is set by default in LHESource source code [**] already and made the jobs failed. Is there anyway to fix this issue? We need this urgently for UL validation campaign. 

Thanks in advance.
Best, 
Chayanit for PdmV
[*]
https://cms-unified.web.cern.ch/cms-unified/report/chayanit_RVCMSSW_10_6_0_pre2GluGluHToGG_M125_Pow_MINLO_NNLOPS_py8_13UP17_190329_142932_814
[**]
https://github.com/cms-sw/cmssw/blob/master/GeneratorInterface/LHEInterface/plugins/LHESource.cc#L38

@pgunnell , @zhenhu , @prebello

**Comment by Dr15Jones** [comment]
As stated in the hypernews post on this subject, the parameter is being added to your configuration by the workflow management system. I downloaded the configuration being run on the worknodes and then dumped the configuration of the source
```
[cdj@cmslpc41 matrix]$ python -i PSet.py
>>> print process.source
cms.Source("LHESource",
    fileNames = cms.untracked.vstring('/store/lhe/18334/HJ_nnlops_M125_nojhugen.lhe.xz'),
    firstLuminosityBlock = cms.untracked.uint32(1),
    firstRun = cms.untracked.uint32(1),
    numberEventsInLuminosityBlock = cms.untracked.uint32(50),
    skipEvents = cms.untracked.uint32(0)
)
```
This is not being added by CMSSW. 

I did see that there is a bug in the LHESource since it is supposed to accept `skipEvents` but recent addition of code that validates the LHESource configuration is missing that as an allowed option.

**Comment by Dr15Jones** [comment]
#26334 fixes the validation to properly accept the skipEvents parameter.

**Comment by chayanit** [comment]
Hi @Dr15Jones , thank you for the fix! from your reply on HN, I was also trying to reach some people from operations (I assumed someone from computing) and opened JIRA ticket (https://its.cern.ch/jira/browse/CMSCOMPPR-5297#add-comment) but as I didn't receive any feedback so it seems I went to wrong group. Anyway, thanks again for your help. 
Chayanit

**Comment by fabiocos** [comment]
@chayanit this issue implies a follow-up in #26348

**Comment by chayanit** [comment]
@Dr15Jones , sorry for my ignorance. Does this fix need to be merged first and re-test with new release? Can I test by adding this debugging line in my local area under 10_6_0_pre2 and resubmit batch jobs? I guess not as it failed again https://dmytro.web.cern.ch/dmytro/cmsprodmon/workflows.php?prep_id=CMSSW_10_6_0_pre2__fullsim_noPU_2017_testpLHErelval_rsb-1554351600-GluGluHToGG_M125_Pow_MINLO_NNLOPS_py8_13UP17.

**Comment by Dr15Jones** [comment]
@chayanit you'll have to speak to an expert on McM (or what ever workflow system you use) to see how to get user built code to run. That is not something controlled by CMSSW.

**Comment by prebello** [comment]
@chayanit let's wait for pre4 then. Thank you @Dr15Jones

**Comment by davidlange6** [comment]
lets hope it continues not to be possible to run random code in production.. Releases are there so we know what we run

**Comment by chayanit** [comment]
ok thank you @Dr15Jones
