### ISSUE TITLE
Testing lumi section boundaries in relval

### ISSUE THREAD

**Issue by fabiocos** [cms-sw/cmssw#26348]
In order to probe the FWK capability to run concurrent lumi sections (see https://indico.cern.ch/event/808002/contributions/3363746/attachments/1822355/2981266/Framework_Status_OC_Spring_2019.pdf slide 4), and test in general the code behaviour across boundaries, it would be useful to setup a few workflows (one MC starting from LHE and one real data) where two lumi sections are checked in the job. This may be achieved by properly selecting the first event , keeping a reasonably small number of events in the test. I do not think we have such a test running, PdmV experts are welcome to correct me.

The test should come in two flavours IMO (i.e. 2 parallel workflows for each input sample): in the default configuration of cmsDriver, and activating the new options provided in #25673 by @Dr15Jones , i.e. having 2 concurrent lumis (and multiple threads). For real data I had already found a possible selection, something similar should be used for MC. @srimanob may have a suggestion, in case we had recently a problem with pythia8 crossing the boundary between two lumis for LHE input files.

**Comment by fabiocos** [comment]
assign pdmv

**Comment by Dr15Jones** [comment]
> This seems to me a mixing of 2 topics, to test the framework capability to run concurrent lumi sections, you can start from any type of MC, i.e. add this option to a pythia workflow can be the test also. Is this correct?

There are two parts. One is to test the framework. For that, we already have unit tests which check the correctness. The second is to test all modules used in production to be sure they work as expected when mulitple LuminosityBlocks are running. For that, we need to have tests of each stage (GEN, SIM, DIGI, RECO, etc.).

>  But if EventsPerJob > EventsPerLumi, so basically we can cross the boundary at the single job, and then the test on concurrent lumi can be triggered. Do I understand correctly?

I believe that would work, yes.

**Comment by fabiocos** [comment]
@srimanob I think it would be good to use a workflow starting from LHE, because we had a specific issue there, as you will recall. My idea is to be able to test a whole workflow chain when we cross the lumi boundary in a single test workflow

**Comment by srimanob** [comment]
@Dr15Jones Thanks for clarification.
@fabiocos OK, then I will put it together with LHE PR then.
The pilot test ran fine but --nConcurrentLumis is applied to GS only, I will make it to all step. RunTheMatrix needs to be updated a bit to make it possible to inject with several Lumi in each job.

FYI @franzoni @prebello @zhenhu @pgunnell @chayanit

**Comment by fabiocos** [comment]
The issue is addressed in #27928 for simulation wf and #27937 for data wfs. @srimanob please have a look and provide possible feedback/alternative suggestions.

**Comment by srimanob** [comment]
@fabiocos 
Regarding the original description, we expect also to enable in data, right?
Currently, we process only 1 lumi/job in data relvals (most, or all), Should we modify this?

For MC, it looks OK to me, thanks.

**Comment by fabiocos** [comment]
@srimanob for data workflows I propose #27937 as initial test of lumi boundary crossing in the same job (and concurrent lumi processing).

**Comment by fabiocos** [comment]
@srimanob I believe that a basic handling of this issue has been provided, and I will close it.
