### ISSUE TITLE
Unit tests in TauAnalysis/MCEmbeddingTools fail

### ISSUE THREAD

**Issue by Sam-Harper** [cms-sw/cmssw#26385]
Dear All,

When running the unit tests for TauAnalysis/MCEmbeddingTools

MSG-w XrdAdaptorInternal:  file_open 08-Apr-2019 15:57:35 CEST pre-events
Failed to open file at URL root://cms-xrd-global.cern.ch:1094//store/user/swayand/Emmbeddingfiles/Emmbedding_testInput3.root?tried=+1213llrxrd-redir.in2p3.fr,.
%MSG
----- Begin Fatal Exception 08-Apr-2019 15:57:35 CEST-----------------------
An exception of category 'FallbackFileOpenError' occurred while
   [0] Constructing the EventProcessor
   [1] Constructing input source of type PoolSource
   [2] Calling RootFileSequenceBase::initTheFile()

Closer inspection implies the swayand has left cern and their eos area deleted. 

Can we fix this? Or disable the tests (or is there a workaround).

**Comment by slava77** [comment]
@rmanzoni @steggema @mbluj @swozniewski 
please take a look and forward to someone who can address the issue.
Thank you.

**Comment by rmanzoni** [comment]
@roger-wolf should know better

**Comment by swozniewski** [comment]
I'll ask the embedding guys in our group.

**Comment by janekbechtel** [comment]
The file was indeed removed, however the code that is being tested is deprecated anyhow, so the test can be disabled from our side.

**Comment by slava77** [comment]
I think that the resolution should be to fix the tests.
Otherwise, if the code in  TauAnalysis/MCEmbeddingTools is obsolete and not testable, it should just be removed.

**Comment by Sam-Harper** [comment]
I deleted in it in my PR.

**Comment by slava77** [comment]
On 4/12/19 3:20 PM, Sam Harper wrote:
> I deleted in it in my PR.
> 


if "it" is the unit test only, then that's not what I would prefer (as
expressed in the previous message).

**Comment by janekbechtel** [comment]
Hi,
the test can be fixed by replacing the missing file with the file path
`/store/user/jbechtel/Embedding/CMSSW_UnitTest/preselected.root`

**Comment by Sam-Harper** [comment]
@janekbechtel , please put it in a central area, such as the tau pogs eos space, not on a private area otherwise we'll have the same problem in a few years time

**Comment by janekbechtel** [comment]
I agree, the file is now also available at 
`/store/group/phys_tau/Embedding/preselected.root`
