### ISSUE TITLE
Save ECAL/HCAL energy fractions in MiniAOD for all PF charged hadrons

### ISSUE THREAD

**Issue by steggema** [cms-sw/cmssw#26406]
@peruzzim @rmanzoni @mbluj @slava77 @fgolf 

Following a discussion in today's XPOG meeting, and based on the new possibility to rerun tau reconstruction on MiniAOD input, we propose to save ECAL and HCAL energy fractions for all PF charged hadrons in MiniAOD, which will enable us to have improved e->tauh and muon->tauh rejection for taus reconstructed from MiniAOD. This would be great to have for the MiniAODs for the upcoming ultra-legacy productions already.

Code-wise, it will be straightforward to implement by simply allowing the following condition to pass for all PF charged hadrons (pdgId ±211)

https://github.com/cms-sw/cmssw/blob/e50ff5c684d63017842fc9685e97aeb2e059cbe6/PhysicsTools/PatAlgos/plugins/PATPackedCandidateProducer.cc#L317

How can we check the impact on the MiniAOD event size? Is there a standard procedure?

related to #22594

**Comment by peruzzim** [comment]
> How can we check the impact on the MiniAOD event size? Is there a standard procedure?

I would suggest you first try to run a standard MINIAOD production (take e.g. as a reference one of the ongoing campaigns) on 10000 TTBar events (running on too few events makes the estimate not very reliable, also because of compression).

Then, the standard testing workflows will also test the size automatically.

**Comment by steggema** [comment]
After additional input from @mbluj and discussion with @rmanzoni, we realised that the implementation is not as straightforward as originally thought since we need to save "calibrated" energy fractions and not raw energy fractions (the latter are saved for JetMET's charged hadron calibration workflow), i.e. we need to add data members to make sure we save the fractions since the fractions JetMET saves for isolated charged hadrons are incompatible with what we need, but we need this information for all charged PF candidates including those charged hadrons.

I have prepared a branch that has the needed changes

https://github.com/cms-sw/cmssw/compare/master...steggema:CMSSW_10_6_X_PackedCandidateMoreCaloFractions?expand=1

On an Autumn 18 TTV file with 10000 events, this increases by some margin the size of MiniAOD:

Original:
patPackedCandidates_packedPFCandidates__PAT. 141015 20723.3

New:
patPackedCandidates_packedPFCandidates__PAT. 145227 21915.3

which translates to a 6% increase of the compressed size of this branch and a < 2% increase of the size of the MiniAOD output file.

Please let me know if you have any remarks, otherwise I'll submit a PR after basic tests and we can have a discussion on the implementation there.

**Comment by slava77** [comment]
> which translates to a 6% increase of the compressed size of this branch and a < 2% increase of the size of the MiniAOD output file.

is there some reasonable pre-selection that can be applied to reduce this?
E.g. use some cones around taus in AOD (or jets that used to seed that tau reco)

**Comment by steggema** [comment]
> is there some reasonable pre-selection that can be applied to reduce this?
> E.g. use some cones around taus in AOD (or jets that used to seed that tau reco)

This is surprisingly difficult if we want this tau reconstruction to work generally, e.g. if we want to use it to reconstruct low-pT taus, in which case we cannot make assumptions about taus being reconstructed in AOD or about the pT for jets that seed the reconstruction. We only have a 0.5 GeV minimum pT requirement for charged candidates that enter the tau reconstruction. On the last slide of the following DP note, https://cds.cern.ch/record/2216986/files/DP2016_060.pdf#page=14, you can see the charge-neutral energy asymmetry for 1-prong + pi0 taus, and that it extends to the case where we have a low-pT charged hadron and a high-pT reconstructed pi0. 

With that said, I'm going to test if adding a cut on 0.5 GeV makes a discernible difference. 

Another other idea would be to require the charged particle to be in the cone of a jet with raw pT larger than the minimum pT threshold for which we want the tau reco to work, which may be as low as 10 GeV and may hence have less of an impact than we might hope if we don't want to make the assumption that the tau comes from the identified primary vertex. This latter idea may be difficult to test and it may well have no impact at all at current pileup levels.

Other ideas are of course welcome.

**Comment by steggema** [comment]
Getting back to this:
Increasing the pT threshold to 0.5 GeV reduces the compressed size of the branch so that the increase  is 3.8% (instead of 5.8%). 0.5 GeV is the current threshold used in the reconstruction.
Increasing the pT threshold to 1 GeV reduces the compressed size further such that the increase is 1.6%. This may have sufficiently minor implications on the reconstructed taus for this to be tolerable if we can't afford the 0.5 GeV threshold.
