### ISSUE TITLE
Fix confusing exception message from incorrect ESProduct label

### ISSUE THREAD

**Issue by makortel** [cms-sw/cmssw#26478]
The #26449 has a shortcoming leading to confusing exception messages in case an ESProduct is requested with an incorrect product label. Investigation with @Dr15Jones lead to the following findings

- The implementation of `EventSetupRecord::invalidTokenHandle()` is actually the case for not finding a proxy
  * So e.g. the function could be renamed to `noProxyHandle()` and a new function would be created for `invalidTokenHandle()`
- The `noProxyHandle()` should be called from `EventSetupRecord::getHandleImpl()` if `getTokenIndices_[iToken.index().value()] == std::numeric_limits<int>::max()` before calling `EventSetupRecordImpl::getImplementation()`
  * Then the corresponding check at the beginning of 
 `EventSetupRecordImpl::getImplementation()` (which was throwing the confusing exception message) could be changed to an `assert()`

**Comment by Dr15Jones** [comment]
assign core

**Comment by makortel** [comment]
I can confirm that the last commit (https://github.com/cms-sw/cmssw/pull/26449/commits/466ed9057b319dd03ddcbe716335979672104f8a) in #26449 fixes the exception message.

**Comment by Dr15Jones** [comment]
+1
