### ISSUE TITLE
Improve access to GlobalExtBlk information

### ISSUE THREAD

**Issue by fabiocos** [cms-sw/cmssw#26494]
This issue is meant to keep track of the residual comments made by @peruzzim and myself to @apana about #26461 . I did not want to hold the test of this code, but it should be possibly improved for next future.

**Comment by fabiocos** [comment]
assign l1

**Comment by fabiocos** [comment]
@silviodonato @qliphy FYI this was never closed, please comment if the problem is no more there

**Comment by silviodonato** [comment]
@fabiocos The problem is still there. Is https://github.com/cms-sw/cmssw/pull/33711 what you are asking for?

**Comment by fabiocos** [comment]
@silviodonato I think that should be ok, I close this issue
