### ISSUE TITLE
Increase concurrency for Paths containing EDFilters

### ISSUE THREAD

**Issue by makortel** [cms-sw/cmssw#26517]
The recent experiments with `--runUnscheduled` with GEN-SIM and DIGI-HLT steps
* https://hypernews.cern.ch/HyperNews/CMS/get/edmFramework/3861/1/1/1/1/2.html
* https://hypernews.cern.ch/HyperNews/CMS/get/edmFramework/3861/1/1/1.html
* #26448 

show that the customize function added by `--runUnscheduled` (`FWCore.ParameterSet.Utilities.convertToUnscheduled`) can not really be applied for configurations that have EDFilters. We should nevertheless find way(s) to increase the concurrency with Paths containing EDFilters. Some (not exclusive) ideas include

* Migrate all configurations to Tasks making `converTtoUnscheduled()` unnecessary
* Create a new construct for "Task in a Path" (in construct to the current Task, which is *associated* to a Path)
  * The modules in "Task in a Path" would be run only if all preceding EDFilters in the Path would succeed. The difference wrt. current behavior is that these modules would be run concurrently.
* Create a new python module type for EDProducers that use the Accumulator extension. The `convertToUnscheduled()` should treat such producers as EDAnalyzers.
* `convertToUnscheduled()` could stop moving EDProducers that are in Path after EDFilter to Tasks

**Comment by Dr15Jones** [comment]
assign core

**Comment by makortel** [comment]
https://github.com/cms-sw/cmssw/pull/29024 resolves this issue.

**Comment by makortel** [comment]
+1
