### ISSUE TITLE
Cleaning up Run 1 EGamma ParticleFlow code

### ISSUE THREAD

**Issue by guitargeek** [cms-sw/cmssw#26658]
The old egamma particle flow code has not been used for 5 years but still is strongly entangled with the current particle flow code, which poses an unnecessary maintenance burden.  As discussed with @bendavid, @Sam-Harper, @slava77 and @hatakeyamak, a clean-up of the legacy PF egamma code is on our todo list for the 11XY cycle.

I open an issue on this topic so I can link it in my presentation tomorrow and we can discuss the problems and progress here.

**Comment by guitargeek** [comment]
These would be the changes to remove the old PFEGamma code:

https://github.com/cms-sw/cmssw/compare/master...guitargeek:remove_egamma_pf_legacy

A few workflows are still using the old configuration of the PFProducer via these files:

* HLTrigger/Configuration/python/HLT_FULL_cff.py
* HLTrigger/Configuration/python/HLT_GRun_cff.py
* HLTrigger/Configuration/python/HLT_HIon_cff.py
* HLTrigger/Configuration/test/OnLine_HLT_FULL.py
* HLTrigger/Configuration/test/OnLine_HLT_GRun.py
* HLTrigger/Configuration/test/OnLine_HLT_HIon.py

The first question is how do these configurations need to be supported? Can they be ported to the new PFEGammaAlgo or they strictly require the old algo? I will update this post with the labels of the workflows from the standard matrix tests which fail due to this.

**Comment by hatakeyamak** [comment]
Thank you.

After yesterday's meeting, I am still trying to understand what your concern was about this cleaning.
In the above configurations,
usePFElectrons
usePFPhotons
are both always False in the above HLT configurations, right? (and useEGammaFilters too at HLT). Some relevant lines still just appear in the above HLT config, because they are just dump from HLT I think. Do you still have some question/concern about this?

**Comment by hatakeyamak** [comment]
@jpata

**Comment by hatakeyamak** [comment]
I think a cycle for 11_x has opened, so it may be a good time to go ahead with this cleanup?

**Comment by guitargeek** [comment]
Yes @hatakeyamak, I think it's time now.

Also, everything I said before in this issue was not accurate. I thought it's either the old PFPhotons/PFElectrons or the new PFEgammaFilters, so I first hardcoded the use of the new PFEgammaFilters which didn't work. As @bendavid pointed out in the meeting, it's because they should also be disabled in HLT.

PR will follow suit.

**Comment by hatakeyamak** [comment]
Sounds good!
