### ISSUE TITLE
[CodeFormat] CMS clang-format customization not applied

### ISSUE THREAD

**Issue by smuzaffar** [cms-sw/cmssw#26686]
Thanks to @wddgit ( https://github.com/cms-sw/cmssw/pull/26678#pullrequestreview-234757992 ) , I noticed that CMS clang-format customization (via https://github.com/cms-sw/cmssw/blob/master/.clang-format ) were not applied in the automatic PRs [a] made by @cmsbuild. This effect packages in **dqm, l1, alca, simulation** categories.

  Note that PRs which are already merged did not break functionality, it was just that CMS clang-format customization were not applied.

  code-format build rule has been fixed and will be part of next 10.6.X IB. We will run clang-format for these merged PRs to get this code correctly fixed.

  I am really sorry for the time you have wasted reviewing these PRs.

[a]
https://github.com/cms-sw/cmssw/pull/26619
https://github.com/cms-sw/cmssw/pull/26621
https://github.com/cms-sw/cmssw/pull/26623
https://github.com/cms-sw/cmssw/pull/26624
https://github.com/cms-sw/cmssw/pull/26626
https://github.com/cms-sw/cmssw/pull/26627
https://github.com/cms-sw/cmssw/pull/26628
https://github.com/cms-sw/cmssw/pull/26629
https://github.com/cms-sw/cmssw/pull/26630
https://github.com/cms-sw/cmssw/pull/26631
https://github.com/cms-sw/cmssw/pull/26632

**Comment by smuzaffar** [comment]
assign dqm, l1, alca, simulation

**Comment by fabiocos** [comment]
@smuzaffar is this just affecting the indentation in namespaces?

**Comment by smuzaffar** [comment]
@fabiocos , yes mostly but it also fixes few things e.g.
- line length: instead of default 80 to cms setting 120 e.g. https://github.com/cms-sw/cmssw/pull/26690/files#diff-9ce9a7fb6cc798736e0af0363bce6fd0R29
- Constructor initializers: https://github.com/cms-sw/cmssw/pull/26690/files#diff-9ce9a7fb6cc798736e0af0363bce6fd0R20

Please see https://github.com/cms-sw/cmssw/pull/26690 which properly applied CMS clang-format customizations.

**Comment by smuzaffar** [comment]
closing this as all PRs to fix this formating are now merged in cmssw.
