### ISSUE TITLE
Error in DQM step of Phase 2 relval production

### ISSUE THREAD

**Issue by fabiocos** [cms-sw/cmssw#26727]
This issue is meant to track information in a public place about the problem reported today by PdmV experts of a massive failure of DQMIO merge step in phase2 CMSSW_10_6_0_pre4 RelVal samples:

_We observed that most of the Phase 2 relval sample workflows (for e.g. [1, 2]) encounter Error 8022:
Fatal Root Error: @SUB=TH1Merger::CopyMerge
at DQM step, which affected DQMIO output statistics.

Can you please have a look at the issue?

Many thanks,
Siddhesh Sawant, for PdmV+UPSG group_

[1] https://dmytro.web.cern.ch/dmytro/cmsprodmon/workflows.php?prep_id=CMSSW_10_6_0_pre4__UPSG_Std_2023D41PU200_highPU-1556096145-TTbar_14TeV <https://dmytro.web.cern.ch/dmytro/cmsprodmon/workflows.php?prep_id=CMSSW_10_6_0_pre4__UPSG_Std_2023D41PU200_highPU-1556096145-TTbar_14TeV>

[2] https://dmytro.web.cern.ch/dmytro/cmsprodmon/workflows.php?prep_id=CMSSW_10_6_0_pre4__UPSG_Std_2023D41noPU-1556059831-ElectronGunPt2To100 <https://dmytro.web.cern.ch/dmytro/cmsprodmon/workflows.php?prep_id=CMSSW_10_6_0_pre4__UPSG_Std_2023D41noPU-1556059831-ElectronGunPt2To100>

[3] Error 8022
https://cms-unified.web.cern.ch/cms-unified/report/ssawant_RVCMSSW_10_6_0_pre4ElectronGunPt2To100__2023D41noPU_190424_005155_567#ERROR <https://cms-unified.web.cern.ch/cms-unified/report/ssawant_RVCMSSW_10_6_0_pre4ElectronGunPt2To100__2023D41noPU_190424_005155_567#ERROR>

Full Job log
https://cms-unified.web.cern.ch/cms-unified//joblogs/ssawant_RVCMSSW_10_6_0_pre4ElectronGunPt2To100__2023D41noPU_190424_005155_567/8022/RecoFullGlobal_2023D41MergeDQMoutput/a97935fb-c204-4a88-b18c-8984a68cca65-0-4-logArchive/job/WMTaskSpace/cmsRun1/ <https://cms-unified.web.cern.ch/cms-unified//joblogs/ssawant_RVCMSSW_10_6_0_pre4ElectronGunPt2To100__2023D41noPU_190424_005155_567/8022/RecoFullGlobal_2023D41MergeDQMoutput/a97935fb-c204-4a88-b18c-8984a68cca65-0-4-logArchive/job/WMTaskSpace/cmsRun1/>

An investigation by @fioriNTU @schneiml provides and explanation and a possible workaround in #26722 : the problem is triggered by the definition of the N_HE histograms of Hcal , which for phase2 gets 0 number of bins. The proposed workaround just prevents the DQMSource to throw and exception by catching it. This anyway just hides the problem without addressing it directly.

**Comment by fabiocos** [comment]
assign dqm

**Comment by fabiocos** [comment]
See also #26726 

@schneiml in between pre3 and pre4 there has been a long list of updates, but ROOT did not change https://cmssdt.cern.ch/SDT/ReleaseNotes/CMSSW_10/CMSSW_10_6_0_pre4.html

**Comment by fabiocos** [comment]
@schneiml I understand that #26726 goes in the direction of activating a test according @davidlange6 suggestion, which is good. Nevertheless it looks like that we are not experience massive failures in non phase2 relvals (@prebello @zhenhu please confirm), so the problem here seems to be triggered by some specific configuration not routinely probed.

**Comment by fabiocos** [comment]
@kpedro88 @abdoulline we are routinely running a very limited set of upgrade workflows, is it clear why we did not notice this problem there? The definition of the histogram should be independent on the amount of statistics in the job.

**Comment by davidlange6** [comment]
Is there a merge performed?

**Comment by schneiml** [comment]
@fabiocos Yes, #26726 does basically what David suggested and the result (if my local tests didn't fool me) is basically what I expected: this 0-0 range exists and existed in many places, and while it triggers the chain of problems, it is not why we see these failures now.

Normally these exceptions should never leave ROOT; but somehow they do now, and only in some cases (we had succeeding relvals with 0-0 ranged plots in them, if I saw that correctly).

More technical details: Actually, it might be that in the past we *silently* swallowed these 0-0 range histograms, since our test did not catch them, and ROOT should have gone the `Merge()` route when it (falsely) noticed the inconsistent axis. I didn't check what `Merge()` does in that case, but my guess is that it neither merges correctly nor throws, so we end up with a wrong result and a swallowed error.

So: we should fix all the subsystem code using zero-width ranges, but also that is not at all the cause of the problem in this specific situation.

**Comment by schneiml** [comment]
@davidlange6 no, DQMIO merging is only tested in a unit test with artificial test data, not on real data DQMIO files.

**Comment by fabiocos** [comment]
@davidlange6 @schneiml right, we are just running harvesting on a single file...

**Comment by abdoulline** [comment]
@fabiocos 

Nbins is evaluated (in the DQMOffline/Hcal code in question) from the number of subdetector channels from Geometry. And it's unprotected. I suppose for Phase2 (no HE) it gets 0 
(I've sent a query to @bsunanda, asking for his confirmation).

I'll try to fix it (set appropriate protection) in several places in DQMOffline/Hcal and Validation/Hcalxxx tomorrow.

**Comment by fabiocos** [comment]
@abdoulline yes, my guess is that this is a code run outside the basic configuration for what it was designed, and the lack of protection causes the weird histogram definition (regardless whether this is the origin of the problem or just the symptom of something deeper).

**Comment by fabiocos** [comment]
We are not testing the merge of multiple DQM files in relVals, but the problem is very easily reproducible by splitting the step3 of wf 29034.0 (just to pick the D41 scenario example we are routine testing) into two sets of 5 events, and then trying the merge there with:

```
import FWCore.ParameterSet.Config as cms

process = cms.Process("Merge")

process.source = cms.Source("DQMRootSource",
    fileNames = cms.untracked.vstring('file:step3_inDQM_1.root','file:step3_inDQM_2.root'),
    skipBadFiles = cms.untracked.bool(True)
)
process.maxEvents = cms.untracked.PSet(
    input = cms.untracked.int32(-1)
)

process.options = cms.untracked.PSet(
    numberOfStreams = cms.untracked.uint32(0),
    numberOfThreads = cms.untracked.uint32(1)
)

process.Merged = cms.OutputModule("DQMRootOutputModule",
    dataset = cms.untracked.PSet(
        dataTier = cms.untracked.string(''),
        filterName = cms.untracked.string('')
    ),
    fileName = cms.untracked.string('Merged.root'),
#    logicalFileName = cms.untracked.string('/store/relval/CMSSW_10_6_0_pre4/RelValElectronGunPt2To100/DQMIO/106X_upgrade2023_realistic_v2_2023D41noPU-v1/10000/Merged.root')
)


process.CPU = cms.Service("CPU")


process.CondorStatusService = cms.Service("CondorStatusService",
    tag = cms.untracked.string('_cmsRun1_')
)


process.DQMStore = cms.Service("DQMStore",
    forceResetOnBeginLumi = cms.untracked.bool(True)
)


process.SimpleMemoryCheck = cms.Service("SimpleMemoryCheck")


process.Timing = cms.Service("Timing",
    summaryOnly = cms.untracked.bool(True)
)


process.outputPath = cms.EndPath(process.Merged)

```

getting

```
10-May-2019 00:21:37 CEST  Initiating request to open file file:step3_inDQM_1.root
10-May-2019 00:21:38 CEST  Successfully opened file file:step3_inDQM_1.root
10-May-2019 00:21:44 CEST  Closed file file:step3_inDQM_1.root
10-May-2019 00:21:44 CEST  Initiating request to open file file:step3_inDQM_2.root
10-May-2019 00:21:44 CEST  Successfully opened file file:step3_inDQM_2.root
----- Begin Fatal Exception 10-May-2019 00:21:45 CEST-----------------------
An exception of category 'FatalRootError' occurred while
   [0] Calling InputSource::readRun_
   Additional Info:
      [a] Fatal Root Error: @SUB=TH1Merger::CopyMerge
invalid inputs: 0x7fd9ca15ec00, 0x7fd9c8375c00, 0x7fd9c9907700, (nil) -> do nothing

----- End Fatal Exception -------------------------------------------------
```

It is a pity missing a problem that could be caught with a 5 minutes test...

**Comment by schneiml** [comment]
@fabiocos That lack of testing of the various merging modes in DQM (also harvesting with more than one input file and crossing lumi boundaries) has bothered me since a while, but apparently the merging worked without any trouble for so many years that the DQM team even forgot it existed...

I changed the proposed fix to #26738, since the previous approach does cause a hard-to-estimate risk of corrupting state in ROOT(-objects). It is different in that while  #26722 allowed to merge more histograms than before, #26738 allows less histograms to merge. The affected histograms should all be degenerate cases anyways (some of them pointed out by #26726).

**Comment by fabiocos** [comment]
yesterday we have moved to ROOT 6.14, I have repeated the above test for wf 29034.0 with the following result:

```
10-May-2019 13:51:55 CEST  Initiating request to open file file:step3_inDQM_1.root
10-May-2019 13:51:55 CEST  Successfully opened file file:step3_inDQM_1.root
10-May-2019 13:52:03 CEST  Closed file file:step3_inDQM_1.root
10-May-2019 13:52:03 CEST  Initiating request to open file file:step3_inDQM_2.root
10-May-2019 13:52:03 CEST  Successfully opened file file:step3_inDQM_2.root
%MSG-e MergeFailure:  source 10-May-2019 13:52:03 CEST PostStreamBeginLumi
Found histograms with different axis limits or different labels'HitsVsLUMI_total_PXB_Subdet1' not merged.
%MSG
%MSG-e MergeFailure:  source 10-May-2019 13:52:03 CEST PostStreamBeginLumi
Found histograms with different axis limits or different labels'HitsVsLUMI_total_PXB_Subdet2' not merged.
%MSG
%MSG-e MergeFailure:  source 10-May-2019 13:52:03 CEST PostStreamBeginLumi
Found histograms with different axis limits or different labels'HitsVsLUMI_total_PXB_Subdet3' not merged.
%MSG
%MSG-e MergeFailure:  source 10-May-2019 13:52:03 CEST PostStreamBeginLumi
Found histograms with different axis limits or different labels'HitsVsLUMI_total_PXB_Subdet4' not merged.
%MSG
(...)
```

There are 324 histograms firing complaints, all from Tracker, N_HE from HCAL is not there.
The output merged file is produced.

**Comment by fabiocos** [comment]
... and the harvesting runs smoothly (at least apparently) on top of the merged file.

**Comment by kpedro88** [comment]
I had remarked in the earlier email thread that a commit in ROOT 6.14 changes the condition for the error message, which stops it from occurring in this case:
https://github.com/root-project/root/commit/dab04da2641532d1612b548ce86ebac7cd129392

**Comment by fioriNTU** [comment]
@fabiocos do you think this issue can be closed, given the spontaneous fix with the new ROOT version?

**Comment by fabiocos** [comment]
@fioriNTU the problem in itself is no more present with the move to ROOT 6.14. I think that the issue is still not fully understood, and anyway a check and clean of anomalous definitions of histograms should be considered in the work plan. This might be tracked in a separate issue, do you agree?

**Comment by fioriNTU** [comment]
> @fioriNTU the problem in itself is no more present with the move to ROOT 6.14. I think that the issue is still not fully understood, and anyway a check and clean of anomalous definitions of histograms should be considered in the work plan. This might be tracked in a separate issue, do you agree?

@fabiocos , sorry I have overlooked your proposal. I agree that this issue is not fully understood, so, if you think it is worth, let's keep this open. I do not think that opening a different issue on anomalous definition of histograms would help, I believe that we (DQM) should check more carefully for such cases in the PR review process.

**Comment by fabiocos** [comment]
The problem will be followed in #27528 , as it appears again
