### ISSUE TITLE
Avoid code duplication in SiPixelRawToDigi ErrorChecker's

### ISSUE THREAD

**Issue by perrotta** [cms-sw/cmssw#26731]
In PR #26679 the ErrorChecker class was differentiated for Phase0 and Phase1. 

In it, from the previous single ErrorChecker two classes
- ErrorChecker (for Phase1)
- ErrorCheckerPhase0

were defined, both deriving from a common base class ErrorCheckerBase.

In the implementation of that PR, basically all methods in the base class are virtual, and the specializations are implemented separately for the two derived classes.

However, almost all those methods are identical in the two implementations, and they were just copy-pasted from one class to the other. The only exceptions are the two methods:
- ```checkROC```
- ```errorDetId```

Moreover, ```errorDetId``` is basically identical in the two derived classes: it could also be moved into the base class if one specializes a function which returns ```(DetId(detIdx.rawId).subdetId() == static_cast<int>(PixelSubdetector::PixelBarrel))``` as a bool in Phase0, and just ```true``` in Phase1

In order to avoid a lot of (error prone during maintenance) copy/paste one should move all common methods in the base class, and only specialize in the derived ones the two different ones. In case some specialization in future will be required for the Phase1 code (as the Phase0 one is expected to remain frozen for the time being, excluding the adaptations that will be needed in case of some modification up-hill or in the framework), one could simply specialize that method in the derived class once again.

This should get fixed for the next cycle after the one for the UL release: it will be 11_0

**Comment by perrotta** [comment]
assign reconstruction

**Comment by slava77** [comment]
+reconstruction

via #33884
