### ISSUE TITLE
Migrate ESProducers used in standard workflows to EventSetup consumes

### ISSUE THREAD

**Issue by makortel** [cms-sw/cmssw#26748]
This issue is a successor of #26584 to migrate the rest of ESProducers used in standard workflows to EventSetup consumes. I gathered a list of ESProducers (and the packages they are in) by running `edmConfigDump` to each configuration of the full `runTheMatrix.py`, and grepping for `ESProducer`
https://docs.google.com/spreadsheets/d/1uOJNwGpTtnDC_GA3PZC2bFva9-WqtyCqAmgCwK3bIFo/edit?usp=sharing

The core group will migrate the ESProducers in these packages, unless others step in first.

**Comment by Dr15Jones** [comment]
assign core

**Comment by makortel** [comment]
#26997 had a case where record `CaloTPGRecord` depends on `HcalLutMetadataRcd`, which further depends on `HcalRecNumberingRecord`. I tried to use a token `edm::ESGetToken<HcalTopology, HcalRecNumberingRecord>` to get data from `CaloTPGRecord`, but that didn't work because `DependentRecordImplementation::get()` does not look beyond the first level of dependent-on records.

We decided to take the simple route (i.e. to explicitly get `HcalLutMetadataRcd` from `CaloTPGRecord`), but if we encounter many such cases during the migration, it might be beneficial to rethink a better solution.

**Comment by makortel** [comment]
> We decided to take the simple route (i.e. to explicitly get `HcalLutMetadataRcd` from `CaloTPGRecord`), but if we encounter many such cases during the migration, it might be beneficial to rethink a better solution.

Another example such pattern is in #27012 with `HcalTPGRecord` depending on `HcalDbRecord`, which further depends on `HcalTimeSlewRecord`, and the code gets `edm::ESGetToken<HcalTimeSlew, HcalTimeSlewRecord>` from `HcalTPGRecord`.

**Comment by makortel** [comment]
#27043 is an RFC PR for a case where 2 ESProducers determine in `produce()` which of 6 possible input product labels to use based on the value of magnetic field.

**Comment by makortel** [comment]
> #27043 is an RFC PR for a case where 2 ESProducers determine in `produce()` which of 6 possible input product labels to use based on the value of magnetic field.

#27099 is another RFC PR for a similar case. It as also 2 ESProducers that determine in `produce()` which of 2 possible input product labels to use based on a value of another input product.

**Comment by makortel** [comment]
> We decided to take the simple route (i.e. to explicitly get `HcalLutMetadataRcd` from `CaloTPGRecord`), but if we encounter many such cases during the migration, it might be beneficial to rethink a better solution

Another example is in #27292 (with two ESProducers) with `SiStripBackPlaneCorrectionRcd` depending on `TrackerTopologyRcd`, that further depends on `IdealGeometryRecord`, and the code gets `edm::ESGetToken<GeometricDet, IdealGeometryRecord>` from `SiStripBackPlaneCorrectionRcd`.

**Comment by makortel** [comment]
> #27043 is an RFC PR for a case where 2 ESProducers determine in `produce()` which of 6 possible input product labels to use based on the value of magnetic field.

https://github.com/cms-sw/cmssw/pull/27413 is another RFC PR for a similar case. The PR has one ESProducer, which decides which of the configured payloads to use based on `m_avg_current` member of `RunInfo` ESProduct.

**Comment by Dr15Jones** [comment]
#28120 is part of this

**Comment by makortel** [comment]
All PRs addressing the  ESProducers and packages mentioned in the description have been merged now, so the issue can be closed.

**Comment by makortel** [comment]
> We decided to take the simple route (i.e. to explicitly get `HcalLutMetadataRcd` from `CaloTPGRecord`), but if we encounter many such cases during the migration, it might be beneficial to rethink a better solution.

Another case came up in #28564.
