### ISSUE TITLE
Invalid filename specified in 2021 geometry XML file

### ISSUE THREAD

**Issue by christopheralanwest** [cms-sw/cmssw#26771]
There is a minor problem with the rearranging of files in PR #26535. The line

https://github.com/cms-sw/cmssw/blob/ebb659b4d047d61b577ae18e19dde7a5d95392e8/Geometry/CMSCommonData/python/cmsExtendedGeometry2021XML_cfi.py#L278

specifies an invalid filename. When commit a87a02059bc357cf065cb86f3f3411342b36ed6e renamed `Geometry/MuonSimData/data/2021/muonProdCuts.xml`
 to `Geometry/MuonSimData/data/2021/v1/muonProdCuts.xml`, I suppose the corresponding change should have also been made to `cmsExtendedGeometry2021XML_cfi.py`.

I came across this problem as follows:
```
cmsrel CMSSW_10_6_X_2019-05-10-1100
cd CMSSW_10_6_X_2019-05-10-1100/src
cmsenv
cmsRun $CMSSW_RELEASE_BASE/src/CondTools/Hcal/test/runDumpHcalCond_cfg.py dumplist="LutMetadata" usehardcode=True run=999999 geometry=Extended2021
```
which results in the exception message:
``
edm::FileInPath unable to find file Geometry/MuonSimData/data/2021/muonProdCuts.xml anywhere in the search path.
``
though clearly the exact command isn't relevant.

**Comment by Dr15Jones** [comment]
assign geometry

**Comment by kpedro88** [comment]
@boudoul @ianna FYI

**Comment by boudoul** [comment]
It should be fixed with #26856  - Thanks for reporting.

**Comment by christopheralanwest** [comment]
I'm closing this issue as it has been resolved. @cvuosalo @ianna, you may want to sign off for bookkeeping purposes.

**Comment by ianna** [comment]
+1
