### ISSUE TITLE
Issue with cmsDriver with GEN step only

### ISSUE THREAD

**Issue by srimanob** [cms-sw/cmssw#26812]
If I use the following cmsDriver in 10_6_0,

> cmsDriver.py ZEE_13TeV_TuneCUETP8M1_cfi --conditions auto:phase1_2017_realistic -n 10 --era Run2_2017 --eventcontent FEVTDEBUG --relval 9000,50 --step GEN --datatier GEN --beamspot Realistic25ns13TeVEarly2017Collision --io ZEE_13GENUP17.io --python ZEE_13GENUP17.py --no_exec --fileout file:step1.root --nThreads 4

it gives me

> Traceback (most recent call last):
>   File "/cvmfs/cms.cern.ch/slc7_amd64_gcc700/cms/cmssw/CMSSW_10_6_0/bin/slc7_amd64_gcc700/cmsDriver.py", line 56, in <module>
>     run()
>   File "/cvmfs/cms.cern.ch/slc7_amd64_gcc700/cms/cmssw/CMSSW_10_6_0/bin/slc7_amd64_gcc700/cmsDriver.py", line 28, in run
>     configBuilder.prepare()
>   File "/cvmfs/cms.cern.ch/slc7_amd64_gcc700/cms/cmssw/CMSSW_10_6_0/python/Configuration/Applications/ConfigBuilder.py", line 2120, in prepare
>     self.addStandardSequences()
>   File "/cvmfs/cms.cern.ch/slc7_amd64_gcc700/cms/cmssw/CMSSW_10_6_0/python/Configuration/Applications/ConfigBuilder.py", line 756, in addStandardSequences
>     getattr(self,"prepare_"+stepName)(sequence = getattr(self,stepName+"DefaultSeq"))
>   File "/cvmfs/cms.cern.ch/slc7_amd64_gcc700/cms/cmssw/CMSSW_10_6_0/python/Configuration/Applications/ConfigBuilder.py", line 1374, in prepare_GEN
>     cffToBeLoaded=VtxSmeared[self._options.beamspot]
> KeyError: None

However, if I change 
--eventcontent FEVTDEBUG ==> RAWSIM (we used to have this in GENOnly campaign)
or
--step GEN ==> GEN,SIM
or
--datatier GEN ==> GEN-SIM or random like MINIAODSIM
things run fine. 

It seems to me that if I choose "FEVTDEBUG", the datatier needs to have the keyword "SIM". The cmsDriver run fine with any random datatier with SIM, like PHAT-CRAZY-SIM. Is this by intension?

**Comment by fabiocos** [comment]
assign pdmv

**Comment by fabiocos** [comment]
@srimanob I think you observe just the effect of

https://cmssdt.cern.ch/lxr/source/Configuration/Applications/python/cmsDriverOptions.py#0217

alternatively you may just add ```--mc``` to your command and it should work. I believe this should be updated to add both ```GEN``` and ```LHE``` as steps that trigger the ```isMC``` definition

**Comment by fabiocos** [comment]
```
13:37 cmsdev25 7077> $CMSSW_BASE/bin/slc7_amd64_gcc700/cmsDriver.py ZEE_13TeV_TuneCUETP8M1_cfi --conditions auto:phase1_2017_realistic -n 10 --era Run2_2017 --eventcontent FEVTDEBUG --relval 9000,50 --step GEN --datatier GEN --beamspot Realistic25ns13TeVEarly2017Collision --io ZEE_13GENUP17.io --python ZEE_13GENUP17.py --no_exec --fileout file:step1.root --nThreads 4 --mc
GEN,ENDJOB
Step: GEN Spec: 
Loading generator fragment from Configuration.Generator.ZEE_13TeV_TuneCUETP8M1_cfi
Step: ENDJOB Spec: 
Config file ZEE_13GENUP17.py created
```

**Comment by srimanob** [comment]
Big thanks, Fabio.
Yes, the warning shows clearly, but I skipped the line
`We have determined that this is real data (if not, rerun cmsDriver.py with --mc)`

I put the PR to add more options to trigger isMC, https://github.com/cms-sw/cmssw/pull/26818
