### ISSUE TITLE
Make Phase2-only parameters not mandatory in Phase1 configs

### ISSUE THREAD

**Issue by perrotta** [cms-sw/cmssw#26846]
Summarizing here the request posted in a past thread in the reconstruction hn, see https://hypernews.cern.ch/HyperNews/CMS/get/recoDevelopment/1615.html, con contributions from @fwyzard and @VinInn :

All Phase 2 developers should make the Phase 2-only parameters *not* mandatory in the modules configurations.

An example is ```PixelThresholdClusterizer``` which in CMSSW 10.4.x requires these parameters to be defined:
```C++
    doPhase2Calibration( conf.getParameter<bool>("Phase2Calibration") ),
    thePhase2ReadoutMode( conf.getParameter<int>("Phase2ReadoutMode") ),
    thePhase2DigiBaseline( conf.getParameter<double>("Phase2DigiBaseline")
),
    thePhase2KinkADC( conf.getParameter<int>("Phase2KinkADC") ),
```

That is wrong: the Run 2 configurations should never have to defined such parameters
If the Phase 2 reconstruction needs additional or different parameters, they should be required only if some kind of "Phase 2" mode is enabled.

More in general, having to specify additional or different parameters makes the configurations less understandable. For example, in a Phase 2 configuration, are the non-Phase2-named parameters used or not? And in a non-Phase 2 configuration, why would I need to specify them, except maybe for a single configuration switch to choose Phase 1 vs Phase 2?

While maintaining the request for the future developments, this issue is meant to keep track of the removal of those instances in current CMSSW, perhaps starting from the already mentioned ```PixelThresholdClusterizer```.

**Comment by perrotta** [comment]
assign reconstruction, upgrade

**Comment by mmusich** [comment]
@avartak @emiglior FYI

**Comment by slava77** [comment]
It looks like we can make some use of the new PSet feature recently introduced in #27191 . It is available from CMSSW_11_0_X_2019-06-18-1100 and should appear  starting from 11_0_0_pre3.

**Comment by slava77** [comment]
> It looks like we can make some use of the new PSet feature recently introduced in #27191 . It is available from CMSSW_11_0_X_2019-06-18-1100 and should appear starting from 11_0_0_pre3.

Now in the SWGuide: https://twiki.cern.ch/twiki/bin/view/CMSPublic/SWGuideAboutPythonConfigFile#Parameters_without_defaults

**Comment by tvami** [comment]
Hi @perrotta looking at the cc files
https://github.com/cms-sw/cmssw/blob/master/RecoLocalTracker/SiPixelClusterizer/plugins/PixelThresholdClusterizer.cc#L73-L91
it seems now the `fillPSetDescription()` method resolved this issue, right?

**Comment by tvami** [comment]
@cmsbuild , please close 
 * see https://github.com/cms-sw/cmssw/issues/26846#issuecomment-1396258494
