### ISSUE TITLE
self-subtractions : possible bugs

### ISSUE THREAD

**Issue by slava77** [cms-sw/cmssw#26913]
as a follow up to https://github.com/cms-sw/cmssw/pull/26868#issuecomment-495163121
I made some egrep of the CMSSW code base for repeated patterns [1]. 

This is not exhaustive (e.g. function calls with arguments like ```x(y) - x(y)``` are not covered) and perhaps a better tool/parsing should be added.
@fabiocos @smuzaffar perhaps we even have something automated? Clang static analyzer report does not pick up these as issues.

The results are as follows:
- [ ] RecoLocalMuon/GEMSegment/plugins/ME0SegAlgoRU.cc already reported https://github.com/cms-sw/cmssw/blob/ba500c0d38075ac562531832c437568ab6e2dfc0/RecoLocalMuon/GEMSegment/plugins/ME0SegAlgoRU.cc#L325-L327 
    - @jshlee please check
- [x] RecoPixelVertexing/PixelLowPtUtilities/src/ValidHitPairFilter.cc https://github.com/cms-sw/cmssw/blob/ba500c0d38075ac562531832c437568ab6e2dfc0/RecoPixelVertexing/PixelLowPtUtilities/src/ValidHitPairFilter.cc#L220-L224
    - @makortel @VinInn please check
    - this was "fixed" in #26972
- [x] RecoBTag/ImpactParameter/plugins/IPProducer.h https://github.com/cms-sw/cmssw/blob/ba500c0d38075ac562531832c437568ab6e2dfc0/RecoBTag/ImpactParameter/plugins/IPProducer.h#L393-L398
    - it looks like a comma is missing. @arizzi @ferencek  please check for b-tag needs.
    - this was fixed in #27000 
- [x] in Fireworks/Calo/src/FWTauProxyBuilderBase.cc https://github.com/cms-sw/cmssw/blob/ba500c0d38075ac562531832c437568ab6e2dfc0/Fireworks/Calo/src/FWTauProxyBuilderBase.cc#L95-L99
    - perhaps should be first-second? @alja please check
    - this was fixed in #27009

[1] ```egrep -R "(\b[a-zA-Z0-9\.]+\b)()[^A-Za-z=0-9,/:-]*-[^A-Za-z0-9>=%($]*\1[^_A-Za-z0-9]|(\b[a-zA-Z0-9\.]+\b)[^A-Za-z=0-9,/:)]*-[^A-Za-z0-9>=%($]*\1[^_A-Za-z0-9]"```

**Comment by makortel** [comment]
> RecoPixelVertexing/PixelLowPtUtilities/src/ValidHitPairFilter.cc
> https://github.com/cms-sw/cmssw/blob/ba500c0d38075ac562531832c437568ab6e2dfc0/RecoPixelVertexing/PixelLowPtUtilities/src/ValidHitPairFilter.cc#L220-L224
> 

On a quick look this class is a good candidate for dead code (not used anywhere in CMSSW, last non-technical-migration change was in 2010 (in 2008 for this specific fragment).

**Comment by ferencek** [comment]
>     * [ ]  RecoBTag/ImpactParameter/plugins/IPProducer.h https://github.com/cms-sw/cmssw/blob/ba500c0d38075ac562531832c437568ab6e2dfc0/RecoBTag/ImpactParameter/plugins/IPProducer.h#L393-L398
>       
>       
>       * it looks like a comma is missing. @arizzi @ferencek  please check for b-tag needs.

Hi @slava77, indeed, this looks like a bug and a comma is missing there. The ghost track feature is not really in active use which probably explains why this went unnoticed all this time.

**Comment by slava77** [comment]
> > ```
> > * [ ]  RecoBTag/ImpactParameter/plugins/IPProducer.h https://github.com/cms-sw/cmssw/blob/ba500c0d38075ac562531832c437568ab6e2dfc0/RecoBTag/ImpactParameter/plugins/IPProducer.h#L393-L398
> >   
> >   
> >   * it looks like a comma is missing. @arizzi @ferencek  please check for b-tag needs.
> > ```
> 
> Hi @slava77, indeed, this looks like a bug and a comma is missing there. The ghost track feature is not really in active use which probably explains why this went unnoticed all this time.

What would be the right fix?
It seems like the error = 0 (current incidental default) has a special meaning.
Grepping for similar calls, I see other defaults like ```Measurement1D(-1, 1)``` in 
https://github.com/cms-sw/cmssw/blob/ba500c0d38075ac562531832c437568ab6e2dfc0/RecoBTag/SecondaryVertex/src/GhostTrackComputer.cc#L78-L85

Would this be a more correct value than what will be from a simple addition of a comma ``Measurement1D(-1, -1)```?

**Comment by ferencek** [comment]
`Measurement1D` is used to store a track impact parameter and related uncertainty. The impact parameter can be signed so generally speaking `Measurement1D(-1.0, 1.0)` could be a valid entry. `Measurement1D(-1., -1.)` is clearly an invalid entry because of the negative error but the problem with this is that `Measurement1D::significance()` would return 1 which could look completely legitimate. Personally, I would prefer `Measurement1D(0., -1.)`.

**Comment by alja** [comment]
@slava77  The phi range check in the FWTauProxyBuilderBase.cc is not necessary.  I have submitted #27001 for this.

**Comment by slava77** [comment]
Currently, only the issue in RecoLocalMuon/GEMSegment/plugins/ME0SegAlgoRU.cc is remaining.

@nickmccoll  perhaps you know what would be a correct fix here
https://github.com/cms-sw/cmssw/blob/ba500c0d38075ac562531832c437568ab6e2dfc0/RecoLocalMuon/GEMSegment/plugins/ME0SegAlgoRU.cc#L325-L327

**Comment by perrotta** [comment]
> Currently, only the issue in RecoLocalMuon/GEMSegment/plugins/ME0SegAlgoRU.cc is remaining. 
> @nickmccoll perhaps you know what would be a correct fix here

Well, the correct fix is obvious, that is replace one of the ```h1``` with ```h2```
What has actually to be checked before implementing it blindly is to asses its effect on the physics performance, which will likely be touched because this ```areHitsCloseInEta``` is used in the segment building. Here some hint or investigations from the GEM local reco experts is needed.

**Comment by jshlee** [comment]
> > Currently, only the issue in RecoLocalMuon/GEMSegment/plugins/ME0SegAlgoRU.cc is remaining.
> > @nickmccoll perhaps you know what would be a correct fix here
> 
> Well, the correct fix is obvious, that is replace one of the `h1` with `h2`
> What has actually to be checked before implementing it blindly is to asses its effect on the physics performance, which will likely be touched because this `areHitsCloseInEta` is used in the segment building. Here some hint or investigations from the GEM local reco experts is needed.

yes it should be the diff of h1 and h2, we will look into the effects on segment reco.

**Comment by nickmccoll** [comment]
@slava77 wow, that is a bad bug on my part! This is a part of the seeding, and is effectively a vertex constraint that was supposed to be, but apparently not, implemented. I would think that fixing it should just reduce the background rate (e.g. wide angle punch throughs), but it should be double checked.

**Comment by slava77** [comment]
@nickmccoll @jshlee please update on the status of checking/applying the fix in ME0SegAlgoRU.cc is .
Thank you.

**Comment by slava77** [comment]
assign reconstruction

**Comment by jshlee** [comment]
@slava77 - will update now

**Comment by perrotta** [comment]
+1
- All cases look like as having been fixed now
