### ISSUE TITLE
Phase 2 geometry cleanup in 11_X

### ISSUE THREAD

**Issue by kpedro88** [cms-sw/cmssw#26938]
In the new release cycle, it is time to clean up the proliferation of Phase 2 geometries. The full list is here: https://github.com/cms-sw/cmssw/tree/master/Configuration/Geometry

Notes:
* D17 was HGCal TDR baseline
* D35 was MTD TDR baseline
* D41 is L1 TDR baseline (ongoing)

Here are my proposals for what to keep. These are intentionally quite limited. Any request to add another subdetector version added to this list will require a *strong* argument of why any studies with that subdetector version can't be done in the approved L1 TDR release cycle 10_6_X.

Tracker: (@emiglior @ghugo83)
* T6, T14
* if T15 will supersede T14 we can keep it as well, but let's decide soon

HGCal: (@rovere @cseez @bsunanda)
* C4, C6, C8
* C6 only to keep HF nose alive - it could be replaced by a v10 geometry w/ the HF nose

Muons:
* M2, M3
* no other variations present, M2 is outdated but was used for MTD TDR

MTD: (@fabiocos @lgray @pmeridian)
* I5, I9
* let's finally remove all geometries w/out MTD, since it is approved now

Outer, forward: (all needed)
* O2, O3
* F2, F3

This would reduce us to the two most recent baselines (D35 and D41), plus an upgrade to D31 (HF nose) to include MTD and maybe HGCal v10 (as suggested above).

When this large deprecation is implemented, the workflow numbers will also be reset.

**Comment by kpedro88** [comment]
assign upgrade,geometry

**Comment by fabiocos** [comment]
@kpedro88 I think this is something we should do in 11_0_X, in any case for possible legacy comparison studies older releases with older geometries are not disappearing. We need anyway to be careful in not creating problems to possible ongoing further checks.

**Comment by kpedro88** [comment]
@emiglior @ghugo83 please advise about T15 and any other tracker considerations

**Comment by ghugo83** [comment]
Hi,
Hmm take care with T5, I would say it is important to keep it for reference, since it was used for the Phase II Tracker TDR.
T11 could be removed (and re-introduced later based on latest Tracker geometry, with 25x100 -> 50x50).
T14 <-> T15 comparison has not been fully discussed yet.

**Comment by kpedro88** [comment]
@ghugo83 in general, we aren't keeping old TDR workflows alive forever in the latest releases. The D4 geometry used for the tracker TDR has already been deprecated and removed a while ago. These geometries are still present in the old releases if more studies are needed. In the end, we will only build one version of the Phase 2 detector, so indefinite support for dozens of past variations is not feasible or desirable.

**Comment by ghugo83** [comment]
Hi @kpedro88 , Yes if you can guarantee an old release containing T5 stay alive that will be fine.

**Comment by ghugo83** [comment]
Hmm I see D17 (HGCal TDR) and D19 are still using T5.

**Comment by kpedro88** [comment]
@ghugo83 yes, this issue proposes removing those workflows in the 11_X cycle, as described in the first post. They will remain available in the older release cycles.

**Comment by ghugo83** [comment]
@kpedro88 Ok, thanks.

**Comment by fabiocos** [comment]
@ghugo83 @emiglior old releases will clearly stay untouched, the proposal of @kpedro88 refers to 11_0_X and the future

**Comment by kpedro88** [comment]
@emiglior what was the feedback from the meeting?

**Comment by emiglior** [comment]
@kpedro88 

since the Tracker design is not yet frozen, there are concerns about removing T5 geometry in case we are asked (in a future review) to compare results with TDR layout vs. results with current layout using the same configuration of simulation and local reco (and we chronically lack manpower for backporting new developments....)

About T15 vs. T14, T15 is heavier but more realistic. It will be superseeded, but right now is the state-of-the-art.

**Comment by kpedro88** [comment]
@emiglior an alternative proposal:
a. acknowledging that the only geometry/workflow currently containing T5 has a several-year-old version of HGCal and no MTD
b. also acknowledging that keeping dozens of ancient Phase 2 geometries active in the latest development release is not a viable path for progress (and in fact actively interferes with many ongoing efforts), especially if the only reason is nebulous fear of some future review question
c. we can keep T5 as an "active" subdetector option (i.e. not deprecated), but not include it in any full geometry or workflow for the time being. If such a review question eventually comes to pass (I suspect it won't), it is relatively straightforward to prepare a full geometry and workflow to answer it.

**Comment by emiglior** [comment]
@kpedro88 do you mean to keep in the release the "T5" files of Geometry/TrackerCommonData (etc.) but remove the definitions and workflows of 2023D17 and 2023D19?

**Comment by kpedro88** [comment]
Yes, exactly. Other components of D17 (e.g. the old HGCal) will definitely be removed, so those workflows will not function anyway.

**Comment by kpedro88** [comment]
As another item to address in this issue, we should stop using "2023" for Phase2 workflows (since that year will actually be Run3) and move to "2026" or something even further in the future.

**Comment by boudoul** [comment]
for the 2023--> 2026, do you want me to take care (as I did for 2021 ?) -

**Comment by kpedro88** [comment]
@boudoul thanks, but I think I can just take care of it when I implement all the geometry deprecations (once we have a final agreement in this issue).

**Comment by boudoul** [comment]
perfect thanks

**Comment by emiglior** [comment]
> @emiglior an alternative proposal:
> a. acknowledging that the only geometry/workflow currently containing T5 has a several-year-old version of HGCal and no MTD
> b. also acknowledging that keeping dozens of ancient Phase 2 geometries active in the latest development release is not a viable path for progress (and in fact actively interferes with many ongoing efforts), especially if the only reason is nebulous fear of some future review question
> c. we can keep T5 as an "active" subdetector option (i.e. not deprecated), but not include it in any full geometry or workflow for the time being. If such a review question eventually comes to pass (I suspect it won't), it is relatively straightforward to prepare a full geometry and workflow to answer it.

@kpedro88 I think this proposal is fine
@pwittich, @ghugo83  what do you think?

**Comment by ghugo83** [comment]
@emiglior Yes, that's fine.

**Comment by fabiocos** [comment]
@kpedro88 @emiglior @ghugo83 I have a small update for MTD, used to produce material budget plots, that I would like to keep in the release as starting point for next developments. Of course in principle I might get it without a scenario, but seen this discussion, I believe it might make sense to have a D43 that is D41 (the most recent production state of the art) + this updated MTD + tracker T15 (claimed to be the present tracker state of the art).

**Comment by emiglior** [comment]
@fabiocos @pwittich @ghugo83  please keep in mind that the main motivation for introducing T15 "now" was to check using RelVals the effect on tracking of some of the proposed engineering solutions.
Some of these solutions evolved in the meanwhile and the effort is to keep the material bill in between the T14 and T15 scenarios.
