### ISSUE TITLE
Reduce cpu for DeepTauID 2017v2

### ISSUE THREAD

**Issue by perrotta** [cms-sw/cmssw#27119]
With PR #26796 the DeepTauID 2017v2 is going to be integrated into the miniAOD production chain. The physics reach of that ID outperforms the one of the other tau IDs. 

Unfortunately, the timing performance is not yet fast enough for having it run in normal nanoAOD productions. According to what reported in that PR the performance with 1k ttbar events is:

Memory:
- size of three training files: 2.9+0.85+0.85=4.6MiB (was 21MiB in 2017v1);
- memory consumption: on top of DeepJet: 6.4MiB or 21.5 MiB standalone. The difference between the two comes mainly from executing pat::PackedCandidate::dzError() method which triggers unpacking of track covariance matrix and at smaller extend from initialization of TensorFlow. Full information on memory usage from IGProf can be accessed at this link: http://mdidomen.web.cern.ch/mdidomen/cgi-bin/igprof-navigator/changes_PR_126/DeepTau_memory_usage/;

CPU timing:
- Full timing of a simple test workflow is 0.11s/event with DeepTauId::getPredictions 0.088s/event; details at at http://mdidomen.web.cern.ch/mdidomen/cgi-bin/igprof-navigator/changes_PR_126/DeepTauCPU_TT;
- Full timing of miniAOD workflow is 1.06s/event with DeepTauId::getPredictions 0.082s/event; details at http://mdidomen.web.cern.ch/mdidomen/cgi-bin/igprof-navigator/changes_PR_126/DeepTau_MiniAOD.

This issue is meant to keep track of the improvement in the timing of that ID: it can be considered as completed as soon as its timing performance is deemed enough to be included in the central nanoAOD productions

@mbluj @swozniewski

**Comment by perrotta** [comment]
assign reconstruction

**Comment by arizzi** [comment]
@perrotta I'm not sure I understand the comparison what is the input to the 0.11s/ev ? what are the differences with the 1.06s/ev workflow?

**Comment by perrotta** [comment]
@arizzi all the details are in the (longish) thread of #26796
As far as I understand 0.11s/ev is for a test job which only runs the tau id's; while 1.06s/ev is calculated with a full re-miniAOD job  with 1000 events in a ttbar sample. The important point to notice, according to me, is that the new ID would consume some 8% of the overall CPU time taken by miniAOD.

**Comment by mbluj** [comment]
> @arizzi all the details are in the (longish) thread of #26796
> As far as I understand 0.11s/ev is for a test job which only runs the tau id's; while 1.06s/ev is calculated with a full re-miniAOD job with 1000 events in a ttbar sample. The important point to notice, according to me, is that the new ID would consume some 8% of the overall CPU time taken by miniAOD.

Yes, I confirm what @perrotta wrote above: the point is that DeepTauID as it is now consume ~8% of CPU time needed to build MiniAOD as got with ttbar sample of 1k events. For other samples fraction of CPU time consumed by DeepTauID is different (number and type of tau candidates and jets counts), but on the same ballpark.

**Comment by slava77** [comment]
+reconstruction

via #28128 (and perhaps some other updates)

http://cms-reco-profiling.web.cern.ch/cms-reco-profiling/circles/piechart.php?local=false&dataset=CMSSW_12_0_0_pre3%2Fslc7_amd64_gcc900%2F11834.21%2Fstep4_circles&resource=time_thread&colours=default&groups=packages&threshold=0

<img width="991" alt="image" src="https://user-images.githubusercontent.com/4676718/126677269-4c8c9dbe-a5a9-400b-9020-3a734a60ace6.png">


deepTau takes 3.6%
