### ISSUE TITLE
Stitched: remove use of PhysicsTools/Utilities/scripts/edmCopyPickMerge from FWCore/Integration/test scripts

### ISSUE THREAD

**Issue by gartung** [cms-sw/cmssw#27176]
edmCopyPickMerge used by test script FWCore/Integration/test/run_TestSwitchProducer.sh

**Comment by gartung** [comment]
@Dr15Jones @smuzaffar

**Comment by makortel** [comment]
@Dr15Jones Do we have a (generic) configuration/way for merging files under FWCore?

**Comment by Dr15Jones** [comment]
> Do we have a (generic) configuration/way for merging files under FWCore?

Since the necessary configuration is so trivial, I've always just written it by hand.

**Comment by makortel** [comment]
Done in #27229.

**Comment by Dr15Jones** [comment]
assign core

**Comment by Dr15Jones** [comment]
+1
