### ISSUE TITLE
Use of DQMStore in SiStripBadModuleFedErrESSource

### ISSUE THREAD

**Issue by makortel** [cms-sw/cmssw#27178]
The `SiStripBadModuleFedErrESSource` reads histograms from DQMStore in its `produce()` method
https://github.com/cms-sw/cmssw/blob/7b107049ae78e1b2b01945ed3aa9a0c36245aec3/CalibTracker/SiStripESProducers/plugins/real/SiStripBadModuleFedErrESSource.cc#L121-L130

This approach is problematic because
- framework does not guarantee that the DQMStore would be filled at "begin run" time (by the DQM input source) **before** the ESSource `produce()` is called
  * even if it works today
  * the only way to guarantee proper ordering is to read the run product (which ES modules can not do)
- if DQMStore becomes module-local and delivers all the MonitorElements via ED products, the ES module has no way to access those products

**Comment by makortel** [comment]
Some possible ways to fix the issue
- make the ESSource to read the necessary information directly from a file
- transform the ESSource to an EDProducer that reads the histograms as run products and provides the information downstream as run products

**Comment by fabiocos** [comment]
assign alca

@mmusich FYI

**Comment by mmusich** [comment]
@fabiocos thanks, we are already in contact with Matti about this.

> make the ESSource to read the necessary information directly from a file

I am not sure how this can work when the DQM is run together with the rest of reconstruction at Tier-0 jobs. Can you clarify?

**Comment by makortel** [comment]
> > make the ESSource to read the necessary information directly from a file
> 
> I am not sure how this can work when the DQM is run together with the rest of reconstruction at Tier-0 jobs. Can you clarify?

You're right, in that mode it would not work.

**Comment by mmusich** [comment]
This issue has been addressed in https://github.com/cms-sw/cmssw/pull/27565.
@christopheralanwest please sign the issue so it can be closed.

**Comment by christopheralanwest** [comment]
+1
