### ISSUE TITLE
Which format for associating int to jets (ValueMap/TagInfo/...)

### ISSUE THREAD

**Issue by zucchett** [cms-sw/cmssw#27286]
Dear framework experts,

we are considering a novel approach for b-tagging very high pT jets based on the pixel hit multiplicity. We need to add the pixel hit multiplicity information to AOD, which can be limited to 20 integers per jet (4 pixel layers x 5 jet-pixel hit association cones - the char data type can also be used to save space). Before implementing these features, we would like to check with you what would be the most convenient way to proceed:
1) filling 20 different ValueMaps
2) developing a dedicated TagInfo class, and store the 20 integers in the TagInfo object
3) is there a better alternative to 1 and 2?

@msommerh, and from BTV @mverzett , @kskovpen, @XavierAtCERN, @smoortga are also involved and interested in these developments.

**Comment by Dr15Jones** [comment]
assign core, reconstruction

**Comment by perrotta** [comment]
Dear @zucchett, will you or one of the other proponents be able to join or connect to the reco meeting tomorrow (https://indico.cern.ch/event/830302), so that you can shortly present the issue and have it discussed there? There is still room in agenda, and I can add a slot for you.

**Comment by zucchett** [comment]
Yes, we can prepare few slides to explain our case and discuss the solutions.

**Comment by perrotta** [comment]
I have added a 10' slot for you at the end of tomorrow's reco meeting agenda for discussing this issue:
https://indico.cern.ch/event/830302/

**Comment by perrotta** [comment]
+1
- This issue was solved by the discussion in the reco meeting and hn, ending up with PR #27738, merged since CMSSW_11_0_0_pre7

**Comment by smuzaffar** [comment]
resolved
