### ISSUE TITLE
Move PR tests to 2021 workflows in CMSSW_11

### ISSUE THREAD

**Issue by Martin-Grunewald** [cms-sw/cmssw#27372]
With PR ttps://github.com/cms-sw/cmssw/pull/27331, the HLT menu used for @relval2018 becomes the stripped down Fake2 menu (as was done for @relval2017 about a year ago),
no longer GRun (full menu).
There is now @relval2021 which points to the GRun menu incorporating Run-3 changes.
Thus, PR validation workflows should be changed to use 2021 workflows, rather than 2018 workflows (CMSSW_11 only).

**Comment by kpedro88** [comment]
assign pdmv

**Comment by AdrianoDee** [comment]
please close
