### ISSUE TITLE
Consolidate MTD modifiers

### ISSUE THREAD

**Issue by kpedro88** [cms-sw/cmssw#27450]
After #27449, the "tile" option for MTD is no longer exercised anywhere. I propose:
* merging the modifiers phase2_timing_layer and phase2_timing_layer_bar
* removing the modifier phase2_timing_layer_tile
* simplifying the naming of Phase2 top-level Eras (since only Eras appended with "_timing_layer_bar" are used)
* removing any extraneous code that supports the "tile" option
* removing code only used for the old, TP implementation, e.g. FTLDigitizer and related classes (maybe even related data formats)

attn: @fabiocos @lgray @pmeridian @casarsa

**Comment by kpedro88** [comment]
assign upgrade

**Comment by fabiocos** [comment]
@kpedro88 once the tile scenario is removed what you propose makes sense. As it will stay available in older releases I think it should be ok, anyway I would like to understand from @pmeridian @lgray whether they envisage lates studies using that scenario (I doubt but...)

**Comment by casarsa** [comment]
@kpedro88 @fabiocos @pmeridian @lgray To further clean and simplify the MTD code, could we also consider removing the old SimpleFTLDigitizer?

**Comment by kpedro88** [comment]
@casarsa I highly encourage removing any code that is unused/unneeded after the workflow cleanup

**Comment by kpedro88** [comment]
The first part of this issue is addressed in #28387 

MTD developers should handle the actual code changes (removing unneeded features/classes/etc.)

**Comment by kpedro88** [comment]
+upgrade
resolved by #28915
