### ISSUE TITLE
Circular dependency in SimG4Core between Application and GFlash

### ISSUE THREAD

**Issue by Dr15Jones** [cms-sw/cmssw#27451]
SimG4Core/Application links with SimG4Core/GFlash while within G4Flash we have these includes

```
src/GflashEMShowerModel.cc:#include "SimG4Core/Application/interface/SteppingAction.h"
src/GflashHadronShowerModel.cc:#include "SimG4Core/Application/interface/SteppingAction.h"
```

In order for UBSAN to work, SimG4Core/GFlash needs to link with the library that has the definition of SteppingAction (in order to get the type info).

**Comment by Dr15Jones** [comment]
assign simulation

**Comment by civanch** [comment]
@Dr15Jones , thanks, I recently also see this and want to fix asap.

**Comment by civanch** [comment]
Fixed in #27452

**Comment by Dr15Jones** [comment]
@civanch please sign this issue as the problem has been fixed.

**Comment by civanch** [comment]
+1
