### ISSUE TITLE
Memory over read in HGCalGeomTools::radius

### ISSUE THREAD

**Issue by Dr15Jones** [cms-sw/cmssw#27514]
The Address Sanitizer has found that HGCalGeomTools::radius is reading beyond the ends of memory region of a container. The exact problem is here:

https://github.com/cms-sw/cmssw/blob/44d504fe304526fc5bce2b42416d3a5d58fb0fb5/Geometry/HGCalCommonData/src/HGCalGeomTools.cc#L133

The problem is `zFront[ik + 1]` for the case that ik is the index to the last element of the container. then `ik+1` is beyond that end.

As a guess, it seems like the correct logic would be
```C++
if (ik < zFront.size()+1 && std::abs(z - zFront[ik + 1]) < tol_)
```
In that way, if the above is true, then doing `++ik` still gives a valid index into the container.

**Comment by Dr15Jones** [comment]
assign geometry

**Comment by Dr15Jones** [comment]
@bsunanda  FYI

**Comment by cvuosalo** [comment]
@Dr15Jones: Wouldn't the correct logic be:
```
if (ik < (zFront.size() - 1) && std::abs(z - zFront[ik + 1]) < tol_)
```
Or am I missing something?

**Comment by Dr15Jones** [comment]
@cvuosalo My code was wrong, yours is correct. What I had meant to write was
```C++
if ( (ik+1) < zFront.size() && std::abs(z - zFront[ik + 1]) < tol_)
```

**Comment by bsunanda** [comment]
@Dr15Jones @cvuosalo Adding a fix in the next PR

**Comment by Dr15Jones** [comment]
A different radius method is having the same sort of problem 
https://cmssdt.cern.ch/SDT/cgi-bin/logreader/slc7_amd64_gcc700/CMSSW_11_0_ASAN_X_2019-07-19-2300/pyRelValMatrixLogs/run/20434.0_TTbar_14TeV+TTbar_14TeV_TuneCUETP8M1_2026D41_GenSimHLBeamSpotFull14INPUT+DigiFullTrigger_2026D41+RecoFullGlobal_2026D41+HARVESTFullGlobal_2026D41/step2_TTbar_14TeV+TTbar_14TeV_TuneCUETP8M1_2026D41_GenSimHLBeamSpotFull14INPUT+DigiFullTrigger_2026D41+RecoFullGlobal_2026D41+HARVESTFullGlobal_2026D41.log#/

**Comment by Dr15Jones** [comment]
The new problem is
https://github.com/cms-sw/cmssw/blob/8ca5ef6c74ee954287c5352dd8ad84abe2c0adaf/Geometry/HGCalCommonData/src/HGCalGeomTools.cc#L26

where zf1 is an iterator to the last element. So `*(zf1+1)` is dereferencing off the end.

The debugger has
```
(gdb) print zFront1
$8 = std::vector of length 4, capacity 4 = {3210.5, 3625.0999999999999, 4103.1000000000004, 4352.1000000000004}
```
with the arguments being
```
#1  0x00007fffdba69403 in HGCalGeomTools::radius (zf=4353.8000000000011, zb=4354.9000000000015, zFront1=std::vector of length 4, capacity 4 = {...}, rFront1=std::vector of length 4, capacity 4 = {...}, 
    slope1=std::vector of length 4, capacity 4 = {...}, zFront2=std::vector of length 4, capacity 4 = {...}, rFront2=std::vector of length 4, capacity 4 = {...}, slope2=std::vector of length 4, capacity 4 = {...}, flag=1, 
    zz=std::vector of length 0, capacity 0, rin=std::vector of length 0, capacity 0, rout=std::vector of length 0, capacity 0)
```

going up the stack, the call is
```
#2  0x00007fffbdef20c8 in DDHGCalHEAlgo::constructLayers (this=0x619000326e80, module=..., cpv=...) at src/Geometry/HGCalCommonData/plugins/DDHGCalHEAlgo.cc:230
```
with the arguments being
```
230	          HGCalGeomTools::radius(zz - hthick,
231	                                 zz + hthick,
232	                                 zFrontB_,
233	                                 rMinFront_,
234	                                 slopeB_,
(gdb) print zz
$10 = 4354.3500000000013
(gdb) print hthick
$11 = 0.55000000000000004
```

**Comment by bsunanda** [comment]
I am trying to address this in PR #27557

**Comment by cvuosalo** [comment]
@Dr15Jones: I believe this issue is resolved, since PR #27557 has been merged. Can this issue be closed?

**Comment by Dr15Jones** [comment]
@cvuosalo do you have permision to do the 'plus 1'? That is what is we normally wait for.

**Comment by cvuosalo** [comment]
+1
