### ISSUE TITLE
add "data" files to the data repository for PPS simulation

### ISSUE THREAD

**Issue by mundim** [cms-sw/cmssw#27599]
Hello

PPS simulation needs a data dir to be added in the repository. It is located at:
/eos/home-m/mundim

with name (and path)

SimPPS/PPSPixelDigiProducer/data

The related code is under review in the ongoing PR number 27559.

Thanks

**Comment by smuzaffar** [comment]
@mundim , data repository https://github.com/cms-data/SimPPS-PPSPixelDigiProducer now exists. Please make a PR there for your data files.

**Comment by mundim** [comment]
@smuzaffar, git says I don't have privileges to push.

**Comment by davidlange6** [comment]
Right - you need to make a pull request instead (as is the case for all the cms-sw repositories)

**Comment by mundim** [comment]
Don't I have to add the data files first? Or just an initial PR? thanks.

**Comment by mundim** [comment]
Another doubt: it is not clear what would be the path for the data files, should I add the files in the top level or create the desired path? thxs.

**Comment by kpedro88** [comment]
Files should go in the top level.

The procedure to add the files is:
1. make a fork of the repository
2. clone your fork locally
3. add the files, commit, push
4. send a PR to the upstream repo from your branch in your fork

**Comment by mundim** [comment]
Done. Thank you very much.
