### ISSUE TITLE
problems with git cms-init

### ISSUE THREAD

**Issue by barriap** [cms-sw/cmssw#27654]
Hi,

since from yesterday I'm facing issues with git cms-int in order to setup the CMSSW_10_3_1 release on lxplus.
The check connectivity step seems to be done then when it swtches to the new branch 'from-CMSSW_10_3_1' it takes a long time and then it fails with this error:
error: RPC failed; curl 18 transfer closed with outstanding read data remaining
fatal: The remote end hung up unexpectedly
Any help it's really appreciated to fix it.

Best

Patrizia

**Comment by kpedro88** [comment]
GitHub appears to be throttling https requests intermittently.

You can use the `--ssh` flag to use ssh connectivity, which is more reliable. If you want to enable this permanently:
```
git config --global cms.protocol ssh
```

Please note, this requires having your ssh key associated with your GitHub account.

**Comment by barriap** [comment]
Thanks finally it seems to work
