### ISSUE TITLE
remove EcalDeadChannelRecoveryNN and related from CMSSW code base

### ISSUE THREAD

**Issue by slava77** [cms-sw/cmssw#27657]
This is a follow up to the developments coming with  #27175.

EcalDeadChannelRecoveryNN was never deployed for production use.
A new solution is available now and it should replace the NN variant, it came with #27175 .
Given no plan for further use or support of the (old) NN variant, it can be removed safely after #27175 is integrated.

@crovelli @argiro @zghiche @fcouderc
@nancymarinelli @taroni

**Comment by slava77** [comment]
assign reconstruction

**Comment by nancymarinelli** [comment]
Hi Slava,
you should trash also all what's in 
/afs/cern.ch/work/n/nancy/private/testDeadChannelDev/CMSSW_11_0_X_2019-07-28-2300/src/RecoLocalCalo/EcalDeadChannelRecoveryAlgos/test

All that stuff is connected to NN. And we had to make it compile each time
Best,
  Nancy

@crovelli @argiro @zghiche @fcouderc
@taroni



On 31/07/19 17:45, Slava Krutelyov wrote:
> This is a follow up to the developments coming with  #27175.
>
> EcalDeadChannelRecoveryNN was never deployed for production use.
> A new solution is available now and it should replace the NN variant, it came with #27175 .
> Given no plan for further use or support of the (old) NN variant, it can be removed safely after #27175 is integrated.
>
> @crovelli @argiro @zghiche @fcouderc
> @nancymarinelli @taroni
>
>

-- 
________________________________________
Nancy Marinelli
Research Associate Professor
University of Notre Dame, IN, US
CERN, Bdg 40/3-A01, 1211 Geneva
SWITZERLAND
Phone +41-22-76-70809
fax +41-22-76-78940

**Comment by slava77** [comment]
+1

done in #27986
