### ISSUE TITLE
switch case fallthrough in TrackerAlignment_PayloadInspector.cc

### ISSUE THREAD

**Issue by Dr15Jones** [cms-sw/cmssw#27718]
The gcc 9 compiler is complaining about TrackerAlignment_PayloadInspector.cc have a swtich statement in which the case statements _fallthrough_ from one case statement to the next. See

https://github.com/cms-sw/cmssw/blob/master/CondCore/AlignmentPlugins/plugins/TrackerAlignment_PayloadInspector.cc#L600-L631

If the code is intended to _fallthrough_ please add `[[fallthrough]]` to the end of each case statements, e.g.
```C++
          case AlignmentPI::BPix:
            Xbarycenters[0] += (ali.translation().x());
            Ybarycenters[0] += (ali.translation().y());
            Zbarycenters[0] += (ali.translation().z());
            nmodules[0]++;
            [[fallthrough]];
          case AlignmentPI::FPix:
```

if the intention was not to fall through, then please add `break;` to the end of each case statement. E.g.

```C++
          case AlignmentPI::BPix:
            Xbarycenters[0] += (ali.translation().x());
            Ybarycenters[0] += (ali.translation().y());
            Zbarycenters[0] += (ali.translation().z());
            nmodules[0]++;
            break;
          case AlignmentPI::FPix:
```

**Comment by Dr15Jones** [comment]
FYI @mmusich

**Comment by Dr15Jones** [comment]
assign db

**Comment by mmusich** [comment]
Fixed in https://github.com/cms-sw/cmssw/pull/27722
