### ISSUE TITLE
AAA Service not active on DQMIO files

### ISSUE THREAD

**Issue by fioriNTU** [cms-sw/cmssw#27724]
After some investigations related to this JIRA ticket https://its.cern.ch/jira/browse/CMSTZ-427, we found that for DQMIO files the AAA servise is not working 

According to Dirk *, is due to the fact that DQMIO files are not in EDM format, and a new feature in CMSSW is required to have it working.

The DQM group is really interested to have this feature implemented, DQMIO datasets can be moved on the grid as any other PD, it should be hence possible to run Harvesting jobs on remote files (also without using crab).

* 
https://its.cern.ch/jira/browse/CMSTZ-427?focusedCommentId=2760341&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-2760341

**Comment by fabiocos** [comment]
assign core

**Comment by Dr15Jones** [comment]
assign dqm

**Comment by Dr15Jones** [comment]
@dan131riley could you look into this?

**Comment by dan131riley** [comment]
First check is whether I understand the problem, the description is a bit vague. I'm guessing that what it means is that DQMRootSource, somewhere in the vicinity of this open:

https://github.com/cms-sw/cmssw/blob/e43377ba7c7fb6b146bcccd58bb89bf32a1ce41d/DQMServices/FwkIO/plugins/DQMRootSource.cc#L771

needs some additional logic such that, if the open fails, it tries the fallbackDataCatalog that routes to the AAA global redirectors.  Does that sound right?  A sample job config would be useful.

(adding @hufnagel as I'm sure he doesn't get enough email already)

**Comment by Dr15Jones** [comment]
@bbockelm FYI

**Comment by fioriNTU** [comment]
@dan131riley , you can test using the code here /afs/cern.ch/user/c/cmst0/public/wrappersTier0Config/harvestWrapper.sh , it will require few inputs:

run: 323940 
PD: /ZeroBias/Run2018D-PromptReco-v2/DQMIO 
LFN: /store/data/Run2018D/ZeroBias/DQMIO/PromptReco-v2/000/323/940/00000/9F411A2F-9C94-D54F-894B-83D60BF55C41.root

**Comment by bbockelm** [comment]
@dan131riley - yes, that's correct.  The integration with AAA is usually done via the fallback mechanism.  File open fails, an exception is thrown, and the exception is suppressed until the fallback succeeds (or fails).

**Comment by dan131riley** [comment]
PR #28064 has been opened to address this.

**Comment by fioriNTU** [comment]
Many thanks @dan131riley !
