### ISSUE TITLE
GBRForest does not support TMVA BDT with "Transform Normalize" option

### ISSUE THREAD

**Issue by jpata** [cms-sw/cmssw#27741]
Hi,

I noticed that the nice GBRForest tool does not support a TMVA BDT that does in-place input variable normalization and gives incorrect / different results compared to TMVA.

Here's how the TMVA XML looks like with normalization:

```xml
  <Transformations NTransformations="2">
    <Transform Name="Normalize">
...
      <Class ClassIndex="2">
        <Ranges>
          <Range Index="0" Min="4.7203484922647476e-02" Max="2.2953859863281250e+03"/>
          <Range Index="1" Min="-2.3887534141540527e+00" Max="2.3851680755615234e+00"/>
          <Range Index="2" Min="-9.9999880790710449e-01" Max="9.9999982118606567e-01"/>
          <Range Index="3" Min="-3.1415925025939941e+00" Max="3.1415898799896240e+00"/>
          <Range Index="4" Min="3.0020778656005859e+01" Max="2.4525869140625000e+03"/>
          <Range Index="5" Min="-4.6972441673278809e+00" Max="4.6995148658752441e+00"/>
          <Range Index="6" Min="3.0000017166137695e+01" Max="1.9576102294921875e+03"/>
          <Range Index="7" Min="1.9073486328125000e-06" Max="9.2963638305664062e+00"/>
          <Range Index="8" Min="2.3841857910156250e-07" Max="3.1415905952453613e+00"/>
          <Range Index="9" Min="1.4612787246704102e+01" Max="7.8207197265625000e+03"/>
          <Range Index="10" Min="2.2545950487256050e-02" Max="1.1295844726562500e+03"/>
          <Range Index="11" Min="-1.4998049736022949e+01" Max="1.4996270179748535e+01"/>
          <Range Index="12" Min="1.1500000762939453e+02" Max="1.3499995422363281e+02"/>
          <Range Index="13" Min="2.0000000000000000e+00" Max="8.0000000000000000e+00"/>
          <Range Index="14" Min="4.0018019080162048e-01" Max="6.5247039794921875e+00"/>
        </Ranges>
      </Class>
    </Transform>
  </Transformations>
```

TMVA implements it here: https://github.com/root-project/root/blob/master/tmva/tmva/src/VariableNormalizeTransform.cxx#L151

Should I make a PR with an updated GBRForest, is it of interest to core CMSSW? We can also think of a small test suite to compare GBR evaluations to TMVA. If this is not useful/relevant/the right place, just close this issue.

Cheers,

cc @guitargeek

**Comment by guitargeek** [comment]
HI Joosep, is this functionality required anywhere in CMSSW or you intend to use it? I personally think it only makes sense to implement it in that case.

But in case you want to implement it, here is just a heads up: the GBRForest is used as a conditions data format, so any additional class member would break compatibility with old CMSSW releases and this this not desired. So if you want to implement this functionality, you probably don't want to touch the GBRForest class in `CondFormats/EgammaObjects` but come up with some other solution. Maybe a new `MinMaxTransformer` class? Probably this new code you'd write should end up in `CommonTools/MVAUtils` then.

**Comment by jpata** [comment]
I ran into it in my own analysis using the GBRForest code. I just thought it might happen silently for someone who intends to use a TMVA XML in CMSSW as well. If you think it's not an issue or might be solved in case it arises, it's fine, I don't need to push my version upstream here, just making a note here.
I see your point about CondFormats, I don't have much experience with it.

**Comment by bendavid** [comment]
(It was intended from the beginning to add some checks for unsupported TMVA features when trying to convert from TMVA weights and throw an error rather than succeed and silently give incorrect results.)

**Comment by jpata** [comment]
not going to be addressed.
