### ISSUE TITLE
DQM Root Source Producer 

### ISSUE THREAD

**Issue by andrius-k** [cms-sw/cmssw#27780]
Hello,
I just encountered an issue adapting the `DQMServices/FwkIO/plugins/DQMRootSource.cc` to the new codebase in the context of restructuring the DQM code. The old producer would populate the `DQMStore` with histograms directly but since the global `DQMStore` doesn't exist anymore I would like it to produce regular products (`produces<MonitorElementCollection>`). [Documentation](https://twiki.cern.ch/twiki/bin/view/CMSPublic/SWGuideInputSources#Writing_an_input_source) is instructing to inherit from one of the base classes but current `DQMRootSource` doesn't do that. Is there a reason for this? Can part of the code be removed by just inheriting from a correct base? What is the best way to produce per lumi and per run products in this case?
Regards,
Andrius

**Comment by Dr15Jones** [comment]
Assign dqm, core

**Comment by andrius-k** [comment]
Dear framework experts,
I played around with an existing input source and the problem that I had could be solved by simply knowing how to create per run and per lumi products in the input source. There is the ``

**Comment by andrius-k** [comment]
Dear framework experts,
This feature is something that we are missing in order to continue our work on fixing issues in the harvesting stage. Without the input source we are stuck and unable to proceed. If you have any suggestions or some advice, please let us know!
Regards,
Andrius

**Comment by Dr15Jones** [comment]
After looking at the framework and DQM code, probably the easiest (but not best) way would be to inherit from `edm::PuttableSourceBase`. All the methods in `DQMRootSource` would remain and in addition one would implement `beginRun(edm::Run&)` and `beginLuminosityBlock(LuminosityBlock&)`. In the constructor you would call `produces` just like for an `EDProducer` and in `beginRun` and `beginLuminosityBlock` you would call `put` just like an `EDProducer`. You would also change `readRun_` and `readLuminosityBlock_` to not call `readElements()` and instead do that work in the appropriate `begin*` function.

The downside to this is all the data products you put into the Run or LuminosityBlock will have the label 'source' and not the label of the module which made them in the previous process. It is possible to do the latter, just not by inheriting from `edm::PuttableSourceBase`.

**Comment by andrius-k** [comment]
Thank you @Dr15Jones! Just got back from vacation myself and found out that @schneiml used your advice to produce successfully compiling code while I was gone. let me test it and I will get back to you with the results.

**Comment by Dr15Jones** [comment]
+1

**Comment by andrius-k** [comment]
Dear Chris @Dr15Jones, framework experts,
Your suggestion, indeed, works but I have a few uncertainties about how the code used to work previously and what exactly should the new version do.

My understanding, after carefully reading the code, is that previously, the data was read from DQMIO files sequentially (first one file then the other, etc.) and everything was being placed into a global instance of `DQMStore` that will later be passed on to the modules. It is, however, possible that one run is split into multiple files. In this case, input source would [merge](https://github.com/cms-sw/cmssw/blob/master/DQMServices/FwkIO/plugins/DQMRootSource.cc#L235) (potentially) previously read histogram with the new one and replace it in the `DQMStore`. In order to support this now, we can't end a run before everything is read. So my suggestion would be to read the metadata from ALL files, sort it, process the runs/lumis sequentially and call `.put(product)` only once for each run and lumi. Is my reasoning about previous and future code correct? Perhaps I'm missing something? Also how much support for merging histograms can I expect to get from the EDM framework? What would happen, for example, if I call `run.put(product)` on the same run twice and it already contains a histogram with the same name?

Another, more puzzling, concern that I have is that the input source was used to read DQMIO files that contain data from multiple runs. I don't see how would the previous code work without incorrectly merging the histograms from multiple runs!!! What I suspect is that [filterOnRun](https://github.com/cms-sw/cmssw/blob/master/DQMServices/FwkIO/plugins/DQMRootSource.cc#L422) option was being set all the time and other runs were just being ignored. I don't have evidence for it but at the moment, I don't see any other way it could have worked. So my question is this: how should the new code handle DQMIO files with multiple runs?

Regards,
Andrius

**Comment by makortel** [comment]
@andrius-k If I read the `DQMEDHarvester` correctly, it allows user code to operate at the end of LuminosityBlock or and the end of the job
https://github.com/cms-sw/cmssw/blob/747a9c4ba1d8bb773153b75d8e12508b07115644/DQMServices/Core/interface/DQMEDHarvester.h#L37-L41

I would then guess that the code reading run histograms uses `dqmEndJob()` at which point all the run histograms would have been fully merged by the source.

Or is there any code that would actually look the histograms at run transitions (begin/end)?

**Comment by andrius-k** [comment]
Hi Matti @makortel,
You're right, that's how it works currently. But in the new, product based design there is no global `DQMStore` anymore. It will no longer be possible to use `dqmEndJob` in harvesters because as far as I know, there is no support for job products in the EDM framework. 

The only way I see this working is that we open all input files, sort the metadata to have sequential runs and produce proper run/lumi transitions. In all subclasses of `DQMEDHarvester`, code will have to be moved from `dqmEndJob` to the (new) `dqmEndRun`. Maybe I'm missing something?

Regards,
Andrius

**Comment by makortel** [comment]
@andrius-k 
> You're right, that's how it works currently. But in the new, product based design there is no global `DQMStore` anymore. It will no longer be possible to use `dqmEndJob` in harvesters because as far as I know, there is no support for job products in the EDM framework

Right, I was trying to understand how the current system was working since you raised some questions on it in https://github.com/cms-sw/cmssw/issues/27780#issuecomment-530015017.

**Comment by schneiml** [comment]
+1

New `DQMRootSource` was merged with #28622.
