### ISSUE TITLE
RelMon: failing comparison evaluated as successfull

### ISSUE THREAD

**Issue by jan-kaspar** [cms-sw/cmssw#27802]
Here's an example
  https://cmsweb.cern.ch/dqm/relval/plotfairy/overlay?obj=archive%2F319450%2FCharmonium%2FCMSSW_11_0_0_pre4%2D106X_dataRun2_v17_RelVal_2018C%2Dv1%2FDQMIO%2FCTPPS%2Fcommon%2Fevents%20per%20BX;obj=archive%2F319450%2FCharmonium%2FCMSSW_11_0_0_pre4%2D106X_dataRun2_v17_gcc8_RelVal_2018C%2Dv1%2FDQMIO%2FCTPPS%2Fcommon%2Fevents%20per%20BX;w=600;h=600;ref=ratiooverlay
of two obviously different histograms evaluated as "successful comparison" which I find wrong.

The above problem is possibly related to the following observation. For example, at this page: https://cms-pdmv.cern.ch/ReleaseMonitoring/CMSSW_11_0_0_pre4_2018gcc8_vs_CMSSW_11_0_0_pre4_2018/DataReport/
if I look at the "Summary Table" section, at row "CTPPS" and for example column "Charmonium2018C" I see a fully green chart. However whenI click trough the details, I see the differences.

Thanks in advance!

**Comment by kpedro88** [comment]
assign dqm

**Comment by jfernan2** [comment]
@jan-kaspar the plot you point out in CTPPS/common/events per BX  is totally compatible within precision: same mean and same RMS, despite the different number of entries. Hence the comparison is sucessful, I see nothing wrong in this case.
Can you show me other clearer example? Thanks

**Comment by jfernan2** [comment]
This issue should be closed unless @jan-kaspar  has further comments

**Comment by jan-kaspar** [comment]
I apologise for the extremely late reply.

I guess the problem in definition of "compatibility". For the usecase of SW tests, where often one needs to check that a certain code change doesn't lead to ANY change in the results, I'd welcome a more strict definition of "compatibility".

In the above example, obviously, the blue histogram has significantly less entries thus most likely some dataset was not processed. Most likely this was due to a mistake and I believe that it should have been reported in a way.

Furthermore, since the blue histogram has systematically less entries in every bin, the two histograms are hardly compatible even in "statistical" interpretation.

So personally, I still find that there is a margin for improvement.

**Comment by schneiml** [comment]
@jan-kaspar For exactly the use case that you describe, we introduced the not-relmon-based bin-by-bin comparison to the PR tests. It should be possible for you to just download the respective root files from the GUI and feed them to `compareHistograms.py`.

RelMon can also be set up to apply more strict checks (and the configuration run in the PR tests is set up like this), but to get that for the normal RelVals you'd have to ask PDMV.

**Comment by jan-kaspar** [comment]
Thanks @schneiml !

Still, I believe that a similar check would be useful also for RelVals (provided that the input is still the same as I presume).

**Comment by jan-kaspar** [comment]
I guess that we all have more important things to do at this moment - I close the issue.
