### ISSUE TITLE
RelMon: more useful DQM-GUI link

### ISSUE THREAD

**Issue by jan-kaspar** [cms-sw/cmssw#27800]
In pages like:
https://cms-pdmv.cern.ch/ReleaseMonitoring/CMSSW_11_0_0_pre4_2018gcc8_vs_CMSSW_11_0_0_pre4_2018/DataReport/SingleMuon2018C-v1_106X_dataRun2_v17_RelVal_2018C_319450/41f33f54ab.html
I'd like to propose that the "To the DQM GUI" link points GUI page related to the RelMon page. This would be much more useful than the current static link. Thanks in advance!

**Comment by kpedro88** [comment]
assign dqm

**Comment by jfernan2** [comment]
This issue was partially solved in the PR above

**Comment by jan-kaspar** [comment]
Thanks!
