### ISSUE TITLE
Missing file HepPDT/ParticleDataTable.hh

### ISSUE THREAD

**Issue by TSA26** [cms-sw/cmssw#27904]
Following error emerge when tried to compile ParticleTreeDrawer.cc:

> /cvmfs/cms.cern.ch/slc7_amd64_gcc700/cms/cmssw/CMSSW_10_3_1/src/SimGeneral/HepPDTRecord/interface/ParticleDataTable.h:5:10: fatal error: HepPDT/ParticleDataTable.hh: No such file or directory
> 
>  #include "HepPDT/ParticleDataTable.hh"

**Comment by smuzaffar** [comment]
you might be missing `<use name="SimGeneral/HepPDTRecord"/>` in your BuildFile.xml?

**Comment by smuzaffar** [comment]
@TSA26, did adding the missing dependency fixed your issue? can we close this issue?
