### ISSUE TITLE
Configuration CRITICAL exception in SimpleMemoryCheck for 10_6_0

### ISSUE THREAD

**Issue by amaltaro** [cms-sw/cmssw#27977]
While running some test workflows using CMSSW_10_6_0_patch2/slc7_amd64_gcc700, I noticed a handful of jobs failed because they could not open the file (PID) to retrieve the process stats, as can be seen in this excerpt from the job log
```
2019-09-05 10:29:16,592:INFO:CMSSW:Executing CMSSW. args: ['/bin/bash', '/srv/job/WMTaskSpace/cmsRun3/cmsRun3-main.sh', '', u'slc7_amd64_gcc700', 'scramv1', 'CMSSW', 'CMSSW_10_6_0_patch2', 'FrameworkJobReport.xml', 'cmsRun', 'PSet.py', '', '', '']
2019-09-05 10:29:26,543:CRITICAL:CMSSW:Error running cmsRun
{'arguments': ['/bin/bash', '/srv/job/WMTaskSpace/cmsRun3/cmsRun3-main.sh', '', u'slc7_amd64_gcc700', 'scramv1', 'CMSSW', 'CMSSW_10_6_0_patch2', 'FrameworkJobReport.xml', 'cmsRun', 'PSet.py', '', '', '']}
CMSSW Return code: 8009

2019-09-05 10:29:26,546:CRITICAL:CMSSW:Error message: An exception of category 'Configuration' occurred while
   [0] Constructing the EventProcessor
   [1] Constructing service of type SimpleMemoryCheck
Exception Message:
Failed to open /proc/1697/stat
```

Given that it's solely fetching statistics for the cmsRun process, I wonder if we should rather catch that exception and just log an error (or warning) and keep the processing going(?)

**Comment by Dr15Jones** [comment]
Assign core

**Comment by Dr15Jones** [comment]
@amaltaro what does ops want to do in this case? If SimpleMemoryTest fails then the framework job report would contain no memory related information.

**Comment by amaltaro** [comment]
Wait, are you saying these statistics are collected only once in a `cmsRun` lifetime? I though it was following a polling cycle and fetching those from time to time.

By "no memory related information" you meant that the FJR would not have the Memory section in the FJR or that the values would all be 0 (or something else representing that)?

**Comment by Dr15Jones** [comment]
Without looking at the code, I'm not sure exactly what info the SimpleMemoryCheck was trying to do at construction time. Maybe doing a baseline memory check or doing a one time initialization of some information? If the latter than we'd be missing crucial info. If the former then we would have incomplete information about the job.

**Comment by Dr15Jones** [comment]
I just checked the code, the file is opened once in the job so if that fails, no measurements are possible.

**Comment by smuzaffar** [comment]
@amaltaro , should we close this issue?

**Comment by amaltaro** [comment]
Apologies for not following this issue up. Yes, I think there is nothing to be worked on here. In addition to that, I haven't seen anymore such errors in my test workflows. Closing!
