### ISSUE TITLE
Make HGCal Trackster's a class in CMSSW, instead of a struct

### ISSUE THREAD

**Issue by perrotta** [cms-sw/cmssw#28049]
Following the [comment](https://github.com/cms-sw/cmssw/pull/27917#discussion_r321334892) inserted by @slava77 during the review of #27917, non-trivial methods are not really expected for plain structs in data formats.
Trackster in DataFormats/HGCalReco/interface/Trackster.h should be transformed in a normal C++ class.
@riga @felicepantaleo

**Comment by perrotta** [comment]
assign reconstruction, upgrade

**Comment by perrotta** [comment]
Just to keep track of it, there is now a [commit](https://github.com/cms-sw/cmssw/pull/29081/commits/ba75e6d3309e841846770e75ff9618a93acdd78a) in #29081 which transform the current ```struct Trackster``` into a C++ ```class```, Once that PR will get merged this issue can be considered solved, then

**Comment by slava77** [comment]
+1
via #29081

**Comment by kpedro88** [comment]
+upgrade
