### ISSUE TITLE
Index of xBin,yBin can be out of range 

### ISSUE THREAD

**Issue by ZihengChen** [cms-sw/cmssw#28047]
https://github.com/cms-sw/cmssw/blob/92f3a0c522e9accbf3b6846874b778329cb7c2cb/RecoLocalCalo/HGCalRecProducers/interface/HGCalLayerTiles.h#L44

I think the correct std::clamp range should `(0, hgcaltilesconstants::nColumns-1)`
And so as yBin, etaBin, phiBin.
Otherwise segmentation fault could happen.

**Comment by ZihengChen** [comment]
@felicepantaleo

**Comment by Dr15Jones** [comment]
assign reconstruction

**Comment by slava77** [comment]
@felicepantaleo @rovere 
please clarify if this issue is being addressed.
Thank you.

**Comment by perrotta** [comment]
+1
- This was fixed with #28048, already merged since CMSSW_11_0_0_pre10
