### ISSUE TITLE
::getenv is not guaranteed to be thread safe

### ISSUE THREAD

**Issue by Dr15Jones** [cms-sw/cmssw#28073]
The POSIX and C standard state that muliple calls to `::getenv` are not guaranteed to be thread safe. The C++ standard `std::getenv` is thread safe. We should change all uses of `::getenv` in CMSSW to use `std::getenv`.

**Comment by Dr15Jones** [comment]
assign core, reconstruction, simulation, dam

**Comment by civanch** [comment]
@Dr15Jones , Geant4 has a lot of calls to environment in order to access data files. Should we inform Geant4 about this problem?

**Comment by Dr15Jones** [comment]
@civanch 
> Should we inform Geant4 about this problem?

That's probably a good idea.

**Comment by Dr15Jones** [comment]
#28117 changes all code for core.

**Comment by fabiocos** [comment]
@Dr15Jones @smuzaffar preparing a PR to change all the rest...

**Comment by Dr15Jones** [comment]
#28124 does the rest

**Comment by perrotta** [comment]
@Dr15Jones , I can still find three ```::getenv``` in CMSSW after your #28117 and #28124, namely:
- two in ```CondCore/Utilities/bin/cmscond_authentication_manager.cpp```
- one in ```OnlineDB/EcalCondDB/bin/cmsecal_write_offline_det_id.cpp```

Were they just got forgotten, or maybe that code is not to be run multithread?

**Comment by Dr15Jones** [comment]
@perrotta given both are stand alone programs, they were going to cause a problem for cmsRun :).

**Comment by perrotta** [comment]
+1
- FIxed with #28117 and #28124

**Comment by civanch** [comment]
The issue is fixed in Geant4 10.6 in all classes related to CMS productions.

**Comment by civanch** [comment]
+1
