### ISSUE TITLE
DataFormats dependency on Geometry must be forbidden

### ISSUE THREAD

**Issue by ianna** [cms-sw/cmssw#28106]
Both direct and indirect dependency of the DataFormat classes&packages on any of the classes&packages residing in the Geometry subsystem must be forbidden. 

Refactoring should be done if there are any legitimate cases where it's needed.

@smuzaffar - as discussed.

**Comment by slava77** [comment]
isn't this a rule for DF dependencies https://twiki.cern.ch/twiki/bin/view/CMSPublic/SWGuideCreatingNewProducts#Restrictions_on_the_package_defi

Or is this an issue to request some automated code checking?

**Comment by smuzaffar** [comment]
request is to update dependency violations rules [a] and catch it at PR test time.

[a]
https://github.com/cms-sw/cmssw/blob/master/Utilities/ReleaseScripts/scripts/CMSSWReleaseDependency.rules

**Comment by fabiocos** [comment]
@ianna @smuzaffar is this issue a consequence of a problem caught?

**Comment by ianna** [comment]
closed in favour of https://github.com/cms-sw/cmssw/issues/34663
