### ISSUE TITLE
Clean CE_{E,H} workflows for runTheMatrix

### ISSUE THREAD

**Issue by rovere** [cms-sw/cmssw#28139]
At present we seem to create HGCAL specific workflows for all scenarios (2017/2018/2021/2023/2016).
We should keep just the last one.

**Comment by kpedro88** [comment]
assign upgrade

**Comment by fabiocos** [comment]
@rovere @kpedro88 my understanding of the policy used so far is to keep tested the main recent production scenarios (D35 and D41 at present) plus a few more recent experimental ones. A large cleanup of obsolete scenarios was already done this summer by Kevin. Anyway the HGCal community may better comment about the real latest needs (@bsunanda has provided a number of the more recent ones)

**Comment by kpedro88** [comment]
@rovere I thought you meant the special HGCal workflows for TICL tests (.51 and .52), but these are already restricted to 2026 workflows. Can you clarify exactly which workflows you think should be removed?

**Comment by rovere** [comment]
@kpedro88 
I explicitly mean remove workflows:

   * 10[094-101].*
   * 10[294-301].*
   * 10[494-501].*
   * 10[694-701].*
   * 10[894-901].*
   * 11[094-101].*
   * 11[294-301].*
   * 11[494-501].*
   * 11[694-701].*
   * 11[894-901].*
   * 12[094-101].*
   * 12[294-301].*
   * 12[494-501].*
   * 12[694-701].*
   * 12[894-901].*
   * 13[094-101].*

**Comment by kpedro88** [comment]
@rovere I see, you want to remove the CloseByParticleGun fragments from non-Phase2 workflow series. There is not currently any functionality to selectively add or remove generator fragments when putting together upgrade workflows. This could be added, but could also lead to inconsistency in workflow numbering, so would need some thought.

**Comment by kpedro88** [comment]
assign pdmv

**Comment by rovere** [comment]
> @rovere I see, you want to remove the CloseByParticleGun fragments from non-Phase2 workflow series. There is not currently any functionality to selectively add or remove generator fragments when putting together upgrade workflows. This could be added, but could also lead to inconsistency in workflow numbering, so would need some thought.

I'm not sure I follow your statement. That's what I did when I added specific TICL workflows: see my commit 068334050829667dbf411379722f1de2b184f802

**Comment by kpedro88** [comment]
Yes, for the "special" workflows labeled `.n` with `n > 0`, this is a common practice. For the "default" workflows labeled with `.0`, this has not traditionally been done. It could be done in a similar way, but I'm concerned about potential inconsistencies. I will think about it some more.

**Comment by fabiocos** [comment]
this looks now addressed by 28281
