### ISSUE TITLE
Calling call_pyinit from clang is leading to segmentation fault

### ISSUE THREAD

**Issue by Dr15Jones** [cms-sw/cmssw#28149]
The nightly IB RelVals are crashing in the module PyquenGeneratorFilter, e.g.

https://cmssdt.cern.ch/SDT/cgi-bin/logreader/slc7_amd64_gcc820/CMSSW_11_0_CLANG_X_2019-10-08-2300/pyRelValMatrixLogs/run/300.0_Pyquen_GammaJet_pt20_2760GeV+Pyquen_GammaJet_pt20_2760GeV+DIGIHIMIX+RECOHIMIX+HARVESTHI2018PPRECO/step1_Pyquen_GammaJet_pt20_2760GeV+Pyquen_GammaJet_pt20_2760GeV+DIGIHIMIX+RECOHIMIX+HARVESTHI2018PPRECO.log#/

I believe I have traced the problem to disagreement between the C function declaration to what FORTRAN expects. Running in the debugger, I see that the call as seen from C has OK values for the argument
```
#1  0x00007f75e2c3c1e6 in call_pyinit (frame=0x7f75e2c501af 'CMS\000', beam=0x7f75e2c501ad 'p\000', target=0x7f75e2c501ad 'p\000', win=2760)
    at /cvmfs/cms-ib.cern.ch/nweek-02597/slc7_amd64_gcc820/external/hepmc/2.06.07-pafccj/include/HepMC/PythiaWrapper6_4.h:262
```

But on the FORTRAN side, the arguments make no sense
```
#0  pyinit (frame=..., beam=..., target=<error reading variable: value requires 522508400 bytes, which is more than max-value-size>, win=2760, _frame=3, _beam=1, _target=3544668429585743873) at pyinit.f:8
```

I believe the C function description is here at line 144 and 134
http://lcgapp.cern.ch/project/simu/HepMC/20400/html/PythiaWrapper6__2_8h-source.html

Notice that in that description the 'hidden' arguments for FORTRAN (which hold the length of the strings) is an `int`. But if one converts the `_target=3544668429585743873` to binary we get
```
>>> bin(3544668429585743873)
'0b11000100110001001100010010100000000000000000000000000000000001'
```
where the correct answer is 1, which is the value at the lowest bit. Doing a google search on FORTRAN calling convention
https://gcc.gnu.org/onlinedocs/gfortran/Argument-passing-conventions.html

we see that at gcc 7 the size of the 'hidden' variable changed from an `int` to a `size_t`. So it appears the PythiaWrapper.h file needs to be updated to get the correct type for the 'hidden' variables.

**Comment by Dr15Jones** [comment]
assign generator

**Comment by Dr15Jones** [comment]
NOTE: I thing we do not see a crash on gcc just out of luck. Looking at the assembly, gcc and clang are handling the passing of the arguments slightly differently. The problematic 'hidden' variable is the last one on the call order an appears to be passed on the stack while the others are in registers. gcc just happens to have put 0s in the full `size_t` range while clang seems to pack its stack closer.

**Comment by Dr15Jones** [comment]
assign generators

**Comment by fabiocos** [comment]
We are using an old frozen version of HepMC, so I would say that unless an update to v3 is foreseen (and this goes beyond the scope of this fix) we should just provide a patch
