### ISSUE TITLE
cmsDriver creates configuration that cannot be expanded

### ISSUE THREAD

**Issue by fwyzard** [cms-sw/cmssw#28172]
Hi,
in recent CMSSW_11_0_X releases, one of the workflows in the "limited" matrix creates a configuration that runs, but cannot be expanded into a valid python:

```python
cmsrel CMSSW_11_0_0_pre10
cd CMSSW_11_0_0_pre10
cmsenv
runTheMatrix.py -j 0 -l 250202.181
cd 250202.181_*/

# this works
python step3_DIGI_DATAMIX_L1_DIGI2RAW_HLT.py

# this fails
edmConfigDump step3_DIGI_DATAMIX_L1_DIGI2RAW_HLT.py > step3.py
python step3.py
Traceback (most recent call last):
  File "step3.py", line 23479, in <module>
    process.pdigiTask_nogen = cms.Task(cms.TaskPlaceholder("mix"), cms.TaskPlaceholder("randomEngineStateProducer"), process.None, process.addPileupInfo, process.doAllDigiTask, process.generatorSmeared)
AttributeError: 'Process' object has no attribute 'None'
```

**Comment by makortel** [comment]
@Dr15Jones I'm taking a look on how the `None` ends up in the `Task.

**Comment by makortel** [comment]
The `None` corresponds the `genPUProtongs` in
https://github.com/cms-sw/cmssw/blob/28ee89b235caa54439092c0de66c224a576b2923/Configuration/StandardSequences/python/Digi_cff.py#L34
The module gets turned to a None by this assignment in a ProcessModifier (specific to premix stage2 job)
https://github.com/cms-sw/cmssw/blob/28ee89b235caa54439092c0de66c224a576b2923/Configuration/StandardSequences/python/DigiDM_cff.py#L52-L60

I/we need to think a bit the proper fix (at minimum `del process.genPUProtons` before the assignment seems to do the job).

**Comment by makortel** [comment]
After discussion with @Dr15Jones we ended up with a couple things to be fixed
- [ ] Remove the ProcessModifier in `DigiDM_cff`, add another one in `Digi_cff` that introduces the `genPUProtons` as an EDProducer (and the dependent Tasks) on `~premix_stage2` condition
- [ ] Add an exception to be raised in case one replaces an EDModule that is in a Task/etc with EDAlias (an exception is already thrown if one replaces an EDModule with another EDModule)
- [ ] Add an option to `edmConfigDump` to prune the configuration before dumping it
