### ISSUE TITLE
cond::persistency::KeyList is not thread safe

### ISSUE THREAD

**Issue by Dr15Jones** [cms-sw/cmssw#28203]
The `KeyList` class is made available in the EventSetup, presumably from `PoolDBESSource`

https://github.com/cms-sw/cmssw/blob/master/CondCore/CondDB/src/T_EventSetup_KeyList.cc#L5

When asking for items from a `KeyList` the code modifies the internals in a non-thread safe manner

https://github.com/cms-sw/cmssw/blob/master/CondCore/CondDB/interface/KeyList.h#L45-L46

A related problem is the module used in production, `DTConfigDBProducer` uses the `DTKeyedConfigCache` which retrieves the `KeyList` from the EventSetup system. This class then casts away the const 
https://github.com/cms-sw/cmssw/blob/master/CondTools/DT/src/DTKeyedConfigCache.cc#L89

and causes the entire object to have its data replaced via the call
https://github.com/cms-sw/cmssw/blob/master/CondTools/DT/src/DTKeyedConfigCache.cc#L98

which appears to do a behind the scene call back to the DB, which I would guess is not concurrent access safe
https://github.com/cms-sw/cmssw/blob/master/CondCore/CondDB/src/KeyList.cc#L18

The Framework is moving towards enabling concurrent running of ES modules which will lead to the possible race conditions when using `KeyList` and `DTConfigDBProducer`.

**Comment by Dr15Jones** [comment]
From further inspection, it appears that the `KeyList` is intended to change the meaning of the values stored in the `IOVProxy` which it holds. Instead of an entry in the `IOVProxy` begin related to time or Run# it is used as an arbitrary index. That arbitrary index is then used to lookup items one-by-one from the DB.

This can be seen in the call
https://github.com/cms-sw/cmssw/blob/master/CondTools/DT/src/DTKeyedConfigCache.cc#L98

where the value of `cfgId` comes either from the a `DTKeyedConfig` just retrieved from the DB 
https://github.com/cms-sw/cmssw/blob/master/CondTools/DT/src/DTKeyedConfigCache.cc#L145

(so `DTKeyedConfig` in the DB acting like a node in a linked list) or from the `DTCCBConfig` obtained the normal way from the CondDBESSource:
https://github.com/cms-sw/cmssw/blob/master/L1TriggerConfig/DTTPGConfigProducers/src/DTConfigDBProducer.cc#L341

**Comment by Dr15Jones** [comment]
It appears to me like this system is intended to provide an IOV to a `vector<std::string>`. I'm guessing it wasn't implemented like that since there were groups of `std::string` which get repeated over and over and there was a wish to not have those duplicated within the database.

**Comment by Dr15Jones** [comment]
Upon further inspection, it appears to me that the `mutable` data members in `KeyList`
https://github.com/cms-sw/cmssw/blob/master/CondCore/CondDB/interface/KeyList.h#L60-L61

are unnecessary as they are just set and the cleared after each call to the pair `load` and `get`. So instead, the two functions should be joined to one new `get` which only takes one value which is the `unsigned long long` used to lookup the `T` from the database.

**Comment by tvami** [comment]
@Dr15Jones is this issue resolved in https://github.com/cms-sw/cmssw/pull/28216
Can it be closed now?

**Comment by Dr15Jones** [comment]
@tvami I do not know if #28216 dealt with all the issues mentioned here. We are concurrently running ES modules and we haven't seen any known problems stemming from this code.

**Comment by Dr15Jones** [comment]
#28312 does appear to have made the necessary changes

**Comment by tvami** [comment]
> #28312 does appear to have made the necessary changes

Great!

**Comment by tvami** [comment]
+db
 * as discussed above, this was resolved in https://github.com/cms-sw/cmssw/pull/28312
