### ISSUE TITLE
PRs target for 11_0_0

### ISSUE THREAD

**Issue by srimanob** [cms-sw/cmssw#28248]
This issue is to collect PRs that target for 11_0_0. From the proposed schedule:
• CMSSW_11_0_0 on December 17
• End of open development: November 19
• Closed pre-release for fixes: December 3
(Page 9 in [Tentative plan](https://indico.cern.ch/event/842166/contributions/3581608/attachments/1930353/3198411/OCWeek_20191022.pdf))

- UL:

- Run-3:

- [ ] #28193  [HBHE] Update MahiDebugger and fix nP in NNLS

- Run dependent (good to have):

- [ ] #28214  Premix option c, with 2 tags, ECAL, 11_0_X, no new object for apdpnMC

- HLT TDR:

- Others:

**Comment by fabiocos** [comment]
@srimanob I think that with such an advance we should be capable to discuss all this in next ORPs, anyway fine for me to keep track here of a few relevant developments that are already available
