### ISSUE TITLE
DD4hep: TIBLayer0DOHMCarrierFW definition is wrong

### ISSUE THREAD

**Issue by ianna** [cms-sw/cmssw#28256]
Running simulation on Tracker only with all algorithms enabled:
```
Geant4Converter  INFO  +++  Successfully converted geometry to Geant4.

**************************************************** 
*  A runtime error has occured :                     
*    
-------- EEEE ------- G4Exception-START -------- EEEE -------
*** G4Exception : GeomMgt0002
      issued by : G4SmartVoxelHeader::BuildNodes()
PANIC! - Overlapping daughter with mother volume.
         Daughter physical volume TIBDOHMPrim_1
         is entirely outside mother logical volume tiblayer0:TIBLayer0DOHMCarrierFW !!
-------- EEEE -------- G4Exception-END --------- EEEE -------

*  the program will have to be terminated - sorry.   
**************************************************** 

```
Geometry build with DD4hep: the shape in question is selected (red tube segment) and obviously smaller then its children (green boxes)
![Screen Shot 2019-10-24 at 16 22 00](https://user-images.githubusercontent.com/1390682/67496497-c6036680-f67c-11e9-963a-03c7630c5bdc.png)
```
*** Shape tiblayer0:TIBLayer0DOHMCarrier_shape_0x7fcf82a73780: TGeoTubeSeg ***
    Rmin =    28.60000
    Rmax =    29.40000
    dz   =     0.03491
    phi1 =   845.11275
    phi2 =   896.00000
 Bounding box:
*** Shape tiblayer0:TIBLayer0DOHMCarrier_shape_0x7fcf82a73780: TGeoBBox ***
    dX =    29.40000
    dY =    29.40000
    dZ =     0.03491
    origin: x=    0.00000 y=    0.00000 z=    0.00000
```
Geometry build with DD as a reference. The selected tube segment contains all the boxes.
![Screen Shot 2019-10-24 at 16 29 26](https://user-images.githubusercontent.com/1390682/67496111-38277b80-f67c-11e9-8a62-848ed9decf76.png)
```
*** Shape tiblayer0:TIBLayer0DOHMCarrier: TGeoTubeSeg ***
    Rmin =    28.60000
    Rmax =    29.40000
    dz   =    14.75000
    phi1 =     2.00000
    phi2 =   178.00000
 Bounding box:
*** Shape tiblayer0:TIBLayer0DOHMCarrier: TGeoBBox ***
    dX =    29.38209
    dY =    14.20094
    dZ =    14.75000
    origin: x=    0.00000 y=   15.19906 z=    0.00000
```

**Comment by ianna** [comment]
@vargasa - Could you, please, have a look after https://github.com/cms-sw/cmssw/pull/28260 is merged in the IBs? Thanks.

**Comment by vargasa** [comment]
Thanks @ianna. I'll take a look

**Comment by vargasa** [comment]
I can confirm that the overlaps are still present by using `CMSSW_11_0_X_2019-11-11-1100`  with #28260 was merged. Will have to take a further look into this

![Screenshot from 2019-11-11 14-27-58](https://user-images.githubusercontent.com/16821717/68614793-a7300d00-048f-11ea-9def-a56a12e7df95.png)

**Comment by ianna** [comment]
fixed in https://github.com/cms-sw/cmssw/pull/28386
