### ISSUE TITLE
XML Material Description: Pixel materials defined in a top level description

### ISSUE THREAD

**Issue by ianna** [cms-sw/cmssw#28285]
Phase1 BPIX _micro-twisted pairs boundle_ material as defined by L. Caminada is defined but not used. It refers to a tracker material that are defined elsewhere creating a circular dependency between **material.xml** and **trackermaterials.xml** files.

_To check:_ what is an actual material used in BPIX and either remove or move the definition to a more appropriate location. 

Note: **T_Material** similar or even equivalent to **Material** definitions are needed for the material variation studies.

**Comment by fabiocos** [comment]
assign geometry

@vargasa FYI

**Comment by ianna** [comment]
+1

fixed
