### ISSUE TITLE
add local caching interface in MagneticField

### ISSUE THREAD

**Issue by slava77** [cms-sw/cmssw#28284]
This issue is to address the performance scaling problem resulting from cache trashing of the cache used in the MagGeometry (internal to the VolumeBasedMagneticField) observed in multi-threaded applications.
As a follow up to #28180, in line with https://github.com/cms-sw/cmssw/pull/28180#issuecomment-545431737, an update to the interface is expected in 2019 with follow up PR(s) to enable/benefit from local caching.

For convenience, a copy from https://github.com/cms-sw/cmssw/pull/28180#issuecomment-545431737
`it will be straightforward to move the internal cache up to MagGeometry::fieldInTesla(const GlobalPoint& gp) and add a separate MagGeometry::fieldInTesla(const GlobalPoint& gp, MagneticFieldCache& cache) since these are very simple methods.`

@namapane @amadio @dpiparo

**Comment by slava77** [comment]
assign reconstruction,simulation

**Comment by civanch** [comment]
@slava77 , @namapane , @amadio, how will proceed? who will make PR(s)?

**Comment by namapane** [comment]
@civanch, as I mentioned in #28180 I can add the new interface but I am working on other developments in the same subsystems that I'd prefer to finish beforehand. It will take a couple of weeks I hope. Otherwise it's fine for me if that is done independently by somebody else; just let me know.

**Comment by namapane** [comment]
This should be probably closed with #29561  .

**Comment by slava77** [comment]
+1

via discussion related to #29561
