### ISSUE TITLE
DD4hep: Using DDHCalBarrelAlgo report overlaps

### ISSUE THREAD

**Issue by ianna** [cms-sw/cmssw#28292]
![Screen Shot 2019-10-28 at 16 50 43](https://user-images.githubusercontent.com/1390682/67694405-8fdb2500-f9a3-11e9-88e2-17a68927679e.png)

**Comment by ianna** [comment]
@bsunanda - FYI

**Comment by fabiocos** [comment]
assign geometry

**Comment by ianna** [comment]
It's a bug in the DD4hep ROOT to G4 converter of a Polyhedra:
![Screen Shot 2019-11-04 at 17 32 07](https://user-images.githubusercontent.com/1390682/68139271-279fbc80-ff2a-11e9-9290-e1acd0574dc1.png)
![Screen Shot 2019-11-04 at 17 33 19](https://user-images.githubusercontent.com/1390682/68139272-279fbc80-ff2a-11e9-9461-bb3c2bc7b4b0.png)
![Screen Shot 2019-11-04 at 17 34 27](https://user-images.githubusercontent.com/1390682/68139273-279fbc80-ff2a-11e9-93a3-b76b86070734.png)

**Comment by ianna** [comment]
the bug has been fixed, but the overlaps remain, though G4 does not report them:

**Comment by bsunanda** [comment]
Hi Ianna - I shall take a look once your PR is merged. Regards      Sunanda
________________________________

**Comment by ianna** [comment]
@bsunanda - it seems like the overlaps reported by ROOT are false-positive:
```
=====================================================================
CMSG4OverlapCheck is initialised with 1 nodes;  nPoints= 10000; tolerance= 0 mm; verbose: 1
               RegionFlag: 1  PVname:   LVname: 
               Nlv= 3398   Npv= 18955
=====================================================================
### Check overlaps for DDDWorld 
Checking overlaps for volume OCMS_1 ... OK! 
Checking overlaps for volume CMSE_1 ... OK! 
---------------- End of overlap checks ---------------------
Overlaps_Geom2021DD4hep.txt (END)
```

**Comment by ianna** [comment]
+1
