### ISSUE TITLE
Simulation: Phase II Beam Pipe description

### ISSUE THREAD

**Issue by ianna** [cms-sw/cmssw#28303]
Check Phase II Beam Pipe description and update it to include new supports at 16 m. See the following presentations for more details:
https://indico.cern.ch/event/859122/

**Comment by Dr15Jones** [comment]
assign geometry

**Comment by ianna** [comment]
+1

**Comment by ianna** [comment]
Implemented via https://github.com/cms-sw/cmssw/pull/29900
