### ISSUE TITLE
Non reproducibility of LETDCTime HCAL DigiTask histograms in PR tests

### ISSUE THREAD

**Issue by fabiocos** [cms-sw/cmssw#28367]
After the integration of #28330 we observe non reproducibility of DQM histograms in the LETDCTime section of HCAL DigiTask tests, in PRs which cannot affect this (e.g. #28363).
This happens for test wfs 10024.0, 10042.0 and 10224.0 .

This issue is to keep track of the problem (whose origin seems defined) after the initial remarks by @abdoulline https://github.com/cms-sw/cmssw/pull/28330#issuecomment-551434840 until it is solved.

**Comment by fabiocos** [comment]
assign reconstruction,simulation,dqm

@abdoulline @lwang046 @DryRun FYI

**Comment by abdoulline** [comment]
We've agreed with Long on a workaround and he's submitted it:  
https://github.com/cms-sw/cmssw/pull/28368

In the meantime, I've asked our DQM expert (David  @DryRun) to try to figure out what might have been a reason of this issue, specific to 2017 HEP17 (QIE11 pilot module) in legacy HE (QIE8).

Even if we know and all agreed earlier this year that DQM back-compatibility (now turned toward Run3) is not required, see here:  https://github.com/cms-sw/cmssw/pull/27149
it's not clear to me how it can be a reason for non-reproducibility of MC HEP17 TDC results in this particular 2017 MC case...

**Comment by slava77** [comment]
it looks like this can be signed and closed.
@perrotta please confirm (since you followed up on this directly).

**Comment by perrotta** [comment]
> it looks like this can be signed and closed.
> @perrotta please confirm (since you followed up on this directly).

According to what @abdoulline wrote in https://github.com/cms-sw/cmssw/pull/28368#issuecomment-552512465 , there can be still an issue with the HCAL data-specialized DQM (DQM/HcalTasks: DigiTask, where the issue popped up). That specialized DQM is not even supposed to be used for 2018 data, and of course not for MC and previous years.

As such this is certainly not an issue for reco any more, and as far as I understand not even for DQM.

**Comment by perrotta** [comment]
+1
- not an issue for reco any more, and not even for DQM (see https://github.com/cms-sw/cmssw/pull/28368#issuecomment-552512465)

**Comment by fabiocos** [comment]
@slava77 @perrotta in practice the issue has not been observed after the integration of the workaround, so I believe that this can be closed at this point, @jfernan2 do you agree?

**Comment by jfernan2** [comment]
+1
Yes, it seems this is gone. Nevertheless, we expect some DQM cleanup from HCAL in the mid-term future. Thanks
