### ISSUE TITLE
Modernize string usage in cms::DDFilteredView interface

### ISSUE THREAD

**Issue by kpedro88** [cms-sw/cmssw#28382]
In #28361, I noticed `c_str()` being used repeatedly within calls to `cms::DDFilteredView::get()`. Apparently the interface currently requires it:
https://github.com/cms-sw/cmssw/blob/e626860d26692de5880c52c7c80aec7b859a0c60/DetectorDescription/DDCMS/interface/DDFilteredView.h#L148-L154

This should be modernized to use `std::string`. If functions called inside of `get()` require c-strings for some archaic reason, the `c_str()` calls should be made inside `get()`, rather than cluttering a lot of other geometry code.

**Comment by kpedro88** [comment]
assign geometry

**Comment by ianna** [comment]
https://github.com/cms-sw/cmssw/pull/28384

**Comment by ianna** [comment]
+1

**Comment by kpedro88** [comment]
thanks @ianna
