### ISSUE TITLE
Broken HLT customisation function

### ISSUE THREAD

**Issue by Sam-Harper** [cms-sw/cmssw#28403]
Dear All,

After https://github.com/cms-sw/cmssw/pull/28110, the frozen 2018 menu in 110X (/frozen/2018/110X/HLT/V3) can no longer be run. Specifically the error is 

```
Exception Message:
 unknown python problem occurred.
AttributeError: bCalibSecondary

At:
  /cvmfs/cms.cern.ch/slc7_amd64_gcc820/cms/cmssw/CMSSW_11_0_0_pre12/python/FWCore/ParameterSet/Mixins.py(293): __delattr__
  /cvmfs/cms.cern.ch/slc7_amd64_gcc820/cms/cmssw/CMSSW_11_0_0_pre12/python/HLTrigger/Configuration/customizeHLTforCMSSW.py(29): customiseFor28110
  /cvmfs/cms.cern.ch/slc7_amd64_gcc820/cms/cmssw/CMSSW_11_0_0_pre12/python/HLTrigger/Configuration/customizeHLTforCMSSW.py(246): customizeHLTforCMSSW
  refMenu.py(92117): <module>

```

I'm also surprised it runs on any HLT menu, looking at /dev/CMSSW_11_0_0/GRun/V11  in hltParticleFlow:
```
iCfgCandConnector = cms.PSet( 
      nuclCalibFactors = cms.vdouble( 0.8, 0.15, 0.5, 0.5, 0.05 ),
      bCorrect = cms.bool( False ),
      bCalibPrimary = cms.bool( False )
    ),
```

is set so it'll crash again. Right now the work around is easy, just catch the exception
```
 try:
      delattr(pset,'bCalibSecondary')
 except AttributeError:
      pass
```

but I would like an expert to weigh in why this was expected to work first just incase I'm missing something.

@Martin-Grunewald @hatakeyamak

**Comment by Dr15Jones** [comment]
assign hlt

**Comment by hatakeyamak** [comment]
Looks like I should have added some protection for deletion of bCalibSecondary in case bCalibSecondary doesn't exist. Probably this wasn't an issue during PR review since all tests were done using HLT configs that have bCalibSecondary.
I am new to this, so will wait to hear suggestions from @Martin-Grunewald .

**Comment by Martin-Grunewald** [comment]
Fixed by https://github.com/cms-sw/cmssw/pull/28406
which absorbs the customisation of the PFProducer instances in all menus

**Comment by Martin-Grunewald** [comment]
/frozen/2018/110X/HLT/V3 has the changes in so the custom function should no longer
be applied - you were too fast :-)

**Comment by Sam-Harper** [comment]
thanks martin for the clarification and fix! Much appreciated

**Comment by fabiocos** [comment]
the fix has been integrated
