### ISSUE TITLE
Investigate changing MessageDrop::runEvent to std::string_view

### ISSUE THREAD

**Issue by Dr15Jones** [cms-sw/cmssw#28451]
With the change #28450 it looks like all the string copies done to fill `MessageDrop::runEvent` are now redundant as the source string has a lifetime as long as that value of `runEvent` is in use.

**Comment by Dr15Jones** [comment]
assign core

**Comment by Dr15Jones** [comment]
See #28457 for a solution

**Comment by fabiocos** [comment]
@Dr15Jones your #28457 has been now integrated

**Comment by Dr15Jones** [comment]
+1
