### ISSUE TITLE
Frontier fails when FRONTIER_LOG_LEVEL and frontier-connect ipfamily are set

### ISSUE THREAD

**Issue by smuzaffar** [cms-sw/cmssw#28499]
We have seen that recently a CMSSW unit test is failing with error [b]. It only fails when we set following env[a]. Note `/cvmfs/cms-ib.cern.ch` contains a local SITECONF https://github.com/cms-sw/siteconf . @DrDaveD why it is happening? Unsetting `FRONTIER_LOG_LEVEL` or using `CMS_PATH=/cvmfs/cms.cern.ch`  do not break the test. Looks like the the change https://github.com/cms-sw/siteconf/commit/bcd4094d1a0289abfa0c1dcf9a571ff5bbf668ff is causing this failure (only if `FRONTIER_LOG_LEVEL` is set). Any idea what's wrong here? You can reproduce this test by  following steps in [c]. 

**Frontier client version we are using is `2.8.20`**

[a]
```
export FRONTIER_LOG_LEVEL=warning
export CMS_PATH=/cvmfs/cms-ib.cern.ch
```
[b]
```
dropped waiting message count 0
0a1,4
> warn  [frontier_config.c:945]: unable to connect to proxyconfig server grid-wpad[2001:1458:301:d2::100:2]: [fn-socket.c:125]: connect to 2001:1458:301:d2::100:2 timed out after 5 seconds
> warn  [frontier_config.c:1019]: Trying next proxyconfig server grid-wpad[2001:1458:301:7f::100:1a]
> warn  [frontier.c:1014]: Request 25 on chan 1 failed at Thu Nov 28 11:06:13 2019: -9 [fn-socket.c:125]: connect to 2001:1458:301:d2::100:2 timed out after 5 seconds
> warn  [frontier.c:1114]: Trying next proxy cmsmeyproxy.cern.ch[2001:1458:301:7f::100:1a] with same server cmsfrontier.cern.ch
```

[c]
```
ssh lxplus
bash
cd /tmp/`whoami`
scram p CMSSW_11_0_X_2019-11-27-2300
cd CMSSW_11_0_X_2019-11-27-2300/
cmsenv
git cms-addpkg CondCore/ESSources
scram b -j 8
#The following runs successfully
FRONTIER_LOG_LEVEL="warning" CMS_PATH=/cvmfs/cms.cern.ch scram b runtests
#The following runs successfully
CMS_PATH=/cvmfs/cms-ib.cern.ch scram b runtests
#The folowing fails
FRONTIER_LOG_LEVEL="warning" CMS_PATH=/cvmfs/cms-ib.cern.ch scram b runtests
```

**Comment by DrDaveD** [comment]
@smuzaffar That's not a fatal error, it's only a warning, correct?

It appears that the IPv6 connectivity to the grid-wpad.cern.ch servers is intermittent.  When I do the connections by hand, it works sometimes and fails sometimes.  I will need to look into it later, today and tomorrow are U.S. holidays.

**Comment by smuzaffar** [comment]
@DrDaveD , correct, it is a warning. 
@wddgit CMSSW unit tests is failing due to `diff` comand we are doing here https://github.com/cms-sw/cmssw/blob/master/CondCore/ESSources/test/TestConcurrentIOVsCondCore.sh#L9. May be we can keep only `'^lumi `  lines in log for comparion?

**Comment by DrDaveD** [comment]
It's good that you reported this, because otherwise I wouldn't have known about the intermittent failures.  I made service desk ticket INC2225950.

**Comment by wddgit** [comment]
I will take a look and submit a PR fixing this today. Sorry for the delay replying, holidays and time off...
Just got back today.

**Comment by DrDaveD** [comment]
We could also work around it by removing the IPv6 address for that server from DNS.  We're not getting any response on the ticket yet, but I think we'll first try rebooting the machine but if that doesn't fix it we'll make it be IPv4-only for now.

**Comment by wddgit** [comment]
PR #28530 fixes this is in 11_1_X. It makes the test less fragile, so we should do this. Possibly in addition we might want to think about other changes, but anything else would be someone else's responsibility. I occasionally use cout (standard output), but only in unit tests. I never use it in code that might run in production or outside a test. I am wondering why something else is sending output there...

Should I backport to 11_0_X?

**Comment by smuzaffar** [comment]
thanks @wddgit , 11.1.X is fine for now

**Comment by DrDaveD** [comment]
The service is back to working 100% on IPv6.

**Comment by DrDaveD** [comment]
This issue can be closed.
