### ISSUE TITLE
Add pre/post signals for write-lumi and write-run

### ISSUE THREAD

**Issue by makortel** [cms-sw/cmssw#28555]
In the context of #28521 @Dr15Jones and I realized that while the framework emits pre/post signals for globalEndLumi before/after the global end-lumi functions of all modules (including output) have been called, there are no signals for the subsequent write-lumi transitions (same holds for run).

We came to the conclusion that it would be beneficial to add pre/post signals for write-lumi and write-run in order to let other parts know when the processing of lumis and runs are fully done.

**Comment by Dr15Jones** [comment]
assign core

**Comment by schneiml** [comment]
Just to confirm: this is exactly what I wanted to request in #28521.

**Comment by Dr15Jones** [comment]
Accomplished with #28562

**Comment by Dr15Jones** [comment]
+1
