### ISSUE TITLE
Provide a way to silence static analyzer warnings

### ISSUE THREAD

**Issue by makortel** [cms-sw/cmssw#28553]
Discussion in https://github.com/cms-sw/cmssw/pull/28459#issuecomment-561313562 brought up a need for a way to silence static analyzer warnings in specific cases that are not covered with `CMS_THREAD_SAFE` or `CMS_THREAD_GUARD()`. For example `mutable` members in "thread friendly" (non-data format) classes are acceptable as long as no mutable state is shared between objects of that class.

A proposal is to add an attribute `[[cms::sa_allow]]` with `CMS_SA_ALLOW` macro with the following policy
* use of the attribute also requires a comment stating why it should be allowed
* the attribute/macro is forbidden in data product / EventSetup product / module caches

**Comment by makortel** [comment]
@Dr15Jones @gartung

**Comment by gartung** [comment]
The new macro definition is added in PR
https://github.com/cms-sw/cmssw/pull/28554

**Comment by Dr15Jones** [comment]
assign core

**Comment by makortel** [comment]
https://github.com/cms-sw/cmssw/pull/28554 has been merged
