### ISSUE TITLE
MTDGeomDet type problem

### ISSUE THREAD

**Issue by dan131riley** [cms-sw/cmssw#28571]
This is a followup to PR #28531.  In that PR, address sanitizer found that some unit tests were passing the wrong GeomDet type to the BaseTrackerRecHit constructor.  That constructor implicitly assumes that the GeomDet it receives is a TrackerGeomDet via this static_cast:

https://github.com/cms-sw/cmssw/blob/30a2ff8ff13aaa416259453b54ad0b62588edc91/DataFormats/TrackerRecHit2D/interface/BaseTrackerRecHit.h#L29

As an integrity test I ran a limited matrix with all the pointer static_casts in DataFormats/TrackerRecHit2D changed to dynamic_casts, which resulted in crashes in MTDTrackingRecHitProducer::run here:

https://github.com/cms-sw/cmssw/blob/30a2ff8ff13aaa416259453b54ad0b62588edc91/RecoLocalFastTime/FTLRecProducers/plugins/MTDTrackingRecHitProducer.cc#L120

I suspect this is because MTDGeomDet is not a TrackerGeomDet:

https://github.com/cms-sw/cmssw/blob/30a2ff8ff13aaa416259453b54ad0b62588edc91/Geometry/CommonDetUnit/interface/MTDGeomDet.h#L6

In fact, MTDGeomDet appears to be a cut&paste of TrackerGeomDet, so it has the same layout as the TrackerGeomDet, which is likely why the code doesn't crash with the static_cast.  Nevertheless, this is a bug.  I would guess that the correct fix is to make MTDGeomDet a TrackerGeomDet, either by inheritance or a simple 'using' alias (since there don't seem to be any differences in behavior), but a subject expert should take a look.

As a secondary issue, there are a lot of other hidden assumptions in the GeomDet code where static casts are used.  The C++ Core Guidelines (which are referenced by the CMS coding style guide) recommends dynamic_cast for runtime type safety when navigating the class hierarchy is unavoidable.  Since the static_casts have proven to be fallible, should there be a campaign to change the GeomDet static casts to dynamic casts?

**Comment by dan131riley** [comment]
@perrotta this is a followup to your question on #28531

**Comment by perrotta** [comment]
assign geometry, reconstruction

**Comment by dan131riley** [comment]
Replacing MTDGeomDet.h with `using MTDGeomDet = TrackerGeomDet;` seems to work.  I pushed my working area with that change and several static casts converted to dynamic casts to https://github.com/dan131riley/cmssw/tree/GeomDet-type-fixes

If there's interest I could make a straw-man PR  for discussion.

**Comment by cvuosalo** [comment]
@dan131riley Changing to the `using` seems like a good idea as a quick fix. If you could submit the PR, that would be helpful.
For a more comprehensive solution, I don't see why these clumsy casts are used in the first place. Maybe `GeomDet::localAlignmentError()` could be added as a virtual function so the casts wouldn't be necessary.

**Comment by dan131riley** [comment]
@cvuosalo Ok, I'll make PR.  Making a virtual `GeomDet::localAlignmentError()` would be easy enough except that `MuonGeomDet` has its own version with a different type signature:

https://github.com/cms-sw/cmssw/blob/bf5212e884781d1fa3d172b9d97c8ac162bc88d2/Geometry/CommonTopologies/interface/MuonGeomDet.h#L16

This isn't actually used:

https://github.com/cms-sw/cmssw/blob/bf5212e884781d1fa3d172b9d97c8ac162bc88d2/Geometry/CommonTopologies/src/MuonGeomDet.cc#L4

If we could get rid of it, the rest is easy.

**Comment by fabiocos** [comment]
@dan131riley indeed a large part of the MTD reco geometry is cloned (and slightly adapted) from the Tracker one, as MTD could be logically considered as an additional tracker layer

**Comment by perrotta** [comment]
+1
- #28590 is merged, and it fixes the issue pointed out here
