### ISSUE TITLE
Thread safety issue in SwitchBaseProductResolver::resolveProductImpl

### ISSUE THREAD

**Issue by Dr15Jones** [cms-sw/cmssw#28680]
The method SwitchBaseProductResolver::resolveProductImpl is called each time another module calls `edm::Event::get*` for the data product. Such can happen concurrently. However, the function is not thread safe as it calls `edm:::ProductData::unsafe_setWrapper` 

https://github.com/cms-sw/cmssw/blob/master/FWCore/Framework/src/ProductResolvers.cc#L621

The proper thing to do is to set the Wrapper during the data prefetching stage.

**Comment by Dr15Jones** [comment]
assign core

**Comment by Dr15Jones** [comment]
@makortel please look into this

**Comment by makortel** [comment]
Addressed in #28686 along some other problems I realized while trying to understand what is going on.
