### ISSUE TITLE
PopConSourceHandler leaks memory

### ISSUE THREAD

**Issue by Dr15Jones** [cms-sw/cmssw#28699]
Classes inheriting from PopConSourceHandler are required to call `new` in the `getNewObjects()` method and add those to a protected member container. I could not find anywhere that later deletes the objects placed into that container.

**Comment by Dr15Jones** [comment]
assign alca, db

**Comment by tvami** [comment]
+alca

**Comment by tvami** [comment]
Since https://github.com/cms-sw/cmssw/pull/35048 is merged, this issue can be closed

**Comment by tvami** [comment]
close https://github.com/cms-sw/cmssw/issues/28699

**Comment by tvami** [comment]
> close #28699

I don't have the power to close this. @Dr15Jones @qliphy @perrotta

**Comment by ggovi** [comment]
+1
