### ISSUE TITLE
Ordering issue in Task.replace() affecting dumpPython()

### ISSUE THREAD

**Issue by makortel** [cms-sw/cmssw#28703]
The python 3 unit test failure
```
Traceback (most recent call last):
  File "/cvmfs/cms-ib.cern.ch/nweek-02609/slc7_amd64_gcc820/cms/cmssw-patch/CMSSW_11_1_PY3_X_2019-12-31-2300/python/FWCore/ParameterSet/Config.py", line 2425, in testTask
    self.assertTrue(process.path21.dumpPython(PrintOptions()) == 'cms.Path(process.mproducer10+process.mproducer8+process.mproducer8+(process.mproducer8+process.mproducer9)+process.sequence3, cms.Task(), cms.Task(process.None, process.mproducer10), cms.Task(process.d, process.mesproducer, process.messource, process.mfilter, process.mproducer10, process.mproducer2, process.myTask6), process.myTask100, process.myTask5)\n')
AssertionError: False is not true
```
seems to be caused by a different order of Tasks whose `replace()` functions are called by this line
https://github.com/cms-sw/cmssw/blob/a04e878f77214f485f86bf0b61116129d65c6e69/FWCore/ParameterSet/python/Config.py#L2387
Essentially the nested task structure before the call is
```python
process.myTask5 = cms.Task(process.d) # d is Service
process.myTask8 = cms.Task(process.myTask5, process.mproducer8)
process.myTask7 = cms.Task(process.myTask8)
process.myTask6 = cms.Task(process.myTask7)
process.myTask1 = cms.Task(process.myTask6, ...)
```
In the py2 build, this loop
https://github.com/cms-sw/cmssw/blob/a04e878f77214f485f86bf0b61116129d65c6e69/FWCore/ParameterSet/python/Config.py#L1071-L1074
operates first on `process.myTask8` and sets its value to be `cms.Task(process.mproducer8)`. Then the loop operates on `process.myTask1`, and nothing needs to be done.

In py3 build the loop operates first on `process.myTask1`. The visitor proceeds up to `myTask8`, removes the `myTask5`, and, because values were changed, recreates the nested task structure with anonymous Tasks
https://github.com/cms-sw/cmssw/blob/a04e878f77214f485f86bf0b61116129d65c6e69/FWCore/ParameterSet/python/SequenceTypes.py#L1275-L1280
i.e. to
```python
process.myTask1 = cms.Task(cms.Task(cms.Task(cms.Task(process.mproducer8, cms.Task()))), ...)
```
The anonymous Tasks lead to the failure of the test that expects to see `process.myTask6` in the `dumpPython()` output. As far as I can tell, the issue affects only the `dumpPython()`, the module/component contents of the tasks are still correct.

**Comment by Dr15Jones** [comment]
assign core
