### ISSUE TITLE
ESGetToken does not work in TestProcessor

### ISSUE THREAD

**Issue by makortel** [cms-sw/cmssw#28709]
A `TestProcessor` configuration where the module-to-be-tested reads an ESProduct from an ESProducer appears to fail if the module retrieves the product with `ESGetToken`. This behavior is demonstrated in #28708.

**Comment by makortel** [comment]
@Dr15Jones could you take a look?

**Comment by Dr15Jones** [comment]
Fixed as part of #28708

**Comment by Dr15Jones** [comment]
assign core
