### ISSUE TITLE
[Utilities/XrdAdaptor] Multi-source open requests should specify triedrc=resel

### ISSUE THREAD

**Issue by osschar** [cms-sw/cmssw#28716]
Since xrootd-4.10 xrootd server supports differentiated processing of file-open requests for server reselection. There are two main uses:
1. Local storage accessed through xrootd where server reselection should not "escape" outside of the local cluster.
2. XCache clusters, where opening of a file multiple times effectively creates several copies of that file in the cache, thus wasting the cache space.

Both of these use-cases are covered by introducing the opaque parameter triedrc=resel into the request URL when opening a new file for multi-source reading.

**Comment by osschar** [comment]
Justas (juztas) and @osschar will do the changes,  @bbockelm agreed to help and review the changes.

**Comment by makortel** [comment]
assign core

**Comment by makortel** [comment]
+1

Done in https://github.com/cms-sw/cmssw/pull/34700
