### ISSUE TITLE
Python3 incompatibility: ConfigParser 

### ISSUE THREAD

**Issue by silviodonato** [cms-sw/cmssw#28765]
The PR #28739 revealed the existence of incompatibilities with Python3 in CMSSW due to "import ConfigParser".
In Python3 "ConfigParser" has been renamed to "configparser". The minimal fix is to replace "import ConfigParser" with "import configparser as ConfigParser" (that is compatible also to Python2.7).

From LXR, we see that "import ConfigParser" appears in:

Alignment/APEEstimation/test/autoSubmitter/autoSubmitter.py
Alignment/MillePedeAlignmentAlgorithm/python/mpsvalidate/iniparser.py
Alignment/MillePedeAlignmentAlgorithm/scripts/mps_alisetup.py
Alignment/OfflineValidation/python/TkAlAllInOneTool/betterConfigParser.py
Alignment/OfflineValidation/python/TkAlAllInOneTool/geometryComparison.py
Alignment/OfflineValidation/test/submitAllJobs.py
CondCore/DBOutputService/scripts/cmscond_logdb_dump
DQM/Integration/python/config/environment_cfi.py
DQMOffline/Alignment/test/alcarecoTester.py
FastSimulation/Calorimetry/test/calculateECALresponceScales.py
Geometry/TrackerCommonData/test/twikiExport.py
HLTriggerOffline/Btag/python/helper.py
RecoVertex/BeamSpotProducer/scripts/BeamSpotWorkflow.py
RecoVertex/BeamSpotProducer/test/InspectFwBeamSpot.py

core:   @Dr15Jones  @smuzaffar  @makortel 
alca:   @christopheralanwest  @franzoni  @tlampen  @pohsun  @tocheng

**Comment by silviodonato** [comment]
#28822

**Comment by makortel** [comment]
@silviodonato The https://github.com/cms-sw/cmssw/pull/28822 fully fixed this issue, right?

**Comment by silviodonato** [comment]
Yes, #28822 and https://github.com/cms-sw/cmssw/pull/28838 solved the issue.
Closing the issue
