### ISSUE TITLE
Provenance issue with DAQ input source (11_1_0_pre2)

### ISSUE THREAD

**Issue by smorovic** [cms-sw/cmssw#28786]
In CMSSW_11_1_0_pre2 DAQ source (FedRawDataInputSource) throws exception due to issue with provenance BranchID

----- Begin Fatal Exception 24-Jan-2020 14:15:33 CET-----------------------
An exception of category 'LogicError' occurred while
   [0] Calling InputSource::readEvent_
Exception Message:
ProductProvenanceRetriever::insertIntoSet passed a BranchID 1017257328 that has not been pre-registered
----- End Fatal Exception -------------------------------------------------

This source uses edm::DaqProvenanceHelper to insert RawDataCollection with rawDataCollector label, which is used in HLT. Tested with SCRAM_ARCH cc8_amd64_gcc8.
"FRDStreamSource", which does not use above and inserts as "source" does not experience this problem.

Condition which calls the exception was added by this change:
https://github.com/cms-sw/cmssw/commit/a9e7916ceaf37ce211bcbc7009cb982830613b8d#diff-34fb01ea43a1c8a8fe3c97d24f19275eR131

Instruction to reproduce this problem:
- change EventFilter/Utilities/startFU.py : remove "process.daqHistoTest" and "process.hltDQMFileSaver" from the Endpath (configuration needs to be updated due to changes in DQM file saver)
- run: EventFilter/Utilities/test/RunBUFU.sh
- log with the error is found in /tmp/results_${USER}${PID}/out_1_fu.log (new directory for each execution)

notifying: @Dr15Jones

**Comment by Dr15Jones** [comment]
assign core

**Comment by wddgit** [comment]
PR #28791 should fix this. If you notice addition problems, please let me know.

**Comment by makortel** [comment]
@smorovic Would it be feasible to have tests for `FedRawDataInputSource` in CMSSW? Those would help us catching such problems earlier.

**Comment by smorovic** [comment]
I confirm that #28791 fixes the problem.

@makortel I already tried to add RunBUFU.sh as unit test. However this only worked fine in my environment, and it failed with cmsbuild. Since it relies on uses file locking (which I suspect can work or not depending on the filesystem), I will try to implement a similar test that uses a non-file-locking mode of this input source.

**Comment by makortel** [comment]
Thanks @smorovic for confirming https://github.com/cms-sw/cmssw/pull/28791 fixing the problem, and adding a test!

**Comment by smorovic** [comment]
Fix and unt test are merged, so closing this, thanks!
