### ISSUE TITLE
Crash in RivetInterface (NanoAOD) when only 1 incident parton is found 

### ISSUE THREAD

**Issue by srimanob** [cms-sw/cmssw#28803]
Following the recent report on infinite loop in RECOSIM which bug-fix PR is placed in https://github.com/cms-sw/cmssw/pull/28802

Another issue is found in NanoAOD step when local test is done. It seems that in the event mentioned, example at the end (*), somehow parton1 is matched, while parton2 is NULL. This leads to a crash in
https://github.com/cms-sw/cmssw/blob/568c52a6ce12d5bbe3608f58be8f9d66fb02c489/GeneratorInterface/RivetInterface/plugins/GenParticles2HepMCConverter.cc#L139-L154

To test: files (LHE, configuration, root) can be found in
/afs/cern.ch/user/s/srimanob/public/ForPdmV/McM/PPS-RunIIFall18GS-00004

CMSSW_10_2_11_patch1 is used in DR/MiniAOD steps
+ PPS-RunIIFall18GS-00004_1_cfg.py for GEN-SIM
+ PPS-RunIIAutumn18DRPremix-00004_1_cfg.py for DIGI
+ PPS-RunIIAutumn18DRPremix-00004_2_cfg.py for RECO => success if #28802 is integrated
   + Output = PPS-RunIIAutumn18DRPremix-00004.root
+ PPS-RunIIAutumn18MiniAOD-00004_1_cfg.py for MINIAOD
   + Output = PPS-RunIIAutumn18MiniAOD-00004.root

CMSSW_10_2_18 is used for NanoAOD step
+ NanoAOD_PPS_cfg.py

(*)
/afs/cern.ch/user/s/srimanob/public/ForPdmV/McM/PPS-RunIIFall18GS-00004/LPAIR_gammagammaMuMu_inel-el_pt40.lhe.xz

**Comment by Dr15Jones** [comment]
assign generator

**Comment by makortel** [comment]
assign generators

**Comment by qliphy** [comment]
adding @intrepid42 @xjanssen

**Comment by intrepid42** [comment]
Hi Phat, these LHE files are very special, see the first event below.

Do you have a log file where we can see which event number fails?

Maybe it's enough to make change this `and` -> `or`?
https://github.com/cms-sw/cmssw/blob/568c52a6ce12d5bbe3608f58be8f9d66fb02c489/GeneratorInterface/RivetInterface/plugins/GenParticles2HepMCConverter.cc#L141

```
<event>
20 0 0.2983460E-04  0.9118800E+02  0.7546772E-02  0.1300000E+00
    22  -1   0   0   0   0      0.320478      0.727880   -265.319336    265.318573  0.000000 0.  1.000000
    22  -1   0   0   0   0     -0.020876     -0.004164     29.550026     29.550026  0.000000 0. -1.000000
   -13   1   0   0   0   0    -51.421627     52.758270    -35.889500     81.949295  0.105700 0.  0.000000
    13  21   0   0   0   0     51.742111    -52.030392   -229.429840    183.369278  0.105700 0.  0.000000
    13   1   4   0   0   0     51.721230    -52.034554   -199.879807    212.919312  0.105700 0.  0.000000
  2212   1   0   0   0   0      0.020876      0.004164   6470.450195   6470.450195  0.938300 0.  0.000000
     2   3   2   0   0   0      0.925696      0.001816   -663.646667    663.647278  0.005600 0.  0.000000
  2103   3   2   0   0   0     -1.246174     -0.729696  -5571.034668   5571.034668  0.771333 0.  0.000000
     2   3   7   0   0   0      0.925696      0.001816   -663.646667    663.647278  0.005600 0.  0.000000
  2103   3   8   0   0   0     -1.246174     -0.729696  -5571.034668   5571.034668  0.771333 0.  0.000000
    92   3   9   0   0   0     -0.320478     -0.727880  -6234.681152   6234.682129  3.227662 0.  0.000000
   213   2  11   0   0   0      0.150203     -0.147096  -1052.340942   1052.341187  0.803285 0.  0.000000
  2112   1  11   0   0   0     -0.613431     -0.662377  -1634.096069   1634.096558  0.939600 0.  0.000000
   113   2  11   0   0   0      0.142750      0.081593  -3548.244873   3548.244873  0.500378 0.  0.000000
   211   1  12   0   0   0     -0.082213      0.160751   -767.993103    767.993164  0.139600 0.  0.000000
   111   2  12   0   0   0      0.232416     -0.307846   -284.347717    284.347961  0.135000 0.  0.000000
   211   1  14   0   0   0      0.017574      0.186280  -2758.993896   2758.993896  0.139600 0.  0.000000
  -211   1  14   0   0   0      0.125176     -0.104687   -789.251099    789.251160  0.139600 0.  0.000000
    22   1  16   0   0   0      0.232502     -0.294809   -282.420685    282.420868  0.000000 0.  0.000000
    22   1  16   0   0   0     -0.000086     -0.013037     -1.927012      1.927055  0.000000 0.  0.000000
</event>
```

**Comment by srimanob** [comment]
@intrepid42 
Sorry for late reply, I am travelling. I will send the log to you soon.
My test crash in the first event (but it's event 5 of LHE).

My original questions is when the module try to guess what is the parton, does it work correctly to find the first one.

Thx.

**Comment by srimanob** [comment]
To me, event 9 runs first, and it crashed there also:

```
<event>
18 0 0.2983460E-04  0.9118800E+02  0.7546772E-02  0.1300000E+00
    22  -1   0   0   0   0     -0.226451     -1.342210    -34.306725     34.306427  0.000000 0.  1.000000
    22  -1   0   0   0   0     -0.091697     -0.022095     80.237701     80.237701  0.000000 0. -1.000000
    13   1   0   0   0   0     48.365635     -5.329955      1.762468     48.690456  0.105700 0.  0.000000
   -13  21   0   0   0   0    -48.592087      3.987746    -36.069195    -14.384032  0.105700 0.  0.000000
   -13   1   4   0   0   0    -48.683784      3.965650     44.168510     65.853668  0.105700 0.  0.000000
  2212   1   0   0   0   0      0.091697      0.022095   6419.762207   6419.762207  0.938300 0.  0.000000
     2   3   2   0   0   0      0.545083      0.566543  -1021.817078   1021.817444  0.005600 0.  0.000000
  2101   3   2   0   0   0     -0.318632      0.775667  -5443.875977   5443.876465  0.579333 0.  0.000000
     2   3   7   0   0   0      0.545083      0.566543  -1021.817078   1021.817444  0.005600 0.  0.000000
  2101   3   8   0   0   0     -0.318632      0.775667  -5443.875977   5443.876465  0.579333 0.  0.000000
    92   3   9   0   0   0      0.226451      1.342210  -6465.692871   6465.693359  1.814447 0.  0.000000
   223   2  11   0   0   0     -0.005318      0.396791  -2001.558960   2001.559204  0.784647 0.  0.000000
  2212   1  11   0   0   0      0.231769      0.945420  -4464.134277   4464.134277  0.938300 0.  0.000000
   211   1  12   0   0   0     -0.020294     -0.073524   -720.788025    720.788025  0.139600 0.  0.000000
  -211   1  12   0   0   0      0.134932      0.168698   -824.625427    824.625488  0.139600 0.  0.000000
   111   2  12   0   0   0     -0.119957      0.301617   -456.145386    456.145538  0.135000 0.  0.000000
    22   1  16   0   0   0     -0.093442      0.184938   -362.204803    362.204865  0.000000 0.  0.000000
    22   1  16   0   0   0     -0.026514      0.116679    -93.940575     93.940666  0.000000 0.  0.000000
</event>

```

**Comment by srimanob** [comment]
@intrepid42 
I assume if we treat this kind of events with fake vertex, it should be OK. This will allow us to be more flexible in case of issue w/ LHE.

**Comment by intrepid42** [comment]
Ok, that looks reasonable to me: we ask for motherless particles with `abs(pz)>1000` to assign them as beam. In these events, the code finds one proton going in one direction fulfilling those criteria, and crashes because there is no other beam-like particle.
This is different from the `Neutrino_E-10_gun` where we have 0 beam-like particles, and thus the `if` handles the situation by adding fake beam particles.

So I propose to change the code like this:
```diff
- if (parton1 == nullptr and parton2 == nullptr) { 
+ if (parton1 == nullptr or parton2 == nullptr) { 
```

Does that sounds reasonable to everyone?
