### ISSUE TITLE
ConfigParser and Python3  in Alignment/OfflineValidation

### ISSUE THREAD

**Issue by silviodonato** [cms-sw/cmssw#28830]
@mmusich  @christopheralanwest  @franzoni  @tlampen  @pohsun  @tocheng 

The PR #28739 added a unit test crashing in Python3 because of `import ConfigParser` in Alignment/OfflineValidation/python/TkAlAllInOneTool/betterConfigParser.py.
In Python3 "ConfigParser" has been renamed to "configparser". The minimal fix is to replace `import ConfigParser` with `import configparser as ConfigParser` (that is compatible also to Python2.7) (see #28822).
Unfortunately this fix does not work with betterConfigParser.  betterConfigParser uses an hacked version of dictionary (AdaptedDict https://github.com/cms-sw/cmssw/blob/master/Alignment/OfflineValidation/python/TkAlAllInOneTool/betterConfigParser.py#L11-L57). The idea is that if we are parsing the `[validation]` section of the INI file, we fill a list (`validationslist`) instead of using a dictionary (`collections.OrderedDict`).
This check is performed looking at the variable `__name__` inside the dictionary (`self["__name__"]=="validation"`), but unfortunately this trick cannot work in Python3 because the  special key `__name__` has been removed (see https://stackoverflow.com/questions/47200088/when-and-why-has-been-name-magic-variable-removed-from-configparser-in).

I'm afraid the best solution is to change the format of the `[validation]` section in order to avoid repetitions. You can find a working quick&dirty example at https://github.com/cms-sw/cmssw/compare/master...silviodonato:AlCaValPy3

The migration to Python3 should complete in the next months, because the maintenance of Python2 ended on Jan 1, 2020.

**Comment by makortel** [comment]
assign alca

**Comment by mmusich** [comment]
adding @connorpa @vbotta FYI.
There are active moves towards ditching this tool all together (see: https://indico.cern.ch/event/879465/?showDate=all&showSession=0#51-validation-framework )
I am not sure if we want to waste time on this....

**Comment by mmusich** [comment]
@silviodonato 
I started from your branch (which didn't work) and come up with https://github.com/cms-sw/cmssw/pull/28838.
Please have a look.

**Comment by christopheralanwest** [comment]
+1
