### ISSUE TITLE
GEDGsfElectronFinalizer is not thread safe

### ISSUE THREAD

**Issue by Dr15Jones** [cms-sw/cmssw#28849]
In ##28746 GEDGsfElectronFinalizer was changed from a stream module to a global module. Unfornately this broke thread safety since the member data
```
 std::unique_ptr<ModifyObjectValueBase> gedRegression_;
```
is not non-const thread safe. One indicator of a problem was that the member data was not declared
```
std::unique_ptr<ModifyObjectValueBase const> gedRegression_;
```
In addition, these lines
https://github.com/cms-sw/cmssw/blob/23e8336f9ee6b06b081d3a391489b4a92d7d9d23/RecoEgamma/EgammaElectronProducers/plugins/GEDGsfElectronFinalizer.cc#L58-L59

should also have been seen as problematic for a function that is supposed to be thread-safe.

**Comment by Dr15Jones** [comment]
assign reconstruction

**Comment by Dr15Jones** [comment]
This problem was seen by ASAN and is also probably the reason we are getting a seg fault in gcc9 IBs.

**Comment by perrotta** [comment]
Thank you @Dr15Jones , good catch!
Putting that module back as being a stream module should fix it, isn't it?

**Comment by Dr15Jones** [comment]
Going back to a stream would fix it.

**Comment by perrotta** [comment]
#28853 brings back the GEDGsfElectronFinalizer to be a stream module, instead of a global one

**Comment by guitargeek** [comment]
Thanks! Sorry for missing this

**Comment by perrotta** [comment]
+1
- #28853 merged since CMSSW_11_1_X_2020-02-03-2300
