### ISSUE TITLE
EcalDQMCommonUtils relies on global variables, data race

### ISSUE THREAD

**Issue by wddgit** [cms-sw/cmssw#28858]
I see the hard work that went into writing this code. And
someone without experience trying to make CMS code run
concurrently and efficiently might not be aware of the
problems reported here. So I feel a little bad being so negative,
but if we want CMS software to run concurrently and efficiently
we need to improve things like this...

EcalDQMCommonUtils relies on global variables. See
DQM/EcalCommon/src/EcalDQMCommonUtils.cc

std::mutex mapMutex;
EcalElectronicsMapping const *electronicsMap(nullptr);
EcalTrigTowerConstituentsMap const *trigtowerMap(nullptr);
CaloGeometry const *geometry(nullptr);
CaloTopology const *topology(nullptr);

This code gets pointers from the EventSetup system
and puts them in global variables which are accessible by
global functions and tries (but fails) to protect them using
a mutex.

There are several problems:

1. There is a data race because the functions like
getElectronicsMap() do not lock the mutex before
accessing the global variable. It might be true that actual
problems are very rare, but undefined behavior is possible.

2. Much effort has gone into making CMSSW multi-threaded
and much of that involves lock free programming techniques.
A pattern that uses globals protected by a mutex leads to blocking
and poor multi-threading performance. Much better would be to
make these pointers data members of each module. This is the
simplest way and usually the performance is good enough.
Alternatively, a helper class could be written to be used by several
modules or to better organize that code. Or the module could
use one of the caches supported by the Framework or possibly
a dedicated ESProducer could deliver this data in more complicated
cases. The whole purpose of the EventSetup system is to pass this kind
of data to modules. It is efficient and designed for concurrent
operations. Effectively, these globals are used to work around
the EventSetup system and to pass this data between modules.

3. As written, this code would not support data that needs to be
updated at IOV boundaries. It might not be an actual problem,
because maybe CMS never runs jobs that cross IOV boundaries
for this data. I don't know.

4. Violates rule 7-1 of the CMS coding and style rules. "Do not use mutable
global data (no globals)." This also raises issues with data being
communicated outside the Event which can create dependences
between modules that the Framework cannot understand (and
developers also have a hard time understanding). The Framework
cannot efficiently schedule work in a multi-threading environment
when this pattern is followed. It leads to poor performance.
It can also lead to requirements on the order modules are executed
which makes it difficult to write configurations and can lead
to data not found exceptions.

I noticed this problem as I was working on the migration to add calls
to esConsumes for all modules that get data from the EventSetup.
The whole purpose of the migration is to improve concurrency
of the EventSetup system and the code that uses it. At least
for the moment, I am skipping the modules that led me to look at this,
so I can continue with the consumes migration. Enough code depends
on this that it will be a non-trivial amount of work to fix this. I'm
not sure who will do it or when...

**Comment by Dr15Jones** [comment]
assign dqm

**Comment by jfernan2** [comment]
FYI @tanmaymudholkar

**Comment by jfernan2** [comment]
ping @tanmaymudholkar

**Comment by tanmaymudholkar** [comment]
Hi @jfernan2 , sorry for the delay, we were focusing on the concurrent lumis for the last few days, we will look into this asap.

**Comment by jfernan2** [comment]
ping @tanmaymudholkar

**Comment by jfernan2** [comment]
+1
solved by https://github.com/cms-sw/cmssw/pull/33200   afaiu
