### ISSUE TITLE
Mistaken use of pt instead of phi in JetCorrectionUncertainty

### ISSUE THREAD

**Issue by jrueb** [cms-sw/cmssw#28860]
I noticed the following line 
https://github.com/cms-sw/cmssw/blob/2a0f8519866fae6b40a9f734a36c3c3282261299/CondFormats/JetMETObjects/src/JetCorrectionUncertainty.cc#L124
 It looks like it's supposed to push back phi (`result.push_back(mJetPhi);`) but instead it actually pushes pt. The pushing of pt is done already in the lines above it. Isn't this a mistake?
(Previously reported at https://github.com/cms-nanoAOD/cmssw/issues/495)

**Comment by Dr15Jones** [comment]
assign alca, reconstruction

**Comment by christopheralanwest** [comment]
Adding JetMET experts: @juska @lathomas @ahinzmann

**Comment by christopheralanwest** [comment]
+1

- Bug fix PRs are merged.

**Comment by perrotta** [comment]
+1
- Fix integrated in the master, in 10_6 and 10_2
