### ISSUE TITLE
[DD4hep] DDFilteredView add an accessor to a vector from a SpecPar by a path selector  

### ISSUE THREAD

**Issue by ianna** [cms-sw/cmssw#28871]
requested by @slomeo

**Comment by makortel** [comment]
assign geometry

**Comment by slomeo** [comment]
@ianna any news about this PR?

**Comment by cvuosalo** [comment]
@ianna This issue is becoming urgent. Are you able to work on it?

**Comment by ianna** [comment]
urgent

**Comment by ianna** [comment]
+1

this feature is already used in #29111
