### ISSUE TITLE
Migration to DD4hep: Geometric(Timing)Det dependence on DDD

### ISSUE THREAD

**Issue by fabiocos** [cms-sw/cmssw#28914]
In the process of migrating the MTD reco geometry to DD4hep, I notice that the ```GeometricTimingDet``` object in ```MTDNumberingBuilder```, as well as its tracker counterpart ```GeometricDet```, depend explicitly on DDD through ```DDSolidShape``` and the use of the ```ExpandedNode```. This means that even the present tracker migration is not fully complete.

Before inventing ad-hoc solutions, I would like to understand from @ianna and @cvuosalo whether they already envisaged a strategy to manage this issue.

@vargasa FYI

**Comment by fabiocos** [comment]
assign geometry

**Comment by ianna** [comment]
@cvuosalo and @fabiocos - following the discussion with Adinda here.
Given that we want to support the legacy payloads and due to a recorded `int` as a shape identifier in a `PGeometricDet` we need to make sure that the old and the new `DDSolidShape` enums are identical. It's not the case now:
https://cmssdt.cern.ch/lxr/source/DetectorDescription/Core/interface/DDSolidShapes.h#0006
https://cmssdt.cern.ch/lxr/source/DetectorDescription/DDCMS/interface/DDSolidShapes.h#0062

**Comment by fabiocos** [comment]
@ianna thanks for looking into this. Silly question: what was the reason for this choice at the beginning of the porting? I mean I see that the two lists mostly overlaps, and codes could be made correspondent,  with 2 o3 noticeable differences. Do we have loops that are preventing discontinuities in the lists? The question is of course about the correspondence of polycones and plyhedras...

**Comment by ianna** [comment]
> @ianna thanks for looking into this. Silly question: what was the reason for this choice at the beginning of the porting? I mean I see that the two lists mostly overlaps, and codes could be made correspondent, with 2 o3 noticeable differences. Do we have loops that are preventing discontinuities in the lists? The question is of course about the correspondence of polycones and polyhedras...

Changing `enum` was intentional to weed out reliance on `int`.

**Comment by fabiocos** [comment]
@ianna sorry, perhaps I was not clear. I am not questioning the ```enum``` choice, just wondering about the reason for the two different structures.

**Comment by cvuosalo** [comment]
@fabiocos Adinda is fixing the `DDSolidShape` issue in these files, but the `DDExpandedView` part still needs to be migrated. What are your plans for migrating these files?

**Comment by fabiocos** [comment]
@cvuosalo are you speaking of 
https://github.com/cms-sw/cmssw/blob/master/Geometry/MTDNumberingBuilder/interface/GeometricTimingDet.h#L41
https://github.com/cms-sw/cmssw/blob/master/Geometry/MTDNumberingBuilder/interface/GeometricTimingDet.h#L41
?

This dependence seems completely fake to me, given that it is just a common type definition:
https://github.com/cms-sw/cmssw/blob/master/DetectorDescription/Core/interface/DDExpandedView.h#L48

and we might either put this common definition somewhere else or just cut-and-paste it explicitly (I do not see anything thrilling in a vector of integers).

As far as ```PoolAlloc``` is concerned, I do not see any definition or use of it within CMSSW, is this a remnant of the past?

**Comment by cvuosalo** [comment]
@fabiocos Actually, Adinda has just fixed the `nav_type` in #29905. There is still the `using GeoHistory = std::vector<DDExpandedNode>;` to remove or fix in several MTD and Tracker files.
I think `PoolAlloc` is obsolete and can be deleted.
Could you and @adewit please coordinate on how these fixes can be made?

**Comment by adewit** [comment]
Hi, I had another look at the `DDExpandedNode` usage in the code today to see if it might be straightforward to do these fixes. I see that `DDFilteredView` has a `geoHistory` method which returns a vector of `DDExpandedNode`s. It looks like in `cms::DDFilteredView` that has been replaced by a method that returns a vector of `TGeoNode`s - I'm afraid I don't have time to try to understand how this is different from what was used in the old DD case (and thus how any methods called on `GeoHistory`s would have to be modified)

**Comment by cvuosalo** [comment]
@adewit, @fabiocos, @vargasa The DD4hep migration of the `TrackerNumberingBuilder` won't be complete until the dependence on `DDExpandedNode` is handled. Can one of you perform this task?

**Comment by fabiocos** [comment]
@adewit see my comments in https://github.com/cms-sw/cmssw/pull/30276#issuecomment-646212566 In my understanding ```GeometricDetExtra``` is just a debugging tool used in a very limited number of places. Is it still actively used by the Tracker community?

Assuming the answering is yes, in my view the issue is not how to extract the GeoHistory information used from ```cms::DDFilteredView```, because for that I believe one could just use that history in a manner similar to what I do in my MTD test code, where I build the whole volume hierarchy above a given node. The issue is more linked to the fact that one of the data members of this class is a DDD object, and it cannot be kept as it is if you want to become independent of it. One simple possibility is to replace it with a structure of arrays, one containing volume names and the other corresponding copy numbers (what I call basenames) encoding the information that is practically used for what I can see in the debugging code.

**Comment by adewit** [comment]
Adding @mmusich since he probably knows this better than me. I agree it looks like `GeometricDetExtra` is just used for debugging in the tracker code, but someone might need the plugins that use it anyway.

**Comment by cvuosalo** [comment]
PR #29905 has migrated the Tracker Numbering Builder GeometricDet objects to DD4hep. Now the same changes need to be made to the MTD Numbering Builder.

**Comment by cvuosalo** [comment]
MTD Numbering Builder migration has been completed with the merging of #30834. This issue can be closed.

**Comment by cvuosalo** [comment]
+1
