### ISSUE TITLE
Writing an ESProducer to create a record holding a tensorflow::Session object

### ISSUE THREAD

**Issue by simonepigazzini** [cms-sw/cmssw#28912]
Dear Experts,

in the context of the H->gg analysis we would like to have in our framework too share the same
tensorflow::Session among different EDProducers. This is in order to reduce the virtual memory used by each process.

My idea is to embed the tensorflow::Session object inside a record that is produced by a dedicatd ESProducer at the beginning of each job and is then accessed by each plugin that requires the session. I managed to get the Record and the ESProducer to compile but I am now get a runtime error [1]. My understanding is that an ESProducer only inject its record into the event setup once an IOV change is detected from a "parent" record. In the case of the tensorflow::Session there is no natural "parent" record to monitor so I see two possibilities:
1) Make the ESProducer dependent on a random record.
2) Force the ESProducer to inject the record at the beginning of the processing.

I can test option 1 but I am not sure that option 2 is at all foreseen by the framework. Is there a way to force the IOV  for an ESProducer without making it dependent on any other ESSource or ESProducer? 

Thank you,
simone  

[1] 
```
No "flashgg::TensorFlowWrapperRcd" record found in the EventSetup.n
The Record is delivered by an ESSource or ESProducer but there is no valid IOV for the synchronizatio value.
 Please check 
   a) if the synchronization value is reasonable and report to the hypernews if it is not.
   b) else check that all ESSources have been properly configured. 
```

**Comment by makortel** [comment]
A new record that does not depend on any other record needs to have an IOV produced by an `ESSource` (error message's case b). You can either modify your `ESProducer` to become also an `ESSource`, or use `EmptyESSource` to create the IOV of the record and continue to use your `ESProducer`.

For `EmptyESSource` there are plenty of examples in CMSSW, see e.g.
https://github.com/cms-sw/cmssw/blob/master/Geometry/CaloEventSetup/python/FakeCaloAlignments_cff.py

To make your `ESProducer` also an `ESSource`, you need to
* make it inherit from `edm::EventSetupRecordIntervalFinder` (in addition to `edm::ESProducer`)
* override `setIntervalFor()` function
* declare the plugin with `DEFINE_FWK_EVENTSETUP_SOURCE` macro
* use `cms.ESSource(...)` in the configuration

For an example, see e.g.
https://github.com/cms-sw/cmssw/blob/master/CalibTracker/SiPixelESProducers/interface/SiPixelFakeGainESSource.h
https://github.com/cms-sw/cmssw/blob/master/CalibTracker/SiPixelESProducers/plugins/SiPixelFakeGainESSource.cc

**Comment by makortel** [comment]
@slava77 @perrotta @riga Could this kind of ESProducer be of wider interest?

**Comment by slava77** [comment]
> @slava77 @perrotta @riga Could this kind of ESProducer be of wider interest?

There were no clear use cases in reco so far (other than this issue?); however I can think of some in the HLT context.

**Comment by simonepigazzini** [comment]
@makortel thank you for the suggestions. I went for the EmptyESSource and it works just fine. I am testing now if the memory usage is indeed the one expected from a single session. I am also doing something similar for BDTs, in my case is for a TMVA::Reader but I think it could be adapted easily for the GBRForest. 

I think this might be of interest for analysis mainly, in our case the issue arise from executing the same sequence for different systematic variations. Of course this can be solved in many other ways but we do not want to rewrite our framework at the moment so we are going for this solution.

Once I clean up the working branch in which I'm testing the ESproducer I'll link the code here for you to take a look in case you're interested.

simone

**Comment by makortel** [comment]
@hajohajo reminded me privately that there actually would be a use case for using the same graph in multiple modules in track selection (the earlier DNN attempt used LWTNN, IIRC only as a temporary solution while waiting for the initial TF integraion in #19893 to converge).

That spurred a question in my head: @simonepigazzini in the description of this issue you wrote
>  share the same tensorflow::Session among different EDProducers

IIUC, the `tensorflow::Session` is not a thread-safe object (although it is thread friendly, and e.g. https://github.com/cms-sw/cmssw/blob/master/RecoBTag/TensorFlow/plugins/DeepVertexTFJetTagsProducer.cc creates `tensorflow::GraphDef` in the global cache, and `tensorflow::Session` for each EDM stream). How exactly are you dealing with `tensorflow::Session` in the ESProducer?

**Comment by simonepigazzini** [comment]
Hi @makortel,

in the most basic way at the moment ... I simply store a pointer to the session embed it into a container which is the actual record (which holds all the TF sessions).
I think this should be made safer at least by using a shared pointer. I also need to do a const_cast in order to pass the session to other tensorflow routines since the objects inside the ES are const.

The working branch is here now:
https://github.com/simonepigazzini/flashgg/tree/topic_ttH_RunII_MVAs_v3

The implementation is under DataFormats:
ESProducer: https://github.com/simonepigazzini/flashgg/blob/topic_ttH_RunII_MVAs_v3/DataFormats/plugins/TensorFlowObjectsESProducer.cc

Object: https://github.com/simonepigazzini/flashgg/blob/topic_ttH_RunII_MVAs_v3/DataFormats/interface/TensorFlowWrapperObj.h

and sage example:
https://github.com/simonepigazzini/flashgg/blob/topic_ttH_RunII_MVAs_v3/Taggers/plugins/TTHHadronicTagProducer.cc#L1187-L1193

https://github.com/simonepigazzini/flashgg/blob/topic_ttH_RunII_MVAs_v3/Taggers/python/flashggTagSequence_cfi.py#L43-L64

simone

**Comment by simonepigazzini** [comment]
I was not aware of the existence of `edm::GlobalCache`, does it work also across different plugins? From the DeepVertex esample I understand it's meant to serve as a chace across different version of the same producer running in different threads, correct?

simone

**Comment by makortel** [comment]
@simonepigazzini Thanks for the details.

> I also need to do a `const_cast` in order to pass the session to other tensorflow routines since the objects inside the ES are const.

This is almost certainly not thread safe.

> I was not aware of the existence of `edm::GlobalCache`, does it work also across different plugins? 

It does not.

> From the DeepVertex esample I understand it's meant to serve as a chace across different version of the same producer running in different threads, correct?

Exactly, the purpose of `edm::GlobalCache` is to share a thread-safe cache among the EDM stream instances of the same module.

I believe we'd need a proper (safe and efficient) implementation for a TensorFlow-ESProducer.

**Comment by simonepigazzini** [comment]
I think to start with I can change the ESProducer to produce an object that stores the `tensorflow::GraphDef` only, I think it should be ok for that to have it const.

**Comment by makortel** [comment]
How heavy is the creation of `tensorflow::Session`? Is it something that could be done for every event? (I doubt, but let's make sure; the following assumes it is too heavy to be created for every event)

One option would be to share the `tensorflow::GraphDef` to multiple modules as an ESProduct, and the modules would then create the `tensorflow::Session` in their `produce()` at the first call (and store the `Session` as a member variable of an `edm::stream` module or in the stream cache of an `edm::one` module).

Another option would be to have an ESProduct that contains the `GraphDef` and an `edm::ReusableObjectHolder`, and creates the `Session` objects on the fly and caches them for later use (`ReusableObjectHolder` helps to do that in a thread-safe way).

The former option would imply N(modules)xN(streams) `Session` objects, while the latter would imply at most N(threads) (plus maybe one to cover the cases where one thread is getting a `Session` while another one is returning one) and some synchronization cost.

**Comment by makortel** [comment]
By now `tensorflow::Session` has become thread safe, and there is an `ESProducer` that creates an EventSetup data product containing both the `GraphDef` and `Session`
https://github.com/cms-sw/cmssw/blob/4635bff7d6bee3aaee115ae16ec4c540ca76d7b0/PhysicsTools/TensorFlow/plugins/TfGraphDefProducer.cc#L28
https://github.com/cms-sw/cmssw/blob/4635bff7d6bee3aaee115ae16ec4c540ca76d7b0/PhysicsTools/TensorFlow/interface/TfGraphDefWrapper.h#L6

I think this issue can be closed. FYI @cms-sw/ml-l2

**Comment by makortel** [comment]
@cmsbuild, please close
