### ISSUE TITLE
[GCC9] Fix fortran warning in GeneratorInterface/PartonShowerVeto

### ISSUE THREAD

**Issue by mrodozov** [cms-sw/cmssw#28928]
There is a warning about uninit var in:
https://cmssdt.cern.ch/SDT/cgi-bin/buildlogs/slc7_amd64_gcc900/CMSSW_11_1_X_2020-02-11-2300/GeneratorInterface/PartonShowerVeto
which we'd like to know what init value to use for, to fix the warning.

**Comment by makortel** [comment]
assign generators

**Comment by agrohsje** [comment]
Just to say: I am not aware of anybody using this code. 
YCUT  should be something say 100 or similar. So we can initialize it with a neg value and throw an error if it is below 0.

**Comment by makortel** [comment]
> Just to say: I am not aware of anybody using this code.

Can this piece of code be removed then?

**Comment by silviodonato** [comment]
> > Just to say: I am not aware of anybody using this code.
> 
> Can this piece of code be removed then?

@agrohsje

**Comment by agrohsje** [comment]
@qliphy @mkirsano @SiewYan 
checking the history, I don't think this is still used:  
https://github.com/cms-sw/cmssw/tree/master/GeneratorInterface/PartonShowerVeto
plotting matching is in genproductions.  please comment as well.

**Comment by qliphy** [comment]
It might still be safe to keep the package for the moment.

To fix the warning, I agree with @agrohsje "YCUT should be something say 100 or similar. So we can initialize it with a neg value and throw an error if it is below 0."

**Comment by smuzaffar** [comment]
https://github.com/cms-sw/cmssw/pull/29757 should resolve this issue.
