### ISSUE TITLE
[DD4Hep] Unit test fails because of NULL values in XML

### ISSUE THREAD

**Issue by mrodozov** [cms-sw/cmssw#28973]
The latest integration test https://github.com/cms-sw/cmsdist/pull/5554 of DD4Hep fails because of failing to parse the NULL values in this section:
https://github.com/cms-sw/cmssw/blob/master/Geometry/TrackerCommonData/data/tibstring0ll.xml#L71
seems to be line 
https://github.com/cms-sw/cmssw/blob/master/Geometry/TrackerCommonData/data/tibstring0ll.xml#L79
```
Detector         INFO  *********** Created World volume with size: 10100 10100 45000
DD4CMS           ERROR Exception while processing xml source:file:///data/cmsbld/jenkins/workspace/ib-run-pr-tests/CMSSW_11_1_X_2020-02-16-2300/src/Geometry/TrackerCommonData/data/tibstring0ll.xml
DD4CMS           ERROR ----> The type std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > cannot be converted: Data conversion of [tibstringpar:NULL,tibstringpar:NULL,tibstringpar:NULL] to type 'std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >' is not defined.
dd4hep: Error interpreting XML nodes of type <Algorithm/>
E
```
Both test fail for the same reason , fail to parse that part, see https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-60f4e6/4695/unitTests.log

Please suggest what to do / provide a fix.

**Comment by makortel** [comment]
assign geometry

**Comment by cvuosalo** [comment]
#28951 may be related to this issue. It was recently merged.

**Comment by cvuosalo** [comment]
The unit test runs fine in CMSSW_11_1_X_2020-02-17-1100

**Comment by cvuosalo** [comment]
@mrodozov Could you please clarify what previous version of DD4hep were we using? And what version of DD4hep is failing this unit test?

**Comment by mrodozov** [comment]
The unit test is failing in the integration test for the update of DD4hep external, they are not failing in the current IB.
The versions can be seen here:
https://github.com/cms-sw/cmsdist/pull/5554/files , the one we are using currently is:
https://github.com/AIDASoft/DD4hep/commit/5bbbb8c86ff764eb452608b5439db90b5e3d2450
and the one we one to update to is 
https://github.com/AIDASoft/DD4hep/commit/e7882469767472c5d018b74fa13e600e9aba31d3
To setup the new version and run it to fail do this:

```
ssh cmsdev21 ; mkdir -p /build/${USER} ; cd /build/${USER} 
git clone https://github.com/cms-sw/cms-bot
 ./cms-bot/test-prs.sh cms-sw/cmsdist#5554
# when the pull request is built go in the checked CMSSW area and checkout 
git-cms-addpkg DetectorDescription/DDCMS
scram b -j 16
scram b runtests
```
to make the unit tests fail

**Comment by cvuosalo** [comment]
Issue opened with DD4hep: https://github.com/AIDASoft/DD4hep/issues/628

**Comment by cvuosalo** [comment]
This problem is fixed with the new version of DD4hep. See https://github.com/cms-sw/cmsdist/pull/5554

**Comment by cvuosalo** [comment]
+1
