### ISSUE TITLE
Missing file and xrootd-cms.infn.it

### ISSUE THREAD

**Issue by silviodonato** [cms-sw/cmssw#28983]
The unit test of Calibration/LumiAlCaRecoProducers
is crashing because there is a glitch in xrootd-cms.infn.it redirector.
```
----- Begin Fatal Exception 18-Feb-2020 03:47:39 CET-----------------------
An exception of category 'FileOpenError' occurred while
   [0] Constructing the EventProcessor
   [1] Constructing input source of type PoolSource
   [2] Calling RootFileSequenceBase::initTheFile()
   [3] Calling StorageFactory::open()
   [4] Calling XrdFile::open()
Exception Message:
Failed to open the file 'root://xrootd-cms.infn.it//store/data/Commissioning2018/AlCaLumiPixels0/ALCARECO/AlCaPCCRandom-02May2018-v1/70000/6CE65B93-D657-E811-BBB5-FA163E8006EF.root'
   Additional Info:
      [a] Input file root://xrootd-cms.infn.it//store/data/Commissioning2018/AlCaLumiPixels0/ALCARECO/AlCaPCCRandom-02May2018-v1/70000/6CE65B93-D657-E811-BBB5-FA163E8006EF.root could not be opened.
      [b] XrdCl::File::Open(name='root://xrootd-cms.infn.it//store/data/Commissioning2018/AlCaLumiPixels0/ALCARECO/AlCaPCCRandom-02May2018-v1/70000/6CE65B93-D657-E811-BBB5-FA163E8006EF.root', flags=0x10, permissions=0660) =&gt; error '[ERROR] Operation expired' (errno=0, code=206). No additional data servers were found.
      [c] Last URL tried: root://heplnx228.pp.rl.ac.uk:1094//store/data/Commissioning2018/AlCaLumiPixels0/ALCARECO/AlCaPCCRandom-02May2018-v1/70000/6CE65B93-D657-E811-BBB5-FA163E8006EF.root?tried=
      [d] Problematic data server: heplnx228.pp.rl.ac.uk:1094
      [e] Disabled source: heplnx228.pp.rl.ac.uk:1094
----- End Fatal Exception -------------------------------------------------
```
https://cmssdt.cern.ch/SDT/cgi-bin/buildlogs/raw/slc7_amd64_gcc820/CMSSW_11_1_PY3_X_2020-02-17-2300/unitTestLogs/Calibration/LumiAlCaRecoProducers

Searching for "xrootd-cms.infn.it" in CMSSW I realized that this is the only unit test using xrootd-cms.infn.it 
https://cmssdt.cern.ch/lxr/search?%21v=CMSSW_11_1_X_2020-02-17-2300&_filestring=&_string=xrootd-cms.infn.it
Many more tests use cms-xrd-global.cern.ch
https://cmssdt.cern.ch/lxr/search?%21v=CMSSW_11_1_X_2020-02-17-2300&_filestring=&_string=cms-xrd-global.cern.ch

Could you move the re-director from xrootd-cms.infn.it to cms-xrd-global.cern.ch or, even better, use cms-data?

**Comment by silviodonato** [comment]
assign alca

**Comment by smuzaffar** [comment]
I would suggest to just use LFN e.g. `/store/data/Commissioning2018/AlCaLumiPixels0/ALCARECO/AlCaPCCRandom-02May2018-v1/70000/6CE65B93-D657-E811-BBB5-FA163E8006EF.root` instead of 'root://xrootd-cms.infn.it//store/data/Commissioning2018/AlCaLumiPixels0/ALCARECO/AlCaPCCRandom-02May2018-v1/70000/6CE65B93-D657-E811-BBB5-FA163E8006EF.root' . This file has already been caches in our ibeos. So using the LFN will allow our test system to use the cached version

**Comment by silviodonato** [comment]
Fixed in #28987

**Comment by silviodonato** [comment]
thanks @smuzaffar , I was not aware of the file caches in our ibeos

**Comment by christopheralanwest** [comment]
+1
