### ISSUE TITLE
Phase2TrackerDigitizerAlgorithm::convertSignalToAdc dominated by LogInfo

### ISSUE THREAD

**Issue by davidlange6** [cms-sw/cmssw#29001]
from
http://mkortela.web.cern.ch/mkortela/cgi-bin/navigator/premix_d35_1040mtd5/test_06_perf/51

it appears that a LogTrace instead of LogInfo here:

https://github.com/cms-sw/cmssw/blob/master/SimTracker/SiPhase2Digitizer/plugins/Phase2TrackerDigitizerAlgorithm.cc#L979

may save 2-4% of a premixing job in HLLHC configuration.

**Comment by davidlange6** [comment]
assign sim

**Comment by davidlange6** [comment]
assign simulation

On Feb 19, 2020, at 7:31 PM, David Lange <notifications@github.com<mailto:notifications@github.com>> wrote:


assign sim

**Comment by kpedro88** [comment]
assign upgrade

**Comment by kpedro88** [comment]
@suchandradutta could you take a look at this?

**Comment by kpedro88** [comment]
+upgrade
resolved by #29041

**Comment by civanch** [comment]
+1
