### ISSUE TITLE
[DD4hep] Implement delayed Vector evaluation 

### ISSUE THREAD

**Issue by ianna** [cms-sw/cmssw#29057]
`Vector` is defined in `ConstantsSection` and can refer to the unresolved constants from the same section. The unresolved constants are cached and evaluated at the end of the `ConstantsSection`s processing. The same should be done with `Vector`s

requested by @bsunanda

**Comment by ianna** [comment]
assign geometry

**Comment by bsunanda** [comment]
@ianna Please let me know if this is resolved

**Comment by ianna** [comment]
> @ianna Please let me know if this is resolved

@bsunanda - no, not yet. I haven't had a chance to start working on it properly. I did a quick prototype where I resolve constants file by file did not work - some calculations required ALL constant sections from ALL files to be parsed first. So next iteration will be either adding a registry of unresolved vectors and then resolve them or making a new section: `VectorSection`. The latter would be a better solution, but require changes in current XML. What do you think?

**Comment by cvuosalo** [comment]
@ianna At this late date, I think we want to avoid any changes that would require XML changes. If we can change the code to handle the current XML, even if the design is not ideal, that's what we need to do.

**Comment by ianna** [comment]
Close via **[DD4hep] Add delayed Vector resolution** #29126

**Comment by ianna** [comment]
+1
