### ISSUE TITLE
Is GenXSecAnalyzer still useful?

### ISSUE THREAD

**Issue by makortel** [cms-sw/cmssw#29098]
The `GenXSecAnalyzer` is an `edm::one::EDAnalyzer<edm::one::WatchRuns, edm::one::WatchLuminosityBlocks>` that prevents efficient use of concurrent luminosity blocks (https://github.com/cms-sw/cmssw/issues/25090#issuecomment-594119628). By quick look it aggregates various information in `endLuminosityBlock()` and `endRun()`, and prints out the result in `endJob()`.

Is this behavior needed in MC production (or RelVals)? Are these printouts looked at systematically?

**Comment by makortel** [comment]
assign generators

**Comment by qliphy** [comment]
@makortel   

GenXSecAnalyzer is used to gather cross section and filter informations from each luminosityBlock, and then combine them to reach high accuracy with larger statistics.  
https://twiki.cern.ch/twiki/bin/viewauth/CMS/HowToGenXSecAnalyzer

This is needed in MC production, especially for MC Contacts who make McM requests and need to input these information (especially on Filter/Matching efficiency which affect the job submission ) based on the print out.

**Comment by makortel** [comment]
@qliphy Thanks. Is it needed in every GEN job (notably in RelVal and production)? Or would it be sufficient if it could be easily included in a GEN job when needed, but it would not be run by default?

**Comment by qliphy** [comment]
@makortel  Yes, I think for RelVal and Production, this is not needed to be run .

**Comment by makortel** [comment]
How are the configurations for the MC contacts created? Is there perhaps a template, a recipe for cmsDriver command, or generation by a web service?

I'm just thinking if a modifier (e.g. `--processModifier genXsecAnalyzer` for cmsDriver) would work, and where exactly that would need to be propagated (recipe on webpage/twiki, script, web service)

**Comment by qliphy** [comment]
The cmsDriver commands for MC contacts are got from McM automatically:
[B2G-RunIISummer15GS-00007](https://cms-pdmv.cern.ch/mcm/requests?prepid=B2G-RunIISummer15GS-00007&page=0&shown=127)
and
https://cms-pdmv.cern.ch/mcm/public/restapi/requests/get_test/B2G-RunIISummer15GS-00007

**Comment by makortel** [comment]
Thanks. So in principle it could be sufficient to modify McM to add an extra parameter to `cmsDriver` for the MC contacts, right? Does/can McM give a (slightly) different `cmsDriver` for production? Can that depend on CMSSW version?

Who should be contacted to get such change in McM?

**Comment by qliphy** [comment]
adding @justinasr and @pgunnell

**Comment by makortel** [comment]
Made obsolete by GenXSecAnalyzer getting migrated to be thread efficient in https://github.com/cms-sw/cmssw/pull/29328.
