### ISSUE TITLE
Convert TriggerRulePrefireVetoFilter.cc to callable function

### ISSUE THREAD

**Issue by benkrikler** [cms-sw/cmssw#29145]
I would like to be able to call the functionality of `EventFilter/L1TRawToDigi/plugins/TriggerRulePrefireVetoFilter.cc` from elsewhere but not use it as purely a filter.  Is it reasonable to convert this plugin to a simple function and then use that function within the existing plugin so we maintain the existing functionality?

I can implement this but having not done this sort of thing before, is there anything I would need to know before I do it?

**Comment by makortel** [comment]
assign l1

**Comment by makortel** [comment]
Something along the following should work out
* create a new function in `EventFilter/L1TRawToDigi/interface/<NewFunction>.h` and `EventFilter/L1TRawToDigi/src/<NewFunction>.cc` that takes `const TCDSRecord&` as a parameter, move the relevant content fro `filter()` there
* use that function in `TriggerRulePrefireVetoFilter.cc`
* if the "elsewhere" is in another package, declare that package to depend on `EventFilter/L1TRawToDigi`
   * if the another package may not depend on `EventFilter/L1TRawToDigi`, need to find a new place for the function that both packages can depend on
* use the function in "elsewhere"

**Comment by cecilecaillol** [comment]
No interest anymore in this functionality, we can close the issue

**Comment by cecilecaillol** [comment]
+l1
