### ISSUE TITLE
Build CMSSW_11_1_0_pre4_GEANT4_NativeGeom

### ISSUE THREAD

**Issue by civanch** [cms-sw/cmssw#29178]
Recently a new build CMSSW_11_1_0_pre4_GEANT4 was produced. 

At the recent release meeting we requested to make CMSSW_11_1_0_pre4_GEANT4_NativeGeom which does not use VecGeom but only native geometry. This release will be use to analize Run-3 geometry and to cross check VecGeom and Native geometry of Geant4.

**Comment by smuzaffar** [comment]
@civanch , I am working on updating cmsdist to remove vecgeom dependency . Once ready we will build this special release.

**Comment by smuzaffar** [comment]
@civanch , I have open https://github.com/cms-sw/cmssw/issues/29192 to build this special release
