### ISSUE TITLE
Consider edm::async()

### ISSUE THREAD

**Issue by makortel** [cms-sw/cmssw#29188]
PR https://github.com/cms-sw/cmssw/pull/29141 uses mostly-sleeping threads to achieve "pseudo asynchronous" behavior with RPC API's that do not provide fully asynchronous API (thread does the remote calls, then blocks the thread to wait for response, and after waking up notifies the `edm::WaitingTaskWithArenaHolder` that the work is done). If the use such threads starts to spread (more classes, more modules), it could be beneficial to abstract that behavior.

In a sense `std::async()` does the job, except
* thread behavior is unspecified (create+join every time vs pool)
* returns a `future` with which one can either query the state, or block the calling thread
  * Concurrency TS adds continuation passing which is the behavior we want

One option would be to create `edm::async()` that uses a specific thread pool to minimize thread creation and joining, and continuation passing (e.g. requiring `edm::WaitingTaskWithArenaHolder` be passed around).

**Comment by makortel** [comment]
assing core

**Comment by makortel** [comment]
assign core

**Comment by fwyzard** [comment]
Would that need a Service to own the thread pool ?

**Comment by makortel** [comment]
I haven't managed to come up with a better solution than a Service or a singleton object for a "nice" API, and that is the part I don't like that much.

**Comment by makortel** [comment]
Implemented in https://github.com/cms-sw/cmssw/pull/44901
