### ISSUE TITLE
METAnalyzer::makeRatePlot calculation incorrect

### ISSUE THREAD

**Issue by Dr15Jones** [cms-sw/cmssw#29187]
The function METAnalyzer::makeRatePlot appears to have been broken since 2014. Is this really needed anymore since it is causing complications for concurrent luminosity running.

**Comment by Dr15Jones** [comment]
assign dqm

**Comment by jfernan2** [comment]
Hi @Dr15Jones  I am notifying JetMET DQM/Validation contacts to have an answer:
@iatakisi @ramankhurana

**Comment by Dr15Jones** [comment]
The function METAnalyzer::makeRatePlot

https://github.com/cms-sw/cmssw/blob/7bf830bbb5f57be6673227056342a5adf8c88567/DQMOffline/JetMET/src/METAnalyzer.cc#L1388-L1411

actually ends up just calculating a histogram which is equivalent to the histogram labeled `DirName +"/MET"` but divided by `tottime`

This was not what the original function did prior to 2014
https://github.com/cms-sw/cmssw/blame/567f9f9411e2dcc19c6362ed792a4fdbc6e240b4/DQMOffline/JetMET/src/METAnalyzer.cc#L580

Where bins from the new histograms are affecting the values of neighboring bins.

**Comment by Dr15Jones** [comment]
ping

**Comment by jfernan2** [comment]
ping @iatakisi @ramankhurana

**Comment by jfernan2** [comment]
This issue is solved by https://github.com/cms-sw/cmssw/pull/32041

**Comment by jfernan2** [comment]
+1
