### ISSUE TITLE
 CSC migration to DD4HEP  

### ISSUE THREAD

**Issue by silviodonato** [cms-sw/cmssw#29202]
After #29111, @slomeo this is a reminder to "useDD4hep" to a tracked paramter (https://github.com/cms-sw/cmssw/pull/29111/files#diff-795f20cbe45a874da3809baf1e566662R32).  
As suggested by @fabiocos , you could also use https://cmssdt.cern.ch/lxr/source/Configuration/ProcessModifiers/python/dd4hep_cff.py  to switch on dd4hep.

**Comment by silviodonato** [comment]
assign geometry

**Comment by ianna** [comment]
@silviodonato - please, check the implementation and close or update the issue. Thanks!
https://cmssdt.cern.ch/lxr/source/Geometry/CSCGeometryBuilder/python/cscGeometry_cfi.py#0023

**Comment by cvuosalo** [comment]
+1
