### ISSUE TITLE
Dataset deleted from T2_CH_CERN

### ISSUE THREAD

**Issue by silviodonato** [cms-sw/cmssw#29204]
The dataset 
`/RelValTTbar_14TeV/CMSSW_10_6_1-106X_mcRun3_2021_realistic_v1_rsb-v1/GEN-SIM`
is available only at `T1_US_FNAL_Disk` and it is not available at `T2_CH_CERN`
https://cmsweb.cern.ch/das/request?instance=prod/global&input=site+dataset%3D%2FRelValTTbar_14TeV%2FCMSSW_10_6_1-106X_mcRun3_2021_realistic_v1_rsb-v1%2FGEN-SIM

As a result, step1 of `runTheMatrix.py -l 13034.0 -i all --job-reports -t 4 &>logRunMatrix` gives no entries `dasgoclient --limit 0 --query 'file dataset=/RelValTTbar_14TeV/CMSSW_10_6_1-106X_mcRun3_2021_realistic_v1_rsb-v1/GEN-SIM site=T2_CH_CERN' | ibeos-lfn-sort -u > step1_dasquery.log  2>&1 `

This might explain the failure of 13034.0 during the IB tests of CMSSW_11_1_X_2020-03-13-2300

https://github.com/cms-sw/cmssw/blob/master//Configuration/PyReleaseValidation/python/relval_steps.py#L3114-L3117

------------------------------------------------------------------------------------

We have a similar problem  in wf 310.0, 311.0, 312.0 because  `/RelValHydjetQ_B12_5020GeV_2021/CMSSW_10_6_0-106X_upgrade2018_realistic_v4-v1/GEN-SIM` does not exist

`cmsDriver.py Pyquen_GammaJet_pt20_2760GeV_cfi  --conditions auto:phase1_2021_realistic_hi --scenario HeavyIons --pileup_input das:/RelValHydjetQ_B12_5020GeV_2021/CMSSW_10_6_0-106X_upgrade2018_realistic_v4-v1/GEN-SIM -n 2 ...`

https://cmsweb.cern.ch/das/request?view=list&limit=50&instance=prod%2Fglobal&input=dataset+dataset%3D%2FRelValHydjetQ_B12_5020GeV_2021%2FCMSSW_10_6_0-106X_upgrade2018_realistic_v4-v1%2FGEN-SIM

https://github.com/cms-sw/cmssw/blob/master//Configuration/PyReleaseValidation/python/relval_steps.py#L2604

**Comment by silviodonato** [comment]
assign pdmv

**Comment by makortel** [comment]
I though we cache the files used in IB tests separately from the centrally managed storage (for which `runTheMatrix.py` needs `--ibeos` parameter to access). It follows that when a new file is added to the set, it can take couple of IBs before the corresponding workflow starts to succeed (but of course nothing helps if the dataset doesn't exist).

The failure in 13034.0 looks something else than a file I/O problem.

**Comment by silviodonato** [comment]
Thanks Matti, indeed we did not get error in recent IB. I will open a new issue for the problem with wf 310.0, 311.0, 312.0
