### ISSUE TITLE
Missing pileup dataset in wf 310, 311, 312

### ISSUE THREAD

**Issue by silviodonato** [cms-sw/cmssw#29216]
PR https://github.com/cms-sw/cmssw/pull/29032 creates the three new wfs 310, 311, 312 [1] using a not existing pileup dataset `/RelValHydjetQ_B12_5020GeV_2021/CMSSW_10_6_0-106X_upgrade2018_realistic_v4-v1/GEN-SIM` [2] [3].
In the PR discussusion, @mandrenguyen commented 

> 310 and related workflows fail b/c of the lack of an appropriate pileup_dataset. The GEN-SIM output of the new workflow 159 will be used for this. See the discussion with @chayanit in this PR's comments.

Wf 158 is properly running in IB tests, but we are still getting error from wf 310, 311, 312 in IB tests.
@mandrenguyen what was your plan?

[1] https://github.com/cms-sw/cmssw/pull/29032/files#diff-832851e45f413b81f29e72f3394e5c37R23-R25
[2] https://github.com/cms-sw/cmssw/pull/29032/files#diff-819af2ec677272fddf1fef50e788a88bR1561
[3] https://cmsweb.cern.ch/das/request?view=list&limit=50&instance=prod%2Fglobal&input=dataset+dataset%3D%2FRelValHydjetQ_B12_5020GeV_2021%2F*%2FGEN-SIM

**Comment by silviodonato** [comment]
assign pdmv

**Comment by mandrenguyen** [comment]
@silviodonato The GEN-SIM output of wf 159 should be used as the pileup dataset for 310 et al.
I guess we need to wait for a pre-release where 159 is run?

**Comment by silviodonato** [comment]
Ok, so you wanted to use a single pre-release to both create the pileup dateset with a new wf (159) and run a new wf (310) using that pileup dataset. It sounds a bit weird, because 310 will be not validated with the usual IB tests until the prerelease, but I understand that in this way we gain a lot of time (3 weeks).

The pileup dataset is `/RelValHydjetQ_B12_5020GeV_2021/CMSSW_10_6_0-106X_upgrade2018_realistic_v4-v1/GEN-SIM` [1], does this dataset need to be produced with wf 159 in 10_6_0?

[1] https://github.com/cms-sw/cmssw/blob/master/Configuration/PyReleaseValidation/python/relval_steps.py#L643
[2] https://github.com/cms-sw/cmssw/blob/master/Configuration/PyReleaseValidation/python/relval_steps.py#L1561

**Comment by mandrenguyen** [comment]
@silviodonato I guess that's what I wanted to do.  As long as its run with the Run 3 geometry, I don't know of any reason that 159 needs to be run in any particular release.

**Comment by chayanit** [comment]
@silviodonato , @mandrenguyen Sorry but I do not agree to produce /RelValHydjetQ_B12_5020GeV_2021/CMSSW_10_6_0-106X_upgrade2018_realistic_v4-v1/GEN-SIM in 10_6_0. That's why I was asking Matthew to add new baseDataSetRelease to be used to HI 2021 GENSIM. Should we revert the PR #29032 and add this fix? RelValHydjetQ_B12_5020GeV_2021 should be produced in master IMOP.

**Comment by mandrenguyen** [comment]
@chayanit I didn't update the baseDataSetRelease because I didn't know which release to choose.  I still don't know.  wouldn't it make sense to just let 159 run in the next release and then fix this?

**Comment by chayanit** [comment]
@mandrenguyen that would work as well, as long as @silviodonato has no objection and no issue is foreseen for the IB test we can go with this solution. Thanks.

**Comment by silviodonato** [comment]
If I undestood correctly, the pileup dataset will be produced using wf 159 in the next prerelease (`CMSSW_11_1_0_pre5`).
Therefore, the pileup dataset name will be something like `/RelValHydjetQ_B12_5020GeV_2021/CMSSW_11_1_0_pre5-111X_upgrade2018_realistic_vX-vY/GEN-SIM` (we don't know the GT yet).
In addition, you want to use wf 310 to produce RelVals in `CMSSW_11_1_0_pre5` using that pileup dataset.
Is it correct? 

If yes, I propose to comment out wf 310, 311, 312 (https://github.com/cms-sw/cmssw/blob/master/Configuration/PyReleaseValidation/python/relval_pileup.py#L23-L25) 
and uncomment them as soon as you have the name of the future pileup dataset.

**Comment by chayanit** [comment]
Hi @silviodonato not sure if the question is to me but I have not noticed or been informed that HIN group would like to start the validation of Run3 so we didn't plan to produce HIN workflows yet but @mandrenguyen can clarify. 

Concerning the pileup dataset, in order to make the wfs 310, 311 and 312 work. We can produce this sample when pre5 arrives /RelValHydjetQ_B12_5020GeV_2021/CMSSW_11_1_0_pre5-111X_upgrade2018_realistic_vX-vY/GEN-SIM

**Comment by silviodonato** [comment]
> Hi @silviodonato not sure if the question is to me but I have not noticed or been informed that HIN group would like to start the validation of Run3 so we didn't plan to produce HIN workflows yet but @mandrenguyen can clarify.
> 
> Concerning the pileup dataset, in order to make the wfs 310, 311 and 312 work. We can produce this sample when pre5 arrives /RelValHydjetQ_B12_5020GeV_2021/CMSSW_11_1_0_pre5-111X_upgrade2018_realistic_vX-vY/GEN-SIM

Thanks @chayanit. If you don't produce Relvals with wf 310, 311, 312, we can temporary remove those workflows and add them back as soon as the pileup dataset is ready, ie. after CMSSW_11_1_0_pre5.

**Comment by silviodonato** [comment]
I made a PR to disable temporarily these workflows https://github.com/cms-sw/cmssw/pull/29218

**Comment by chayanit** [comment]
OK thanks @silviodonato

**Comment by silviodonato** [comment]
solved with #29218 
@mandrenguyen please open a PR to restore wf 310, 311, 312 and to update the pileup dataset name
 as soon as the pileup dataset is ready, or at least we know the pileup dataset name
