### ISSUE TITLE
Crash in workflow  20634.99

### ISSUE THREAD

**Issue by suchandradutta** [cms-sw/cmssw#29274]
There is a crash during the step3 (digitization after using pre-mixed sample) of the workflow
20610.99. The crash occurs after processing a couple of events with the following exception:

---- Begin Fatal Exception 23-Mar-2020 12:16:28 CET-----------------------
An exception of category 'NullPointerError' occurred while
   [0] Processing  Event run: 1 lumi: 1 event: 2 stream: 0
   [1] Running path 'HLTAnalyzerEndpath'
   [2] Prefetching for module L1TRawToDigi/'hltGtStage2Digis'
   [3] Prefetching for module RawDataCollectorByLabel/'rawDataCollector'
   [4] Prefetching for module CSCDigiToRawModule/'cscpacker'
   [5] Prefetching for module CSCDigiProducer/'simMuonCSCDigis'
   [6] Prefetching for module PreMixingModule/'mixData'
   [7] Calling method for module MixingModule/'mix'
Exception Message:
Event::put: A null unique_ptr was passed to 'put'.
The pointer is of type PHGCSimAccumulator.
The specified productInstanceName was 'HGCDigisHEback'.
----- End Fatal Exception -------------------------------------------------

CMSSW release: CMSSW_11_1_0_pre2
runTheMatrix.py --what upgrade -l 20610.99 -ne

@emiglior, @skinnari, @tsusa, @mmusich, @subirsarkar

**Comment by makortel** [comment]
assign simulation

**Comment by makortel** [comment]
By quick look on the code
https://github.com/cms-sw/cmssw/blob/5e3f992f4fa48c721233224807b7ef95114ecb30/SimCalorimetry/HGCalSimProducers/src/HGCDigitizer.cc#L259-L264
the problem could be caused by 'simHitAccumulator_` being empty. So probably the code should be
```cpp
 auto simResult = std::make_unique<PHGCSimAccumulator>();
 std::unique_ptr<PHGCSimAccumulator> simResult; 
 if (!simHitAccumulator_->empty()) { 
   saveSimHitAccumulator(*simResult, *simHitAccumulator_, validIds_, premixStage1MinCharge_, premixStage1MaxCharge_); 
 } 
 e.put(std::move(simResult), digiCollection()); 
```
instead to always `put()` a valid product.

Any volunteers to try it out?

**Comment by boudoul** [comment]
the PU dataset in the WF 20610.99 seems pretty old ... /RelValMinBias_14TeV/CMSSW_10_6_0_patch2-106X_upgrade2023_realistic_v3_2023D41noPU-v1/GEN-SIM   
...  did the HGCAL geeometry not change since 10_6_0_patch2 (release announced in May 2019 ), maybe pdmv should update the PU dataset in runthematrix ?

**Comment by srimanob** [comment]
@boudoul 
It's D41 geometry, we did not produce many D41 datasets after 10_6_0. From DAS, we have few from 11_0_0_preX,
https://cmsweb.cern.ch/das/request?view=list&limit=50&instance=prod%2Fglobal&input=%2FRelValMinBias_14TeV%2F*D41*%2FGEN-SIM

One may consider to update with
/RelValMinBias_14TeV/CMSSW_11_0_0_pre13-110X_mcRun4_realistic_v2_2026D41noPU-v1/GEN-SIM
which was produced in 2019-12-04

This may need to check first. @chayanit

**Comment by chayanit** [comment]
Hi, does the old PU dataset cause this crash? I don't get.

**Comment by suchandradutta** [comment]
No, I do not think the old RelVal PU sample is responsible for the crash! Using the same sample
we could run the workflow  20634.99 without any problem.

**Comment by mmusich** [comment]
@makortel 
with these changes:
```diff
diff --git a/SimCalorimetry/HGCalSimProducers/src/HGCDigitizer.cc b/SimCalorimetry/HGCalSimProducers/src/HGCDigitizer.cc
index ab6b28958c9..f23613ac984 100644
--- a/SimCalorimetry/HGCalSimProducers/src/HGCDigitizer.cc
+++ b/SimCalorimetry/HGCalSimProducers/src/HGCDigitizer.cc
@@ -256,9 +256,8 @@ void HGCDigitizer::finalizeEvent(edm::Event& e, edm::EventSetup const& es, CLHEP
   averageOccupancies_[idx] = (averageOccupancies_[idx] * (nEvents_ - 1) + thisOcc) / nEvents_;
 
   if (premixStage1_) {
-    std::unique_ptr<PHGCSimAccumulator> simResult;
+    auto simResult = std::make_unique<PHGCSimAccumulator>();
     if (!simHitAccumulator_->empty()) {
-      simResult = std::make_unique<PHGCSimAccumulator>();
       saveSimHitAccumulator(*simResult, *simHitAccumulator_, validIds_, premixStage1MinCharge_, premixStage1MaxCharge_);
     }
     e.put(std::move(simResult), digiCollection());
```
The aforementioned wf runs to completion.

```
20610.99_FourMuExtendedPt1_200+FourMuExtendedPt_1_200_pythia8_2026D41PU_GenSimHLBeamSpotFull+PREMIX_2026D41PU_PremixHLBeamSpotFullPU_Premix+DigiFullTriggerPUPRMXCombined_2026D41PU+RecoFullGlobalPUPRMX_2026D41PU+HARVESTFullGlobalPU_2026D41PU Step0-PASSED Step1-PASSED Step2-PASSED Step3-PASSED Step4-PASSED  - time date Tue Mar 24 13:45:34 2020-date Tue Mar 24 12:20:56 2020; exit: 0 0 0 0 0
1 1 1 1 1 tests passed, 0 0 0 0 0 failed
```

shall I make a PR?

**Comment by makortel** [comment]
> shall I make a PR?

Yes please.

**Comment by makortel** [comment]
@mmusich And thanks for making the test!

**Comment by mmusich** [comment]
https://github.com/cms-sw/cmssw/pull/29286 for the record.

**Comment by kpedro88** [comment]
assign upgrade
