### ISSUE TITLE
[DD4hep] Access to a specific node by its name and its copy number

### ISSUE THREAD

**Issue by ianna** [cms-sw/cmssw#29320]
Add a possibility to select a specific node based on its copy number 

@vargasa - FYI

**Comment by makortel** [comment]
assign geometry

**Comment by ianna** [comment]
@vargasa - can I close this issue? thanks

**Comment by vargasa** [comment]
Sure. Thanks Ianna

**Comment by ianna** [comment]
+1

**Comment by ianna** [comment]
implemented via https://github.com/cms-sw/cmssw/pull/29543 and https://github.com/cms-sw/cmssw/pull/29368
