### ISSUE TITLE
Does NanoAOD step support --dump_python?

### ISSUE THREAD

**Issue by srimanob** [cms-sw/cmssw#29345]
Not sure, it is a known issue. As a question in the title of the issue, does NanoAOD step support `--dump_python`?

I just try with 11_1 (**), and 10_2 (*), and they does not work to me. The config file w/o --dump_python is runable.

(*)
10_2
`cmsDriver.py step1 --filein "file:in.root" --fileout file:out.root --mc --eventcontent NANOEDMAODSIM --datatier NANOAODSIM --conditions 102X_upgrade2018_realistic_v20 --step NANO --nThreads 2 --era Run2_2018,run2_nanoAOD_102Xv1 --python_filename test.py --no_exec --dump_python`

> Traceback (most recent call last):
>   File "/cvmfs/cms.cern.ch/slc7_amd64_gcc700/cms/cmssw/CMSSW_10_2_20_UL/bin/slc7_amd64_gcc700/cmsDriver.py", line 55, in <module>
>     run()
>   File "/cvmfs/cms.cern.ch/slc7_amd64_gcc700/cms/cmssw/CMSSW_10_2_20_UL/bin/slc7_amd64_gcc700/cmsDriver.py", line 36, in run
>     execfile(options.python_filename, result)
>   File "test.py", line 84, in <module>
>     process = nanoAOD_customizeMC(process)
>   File "/cvmfs/cms.cern.ch/slc7_amd64_gcc700/cms/cmssw/CMSSW_10_2_20_UL/python/PhysicsTools/NanoAOD/nano_cff.py", line 323, in nanoAOD_customizeMC
>     process = nanoAOD_customizeCommon(process)
>   File "/cvmfs/cms.cern.ch/slc7_amd64_gcc700/cms/cmssw/CMSSW_10_2_20_UL/python/PhysicsTools/NanoAOD/nano_cff.py", line 312, in nanoAOD_customizeCommon
>     (~run2_miniAOD_80XLegacy).toModify(process, lambda p : nanoAOD_addTauIds(p))
>   File "/cvmfs/cms.cern.ch/slc7_amd64_gcc700/cms/cmssw/CMSSW_10_2_20_UL/python/FWCore/ParameterSet/Config.py", line 1291, in toModify
>     Modifier._toModify(obj,func,**kw)
>   File "/cvmfs/cms.cern.ch/slc7_amd64_gcc700/cms/cmssw/CMSSW_10_2_20_UL/python/FWCore/ParameterSet/Config.py", line 1373, in _toModify
>     func(obj)
>   File "/cvmfs/cms.cern.ch/slc7_amd64_gcc700/cms/cmssw/CMSSW_10_2_20_UL/python/PhysicsTools/NanoAOD/nano_cff.py", line 312, in <lambda>
>     (~run2_miniAOD_80XLegacy).toModify(process, lambda p : nanoAOD_addTauIds(p))
>   File "/cvmfs/cms.cern.ch/slc7_amd64_gcc700/cms/cmssw/CMSSW_10_2_20_UL/python/PhysicsTools/NanoAOD/nano_cff.py", line 147, in nanoAOD_addTauIds
>     tauIdEmbedder.runTauID()
>   File "/cvmfs/cms.cern.ch/slc7_amd64_gcc700/cms/cmssw/CMSSW_10_2_20_UL/python/RecoTauTag/RecoTau/tools/runTauIdMVA.py", line 1124, in runTauID
>     tauIDSources)
>   File "/cvmfs/cms.cern.ch/slc7_amd64_gcc700/cms/cmssw/CMSSW_10_2_20_UL/python/FWCore/ParameterSet/Types.py", line 639, in __init__
>     _Parameterizable.__init__(self,*arg,**args)
>   File "/cvmfs/cms.cern.ch/slc7_amd64_gcc700/cms/cmssw/CMSSW_10_2_20_UL/python/FWCore/ParameterSet/Mixins.py", line 137, in __init__
>     self.__setParameters(block.parameters_())
>   File "/cvmfs/cms.cern.ch/slc7_amd64_gcc700/cms/cmssw/CMSSW_10_2_20_UL/python/FWCore/ParameterSet/Mixins.py", line 210, in __setParameters
>     self.__addParameter(name, value)
>   File "/cvmfs/cms.cern.ch/slc7_amd64_gcc700/cms/cmssw/CMSSW_10_2_20_UL/python/FWCore/ParameterSet/Mixins.py", line 203, in __addParameter
>     raise ValueError(message)
> ValueError: Duplicate insert of member byTightDeepTau2017v2p1VSmu
> The original parameters are:
> ....

11_0
`cmsDriver.py step5 --conditions auto:phase1_2018_realistic -n 10 --era Run2_2018 --eventcontent NANOEDMAODSIM --filein file:step3_inMINIAODSIM.root -s NANO --datatier NANOAODSIM --geometry DB:Extended --python test.py --no_exec --fileout file:step5.root --dump_python`

> Traceback (most recent call last):
>   File "/cvmfs/cms.cern.ch/slc7_amd64_gcc820/cms/cmssw/CMSSW_10_6_10/bin/slc7_amd64_gcc820/cmsDriver.py", line 56, in <module>
>     run()
>   File "/cvmfs/cms.cern.ch/slc7_amd64_gcc820/cms/cmssw/CMSSW_10_6_10/bin/slc7_amd64_gcc820/cmsDriver.py", line 39, in run
>     expanded = process.dumpPython()
>   File "/cvmfs/cms.cern.ch/slc7_amd64_gcc820/cms/cmssw/CMSSW_10_6_10/python/FWCore/ParameterSet/Config.py", line 851, in dumpPython
>     result+=self._dumpPythonList(self._itemsInDependencyOrder(self.sequences), options)
>   File "/cvmfs/cms.cern.ch/slc7_amd64_gcc820/cms/cmssw/CMSSW_10_6_10/python/FWCore/ParameterSet/Config.py", line 809, in _itemsInDependencyOrder
>     "label = " + containedItem.label_())
> RuntimeError: Sequence has a label, but using its label to get an attribute from the process yields a different object or None
> label = egmPhotonIDSequence

**Comment by makortel** [comment]
@srimanob Does `edmConfigDump` on a configuration generated without `--dump_python` work any better?

**Comment by srimanob** [comment]
@makortel 
Ah, thanks. It works better with `edmConfigDump`

**Comment by makortel** [comment]
assign operations

Something on the cmsDriver side then than in the NanoAOD itself (maybe).

**Comment by makortel** [comment]
The difference seems to be that `edmConfigDump` uses `imp.load_source()`
https://github.com/cms-sw/cmssw/blob/aad09fbdaedb52f82e65eaac8820b9818c53baca/FWCore/ParameterSet/scripts/edmConfigDump#L21-L29
while `cmsDriver.py` uses `exec()`
https://github.com/cms-sw/cmssw/blob/aad09fbdaedb52f82e65eaac8820b9818c53baca/Configuration/Applications/scripts/cmsDriver.py#L37-L39

**Comment by srimanob** [comment]
Close and follow up in https://github.com/cms-sw/cmssw/issues/38686
