### ISSUE TITLE
How can I install scram and cmsenv to create CMS area?

### ISSUE THREAD

**Issue by mariayestan** [cms-sw/cmssw#29362]
How can I install scram and cmsenv to my local machine to create CMS area?

**Comment by smuzaffar** [comment]
@mariayestan, easiest way would be to install CVMFS (https://cernvm.cern.ch/portal/filesystem/quickstart)  on your machine and source `/cvmfs/cms.cern.ch/cmsset_default.sh` to get SCRAM and cms environment setup. This will allow you to use all CMSSW release.

The other way is to install full CMSSW releases locally (https://twiki.cern.ch/twiki/bin/view/CMSPublic/SDTCMSSW_aptinstaller#Recipe_for_the_impatient_SH_BASH) on your machine. This might need more than 50GB disk space (for a single cmssw release) available on your machine. I would not recommend this.

If you are not running standard CERN linux (slc6, Centos7) then I would also suggest to install `singularity` (https://sylabs.io/guides/3.5/user-guide/quick_start.html#quick-installation-steps ) and use `/cvmfs/cms.cern.ch/common/cmssw-cc*` scripts (http://cms-sw.github.io/singularity.html) to setup cms environment.

**Comment by mariayestan** [comment]
OK， I'll try it

**Comment by mariayestan** [comment]
> @mariayestan, easiest way would be to install CVMFS (https://cernvm.cern.ch/portal/filesystem/quickstart) on your machine and source `/cvmfs/cms.cern.ch/cmsset_default.sh` to get SCRAM and cms environment setup. This will allow you to use all CMSSW release.
> 
> The other way is to install full CMSSW releases locally (https://twiki.cern.ch/twiki/bin/view/CMSPublic/SDTCMSSW_aptinstaller#Recipe_for_the_impatient_SH_BASH) on your machine. This might need more than 50GB disk space (for a single cmssw release) available on your machine. I would not recommend this.
> 
> If you are not running standard CERN linux (slc6, Centos7) then I would also suggest to install `singularity` (https://sylabs.io/guides/3.5/user-guide/quick_start.html#quick-installation-steps ) and use `/cvmfs/cms.cern.ch/common/cmssw-cc*` scripts (http://cms-sw.github.io/singularity.html) to setup cms environment.

Get it! Thank you for you help!

**Comment by smuzaffar** [comment]
Just for information @mariayestan , did you go for CVMFS based installation or local cmssw installation?

**Comment by mariayestan** [comment]
CVMFS based installation
