### ISSUE TITLE
Inner Tracker cabling map CMSSW integration: Add possibility to specify GBT Id only

### ISSUE THREAD

**Issue by ghugo83** [cms-sw/cmssw#29390]
The latest version of the Inner Tracker cabling map is accessible here: http://cms-tklayout.web.cern.ch/cms-tklayout/layouts-work/recent-layouts/OT616_IT613/cablingInner.html 

In view of CMSSW integration for bandwidth studies, the e-link port number should not be needed.
The relevant mapping info (as provided by tkLayout) is:
Module DetId <-> Number of e-links per module DetId <-> LpGBT Id <-> DTC Id
This info should be enough to access the data rates per sensor, per e-link, and per GBT board.

As discussed with @luigicalligaris and @sorfanel , it would be good to add an option in
https://github.com/cms-sw/cmssw/blob/master/CondTools/SiPhase2Tracker/plugins/DTCCablingMapProducer.cc
So that one can specify the GBT Id only, without having to worry about the e-link port number (port number can be assigned sequentially if that helps).

**Comment by luigicalligaris** [comment]
I will modify the code, and will reference this feature request in the PR

**Comment by makortel** [comment]
assign alca, upgrade

**Comment by luigicalligaris** [comment]
Let me tag @mmusich as well

**Comment by mmusich** [comment]
@ghugo83 @luigicalligaris 
I am not totally sure to understand the implications of:

> The relevant mapping info (as provided by tkLayout) is:
Module DetId <-> Number of e-links per module DetId <-> LpGBT Id <-> DTC Id
This info should be enough to access the data rates per sensor, per e-link, and per GBT board.

does it imply a change in the CondFormat? As a reminder schema evolution is not supported by the DB group.
Thanks for the clarification

**Comment by luigicalligaris** [comment]
It does not imply a change in the CondFormat. It just regards what numbers are written in the fields of the object, which will remain unchanged.

**Comment by mmusich** [comment]
OK good then. I suppose some update the GT is also in order.

**Comment by ghugo83** [comment]
Adding @emiglior

**Comment by emiglior** [comment]
adding @skinnari

**Comment by luigicalligaris** [comment]
Implemented in PR #29443

https://github.com/cms-sw/cmssw/pull/29443

**Comment by christopheralanwest** [comment]
+1

- Implementation in PR #29443 been merged
