### ISSUE TITLE
HGCal Trackster dictionary error

### ISSUE THREAD

**Issue by kpedro88** [cms-sw/cmssw#29444]
After #29081 was merged, there is an error in the phase2 workflows (step3) in the IBs:
```
In file included from DataFormatsHGCalReco_xr dictionary payload:55:
/cvmfs/cms-ib.cern.ch/nweek-02623/slc7_amd64_gcc820/cms/cmssw/CMSSW_11_1_X_2020-04-09-1100/src/DataFormats/HGCalReco/interface/Trackster.h:12:10: fatal error: 'Eigen/Core' file not found
#include <Eigen/Core>
         ^~~~~~~~~~~~
09-Apr-2020 16:37:43 CEST  Closed file file:step2.root
----- Begin Fatal Exception 09-Apr-2020 16:37:43 CEST-----------------------
An exception of category 'FatalRootError' occurred while
   [0] Constructing the EventProcessor
   [1] Constructing module: class=TICLLayerTileProducer label='ticlLayerTileProducer'
   [2] While initializing meta data for branch: ticlTileConstantsTICLLayerTileT104stdarrayTICLGenericTile_ticlLayerTileProducer__RECO.
   Additional Info:
      [a] Fatal Root Error: @SUB=TInterpreter::AutoParse
Error parsing payload code for class TICLLayerTileT<ticl::TileConstants> with content:

#line 1 "DataFormatsHGCalReco_xr dictionary payload"

#ifndef CMS_DICT_IMPL
  #define CMS_DICT_IMPL 1
#endif
#ifndef _REENTRANT
  #define _REENTRANT 1
#endif
#ifndef GNUSOURCE
  #define GNUSOURCE 1
#endif
#ifndef __STRICT_ANSI__
  #define __STRICT_ANSI__ 1
#endif
#ifndef GNU_GCC
  #define GNU_GCC 1
#endif
#ifndef _GNU_SOURCE
  #define _GNU_SOURCE 1
#endif
#ifndef EIGEN_DONT_PARALLELIZE
  #define EIGEN_DONT_PARALLELIZE 1
#endif
#ifndef TBB_USE_GLIBCXX_VERSION
  #define TBB_USE_GLIBCXX_VERSION 80301
#endif
#ifndef BOOST_SPIRIT_THREADSAFE
  #define BOOST_SPIRIT_THREADSAFE 1
#endif
#ifndef PHOENIX_THREADSAFE
  #define PHOENIX_THREADSAFE 1
#endif
#ifndef BOOST_MATH_DISABLE_STD_FPCLASSIFY
  #define BOOST_MATH_DISABLE_STD_FPCLASSIFY 1
#endif
#ifndef BOOST_UUID_RANDOM_PROVIDER_FORCE_POSIX
  #define BOOST_UUID_RANDOM_PROVIDER_FORCE_POSIX 1
#endif
#ifndef CMSSW_GIT_HASH
  #define CMSSW_GIT_HASH "CMSSW_11_1_X_2020-04-09-1100"
#endif
#ifndef PROJECT_NAME
  #define PROJECT_NAME "CMSSW"
#endif
#ifndef PROJECT_VERSION
  #define PROJECT_VERSION "CMSSW_11_1_X_2020-04-09-1100"
#endif
#ifndef CMSSW_REFLEX_DICT
  #define CMSSW_REFLEX_DICT 1
#endif

#define _BACKWARD_BACKWARD_WARNING_H
// Inline headers
#include <vector>
#include <array>
#include "DataFormats/HGCalReco/interface/Trackster.h"
#include "DataFormats/HGCalReco/interface/TICLLayerTile.h"
#include "DataFormats/HGCalReco/interface/TICLSeedingRegion.h"
#include "DataFormats/HGCalReco/interface/TICLCandidate.h"
#include "DataFormats/Common/interface/Wrapper.h"

#undef  _BACKWARD_BACKWARD_WARNING_H


----- End Fatal Exception -------------------------------------------------
```

@rovere @felicepantaleo please take a look ASAP

**Comment by kpedro88** [comment]
assign upgrade,reconstruction

**Comment by makortel** [comment]
assign core

**Comment by makortel** [comment]
As far as I can tell, https://github.com/cms-sw/cmssw/pull/29081 does not add any `Eigen` members to the persisted classes, i.e. `Eigen` is used only on the class interfaces. The error dictionary load attempt looks to me like ROOT (or something in the chain) would not be able to find `Eigen/Core` header.

@pcanal Would you have any insight on what could be going on?

**Comment by smuzaffar** [comment]
This is true that we do not have eigen include directory in ROOT_INCLUDE_PATH env variable which root uses at runtime to find headers.

**Comment by smuzaffar** [comment]
Adding eigne include directory to ROOT_INCLUDE_PATH let me run one of the workflows.
So question is hainf eigen dependency in dataformats is acceptable? 

```
20034.0_TTbar_14TeV+TTbar_14TeV_TuneCP5_2026D35_GenSimHLBeamSpotFull14INPUT+DigiFullTrigger_2026D35+RecoFullGlobal_2026D35+HARVESTFullGlobal_2026D35 Step0-PASSED Step1-PASSED Step2-PASSED Step3-PASSED  - time date Thu Apr  9 21:23:17 2020-date Thu Apr  9 21:12:45 2020; exit: 0 0 0 0
1 1 1 1 tests passed, 0 0 0 0 failed
```

**Comment by smuzaffar** [comment]
For now I have opened https://github.com/cms-sw/cmsdist/pull/5734 which added the eigen include directory in ROOT_INCLUDE_PATH . We should still see if eigen dependency in dataformat is acceptable.

**Comment by slava77** [comment]
> For now I have opened [cms-sw/cmsdist#5734](https://github.com/cms-sw/cmsdist/pull/5734) which added the eigen include directory in ROOT_INCLUDE_PATH . We should still see if eigen dependency in dataformat is acceptable.

From 
https://github.com/cms-sw/cmssw/pull/29110#issuecomment-604434084
> Core is fine with adding Eigen as a dependence for DataFormats, as long as it does not have any side effects (like starting new threads that we encountered with TensorFlow's use of Eigen).

**Comment by smuzaffar** [comment]
thanks @slava77 ,  cms-sw/cmsdist#5734 is now merged and will be available in next IB

**Comment by rovere** [comment]
@makortel for my education: why the error was not triggered neither in my local development area nor during the usual testing phase?

**Comment by smuzaffar** [comment]
@rovere , during local build or test phase, `root` has used the include paths it had saved in the library. Note that root stores -I/externals/include in the library [a] and during local build or test phase these path exists and root can find header but now when you run the test again (with out rebuiulding DataFormats/HGCalReco ) then those paths are not there and root fallback to ROOT_INCLUDE_PATH .

[a]
```
strings lib/slc7_amd64_gcc820/libDataFormatsHGCalReco.so | grep -A2 -B2 eigen
/data/cmsbld/jenkins/workspace/build-any-ib/w/slc7_amd64_gcc820/external/xz/5.2.4-bcolbf/include
/data/cmsbld/jenkins/workspace/build-any-ib/w/slc7_amd64_gcc820/external/zlib/1.2.11/include
/data/cmsbld/jenkins/workspace/build-any-ib/w/slc7_amd64_gcc820/external/eigen/d812f411c3f9-bcolbf/include/eigen3
/data/cmsbld/jenkins/workspace/build-any-ib/w/slc7_amd64_gcc820/external/md5/1.0.0-bcolbf/include
/data/cmsbld/jenkins/workspace/build-any-ib/w/slc7_amd64_gcc820/external/OpenBLAS/0.3.7/include
```

**Comment by rovere** [comment]
Thanks @smuzaffar for the explanation.
I guess there's no easy way for me (or anyone else) in future to catch such kind of problems, right?

**Comment by makortel** [comment]
> Thanks @smuzaffar for the explanation.
> I guess there's no easy way for me (or anyone else) in future to catch such kind of problems, right?

I guess the same. In retrospect the addition of `eigen` to the list of accepted dependencies to DataFormats (https://github.com/cms-sw/cmssw/pull/29110#issuecomment-604434084, https://twiki.cern.ch/twiki/bin/view/CMSPublic/SWGuideCreatingNewProducts#Restrictions_on_the_package_defi) should have ringed a bell. I added a reminder on the twiki page about `ROOT_INCLUDE_PATH` in case new dependencies are permitted.

**Comment by slava77** [comment]
+1

it looks like the problem went away

**Comment by silviodonato** [comment]
@smuzaffar @makortel , can we close this issue?

**Comment by smuzaffar** [comment]
+core

**Comment by smuzaffar** [comment]
issue has been fixed by adding the eigen include to ROOT_INCLUDE_PATH
