### ISSUE TITLE
Strange output when firstLuminosityBlockForEachRun is used for Run-Dependent MC

### ISSUE THREAD

**Issue by srimanob** [cms-sw/cmssw#29472]
Looking on last relvals of Run-Dependent MC,
https://dmytro.web.cern.ch/dmytro/cmsprodmon/workflows.php?prep_id=CMSSW_11_1_0_pre5__RD_Harvesting_6HS-1586551827-ZEE_13UP18_RD

There is a strange in RUN number shows up in output, not sure if I understand how overwriten on run number should work. RelVal was submitted with following setting in DIGI step,
`process.source.firstLuminosityBlockForEachRun = cms.untracked.VLuminosityBlockID(*[cms.LuminosityBlockID(x,y) for x,y in ((315257, 1), (316082, 222), (316720, 445), (317527, 668), (320917, 890), (321414, 1112), (321973, 1334), (322492, 1556), (324245, 1779))])`

What RUN number should be for input (GEN-SIM) with Run-1, LS 378? Should it be 316082? When I look on MiniAOD, [DAS](https://cmsweb.cern.ch/das/request?instance=prod/global&input=lumi+file%3D%2Fstore%2Frelval%2FCMSSW_11_1_0_pre5%2FRelValZEE_13UP18_RD%2FMINIAODSIM%2FPUpmx25ns_110X_upgrade2018_realistic_v9_RD_Harvesting_6HS-v1%2F10000%2F1FB8ECCF-0019-8046-A50A-38A3A4A792F4.root)
Run = 315257 was assigned instead of 316082. 

Do I misunderstand how the code should work? Thanks in advance for the clarification.

Thanks to @schneiml  for a first look on harvesting and spot this issue out from harvesting step.

FYI @jfernan2 @fioriNTU @christopheralanwest @ameyer-cern @tlampen @tocheng @chayanit @pgunnell  @wajidalikhan

**Comment by makortel** [comment]
assign core

**Comment by Dr15Jones** [comment]
Which source type was being used?

**Comment by srimanob** [comment]
Hi @Dr15Jones 
PoolSource,
https://cmsweb.cern.ch/couchdb/reqmgr_config_cache/9878a8ca41e589b33baa4842202f0e80/configFile

**Comment by makortel** [comment]
Not sure if it adds, but here is an example of GEN-SIM-DIGI-RAW-HLTDEBUG file
[/store/relval/CMSSW_11_1_0_pre5/RelValZEE_13UP18_RD/GEN-SIM-DIGI-RAW-HLTDEBUG/PUpmx25ns_110X_upgrade2018_realistic_v9_RD_Harvesting_6HS-v1/10000/F44DA59C-C03C-BA4E-BA09-9F38F8351EC4.root](https://cmsweb.cern.ch/das/request?instance=prod/global&input=lumi+file%3D%2Fstore%2Frelval%2FCMSSW_11_1_0_pre5%2FRelValZEE_13UP18_RD%2FGEN-SIM-DIGI-RAW-HLTDEBUG%2FPUpmx25ns_110X_upgrade2018_realistic_v9_RD_Harvesting_6HS-v1%2F10000%2FF44DA59C-C03C-BA4E-BA09-9F38F8351EC4.root)
where lumi 1145 is assigned to run 316082 instead of 321414 (this is the output of the job that does the actual renumbering of runs, right?).

**Comment by srimanob** [comment]
Yes, that is correct. GEN-SIM-DIGI-RAW-HLTDEBUG is the output from DIGI step where the overwritten happened.

All cmsDriver and workflow can be found at
https://cmsweb.cern.ch/reqmgr2/fetch?rid=srimanob_RVCMSSW_11_1_0_pre5ZEE_13UP18_RD_PUpmx25ns__RD_Harvesting_6HS_200410_225408_9251

**Comment by Dr15Jones** [comment]
Are there log files for the jobs which did the renumbering?

**Comment by srimanob** [comment]
I don't have any link to log from request page, and it seems all jobs success

https://dmytro.web.cern.ch/dmytro/cmsprodmon/workflows.php?prep_id=CMSSW_11_1_0_pre5__RD_Harvesting_6HS-1586551827-ZEE_13UP18_RD

@amaltaro Do you know if I can find log of success relvals jobs

**Comment by Dr15Jones** [comment]
So I did the following

create a file containing Run 1, Lumi 378 
step1_cfg.py
```python
import FWCore.ParameterSet.Config as cms
process = cms.Process("STEP1")
process.source = cms.Source("EmptySource",
                            firstLuminosityBlock = cms.untracked.uint32(378) )
process.out = cms.OutputModule("PoolOutputModule", fileName = cms.untracked.string("step1.root"))
process.o = cms.EndPath(process.out)
process.maxEvents.input = 100
```

Read that file and change the Run number
```python
import FWCore.ParameterSet.Config as cms

process = cms.Process("STEP2")

process.source = cms.Source("PoolSource",
                            fileNames = cms.untracked.vstring("file:step1.root"),
                            firstLuminosityBlockForEachRun = cms.untracked.VLuminosityBlockID(*[cms.LuminosityBlockID(x,y) for x,y in ((315257, 1), (316082, 222), (316720, 445), (317527, 668), (320917, 890), (321414, 1112), (321973, 1334), (322492, 1556), (324245, 1779))]) )
```

This created the output
```
14-Apr-2020 13:26:47 CDT  Initiating request to open file file:step1.root
14-Apr-2020 13:26:48 CDT  Successfully opened file file:step1.root
Begin processing the 1st record. Run 316082, Event 1, LumiSection 378 on stream 0 at 14-Apr-2020 13:26:48.338 CDT
Begin processing the 2nd record. Run 316082, Event 2, LumiSection 378 on stream 0 at 14-Apr-2020 13:26:48.339 CDT
Begin processing the 3rd record. Run 316082, Event 3, LumiSection 378 on stream 0 at 14-Apr-2020 13:26:48.339 CDT
...
Begin processing the 99th record. Run 316082, Event 99, LumiSection 378 on stream 0 at 14-Apr-2020 13:26:48.343 CDT
Begin processing the 100th record. Run 316082, Event 100, LumiSection 378 on stream 0 at 14-Apr-2020 13:26:48.343 CDT
14-Apr-2020 13:26:48 CDT  Closed file file:step1.root
```

Which is exactly what we wanted. Therefore I need more information to attempt to reproduce the problem seen.

**Comment by Dr15Jones** [comment]
So I did the same test but this time generating a file containing just Run 1 Lumi 1145. Then doing the second step I get what we would have expected
```
14-Apr-2020 13:45:36 CDT  Initiating request to open file file:step1.root
14-Apr-2020 13:45:37 CDT  Successfully opened file file:step1.root
Begin processing the 1st record. Run 321414, Event 1, LumiSection 1145 on stream 0 at 14-Apr-2020 13:45:37.132 CDT
Begin processing the 2nd record. Run 321414, Event 2, LumiSection 1145 on stream 0 at 14-Apr-2020 13:45:37.133 CDT
...
Begin processing the 99th record. Run 321414, Event 99, LumiSection 1145 on stream 0 at 14-Apr-2020 13:45:37.137 CDT
Begin processing the 100th record. Run 321414, Event 100, LumiSection 1145 on stream 0 at 14-Apr-2020 13:45:37.137 CDT
14-Apr-2020 13:45:37 CDT  Closed file file:step1.root
```

So there appears to be some step I'm not replicating.

**Comment by Dr15Jones** [comment]
So I was eventually able to cause the same effect. If I created two files one with Lumi 378 and the other with Lumi 1145; merge the two files together; have the 'step2' read the file but use `source.firstLuminosityBlock = cms.untracked.uint32(1145)` then the run number assigned to 1145 is 316082 instead of 321414.

**Comment by amaltaro** [comment]
@srimanob Phat, there is one log available here, for the DIGI step:
https://eoscmsweb.cern.ch/eos/cms/store/logs/prod/recent/PRODUCTION/srimanob_RVCMSSW_11_1_0_pre5ZEE_13UP18_RD_PUpmx25ns__RD_Harvesting_6HS_200410_225408_9251/DIGIPRMXUP18_PU25_RD

**Comment by srimanob** [comment]
Interesting. I am testing the same with `/store/relval/CMSSW_11_1_0_pre5/RelValZEE_13UP18_RD/GEN-SIM/110X_upgrade2018_realistic_v9_RD_Harvesting_6HS-v1/10000/FCD14A86-3935-E84F-9E81-B11A34390C61.root` which we have LS crossing from 217, 226. But I can't reproduce the issue. 

```
Begin processing the 299th record. Run 315257, Event 21699, LumiSection 217 on stream 0 at 14-Apr-2020 21:10:59.185 CEST
Begin processing the 300th record. Run 315257, Event 21700, LumiSection 217 on stream 1 at 14-Apr-2020 21:11:02.510 CEST
Begin processing the 301st record. Run 316082, Event 22503, LumiSection 226 on stream 1 at 14-Apr-2020 21:11:15.885 CEST
Begin processing the 302nd record. Run 316082, Event 22501, LumiSection 226 on stream 2 at 14-Apr-2020 21:11:15.885 CEST
```

**Comment by Dr15Jones** [comment]
Should be fixed with #29473

**Comment by srimanob** [comment]
Thanks very much, @Dr15Jones 
However, I think I miss one piece of the picture. How does `source.firstLuminosityBlock` appear? It was not a part of cmsDriver. Is it somehow added during the production?

**Comment by Dr15Jones** [comment]
@SridharaDasu 
> However, I think I miss one piece of the picture. How does source.firstLuminosityBlock appear? It was not a part of cmsDriver. Is it somehow added during the production?

Looking at the file used in the original job, the LuminosityBlocks in the file were not consecutive. I assumed that was because the GEN jobs had their outputs merged. Then during the next step the workflow system normally tells that job which LuminosityBlocks within the input files should be processed (we do not always process an entire file in a workflow). So I assumed the job which created the file had skipped forward.

**Comment by silviodonato** [comment]
@srimanob  can we close this issue?

**Comment by srimanob** [comment]
@silviodonato 
I plan to inject relvals with _pre6 first, then confirm if issue solved. I will come back to this issue when I get a result.

**Comment by srimanob** [comment]
@Dr15Jones @makortel @silviodonato 

It seems we have a large failure of RunDependent RelVals, [10k event](https://cms-unified.web.cern.ch/cms-unified/report/srimanob_RVCMSSW_11_1_0_pre6ZEE_13UP18_RD_PUpmx25ns__RD_Harvesting_8_200416_161631_4812), [High statistics](https://cms-unified.web.cern.ch/cms-unified/report/srimanob_RVCMSSW_11_1_0_pre6ZEE_13UP18_RD_PUpmx25ns__RD_Harvesting_8HS_200416_161423_9045)

One log can be found [here](https://cms-unified.web.cern.ch/cms-unified//joblogs/srimanob_RVCMSSW_11_1_0_pre6ZEE_13UP18_RD_PUpmx25ns__RD_Harvesting_8_200416_161631_4812/134/DIGIPRMXUP18_PU25_RD/27dedadf-7014-4d74-b76d-740aaeb26340-105-2-logArchive/job/WMTaskSpace/cmsRun1/)

The issue seems to come from non-matching between currentRun() and run in 
https://github.com/cms-sw/cmssw/blob/master/DataFormats/Provenance/src/IndexIntoFile.cc#L100

I can reproduce the crash locally using

`root://cmsxrootd-site.fnal.gov//store/relval/CMSSW_11_1_0_pre6/RelValZEE_13UP18_RD/GEN-SIM/110X_upgrade2018_realistic_v9_RD_Harvesting_8-v1/10000/83F02CCA-B396-8243-A2A6-4FD652A53CFC.root `

with `/afs/cern.ch/user/s/srimanob/public/ForRunDependent/DIGIPRMXUP18_PU25_RD.py`

Log:

> Begin processing the 546th record. Run 321414, Event 6546, LumiSection 1310 on stream 2 at 18-Apr-2020 13:05:15.980 CEST
> Begin processing the 547th record. Run 321414, Event 6549, LumiSection 1310 on stream 3 at 18-Apr-2020 13:05:15.980 CEST
> Begin processing the 548th record. Run 321414, Event 6548, LumiSection 1310 on stream 0 at 18-Apr-2020 13:05:15.980 CEST
> Begin processing the 549th record. Run 321414, Event 6550, LumiSection 1310 on stream 1 at 18-Apr-2020 13:05:15.981 CEST
> currentRun(): 321414
> run: 321414
> Begin processing the 550th record. Run 321414, Event 6547, LumiSection 1310 on stream 0 at 18-Apr-2020 13:05:23.302 CEST
> currentRun(): 321414
> run: 321414
> currentRun(): 321414
> run: 321414
> currentRun(): 321414
> run: 321414
> currentRun(): 321414
> run: 321414
> currentRun(): 321414
> run: 321414
> Begin processing the 551st record. Run 321973, Event 6704, LumiSection 1341 on stream 0 at 18-Apr-2020 13:05:33.554 CEST
> Begin processing the 552nd record. Run 321973, Event 6701, LumiSection 1341 on stream 2 at 18-Apr-2020 13:05:33.554 CEST
> Begin processing the 553rd record. Run 321973, Event 6703, LumiSection 1341 on stream 1 at 18-Apr-2020 13:05:33.554 CEST
> Begin processing the 554th record. Run 321973, Event 6702, LumiSection 1341 on stream 3 at 18-Apr-2020 13:05:33.554 CEST
> currentRun(): 321414
> run: 321973
> cmsRun: /afs/cern.ch/work/s/srimanob/test/relvals/RunDependent/CMSSW_11_1_0_pre6/src/DataFormats/Provenance/src/IndexIntoFile.cc:103: void edm::IndexIntoFile::addEntry(const ProcessHistoryID&, edm::RunNumber_t, edm::LuminosityBlockNumber_t, edm::EventNumber_t, edm::IndexIntoFile::EntryNumber_t): Assertion `(currentRun() == run && currentIndex() == index) || currentRun() == invalidRun' failed.

**Comment by srimanob** [comment]
FYI @chayanit 
It should not affect normal MC relvals as RUN always be 1 for MC.

**Comment by Dr15Jones** [comment]
@srimanob thanks for the example configuration. I was able to pair it down to just the Source and PoolOutputModule and still get the failure. The problem appears to be that when going from 1 LuminosityBlock to the next, the framework failed to generate the endRun/beginRun transitions but went ahead and changed the Run # on the next LuminosityBlock.

**Comment by Dr15Jones** [comment]
I extended the framework unit test to also check Run and LuminosityBlock transitions are being done correctly and it now sees this problem (and the update test now reports failure).

**Comment by Dr15Jones** [comment]
This should be the fix #29525.

**Comment by srimanob** [comment]
Thanks, @Dr15Jones 
I would like to confirm that I try to run locally with CMSSW_11_1_X_2020-04-22-2300, and the Run transition is done properly.

**Comment by Dr15Jones** [comment]
@srimanob thanks for running the test!

**Comment by srimanob** [comment]
New relvals with 11_1_0_pre7 is done. ECAL checks and confirm that RUNs are assigned properly:
![alknkdhnffhlhbnh](https://user-images.githubusercontent.com/4701449/81568607-4a5dd280-939e-11ea-949c-6caa1e833122.png)

Thanks @amassiro 
FYI @Dr15Jones @silviodonato

**Comment by Dr15Jones** [comment]
@srimanob Thanks!
