### ISSUE TITLE
Segfault in Phase2EndcapRing::computeCrossings when running cmsRunVDT with RECO config

### ISSUE THREAD

**Issue by gartung** [cms-sw/cmssw#29551]
To reproduce:
runTheMatrix.py -l 20634.21 -w upgrade --dryRun
Update config files 
TTbar_14TeV_TuneCP5_cfi_GEN_SIM.py and step2_DIGI_L1_L1TrackTrigger_DIGI2RAW_HLT_PU.py 
to generate 100 events and use 8 threads. Run these configs
cmsRunVDT TTbar_14TeV_TuneCP5_cfi_GEN_SIM.py 
cmsRunVDT step2_DIGI_L1_L1TrackTrigger_DIGI2RAW_HLT_PU.py 

Update config file step3_RAW2DIGI_L1Reco_RECO_RECOSIM_PU.py 
to generate 100 events and use 8 threads. Run this configs
cmsRunVDT step3_RAW2DIGI_L1Reco_RECO_RECOSIM_PU.py

This results in s segfault at 
#5  0x00007fe842870026 in Phase2EndcapRing::computeCrossings (this=this@entry=0x7fe82cefad40, startingState=..., propDir=<optimized out>) at /cvmfs/cms-ib.cern.ch/week1/slc7_amd64_gcc900/cms/cmssw/CMSSW_11_1_X_2020-04-19-2300/src/DataFormats/Math/interface/deltaPhi.h:32

Instead of calling the functions in the arguments of the deltaPhi functions I made local variables to get their return values as shown in the diff here
https://github.com/cms-sw/cmssw/compare/master...gartung:gartung-Phase2EndcapRing-computeCrossings-segfault

Making this change and running valgrind on the config step3_RAW2DIGI_L1Reco_RECO_RECOSIM_PU.py modified to skip to the 90 event which produces the segfault and running only one thread I get this log 
https://gartung.web.cern.ch/gartung/valgrind.log
which shows a read of an invalid pointer at
https://cmssdt.cern.ch/dxr/CMSSW/source/Geometry/CommonDetUnit/interface/GeomDet.h#37

Further investigation is needed to determine if the frontDets vector is filled correctly before it is accesed.

**Comment by kpedro88** [comment]
assign reconstruction,upgrade
attn: @JanFSchulte @mtosi

**Comment by makortel** [comment]
Is the pointer invalid also with regular `cmsRun`? (if yes, it would hint towards something going wrong with `cmsRunVDT` earlier when the geometry is built)

**Comment by gartung** [comment]
It runs without segfaulting under cmsRun. Perhaps this is a timing issue that running under cmsRunVDT reveals.

**Comment by gartung** [comment]
Running valgrind with cmsRun and the same config now.

**Comment by gartung** [comment]
The only difference between cmsRun and cmsRunVDT is that the VDT library is linked in the second. I searched through the code and vdt:: namespace functions are called in various places. What happens to these when the VDT library function is not available?

**Comment by kpedro88** [comment]
The vdt headers and library can be included on a per-package basis, as they are distributed in ROOT.

**Comment by slava77** [comment]
> To reproduce:
> runTheMatrix.py -l 20634.21 -w upgrade --dryRun
> Update config files
> TTbar_14TeV_TuneCP5_cfi_GEN_SIM.py and step2_DIGI_L1_L1TrackTrigger_DIGI2RAW_HLT_PU.py
> to generate 100 events and use 8 threads. Run these configs
> cmsRunVDT TTbar_14TeV_TuneCP5_cfi_GEN_SIM.py
> cmsRunVDT step2_DIGI_L1_L1TrackTrigger_DIGI2RAW_HLT_PU.py
> 
> Update config file step3_RAW2DIGI_L1Reco_RECO_RECOSIM_PU.py
> to generate 100 events and use 8 threads. Run this configs
> cmsRunVDT step3_RAW2DIGI_L1Reco_RECO_RECOSIM_PU.py

Does it crash in one thread or does it have to be 8?
please copy the input file to some place readable.
Thank you.

**Comment by gartung** [comment]
The segfault happens whether 8 threads or one thread is used. The segfaults happened with multiple runs of step1 and step2 which generated a new steo2.root each time.

**Comment by gartung** [comment]
The files currently being used  can be found on cmsdev34 in /build/gartung/CMSSW_11_1_0_pre6/TimeMemory

**Comment by gartung** [comment]
I am also copying them to 
/eos/home-g/gartung/TimeMemory

**Comment by gartung** [comment]
There is no segfault running cmsRun with the same config and input.

**Comment by gartung** [comment]
LogDebug output enabled log showing construction of objects
https://gartung.web.cern.ch/gartung/step3-log-debug.log
