### ISSUE TITLE
Phase2 Tracker Premixed DIGIs are broken 

### ISSUE THREAD

**Issue by mmusich** [cms-sw/cmssw#29563]
Two problems have been detected in the Premixing vs Standard Mixing validation for the Phase-2 Trackers:

## Issue with Inner Tracker digis
Full details in this presentation from @suchandradutta:

https://indico.cern.ch/event/879033/contributions/3840120/.

In short:
- premixing stage1 uses a single electron to ADC (=135) conversion factor for both IT (inner tracker) / OT  (outer tracker)
https://github.com/cms-sw/cmssw/blob/9abb3c7dc5a6754abec4dd055d3b52a490b33bfd/SimTracker/SiPhase2Digitizer/python/phase2TrackerDigitizer_cfi.py#L230-L240
- premixing stage2 (first step) uses again the same value for both IT and OT https://github.com/cms-sw/cmssw/blob/9abb3c7dc5a6754abec4dd055d3b52a490b33bfd/SimGeneral/PreMixingModule/python/mixOne_premix_on_sim_cfi.py#L227
- the final digitization step in stage2 uses instead 600 for IT: https://github.com/cms-sw/cmssw/blob/9abb3c7dc5a6754abec4dd055d3b52a490b33bfd/SimTracker/SiPhase2Digitizer/python/phase2TrackerDigitizer_cfi.py#L23 while 135 is used for OT: https://github.com/cms-sw/cmssw/blob/9abb3c7dc5a6754abec4dd055d3b52a490b33bfd/SimTracker/SiPhase2Digitizer/python/phase2TrackerDigitizer_cfi.py#L105

As a result of the double (lossy) conversion performed with different conversion factors in the Inner Tracker there is a noticeable change in the final ADC distributions (red is Premixing, green is Std Mixing)

![image](https://user-images.githubusercontent.com/5082376/80251294-b12c7d80-8675-11ea-8fbb-e5dc12943004.png)

Few concrete examples for some `SimHits` are as follows:

| Charge [e-] | Charge (ADC) (standard mix) e/ADC = 600 | Charge [ADC] (premix step1) e/ADC = 135 | Charge [e-] (premix step2) e/ADC = 135 | Charge [ADC] (premix final) e/ADC = 600 |
| ------------- | ------------- | ------------- | ------------- | ------------- |
| 3639.4 | 6 (6.07) | 26 | 3510.0 | 5 (5.85) | 
| 8435.7 | 14 (14.06) | 62| 8370.0 | 13 (13.95)|
| 9000.6 |15 (15.0) | 66 | 8910.0 | 14 (14.85)| 
| 4234.6 | 7 (7.06) | 31 | 4185.0 | 6 (6.97) |
|13896.1 |23 (23.16) | 102 | 10037.7 | 22 (22.95) |

This in principle can be recovered by allowing the collections of `PixelDigi`s produced by the premixing stage1 and the signal digitization in step2 with two different conversion factor for IT and OT and then let the `PreMixingPhase2TrackerWorker` to undo the conversion separately for IT and OT.

## Issue with Outer Tracker digis
In addition it was noticed that the fraction of OverThreshold digis in the premixed case for the PS modules is always 1, while it has a non-trivial distribution for the standard mixing case, see plot below:

![image](https://user-images.githubusercontent.com/5082376/80353382-94f72f00-8875-11ea-96fa-9a26e2fd2265.png)
 
As a possible solution we need to  configure the digitizer to have analog readout for OT (at least for the PSS layers) at step 1 of pre-mixing, as the actual charge information is essential.

cc:
@suchandradutta @emiglior @skinnari @tsusa

**Comment by Dr15Jones** [comment]
assign simulation

**Comment by civanch** [comment]
assign upgrade

**Comment by kpedro88** [comment]
@mdhildreth @makortel if you have time, can you take a look? hopefully the first issue is easy to fix, the second one might take some more work

**Comment by mmusich** [comment]
a possible solution is at https://github.com/cms-sw/cmssw/pull/29565

**Comment by kpedro88** [comment]
@mmusich excellent, thanks!
