### ISSUE TITLE
Exception: Original collection and shifted collection are of different size in ShiftedParticleMETcorrInputProducer

### ISSUE THREAD

**Issue by silviodonato** [cms-sw/cmssw#29744]
Several workflows (25211.18, 25403.0, 250205.0, 250208.18) are failing with the error
```
----- Begin Fatal Exception 06-May-2020 05:07:53 CEST-----------------------
An exception of category 'InvalidInput' occurred while
   [0] Processing  Event run: 1 lumi: 1 event: 8 stream: 3
   [1] Prefetching for module METTester/'pfPuppiMetAnalyzerMiniAOD'
   [2] Prefetching for module PATMETSlimmer/'slimmedMETsPuppi'
   [3] Prefetching for module CorrectedPATMETProducer/'patPFMetT1SmearJetResUpPuppi'
   [4] Calling method for module ShiftedParticleMETcorrInputProducer/'shiftedPatMETCorrSmearedJetResUpPuppi'
Exception Message:
Original collection and shifted collection are of different size in ShiftedParticleMETcorrInputProducer
----- End Fatal Exception -------------------------------------------------
```
Most likely, the error is related to https://github.com/cms-sw/cmssw/pull/29254 .

https://cmssdt.cern.ch/SDT/cgi-bin/logreader/slc7_amd64_gcc820/CMSSW_11_1_X_2020-05-05-2300/pyRelValMatrixLogs/run/25211.18_GluGluHToZZTo4L_M125_Pow_py8_Evt_13UP18+GluGluHToZZTo4L_M125_Pow_py8_Evt_13UP18+DIGIUP18_PU25+RECOUP18_PU25+HARVESTUP18_PU25/step3_GluGluHToZZTo4L_M125_Pow_py8_Evt_13UP18+GluGluHToZZTo4L_M125_Pow_py8_Evt_13UP18+DIGIUP18_PU25+RECOUP18_PU25+HARVESTUP18_PU25.log#/721-721

**Comment by silviodonato** [comment]
assign reconstruction

**Comment by silviodonato** [comment]
@ahinzmann

**Comment by silviodonato** [comment]
Please note that in  `slc7_amd64_gcc900` fewer and different workflow are failing (`25212.18`). This sounds weird. We see the same effect also in  #29743.

**Comment by ahinzmann** [comment]
Hi, sorry, I'm out of (home-)office this week, will look into it next week.

**Comment by silviodonato** [comment]
I'm afraid we have to revert  #29743 from 11_1_0_pre7.
We are getting too many errors in random workflows
https://cmssdt.cern.ch/SDT/html/cmssdt-ib/#/ib/CMSSW_11_1_X

**Comment by silviodonato** [comment]
I opened the revert PR in #29748

**Comment by slava77** [comment]
I tried 25403.0, 250205.0, 250208.18 in CMSSW_11_1_X_2020-04-29-2300 where I was testing #29254 and was not able to reproduce the problem.

**Comment by slava77** [comment]
@mrodozov @smuzaffar 
is there a link/place where I can copy the outputs of the failing tests (25211.18, 25403.0, 250205.0, 250208.18 for slc7_amd64_gcc820 CMSSW_11_1_X_2020-05-05-2300)?
Please let me know.
Thank you.

**Comment by slava77** [comment]
@silviodonato 
did this show up in any of the PR tests?
For PRs I know how to get the matrix outputs, which should at least allow to avoid the SIM/DIGI randomness in an effort to reproduce the problem.

**Comment by slava77** [comment]
> I tried 25403.0, 250205.0, 250208.18 in CMSSW_11_1_X_2020-04-29-2300 where I was testing #29254 and was not able to reproduce the problem.

no luck with any of the 4 wfs in CMSSW_11_1_X_2020-05-05-2300 on cmsdev34 : all pass OK.

**Comment by silviodonato** [comment]
We see the error also in `CMSSW_11_1_X_2020-05-06-1300`
https://cmssdt.cern.ch/SDT/cgi-bin/logreader/slc7_amd64_gcc820/CMSSW_11_1_X_2020-05-06-1300/pyRelValMatrixLogs/run/500206.0_ZMM_13+ZMM_13INPUT+DIGIPRMXUP15_PU50+RECOPRMXUP15_PU50+HARVESTUP15_PU50/step3_ZMM_13+ZMM_13INPUT+DIGIPRMXUP15_PU50+RECOPRMXUP15_PU50+HARVESTUP15_PU50.log#/

@slava77 I don't know where we can get the files of the IB tests.
Yes, the error is not reproducible, very weird.
We are getting another not reproducible error with https://github.com/cms-sw/cmssw/issues/29743 , they do not seem to be related, but it is two time weird that we got these errors at the same time.

**Comment by silviodonato** [comment]
The directory is `/data/cmsbld/jenkins/workspace/ib-run-relvals/CMSSW_11_1_X_2020-05-06-1300/pyRelval/` , for instance in `cmsbuild15` I found many relvals, but not all of them :-(

**Comment by silviodonato** [comment]
It looks like the outputs are deleted as soon as the `ib-run-relvals` ends the job https://cmssdt.cern.ch/jenkins/job/ib-run-relvals/154571/consoleText

**Comment by slava77** [comment]
+1

resoved in #29769
