### ISSUE TITLE
[Suggestion] Add energy values and conversions to DataFormats/Math/interface/CMSUnits.h

### ISSUE THREAD

**Issue by cvuosalo** [cms-sw/cmssw#29750]
`GeantUnits.h` contains energy values like `_GeV`. The same user-defined literals could be added to `CMSUnits.h` for the CMS convention.
Energy conversion functions would also be helpful, like `convertGeVToKeV()`.

An example file that could benefit from such additions is `SimCalorimetry/HGCalSimProducers/src/HGCDigitizer.cc`.

**Comment by cvuosalo** [comment]
assign reco, geometry

**Comment by cvuosalo** [comment]
assign reconstruction

**Comment by civanch** [comment]
@cvuosalo , likely this was done long ago?

**Comment by cvuosalo** [comment]
@civanch No, this issue is just a nice idea but not very important. I create issues like this just to document ideas, not necessarily to get them done promptly. Is it inappropriate to create GitHub issues merely for suggestions that may never need to be implemented?

**Comment by makortel** [comment]
> Is it inappropriate to create GitHub issues merely for suggestions that may never need to be implemented?

In general no, e.g. in `core` we have plenty of such GitHub issues.

**Comment by civanch** [comment]
@cvuosalo , we do not have alternative easy mechanism to collect issues. It may stay for long but from time to time it would be useful to review and close those which will never be implemented.

**Comment by cvuosalo** [comment]
Resolved by PR #37037.

**Comment by cvuosalo** [comment]
+1

**Comment by cvuosalo** [comment]
@cms-sw/reconstruction-l2 This issue is now resolved by #37037. Could you please approve it so I can close it?

**Comment by jpata** [comment]
+reconstruction

**Comment by perrotta** [comment]
> Resolved by PR #37037 

as commented by the proponent of this github issue (@cvuosalo), who also signed this issue for "geometry": it think it can be closed, then
