### ISSUE TITLE
DQMServices/Demo unit test failure

### ISSUE THREAD

**Issue by silviodonato** [cms-sw/cmssw#29794]
We are getting a unit test failure from `DQMServices/Demo`
```
MessageLogger Summary

Severity    # Occurrences   Total Occurrences
--------    -------------   -----------------

dropped waiting message count 0
+ PID=19387
+ sleep 5
+ cmsRun /data/cmsbld/jenkins/workspace/ib-run-qa/CMSSW_11_1_ROOT6_X_2020-05-08-2300/src/DQMServices/Demo/test/run_analyzers_cfg.py outfile=noevents.root processingMode=RunsAndLumis
+ kill -INT 19387
+ wait
++ wc -l
++ dqmiolistmes.py noevents.root -r 1
Traceback (most recent call last):
  File "/cvmfs/cms-ib.cern.ch/nweek-02627/slc7_amd64_gcc820/cms/cmssw-patch/CMSSW_11_1_ROOT6_X_2020-05-08-2300/bin/slc7_amd64_gcc820/dqmiolistmes.py", line 20, in &lt;module&gt;
    f = uproot.open(args.filename)
  File "/cvmfs/cms-ib.cern.ch/nweek-02627/slc7_amd64_gcc820/external/py2-uproot/3.11.3-hpgckg/lib/python2.7/site-packages/uproot/rootio.py", line 54, in open
    return ROOTDirectory.read(openfcn(path), **options)
  File "/cvmfs/cms-ib.cern.ch/nweek-02627/slc7_amd64_gcc820/external/py2-uproot/3.11.3-hpgckg/lib/python2.7/site-packages/uproot/rootio.py", line 51, in &lt;lambda&gt;
    openfcn = lambda path: MemmapSource(path, **kwargs)
  File "/cvmfs/cms-ib.cern.ch/nweek-02627/slc7_amd64_gcc820/external/py2-uproot/3.11.3-hpgckg/lib/python2.7/site-packages/uproot/source/memmap.py", line 21, in __init__
    self._source = numpy.memmap(self.path, dtype=numpy.uint8, mode="r")
  File "/cvmfs/cms-ib.cern.ch/nweek-02627/slc7_amd64_gcc820/external/py2-numpy/1.16.6-hpgckg/lib/python2.7/site-packages/numpy/core/memmap.py", line 225, in __new__
    f_ctx = open(os_fspath(filename), ('r' if mode == 'c' else mode)+'b')
IOError: [Errno 2] No such file or directory: 'noevents.root'
+ '[' 66 = 0 ']'
status = 256

---&gt; test TestDQMServicesDemo had ERRORS
 
^^^^ End Test TestDQMServicesDemo ^^^^
&gt;&gt; Tests for package DQMServices/Demo ran.
```

https://cmssdt.cern.ch/SDT/cgi-bin/logreader/slc7_amd64_gcc820/CMSSW_11_1_ROOT6_X_2020-05-08-2300/unitTestLogs/DQMServices/Demo#/

The error appeared in:
- CMSSW_11_1_X_2020-05-08-2300: ROOT6_X, Patatrack
- CMSSW_11_1_X_2020-05-10-0000: ROOT6_X, ROOT620_X
- CMSSW_11_1_X_2020-05-10-2300: DEFAULT(slc7_amd64_gcc820), ROOT6_X

**Comment by silviodonato** [comment]
assign dqm

**Comment by schneiml** [comment]
Ok, that is not very surprising, probably it just means starting up cmssw was slower than I expected.

Workaround would be to give the sleep a bit more time, or just try again, it should usually work.

@makortel @Dr15Jones can we get the `EmptySource` to properly support the `RunsAndLumis` mode? Then we could get rid of  this ugly contraption [1] in that test.

[1] https://github.com/cms-sw/cmssw/blob/master/DQMServices/Demo/test/runtests.sh#L158-L163

**Comment by makortel** [comment]
> can we get the `EmptySource` to properly support the `RunsAndLumis` mode? 

@Dr15Jones Could you take a look at this?

**Comment by Dr15Jones** [comment]
> > can we get the EmptySource to properly support the RunsAndLumis mode?
> @Dr15Jones Could you take a look at this?

It isn't a problem with EmptySource. The issue is the framework only has a `maxEvents` ability, not a `maxLuminosityBlocks` nor `maxRuns` ability.

**Comment by Dr15Jones** [comment]
The issue could be handled in a different way. An inintial job could be run to generate a ROOT file containing empty events. Then the test would use the PoolSource in 'RunAndLumi' mode to read that file.

**Comment by Dr15Jones** [comment]
Actually, I'm wrong. The framework does support `maxLuminosityBlocks`.

**Comment by Dr15Jones** [comment]
There seems to be an off-by-one counting error. When I do
```python
import FWCore.ParameterSet.Config as cms

process = cms.Process("Test")
process.source = cms.Source("EmptySource", numberEventsInLuminosityBlock = cms.untracked.uint32(2), processingMode=cms.untracked.string('RunsAndLumis'))

process.maxLuminosityBlocks.input = 3

process.add_(cms.Service("Tracer"))
```

It only processes 2 Lumis before ending the job. Although such a behavior is wrong, it would not prevent this unit test from working.

**Comment by schneiml** [comment]
Oh, I didn't actually test if that exists. Makes things much easier. PR coming soon.
