### ISSUE TITLE
Is HardEventHypothesis class still useful?

### ISSUE THREAD

**Issue by makortel** [cms-sw/cmssw#29834]
While trying to address #29306 and #26618 I came across [`mkevhyp`](https://github.com/cms-sw/cmssw/blob/master/FWCore/Skeletons/scripts/mkevhyp) and 
https://github.com/cms-sw/cmssw/blob/e1b8483500a3c449e1763d8e77ce70343fe14844/DataFormats/PatCandidates/interface/HardEventHypothesis.h#L110
class.

`git grep HardEventHypothesis` does not show any use in CMSSW beyond the class definition and the Skeletons template. The `HardEventHypothesis.h` looks like it has not gone through `clang-format`. Git history shows total of 4 commits, last one from 2013 for removing CVS keywords, and the other 3 from 2008.

Before putting effort into modernizing the template I would like to understand if this class is still useful. If not, I would really like to remove it, or at least the Skeletons template.

**Comment by makortel** [comment]
assign reconstruction, analysis

**Comment by perrotta** [comment]
At a first glance it could even safely get removed
Let however add @rappoccio in the discussion , who was the original author of it

**Comment by makortel** [comment]
Thanks @perrotta, I will then remove the `mkevhyp` and related skeleton, and leave the removal of `DataFormats/PatCandidates/interface/HardEventHypothesis.h` to a separate PR.

**Comment by santocch** [comment]
+1 
OK to proceed as @makortel propose

**Comment by makortel** [comment]
> I will then remove the `mkevhyp` and related skeleton,

Done as part of #29840.

**Comment by rappoccio** [comment]
Wow, this is 12+ years old, I entirely forgot about it. It has no purpose anymore and can be removed.

**Comment by perrotta** [comment]
Created PR #29903 to remove the HardEventHypothesis class from CMSSW

**Comment by perrotta** [comment]
+1
- Done with #29840. and #29903, both merged

**Comment by makortel** [comment]
Thanks!
