### ISSUE TITLE
build cms.InputTag from tuple

### ISSUE THREAD

**Issue by fwyzard** [cms-sw/cmssw#29846]
As far as I know, an `InputTag` can be built as
```python
parameter = cms.InputTag("label", "instance", "process")
```
or as
```python
parameter = cms.InputTag("label:instance:process")
```
(plus syntaxes where only some of the fields are available).

Once the parameter type  is known, it can be customised with
```python
parameter = "label:instance:process"
```
but there is no equivalent syntax with separate fields that does not specify the full `cms.type`.

I would propose to add the possibility of building an `InputTag` from a `tuple`, i.e.
```python
parameter = ("label", "instance", "process")
```

**Comment by fwyzard** [comment]
assign core

**Comment by Dr15Jones** [comment]
I like the idea as I've always been a proponent of separating the different fields explicitly.

**Comment by makortel** [comment]
Done in https://github.com/cms-sw/cmssw/pull/29992
