### ISSUE TITLE
Use 2021/v1/materials.xml for new scenarios for upgrade and Run 3

### ISSUE THREAD

**Issue by cvuosalo** [cms-sw/cmssw#29851]
The obsolete `Geometry/CMSCommonData/data/materials.xml` is being replaced by `Geometry/CMSCommonData/data/materials/2021/v1/materials.xml`. New upgrade scenarios should use this new version of the file. It is also used for Run 3.

This change is not urgent but would be nice to be used for all new upgrade scenarios going forward. The materials revisions are merely making the densities and atomic weights of the elements match those in Geant4.

**Comment by cvuosalo** [comment]
assign upgrade

**Comment by kpedro88** [comment]
+upgrade
new common geometry sections for Phase 2 (O5-onward) are using the new file

**Comment by cvuosalo** [comment]
close
