### ISSUE TITLE
Can not produce std::unordered_map - illegal underscore

### ISSUE THREAD

**Issue by lecriste** [cms-sw/cmssw#29967]
Trying to replace an `std::map` with an `std::unordered_map` [here](https://github.com/lecriste/cmssw/commit/2d7e96c18eada02ffb7c1f3754fb20e00255c749#diff-de159032ed18703ecac25de24a34f686), `cmsRun` throws the exception below.

The branch can be tested in `CMSSW_11_1_0_pre7`.

```
An exception of category 'IllegalCharacter' occurred while
   [0] Constructing the EventProcessor
   [1] Constructing module: class=HGCalRecHitMapProducer label='hgcRecHitMapProducer'
Exception Message:
Class name 'DetIdconstHGCRecHitptrDetIdstdhashDetIdstdequal_tostdunordered_map' contains an underscore ('_'), which is illegal in the name of a product.
```

**Comment by kpedro88** [comment]
assign core

**Comment by makortel** [comment]
The friendly class name itself should be straightforward to fix, but @lecriste could you clarify if the `unordered_map` is intended to be persisted or only a transient product?

**Comment by lecriste** [comment]
@makortel the `unordered_map` is intended to be transient:
https://github.com/lecriste/cmssw/commit/2d7e96c18eada02ffb7c1f3754fb20e00255c749#diff-9dbb72aa199e1435b02ab2c8ecc9d6fc

**Comment by makortel** [comment]
Fixed in #29987

**Comment by lecriste** [comment]
@makortel the exception is still there with https://github.com/lecriste/cmssw/tree/HGCalRecHitMapProducer-use-merge in CMSSW_11_2_X_2020-05-26-2300:

```
An exception of category 'IllegalCharacter' occurred while
   [0] Constructing the EventProcessor
   [1] Constructing module: class=HGCalRecHitMapProducer label='hgcRecHitMapProducer'
Exception Message:
Class name 'DetIdconstHGCRecHitptrDetIdstdhashDetIdstdequal_tostdumap' contains an underscore ('_'), which is illegal in the name of a product.
```

**Comment by makortel** [comment]
Thanks, I missed the one coming from `KeyEqual = std::equal<T>`. Reminds me of the `unique_ptr` with `default_delete` (https://github.com/cms-sw/cmssw/pull/27861).

@smuzaffar Could you re-open the issue?

**Comment by smuzaffar** [comment]
reopen
lets see if bot knows this:-)

**Comment by makortel** [comment]
I have a new attempt in #30004 .
