### ISSUE TITLE
CondCore unit tests failing for PY3 IBs due to use of boost_python

### ISSUE THREAD

**Issue by smuzaffar** [cms-sw/cmssw#29983]
@ggovi , many CodeCore unit tests are failing in PY3 IBs with error like [a]. Problem is that in PY3 IBs , the default python is python3 which these unit tests are linked to boost_python which was build against python2. In past we have avoided such issues by replacing boost_python with pybind11.  Can you please look in to these tests and use PyBind11 instead of boost_python?

[a]
```
===== Test "testAlCaRecoTriggerBitsPayloadInspector" ====
Could not find platform independent libraries &lt;prefix&gt;
Could not find platform dependent libraries &lt;exec_prefix&gt;
Consider setting $PYTHONHOME to &lt;prefix&gt;[:&lt;exec_prefix&gt;]
ImportError: No module named site

---&gt; test testAlCaRecoTriggerBitsPayloadInspector had ERRORS
 
^^^^ End Test testAlCaRecoTriggerBitsPayloadInspector ^^^^
```

**Comment by smuzaffar** [comment]
assign db

**Comment by mmusich** [comment]
I think this issue is caused by the integration of PR #29622.
In PR #29993 I address the issue in a similar fashion as done PR #28842 which was fixing issue #28837. 
Probably `PyBind11` is the best solution though I suspect that needs a more thorough re-thinking of the payload inspector code. My solution at least will remove the unit test failures.

**Comment by smuzaffar** [comment]
thanks @mmusich , can you please also proivde the fix for CondCore/Utilities : https://cmssdt.cern.ch/SDT/cgi-bin/logreader/slc7_amd64_gcc820/CMSSW_11_2_PY3_X_2020-05-27-2300/unitTestLogs/CondCore/Utilities#/

**Comment by mmusich** [comment]
@smuzaffar see https://github.com/cms-sw/cmssw/pull/30008

**Comment by smuzaffar** [comment]
thanks @mmusich
