### ISSUE TITLE
HitPattern class functions giving different return values on edmCopyPickMerged events in CMSSW_10_2_X

### ISSUE THREAD

**Issue by tomcornelis** [cms-sw/cmssw#30143]
I see some inconsistency in the HitPattern functions when running directly on MINIAODSIM files, or when I run on a subset obtained using edmCopyPickMerge, e.g. when you run the framework on

(1) /store/mc/RunIISummer16MiniAODv3/DYJetsToLL_M-50_TuneCUETP8M1_13TeV-amcatnloFXFX-pythia8/MINIAODSIM/PUMoriond17_94X_mcRun2_asymptotic_v3_ext2-v1/100000/005FEC6C-D6C2-E811-A83B-A0369FC5E094.root

(2) file:/eos/cms/store/group/phys_egamma/tnpTuples/testFiles/RunIISummer16MiniAODv3-DYJetsToLL_M-50.root (obtained from the above file using edmCopyPickMerge)

for a CMSSW_10_2_X branch (I tested CMSSW_10_2_22) and compare the output for functions like
electron->gsfTrack()->hitPattern().trackerLayersWithMeasurement()
electron->gsfTrack()->hitPattern().numberOfLostHits(reco::HitPattern::MISSING_INNER_HITS)

you obtain different values, while everything else in the event stays the same.

I'm not sure if this is caused by the HitPattern code, or if something gets corrupted during the edmCopyPickMerge. But I have tested it also in CMSSW_10_6_X running on the same files where this issue is not present. So I would assume there exist some fix for it (either fixing the HitPattern code, or being able to deal with corrupt files from edmCopyPickMerge) which has not been backported to CMSSW_10_2_X?

**Comment by Dr15Jones** [comment]
assign core, reconstruction

**Comment by slava77** [comment]
@tomcornelis 
please specify run:ls:event for events with differences
together with the values and e.g. pt,eta,phi for the electrons.

I tried the two variables in FWLite and the values appear to be the same in both files.

**Comment by tomcornelis** [comment]
Here's some sdiff output when I run on both files:
[diff.txt](https://github.com/cms-sw/cmssw/files/4746232/diff.txt)

The missing hits you don't see much changes (in only occurs in very few events), but for the trackerLayerWithMeasurements() function it results in another integer value for almost all events.
(Note: this is in CMSSW_10_2_22, I don't see these differences when running in CMSSW_10_6)

**Comment by slava77** [comment]
@tomcornelis 
how exactly did you get the RunIISummer16MiniAODv3-DYJetsToLL_M-50.root?
I see that the underlying hitPattern array is different in both cases.

**Comment by tomcornelis** [comment]
The exact command to create the file was:

edmCopyPickMerge inputFiles=/store/mc/RunIISummer16MiniAODv3/DYJetsToLL_M-50_TuneCUETP8M1_13TeV-amcatnloFXFX-pythia8/MINIAODSIM/PUMoriond17_94X_mcRun2_asymptotic_v3_ext2-v1/100000/005FEC6C-D6C2-E811-A83B-A0369FC5E094.root outputFile=RunIISummer16MiniAODv3-DYJetsToLL_M-50.root maxEvents=1000

i.e. I simply wanted to have the first 1000 events from the original file, in order to have a test file at hand. So probably the edmCopyPickMerge command did something wrong then.

**Comment by slava77** [comment]
> The exact command to create the file was:
> 
> edmCopyPickMerge

was it after setting up CMSSW_10_2_22?

**Comment by tomcornelis** [comment]
Yes, I originally did it in an older CMSSW_10_2_X release, but I quickly checked and CMSSW_10_2_22 produces the same result

**Comment by tomcornelis** [comment]
Actually I have to correct myself (I was too quick in the check), and the new edmCopyPickMerge I did in CMSSW_10_2_22 is fine.

But even going back to the older release (CMSSW_10_2_10) I know produce a file which seems to be correct. So I am not sure why edmCopyPickMerge did create something different when I used if a few days ago.

**Comment by slava77** [comment]
Looking at the hitPattern array content, it looks like your RunIISummer16MiniAODv3-DYJetsToLL_M-50.root was made in 10_6_X (the hit bits are re-aligned to 12 bit).

If this issue is resolved now, please close.

**Comment by tomcornelis** [comment]
Ok, I guess this might explain it. Probably I was not aware I had still a cmsenv in a CMSSW_10_6_X release.
