### ISSUE TITLE
[Geometry Configuration] Auto generate a 2021 scenario from a dictionary 

### ISSUE THREAD

**Issue by ianna** [cms-sw/cmssw#30205]
- [ ] Make a 2021 dictionary similar to 2026 one

- [ ] Generate automatically both DD4hep and DD 2021 scenarios

- [ ] Forbid modifications by hand to the 2021 scenario

**Comment by makortel** [comment]
assign geometry

**Comment by ianna** [comment]
this is being implemented in https://github.com/cms-sw/cmssw/pull/30214

**Comment by cvuosalo** [comment]
+1
