### ISSUE TITLE
PuppiMET does not include latest JECs for Type-1 corrections in NanoAOD and missing uncertainties

### ISSUE THREAD

**Issue by saghosh** [cms-sw/cmssw#30304]
Reapplication of JECs for Type-1 corrections for PuppiMET is not performed to include the latest JECs during NanoAOD production.
https://github.com/cms-sw/cmssw/blob/master/PhysicsTools/NanoAOD/python/nano_cff.py#L198

This is particularly relevant for 2018D in which the MiniAOD is PROMPT RECO.
It is not possible to re-apply JECs on the fly since the AK4PuppiJet collection is not stored in NanoAOD.

Also uncertainties for PuppiMET, particularly UnclusteredEnergy Uncertainties and the JER, JES down uncertainties are missing.
Only part of the uncertainties were added previously : https://github.com/cms-nanoAOD/cmssw/pull/516/files

This issue is already raised in the NanoAOD git area : 
https://github.com/cms-nanoAOD/cmssw/issues/523

**Comment by saghosh** [comment]
Bringing to the notice of @ahinzmann , @lathomas , @peruzzim 

I have made the code changes required for a pull request [1].

Before opening a pull request, I wanted to ask about the line 219
in the nano_cff file [2], where the 'switchOnVIDPhotonIdProducer'
function is called and it is mentioned in the comments that this
should not be used in case 'makePuppiesFromMiniAOD' is called, which
we want to do.
Going through the history, it appears that @peruzzim  had made the last
change for this [3], so perhaps you can tell me if I should also
comment out the call to switchOnVIDPhotonIdProducer for this code
change or not.

[1] https://github.com/saghosh/cmssw/commit/ae4793e9450a879ef68c2ad69d5b76e5a64c1bd0#

[2] https://github.com/cms-sw/cmssw/blob/master/PhysicsTools/NanoAOD/python/nano_cff.py#L219

[3] https://github.com/cms-sw/cmssw/commit/88d684cc772c4101dcf057a79638403813969c00

**Comment by makortel** [comment]
assign reconstruction, xpog

**Comment by ahinzmann** [comment]
@saghosh In the latest Run2 release (10_6_X) Puppi is actually not using photon ID anymore and not calling switchOnVIDPhotonIdProducer anymore:
https://github.com/cms-sw/cmssw/blob/CMSSW_10_6_X/PhysicsTools/PatAlgos/python/slimming/puppiForMET_cff.py
So I believe you can leave the NanoAOD code untouched, and get rid of the comments related to VID, which do not hold anymore.

**Comment by saghosh** [comment]
Hello, thank you.
For more details about the issue and resolution and the verification of it, please see the slides linked below
https://indico.cern.ch/event/924615/contributions/3885484/attachments/2049952/3435787/Pre_EPR_MET_June3.pdf

**Comment by saghosh** [comment]
Resolved with PR https://github.com/cms-sw/cmssw/pull/30922
