### ISSUE TITLE
Missing Parameter in L1TTauOffline/'l1tTauOfflineDQM'

### ISSUE THREAD

**Issue by chayanit** [cms-sw/cmssw#30324]
I have been running premixing PU RelVals 2021 scenario to be validated for closed cycle of 11_1_0 and getting this error in production. "workingsPoints" parameter is missing at L1T. 

Fatal Exception (Exit code: 8009)
An exception of category 'Configuration' occurred while
[0] Processing Event run: 1 lumi: 148 event: 14705 stream: 0
[1] Calling method for module L1TTauOffline/'l1tTauOfflineDQM'
Exception Message:
MissingParameter: Parameter 'workingsPoints' not found.

See https://dmytro.web.cern.ch/dmytro/cmsprodmon/workflows.php?prep_id=CMSSW_11_1_0_pre8__fullsim_PU2021_premix-1592492510-ZMM_14 

It seems something related to this merge PR #28417 @swozniewski. Could you help checking? Thanks in advance. 

FYI. @silviodonato

**Comment by swozniewski** [comment]
Hi, this seems to be a stupid typo. sorry for that! This line is calling 'workingsPoints' (note the 's' in the middle, which I only realized after reading it several times now...) from provenance of the antiElectronID, which has 'workingPoints' in its config. See
https://github.com/cms-tau-pog/cmssw/blob/e3ee2f54d22194b79a0f8ad58d32cfb1b8b946e2/DQMOffline/L1Trigger/src/L1TTauOffline.cc#L681
and 
https://github.com/cms-sw/cmssw/blob/master/RecoTauTag/Configuration/python/HPSPFTaus_cff.py#L287
Could you please check whether your workflow runs successfully if you remove the 's' in the middle? I will set up the PR then to fix it.

**Comment by chayanit** [comment]
Thanks! @swozniewski  ok I will resubmit and let you know.

**Comment by makortel** [comment]
assign dqm

**Comment by chayanit** [comment]
@swozniewski I can't fix this locally. Please make PR and I can only check the production when PR is merged to new release.

**Comment by swozniewski** [comment]
Ok, sure. I think the problem here is rather clear. Would have only been nice to see that nothing else pops up.

**Comment by swozniewski** [comment]
@chayanit just in case you did not notice anyway: The two PRs mentioned above are now merged.

**Comment by chayanit** [comment]
Thanks! indeed I did not notice but now I do :) @swozniewski

**Comment by jfernan2** [comment]
+1
