### ISSUE TITLE
RecoTrack/FinalTrackSelectors: Replace float with double per Intel Advisor

### ISSUE THREAD

**Issue by gartung** [cms-sw/cmssw#30331]
Intel Advisor flagged this loop
https://github.com/cms-sw/cmssw/blob/8008927682387dc69c5dfde3ced7b0d8fe918373/RecoTracker/FinalTrackSelectors/plugins/TrackListMerger.cc#L501
because of type conversion done at line 579 and 580.
https://github.com/cms-sw/cmssw/blob/8008927682387dc69c5dfde3ced7b0d8fe918373/RecoTracker/FinalTrackSelectors/plugins/TrackListMerger.cc#L579
This can be avoided by changing
float shareFrac_ 
to 
double shareFrac_
as indicated by the paremeterSet type.
https://github.com/cms-sw/cmssw/blob/8008927682387dc69c5dfde3ced7b0d8fe918373/RecoTracker/FinalTrackSelectors/plugins/TrackListMerger.cc#L99

**Comment by makortel** [comment]
assign reconstruction

**Comment by slava77** [comment]
It looks like the issue is in 
```c++
                  ? (noverlap - firstoverlap) > (std::min(nhit1, nhit2) - firstoverlap) * shareFrac_
                  : (noverlap - firstoverlap) > (std::min(nhit1, nhit2) - firstoverlap) * indivShareFrac_[collNum];
```
where ```shareFrac_``` is a float, while ```indivShareFrac_``` is a double.

I'd change everything to float (and be careful with some double literals in the code to be converted to floats as well).

@VinInn

**Comment by VinInn** [comment]
+1

**Comment by VinInn** [comment]
If that line were a real performance issue then the solution would be to transform it in fixed point

say

auto frac = collNum==collNum2 ? indivShareFracX100_[collNum] : shareFracX1000_;
auto dup = 1000*(noverlap - firstoverlap) > (std::min(nhit1, nhit2) - firstoverlap) * frac;


were the aX1000 is  int(a*1000.+0.5); done ONCE in the constructor
.

**Comment by gartung** [comment]
Mattermost thread with screenshots showing the marked line and corresponding assembley
https://mattermost.web.cern.ch/cms-o-and-c/pl/rbdad811r78zffrjg9rbafnqsh

**Comment by gartung** [comment]
![Screen Shot 2020-06-23 at 11 16 17 AM](https://user-images.githubusercontent.com/4292184/85443013-62f10900-b556-11ea-977e-10f4d07570af.png)

**Comment by gartung** [comment]
![Screen Shot 2020-06-23 at 11 20 05 AM](https://user-images.githubusercontent.com/4292184/85443047-6e443480-b556-11ea-802c-ffc3b0a0b526.png)

**Comment by gartung** [comment]
The actual statement from Intel Advisor below
![Screenshot from 2020-06-23 18-16-22](https://user-images.githubusercontent.com/4292184/85477297-add34680-b57f-11ea-9c4d-a198e1cfe259.png)
