### ISSUE TITLE
RecoVertex/PrimaryVertexProducer: DAClusterizeInZ_vector.cc loop at line 654 with type conversion

### ISSUE THREAD

**Issue by gartung** [cms-sw/cmssw#30332]
Intel Advisor identified the loop at line 654 has a conversion most likely in the expression at line 657 where the loop spends the most time
https://github.com/cms-sw/cmssw/blob/af0491716a5e551e527bc33c4e995e5870823467/RecoVertex/PrimaryVertexProducer/src/DAClusterizerInZ_vect.cc#L657

**Comment by makortel** [comment]
assign reconstruction

**Comment by slava77** [comment]
@gartung 
everything appears to be in double at that line.
Are there any more diagnostic details from the advisor?
If the loc is not directly identifiable, even an assembley snippet could be informative.

@werdmann 
please note

**Comment by gartung** [comment]
At line 657 and line 660 the comparison should be made to '0.0' not 1e-100 or 0.

**Comment by gartung** [comment]
The second longest time is spent at line 660 so perhaps it is identifying the conversion of 0 to 0.0 for comparison.

**Comment by slava77** [comment]
> At line 657 and line 660 the comparison should be made to '0.0' not 1e-100 or 0.

in ```tks.Z_sum_ptr[i] > 1.e-100``` 1e-100 is still a double, compared to a double; and 1e-100 is not equal 0.0 in double precision.
Changing to 0.0 here is inappropriate, IIUC.

**Comment by gartung** [comment]
Agreed. I think the conversion is at line 660 from 0 to 0.0

**Comment by werdmann** [comment]
Interesting. I agree that the 1e-100 should not be 0.0, just a small non-zero number to make sure that Z_sum does not become arbitrarily close to 0.
Coincidentally I am currently playing with the 0 in in line 660 and see improvements with larger values. Optimization is still ongoing, but 0.5 seems safe and conservative bet. So if you touch it now, I would propose 0.5. The optimal value may be slightly higher but needs more testing (means that the tracks counted as "unique" to this cluster are not allowed to have large impact parameters)

**Comment by gartung** [comment]
The performance measurement was taken with CMSSW_11_1_0_pre8. Has a PR been merged that updates this?
The assembly shows 3 type conversions on line  657.

**Comment by werdmann** [comment]
No PR yet, maybe in a couple of weeks. I have no idea what "The assembly shows 3 type conversions on line 657" mean. I'm happy if you make changes to optimize the cpu time. All I wanted to say is, that if you do something to that "0" in line 660 you may as well make it a nonzero value like 0.5 which reduces the fake rate without loss of efficiency (to be clear, when I said improvement I meant the quality of the reconstruction, not the cpu time, but yes I worked  in 11_1_0_pre8).

**Comment by slava77** [comment]
> The performance measurement was taken with CMSSW_11_1_0_pre8. Has a PR been merged that updates this?
> The assembly shows 3 type conversions on line 657.

IIRC, this code was not changed after CMSSW_11_1_0_pre8, but it was changed for CMSSW_11_1_0_pre8 (just to make sure if the profiling was not done with a version older than pre8).

**Comment by gartung** [comment]
Github doesn't allow posting screenshots but Mattermost does. See
https://mattermost.web.cern.ch/cms-o-and-c/pl/gsj4dshr13rq8kqrwtn6suj54h

**Comment by gartung** [comment]
I mean that the assembly code the gcc produces which Intel Advisor display with the corresponding line in the code.

**Comment by slava77** [comment]
Looking in the assembly, I'm guessing  that the conversion could come from outside:
https://github.com/dpiparo/vdt/blob/3cd969d8ee48b99ccfea9e3062274a2832cceeec/include/vdtcore_common.h#L217-L221

Here is a snippet from ```objdump -dal ../lib/slc7_amd64_gcc820/libRecoVertexPrimaryVertexProducer.so  | c++filt ``` after recompiling the library with -g.

```
vdt::fast_exp(double)():
/cvmfs/cms.cern.ch/slc7_amd64_gcc820/cms/vdt/0.4.0-bcolbf2/include/vdt/exp.h:78
   2ea03:       66 0f 28 d8             movapd %xmm0,%xmm3
/cvmfs/cms.cern.ch/slc7_amd64_gcc820/cms/vdt/0.4.0-bcolbf2/include/vdt/exp.h:73
   2ea07:       f2 41 0f 59 cf          mulsd  %xmm15,%xmm1
   2ea0c:       f2 0f 58 0d 1c 0a 02    addsd  0x20a1c(%rip),%xmm1        # 4f430 <typeinfo name for DAClusterizerInZ+0x70>
   2ea13:       00
vdt::details::fpfloor(double)():
/cvmfs/cms.cern.ch/slc7_amd64_gcc820/cms/vdt/0.4.0-bcolbf2/include/vdt/vdtcore_common.h:219
   2ea14:       f2 0f 2c c9             cvttsd2si %xmm1,%ecx
/cvmfs/cms.cern.ch/slc7_amd64_gcc820/cms/vdt/0.4.0-bcolbf2/include/vdt/vdtcore_common.h:220
   2ea18:       f2 0f 5a e1             cvtsd2ss %xmm1,%xmm4
   2ea1c:       66 41 0f 7e e0          movd   %xmm4,%r8d
/cvmfs/cms.cern.ch/slc7_amd64_gcc820/cms/vdt/0.4.0-bcolbf2/include/vdt/vdtcore_common.h:221
   2ea21:       66 0f ef c9             pxor   %xmm1,%xmm1
/cvmfs/cms.cern.ch/slc7_amd64_gcc820/cms/vdt/0.4.0-bcolbf2/include/vdt/vdtcore_common.h:220
   2ea25:       41 c1 e8 1f             shr    $0x1f,%r8d
   2ea29:       44 29 c1                sub    %r8d,%ecx
/cvmfs/cms.cern.ch/slc7_amd64_gcc820/cms/vdt/0.4.0-bcolbf2/include/vdt/vdtcore_common.h:221
   2ea2c:       f2 0f 2a c9             cvtsi2sd %ecx,%xmm1
```

@gartung 
do you have a relevant assembly snippet from the Advisor?

**Comment by gartung** [comment]
Yes. I attached it to the Mattermost thread linked above.

**Comment by slava77** [comment]
> Yes. I attached it to the Mattermost thread linked above.

it looks like my part matches your 3 cvt\* calls with some (minor?) offset in the address.
So, this confirms that the operation is a part of the ```fast_exp``` call from vdt, more specifically from ```details::fpfloor```

**Comment by gartung** [comment]
It looks like the compiler sees the input to local_exp as a float and there is only a version of local_exp that takes a double
https://github.com/cms-sw/cmssw/blob/af0491716a5e551e527bc33c4e995e5870823467/RecoVertex/PrimaryVertexProducer/src/DAClusterizerInZ_vect.cc#L96
Perhaps adding a version of local_exp that takes float as an argument.

**Comment by gartung** [comment]
Nevermind. It looks like there is always a conversion from int32_t to double or float no matter which version of fpfloor is called
https://github.com/dpiparo/vdt/blob/3cd969d8ee48b99ccfea9e3062274a2832cceeec/include/vdtcore_common.h#L221

**Comment by gartung** [comment]
![image](https://user-images.githubusercontent.com/4292184/85442748-1e656d80-b556-11ea-8e7d-daf881fb0132.png)

**Comment by gartung** [comment]
![Screen Shot 2020-06-23 at 10 46 00 AM](https://user-images.githubusercontent.com/4292184/85442811-33420100-b556-11ea-9115-6926d513620a.png)

**Comment by gartung** [comment]
I didn'y realize you can copy paster an image into github comments.

**Comment by gartung** [comment]
The type conversion is not the cause of the loop not being vectorized. The statement from Intel Advisor is shown in the cap below

![Screenshot from 2020-06-23 18-16-22](https://user-images.githubusercontent.com/4292184/85477209-76649a00-b57f-11ea-92f1-41aaca149216.png)

**Comment by slava77** [comment]
by now it looks like we cleared on the mattermost chat that the issue here is with the conditionals 

the current loop
```c++
    for (unsigned int i = 0; i < nt; i++) {
      if (tks.Z_sum_ptr[i] > 1.e-100) {
        double p = y.pk_ptr[k] * local_exp(-beta * Eik(tks.z_ptr[i], y.z_ptr[k], tks.dz2_ptr[i])) / tks.Z_sum_ptr[i];
        sump += p;
        if ((p > uniquetrkweight_ * pmax) && (tks.pi_ptr[i] > 0)) {
          nUnique++;
        }
      }
    }
should be split in two: one to compute a vector/array of ```p``` and another much simpler to get ```sump```  and ```nUnique``` out of it; that's all assuming that ```tks.Z_sum_ptr[i] > 1.e-100``` is the dominant case, at least to happen in 50% of cases to not slow down with the current SSE compilation flags in CMSSW.

**Comment by slava77** [comment]
@werdmann 
how often is the following true in this part of the code?
> if (tks.Z_sum_ptr[i] > 1.e-100)

**Comment by gartung** [comment]
see https://github.com/cms-sw/cmssw/pull/30437
