### ISSUE TITLE
Problem with ParameterSet when ExternalGeneratorFilter is used

### ISSUE THREAD

**Issue by srimanob** [cms-sw/cmssw#30335]
The relvals on ExternalGeneratorFilter faces an issue on PSet.py, https://cms-unified.web.cern.ch/cms-unified/report/asikdar_RVCMSSW_11_1_0_pre8LambdabToLambdasMuMu_13TeV_Pythia8__JIRA81_gen_200619_123719_2525

> An exception of category 'ConfigFileReadError' occurred while
> [0] Processing the python configuration file named PSet.py
> Exception Message:
> unknown python problem occurred.
> KeyError: '_prod'

Copying PSet.* from https://cms-unified.web.cern.ch/cms-unified//joblogs/asikdar_RVCMSSW_11_1_0_pre8LambdabToLambdasMuMu_13TeV_Pythia8__JIRA81_gen_200619_123719_2525/7002/LambdabToLambdasMuMu_13TeV_Pythia8/a1e2f744-5b50-40ff-9e6a-2233f0dba2b5-0-3-logArchive/job/WMTaskSpace/cmsRun1/
and try to do edmConfigDump PSet.py shows an issue, e.g.

> Traceback (most recent call last):
>   File "/afs/cern.ch/work/s/srimanob/test/GEN/CMSSW_11_1_0_pre8/python/GeneratorInterface/Core/ExternalGeneratorFilter.py", line 19, in __getattr__
>     return getattr(self._prod, name)

In addition, when I try to run cmsDriver locally, using GEN fragment in
/afs/cern.ch/user/s/srimanob/public/ForPdmV/LambdabToLambdasMuMu_13TeV_Pythia8_cfi.py

`cmsDriver.py Configuration/Generator/LambdabToLambdasMuMu_13TeV_Pythia8_cfi --conditions 102X_upgrade2018_realistic_v11 -n 10 --era Run2_2018 --eventcontent RAWSIM,DQM --relval 1000000,10000 -s GEN,VALIDATION:genvalid_all --datatier GEN,DQMIO --beamspot Realistic25ns13TeVEarly2018Collision --geometry DB:Extended --io LambdabToLambdasMuMu_13TeV_Pythia8.io --python LambdabToLambdasMuMu_13TeV_Pythia8_cfg.py --customise Configuration/DataProcessing/Utils.addMonitoring --no_exec --fileout file:step1.root --nThreads 8`

I always get kind-of warning, "cannot inline -_generator- : not known" but configuration seems to dump properly.

**Comment by makortel** [comment]
assign core, generators

**Comment by makortel** [comment]
@Dr15Jones Could you take a look?

**Comment by Dr15Jones** [comment]
@makortel yes, I will look into this

**Comment by Dr15Jones** [comment]
Fixed in #30347 and #30346

**Comment by srimanob** [comment]
Thanks @Dr15Jones 
@silviodonato PR #30346 should target for the next 11_1_0, thanks.

**Comment by makortel** [comment]
#30346 is being backported to 10_6 in #30649

**Comment by makortel** [comment]
+1

**Comment by makortel** [comment]
I think this issue could be closed
