### ISSUE TITLE
add re-miniAOD workflow for HI 2018 data

### ISSUE THREAD

**Issue by slava77** [cms-sw/cmssw#30349]
this is needed to support the planned miniAOD (re)processing of HI data (and MC).
Ideally, this should include all necessary validation and DQM setup

@mandrenguyen 
It would be nice if someone from the HI community can make a PR for this.
I may be able to get to this soon, but will need a good reference file for testing; a pair of MC and data would be needed.

**Comment by slava77** [comment]
assign reconstruction,pdmv

**Comment by mandrenguyen** [comment]
@slava77 I can take care of that.   Incidentally, for data there is a issue related to the reMiniAOD of 10_3_X data in 11_2.  It seems puppi was moved to reco, such that the miniAOD in 11_2 looks for the products.  Probably not a hard fix, but we should probably make a decision about whether the reMiniAOD will happen in 11_2 or whether we would like to backport the HI miniAOD stuff into CMSSW 10.  How should we proceed?

**Comment by slava77** [comment]
I still expect that we can support remini in the master.
The puppi parts can be remade similar to other re-miniAOD workflows.

I understood that the 10_6_X is preferred for the actual production because the (ultra) legacy remini is done there.
Even though in this case there is no match in the base release, I guess the point is that you would still be better off to be able to also potentially use the UL samples.

**Comment by slava77** [comment]
+1

resolved by #30354
