### ISSUE TITLE
ProductNotFound (simEcalEBTriggerPrimitiveDigis) in wf 20634.99

### ISSUE THREAD

**Issue by silviodonato** [cms-sw/cmssw#30539]
After having turned on the new Phase-2 L1T package (`CMSSW_11_2 2020-07-02-2300`, #30498, #30479) we are getting an exception in 20634.99:
```
----- Begin Fatal Exception 04-Jul-2020 03:42:40 CEST-----------------------
An exception of category 'ProductNotFound' occurred while
   [0] Processing  Event run: 1 lumi: 2 event: 104 stream: 2
   [1] Running path 'FEVTDEBUGHLToutput_step'
   [2] Prefetching for module PoolOutputModule/'FEVTDEBUGHLToutput'
   [3] Calling method for module L1EGCrystalClusterEmulatorProducer/'L1EGammaClusterEmuProducer'
Exception Message:
Principal::getByToken: Found zero products matching all criteria
Looking for type: edm::SortedCollection&lt;EcalEBTriggerPrimitiveDigi,edm::StrictWeakOrdering&lt;EcalEBTriggerPrimitiveDigi&gt; &gt;
Looking for module label: simEcalEBTriggerPrimitiveDigis
Looking for productInstanceName: 
Looking for process: HLT
   Additional Info:
      [a] If you wish to continue processing events after a ProductNotFound exception,
add "SkipEvent = cms.untracked.vstring('ProductNotFound')" to the "options" PSet in the configuration.

----- End Fatal Exception -------------------------------------------------
```

**Comment by silviodonato** [comment]
assign l1

**Comment by silviodonato** [comment]
assign upgrade

**Comment by silviodonato** [comment]
The problem is related to this line
https://github.com/cms-sw/cmssw/blob/master/Configuration/StandardSequences/python/DigiDM_cff.py#L43
(https://github.com/cms-sw/cmssw/pull/23065)

The offending `cmsDriver.py` command is 
`step3 --datamix PreMix --conditions auto:phase2_realistic_T14 --pileup_input file:step2.root -n 10 --era Phase2C8 --eventcontent FEVTDEBUGHLT --procModifiers premix_stage2 --filein file:step1.root -s DIGI:pdigi_valid,DATAMIX,L1TrackTrigger,L1,DIGI2RAW,HLT:@fake2 --datatier GEN-SIM-DIGI-RAW --geometry Extended2026D41 --fileout file:step3.root`

**Comment by kpedro88** [comment]
@makortel FYI

I think the input tag needs to be customized to `DMEcalEBTriggerPrimitiveDigis` using the `premix_stage2` modifier

**Comment by makortel** [comment]
> I think the input tag needs to be customized to `DMEcalEBTriggerPrimitiveDigis` using the `premix_stage2` modifier

By quick look I agree (alternative would be to take a step towards resolving https://github.com/cms-sw/cmssw/issues/26001, but that would require larger re-engineering).
