### ISSUE TITLE
PixelRecoUtilities needs to be reworked to support EventSetup consumes

### ISSUE THREAD

**Issue by Dr15Jones** [cms-sw/cmssw#30560]
The PixelRecoUtilities takes an EventSetup in order to get access to the magnetic field (which it then caches in a function local `static`). This needs to be changed in order to accomodate specifying the consumes of the EventSetup. The most straight-forward way to proceed would be to change the code to take the MagneticField directly instead of passing down the EventSetup. Then it becomes the responsibility of the client code to do the consumes.

**Comment by Dr15Jones** [comment]
assign reconstruction

**Comment by slava77** [comment]
@VinInn 
at least a part of the original change was yours
https://github.com/cms-sw/cmssw/commit/df6b957cf54e79155e938be78e32cf389be37bba#diff-40e1ccc149b11611cde767c194141616

Please comment if the proposed solution would be OK

> The most straight-forward way to proceed would be to change the code to take the MagneticField directly instead of passing down the EventSetup. 


@mtosi @JanFSchulte @vmariani

**Comment by VinInn** [comment]
These utilities where already obsolete at the time of my modifications.
The problem is similar, but simpler as limited to 0,0,0, to what already discussed for the mag field cache for Geant4.
we just need a global variable, accessible from everywhere at no cost, that return the nominal mag field...
