### ISSUE TITLE
Missing dictionaries from L1T developments

### ISSUE THREAD

**Issue by davidlange6** [cms-sw/cmssw#30570]
The modules build suggests we miss a dictionary for

Fatal Root Error: @SUB=TStreamerInfo::Build
pair<edm::Ptr<TrackingParticle>,vector<edm::Ref<edmNew::DetSetVector<TTCluster<edm::Ref<edm::DetSetVector<Phase2TrackerDigi>,Phase2TrackerDigi,edm::refhelper::FindForDetSetVector<Phase2TrackerDigi> > > >,TTCluster<edm::Ref<edm::DetSetVector<Phase2TrackerDigi>,Phase2TrackerDigi,edm::refhelper::FindForDetSetVector<Phase2TrackerDigi> > >,edmNew::DetSetVector<TTCluster<edm::Ref<edm::DetSetVector<Phase2TrackerDigi>,Phase2TrackerDigi,edm::refhelper::FindForDetSetVector<Phase2TrackerDigi> > > >::FindForDetSetVector> > >: edm::Ptr<TrackingParticle> has no streamer or dictionary, data member "first" will not be saved

Could this be fixed. Thanks

**Comment by Dr15Jones** [comment]
edm::Ptr is a templated class. What is the template argument for the missing type?

**Comment by davidlange6** [comment]
Oh strange - my text got mangled.

```
pair<edm::Ptr<TrackingParticle>,vector<edm::Ref<edmNew::DetSetVector<TTCluster<edm::Ref<edm::DetSetVector<Phase2TrackerDigi>,Phase2TrackerDigi,edm::refhelper::FindForDetSetVector<Phase2TrackerDigi> > > >,TTCluster<edm::Ref<edm::DetSetVector<Phase2TrackerDigi>,Phase2TrackerDigi,edm::refhelper::FindForDetSetVector<Phase2TrackerDigi> > >,edmNew::DetSetVector<TTCluster<edm::Ref<edm::DetSetVector<Phase2TrackerDigi>,Phase2TrackerDigi,edm::refhelper::FindForDetSetVector<Phase2TrackerDigi> > > >::FindForDetSetVector> > >: edm::Ptr<TrackingParticle> has no streamer or dictionary, data member "first" will not be saved
```

Lets see if this is better.

On Jul 7, 2020, at 2:14 PM, Chris Jones <notifications@github.com<mailto:notifications@github.com>> wrote:



edm::Ptr is a templated class. What is the template argument for the missing type?

**Comment by makortel** [comment]
The error itself looks similar to https://github.com/cms-sw/cmssw/pull/30510#issuecomment-653185215. I'm wondering why we see these errors in ROOT's `TStreamerInfo::Build` instead of e.g. framework's `produce<T>()`.

**Comment by makortel** [comment]
assign l1,upgrade

**Comment by kpedro88** [comment]
https://github.com/cms-sw/cmssw/blob/02d4198c0b6615287fd88e9a8ff650aea994412e/SimGeneral/TrackingAnalysis/src/classes_def.xml#L5

why isn't that dictionary used?

it's hard for me to tell where this error comes from.

**Comment by makortel** [comment]
> https://github.com/cms-sw/cmssw/blob/02d4198c0b6615287fd88e9a8ff650aea994412e/SimGeneral/TrackingAnalysis/src/classes_def.xml#L5
> 
> why isn't that dictionary used?

Not sure, but at least all those dictionary declarations are in a wrong package. None of them are declared as transient, so all should be declared in some data format package. By quick look I'd place all of them to `SimDataFormats/TrackingAnalysis` where `TrackingParticle` is defined.

**Comment by kpedro88** [comment]
There are some cases that mix classes from `SimDataFormats/TrackingAnalysis` and `DataFormats/L1TrackTrigger`. How should those be handled?

Also, how can the error observed by @davidlange6 be reproduced?

**Comment by makortel** [comment]
> There are some cases that mix classes from `SimDataFormats/TrackingAnalysis` and `DataFormats/L1TrackTrigger`. How should those be handled?

`DataFormats/L1TrackTrigger` must not depend on `SimDataFormats`, but other way around is allowed. Also `SimDataFormats/TrackingAnalysis` already depends on `DataFormats/TrackReco` for types containing both `TrackingParticle` and `reco::Track`, I think the L1 track trigger classes could be dealt similarly.

**Comment by davidlange6** [comment]
> > https://github.com/cms-sw/cmssw/blob/02d4198c0b6615287fd88e9a8ff650aea994412e/SimGeneral/TrackingAnalysis/src/classes_def.xml#L5
> > 
> > why isn't that dictionary used?
> 
> Not sure, but at least all those dictionary declarations are in a wrong package. None of them are declared as transient, so all should be declared in some data format package. By quick look I'd place all of them to `SimDataFormats/TrackingAnalysis` where `TrackingParticle` is defined.

can we establish a rule about this? Is there a valid reason to have dictionaries declared outside of *data*formats and condformats packages?

**Comment by makortel** [comment]
> can we establish a rule about this? 

We have rules stated in https://twiki.cern.ch/twiki/bin/view/CMSPublic/SWGuideCreatingNewProducts that essentially say that the `classes_def.xml` needs to be in the package that defines the product. 

> Is there a valid reason to have dictionaries declared outside of _data_formats and condformats packages?

We have allowed dictionaries for transient-only products (that includes also algorithms) and (I believe) classes needed only in string parsing be declared in non-formats packages.

**Comment by davidlange6** [comment]
#30848 at least partly addresses this issue I believe.
