### ISSUE TITLE
PFClusterValidation module is unsafe and potentially incorrect

### ISSUE THREAD

**Issue by fwyzard** [cms-sw/cmssw#30588]
The [`PFClusterValidation`](https://github.com/cms-sw/cmssw/blob/master/Validation/RecoParticleFlow/plugins/PFClusterValidation.cc) uses unsafe and potentially incorrect constructs:

This https://github.com/cms-sw/cmssw/blob/9bfebaea09245072fa05ba5c03ac079636ea3ae7/Validation/RecoParticleFlow/plugins/PFClusterValidation.h#L77 make "leak" values from one event to the next.

This https://github.com/cms-sw/cmssw/blob/9bfebaea09245072fa05ba5c03ac079636ea3ae7/Validation/RecoParticleFlow/plugins/PFClusterValidation.cc#L139-L148 will try to read the MC collection even after checking that it's missing.

This https://github.com/cms-sw/cmssw/blob/9bfebaea09245072fa05ba5c03ac079636ea3ae7/Validation/RecoParticleFlow/plugins/PFClusterValidation.cc#L240-L252 should just be replaced by a call to `reco::deltaR()` (or better, `reco::DeltaR2()`).

Of course the variables should be renamed to follow the usual CMS coding rules, *etc.*, but that's less of a problem... 

Is this modules still used ?

**Comment by fwyzard** [comment]
assign reconstruction

**Comment by fwyzard** [comment]
@bendavid @hatakeyamak FYI

**Comment by davidlange6** [comment]
Its dqm that manages Validation packages.

On Jul 8, 2020, at 8:49 AM, Andrea Bocci <notifications@github.com<mailto:notifications@github.com>> wrote:



assign reconstruction

**Comment by fwyzard** [comment]
I would assume that "validation of something" falls under the responsibility of the developers for "something" - in this case Particle Flow, which IIRC is under Reconstruction.

**Comment by davidlange6** [comment]
Not at the level of the coordination groups in cms anyway, no.

On Jul 8, 2020, at 9:03 AM, Andrea Bocci <notifications@github.com<mailto:notifications@github.com>> wrote:



I would assume that "validation of something" falls under the responsibility of the developers for "something" - in this case Particle Flow, which IIRC is under Reconstruction.

**Comment by fwyzard** [comment]
Do you disagree that PF should look into this issue ?

**Comment by davidlange6** [comment]
No. That is the needed outcome.   PF is not strictly “under reconstruction” organizationally or code-responsibility wise (the way CMS organized itself).

On Jul 8, 2020, at 9:44 AM, Andrea Bocci <notifications@github.com<mailto:notifications@github.com>> wrote:



Do you disagree that PF should look into this issue ?

**Comment by fwyzard** [comment]
So, how do I "assign" an issue to PF ?

**Comment by davidlange6** [comment]
indeed… I guess the path is

1) Assign dqm
2) Dqm propagates to the dqm experts in PF.

On Jul 8, 2020, at 10:14 AM, Andrea Bocci <notifications@github.com<mailto:notifications@github.com>> wrote:



So, how do I "assign" an issue to PF ?

**Comment by fwyzard** [comment]
I see.

Well, I'd rather ping the PF people directly than add another link to the chain... 

It's taken more time to comment on this than to actually fix it.

**Comment by makortel** [comment]
assign dqm

**Comment by hatakeyamak** [comment]
Noted. Will try to address it.
@juska

**Comment by fwyzard** [comment]
see #30589

**Comment by hatakeyamak** [comment]
I see. Thank you for this PR.

**Comment by slava77** [comment]
unassign reconstruction

we are tagged here already, which is enough, just in case

**Comment by fwyzard** [comment]
@hatakeyamak @juska apart from the code improvements - is the `PFClusterValidation` module still used / useful ?

**Comment by juska** [comment]
I'd assume that this fairly new module is still in use. @hatakeyamak or @akanugan as the original author for this module can confirm.

**Comment by jfernan2** [comment]
pinging  @hatakeyamak or @akanugan ?

**Comment by hatakeyamak** [comment]
This is actually a rather old validation code, which we are not closely monitoring now, so it didn't get a high priority. It doesn't necessarily mean that this is not useful though.

I am right now developing a cleanup branch/PR of pf validation package:
https://github.com/hatakeyamak/cmssw/tree/PFVal_update_11_2
so I will try to address it as a part of this.

**Comment by hatakeyamak** [comment]
I wouldn't say this is heavily used, but it helps, for example, for single particle gun samples. So, it will be reasonable to keep it.

**Comment by fwyzard** [comment]
I think #30589 fixed the potential problems, so shall we close this issue ?

**Comment by hatakeyamak** [comment]
Certainly ok for me.
