### ISSUE TITLE
Github teams for CMSSW L2s

### ISSUE THREAD

**Issue by smuzaffar** [cms-sw/cmssw#30597]
As discussed here https://github.com/cms-sw/cms-bot/issues/1335 , we have now created `cms-sw/<category>-l2` github teams . This will allow you to get attention of L2's by using `@cms-sw/<category>-l2` in comment. In order to automatically manage these teams, one should be added as member of `cms-sw` organization. Some of you might have received an invitation to join `cms-sw` organization, please accept that invitation so that bot can automatically add you to the correct team.

There is also a special team `cms-sw/all-l2` which can be used to ping all L2's and ORP.

**Comment by smuzaffar** [comment]
@tlampen,@jpata,@alberto-sanchez,@peruzzim,@tocheng,@rekovic,@mkirsano,@lveldere,@sbein,@wajidalikhan,@christopheralanwest,@pgunnell,@SiewYan,@kmaeshima  can you please accept the invitation to join `cms-sw` organization ?

**Comment by smuzaffar** [comment]
@makortel , @Dr15Jones , @silviodonato we have `docs` category with `cmsdoxy` user as L2 [a]. this was there as we had a cat-A running doxygen for generating cmssw documentation. This is now done by CMSSDT group. So I would suggestto drop the `docs` category and add these packages under `core`. Any objections? 

[a]
```
  "docs": [
    "Documentation/CodingRules",
    "Documentation/DataFormats",
    "Documentation/PhysicsTools",
    "Documentation/ReferenceManualScripts",
  ],
```

**Comment by makortel** [comment]
No objections from me.

**Comment by smuzaffar** [comment]
thanks @makortel . category `docs` is now merged with `core` ( https://github.com/cms-sw/cms-bot/pull/1342 )

**Comment by mmusich** [comment]
@smuzaffar is this supposed to work for everybody or only for L2s? 
I tried it here: https://github.com/cms-sw/cmssw/pull/31253#issuecomment-686409500 
but it doesn't seem to tag anyone.

**Comment by smuzaffar** [comment]
@mmusich , bot is not going to tag any one. In this case github should have sent a message to members of these teams.

**Comment by mmusich** [comment]
@smuzaffar I mean that it looks like the "@" is not working, if I hover with the mouse over it, it doesn't seem a "tag" in the gitHub sense, but just a plain string. In other places where it was used by others it looks different (e.g. here: https://github.com/cms-sw/cmssw/pull/30847#issuecomment-679928752)

**Comment by smuzaffar** [comment]
testing @cms-sw/core-l2 mentioning here

**Comment by smuzaffar** [comment]
@mmusich , looks like it works only for members of the organization. I will check if there is way to open it for every one

**Comment by mmusich** [comment]
@smuzaffar thanks. No problem, I just wanted to understand if I may use it or not.

**Comment by slava77** [comment]
@smuzaffar is there a team for generators?

**Comment by smuzaffar** [comment]
yes there is @cms-sw/generators-l2

**Comment by slava77** [comment]
I'm getting a 404 at https://github.com/orgs/cms-sw/teams/generators-l2

**Comment by smuzaffar** [comment]
can you see teams other teams which you are not member of e.g. https://github.com/orgs/cms-sw/teams/l1-l2 ?

**Comment by slava77** [comment]
I can see https://github.com/orgs/cms-sw/teams/l1-l2

**Comment by slava77** [comment]
my questions started after I couldn't tag generators in https://github.com/cms-sw/cmssw/issues/32356#issuecomment-762464596

**Comment by smuzaffar** [comment]
very strange, setting for both teams are identical and all member of cms-sw org should be able to see them

**Comment by smuzaffar** [comment]
try now, somehow the team was marked as secret. It should be fixed now.

**Comment by slava77** [comment]
> try now, somehow the team was marked as secret. It should be fixed now.

it works now.
Thank you.

**Comment by slava77** [comment]
@smuzaffar 
I wanted to give a try to github projects; we have https://github.com/orgs/cms-sw/teams/reconstruction-l2/projects but I apparently do not have permissions to create projects here. 
If the per-team projects are possible, it would be nice to get permissions.

**Comment by smuzaffar** [comment]
@slava77 , @makortel asked me about this last week but I could not find any time to look in to it. 
For now I have created reconstruction project https://github.com/orgs/cms-sw/projects and @cms-sw/reconstruction-l2  team should have admin rights there. Please check if you have correct right and if settings look good. Once we have a basic idea of settings then I will automate it and create one project per cmssw category.

**Comment by slava77** [comment]
> For now I have created reconstruction project https://github.com/orgs/cms-sw/projects

this is not quite the same, but I guess it's better than none.

Isn't the solution for the teams projects permissions to make the team member(s) to be maintainers?

**Comment by smuzaffar** [comment]
No, `maintainer` is a person who can maintain a team itself (e.g adding/removing members from team itself). The `project` belongs to `organization` or `user`. So only `organization` `owners` can create project and then can assign that project to a team.

**Comment by makortel** [comment]
> Once we have a basic idea of settings then I will automate it and create one project per cmssw category.

I have a feeling that different groups could have different needs, like some not needing a project at all and some needing to go to beyond a single project board. For example, my use case of framework would be a subset of `core`, and our current idea would utilize many project boards (1 + 1 per quarter), although this may evolve with more experience.

**Comment by smuzaffar** [comment]
closing it, it was just for information purpose
