### ISSUE TITLE
Possible issue with rawId() in GEMDetId 

### ISSUE THREAD

**Issue by dildick** [cms-sw/cmssw#30644]
In CMSSW_11_2_X_2020-07-09-1100, I notice the following. When you write:
```
unsigned rawId;
GEMDetId detId(rawId);
```
then ```rawId``` does not equal ```detId.rawId()```

Example, in a 2026D41 geometry the detid ```Re -1 Ri 1 St 1 La 2 Ch 10 Ro 1``` was instantiated with rawId 671189248, but detId.rawId() returns 688425248.

I should add that I was trying to run on a PhaseIITDRSpring19DR PU200 sample.

**Comment by makortel** [comment]
assign simulation, upgrade

**Comment by dildick** [comment]
@bsunanda Do you think this is due to the sample that I'm analyzing or is it an actual bug in the code?

**Comment by bsunanda** [comment]
@didick I shall check this. It is strange - do you have other examples?

**Comment by dildick** [comment]
No I don't I'm afraid. If there is a Run-3 matrix test with single muons, I could that and check it.

**Comment by dildick** [comment]
@bsunanda Were you able to reproduce the error?

**Comment by bsunanda** [comment]
@dildick Yes I understand the issue. This is mainly due to transition from 10_6 to 11_0. GEMDetId internal structure is modified to accommodate GE0. So there is an internal conversion code which changes rawId to match the  current format. The cell specified by (Re -1 Ri 1 St 1 La 2 Ch 10 Ro 1) is 688425248. In older format it was 671189248

**Comment by bsunanda** [comment]
I am submitting a new PR which tests the issue and adds some test code

**Comment by dildick** [comment]
This issue can be closed I think.

**Comment by makortel** [comment]
@dildick You should be able to close the issue (that you opened) yourself as well.

**Comment by bsunanda** [comment]
Please do
________________________________
