### ISSUE TITLE
EventSetup conditions fail using ESGetToken for a product that uses a Service

### ISSUE THREAD

**Issue by fwyzard** [cms-sw/cmssw#30669]
We are seeing an issue with the use of `ESGetToken` after migrating the Patatrack branch to CMSSW_11_2_X .

Some modules fail with an error like
```
----- Begin Fatal Exception 13-Jul-2020 19:11:32 CEST-----------------------
An exception of category 'NotFound' occurred while
   [0] Running EventSetup component SiPixelGainCalibrationForHLTGPUESProducer/'siPixelGainCalibrationForHLTGPU
Exception Message:
Service no ServiceRegistry has been set for this thread
----- End Fatal Exception -------------------------------------------------
```

A cursory investigation following a suggestion by @makortel suggests that this happens when an `ESGetToken` is used to access a product, produced by an ESProducers that accesses a Service (in our case likely the `CUDAService`) when the product is being produced.

**Comment by makortel** [comment]
assign core

**Comment by makortel** [comment]
The `CUDAService` gets called in the constructor of the ESProduct, that has `cms::cuda::ESProduct` member
https://github.com/cms-sw/cmssw/blob/692a8d52c9e0585796ecb7d806fd7b29c4b08429/HeterogeneousCore/CUDACore/interface/ESProduct.h#L21
https://github.com/cms-sw/cmssw/blob/692a8d52c9e0585796ecb7d806fd7b29c4b08429/HeterogeneousCore/CUDAServices/src/numberOfDevices.cc#L5-L10

**Comment by Dr15Jones** [comment]
#30688 should fix this. Thanks for the report.

**Comment by makortel** [comment]
+1

Fix has been merged
