### ISSUE TITLE
Memory consumption in DQM merge step

### ISSUE THREAD

**Issue by srimanob** [cms-sw/cmssw#30664]
Hi All,

Here is the summary of issues we have found so far on memory consumption in DQMMerge step.

+ All Phase-2 RelVals in 11_1_0 fail during DQM merge. After debugging, we see a big jump in memory consumption caused by ROOT 6.20 (*). 
   + Report to ROOT team: https://sft.its.cern.ch/jira/browse/ROOT-10927
   + We ask to revert ROOT back to 6.18 in CMSSW_11_1. @silviodonato prepares https://github.com/cms-sw/cmsdist/pull/6068
   + We may stay with ROOT620 for 11_2, hope ROOT team will come up with solution/fix very soon.

+ In addition, we random see failure in merging starting from CMSSW_11_1_0_pre5 (**). This seems to be clear the issue is not on ROOT620 only. Few points which may important
   + The failure is on Phase-2 only. Merging on Run-3 DQM relvals run successfully all the time.
   + Start to see failing in pre5
   + From (*), we also see memory increasing, maybe at the time when new files are added. Is this behaviour expected? The current CMSSW agents limit the PSS memory at 2.3 GB. From the plot it seems we can cross that point randomly, and job will fail if condor measures memory at that moment.

While we are waiting for ROOT team to deal with ROOT6.20/6.22, we may start to look on our side, Phase-2 validation.

(*)
<img width="800" alt="Screenshot 2020-07-13 19 10 09" src="https://user-images.githubusercontent.com/4701449/87332842-864b1a80-c53c-11ea-969a-5a4f326acb13.png">

(**)
% of complete merge
11_2_0_pre1: H125GG (82%), TenTau (72%),  NuGun (71%),  QCD_Pt15 (69%) and TTbar (52%)
11_1_0_pre8: QCD_Pt15To7000 (48%)
11_1_0_pre7_ROOT620: No information as issue with agents.
11_1_0_pre7: QCD_Pt15To7000 (85%), ZEE (78%), ZpTT( 89%)
11_1_0_pre6: NuGun (84%), QCD_Pt15To7000 (70%), ZpTT (86%)
11_1_0_pre5: ZpTT (87%)

**Comment by makortel** [comment]
assign core

**Comment by srimanob** [comment]
I am trying to understand why the issue happens in Phase-2 only by comparing DQMIO and merge in 11_2_0_pre1 (ROOT618)

Here is the result,
https://srimanob.web.cern.ch/DQM/mbGraph.html#?profile=performance-Run3.json&reference=performance-Phase2.json&pid=_sum

Light blue: Phase2
Dark blue: Run3

<img width="800" alt="Screenshot 2020-07-15 08 39 48" src="https://user-images.githubusercontent.com/4701449/87512131-c57d8680-c676-11ea-8da1-446d844b1a4a.png">

The memory jump (which should cause an issue if condor measure memory at that moment) happen in Phase-2 only. The merge config file which contains a list of DQMIO i used can be found at
/afs/cern.ch/user/s/srimanob/public/ForDQM/MemoryComparison/RunMergeCfg.py

**Comment by davidlange6** [comment]
This graphic potentially just says that phase2 has more histogram Bins than run3.


On 15 Jul 2020, at 08:41, Phat Srimanobhas <notifications@github.com> wrote:

﻿

I am trying to understand why the issue happens in Phase-2 only by comparing DQMIO and merge in 11_2_0_pre1 (ROOT618)

Here is the result,
https://srimanob.web.cern.ch/DQM/mbGraph.html#?profile=performance-Run3.json&reference=performance-Phase2.json&pid=_sum

Light blue: Phase2
Dark blue: Run3

[Screenshot 2020-07-15 08 39 48]<https://user-images.githubusercontent.com/4701449/87512131-c57d8680-c676-11ea-8da1-446d844b1a4a.png>

The memory jump (which should cause an issue if condor measure memory at that moment) happen in Phase-2 only. The merge config file which contains a list of DQMIO i used can be found at
/afs/cern.ch/user/s/srimanob/public/ForDQM/MemoryComparison/RunMergeCfg.py

**Comment by srimanob** [comment]
Hi @davidlange6 

Thanks for the comment.

The point I would like to make is that if we consider it's normal, we may need to consider raising memory allowance in DQM Merge permanently. Currently, we allow 2.3 GB, and Phase-2 relvals merge fail significantly.

**Comment by davidlange6** [comment]
Perhaps one should understand why that is. I guess DQM has tools that count bins by directory..

On Jul 15, 2020, at 9:28 AM, Phat Srimanobhas <notifications@github.com<mailto:notifications@github.com>> wrote:



Hi @davidlange6<https://github.com/davidlange6>

Thanks for the comment.

The point I would like to make is that if we consider it's normal, we may need to consider raising memory allowance in DQM Merge permanently. Currently, we allow 2.3 GB, and Phase-2 relvals merge fail significantly.

**Comment by silviodonato** [comment]
Fixed https://github.com/cms-sw/cmsdist/pull/6074
