### ISSUE TITLE
Igprof analysis of 11_1_0_p3_ROOT618 : trklet::TrackletEngineDisplaced::execute()

### ISSUE THREAD

**Issue by tommasoboccali** [cms-sw/cmssw#30744]
Dear all,
an igprof analysis of L1+RECO [here](https://dpiparo.web.cern.ch/dpiparo/cgi-bin/igprof-navigator/L1_Reco_tt_evt1.mp)

shows a large allocation (250MB) in

https://github.com/cms-sw/cmssw/blob/9010c72dccae06e78cb0ec045bc1c829cf1afd54/L1Trigger/TrackFindingTracklet/src/TrackletEngineDisplaced.cc#L99

direct link [HERE](https://dpiparo.web.cern.ch/dpiparo/cgi-bin/igprof-navigator/L1_Reco_tt_evt2.mp/105)

please have a look at whether this is meaningful.

cheers

**Comment by Dr15Jones** [comment]
The memory is being used for the member data `table_`
https://github.com/cms-sw/cmssw/blob/9010c72dccae06e78cb0ec045bc1c829cf1afd54/L1Trigger/TrackFindingTracklet/interface/TrackletEngineDisplaced.h#L44

with the allocations being various `resize` calls
https://github.com/cms-sw/cmssw/blob/9010c72dccae06e78cb0ec045bc1c829cf1afd54/L1Trigger/TrackFindingTracklet/src/TrackletEngineDisplaced.cc#L326-L336

and

https://github.com/cms-sw/cmssw/blob/9010c72dccae06e78cb0ec045bc1c829cf1afd54/L1Trigger/TrackFindingTracklet/src/TrackletEngineDisplaced.cc#L247-L256

and

https://github.com/cms-sw/cmssw/blob/9010c72dccae06e78cb0ec045bc1c829cf1afd54/L1Trigger/TrackFindingTracklet/src/TrackletEngineDisplaced.cc#L326-L336

Given that bit shifting is being used to calculate the index, it would be very easy to create an enormous value and thereby requesting a huge memory allocation.

**Comment by makortel** [comment]
assign l1,upgrade

**Comment by kpedro88** [comment]
@skinnari please take a look

**Comment by srimanob** [comment]
+Upgrade

**Comment by cecilecaillol** [comment]
+l1
