### ISSUE TITLE
Adding TTStubs, missing dictionary for collection "bitset<64>"

### ISSUE THREAD

**Issue by rekovic** [cms-sw/cmssw#30754]
I was trying to keep TTStubs which are created in the `L1TrackTrigger` when re-processing Phase-2 sample, 
```
cmsDriver.py step1 --conditions auto:phase2_realistic_T15 -n 2 --era Phase2C9 --eventcontent FEVTDEBUGHLT --runUnscheduled --filein file:/eos/cms/store/relval/CMSSW_11_0_0/RelValTTbar_14TeV/GEN-SIM-DIGI-RAW/PU25ns_110X_mcRun4_realistic_v3_2026D49PU200-v2/10000/01054EE2-1B51-C449-91A2-5202A60D16A3.root -s RAW2DIGI,L1TrackTrigger,L1 --datatier FEVTDEBUGHLT --customise SLHCUpgradeSimulations/Configuration/aging.customise_aging_1000,L1Trigger/Configuration/customisePhase2TTNoMC.customisePhase2TTNoMC,Configuration/DataProcessing/Utils.addMonitoring --geometry Extended2026D49 --fileout file:/tmp/rekovic/step1_keepAll.root --customise_command process.SimpleMemoryCheck = cms.Service('SimpleMemoryCheck',ignoreTotal = cms.untracked.int32(1)) --no_exec --nThreads 8 --python step1_L1_ProdLike_keepAll.py --customise_command process.FEVTDEBUGHLToutput.outputCommands.append('keep *_*_*_*')
```

but encountered issues with dictionary

`
The class "pair<edm::Ref<edmNew::DetSetVector<TTStub<edm::Ref<edm::DetSetVector<Phase2TrackerDigi>,Phase2TrackerDigi,edm::refhelper::FindForDetSetVector<Phase2TrackerDigi> > > >,TTStub<edm::Ref<edm::DetSetVector<Phase2TrackerDigi>,Phase2TrackerDigi,edm::refhelper::FindForDetSetVector<Phase2TrackerDigi> > >,edmNew::DetSetVector<TTStub<edm::Ref<edm::DetSetVector<Phase2TrackerDigi>,Phase2TrackerDigi,edm::refhelper::FindForDetSetVector<Phase2TrackerDigi> > > >::FindForDetSetVector>,bitset<64> >" is interpreted and for its data member "second" we do not have a dictionary for the collection "bitset<64>". Because of this, we will not be able to read or write this data member.
`

Tried fixing it, but did not work.
```

diff --git a/DataFormats/L1TrackTrigger/src/classes_def.xml b/DataFormats/L1TrackTrigger/src/classes_def.xml
index 48c4d162a39..366d17e1fd8 100644
--- a/DataFormats/L1TrackTrigger/src/classes_def.xml
+++ b/DataFormats/L1TrackTrigger/src/classes_def.xml
@@ -24,6 +24,8 @@
   <class name="std::vector<TTTrack_TrackWord>"/>
   <class name="edm::Wrapper<std::vector<TTTrack_TrackWord> >"/>
   <class name="edm::Ptr<TTTrack<edm::Ref<edm::DetSetVector<Phase2TrackerDigi>,Phase2TrackerDigi,edm::refhelper::FindForDetSetVector<Phase2TrackerDigi> > > >" />
+  <class name="edm::Ptr<TTCluster<edm::Ref<edm::DetSetVector<Phase2TrackerDigi>,Phase2TrackerDigi,edm::refhelper::FindForDetSetVector<Phase2TrackerDigi> > > >" />
+  <class name="edm::Ptr<TTStub<edm::Ref<edm::DetSetVector<Phase2TrackerDigi>,Phase2TrackerDigi,edm::refhelper::FindForDetSetVector<Phase2TrackerDigi> > > >" />
   <class name="TTDTC"/>
   <class name="edm::Wrapper<TTDTC>"/>
   <class name="TTDTC::Streams"/>
```

Any suggestions @makortel @kpedro88 ?

**Comment by makortel** [comment]
The error complains about `we do not have a dictionary for the collection "bitset<64>"`, which needs to be added here
https://github.com/cms-sw/cmssw/blob/517d3727e9894c7df0497f694fac0abd46a43fb6/DataFormats/StdDictionaries/src/classes_def_others.xml#L11-L12

**Comment by rekovic** [comment]
Thanks @makortel

**Comment by silviodonato** [comment]
Fixed https://github.com/cms-sw/cmssw/pull/30768
