### ISSUE TITLE
make using ESGetToken less verbose

### ISSUE THREAD

**Issue by fwyzard** [cms-sw/cmssw#30828]
It looks to me like an `ESGetToken` object already knows the types that need to be passed to `esConsumes<...>()`.

Why not add a simpler `ESGetToken` constructor that takes as argument only a pointer or reference to the module being constructed ?
So that a line like
```c++
      multifitParametersToken_{esConsumes<EcalMultifitParametersGPU, EcalMultifitParametersGPURecord>()},
```
could become
```c++
      multifitParametersToken_(*this)),
```
and the constructor could take care of calling the module's `sConsumes<T, R>()` with the right types ?

**Comment by fwyzard** [comment]
assign core

**Comment by fwyzard** [comment]
In fact, if such constructor were available, one could then just define the `ESGetToken` data members as
```c++
const edm::ESGetToken<EcalMultifitParametersGPU, EcalMultifitParametersGPURecord> multifitParametersToken_(*this);
```
and it wouldn't be necessary to initialise it explicitly in the constructor.

**Comment by makortel** [comment]
With `setConsumes()` your example would become
```cpp
class TestModule {
...
  TestModule(...) :
    ...
  {
    setConsumes(multifitParametersToken_);
  }

private:
  edm::ESGetToken<EcalMultifitParametersGPU, EcalMultifitParametersGPURecord> multifitParametersToken_;

  ...
```

@Dr15Jones came up with an idea that could allow something along
```cpp
lass TestModule {
...
  TestModule(...) :
    ...
    multifitParametersToken_{esConsumesAuto()}
  { }

private:
  edm::ESGetToken<EcalMultifitParametersGPU, EcalMultifitParametersGPURecord> multifitParametersToken_;

  ...
```
to work, or possibly even overloading the `esConsumes()`
```cpp
lass TestModule {
...
  TestModule(...) :
    ...
    multifitParametersToken_{esConsumes()}
  { }

private:
  edm::ESGetToken<EcalMultifitParametersGPU, EcalMultifitParametersGPURecord> multifitParametersToken_;

  ...
```
that would be much closer to the current consumes API.

We'll try if this idea can be made to work in practice. In the meanwhile I'll close #31209.

**Comment by Dr15Jones** [comment]
See #31223 as a working implementation.

**Comment by makortel** [comment]
+1
