### ISSUE TITLE
PFMuonAlgo configuration

### ISSUE THREAD

**Issue by guitargeek** [cms-sw/cmssw#30849]
The PFProducer tries to configure the PFMuonAlgo with the parameters of PFEgammaFilters:

https://github.com/cms-sw/cmssw/blob/master/RecoParticleFlow/PFProducer/plugins/PFProducer.cc#L352

In practice, this causes no problem *for the moment* because the PFMuonAlgo has its own default configuration hardcoded in the constructor in case no parameters are provided:

https://github.com/cms-sw/cmssw/blob/master/RecoParticleFlow/PFProducer/src/PFMuonAlgo.cc#L40

It would be better if the configuration parameters are removed from the constructor of PFMuonAlgo (after all it has its own `fillPSetDescription` function [1]), and if the PFProducer configures the PFMuonAlgo correctly.

[1] https://github.com/cms-sw/cmssw/blob/master/RecoParticleFlow/PFProducer/src/PFMuonAlgo.cc#L1038

**Comment by makortel** [comment]
assign reconstruction

**Comment by slava77** [comment]
@hatakeyamak @bendavid 
please take a note

**Comment by hatakeyamak** [comment]
I see the issue. I will fix this asap.

**Comment by hatakeyamak** [comment]
I think this will address the "bug" in PFProducer.
https://github.com/cms-sw/cmssw/compare
/master...hatakeyamak:PFProducerFixForPFMuonAlgoFillPSetDescription?expand=1

> It would be better if the configuration parameters are removed from the constructor of PFMuonAlgo (after all it has its own fillPSetDescription function), and if the PFProducer configures the PFMuonAlgo correctly.
This is a little involved, as PFMuonAlgo is also used in PFBlockProducer which doesn't use fillDescriptions and introducing fillDescriptions to PFBlockProducer is somewhat daunting.

After running some validation, I plan to make a PR based on the above fix.

**Comment by guitargeek** [comment]
Fixed by https://github.com/cms-sw/cmssw/pull/30936, thank you very much @hatakeyamak!
