### ISSUE TITLE
Fix compilation warning/error in FWCore/ParameterSetReader/interface/ParameterSetReader.h

### ISSUE THREAD

**Issue by veelken** [cms-sw/cmssw#30844]
Hi,

please remove the superfluous semicolon in line 
  https://github.com/cms-sw/cmssw/blob/master/FWCore/ParameterSetReader/interface/ParameterSetReader.h#L18
The presence of this semicolon violates the C++ syntax for namespaces ( https://en.cppreference.com/w/cpp/language/namespace ) and produces a compilation warning, which turns into an error in case code that includes this header files is compiled with the -Werror flag.

Thank you,

Christian

**Comment by makortel** [comment]
assign core

**Comment by makortel** [comment]
Thanks for reporting, fixed in #30846 

I'm left to wonder why none of our tools reported that.
