### ISSUE TITLE
Huge histograms in HGCAL Validation

### ISSUE THREAD

**Issue by schneiml** [cms-sw/cmssw#30853]
Recently, we experienced some problems with DQMIO merge jobs running out of memory on Phase2 workflows (various threads on this issue exist). These problems are caused by two histograms:
```
HGCAL/HGCalSimHitsV/HitValidation/heeRecVsSimZ
HGCAL/HGCalSimHitsV/HitValidation/hefRecVsSimZ
```

Booked here: https://github.com/cms-sw/cmssw/blob/master/Validation/HGCalValidation/plugins/HGCalHitValidation.cc#L156-L163

Each consuming a significant fraction of the total memory used by the affected jobs.

Those huge histograms also triggered the bug ROOT-10927 [1] which lead us to uncover this issue.

It would be highly appreciated if these histograms could be replaced by less memory-hungry ones.

@srimanob  FYI

[1] https://sft.its.cern.ch/jira/browse/ROOT-10927

**Comment by Dr15Jones** [comment]
assign dqm, upgrade

**Comment by srimanob** [comment]
FYI @bsunanda @rovere @hatakeyamak

**Comment by rovere** [comment]
@apsallid @lecriste 
would you mind taking a look and reducing the number of bins to a reasonable number?

**Comment by apsallid** [comment]
@bsunanda @rovere @schneiml Is reducing in half (e.g. 8200 to 4100) a good choice for all sides or more is needed? I don't know if this is a trial and error procedure.

**Comment by bsunanda** [comment]
The level of reduction should come from DQM and PPD convenors.
________________________________

**Comment by rovere** [comment]
@bsunanda the level or reduction should be derived from the usefulness and information that is supposed to be stored in the plots. If I were DQM convener, I'd refuse anything less than a factor 10 reduction in number of bins (for each axis). This is validation, not visualization.

**Comment by jfernan2** [comment]
@apsallid  at least factor 10 (or even 20 in line with the MEs for X and Y coordinates, unless Z is indeed as much as twice sensible) is requested yes, as @rovere pointed out, a factor 2 is totally insufficient. Please bear in mind the usual stats involved in a RelVal sample for validation and the stats you plan to get to populate those MEs.
As an example, for a TT 5k event RelVal:
https://tinyurl.com/yyrf53tx
 there are many plots *VsSimX/Y/Z which seem to appear empty, apart from the two spotted which simply crash.
Please reduce hefdzVsZ and heedzVsZ too to avoid similar problems in the future. Something greater than 1k bins is more than enough
Thanks

**Comment by schneiml** [comment]
The current version of these plots is so big that DQMGUI refuses to render them, as I suspected (the limit is 8MB IIRC, so somewhere around 1M-2M bins). 

In general, we don't really care about a few thousand bins here and there (and that gives plenty of room to add all sorts of plots), but once it gets to millions of bins, memory consumption really starts to matter (no matter if it is in one huge plot or many small ones).

As Javi wrote, there are a bunch of other questionably large histograms, but those two really seriously stand out.

**Comment by jfernan2** [comment]
Plots are now rendered in Jenkins tests of #30879

**Comment by kpedro88** [comment]
Has this been improved sufficiently to close the issue?

**Comment by apsallid** [comment]
I see that the plots are shown now in the DQM GUI in the latest RelVals with the ongoing 11_2_0_pre5_phase2 campaign. I don't know if the reduction in memory is sufficient from DQM side. 

@kpedro88 @jfernan2

**Comment by rovere** [comment]
Ciao @kpedro88 
I consider the issue as solved.

**Comment by jfernan2** [comment]
Hi, from DQM side the solution is sufficient

**Comment by kpedro88** [comment]
+upgrade

**Comment by jfernan2** [comment]
+1

**Comment by jfernan2** [comment]
This issue can be closed IMHO
