### ISSUE TITLE
Uninitialized edm::Handle does not throw when dereferenced

### ISSUE THREAD

**Issue by Dr15Jones** [cms-sw/cmssw#30915]
The following code does not throw
```C++
edm::Hande<Foo> hFoo;
*hFoo;
```

This is because the exception factory is not set when constructing a defaultly constructed handle and only the presence of a factory is used to cause the exception. We have two possible fixes

1. Have a shared factory which is used by all defaultly constructed Handles of a given type
2. When dereferencing a Handle, we also check if the product is null and throw directly from their

At the moment I'm leaning towards 2. since we would not need the per type memory for all those factories in every job.

NOTE: this was found when I looked at an UBSAN report of the Handle assigning a nullptr to a reference.

**Comment by Dr15Jones** [comment]
assign core

**Comment by makortel** [comment]
I'm leaning towards option 2 as well.

**Comment by smuzaffar** [comment]
@Dr15Jones , was this fixed/implemented ?

**Comment by makortel** [comment]
+core

**Comment by makortel** [comment]
@cmsbuild, please close
