### ISSUE TITLE
Simpler syntax for fillDescriptions items with limited choices

### ISSUE THREAD

**Issue by kpedro88** [cms-sw/cmssw#30932]
I recently learned (in review of #30850) that fillDescriptions can restrict the allowed choices for a configuration parameter using `ifValue()`. However, the syntax for this is currently a bit clunky:
```cpp
  desc.ifValue(edm::ParameterDescription<std::string>("mode", "PseudoAsync", true),
      "Sync" >> edm::EmptyGroupDescription() or
      "Async" >> edm::EmptyGroupDescription() or
      "PseudoAsync" >> edm::EmptyGroupDescription());
```

This syntax is intended to allow for switching between more complex parameter groups. However, in the case of a simple choice (such as above), it would be nice to have a simpler syntax. For example, the allowed choices could just be provided as a vector.

**Comment by kpedro88** [comment]
assign core

**Comment by makortel** [comment]
Here is an earlier discussion on the topic https://hypernews.cern.ch/HyperNews/CMS/get/progQuestions/331.html

**Comment by Dr15Jones** [comment]
How about
```C++
desc.ifValue(edm::ParameterDescription<std::string>("mode", "PseudoAsync", true),
             edm::allowedValues("Sync", "Async", "PseudoAsync"));
```
?

In a quick test I was able to make that work. All it needed was the new templated function `edm::allowedValues` which does exactly what your earlier code did but behind the scenes.

**Comment by kpedro88** [comment]
That looks good to me.

**Comment by makortel** [comment]
@Dr15Jones How necessary the `desc.ifValue()` is? (for a quick solution it probably is)

I'm just wondering if we should think about a more general mechanism to specify constraints on allowed values.

**Comment by Dr15Jones** [comment]
See #30950

**Comment by makortel** [comment]
+1

Done in #30950
