### ISSUE TITLE
Revise implementation of DDShapes

### ISSUE THREAD

**Issue by cvuosalo** [cms-sw/cmssw#30964]
The implementation of some of the shapes  declared in `DetectorDescription/DDCMS/interface/DDShapes.h` can be improved. `DDBox, DDCons, DDTrap, DDTubs`, and `DDTruncTubs` could be implemented in the manner of `DDPolycone` or even more simply as type aliases in some cases. See the comments in #30931 for suggestions.

This change in implementation would have only negligible effects on cpu and memory performance but would eliminate unnecessary data members and would enhance maintainability of the code.

**Comment by cvuosalo** [comment]
assign geometry

**Comment by ianna** [comment]
@cvuosalo - IMHO, a type alias and a function alias using perfect forwarding would remove any need to have these classes in CMSSW

**Comment by cvuosalo** [comment]
This issue is no longer relevant. When the shape accessors appear in the DD4hep release, we will need a new issue for adopting the new interface.

**Comment by cvuosalo** [comment]
-1
