### ISSUE TITLE
Use [[deprecated]] to mark deprecated classes and functions

### ISSUE THREAD

**Issue by Dr15Jones** [cms-sw/cmssw#31021]
Both gcc 8.3+ and clang 9+ support the attrbute [[deprecated]]. We could use this to
- mark the legacy EDFilter, EDProducer, and EDAnalyzer legacy classes
- mark the EventSetupRecord::get calls which do not use an ESGetToken

These would likely generate a large number of warnings at first but would at least force pull requests to not use the deprecated items.

**Comment by Dr15Jones** [comment]
assign core

**Comment by Dr15Jones** [comment]
In order to avoid flooding the IBs with warnings, we could wrap the use of [[deprecated]] in a macro and make sure the macro is off during the IB builds but on during the pull request tests and when people build locally.

**Comment by makortel** [comment]
Being able to ignore these warnings in IBs is (also?) my main concern. In PR tests, what about code in files not touched by the PR? If we manage to ignore those, this would effectively mean that any change in an "offending" file would require a migration away (which could be ok, but would require a policy discussion first I suppose).

**Comment by makortel** [comment]
+1

This has been implemented.
