### ISSUE TITLE
repeated AK8PuppiSoftDrop ecfN data in slimmedJetsAK8

### ISSUE THREAD

**Issue by slava77** [cms-sw/cmssw#31052]
in regular miniAOD (both in 106X and 112X) we have duplicate values of userFloats in slimmedJetsAK8 appearing with different names, eg. :
- ak8PFJetsPuppiSoftDropValueMap:nb1AK8PuppiSoftDropN2
    - this comes via ak8PFJetsPuppiSoftDropValueMap , inserted in patJetsAK8Puppi 
- nb1AK8PuppiSoftDrop:ecfN2
    - this comes via patJetsAK8PFPuppiSoftDrop, inserted in packedPatJetsAK8

Notably, the former is always present in the jets, while the latter is added only in some jets (where a matching SoftDrop is available?).

one of these should be removed 
@ahinzmann  @camclean @alefisico
please check and comment if this can be addressed soon.
Thank you.

**Comment by slava77** [comment]
assign reconstruction,xpog

**Comment by ahinzmann** [comment]
I think one of them can be dropped.
@camclean @alefisico @rappoccio Can you comment which of the two is commonly used by analyses?

**Comment by alefisico** [comment]
I assume that the first one:
`ak8PFJetsPuppiSoftDropValueMap:nb1AK8PuppiSoftDropN2`
is the most commonly used, just because it is the only one described in the [miniAOD twiki](https://twiki.cern.ch/twiki/bin/view/CMSPublic/WorkBookMiniAOD2017#Jets).

**Comment by ahinzmann** [comment]
Ok, so this duplicate is mainly there to keep backward compatibility. I suggest to break it for Run3 and keep only the variable nb1AK8PuppiSoftDrop:ecfN2 (and update the TWiki accordingly)

**Comment by rappoccio** [comment]
Yes, this was done for backwards compatibility. We need to only keep `nb1AK8PuppiSoftDrop:ecfN2`.
