### ISSUE TITLE
Very confusion when new Phase-2 L1T paths show up in Run-2 config

### ISSUE THREAD

**Issue by srimanob** [cms-sw/cmssw#31054]
Dumping python config of Run-2, i.e. from runTheMatrix
`runTheMatrix.py --what upgrade -l 10825.0 -t 8 -b 'PHATTEST_R2112' --label 'PHATTEST_R2112' --wm init`
shows that in the L1 step, some paths which should not belong to Run-2 appears in the config.

```
cmsDriver.py step2 --conditions auto:phase1_2018_realistic -s DIGI:pdigi_valid,L1,DIGI2RAW,HLT:@relval2018 --datatier GEN-SIM-DIGI-RAW -n 10 --geometry DB:Extended --era Run2_2018 --ev
entcontent FEVTDEBUGHLT --io DigiFull_2018.io --python DigiFull_2018.py --no_exec --filein file:step1.root --fileout file:step2.root --nThreads 8
```
gives
```
# Path and EndPath definitions
process.digitisation_step = cms.Path(process.pdigi_valid)
process.pL1TkPrimaryVertex = cms.Path(process.L1TkPrimaryVertex)
process.pL1TkPhotonsCrystal = cms.Path(process.L1TkPhotonsCrystal)
process.pL1TkIsoElectronsCrystal = cms.Path(process.L1TkIsoElectronsCrystal)
process.pL1TkElectronsLooseCrystal = cms.Path(process.L1TkElectronsLooseCrystal)
process.pL1TkElectronsHGC = cms.Path(process.L1TkElectronsHGC)
process.pL1TkMuon = cms.Path(process.L1TkMuons+process.L1TkMuonsTP)
process.pL1TkElectronsLooseHGC = cms.Path(process.L1TkElectronsLooseHGC)
process.pL1TkElectronsEllipticMatchHGC = cms.Path(process.L1TkElectronsEllipticMatchHGC)
process.pL1TkElectronsCrystal = cms.Path(process.L1TkElectronsCrystal)
process.pL1TkPhotonsHGC = cms.Path(process.L1TkPhotonsHGC)
process.pL1TkIsoElectronsHGC = cms.Path(process.L1TkIsoElectronsHGC)
process.pL1TkElectronsEllipticMatchCrystal = cms.Path(process.L1TkElectronsEllipticMatchCrystal)
process.L1simulation_step = cms.Path(process.SimL1Emulator)
process.digi2raw_step = cms.Path(process.DigiToRaw)
process.endjob_step = cms.EndPath(process.endOfProcess)
process.FEVTDEBUGHLToutput_step = cms.EndPath(process.FEVTDEBUGHLToutput)
```

I understand for the schedule that those pL1Tk will not run,
`process.schedule = cms.Schedule(process.digitisation_step,process.L1simulation_step,process.digi2raw_step)`
but better if they do not show up. 

Should we make more clean config?

**Comment by silviodonato** [comment]
assign upgrade

**Comment by silviodonato** [comment]
assign pdmv

**Comment by srimanob** [comment]
Hi @silviodonato @rekovic 

I used to comment before when we check HLT TDR cmsDriver that those paths defined in
https://github.com/cms-sw/cmssw/blob/master/L1Trigger/L1TTrackMatch/python/L1TkObjectProducers_cff.py

However, they are never called, e.g. from 
https://github.com/cms-sw/cmssw/blob/master/L1Trigger/Configuration/python/SimL1Emulator_cff.py

Possible to clean up from L1T side?

**Comment by chayanit** [comment]
Hi @silviodonato , could you replace @pgunnell with @jordan-martins in PdmV?

**Comment by silviodonato** [comment]
Hi @srimanob,
I don't know the reason of the definition of those paths. Perhaps, they were made for debugging. I will prepare a PR to remove them. @rekovic do you know the reason of those paths?

**Comment by silviodonato** [comment]
See https://github.com/cms-sw/cmssw/pull/31057

**Comment by kpedro88** [comment]
+upgrade

**Comment by chayanit** [comment]
+1
