### ISSUE TITLE
Pending Tasks on SimTracker/TrackerMaterialAnalysis 

### ISSUE THREAD

**Issue by vargasa** [cms-sw/cmssw#31068]
Present Issue serves as a way to keep track of work needed on the `SimTracker/TrackerMaterialAnalysis`

In its current form `CMSSW_11_2_X_2020-07-21-1100` the `SimTracker/TrackerMaterialAnalysis` is throwing the following:

- [ ] Multiple errors coming from https://github.com/cms-sw/cmssw/blob/503f8053329b5587411ab9607f14955428587ccf/SimTracker/TrackerMaterialAnalysis/plugins/TrackingMaterialAnalyser.cc#L347

```
TrackingMaterialAnalyser::findLayer(...): ERROR: detector does not belong to any DetLayer
TrackingMaterialAnalyser::findLayer(...): detector position:  (r: 117.6, z: -236.0, phi: -2.116)
```

- [x]  `GeometryExtended2026D41Reco` from https://github.com/cms-sw/cmssw/blob/master/SimTracker/TrackerMaterialAnalysis/test/trackingMaterialAnalyser_ForPhaseII.py#L19 is not available anymore. We need to somehow figure out a way to flag future problems in the PRs directly if Geometry files are deleted/renamed

- [ ] Some of the present tests are not functional: https://github.com/cms-sw/cmssw/blob/master/SimTracker/TrackerMaterialAnalysis/test/listIds.py, if they're no longer needed they should be removed. The question would be, which ones are needed?

- [x] By setting to true the `SaveDetailedPlots` option: https://github.com/cms-sw/cmssw/blob/master/SimTracker/TrackerMaterialAnalysis/test/trackingMaterialAnalyser_ForPhaseII.py#L31 the group-wise histograms provided by the module are empty. This is probably related with a mismatching between SpecPars and the Scenario used

- [ ] A brief `README.md` is needed

- [x] A unit test would be good to have

- [ ] If package is used by different subdetectors we should probably remove Tracker from its name. @ianna suggested to move this package to `BigProducts`

- [ ] These issues need to be addressed to fully validate the dd4hep migration of the package

##### DD4hep

- [ ]  test: `GeometryDD4hepExtended2026Reco_cff.py` is not available, yet. Pending addition to dd4hep test
- [ ]  SpecPars currently conflicting

##### How to reproduce?

```
$cmsRun trackingMaterialProducer10GeVNeutrino_ForPhaseII.py
$cmsRun trackingMaterialAnalyser_ForPhaseII.py
```
##### Associated twiki

https://twiki.cern.ch/twiki/bin/viewauth/CMS/TrackingPOGRecoMaterialFromGeometry

FYI: @mtosi @mmusich @rbartek

**Comment by makortel** [comment]
assign simulation, geometry

**Comment by mmusich** [comment]
@vargasa 

> GeometryExtended2026D41Reco from https://github.com/cms-sw/cmssw/blob/master/SimTracker/TrackerMaterialAnalysis/test/trackingMaterialAnalyser_ForPhaseII.py#L19 is not available anymore. We need to somehow figure out a way to flag future problems in the PRs directly if Geometry files are deleted/renamed

I am adding @emiglior since he was the last person to change that in PR https://github.com/cms-sw/cmssw/pull/27661.
As for checking if that file is functional (as well as all the others in that package) I would simply add a unit test, we are doing it in many other packages and the mechanism has served well so far.

**Comment by civanch** [comment]
+1
