### ISSUE TITLE
AllStepsToTree Option Failing on Validation/Geometry

### ISSUE THREAD

**Issue by vargasa** [cms-sw/cmssw#31069]
By setting `AllStepsToTree` to true on https://github.com/cms-sw/cmssw/blob/master/Validation/Geometry/test/runP_Tracker.py#L129 the module crashes.

The TTree's branches are reserved here https://github.com/cms-sw/cmssw/blob/master/Validation/Geometry/src/MaterialBudgetTree.cc#L15 and filled in the same class with data coming from `MaterialBudgetData.cc`.

When `AllStepsToTree` is set to false (default), the code branch filling is not executed and therefore no crash is seen: https://github.com/cms-sw/cmssw/blob/master/Validation/Geometry/src/MaterialBudgetTree.cc#L29

##### How to reproduce?
```
cmsRun test/single_neutrino_cfg.py nEvents=1000
cmsRun test/runP_Tracker.py geom="Extended2017Plan1" label=Tracker 
```
See https://github.com/cms-sw/cmssw/blob/master/Validation/Geometry/test/genTrackerPlots.sh

**Comment by makortel** [comment]
assign dqm,geometry

**Comment by jfernan2** [comment]
In CMSSW_12_2_0_pre3 the error now is different:

cmsRun test/runP_Tracker.py geom="Extended2017Plan1" label=Tracker
----- Begin Fatal Exception 13-Dec-2021 09:23:13 CET-----------------------
An exception of category 'ConfigFileReadError' occurred while
   [0] Processing the python configuration file named test/runP_Tracker.py
Exception Message:
 unknown python problem occurred.
RuntimeError: An exception of category 'PluginManagerReconfigured' occurred.


At:
  /cvmfs/cms.cern.ch/slc7_amd64_gcc900/cms/cmssw/CMSSW_12_2_0_pre3/python/FWCore/PythonFramework/CmsRun.py(10): __init__
  test/runP_Tracker.py(140): <module>

----- End Fatal Exception ----------------------------------------------

**Comment by cvuosalo** [comment]
Note the correct way to run the script is:
```
cmsRun test/single_neutrino_cfg.py nEvents=1000
python3 test/runP_Tracker.py geom="Extended2017Plan1" label=Tracker 
```
Running `runP_Tracker.py` with `cmsRun` causes the exception seen by @jfernan2.

**Comment by cvuosalo** [comment]
This issue is resolved by #37095.

**Comment by jfernan2** [comment]
Thanks @cvuosalo

**Comment by jfernan2** [comment]
+1

**Comment by cvuosalo** [comment]
+1

**Comment by cvuosalo** [comment]
This issue has been resolved. It can be closed.
