### ISSUE TITLE
Extended 2026 D41 Reco scenario now deprecated

### ISSUE THREAD

**Issue by vargasa** [cms-sw/cmssw#31081]
`D41` is now deprecated, see https://github.com/cms-sw/cmssw/commit/44ce8eb935fb9d47f388994d9692dce8d7d7da07#diff-67340df274822cfd075708d5be080594

The following list of `files:nLine:line` still make reference to it

```
CalibCalorimetry/HcalPlugins/test/hbhedarkeninganalyzer_cfg.py:10:#process.load("Configuration.Geometry.GeometryExtended2026D41Reco_cff")
Geometry/HGCalGeometry/test/python/hgcGeomAnalyzer_cfg.py:17:    process.load('Configuration.Geometry.GeometryExtended2026D41Reco_cff')
Geometry/HGCalGeometry/test/python/testHGCalGeomLocator_cfg.py:6:process.load("Configuration.Geometry.GeometryExtended2026D41Reco_cff")
Geometry/HGCalGeometry/test/python/testHGCalGeometryCheck_cfg.py:11:process.load('Configuration.Geometry.GeometryExtended2026D41Reco_cff')
Geometry/HGCalGeometry/test/python/testHGCalGeometry_cfg.py:6:process.load("Configuration.Geometry.GeometryExtended2026D41Reco_cff")
Geometry/HGCalGeometry/test/python/testHGCalRecHitTool_cfg.py:8:#process.load("Configuration.Geometry.GeometryExtended2026D41Reco_cff")
Geometry/HcalCommonData/test/python/runHcalRecNumberingTester_cfg.py:4:process.load('Configuration.Geometry.GeometryExtended2026D41Reco_cff')
L1Trigger/DTTriggerPhase2/test/test_primitivesPhase2Prod_over_dTDigis_and_4Dsegments_cfg.py:5:process.load('Configuration.Geometry.GeometryExtended2026D41Reco_cff')
L1Trigger/L1THGCal/test/testHGCalL1TGeometryV10Imp1_cfg.py:13:process.load('Configuration.Geometry.GeometryExtended2026D41Reco_cff')
L1Trigger/L1THGCal/test/testHGCalL1TGeometryV10Imp2_cfg.py:13:process.load('Configuration.Geometry.GeometryExtended2026D41Reco_cff')
L1Trigger/L1THGCalUtilities/test/testHGCalL1T_RelValV10_cfg.py:12:process.load('Configuration.Geometry.GeometryExtended2026D41Reco_cff')
RecoTauTag/RecoTau/test/rerunMVAIsolationOnMiniAOD_Phase2.py:5:process.load('Configuration.Geometry.GeometryExtended2026D41Reco_cff')
SimCalorimetry/HGCalSimAlgos/test/hgchebacksignalscaler_cfg.py:16:process.load('Configuration.Geometry.GeometryExtended2026D41Reco_cff')
SimTracker/TrackerMaterialAnalysis/test/listGroups.py:20:    process.load('Configuration.Geometry.GeometryExtended2026D41Reco_cff')
SimTracker/TrackerMaterialAnalysis/test/listIds_PhaseII.py:10:  process.load('Configuration.Geometry.GeometryExtended2026D41Reco_cff')
Validation/HGCalValidation/test/python/runHGCGeomCheck_cfg.py:11:process.load('Configuration.Geometry.GeometryExtended2026D41Reco_cff')
Validation/HGCalValidation/test/python/runHGCHitAnalyzer_cfg.py:11:process.load('Configuration.Geometry.GeometryExtended2026D41Reco_cff')
Validation/HGCalValidation/test/python/runHGCalDigiStudy_cfg.py:11:process.load('Configuration.Geometry.GeometryExtended2026D41Reco_cff')
Validation/HGCalValidation/test/python/runHGCalHitCalibration_cfg.py:12:process.load('Configuration.Geometry.GeometryExtended2026D41Reco_cff')
Validation/HGCalValidation/test/python/runHGCalRecHitStudy_cfg.py:12:process.load('Configuration.Geometry.GeometryExtended2026D41Reco_cff')
Validation/HGCalValidation/test/python/runHGCalSimHitStudy_cfg.py:11:process.load('Configuration.Geometry.GeometryExtended2026D41Reco_cff')
Validation/HGCalValidation/test/python/runHGCalWaferStudy_cfg.py:11:process.load('Configuration.Geometry.GeometryExtended2026D41Reco_cff')
Validation/HGCalValidation/test/python/testHGCalBHValid_cfg.py:12:process.load('Configuration.Geometry.GeometryExtended2026D41Reco_cff')
Validation/HGCalValidation/test/python/testHGCalSimHitStudy_cfg.py:11:process.load('Configuration.Geometry.GeometryExtended2026D41Reco_cff')
Validation/HGCalValidation/test/python/testHGCalSimWatcherV10_cfg.py:12:process.load('Configuration.Geometry.GeometryExtended2026D41Reco_cff')

```

**Comment by makortel** [comment]
assign geometry, upgrade, alca, l1, reconstruction, simulation, dqm

**Comment by kpedro88** [comment]
-1
test configs are not supported in general
if users/developers want them to be supported, they should make actual unit tests

**Comment by perrotta** [comment]
@mbluj @swozniewski please notice that there is a Tau test config which still loads the deprecated Extended 2026 D41 scenario: `RecoTauTag/RecoTau/test/rerunMVAIsolationOnMiniAOD_Phase2.py`
Test configs will not be dealt with centrally by reco, but you are invited to either update or remove it

**Comment by mbluj** [comment]
> 
> 
> @mbluj @swozniewski please notice that there is a Tau test config which still loads the deprecated Extended 2026 D41 scenario: `RecoTauTag/RecoTau/test/rerunMVAIsolationOnMiniAOD_Phase2.py`
> Test configs will not be dealt with centrally by reco, but you are invited to either update or remove it

Thank you for notifying us. We will update this test configuration to newer scenario. Tested tauID should be quite robust against changes of scenarios. Is there a recommended scenario to replace D41 one?

**Comment by perrotta** [comment]
> Thank you for notifying us. We will update this test configuration to newer scenario. Tested tauID should be quite robust against changes of scenarios. Is there a recommended scenario to replace D41 one?

Thank you @mbluj 
D49 is the current "replacement" of D41

**Comment by christopheralanwest** [comment]
@kpedro88 Among the list of affected files, the only one within the AlCa domain is a single commented line in your config `CalibCalorimetry/HcalPlugins/test/hbhedarkeninganalyzer_cfg.py`. Could you recommend whether the line should be updated or deleted?

**Comment by kpedro88** [comment]
@christopheralanwest if you're going to make a PR, it would be better to update the commented line. However, as I remark roughly once/week, I strongly encourage everyone to ignore configs in test directories that aren't explicitly unit tested. (This even applies to configs that I created.)

**Comment by perrotta** [comment]
+1
- The only reco-related file in the list got just merged in the master with #31349 (where the test config was also included in the unit tests)

**Comment by christopheralanwest** [comment]
+alca

- The only file under the AlCa domain was modified in the recently merged #31412

**Comment by jfernan2** [comment]
For DQM (Validation package) it has been removed for all Validation/HGCalValidation/test/python/* in merged PR
https://github.com/cms-sw/cmssw/pull/31767
except 
Validation/HGCalValidation/test/python/testHGCalSimWatcherV10_cfg.py
L11:process.load('Configuration.Geometry.GeometryExtended2026D41Reco_cff')
L12:process.load('Configuration.Geometry.GeometryExtended2026D41_cff')
FYI: @bsunanda

**Comment by civanch** [comment]
@vargasa , likely this PR should be closed?

**Comment by civanch** [comment]
+1

**Comment by civanch** [comment]
@qliphy, @perrotta , this issue is not relevant anymore, can you, please, close it?

**Comment by jfernan2** [comment]
+1
