### ISSUE TITLE
[DD4hep] CMS Overlaps

### ISSUE THREAD

**Issue by vargasa** [cms-sw/cmssw#31182]
Overlaps currently present within `OCMS_1`

##### How to reproduce?

Check: https://github.com/cms-sw/cmssw/pull/31181

Here's the full log: `$grep detected /afs/cern.ch/user/s/slomeo/public/Overlaps/overlaps.out| sort --unique`

##### Edit:
* List has been updated after https://github.com/cms-sw/cmssw/pull/31434

```
          Overlap is detected for volume Bottom_Wall_1:1 (G4SubtractionSolid)
          Overlap is detected for volume BumpBond_1:1 (G4Box)
          Overlap is detected for volume BumpBond_2:2 (G4Box)
          Overlap is detected for volume BumpBond_3:3 (G4Box)
          Overlap is detected for volume BumpBond_4:4 (G4Box)
          Overlap is detected for volume BumpBond_5:5 (G4Box)
          Overlap is detected for volume BumpBond_6:6 (G4Box)
          Overlap is detected for volume CTPPS_Diamond_Main_Box_1:1 (G4UnionSolid)
          Overlap is detected for volume CTPPS_Diamond_Plane_1:1 (G4Box)
          Overlap is detected for volume CTPPS_Diamond_Plane_2:2 (G4Box)
          Overlap is detected for volume CTPPS_Diamond_Plane_3:3 (G4Box)
          Overlap is detected for volume CTPPS_Diamond_Plane_4:4 (G4Box)
          Overlap is detected for volume ebalgo:ESPM_10:10 (G4SubtractionSolid)
          Overlap is detected for volume ebalgo:ESPM_11:11 (G4SubtractionSolid)
          Overlap is detected for volume ebalgo:ESPM_1:1 (G4SubtractionSolid)
          Overlap is detected for volume ebalgo:ESPM_12:12 (G4SubtractionSolid)
          Overlap is detected for volume ebalgo:ESPM_13:13 (G4SubtractionSolid)
          Overlap is detected for volume ebalgo:ESPM_14:14 (G4SubtractionSolid)
          Overlap is detected for volume ebalgo:ESPM_15:15 (G4SubtractionSolid)
          Overlap is detected for volume ebalgo:ESPM_16:16 (G4SubtractionSolid)
          Overlap is detected for volume ebalgo:ESPM_17:17 (G4SubtractionSolid)
          Overlap is detected for volume ebalgo:ESPM_18:18 (G4SubtractionSolid)
          Overlap is detected for volume ebalgo:ESPM_19:19 (G4SubtractionSolid)
          Overlap is detected for volume ebalgo:ESPM_20:20 (G4SubtractionSolid)
          Overlap is detected for volume ebalgo:ESPM_21:21 (G4SubtractionSolid)
          Overlap is detected for volume ebalgo:ESPM_22:22 (G4SubtractionSolid)
          Overlap is detected for volume ebalgo:ESPM_2:2 (G4SubtractionSolid)
          Overlap is detected for volume ebalgo:ESPM_23:23 (G4SubtractionSolid)
          Overlap is detected for volume ebalgo:ESPM_24:24 (G4SubtractionSolid)
          Overlap is detected for volume ebalgo:ESPM_25:25 (G4SubtractionSolid)
          Overlap is detected for volume ebalgo:ESPM_26:26 (G4SubtractionSolid)
          Overlap is detected for volume ebalgo:ESPM_27:27 (G4SubtractionSolid)
          Overlap is detected for volume ebalgo:ESPM_28:28 (G4SubtractionSolid)
          Overlap is detected for volume ebalgo:ESPM_29:29 (G4SubtractionSolid)
          Overlap is detected for volume ebalgo:ESPM_30:30 (G4SubtractionSolid)
          Overlap is detected for volume ebalgo:ESPM_31:31 (G4SubtractionSolid)
          Overlap is detected for volume ebalgo:ESPM_32:32 (G4SubtractionSolid)
          Overlap is detected for volume ebalgo:ESPM_33:33 (G4SubtractionSolid)
          Overlap is detected for volume ebalgo:ESPM_3:3 (G4SubtractionSolid)
          Overlap is detected for volume ebalgo:ESPM_34:34 (G4SubtractionSolid)
          Overlap is detected for volume ebalgo:ESPM_35:35 (G4SubtractionSolid)
          Overlap is detected for volume ebalgo:ESPM_36:36 (G4SubtractionSolid)
          Overlap is detected for volume ebalgo:ESPM_4:4 (G4SubtractionSolid)
          Overlap is detected for volume ebalgo:ESPM_5:5 (G4SubtractionSolid)
          Overlap is detected for volume ebalgo:ESPM_6:6 (G4SubtractionSolid)
          Overlap is detected for volume ebalgo:ESPM_7:7 (G4SubtractionSolid)
          Overlap is detected for volume ebalgo:ESPM_8:8 (G4SubtractionSolid)
          Overlap is detected for volume ebalgo:ESPM_9:9 (G4SubtractionSolid)
          Overlap is detected for volume EHAWR_1:1 (G4SubtractionSolid)
          Overlap is detected for volume EHAWR_2:2 (G4SubtractionSolid)
          Overlap is detected for volume esalgo:SFAbs1PbLinPb_1:1 (G4SubtractionSolid)
          Overlap is detected for volume esalgo:SFAbs1PbLOutAl_1:1 (G4SubtractionSolid)
          Overlap is detected for volume esalgo:SFAbs2PbLinPb_1:1 (G4SubtractionSolid)
          Overlap is detected for volume esalgo:SFAbs2PbLOutAl_1:1 (G4SubtractionSolid)
          Overlap is detected for volume RP_210_Left_Station_1:1 (G4Tubs)
          Overlap is detected for volume RP_210_Right_Station_1:1 (G4Tubs)
          Overlap is detected for volume RP_220_Left_Station_1:1 (G4Tubs)
          Overlap is detected for volume RP_220_Right_Station_1:1 (G4Tubs)
```

@civanch given https://github.com/cms-sw/cmssw/issues/31143#issuecomment-675516812 can you tell us which ones can be ignored?

**Comment by civanch** [comment]
@vargasa , this likely problem of DD4Hep. In DDD we have overlaps but they do not make real problem for simulation.

**Comment by makortel** [comment]
assign geometry

**Comment by vargasa** [comment]
@cvuosalo, @slomeo, @bsunanda. FYI: `YB*` volumes are part of the muon system and `EHAWR*` are part of ecal

**Comment by slomeo** [comment]
@vargasa I'll check them, following the commands present in #31181, after that PR #31043 will be merged. @cvuosalo @bsunanda @ianna @civanch  : Last year I fixed all YB* (i.e not active volumes) overlaps seen by "cmsShow -c overlaps.fwc --sim-geom-file cmsSimGeom.root" (i.e not dd4hep version) so I think that these overlaps are related to dd4hep position alghorithms (i.e not xml code) as @vargasa has found in #31181 for Tracker

**Comment by vargasa** [comment]
Here's the full log: https://drive.google.com/file/d/1DY_tK7z_cCNuDVK_ynMiSt67fn5sFMkA/view

**Comment by slomeo** [comment]
@bsunanda : I followed what @vargas made in #31181 to search overlaps:

1) In CMSSW_11_2_X_2020-08-31-2300  I run "cmsRun DetectorDescription/DDCMS/test/python/testGeometry2021.py " that created cmsDD4HepGeom.root
2) Then I run "cmsShow.exe -c overlaps.fwc --sim-geom-file cmsDD4HepGeom.root --tgeo-name=CMS"

I found 100 overlaps.
Then I looked into the MUON system and you can see the results in the attached picture.

MBTail and MBBC are defined in https://cmssdt.cern.ch/lxr/source/Geometry/HcalCommonData/data/hcalouteralgo.xml and not in muon xml files. Am I correct?

Now I'll use SimG4Core/PrintGeomInfo/test/python/g4OverlapCheckDD4Hep_cfg.py script to see YB* overlaps because as @vargasa said cmsShow is not able to find them.

![Schermata 2020-09-01 alle 13 37 47](https://user-images.githubusercontent.com/28751695/91846287-71485900-ec5a-11ea-8f8d-7586f7951f1c.png)

**Comment by bsunanda** [comment]
Hi Sergio

You are right - I remember MBBC in hcalouteralgo.xml. From the name MBTail also sounds to be in the tailcatcher geometry. But I would prefer the G4 checkoverlap tool - because that is the one relevant for CMSSW. Overlap cause problem only in SIM step for tracking particles. Regards

Sunanda
________________________________

**Comment by bsunanda** [comment]
@slomeo @ianna @cvuosalo There is a difference between DDD and DD4Hep is the use of double vs float. This might cause overlap for rotation matrix. Is there a double version of rotation matrix in dd4hep? I am making a PR and see if it helps. But if dd4hep does not have a version with double we may not get a solution

**Comment by cvuosalo** [comment]
@bsunanda Which rotation matrices are you referring to?

**Comment by bsunanda** [comment]
We have used DDHcalAngular which in turn uses RotationZ. Let me try with the parameters of DDHcaAngular computed in double and see if it resolves the issue.
________________________________

**Comment by slomeo** [comment]
@vargasa @cvuosalo @civanch @bsunanda : please take a look to #31434

**Comment by slomeo** [comment]
@vargasa @cvuosalo @civanch @kpedro88 : the updated list of the Overlaps for DD4HEP Scenario 2021 is present in a comment of the PR #31434

**Comment by slomeo** [comment]
@vargasa  @cvuosalo @civanch @kpedro88  : the updated list of the Overlaps for DD4HEP Scenario 2021 is present in a comment of the PR #31434

**Comment by vargasa** [comment]
Thank you @slomeo I updated the list in the issue description

**Comment by civanch** [comment]
+1
