### ISSUE TITLE
HLT updates for Run 3: hltFEDSelector

### ISSUE THREAD

**Issue by fwyzard** [cms-sw/cmssw#31185]
The `hltFEDSelector` module is used to select only the DAQ and TCDS FEDs:
```python
process.hltFEDSelector = cms.EDProducer( "EvFFEDSelector",
    inputTag = cms.InputTag( "rawDataCollector" ),
    fedList = cms.vuint32( 1023, 1024 )
)
```
to save them to the "NanoDST" stream along with the uGT and HLT trigger results:
```python
process.hltOutputNanoDST = cms.OutputModule( "ShmStreamConsumer",
    SelectEvents = cms.untracked.PSet(  SelectEvents = cms.vstring( 'DST_Physics_v7', 'DST_ZeroBias_v2' ) ),
    outputCommands = cms.untracked.vstring( 'drop *',
      'keep *_hltFEDSelector_*_*',
      'keep *_hltGtStage2Digis_*_*',
      'keep edmTriggerResults_*_*_*' )
)
```

1. is the list of FEDs still correct ?
2. should it be renamed to something like `hltTCDSFEDSelector` ?

**Comment by fwyzard** [comment]
assign hlt

**Comment by fwyzard** [comment]
@Sam-Harper @gennai FYI

**Comment by gennai** [comment]
Shall we also open a Jira ticket for the HLT configuration?

**Comment by fwyzard** [comment]
As you prefer !

GitHub issues are easier to work with... and we don't know what the configuration changes should be, yet.

**Comment by gennai** [comment]
Ok, so let's discuss it here and provide a Jira when the configuration proposal is made.

Best,
S.

**Comment by fwyzard** [comment]
@acostad FYI

**Comment by missirol** [comment]
+hlt

This long-standing issue was addressed in [CMSHLT-2325](https://its.cern.ch/jira/browse/CMSHLT-2325).

  - The list of TCDS FEDs was updated from `[1023,1024]` to `[1024,1025]` [*].
  - The HLT module was renamed from `hltFEDSelector` to `hltFEDSelectorTCDS` for clarity.

[*] @smorovic explained that `1024` is the primary TCDS FED which we currently use, `1025` is the FED reserved for secondary TCDS, and `1023` was the DAQ FED which has been retired.
