### ISSUE TITLE
CutParser problem on ARM64

### ISSUE THREAD

**Issue by Dr15Jones** [cms-sw/cmssw#31194]
We see unit test failures in CommonTools/Utils coming from both cutParser and expressionParser both with respect to calls to `reco::Track::charge`.

From https://cmssdt.cern.ch/SDT/cgi-bin/logreader/slc7_aarch64_gcc820/CMSSW_11_2_X_2020-08-20-1100/unitTestLogs/CommonTools/Utils#/78-78

```
===== Test "testCommonToolsUtil" ====
Running ....Track pt: 3
parsing cut: ""
parsing lazy cut: ""
parsing cut: "  "
parsing lazy cut: "  "
parsing cut: "pt"
parsing lazy cut: "pt"
parsing cut: "px"
parsing lazy cut: "px"
parsing cut: "pt > 2"
parsing lazy cut: "pt > 2"
parsing cut: "charge < 0"
F.Testing reco::Muon::ArbitrationType SegmentArbitration
Testing reco::TrackBase::TrackQuality (tight, highPurity)
.checking expression: "pt" = 5.83095
checking lazy expression: "pt" = 5.83095
checking expression: "charge"F.....

testCutParser.cc:54:Assertion
Test name: testCutParser::checkAll
assertion failed
- Expression: (*sel)(o) == res

testExpressionParser.cc:52:Assertion
Test name: testExpressionParser::checkAll
assertion failed
- Expression: fabs(f(trk) - x) < 1.e-6

Failures !!!
Run: 11   Failure total: 2   Failures: 2   Errors: 0

---> test testCommonToolsUtil had ERRORS
```

See
https://github.com/cms-sw/cmssw/blob/master/CommonTools/Utils/test/testCutParser.cc#L51-L54

and

https://github.com/cms-sw/cmssw/blob/master/CommonTools/Utils/test/testCutParser.cc#L51-L54

**Comment by smuzaffar** [comment]
Looks like issue with type convertion (int to double) here https://github.com/cms-sw/cmssw/blob/master/CommonTools/Utils/test/testExpressionParser.cc#L43 ? If I initialize `reco::Track` (https://github.com/cms-sw/cmssw/blob/master/CommonTools/Utils/test/testExpressionParser.cc#L123 ) with `charge >= 0` then it runs [a,b] but with `charge<0` it fails [c, d]


[a] `trk = reco::Track(chi2, ndof, v, p, 1, cov);`
checking expression: "charge"1:1
res= 1
x=1
trk.charge() = 1
f(trk)=1

[b] `trk = reco::Track(chi2, ndof, v, p, 0, cov);`
checking expression: "charge"
res= 0
x=0
trk.charge() = 0
f(trk)=0

[c] `trk = reco::Track(chi2, ndof, v, p, -1, cov);`
checking expression: "charge"
res= 255
x=-1
trk.charge() = -1
f(trk)=255

[d] `trk = reco::Track(chi2, ndof, v, p, -2, cov);`
checking expression: "charge"
res= 254
x=-2
trk.charge() = -=2
f(trk)=254

**Comment by makortel** [comment]
I took a look as well, but I suspect if it could be somehow connected to the fact that `charge_` is declared as `char`
https://github.com/cms-sw/cmssw/blob/587ea29fd84187b0be436e3072f728c053d982b2/DataFormats/TrackReco/interface/TrackBase.h#L475
Printing out `trk.charge()` indeed gives `-1`. On the other hand, I get the following in ROOT prompt in ARM
```
root [0] char x = -1
(char) '0xff'
root [1] int y = x
(int) 255
```
Doing the same in the unit test code gives `y == -1`.

I noticed that we are using `-fsigned-char`, and that indeed gives similar behavior with a simple test program
```cpp
// foo.cc
#include <iostream>

int main() {
  std::cout << int(char(-1)) << std::endl;
  return 0;
}
```
```sh
$ g++ -std=c++17 -o foo foo.cc
$ ./foo
255
$ g++ -std=c++17 -fsigned-char -o foo foo.cc
$ ./foo
-1
```

Given that `MethodInvoker` uses `edm::FunctionWithDict` which uses `TMethdod` to evaluate the function, are we building ROOT with `-fsigned-char`?

**Comment by smuzaffar** [comment]
yes for both amd64 and aarch64 root build use `-fsigned-char`
```
-- Compiler Flags: -O3 -DNDEBUG -D__ROOFIT_NOBANNER -std=c++17 -Wno-implicit-fallthrough -Wno-noexcept-type -pipe  -Wshadow -Wall -W -Woverloaded-virtual -fsigned-char -pthread
```

**Comment by makortel** [comment]
Should we open a ticket with ROOT? In the end, despite of the `-fsigned-char`, I do get
```
root [2] static_cast<int>(static_cast<char>(-1))
(int) 255
```
on ARM.

**Comment by smuzaffar** [comment]
yes we should open a ticket. I will do it. Thanks for simple reproducer

**Comment by makortel** [comment]
+1

This seems to have been fixed
