### ISSUE TITLE
[DD4hep] HcalParametersAnalyzer crashes with unused undefined solid in XML

### ISSUE THREAD

**Issue by cvuosalo** [cms-sw/cmssw#31197]
The HcalParametersAnalyzer crashes when using XML that contains an unused reference to an undefined solid. This crash exposes a vulnerability in the core DDCMS code for processing XML files.

Recipe to cause the crash:
1. in `Geometry/CMSCommonData/data/dd4hep/cmsExtendedGeometry2026D49.xml`, move `cavern.xml` very early in the list of XML files, to a position prior to the other XML files that define the solids it uses, in particular prior to `muonBase.xml`.
2. In `Geometry/CMSCommonData/data/cavern/2021/v1/cavern.xml` comment out the Logical Part and Pos Part sections.
3. cmsRun Geometry/CMSCommonData/test/dd4hep/2026D49.py
4. Crash will occur near the end of the processing of the XML files.

The crash occurs in `DetectorDescription/DDCMS/plugins/dd4hep/DDDefinitions2Objects.cc` in this loop in `static long load_dddefinition(Detector& det, xml_h element)`.
``` 
while (!context.unresolvedShapes.empty()) {
          for (auto it = context.unresolvedShapes.begin(); it != context.unresolvedShapes.end();) {
            auto const& name = it->first;
            auto const& aname = std::visit([](auto&& arg) -> std::string { return arg.firstSolidName; }, it->second);
            auto const& bname = std::visit([](auto&& arg) -> std::string { return arg.secondSolidName; }, it->second);

            auto const& ait = context.shapes.find(aname);
            if (ait->second.isValid()) {
              auto const& bit = context.shapes.find(bname);
              if (bit->second.isValid()) {
                dd4hep::Solid shape =
                    std::visit([&ait, &bit](auto&& arg) -> dd4hep::Solid { return arg.make(ait->second, bit->second); },
                               it->second);
                context.shapes[name] = shape;
                it = context.unresolvedShapes.erase(it);
              } else
                ++it;
            } else
              ++it;
          }
```
It is probably null pointers for either `if (ait->second.isValid()) {` or `if (bit->second.isValid()) {` that cause the crash.

Here is debug output immediately prior to the crash.
```
DD4CMS                 +++ Finished processing file:///afs/cern.ch/work/c/cvuosalo/geometry/CMSSW_11_2_X_2020-08-02-2300_cavfix/src/Geometry/CMSCommonData/data/FieldParameters.xml
DD4CMS                 +++ Processing data from: file:///afs/cern.ch/work/c/cvuosalo/geometry/CMSSW_11_2_X_2020-08-02-2300_cavfix/src/Geometry/CMSCommonData/data/dd4hep/cmsExtendedGeometry2026D49.xml
DD4CMS                 About to process Solid Section
DD4CMS                 Now resolve unresolved shapes
DD4CMS                 Resolving shapes count = 6
DD4CMS                 Trying to find shape = Wall.
DD4CMS                 Trying to find sub shape = Wallv1.
DD4CMS                 Trying to find shape = WallAir.
DD4CMS                 Trying to find sub shape = WallAirv1.
DD4CMS                 Trying to find shape = WallAirv1.
DD4CMS                 Trying to find sub shape = cavern:CMSWallAirv0.
DD4CMS                 Found shape = WallAirv1.
DD4CMS                 Trying to find shape = Wallv1.
DD4CMS                 Trying to find sub shape = cavern:CMSWallv0.
DD4CMS                 Found shape = Wallv1.
DD4CMS                 Trying to find shape = YBFeetLeftO.
DD4CMS                 Trying to find sub shape = YBFeetLeft. 
```

**Comment by cvuosalo** [comment]
assign geometry

**Comment by cvuosalo** [comment]
The `while` loop shown in the description can also become infinite under certain error conditions. The loop needs to be fixed in some simple way in the near term. In the long term, enforcing correct XML ordering with some XML validation tool would eliminate this danger, as mentioned here:
https://github.com/cms-sw/cmssw/pull/31003#discussion_r474032507

**Comment by ianna** [comment]
@cvuosalo - Could you please make a unit test in `DetectorDescription/DDCMS` to reproduce the problem? It should be a simple XML file in https://cmssdt.cern.ch/lxr/source/DetectorDescription/DDCMS/test/data/, not a full scenario. The scenarios in Geometry/CMSCommonData are auto generated. Thanks!

**Comment by cvuosalo** [comment]
Code improvements since this issue was created have eliminated the crash. Now, an attempt to use an undefined solid results in an exception rather than a crash, as shown by tests with CMSSW_12_3_X_2022-03-01-1100. This issue is resolved.

**Comment by cvuosalo** [comment]
+1
