### ISSUE TITLE
Unit test failure in FWCore/TFWLiteSelector ROOT6 (master) IB

### ISSUE THREAD

**Issue by mrodozov** [cms-sw/cmssw#31233]
There is a repetative unit test failure in
ROOT6 IB in 
FWCore/TFWLiteSelector

https://cmssdt.cern.ch/SDT/cgi-bin/logreader/slc7_amd64_gcc820/CMSSW_11_2_ROOT6_X_2020-08-24-2300/unitTestLogs/FWCore/TFWLiteSelector#/255-255

started failing with:

```
Info in &lt;TPacketizer::TPacketizer&gt;: Initial number of workers: 0
Info in &lt;TPacketizer::TPacketizer&gt;: no valid or non-empty file found: setting invalid
Error in &lt;TProofPlayerLite::InitPacketizer&gt;: instantiated packetizer object 'TPacketizer' is invalid
Error in &lt;TProofPlayerLite::Process&gt;: cannot init the packetizer
Info in &lt;TProofLite::UpdateDialog&gt;: processing was aborted - 0 events processed
Failed tfwliteselectortest::ThingsTSelector test, no histograms: status 20
status = 5120
```

**Comment by Dr15Jones** [comment]
@mrodozov we've actually gotten this problem randomly over the years. It would be interesting to see if it finally is reproducible.

**Comment by Dr15Jones** [comment]
assign core

**Comment by mrodozov** [comment]
@Dr15Jones by consistent I mean that it keep appearing in the IBs. 
Also I'm opening this issues to keep track of the "known" failures.

**Comment by smuzaffar** [comment]
See https://github.com/cms-sw/cmssw/issues/42992#issuecomment-1816410736
