### ISSUE TITLE
libCheck column in IB pages?

### ISSUE THREAD

**Issue by davidlange6** [cms-sw/cmssw#31247]
What is the source of the libCheck column in the IBs? I did a spot check of one reported error, and don't agree with it. Does the tool consider link and header dependencies?

**Comment by Dr15Jones** [comment]
assign core

**Comment by smuzaffar** [comment]
@davidlange6 , the information is obtained by running `ldd -u -r libName.so` [a]

[a]
https://github.com/cms-sw/cmssw/blob/master/Utilities/ReleaseScripts/scripts/libchecker.pl#L42

**Comment by davidlange6** [comment]
Thanks  — So no, it doesn’t capture header-only dependencies that scram requires also to be expressed via BuildFiles. Perhaps this is not a good metric then?

**Comment by smuzaffar** [comment]
this basically tells that there is no need to link against a library as it is not directly needed. But if we know that dependency is needed so that scram can correctly generate modules then one should change

```
<use name="Subsystem/Package"/>
```
to
```
<use name="Subsystem/Package" source_only="1"/>
```

**Comment by davidlange6** [comment]
Ah - too bad - when last I asked about a way to do header only dependencies, the solution was just to add them to the build file. So the opportunity to do it correctly is lost for a lot of places.

On Aug 26, 2020, at 4:42 PM, Malik Shahzad Muzaffar <notifications@github.com<mailto:notifications@github.com>> wrote:



this basically tells that there is no need to link against a library as it is not directly needed. But if we know that dependency is needed so that scram can correctly generate modules then one should change

<use name="Subsystem/Package"/>


to

<use name="Subsystem/Package" source_only="1"/>

**Comment by smuzaffar** [comment]
closing it, question has been answered
