### ISSUE TITLE
Should GeomDet be in DataFormats rather than Geometry?

### ISSUE THREAD

**Issue by davidlange6** [cms-sw/cmssw#31252]
Among the violations of dependencies in DataFormats is the use of GeomDet. This has created a cyclic dependency in module 'GeometryCommonTopologies': GeometryCommonTopologies -> DataFormatsTrackingRecHit -> GeometryCommonTopologies

which I'd like to break..

**Comment by davidlange6** [comment]
assign geometry

**Comment by Dr15Jones** [comment]
My personal take is why does Geometry depend on TrackingRecHit?

**Comment by Dr15Jones** [comment]
The answer is
```
cdj@mac-131265> git grep '#include "DataFormats/TrackingRecHit' | grep "Geometry/CommonTopologies"
Geometry/CommonTopologies/interface/GeometryAligner.h:#include "DataFormats/TrackingRecHit/interface/AlignmentPositionError.h"
Geometry/CommonTopologies/src/GeomDet.cc:#include "DataFormats/TrackingRecHit/interface/AlignmentPositionError.h"
Geometry/CommonTopologies/src/TrackerGeomDet.cc:#include "DataFormats/TrackingRecHit/interface/AlignmentPositionError.h"
```

So my take is `DataFormats/TrackingRecHit/interface/AlignmentPositionError.h` should move to `Geometry/CommonTopologies`.

**Comment by davidlange6** [comment]
I don’t see anything the breaks by doing that.

On Aug 26, 2020, at 7:35 PM, Chris Jones <notifications@github.com<mailto:notifications@github.com>> wrote:



The answer is

cdj@mac-131265> git grep '#include "DataFormats/TrackingRecHit' | grep "Geometry/CommonTopologies"
Geometry/CommonTopologies/interface/GeometryAligner.h:#include "DataFormats/TrackingRecHit/interface/AlignmentPositionError.h"
Geometry/CommonTopologies/src/GeomDet.cc<http://GeomDet.cc>:#include "DataFormats/TrackingRecHit/interface/AlignmentPositionError.h"
Geometry/CommonTopologies/src/TrackerGeomDet.cc<http://TrackerGeomDet.cc>:#include "DataFormats/TrackingRecHit/interface/AlignmentPositionError.h"


So my take is DataFormats/TrackingRecHit/interface/AlignmentPositionError.h should move to Geometry/CommonTopologies.

**Comment by slava77** [comment]
> So my take is `DataFormats/TrackingRecHit/interface/AlignmentPositionError.h` should move to `Geometry/CommonTopologies`.

perhaps DataFormats/GeometryCommonDetAlgo
because in DataFormats/TrackingRecHit/interface/AlignmentPositionError.h
```c++
#include "DataFormats/GeometryCommonDetAlgo/interface/GlobalError.h"
```

**Comment by cvuosalo** [comment]
+1
