### ISSUE TITLE
PFMultiLinksType in PFBlockAlgo uses the equality of (eta, phi) doubles to determine link status

### ISSUE THREAD

**Issue by jpata** [cms-sw/cmssw#31280]
In PFMultilinksTC [1] we store a pair of eta, phi doubles, which is later used as a key to search for the right elements in a different collection [2] in PFBlockAlgo linkers. Switching PFMultilinksTC to store instead an integer index to the right collection would potentially be safer and faster.

[1] https://github.com/cms-sw/cmssw/blob/master/DataFormats/ParticleFlowReco/interface/PFMultilinksTC.h#L13
[2] https://github.com/cms-sw/cmssw/blob/master/RecoParticleFlow/PFProducer/plugins/linkers/TrackAndECALLinker.cc#L67

attn @hatakeyamak @bendavid

**Comment by Dr15Jones** [comment]
assign reconstruction

**Comment by jpata** [comment]
Note: this is addressed in #31191 (not yet reviewed/merged): https://github.com/cms-sw/cmssw/pull/31191/files#diff-d8b43a58384a8e7415021b981d132c56R31
MultiLinks is an implementation detail of PFBlockAlgo that should not be exposed or used outside.

**Comment by hatakeyamak** [comment]
This one came up in the PF reco chat today.
Probably a good way forward is to use to use id() and key().
(example: https://github.com/hatakeyamak/cmssw/blob/fec870f600ff2db789ddd44f9818677be3ebb6d2/RecoParticleFlow/PFProducer/plugins/importers/GeneralTracksImporter.cc#L75)

**Comment by rappoccio** [comment]
Yes, can also even investigate using =edm::Ref= or =edm::RefVector=.

**Comment by slava77** [comment]
+reconstruction

resolved in #34385
