### ISSUE TITLE
Arm uses more Vsize memory and RSS compared to Intel (and IBM)

### ISSUE THREAD

**Issue by mrodozov** [cms-sw/cmssw#31306]
That unit test is testing the Service that aborts if the job takes too much memory. In this case, it is supposed to succeed since it was guessed that 1GB of VSize would be sufficient to run that simple job. For ARM, that is not the case (which is kind of sad). We can get the test to work by moving the max size to be 1.5 for the test. [Although it still would be nice to find out why ARM is requiring so much more virtual memory]

_Originally posted by @Dr15Jones in https://github.com/cms-sw/cmssw/issues/31236#issuecomment-680050896_

**Comment by mrodozov** [comment]
Following #31236 how this is happening should be the topic of a separate issue
https://github.com/cms-sw/cmssw/issues/31236

**Comment by mrodozov** [comment]
I ran the test on intel, ibm and arm and printed the vsize and rss with making the vsize reference very small (1 isntead of 1000) and printed the rss after the vsize 
,the results is the arm test is using nearly twice the vsize and ~7 time the rss compared with intel. see below the number for ibm
 Arm:

```
Exceeded maximum allowed VSize of 1 GB (VSize is 1.37794pi.rss is1.14362)
Exceeded maximum allowed VSize of 1 GB (VSize is 1.37794pi.rss is1.14362)
Exceeded maximum allowed VSize of 1 GB (VSize is 1.37794pi.rss is1.14369)
Exceeded maximum allowed VSize of 1 GB (VSize is 1.37794pi.rss is1.14369)
Exceeded maximum allowed VSize of 1 GB (VSize is 1.37794pi.rss is1.14369)
Exceeded maximum allowed VSize of 1 GB (VSize is 1.37794pi.rss is1.14544)
Exceeded maximum allowed VSize of 1 GB (VSize is 1.37794pi.rss is1.14538)
Exceeded maximum allowed VSize of 1 GB (VSize is 1.37794pi.rss is1.14362)
Exceeded maximum allowed VSize of 1 GB (VSize is 1.37794pi.rss is1.14544)
Exceeded maximum allowed VSize of 1 GB (VSize is 1.37794pi.rss is1.1455)
Exceeded maximum allowed VSize of 1 GB (VSize is 1.37794pi.rss is1.14544)
Exceeded maximum allowed VSize of 1 GB (VSize is 1.37794pi.rss is1.1455)
Exceeded maximum allowed VSize of 1 GB (VSize is 1.37794pi.rss is1.14362)
Exceeded maximum allowed VSize of 1 GB (VSize is 1.37794pi.rss is1.14362)
Exceeded maximum allowed VSize of 1 GB (VSize is 1.37794pi.rss is1.14506)
Exceeded maximum allowed VSize of 1 GB (VSize is 1.37794pi.rss is1.1455)
Exceeded maximum allowed VSize of 1 GB (VSize is 1.37794pi.rss is1.14538)
Exceeded maximum allowed VSize of 1 GB (VSize is 1.37794pi.rss is1.14544)
Exceeded maximum allowed VSize of 1 GB (VSize is 1.37794pi.rss is1.1455)
Exceeded maximum allowed VSize of 1 GB (VSize is 1.37794pi.rss is1.14369)
Exceeded maximum allowed VSize of 1 GB (VSize is 1.37794pi.rss is1.14544)
Exceeded maximum allowed VSize of 1 GB (VSize is 1.37794pi.rss is1.14362)
Exceeded maximum allowed VSize of 1 GB (VSize is 1.37794pi.rss is1.14362)
Exceeded maximum allowed VSize of 1 GB (VSize is 1.37794pi.rss is1.1455)
Exceeded maximum allowed VSize of 1 GB (VSize is 1.37794pi.rss is1.14369)
Exceeded maximum allowed VSize of 1 GB (VSize is 1.37794pi.rss is1.14369)
Exceeded maximum allowed VSize of 1 GB (VSize is 1.37794pi.rss is1.14362)
Exceeded maximum allowed VSize of 1 GB (VSize is 1.37794pi.rss is1.14369)
Exceeded maximum allowed VSize of 1 GB (VSize is 1.37794pi.rss is1.14362)
Exceeded maximum allowed VSize of 1 GB (VSize is 1.37794pi.rss is1.14369)
Exceeded maximum allowed VSize of 1 GB (VSize is 1.37794pi.rss is1.14538)
Exceeded maximum allowed VSize of 1 GB (VSize is 1.37794pi.rss is1.14544)
Exceeded maximum allowed VSize of 1 GB (VSize is 1.37794pi.rss is1.14362)
Exceeded maximum allowed VSize of 1 GB (VSize is 1.37794pi.rss is1.1455)
Exceeded maximum allowed VSize of 1 GB (VSize is 1.37794pi.rss is1.14362)
Exceeded maximum allowed VSize of 1 GB (VSize is 1.37794pi.rss is1.1455)
Exceeded maximum allowed VSize of 1 GB (VSize is 1.37794pi.rss is1.14362
```
 intel:
```
Exceeded maximum allowed VSize of 1 GB (VSize is 0.590613pi.rss is0.162477)
Exceeded maximum allowed VSize of 1 GB (VSize is 0.590613pi.rss is0.177434)
Exceeded maximum allowed VSize of 1 GB (VSize is 0.590613pi.rss is0.177453)
Exceeded maximum allowed VSize of 1 GB (VSize is 0.590613pi.rss is0.177496)
Exceeded maximum allowed VSize of 1 GB (VSize is 0.590613pi.rss is0.177508)
Exceeded maximum allowed VSize of 1 GB (VSize is 0.590613pi.rss is0.177512)
Exceeded maximum allowed VSize of 1 GB (VSize is 0.590613pi.rss is0.177516)
Exceeded maximum allowed VSize of 1 GB (VSize is 0.590613pi.rss is0.177527)
Exceeded maximum allowed VSize of 1 GB (VSize is 0.590613pi.rss is0.177539)
Exceeded maximum allowed VSize of 1 GB (VSize is 0.590613pi.rss is0.177551)
Exceeded maximum allowed VSize of 1 GB (VSize is 0.590613pi.rss is0.177555)
Exceeded maximum allowed VSize of 1 GB (VSize is 0.590613pi.rss is0.177559)
Exceeded maximum allowed VSize of 1 GB (VSize is 0.590613pi.rss is0.177566)
Exceeded maximum allowed VSize of 1 GB (VSize is 0.590613pi.rss is0.17757)
Exceeded maximum allowed VSize of 1 GB (VSize is 0.590613pi.rss is0.177586)
Exceeded maximum allowed VSize of 1 GB (VSize is 0.590613pi.rss is0.177605)
Exceeded maximum allowed VSize of 1 GB (VSize is 0.590613pi.rss is0.177617)
Exceeded maximum allowed VSize of 1 GB (VSize is 0.590613pi.rss is0.177637)
Exceeded maximum allowed VSize of 1 GB (VSize is 0.590613pi.rss is0.177641)
Exceeded maximum allowed VSize of 1 GB (VSize is 0.590613pi.rss is0.177645)
Exceeded maximum allowed VSize of 1 GB (VSize is 0.590613pi.rss is0.177648)
Exceeded maximum allowed VSize of 1 GB (VSize is 0.590613pi.rss is0.177652)
Exceeded maximum allowed VSize of 1 GB (VSize is 0.590613pi.rss is0.177656)
Exceeded maximum allowed VSize of 1 GB (VSize is 0.590613pi.rss is0.17766)
Exceeded maximum allowed VSize of 1 GB (VSize is 0.590613pi.rss is0.177684)
Exceeded maximum allowed VSize of 1 GB (VSize is 0.590613pi.rss is0.177695)
Exceeded maximum allowed VSize of 1 GB (VSize is 0.590613pi.rss is0.177699)
Exceeded maximum allowed VSize of 1 GB (VSize is 0.590613pi.rss is0.177715)
Exceeded maximum allowed VSize of 1 GB (VSize is 0.590613pi.rss is0.178184)
Exceeded maximum allowed VSize of 1 GB (VSize is 0.590613pi.rss is0.178395)
Exceeded maximum allowed VSize of 1 GB (VSize is 0.590613pi.rss is0.178426)
Exceeded maximum allowed VSize of 1 GB (VSize is 0.596613pi.rss is0.177395)
Exceeded maximum allowed VSize of 1 GB (VSize is 0.596613pi.rss is0.177398)
Exceeded maximum allowed VSize of 1 GB (VSize is 0.596613pi.rss is0.177477)
Exceeded maximum allowed VSize of 1 GB (VSize is 0.596613pi.rss is0.177492)
Exceeded maximum allowed VSize of 1 GB (VSize is 0.596613pi.rss is0.177496)
Exceeded maximum allowed VSize of 1 GB (VSize is 0.596613pi.rss is0.177527)
Exceeded maximum allowed VSize of 1 GB (VSize is 0.596613pi.rss is0.177551)
Exceeded maximum allowed VSize of 1 GB (VSize is 0.596613pi.rss is0.177578)
Exceeded maximum allowed VSize of 1 GB (VSize is 0.596613pi.rss is0.177582)
Exceeded maximum allowed VSize of 1 GB (VSize is 0.596613pi.rss is0.177605)
Exceeded maximum allowed VSize of 1 GB (VSize is 0.596613pi.rss is0.177609)
Exceeded maximum allowed VSize of 1 GB (VSize is 0.596613pi.rss is0.177613)
Exceeded maximum allowed VSize of 1 GB (VSize is 0.596613pi.rss is0.177621)
Exceeded maximum allowed VSize of 1 GB (VSize is 0.596613pi.rss is0.177629)
Exceeded maximum allowed VSize of 1 GB (VSize is 0.596613pi.rss is0.177633)
Exceeded maximum allowed VSize of 1 GB (VSize is 0.596613pi.rss is0.177641)
Exceeded maximum allowed VSize of 1 GB (VSize is 0.596613pi.rss is0.17766)
Exceeded maximum allowed VSize of 1 GB (VSize is 0.596613pi.rss is0.177664)
Exceeded maximum allowed VSize of 1 GB (VSize is 0.596613pi.rss is0.177668)
Exceeded maximum allowed VSize of 1 GB (VSize is 0.596613pi.rss is0.177672)
Exceeded maximum allowed VSize of 1 GB (VSize is 0.596613pi.rss is0.177676)
Exceeded maximum allowed VSize of 1 GB (VSize is 0.596613pi.rss is0.17768)
Exceeded maximum allowed VSize of 1 GB (VSize is 0.596613pi.rss is0.177684)
Exceeded maximum allowed VSize of 1 GB (VSize is 0.596613pi.rss is0.177687)
Exceeded maximum allowed VSize of 1 GB (VSize is 0.596613pi.rss is0.177699)
Exceeded maximum allowed VSize of 1 GB (VSize is 0.596613pi.rss is0.177703)
Exceeded maximum allowed VSize of 1 GB (VSize is 0.596613pi.rss is0.177734)
Exceeded maximum allowed VSize of 1 GB (VSize is 0.596613pi.rss is0.178191)
Exceeded maximum allowed VSize of 1 GB (VSize is 0.596613pi.rss is0.178215)
Exceeded maximum allowed VSize of 1 GB (VSize is 0.596613pi.rss is0.179602)
```
ibm
```
Exceeded maximum allowed VSize of 1 GB (VSize is 0.608437pi.rss is0.289438)
Exceeded maximum allowed VSize of 1 GB (VSize is 0.608437pi.rss is0.289438)
Exceeded maximum allowed VSize of 1 GB (VSize is 0.608437pi.rss is0.289375)
Exceeded maximum allowed VSize of 1 GB (VSize is 0.608437pi.rss is0.2895)
Exceeded maximum allowed VSize of 1 GB (VSize is 0.608437pi.rss is0.28925)
```
The values doesn't change much, the ratio is 
RSS
1.14362 / 0.162477 = 7.0386
1.14362 / 0.28925 = 3.9537 
VSize 
1.37794 / 0.596613 = 2.31
1.37794 /0.608437 = 2.26

**Comment by Dr15Jones** [comment]
could you try with cmsRunGlibC?

**Comment by mrodozov** [comment]
with cmsRunGlibC on Arm the vsize and rss are nearly compatible with intel and ibm, actually less:

```
arm: Exceeded maximum allowed VSize of 1 GB (VSize is 0.402062pi.rss is0.170313) 
intel: Exceeded maximum allowed VSize of 1 GB (VSize is 0.581195pi.rss is0.173039)
ibm: Exceeded maximum allowed VSize of 1 GB (VSize is 0.55725pi.rss is0.281687)
```

**Comment by dan131riley** [comment]
jemalloc likes to work with entire kernel pages, and it takes what I call a "slash and burn" approach to address space, where for allocations larger than some number of pages it makes a separate allocation on a page boundary and later frees the address space using calls to `madvise(2)` with the flag `MADV_DONTNEED`.  jemalloc sets the kernel page size it uses for this and for all allocations at compile time.  This causes a problem with aarch64, where the page size may vary depending on the kernel, see

https://github.com/jemalloc/jemalloc/issues/467

To work around this, we build jemalloc on aarch64 and ppc64 with a 64k page size

https://github.com/cms-sw/cmsdist/blob/82727b037e18e1a826c31275e4feab8eedc8009d/jemalloc.spec#L15-L18
```
case %{cmsplatf} in
  # set the page size to 64k on ARMv8 and PowerPC
  *_aarch64_*|*_ppc64le_*|*_ppc64_*) XOPTS="--with-lg-page=16" ;;
esac
```

This has two noticeable effects.

1) For the test in question, jemalloc never passes the threshold to do the "slash and burn" allocations.  If I run that unit test on amd64 tracing madvise calls I get a bunch of them, most of them for less than 64k:
```
% strace -e trace=madvise cmsRun test_resource_succeed_cfg.py 2>&1 | grep '^madvise'
madvise(0x7fc16c9e9000, 4096, MADV_FREE) = 0
madvise(0x7fc1674e4000, 4096, MADV_DONTNEED) = 0
madvise(0x7fc166a23000, 12288, MADV_DONTNEED) = 0
madvise(0x7fc166a30000, 8192, MADV_DONTNEED) = 0
madvise(0x7fc166b07000, 20480, MADV_DONTNEED) = 0
madvise(0x7fc166a98000, 4096, MADV_DONTNEED) = 0
madvise(0x7fc166a7a000, 20480, MADV_DONTNEED) = 0
madvise(0x7fc166a46000, 24576, MADV_DONTNEED) = 0
madvise(0x7fc166a37000, 20480, MADV_DONTNEED) = 0
madvise(0x7fc166b13000, 233472, MADV_DONTNEED) = 0
madvise(0x7fc166ac5000, 32768, MADV_DONTNEED) = 0
```
Doing the same on an aarch64 system, there are no calls to `madvise`, so jemalloc never hits an allocation large enough that it can later tell the OS to kick that address range out of RSS.

2) jemalloc allocates entire pages at a time; on amd64 that's almost always 4k pages, while on aarch64 we've told it to allocate 64k pages.  Whatever algorithm it uses for packing allocations into pages ends up wasting a lot of space with 64k pages.  Adding up `mmap` ops on amd64 for the allocation test:
```
% strace -e trace=mmap cmsRun test_resource_succeed_cfg.py 2>&1 | grep '^mmap' | awk '{ sum += $2 } END { print sum }'
613389674
```
and on aarch64 (with the test threshold bumped to 1.5 so it doesn't fail):
```
% strace -e trace=mmap cmsRun test_resource_succeed_cfg.py 2>&1 | grep '^mmap' | awk '{ sum += $2 } END { print sum }'
2681515776
```
so the combination of a large page size and I would guess some non-optimality in how jemalloc handles them leads to a much larger memory allocation and a lot of empty allocated space (my sums are, of course, overestimates since I'm not accounting for `munmap` calls, but it should still be good enough for illustrative purposes).

Apparently issues with jemalloc interacting with large pages are somewhat known, see for example

https://www.digitalocean.com/blog/transparent-huge-pages-and-alternative-memory-allocators/

I don't know how severe this address-space inefficiency will be for more realistic jobs.  If it is as bad, we may have to give up the portability of using a large page size or give up on jemalloc on platforms where this is an issue.

**Comment by Dr15Jones** [comment]
Thanks Dan!

**Comment by dan131riley** [comment]
Well, there is a problem with this theory, if I'm right then we should see the same thing on ppc64.  @smuzaffar is there a ppc64 system I can run a few tests on?

**Comment by smuzaffar** [comment]
@dan131riley , we do have ppc64le machines but they are under CERN openlab control. Please open a request https://cern.service-now.com/service-portal?id=sc_cat_item&name=request&fe=openlab-IBM and ask for access to ibmminsky-1 node.

**Comment by mrodozov** [comment]
After reading the jemalloc 467 issue (and others and the manual) it seems that our "problem" comes from the kernel page size on our ppc and arm machines being 64k, which jemalloc configures itself to use, so in this case having the flag
`--with-lg-page=16` that sets the page size to be used 64k makes it redundant. So I removed it in https://github.com/cms-sw/cmsdist/pull/6243 
It also says "this should be at least one page size big" i.e. 64k for our arm and ppc machines, no escape from it (to use less).
In the same issue is mentioned "the kernel page size depends on OS" and on Debian(Arm) for example is 4k.
This is what the page size for this distro is by default.
If we want to "fix" this, we can:
- use a Debian (or else) distro for arm and ppc production (when we have prod). The page size is 4k which "solves" this
- build our own centos/redhat/fedora kernel with 4k page size (as the page size is embedded in a way as "fixed" entity )
- see how it goes without the flag and decide if its acceptable. we compared vsize with/without flag and without is using ~20% less vmem (I compared few relvals only). not sure why/how yet.
Also lets ask  @davidlt to tell us about how he decided to use lg_chunks:18 at the time when he can.
We also ran comparison tests last week which I'm sharing here.

**Comment by mrodozov** [comment]
![Screenshot 2020-09-16 at 09 51 05](https://user-images.githubusercontent.com/3791215/93302431-a5974a00-f802-11ea-98ca-1e8aca43358b.png)
![Screenshot 2020-09-16 at 09 50 47](https://user-images.githubusercontent.com/3791215/93302433-a6c87700-f802-11ea-803e-edec04b55ba9.png)
![Screenshot 2020-09-16 at 09 50 05](https://user-images.githubusercontent.com/3791215/93302435-a7f9a400-f802-11ea-90c7-181fda2b15e7.png)
![Screenshot 2020-09-16 at 09 49 38](https://user-images.githubusercontent.com/3791215/93302438-a8923a80-f802-11ea-8daf-415dc0231ad8.png)
![Screenshot 2020-09-10 at 13 58 55](https://user-images.githubusercontent.com/3791215/93302467-b47dfc80-f802-11ea-9474-9693a9ac0195.png)
![Screenshot 2020-09-10 at 13 59 30](https://user-images.githubusercontent.com/3791215/93302581-e68f5e80-f802-11ea-884b-0c7081fbf3b6.png)

**Comment by mrodozov** [comment]
I'm explaining for Chris and Dan - we are running a monitoring script that records various metrics vms_25 50 75 90 max avg and the same is recorded for rss , you can see all available metrics here on the left panel:
https://es-cmssdt.cern.ch/kibana/app/kibana#/discover?_g=(refreshInterval:(pause:!t,value:0),time:(from:now-15h,to:now))&_a=(columns:!(_source),index:AWhWonmqFDQSYvxIl8U0,interval:auto,query:(language:kuery,query:''),sort:!('@timestamp',desc))
Running under the same condition, I run the same workflows for both jemalloc and glibc on plots 1,2,5 and 6, and then do the ratio between the same workflow/steps and plot it. For the 3 and 4 plot I ran with the existing flag in the jemalloc external (jm_16), removed it, recompile and run again, and then plot the same ratio. 
Surprisingly PPC is allocating the same memory with both glibc and jemalloc. The plot 5 is what we already suspected/knew - visualized with more statistics. 
I also changed the with-lg-page flag value to 17,18, and 22 , but the vms_max didn't move, neither do time for execution. It doesn't increase the allocated memory (at least not on arm). Thats why no plots for 22/17 22/18 etc

**Comment by mrodozov** [comment]
Update is one of the techlab machines uses 10x RSS compared with the other one. Virtual memory for the same jobs is compatible on both machines (although its > 1Gb on average)
One can see it here: https://tinyurl.com/yxbuu7n3

**Comment by dan131riley** [comment]
Does the command `getconf PAGESIZE` give the same result on both systems?

**Comment by mrodozov** [comment]
It does. its 65536 on all arm and ppc machines

**Comment by dan131riley** [comment]
Found the difference--on ibmminsky-2,
```
ibmminsky-2:dsr> grep Hugepagesize /proc/meminfo 
Hugepagesize:      16384 kB
```
and olarm-202:
```
olarm-202:~> grep Hugepagesize /proc/meminfo 
Hugepagesize:     524288 kB
```
jemalloc uses multiples of the Hugepagesize for blocks it allocates for bookkeeping arrays/bitmaps:

https://github.com/jemalloc/jemalloc/blob/481bbfc9906e7744716677edd49d0d6c22556a1a/src/base.c#L252-L266

Allocate an arena per each of 4 threads and there's 2GB of address space which barely gets used.  So we need to give aarch64 a reasonable `--with-lg-hugepage`, the ppc value of 16384 is probably reasonable to start with.

**Comment by dan131riley** [comment]
FWCore/Services resource limit tests succeed on aarch64 with https://github.com/cms-sw/cmsdist/pull/8181, and no new problems appeared, so I think this issue can be closed.

**Comment by makortel** [comment]
assign core

**Comment by makortel** [comment]
+core

Fixed with https://github.com/cms-sw/cmsdist/pull/8181

**Comment by makortel** [comment]
@cmsbuild, please close
