### ISSUE TITLE
Preferred way to break DataFormats/TrackReco and DataFormats/TrackCandidate circle?

### ISSUE THREAD

**Issue by davidlange6** [cms-sw/cmssw#31301]
There is a ~trivially fixed circular dependency between DataFormats/TrackReco and DataFormats/TrackCandidate. Which package is meant to depend on the other. I can move things accordingly (either some dictionaries that use classes from both packages or one header)

**Comment by davidlange6** [comment]
assign reconstruction

**Comment by slava77** [comment]
@davidlange6 
I'm missing details or being confused by the phrasing (perhaps as trivial as a question mark in the "Which package is meant to depend on the other.")

**Comment by slava77** [comment]
after looking a bit more, I see that the direct dependence of TrackReco on TrackCandidate is only in the dictionaries definition in classes.h used for an aggregate ```<TrackCandidate, Track>``` definition.

The dependence of TrackCandidate is apparently via 
DataFormats/TrackCandidate/interface/TrackCandidate.h:
```#include "DataFormats/TrackReco/interface/TrajectoryStopReasons.h"```

@davidlange6 
please clarify if this is what you meant with the issue description.

**Comment by davidlange6** [comment]
Yes, that sentence misses a question mark. Would we like DataFormats/TrackReco to depend on DataFormats/TrackCandidate or would we like DataFormats/TrackCandidate to depend on DataFormats/TrackReco?

On Aug 31, 2020, at 2:50 PM, Slava Krutelyov <notifications@github.com<mailto:notifications@github.com>> wrote:



@davidlange6<https://github.com/davidlange6>
I'm missing details or being confused by the phrasing (perhaps as trivial as a question mark in the "Which package is meant to depend on the other.")

**Comment by slava77** [comment]
@mtosi @vmariani 

@rovere 
it looks like you are the original developer and perhaps recall the history.

Naively, it looks to me that DataFormats/TrackReco/interface/TrajectoryStopReasons.h can be moved to DataFormats/TrackCandidate/interface/

**Comment by davidlange6** [comment]
Yes, thats all correct.

On Aug 31, 2020, at 3:01 PM, Slava Krutelyov <notifications@github.com<mailto:notifications@github.com>> wrote:



after looking a bit more, I see that the direct dependence of TrackReco on TrackCandidate is only in the dictionaries definition in classes.h used for an aggregate <TrackCandidate, Track> definition.

The dependence of TrackCandidate is apparently via
DataFormats/TrackCandidate/interface/TrackCandidate.h:
#include "DataFormats/TrackReco/interface/TrajectoryStopReasons.h"

@davidlange6<https://github.com/davidlange6>
please clarify if this is what you meant with the issue description.

**Comment by rovere** [comment]
> @mtosi @vmariani
> 
> @rovere
> it looks like you are the original developer and perhaps recall the history.
> 
> Naively, it looks to me that DataFormats/TrackReco/interface/TrajectoryStopReasons.h can be moved to DataFormats/TrackCandidate/interface/

From a quick look, I tend to agree on that. That would also imply to move the corresponding *cc.

**Comment by slava77** [comment]
FWIW, TrajectoryStopReasons is actually a track candidate stop reason.
So, the relocation seems reasonable.

**Comment by slava77** [comment]
+1

fixed in #31327 (merged Sept 3)
the dependency cycle is gone, according to the ignominy report in https://cmssdt.cern.ch/SDT/cgi-bin/newQA.py?arch=slc7_amd64_gcc820&release=CMSSW_11_2_X_2020-09-04-2300
