### ISSUE TITLE
Possible improvements in TrackBase

### ISSUE THREAD

**Issue by jpata** [cms-sw/cmssw#31326]
As pointed out by @dpiparo, [TrackBase](https://github.com/cms-sw/cmssw/blob/4e01538cc734853c97f2b30fcdf0a3eb9bcf3f21/DataFormats/TrackReco/interface/TrackBase.h#L62) could potentially be improved by caching costly functions:
> Things to improve: several calls to methods which have a cost, divisions. For ::ptError, here,  the safety for neutrals might not be needed, in some cases perhaps the sqrt can be avoided providing the error2 only.

Given that most of the class methods are inlined, we can't see the potential gains directly in igprof in advance, but TrackBase is used widely throughout reconstruction.

**Comment by jpata** [comment]
assign reconstruction

**Comment by jpata** [comment]
Via @slava77 
> For the "invisible" costs, I'd propose to recompile the package and its
dependencies with -O0 to at least check if we have non-linearly scaling
call patterns.

**Comment by jpata** [comment]
adding TRK POG: @mtosi @JanFSchulte

**Comment by JanFSchulte** [comment]
adding new TRK POG convener @vmariani

**Comment by VinInn** [comment]
ptError shall be banned. It is dominated by the error on 1/pt and is this that shall be used

**Comment by dpiparo** [comment]
@mtosi @vmariani here a proposal to continue the discussion: https://github.com/cms-sw/cmssw/pull/31433 removing some sqrts and divisions, one can get 2% speedup in the event loop (phase2 - 200 PU).
The PR is not all that can be done: by some interventions in the code of components such as pf or muon reco, one could save even more.

**Comment by VinInn** [comment]
I am stil convinced that action shall be taken in the client code. For instance use error^2, pt^2 etc

**Comment by dpiparo** [comment]
absolutely. Whenever possible the client code ought to be changed. 
There could be some percent, hard to quantifify, still on the table. It would not be bad to have a bundle of ~4/5% reduction in the event loop...

**Comment by slava77** [comment]
+1

after #31433 was merged
