### ISSUE TITLE
ALCAHARVEST:SiPixelAli is broken

### ISSUE THREAD

**Issue by mmusich** [cms-sw/cmssw#31381]
Since `CMSSW_11_2_0_pre4` the following command:

```python
cmsDriver.py pedeStep --data --conditions auto:run2_data --era Run2_2018 --scenario pp -s ALCAHARVEST:SiPixelAli --filein /store/group/alca_trackeralign/debug/PromptCalibProdSiPixelAli.root
```

returns:

```
ALCAHARVEST:SiPixelAli
magnetic field option forced to: AutoFromDBCurrent
entry /store/group/alca_trackeralign/debug/PromptCalibProdSiPixelAli.root
Step: ALCAHARVEST Spec: ['SiPixelAli']
Starting  cmsRun  pedeStep_ALCAHARVEST.py
07-Sep-2020 12:50:56 CEST  Initiating request to open file root://eoscms.cern.ch//eos/cms/store/group/alca_trackeralign/debug/PromptCalibProdSiPixelAli.root
%MSG-w XrdAdaptor:  file_open 07-Sep-2020 12:51:03 CEST pre-events
Data is served from cern.ch instead of original site eoscms
%MSG
07-Sep-2020 12:51:03 CEST  Successfully opened file root://eoscms.cern.ch//eos/cms/store/group/alca_trackeralign/debug/PromptCalibProdSiPixelAli.root
07-Sep-2020 12:51:32 CEST  Closed file root://eoscms.cern.ch//eos/cms/store/group/alca_trackeralign/debug/PromptCalibProdSiPixelAli.root
%MSG-e MillePedeFileReader:   MillePedeDQMModule:SiPixelAliDQMModule@endProcessBlock  07-Sep-2020 12:51:32 CEST post-events
Could not read millepede end-file.
%MSG
%MSG-e MillePedeFileReader:   MillePedeDQMModule:SiPixelAliDQMModule@endProcessBlock  07-Sep-2020 12:51:32 CEST post-events
Could not read millepede log-file.
%MSG
%MSG-e MillePedeFileReader:   MillePedeDQMModule:SiPixelAliDQMModule@endProcessBlock  07-Sep-2020 12:51:32 CEST post-events
Could not read millepede result-file.
%MSG
DQMFileSaver::globalEndRun()
%MSG-w Alignment:   AlignmentProducerAsAnalyzer:SiPixelAliPedeAlignmentProducer@endJob  MillePedeAlignmentAlgorithm::doIO() 07-Sep-2020 12:53:10 CEST EndJob
'vstring mergeTreeFiles' and 'vstring mergeBinaryFiles' differ in size
%MSG
```
The output DQM file contains no information whatsoever of the alignment parameters fit, while in previous releases the same command does not have any issue:
| `CMSSW_11_2_0_pre4`| `CMSSW_11_2_0_pre3` |
| ------ | ------ |
| ![image](https://user-images.githubusercontent.com/5082376/92380783-04c1d400-f10a-11ea-9daa-4dee463d51f4.png) | ![image](https://user-images.githubusercontent.com/5082376/92384070-b7486580-f10f-11ea-9010-30d08579ea9b.png) |

I strongly suspect that's tied to https://github.com/cms-sw/cmssw/pull/30698.
It looks like `MillePedeFileReader ::read()` 

https://github.com/cms-sw/cmssw/blob/2c7b8d660b81a6dd7420ec6d69c579851736de6c/Alignment/MillePedeAlignmentAlgorithm/src/MillePedeFileReader.cc#L24-L27

is called even before the result files `millepede.end (res, log)` are created.
What guarantees the ordering is correct in the `endProcessBlock()`?
The sequence which is run is:

```python
process.ALCAHARVESTSiPixelAli = cms.Sequence(process.SiPixelAliMilleFileExtractor+process.SiPixelAliPedeAlignmentProducer+process.SiPixelAliDQMModule+process.dqmEnvSiPixelAli)
process.SiPixelAli = cms.Path(process.ALCAHARVESTSiPixelAli)
process.schedule = cms.Schedule(*[ process.SiPixelAli, process.ALCAHARVESTDQMSaveAndMetadataWriter ], tasks=[process.patAlgosToolsTask])
```
cc:
@dmeuser @connorpa @vbotta

**Comment by Dr15Jones** [comment]
assign alca, dqm

**Comment by makortel** [comment]
> What guarantees the ordering is correct in the `endProcessBlock()`?

Do I read the code correctly that `AlignmentProducerAsAnalyzer` creates the files in `endJob()` , and the intention is for the `MillePedeDQMModule` to read something from them into DQM?

Then a correct ordering can be guaranteed by changing `AlignmentProducerAsAnalyzer` to write the files in `endProcessBlock()` instead of `endJob()` and to produce something into ProcessBlock (e.g. empty `struct AlignmentToken{};`), and changing `MillePedeDQMModule` to consume that product.

**Comment by mmusich** [comment]
Hi @makortel 

> Do I read the code correctly that `AlignmentProducerAsAnalyzer` creates the files in endJob() , and the intention is for the `MillePedeDQMModule` to read something from them into DQM?

the intention is that `MillePedeDQMModule` reads something from those files and then *puts* it into DQM.

> Then a correct ordering can be guaranteed by changing `AlignmentProducerAsAnalyzer` to write the files in `endProcessBlock()` instead of `endJob()` and to produce something into ProcessBlock (e.g. empty `struct AlignmentToken{};`), and changing `MillePedeDQMModule` to consume that product.

Thanks for the suggestion.
Can you point to some documentation and / or example on how that should be done?
Also `AlignmentProducerAsAnalyzer` (as the name is betraying) is an `EDAnalyzer` (actually: `edm::one::EDAnalyzer<edm::one::WatchRuns, edm::one::WatchLuminosityBlocks, edm::one::SharedResources>`.

https://github.com/cms-sw/cmssw/blob/1cd14f8427fa32d147342d64bb245b2430a89bad/Alignment/CommonAlignmentProducer/plugins/AlignmentProducerAsAnalyzer.h#L26-L28

 Does your suggestion imply it should become an `EDProducer`?

**Comment by makortel** [comment]
@mmusich 

> > Then a correct ordering can be guaranteed by changing `AlignmentProducerAsAnalyzer` to write the files in `endProcessBlock()` instead of `endJob()` and to produce something into ProcessBlock (e.g. empty `struct AlignmentToken{};`), and changing `MillePedeDQMModule` to consume that product.
> 
> Thanks for the suggestion.
> Can you point to some documentation and / or example on how that should be done?

In a sense DQM itself serves as an example (but see more specific suggestions below).

> Also `AlignmentProducerAsAnalyzer` (as the name is betraying) is an `EDAnalyzer` 
> 
> Does your suggestion imply it should become an `EDProducer`?

Yes, it would have to become an `EDProducer`, just like in DQM all `DQMEDAnalyzer`s are actually `EDProducer`s. 

Overall the necessary changes would be, in addition,
* Make `AlignmentProducerAsAnalyzer` to use [`edm::Accumulator`](https://twiki.cern.ch/twiki/bin/view/CMSPublic/FWMultithreadedFrameworkOneModuleInterface#edm_Accumulator), and [`edm::EndProcessBlockProducer`](https://twiki.cern.ch/twiki/bin/view/CMSPublic/FWMultithreadedFrameworkOneModuleInterface#edm_EndProcessBlockProducer) abilities
  * `Accumulator` in order to keep the module running for each event, similar to `DQMEDAnalyzer`
* Create a "token" class similar to [`DQMToken`](https://github.com/cms-sw/cmssw/blob/master/DataFormats/Histograms/interface/DQMToken.h), I'll call it `AlignmentToken` in the following but the name can be "anything"
   * In principle `DQMToken` could be used as well, but I think a separate product type would make the intention more clear, and with that there would be no interference with some DQM code consuming all `DQMToken`s in `ProcessBlock` in the future
* Make `AlignmentProducerAsAnalyzer` to produce the `AlignmentToken` in `endProcessBlockProduce()`
* Make `MillePedeDQMModule` to consume the `AlignmentToken` in the `edm::Transition::EndProcessBlock` transition. The consumes declaration is sufficient, there is no need to read the actual token.

**Comment by mmusich** [comment]
@makortel 
Thanks for the detailed recipe. I think I have something working for the `AlignmentProducerAsAnalyzer` but it's not very clear to me what is the right syntax to do this

> Make` MillePedeDQMModule` to consume the` AlignmentToken` in the `edm::Transition::EndProcessBlock` transition. The consumes declaration is sufficient, there is no need to read the actual token.

I've tried:
```diff
diff --git a/Alignment/MillePedeAlignmentAlgorithm/plugins/MillePedeDQMModule.cc b/Alignment/MillePedeAlignmentAlgorithm/plugins/MillePedeDQMModule.cc
index ea391c5e9ac..a8fca1594bf 100644
--- a/Alignment/MillePedeAlignmentAlgorithm/plugins/MillePedeDQMModule.cc
+++ b/Alignment/MillePedeAlignmentAlgorithm/plugins/MillePedeDQMModule.cc
@@ -30,8 +30,14 @@
 /*** Thresholds from DB ***/
 #include "CondFormats/DataRecord/interface/AlignPCLThresholdsRcd.h"
 
+/*** Necessary Framework infrastructure ***/
+#include "FWCore/Framework/interface/ProcessBlock.h"
+#include "DataFormats/Alignment/interface/AlignmentToken.h"
+
 MillePedeDQMModule ::MillePedeDQMModule(const edm::ParameterSet& config)
-    : mpReaderConfig_(config.getParameter<edm::ParameterSet>("MillePedeFileReader")) {}
+  : mpReaderConfig_(config.getParameter<edm::ParameterSet>("MillePedeFileReader")) {
+  consumes<AlignmentToken, edm::Transition::EndProcessBlock>();
+}
 
 MillePedeDQMModule ::~MillePedeDQMModule() {}
```
but that clearly doesn't even compile. 
Having a look in `cmssw` I see similar usages e.g. here: 

https://github.com/cms-sw/cmssw/blob/e9fd14517b7cd1514dfd5704a003b82fe6ad4c62/DQM/SiStripMonitorClient/plugins/SiStripOfflineDQM.cc#L71
 
what's the syntactic equivalent for `ProcessBlock` of `edm::InRun` ?

**Comment by Dr15Jones** [comment]
>what's the syntactic equivalent for ProcessBlock of edm::InRun ?

Your syntax was correct, however you stll need to pass an `edm::InputTag` as an argument to the `consumes` function.

**Comment by mmusich** [comment]
@Dr15Jones perhaps I am doing something very dumb but using:
```C++
+  consumes<AlignmentToken, edm::Transition::EndProcessBlock>(edm::InputTag("alignmentToken"));
```
I am still getting this compilation error: https://paste.in/VlCgCb

**Comment by Dr15Jones** [comment]
The second template argument isn't a `Transition`, it is a `edm::BranchType`. So you want
```
consumes<AlignmentToken, edm::InProcess>(edm::InputTag("alignmentToken"));
```

Sorry I missed that initially.

**Comment by makortel** [comment]
> The second template argument isn't a `Transition`, it is a `edm::BranchType`.

Right, apologies for the confusion in my recipe https://github.com/cms-sw/cmssw/issues/31381#issuecomment-689079333 (which I just updated), without thinking I was assuming that `consumes()` would work also with `Transition` as `produces()` does.

**Comment by mmusich** [comment]
@Dr15Jones @makortel thanks for the suggestions.
Indeed with using `consumes<AlignmentToken, edm::InProcess>(edm::InputTag("alignmentToken"));` it compiles, though I am still unable to make it run in the correct order. I prepared a draft PR https://github.com/cms-sw/cmssw/pull/31411, if you can give a quick look and suggest what is still missing. 
Thanks!

**Comment by mmusich** [comment]
This issue has been solved by #31381, AlCa and DQM conveners might want to sign this.

**Comment by christopheralanwest** [comment]
+alca

**Comment by jfernan2** [comment]
+1
