### ISSUE TITLE
NanoGEN pending action items

### ISSUE THREAD

**Issue by silviodonato** [cms-sw/cmssw#31393]
This issue is to keep track of the action items about NanoGEN https://github.com/cms-sw/cmssw/pull/30306

-  creation of a dedicated workflow to test in the runTheMatrix and unit test (https://github.com/cms-sw/cmssw/pull/30306#issuecomment-684820124)
- PDF update (https://github.com/cms-sw/cmssw/pull/30306#issuecomment-687268037)

**Comment by silviodonato** [comment]
assign xpog

**Comment by silviodonato** [comment]
assign @kdlong

**Comment by qliphy** [comment]
also assign generators

**Comment by mariadalfonso** [comment]
change of PDF done here https://github.com/cms-sw/cmssw/pull/31946

+xpog

**Comment by mariadalfonso** [comment]
+xpog

**Comment by agrohsje** [comment]
+1

**Comment by silviodonato** [comment]
see wf `546.0`, `547.0`, `548.0`
