### ISSUE TITLE
Create repository cms-data/Alignment-OfflineValidation

### ISSUE THREAD

**Issue by silviodonato** [cms-sw/cmssw#31421]
Please create a new cms-data repository for `Alignment/OfflineValidation` https://github.com/cms-data/Alignment-OfflineValidation .
See https://github.com/cms-sw/cmssw/pull/31376#discussion_r484300888

**Comment by mrodozov** [comment]
Hi @silviodonato , see this comment:
https://github.com/cms-sw/cms-bot/blob/master/categories.py#L11
only L1 can create repos. This includes you :)
`CMSSW_L1 = ["dpiparo", "silviodonato","qliphy"]`
Once created I can touch it later but I can't create it

**Comment by silviodonato** [comment]
> Hi @silviodonato , see this comment:
> https://github.com/cms-sw/cms-bot/blob/master/categories.py#L11
> only L1 can create repos. This includes you :)
> `CMSSW_L1 = ["dpiparo", "silviodonato","qliphy"]`
> Once created I can touch it later but I can't create it

Thanks, I've made https://github.com/cms-data/Alignment-OfflineValidation

**Comment by mrodozov** [comment]
you can close this issue now :)
