### ISSUE TITLE
[Simulation] SimG4Core/PrintGeomInfo/test/python/ Configurations Cleanup

### ISSUE THREAD

**Issue by ianna** [cms-sw/cmssw#31465]
Most configuration fragments in `SimG4Core/PrintGeomInfo/test/python/` cannot be run due to references to an obsolete geometries or conditions.

Proposed solution:
To avoid diverging make all test configurations run in an IB. Please, see `DDCMS` package for detailed implementation of a run script:
```bash
0001 #!/bin/sh
0002 
0003 function die { echo $1: status $2 ; exit $2; }
0004 
0005 echo " testing DetectorDescription/DDCMS"
0006 
0007 export tmpdir=${LOCAL_TMP_DIR:-/tmp}
0008 echo "===== Test \"python UnitsCheck.py testUnits.xml\" ===="
0009 python ${LOCAL_TEST_DIR}/python/UnitsCheck.py ${LOCAL_TEST_DIR}/data/testUnits.xml
0010 
0011 for entry in "${LOCAL_TEST_DIR}/python"/test*
0012 do
0013   echo "===== Test \"cmsRun $entry \" ===="
0014   (cmsRun $entry) || die "Failure using cmsRun $entry" $?
0015 done
0016 
```

**Comment by makortel** [comment]
assign simulation

**Comment by civanch** [comment]
@ianna , these tests are long unfortunately, I do not see a reason run them permanently but I fully agree, that they should be checked and fixed if needed.

**Comment by ianna** [comment]
closed in favour of https://github.com/cms-sw/cmssw/issues/34663
