### ISSUE TITLE
[DD4hep] DT Geometry Validation

### ISSUE THREAD

**Issue by ianna** [cms-sw/cmssw#31464]
```test/python/validateDTGeometry_cfg.py``` that is a part of IB tests does not report an error if the newly build geometry is incomplete or non existent.

1. The test succeeds if a line 169 in `DTGeometryBuilder` is commented out, e.g. there is no DT geometry built. The resulting `validateDTGeometry.root` file is empty.
```c++
void DTGeometryBuilder::build(DTGeometry& geom,
                              const DDDetector* det,
                              const MuonGeometryConstants& num,
                              const dd4hep::SpecParRefs& refs) {
  Volume top = det->worldVolume();
  DDFilteredView fview(det, top);
  fview.mergedSpecifics(refs);
  //buildGeometry(fview, geom, num);
}
```

2. The test succeeds if a part of the DT geometry is built. Here is an example where only 10 chambers are built, so the comparison is done only for these 10 chambers.
```c++
void DTGeometryBuilder::buildGeometry(DDFilteredView& fview, DTGeometry& geom, const MuonGeometryConstants& num) const {
  bool doChamber = fview.firstChild();
  int x = 0;
  
  while (doChamber) {
    DTChamber* chamber = buildChamber(fview, num);
    x++;
    if (x > 10) return;

```
<img width="535" alt="Screenshot 2020-09-15 at 14 06 22" src="https://user-images.githubusercontent.com/1390682/93209126-ef7a2480-f75d-11ea-9cbe-958f0565545c.png">
<img width="537" alt="Screenshot 2020-09-15 at 14 06 40" src="https://user-images.githubusercontent.com/1390682/93209129-f0ab5180-f75d-11ea-8ccc-f7b1d1f7a869.png">

Proposed solution:
1. Throw an exception if there is no geometry to compare.
2. Reverse the logic: take original DT geometry first and compare it with the DD4hep one.

@cvuosalo and @slomeo - FYI 
This issue replaces the one I've closed previously because it describes the problem in more details.

**Comment by slomeo** [comment]
@ianna : something like "if geom is not empty then build" and "else throw an exception"? in line 169 of DTGeometryBuilder?

**Comment by makortel** [comment]
assign geometry

**Comment by civanch** [comment]
@ianna, is it fixed?

**Comment by ianna** [comment]
closed in favour of https://github.com/cms-sw/cmssw/issues/34663
