### ISSUE TITLE
MessageLogger constructors should accept string_view

### ISSUE THREAD

**Issue by kpedro88** [cms-sw/cmssw#31475]
Currently, passing `std::string_view` when constructing e.g. `edm::LogInfo` produces the following errors:
```
error: no matching function for call to 'edm::LogInfo::LogInfo(std::string_view&)'

note: candidate: 'edm::LogInfo::LogInfo(const string&)'
     explicit LogInfo(std::string const& id)
```

This is because `std::string_view` can't be implicitly converted to `std::string`.

It would be useful to provide constructors for MessageLogger instances that accept `std::string_view`. In some cases, this would avoid extra string constructions.

**Comment by kpedro88** [comment]
assign core

**Comment by makortel** [comment]
By quick look changing the `std::string const&` to `std::string_view` would allow to avoid one string creation when `edm::LogInfo` is constructed with `char const *`. The string argument is anyway copied in
https://github.com/cms-sw/cmssw/blob/916cb3d20213734a0465240720c8c8c392b92eac/FWCore/MessageLogger/src/ErrorObj.cc#L159-L163

**Comment by makortel** [comment]
Done in #31498.
