### ISSUE TITLE
[Geometry][Tracker] 2021 Scenario Needs to be Checked

### ISSUE THREAD

**Issue by ianna** [cms-sw/cmssw#31519]
Evgueni Tcherniaev repots subtraction of non-overlapping solids in the Tracker. Note also the Shape differences between `+ `and `-` **Z** in the last four snapshots.

@ghugo83 and @vargasa - FYI

```
TIBModHybLedge0x7fd6a4fb2d80          = TIBModHybLedgeNoCut0x7fd6a2b06b00 - TIBModHybLedgeCut0x7fd6a2b06b80
 TIBAOHLedge0x7fd6a2b090a0             = TIBAOHLedgeNoCut0x7fd6a2b67e00 - TIBAOHLedgeCut0x7fd6a2b67e80
 TIDWheelFixCutted0x7fd6a2b09f00       = TIDWheelFix0x7fd6a2c67680 - TIDWheelFixHole0x7fd6a2c67980
 TIDRing1FlatCableCutted0x7fd6a2b09fa0 = TIDRing1FlatCable0x7fd6a2c67f80 - TIDRing1FlatCableHole0x7fd6a2c68100
 TOBRodCentralL0x7fd6a2b0a4a0          = TOBRod1Cent0x7fd6a4d7b980 - TOBRod2Cent0x7fd6a4d7ba00
 TOBRodL0x7fd6a2b0a400                 = TOBRodout0x7fd6a4d7b780 - TOBRodin0x7fd6a4d7b800
 TOBRodCentralH0x7fd6a2b0a540          = TOBRod1Cent0x7fd6a2cee400 - TOBRod2Cent0x7fd6a2cee480
 TOBRodH0x7fd6a2b0a720                 = TOBRodout0x7fd6a2cee300 - TOBRodin0x7fd6a2cee380
```
Please, see the attached snapshots of the SubtractionSolids.
<img width="871" alt="Screenshot 2020-09-21 at 13 19 04" src="https://user-images.githubusercontent.com/1390682/93762051-28f3d980-fc0f-11ea-88a3-f1405d8a3c49.png">
<img width="872" alt="Screenshot 2020-09-21 at 13 20 19" src="https://user-images.githubusercontent.com/1390682/93762062-2beeca00-fc0f-11ea-9ae7-96d2fa5cdfcb.png">
<img width="871" alt="Screenshot 2020-09-21 at 13 21 10" src="https://user-images.githubusercontent.com/1390682/93762064-2c876080-fc0f-11ea-82e8-d839db283145.png">
<img width="875" alt="Screenshot 2020-09-21 at 13 21 53" src="https://user-images.githubusercontent.com/1390682/93762067-2d1ff700-fc0f-11ea-851d-c8d61734d949.png">
<img width="871" alt="Screenshot 2020-09-21 at 13 26 01" src="https://user-images.githubusercontent.com/1390682/93762069-2db88d80-fc0f-11ea-9e23-2a38d1d15750.png">
<img width="873" alt="Screenshot 2020-09-21 at 13 27 25" src="https://user-images.githubusercontent.com/1390682/93762070-2e512400-fc0f-11ea-8b23-375f33ddf6ca.png">
<img width="872" alt="Screenshot 2020-09-21 at 13 28 03" src="https://user-images.githubusercontent.com/1390682/93762071-2e512400-fc0f-11ea-94e7-9361dbdf2fc0.png">
<img width="871" alt="Screenshot 2020-09-21 at 13 28 39" src="https://user-images.githubusercontent.com/1390682/93762072-2ee9ba80-fc0f-11ea-9de1-48ab3556fdc6.png">

**Comment by ianna** [comment]
@civanch - FYI

**Comment by makortel** [comment]
assign geometry

**Comment by vargasa** [comment]
Hi @ianna, thanks. I can have a look

**Comment by vargasa** [comment]
Hi @ianna 

I see no difference between `dd` and `dd4hep` so I assume this is not a migration related issue.

Is the task to substitute the existing `SubtractionSolid` with an `UnionSolid`? (as in https://github.com/cms-sw/cmssw/issues/31520#issuecomment-696190608) 

Is this "only" about performance? or Why exactly there is an issue with the `SubstractionSolid` usage?

**Comment by ianna** [comment]
> Hi @ianna
> 
> I see no difference between `dd` and `dd4hep` so I assume this is not a migration related issue.
> 
> Is the task to substitute the existing `SubtractionSolid` with an `UnionSolid`? (as in [#31520 (comment)](https://github.com/cms-sw/cmssw/issues/31520#issuecomment-696190608))
> 
> Is this "only" about performance? or Why exactly there is an issue with the `SubstractionSolid` usage?

@vargasa - the issue is unrelated to the migration. It can be performance related or it is an indication of a bug. I'll give you an example. Say, a `SubtractionSolid` is defined as a `BoxA` minus a `BoxB`. If these boxes do not overlap, the `SubtractionSolid` is equal to a `BoxA`. Either the `BoxA` can replace the `SubtractionSolid` in the definition, or it's a bug where the `BoxB` position is incorrect.

BTW is it intentional that `TOBRodH` and `TOBRodL` are not symmetric?

**Comment by vargasa** [comment]
> Say, a `SubtractionSolid` is defined as a `BoxA` minus a `BoxB`. If these boxes do not overlap, the `SubtractionSolid` is equal to a `BoxA`. Either the `BoxA` can replace the `SubtractionSolid` in the definition, or it's a bug where the `BoxB` position is incorrect.

I only have access the final shape. Can Evgueni provide more details about how to reproduce the issue? i.e How can we see that `TIBModHybLedgeNoCut` and `TIBModHybLedgeCut` (etc) are non-overlapping?. I see them [here](https://cmssdt.cern.ch/lxr/source/Geometry/TrackerCommonData/data/tibmodpar.xml#0112) but from there it's not obvious to me there's an issue with the definition

> BTW is it intentional that `TOBRodH` and `TOBRodL` are not symmetric?

I may be missing something but they look symmetrical to me (snapshots below), @mmusich Can you comment on this please?

![Screenshot from 2020-09-21 16-17-54](https://user-images.githubusercontent.com/16821717/93817281-ba227a80-fc26-11ea-9d93-dac6a51821a3.png)

![Screenshot from 2020-09-21 16-17-31](https://user-images.githubusercontent.com/16821717/93817282-ba227a80-fc26-11ea-8cf6-4e8dbcd6db3b.png)

![Screenshot from 2020-09-21 16-17-10](https://user-images.githubusercontent.com/16821717/93817336-ceff0e00-fc26-11ea-8178-8cafe73499c4.png)

**Comment by ianna** [comment]
> I only have access the final shape. Can Evgueni provide more details about how to reproduce the issue? i.e How can we see that `TIBModHybLedgeNoCut` and `TIBModHybLedgeCut` (etc) are non-overlapping?. I see them [here](https://cmssdt.cern.ch/lxr/source/Geometry/TrackerCommonData/data/tibmodpar.xml#0112) but from there it's not obvious to me there's an issue with the definition

There is no magic bullet. To enable easier debugging I can suggest to change a `SubtractionSolid` to a `UnionSolid` and see where the constituting shapes are with respect to each other. Another option is to add both constituting shapes separately.

**Comment by vargasa** [comment]
@ianna  I dumped the 2015 geometry using `9_2_0` and they look the same:

![Screenshot from 2020-09-23 18-13-30](https://user-images.githubusercontent.com/16821717/94075238-d2ca9600-fdc8-11ea-917e-16dcf00697b1.png)

![Screenshot from 2020-09-23 18-13-24](https://user-images.githubusercontent.com/16821717/94075240-d2ca9600-fdc8-11ea-8312-10ae09968271.png)

Both complement each other, 

![Screenshot from 2020-09-23 18-21-05](https://user-images.githubusercontent.com/16821717/94075739-bda23700-fdc9-11ea-8963-f35e55b68da3.png)
![Screenshot from 2020-09-23 18-20-56](https://user-images.githubusercontent.com/16821717/94075742-bda23700-fdc9-11ea-9f34-8aa78b978495.png)
![Screenshot from 2020-09-23 18-21-15](https://user-images.githubusercontent.com/16821717/94075738-bd09a080-fdc9-11ea-8956-aab746f61df7.png)

@cvuosalo I'm not sure how this may affect https://github.com/cms-sw/cmssw/pull/31529

**Comment by vargasa** [comment]
Regarding the `SubtractionSolid`:

##### From [`TGeoMgrFromDdd`](https://cmssdt.cern.ch/lxr/source/Fireworks/Geometry/plugins/TGeoMgrFromDdd.cc#0447) logs I see:

`TOBRodH`
```
TGeoMgrFromDdd::createShape with name: tobrodpar:TOBRodL and solid: tobrodpar:TOBRodL   SubtractionSolid: 
        DDSolidShape index:11, name: SubtractionSolid
TGeoMgrFromDdd::createShape with name: tobrodpar:TOBRodout and solid: tobrodpar:TOBRodout   Box:  xhalf[cm]=8.25 yhalf[cm]=1 zhalf[cm]=55.9
        DDSolidShape index:1, name: Box
TGeoMgrFromDdd::createShape solid tobrodpar:TOBRodout has been created.
        Left: tobrodpar:TOBRodout   Box:  xhalf[cm]=8.25 yhalf[cm]=1 zhalf[cm]=55.9
        boolSolid translation: (0,5,549)
TGeoMgrFromDdd::createShape with name: tobrodpar:TOBRodin and solid: tobrodpar:TOBRodin   Box:  xhalf[cm]=8.25 yhalf[cm]=0.5 zhalf[cm]=1
        DDSolidShape index:1, name: Box
TGeoMgrFromDdd::createShape solid tobrodpar:TOBRodin has been created.
        Right: tobrodpar:TOBRodin   Box:  xhalf[cm]=8.25 yhalf[cm]=0.5 zhalf[cm]=1
        boolSolid translation: (0,5,549)
TGeoMgrFromDdd::createShape solid tobrodpar:TOBRodL has been created.

```

`TOBRodH`
```
TGeoMgrFromDdd::createShape with name: tobrodpar:TOBRodH and solid: tobrodpar:TOBRodH   SubtractionSolid: 
        DDSolidShape index:11, name: SubtractionSolid
TGeoMgrFromDdd::createShape with name: tobrodpar:TOBRodout and solid: tobrodpar:TOBRodout   Box:  xhalf[cm]=8.25 yhalf[cm]=1 zhalf[cm]=55.9
        DDSolidShape index:1, name: Box
TGeoMgrFromDdd::createShape solid tobrodpar:TOBRodout has been created.
        Left: tobrodpar:TOBRodout   Box:  xhalf[cm]=8.25 yhalf[cm]=1 zhalf[cm]=55.9
        boolSolid translation: (0,-5,-549)
TGeoMgrFromDdd::createShape with name: tobrodpar:TOBRodin and solid: tobrodpar:TOBRodin   Box:  xhalf[cm]=8.25 yhalf[cm]=0.5 zhalf[cm]=1
        DDSolidShape index:1, name: Box
TGeoMgrFromDdd::createShape solid tobrodpar:TOBRodin has been created.
        Right: tobrodpar:TOBRodin   Box:  xhalf[cm]=8.25 yhalf[cm]=0.5 zhalf[cm]=1
        boolSolid translation: (0,-5,-549)
TGeoMgrFromDdd::createShape solid tobrodpar:TOBRodH has been created.
```
If I understand correctly the `TGeoBBox` constructor they (`TOBRodout` and `TOBRodin`) are in fact overlapping, as [a common origin is provided](https://cmssdt.cern.ch/lxr/source/Fireworks/Geometry/plugins/TGeoMgrFromDdd.cc#454). @ianna, we may need more information to reproduce the issue reported :confused:

**Comment by vargasa** [comment]
The subtraction is subtle but it is there: 

![Screenshot from 2020-09-23 20-33-48](https://user-images.githubusercontent.com/16821717/94087608-314d3f80-fddc-11ea-8f59-2e28e1fcb35a.png)

**Comment by ianna** [comment]
It's the same for the 2017 geometry scenario:

<img width="948" alt="Screenshot 2020-09-23 at 19 17 45" src="https://user-images.githubusercontent.com/1390682/94046951-a6674780-fdd1-11ea-9b13-14cad3be0eb4.png">
<img width="944" alt="Screenshot 2020-09-23 at 19 18 01" src="https://user-images.githubusercontent.com/1390682/94046954-a7987480-fdd1-11ea-8095-b48264a933a9.png">

**Comment by cvuosalo** [comment]
@ianna @vargasa I am understanding that issues raised here are long-standing and were in Run 2. The subtraction solid seems to be valid. The size mismatch may be intentional and not a mistake, or, at least, it might be mistake that was also in Run 2.
Please confirm that the DB payloads PR should not wait for this issue and should go forward.

**Comment by ianna** [comment]
@cvuosalo - yes, the geometry DB payloads (#31529) can go ahead without the resolution of this issue.

**Comment by etcherniaev** [comment]
This issue is false positive, the subtractions are correct. The issue can be closed.

**Comment by ianna** [comment]
+1
