### ISSUE TITLE
Integration of PPS alignment code

### ISSUE THREAD

**Issue by jan-kaspar** [cms-sw/cmssw#31518]
Dear AlCa colleauges (@pohsun, @tlampen, @tocheng, @christopheralanwest),

PPS is preparing an integration of its alignment code to CMSSW. It has two parts:
  * relative alignment among sensors in one PPS arm - this is to be run manually on special data samples
  * global alignment of PPS detectors wrt the LHC beam - here we plan two execution regimes
    * "automatic" for quick analysis eventually in PCLs (targeting promt reco)
    * "manual" for best possible results (targeting a re-reco)

For historical reasons we currently develop the code in the following packages:
  * relative alignment: ``Alignment/PPSTrackBased``
  * global alignment: ``CalibPPS/Alignment``

I find it somewhat non-uniform - what would be your suggestion?

**Comment by makortel** [comment]
assign alca

**Comment by jan-kaspar** [comment]
After some discussions, I'd like to propose that all calibration code for PPS is put under CalibPPS. In particular,
 * relative alignment in: CalibPPS/AlignmentRelative
 * global alignment in: CalibPPS/AlignmentGlobal

Unless you have comments, I will proceed and close this issue in few days.

**Comment by jan-kaspar** [comment]
As no comments have been raised, I am closing the issue.
