### ISSUE TITLE
[Geometry][Muon] 2021 Geometry Scenario Needs to be Checked

### ISSUE THREAD

**Issue by ianna** [cms-sw/cmssw#31520]
Evgueni Tcherniaev repots subtraction of non-overlapping solids in the **Muon barrel SuperLayer Gas** volumes:
```
 MBSLPhiGas_b0x7fd6a2943c60 = MBSLPhiGas_a0x7fd6a23ddf00 - MBSLPhiIBeamWing0x7fd6a23ddf80
 MBSLPhiGas_c0x7fd6a2943d00 = MBSLPhiGas_b0x7fd6a2943c60 - MBSLPhiIBeamWing0x7fd6a23e6000
 MBSLPhiGas_d0x7fd6a2943da0 = MBSLPhiGas_c0x7fd6a2943d00 - MBSLPhiIBeamWing0x7fd6a23e6080
 MBSLPhiGas0x7fd6a2943e40   = MBSLPhiGas_d0x7fd6a2943da0 - MBSLPhiIBeamWing0x7fd6a23e6100

 MB1SLZGas_b0x7fd6a2943ee0 = MB1SLZGas_a0x7fd6a23e6800 - MB1SLZIBeamWing0x7fd6a23e6880
 MB1SLZGas_c0x7fd6a2943f80 = MB1SLZGas_b0x7fd6a2943ee0 - MB1SLZIBeamWing0x7fd6a23e6900
 MB1SLZGas_d0x7fd6a2944020 = MB1SLZGas_c0x7fd6a2943f80 - MB1SLZIBeamWing0x7fd6a23e6980
 MB1SLZGas0x7fd6a29440c0   = MB1SLZGas_d0x7fd6a2944020 - MB1SLZIBeamWing0x7fd6a23e6a00
 MB2SLZGas_b0x7fd6a29443e0 = MB2SLZGas_a0x7fd6a2352d80 - MB2SLZIBeamWing0x7fd6a2352e00
 MB2SLZGas_c0x7fd6a2944480 = MB2SLZGas_b0x7fd6a29443e0 - MB2SLZIBeamWing0x7fd6a2352e80
 MB2SLZGas_d0x7fd6a2944520 = MB2SLZGas_c0x7fd6a2944480 - MB2SLZIBeamWing0x7fd6a2352f00
 MB2SLZGas0x7fd6a29445c0   = MB2SLZGas_d0x7fd6a2944520 - MB2SLZIBeamWing0x7fd6a2352f80
 MB3SLZGas_b0x7fd6a2944660 = MB3SLZGas_a0x7fd6a24a3580 - MB3SLZIBeamWing0x7fd6a24a3600
 MB3SLZGas_c0x7fd6a2944700 = MB3SLZGas_b0x7fd6a2944660 - MB3SLZIBeamWing0x7fd6a24a3680
 MB3SLZGas_d0x7fd6a29447a0 = MB3SLZGas_c0x7fd6a2944700 - MB3SLZIBeamWing0x7fd6a24a3700
 MB3SLZGas0x7fd6a2944840   = MB3SLZGas_d0x7fd6a29447a0 - MB3SLZIBeamWing0x7fd6a24a3780

 MBChimSLPhiGas_b0x7fd6a2944160 = MBChimSLPhiGas_a0x7fd6a2339380 - MBChimSLPhiIBeamWing0x7fd6a2339500
 MBChimSLPhiGas_c0x7fd6a2944200 = MBChimSLPhiGas_b0x7fd6a2944160 - MBChimSLPhiIBeamWing0x7fd6a2339580
 MBChimSLPhiGas_d0x7fd6a29442a0 = MBChimSLPhiGas_c0x7fd6a2944200 - MBChimSLPhiIBeamWing0x7fd6a2339600
 MBChimSLPhiGas0x7fd6a2944340   = MBChimSLPhiGas_d0x7fd6a29442a0 - MBChimSLPhiIBeamWing0x7fd6a2339680
```
<img width="870" alt="Screenshot 2020-09-21 at 13 47 31" src="https://user-images.githubusercontent.com/1390682/93763196-47f36b00-fc11-11ea-9bd5-13744af71eef.png">

and ME:
```
 ME12AlumFrameTempBlock0x7fd6a2945420 = ME12AlumFrameBlock0x7fd6a2587680 - ME12AlumFrameSubtraction0x7fd6a2587900
 ME12AlumFrame0x7fd6a29454c0          = ME12AlumFrameTempBlock0x7fd6a2945420 - ME12AlumFrameSubtraction0x7fd6a2587b80
 ME13AlumFrameTempBlock0x7fd6a2945560 = ME13AlumFrameBlock0x7fd6a2588080 - ME13AlumFrameSubtraction0x7fd6a2588300
 ME13AlumFrame0x7fd6a2945600          = ME13AlumFrameTempBlock0x7fd6a2945560 - ME13AlumFrameSubtraction0x7fd6a2588580
 ME21AlumFrameTempBlock0x7fd6a29456a0 = ME21AlumFrameBlock0x7fd6a2588a80 - ME21AlumFrameSubtraction0x7fd6a2588d00
 ME21AlumFrame0x7fd6a2945740          = ME21AlumFrameTempBlock0x7fd6a29456a0 - ME21AlumFrameSubtraction0x7fd6a2588f80
 ME22AlumFrameTempBlock0x7fd6a29457e0 = ME22AlumFrameBlock0x7fd6a2589480 - ME22AlumFrameSubtraction0x7fd6a2589700
 ME22AlumFrame0x7fd6a2945880          = ME22AlumFrameTempBlock0x7fd6a29457e0 - ME22AlumFrameSubtraction0x7fd6a2589980
 ME31AlumFrameTempBlock0x7fd6a2944e80 = ME31AlumFrameBlock0x7fd6a2577e80 - ME31AlumFrameSubtraction0x7fd6a2578100
 ME31AlumFrame0x7fd6a2944fc0          = ME31AlumFrameTempBlock0x7fd6a2944e80 - ME31AlumFrameSubtraction0x7fd6a2578380
 ME32AlumFrameTempBlock0x7fd6a2945060 = ME32AlumFrameBlock0x7fd6a2578880 - ME32AlumFrameSubtraction0x7fd6a2578b00
 ME32AlumFrame0x7fd6a2945100          = ME32AlumFrameTempBlock0x7fd6a2945060 - ME32AlumFrameSubtraction0x7fd6a2578d80
 ME41AlumFrameTempBlock0x7fd6a29451a0 = ME41AlumFrameBlock0x7fd6a2586280 - ME41AlumFrameSubtraction0x7fd6a2586500
 ME41AlumFrame0x7fd6a2945240          = ME41AlumFrameTempBlock0x7fd6a29451a0 - ME41AlumFrameSubtraction0x7fd6a2586780
 ME42AlumFrameTempBlock0x7fd6a29452e0 = ME42AlumFrameBlock0x7fd6a2586c80 - ME42AlumFrameSubtraction0x7fd6a2586f00
 ME42AlumFrame0x7fd6a2945380          = ME42AlumFrameTempBlock0x7fd6a29452e0 - ME42AlumFrameSubtraction0x7fd6a2587180

```

@slomeo - FYI
@civanch - FYI

**Comment by slomeo** [comment]
@ianna : I'm sorry but I didn't understand what is the problem?

**Comment by makortel** [comment]
assign geometry

**Comment by ianna** [comment]
> @ianna : I'm sorry but I didn't understand what is the problem?

There are two problems.

The first one is that we have a `SubtractionSolid` volumes in 2021 scenario where the two solids that constitute it do not overlap. That means that a final shape can be replaced with a first child.

The second problem is that this particular issue has been fixed for Run 2 geometry in https://github.com/cms-sw/cmssw/pull/15674/ on 13 Sep 2016.

<img width="1092" alt="Screenshot 2020-09-21 at 17 18 53" src="https://user-images.githubusercontent.com/1390682/93785786-c14d8680-fc2e-11ea-9f15-5105f2208068.png">

```xml
0069     <SolidSection label="mbCommon.xml">
0070         <!-- ####  DTBX Gas cell for non chimney chambers -->
0071         <!--%% Effective gas volume: This volume should not include the Ibeam horizontal bars (those that make the 'I' shape; without them it would be a '|') -->
0072         <Box name="MBSLPhiGas_a" dx="20.35*mm" dz="[MBGas_height]" dy="[MBSLPhiBareWire_length]"/>
0073         <Box name="MBSLPhiIBeamWing" dx="3.175*mm" dz="0.65*mm" dy="[MBSLPhiBareWire_length]"/>
0074         <SubtractionSolid name="MBSLPhiGas_b">
0075             <rSolid name="MBSLPhiGas_a"/>
0076             <rSolid name="MBSLPhiIBeamWing"/>
0077             <rRotation name="rotations:000D"/>
0078             <Translation x="17.175*mm" z="5.1*mm" y="0.*fm"/>
0079         </SubtractionSolid>
0080         <SubtractionSolid name="MBSLPhiGas_c">
0081             <rSolid name="MBSLPhiGas_b"/>
0082             <rSolid name="MBSLPhiIBeamWing"/>
0083             <rRotation name="rotations:000D"/>
0084             <Translation x="17.175*mm" z="-5.1*mm" y="0.*fm"/>
0085         </SubtractionSolid>
0086         <SubtractionSolid name="MBSLPhiGas_d">
0087             <rSolid name="MBSLPhiGas_c"/>
0088             <rSolid name="MBSLPhiIBeamWing"/>
0089             <rRotation name="rotations:000D"/>
0090             <Translation x="-17.175*mm" z="5.1*mm" y="0.*fm"/>
0091         </SubtractionSolid>
0092         <SubtractionSolid name="MBSLPhiGas">
0093             <rSolid name="MBSLPhiGas_d"/>
0094             <rSolid name="MBSLPhiIBeamWing"/>
0095             <rRotation name="rotations:000D"/>
0096             <Translation x="-17.175*mm" z="-5.1*mm" y="0.*fm"/>
0097         </SubtractionSolid>

```

**Comment by ianna** [comment]
<img width="711" alt="Screenshot 2020-09-21 at 17 23 53" src="https://user-images.githubusercontent.com/1390682/93786150-420c8280-fc2f-11ea-80d2-55b79c5bbbde.png">

**Comment by ianna** [comment]
Here is a snapshot of my presentation explaining the situation :-)
<img width="718" alt="Screenshot 2020-09-21 at 17 26 35" src="https://user-images.githubusercontent.com/1390682/93786639-da0a6c00-fc2f-11ea-8f76-d32cb1824499.png">
<img width="715" alt="Screenshot 2020-09-21 at 17 26 44" src="https://user-images.githubusercontent.com/1390682/93786643-daa30280-fc2f-11ea-867b-2eed6f7723bf.png">
<img width="717" alt="Screenshot 2020-09-21 at 17 26 52" src="https://user-images.githubusercontent.com/1390682/93786644-db3b9900-fc2f-11ea-9e6b-e315ae05051a.png">
<img width="715" alt="Screenshot 2020-09-21 at 17 26 59" src="https://user-images.githubusercontent.com/1390682/93786645-db3b9900-fc2f-11ea-8126-1e697b7f4f87.png">
<img width="715" alt="Screenshot 2020-09-21 at 17 27 07" src="https://user-images.githubusercontent.com/1390682/93786647-db3b9900-fc2f-11ea-94ad-4bfe5bb51583.png">
<img width="718" alt="Screenshot 2020-09-21 at 17 27 15" src="https://user-images.githubusercontent.com/1390682/93786648-dbd42f80-fc2f-11ea-8d6d-21788bee5deb.png">
<img width="715" alt="Screenshot 2020-09-21 at 17 27 25" src="https://user-images.githubusercontent.com/1390682/93786650-dbd42f80-fc2f-11ea-8af2-13c33307ce33.png">
<img width="716" alt="Screenshot 2020-09-21 at 17 27 33" src="https://user-images.githubusercontent.com/1390682/93786651-dc6cc600-fc2f-11ea-8b39-3970eadd662b.png">

**Comment by slomeo** [comment]
@ianna : looking at your first comment (i.e the list made by Evgueni Tcherniaev), it seems that MBSLPhiGas_a and MBSLPhiIBeamWing are not overlapping so the subtraction (for example MBSLPhiGas_b0x7fd6a2943c60 = MBSLPhiGas_a0x7fd6a23ddf00 - MBSLPhiIBeamWing0x7fd6a23ddf8) doesn't make sense (i.e its better to perform a union solid) do I understand well?
P.S which the git name of Evgueni Tcherniaev?

**Comment by ianna** [comment]
> @ianna : looking at your first comment (i.e the list made by Evgueni Tcherniaev), it seems that MBSLPhiGas_a and MBSLPhiIBeamWing are not overlapping so the subtraction (for example MBSLPhiGas_b0x7fd6a2943c60 = MBSLPhiGas_a0x7fd6a23ddf00 - MBSLPhiIBeamWing0x7fd6a23ddf8) doesn't make sense (i.e its better to perform a union solid) do I understand well?

yes.

> P.S which the git name of Evgueni Tcherniaev?

@civanch might know

**Comment by slomeo** [comment]
@ianna : ok, just another question always related (for example) to "MBSLPhiGas_b0x7fd6a2943c60 = MBSLPhiGas_a0x7fd6a23ddf00 - MBSLPhiGas_a0x7fd6a23ddf8". Looking at the code when SubtractionSolid will become UnionSolid, as MBSLPhiGas_a and MBSLPhiGas_a don't overlap, this means that <Translation x="17.175*mm" z="5.1*mm" y="0.*fm"/> will be <Translation x="0*fm" z="0*fm" y="0.*fm"/>, Am I correct?

**Comment by ianna** [comment]
> @ianna : ok, just another question always related (for example) to "MBSLPhiGas_b0x7fd6a2943c60 = MBSLPhiGas_a0x7fd6a23ddf00 - MBSLPhiGas_a0x7fd6a23ddf8". Looking at the code when SubtractionSolid will become UnionSolid, as MBSLPhiGas_a and MBSLPhiGas_a don't overlap, this means that Translation x=17.175mm z=5.1mm y=0.fm will be Translation x=0fm z=0fm y=0.fm, Am I correct?

@slomeo - as you can see fro the xml and from the snapshots four `SubtractionSolid`s (lines #72-97) are replaced by one `UnionSolid` (lines #72-80) and their constituting shapes are not the same.

**Comment by slomeo** [comment]
ianna: ok, I understood, but as regards "MB1SLZGas_b0x7fd6a2943ee0 = MB1SLZGas_a0x7fd6a23e6800 - MB1SLZIBeamWing0x7fd6a23e6880" I see that inside data/Run2/mb1.xml ( your old PR #15674) and data/mb1/2015/v2/mb1.xml (i.e Scenario 2021) the MB1SLZGas definitions are identical (i.e SubstractionSolid). What do I have to do? Do I edit them in the same way of MBSLPhiGas?

**Comment by ianna** [comment]
> @ianna : ok, just another question always related (for example) to "MBSLPhiGas_b0x7fd6a2943c60 = MBSLPhiGas_a0x7fd6a23ddf00 - MBSLPhiGas_a0x7fd6a23ddf8". Looking at the code when SubtractionSolid will become UnionSolid, as MBSLPhiGas_a and MBSLPhiGas_a don't overlap, this means that Translation x=17.175mm z=5.1mm y=0.fm will be Translation x=0fm z=0fm y=0.fm, Am I correct?

@slomeo - I think, these are also good candidates to be replaced (e.g. one `UnionSolid` instead of 4 `SubtractionSolids`). There are quite a few of these volumes:
<img width="934" alt="Screenshot 2020-09-24 at 11 23 16" src="https://user-images.githubusercontent.com/1390682/94126892-7fa02400-fe58-11ea-93fe-6c8b605f617c.png">

and it looks like the `SubtractionSolid` does not do much, however, replacing it with a `Box` may introduce overlaps:
<img width="937" alt="Screenshot 2020-09-24 at 11 22 34" src="https://user-images.githubusercontent.com/1390682/94127091-c7bf4680-fe58-11ea-8af6-e7486c0de7bd.png">

**Comment by slomeo** [comment]
@ianna : ok I already wrote new lines for MBSLPhiGas and MBChimSLPhiGas as you did in PR #15674. My question is for MB1 (probably MB2, MB3, MB4). It seems that, for MB1, the MB1SLZGas definition is the same for both mb1.xml files (Run2 and Run3).  Do I have to do the same job for MB1SLZGas as I did for MBSLPhiGas?

**Comment by ianna** [comment]
> @ianna : ok I already wrote new lines for MBSLPhiGas and MBChimSLPhiGas as you did in PR #15674. My question is for MB1 (probably MB2, MB3, MB4). It seems that, for MB1, the MB1SLZGas definition is the same for both mb1.xml files (Run2 and Run3). Do I have to do the same job for MB1SLZGas as I did for MBSLPhiGas?

yes, I think so. Thanks!

**Comment by etcherniaev** [comment]
@slomeo, @ianna : implementation of Boolean solids in G4 is rather complex. For this  reason, from performance point of view, it is always better to apply other solutions instead of Boolean operations. For example, "holes" can be defined as daughter volumes with different from the mother volume material.

In this particular case, I would suggest to consider also usage of G4ExtrudedSolid. Or, in case if this volume does not contains daughter volumes, describe it as three separate boxes.

**Comment by ianna** [comment]
> @slomeo, @ianna : implementation of Boolean solids in G4 is rather complex. For this reason, from performance point of view, it is always better to apply other solutions instead of Boolean operations. For example, "holes" can be defined as daughter volumes with different from the mother volume material.
> 
> In this particular case, I would suggest to consider also usage of G4ExtrudedSolid. Or, in case if this volume does not contains daughter volumes, describe it as three separate boxes.

@etcherniaev - these volumes are very small, numerous, and sensitive. Three box solution will lead to tons of rounding overlaps for sure ;-)

**Comment by slomeo** [comment]
> > @slomeo, @ianna : implementation of Boolean solids in G4 is rather complex. For this reason, from performance point of view, it is always better to apply other solutions instead of Boolean operations. For example, "holes" can be defined as daughter volumes with different from the mother volume material.
> > In this particular case, I would suggest to consider also usage of G4ExtrudedSolid. Or, in case if this volume does not contains daughter volumes, describe it as three separate boxes.
> 
> @etcherniaev - these volumes are very small, numerous, and sensitive. Three box solution will lead to tons of rounding overlaps for sure ;-)

@etcherniaev @ianna : I think that it's better (for now) to proceed with UnionSolid instead of SubtractionSolid in order to not create other problems with overlaps.. I don't need them (again) :-)

**Comment by slomeo** [comment]
@ianna : as regards ME, I searched (for example) ME12AlumFrameTemp and I found some results (please see: https://cmssdt.cern.ch/lxr/search?%21v=CMSSW_11_2_X_2020-09-23-2300&_filestring=&_string=ME12AlumFrameTemp). What is the right file to edit? csc.xml, mf.xml...

**Comment by cvuosalo** [comment]
@ianna @slomeo From this discussion, I understand that the subtraction solids mentioned are non-optimal but mostly harmless and have existed in Run 2.
Please confirm that the geometry DB payloads (#31529) can go ahead without the resolution of this issue. When this issue is fully resolved, we can consider whether to upload new DB payloads. At that time, PPS geometry might also be completed and give another reason for uploading the geometry payloads.

**Comment by ianna** [comment]
@civanch - yes,  the geometry DB payloads (#31529) can go ahead without the resolution of this issue.

**Comment by etcherniaev** [comment]
This issue is false positive, the subtractions are correct. The issue can be closed.

**Comment by ianna** [comment]
+1

**Comment by slomeo** [comment]
@ianna : Do I stop my job on this issue?

**Comment by ianna** [comment]
@slomeo - please, continue. Even if it's not an issue any more it will improve the Muon geometry description. Thanks!

**Comment by slomeo** [comment]
@ianna : ok, but for ME list what is the right file to edit? csc.xml, mf.xml...

**Comment by ianna** [comment]
> @ianna : ok, but for ME list what is the right file to edit? csc.xml, mf.xml...

@slomeo - I'd suggest you make a new version 3 of the following files:
```
Geometry/MuonCommonData/data/csc/2021/v2/csc.xml
Geometry/MuonCommonData/data/mf/2021/v2/mf.xml
```
