### ISSUE TITLE
[Geometry][BRM] 2021 Geometry Scenario Needs to be Checked

### ISSUE THREAD

**Issue by ianna** [cms-sw/cmssw#31521]
Evgueni Tcherniaev repots subtraction of non-overlapping solids in the BSC description:
```
 BSC2AlPadCoversFront0x7fd6a29459c0 = BSC2AlPadCoversFront0x7fd6a25d9880 - BSC2AlPadCoversFront0x7fd6a2590400
 BSC2AlPadCoversBack0x7fd6a2945b00  = BSC2AlPadCoversBack0x7fd6a25d9a00 - BSC2AlPadCoversBack0x7fd6a2590480
 BSC2Pad0x7fd6a2945a60              = BSC2Pad0x7fd6a25d9700 - BSC2Pad0x7fd6a2590380
 BSCPadActive0x7fd6a2945e20         = BSCPadActive0x7fd6a25fe180 - BSCPadActive0x7fd6a2590780
 BSCPad0x7fd6a2945c40               = BSCPad0x7fd6a25d9d00 - BSCPad0x7fd6a2590600
 BSCAlPadCoversBack0x7fd6a2945ce0   = BSCAlPadCoversBack0x7fd6a25d9e80 - BSCAlPadCoversBack0x7fd6a2590680
 BSCAlPadCoversFront0x7fd6a2945d80  = BSCAlPadCoversFront0x7fd6a25fe000 - BSCAlPadCoversFront0x7fd6a2590700
 BSCPadAir0x7fd6a2945ba0            = BSCPadAir0x7fd6a25d9b80 - BSCPadAir0x7fd6a2590500
```
<img width="873" alt="Screenshot 2020-09-21 at 13 53 27" src="https://user-images.githubusercontent.com/1390682/93764047-be449d00-fc12-11ea-8a82-3326f05b103b.png">
<img width="873" alt="Screenshot 2020-09-21 at 13 54 57" src="https://user-images.githubusercontent.com/1390682/93764058-c0a6f700-fc12-11ea-948c-451fab7c4902.png">

@civanch - these are only a few volumes and they are quite far away.

**Comment by makortel** [comment]
assign geometry

**Comment by etcherniaev** [comment]
All 8 solids are similar, they are constrcuted as: G4Tubs - G4Box. All 8 G4Tubs solids are 45 degree sectors of a tube. All 8 G4Box solids are rotated around Z and then shifted along X.

@ianna : for me it looks like an implementation	of TruncTubs, could you check.

Below is the data for the first solid
`BSC2AlPadCoversFront0x7fd6a29459c0 = BSC2AlPadCoversFront0x7fd6a25d9880 - BSC2AlPadCoversFront0x7fd6a2590400`

**Dump for solid - BSC2AlPadCoversFront0x7fd6a25d9880**
Solid type: G4Tubs
Parameters:
    inner radius : 97 mm
    outer radius : 310 mm
    half length Z: 4 mm
    starting phi : 0 degrees
    delta phi    : 45 degrees

**Dump for solid - BSC2AlPadCoversFront0x7fd6a2590400**
Solid type: G4Box
Parameters:
   half length X: 482.2468247692255 mm
   half length Y: 482.2468247692255 mm
   half length Z: 4.4 mm

**Rotation :**
0.382683 0.92388  0
-0.92388 0.382683 0
0        0        1
**Translation :** (-424.98, 0, 0)

**Comment by civanch** [comment]
@ianna , @cvuosalo , is this fixed?

**Comment by ianna** [comment]
closed in favour of https://github.com/cms-sw/cmssw/issues/34663
