### ISSUE TITLE
Unit test failure in  DQM/Integration ARM IB

### ISSUE THREAD

**Issue by mrodozov** [cms-sw/cmssw#31539]
There is consistent failure in the Arm IB in DQM/Integration failing in :
`DQM/Integration/test/runtest.sh: line 19: 37857 Segmentation fault `
which is actually failing in 
DQMServices/FileIO/plugins/DQMFileSaverPB.cc
when calling this function
https://github.com/cms-sw/cmssw/blob/master/DQMServices/FileIO/plugins/DQMFileSaverPB.cc#L342
from within this one:
https://github.com/cms-sw/cmssw/blob/master/DQMServices/FileIO/plugins/DQMFileSaverPB.cc#L259

The ASAN IB is reporting problems in 3 others within DQM/Integration but not this test.

**Comment by makortel** [comment]
assign dqm

**Comment by jfernan2** [comment]
@mrodozov  do we have any log or any recipe to reproduce the error? Thanks!

**Comment by mrodozov** [comment]
unfortunately the only way to reproduce it is on Arm it doesn't manifest itself even in ASAN IBs :/ 
The recipe is to just run the unit test on Arm (having an account)
I can add your user because I have sudo rights is one way of doing it

**Comment by jfernan2** [comment]
OK, but then I would need some tutorial or twiki on Arm too, I know nothing about it :-|

**Comment by mrodozov** [comment]
not much difference actually, at least not from debugging a program viewpoint.
they(cern techlab people) voided my sudo rights, we have to ask for you to be added in the "normal" way as a user

**Comment by jfernan2** [comment]
OK, is there any JIRA project or so where I should request an account for my username?

**Comment by mrodozov** [comment]
Use this link
https://cern.service-now.com/service-portal?id=functional_element&name=Hardware-Labs
and submit a request explaining you are from CMS and you want access to 
techlab-arm64-thunderx2-02 
techlab-arm64-thunderx-02
machines for dev purposes.

**Comment by mrodozov** [comment]
when you get your account use the singularity image 
`/cvmfs/cms.cern.ch/common/cmssw-cc7`
to do your setup. you should be able to make a folder under /build

**Comment by jfernan2** [comment]
Thanks @mrodozov 

> to do your setup. you should be able to make a folder under /build

but it seems I cannot:
[techlab-arm64-thunderx-02] /build $ mkdir jfernan2
mkdir: cannot create directory ‘jfernan2’: Permission denied

However I see you folder in there...

**Comment by mrodozov** [comment]
well I see I can't create a folder under /home , you could ask the admins for a /build/$USER folder or use /afs space 
I see /afs its mounted

**Comment by jfernan2** [comment]
Sorry @mrodozov but I get the following error:
bash-4.2$  /cvmfs/cms.cern.ch/common/cmssw-env --cmsos cc7
/cvmfs/cms.cern.ch/common/cmssw-env: line 92: singularity: command not found


This is what I did:

sh /cvmfs/cms.cern.ch/common/cmssw-cc7
scramv1 project CMSSW_11_2_X_2020-09-29-1100
cd CMSSW_11_2_X_2020-09-29-1100/src
/cvmfs/cms.cern.ch/common/cmssw-env --cmsos cc7
Thanks

**Comment by mrodozov** [comment]
try
```
/cvmfs/cms.cern.ch/common/cmssw-cc7
scram -a slc7_aarch64_gcc820 p CMSSW_11_2_X_2020-09-29-1100
source /cvmfs/cms.cern.ch/cmsset_default.sh
cmsenv
```
when you are running /cvmfs/cms.cern.ch/common/cmssw-env --cmsos cc7
after you've started singularity with /cvmfs/cms.cern.ch/common/cmssw-cc7
you are trying to run singularity within singularity I don't think thats possible

**Comment by jfernan2** [comment]
I have reproduced the error and it is on: TestDQMOnlineClient-gem_dqm_sourceclient
This seems related to the problem spotted in Online DQM at 11_1_X here:
https://github.com/cms-sw/cmssw/pull/31447#issuecomment-693455946

which has not been forwardported yet. I have just requested a forwardport to GEM developers

**Comment by jfernan2** [comment]
GEM created this PR to fix this issue:
https://github.com/cms-sw/cmssw/pull/31623
I have tested it in ARM and the crash disappears

**Comment by jfernan2** [comment]
This issue is solved by: https://github.com/cms-sw/cmssw/pull/31623

**Comment by mrodozov** [comment]
I don't see the unit test failing anymore. Closing this
