### ISSUE TITLE
A new ZeroMaterial GeometryFileRcd payload is needed for the Run-3 scenario

### ISSUE THREAD

**Issue by mmusich** [cms-sw/cmssw#31550]
Posting here, as per comment https://github.com/cms-sw/cmssw/pull/31529#issuecomment-696881700. 
A new `ExtentedZeroMaterial` labeled database tag for `GeometryFileRcd`, based on the `Extended2021ZeroMaterial` scenario introduced in #31082 is needed in order to process some samples for Run-3 calibration studies [*]

[*] https://hypernews.cern.ch/HyperNews/CMS/get/prep-ops/7302.html

**Comment by ianna** [comment]
assign geometry

**Comment by civanch** [comment]
+1

I believe it is done.

**Comment by mmusich** [comment]
@civanch is it?
Can you point me to the payloads?

**Comment by civanch** [comment]
Then I may be wrong - XML exist but I do not know about payloads. @cvuosalo , can you, please, comment?

**Comment by civanch** [comment]
hold

**Comment by cvuosalo** [comment]
The scripts have been developed to make the payloads, but I don't think the payloads have been uploaded. @bsunanda Could you please comment on the zero material payloads?

**Comment by mmusich** [comment]
I think this has been address within the dd4hep migration at: https://github.com/cms-sw/cmssw/pull/35920
@civanch please unhold so that the issue can be signed and closed.
Thanks.

**Comment by cvuosalo** [comment]
Yes, this issue has been resolved.

**Comment by mmusich** [comment]
@civanch please unhold
