### ISSUE TITLE
[Geometry][Tracker][RECO] Legacy GeometricDetExtra to be removed

### ISSUE THREAD

**Issue by ianna** [cms-sw/cmssw#31567]
`GeometricDetExtra` was used to store and access extra information for `GeometricDet` s such as its material, its volume, its weight, etc. None of it is used in RECO any more. Is it time to remove legacy `GeometricDetExtra`, its `PGeometricDetExtra` schema and a DB payload?

@vargasa, @ghugo83  - Could you, please, discuss it with Tracker DPG? Thanks
@cvuosalo - FYI

**Comment by makortel** [comment]
assign geometry

**Comment by cvuosalo** [comment]
Isn't `GeometricDetExtra` harmless at this point? Yes, we can clean it eventually, but why should its removal be a priority at this time?

**Comment by mmusich** [comment]
@cmsbuild, please test

**Comment by ianna** [comment]
> Isn't `GeometricDetExtra` harmless at this point? Yes, we can clean it eventually, but why should its removal be a priority at this time?

If it stays, we’d need to port it to DD4HEP. This is quite a bit of work.

**Comment by cvuosalo** [comment]
@ianna Can `GeometricDetExtra` be disabled and ignored for DD4hep but retained for now for the old DD? If it is not used, I am not understanding why it has to be completely deleted immediately.

**Comment by ianna** [comment]
> @ianna Can `GeometricDetExtra` be disabled and ignored for DD4hep but retained for now for the old DD? If it is not used, I am not understanding why it has to be completely deleted immediately.

I though that we do not want to diverge too much? The work has been done already. Why would we want to delay it?

**Comment by cvuosalo** [comment]
This issue is taking up time and effort that we need to direct to fixing the DD4hep workflows. It also creates risk of bugs and unforeseen consequences from deleted records.
I don't understand how this issue became a higher priority than urgent bug-fixing.

**Comment by mmusich** [comment]
Out of curiosity, why this issue does not target also the MTD counterpart DB schema: `PGeometricTimingDetExtra` ?  
Comparing the classes they look carbon-copies!

https://github.com/cms-sw/cmssw/blob/05c82a35723127a5f959b3fab75a261613c31fe7/CondFormats/GeometryObjects/interface/PGeometricTimingDetExtra.h#L1-L32

vs 

https://github.com/cms-sw/cmssw/blob/05c82a35723127a5f959b3fab75a261613c31fe7/CondFormats/GeometryObjects/interface/PGeometricDetExtra.h#L1-L32

**Comment by ianna** [comment]
> Out of curiosity, why this issue does not target also the MTD counterpart DB schema: `PGeometricTimingDetExtra` ?
> Comparing the classes they look carbon-copies!
> 
> https://github.com/cms-sw/cmssw/blob/05c82a35723127a5f959b3fab75a261613c31fe7/CondFormats/GeometryObjects/interface/PGeometricTimingDetExtra.h#L1-L32
> 
> vs
> 
> https://github.com/cms-sw/cmssw/blob/05c82a35723127a5f959b3fab75a261613c31fe7/CondFormats/GeometryObjects/interface/PGeometricDetExtra.h#L1-L32

different DPGs? ;-)

Jokes aside, you are right - it absolutely should.

**Comment by ianna** [comment]
@mmusich - thanks for bringing it up. I've opened a separate issue to track it https://github.com/cms-sw/cmssw/issues/31822

**Comment by vargasa** [comment]
Addressed in https://github.com/cms-sw/cmssw/pull/31729. See also https://github.com/cms-sw/cmssw/issues/31869#issuecomment-713365246

**Comment by ianna** [comment]
+1

@vargasa - excellent! You deleted roughly one thousand lines - well done! Thanks

**Comment by ianna** [comment]
+1
