### ISSUE TITLE
[Geometry][Muon] SubtractionSolids can be replaced with Union

### ISSUE THREAD

**Issue by ianna** [cms-sw/cmssw#31576]
@slomeo - FYI

See https://github.com/cms-sw/cmssw/issues/31520

**Comment by ianna** [comment]
assign geometry

**Comment by slomeo** [comment]
@ianna : ok, the MB list is fixed (in my private directory), now I'm looking for ME (please see my question in #31520 )

**Comment by cvuosalo** [comment]
@slomeo Is this issue resolved?

**Comment by slomeo** [comment]
> @slomeo Is this issue resolved?

@cvuosalo I fixed only Muon Barrel, I have to do the same job for ME.

**Comment by slomeo** [comment]
@ianna @cvuosalo  : as the PRs #31903 and #31683 are merged I think you can close this PR.

**Comment by cvuosalo** [comment]
+1
