### ISSUE TITLE
Error in testDD4hepFilteredViewLevel and testDD4hepFilteredViewGoTo

### ISSUE THREAD

**Issue by silviodonato** [cms-sw/cmssw#31604]
We are getting two errors in the unit test of `DetectorDescription/DDCMS` in `testDD4hepFilteredViewLevel` and `testDD4hepFilteredViewGoTo` since `CMSSW_11_2_X_2020-09-27-0000`, after having merged #31508.
It turned out that the error is related to the hard-coded level numbers in the unit test (eg. https://github.com/cms-sw/cmssw/blob/master/DetectorDescription/DDCMS/test/DDFilteredView.goto.cppunit.cc#L73).
More details in  #31508.
@ianna could you have a look to this issue?

**Comment by silviodonato** [comment]
assign geometry

**Comment by ianna** [comment]
@silviodonato - I do not see errors in the PR IB linked here. I'll check in the local area.

**Comment by qliphy** [comment]
@ianna  You can find more info from #31574 
https://github.com/cms-sw/cmssw/pull/31574#issuecomment-699906732

**Comment by ianna** [comment]
@qliphy - thanks! I've reproduced the error in a local area. The scenario has changed. I'm afraid, the construction order is not guaranteed, so the reference point has shifted.

**Comment by ianna** [comment]
please, take https://github.com/cms-sw/cmssw/pull/31605 that fixes it.

**Comment by cvuosalo** [comment]
@ianna Can this problem happen again? How can we prevent it?

**Comment by ianna** [comment]
+1

**Comment by ianna** [comment]
> @ianna Can this problem happen again? How can we prevent it?

Good question. Yes, it will definitely happen when the geometry changes: a geo history reflects a child number at a level, but if there is another child created before, the geo history of the first one will shift.

Will it happen if geometry does not change? Yes, when we will start using multiple processes. We cannot guarantee the order of parsing and creation.

**Comment by ianna** [comment]
Here is an explanation why the unit test failed: two copies of a `ZDCtoFP4201` and a `ZDCtoFP4202` volumes were added shifting the Tracker from the 4th to the 6th position.
Here is the snapshot of a 2021 geometry tree in the IB:
<img width="570" alt="Screenshot 2020-09-29 at 13 16 24" src="https://user-images.githubusercontent.com/1390682/94557216-8ff03e80-025e-11eb-9fda-b9e3dda4af3c.png">
where it used to be only two copies of a `ZDCtoFP420` volume:
<img width="500" alt="Screenshot 2020-09-29 at 13 19 34" src="https://user-images.githubusercontent.com/1390682/94557221-91ba0200-025e-11eb-9ca2-a7979c0fb0fb.png">

**Comment by ianna** [comment]
@silviodonato - IMHO, this can be closed now. Thanks!

**Comment by silviodonato** [comment]
@ianna I would keep this issue open to remind us that the tests are currently incompatible with geometry changes and multiple processes. If you prefer we can close this issue and open another one. Of course this issue is much less urgent than the DD4HEP migration, but I think it is good to keep a reminder.

**Comment by ianna** [comment]
> @ianna I would keep this issue open to remind us that the tests are currently incompatible with geometry changes and multiple processes. If you prefer we can close this issue and open another one. Of course this issue is much less urgent than the DD4HEP migration, but I think it is good to keep a reminder.

@silviodonato - the unit test does exactly what it is suppose to do - it fails if the geometry changes ;-)

**Comment by cvuosalo** [comment]
@smuzaffar Could the unit test described in this issue be added to the PR tests for any change to "Geometry" packages?

**Comment by silviodonato** [comment]
> Could the unit test described in this issue be added to the PR tests for any change to "Geometry" packages?

@cvuosalo you can include manually this unit test by adding `DetectorDescription/DDCMS` in the PR test (see http://cms-sw.github.io/cms-bot-cmssw-cmds.html)
```
test parameters:
addpkg = DetectorDescription/DDCMS
```

**Comment by silviodonato** [comment]
> > @ianna I would keep this issue open to remind us that the tests are currently incompatible with geometry changes and multiple processes. If you prefer we can close this issue and open another one. Of course this issue is much less urgent than the DD4HEP migration, but I think it is good to keep a reminder.
> 
> @silviodonato - the unit test does exactly what it is suppose to do - it fails if the geometry changes ;-)

Ok, so I assume that you want to keep the test as it is. If somebody wants to change the geometry, s/he needs also to update the unit test. As @cvuosalo pointed out, it would be good to run this test anytime we change a `Geometry` package
