### ISSUE TITLE
Backport of PR #31553 to production releases

### ISSUE THREAD

**Issue by jordan-martins** [cms-sw/cmssw#31611]
[Description]: pLHE requests are failing validation and submission from McM, as well as local tests are unable to be performed.
[Action]: Backport PR [1] to all production releases:

- CMSSW_10_2_24
- CMSSW_10_3_2
- CMSSW_10_6_12
- CMSSW_10_6_17_patch1
- CMSSW_7_5_8_patch7
- CMSSW_8_0_31
- CMSSW_9_3_18
- CMSSW_9_3_9_patch1
- CMSSW_9_4_11

Thanks a lot,
PdmV Team.
[1] https://github.com/cms-sw/cmssw/pull/31553

**Comment by silviodonato** [comment]
Thanks @jordan-martins 
Let me add the link to the pLHE campaigns https://cms-pdmv.cern.ch/mcm/campaigns?prepid=*pLHE*&page=0&shown=63&limit=100

**Comment by silviodonato** [comment]
we will discuss about this at the ORP meeting

**Comment by silviodonato** [comment]
Issue solved by https://github.com/cms-sw/cmsdist/pull/6283
Please note that it works even for the very old releases.
Eg.
```
$ cmsrel CMSSW_5_3_11
$ cd CMSSW_5_3_11/src
$ cmsenv
$ which cmsLHEtoEOSManager.py
/cvmfs/cms.cern.ch/share/overrides/bin/cmsLHEtoEOSManager.py
```
