### ISSUE TITLE
testFWCoreSharedMemoryMonitorThreadSignals had ERRORS in 10_6_X

### ISSUE THREAD

**Issue by silviodonato** [cms-sw/cmssw#31624]
We get error in a `/FWCore/SharedMemory/` unit test in 10_6_X since `CMSSW_10_6_X_2020-09-24-1100`, even since no PRs were merged between `CMSSW_10_6_X_2020-09-23-2300` and `CMSSW_10_6_X_2020-09-24-1100`

```
===== Test "testFWCoreSharedMemoryMonitorThreadSignals" ====
Wrong return value  127

---> test testFWCoreSharedMemoryMonitorThreadSignals had ERRORS
```

![image](https://user-images.githubusercontent.com/6177433/94667566-44e23400-030f-11eb-91c3-7f82e8e5be47.png)

**Comment by silviodonato** [comment]
assign core
I don't know if this was expected or so. Anyhow I just wanted to keep track of it

**Comment by makortel** [comment]
I see this unit test failing already in CMSSW_10_6_X_2020-09-23-1100, which is the oldest one reported at the moment.

**Comment by Dr15Jones** [comment]
The unix code 127 means the bash command trying to be executed can not be found. From the script we get

https://github.com/cms-sw/cmssw/blob/master/FWCore/SharedMemory/test/test_monitor_thread_signals.sh#L9-L12

where the test `testFWCoreSharedMemoryMonitorThread` is expected to be on PATH (the comment says SCRAM does that for tests). I'm guessing that CMSSW_10_6 is before scram started adding the tests to PATH.

**Comment by Dr15Jones** [comment]
Another possibility is there is a special command in the BuildFile.xml

https://github.com/cms-sw/cmssw/blob/CMSSW_10_6_X/FWCore/SharedMemory/test/BuildFile.xml#L15-L17

perhaps CMSSW_10_6 scram doesn't understand the `PRE_TEST` flag?

**Comment by makortel** [comment]
I see the test still fails in 10_6_X, but not in 11_0_X. Probably not worth of trying to understand better (like what exactly fixed it).

**Comment by makortel** [comment]
+core

**Comment by makortel** [comment]
@cmsbuild, please close
