### ISSUE TITLE
[DD4hep][Simulation] Muon Sim Hits are ~ 10x off

### ISSUE THREAD

**Issue by ianna** [cms-sw/cmssw#31632]
```
cmsRun $CMSSW_RELEASE_BASE/src/SimG4Core/Configuration/test/dd4hep_ZMM_Run3_Step1_cfg.py
```
produces a non-empty file, but the RPC (in yellow) and DT (in red) simhits look a factor off their intended positions. Pixel simhits (in green) look where they suppose to be.

@slomeo - FYI Could you, please, have a look? You'll need a tomorrows IB and #31573

<img width="1453" alt="Screenshot 2020-09-30 at 19 14 55" src="https://user-images.githubusercontent.com/1390682/94718956-c7401780-0352-11eb-8c6f-2b7dc0ad4910.png">

**Comment by makortel** [comment]
assign geometry, simulation

**Comment by dildick** [comment]
Hi @ianna Is there any indication that the CSC or GEM simhits are off their nominal positions by using DD4HEP? Thanks!

**Comment by ianna** [comment]
@dildick - I did not see the GEM sim hits, I've run only a few events.

**Comment by slomeo** [comment]
ianna: I'll check it but it's very strange... all geometry validation scripts (i.e DD vs DD4hep) for Muon System were fine, maybe a problem related to the Muon Sensitive Detectors?

**Comment by slomeo** [comment]
@ianna : did you run the same test for DDD?

**Comment by ianna** [comment]
> @ianna: I'll check it but it's very strange... all geometry validation scripts (i.e DD vs DD4hep) for Muon System were fine, maybe a problem related to the Muon Sensitive Detectors?

Yes, it could be - the RPhi view shows the his aligned, but scaled down, while RZ looks very strange.

**Comment by ianna** [comment]
> @ianna : did you run the same test for DDD?

No, I did not

**Comment by slomeo** [comment]
@ianna  @civanch : is it possible to perform two simulations (DDD vs DD4hep) with the same initial seed (same scenario and fragment) and cross check the results? From Muon System I had this request but the cross check asked was for the step4 and not for sim hits.

**Comment by slomeo** [comment]
> Yes, it could be - the RPhi view shows the his aligned, but scaled down, while RZ looks very strange.
@ianna : what is the command to obtain your screen shot? cmsShow.....

**Comment by civanch** [comment]
@slomeo , no chance to run in regression. When build DD4Hep geometry we do different operations and numerically final numbers are not guaranteed to agree with DDD. If any value in geometry is different on a very small value simulation cannot be identical.

**Comment by cvuosalo** [comment]
@slomeo Are you working on this issue? It is high priority.

**Comment by slomeo** [comment]
@cvuosalo : no, I'm not working on it because I had understood that I have to wait the PR #31573 will be merged. If I'm wrong  I'll start tomorrow.

**Comment by slomeo** [comment]
@cvuosalo : the PR #31573 was merged 11 hours ago. Only now I saw it

**Comment by ianna** [comment]
+1
