### ISSUE TITLE
cleanup/optimize pp on HI in miniAOD/PAT, EI (and maybe RECO) steps to align better with heavy ions needs

### ISSUE THREAD

**Issue by slava77** [cms-sw/cmssw#31647]
A few items still not needed in heavy ions were left over during integration of #30898 
- [x] a few pp_on_aa modifier calls are now redundant and should be removed in configurations that are no longer a part of HI miniAOD (see miniAOD_tools.py methods applied with `(~_hiGeneral).toModify`
    - (noted on Feb 11, 2021) some cleanup was made in #31893
- [ ] EI step should be either updated to use `akCs4PFJets` or considered for elimination from pp_on_aa workflows
    - (noted on Feb 11, 2021) EI is on the way out based on #32643
- [x] puppi is still used in some parts of miniAOD (patPhoton isolation), but is possibly present in parts of RECO; this should be cleaned up
    - (noted on Feb 11, 2021) fixed in #31893

Possible computational level cleanup (e.g. test on 140.5611)
- [x] `isolatedTracks` timing does not scale well in more central events (it takes 9% of miniAOD CPU time in 140.5611): check if all computations are needed in HI context
    - (noted on Feb 11, 2021) fixed in #31727
- [x] slimmedJets tagInfos can take fairly large fraction of miniAOD file size in central events (25% in 140.5611): either preselections or slimming should be considered to mitigate this
    - (noted on Feb 11, 2021) fixed in #31893

@mandrenguyen 
feel free to post other known modules or sequences that may be lingering from pp setup at non-negligible cost and are not actually needed

**Comment by slava77** [comment]
assign reconstruction,xpog

**Comment by slava77** [comment]
+1

I updated the notes in the issue description

**Comment by mariadalfonso** [comment]
+xpog
