### ISSUE TITLE
Update EventSetupRecordDataGetter to use esConsumes

### ISSUE THREAD

**Issue by Dr15Jones** [cms-sw/cmssw#31716]
The module EventSetupRecordDataGetter needs to be changed to use esConsumes. This will require new infrastructure as the module presently decides during the Event loop which EventSetup data products are available and then requests them. We may need to add a facility like `callWhenNewProductsRegistered` to the EventSetup system.

**Comment by Dr15Jones** [comment]
assign core

**Comment by Dr15Jones** [comment]
NOTE: instead of doing something like `callWhenNewProductsRegistered`, we could instead just have a callback once all EventSetup data products have been declared but before we finalize the esConsumes info. This works since no ED module is allowed to generate an ES data product therefore we do not need to worry about the issue in the ED system where a produces call can trick another produces call via the `callWhenNewProductsRegistered` mechanism.

**Comment by Dr15Jones** [comment]
Looks like we could add a call to a virtual function in `EDConsumerBase::updateLookup` at the very beginning of that routine to allow setting of `esConsumes` based on what is available in the EventSetup.

**Comment by Dr15Jones** [comment]
Done in #31775

**Comment by makortel** [comment]
+1
