### ISSUE TITLE
SLHCUpgradeSimulations/Geometry tests broken

### ISSUE THREAD

**Issue by vargasa** [cms-sw/cmssw#31739]
##### 1
```
cmsRun SLHCUpgradeSimulations/Geometry/trackerModuleInfo_Phase2_cfg.py

----- Begin Fatal Exception 09-Oct-2020 13:02:39 CDT-----------------------
An exception of category 'ConfigFileReadError' occurred while
   [0] Processing the python configuration file named trackerModuleInfo_Phase2_cfg.py
Exception Message:
 unknown python problem occurred.
ImportError: No module named CommonInputs_cff

At:
  /cvmfs/cms-ib.cern.ch/week1/slc7_amd64_gcc820/cms/cmssw/CMSSW_11_2_X_2020-10-09-1100/python/FWCore/ParameterSet/Config.py(683): load
  trackerModuleInfo_Phase2_cfg.py(9): <module>

----- End Fatal Exception -------------------------------------------------
```
##### 2
```
cmsRun SLHCUpgradeSimulations/Geometry/print_geominfo_cfg.py 
----- Begin Fatal Exception 09-Oct-2020 13:10:50 CDT-----------------------
An exception of category 'ConfigFileReadError' occurred while
   [0] Processing the python configuration file named print_geominfo_cfg.py
Exception Message:
 unknown python problem occurred.
ImportError: No module named Phase1_R34F16_cmsSimIdealGeometryXML_cff

At:
  /cvmfs/cms-ib.cern.ch/week1/slc7_amd64_gcc820/cms/cmssw/CMSSW_11_2_X_2020-10-09-1100/python/FWCore/ParameterSet/Config.py(683): load
  print_geominfo_cfg.py(9): <module>

----- End Fatal Exception -------------------------------------------------
```
##### 3
```
cmsRun SLHCUpgradeSimulations/Geometry/writeFile_phase2_cfg.py 
----- Begin Fatal Exception 09-Oct-2020 13:16:27 CDT-----------------------
An exception of category 'ConfigFileReadError' occurred while
   [0] Processing the python configuration file named writeFile_phase2_cfg.py
Exception Message:
 unknown python problem occurred.
ImportError: No module named GeometryExtended2023D17Reco_cff

At:
  /cvmfs/cms-ib.cern.ch/week1/slc7_amd64_gcc820/cms/cmssw/CMSSW_11_2_X_2020-10-09-1100/python/FWCore/ParameterSet/Config.py(683): load
  writeFile_phase2_cfg.py(5): <module>

----- End Fatal Exception -------------------------------------------------
```

**Comment by makortel** [comment]
assign geometry, upgrade

**Comment by kpedro88** [comment]
-1
the only actual unit test in `SLHCUpgradeSimulations/Geometry` is https://github.com/cms-sw/cmssw/blob/0da1310fe6ca207b80cd9107072ddeec5b63b49b/SLHCUpgradeSimulations/Geometry/test/BuildFile.xml#L36-L39
any other files in the `test` directory are considered unmaintained, and the default expectation at any given time is that they're broken

**Comment by civanch** [comment]
@kpedro88 , should broken tests we removed or only marked "work to be done in future"?
This issue may be closed.

**Comment by kpedro88** [comment]
If some developers still find them useful and update them periodically, they could stay in the repo.

I just really want to emphasize that central maintenance is not provided for anything not automatically tested (as unit test or matrix test).

**Comment by cvuosalo** [comment]
-1

**Comment by vargasa** [comment]
I'm pointing this out mainly for the record, some (broken?, unused?) code in this package is using `GeometricDetExtra` that's in the process of being removed

**Comment by makortel** [comment]
How about making an attempt to remove that code?

**Comment by mmusich** [comment]
Actually problem n. 3) is trivial to fix and the underlying source code is still functional and potentially still useful. I'll make a PR that restores it shortly.
Problem 1) is coupled to not trivial code changes necessary to cope with the actual Tracker phase2 geometry, some more work is needed. 
Problem 2) is related to code not existing anymore in current CMSSW so can indeed be removed.
