### ISSUE TITLE
[DD4hep][Simulation] Define a dd4hep Era workflow for RelVal

### ISSUE THREAD

**Issue by ianna** [cms-sw/cmssw#31753]
Define a dd4hep Era workflow for RelVal
  
as discussed during Sim meeting

**Comment by makortel** [comment]
assign geometry, simulation, pdmv

**Comment by cvuosalo** [comment]
DD4hep workflows 11624.911 and 11642.911 are running successfully in PR and IB tests. In CMSSW_11_3_X_2020-12-08-1100, they were confirmed to run successfully to completion with 1000 events in both single- and multi-threaded modes.

I think this issue can be closed.

**Comment by cvuosalo** [comment]
+1

**Comment by civanch** [comment]
+1
