### ISSUE TITLE
Reduce non-Debug messages in TrackerG4SimHitNumberingScheme

### ISSUE THREAD

**Issue by makortel** [cms-sw/cmssw#31757]
It was found out that when enlarging the MessaLogger's waiting message queue size
```python
process.MessageLogger.waiting_threshold = cms.untracked.uint32(2000000000)
```
running the GEN-SIM step of (at least) a run3 workflow 11640 with about 16 threads (and streams) and beyond the MessageLogger starts to hog memory. An IgProf [MEM_LIVE on 16-thread job after 48 events](http://mkortela.web.cern.ch/mkortela/cgi-bin/navigator/mtsim/test_07.mem.48/25) indicates that a vast majority of the queued messages originate from `TrackerG4SimHitNumberingScheme`, and by quick look of the code
https://github.com/cms-sw/cmssw/blob/master/SimG4CMS/Tracker/src/TrackerG4SimHitNumberingScheme.cc
there are indeed potentially many Info-level messages sent.

While increasing the MessageLogger's `waiting_threshold` that large itself is questionable, it could be worthwhile to change the messages in `TrackerG4SimHitNumberingScheme` to `LogTrace` if possible.

**Comment by makortel** [comment]
assign simulation

**Comment by VinInn** [comment]
Why debug log should run in production?
I think we should remove the Info class

**Comment by makortel** [comment]
I opened another issue (#31759) to look into rejecting INFO messages earlier.

**Comment by civanch** [comment]
@ghugo83 , likely this info printout was forgotten in your recent PR. Would you fix or you are busy with other debugging?

**Comment by ghugo83** [comment]
@civanch My PR was not touching SimG4CMS/Tracker/src/TrackerG4SimHitNumberingScheme.cc

**Comment by ghugo83** [comment]
This was introduced by @vargasa  at https://github.com/cms-sw/cmssw/commit/10db664e05720166306691d1d156fb4d26f60953 
I guess that commit should be reverted. Actually, that full PR could be reverted, as it was not fixing the navigation, but since TrackerNumberingBuilder has changed a lot since, I guess the easiest is just to revert that specific commit.

**Comment by vargasa** [comment]
thanks @ghugo83. I can take a look at this later today

**Comment by civanch** [comment]
@makortel , #31811 should fix the issue.
