### ISSUE TITLE
 'PSet' object has no attribute 'btagCMVA' 

### ISSUE THREAD

**Issue by silviodonato** [cms-sw/cmssw#31768]
After having merged #31618 (`CMSSW_11_2_X_2020-10-13-1100`) we get this error in wf 10224.15, 11024.15, 25202.15
```
NANO,ENDJOB
We have determined that this is simulation (if not, rerun cmsDriver.py with --data)
with DB:
entry file:step3_inMINIAODSIM.root
Step: NANO Spec: 
Step: ENDJOB Spec: 
customising the process with nanoAOD_customizeMC from PhysicsTools/NanoAOD/nano_cff
Traceback (most recent call last):
  File "/cvmfs/cms-ib.cern.ch/nweek-02650/cc8_amd64_gcc8/cms/cmssw/CMSSW_11_2_X_2020-10-12-2300/bin/cc8_amd64_gcc8/cmsDriver.py", line 56, in <module>
    run()
  File "/cvmfs/cms-ib.cern.ch/nweek-02650/cc8_amd64_gcc8/cms/cmssw/CMSSW_11_2_X_2020-10-12-2300/bin/cc8_amd64_gcc8/cmsDriver.py", line 28, in run
    configBuilder.prepare()
  File "/cvmfs/cms-ib.cern.ch/nweek-02650/cc8_amd64_gcc8/cms/cmssw/CMSSW_11_2_X_2020-10-12-2300/python/Configuration/Applications/ConfigBuilder.py", line 2277, in prepare
    self.pythonCfgCode += self.addCustomise()
  File "/cvmfs/cms-ib.cern.ch/nweek-02650/cc8_amd64_gcc8/cms/cmssw/CMSSW_11_2_X_2020-10-12-2300/python/Configuration/Applications/ConfigBuilder.py", line 865, in addCustomise
    __import__(packageName)
  File "/cvmfs/cms-ib.cern.ch/nweek-02650/cc8_amd64_gcc8/cms/cmssw/CMSSW_11_2_X_2020-10-12-2300/python/PhysicsTools/NanoAOD/custom_jme_cff.py", line 173, in <module>
    btagCMVA  = jetTable.variables.btagCMVA,
AttributeError: 'PSet' object has no attribute 'btagCMVA'
```

**Comment by silviodonato** [comment]
assign xpog

**Comment by mariadalfonso** [comment]
@alefisico @camclean @andrzejnovak 

The JMEnano (also used by the BTV) workflows are giving problem.

The BTV group is deprecating some of the discriminator for the central nano after the 10_6 and you are adding them for the JMEnano for any potential jets reconstruction
https://github.com/cms-sw/cmssw/pull/31714#discussion_r501930168

Do you really need them in the JME(BTV)nano ?

**Comment by andrzejnovak** [comment]
I'm taking a look, but CMVA is not supported and I don't know of anyone using it for anything.

**Comment by alefisico** [comment]
No,we dont need them, we need the default btagging discriminators. Sorry if my comment in #31714 was confusing, what I meant is that we need the default btagging discriminators in all the other jet collections.

**Comment by gouskos** [comment]
Hi: The CSV discriminant for AK8/AK15 jet collections should be kept [and I think it does not create any errors] since it is used for the calibration of DeepAK8/DeepAK15/ParticleNet

**Comment by mariadalfonso** [comment]
@gouskos 

BTV want to keep the 
btagCSVV2 = Var("bDiscriminator('pfCombinedInclusiveSecondaryVertexV2BJetTags')

do you really need what is not supported by BTV ? 
btagCMVA = Var("bDiscriminator('pfCombinedMVAV2BJetTags') ?

**Comment by gouskos** [comment]
Hi @mariadalfonso - Yes this what I wrote keep *CSV*; CMVA can be removed

**Comment by andrzejnovak** [comment]
Yes, this checks out. We are removing CMVA, keeping CSVv2.

**Comment by mariadalfonso** [comment]
@andrzejnovak  

I think the CSVv2 is the main tagger for the EOY still. let's take the experience from the UL analysis first then we review for the Run3 central nano. JMEnano can be adapted after also.

There is no reason to have packed candidates occupy twice disk space (one in miniAOD and one in PFNano(NanoAODJMAR), as you see multiplication of nano lead always to errors.

**Comment by mariadalfonso** [comment]
@andrzejnovak @alefisico @hqucms 
we need a fix for the broken JMEnano _asap_. we agreed to remove the CMVA from the JMEnano

Two possibilities
@hqucms  can update  his PR cms-sw#31714
@andrzejnovak can make a new PR in master

in any cases the PR should pass
runTheMatrix.py -l 10224.15, 11024.15, 25202.15

let me know how you proceed ?

Maria

**Comment by andrzejnovak** [comment]
@mariadalfonso looks like an easy fix, I'm running the failed WFs now, will submit a PR asap
