### ISSUE TITLE
Possible bug in the usage of rpcMatches in a reco::Muon

### ISSUE THREAD

**Issue by perrotta** [cms-sw/cmssw#31783]
While reviewing the Muon/MuonId code, I stumbled into the usage of RPC matches in the Muon DataFormat.

Consider for example the loop starting here:
https://github.com/cms-sw/cmssw/blob/master/DataFormats/MuonReco/src/Muon.cc#L160
or also this other one:
https://github.com/cms-sw/cmssw/blob/master/DataFormats/MuonReco/src/Muon.cc#L251

In both cases, a loop over rpcMatches is performed. But in the end "curmask" (same name for the local variable computed inside the loop in both cases) is identically the same in all iterations, as it only depends on quantities which are computed outside that loop. Therefore, I am tempted to say that either:
- the code is wrong and that `curmask` was supposed to be updated at every `rpcMatch`;
- the code is inefficient, as one could just check if the size of `chamberMatch->rpcMatches` is above 0, compute once `curmask`, and add it to the `totMask`

The Muon POG reco contacts (@trocino @ArnabPurohit) have been already informed, and they are taking care of it. This issue is just to keep track of the updates and resolution

**Comment by perrotta** [comment]
assign reconstruction

**Comment by trocino** [comment]
Thanks Andrea for catching this. I agree, both loops ([L 160](https://github.com/cms-sw/cmssw/blob/master/DataFormats/MuonReco/src/Muon.cc#L160) and [L 251](https://github.com/cms-sw/cmssw/blob/master/DataFormats/MuonReco/src/Muon.cc#L251)) seem unnecessary. I will cross check with the RPC team that implemented RPCMuons (@jhgoh ) if some selection was supposed to be applied to the RPC matches at each loop (like it's done with segment matches for other types of arbitration), but I doubt it. If not, we can proceed and correct it.

At the same time, there are a few other things that could be improved in the same functions, e.g.:
- lines [193](https://github.com/cms-sw/cmssw/blob/master/DataFormats/MuonReco/src/Muon.cc#L193) and [202](https://github.com/cms-sw/cmssw/blob/master/DataFormats/MuonReco/src/Muon.cc#L202) could be made "else if"
- the whole block [L 172-212](https://github.com/cms-sw/cmssw/blob/master/DataFormats/MuonReco/src/Muon.cc#L172-L212) could be enclosed in an "else" following [if (type == RPCHitAndTrackArbitration)](https://github.com/cms-sw/cmssw/blob/master/DataFormats/MuonReco/src/Muon.cc#L150)
- in lines [243-246](https://github.com/cms-sw/cmssw/blob/master/DataFormats/MuonReco/src/Muon.cc#L243-L246) there are five calls to "chamberMatch->station()", which can be easily reduced to just one (the first one at L 243), without introducing new variables
Should those be addressed too? In this same PR or a new one?

There are also several "fabs" that can be changed to "std::abs"

**Comment by perrotta** [comment]
Thank you @trocino : please have a look to #31789, where I implemented the second bullet listed in the issue description (" just check if the size of `chamberMatch->rpcMatches` is above 0, compute once `curmask,` and add it to the `totMask`), and with the last commit I also took into account your comments (the third bullet, as the first two are not expected to have a relevant impact, just a couple of bool checks).
If also @jhgoh confirms that such a loop in the rpcMatches is actually not needed, I will remove the comment left as a warning before the affected lines in the code, and I will consider closed this issue.

**Comment by perrotta** [comment]
I'm going to approve #31789 as it is coded now. As soon as  @jhgoh confirms that such a loop in the rpcMatches is actually not needed, I will submit another (trivial) PR which removes the comment lines added as a warning in https://github.com/cms-sw/cmssw/pull/31789/files#diff-84d3b2406deefaf4cd5103d8a2cfba5c84f294c81f62dd46aecd3ec2ff24487eR152 and https://github.com/cms-sw/cmssw/pull/31789/files#diff-84d3b2406deefaf4cd5103d8a2cfba5c84f294c81f62dd46aecd3ec2ff24487eR241

This issue will remain open till then

**Comment by jhgoh** [comment]
@perrotta Thank you for catching the meaningless loop.
I guess the routine was there long ago hidden in the very long lines of routines and simply not been caught. Logically the code changes in the master branch is identical to the one before the fix and must be safe.
For the author's intentions, it is not clear for me, though... In any case, I think this issue can be closed.

**Comment by slava77** [comment]
>  For the author's intentions, it is not clear for me, though... In any case, I think this issue can be closed.

@perrotta , if you agree, please "+1" or/and close this issue.

**Comment by perrotta** [comment]
Thank you for reminding me, @slava77 

Following https://github.com/cms-sw/cmssw/issues/31783#issuecomment-714383643, I made #32884 which removes the comment lines in DataFormats/MuonReco/src/Muon.cc that point out the possible bug this issue is dealing with: as soon as that PR will get merged we can close this issue (it will likely happen automatically, if the magic word "fixes" that I wrote in the PR description does its job)
