### ISSUE TITLE
Creation of SimHits for the Muon system for dd4hep

### ISSUE THREAD

**Issue by bsunanda** [cms-sw/cmssw#31797]
Creation of Geant4 geometry tree in the classical DDD package, the copy number is complemented with an offset and a tag which are used later on used in setting the DetId for muons. Most likely it is used only for the muons. The added copy numbers are used in the muon sensitive detector class (an auxiliary class of the SD). This can either be done at the time of creation of Geant4 geometry by DD4Hep or to be taken care of in the CMS specific code of creation of DetID

**Comment by makortel** [comment]
assign geometry, simulation

**Comment by cvuosalo** [comment]
FYI @slomeo

**Comment by cvuosalo** [comment]
+1

**Comment by cvuosalo** [comment]
@bsunanda I believe you fixed this problem. Could you please close it?

**Comment by bsunanda** [comment]
This issue is fixed.
