### ISSUE TITLE
DD4Hep complains about duplicate volume

### ISSUE THREAD

**Issue by bsunanda** [cms-sw/cmssw#31798]
DD4Hep complains of duplicate volume when it finds the same name and copy number is positioned multiple time. Those volumes are skipped and thus the geometry is incomplete for dd4hep. This happens for EB geometry as well as for PPS. In case of PPS, the same name is used in 2 separate XML files. So a combination of name and namespace resolves the case for DDD in case of PPS. The issue for EB is not understood - it may have something to do with the way DD4Hep assigns name of a volume. Name is important for EB numbering scheme.

**Comment by makortel** [comment]
assign geometry

**Comment by vargasa** [comment]
@bsunanda Is this different from https://github.com/cms-sw/cmssw/issues/31466 ?

**Comment by cvuosalo** [comment]
FYI @slomeo

**Comment by cvuosalo** [comment]
+1

**Comment by cvuosalo** [comment]
@bsunanda I think this issue is fixed. Could you please close it?

**Comment by bsunanda** [comment]
This issue is fixed
