### ISSUE TITLE
SonicTriton package does not build in slc7_ppc64le

### ISSUE THREAD

**Issue by makortel** [cms-sw/cmssw#31807]
This occurs in CMSSW_11_2_X_2020-10-14-2300 after the merges of https://github.com/cms-sw/cmssw/pull/31715 and https://github.com/cms-sw/cmsdist/pull/6297.
```
In file included from /scratch/cmsbuild/jenkins_a/workspace/build-any-ib/w/tmp/BUILDROOT/9ed5c5a91eb4757abad16efe82411e3d/opt/cmssw/slc7_ppc64le_gcc820/cms/cmssw/CMSSW_11_2_X_2020-10-13-2300/src/HeterogeneousCore/SonicTriton/src/TritonData.cc:1:
/scratch/cmsbuild/jenkins_a/workspace/build-any-ib/w/tmp/BUILDROOT/9ed5c5a91eb4757abad16efe82411e3d/opt/cmssw/slc7_ppc64le_gcc820/cms/cmssw/CMSSW_11_2_X_2020-10-13-2300/src/HeterogeneousCore/SonicTriton/interface/TritonData.h:15:10: fatal error: request_grpc.h: No such file or directory
 #include "request_grpc.h"
```

**Comment by makortel** [comment]
assign core, heterogeneous

FYI @kpedro88

**Comment by smuzaffar** [comment]
we can not. slc7_ppc64le_gcc820 uses the same branch as production arch (slc7_amd64_gcc820) https://github.com/cms-sw/cms-bot/blob/master/config.map#L11

**Comment by smuzaffar** [comment]
this is fixed in CMSSW_11_2_X_2020-10-14-2300 IBs ... right?

**Comment by makortel** [comment]
Ah sorry, i mixed up things. I observed the failures of CMSSW_11_2_X_2020-10-13-2300 and went to investigate what happened in CMSSW_11_2_X_2020-10-14-2300. All is good, sorry for the noise.
