### ISSUE TITLE
phase 2 MINIAOD size blows up in 11_2_X_pre7 due to switching on TICL egamma reco

### ISSUE THREAD

**Issue by jpata** [cms-sw/cmssw#31817]
It was noticed that after merging https://github.com/cms-sw/cmssw/pull/31527, the phase 2 MINIAOD size increases by a factor 2. The underlying reason is described in https://github.com/cms-sw/cmssw/pull/31766#issuecomment-709274945, coming from egamma TICL.

In order to avoid issues in production, we would like to have this fixed in pre8, let's discuss here how this can be achieved.

**Comment by jpata** [comment]
assign reconstruction

**Comment by jpata** [comment]
cc HGCAL: @rovere @SohamBhattacharya 
upgrade: @cms-sw/upgrade-l2

**Comment by kpedro88** [comment]
assign upgrade

**Comment by slava77** [comment]
from https://hypernews.cern.ch/HyperNews/CMS/get/relval/15189/9.html

> With high PU, the regression changed for the endcaps [3] and the performances look worse than before [4] & [5].
This problem is known and will be fixed in a future version. All the changes are described in [6]. 

It's not just the technical performance issue; the physics is also worse, apparently.

**Comment by slava77** [comment]
@jpata 
since we know the reason for the size blowup, please update the issue title to be more descriptive of the origins

**Comment by rovere** [comment]
Dear all, @SohamBhattacharya 
I did a quick investigation of the effect of including #31906 on the final size of the miniAODSIM.
I post here my findings after running on 25 events of TTBar with 200PU. Maybe not the definitive answer, but I think it is worth sharing the results here.
I used `CMSSW_11_2_0_pre8` and `CMSSW_11_2_0_pre8` + #31906 

I attach below the report from `edmEventSize` on the output `miniAODSIM` files.

``` diff
--- miniAOD_pr31906_sortedByName.txt    2020-10-29 15:49:05.074737397 +0100
+++ miniAOD_original_sortedByName.txt   2020-10-29 15:49:17.403986252 +0100
@@ -10 +10 @@
-EventAuxiliary 137.64 17.6
+EventAuxiliary 137.64 17.76
@@ -13 +13 @@
-File step3_inMINIAODSIM.root Events 25
+File ../step3_inMINIAODSIM.root Events 25
@@ -55,4 +55,4 @@
-patCompositeCandidates_oniaPhotonCandidates_conversions_RECO. 6146.8 2034.16
-patElectrons_slimmedElectronsFromMultiCl__RECO. 248788 24349.4
-patElectrons_slimmedElectrons__RECO. 10517 2424.44
-patIsolatedTracks_isolatedTracks__RECO. 6493.92 1793.52
+patCompositeCandidates_oniaPhotonCandidates_conversions_RECO. 6146.8 2033.52
+patElectrons_slimmedElectronsFromMultiCl__RECO. 1.61709e+06 150491
+patElectrons_slimmedElectrons__RECO. 10517 2424.92
+patIsolatedTracks_isolatedTracks__RECO. 6493.92 1793.68
@@ -66 +66 @@
-patMuons_slimmedMuons__RECO. 77739.5 22511.5
+patMuons_slimmedMuons__RECO. 77739.5 22510.9
@@ -70 +70 @@
-patPackedGenParticles_packedGenParticles__RECO. 44477.5 5383.88
+patPackedGenParticles_packedGenParticles__RECO. 44477.5 5382.6
@@ -75 +75 @@
-patPhotons_slimmedPhotonsFromMultiCl__RECO. 288364 22084.7
+patPhotons_slimmedPhotonsFromMultiCl__RECO. 3.39665e+06 262620
@@ -77,2 +77,2 @@
-patTaus_slimmedTausBoosted__RECO. 10421.6 1804.88
-patTaus_slimmedTaus__RECO. 17104.6 2369.76
+patTaus_slimmedTausBoosted__RECO. 10421.6 1805.04
+patTaus_slimmedTaus__RECO. 17104.6 2369.44
@@ -103 +103 @@
-recoGsfTracks_reducedEgamma_reducedGsfTracks_RECO. 2155.48 875.4
+recoGsfTracks_reducedEgamma_reducedGsfTracks_RECO. 2155.48 875.56
```

I think we already see quite a significant reduction on the size of electrons and photons related collections that were the ones affected by the changes introduces by #31527
I'm not familiar with the corresponding sizes before the introduction of #31527, but I think this reduction alone could ~close the issue.
If you happen to have numbers to compare to, that would be interesting.

**Comment by kpedro88** [comment]
thanks @rovere 
the change from pre6 to pre7 is shown here: https://jiwoong.web.cern.ch/jiwoong/results/phase2/compare_products_11_2_0/prod_PAT_compare_cpu_11_2_0Pre6vsPre7.txt
I think the byte sizes are not directly comparable (different events), but for example, patElectrons_slimmedElectronsFromMultiCl__PAT increased by ~7x from pre6 to pre7, and here it decreases by ~6x, so that mostly recovers the original size.

**Comment by rovere** [comment]
Thanks, @kpedro88 for the pointers and numbers.

**Comment by rovere** [comment]
Can we have this re-assessed using `CMSSW_11_2_0_pre9` and, in case, close the issue if the problems are solved?

**Comment by jpata** [comment]
Yes, making a note here to recheck & close once pre9 is available at https://jiwoong.web.cern.ch/jiwoong/

**Comment by jpata** [comment]
+reconstruction 

The latest [profiling](https://jiwoong.web.cern.ch/jiwoong/) by Jiwoong reports that things are back to normal in pre9:

```
step3: [CompareOutProd (edmEventSize)]preview: 26782791 -> 19057863 
step4: [CompareOutProd (edmEventSize)]preview: 589587 -> 261253 
```

**Comment by kpedro88** [comment]
+upgrade
