### ISSUE TITLE
[Upgrade] PhaseII L1 reconstruction crash

### ISSUE THREAD

**Issue by rovere** [cms-sw/cmssw#31840]
While testing `TICLv2` branch in CMSSW_11_1_X, I noticed several failures that apparently are not directly connected with any of the changes we've been developing.
The error looks like the following:

```
----- Begin Fatal Exception 13-Oct-2020 13:42:24 CEST-----------------------
An exception of category 'FatalRootError' occurred while
   [0] Processing  Event run: 1 lumi: 1 event: 4 stream: 2
   [1] Running path 'FEVTDEBUGHLToutput_step'
   [2] Prefetching for module PoolOutputModule/'FEVTDEBUGHLToutput'
   [3] Prefetching for module FastjetJetProducer/'ak4PFL1Calo'
   [4] Prefetching for module L1TPFCandMultiMerger/'l1pfCandidates'
   [5] Prefetching for module L1TPFProducer/'l1pfProducerBarrel'
   [6] Calling method for module L1TkMuonProducer/'L1TkMuons'
   Additional Info:
      [a] Fatal Root Error: @SUB=TFormula::ReInitializeEvalMethod
Formula is NOT properly initialized - try calling again TFormula::PrepareEvalMethod

----- End Fatal Exception -------------------------------------------------
```

I checked in the IB page and noticed that this error is present (not every IB, but frequently enough) also in `vanilla` CMSSW_11_1_X_IBs.
See, e.g. [here](https://cmssdt.cern.ch/SDT/cgi-bin/logreader/slc7_amd64_gcc820/CMSSW_11_1_X_2020-10-17-1100/pyRelValMatrixLogs/run/26234.0_TTbar_14TeV+TTbar_14TeV_TuneCP5_2026D55_GenSimHLBeamSpotFull14+DigiFullTrigger_2026D55+RecoFullGlobal_2026D55+HARVESTFullGlobal_2026D55/step2_TTbar_14TeV+TTbar_14TeV_TuneCP5_2026D55_GenSimHLBeamSpotFull14+DigiFullTrigger_2026D55+RecoFullGlobal_2026D55+HARVESTFullGlobal_2026D55.log#/) and [here](https://cmssdt.cern.ch/SDT/cgi-bin/logreader/slc7_amd64_gcc820/CMSSW_11_1_X_2020-10-15-2300/pyRelValMatrixLogs/run/26234.0_TTbar_14TeV+TTbar_14TeV_TuneCP5_2026D55_GenSimHLBeamSpotFull14+DigiFullTrigger_2026D55+RecoFullGlobal_2026D55+HARVESTFullGlobal_2026D55/step2_TTbar_14TeV+TTbar_14TeV_TuneCP5_2026D55_GenSimHLBeamSpotFull14+DigiFullTrigger_2026D55+RecoFullGlobal_2026D55+HARVESTFullGlobal_2026D55.log#/)

**Comment by rovere** [comment]
assign upgrade

**Comment by rovere** [comment]
assign reconstruction

**Comment by slava77** [comment]
assign upgrade,l1

@rovere I do not see a reason to assign reco here, because the problem is in L1 code (L1TkMuonProducer is in L1 and it is not consumed by anything in reco).
Please also update the title of the issue.

**Comment by kpedro88** [comment]
#31099 should address this - previously it wasn't being observed in 11_1_X. Can you try it? If it helps, we should merge it. attn @silviodonato

**Comment by silviodonato** [comment]
Thanks Kevin. I've opened back https://github.com/cms-sw/cmssw/pull/31099

**Comment by kpedro88** [comment]
+upgrade

**Comment by srimanob** [comment]
Can this issue close? @cms-sw/l1-l2
