### ISSUE TITLE
Exception while attempting to load plugin PGeometricDetExtraRcd@NewProxy

### ISSUE THREAD

**Issue by silviodonato** [cms-sw/cmssw#31869]
We get 20 unit test failures in `DQM/Integration` and exception in wf 1001.2 1030.0 1040.0 1040.1 since `CMSSW_11_2_X_2020-10-19-2300`

```
----- Begin Fatal Exception 20-Oct-2020 09:11:48 CEST-----------------------
An exception of category 'PluginLibraryLoadError' occurred while
   [0] Constructing the EventProcessor
   [1] Constructing ESSource: class=PoolDBESSource label='GlobalTag'
   [2] While attempting to load plugin PGeometricDetExtraRcd@NewProxy
Exception Message:
unable to load /cvmfs/cms-ib.cern.ch/nweek-02651/cc8_amd64_gcc8/cms/cmssw-patch/CMSSW_11_2_X_2020-10-19-2300/lib/cc8_amd64_gcc8/poisoned/plugin-poisoned-CondCoreGeometryPluginsPlugins.so because /cvmfs/cms-ib.cern.ch/nweek-02651/cc8_amd64_gcc8/cms/cmssw-patch/CMSSW_11_2_X_2020-10-19-2300/lib/cc8_amd64_gcc8/poisoned/plugin-poisoned-CondCoreGeometryPluginsPlugins.so: cannot open shared object file: No such file or directory
----- End Fatal Exception -------------------------------------------------
```

The orgin of the error is https://github.com/cms-sw/cmssw/pull/31729 .
I hope it can be fixed by updating the global tag as we did with https://github.com/cms-sw/cmssw/pull/31780.

**Comment by silviodonato** [comment]
assign alca

**Comment by silviodonato** [comment]
cc @vargasa @cms-sw/db-l2

**Comment by mmusich** [comment]
@silviodonato I have taken care of that here: https://github.com/cms-sw/cmssw/pull/31871

**Comment by mmusich** [comment]
with #31871 integrated in `CMSSW_11_2_X_2020-10-20-2300`, [unit tests](https://cmssdt.cern.ch/SDT/cgi-bin/showBuildLogs.py/slc7_amd64_gcc820/www/tue/11.2-tue-23/CMSSW_11_2_X_2020-10-20-2300) and [relvals](https://cms-sw.github.io/relvalLogDetail.html#slc7_amd64_gcc820;CMSSW_11_2_X_2020-10-20-2300) look clean. 
I guess this issue can be signed and closed.

**Comment by vargasa** [comment]
@mmusich Thanks for taking care of the remaining changes

**Comment by silviodonato** [comment]
right, we can close the issue. thanks @mmusich for providing quickly a fix

**Comment by christopheralanwest** [comment]
+1
