### ISSUE TITLE
testAlignmentOfflineValidation had ERRORS and failure in 1000.0

### ISSUE THREAD

**Issue by silviodonato** [cms-sw/cmssw#31889]
In CMSSW_11_2_X_2020-10-21-1100 we get a unit test failure in `Alignment/OfflineValidation`
https://cmssdt.cern.ch/SDT/cgi-bin/logreader/slc7_amd64_gcc820/CMSSW_11_2_X_2020-10-21-1100/unitTestLogs/Alignment/OfflineValidation#/478-478
and workflow `1000.0 RunMinBias2011A+RunMinBias2011A+TIER0+SKIMD+HARVESTDfst2+ALCASPLIT` 
gives segmentation fault.

Both of them seems related to https://github.com/cms-sw/cmssw/pull/31827. @mmusich could you have a look?

**Comment by silviodonato** [comment]
assign alca

**Comment by mmusich** [comment]
@silviodonato the failure in the `Alignment/OfflineValidation` is due to an empty DAS query. I guess I can reduce the severity of the exception.
The failure in 1000.0 does not seem directly related to anything I changed though (?)

**Comment by silviodonato** [comment]
we get also https://github.com/cms-sw/cmssw/pull/31654#issuecomment-713632176
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-4287c1/10176/unitTests.log

**Comment by silviodonato** [comment]
assign core
something weird is happening

**Comment by makortel** [comment]
That segfault in 1000.0 occurs randomly and is being tracked in https://github.com/cms-sw/cmssw/issues/30359

**Comment by makortel** [comment]
unassign core

(assuming the assignment was based on the segfault in 1000.0)

**Comment by silviodonato** [comment]
ok, so the error of 1000.0 is  #30359 and the unit test failure is a transient problem with DAS (indeed the unit test is ok in Patatrack and ARM)

**Comment by mmusich** [comment]
> and the unit test failure is a transient problem 

I'll mitigate for transient failures anyway (tomorrow morning).

**Comment by mmusich** [comment]
> I'll mitigate for transient failures anyway (tomorrow morning).

addressed in #31901.
