### ISSUE TITLE
cmsExtendedGeometry2021.xml differs (unit test)

### ISSUE THREAD

**Issue by silviodonato** [cms-sw/cmssw#31914]
Unit test in `Configuration/Geometry`
```
===== Test "test2021Geometry" ====
cmsExtendedGeometry2021.xml differs

---> test test2021Geometry had ERRORS
 
^^^^ End Test test2021Geometry ^^^^
```

**Comment by silviodonato** [comment]
assign geometry

**Comment by ianna** [comment]
@silviodonato - this should fix it https://github.com/cms-sw/cmssw/pull/31915

**Comment by silviodonato** [comment]
Thanks @ianna. Is it a serious problem or shall go ahead with the build of `CMSSW_11_2_0_pre8`? I see all workflows run without errors.

**Comment by ianna** [comment]
@silviodonato - no, it's not a serious problem. However, you may want to integrate the fix to have a clean pre8.

**Comment by silviodonato** [comment]
I prefer to upload pre8 now, otherwise we will miss the weekend for the relval production
