### ISSUE TITLE
UnexpectedMagneticField message in Pixel2D template (Run3 data at 0T)

### ISSUE THREAD

**Issue by boudoul** [cms-sw/cmssw#31956]
Hello 
I noticed when reconstructing a run from MWGR this message : 

_%MSG-w UnexpectedMagneticFieldUsingNonIdealPixel2DTemplate:  PostModuleEvent  27-Oct-2020 15:14:15 CET Run: 334393 Event: 9562884
Magnetic field is 0 Template Magnetic field is 3.8_

I'm just reporting here in case this is the sign that something needs to be fixed in order to have the right config when taking data at 0T (= the current case at P5 and will be important when commisioning the full detector during CRUZET later in 2021). Is this a known problem ? 

How to reproduce ? Easy   : running on 1 event of the workflow 138.1 (with a valid  certificate to access data)  
runTheMatrix.py -l 138.1 --command "-n 1"

Thanks.

**Comment by makortel** [comment]
assign reconstruction

**Comment by boudoul** [comment]
Adding @amassiro

**Comment by slava77** [comment]
@pmaksim1 @mmusich @OzAmram

**Comment by slava77** [comment]
assign alca

it looks more like an alca topic for GT content

**Comment by mmusich** [comment]
For now this is **WONTFIX**:
1) Pixel Tracker is not part of MWGR
2) 2D template reco is irrelevant for cosmics anyway

For more discussion:

https://github.com/cms-sw/cmssw/pull/26940

Will eventually be fixed before start of data-taking for collisions.

**Comment by mmusich** [comment]
@tvami @ferencek FYI

**Comment by tvami** [comment]
This has been fixed in https://github.com/cms-sw/cmssw/pull/34390
So the issue can be closed!

**Comment by tvami** [comment]
+alca
This has been fixed in #34390
So the issue can be closed!

**Comment by tvami** [comment]
Hi @slava77 , can you please sign this? thanks!

**Comment by slava77** [comment]
+reconstruction
