### ISSUE TITLE
Muon DB loaders need to be migrated to DD4hep

### ISSUE THREAD

**Issue by cvuosalo** [cms-sw/cmssw#31958]
In `CondTools/​Geometry/​plugins/` the muon DB loaders need to be migrated to DD4hep.
```
CSCRecoIdealDBLoader.cc
DTRecoIdealDBLoader.cc
GEMRecoIdealDBLoader.cc
ME0RecoIdealDBLoader.cc
```
`HcalParametersDBBuilder.cc` provides an example of what needs to be done.

**Comment by cvuosalo** [comment]
@slomeo This issue is low-priority but should be done when you have time.

**Comment by cvuosalo** [comment]
assign geometry

**Comment by cvuosalo** [comment]
closed by accident

**Comment by slomeo** [comment]
@cvuosalo @ptcox : I have edited CondTools/Geometry/plugins/CSCRecoIdealDBLoader.cc in oreder to add the dd4hep flag as I saw in HcalParametersDBBuilder.cc and the compilation is fine. 
Two questions:
1) do I have to add CSCParametersWriter_cff.py in CondTools/Geometry/python ?
2) do I have to edit  in CondTools/Geometry/test/cscgeometrywriter.py ?

**Comment by cvuosalo** [comment]
@slomeo You should change `cscgeometrywriter.py` to include the new DD4hep flag. Test the script with dd4hep=true, but in the PR set the flag to false because we are not ready yet to create DB payloads with DD4hep.

I don't understand your question about `CSCParametersWriter_cff.py`.

**Comment by ptcox** [comment]
And I have no idea either. I know nothing about CSCParametersWriter. 
Something to do with geometry-in-database?

Sorry,

Tim

**Comment by slomeo** [comment]
@cvuosalo : ok. 
As far as CSCParametersWriter_cff.py I followed what I understood by looking: 
1) at https://cmssdt.cern.ch/lxr/source/CondTools/Geometry/plugins/HcalParametersDBBuilder.cc  (line 42) 
2) at https://cmssdt.cern.ch/lxr/source/CondTools/Geometry/python/HcalParametersWriter_cff.py
Is a new file (CSCParametersWriter_cff.py ) needed?

**Comment by slomeo** [comment]
@ptcox : please see my answer (above) to @cvuosalo

**Comment by slomeo** [comment]
@cvuosalo @ptcox : in summary, if I have to follow what it has been done for HcalParametersDBBuilder.cc, is a ParameterWriter file (as HcalParametersWriter_cff.py) need for CSC too?

**Comment by slomeo** [comment]
@cvuosalo @ptcox please take a look to PR #32001

**Comment by cvuosalo** [comment]
+1

**Comment by cvuosalo** [comment]
All of the muon DB loaders have been migrated.
