### ISSUE TITLE
[Muon][Geometry] use smart pointers

### ISSUE THREAD

**Issue by ianna** [cms-sw/cmssw#31954]
`DTGeometry`, `CSCGeometry`, `RPCGeometry`, `GEMGeometry`, `ME0Geometry` should use `std::unique_ptr` smart pointer that owns and manages another object through a pointer and disposes of that object when the unique_ptr goes out of scope.

`DT` and `CSC` deallocate the resources:
https://cmssdt.cern.ch/lxr/source/Geometry/DTGeometry/src/DTGeometry.cc#0016
https://cmssdt.cern.ch/lxr/source/Geometry/CSCGeometry/src/CSCGeometry.cc#0031

Neither `GEM` nor `ME0` nor `RPC` geometries deallocate the resources:
https://cmssdt.cern.ch/lxr/source/Geometry/GEMGeometry/src/GEMGeometry.cc#0011
https://cmssdt.cern.ch/lxr/source/Geometry/GEMGeometry/src/ME0Geometry.cc#0010
https://cmssdt.cern.ch/lxr/source/Geometry/RPCGeometry/src/RPCGeometry.cc#0012

Please, review if all the containers are used.

@slomeo , @namapane , @ptcox - FYI

**Comment by makortel** [comment]
assign geometry

**Comment by ianna** [comment]
@bsunanda - FYI

**Comment by cvuosalo** [comment]
This issue is low-priority, and it can be addressed after more urgent issues are resolved. It is helpful optimization to reduce memory use.

**Comment by namapane** [comment]
@ianna I'm not sure I understand: do you mean DT and CSC (which deallocate resources) should be changed to use std::unique_ptr, or just that GEM, ME0 and RPC need to add proper memory handling?
DT and CSC codes were written well before std::unique_ptr made its appearance in the C++ standard. I am personally against changing code that behaves properly and is well tested to embrace newer features of the language - if it ain't broke... :-)

**Comment by ianna** [comment]
> @ianna I'm not sure I understand: do you mean DT and CSC (which deallocate resources) should be changed to use std::unique_ptr, or just that GEM, ME0 and RPC need to add proper memory handling?
> DT and CSC codes were written well before std::unique_ptr made its appearance in the C++ standard. I am personally against changing code that behaves properly and is well tested to embrace newer features of the language - if it ain't broke... :-)

@namapane - it would be nice to have a uniform and consistent code. We are revisiting the geometry builders for the DD4hep migration. `new` looks kinda old there :-) 
Besides a copy-and-paste practice is common in CMSSW development - the problems arise  when only a part of the code is copied (see RPC's). Also, are all the containers used and useful?

Note, CMSSW is heading toward an automated linting and the same question may pop up again rather soon.

**Comment by namapane** [comment]
>  Also, are all the containers used and useful?

Uhm, which "containers" are you referring to?

**Comment by ianna** [comment]
closed in favour of https://github.com/cms-sw/cmssw/issues/34663
