### ISSUE TITLE
[DD4hep] Change DD4hep to return values with the Geant4 units convention

### ISSUE THREAD

**Issue by cvuosalo** [cms-sw/cmssw#31979]
DD4hep returns values with the ROOT/CMS units convention, where lengths are in cm. Geant4 uses its own units convention, where lengths are in mm. When values obtained from DD4hep are sent to Geant4, they need to be converted.

These conversions impose costs in terms of performance and precision. DD4hep can be configured to return values with the Geant4 units convention. Doing so would improve performance and avoid numerical imprecision will also simplifying our code. However, our current code has been written to support DD4hep following the ROOT/CMS convention, so making the change in units convention will require changing a fair amount of code and risking the introduction of bugs. This change needs to be scheduled at a time when other priorities are not pressing and when we have sufficient resources to complete the task.

This issue is low priority since the current code is working correctly as far as we know, except for some numerical imprecision caused by repeated conversions.

More details will be added to this issue soon.

**Comment by cvuosalo** [comment]
assign geometry

**Comment by cvuosalo** [comment]
> +++ Reason 1 **Performance**
> Conversion between ROOT -> G4 units costs us roughly 16 divisions per volume - excluding the number of parameters per shape.
> 
> 2021 scenario has 2111632 volumes.
> 2026 scenario has 13262283 volumes.
> 
> Moving to the same units would be a multiplication by 1 in the worst case. Multiplication by 1 is part of a class of simple optimisations known as arithmetic local optimisations. The compiler would optimise it.
> 
> +++ Reason 2 **Precision**
> There are 13 levels of the cumulative transformations in CMS geometry description. XML -> ROOT units -> G4 units introduces bigger precision errors than XML -> G4
> because we are accumulating error every time we divide by 10 (since 10 is not power of 2).
> 
> +++ Reason 3 **Minimise our own effort**
> Simulation will run fine with the G4 units as the default ones without any extra effort. We have always assumed that we'd use the G4 units when it comes to production.
> 
> **An effort is required if we want to move to the ROOT units consistently.** ProductionCuts is only one example. We never fully analysed the CMSSW code for this use case. If this move is done, an extra work will have to be done to move back to the G4 units.
> 
> It has been confirmed yesterday that migration to the G4 units is fine for Calorimeters. The other three links point to the MTD, Tracker and Forward sub detectors. All of the quoted cases would benefit by using the G4 units directly to avoid multiplications - a dozen multiplications per a DetUnit in Tracker, for example.
> 
> +++ Reason 4 **Keeping good faith with DD4hep developers**
> Historically, DD4hep relied on ROOT units as the default ones. CMS has requested to switch to G4 units - our default in Simulation. They have done as we’ve asked and delivered by migrating their own code and their users code to the G4 units. It has been a huge effort for them and there was a sense of disappointment during the DD4hep developers meeting when we were not enthusiastic about them switching to the units we’ve asked.

**Comment by ianna** [comment]
Sorry I didn’t see it in your plan. So, why it’s not a high priority issue? It’s 10 days before CERN closes, if we do not update to the new version of DD4Hep this week, we’ll loose one month of development.

We are already concerned about performance, we have heard reports about Ecal geometry discrepancy at a the level of precision, we have thread safety and performance issues due to bringing in the evaluator in Reco. This issue is a showstopper for Run 1 legacy payload usage. All this points to the need of the migration ASAP.

What is the reason for delaying the units switch? We will be hitting other problems that we do not have unit tests for.

**Comment by ianna** [comment]
Duplicate

**Comment by ianna** [comment]
As CMS has requested, DD4hep is ready to do the switch. A copy form a geometry forum discussion is beneath.

 > +++ Reason 1 **Performance**
> Conversion between ROOT -> G4 units costs us roughly 16 divisions per volume - excluding the number of parameters per shape.
> 
> 2021 scenario has 2111632 volumes.
> 2026 scenario has 13262283 volumes.
> 
> Moving to the same units would be a multiplication by 1 in the worst case. Multiplication by 1 is part of a class of simple optimisations known as arithmetic local optimisations. The compiler would optimise it.
> 
> +++ Reason 2 **Precision**
> There are 13 levels of the cumulative transformations in CMS geometry description. XML -> ROOT units -> G4 units introduces bigger precision errors than XML -> G4
> because we are accumulating error every time we divide by 10 (since 10 is not power of 2).
> 
> +++ Reason 3 **Minimise our own effort**
> Simulation will run fine with the G4 units as the default ones without any extra effort. We have always assumed that we'd use the G4 units when it comes to production.
> 
> **An effort is required if we want to move to the ROOT units consistently.** ProductionCuts is only one example. We never fully analysed the CMSSW code for this use case. If this move is done, an extra work will have to be done to move back to the G4 units.
> 
> It has been confirmed yesterday that migration to the G4 units is fine for Calorimeters. The other three links point to the MTD, Tracker and Forward sub detectors. All of the quoted cases would benefit by using the G4 units directly to avoid multiplications - a dozen multiplications per a DetUnit in Tracker, for example.
> 
> +++ Reason 4 **Keeping good faith with DD4hep developers**
> Historically, DD4hep relied on ROOT units as the default ones. CMS has requested to switch to G4 units - our default in Simulation. They have done as we’ve asked and delivered by migrating their own code and their users code to the G4 units. It has been a huge effort for them and there was a sense of disappointment during the DD4hep developers meeting when we were not enthusiastic about them switching to the units we’ve asked.

**Comment by cvuosalo** [comment]
From my point of view, the top priority is to fix the Run 3 DD4hep workflows so they run successfully to completion. Currently, the 11624_TTbar workflow is terminating early in the reco step, and I am investigating the problem. The next priority is to address the discrepancy between DDD and DD4hep in the number of physical volumes and material cut couples, because these mismatches could be indicating a deeper underlying problem.

I see the most urgent task being the achievement of a clean Run 3 baseline for DD4hep: Making sure known bugs are fixed and the two Run3 DD4hep workflows run successfully to completion with at least 1000 events. Once we have the clean Run 3 DD4hep baseline, we can announce that and possibly ask for preliminary validation. Very optimistically we could aim to get to the clean basline for CMSSW_11_3_0_pre1 on Dec. 15.

I see the DD4hep units conversion as an optimization. I am not aware of any current DD4hep Run 3 bug where detector elements are off by a factor of 10, so I think the current DD4hep Run 3 code is functioning. Once we have a clean DD4hep baseline, it will be easier to perform the DD4hep units conversion.

As for performing the DD4hep units conversion in December, I think that train has already left the station. An achievable goal might be to aim to complete the DD4hep units conversion and other optimizations in time for CMSSW_11_3_0_pre2 on 2021/01/19.

With all that being said, any developer who has time can start work on the DD4hep units conversion now. Using the constructs like "ddhep:mm" can allow revision of code that will work correctly before and after the DD4hep units conversion.

**Comment by civanch** [comment]
I agree with the plan as described by Carl, in fact. When we see, that Run3 is fully functional, we make a request for special IB and start migration of units. However, we may not be able to converge without units change. Also, we can request for PPD validation if we have a new GT, making GT may require some time. So, the 1st priority is to make Run3 WFs fully working, so we have "working point". Just after start migration of units. When we make PPD validation for me not fully clear - it will depend on success with these two milestones.

**Comment by ianna** [comment]
> I agree with the plan as described by Carl, in fact. When we see, that Run3 is fully functional, we make a request for special IB and start migration of units. However, we may not be able to converge without units change. Also, we can request for PPD validation if we have a new GT, making GT may require some time. So, the 1st priority is to make Run3 WFs fully working, so we have "working point". Just after start migration of units. When we make PPD validation for me not fully clear - it will depend on success with these two milestones.

@civanch - we will not be able to coverage without the units change. It’s a showstopper.

**Comment by cvuosalo** [comment]
+1
