### ISSUE TITLE
pLHE production, singularity, and xrdfs in CMSSW_7_1_X

### ISSUE THREAD

**Issue by silviodonato** [cms-sw/cmssw#32035]
@jordan-martins reported a crash related to the `cmsLHEtoEOSManager` in the pLHE production in CMSSW_7_1_X ( https://cms-pdmv.cern.ch/mcm/public/restapi/requests/get_test/BPH-RunIIWinter15pLHE-00009 ):

```
[...]
>> Done generating edm plugin poisoned information
gmake[1]: Leaving directory `/afs/cern.ch/work/s/sdonato/ORP/test/CMSSW_7_1_32'

LHE input from article  19210
/bin/sh: xrdfs: command not found
Issue to load LHE files, please check and try again.
INFO:    Cleaning up image...
```

The script `BPH-RunIIWinter15pLHE-00009` runs the command 
```
singularity run -B /afs -B /eos -B /cvmfs -B /etc/grid-security --home $PWD:$PWD docker://cmssw/slc6:latest $(echo $(pwd)/BPH-RunIIWinter15pLHE-00009_test.sh)
``` 
I noticed that we do not get any error running directly `./BPH-RunIIWinter15pLHE-00009_test.sh` on `lxplus6`.

I temporarly fixed the problem by adding 
```
source /cvmfs/sft.cern.ch/lcg/views/LCG_83/x86_64-slc6-gcc48-opt/setup.sh
export LC_ALL=en_US.UTF-8
```
just before 
```
export SCRAM_ARCH=slc6_amd64_gcc481
```
in https://cms-pdmv.cern.ch/mcm/public/restapi/requests/get_test/BPH-RunIIWinter15pLHE-00009

The first line needs to load `xrdfs`. The second line is needed to remove many warnings from perls:
```
[sdonato@lxplus790 test]$ cmssw-cc6  
Singularity> scram
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
	LANGUAGE = (unset),
	LC_ALL = (unset),
	LC_PAPER = "en_NZ.UTF-8",
	LC_ADDRESS = "en_NZ.UTF-8",
	LC_MONETARY = "en_NZ.UTF-8",
	LC_NUMERIC = "en_NZ.UTF-8",
	LC_TELEPHONE = "en_NZ.UTF-8",
	LC_IDENTIFICATION = "en_NZ.UTF-8",
	LC_MEASUREMENT = "en_NZ.UTF-8",
	LC_TIME = "en_NZ.UTF-8",
	LC_NAME = "en_NZ.UTF-8",
	LANG = "C"
    are supported and installed on your system.
perl: warning: Falling back to the standard locale ("C").
```

@cms-sw/externals-l2 how should we fix this? Do we need to fix singularity or the script `pLHE` scripts (eg. `BPH-RunIIWinter15pLHE-00009`)

Related to:
https://github.com/cms-sw/cmsdist/pull/6355
cms-sw/cmssw#31553
cms-sw/cmssw#31922

**Comment by silviodonato** [comment]
assign externals, pdmv

**Comment by smuzaffar** [comment]
@silviodonato , first I would not suggest to source `/cvmfs/sft.cern.ch/lcg/views/LCG_83/x86_64-slc6-gcc48-opt/setup.sh`  even if it fixes the issue. This will bring in other issue as we mix sft and cms env.

Can you please try with `docker://cmssw/slc6:amd64` container instead of `docker://cmssw/slc6:latest`

**Comment by silviodonato** [comment]
@smuzaffar I get
```
/bin/sh: xrdfs: command not found
```
even with
`singularity run -B /afs -B /eos -B /cvmfs -B /etc/grid-security --home $PWD:$PWD docker://cmssw/slc6:amd64 $(echo $(pwd)/BPH-RunIIWinter15pLHE-00009_test.sh)`

**Comment by silviodonato** [comment]
as well as
```
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
	LANGUAGE = (unset),
	LC_ALL = (unset),
	LC_PAPER = "en_NZ.UTF-8",
	LC_ADDRESS = "en_NZ.UTF-8",
	LC_MONETARY = "en_NZ.UTF-8",
	LC_NUMERIC = "en_NZ.UTF-8",
	LC_TELEPHONE = "en_NZ.UTF-8",
	LC_IDENTIFICATION = "en_NZ.UTF-8",
	LC_MEASUREMENT = "en_NZ.UTF-8",
	LC_TIME = "en_NZ.UTF-8",
	LC_NAME = "en_NZ.UTF-8",
	LANG = "C"
    are supported and installed on your system.
perl: warning: Falling back to the standard locale ("C").
```

**Comment by smuzaffar** [comment]
If issue is missing xrdfs then we can install make it available in the continer. I though we pick up xrootd from cmssw env.

**Comment by silviodonato** [comment]
We pick `xrdfs` up from cmssw starting from `CMSSW_7_4_0`

**Comment by smuzaffar** [comment]
about the perl warning, I can not reproduce it ( may be due to my env where I have LC_* env set)

**Comment by silviodonato** [comment]
> about the perl warning, I can not reproduce it ( may be due to my env where I have LC_* env set)

Right, I can fix it even setting the variable outside `singularity`
```
[sdonato@lxplus7109 ~]$ export LC_ALL=en_US.UTF-8
[sdonato@lxplus7109 ~]$ cmssw-cc6  
Singularity> scram
***************************************************
SCRAM HELP ------------- Recognised Commands
***************************************************
[...]
Singularity> 
```

About `xrdfs`, I found it only on these releases
```
[sdonato@lxplus790 test]$ ls /cvmfs/cms.cern.ch/*/cms/cmssw/CMSSW_7_*/external/*/bin/xrdfs
/cvmfs/cms.cern.ch/slc6_amd64_gcc481/cms/cmssw/CMSSW_7_0_0_XROOTD/external/slc6_amd64_gcc481/bin/xrdfs
/cvmfs/cms.cern.ch/slc6_amd64_gcc481/cms/cmssw/CMSSW_7_0_0_XROOTD2/external/slc6_amd64_gcc481/bin/xrdfs
/cvmfs/cms.cern.ch/slc6_amd64_gcc481/cms/cmssw/CMSSW_7_2_0_pre4/external/slc6_amd64_gcc481/bin/xrdfs
/cvmfs/cms.cern.ch/slc6_amd64_gcc481/cms/cmssw/CMSSW_7_3_0_pre2_DEVEL/external/slc6_amd64_gcc481/bin/xrdfs
/cvmfs/cms.cern.ch/slc6_amd64_gcc481/cms/cmssw/CMSSW_7_4_0_pre1/external/slc6_amd64_gcc481/bin/xrdfs
```
and beyond `CMSSW_7_4_0_pre1`

**Comment by smuzaffar** [comment]
yes xrdfs commands are part of xrootd 4.X client which was only available in CMSSW_7_4 and above. I will update the container to include xrootd client.

**Comment by smuzaffar** [comment]
@silviodonato , I have created a new container `cmssw/slc6:amd64-d20201105` which includes xrootd client. Can you please try it and if this works then I will tag it as `cmssw/slc6:amd64`

**Comment by silviodonato** [comment]
@smuzaffar it works with `cmssw/slc6:amd64-d20201105`!

**Comment by smuzaffar** [comment]
@silviodonato , `cmssw/slc6:amd64` and `cmssw/slc6:latest` containers are now same as `cmssw/slc6:amd64-d20201105`

**Comment by silviodonato** [comment]
Perfect, thanks!
