### ISSUE TITLE
Fortran warnings in GeneratorInterface for GCC 10

### ISSUE THREAD

**Issue by mrodozov** [cms-sw/cmssw#32058]
There are 16 fortran warnings in 4 subpackages in GeneratorInterface/* that can be seen here:

https://cmssdt.cern.ch/SDT/cgi-bin/showBuildLogs.py/slc7_amd64_gcc10/www/thu/11.2-thu-23/CMSSW_11_2_X_2020-11-05-2300

Unless the warnings are fixed we cannot start the validation for gcc10
Usually we'd be happy to fix them right away (if they were C++ warnings), but this files are very long and we are not familiar with where the variables should be initialized.

**Comment by mrodozov** [comment]
assign generators

**Comment by agrohsje** [comment]
Hi @mkirsano , @SiewYan. Is one of you available to fix? 
I am wondering about removing 
MCatNLOInterface, which isn't used at all anymore.

**Comment by mkirsano** [comment]
Hello, I am still working on the pythia8 crash, can look only after that

**Comment by SiewYan** [comment]
@mrodozov , i will take a look at it. Sorry, could you remind me i shall fix it on the master branch? Thanks

**Comment by mrodozov** [comment]
Yes, you need master but setup the gcc10 IB, changing the SCRAM_ARCH to slc7_amd64_gcc10

**Comment by SiewYan** [comment]
Thanks, i have setup the gcc10 IB, i will need some time to remove warning message for 16 files. Once all is done i will reference the PR here.

**Comment by SiewYan** [comment]
PR #32109

**Comment by SiewYan** [comment]
Thanks @agrohsje for approving the PR . @mrodozov you may close this issue.

**Comment by SiewYan** [comment]
+1
