### ISSUE TITLE
numberOfThreads does not check for type

### ISSUE THREAD

**Issue by bfonta** [cms-sw/cmssw#32070]
In a ```python``` configuration file, the maximum number of CPU threads to be considered by CMSSW when running a series of modules is specified as follows:

```python
process.options = cms.untracked.PSet(
    numberOfThreads = cms.untracked.uint32(8),
    ... )
```

If the user, by mistake specifies the following:

```python
process.options = cms.untracked.PSet(
    numberOfThreads = cms.untracked.uint32(8),
    numberOfStreams = cms.untracked.int32(8)
    ... )
```

it is prompted with a reasonably looking error:

```shell
Exception Message:
Parameter "numberOfStreams" should be defined as an untracked uint32.
```

However, an equivalent message is not displayed when the mistake happens with ```numberOfThreads```; in that case, the CMSSW modules are run with one thread/stream only (when ```numberOfStreams``` is not specified, it is equal to ```numberOfThreads```).

**Comment by makortel** [comment]
assign core

**Comment by makortel** [comment]
I can reproduce in 11_2_0_pre8 (it's a bit strange though).

Note that already for some time now the `process.options` PSet is pre-defined by the `cms.Process` constructor and you can do just
```python
process = cms.Process("TEST")
process.options.numberOfThreads = 8
process.options.numberOfStream = 8
```

**Comment by makortel** [comment]
Ok, what happens is the following. The `process.options` PSet (throwing the exception for `numberOfStreams`)  is called from `EventProcessor::init()`
https://github.com/cms-sw/cmssw/blob/fc0a40f7e66a9de1b58b0527904da2ce6551d587/FWCore/Framework/src/EventProcessor.cc#L345-L348

The `EventProcessor::init()` is called by its constructor, which is called by `main()`
https://github.com/cms-sw/cmssw/blob/fc0a40f7e66a9de1b58b0527904da2ce6551d587/FWCore/Framework/bin/cmsRun.cpp#L284-L288
but before that the `process.options.numberOfThreads` is accessed here
https://github.com/cms-sw/cmssw/blob/fc0a40f7e66a9de1b58b0527904da2ce6551d587/FWCore/Framework/bin/cmsRun.cpp#L250
https://github.com/cms-sw/cmssw/blob/fc0a40f7e66a9de1b58b0527904da2ce6551d587/FWCore/ParameterSet/src/ThreadsInfo.cc#L17-L19

and then set in the PSet according to the actual value used for the TBB thread pool here
https://github.com/cms-sw/cmssw/blob/fc0a40f7e66a9de1b58b0527904da2ce6551d587/FWCore/Framework/bin/cmsRun.cpp#L267-L268
https://github.com/cms-sw/cmssw/blob/fc0a40f7e66a9de1b58b0527904da2ce6551d587/FWCore/ParameterSet/src/ThreadsInfo.cc#L32

Therefore, if the type of `numberOfThreads` is incorrect, that value is ignored, and the parameter value is overwritten with the default value.

@Dr15Jones Could we simply change the `ops.existsAs()`  to `ops.exists()` in
https://github.com/cms-sw/cmssw/blob/fc0a40f7e66a9de1b58b0527904da2ce6551d587/FWCore/ParameterSet/src/ThreadsInfo.cc#L17-L21
(or do we even need them at all given that `cms.Process` pre-defines the `process.options`) ?

**Comment by makortel** [comment]
We got bitten again by this problem (more details in the description of https://github.com/cms-sw/cmssw/issues/41347)

**Comment by makortel** [comment]
> (or do we even need them at all given that `cms.Process` pre-defines the `process.options`) ?

To answer my own question, I'd say "yes" because we can't really prevent `del process.options.numberOfThreads` (and that does not sound unreasonable way to go back to default).

**Comment by makortel** [comment]
https://github.com/cms-sw/cmssw/pull/41349 attempts to fix along the lines described in https://github.com/cms-sw/cmssw/issues/32070#issuecomment-724242123
