### ISSUE TITLE
[PPC] Unit test in DetectorDescription/Core is failing on PPC 

### ISSUE THREAD

**Issue by mrodozov** [cms-sw/cmssw#32079]
The test testUnits is failing on this assertion:
https://github.com/cms-sw/cmssw/blob/master/DetectorDescription/Core/test/DDUnits.cppunit.cc#L53
on PowerPC 
https://cmssdt.cern.ch/SDT/cgi-bin/logreader/slc7_ppc64le_gcc820/CMSSW_11_2_X_2020-11-05-2300/unitTestLogs/DetectorDescription/Core#/198-198
When the line is commented it runs, and when I put the angle12 to be unsingned:
`unsigned angle120 = convertRadToDeg(twoPiAngle / 3);`
the cout shows angle120 to be 119

**Comment by makortel** [comment]
assign geometry

**Comment by cvuosalo** [comment]
@mrodozov This unit test has been in place for months. Why is it suddenly failing now? What is the urgency of this issue?

**Comment by mrodozov** [comment]
It fails in the PowerPC IB. And it was failing all along, we just want to clear all unit tests in that IB

**Comment by cvuosalo** [comment]
`convertRadToDeg` comes from here:
https://cmssdt.cern.ch/lxr/source/DataFormats/Math/interface/angle_units.h
In effect, it is `angle * 180. / M_PIl`. 

I think we need a Power PC expert to look at these issues, or at least someone who has access to a Power PC.

**Comment by mrodozov** [comment]
We have access to a Power PC, and this is how we are building this IBs
You can request an access for your zh user name here:
https://cern.service-now.com/service-portal?id=sc_cat_item&name=access-openlab-machine&se=it-procurement

**Comment by mrodozov** [comment]
fixed by #33705
