### ISSUE TITLE
Geometry with material budget variations in 2017 and 2018

### ISSUE THREAD

**Issue by rchatter** [cms-sw/cmssw#32072]
For the Higgs mass measurement in the diphoton channel, one of the sources of uncertainty is that on the photon energy scale due to the uncertainty in the modelling of the material budget from the interaction point up to the ECAL. More details  may be found in Section 14.5,1 of  AN-17-036 [1].

This estimate is performed using dedicated samples where the said material budget is varied by +/- 5 and 10%. These [2] were the ones in 2016. For the same in 2017 and 2018 we need to update the relevant material budget estimates due to the new pixel detector [with less material than before]. The original request was made by @gourangakole and discussed in this [3] hypernews thread.

The issue here is to follow up on this request to obtain these geometry conditions for 2017 and 2018 for Run 2 so that we can request similar samples as [2], to re-estimate this systematic uncertainty on the Higgs boson mass. Also tagging the experts @bsunanda , @cvuosalo, @ianna 

Thanks,
@edjtscott , Jin and Rajdeep for the HGG group

[1]: http://cms.cern.ch/iCMS/jsp/db_notes/noteInfo.jsp?cmsnoteid=CMS%20AN-2017/036 
[2]:
/GluGluHToGG_M90_13TeV_amcatnloFXFX_pythia8/RunIISummer16MiniAODv3-PUMoriond17_minus10percentMaterial_94X_mcRun2_asymptotic_v3-v2/MINIAODSIM
/GluGluHToGG_M90_13TeV_amcatnloFXFX_pythia8/RunIISummer16MiniAODv3-PUMoriond17_minus5percentMaterial_94X_mcRun2_asymptotic_v3-v2/MINIAODSIM
/GluGluHToGG_M90_13TeV_amcatnloFXFX_pythia8/RunIISummer16MiniAODv3-PUMoriond17_plus10percentMaterial_94X_mcRun2_asymptotic_v3-v2/MINIAODSIM
/GluGluHToGG_M90_13TeV_amcatnloFXFX_pythia8/RunIISummer16MiniAODv3-PUMoriond17_plus5percentMaterial_94X_mcRun2_asymptotic_v3-v2/MINIAODSIM
/DYJetsToLL_M-50_TuneCUETP8M1_13TeV-amcatnloFXFX-pythia8/RunIISummer16MiniAODv3-PUMoriond17_minus10percentMaterial_94X_mcRun2_asymptotic_v3-v2/MINIAODSIM
/DYJetsToLL_M-50_TuneCUETP8M1_13TeV-amcatnloFXFX-pythia8/RunIISummer16MiniAODv3-PUMoriond17_minus5percentMaterial_94X_mcRun2_asymptotic_v3-v2/MINIAODSIM
/DYJetsToLL_M-50_TuneCUETP8M1_13TeV-amcatnloFXFX-pythia8/RunIISummer16MiniAODv3-PUMoriond17_plus10percentMaterial_94X_mcRun2_asymptotic_v3-v2/MINIAODSIM
/DYJetsToLL_M-50_TuneCUETP8M1_13TeV-amcatnloFXFX-pythia8/RunIISummer16MiniAODv3-PUMoriond17_plus5percentMaterial_94X_mcRun2_asymptotic_v3-v2/MINIAODSIM

[3]:https://hypernews.cern.ch/HyperNews/CMS/get/simDevelopment/1841/2/1/1/1/1/1/1/1/1/1/1/1/1/1/1.html

**Comment by makortel** [comment]
Assign geometry

**Comment by cvuosalo** [comment]
@rchatter The material budget variation scenarios for 2017 and 2018 were created some time ago in `Configuration/Geometry`. I think this issue has been resolved. Do you agree?

**Comment by rchatter** [comment]
> @rchatter The material budget variation scenarios for 2017 and 2018 were created some time ago in `Configuration/Geometry`. I think this issue has been resolved. Do you agree?

Hi @cvuosalo ,
Sorry I hadn't acknowledged this earlier. Yes this issue is resolved since the scenarios were created a while back, and can be closed.
Thanks,
Rajdeep

**Comment by cvuosalo** [comment]
+1
