### ISSUE TITLE
[PPC] Two unit tests failing in Alignment/MillePedeAlignmentAlgorithm

### ISSUE THREAD

**Issue by mrodozov** [cms-sw/cmssw#32084]
Two unit tests are failing in 
Alignment/MillePedeAlignmentAlgorithm
https://cmssdt.cern.ch/SDT/cgi-bin/logreader/slc7_ppc64le_gcc820/CMSSW_11_2_X_2020-11-05-2300/unitTestLogs/Alignment/MillePedeAlignmentAlgorithm#/105-105

running the same script over the (what it looks like) the same .db file:

1.
test_MpsWorkFlow
```
+ mps_prepare_input_db.py -g auto:run2_mc -r 379 -o test_input.db
/scratch/mrodozov/units/DD_Core/CMSSW_11_2_X_2020-11-09-2300/src/Alignment/MillePedeAlignmentAlgorithm/test/test_mps-workflow.sh: line 6: 97448 Segmentation fault      (core dumped) "${@}"
```
2.
test_PrepareInputDb
```
/bin/sh: line 1: 99315 Segmentation fault      (core dumped) while running
mps_prepare_input_db.py -g auto:run2_data -r 1 -o /scratch/mrodozov/units/DD_Core/CMSSW_11_2_X_2020-11-09-2300/tmp/test_input.db
```

To reproduce this access to any of our powerpc machines is required

**Comment by makortel** [comment]
assign alca

**Comment by mmusich** [comment]
> To reproduce this access to any of our powerpc machines is required

Out of curiousity how does one gain access to such machines?

**Comment by mrodozov** [comment]
I think I'll add this to all of this PPC issues:
https://github.com/cms-sw/cmssw/issues/32079#issuecomment-725025273

**Comment by mrodozov** [comment]
@mmusich it's seems it's not as easy as it was (getting access). But still, this is the way

**Comment by mrodozov** [comment]
This problem is present now in the ASAN IBs and it's probably related to Python types not properly passed trough C types
I suspect something wrong with the python part

Most failures in ASAN now are originating from CondTools, CondCore and Alignment all of which end up in frontier_client .

**Comment by tvami** [comment]
assign db

**Comment by mrodozov** [comment]
@tvami see https://github.com/cms-sw/cmssw/issues/33945 and I'll suggest we close this one. This is a consequence to whats in 33945

**Comment by tvami** [comment]
Ok let's close this one then!
