### ISSUE TITLE
[PPC] Unit test failing in Alignment/OfflineValidation

### ISSUE THREAD

**Issue by mrodozov** [cms-sw/cmssw#32085]
One unit test is failing  in Alignment/OfflineValidation :

testAlignmentOfflineValidation

running 

`conddb --yes --db pro copy TrackerAlignment_Upgrade2017_design_v4 --destdb myfile.db`

```
[2020-11-10 19:18:17,791] INFO: Connecting to pro [frontier://PromptProd/CMS_CONDITIONS]
/scratch/mrodozov/units/CMSSW_11_2_X_2020-11-05-2300/src/Alignment/OfflineValidation/test/test_all.sh: line 14: 129282 Segmentation fault      (core dumped) conddb --yes --db pro copy TrackerAlignment_Upgrade2017_design_v4 --destdb myfile.db
[2020-11-10 19:18:18,994] INFO: Connecting to pro [frontier://PromptProd/CMS_CONDITIONS]
/scratch/mrodozov/units/CMSSW_11_2_X_2020-11-05-2300/src/Alignment/OfflineValidation/test/test_all.sh: line 15: 129287 Segmentation fault      (core dumped) conddb --yes --db pro copy TrackerAlignmentErrorsExtended_Upgrade2017_design_v0 --destdb myfile.db
```

https://cmssdt.cern.ch/SDT/cgi-bin/logreader/slc7_ppc64le_gcc820/CMSSW_11_2_X_2020-11-05-2300/unitTestLogs/Alignment/OfflineValidation#/377

note to self: this is not the only DB related issue so I'm thinking could it be arch related (althogh conddb is a python program)

**Comment by makortel** [comment]
assign alca

**Comment by mmusich** [comment]
I think this as well as https://github.com/cms-sw/cmssw/issues/32084 should rather be db-assigned as it is actually `conddb` which is failing

**Comment by christopheralanwest** [comment]
assign db

**Comment by tvami** [comment]
+1
I think this issue is gone, right @mrodozov ?
https://cmssdt.cern.ch/SDT/cgi-bin/logreader/slc7_ppc64le_gcc11/CMSSW_12_3_X_2022-03-03-2300/unitTestLogs/Alignment/OfflineValidation#/

**Comment by smuzaffar** [comment]
correct, frontier client  was patched to fix this issue
