### ISSUE TITLE
Two relvals failing in ROOT6 IBs (root master branch)

### ISSUE THREAD

**Issue by mrodozov** [cms-sw/cmssw#32142]
After merging changes following a delay in ROOT6 IBs (root master branch IBs)
two relvals started failing with what looks like a root exception about "duplicate labels"
`[a] Fatal Root Error: @SUB=TH1Merger::CheckForDuplicateLabels`
I think this is the setup for the histo in question:
https://github.com/cms-sw/cmssw/blob/master/DQM/EcalMonitorTasks/python/TimingTask_cfi.py#L152
so it's DQM

**Comment by mrodozov** [comment]
assign dqm

**Comment by jfernan2** [comment]
@tanmaymudholkar @alejands   can you please provide a fix?

**Comment by alejands** [comment]
Hi Javi,

Thank you. We will look into this. A couple of of questions.

(1): How do we replicate this error? This is not clear to us. Would is be possible to see the full error stack?

(2): What is the urgency -- should we just remove the plot in question for the time being (it's just one plot) or can we get a bit more time?

Alejandro for ECAL DQM

**Comment by mrodozov** [comment]
Hi there,
to replicated this you need to:
```
ssh cmsdev20 # 20 to 25 are cmsdev machines 
cd /build/ ; mkdir $USER ; cd $USER
scram list ROOT6
# pick a ROOT6 IB, for example 
scram p CMSSW_11_2_ROOT6_X_2020-11-22-0000
cd CMSSW_11_2_ROOT6_X_2020-11-22-0000/src ; cmsenv
git-cms-addpkg DQM/EcalMonitorTasks
scram b -j 16 # build the DQM/EcalMonitorTasks package
voms-proxy-init # init your proxy 
# the two failing relvals are 136.8861 and 137.8
runTheMatrix.py -i all -l 137.8,136.8861 --ibeos
```
you can see the failures here (older IB, the new is still running)
https://cmssdt.cern.ch/SDT/html/cmssdt-ib/#/relVal/CMSSW_11_2/2020-11-20-2300?selectedArchs=slc7_amd64_gcc820&selectedFlavors=ROOT6_X&selectedStatus=failed

**Comment by alejands** [comment]
Hello,

We have a fix ready. Which branch do we make a PR to? 

Alejandro for ECAL DQM

**Comment by makortel** [comment]
> Which branch do we make a PR to?

In CMSSW `master` as usual, thanks. (the ROOT master IBs uses the same CMSSW branch)

**Comment by alejands** [comment]
Hello,

We've submitted a PR here: https://github.com/cms-sw/cmssw/pull/32250

We noticed that the same issue had previously occurred with JetMET https://github.com/cms-sw/cmssw/issues/27472 and fixed here https://github.com/cms-sw/cmssw/pull/27647. It may be worth documenting this issue.

Alejandro for ECAL DQM

**Comment by jfernan2** [comment]
+1
The PR seems to solve the issue
