### ISSUE TITLE
Unit test failing in DQM/Integration

### ISSUE THREAD

**Issue by mrodozov** [cms-sw/cmssw#32160]
A unit test started failing in DQM/Integration since 12.11, 
failure is not present in all IBs but it's failing consistently since that date, on and off

https://cmssdt.cern.ch/SDT/cgi-bin/logreader/slc7_amd64_gcc820/CMSSW_11_2_X_2020-11-15-0000/unitTestLogs/DQM/Integration#/52

**Comment by mrodozov** [comment]
assign dqm

**Comment by jfernan2** [comment]
I believe this is being fixed by this PR https://github.com/cms-sw/cmssw/pull/32136

**Comment by mrodozov** [comment]
lets hope so then :) when it's fixed I'll close the issue

**Comment by mrodozov** [comment]
it's gone. closing
