### ISSUE TITLE
Automatically check for unsafe PSet attribute overrides

### ISSUE THREAD

**Issue by jpata** [cms-sw/cmssw#32177]
There's now been a lot of work to clean up python configs in reco from unsafe overrides in PSet attributes (e.g. https://github.com/cms-sw/cmssw/pull/32171).

I was wondering if there was a way to check for these unsafe overrides automatically (either as an offline reco check, or as part of `code-checks`) based on checks introduced to `__setattr__` in `PSet` and `_Module`.

With the following modifications https://github.com/jpata/cmssw/commit/61fd7d0c753b69fb513398a6f2c2d3b2a0546083 (obviously to be improved), I'm already able to get a decent set of warnings for one of the files addressed in the above PR.

```python
$ python RecoHI/Configuration/python/Reconstruction_hiPF_cff.py | sort | uniq | grep Reconstruction_hiPF_cff
unsafe override of 'ctfTracks' in RecoHI/Configuration/python/Reconstruction_hiPF_cff.py:10:<module>
unsafe override of 'ctfTracksTag' in RecoHI/Configuration/python/Reconstruction_hiPF_cff.py:11:<module>
unsafe override of 'elementImporters' in RecoHI/Configuration/python/Reconstruction_hiPF_cff.py:79:<module>
unsafe override of 'enable' in RecoHI/Configuration/python/Reconstruction_hiPF_cff.py:87:<module>
unsafe override of 'Enable' in RecoHI/Configuration/python/Reconstruction_hiPF_cff.py:88:<module>
unsafe override of 'enable' in RecoHI/Configuration/python/Reconstruction_hiPF_cff.py:89:<module>
unsafe override of 'Enable' in RecoHI/Configuration/python/Reconstruction_hiPF_cff.py:90:<module>
unsafe override of 'fillConvVtxFitProb' in RecoHI/Configuration/python/Reconstruction_hiPF_cff.py:15:<module>
unsafe override of 'maxEOverPBarrel' in RecoHI/Configuration/python/Reconstruction_hiPF_cff.py:30:<module>
unsafe override of 'maxEOverPEndcaps' in RecoHI/Configuration/python/Reconstruction_hiPF_cff.py:31:<module>
unsafe override of 'maxHOverEBarrelCone' in RecoHI/Configuration/python/Reconstruction_hiPF_cff.py:26:<module>
unsafe override of 'maxHOverEBarrelTower' in RecoHI/Configuration/python/Reconstruction_hiPF_cff.py:28:<module>
unsafe override of 'maxHOverEEndcapsCone' in RecoHI/Configuration/python/Reconstruction_hiPF_cff.py:27:<module>
unsafe override of 'maxHOverEEndcapsTower' in RecoHI/Configuration/python/Reconstruction_hiPF_cff.py:29:<module>
unsafe override of 'minSCEtBarrel' in RecoHI/Configuration/python/Reconstruction_hiPF_cff.py:13:<module>
unsafe override of 'minSCEtEndcaps' in RecoHI/Configuration/python/Reconstruction_hiPF_cff.py:14:<module>
unsafe override of 'muons' in RecoHI/Configuration/python/Reconstruction_hiPF_cff.py:84:<module>
unsafe override of 'Muons' in RecoHI/Configuration/python/Reconstruction_hiPF_cff.py:91:<module>
unsafe override of 'postMuonCleaning' in RecoHI/Configuration/python/Reconstruction_hiPF_cff.py:82:<module>
unsafe override of 'primaryVertexProducer' in RecoHI/Configuration/python/Reconstruction_hiPF_cff.py:17:<module>
unsafe override of 'primaryVertexProducer' in RecoHI/Configuration/python/Reconstruction_hiPF_cff.py:19:<module>
unsafe override of 'primaryVertexProducer' in RecoHI/Configuration/python/Reconstruction_hiPF_cff.py:33:<module>
unsafe override of 'primaryVertexProducer' in RecoHI/Configuration/python/Reconstruction_hiPF_cff.py:35:<module>
unsafe override of 'trackProducer' in RecoHI/Configuration/python/Reconstruction_hiPF_cff.py:18:<module>
unsafe override of 'trackProducer' in RecoHI/Configuration/python/Reconstruction_hiPF_cff.py:20:<module>
unsafe override of 'trackProducer' in RecoHI/Configuration/python/Reconstruction_hiPF_cff.py:34:<module>
unsafe override of 'trackProducer' in RecoHI/Configuration/python/Reconstruction_hiPF_cff.py:36:<module>
unsafe override of 'usePFConversions' in RecoHI/Configuration/python/Reconstruction_hiPF_cff.py:85:<module>
unsafe override of 'vertexCollection' in RecoHI/Configuration/python/Reconstruction_hiPF_cff.py:83:<module>
unsafe override of 'vertexCollection' in RecoHI/Configuration/python/Reconstruction_hiPF_cff.py:9:<module>
unsafe override of 'vertexTag' in RecoHI/Configuration/python/Reconstruction_hiPF_cff.py:40:<module>
unsafe override of 'vertices' in RecoHI/Configuration/python/Reconstruction_hiPF_cff.py:21:<module>
unsafe override of 'vtxTag' in RecoHI/Configuration/python/Reconstruction_hiPF_cff.py:12:<module>
```

I would like to understand from the core team & others if you think this is a feasible approach and what are the potential improvements/pitfalls/considerations to introducing a tool or check for this.

cc @slava77

**Comment by jpata** [comment]
assing core, reconstruction

**Comment by makortel** [comment]
@jpata Could you clarify what do you mean with "unsafe PSet attribute overrides"?

**Comment by jpata** [comment]
For the reco migration campaing, the criterion was so far whenever the type was redefined (but could instead be assumed implicitly), for example:
https://github.com/cms-sw/cmssw/pull/32171/files#diff-ed50331777a0be0f1b34490d337792a73bc96b3e8204a95cf8f287b527843e2dL9

**Comment by jpata** [comment]
My current prototype does not detect overrides in `PSet.clone()` e.g. https://github.com/cms-sw/cmssw/pull/32171/files#diff-e53ff3f23fe86465268f25002e18b0422bf46d3fb1c96318a5578b067c39e806R21, but perhaps there's a way to add that too (will need to investigate).

**Comment by makortel** [comment]
Would the aim be to detect the places where an explicit type is used in an assignment, and remove the explicit types?

**Comment by jpata** [comment]
What you describe was recently done manually over many maintenance PRs touching all reco packages.

I was wondering if we can have an automatic check to warn if a future PR reintroduces any such case. 

Fixing would be manual.

**Comment by makortel** [comment]
Here are some concerns for general inclusion of a check if the assigned value has an explicit type or not
* There may be code that relies on being able to change parameter type with an assignment
* There are types in the configuration that (currently) can not be assigned-to without an explicit type

A more general place for the check could be
https://github.com/cms-sw/cmssw/blob/fa3869f3f43eb91d641a02b48451fe503c923d63/FWCore/ParameterSet/python/Mixins.py#L279-L281

**Comment by jpata** [comment]
-reconstruction
- not going to be addressed

**Comment by makortel** [comment]
-1

for the record
