### ISSUE TITLE
Revisit use of HitPattern in DataFormats/Scouting

### ISSUE THREAD

**Issue by makortel** [cms-sw/cmssw#32219]
https://github.com/cms-sw/cmssw/pull/31962 added use of complex data structure `reco::HitPattern` in `Run3ScoutingMuon`. It was [agreed](https://github.com/cms-sw/cmssw/pull/31962#issuecomment-729255742) to revisit that usage before the data taking of Run3 to either remove the usage (as too heavy for production use), or replace with e.g. a frozen version of `HitPattern` that could be easy to guarantee to be read in any later release.

The purpose of this issue is to act as a reminder.

**Comment by makortel** [comment]
assign core,hlt

**Comment by makortel** [comment]
Any news yet on whether `HitPattern` like information will be needed for `Run3ScoutingMuon`? @jsalfeld

**Comment by jsalfeld** [comment]
@mmasciov wanted to check

(cc'ing @dsperka )

**Comment by silviodonato** [comment]
I remember about this issue. Thank you Matti and Jakob for raising this up. I will keep this in mind that this need to be solved much before the data taking.
cc @acostad

**Comment by makortel** [comment]
Is there any chance this question could be resolved already for 12_1_0?

**Comment by mmasciov** [comment]
@makortel: if it is OK with you, given that recent measurements by @dsperka showed that HitPattern for Run3ScoutingMuon shall not be heavy at all, I'll go with option (2). I.e., I'll make a frozen copy of HitPattern for scouting, and use such copy in Run3ScoutingMuon.

**Comment by mmasciov** [comment]
As for the timeline, this option should be fast, and in time for 12_1_0 (before 19th of October).

**Comment by makortel** [comment]
Thanks @mmasciov, that option is fine. For the record, could you give pointer to
>  @dsperka showed that HitPattern for Run3ScoutingMuon shall not be heavy at all

?

**Comment by mmasciov** [comment]
The latest slides showing that muons are little in size should be: https://indico.cern.ch/event/1066775/contributions/4492263/attachments/2301466/3914859/scouting_event_content_xpog.pdf
However, @dsperka may have more recent/accurate numbers.

**Comment by VinInn** [comment]
If possible I would change current HitPattern to
```
template<int N>
HitPatternT;

and then have to aliases
using HitPattern = HitPatternT<kOfflineHitPatternSize>;
and
using HitPatternScouting = HitPatternT<kScoutingHitPatternSize>;

if (kScoutingHitPatternSize==kOfflineHitPatternSize) memcpy is enough
if (kScoutingHitPatternSize<kOfflineHitPatternSize) a custom copy constructor should work.
I do not expect kScoutingHitPatternSize>kOfflineHitPatternSize will ever happen....

up to the expert to guess the proper versioning mechanism for the offline version

**Comment by slava77** [comment]
if the past can be a reference for possible developments, the size of the array is not the only thing that can change; other data members (indices) can change as well.

**Comment by missirol** [comment]
+hlt

 - addressed by @mmasciov in https://github.com/cms-sw/cmssw/pull/37149

**Comment by makortel** [comment]
+core
