### ISSUE TITLE
RootEmbeddedFileSequence no input files specified for secondary input source

### ISSUE THREAD

**Issue by silviodonato** [cms-sw/cmssw#32237]
Several workflows (12634.0, 12634.99, 13034.0, 13034.99) are crashing in `CMSSW_11_2_X_2020-11-21-1100`. Most likely the crash is related to #32140

```
----- Begin Fatal Exception 21-Nov-2020 12:54:14 CET-----------------------
An exception of category 'NoSecondaryFiles' occurred while
   [0] Constructing the EventProcessor
   [1] Constructing module: class=MixingModule label='mix'
Exception Message:
RootEmbeddedFileSequence no input files specified for secondary input source.
----- End Fatal Exception -------------------------------------------------
```

**Comment by silviodonato** [comment]
assign pdmv

**Comment by silviodonato** [comment]
12634.0 and 12634.99 has ` --pileup_input das:/RelValMinBias_14TeV/CMSSW_11_2_0_pre8-112X_mcRun3_2023_realistic_v10-v1/GEN-SIM`
13034.0 and 13034.99 has `--pileup_input das:/RelValMinBias_14TeV/CMSSW_11_2_0_pre8-112X_mcRun3_2024_realistic_v10-v1/GEN-SIM`

**Comment by chayanit** [comment]
@silviodonato OK, I have submitted them, should be ready by the end of today or tomorrow

**Comment by silviodonato** [comment]
Everything is ok in `CMSSW_11_2_X_2020-11-23-1100`
