### ISSUE TITLE
reduce size of low-pt electron training forest

### ISSUE THREAD

**Issue by slava77** [cms-sw/cmssw#32293]
as found during integration of #31220 the ID GBRForest is taking up about 60MB in memory. This is large (although not yet prohibitively so, considering per-job allocation).

Some effort should be made to reduce the size of the model/trees at some minimal cost to performance.

@bainbrid @jainshilpi @lfinco @afiqaize @SohamBhattacharya

**Comment by slava77** [comment]
assign reconstruction

**Comment by bainbrid** [comment]
@crovelli @cavalari

**Comment by slava77** [comment]
+1

closing this for now, 
after a fairly significant reduction provided with https://github.com/cms-sw/cmssw/pull/32391#issuecomment-751284274 (the PR was merged Jan 11, 2021)
