### ISSUE TITLE
How do I call github files from a CMSSW python configuration file? 

### ISSUE THREAD

**Issue by lgemedia** [cms-sw/cmssw#32306]
How do I call github files from a python configuration file? 
For instance, my original python ConfFile_XXX_RECO_withDedx.py says:
process.load("UserCode.EnergyLossPID.EnergyLossProducer_cff")
My new github usercode is:  lgemedia/EnergyLossPID .
How do I get access to the EnergyLossPID project from python config?

Thanks
Luiz

**Comment by silviodonato** [comment]
Please try with 
```
cmsrel CMSSW_X_Y_Z
cd CMSSW_X_Y_Z/src
cmsenv
mkdir UserCode
cd UserCode/
git clone git@github.com:lgemedia/EnergyLossPID.git
cd ..
scram b -j8
```
clearly `CMSSW_X_Y_Z` correspond to the actual version of CMSSW you used to develop your tool.

**Comment by lgemedia** [comment]
Hi Silvio,

Thanks a lot for the information.

Best,
Luiz
