### ISSUE TITLE
re-enable ctppsProtons for Run3 after #32352 

### ISSUE THREAD

**Issue by slava77** [cms-sw/cmssw#32356]
this depends on the resolution of #32340 and/or  #32207

**Comment by slava77** [comment]
assign reconstruction

**Comment by slava77** [comment]
@jan-kaspar 
are we in a position to re-enable the PPS proton reco, or is there still some work in progress?

**Comment by jan-kaspar** [comment]
Thanks for brining this up!

I might not be the best person to ask. I am also adding @fabferro .

From the perspective of the PPS reco SW, I don't see a problem to go ahead.

As far as I remember, the PPS reco was disabled due to the problem https://github.com/cms-sw/cmssw/issues/32340 - this appears in a (full) simu WF. @mundim is reponsible for PPS simu SW and he may know better. Also @clemencia may know whether the simu DB tags have already been updated.

BTW: we have decided that (at least for the moment) the conditions handling from https://github.com/cms-sw/cmssw/pull/32207 would only be used in PPS "direct" simulation. Mostly not to complicate any further the start up of the PPS full simu.

**Comment by slava77** [comment]
> I might not be the best person to ask. I am also adding @fabferro .
> 
> From the perspective of the PPS reco SW, I don't see a problem to go ahead.
> 
> As far as I remember, the PPS reco was disabled due to the problem #32340 - this appears in a (full) simu WF. @mundim is reponsible for PPS simu SW and he may know better. Also @clemencia may know whether the simu DB tags have already been updated.

It would be nice to get some more explicit feedback.


@silviodonato 
before trying to revert #32352, please remind me which workflow #s were failing so that a check can be done with the bot.

**Comment by silviodonato** [comment]
@slava77 looking at https://github.com/cms-sw/cmssw/issues/32340 almost all Run-3 workflows were crashing. The problem was that the crash happens after more than 100 events.
In `/afs/cern.ch/work/s/sdonato/public/debug_PPS/badd237c-4857-4f48-b10f-52c832f57f02_ev1126.root` I selected a single GEN-SIM-DIGI-RAW event causing the cras (taken from `root://cms-xrd-global.cern.ch//store/relval/CMSSW_11_2_0_pre10/RelValTTbar_14TeV/GEN-SIM-DIGI-RAW/112X_mcRun3_2021_realistic_v13_rsb-v1/00000/badd237c-4857-4f48-b10f-52c832f57f02.root`).
This dataset was generated with `11634.0` (@cms-sw/pdmv-l2  please correct me if I'm wrong)

**Comment by slava77** [comment]
@mundim @fabferro 
do we have a more specific PPS simulation workflow where some inputs to the PPS proton reconstruction can appear in the first (few) events?

**Comment by chayanit** [comment]
> @slava77 looking at #32340 almost all Run-3 workflows were crashing. The problem was that the crash happens after more than 100 events.
> In `/afs/cern.ch/work/s/sdonato/public/debug_PPS/badd237c-4857-4f48-b10f-52c832f57f02_ev1126.root` I selected a single GEN-SIM-DIGI-RAW event causing the cras (taken from `root://cms-xrd-global.cern.ch//store/relval/CMSSW_11_2_0_pre10/RelValTTbar_14TeV/GEN-SIM-DIGI-RAW/112X_mcRun3_2021_realistic_v13_rsb-v1/00000/badd237c-4857-4f48-b10f-52c832f57f02.root`).
> This dataset was generated with `11634.0` (@cms-sw/pdmv-l2 please correct me if I'm wrong)

Yes, this dataset is 11634.0

**Comment by fabferro** [comment]
It's not fully clear to me why the crash happens after ~100 events. The only reason I can imagine is that no proton needs to be propagated in the first ~100 events, therefore I can't indicate a "better" workflow.
As to the issue of the missing record (LHCInfo), we have prepared the proper sqlite file, going to test it and then send it for imlementation in the GT. Sorry for being late.

**Comment by mundim** [comment]
> @mundim @fabferro
> do we have a more specific PPS simulation workflow where some inputs to the PPS proton reconstruction can appear in the first (few) events?

Hi @slava77. There are two possible ways to do it, using a particle gun that shoots protons inside the acceptance of PPS or using ExHume also inside the PPS phase space. What do you prefer, I can send you a piece of configuration for either one.

**Comment by mundim** [comment]
> > @slava77 looking at #32340 almost all Run-3 workflows were crashing. The problem was that the crash happens after more than 100 events.
> > In `/afs/cern.ch/work/s/sdonato/public/debug_PPS/badd237c-4857-4f48-b10f-52c832f57f02_ev1126.root` I selected a single GEN-SIM-DIGI-RAW event causing the cras (taken from `root://cms-xrd-global.cern.ch//store/relval/CMSSW_11_2_0_pre10/RelValTTbar_14TeV/GEN-SIM-DIGI-RAW/112X_mcRun3_2021_realistic_v13_rsb-v1/00000/badd237c-4857-4f48-b10f-52c832f57f02.root`).
> > This dataset was generated with `11634.0` (@cms-sw/pdmv-l2 please correct me if I'm wrong)
> 
> Yes, this dataset is 11634.0

Sorry, I could not find the error messages, can you point me to them, please? Maybe I can have a more precise idea looking at them. Thanks.

**Comment by slava77** [comment]
> Hi @slava77. There are two possible ways to do it, using a particle gun that shoots protons inside the acceptance of PPS or using ExHume also inside the PPS phase space. What do you prefer, I can send you a piece of configuration for either one.

Either way (a gun or ExHume sound fine). I was looking -- at least eventually -- for a numbered workflow in the runTheMatrix.py

**Comment by mundim** [comment]
To where do you want me to send the piece of python config? Here or to your email?

**Comment by slava77** [comment]
> To where do you want me to send the piece of python config? Here or to your email?

@cms-sw/pdmv-l2 
should be able to point to the right places
IIUC, it will involve Configuration/PyReleaseValidation/python/relval_upgrade.py, Configuration/PyReleaseValidation/python/relval_steps.py, Configuration/PyReleaseValidation/python/upgradeWorkflowComponents.py
and if this requires a new GEN fragment, I guess it will also be a file in Configuration/Generator/python/ to be coordinated with @cms-sw/generators-l2

**Comment by chayanit** [comment]
@mundim here is the list of python configs included already in runTheMatrix. If your config is not yet there, you will need to include one (suggest at the bottom to not ruin the order of workflow ID). https://github.com/cms-sw/cmssw/blob/master/Configuration/PyReleaseValidation/python/upgradeWorkflowComponents.py#L1165

**Comment by mundim** [comment]
@chayanit Thanks. It seems the fragment is not there, but I'm afraid I have not understood the syntax to include it. I'll have a look at the other fragments to see if some adaptation is needed, but could someone give me the instructions about how to include it, please? Thanks.

**Comment by chayanit** [comment]
@mundim , when you have your GEN fragment, you will need add it to two place
- Configuration/Generator/python/ which will be approved by @cms-sw/generators-l2 
- Configuration/PyReleaseValidation/python/upgradeWorkflowComponents.py : to call your GEN fragment and enable it in runTheMatrix as a new workflow added. You should add it below this line in a similar style https://github.com/cms-sw/cmssw/blob/master/Configuration/PyReleaseValidation/python/upgradeWorkflowComponents.py#L1290
- ('Name of Fragment file', UpgradeFragment(Kby(9,50), 'Name of output dataset')), 
- UpgradeFragment(Kby(9,50) obtain the number of events to be produced as 9k and submit 50 events per job in production
- Name of output dataset is a bit flexible but should tell which process it is and please try to keep it short but clear

**Comment by mundim** [comment]
@chayanit, sorry for the long time to reply. I prepared a fragment as you told above. Is there a special way to test it or just run runTheMatrix as usual? Thanks a lot

**Comment by mundim** [comment]
> > > @slava77 looking at #32340 almost all Run-3 workflows were crashing. The problem was that the crash happens after more than 100 events.
> > > In `/afs/cern.ch/work/s/sdonato/public/debug_PPS/badd237c-4857-4f48-b10f-52c832f57f02_ev1126.root` I selected a single GEN-SIM-DIGI-RAW event causing the cras (taken from `root://cms-xrd-global.cern.ch//store/relval/CMSSW_11_2_0_pre10/RelValTTbar_14TeV/GEN-SIM-DIGI-RAW/112X_mcRun3_2021_realistic_v13_rsb-v1/00000/badd237c-4857-4f48-b10f-52c832f57f02.root`).
> > > This dataset was generated with `11634.0` (@cms-sw/pdmv-l2 please correct me if I'm wrong)
> > 
> > 
> > Yes, this dataset is 11634.0
> 
> Sorry, I could not find the error messages, can you point me to them, please? Maybe I can have a more precise idea looking at them. Thanks.

Testing this particular wf with the new fragment, produce no errors (1 1 1 1 1 tests passed, 0 0 0 0 0 failed), but I'm not sure if the generator fragment I introduced is begin executed.

**Comment by chayanit** [comment]
> > > > @slava77 looking at #32340 almost all Run-3 workflows were crashing. The problem was that the crash happens after more than 100 events.
> > > > In `/afs/cern.ch/work/s/sdonato/public/debug_PPS/badd237c-4857-4f48-b10f-52c832f57f02_ev1126.root` I selected a single GEN-SIM-DIGI-RAW event causing the cras (taken from `root://cms-xrd-global.cern.ch//store/relval/CMSSW_11_2_0_pre10/RelValTTbar_14TeV/GEN-SIM-DIGI-RAW/112X_mcRun3_2021_realistic_v13_rsb-v1/00000/badd237c-4857-4f48-b10f-52c832f57f02.root`).
> > > > This dataset was generated with `11634.0` (@cms-sw/pdmv-l2 please correct me if I'm wrong)
> > > 
> > > 
> > > Yes, this dataset is 11634.0
> > 
> > 
> > Sorry, I could not find the error messages, can you point me to them, please? Maybe I can have a more precise idea looking at them. Thanks.
> 
> Testing this particular wf with the new fragment, produce no errors (1 1 1 1 1 tests passed, 0 0 0 0 0 failed), but I'm not sure if the generator fragment I introduced is begin executed.


@mundim it seems I missed the PR. Can you share the link to PR? Which command line have you tried?

**Comment by mundim** [comment]
Hi @chayanit , I tried first:
runTheMatrix.py --job-reports --ibeos -i all -l 11634.0
with no error.

Then I tried
runTheMatrix.py --job-reports  -j 16 -l limited --ibeos
some to the wf failed possibly due to time out: 4.53,25.0,135.4,312.0,1306.0,1330.0,136.731,136.793,136.874,10224.0,25202.0

I ran a second time with only these ones and finally, none failed.

But I'm not sure the fragment I'm trying to include is being executed.

**Comment by slava77** [comment]
from the list in https://github.com/cms-sw/cmssw/issues/32356#issuecomment-768239837 I don't see how any of these can possibly include a new fragment (unless perhaps in a local test there was a manual replacement of an existing file)

**Comment by mundim** [comment]
I tried already to find documentation about the runTheMatrix options, but I didn't find it, maybe I have not searched enough. I never learned what those numbers mean, if someone points me to a description about it I will really appreciate it, this will certainly not be the last time I will need it. Thank you very much.

**Comment by mundim** [comment]
> from the list in [#32356 (comment)](https://github.com/cms-sw/cmssw/issues/32356#issuecomment-768239837) I don't see how any of these can possibly include a new fragment (unless perhaps in a local test there was a manual replacement of an existing file)

Just to make it clearer:

I added, in a working area (CMSSW_11_3_X_2021-01-25-1100)

Configuration/Generator
Configuration/PyReleaseValidation

I added the file:
Configuration/Generator/python/GluGluTo2Jets_M_300_2000_14TeV_Exhume_cff.py
which contains the fragment 
I added the line:
`    ('GluGluTo2Jets_M_300_2000_14TeV_Exhume_cff.py',UpgradeFragment(Kby(9,100),'GluGluTo2Jets_M_300_2000_14TeV')),`

at the end of Configuration/PyReleaseValidation/python/upgradeWorkflowComponents.py

**Comment by mundim** [comment]
Don't we need to create a new wf number for this fragment? Sorry, just wondering

**Comment by slava77** [comment]
I think that a new wf may just show up in the list already; take a look at `runTheMatrix.py -n -w upgrade | grep GluGluTo2Jets_M`

**Comment by mundim** [comment]
@slava77, YES! It is there.
But which option I have to use to execute it, because the previous format hasn't. It something "-w upgrade"?
Thank you very much.

**Comment by mundim** [comment]
Sorry, @slava77, I found how to run it. Thanks and sorry to bother you.

**Comment by slava77** [comment]
for 2021 without PU we can use 116XX.0 (where XX should match your new fragment wf index).
This value will need to be entered in https://github.com/cms-sw/cmssw/blob/master/Configuration/PyReleaseValidation/python/relval_2017.py#L60 so that it can also be picked up by the cms-bot for tests (or/same as also being visible with `runTheMatrix.py -l 116XX.0` without `-w upgrade`)

**Comment by mundim** [comment]
Sorry, I thought I had found out how to run it but I was mistaken. There are quite a lot of wf numbers in the output of the command you told me, for instance:
`12125.0 2021Design+GluGluTo2Jets_M_300_2000_14TeV_Exhume_GenSim+Digi+Reco+HARVEST `
Should I include all of them in the file as you told me above?
In this particular example, the index is 25 (with a prefix of 121) or it is the full number 12125.0?

Thank you.

**Comment by slava77** [comment]
I was proposing a wf starting with 116

**Comment by slava77** [comment]
> I was proposing a wf starting with 116

ah, I guess if the number of fragments is over 100, this is 11600+125; based on what I'm guessing from 12125

**Comment by mundim** [comment]
> > I was proposing a wf starting with 116
> 
> ah, I guess if the number of fragments is over 100, this is 11600+125; based on what I'm guessing from 12125

That makes sense.. I'll try. Thank you. 

Can you confirm I have to include ALL the wf output by `runTheMatrix.py -n -w upgrade | grep GluGluTo2Jets_M` and in which file (relval_2017?). Thanks again.

**Comment by slava77** [comment]
> Can you confirm I have to include ALL the wf output by `runTheMatrix.py -n -w upgrade | grep GluGluTo2Jets_M` and in which file (relval_2017?). Thanks again.

for now we only need a test with 2021, so, please add just 11725.0.
Thank you.

**Comment by mundim** [comment]
Sorry, but it is still not clear to me. You asked to include the wf in the file relval_2017.py but this is not the year I suppose is the correct one, however, there is no relval_2021.py, only relval_2026.py among others like relval_upgrade.py and relval_standard.py. Which one am I supposed to include this wf?

Thank you.

**Comment by chayanit** [comment]
Thanks @slava77 for helping here as well. 

@mundim could you share the list when you run `runTheMatrix.py --what upgrade --showMatrix | grep -i GluGluTo2Jets_M | grep 2021`? I can help checking which ID should be used. It should show you the workflow ID of GluGluTo2Jets_M and we need to pickup one ID to test locally.

I have another command to run 5 events local test you can try if your fragment works. 
`runTheMatrix.py --what upgrade -l 116XX -t 4 --command='-n 5' >& run5evt.log &` 

PS.  We only have this documentation for RelVal team and it might help you understand a bit how runTheMatrix works.  https://twiki.cern.ch/twiki/bin/viewauth/CMS/PdmVRelValInstruction#Relval_Framework

**Comment by mundim** [comment]
Thank you very much @chayanit. For your first request: 

`
11725.0 2021+GluGluTo2Jets_M_300_2000_14TeV_Exhume_GenSim+Digi+Reco+HARVEST+ALCA 
11925.0 2021PU+GluGluTo2Jets_M_300_2000_14TeV_Exhume_GenSim+DigiPU+RecoPU+HARVESTPU+Nano 
11925.98 2021PU_PMXS2+GluGluTo2Jets_M_300_2000_14TeV_Exhume_GenSim+DigiPU+RecoPU+HARVESTPU+Nano 
11925.99 2021PU_PMXS1S2+GluGluTo2Jets_M_300_2000_14TeV_Exhume_GenSim+PREMIX_PremixPU+DigiPU+RecoPU+HARVESTPU+Nano 
12125.0 2021Design+GluGluTo2Jets_M_300_2000_14TeV_Exhume_GenSim+Digi+Reco+HARVEST 
12325.0 2021DesignPU+GluGluTo2Jets_M_300_2000_14TeV_Exhume_GenSim+DigiPU+RecoPU+HARVESTPU 
12325.98 2021DesignPU_PMXS2+GluGluTo2Jets_M_300_2000_14TeV_Exhume_GenSim+DigiPU+RecoPU+HARVESTPU 
12325.99 2021DesignPU_PMXS1S2+GluGluTo2Jets_M_300_2000_14TeV_Exhume_GenSim+PREMIX_PremixPU+DigiPU+RecoPU+HARVESTPU 
`
I'll send the rest in a while.

**Comment by mundim** [comment]
For the second command, it looks like there is a problem. The output is:
`GEN,SIM,ENDJOB
We have determined that this is simulation (if not, rerun cmsDriver.py with --data)
with DB:
Step: GEN Spec:
Loading generator fragment from Configuration.Generator.GluGluTo2Jets_M_300_2000_14TeV_Exhume_cff
Traceback (most recent call last):
  File "/cvmfs/cms-ib.cern.ch/week1/slc7_amd64_gcc900/cms/cmssw/CMSSW_11_3_X_2021-01-25-1100/bin/slc7_amd64_gcc900/cmsDriver.py", line 56, in <module>
    run()
  File "/cvmfs/cms-ib.cern.ch/week1/slc7_amd64_gcc900/cms/cmssw/CMSSW_11_3_X_2021-01-25-1100/bin/slc7_amd64_gcc900/cmsDriver.py", line 28, in run
    configBuilder.prepare()
  File "/cvmfs/cms-ib.cern.ch/week1/slc7_amd64_gcc900/cms/cmssw/CMSSW_11_3_X_2021-01-25-1100/python/Configuration/Applications/ConfigBuilder.py", line 2131, in prepare
    self.addStandardSequences()
  File "/cvmfs/cms-ib.cern.ch/week1/slc7_amd64_gcc900/cms/cmssw/CMSSW_11_3_X_2021-01-25-1100/python/Configuration/Applications/ConfigBuilder.py", line 757, in addStandardSequences
    getattr(self,"prepare_"+stepName)(sequence = getattr(self,stepName+"DefaultSeq"))
  File "/cvmfs/cms-ib.cern.ch/week1/slc7_amd64_gcc900/cms/cmssw/CMSSW_11_3_X_2021-01-25-1100/python/Configuration/Applications/ConfigBuilder.py", line 1337, in prepare_GEN
    raise Exception("Neither gen fragment of input files provided: this is an inconsistent GEN step configuration")
Exception: Neither gen fragment of input files provided: this is an inconsistent GEN step configuration
`

**Comment by chayanit** [comment]
> Thank you very much @chayanit. For your first request:
> 
> `
> 11725.0 2021+GluGluTo2Jets_M_300_2000_14TeV_Exhume_GenSim+Digi+Reco+HARVEST+ALCA
> 
> 11925.0 2021PU+GluGluTo2Jets_M_300_2000_14TeV_Exhume_GenSim+DigiPU+RecoPU+HARVESTPU+Nano
> 
> 11925.98 2021PU_PMXS2+GluGluTo2Jets_M_300_2000_14TeV_Exhume_GenSim+DigiPU+RecoPU+HARVESTPU+Nano
> 
> 11925.99 2021PU_PMXS1S2+GluGluTo2Jets_M_300_2000_14TeV_Exhume_GenSim+PREMIX_PremixPU+DigiPU+RecoPU+HARVESTPU+Nano
> 
> 12125.0 2021Design+GluGluTo2Jets_M_300_2000_14TeV_Exhume_GenSim+Digi+Reco+HARVEST
> 
> 12325.0 2021DesignPU+GluGluTo2Jets_M_300_2000_14TeV_Exhume_GenSim+DigiPU+RecoPU+HARVESTPU
> 
> 12325.98 2021DesignPU_PMXS2+GluGluTo2Jets_M_300_2000_14TeV_Exhume_GenSim+DigiPU+RecoPU+HARVESTPU
> 
> 12325.99 2021DesignPU_PMXS1S2+GluGluTo2Jets_M_300_2000_14TeV_Exhume_GenSim+PREMIX_PremixPU+DigiPU+RecoPU+HARVESTPU
> `
> I'll send the rest in a while.

I think 11725.0 is the one you should go with as it is regular scenario of Run3

**Comment by chayanit** [comment]
> For the second command, it looks like there is a problem. The output is:
> `GEN,SIM,ENDJOB We have determined that this is simulation (if not, rerun cmsDriver.py with --data) with DB: Step: GEN Spec: Loading generator fragment from Configuration.Generator.GluGluTo2Jets_M_300_2000_14TeV_Exhume_cff Traceback (most recent call last): File "/cvmfs/cms-ib.cern.ch/week1/slc7_amd64_gcc900/cms/cmssw/CMSSW_11_3_X_2021-01-25-1100/bin/slc7_amd64_gcc900/cmsDriver.py", line 56, in <module> run() File "/cvmfs/cms-ib.cern.ch/week1/slc7_amd64_gcc900/cms/cmssw/CMSSW_11_3_X_2021-01-25-1100/bin/slc7_amd64_gcc900/cmsDriver.py", line 28, in run configBuilder.prepare() File "/cvmfs/cms-ib.cern.ch/week1/slc7_amd64_gcc900/cms/cmssw/CMSSW_11_3_X_2021-01-25-1100/python/Configuration/Applications/ConfigBuilder.py", line 2131, in prepare self.addStandardSequences() File "/cvmfs/cms-ib.cern.ch/week1/slc7_amd64_gcc900/cms/cmssw/CMSSW_11_3_X_2021-01-25-1100/python/Configuration/Applications/ConfigBuilder.py", line 757, in addStandardSequences getattr(self,"prepare_"+stepName)(sequence = getattr(self,stepName+"DefaultSeq")) File "/cvmfs/cms-ib.cern.ch/week1/slc7_amd64_gcc900/cms/cmssw/CMSSW_11_3_X_2021-01-25-1100/python/Configuration/Applications/ConfigBuilder.py", line 1337, in prepare_GEN raise Exception("Neither gen fragment of input files provided: this is an inconsistent GEN step configuration") Exception: Neither gen fragment of input files provided: this is an inconsistent GEN step configuration`

Not sure but have you run scram b to compile the new fragment you added?

**Comment by mundim** [comment]
Yes, I did, but will make a distclean and compile again.

**Comment by mundim** [comment]
No way. Don't I have to add this wf in some place?

**Comment by mundim** [comment]
SORRY! There was a typo in the gen fragment. It is running. Thank you very much.

**Comment by mundim** [comment]
I ran:

`runTheMatrix.py --what upgrade -l 12125.0 -t 4 --command='-n 5'`

which produced the output:

`1 1 1 1 tests passed, 0 0 0 0 failed`

So, I guess I can submit the PR, right?

**Comment by mundim** [comment]
> > > > > @slava77 looking at #32340 almost all Run-3 workflows were crashing. The problem was that the crash happens after more than 100 events.
> > > > > In `/afs/cern.ch/work/s/sdonato/public/debug_PPS/badd237c-4857-4f48-b10f-52c832f57f02_ev1126.root` I selected a single GEN-SIM-DIGI-RAW event causing the cras (taken from `root://cms-xrd-global.cern.ch//store/relval/CMSSW_11_2_0_pre10/RelValTTbar_14TeV/GEN-SIM-DIGI-RAW/112X_mcRun3_2021_realistic_v13_rsb-v1/00000/badd237c-4857-4f48-b10f-52c832f57f02.root`).
> > > > > This dataset was generated with `11634.0` (@cms-sw/pdmv-l2 please correct me if I'm wrong)
> > > > 
> > > > 
> > > > Yes, this dataset is 11634.0
> > > 
> > > 
> > > Sorry, I could not find the error messages, can you point me to them, please? Maybe I can have a more precise idea looking at them. Thanks.
> > 
> > 
> > Testing this particular wf with the new fragment, produce no errors (1 1 1 1 1 tests passed, 0 0 0 0 0 failed), but I'm not sure if the generator fragment I introduced is begin executed.
> 
> @mundim it seems I missed the PR. Can you share the link to PR? Which command line have you tried?

Hi @chayanit, the PR with the gen fragment is #32765.

**Comment by silviodonato** [comment]
The gen fragment has been merged with #32969 and #32868

**Comment by silviodonato** [comment]
I've made #33266 but the error `No "LHCInfoRcd" record found in the EventSetup.n` appears again in step-3 of `11925.0`.

**Comment by qliphy** [comment]
Should be fixed now by #33415

**Comment by smuzaffar** [comment]
@slava77 , should we close this issue now?

**Comment by slava77** [comment]
+reconstruction
