### ISSUE TITLE
[DD4Hep] Migrate to G4 units as default

### ISSUE THREAD

**Issue by ianna** [cms-sw/cmssw#32403]
As CMS has requested, DD4hep is ready to do the switch. A copy form a geometry forum discussion is beneath.

+++ Reason 1 **Performance**
Conversion between ROOT -> G4 units costs us roughly 16 divisions per volume - excluding the number of parameters per shape. 

2021 scenario has 2111632 volumes. 
2026 scenario has 13262283 volumes.

Moving to the same units would be a multiplication by 1 in the worst case. Multiplication by 1 is part of a class of simple optimisations known as arithmetic local optimisations. The compiler would optimise it.

+++ Reason 2 **Precision**
There are 13 levels of the cumulative transformations in CMS geometry description. XML -> ROOT units -> G4 units introduces bigger precision errors than XML -> G4 
because we are accumulating error every time we divide by 10 (since 10 is not power of 2).

+++ Reason 3 **Minimise our own effort**
Simulation will run fine with the G4 units as the default ones without any extra effort. We have always assumed that we'd use the G4 units when it comes to production.

**An effort is required if we want to move to the ROOT units consistently.** ProductionCuts is only one example. We never fully analysed the CMSSW code for this use case. If this move is done, an extra work will have to be done to move back to the G4 units.

It has been confirmed yesterday that migration to the G4 units is fine for Calorimeters. The other three links point to the MTD, Tracker and Forward sub detectors. All of the quoted cases would benefit by using the G4 units directly to avoid multiplications - a dozen multiplications per a DetUnit in Tracker, for example.

+++ Reason 4 **Keeping good faith with DD4hep developers**
Historically, DD4hep relied on ROOT units as the default ones. CMS has requested to switch to G4 units - our default in Simulation. They have done as we’ve asked and delivered by migrating their own code and their users code to the G4 units. It has been a huge effort for them and there was a sense of disappointment during the DD4hep developers meeting when we were not enthusiastic about them switching to the units we’ve asked.

**Comment by makortel** [comment]
assign geometry

**Comment by cvuosalo** [comment]
Issue #31979 already addresses this topic, does it not? Do we need both?

**Comment by ianna** [comment]
> Issue #31979 already addresses this topic, does it not? Do we need both?

Sorry I didn’t see it in your plan. So, why it’s not a high priority issue? It’s 10 days before CERN closes, if we do not update to the new version of DD4Hep this week, we’ll loose one month of development.

We are already concerned about performance, we have heard reports about Ecal geometry discrepancy at a the level of precision, we have thread safety and performance issues due to bringing in the evaluator in Reco. This issue is a showstopper for Run 1 legacy payload usage. All this points to the need of the migration ASAP.

What is the reason for delaying the units switch? We will be hitting other problems that we do not have unit tests for.

**Comment by ianna** [comment]
Duplicate
