### ISSUE TITLE
[DD4Hep] Legacy Run 1 payloads

### ISSUE THREAD

**Issue by ianna** [cms-sw/cmssw#32411]
The [DD4Hep G4 units as default migration](https://github.com/cms-sw/cmssw/issues/31979) is mandatory in order to use the Run 1 payloads transparently: the G4 units are assumed as a default. There are quite a few places where Run 1 XML description misses units either in the shape definition or in their transformation.

**Comment by makortel** [comment]
assign geometry

**Comment by ianna** [comment]
closed in favour of https://github.com/cms-sw/cmssw/issues/34663
