### ISSUE TITLE
Minuit logging changed in ROOT master

### ISSUE THREAD

**Issue by mrodozov** [cms-sw/cmssw#32416]
Dears,

ROOT has changed in master the way Minuit is logging errors, warnings and info:
https://github.com/root-project/root/pull/6705

which we use at least in RecoLocalCalo/HcalRecAlgos

Adjusting to the new Minuit logging API seems to be (relatively) straightforward - one has to adjust 
MnPrint:: SetLevel -> Verbose and use Info, Error and Warn instead of MN_INFO_MSG2 MN_ERROR_MSG etc 
but this change is only availble in ROOT master and not in 6-22 that we use for CMSSW master. 
I'm going to ask them to backport it (or do it myself) but we also have need changes in CMSSW  and figure something if backport is no possible :/

**Comment by mrodozov** [comment]
assign reconstruction

**Comment by davidlange6** [comment]
From a quick look, I worry that this PR is something we want to back port without some testing..  maybe we can #define something to provide a migration path?

**Comment by Dr15Jones** [comment]
@mrodozov why do we need this change so urgently?

**Comment by mrodozov** [comment]
It's blocking the update of our cmdsit ROOT/master IB, only.
