### ISSUE TITLE
[DD4Hep] Tracker Phase II numeric special parameters need to be passed to an evaluator

### ISSUE THREAD

**Issue by ianna** [cms-sw/cmssw#32414]
Addressing thread-safety and performance. Showstopper for running 2026 DD4Hep workflows. Urgent.

In order to reduce the DD4Hep exposure to RECO all "special" numeric parameters must be marked with `eval=true`. This allows passing it to an evaluator at the time of the XML parsing. Further access to the parameters from `DDFilteredView` is `get<double>`

**WARNING**: If the parameter is not marked to be evaluated, it's treated as a `string`. Access to the `string` parameters via `DDFilteredView` `get<double>` is forbidden:  currently a value `0` is returned, further restriction is being implemented to return `NaN`.

**Comment by makortel** [comment]
assign geometry

**Comment by ghugo83** [comment]
Ha I see was done here for Phase 1, following recent change in FilteredView: https://github.com/cms-sw/cmssw/pull/32388/commits/32a0c74e01bb2178334538d817e4090810f84d6f#diff-7302cd669ba77ff993549a7ab094d7feac189f27ed543dd1970d854dd78b3c05
Gonna push a PR for Phase 2 today

**Comment by ghugo83** [comment]
Can close this issue.
Addressed in https://github.com/cms-sw/cmssw/pull/32479 and https://github.com/cms-sw/cmssw/pull/32843

**Comment by cvuosalo** [comment]
+1
