### ISSUE TITLE
HIPhotonIsolation not correctly added to pat::photon

### ISSUE THREAD

**Issue by ttrk** [cms-sw/cmssw#32451]
https://github.com/cms-sw/cmssw/pull/30255 adds HIPhotonIsolation object (keyed by reco::photon) to pat::photon. However, the detailed checks show that although object is added, its association to the pat::photon is wrong.

Details here : https://indico.cern.ch/event/983567/contributions/4149449/attachments/2161558/3647183/201211_miniAOD_HIPhotonIsolation_reco_meeting.pdf

Please let us know how to proceed with this.

**Comment by makortel** [comment]
assign reconstruction, xpog

(a bit unsure of the assignment though)

**Comment by slava77** [comment]
@guitargeek 
we mentioned you in the meeting as a possible expert to take a look at the issue

**Comment by guitargeek** [comment]
Okay, good. Matt told me privately but I didn't have time to look into it yet. I'll can take a look on Sunday if that's fine? How's the urgency here?

**Comment by slava77** [comment]
@guitargeek 
Thank you.
Based on the discussion in the meeting, in the next few days would be fine (a PR by Tue/Wed? but it depends on its complexity; one can hope for a one-liner fix)

**Comment by guitargeek** [comment]
That's a good timescale! Maybe I can find an easy way to make the EGExtraInfoModifierFromValueMaps to work with non-aligned collections.

**Comment by slava77** [comment]
somehow I thought that `EGExtraInfoModifierFromValueMaps` was working already *only* for aligned collections and it's a bit surprising to see that the protections available in ValueMap to get the values for the collection it was made were not used .

**Comment by slava77** [comment]
+1

fixed in #32462 for 11_3_X and also backported to 11_2_X in #32619

**Comment by mariadalfonso** [comment]
+1
