### ISSUE TITLE
Towards CMSSW_11_2_0 - Problems with L1 trigger

### ISSUE THREAD

**Issue by silviodonato** [cms-sw/cmssw#32467]
Part of #32465

From https://hypernews.cern.ch/HyperNews/CMS/get/relval/15254/34.html

> Release: 11_2_0_PRE9_2021
In category: RECONSTRUCTION
In subcategory: FULLSIM
validation for: L1
Has Changed: From status: NOT YET DONE
             To status: FAILURE
By: MIKKO LOTTI
Comment: The targed release follows the reference release. Reference 11_2_0_pre8 was marked FAILURE by L1T since it is still under investigation but the changes might hint towards problems in the code. Since there is no change between the target and the release, the possible problems in the reference are still part of the pre9 release. Therefore the target is also marked as FAILURE

> Plots and more detail in https://its.cern.ch/jira/browse/CMSLITDPG-916
Links: None

**Comment by silviodonato** [comment]
assign l1

**Comment by silviodonato** [comment]
cc @cms-sw/pdmv-l2

**Comment by silviodonato** [comment]
cc: @cbotta

**Comment by silviodonato** [comment]
You can find more plots at slide5 https://indico.cern.ch/event/971757/contributions/4091291/attachments/2141972/3609473/Release_Validation_Report_2020_11_12.pdf.

pre7: black, pre8: blue
![image](https://user-images.githubusercontent.com/6177433/102090791-325f9d00-3e1e-11eb-87e5-886f220ddf78.png)
![image](https://user-images.githubusercontent.com/6177433/102090804-37245100-3e1e-11eb-9f60-d1b593162376.png)
![image](https://user-images.githubusercontent.com/6177433/102090816-3ab7d800-3e1e-11eb-9d1d-ba4ec07be505.png)

Might be related to https://github.com/cms-sw/cmssw/pull/31608

**Comment by silviodonato** [comment]
From an e-mail from @BenjaminRS @bundocka , I've understood these errors are going to be fixed by https://github.com/cms-sw/cmssw/pull/32455 and https://github.com/cms-sw/cmssw/pull/32365.

**Comment by silviodonato** [comment]
assign pdmv

**Comment by cecilecaillol** [comment]
Fixed in https://github.com/cms-sw/cmssw/pull/32455 and https://github.com/cms-sw/cmssw/pull/32365

**Comment by cecilecaillol** [comment]
+l1

**Comment by AdrianoDee** [comment]
+pdmv

**Comment by AdrianoDee** [comment]
please close
