### ISSUE TITLE
Towards CMSSW_11_2_0 - Differences in MET phase2

### ISSUE THREAD

**Issue by silviodonato** [cms-sw/cmssw#32466]
Part of https://github.com/cms-sw/cmssw/issues/32465

From  https://hypernews.cern.ch/HyperNews/CMS/get/relval/15255/18.html

>Release: 11_2_0_PRE9_PHASE2
In category: RECONSTRUCTION
In subcategory: FULLSIM
validation for: MET
Has Changed: From status: NOT YET DONE
             To status: IN PROGRESS
By: ROBERTO SEIDITA
Comment: 11_2_0_pre9_phase2 Campaign
Target: 11_2_0_pre9_phase2 (blue)
Reference: 11_2_0_pre8_phase2 (black)

>We observe some significant shifts, e.g. in the TTbar sample, both in no PU [11] and PU [12] samples. The origin is not yet clear, we are investigating further.

>NO-PU samples [1]: QCD_FlatPt [2], TTbar [3], Zee [4], ZMM [5]
PU samples [6]: QCD_FlatPt [7], TTbar [8], Zee [9], ZMM [10]
Links: [1]: https://tinyurl.com/y3g7rnzq
[2]: https://tinyurl.com/yyj2c5ls
[3]: https://tinyurl.com/y6a82eoo
[4]: https://tinyurl.com/yy4v5wb4
[5]: https://tinyurl.com/y5r3q65g
[6]: https://tinyurl.com/y6olqk9e
[7]: https://tinyurl.com/y6e5342m
[8]: https://tinyurl.com/y3acjsb5
[9]: https://tinyurl.com/y4m8c3y6
[10]: https://tinyurl.com/yxve8bf9
[11]: https://tinyurl.com/y45z2ghq
[12]: https://tinyurl.com/yx9p5ggh

cc: @ahinzmann @lathomas 

![image](https://user-images.githubusercontent.com/6177433/102078712-acd2f180-3e0b-11eb-8417-9d3338abd392.png)
![image](https://user-images.githubusercontent.com/6177433/102078718-b0667880-3e0b-11eb-92a8-2f0b94d76c60.png)

**Comment by silviodonato** [comment]
assign reconstruction

**Comment by silviodonato** [comment]
cc @cms-sw/pdmv-l2

**Comment by silviodonato** [comment]
Other plots with a very large difference

**PhotonEt fraction in RelValZEE_14_112X_mcRun4_realistic_v3_2026D49noPU**

https://cms-pdmv.cern.ch/relmon/1605870008___CMSSW_11_2_0_pre9_Phase2_vsCMSSW_11_2_0_pre8_Phase2/FullSimReport/RelValZEE_14_112X_mcRun4_realistic_v3_2026D49noPU/24761a4ad6.html

![image](https://user-images.githubusercontent.com/6177433/102084021-c88ec580-3e14-11eb-92b7-2f027f84e247.png)

**HFHadronEtFraction in RelValTTbar_14TeV2026D49PU200**

https://cms-pdmv.cern.ch/relmon/1605870008___CMSSW_11_2_0_pre9_Phase2_vsCMSSW_11_2_0_pre8_Phase2/FullSimReport_PU/RelValTTbar_14TeV2026D49PU200-v1_PU25ns_112X_mcRun4_realistic_v3_2026D49PU200/24761a4ad6.html

![image](https://user-images.githubusercontent.com/6177433/102084124-f6740a00-3e14-11eb-9662-e2befaf8f952.png)

**Comment by silviodonato** [comment]
It might be related to https://github.com/cms-sw/cmssw/pull/31887

**Comment by silviodonato** [comment]
As a reference, these are the plots of slimmedMETs (https://github.com/cms-sw/cmssw/issues/32466#issuecomment-744425292 refers to slimmedMETPuppis)

**PhotonEt fraction in RelValZEE_14_112X_mcRun4_realistic_v3_2026D49noPU**

![image](https://user-images.githubusercontent.com/6177433/102188826-14de1200-3eb6-11eb-99c1-3bc63368b8b3.png)


https://cms-pdmv.cern.ch/relmon/1605870008___CMSSW_11_2_0_pre9_Phase2_vsCMSSW_11_2_0_pre8_Phase2/FullSimReport/RelValZEE_14_112X_mcRun4_realistic_v3_2026D49noPU/1f878051f4.html

**HFHadronEtFraction in RelValTTbar_14TeV2026D49PU200**


![image](https://user-images.githubusercontent.com/6177433/102188881-245d5b00-3eb6-11eb-87c9-54d35fdb3ea0.png)

https://cms-pdmv.cern.ch/relmon/1605870008___CMSSW_11_2_0_pre9_Phase2_vsCMSSW_11_2_0_pre8_Phase2/FullSimReport_PU/RelValTTbar_14TeV2026D49PU200-v1_PU25ns_112X_mcRun4_realistic_v3_2026D49PU200/1f878051f4.html

**Comment by silviodonato** [comment]
and these are the plots of slimmedMETs to be compared with slimmedMETsPuppi (https://github.com/cms-sw/cmssw/issues/32466#issue-766333179)
TTbar noPU

https://cms-pdmv.cern.ch/relmon/1605870008___CMSSW_11_2_0_pre9_Phase2_vsCMSSW_11_2_0_pre8_Phase2/FullSimReport/RelValTTbar_14TeV_112X_mcRun4_realistic_v3_2026D49noPU/1f878051f4.html

![image](https://user-images.githubusercontent.com/6177433/102190089-d6e1ed80-3eb7-11eb-805a-42210a84d378.png)

TTbar PU200

https://cms-pdmv.cern.ch/relmon/1605870008___CMSSW_11_2_0_pre9_Phase2_vsCMSSW_11_2_0_pre8_Phase2/FullSimReport_PU/RelValTTbar_14TeV2026D49PU200-v1_PU25ns_112X_mcRun4_realistic_v3_2026D49PU200/1f878051f4.html

![image](https://user-images.githubusercontent.com/6177433/102190141-ebbe8100-3eb7-11eb-8ec2-bb647b9ac5de.png)

**Comment by lathomas** [comment]
Hello, 
Indeed we do expect changes in PF fractions entering PUPPIMET given the update of the PUPPI tune in https://github.com/cms-sw/cmssw/pull/31887
The fact that the MET resolution doesn't change in TTbar  is reassuring
![image](https://user-images.githubusercontent.com/4995867/102197993-23cac180-3ec2-11eb-867b-8e035bb82574.png)
@ahinzmann Do you agree?

**Comment by lathomas** [comment]
Also the fact that the PUPPIMET distribution in itself doesn't change too much is another indication that things are not getting crazy.
ttbar
![image](https://user-images.githubusercontent.com/4995867/102199744-4231bc80-3ec4-11eb-84ab-8d5be66449c2.png)

ZMuMu
![image](https://user-images.githubusercontent.com/4995867/102199794-51b10580-3ec4-11eb-8c82-c33c1974cceb.png)

**Comment by silviodonato** [comment]
assign pdmv

**Comment by silviodonato** [comment]
As confirmed at the PPD General meeting https://indico.cern.ch/event/984876/ and by @lathomas we can consider this difference as "change expected". Closing the issue
