### ISSUE TITLE
LumiProducer blocks concurrent lumi processing

### ISSUE THREAD

**Issue by jpata** [cms-sw/cmssw#32518]
LumiProducer seems to have several issues:
1) it blocks concurrent lumi processing introduced in 11_3_X: https://github.com/cms-sw/cmssw/issues/25090#issuecomment-745721320
2) it requires updates https://github.com/cms-sw/cmssw/issues/28608
3) it seems it is not really used in production at least from 2018: https://github.com/cms-sw/cmssw/issues/25090#issuecomment-746418195

cc LUMI POG conveners @gkrintir and Christoph Schwick (I couldn't find the github now), can you clarify what is the status of this module? Is it being used (or foreseen to be used in Run 3) for physics? Given the points above, especially (1), it may be a prudent time to remove this from the sequences, if not used. Otherwise, resource will have to be invested to make sure this module is updated.

**Comment by jpata** [comment]
assign reconstruction

**Comment by gkrintir** [comment]
thanks @jpata for reporting

indeed it can be removed from the sequences @capalmer85 please verify

many thx all

**Comment by plujan** [comment]
Yes, I can confirm that this was not used for Run 2 and we have no plans to use it for Run 3, so feel free to take whatever actions are necessary.

**Comment by slava77** [comment]
+reconstruction

removed in #33024
