### ISSUE TITLE
Possible copy/paste error in calculation of diagonal elements in metsig::METSignificance::getCovariance?

### ISSUE THREAD

**Issue by dpiparo** [cms-sw/cmssw#32546]
I was looking for cpu performance optimisation opportunities and I stumbled in 
https://github.com/cms-sw/cmssw/blob/ba6e8604a35283e39e89bc031766843d0afc3240/RecoMET/METAlgorithms/src/METSignificance.cc#L169
the 2 diagonal elements of the matrix are identical and calculated twice. Can this be a copy/paste mistake?

This is not related to the above question but it could be that quite a few multiplications and divisions could be removed in the interest of a minimal performance improvement.

**Comment by makortel** [comment]
assign reconstruction

**Comment by perrotta** [comment]
Adding the JetMET conveners, because a reco contact for MET has not yet appointed:
@kirschen @lathomas

**Comment by lathomas** [comment]
@danbarto  can you take look?

**Comment by dpiparo** [comment]
Hi all, perhaps this got a bit stuck during the holiday?

**Comment by danbarto** [comment]
Hi, sorry I missed being mentioned in this thread. I think having the same calculation twice was there historically and hasn't been updated. I have no objections to calculating the diagonal elements just once and adding the same value to cov_xx and cov_yy.

**Comment by perrotta** [comment]
> the diagonal elements just once and adding the same value to cov_xx and cov_yy

Thank you @danbarto : I implemented what you suggest in #32693
While doing so, I also noticed that there are several computations and assignments in the same code which were uselessly performed when the jet pt is below threshold: in that PR those calculations are only made conditionally.

**Comment by perrotta** [comment]
+1
-  Formally the issue could have been considered solved when @danbarto [confirmed](https://github.com/cms-sw/cmssw/issues/32546#issuecomment-760219905) that the calculation of those diagonal elements was indeed correct
- Furthermore, with #32693 the suggested code optimization, and a few more, were also integrated
