### ISSUE TITLE
SiPixelTemplateStore2D modernization

### ISSUE THREAD

**Issue by jpata** [cms-sw/cmssw#32567]
In https://github.com/cms-sw/cmssw/pull/32494, SiPixelTemplate was modernized to use C++ std::array/std::vector for improved memory management. The same should be done for SiPixelTemplate2D, per https://github.com/cms-sw/cmssw/pull/32494/files/3d61197863ff75dd0b1e0db4ac4ce4e361087553#r545172147.

**Comment by jpata** [comment]
assign reconstruction

**Comment by jpata** [comment]
@toruonu expressed interest in this, cc-ig

**Comment by tvami** [comment]
@jpata I think this was resolved in https://github.com/cms-sw/cmssw/pull/33105 so the issue can be closed, right?

**Comment by jpata** [comment]
+reconstruction

yes, thanks for the reminder.
