### ISSUE TITLE
update 2021 relval matrix with existing input samples

### ISSUE THREAD

**Issue by slava77** [cms-sw/cmssw#32592]
For appropriate coverage of Run-3 developments it is important to have a reference set of workflows with existing GEN-SIM inputs.

This is somewhat related to  #32543, but expands beyond it to make a more complete set.

As a reference I propose to use the 2018 set (with an update to 14TeV).
The following are already available in the default setup:
| workflow | index for 2021 |
| --- | --- |
| RelValTTbar_14 | 34.0 |
| RelValMinBias_14 | 40.0 |
| RelValZEE_14 | 46.0 |
| RelValZMM_14 | 50.0 |

The following now have a GEN-SIM in 11_2_0:
| workflow | index for 2021 |
| --- | --- |
| RelValQCD_FlatPt_15_3000HS_14 | 43.0 |

The following are still missing GEN-SIM
| workflow | index for 2021 |
| --- | --- |
| RelValSingleElectronPt10 | 1.0 |
| RelValSingleElectronPt35 | 2.0 |
| RelValSingleElectronPt1000 | 3.0 |
| RelValSingleGammaPt10 | 4.0 |
| RelValSingleGammaPt35 | 5.0 |
| RelValSingleMuPt1 | 6.0 |
| RelValSingleMuPt10 | 7.0 |
| RelValSingleMuPt100 | 8.0 |
| RelValSingleMuPt1000 | 9.0 |
| RelValQCD_Pt_3000_3500_14 | 30.0 |
| RelValQCD_Pt_600_800_14 | 53.0 |

Once GEN-SIM is available, an update in https://github.com/cms-sw/cmssw/blob/master/Configuration/PyReleaseValidation/python/relval_2017.py#L57 should follow to make these workflows available for the IB infrastructure tests.

**Comment by slava77** [comment]
assign pdmv

**Comment by chayanit** [comment]
Hello @slava77 , I'm trying to understand your request. Do you need to have GEN-SIM produced for the samples you listed? Do I need to update any part of the code?

**Comment by silviodonato** [comment]
@chayanit I think @slava77 meant to both produce the missing GEN-SIM and then add the corresponding relvals in https://github.com/cms-sw/cmssw/blob/master/Configuration/PyReleaseValidation/python/relval_2017.py#L16-L42

For example, we have workflows for SingleMu1000 in 2017 (10009.0) and in 2018 (10809.0), but we don't have the corresponding workflows for 2021. We should add the missing workflow.

**Comment by slava77** [comment]
> Hello @slava77 , I'm trying to understand your request. Do you need to have GEN-SIM produced for the samples you listed? Do I need to update any part of the code?

@silviodonato responded for me above.
Thank you.

**Comment by chayanit** [comment]
Hello @slava77, @silviodonato I have submitted all missing GEN-SIM you listed above and the one mentioned in #32543. To add the corresponding relvals in https://github.com/cms-sw/cmssw/blob/master/Configuration/PyReleaseValidation/python/relval_2017.py#L16-L42, you mean in 11_2_X? I have never done the backport yet. Could someone show me how? Thanks!

**Comment by slava77** [comment]
> Hello @slava77, @silviodonato I have submitted all missing GEN-SIM you listed above and the one mentioned in #32543. 

Thank you.
Which release was used to make these?

> To add the corresponding relvals in https://github.com/cms-sw/cmssw/blob/master/Configuration/PyReleaseValidation/python/relval_2017.py#L16-L42, you mean in 11_2_X? I have never done the backport yet. Could someone show me how? Thanks!

I meant the master branch; I did not really imply a backport.

**Comment by chayanit** [comment]
> > Hello @slava77, @silviodonato I have submitted all missing GEN-SIM you listed above and the one mentioned in #32543.
> 
> Thank you.
> Which release was used to make these?

I produced them with 11_2_0_pre8 to be compatible with the string I put here https://github.com/cms-sw/cmssw/blob/master/Configuration/PyReleaseValidation/python/relval_steps.py#L3227 

> 
> > To add the corresponding relvals in https://github.com/cms-sw/cmssw/blob/master/Configuration/PyReleaseValidation/python/relval_2017.py#L16-L42, you mean in 11_2_X? I have never done the backport yet. Could someone show me how? Thanks!
> 
> I meant the master branch; I did not really imply a backport.

Ok then I will add to master and trigger the test as soon as GENSIM becomes available.

**Comment by slava77** [comment]
> I produced them with 11_2_0_pre8 to be compatible with the string I put here https://github.com/cms-sw/cmssw/blob/master/Configuration/PyReleaseValidation/python/relval_steps.py#L3227

ah, good.
So, this indeed opens a more direct possibility of making a backport to 11_2_X.
I guess we can give it a try after the 11_3_X variant is in and working happily.

**Comment by silviodonato** [comment]
It looks like #32633 went smoothly, without errors.
A backport to 11_2_X is not strictly necessary, but it might be useful for the MWGR.

**Comment by srimanob** [comment]
Is there action needed for this issue, or should we close? Thanks.

**Comment by AdrianoDee** [comment]
+pdmv

**Comment by AdrianoDee** [comment]
@cmsbuild, please close
