### ISSUE TITLE
CMSSW_11_2_0 dqm:@rerecoCommon requires sim information to run

### ISSUE THREAD

**Issue by davidlange6** [cms-sw/cmssw#32634]
Running a reco job 
cmsDriver.py step3  --conditions auto:phase1_2021_realistic -n -1 --era Run3 --eventcontent AODSIM,MINIAODSIM,DQM --runUnscheduled  -s RAW2DIGI,L1Reco,RECO,RECOSIM,EI,PAT,DQM:@rerecoCommon+@miniAODDQM --datatier AODSIM,MINIAODSIM,DQMIO  --geometry DB:Extended --
nThreads 8 --filein file:tt_digi_DIGI_DATAMIX_L1_DIGI2RAW_HLT.root  --fileout recostep.root --suffix "-j JobReport5.xml " --customise Validation/Performance/TimeMemorySummary.customiseWithTimeMemorySummary

on a RAWSIM input yields

An exception of category 'ProductNotFound' occurred while
   [0] Processing  Event run: 1 lumi: 1 event: 11 stream: 0
   [1] Running path 'dqmoffline_14_step'
   [2] Prefetching for module L1TMuonEndCapTrackProducer/'valEmtfStage2Digis'
   [3] Prefetching for module GEMPadDigiClusterProducer/'simMuonGEMPadDigiClusters'
   [4] Calling method for module GEMPadDigiProducer/'simMuonGEMPadDigis'
Exception Message:
Principal::getByToken: Found zero products matching all criteria
Looking for type: MuonDigiCollection<GEMDetId,GEMDigi>
Looking for module label: simMuonGEMDigis
Looking for productInstanceName: 

my understanding is that DQM should not need any sim information (let alone sim information that is not in RAWSIM data tier)

**Comment by makortel** [comment]
assign dqm

**Comment by jfernan2** [comment]
@seungjin-yang @quark2 @hyunyong  as GEM DQM contacts, can you please have a look and provide a fix?

**Comment by seungjin-yang** [comment]
@jshlee

**Comment by seungjin-yang** [comment]
Firstly, look for this file. [L1Trigger/L1TMuonEndCap/python/simEmtfDigis_cfi.py](https://github.com/cms-sw/cmssw/blob/CMSSW_11_2_0/L1Trigger/L1TMuonEndCap/python/simEmtfDigis_cfi.py#L128-L138)
We need to replace `GEMInput` of `simEmtfDigisData` (L1TMuonEndCapTrackProducer) with the real data versioned one.

But I can’t find `GEMPadDigiClusterProducer` for real data. [L1Trigger/L1TGEM/python/simMuonGEMPadDigiClusters_cfi.py](https://github.com/cms-sw/cmssw/blob/CMSSW_11_2_0/L1Trigger/L1TGEM/python/simMuonGEMPadDigiClusters_cfi.py)

**Comment by jshlee** [comment]
@dildick can you look into this.

**Comment by dildick** [comment]
yes, I'm working on a fix

**Comment by dildick** [comment]
@seungjin-yang I'm afraid there is no GEMPadDigiClusterProducer yet for real data; the development the unpacker is still ongoing. What you can do is 1) unpack the GEMDigis (add `muonGEMDigis`) 2) add the trigger-primitives (`simMuonGEMPadDigis`, `simMuonGEMPadDigiClusters`), and add 3) the customization

```
from Configuration.Eras.Modifier_run3_GEM_cff import run3_GEM
    run3_GEM.toModify(process.simMuonGEMPadDigis,
        InputCollection         = 'muonGEMDigis',
    )
```

**Comment by dildick** [comment]
So either implement it here https://github.com/cms-sw/cmssw/blob/master/Configuration/StandardSequences/python/RawToDigi_cff.py, or we can define a sequence in https://github.com/cms-sw/cmssw/tree/master/EventFilter/GEMRawToDigi/python.

**Comment by seungjin-yang** [comment]
@dildick Thank you for your guidance. I made a simple patch. Can you review it? https://github.com/seungjin-yang/cmssw/commit/ca70c5b0d6e3c539ab7d7832ca40c8911e1b1e55

**Comment by seungjin-yang** [comment]
@davidlange6  Can you tell me which matrix or file I should use for testing?

**Comment by dildick** [comment]
@seungjin-yang it looks ok

**Comment by seungjin-yang** [comment]
@ davidlange6, @jfernan2 Can you give me workflow number or a test input file for testing patch https://github.com/seungjin-yang/cmssw/commit/ca70c5b0d6e3c539ab7d7832ca40c8911e1b1e55 ?

**Comment by davidlange6** [comment]
I believe the easiest thing is take a random run3 mc workflow and adjust the step 2 output and step3 config as suggested in the first message of this issue.

**Comment by seungjin-yang** [comment]
Thanks!

**Comment by dildick** [comment]
@seungjin-yang I'll submit a (modified) PR.

**Comment by dildick** [comment]
@davidlange6 This issue can be closed.

**Comment by jfernan2** [comment]
+1
For the records
