### ISSUE TITLE
GEN-SIM datasets for GPU workflows

### ISSUE THREAD

**Issue by silviodonato** [cms-sw/cmssw#32654]
As discussed at the last ORP meeting, we would like to use already-existing GEN-SIM files in order to speed up the GPU tests.
I tried to run `runTheMatrix.py -w gpu --useInput=all --maxStep=2`. 
Everything is ok for workflows based on data (`136.885502`, `136.885512`, `136.885522`, `136.888502`, `136.888512`, `136.888522`)

Input files are missing for MC wf: `10824.502`, `10824.512`, `10824.522`, `10842.502`, `11634.502`, `11634.512`, `11634.522`, `11650.502`
corresponding to

```
/RelValTTbar_13/CMSSW_11_2_0_pre8-112X_upgrade2018_realistic_v4-v1/GEN-SIM
/RelValTTbar_13/CMSSW_11_2_0_pre8-112X_upgrade2018_realistic_v4-v1/GEN-SIM
/RelValTTbar_13/CMSSW_11_2_0_pre8-112X_upgrade2018_realistic_v4-v1/GEN-SIM
/RelValZMM_13/CMSSW_11_2_0_pre8-112X_upgrade2018_realistic_v4-v1/GEN-SIM
/RelValTTbar_14TeV/CMSSW_11_2_0_pre8-112X_mcRun3_2021_realistic_v10-v1/GEN-SIM
/RelValTTbar_14TeV/CMSSW_11_2_0_pre8-112X_mcRun3_2021_realistic_v10-v1/GEN-SIM
/RelValTTbar_14TeV/CMSSW_11_2_0_pre8-112X_mcRun3_2021_realistic_v10-v1/GEN-SIM
/RelValZMM_14/CMSSW_11_2_0_pre8-112X_mcRun3_2021_realistic_v10-v1/GEN-SIM
```

@cms-sw/pdmv-l2 could you start the production of these datasets?

cc @cms-sw/heterogeneous-l2

**Comment by silviodonato** [comment]
assign pdmv

**Comment by fwyzard** [comment]
Shouldn't we use the relvals from `CMSSW_11_3_0_pre1` instead of thos from `CMSSW_11_2_0_pre8` ?

**Comment by chayanit** [comment]
Hello @silviodonato , this is a bit odd as I have produced all of them. https://cmsweb.cern.ch/das/request?view=list&limit=50&instance=prod%2Fglobal&input=%2FRelVal*%2FCMSSW_11_2_0_pre8-112X_upgrade2018_realistic_v4-v1%2FGEN-SIM They should exist. 

@fwyzard , this is because the string on master is still based on CMSSW_11_2_0_pre8 https://github.com/cms-sw/cmssw/blob/master/Configuration/PyReleaseValidation/python/relval_steps.py#L3224

**Comment by fwyzard** [comment]
> @fwyzard , this is because the string on master is still based on CMSSW_11_2_0_pre8 https://github.com/cms-sw/cmssw/blob/master/Configuration/PyReleaseValidation/python/relval_steps.py#L3224

I see.

Should we update it ?

**Comment by chayanit** [comment]
> > @fwyzard , this is because the string on master is still based on CMSSW_11_2_0_pre8 https://github.com/cms-sw/cmssw/blob/master/Configuration/PyReleaseValidation/python/relval_steps.py#L3224
> 
> I see.
> 
> Should we update it ?

We will update it but not on the first pre-release. We normally do when it comes to almost the closed cycle. Is that ok?

**Comment by davidlange6** [comment]
What’s the harm in updating it regularly as new gem-sim becomes available (thus finding generation or simulation bugs faster)

**Comment by chayanit** [comment]
> What’s the harm in updating it regularly as new gem-sim becomes available (thus finding generation or simulation bugs faster)
> […](#)

Because we don't produce all samples for IB test regularly. We only produce part of them.

**Comment by silviodonato** [comment]
@chayanit , you are right the samples are there. Indeed there are no errors using `runTheMatrix.py -w gpu --useInput=all --maxStep=2 --ibeos`
