### ISSUE TITLE
[DD4hep] [For discussion] Consider removing namespace from volume names

### ISSUE THREAD

**Issue by cvuosalo** [cms-sw/cmssw#32740]
Currently, with DD4hep the Phase 2 tracker requires namespaces to distinguish between similar volume names. However, namespaces make the volume names much longer and reduce performance.
The plan is to modify the Phase 2 tracker XML files to change volume names so they are unique without needing namespaces appended. Once this change is completed, work can commence on removing namespaces from all volume names.

**Comment by cvuosalo** [comment]
assign geometry

**Comment by cvuosalo** [comment]
PPS code may also be using repeated names that need to be distinguished by namespace.

**Comment by cvuosalo** [comment]
Removing the namespace from names would be a major project. Many parts of the code may depend on using the namespace to uniquely identify names, so all those cases would need to be understood and changed.

**Comment by ianna** [comment]
IMHO we should keep them.

**Comment by civanch** [comment]
From my point of view, long name (with or without namespace) is convenient for understanding and for memory but definitely will slowdown any DD code. At the same time, it is possible to have a namespace consists of 1 (well enough) or at maximum 2 characters.

**Comment by ianna** [comment]
> but definitely will slowdown any DD code

How long a string? I'd like to see a profiling of that - how a maximum 20 char string performing against 10 char string - I don't think we'd notice any difference.

**Comment by cvuosalo** [comment]
Namespaces are definitely needed to ensure unique identifiers. From my tests, I would say DD4hep processing of the geometry is reasonably fast, and the performance cost of long identifiers with namespaces is acceptable. If anyone has concerns about the cost of long identifiers, they can open a new issue about it, but I will close this issue for now.

**Comment by cvuosalo** [comment]
-1
