### ISSUE TITLE
Memory usage of reco::parser::cutParser

### ISSUE THREAD

**Issue by makortel** [cms-sw/cmssw#32747]
(from https://mattermost.web.cern.ch/cms-o-and-c/pl/nkx5fjhy57fbdx4cif5junsquw)
A memory profile by @dpiparo of a FastSim job (IgProf `MEM_LIVE` at event 61 of 64) https://dpiparo.web.cern.ch/dpiparo/cgi-bin/igprof-navigator/SUS-RunIIAutumn18FSPremix-00001_evt_n61_memlive.mp/164 shows 92 MB memory being used by `reco::parser::cutParser`. ~~, and by quick look this memory usage seems to replicate to each EDM stream.~~

In that job the top uses of `reco::parser::cutParser` are
![image](https://user-images.githubusercontent.com/33993/105868683-0ce8b600-5fbc-11eb-9e0f-7bc1518e3a91.png)

**Comment by makortel** [comment]
assign reconstruction

**Comment by slava77** [comment]
> and by quick look this memory usage seems to replicate to each EDM stream.

please elaborate on this

**Comment by makortel** [comment]
> > and by quick look this memory usage seems to replicate to each EDM stream.
> 
> please elaborate on this

Thanks, my initial look was indeed too quick (apologies). Following the `boost::spririt` links lead me to `TClass::GetMethodWithPrototype()`
https://dpiparo.web.cern.ch/dpiparo/cgi-bin/igprof-navigator/SUS-RunIIAutumn18FSPremix-00001_evt_n61_memlive.mp/139
which likely is a global, i.e. the memory cost gets amortized with streams/threads. @dpiparo Is it nevertheless useful to leave this issue open?

**Comment by slava77** [comment]
I'm tempted to do a "-1" as "will not fix"
We have returned back to this a few times in the last 6 years or so.

**Comment by jpata** [comment]
-reconstruction
- the mem usage is ~60-70MB per job
- as I understand, there is no concrete plan to address this in the near future

[CMSSW_12_4_0_pre3/35234.21/step3/mem_live.99/188
](http://cms-reco-profiling.web.cern.ch/cms-reco-profiling/cgi-bin/igprof-navigator/releases/CMSSW_12_4_0_pre3/35234.21/step3/mem_live.99/188)
<img width="943" alt="Screenshot 2022-05-17 at 11 32 46" src="https://user-images.githubusercontent.com/69717/168767395-8800806c-321b-4469-8396-4cae5b7a7210.png">

http://cms-reco-profiling.web.cern.ch/cms-reco-profiling/cgi-bin/igprof-navigator/releases/CMSSW_12_4_0_pre3/11834.21/step3/mem_live.399/181
<img width="812" alt="Screenshot 2022-05-17 at 11 32 50" src="https://user-images.githubusercontent.com/69717/168767423-75713660-5bc8-4565-a2bb-531c900ad6bf.png">
