### ISSUE TITLE
Two build warnings in CLANG DataFormats/Math/test/CholeskyInvert_t.cpp

### ISSUE THREAD

**Issue by mrodozov** [cms-sw/cmssw#32746]
In the Clang IB we have two warnings due to 

`  /data/cmsbld/jenkins/workspace/build-any-ib/w/tmp/BUILDROOT/cff53344cac83c1abd88bb561d95fc5c/opt/cmssw/slc7_amd64_gcc900/cms/cmssw/CMSSW_11_3_CLANG_X_2021-01-25-2300/src/DataFormats/Math/test/CholeskyInvert_t.cpp:48:6: warning: loop not vectorized: the optimizer was unable to perform the requested transformation; the transformation might be disabled or specified as part of an unsupported transformation ordering [-Wpass-failed=transform-warning]`

which says clang unable to vectorize a loop 
probably around the pragmas in the same file 
https://github.com/cms-sw/cmssw/blob/master/DataFormats/Math/test/CholeskyInvert_t.cpp#L97

Full log is in:
https://cmssdt.cern.ch/SDT/cgi-bin/buildlogs/slc7_amd64_gcc900/CMSSW_11_3_CLANG_X_2021-01-25-2300/DataFormats/Math

One hint is there is a option to be enabled in our llvm build to enable clang to vectorize loops (have not tried yet if the problem is in the llvm external).

**Comment by makortel** [comment]
assign reconstruction

**Comment by makortel** [comment]
I see @smuzaffar silenced the warning in https://github.com/cms-sw/cmssw/pull/29790 for LLVM 9. Was it the (already distant) upgrade to LLVM 10 that made the warning to reappear?

**Comment by mrodozov** [comment]
I was reading this which
https://lists.llvm.org/pipermail/llvm-dev/2016-March/096291.html
is old, but it says
"If a loop contains a function the loop cannot be vectorized unless the function is inlined"
which in our case is indeed inlined.
https://github.com/cms-sw/cmssw/blob/master/DataFormats/Math/interface/choleskyInversion.h#L340
If I remove line 
https://github.com/cms-sw/cmssw/blob/master/DataFormats/Math/test/CholeskyInvert_t.cpp#L103
the warning is gone. If I change the function with any of this:
https://llvm.org/docs/Vectorizers.html#vectorization-of-function-calls
say creating an array;
`int * fff = new int[1024];`
and change the loop to this:
```
for (unsigned int i = 0; i < 1024; ++i) {
       fff[i] = pow(i, 2);
}
```
compiles without warning. The problem is with the cholesky function not being able to get vectorized

**Comment by slava77** [comment]
@VinInn 
it looks like you are the author of the test.
please take a look.
Thank you.

**Comment by mrodozov** [comment]
@VinInn would you suggest how to proceed with this, please :) A kind reminder

**Comment by VinInn** [comment]
the doc is this one https://llvm.org/docs/Vectorizers.html
Most probably we can just remove the pragma.
More in general: this type of info in tests is something useful to verify "regression".
They will appear as warning (in gcc as well). If we cannot manage we have just to silence them.
