### ISSUE TITLE
[DD4hep] [For discussion] Consider removing copy numbers from volume names

### ISSUE THREAD

**Issue by cvuosalo** [cms-sw/cmssw#32757]
With DD4hep, the copy number is appended to the volume name. This appending is probably done by ROOT inside of DD4hep. Presently, ECal code assumes the copy number is part of the volume name.

Shorter volume names would probably improve performance. It should be considered whether CMSSW code should be changed to no longer require the copy number in the volume name. Then, DD4hep could be changed to strip off the copy number from the volume name. The consequences of such a change would need to be evaluated. There might be a performance cost of such stripping.

This issue is open for consideration and discussion, and no course of action has been decided yet.

**Comment by cvuosalo** [comment]
assign geometry

**Comment by cvuosalo** [comment]
This change would seem to be high-risk and low-reward. Changing the code to not depend on copy numbers in the volume names could introduce bugs, while the performance improvement from the slightly shorter names would probably be marginal.

**Comment by ianna** [comment]
> This change would seem to be high-risk and low-reward. Changing the code to not depend on copy numbers in the volume names could introduce bugs, while the performance improvement from the slightly shorter names would probably be marginal.

I agree.

**Comment by cvuosalo** [comment]
I am closing this issue. It does not seem promising -- too much risk, too much effort, too little reward. If there is any future interest in this issue for Phase 2, this issue could re-opened.

**Comment by cvuosalo** [comment]
-1
