### ISSUE TITLE
large memory increase/use in TF session and inference in TICL ID as of 11_3_0_pre2

### ISSUE THREAD

**Issue by slava77** [cms-sw/cmssw#32756]
after merging of https://github.com/cms-data/RecoHGCal-TICL/pull/2 we see a large increase in RSS use by TICL:
- about 306 MiB in TF session (240 MiB more vs pre1)
    - https://jiwoong.web.cern.ch/jiwoong/cgi-bin/igprof-navigator/CMSSW_11_3_0_pre1/igprof_new_step3/ig.1/235 vs https://jiwoong.web.cern.ch/jiwoong/cgi-bin/igprof-navigator/CMSSW_11_3_0_pre2/igprof_new_step3/ig.1/78
- about 168 MiB in TF inference calls (133 MiB more vs pre1)
    - https://jiwoong.web.cern.ch/jiwoong/cgi-bin/igprof-navigator/CMSSW_11_3_0_pre1/igprof_new_step3/ig.50/393 vs https://jiwoong.web.cern.ch/jiwoong/cgi-bin/igprof-navigator/CMSSW_11_3_0_pre2/igprof_new_step3/ig.50/133

Apparently in all cases the same model is used in multiple instances of `TrackstersProducer`

A solution should include a reuse of the same model instance/session across multiple use cases. See e.g. https://github.com/cms-sw/cmssw/pull/32128/files#diff-a78a6eef2fe5dce6b99c68bf12a7fdc1a4d69634092df73559b4e97543cd4743R28 where the model graph is delivered as an ES product.

- @rovere @felicepantaleo please follow up on this issue 
- @riga @mialiu149 you are tagged in case of follow-up comments/questions

**Comment by slava77** [comment]
assign reconstruction,upgrade

**Comment by slava77** [comment]
@rovere @felicepantaleo 

please clarify on the status of resolving this problem.
Thank you.

**Comment by slava77** [comment]
> @rovere @felicepantaleo
> 
> please clarify on the status of resolving this problem.
> Thank you.

there is a problem running relvals with pileup, as mentioned today in the release planning meeting. Resolution of this issue should help significantly to reduce the memory pressure.

@chayanit please post (a link to) some details on the more recent problem in phase-2.
Thank you.

**Comment by chayanit** [comment]
S

> > @rovere @felicepantaleo
> > please clarify on the status of resolving this problem.
> > Thank you.
> 
> there is a problem running relvals with pileup, as mentioned today in the release planning meeting. Resolution of this issue should help significantly to reduce the memory pressure.
> 
> @chayanit please post (a link to) some details on the more recent problem in phase-2.
> Thank you.

Sorry @slava77 for some delayed response. I have created issue here #33004

**Comment by jpata** [comment]
Between 11_3_0_pre1 and 11_3_0_pre2, I track peak RSS going from 4282 -> 4936 = 654 MB of memory increase in [step3](https://github.com/jpata/cms-reco-profiling/blob/main/results/summary.md) for a single threaded workflow.

Comparing the igprof for memory for [pre1](https://jpata.web.cern.ch/jpata/cgi-bin/igprof-navigator/releases/11_3_0_pre1/23434.21/step3/mem/cumulative) and [pre2](https://jpata.web.cern.ch/jpata/cgi-bin/igprof-navigator/releases/11_3_0_pre2/23434.21/step3/mem/cumulative), the overall MEM_LIVE counter goes from 565 MB to 939 MB: 
- Module initialization (doPreallocate) went up from [116 MB](https://jpata.web.cern.ch/jpata/cgi-bin/igprof-navigator/releases/11_3_0_pre1/23434.21/step3/mem/64) -> [354 MB](https://jpata.web.cern.ch/jpata/cgi-bin/igprof-navigator/releases/11_3_0_pre2/23434.21/step3/mem/23) = 238 MB (which can all be associated with TracksterProducer and TrackstersMergeProducer as far as I can tell).
- Event processing (doEvent) went up from [35 MB](https://jpata.web.cern.ch/jpata/cgi-bin/igprof-navigator/releases/11_3_0_pre1/23434.21/step3/mem/236) -> [168 MB](https://jpata.web.cern.ch/jpata/cgi-bin/igprof-navigator/releases/11_3_0_pre2/23434.21/step3/mem/62) = 133 MB (as far as I can tell, again all is TrackstersProducer and TrackstersMergeProducer).

At least what we can track with igprof in step3, in pre1->pre2, all seems to be from initialization and running of TrackstersProducer and TrackstersMergeProducer.

**Comment by jpata** [comment]
Just in case it's helpful for the production and HGCAL teams, I benchmarked 23434.21, 100 events with 8 threads in 11_3_0_pre1 with and without the suspect PR https://github.com/cms-data/RecoHGCal-TICL/pull/2.

11_3_0_pre1 baseline:
```
Max VSIZ 24880.8 on evt 94 ; max RSS 13136.7 on evt 70
Time av 78.7106 s/evt   max 127.115 s on evt 8
```

11_3_0_pre1 + https://github.com/cms-data/RecoHGCal-TICL/pull/2:
```
Max VSIZ 28797.3 on evt 93 ; max RSS 16019.8 on evt 74
Time av 80.1384 s/evt   max 133.136 s on evt 8
```

So we can clearly identify an increase of 13.1GB -> 16GB with the new TICL ML model. It is not for reco to comment (AFAIK) if this is a must-fix for production, nor if this memory increase is justified by physics, but at a minimum, we could suggest the HGCAL team to implement sharing the TF model across threads to improve memory efficiency.

**Comment by chayanit** [comment]
This will be a problem in production. We are not allowed to run more than 15GB for 8 threads. 

 Chayanit from PdmVV

**Comment by jpata** [comment]
@slava77 @cms-sw/operations-l2 @rovere et al, what do you think is the best course of action? It's about a week before 11_3_0 closes. As far as I see:
- either this PR can be reverted
- the threading efficiency improvements be implemented to bring the phase2 workflow below 15GB

**Comment by qliphy** [comment]
@jpata As discussed at yesterday's ORP, the 11_3 release [schedule](https://twiki.cern.ch/twiki/bin/view/CMS/CMSSW_11_3_0) has changed, and the last open pre-release is by April 13.

@chayanit  As production has started with 11_3_0_pre5, do you have computing performance at hand?

**Comment by chayanit** [comment]
We haven't started the relval production in 11_3_0_pre5 yet.

**Comment by silviodonato** [comment]
urgent

many thanks @jpata for https://github.com/cms-sw/cmssw/issues/32756#issuecomment-805622081

**Comment by srimanob** [comment]
Do I understand that this issue can be close now, right? Thanks @jpata @slava77

**Comment by jpata** [comment]
The memory was reduced in cms-data/RecoHGCal-TICL#3, but perhaps we need a confirmation from @chayanit if it's solved for PPD production (once the release is available).

**Comment by chayanit** [comment]
As far as I concerned, the memory doesn't increase or reduce in the latest release pre5.

**Comment by jpata** [comment]
@chayanit it's only available in pre6:

https://github.com/cms-sw/cmssw/releases/tag/CMSSW_11_3_0_pre6
cms-sw/cmsdist#6769 from @cms-sw: Update tag for RecoHGCal-TICL to V00-02-01

**Comment by chayanit** [comment]
OK we noticed the reduction of memory in pre6 indeed. Thanks everyone!
https://cmsweb.cern.ch/couchdb/workloadsummary/_design/WorkloadSummary/_show/histogramByWorkflow/pdmvserv_RVCMSSW_11_3_0_pre6TTbar_14TeV__2026D76PU200_210419_200038_9806

**Comment by jpata** [comment]
+reconstruction

Should this be closed (unsure about the procedure)?

**Comment by srimanob** [comment]
+Upgrade

No issue has been reported so far.
