### ISSUE TITLE
Grouping and/or documenting offset used in relvals upgrade workflows

### ISSUE THREAD

**Issue by srimanob** [cms-sw/cmssw#32869]
It seems to me that the offsets in Upgrade workflow are picking up randomly (or not?),
https://github.com/cms-sw/cmssw/blob/master/Configuration/PyReleaseValidation/python/upgradeWorkflowComponents.py

Should we try to document them, .e.g. add README, so we collect what are in, and guideline on numbering. And maybe we can try to review and to group them a bit, if it is not too many works, and not create a lot of confusion. I believe it will be better for long term support.

**Comment by makortel** [comment]
assign pdmv,upgrade

**Comment by chayanit** [comment]
Hi @srimanob , sounds good to have some documentation so everyone who add things can follow the rules which I actually don't know what the rules are, tbh

**Comment by srimanob** [comment]
Start to put the document in https://github.com/cms-sw/cmssw/pull/33087

**Comment by srimanob** [comment]
+1

**Comment by chayanit** [comment]
+1
