### ISSUE TITLE
ETL-relared failure in XMLIdealGeometryESSource

### ISSUE THREAD

**Issue by makortel** [cms-sw/cmssw#32882]
Workflow 33434.0 step 1 is failing since CMSSW_11_3_X_2021-02-11-1100
```
expr: etl___ETLthickness
------^
Evaluator : calculation error
----- Begin Fatal Exception 11-Feb-2021 18:38:24 CET-----------------------
An exception of category 'DDException' occurred while
   [0] Processing global begin Run run: 1
   [1] Calling method for module OscarMTProducer/'g4SimHits'
   [2] Using EventSetup component XMLIdealGeometryESSource/'' to make data DDCompactView/'' in record IdealGeometryRecord
   [3] Running EventSetup component XMLIdealGeometryESSource/'
Exception Message:
ClhepEvaluator ERROR: can't evaluate: etl___ETLthickness!
 nmspace=
 varname=etl___ETLthickness
 exp=
  at=
----- End Fatal Exception -------------------------------------------------
```
https://cmssdt.cern.ch/SDT/cgi-bin/logreader/slc7_amd64_gcc900/CMSSW_11_3_X_2021-02-11-1100/pyRelValMatrixLogs/run/33434.0_TTbar_14TeV+2026D73+TTbar_14TeV_TuneCP5_GenSimHLBeamSpot14+DigiTrigger+RecoGlobal+HARVESTGlobal/step1_TTbar_14TeV+2026D73+TTbar_14TeV_TuneCP5_GenSimHLBeamSpot14+DigiTrigger+RecoGlobal+HARVESTGlobal.log#/

**Comment by makortel** [comment]
assign geometry

**Comment by makortel** [comment]
From the PRs merged in  CMSSW_11_3_X_2021-02-11-1100 https://github.com/cms-sw/cmssw/pull/32840 looks like a plausible source

**Comment by ianna** [comment]
@fabiocos - please, either update the `ETLthickness` Variable defined in v5 etl.xml
https://cmssdt.cern.ch/lxr/search?%21v=CMSSW_11_3_X_2021-02-11-2300&_filestring=Xml&_string=ETLthickness
Or 2026D73 scenario to include updated v5 of a caloBase.xml that defines `ZposAL`
https://cmssdt.cern.ch/lxr/source/Geometry/CMSCommonData/python/cmsExtendedGeometry2026D73XML_cfi.py

**Comment by fabiocos** [comment]
@ianna @cvuosalo @srimanob sorry for this inconvenience, the obvious solution to me seems to remove scenario D73, that has no further reason to exist at this point.

**Comment by cvuosalo** [comment]
+1

**Comment by cvuosalo** [comment]
I think #32886 resolves the issue.
