### ISSUE TITLE
Uninitialized, unused member variable in SimCluster

### ISSUE THREAD

**Issue by kpedro88** [cms-sw/cmssw#32905]
While running valgrind for something else, I noticed the attached report of uninitialized values.

Looking at https://github.com/cms-sw/cmssw/blob/master/SimDataFormats/CaloAnalysis/interface/SimCluster.h and https://github.com/cms-sw/cmssw/blob/master/SimDataFormats/CaloAnalysis/src/SimCluster.cc, it seems that some of the member variables are definitely left uninitialized by some of the constructors.

I particularly noticed https://github.com/cms-sw/cmssw/blob/442ae0775276f4388f8d51742ea915c1b91e1506/SimDataFormats/CaloAnalysis/interface/SimCluster.h#L219, because it's never set or used anywhere, as far as I can tell.

It would be best to ensure that all primitive member variables are initialized by all constructors, and unused content is removed (saves memory, disk space, etc.).

**Comment by kpedro88** [comment]
assign simulation

**Comment by civanch** [comment]
+1

was fixed with #36346

**Comment by civanch** [comment]
@kpedro88 , this issue may be closed now.
