### ISSUE TITLE
Large allocation in lowptgsfeleseed::HeavyObjectCache

### ISSUE THREAD

**Issue by makortel** [cms-sw/cmssw#32938]
While investigating IgProf profile of 25400.0 step1 in https://github.com/cms-sw/cmssw/issues/32894#issuecomment-780130458 I noticed a large amount of memory, ~1.2 GB, being allocated in the constructor of `lowptgsfeleseed::HeavyObjectCache()`
https://mkortela.web.cern.ch/mkortela/cgi-bin/navigator/113x/fastsim_07.5_live/38

It is also visible in IB IgProf profile of data workflow 146.731 step3
```
           33.6  .............  1'381'344'112 / 1'381'344'441        334'900 / 334'905          edm::WorkerMaker<LowPtGsfElectronSeedProducer>::makeModule(edm::ParameterSet const&) const [37]
[38]       33.6  1'381'344'112              0 / 1'381'344'112        334'900                  lowptgsfeleseed::HeavyObjectCache::HeavyObjectCache(edm::ParameterSet const&)
           33.6  .............  1'381'344'016 / 1'450'690'960        334'897 / 624'356          createGBRForest(edm::FileInPath const&) [33]

```
https://cmssdt.cern.ch/SDT/jenkins-artifacts/igprof/CMSSW_11_3_X_2021-02-17-1100/slc7_amd64_gcc900/mp/136.731_RunSinglePh2016B+RunSinglePh2016B+HLTDR2_2016+RECODR2_2016reHLT_skimSinglePh_HIPM+HARVESTDR2/RES_MEM_step3___1c55e2e6b3a74b2451d9215d67c24de0___1.txt

This reminds me of https://github.com/cms-sw/cmssw/issues/28780#issuecomment-577746252

**Comment by makortel** [comment]
assign fastsim, reconstruction

**Comment by slava77** [comment]
@bainbrid 
please take a look or pass it over to who may know better.
Thank you.

**Comment by slava77** [comment]
IIUC, the same model is also used in phase-2 reco
and it looks OK in 11_3_0_pre2
https://jiwoong.web.cern.ch/jiwoong/cgi-bin/igprof-navigator/CMSSW_11_3_0_pre2/igprof_new_step3/ig.1/430

**Comment by makortel** [comment]
> IIUC, the same model is also used in phase-2 reco
> and it looks OK in 11_3_0_pre2
> https://jiwoong.web.cern.ch/jiwoong/cgi-bin/igprof-navigator/CMSSW_11_3_0_pre2/igprof_new_step3/ig.1/430

I'm also a bit puzzled why the large allocations are not visible there. The difference is largely on `tinyxml2::XMLDocument`
https://mkortela.web.cern.ch/mkortela/cgi-bin/navigator/113x/fastsim_07.5_live/23
vs
https://jiwoong.web.cern.ch/jiwoong/cgi-bin/igprof-navigator/CMSSW_11_3_0_pre2/igprof_new_step3/ig.1/288

The configuration (if I found the right one)
https://github.com/cms-sw/cmssw/blob/f91490fd5861333c9be8b8a0ce74eb7816cb2d11/RecoEgamma/EgammaElectronProducers/python/lowPtGsfElectronSeeds_cfi.py#L24-L27
suggests that XML should get parsed.

**Comment by slava77** [comment]
the memory bump in parsing the xml is expected, but then it's supposed to go away (deallocated).
Did you profile with GlibC?

**Comment by slava77** [comment]
pre3 is also 40 MB
https://slava77sk.web.cern.ch/slava77sk/reco/cgi-bin/igprof-navigator/CMSSW_11_3_0_pre3-orig.136.888.step3.IgProf.1.MEM_LIVE/236

the above is made with ` --customise Validation/Performance/IgProfInfo.customise` and running `igprof -d -t cmsRunGlibC -mp cmsRunGlibC config.py`

Looking at the IB log:
https://cmssdt.cern.ch/SDT/jenkins-artifacts/igprof/CMSSW_11_3_X_2021-02-17-1100/slc7_amd64_gcc900/mp/136.731_RunSinglePh2016B+RunSinglePh2016B+HLTDR2_2016+RECODR2_2016reHLT_skimSinglePh_HIPM+HARVESTDR2/runTheMatrix.log
` --profile mp ` is used instead
IIUC, Configuration/Applications/python/cmsDriverOptions.py converts this to `options.prefix = "igprof -t cmsRun -mp"`


OK, this perhaps explains the difference.
A while back when the switch for -mp to use cmsRunGlibC was made I recall that most of the deallocations were not recognized and MEM_LIVE looked more like MEM_TOTAL with cmsRun/jmealloc. The current result looks more sensible, except for this difference in the file use.

What's the right/more appropriate mem profile setup to use?

**Comment by makortel** [comment]
> Did you profile with GlibC?

I profiled with jemalloc.

> A while back when the switch for -mp to use cmsRunGlibC was made I recall that most of the deallocations were not recognized and MEM_LIVE looked more like MEM_TOTAL with cmsRun/jmealloc.

I've missed this detail. Perhaps this PR is a red herring then. My command was `igprof -d -t cmsRun -z -j -mp` (where `-j` stands for  `use libjemalloc.so library instead of libc.so.6`). I just repeated my profile with `cmsRunGlibC`, and the large allocation is now gone (so I'll close the issue).

> What's the right/more appropriate mem profile setup to use?

Maybe it should `cmsRunGlibC` for the memory profile?

**Comment by slava77** [comment]
digging a bit more, still with 1130pre3 wf 136.888 step3 (sorry for no cross-matching of the earlier used/mentioned workflows)

with `-d -t cmsRun` the log is flooded by messages like 
```
*** IgProf(25028, 1613610145.363): new MEM_LIVE resource 0x7fa99ccdb380 of 440 bytes was never freed in 0x7fa9a1b4c660
```

without `-d` (debug) it runs to completion and the total for the first event comes out at about the same 1.3GiB 
https://slava77sk.web.cern.ch/slava77sk/reco/cgi-bin/igprof-navigator/CMSSW_11_3_0_pre3-orig.136.888.step3.mp-cmsRun.IgProf.1.MEM_LIVE/34
as in your link for fastsim
https://mkortela.web.cern.ch/mkortela/cgi-bin/navigator/113x/fastsim_07.5_live/38

Looking at RSS use by simply polling /proc/$PID/statm for a regular cmsRun job with a `Tracer` enabled, I see that `lowPtGsfElectronSeeds` has a bump in memory use during module construction of about 2.3 GiB a few seconds before the end of the constructor call, with 1.4 GiB extra at the end of the constructor call (compared to 1.2GiB total of  RSS right before the call). By the time the beginStream is called,  the RSS "decays" to 1.4 GiB, which leaves at most 0.2 GiB for everything constructed after and including `lowPtGsfElectronSeeds`. So, it seems to me that there is no real 1.4 GiB .

Note that the same scan of RSS (same as with the post-event MemoryCheck) shows that at the moment of calling the igprof dump I get 3.4 GiB with cmsRunGlibC and  3.6 GiB total with cmsRun, compared to 3.0 GiB in MEM_LIVE with cmsRunGlibC and 4.4 GiB with cmsRun. 

So, igprof with cmsRun/jmealloc  is clearly over-reporting MEM_LIVE.

With cmsRunGlibC it looks like the MEM_LIVE is below the RSS by perhaps some of the shared mem or some pages that were released but not taken over yet.

**Comment by makortel** [comment]
Thanks Slava for the additional tests.

> So, igprof with cmsRun/jmealloc is clearly over-reporting MEM_LIVE.
> 
> With cmsRunGlibC it looks like the MEM_LIVE is below the RSS by perhaps some of the shared mem or some pages that were released but not taken over yet.

So perhaps the `cmsRunGlibC` is indeed better for the IgProf memory profile. @dpiparo Would you have anything to add here?

@gartung FYI as well. I think we should look into using `cmsRunGlibC` in the IgProf memory profiles in (PR?)/IB tests.
