### ISSUE TITLE
Unit test failure in Validation/CTPPS

### ISSUE THREAD

**Issue by makortel** [cms-sw/cmssw#32996]
Unit test in Validation/CTPPS fails in CMSSW_11_3_X_2021-02-25-1100
```
===== Test "TestCTPPSDirectProtonSimulation" ====
argument 0: TestCTPPSDirectProtonSimulation
argument 1: /bin/bash
argument 2: Validation/CTPPS/test/simu
argument 3: run_multiple
shell is: /bin/bash
Current directory is: /data/cmsbld/jenkins/workspace/ib-run-qa/CMSSW_11_3_X_2021-02-25-1100
topdir is: /data/cmsbld/jenkins/workspace/ib-run-qa/CMSSW_11_3_X_2021-02-25-1100
testdir is: /data/cmsbld/jenkins/workspace/ib-run-qa/CMSSW_11_3_X_2021-02-25-1100/src/Validation/CTPPS/test/simu
tmpdir is: /data/cmsbld/jenkins/workspace/ib-run-qa/CMSSW_11_3_X_2021-02-25-1100/tmp/slc7_amd64_gcc900
testbin is: /data/cmsbld/jenkins/workspace/ib-run-qa/CMSSW_11_3_X_2021-02-25-1100/test/slc7_amd64_gcc900
Running script: /data/cmsbld/jenkins/workspace/ib-run-qa/CMSSW_11_3_X_2021-02-25-1100/src/Validation/CTPPS/test/simu/run_multiple
status = 256

---> test TestCTPPSDirectProtonSimulation had ERRORS
```
https://cmssdt.cern.ch/SDT/cgi-bin/logreader/slc7_amd64_gcc900/CMSSW_11_3_X_2021-02-25-1100/unitTestLogs/Validation/CTPPS#/

**Comment by makortel** [comment]
assign dqm

**Comment by jfernan2** [comment]
@jan-kaspar @nminafra can you please have a look and provide a fix?

**Comment by jan-kaspar** [comment]
@forthommel Could this be due to #32974 ?

@makortel @jfernan2 Do you understand why this failure was not discovered during the PR tests?

**Comment by forthommel** [comment]
Possibly, but this was neither observed in my development environment nor in the unit tests of #32974 (priorly rebased on top of `CMSSW_11_3_X_2021-02-22-2300` before issuing the PR).

**Comment by makortel** [comment]
> Do you understand why this failure was not discovered during the PR tests?

Without seeing what exactly is failing and how it is hard for me to say anything. In principle the tests of #32974 should have caught any issue that PR would cause to `Validation/CTPPS` unit tests.

There was another PPS PR merged in the same IB, https://github.com/cms-sw/cmssw/pull/32971. Could that have anything to do with this failure?

**Comment by forthommel** [comment]
Indeed it seems related to the renaming of `label` to `tag` that was not fully propagated in the validation script.
I'm currently preparing a follow-up PR.

**Comment by forthommel** [comment]
... here it is.

**Comment by forthommel** [comment]
As mentioned in the PR description, not sure why it has not been picked up by https://github.com/cms-sw/cmssw/pull/32971#issuecomment-784952590.

**Comment by makortel** [comment]
> As mentioned in the PR description, not sure why it has not been picked up by [#32971 (comment)](https://github.com/cms-sw/cmssw/pull/32971#issuecomment-784952590).

Good question. @smuzaffar, `Validation/CTPPS/python/simu_config/base_cff.py` has imports like
```py
from RecoPPS.Local.ctppsLocalTrackLiteProducer_cff import *
```
so `git cms-checkdeps -a` should know about `Validation/CTPPS` depending on `RecoPPS.Local`, right?

Why didn't the changes in #32971 cause `Validation/CTPPS` to be checked out in the PR tests? Could it be indirection in the imports of `cff` files, or the change ending up in `fillDescriptions()`-generated configuration file?

**Comment by smuzaffar** [comment]
@makortel ,  only if `Validation/CTPPS/python/simu_config/base_cff.py` itself had changed. checkdeps knows deps but it will checkout the dependent packages if there are changes in files they depend on. e.g. changing a `.cc` file is not going to checkout any package before nothing should be depending on a source file.

**Comment by makortel** [comment]
Right. But should a change in a python file that `Validation/CTPPS/python/simu_config/base_cff.py` depends on also cause it to be checked out?

**Comment by smuzaffar** [comment]
yes, change in a python file used by `Validation/CTPPS/python/simu_config/base_cff.py`  should checkout `Validation/CTPPS`

**Comment by makortel** [comment]
What about a change in a python file used by a python file used by `Validation/CTPPS/python/simu_config/base_cff.py` (i.e. adding one level of indirection)?

**Comment by forthommel** [comment]
Can it be that `RecoPPS/Local` (only subpackage modified in #32971) is outside the ballpark of the `Validation/CTPPS` suite? As a naive follow-up question, where is this mapping defined?

**Comment by smuzaffar** [comment]
@makortel , yes it should. If `pack1/py` uses `pack2/py` and `pack2/py` uses `pack3/py` then change in `pack3/py` should checkout both pack1 and pack2. 

@forthommel , mappiong is not hard coded any where. After the build of release we run `https://github.com/cms-sw/cmssw-config/blob/scramv3/SCRAM/findDependencies.pl#L119` to find out the dependencies (e.g. greping for `import and from ` statements ion python files.

**Comment by makortel** [comment]
> yes it should. If `pack1/py` uses `pack2/py` and `pack2/py` uses `pack3/py` then change in `pack3/py` should checkout both pack1 and pack2.

Thanks, that's what I thought. What happened with #32971 is that the `pack3/py` is generated with `fillDescriptions()` (`edmWriteConfigs`), and the C++ code change lead to a change in the generated python file. Could the dependence tracking miss this kind of update in python files?

**Comment by smuzaffar** [comment]
we are not keeping track of generated python files ( as they are not in git, so hard to find if they are changed or not) and any python file in non package/python directory.

**Comment by makortel** [comment]
Thanks, so it was the generated python file that caused the update being "missed". It's a bit unfortunate given the recommendation to use `fllDescription()`, but I suppose there is nothing simple that could be done.

**Comment by smuzaffar** [comment]
> yes it should. If pack1/py uses pack2/py and pack2/py uses pack3/py then change in pack3/py should checkout both pack1 and pack2.

this statement was wrong, I just tested and looks like (for python files) we are only keeping track of direct dependencies.
