### ISSUE TITLE
Treatment of HCAL MC digi flavor in GPU producer

### ISSUE THREAD

**Issue by kpedro88** [cms-sw/cmssw#33002]
A brief history lesson: originally (and throughout Run 2), all QIE11 MC digis were assigned flavor 0:
https://github.com/cms-sw/cmssw/blob/CMSSW_10_6_X/EventFilter/HcalRawToDigi/plugins/PackerHelp.h#L429
https://github.com/cms-sw/cmssw/blob/CMSSW_10_6_X/EventFilter/HcalRawToDigi/src/HcalUnpacker.cc#L631

However, the previously-unused flavor 3 was recently assigned to HB QIE11 digis to handle some format changes (if I understand correctly). In particular, this change interacted with the usage and simulation of the TDC, in a series of PRs from @lwang046 in the 11_X_Y release cycles: #28330, #29159, #30213 (among others).

The upshot is that, right now, HB QIE11 digis *can* be assigned flavor 3, but that behavior is *disabled* by default:
https://github.com/cms-sw/cmssw/blob/5d91b012f45b91b94c51f743072fae2fe80c284b/EventFilter/HcalRawToDigi/plugins/HcalDigiToRawuHTR.cc#L162
https://github.com/cms-sw/cmssw/blob/5d91b012f45b91b94c51f743072fae2fe80c284b/EventFilter/HcalRawToDigi/plugins/HcalDigiToRawuHTR.cc#L293

@yongbinfeng noticed that the GPU digi producer only accepts flavor 3 digis for HB:
https://github.com/cms-sw/cmssw/blob/5d91b012f45b91b94c51f743072fae2fe80c284b/EventFilter/HcalRawToDigi/plugins/HcalDigisProducerGPU.cc#L176-L200

Intuitively, I suspect this is the cause of the unexpected downstream changes when the MAHI GPU code was integrated in CMSSW (much like the HEM problem, hadrons look like electrons if there are no HCAL hits). I have not checked this explicitly, however.

attn: @abdoulline @mariadalfonso

**Comment by kpedro88** [comment]
assign reconstruction, heterogeneous

**Comment by abdoulline** [comment]
@kpedro88   thank you for raising this issue.

So (I'm rephrasing your information for my better understanding) :  

(1) Flavor 3 is hardcoded in PackerHelp.h  in  convertHB()
https://cmssdt.cern.ch/lxr/source/EventFilter/HcalRawToDigi/plugins/PackerHelp.h#0626

(2) While this method is invoked _conditionally_  (for configurable  packHBTDC=True)      
https://cmssdt.cern.ch/lxr/source/EventFilter/HcalRawToDigi/plugins/HcalDigiToRawuHTR.cc#0162
And currently packHBTDC=False by default for MC _studies_ purposes: to keep TDC full-range (non-packed)... 

(3) HcalDigisProducerGPU.cc  only accepts flavor 3 for HB (which is baseline HB flavor for Run3)

**Comment by abdoulline** [comment]
Probably the least intrusive solution would be to set packHBTDC=True by default again and 
require to customize it to False for each MC production, as we did before June 2020  (https://github.com/cms-sw/cmssw/pull/30213).
I'm not sure it would be OK for all the cases though... 
We'll discuss the issue at HCAL Trigger meeting today.

**Comment by fwyzard** [comment]
Thanks Kevin, I've also added it to the list of open issues in #32413 .

**Comment by abdoulline** [comment]
At HCAL meeting it have been just decided to opt for nominal HB flavor=3  (with packed HB TDC) in  >= 11_3_X  MC.  
We'll agree on and set some reasonable configurable parameters of TDC HB packing early next week and submit a PR.

**Comment by perrotta** [comment]
> Intuitively, I suspect this is the cause of the unexpected downstream changes when the MAHI GPU code was integrated in CMSSW (much like the HEM problem, hadrons look like electrons if there are no HCAL hits). I have not checked this explicitly, however.

Did anybody check that #33050 can fix these "unexpected downstream changes"?

**Comment by kpedro88** [comment]
Coming back to this - has the HLT rate been checked with the fix for this issue?

**Comment by slava77** [comment]
> Coming back to this - has the HLT rate been checked with the fix for this issue?

is it perhaps known by now?

**Comment by mariadalfonso** [comment]
I checked the situation at the 12_0_pre5 (this release contains already the roll back to the HB specifications).
I usued the workflows 11634.521 and 11634.522 (here runned the step3 with the same step2 digi to avoid the PU mixing randomness). 
<img width="710" alt="Run3_MC_CPUGPU" src="https://user-images.githubusercontent.com/5656714/132340635-3dca2a6c-f81a-4a6f-8f64-3b2fa39959e5.png">

I think this close this issue: as the GPU can read the DIGI-RUN3 dataformat.

(P.S. now I just need to understand why the CPU has less rechit of the GPU, but this is another issue in ttbar MC.)

**Comment by abdoulline** [comment]
@mariadalfonso  thanks for confirmation about MC "unpack-ability"!

**Comment by perrotta** [comment]
@kpedro88 given https://github.com/cms-sw/cmssw/issues/33002#issuecomment-914245864 can we close this issue?

**Comment by kpedro88** [comment]
@perrotta yes, the latest result addresses this specific issue. (I do think it would still be good to confirm the HLT rate is now as expected.)

**Comment by perrotta** [comment]
> @perrotta yes, the latest result addresses this specific issue. (I do think it would still be good to confirm the HLT rate is now as expected.)

@cms-sw/hlt-l2

**Comment by Martin-Grunewald** [comment]
@fwyzard

**Comment by fwyzard** [comment]
The results from data taking during the pilot beams were looking good; the remaining issues seem more related to the PF code than to the HCAL digis themselves, and are being followed up in https://github.com/cms-sw/cmssw/issues/35923 .
