### ISSUE TITLE
Memory increased in Phase2 PU200 RelVal production since 11_3_0_pre1

### ISSUE THREAD

**Issue by chayanit** [cms-sw/cmssw#33004]
Long story short, during 11_2_X series, we have performed CPU and memory optimisation [*] as requested by Comp-Ops and we finally came up with the conclusion that the newly optimal parameters to submit Phase2 PU200 RelVals is *8 cores 2 streams with 12GB memory* (just a reminder that it used to be 2 cores 15GB in the past which consumed too large memory per CPU core and the memory restriction at FNAL is about 15GB) 

Since then we have been running the Phase2 PU200 Relvals with such computing setup and the PeakRSS value stayed at about 11GB as you can see from the first plot. 

<img width="302" alt="11_3_0_pre1_RECOPU" src="https://user-images.githubusercontent.com/5130391/109264678-a7c7f080-7805-11eb-8242-855b007728bc.png">

However, we have recently observed some memory increased in Phase2 Relval production starting from 11_3_0_pre2 (above 12GB) and increasing again in 11_3_0_pre3 (up to 13GB). The PeakValueRSS now goes beyond the optimal setup of 12GB which led to the jobs failed and we have to resubmit with increasing memory up to 14-15GB now. 

<img width="307" alt="11_3_0_pre2_RECOPU" src="https://user-images.githubusercontent.com/5130391/109264918-00978900-7806-11eb-93a2-a54ed8c66ef0.png">
<img width="322" alt="11_3_0_pre3_RECOPU" src="https://user-images.githubusercontent.com/5130391/109264922-01c8b600-7806-11eb-8b46-09c1c79aade1.png">

As you can see, we are running at the boundary of memory now and we need to report and inform about this to the software team so anyone related can help checking. We can't go beyond 15GB and it would be nice if we can find what cause this memory increased. 

PS. I have checked and found everything is OK for Run3 workflows. Please feel free to include more related people. 

Best,
Chayanit for PdmV team

[*]
https://dmytro.web.cern.ch/dmytro/cmsprodmon/workflows.php?campaign=CMSSW_11_2_0_pre10__UPSG_Std_2026D49PU200_TestMemory-1607095698
https://dmytro.web.cern.ch/dmytro/cmsprodmon/workflows.php?campaign=CMSSW_11_2_0_pre10__UPSG_Std_2026D49PU200_TestMemory-1607146513

FYI. @silviodonato , @qliphy , @cms-sw/reconstruction-l2, @slava77, @cms-sw/upgrade-l2 , @cms-sw/pdmv-l2, @rappoccio

**Comment by makortel** [comment]
assign upgrade, reconstruction, pdmv

**Comment by makortel** [comment]
> the newly optimal parameters to submit Phase2 PU200 RelVals is _8 cores 2 streams with 12GB memory_

@chayanit Out of curiosity, what level of CPU efficiency those jobs achieve?

**Comment by slava77** [comment]
@chayanit 
please post a configuration/reqmgr2 detail for the failing workflow(s) in pre2 and pre3.
This may help.
We (reco) regularly monitor only production-like setup (no DQM/Validation), and it could be that #32756 is not well related

**Comment by chayanit** [comment]
> @chayanit
> please post a configuration/reqmgr2 detail for the failing workflow(s) in pre2 and pre3.
> This may help.
> We (reco) regularly monitor only production-like setup (no DQM/Validation), and it could be that #32756 is not well related

Hi @slava77 , here the link leading to configuration/reqmgr2
pre2 : https://dmytro.web.cern.ch/dmytro/cmsprodmon/workflows.php?campaign=CMSSW_11_3_0_pre2__UPSG_Std_2026D49PU200_highPU-1611425057
pre3 : https://dmytro.web.cern.ch/dmytro/cmsprodmon/workflows.php?campaign=CMSSW_11_3_0_pre3__UPSG_Std_2026D49PU200_highPU-1613369037 

@makortel not sure how we can extract such information from production but when we tested running jobs on HTcondor this is information we have. https://docs.google.com/spreadsheets/d/1aArpu7ZzJBSKfsPnyC8ZusX5OdkI7e6DuTts5C6QpNg/edit?usp=sharing

**Comment by makortel** [comment]
@chayanit 

> not sure how we can extract such information from production

I think I was able to find `pdmvserv_RVCMSSW_11_3_0_pre3TTbar_14TeV__2026D49PU200_210215_071127_7892` in https://cmsdatapop.web.cern.ch/cmsdatapop/cpu_eff/production/CPU_Efficiency_Table.html and the overall CPU efficiency is in the ballpark of 36-38 % (depending on definition; at T1_US_FNAL).

The poor efficiency is partly visible the spreadsheet https://docs.google.com/spreadsheets/d/1aArpu7ZzJBSKfsPnyC8ZusX5OdkI7e6DuTts5C6QpNg/edit?usp=sharing that gives upper limits for
* step2: 56 %
* step3: 92 %

Would it be feasible to use different settings of nThreads and nStreams for different steps? From the spreadsheet step2 on 8 cores could memory-wise fit 4 or 6 streams and that would increase the throughput of that step (and CPU efficiency).

**Comment by slava77** [comment]
> Since then we have been running the Phase2 PU200 Relvals with such computing setup and the PeakRSS value stayed at about 11GB as you can see from the first plot.

were the plots provided made for the full multistep workflow or just step3? 
Please clarify.
The gdoc seems to imply that step2 is rather heavy as well; and the gdoc is in 102pre9 only (not detailed for 103pre2/pre3)

**Comment by chayanit** [comment]
> @chayanit
> 
> > not sure how we can extract such information from production
> 
> I think I was able to find `pdmvserv_RVCMSSW_11_3_0_pre3TTbar_14TeV__2026D49PU200_210215_071127_7892` in https://cmsdatapop.web.cern.ch/cmsdatapop/cpu_eff/production/CPU_Efficiency_Table.html and the overall CPU efficiency is in the ballpark of 36-38 % (depending on definition; at T1_US_FNAL).
> 
> The poor efficiency is partly visible the spreadsheet https://docs.google.com/spreadsheets/d/1aArpu7ZzJBSKfsPnyC8ZusX5OdkI7e6DuTts5C6QpNg/edit?usp=sharing that gives upper limits for
> 
> * step2: 56 %
> * step3: 92 %
> 
> Would it be feasible to use different settings of nThreads and nStreams for different steps? From the spreadsheet step2 on 8 cores could memory-wise fit 4 or 6 streams and that would increase the throughput of that step (and CPU efficiency).

Sorry but why we are talking about CPU efficiency here? I thought one should check which PR or what cause the significant increase in memory across release no? Do I miss anything?

**Comment by makortel** [comment]
> Sorry but why we are talking about CPU efficiency here?

Let's say to provide additional motivation to address the memory issue (because the 8 threads 2 streams setup wastes lot's of CPU).

But in more general, would tuning the steps differently be worthwhile (if they turn out to have very different memory scaling behavior), or would that increase the manual load too much?

**Comment by chayanit** [comment]
> > Since then we have been running the Phase2 PU200 Relvals with such computing setup and the PeakRSS value stayed at about 11GB as you can see from the first plot.
> 
> were the plots provided made for the full multistep workflow or just step3?
> Please clarify.

Multistep

> The gdoc seems to imply that step2 is rather heavy as well; and the gdoc is in 102pre9 only (not detailed for 103pre2/pre3)

gDoc was the work we have done since 11_2_0_pre9 for the optimisation in production based on HTCondor jobs as mentioned in the beginning

**Comment by chayanit** [comment]
Just to follow up the question in ORP meeting today, the memory for Phase2 highPU workflows does not increase between 11_3_0_pre3 and 11_3_0_pre4. But do we understand what cause the increase since 11_3_0_pre2? 

PeakRSSValue for TTbar 2026D76PU200 in pre3
<img width="311" alt="pre3_RECOPU" src="https://user-images.githubusercontent.com/5130391/111351696-bd516d00-8683-11eb-83d5-7373375dc7f0.png">

PeakRSSValue for TTbar 2026D76PU200 in pre4
<img width="321" alt="pre4_RECOPU" src="https://user-images.githubusercontent.com/5130391/111351730-c3dfe480-8683-11eb-8fd5-6e83dda68163.png">

**Comment by jpata** [comment]
>  Btw, do we understand what cause the increase since 11_3_0_pre2?
Yes, as far as I'm aware, a significant part is from this issue: https://github.com/cms-sw/cmssw/issues/32756

**Comment by slava77** [comment]
+reconstruction

https://github.com/cms-sw/cmssw/issues/32756#issuecomment-824831837

**Comment by srimanob** [comment]
+Upgrade

**Comment by srimanob** [comment]
@cms-sw/pdmv-l2 
I believe this issue can be closed,  https://github.com/cms-sw/cmssw/issues/32756#issuecomment-824831837

**Comment by bbilin** [comment]
+1
