### ISSUE TITLE
L1Reco step in Phase2

### ISSUE THREAD

**Issue by srimanob** [cms-sw/cmssw#33012]
Following the discussion with L1T, L1Reco step is obsolete for Phase2. Without this step, the l1 extra particles will not be added to the output (*). cmsDriver seems to be OK (**).

However, it is unclear from user/analysis side. Will we get L1 physics objects (physical representations of L1 hardware)? I think this is the reason that L1Extra was introduced in the past. Currently, this step does 4 things:
`L1Reco = cms.Sequence(l1extraParticles+l1GtTriggerMenuLite+conditionsInEdm+l1L1GtObjectMap)`
In addition, what is currently produced in the workflow by default is meaningful, or junk.

If agree, I will drop L1Reco out from RECO sequence for Phase2.

(*)
```
vector<l1extra::L1EmParticle>         "l1extraParticles"          "Isolated"        "RECO"    
vector<l1extra::L1EmParticle>         "l1extraParticles"          "NonIsolated"     "RECO"    
vector<l1extra::L1EtMissParticle>     "l1extraParticles"          "MET"             "RECO"    
vector<l1extra::L1EtMissParticle>     "l1extraParticles"          "MHT"             "RECO"    
vector<l1extra::L1HFRings>            "l1extraParticles"          ""                "RECO"    
vector<l1extra::L1JetParticle>        "l1extraParticles"          "Central"         "RECO"    
vector<l1extra::L1JetParticle>        "l1extraParticles"          "Forward"         "RECO"    
vector<l1extra::L1JetParticle>        "l1extraParticles"          "IsoTau"          "RECO"    
vector<l1extra::L1JetParticle>        "l1extraParticles"          "Tau"             "RECO"    
vector<l1extra::L1MuonParticle>       "l1extraParticles"          ""                "RECO"   
```

(**)
```
cmsDriver.py step3B  --conditions auto:phase2_realistic_T21 -s RAW2DIGI,RECO,RECOSIM,PAT --datatier AODSIM,MINIAODSIM -n -1 --geometry Extended2026D76 --era Phase2C11M9 --eventcontent AODSIM,MINIAODSIM --python step3B_RecoGlobalMini_ProdLike_2026D76.py --nThreads 8 --no_exec --filein  file:step2.root  --fileout file:step3B.root --customise SLHCUpgradeSimulations/Configuration/aging.customise_aging_1000,Configuration/DataProcessing/Utils.addMonitoring --customise_command 'process.SimpleMemoryCheck.jobReportOutputOnly = cms.untracked.bool(False)' 
```

**Comment by srimanob** [comment]
assign upgrade, l1

**Comment by rekovic** [comment]
@srimanob 
As we discussed in the email thread, the above objects are are all Legacy trigger objects, and they have no meaning for Phase2. So they should be dropped, as well as the L1Reco step from the workflow.  The meaningful L1T objects for Phase2 are produced by the L1 step, i.e. in the `SimL1EmulatorTask` modified by the `phase2_trigger` modifier in the [configuration](https://github.com/cms-sw/cmssw/blob/master/L1Trigger/Configuration/python/SimL1Emulator_cff.py). These are meaningful objects for Phase2 and those objects are indeed that can be of interest to the analysis, just like were the Stage2 objects.

**Comment by davidlange6** [comment]
how will this work for real data? Everything will be stored in the raw data itself?

**Comment by srimanob** [comment]
Hi @rekovic 
I don't know if what @davidlange6 mentioned is what you think? But if that is the case, I assume some collections should propagate to AODSIM, so analysts can use them easily. Where is the right forum to discuss this?

**Comment by srimanob** [comment]
Kindly ping @cms-sw/l1-l2

**Comment by srimanob** [comment]
Hi @cms-sw/l1-l2 @BenjaminRS Could you please comment on this? Should we stop this `L1Reco` step for Phase-2 wf.

**Comment by cecilecaillol** [comment]
@srimanob I think we can remove L1Reco step, which is obsolete, and to run the updated L1 objects we need the steps L1TrackTrigger,L1

**Comment by srimanob** [comment]
Hi @cecilecaillol 
Could you please clarification on L1TrackTrigger,L1

Currently we run
cmsDriver.py step2  -s DIGI:pdigi_valid,L1TrackTrigger,L1,DIGI2RAW,HLT:@fake2 
cmsDriver.py step3  -s RAW2DIGI,L1Reco,RECO,RECOSIM,PAT

and output we save comes from step3. Do you mean we need to rerun L1TrackTrigger,L1 in step-3 also? As current situation, it seems FEVT is not enough, it seems we may need L1TriggerFEVTDEBUG in output.

**Comment by srimanob** [comment]
https://github.com/cms-sw/cmssw/pull/38010 is merged.
However, I propose this ticket to keep opening until we have a clarification on how information is flown, i.e. Have L1 objects in RAW and pass to RECO.
