### ISSUE TITLE
Missing GEN-SIM input file for 11725.0 and 11925.0

### ISSUE THREAD

**Issue by silviodonato** [cms-sw/cmssw#33010]
After having merged #32983 which add `11725.0` and `11925.0`, we need the corresponding GEN-SIM input files 
@cms-sw/pdmv-l2 Could you add the missing files?

**Comment by silviodonato** [comment]
assign pdmv

**Comment by qliphy** [comment]
ping @cms-sw/pdmv-l2   

As shown in https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-0cd059/13091/dasqueries/run.txt
we are missing this file:
/RelValGluGluTo2Jets_14TeV/CMSSW_11_2_0_pre8-112X_mcRun3_2021_realistic_v10-v1/GEN-SIM
Would you please add this?

**Comment by chayanit** [comment]
This is 

> ping @cms-sw/pdmv-l2
> 
> As shown in https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-0cd059/13091/dasqueries/run.txt
> we are missing this file:
> /RelValGluGluTo2Jets_14TeV/CMSSW_11_2_0_pre8-112X_mcRun3_2021_realistic_v10-v1/GEN-SIM
> Would you please add this?

This seems impossible since the given workflows are not yet available in 11_2_0_pre8. Shall we remove from the current IB tests and add back when we update GS string in 11_3_X?

**Comment by qliphy** [comment]
@chayanit  Thanks!  Let's discuss this at the next ORP meeting.

**Comment by silviodonato** [comment]
@cms-sw/pdmv-l2 `CMSSW_11_3_0_pre4` is ready, so you can produce the new dataset.

> Shall we remove from the current IB tests and add back when we update GS string in 11_3_X?

We have removed the wf by #33020. Yes, we will add them back when you update the GS string in 11_3_X, thanks!

**Comment by chayanit** [comment]
> @cms-sw/pdmv-l2 `CMSSW_11_3_0_pre4` is ready, so you can produce the new dataset.
> 
> > Shall we remove from the current IB tests and add back when we update GS string in 11_3_X?
> 
> We have removed the wf by #33020. Yes, we will add them back when you update the GS string in 11_3_X, thanks!

@silviodonato all GENSIM needed for IB test have been submitted. I will inform and create PR to update GT string accordingly.

**Comment by chayanit** [comment]
btw, @silviodonato apart from adding back PPS workflows, I would propose we should update 12024 (TTbar 2021 design but 13TeV) to 12034 which is 14TeV.
https://github.com/cms-sw/cmssw/blob/master/Configuration/PyReleaseValidation/python/relval_2017.py#L60 

and shall we move this workflow back to TTbar (DeepCore) 11634.17? @mtosi 
https://github.com/cms-sw/cmssw/blob/master/Configuration/PyReleaseValidation/python/relval_2017.py#L68 
https://github.com/cms-sw/cmssw/blob/master/Configuration/PyReleaseValidation/python/upgradeWorkflowComponents.py#L327

**Comment by slava77** [comment]
moving to a generic ttbar is not a good idea because the deepcore requires high-pt jets to be enabled. These are sufficiently rare in the generic ttbar that we may end up not running deepcore algorithm at all on a small sample.

**Comment by chayanit** [comment]
@slava77 ah ok I think I was confused. I will leave as it is.

**Comment by chayanit** [comment]
+1 

new PR is opened #33090
