### ISSUE TITLE
Unit test failure in CalibTracker/SiStripChannelGain

### ISSUE THREAD

**Issue by makortel** [cms-sw/cmssw#33055]
Unit test in CalibTracker/SiStripChannelGain fails in CMSSW_11_3_X_2021-03-03-1100
```
Running script: /data/cmsbld/jenkins/workspace/ib-run-qa/CMSSW_11_3_X_2021-03-03-1100/src/CalibTracker/SiStripChannelGain/test/testSSTGain_PCL_FromRECO.sh
03-Mar-2021 13:33:17 CET  Initiating request to open file file:PromptCalibProdSiStripGains_A.root
----- Begin Fatal Exception 03-Mar-2021 13:33:17 CET-----------------------
An exception of category 'FileOpenError' occurred while
   [0] Constructing the EventProcessor
   [1] Constructing input source of type PoolSource
   [2] Calling RootInputFileSequence::initTheFile()
   [3] Calling StorageFactory::open()
   [4] Calling File::sysopen()
Exception Message:
Failed to open the file 'PromptCalibProdSiStripGains_A.root'
   Additional Info:
      [a] Input file file:PromptCalibProdSiStripGains_A.root could not be opened.
      [b] open() failed with system error 'No such file or directory' (error code 2)
----- End Fatal Exception -------------------------------------------------
Failure running cmsRun testSSTGain_HARVEST_FromRECO.py 0: status 84
status = 21504

---> test testSSTGainPCL_fromRECO had ERRORS
```
http://cmssdt.cern.ch/SDT/cgi-bin/logreader/slc7_amd64_gcc900/CMSSW_11_3_X_2021-03-03-1100/unitTestLogs/CalibTracker/SiStripChannelGain

**Comment by makortel** [comment]
assign alca

**Comment by makortel** [comment]
It is not evident from the error message or from the PRs merged in CMSSW_11_3_X_2021-03-03-1100 what could be causing the error.

**Comment by christopheralanwest** [comment]
I can't reproduce this failure. When I run `scram b runtests` in the `CalibTracker/SiStripChannelGain` package under `CMSSW_11_3_X_2021-03-03-1100` I get the following output:

```
===== Test "testSSTGainPCL_fromRECO" ====
argument 0: testSSTGainPCL_fromRECO
argument 1: /bin/bash
argument 2: CalibTracker/SiStripChannelGain/test
argument 3: testSSTGain_PCL_FromRECO.sh
shell is: /bin/bash
Current directory is: /tmp/cawest/CMSSW_11_3_X_2021-03-03-1100
topdir is: /tmp/cawest/CMSSW_11_3_X_2021-03-03-1100
testdir is: /tmp/cawest/CMSSW_11_3_X_2021-03-03-1100/src/CalibTracker/SiStripChannelGain/test
tmpdir is: /tmp/cawest/CMSSW_11_3_X_2021-03-03-1100/tmp/slc7_amd64_gcc900
testbin is: /tmp/cawest/CMSSW_11_3_X_2021-03-03-1100/test/slc7_amd64_gcc900
Running script: /tmp/cawest/CMSSW_11_3_X_2021-03-03-1100/src/CalibTracker/SiStripChannelGain/test/testSSTGain_PCL_FromRECO.sh
Using Dataset: /ZeroBias/Run2018A-SiStripCalMinBias-12Nov2019_UL2018-v1/ALCARECO
```

The error at https://cmssdt.cern.ch/SDT/cgi-bin/logreader/slc7_amd64_gcc900/CMSSW_11_3_X_2021-03-03-1100/unitTestLogs/CalibTracker/SiStripChannelGain#/ does not include the last line that would be printed if the DAS query were successful: 
https://github.com/cms-sw/cmssw/blob/11c42d55511fb94f1ce81dbc8b3184988c10f3ef/CalibTracker/SiStripChannelGain/test/testSSTGain_PCL_FromRECO_cfg.py#L33

Since this step of the tests cannot be run, the output file from this step is not available for the next step of the test.

I will investigate further if the problem does not resolve itself in the next IB.

**Comment by makortel** [comment]
@silviodonato's comment in https://github.com/cms-sw/cmssw/issues/33059#issuecomment-789905943 also suggests a transient failure.

Could the script perhaps be modified to print out that the DAS query failed? (then it would be clear for everyone that such failure would be transient)

**Comment by mmusich** [comment]
> Could the script perhaps be modified to print out that the DAS query failed? (then it would be clear for everyone that such failure would be transient)

I'll provide something, though from `Failed to open the file` seems pretty clear to me something with retrieving data is wrong...

**Comment by makortel** [comment]
> I'll provide something, though from `Failed to open the file` seems pretty clear to me something with retrieving data is wrong...

In principle yes, but the file in this case is local, and without knowing the script it could be an output of an earlier job that failed in some way.

**Comment by silviodonato** [comment]
> @silviodonato's comment in [#33059 (comment)](https://github.com/cms-sw/cmssw/issues/33059#issuecomment-789905943) also suggests a transient failure.
> 
> Could the script perhaps be modified to print out that the DAS query failed? (then it would be clear for everyone that such failure would be transient)

Yes, because I see the error appeared also in CMSSW_11_2_X_2021-03-03-1100 even without merging any PRs https://cmssdt.cern.ch/SDT/html/cmssdt-ib/#/ib/CMSSW_11_2_X

**Comment by mmusich** [comment]
actually I am already printing if the DAS query is unsuccessful here:

https://github.com/cms-sw/cmssw/blob/11c42d55511fb94f1ce81dbc8b3184988c10f3ef/CalibTracker/SiStripChannelGain/test/testSSTGain_PCL_FromRECO_cfg.py#L91-L93

I suppose now that I have other tests that depend on it I can make it exit with a status code 1 when there are no available files, but I am puzzled as to why the `print` message from python is not reported in the log. When I run locally with cmsRun the message **does** appear.
@makortel do you have suggestions?

**Comment by makortel** [comment]
@mmusich Good point. I don't have a good idea why the printout would not propagate to the unit test log. @smuzaffar would you?

**Comment by smuzaffar** [comment]
@mmusich @makortel this test is started under `FWCore/Utilities/interface/TestHelper.h` which might be eating up the output. I would suggest to change https://github.com/cms-sw/cmssw/blob/master/CalibTracker/SiStripChannelGain/test/BuildFile.xml#L2-L5 and directly run the testSSTGain_PCL_FromRECO.sh e.g
```
<test name="testSSTGainPCL_fromRECO" command="testSSTGain_PCL_FromRECO.sh"/>
```

in this case you might want to update `testSSTGain_PCL_FromRECO.sh` and replace `${LOCAL_TEST_DIR}` with $(dirname $0)`

**Comment by mmusich** [comment]
@smuzaffar thanks for the tip, but it didn't help :(
I come up with https://github.com/cms-sw/cmssw/pull/33065.
@silviodonato please let me know if that's enough for you.
