### ISSUE TITLE
Adjust DQM code for new ClassDef version in TF1 and TFormula 

### ISSUE THREAD

**Issue by mrodozov** [cms-sw/cmssw#33053]
In the latest ROOT commits the ClassDef for TF1 class moved from 10 to 12

https://github.com/root-project/root/blob/master/hist/hist/inc/TF1.h#L714 ROOT master
https://github.com/root-project/root/blob/v6-22-00-patches/hist/hist/inc/TF1.h#L708 ROOT 6-22
-> TFormula from 12 to 13:
https://github.com/root-project/root/blob/master/hist/hist/inc/TFormula.h#L262
https://github.com/root-project/root/blob/v6-22-00-patches/hist/hist/inc/TFormula.h#L254

and I understand adjustments in DQM code are needed because of it.
See also https://github.com/cms-sw/cmssw/pull/32890 (if you haven't already)
We are updating the ROOT external to get this changes:
https://github.com/cms-sw/cmsdist/pull/6696

**Comment by mrodozov** [comment]
assign dqm

**Comment by jfernan2** [comment]
Thanks a lot @mrodozov 
Please forgive my ignorance but, for TF1 you have already done the change in #32890 (thanks!) while for TFormula, I don't see any real use of TFormula in DQM Modules/Classes, except for this ECAL file:

https://github.com/cms-sw/cmssw/blob/ba6e8604a35283e39e89bc031766843d0afc3240/DQM/EcalMonitorDbModule/src/DBReaderWorkers.cc#L81-L82

But somehow in an external way since TFormula is not referenced in any case on:
https://github.com/cms-sw/cmssw/blob/a4d4a4152d8918b793134c4a2d55ec53d27d869f/DQMServices/Components/test/testSchemaEvolution.cpp

Are we safe in this matter? Thanks

**Comment by mrodozov** [comment]
Apart from the change in the test I was told this will affect the DQM GUI (IIRC) so I have to ping DQM people from before
That is the reason behind this issue

**Comment by mrodozov** [comment]
@smuzaffar raised the concern not to merge 32890 before asking DQM to adjust, so I'll ask him to clarify what he meant

**Comment by smuzaffar** [comment]
@jfernan2 , IIRC, the unit test add https://github.com/cms-sw/cmssw/pull/22653 was to check the ROOT `TH*` schema evolution. As with new root changes this unit test is failing https://cmssdt.cern.ch/SDT/cgi-bin/logreader/slc7_amd64_gcc900/CMSSW_11_3_ROOT6_X_2021-03-03-2300/unitTestLogs/DQMServices/Components#/62-62 , so we would like to ask you to look in to it and see if there are any changes needed for Online DQMGUI?  The change in https://github.com/cms-sw/cmssw/pull/32890/files just fixes the unit tests but I think you need to change if this is OK for DQMGUI

**Comment by jfernan2** [comment]
Thanks @smuzaffar  I am consulting with the core experts but my understanding of the situation is the following:

- Marcel introduced modifications to ensure the schema evolution test would catch problems for Online GUI too https://github.com/cms-sw/cmssw/pull/24354
- ROOT version is driven by root.spec file, so my question would be which CMSSW release we foresee is going to use this new ROOT version from cms-sw/cmsdist#6696 ?
- At present at P5 we are using CMSSW_11_2_X, I guess this would affect a future 11_3_X version, am I right? 
- I am not sure about the (OLD) Offline GUI, which triggered this intervention by cmsweb in the past: https://hypernews.cern.ch/HyperNews/CMS/get/cernCompAnnounce/1279.html
- You fixed (automatically) this : https://github.com/cms-sw/cmsdist/commit/86fd409bb45c740e73865376fce40a8edd055a81#diff-78d571a1c8e490b280fdf6fe28fd6e7cc3ad4da3ce56c891967838b7811bbd33
but for the NEW GUI only, as far as I understand, which is independent 

I am somehow confused because I don't see where we could change the ROOT version used for the OLD GUIs.... sorry

**Comment by davidlange6** [comment]
Indeed, perhaps the new method of building the dqm gui means that this unit test is now obsolete. That would be great.

**Comment by jfernan2** [comment]
OK, so we have identified the places to change for old and new GUI:

- new: https://github.com/cms-DQM/dqmgui/blob/master/scripts/cmssw_info and rebuild
- old:  https://github.com/cms-sw/cmsdist/blob/comp_gcc630/dqmgui.spec#L1   not sure what RPM version I should use here

Any advice is welcome. Thanks

**Comment by jfernan2** [comment]
@davidlange6  for the new GUI probably yes, since it will be linked to CMSSW version, but old GUI still has some time to live until we commision the new GUI

**Comment by smuzaffar** [comment]
@jfernan2 , new root (version 6.22 with update `TF*`) will go in to 11.3.0.pre5. If you need to deploy old DQM GUI with this updated version of root then I can update the https://github.com/cms-sw/cmsdist/blob/comp_gcc630/root.spec

So looks like we are fine to merge https://github.com/cms-sw/cmssw/pull/32890 for 11.3.X

**Comment by jfernan2** [comment]
Thanks @smuzaffar 
One extra question, again due to my ignorance (my apologies): if we switch to 11.3.0.pre5 at the GUI, would this be backward compatible?
Since at Online we must still run 11.2.X for MWGRs, I fear we should wait for this change in the GUIs

**Comment by smuzaffar** [comment]
with root schema evolution, yes it should be backward compatible  ..... right @davidlange6?

**Comment by davidlange6** [comment]
In root - sure. In protobuf, thats a dqm question.

**Comment by jfernan2** [comment]
@smuzaffar  so, we would like to move to this new ROOT version, can you please  update the https://github.com/cms-sw/cmsdist/blob/comp_gcc630/root.spec   ?

FYI: @ErnestaP

**Comment by smuzaffar** [comment]
The root in comp_gcc630 branch is build only for python2 and I am having difficulties to build the new root with only python 2 ( see  https://github.com/root-project/root/issues/7289#issuecomment-792758306 ). How do you use root in online dqmgui?  Do you use root's python interface? If yes then if I built it only for python3 then will this break onlune dqmgui?

**Comment by jfernan2** [comment]
I don't believe we use root's python interface at all, on the other hand the old GUI has in etc/makefile:
PYTHON_LIBS  = -lboost_python -lpython2.7

As far I know we use ROOT in the standard way, from makefile:
ROOTC_LIBS   = -lCore -lRIO -lNet -lHist -lMatrix -lThread -lTree -lMathCore
ROOTG_LIBS   = $(ROOTC_LIBS) -lTreePlayer -lGpad -lGraf3d -lGraf \
               -lPhysics -lPostscript -lASImage -ljpeg -lpng

Is there any explicit test that I could make to give you a more accurate answer?
Thanks

**Comment by smuzaffar** [comment]
dqmgui is not control/developed by us, so I have no idea. DQM team should have better knowledge of it :-)

**Comment by smuzaffar** [comment]
@jfernan2 , building root 6.22 from comp branch does not work as comp branch uses GCC 6.3.0 and root fails to build with it. Updating GCC version for comp branch will effect all comp services.

I can move dqmgui.spec in to cms branch ( IB/CMSSW_11_3_X/master) as dqmgui-old.spec and build and upload it to cms RPM repository. You might have to change the deployment procedure to get dqmgui-old from cms repo. Let  me know if that is reasonable?

**Comment by smuzaffar** [comment]
@jfernan2, an other issue with old dqmgui is that it does not build with newer boost (1.72) which we have in CMS branch. So including old dqmgui in cms branch also need your help ( the boost code it checksout https://github.com/cms-sw/cmsdist/blob/comp_gcc630/dqmgui.spec#L37 needs adjustments for new boost)

**Comment by andrius-k** [comment]
@smuzaffar, would it be possible to move the DQM GUI to a different comp branch that uses newer GCC so we can build ROOT 6.22?

> Updating GCC version for comp branch will effect all comp services.

Does this mean that if we do what I mentioned above, other things will break? If so, could we get a separate branch just for the DQM GUI?

**Comment by smuzaffar** [comment]
There is no comp branch with newer GCC. It is up to comp team to decide when they want to update their branches.
Having a different branch is not going to break comp services as they will not be using that branch. Again, its comp team who should decide how to maintain dqmgui in comp

**Comment by andrius-k** [comment]
@smuzaffar, so if we were to hand you an equivalent of this branch: https://github.com/cms-sw/cmsdist/blob/comp_gcc630/gcc.spec
just with the newer GCC version in it, could you try build a DQM GUI package for it? If so, what is the target GCC version? Not having Python 2 ROOT support should be fine - we will test this once we have the deployable package.

**Comment by smuzaffar** [comment]
add a new gcc and uploading to comp is not that straight forward. @amaltaro what do you suggest? we need to build dqmgui in comp branch with newer root which now does not build with gcc630 , so I guess we need gcc 9.3.0? How do you suggest what can be come in comp to build this?

**Comment by smuzaffar** [comment]
@andrius-k, if you are ok with different comp branch and architecture ( as gcc version is  part of architecture) then why not just build old dqmgui  for cms branch. every thing up to root (including gcc) is ready in cms branch. All you need is to provide dqmgui fixes for boost and update you deployment script to get dqmgui from a different reoisitory/architecture

**Comment by amaltaro** [comment]
Sorry if it has already been discussed, but at some point I understood that we would no longer need DQMGui to be maintained in the comp_gcc630 branch, and instead it would started to be built with the CMSSW releases (thus living in a different branch). Are you saying that we need to keep both versions available?

Bootstrapping and maintaining a new architecture isn't that simple, and we lack expertise on the comp side as well. I'm not sure I can suggest anything at the moment (in the end, this needs to be discussed with the HTTP group, who AFAIK are the official maintainers of all those specs).

**Comment by jfernan2** [comment]
hi @amaltaro 
I am sorry but the new DQM GUI being currently developed is built with CMSSW. However the old DQM GUI, which we should still mantain, is not.

**Comment by jfernan2** [comment]
> @andrius-k, if you are ok with different comp branch and architecture ( as gcc version is part of architecture) then why not just build old dqmgui for cms branch. every thing up to root (including gcc) is ready in cms branch. All you need is to provide dqmgui fixes for boost and update you deployment script to get dqmgui from a different reoisitory/architecture

@smuzaffar  would you be so kind to provide some instructions on how to build old dqmgui for cms branch so that we cna debug boost errors? I have tried to find out  myself but no success, sorry. Thank you very much

**Comment by smuzaffar** [comment]
@jfernan2 , here is how you can build old dqmgui with cms branch (use one of cmsdev machines)
```
bash
git clone git@github.com:cms-sw/cmsdist -b old-dqmgui
git clone git@github.com:cms-sw/pkgtools -b V00-33-XX
./pkgtools/cmsBuild --weekly -a slc7_amd64_gcc900 -i w -j 10 build dqmgui-old
cd w/BUILD/slc7_amd64_gcc900/cms/dqmgui-old/9.6.0
cat cmsdist-build.sh
```
and run all the commands starting from  
```
cd 'Monitoring'
```
up to 
```
python setup.py -v build_system -s DQM -d
```
just copy and paste those commands (from cmsdist-build.sh script)  on terminal. After this you should get the build error. Try to fix the error and only re-run last `python setup.py -v build_system -s DQM -d` to re-build

**Comment by jfernan2** [comment]
Thank you very much @smuzaffar !!
