### ISSUE TITLE
PFBlock slower by factor 2x in Phase II

### ISSUE THREAD

**Issue by jpata** [cms-sw/cmssw#33083]
PFBlockProducer CPU time goes up by factor 2x from 11_3_0_pre2 to 11_3_0_pre3 for the Phase II workflow:

- https://jpata.web.cern.ch/jpata/cgi-bin/igprof-navigator/releases/11_3_0_pre2/23434.21/step3/cpu/346
- https://jpata.web.cern.ch/jpata/cgi-bin/igprof-navigator/releases/11_3_0_pre3/23434.21/step3/cpu/232

Is this understood to arise from https://github.com/cms-sw/cmssw/pull/32766 ?

cc @hatakeyamak @bendavid

**Comment by jpata** [comment]
assign reconstruction

**Comment by hatakeyamak** [comment]
@jpata 
Thank you for the report. Good to know. I didn't profile when I made a PR, but this is probably expected. We made sure any track will enter pfTICL or PFBlockAlgo. I expect a decent number of more tracks now enter PFBlockAlgo due to generally tighter track seeding in TICL compared to simPF (so it means we pass more tracks to PFBlockAlgo and PFAlgo).

**Comment by slava77** [comment]
https://jpata.web.cern.ch/jpata/cgi-bin/igprof-navigator/releases/11_3_0_pre3/23434.21/step3/cpu/1003
<img width="688" alt="Screen Shot 2021-03-05 at 5 33 38 PM" src="https://user-images.githubusercontent.com/4676718/110190613-00d0ef00-7dd9-11eb-8aa5-12ec0c75489a.png">

(if the call path is to be believed) it's curious how a rather trivial bitwise operation takes up a rather significant fraction of 21% of all of the `PFBlockProducer` time.

in https://github.com/cms-sw/cmssw/blob/CMSSW_11_3_0_pre3/DataFormats/ParticleFlowReco/interface/PFBlockElementTrack.h#L28
```C++
    bool trackType(TrackType trType) const override { return (trackType_ >> trType) & 1; }

    bool isSecondary() const override {
      return trackType(T_FROM_DISP) || trackType(T_FROM_GAMMACONV) || trackType(T_FROM_V0);
    }

    bool isPrimary() const override { return trackType(T_TO_DISP); }

    bool isLinkedToDisplacedVertex() const override { return isSecondary() || isPrimary(); }

```
is it an example of too much virtuality? shouldn't this be instead directly implemented with one mask `&` operation?

**Comment by Dr15Jones** [comment]
Appropriate use of `final` could help. If isPrimary and isSecondary were marked final then isLinkedToDisplacedVertex could call them directly instead of through the virtual table.

**Comment by VinInn** [comment]
I suggest to mark "final" the class itself. Eventually make final all derived classes from PFBlockElement.

**Comment by VinInn** [comment]
I would change all those "or"s with a single mask.

**Comment by hatakeyamak** [comment]
Thank you. Some people are looking into this.

**Comment by jpata** [comment]
OK, thx, concluding that the slowdown is understood, recognized and coming from physics, so we can close this issue. Independently, opportunities for optimization are being addressed in https://github.com/cms-sw/cmssw/pull/33127.
