### ISSUE TITLE
PPS: update of era modifiers

### ISSUE THREAD

**Issue by jan-kaspar** [cms-sw/cmssw#33080]
We'd like to slightly update the era modifiers for (CT)PPS. Before doing so, we'd like to know your opinion.

Let me review our needs.
  1) We need a modifier to represent all eras where PPS was active - this is to turn on PPS code in various reco and simu sequences, e.g. here https://github.com/cms-sw/cmssw/blob/c98ca602f3886cbf736978afdc5623241c70be4f/Configuration/StandardSequences/python/RawToDigi_cff.py#L99
  2) We need per-year modifiers to adjust settings of reco and simu modules, e.g. here https://github.com/cms-sw/cmssw/blob/ba6e8604a35283e39e89bc031766843d0afc3240/RecoPPS/ProtonReconstruction/python/ctppsProtons_cff.py#L61

Up to now we have had `ctpps_2016` used in the sense 1), but `ctpps_2017` and `ctpps_2018` in sense 2). This was mostly for historical reasons and we find that it is the time to rectify the situation, for the following reasons.
  a) The current naming is heavily misleading and leads to mistakes, e.g. the logic combination here https://github.com/cms-sw/cmssw/blob/7170574d17c276aa5c257aca7f30bc721a4c6248/Geometry/VeryForwardGeometry/python/geometryRPFromDB_cfi.py#L19 should have covered all PPS Run2 eras, but undesirably it covers also Run3.
  b) There is no simple (and time invariant) logic combination that would represent Run2 PPS eras.

In consequence, we'd like to propose:
  i) to have `ctpps` modifier for the case 1)
  ii) to have `ctpps_20XY` modifiers for the case 2)
Would such a design make sense to you?

As far as we can see, such a modification would be transparent for the dominant use case when `Run2_20XY` are used.

We propose this change for master, no backports are considered.

**Comment by slava77** [comment]
I'm not sure how the proposal would resolve 2a or 2b.
Which part needs to be removed/not applied in Run3?
It sounds like you may need a `pps_run3`  modifier.

**Comment by makortel** [comment]
assign reconstruction, simulation, operations

(not really sure who else to add)

**Comment by jan-kaspar** [comment]
Now:
 * `ctpps_2016` is activated for all eras where PPS contributed
 * therefore `ctpps_2016` is also activated for Run3 - confusing (at least)

With the proposal:
 * `ctpps_2016` would be only activated for 2016 data
 * therefore `ctpps_2016 | ctpps_2017 | ctpps_2018` refers truly only for Run2, as expected

We need to remove `ctpps_2016` from all but 2016 modifier chains.

**Comment by slava77** [comment]
+reconstruction

via #33415

**Comment by jan-kaspar** [comment]
This change was finally included in #33415 - closing this issue.
