### ISSUE TITLE
Use modifier phase2_etlv4 for any scenario using MTD I12 or I13

### ISSUE THREAD

**Issue by fabiocos** [cms-sw/cmssw#33130]
The validation of scenario D76 by @gsorrentino18 shows a dramatic drop in efficiency of ETL, incompatible with the previous validation of D73. I independently noticed that only a very small number of tracks has ETL hits associated in D76.

One possible source of the problem is the lack of https://github.com/cms-sw/cmssw/blob/master/Configuration/Eras/python/Modifier_phase2_etlV4_cff.py in the definition of the Eras used for newest scenarios, based on MTD I13, as it was done in https://github.com/cms-sw/cmssw/blob/master/Configuration/Eras/python/Era_Phase2C11_etlV4_cff.py . This should be fixed asap, @gsorrentino18 is verifying whether such a fix is enough to recover the previously observed situation. 

Ideally it would be simpler to embed this in the Phase2C11 era, but this is still used also for some scenarios using MTD I11 (D64 till D71). These scenarios should not be taken seriously as far as ETL is concerned, but still if they are required to be functional an "_etlv4" version of the Eras should be provided and used.

@parbol FYI

**Comment by fabiocos** [comment]
@srimanob @bsunanda FYI

**Comment by makortel** [comment]
assign upgrade

(not sure who else)

**Comment by srimanob** [comment]
Thanks for the report @fabiocos @gsorrentino18 
Could you please fill the ValDB, so that PdmV keeps the record of what fails, https://cms-pdmv.cern.ch/valdb/?srch=11_3_0_pre3&selected=11_3_0_pre3_phase2_D76&Reconstruction=true&RFull=true

**Comment by gsorrentino18** [comment]
The following plots (Track efficiency as a function of pT for ETL negative side) have been obtained with 150 TTbar events in the D73 (blue) and D76 (red) scenarios.
On the left, the discrepancy observed while validating the new D76 scenario.
On the right, the proper threshold, calibration constant and MeVtoMIP conversion values are used (those implemented in the missing modifier pointed by Fabio). 
The lack of such modifier in the new Era appears to be the main issue.
<img width="794" alt="Schermata 2021-03-10 alle 19 11 36" src="https://user-images.githubusercontent.com/39314729/110676614-71f71480-81d4-11eb-869c-ac48a5d2cfac.png">

**Comment by fabiocos** [comment]
Issue solved by #33139
