### ISSUE TITLE
Compile cmssw in an ubuntu container without CVMFS ?

### ISSUE THREAD

**Issue by chunyulin** [cms-sw/cmssw#33156]
Is there any updated doc on the general / detail steps ? As installing CVMFS inside a container need the  prevelidge docker, which is almost unlikely for standard container service provided by some institue. Thanks.

**Comment by smuzaffar** [comment]
@chunyulin , ubuntu is not a support CMS architecture and there is no simple way to compile cmssw under it. You need to build the full software stack (starting from gcc and all the externals) for ubuntu in order to build cmssw.

**Comment by chunyulin** [comment]
Thanks @smuzaffar for reply. Could you give me a rough idea, or any links, that I can at least try to install scram and build a minimal cmsRun? I searched on twiki but found no related materials. My intention is to test on the ubuntu GPU container of HPC center, which is hard to adapt to cms's enviorment in a short time due to heavy policy constrain.

**Comment by smuzaffar** [comment]
why not run cms cc7 docker container and install cmssw release inside it? That will be much simpler to run cmssw . In order to do that you can start cmssw/cc7:amd64 ( or cmssw/cc8:amd64) docker container and mount a local directory e.g. -v /build:/build and once insde the container then you can do
```
cd /build
wget http://cmsrep.cern.ch/cmssw/bootstrap.sh
sh ./bootstrap.sh -a slc7_amd64_gcc900 setup
./common/cmspkg -a slc7_amd64_gcc900 install cms+cmssw+CMSSW_11_3_0_pre4
```

**Comment by chunyulin** [comment]
You are right. However, in my scenario, we try to run cmssw, HeterogeneousCore/SonicTriton specifically, in a pre-built, standard, unprivileged tensorRT container service. That means we cannot config CVMFS nor run another container inside, due to the strict policy of our HPC center. So, I naively thought if I could have a scram/cmssw compiled from scratch, maybe I can then utilize my HPC resource for HEP workload.

**Comment by kpedro88** [comment]
@chunyulin I'd like to learn more about the use case and restrictions at your HPC center. Can you run two separate containers (one for CMSSW and one for the Triton server) side-by-side and communicate between them using e.g. docker network?

There are non-cvmfs-based CMSSW container images at https://hub.docker.com/u/cmsopendata and https://gitlab.cern.ch/cms-cloud/cmssw-docker/container_registry, though they are very large, and we might have to request a newer one to use the latest version of SonicTriton.

**Comment by makortel** [comment]
assign core

**Comment by chunyulin** [comment]
Thank @kpedro88, we can, now I get what you mean: SonicTriton can be run in a separate container from Triton server, and I can try to ask our HPC admin to install base containers to install cmssw as @smuzaffar's tips.
