### ISSUE TITLE
Possible threading issue in context information in MessageLogger message decorations

### ISSUE THREAD

**Issue by makortel** [cms-sw/cmssw#33224]
While running some job with different numbers of threads and streams I noticed that the context part in the decoration of one message changed between different runts. With 8 threads and streams I saw
```
%MSG-e TkDetLayers:  PostStreamBeginLumi 19-Mar-2021 07:42:25 PDT  PostStreamBeginLumi
```
but with 8 threads and 1 stream I occasionally saw
```
%MSG-e TkDetLayers:  AfterModStreamBeginLumi 19-Mar-2021 08:05:15 PDT  Run: 1 Event: 1^@tream: 0
```
The message itself was the same in both cases, only the context was different. All preceding printouts were done via MessageLogger, there was a later printout made with `std::cout`.

Summarizing a chat with @Dr15Jones, it could be that the context part gets shared because of not being copied in time. The context is "per thread", so maybe the thread that made the message is different from the thread that writes it.

**Comment by makortel** [comment]
assign core

**Comment by dan131riley** [comment]
> Summarizing a chat with @Dr15Jones, it could be that the context part gets shared because of not being copied in time. The context is "per thread", so maybe the thread that made the message is different from the thread that writes it.

The `messagedrop::StringProducer` variants all store pointers to parts of the context, so we may be violating some ordering assumption about the lifetime of those pointers.

**Comment by makortel** [comment]
Fixed in https://github.com/cms-sw/cmssw/pull/36801

**Comment by makortel** [comment]
+1
