### ISSUE TITLE
11_2_X IB test:  No "EcalMustacheSCParametersRcd" record found in the EventSetup.n  

### ISSUE THREAD

**Issue by qliphy** [cms-sw/cmssw#33237]
After the merging of   
      #33184 from thomreis: Remove ESProducers for ECAL Mustache parameters from configuration - 11_2_X
11_2_X IB test shows several issues as reported in the title.
e.g.
https://cmssdt.cern.ch/SDT/cgi-bin/logreader/slc7_amd64_gcc900/CMSSW_11_2_X_2021-03-20-1100/pyRelValMatrixLogs/run/50200.0_ZEE_13+ZEE_13INPUT+DIGIUP15_PU50+RECOUP15_PU50_L1TEgDQM+HARVESTUP15_PU50_L1TEgDQM/step3_ZEE_13+ZEE_13INPUT+DIGIUP15_PU50+RECOUP15_PU50_L1TEgDQM+HARVESTUP15_PU50_L1TEgDQM.log#/

@francescobrivio @thomreis
Could it be that in #33011 that GT for run2_mc_50ns was not updated?
In #32959 it was instead updated from 113X_mcRun2_startup_v1 to 113X_mcRun2_startup_v2

**Comment by qliphy** [comment]
assign alca

**Comment by francescobrivio** [comment]
I run a quick test (`runTheMatrix.py -l 50200.0 --ibeos`) using a newly created GT candidate for run2_mc_50ns that includes the Ecal supercluster parameters (`112X_mcRun2_startup_Candidate_2021_03_21_10_06_16`) and everything works fine. We'll discuss this and eventually provide a fix PR.

**Comment by francescobrivio** [comment]
After #33239 was merged the 11_2_X IB tests are successful.
I think this issue can be closed.

**Comment by francescobrivio** [comment]
+alca
