### ISSUE TITLE
Under Sim4Core/CustomPhysics change the dark photon mass and dark photon PDGParser

### ISSUE THREAD

**Issue by y19y19** [cms-sw/cmssw#33249]
Hi,

I am planning to generate some dark photon signal samples for my analysis's purpose. I talked to EXO group's MC conveners, and they recommended that I raise an issue here, to get my customized code into official CMSSW, such that it can be used to run a central production for my signal samples. The code that I want to modify is very simple, they are already in CMSSW but I would like to change the parameter:

1) Change the line into 
      1023   5e-4                 # darkphoton
https://github.com/cms-sw/cmssw/blob/7b4b41dbd1989c3890c12cc00ee1d6455188b2bc/SimG4Core/CustomPhysics/data/particle_darkphoton.txt#L3

2) Change the line into 
  return (pdgAbs == 1023);
https://github.com/cms-sw/cmssw/blob/7b4b41dbd1989c3890c12cc00ee1d6455188b2bc/SimG4Core/CustomPhysics/src/CustomPDGParser.cc#L42

The changes are made because I am generating dark photon from a different model, so the pdg id from the model labeled the dark photon as 1023, and also we want to modify the mass of dark photon to be 0.5 MeV.

In addition, there are some code about the customization of the SIM process, it could be put under Sim4Core/CustomPhysics/python, with the following code about hits customization. However, I realized that it can be moved to the GENSIM step's config file (please correct me if you think it is not true), so adding it to CMSSW might be not necessary. Please let me know how you think about it.

def addSimHits(process):
    if hasattr(process,'g4SimHits'):
        # defined watches
        process.g4SimHits.Physics = cms.PSet(
            process.customPhysicsSetup,
            G4BremsstrahlungThreshold = cms.double(0.5), ## cut in GeV
            DefaultCutValue = cms.double(1.), ## cuts in cm,default 1cm
            CutsPerRegion = cms.bool(True),
            type = cms.string('SimG4Core/Physics/CustomPhysics'),
            GflashEcal = cms.bool(False),
            GflashHcal = cms.bool(False),
            RusRoElectronEnergyLimit  = cms.double(0.0),
            ElectronStepLimit         = cms.bool(False),
            ElectronRangeTest         = cms.bool(False),
            PositronStepLimit         = cms.bool(False),
            FlagFluo    = cms.bool(False),
            TrackingCut = cms.bool(False),
            MaxTrackTime  = cms.double(500.0),
            MaxTrackTimes = cms.vdouble(2000.0),
            rhadronPhysics = cms.bool(True),
            GflashEcalHad = cms.bool(False),
            GflashHcalHad = cms.bool(False),
            ModifyTransportation = cms.bool(False),
            ThresholdWarningEnergy    = cms.untracked.double(100.0),
            ThresholdImportantEnergy  = cms.untracked.double(250.0),
            ThresholdTrials           = cms.untracked.int32(10),
        )    
        process.g4SimHits.G4Commands = cms.vstring('/tracking/verbose 0')

Thank you.
Yao

**Comment by makortel** [comment]
assign simulation

**Comment by y19y19** [comment]
Hi, I didn't hear any feedback on this fo over a week. Anyone can comment on it? If you think there is a way to implement the same thing without changing the cmssw code, please let me know. I hope it can be done asap to make a request to central production. Thanks.

**Comment by civanch** [comment]
@y19y19 , please, try out #33334 . What is unclear your request - why you want to modify g4SimHits parameters unrelated to you analysis?

**Comment by y19y19** [comment]
Sorry for the late reply. In my analysis, the signal dark photon is simulated in a way that it can interact with detector material through pair production (similar to SM photon bremstrahlung, but the cross section is scaled to be smaller, based on a variable called dark factor). It will be like a delayed pair production shower of photon.

For g4SimHits part, to be honest, it is the code from previous grad student, and I am not sure about most of the parameters. It looks like that it is setting threshold on the hits that is caused by the dark photon interacting with the material, and thus have the parameter like G4BremsstrahlungThreshold = 0.5 GeV. If you think this part is unnecessary, please let me know. We could discuss.

And thank you for committing the new type dark photon into CMSSW.

**Comment by y19y19** [comment]
Hi @civanch  I haven't heard back for a while. The part that adds SimHits, I did a test that simulates the dark photons without SimHits part, and end up with not finding dark photon showers in the detector. I believe this part is necessary to customize the dark photon shower. Please correct me if you don't think it is the case. I am not an expert in Sim4Core, so I could misunderstand something. I attach the code in this comment. We would also like to add a list of functions defining the various dark factors that we will be using in the central production for our signals.


#############################################
import FWCore.ParameterSet.Config as cms

def addSimHits(process):
    if hasattr(process,'g4SimHits'):
        # defined watches
        process.g4SimHits.Physics = cms.PSet(
            process.customPhysicsSetup,
            G4BremsstrahlungThreshold = cms.double(0.5), ## cut in GeV
            DefaultCutValue = cms.double(1.), ## cuts in cm,default 1cm
            CutsPerRegion = cms.bool(True),
            type = cms.string('SimG4Core/Physics/CustomPhysics'),
            GflashEcal = cms.bool(False),
            GflashHcal = cms.bool(False),
            RusRoElectronEnergyLimit  = cms.double(0.0),
            ElectronStepLimit         = cms.bool(False),
            ElectronRangeTest         = cms.bool(False),
            PositronStepLimit         = cms.bool(False),
            FlagFluo    = cms.bool(False),
            TrackingCut = cms.bool(False),
            MaxTrackTime  = cms.double(500.0),
            MaxTrackTimes = cms.vdouble(2000.0),
            rhadronPhysics = cms.bool(True),
            GflashEcalHad = cms.bool(False),
            GflashHcalHad = cms.bool(False),
            ModifyTransportation = cms.bool(False),
            ThresholdWarningEnergy    = cms.untracked.double(100.0),
            ThresholdImportantEnergy  = cms.untracked.double(250.0),
            ThresholdTrials           = cms.untracked.int32(10),
        )       
        process.g4SimHits.G4Commands = cms.vstring('/tracking/verbose 0')

def customiseDarkPhotonSIM_0p100(process):
    process.customPhysicsSetup = cms.PSet(
        particlesDef    = cms.FileInPath('SimG4Core/CustomPhysics/data/particle_darkphoton.txt'),
        dark_factor     = cms.double(0.1)
        )
    addSimHits(process)
    return (process)

def customiseDarkPhotonSIM_0p063(process):
    process.customPhysicsSetup = cms.PSet(
        particlesDef    = cms.FileInPath('SimG4Core/CustomPhysics/data/particle_darkphoton.txt'),
        dark_factor     = cms.double(0.063)
        )
    addSimHits(process)
    return (process)

def customiseDarkPhotonSIM_0p040(process):
    process.customPhysicsSetup = cms.PSet(
        particlesDef    = cms.FileInPath('SimG4Core/CustomPhysics/data/particle_darkphoton.txt'),
        dark_factor     = cms.double(0.040)
        )
    addSimHits(process)
    return (process)

def customiseDarkPhotonSIM_0p025(process):
    process.customPhysicsSetup = cms.PSet(
        particlesDef    = cms.FileInPath('SimG4Core/CustomPhysics/data/particle_darkphoton.txt'),
        dark_factor     = cms.double(0.025)
        )
    addSimHits(process)
    return (process)

def customiseDarkPhotonSIM_0p016(process):
    process.customPhysicsSetup = cms.PSet(
        particlesDef    = cms.FileInPath('SimG4Core/CustomPhysics/data/particle_darkphoton.txt'),
        dark_factor     = cms.double(0.016)
        )
    addSimHits(process)
    return (process)

def customiseDarkPhotonSIM_0p010(process):
    process.customPhysicsSetup = cms.PSet(
         particlesDef   = cms.FileInPath('SimG4Core/CustomPhysics/data/particle_darkphoton.txt'),
         dark_factor    = cms.double(0.01)
         )   
    addSimHits(process)
    return (process)

def customiseDarkPhotonSIM_0p0063(process):
    process.customPhysicsSetup = cms.PSet(
        particlesDef    = cms.FileInPath('SimG4Core/CustomPhysics/data/particle_darkphoton.txt'),
        dark_factor     = cms.double(0.0063)
        )
    addSimHits(process)
    return (process)

def customiseDarkPhotonSIM_0p0040(process):
    process.customPhysicsSetup = cms.PSet(
        particlesDef    = cms.FileInPath('SimG4Core/CustomPhysics/data/particle_darkphoton.txt'),
        dark_factor     = cms.double(0.0040)
        )
    addSimHits(process)
    return (process)

def customiseDarkPhotonSIM_0p0025(process):
    process.customPhysicsSetup = cms.PSet(
        particlesDef    = cms.FileInPath('SimG4Core/CustomPhysics/data/particle_darkphoton.txt'),
        dark_factor     = cms.double(0.0025)
        )
    addSimHits(process)
    return (process)

def customiseDarkPhotonSIM_0p0016(process):
    process.customPhysicsSetup = cms.PSet(
        particlesDef    = cms.FileInPath('SimG4Core/CustomPhysics/data/particle_darkphoton.txt'),
        dark_factor     = cms.double(0.0016)
        )
    addSimHits(process)
    return (process)

def customiseDarkPhotonSIM_0p0010(process):
    process.customPhysicsSetup = cms.PSet(
        particlesDef    = cms.FileInPath('SimG4Core/CustomPhysics/data/particle_darkphoton.txt'),
        dark_factor     = cms.double(0.001)
        )
    addSimHits(process)
    return (process)

**Comment by civanch** [comment]
+1

#33249 and #33973 are merged
