### ISSUE TITLE
Build issues for sandybridge builds

### ISSUE THREAD

**Issue by smuzaffar** [cms-sw/cmssw#33267]
@VinInn , last night I tried to build `CMSSW_11_3_SKYLAKEAVX512_X` IB with multiple instruction set ( `haswell, sandybridge and skylake-avx512`). All worked fine for `haswell` and `skylake-avx512` but for  `sandybridge` we get this build error in `TrackingTools/AnalyticalJacobians` [a]. Any idea how to avoid such issue, note that it fails when scram use `-march=sandybridge`

[a] 
https://github.com/cms-sw/cmssw/blob/master/TrackingTools/AnalyticalJacobians/src/AnalyticalCurvilinearJacobian.cc#L48
https://cmssdt.cern.ch/SDT/cgi-bin/buildlogs/slc7_amd64_gcc900/CMSSW_11_3_SKYLAKEAVX512_X_2021-03-24-1100/TrackingTools/AnalyticalJacobians
```
>> Compiling sandybridge TrackingTools/AnalyticalJacobians/src/JacobianLocalToCurvilinear.cc
In file included from gcc/9.3.0/lib/gcc/x86_64-unknown-linux-gnu/9.3.0/include/immintrin.h:53,
                 from gcc/9.3.0/lib/gcc/x86_64-unknown-linux-gnu/9.3.0/include/x86intrin.h:32,
                 from src/DataFormats/Math/interface/SSEVec.h:7,
                 from src/DataFormats/Math/interface/SIMDVec.h:57,
                 from src/DataFormats/GeometryVector/interface/Basic3DVector.h:4,
                 from src/DataFormats/GeometryVector/interface/PV3DBase.h:4,
                 from src/DataFormats/GeometryVector/interface/Point3DBase.h:5,
                 from src/DataFormats/GeometryVector/interface/GlobalPoint.h:5,
                 from src/TrackingTools/AnalyticalJacobians/interface/AnalyticalCurvilinearJacobian.h:5,
                 from src/TrackingTools/AnalyticalJacobians/src/AnalyticalCurvilinearJacobian.cc:1:
gcc/9.3.0/lib/gcc/x86_64-unknown-linux-gnu/9.3.0/include/avx2intrin.h: In function '__m256d mathSSE::_mm256_cross_pd(__m256d, __m256d)':
  gcc/9.3.0/lib/gcc/x86_64-unknown-linux-gnu/9.3.0/include/avx2intrin.h:913:1: error: inlining failed in call to always_inline '__m256i _mm256_xor_si256(__m256i, __m256i)': target specific option mismatch
   913 | _mm256_xor_si256 (__m256i __A, __m256i __B)
      | ^~~~~~~~~~~~~~~~
In file included from src/DataFormats/Math/interface/SIMDVec.h:57,
                 from src/DataFormats/GeometryVector/interface/Basic3DVector.h:4,
                 from src/DataFormats/GeometryVector/interface/PV3DBase.h:4,
                 from src/DataFormats/GeometryVector/interface/Point3DBase.h:5,
                 from src/DataFormats/GeometryVector/interface/GlobalPoint.h:5,
                 from src/TrackingTools/AnalyticalJacobians/interface/AnalyticalCurvilinearJacobian.h:5,
                 from src/TrackingTools/AnalyticalJacobians/src/AnalyticalCurvilinearJacobian.cc:1:
src/DataFormats/Math/interface/SSEVec.h:92:36: note: called from here
   92 |     return __m256d(_mm256_xor_si256(__m256i(ret), neg));

```

**Comment by VinInn** [comment]
sandybridge is AVX only. I am almost sure those cose whose written at that time, but apparently not.
One quick solution is to enable it only for AVX2 (or simplu disabled "tout-court": most probably make more damage than good.

**Comment by VinInn** [comment]
just "remove" the AVX part in
https://github.com/cms-sw/cmssw/blob/master/TrackingTools/AnalyticalJacobians/src/AnalyticalCurvilinearJacobianSSE.icc#L53

**Comment by VinInn** [comment]
no clue what "target specific option mismatch" means

**Comment by VinInn** [comment]
apparently ``` _mm256_xor_si256``` is AVX2 only. SO the code was written for haswell and never tested on older machines.

**Comment by smuzaffar** [comment]
thanks @VinInn for quick reply. If it is only tested for avx2 then shouldn't we change https://github.com/cms-sw/cmssw/blob/master/DataFormats/Math/interface/SSEVec.h#L9 to be `__AVX2__`
```
--- a/DataFormats/Math/interface/SSEVec.h
+++ b/DataFormats/Math/interface/SSEVec.h
@@ -6,9 +6,9 @@
 #if defined(__GNUC__)
 #include <x86intrin.h>
 #define CMS_USE_SSE
-#ifdef __AVX__
+#ifdef __AVX2__
 #define CMS_USE_AVX
-#endif /* __AVX__ */
+#endif /* __AVX2__ */
 #endif /* defined(__GNUC__) */
 #endif /* !defined(__arm__) && !defined(__aarch64__) && !defined(__MIC__) */

```

**Comment by VinInn** [comment]
I think is ok to change to AVX2. There are ways to make it compatible to AVX. I do not think it is worth the effort.

**Comment by smuzaffar** [comment]
I have opened https://github.com/cms-sw/cmssw/pull/33268 proposes to use CMS_USE_AVX2 when build for __AVX2__
