### ISSUE TITLE
DetectorDescription/Schema data files duplication

### ISSUE THREAD

**Issue by smuzaffar** [cms-sw/cmssw#33312]
Hi,
  We have duplicate data files for https://github.com/cms-sw/cmssw/tree/master/DetectorDescription/Schema . These files are abvailable vis cmssw/src and cms-data.  @ianna , do you know if we are using these data files?

 Data files from `cmssw/src` are picked for  IB, releases and cmssw PR tests. But for external PR tests ( e.g. cmsdist, cms-data etc.) these files are picked up from cms-data area.

I would suggest to move the cmssw/src/DetectorDescription/Schema/data to cms-data/DetectorDescription-Schema repository.
Any objections @ianna?

**Comment by cvuosalo** [comment]
@smuzaffar These files are for the old DD. I will check into them when I have the chance.

**Comment by civanch** [comment]
@cvuosalo , may be a correct fix would be do as @smuzaffar propose: move files in the same place. I do not think it is easy to remove old files if they are used for Run-1 and Run-2, at least, will require extra efforts.

**Comment by ianna** [comment]
@smuzaffar - we do not use schema for DDD. I think the ones in CMSSW can be safely removed.

**Comment by smuzaffar** [comment]
thanks @ianna , can you please open a PR with the change ?

**Comment by smuzaffar** [comment]
see https://github.com/cms-sw/cmssw/pull/34087
