### ISSUE TITLE
GeneratorInterface/EvtGenInterface data files duplication

### ISSUE THREAD

**Issue by smuzaffar** [cms-sw/cmssw#33313]
One file GeneratorInterface/EvtGenInterface/data/evt.pdl is available via both 
- https://github.com/cms-data/GeneratorInterface-EvtGenInterface
- https://github.com/cms-sw/cmssw/tree/master/GeneratorInterface/EvtGenInterface/data

and both have different contents. This causes problem when testing `cmsdist` , `cms-data` or other external PRs as in that case the cms-data path comes first and data files are picked up from cms-data area. For IB, releases and cmssw only PRs we read this from cmssw/src area. 

Looks like the cmssw data file is newer ( https://github.com/cms-sw/cmssw/blob/master/GeneratorInterface/EvtGenInterface/data/evt.pdl  4 months old). O would suggest to move all of https://github.com/cms-sw/cmssw/blob/master/GeneratorInterface/EvtGenInterface/data in to cms-data/GeneratorInterface-EvtGenInterface and delete them from cmssw.

**Comment by smuzaffar** [comment]
assign generators

**Comment by alberto-sanchez** [comment]
I will take care of this later today. I will clean that directory inside cmssw.

**Comment by alberto-sanchez** [comment]
The corresponding PRs have been created

**Comment by smuzaffar** [comment]
thanks a lot @alberto-sanchez for these PRs

**Comment by agrohsje** [comment]
+generators
