### ISSUE TITLE
Mix use of DD4hep and DD4Hep across CMSSW.

### ISSUE THREAD

**Issue by srimanob** [cms-sw/cmssw#33373]
Seem there are a mixing of "DD4hep" and "DD4Hep" across CMSSW code. It looks like "DD4hep" is the right one to use.

Examples of "DD4Hep":
Geometry/DTGeometryBuilder/src/DTGeometryBuilderFromDD4Hep.cc
Geometry/DTGeometryBuilder/src/DTGeometryBuilderFromDD4Hep.h
MagneticField/Engine/test/regression.py
MagneticField/Engine/test/runTest.sh
SimG4Core/PrintGeomInfo/test/SimFileCompare.cpp
Geometry/RPCGeometryBuilder/src/RPCGeometryParsFromDD.cc
Geometry/EcalCommonData/plugins/EcalSimParametersESModule.cc
...

It does not affect anything, just something not the same across CMSSW. Should I try to migrate all of them to be the same?

**Comment by makortel** [comment]
assign geometry, simulation, reconstruction

**Comment by cvuosalo** [comment]
There are about 100 files with `DD4Hep` instead of `DD4hep`. It would be a fair amount of work to change them all while being sure not to make any mistakes or typos. I'm not sure it is worth the effort.

**Comment by civanch** [comment]
@cvuosalo , how many files start from DD4hep? If more than 10-20 then we cannot fix this.

**Comment by ianna** [comment]
@cvuosalo - IMHO, it would be nice to have identical spelling in all Python configurations. https://cmssdt.cern.ch/lxr/search?%21v=CMSSW_12_2_X_2021-11-04-2300&_filestring=py&_string=fromDD4Hep

It is odd that two geometry producers use different syntax in the same fragment:
https://cmssdt.cern.ch/lxr/source/Alignment/MuonAlignment/test/convertSQLitetoXML_cfg.py#0028

**Comment by srimanob** [comment]
Hi @ianna @cvuosalo @civanch 

Thanks for following up. I agree with @ianna, at least the configuration should be the same. I propose to keep this issue open. I can help with fixing PR.

**Comment by civanch** [comment]
I agree. Also it is possible adiabatically change the situation:

1) better to have correct names in plugins
2) If a class is used only inside its sub-package it is quite easy  make a change, when a this sub-package is changed for another reason.

**Comment by ianna** [comment]
this should be fixed in https://github.com/cms-sw/cmssw/pull/36003

**Comment by srimanob** [comment]
Thanks very much @ianna

**Comment by ianna** [comment]
> this should be fixed in #36004 and #36003

and the final cleanup is done in https://github.com/cms-sw/cmssw/pull/36021

**Comment by ianna** [comment]
@srimanob - please, check if the issue can be closed. Thanks!

**Comment by srimanob** [comment]
Thanks @ianna I think this issue can be closed.
@cms-sw/geometry-l2 @cms-sw/simulation-l2 @cms-sw/reconstruction-l2 Could you please consider, and sign? Or please comment if something else remains.

**Comment by cvuosalo** [comment]
+1

**Comment by civanch** [comment]
+1

**Comment by jpata** [comment]
+reconstruction
 -`git grep DD4Hep` gives only one hit, in Validation/HGCalValidation
