### ISSUE TITLE
update GCC to 10.3.0

### ISSUE THREAD

**Issue by fwyzard** [cms-sw/cmssw#33377]
The GNU Compiler Collection version 10.3 has been released.

Can we update our gcc10 builds ?

**Comment by fwyzard** [comment]
assign core

**Comment by smuzaffar** [comment]
sure, I will open a cmsdist PR to test it

**Comment by makortel** [comment]
If the update goes well, should we consider physics validation of 10.3 already in 12_0_0_pre1? (the plan was make move production architecture to 10 in 12_0_X after the next point release)

**Comment by smuzaffar** [comment]
+core
this has been done via  cms-sw/cmsdist#6799
