### ISSUE TITLE
stuck track G4 exception in EEiEnvScr

### ISSUE THREAD

**Issue by slava77** [cms-sw/cmssw#33396]
I'm getting an exception in 11_3_0_pre5 with the following message

```
-------- EEEE ------- G4Exception-START -------- EEEE -------
*** G4Exception : GeomNav0003
      issued by : G4Navigator::ComputeStep()
Stuck Track: potential geometry or navigation problem.
  Track stuck, not moving for 25 steps.
  Current  phys volume: 'EEiEnvScr'
   - at position : (312.5813231326204,-63.67036776843077,-3180.483673258103)
     in direction: (-0.7788276664646271,-0.1751206899794004,0.6022957827267282)
    (local position: (312.5813231326235,63.67036776843275,-189.5163267418966))
    (local direction: (-0.7788276664646278,0.1751206899794005,-0.6022957827267291)).
  Previous phys volume: 'EEFrontQuad'

  Likely geometry overlap - else navigation problem !
 Track *abandoned* due to excessive number of Zero steps. Event aborted.
```

I'm not sure how to point to a specific event quickly, I run (on AMD) wf 11640 in 16 threads for 100K events and the crash appears after 80K events processed.
If it's an actual overlap, I guess there is a way to figure out the issue from the volume names and the state vector details in the error message.

**Comment by slava77** [comment]
assign geometry,simulation

**Comment by civanch** [comment]
@slava77 , thanks for the report. It is really difficult rare geometry problem. It may be not only overlap but also difficult geometry shape.

**Comment by ianna** [comment]
This `312.5813231326204` makes me believe that the PR https://github.com/cms-sw/cmssw/pull/33390 submitted by @bsunanda will cure the problem. It addresses the area marked in blue with current `Z = 312.5` changing it to `Z = 312.6`:
https://user-images.githubusercontent.com/1390682/113713457-a8e31c00-96e7-11eb-8936-cad7a9da0927.png
