### ISSUE TITLE
Do we still need to support the muon reco duplicate mitigation in PhysicsTools/PatUtils?

### ISSUE THREAD

**Issue by perrotta** [cms-sw/cmssw#33406]
While [reviewing](https://github.com/cms-sw/cmssw/pull/33307#pullrequestreview-626854855) PR #33307 it was evident that we keep spending time and effort in maintaining some code which is quite likely not needed any more in CMSSW:
- PhysicsTools/PatUtils/python/tools/muonRecoMitigation.py assumes the existence of a `PFCandPtrProjector` plugin, which is not found anywhere in CMSSW, not even in 9_1_X (which is the release where this config was introduced with #18165)
- That muon reco duplicate mitigation is only required by `corMETFromMuonAndEG`, which is defined in PhysicsTools/​PatUtils/​python/​tools/​corMETFromMuonAndEG.py and only called by PhysicsTools/PatAlgos/python/slimming/extraSlimmedMETs_MuEGFixMoriond2017.py,;which according to the name is quite likely not in use any more
- Moreover, `muCorrection=False` in there, and therefore this `muonRecoMitigation` wasn't actually ever accessed even from there.

The main point is the following:  do we still need to support the muon reco duplicate mitigation in `corMETFromMuonAndEG`? Do we need to keep supporting  `corMETFromMuonAndEG` at all? Couldn't they be safely removed from the release?

@zdemirag @kirschen @lathomas @ahinzmann @mariadalfonso

**Comment by perrotta** [comment]
assign xpog, reconstruction

**Comment by jpata** [comment]
bringing this up with @michaelwassmer, the current MET reco contact.

**Comment by jpata** [comment]
type jetmet

**Comment by michaelwassmer** [comment]
To my best knowledge, this isn't used anymore. Also, the corresponding MET filters https://github.com/cms-sw/cmssw/blob/master/RecoMET/METFilters/python/badGlobalMuonTaggersAOD_cff.py and https://github.com/cms-sw/cmssw/blob/master/RecoMET/METFilters/python/badGlobalMuonTaggersMiniAOD_cff.py seem not to be recommended anymore, see https://twiki.cern.ch/twiki/bin/viewauth/CMS/MissingETOptionalFiltersRun2.

**Comment by jpata** [comment]
Right, these can't be used because they are relying on old, removed code. Likely the best solution would be to remove these modules.

**Comment by michaelwassmer** [comment]
@vlimant 
I'm not sure I understand what the issue is. Could you explain?

**Comment by vlimant** [comment]
I don't know much more than what the PR description says https://github.com/cms-sw/cmssw/issues/33406#issue-855779681
looks like there are some python configuration files configuring modules that do not exist anymore ?

**Comment by vlimant** [comment]
there is essentially some cleanup to be done from within https://github.com/cms-sw/cmssw/blob/master/PhysicsTools/PatUtils/python/tools/corMETFromMuonAndEG.py to ever have the chance at calling `PFCandPtrProjector` which does not exists.

Is that something you could make a 13.0 PR for @michaelwassmer ? it might be a good occasion to review and streamline what this functions are doing. that looks very unnaturally complicated to me

**Comment by michaelwassmer** [comment]
So should we just remove this stuff? As far as I understood the discussion above, these things aren't used anymore, right?

**Comment by michaelwassmer** [comment]
Ok, I'll try to get this done today or tomorrow.

**Comment by perrotta** [comment]
+1
- Fixed by https://github.com/cms-sw/cmssw/pull/40591, thank you @michaelwassmer
