### ISSUE TITLE
feature request: add methods for adding elements to a task in conjunction with a process modifier

### ISSUE THREAD

**Issue by fwyzard** [cms-sw/cmssw#33456]
Add a way to simplify a common idiom in the offline reconstruction configuration: 
```python
task = cms.Task(a, b, c)

from Configuration.Eras.Modifier_modifier_cff import modifier
_modifier_task = task.copy()
_modifier_task.add(d, e)
modifier.toReplaceWith(task, _modifier_task)
```

A simple approach could to extend the Task interface with a new `copyAndAdd(self, *items)` method.
This is similar to the existing `copyAndExclude()` method, and it would allow the simpler syntax:
```python
task = cms.Task(a, b, c)

from Configuration.Eras.Modifier_modifier_cff import modifier
modifier.toReplaceWith(task, task.copyAndAdd(d, e))
```

An other idea could be to add a `toAddTo(self, task, *items)` method to the Modifier object, supporting a syntax like
```python
task = cms.Task(a, b, c)

from Configuration.Eras.Modifier_modifier_cff import modifier
modifier.toAddTo(task, d, e)
```

In this case, it would be nice to also add the `toRemoveFrom()` or `toExcludeFrom()` counterpart.

**Comment by fwyzard** [comment]
assign core

**Comment by makortel** [comment]
The named `Task` (and two lines) can be avoided already now with
```py
task = cms.Task(a, b, c)

from Configuration.Eras.Modifier_modifier_cff import modifier
modifier.toReplaceWith(task, cms.Task(task.copy(), d, e))
```
One has to be careful with the `.copy()` though, omitting that `toReplaceWith()` appears like it would work, but later use of the `task` leads to infinite loop.

**Comment by fwyzard** [comment]
Thanks, this is already a useful intermediate solution.
