### ISSUE TITLE
Inclusion of NumberEvents metric from JobReport in older releases

### ISSUE THREAD

**Issue by jordan-martins** [cms-sw/cmssw#33478]
Hi all,

PdmV would like to request, if possible, the inclusion of the metric NumberEvents in the JobReport in older releases used still in production. This would mean the go up to 7_X more or less. Could you kindly provide assistance, please?

This variable was requested in PR [1].

Thanks, Jordan.
FYI @silviodonato @qliphy @justinasr 

[1] https://github.com/cms-sw/cmssw/commit/0243d5d2b07e4a105fba8927c24542518546ae64

**Comment by makortel** [comment]
assign core

**Comment by makortel** [comment]
@jordan-martins Could you provide an explicit list of release cycles?

**Comment by jordan-martins** [comment]
Hi @makortel , thanks! Here is the list of our root campaigns releases:
'CMSSW_7_1_22'
'CMSSW_7_1_32'
'CMSSW_7_1_37'
'CMSSW_7_1_47'
'CMSSW_7_4_4'
'CMSSW_7_5_8_patch7'
'CMSSW_7_5_9'
'CMSSW_8_0_19_Geant4102'
'CMSSW_8_0_21'
'CMSSW_8_0_31'
'CMSSW_8_0_36'
'CMSSW_8_2_0'
'CMSSW_8_3_0'
'CMSSW_9_0_0'
'CMSSW_9_0_2'
'CMSSW_9_1_2_patch1'
'CMSSW_9_2_8'
'CMSSW_9_3_6'
'CMSSW_9_3_6_patch2'
'CMSSW_9_3_9_patch1'
'CMSSW_9_3_19'
'CMSSW_9_4_11'
'CMSSW_9_4_12'
'CMSSW_9_4_16'
'CMSSW_9_4_19'
'CMSSW_9_4_20'
'CMSSW_9_4_7'
'CMSSW_10_0_2'
'CMSSW_10_0_3'

**Comment by makortel** [comment]
Thanks, so that would mean
- [ ] 7_1_X
- [ ] 7_4_X
- [ ] 7_5_X
- [ ] 8_0_X
- [ ] 8_2_X
- [ ] 8_3_X
- [ ] 9_0_X
- [ ] 9_1_X
- [ ] 9_2_X
- [ ] 9_3_X
- [ ] 9_4_X
- [ ] 10_0_X

That is a rather long list, are all of those really needed? I vaguely recall an earlier "backport to all earlier releases used in production" concerned fewer releases.

**Comment by makortel** [comment]
Last ORP agenda lists only 7_1_X, 8_0_X, 9_3_X, and 9_4_X of those.

**Comment by jordan-martins** [comment]
Hi @makortel, please, lets aim for the release set from ORP, then.
Thanks, Jordan

**Comment by wddgit** [comment]
The PRs are all submitted now.

**Comment by wddgit** [comment]
The PRs are all merged now. That completes my part of this. I don't when they will show up in releases...

**Comment by makortel** [comment]
+1
