### ISSUE TITLE
Example(s)/Tutorial(s)

### ISSUE THREAD

**Issue by AdvaitDhingra** [cms-sw/cmssw#33512]
Hello,

I would like to contribute to CMSSW, however I can't find any guide as to how I can use the different packages. Does something like this exist, or can it be made?

Kind Regards,

Advait

**Comment by makortel** [comment]
Are you perhaps looking something like http://cms-sw.github.io/tutorial.html?

**Comment by AdvaitDhingra** [comment]
> Are you perhaps looking something like http://cms-sw.github.io/tutorial.html?

Ah yes, thank you!
