### ISSUE TITLE
[DD4hep] Some tracker volumes created without namespace in name

### ISSUE THREAD

**Issue by cvuosalo** [cms-sw/cmssw#33536]
Our standard with DD4hep is that component names should contain the namespace. The following solids and volumes are lacking the namespace in the name:

TECModule0RphiWafer
TECModule0StereoWafer
TECModule1RphiWafer
TECModule1StereoWafer
TECModule2RphiWafer
TECModule3RphiWafer
TECModule4RphiWafer
TECModule4StereoWafer
TECModule5RphiWafer
TECModule6RphiWafer
TOBCoolingManifold1a
TOBCoolingManifold1r
TOBCoolingManifold2a
TOBCoolingManifold2r
TOBCoolingManifold3a
TOBCoolingManifold3r
TOBCoolingManifold4a
TOBCoolingManifold4r
TOBCoolingManifold5a
TOBCoolingManifold5r
TOBCoolingManifold6a
TOBCoolingManifold6r

These components are probably created in the following files:
`Geometry/TrackerCommonData/plugins/dd4hep/DDTECModuleAlgo.cc`
`Geometry/TrackerCommonData/plugins/dd4hep/DDTOBRadCableAlgo.cc`

**Comment by cvuosalo** [comment]
assign geometry

**Comment by cvuosalo** [comment]
FYI @ghugo83 @bsunanda @ianna @adewit

**Comment by ghugo83** [comment]
Thanks @cvuosalo 
@cvuosalo Does that cause any specific issue?
I thought the plan is to remove the namespaces anyway, now that they are not needed anymore in topology building?

**Comment by cvuosalo** [comment]
Sorry, I am forgetting that we want to transition to remove the namespaces once all components have been changed to have unique names without the namespaces. The current situation is confusing where we have most volume names with namespaces and some without.
