### ISSUE TITLE
Non-repeatibility in EgammaV DQM folder

### ISSUE THREAD

**Issue by makortel** [cms-sw/cmssw#33554]
I've now seen a few PRs to show differences in `EgammaV/ElectronMcSignalValidatorMiniAOD/h_ele_neutralHadronRelativeIso_mAOD_recomp` DQM histogram in workflows 10024.0 and 10224.0. Some examples of such PR tests https://github.com/cms-sw/cmssw/pull/33549#issuecomment-828050036, https://github.com/cms-sw/cmssw/pull/33534#issuecomment-827951573.

**Comment by makortel** [comment]
assign dqm

**Comment by jfernan2** [comment]
Not only on 10024 https://tinyurl.com/yhy9j8sq
but also in 10824 https://tinyurl.com/ye8kb4vk
as seen on https://github.com/cms-sw/cmssw/pull/33540 and https://github.com/cms-sw/cmssw/pull/33560
It looks like a precision problem ~0
EGamma Validation developers @archiron @nancymarinelli @guitargeek  could you please have a look?
Thanks

**Comment by makortel** [comment]
Here is another with 10024.0, 10224.0, and 10824.0 https://github.com/cms-sw/cmssw/pull/33561#issuecomment-828431073

**Comment by makortel** [comment]
Here is another with 10024.0, 10224.0, and 10824.0 #33550 (comment)

**Comment by archiron** [comment]
Excuse me, but what are those differences ? It does not look clear for me.
@beaudett

**Comment by makortel** [comment]
E.g. from https://github.com/cms-sw/cmssw/pull/33550

10024.0
![image](https://user-images.githubusercontent.com/33993/116420227-68b51c00-a803-11eb-999b-dbc91b71a578.png)

108240.0
![image](https://user-images.githubusercontent.com/33993/116420256-6fdc2a00-a803-11eb-84b1-c63394496b9a.png)

11634.0
![image](https://user-images.githubusercontent.com/33993/116420283-77033800-a803-11eb-92a0-59f1fe059424.png)

**Comment by beaudett** [comment]
Hi
like @archiron I am confused. I see a problem with the fact than in  [DQM ](https://tinyurl.com/yfyc7jbb) there is only one plot available in that directory. Is that what you are concerned about ? Or is it because the two plots are not identical ?

**Comment by makortel** [comment]
There is something that occasionally causes this histogram to be different between an IB and the IB+PR (where the PR does not have any changes that could impact physics).

**Comment by beaudett** [comment]
I have no clue of what can cause such a difference. This histogram is comparing the PF-isolation computed at the RECO-level and that re-computed on-the-fly from the PF candidates. As a matter of fact, it turns out that these histograms are not much useful and we could simply drop them.

**Comment by jfernan2** [comment]
@beaudett then could you please create a PR removing those plots to not confuse the Jenkin tests around? Thank you very much!

**Comment by beaudett** [comment]
Hi 
@archiron can you please remove the "recomp" plots and prepare a PR ?
@jfernan2 there is not much special with these plots, I am afraid there might be a deeper problem but we'll see and we might learn something in the process.

**Comment by nancymarinelli** [comment]
Are the plots listed so far the only ones or there are more ?


________________________________

**Comment by jfernan2** [comment]
Thank you very much @beaudett

**Comment by archiron** [comment]
@beaudett @jfernan2 Pr made : https://github.com/cms-sw/cmssw/pull/33575

**Comment by perrotta** [comment]
In case it can be useful for further investigations meant to pinpoint other possibe related (and now hidded) issues, the original non-repeatibility appeared right after #33421 was merged.

**Comment by jfernan2** [comment]
It looks like this issue is no present any longer since months

**Comment by jfernan2** [comment]
+1
