### ISSUE TITLE
Random PR test comparison failures in DD4Hep workflows

### ISSUE THREAD

**Issue by makortel** [cms-sw/cmssw#33552]
We are seeing infrequent comparison failures in DD4Hep workflows in tests of unrelated PRs. The purpose of this issue is to track their frequency and progress to find out the cause.

**Comment by makortel** [comment]
assign geometry

**Comment by makortel** [comment]
One occurrence is here https://github.com/cms-sw/cmssw/pull/33526#issuecomment-827662830

**Comment by makortel** [comment]
Another one https://github.com/cms-sw/cmssw/pull/33534#issuecomment-827951573

**Comment by makortel** [comment]
Here is another https://github.com/cms-sw/cmssw/pull/33549#issuecomment-828050036

**Comment by slava77** [comment]
is there a way to track which machine was used in each case?
This is in case there is some architecture dependence (me being reminded of existing differences in reco/miniAOD for e.g. tensorflow's mkl dependency)

**Comment by VinInn** [comment]
Did anybody run valgrind on those DD4HEP wf?

**Comment by mrodozov** [comment]
I asked last week on two PRs for externals the same thing
https://github.com/cms-sw/cmsdist/pull/6822#issuecomment-824326859
https://github.com/cms-sw/cmsdist/pull/6787#issuecomment-824327267

**Comment by makortel** [comment]
Here is another https://github.com/cms-sw/cmssw/pull/33550#issuecomment-828086998

**Comment by cvuosalo** [comment]
This workflow was stable for the last few weeks, but now it is unstable again. I think some recent change either re-activated an old bug or introduced a new stability problem. I will submit a PR to remove it from the PR tests for now.

**Comment by cvuosalo** [comment]
Looking through the recent history of merged PRs, I think the recent ROOT update might be a suspect for triggering the instability:

https://github.com/cms-sw/cmsdist/pull/6835 ROOT change (April 23)
https://github.com/cms-sw/cmsdist/pull/6826 DD4hep change (April 21)

That said, the instability seems to be around the 10% level. Many PR tests pass successfully with this workflow.

**Comment by cvuosalo** [comment]
@VinInn > Did anybody run valgrind on those DD4HEP wf?

Yes, I ran it back on March 5: https://github.com/cms-sw/cmssw/issues/32963#issuecomment-791726546
There have been changes to DD4hep and ROOT since then.

**Comment by cvuosalo** [comment]
PR #33568 submitted to remove the DD4hep workflow from the PR tests.

**Comment by cvuosalo** [comment]
+1

**Comment by cvuosalo** [comment]
The 11634.911 DD4hep workflow is now stable. See #34003. This issue can be closed.
