### ISSUE TITLE
[DD4hep] DD4hep Ecal Endcap algo uses old DD utilities

### ISSUE THREAD

**Issue by cvuosalo** [cms-sw/cmssw#33571]
The DD4hep `Geometry/EcalCommonData/plugins/dd4hep/DDEcalEndcapAlgo.cc` uses `Geometry/EcalCommonData/interface/DDEcalEndcapTrap.h`, which utilizes old DD utilities like `DDRotationMatrix` and `DDTranslation`. Old DD dependencies should be removed from DD4hep code.

**Comment by cvuosalo** [comment]
assign geometry

**Comment by cvuosalo** [comment]
@bsunanda Could you please take a look at this?

**Comment by cvuosalo** [comment]
The old DD utilities are just aliases of ROOT classes, so they are harmless, but we would prefer not to use old DD names in DDh4ep code.

**Comment by civanch** [comment]
@bsunanda , @cvuosalo , is this issue fixed?

**Comment by bsunanda** [comment]
Yes we have fixed that
________________________________

**Comment by civanch** [comment]
+1

**Comment by qliphy** [comment]
fixed by https://github.com/cms-sw/cmssw/pull/33600
