### ISSUE TITLE
/usr/bin/env: python3: No such file or directory

### ISSUE THREAD

**Issue by mariadalfonso** [cms-sw/cmssw#33630]
we stil get error like 
`/usr/bin/env: python3: No such file or directory`
on top of CMSSW_12_0_X_2021-05-04-2300

To reproduce: 

1.  script that try to run 
https://gitlab.cern.ch/cms-nanoAOD/nanoAOD-integration/-/blob/master/scripts/setup_reference.sh
https://gitlab.cern.ch/cms-nanoAOD/nanoAOD-integration/-/blob/master/scripts/find_latest_IB.sh

2. Full Log with error 
https://gitlab.cern.ch/cms-nanoAOD/nanoAOD-integration/-/jobs/13650096

@gouskos @silviodonato @smuzaffar

**Comment by smuzaffar** [comment]
@mariadalfonso , you are missing python3 in your container ci-tools/ci-worker:cc7 . As announced https://hypernews.cern.ch/HyperNews/CMS/get/comp-ops/5318.html , please update your Dockerfile and install python3 also. SCRAM V3 is based on python 3 (as compare to SCRAM V2 which was using PERL)

**Comment by smuzaffar** [comment]
@mariadalfonso , I think all you need is to add python3 here https://gitlab.cern.ch/cms-nanoAOD/nanoAOD-integration/-/blob/master/.gitlab-ci.yml#L14

**Comment by mariadalfonso** [comment]
ok this addition now triggered another problem i.e. we are still calling SCRAMV1
https://gitlab.cern.ch/cms-nanoAOD/nanoAOD-integration/-/jobs/13655799

**Comment by smuzaffar** [comment]
@mariadalfonso , ok looks like in the container python's `socket.getfqdn()` is not returning any thing.  This is an optional call to check the state of a release. I will fix scram to ignore if `getfqdn()` call does not return any thing.

**Comment by felicepantaleo** [comment]
Thanks @smuzaffar , I'm also experiencing the same problem in singularity

**Comment by felicepantaleo** [comment]
solved by adding 
```
%post 
hostname <your_hostname>.cc7
```
in my case the hostname from `x1extreme` became `x1extreme.cc7`

**Comment by smuzaffar** [comment]
can you try again. I just have pushed scram V3_00_22 which should fix this issue

**Comment by smuzaffar** [comment]
SCRAM V3_00_23 is now availableon cvmfs, can you please try again?

**Comment by smuzaffar** [comment]
@mariadalfonso @felicepantaleo , can you please re-run your tests. This issue should be fix now.

**Comment by mariadalfonso** [comment]
@smuzaffar 
indeed I confirm that with IB CMSSW_12_0_X_2021-05-05-2300, nano test are now happily going

Thank you

**Comment by makortel** [comment]
I suppose this issue can be closed?

**Comment by makortel** [comment]
assign core

**Comment by makortel** [comment]
+1
