### ISSUE TITLE
Secondary File Input Check that Secondary File is an Ancestor

### ISSUE THREAD

**Issue by wddgit** [cms-sw/cmssw#33716]
For secondary file input, there is a requirement that the secondary input files must be ancestors of the primary input file. 
See https://twiki.cern.ch/twiki/bin/view/CMSPublic/SWGuidePoolInputSources#Example_5_Merging_files_with_dif This requirement has always existed.

There is a check that is supposed to notice if they are not and print a helpful message with an exception. See checkHistoryConsistency in PoolSource.cc. The problem is that if the file is not an ancestor there can be an assert failure in edm::BranchIDListHelper::fixBranchListIndexes before that check is ever run. Something needs to be done to run the check earlier or run fixBranchListIndexes later.

**Comment by wddgit** [comment]
Note I just changed the documentation to reflect that the actual requirement is that secondary files be ancestors. For some reason before it included the possibility that the secondary files have the same list of process names in the ProcessHistory. This is not what has been in the code...

**Comment by makortel** [comment]
assign core

**Comment by wddgit** [comment]
Original hypernews thread that started us to look at this:

https://hypernews.cern.ch/HyperNews/CMS/get/edmFramework/3921/1/1/1/1/1/1/1/3/2/1.html

**Comment by wddgit** [comment]
The fix was merged.
