### ISSUE TITLE
Failure in building a _DBG release

### ISSUE THREAD

**Issue by Dr15Jones** [cms-sw/cmssw#33734]
CMSSW_12_0_DBG_X_2021-05-13-2300 had several compilation failures. This issue is meant to track progress on fixing them.

The packages with compilation failures are
- CondTools/Ecal
- L1Trigger/CSCTrackFinder
- L1Trigger/DTTriggerPhase2
- SimTransport/PPSProtonTransport
- Validation/HGCalValidation

**Comment by Dr15Jones** [comment]
#33719 fixes Validation/HGCalValidation

**Comment by Dr15Jones** [comment]
assign core

**Comment by Dr15Jones** [comment]
I'll look into the build failure of CondTools/Ecal.

**Comment by gartung** [comment]
Copied from TBB issue
https://github.com/cms-sw/cmssw/pull/33719
https://github.com/cms-sw/cmssw/pull/33718

**Comment by Dr15Jones** [comment]
@smuzaffar @mrodozov So I created a CMSSW_12_0_DBG_X_2021-05-13-2300 work area (at FNAL), checked out CondTools/Ecal and it compiled without issue. Why didn't this fail like the IB?

**Comment by Dr15Jones** [comment]
@smuzaffar @mrodozov I can answer my own question, doing `scram b -v` I see that debugging is actually NOT turned on implicitly when using that build. What are all the environment variable I must set to get the same build environment?

**Comment by Dr15Jones** [comment]
So I discovered that compiling using `USER_CXXFLAGS` set to `-O0 -g3` compiled fine but using `-O3 -g3 -DEDM_ML_DEBUG` lead to the compilation failure.

**Comment by mrodozov** [comment]
I had that issue already yesterday, sorry for not mentioning it, I've used the USER_CXXFLAGS="-g -03 _DEDM_ML_DEBUG" in front of scram commands like:
`USER_CXXFLAGS="-g -03 _DEDM_ML_DEBUG"  scram b -j 100`

**Comment by dan131riley** [comment]
Best to use `-g -O0 -DEDM_ML_DEBUG`, as some of the failures are from conditional debug code, and some are from code that doesn't compile without the optimizer.

**Comment by Dr15Jones** [comment]
See #33737

**Comment by Dr15Jones** [comment]
Interesting, the use of `-O3 -g` actually allowed the compiler to see that the original code would read outside of the array. Using `-O0` or `-O2` did not find the problem.

**Comment by smuzaffar** [comment]
@Dr15Jones , you need to use
```
USER_CXXFLAGS="-g -O3 -DEDM_ML_DEBUG"  scram build
```
Once back to work, I will update the configuratin to make these flags defaults for the _DBG IBs

**Comment by Dr15Jones** [comment]
See #33739 #33740 and #33741

**Comment by smuzaffar** [comment]
+core
build errors for dbg Ibs are fixed now
