### ISSUE TITLE
Framework Secondary File Input for "Sibling" Files

### ISSUE THREAD

**Issue by wddgit** [cms-sw/cmssw#33756]
Currently, the secondary file feature requires a file on the secondary input file list be an ancestor of the primary files. An exception is thrown if this is not the case.

As we were discussing a problem related to secondary file input, Chris suggested it might work if we relaxed that requirement to allow sibling files to also be used for secondary file input. By sibling we mean if two files were produced by the same process, then one could read both files in the same process with one on the secondary file list. This might be useful if one needed some products that were kept in one file and some products that were kept in the other, but all the products needed were not in one file.

The suggestion is we study this carefully and possibly implement this. We need to carefully look at how BranchIDLists are managed to see if this would work. There was some concern EDAlias products might be problematic if one file kept the alias name and the other kept the original branch name.

**Comment by makortel** [comment]
assign core

**Comment by makortel** [comment]
I believe we recently concluded that we can't enable the support for sibling files. @wddgit Did I ask you document the reasons for that? I went to see https://twiki.cern.ch/twiki/bin/view/CMSPublic/SWGuidePoolInputSources#Example_5_Merging_files_with_dif 
but didn't see anything new. Could you add the rationale there (for the next time the question comes up)?

**Comment by wddgit** [comment]
I'll start looking at this now and add some new documentation.

**Comment by wddgit** [comment]
@makortel I added some new documentation in the place you suggested
https://twiki.cern.ch/twiki/bin/view/CMSPublic/SWGuidePoolInputSources#Example_5_Merging_files_with_dif

It is at the end of that section.

Let me know if you want something different. I tried to capture the conclusions of our discussions around the beginning of October.

**Comment by makortel** [comment]
Thanks, I think the new text captures the murky details well enough.

**Comment by makortel** [comment]
-core

**Comment by makortel** [comment]
@cmsbuild, please close
