### ISSUE TITLE
Strange differences in DQM after harvesting step4 despite same step3 files

### ISSUE THREAD

**Issue by jfernan2** [cms-sw/cmssw#33766]
PR https://github.com/cms-sw/cmssw/pull/33610 modified Muon Validation but showed differences in Tracking and Vertexing DQM folders for workflows 9.0  (a Run1 MC) and 135.4 (a FS Run2 sample) ONLY

The following comment has instructiosn to reprodce the issue:
https://github.com/cms-sw/cmssw/pull/33610#issuecomment-843236483

Step3 EDM DQMIO roto files are identical with and without the PR, but step4 HARVESTING makes it different with the PR w.r.t. baseline

**Comment by makortel** [comment]
assign dqm

**Comment by makortel** [comment]
The fits in `DQMGenericClient` maintain state between fit calls, so adding a new histogram to be fitted can show numerical changes in all other histograms produced by those fits.

**Comment by jfernan2** [comment]
OK, but the PR is not adding NEW histograms, just modifying some of them in the Muon folder:
https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_12_0_X_2021-05-17-1100+b486f6/42833/dqm-histo-comparison-summary.html

Modifying some histograms may affect the fits in other ones? This was checked by @abbiendi  in one of his tests, and he arrived to the conclusion (if I got it right...) that the harvesting with his modified plots gave differences:
https://github.com/cms-sw/cmssw/pull/33610#issuecomment-839208056

**Comment by abbiendi** [comment]
yes, I have not added new plots at all and in particular not added new fits to be done

**Comment by davidlange6** [comment]
That is a pretty undesirable feature in general. (And would explain what was seen in the PR from what I read) Can it be changed?

**Comment by makortel** [comment]
Looking back my earlier comments on the subject it seems that already a change in one of the histograms-to-be-fitted can cause changes in other histograms from the fits, e.g. https://github.com/cms-sw/cmssw/pull/12577#issuecomment-161418926 and https://github.com/cms-sw/cmssw/pull/8888#issuecomment-98633381.

Here is some earlier discussion on similar topic https://github.com/cms-sw/cmssw/issues/23105

**Comment by davidlange6** [comment]
I didn’t know this feature of root..

So we could add 
fitFcn->SetParameters(histoY->Integral(),
                                     histoY->GetMean(),
                                     histoY->GetRMS());


https://github.com/cms-sw/cmssw/blob/6d2f66057131baacc2fcbdd203588c41c885b42c/DQMServices/Components/plugins/DQMGenericClient.cc#L1156

(At least for this piece of code)

**Comment by jfernan2** [comment]
It looks like that piece of code does not fix the issue :-(
https://github.com/cms-sw/cmssw/pull/33610#issuecomment-843591769
Any other idea? Thanks

**Comment by davidlange6** [comment]
It's not that the suggested change makes the results the same as in the current ib (ie, the comparison you point to). Rather it should make results independent of the set of (and order of) fits run

On May 19, 2021 9:36 AM, jfernan2 ***@***.***> wrote:

It looks like that piece of code does not fix the issue :-(
#33610 (comment)<https://github.com/cms-sw/cmssw/pull/33610#issuecomment-843591769>
Any other idea? Thanks

**Comment by abbiendi** [comment]
yes, I think this was expected.
The crucial comparison would be with the IB with your new fixes but without my PR

**Comment by davidlange6** [comment]
Yes, thats right.

**Comment by jfernan2** [comment]
It seems I got it all wrong, sorry
