### ISSUE TITLE
Possible thread unsafe operation in workflow 136.8855

### ISSUE THREAD

**Issue by czangela** [cms-sw/cmssw#33868]
I tried to run some custom validation after some modifications to the `ErrorChecker*` / `PixelDataFormatter`, but I couldn't proceed *multithreaded*, because I was getting inconsistent results.

For replication, one can follow these steps:

---
### 1. Check out latest IB release 
```sh
cmsrel CMSSW_12_0_X_2021-05-26-2300
cd CMSSW_12_0_X_2021-05-26-2300/src/
cmsenv
```

### 2. Add relevant packages
```sh
git cms-addpkg EventFilter/SiPixelRawToDigi
```

### 3. Track FED error collection

There are more ways to do this, I used `LogDebug` (which in itself is a thread-safe option) to print all data about FED errors.

To do this, one can apply the following *git patch* :
```diff
diff --git a/EventFilter/SiPixelRawToDigi/src/PixelDataFormatter.cc b/EventFilter/SiPixelRawToDigi/src/PixelDataFormatter.cc
index 5557f806144..02a177018b5 100644
--- a/EventFilter/SiPixelRawToDigi/src/PixelDataFormatter.cc
+++ b/EventFilter/SiPixelRawToDigi/src/PixelDataFormatter.cc
@@ -417,6 +417,11 @@ void PixelDataFormatter::unpackFEDErrors(PixelDataFormatter::Errors const& error
                                          DetErrors& nodeterrors) {
   const uint32_t dummyDetId = 0xffffffff;
   for (const auto& [errorDetId, rawErrorsVec] : errors) {
+	for (auto const& aPixelError : rawErrorsVec) {
+        LogDebug("FedErrors") << "DETID: " << errorDetId << "; FED: " << aPixelError.getFedId()
+                              << ", TYPE: " << aPixelError.getType() << ", WORD: " << aPixelError.getWord32()
+                              << ", MSG: " << aPixelError.getMessage();
+      }
     if (errorDetId == dummyDetId) {  // errors given dummy detId must be sorted by Fed
       nodeterrors.insert(nodeterrors.end(), rawErrorsVec.begin(), rawErrorsVec.end());
     } else {
```

Just save the content to e.g. `federrors_logdebug.patch` then apply it from the `CMSSW_12_0_X_2021-05-26-2300/src` directory with
```sh
git apply federrors_logdebug.patch
```
Build the package with enabled `LogDebug` functionality:
```sh
scram b clean
export USER_CXXFLAGS="-DEDM_ML_DEBUG"
scram b -j
```

### 4. Choose relevant `runTheMatrix.py` workflow

Let's go ahead with the **phase 1** (pixelTrackingOnly) `136.8855` workflow:
```sh
runTheMatrix.py -e -l 136.8855 --maxSteps=3 --ibeos -t 4 -j0
```

This will generate only the commands for the first 3 steps, won't run them.

Add the following lines to `step3_RAW2DIGI_L1Reco_RECO_EI_PAT_ALCA_DQM.py`:

```py
# Load MessageLogger if haven't already
process.load('FWCore.MessageService.MessageLogger_cfi')

...

# Output info to file detailedInfo.log
process.MessageLogger = cms.Service("MessageLogger",
    destinations = cms.untracked.vstring('detailedInfo'),
    categories         = cms.untracked.vstring('FedErrors'),
    debugModules  = cms.untracked.vstring('*'),
        detailedInfo          = cms.untracked.PSet(
        threshold =  cms.untracked.string('DEBUG'),
        default    =  cms.untracked.PSet(limit = cms.untracked.int32(0)),
        INFO       =  cms.untracked.PSet(limit = cms.untracked.int32(0)),
        DEBUG   = cms.untracked.PSet(limit = cms.untracked.int32(0)),
        FedErrors = cms.untracked.PSet(limit = cms.untracked.int32(10000000))
    )
)
```

Run steps 2 and 3:
```sh
cmsRun step2_L1REPACK_HLT.py &
cmsRun step3_RAW2DIGI_L1Reco_RECO_EI_PAT_ALCA_DQM.py &
```

### 5. Run multithreaded version multiple times, run single threaded version, compare results

After running `step3` one can list the number of `FED errors` by type:
```sh
cat detailedInfo.log | grep DETID | awk '//{print $5 $6}' | tr -d ',' | sort | uniq -c
```

It should output something like:
```
  22138 TYPE:25
      4 TYPE:30
     44 TYPE:31
    105 TYPE:37
```

Save `detailedInfo.log` under another name and rerun `step3`:
```
cp detailedInfo.log detailedInfo_old.log
cmsRun step3_RAW2DIGI_L1Reco_RECO_EI_PAT_ALCA_DQM.py &
```

After some grepping and sorting the output of the repeated reconstruction is:
```
  22332 TYPE:25
      4 TYPE:30
     44 TYPE:31
    107 TYPE:37
```

Modify the following line in `step3_RAW2DIGI_L1Reco_RECO_EI_PAT_ALCA_DQM.py` to run **single-threaded**
```py
#Setup FWK for multithreaded
process.options.numberOfThreads = 4
```

The output should contain more `FED errors` than any multithreaded instance ran previously:
```
  22800 TYPE:25
      4 TYPE:30
     44 TYPE:31
    109 TYPE:37
```
---
I'm not sure what's happening in the background it could be that I'm totally misinterpreting this.

**Comment by Dr15Jones** [comment]
One item of note, LogDebug is thread safe (meaning each message will be output in its entirety without any 'overlaps') however the order in which items are printed is not guaranteed and the MessageLogger is allowed to discard messages if too many are happening at one time. You can see the count of discarded messages at the end of the log file.

**Comment by Dr15Jones** [comment]
@czangela what was the resolution?

**Comment by czangela** [comment]
I didn't find the # of dropped messages entry at the end of the log file, but I'm quite sure it was that.
