### ISSUE TITLE
Unit test failure due to wrong username/passwrd in CondTools

### ISSUE THREAD

**Issue by mrodozov** [cms-sw/cmssw#33874]
23 unit tests are failing currently due to inability to authenticate (as it seems)
The list can be seen here
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-1b5abc/15350/unitTests/failed.html

**Comment by mrodozov** [comment]
assign db

**Comment by qliphy** [comment]
@cms-sw/db-l2   Unit failures still show in the 11_3_X and 12_0_X  IBs, would you please have a check soon?

For example:
https://cmssdt.cern.ch/SDT/cgi-bin/logreader/slc7_amd64_gcc900/CMSSW_12_0_X_2021-05-29-1100/unitTestLogs/CondTools/SiStrip#/25
ORA-01017: invalid username/password; logon denied

and
https://cmssdt.cern.ch/SDT/cgi-bin/logreader/slc7_amd64_gcc900/CMSSW_11_3_X_2021-05-29-1100/unitTestLogs/CondTools/SiStrip#/25
ORA-01017: invalid username/password; logon denied

**Comment by mrodozov** [comment]
there is a PR from DB https://github.com/cms-sw/cmssw/pull/33859 which mentions authentication only I'm not sure if it has something to do with that

**Comment by ggovi** [comment]
The tests are failing as a consequence of a massive invalidation of passwords for read-only accounts, caused by the recent Oracle server upgrade.
The passwords involved in Ecal and RunInfo test have been fixed centrally and they should require no additional action.
For the Strip-test, have contacted the concerned O2O experts.

**Comment by mmusich** [comment]
This is solved by now, right?
Unit tests are clean in the [slc7_amd64_gcc90 build](https://cmssdt.cern.ch/SDT/cgi-bin/showBuildLogs.py/slc7_amd64_gcc900/www/wed/12.0-wed-23/CMSSW_12_0_X_2021-06-02-2300).
Can this issue be signed and closed?

**Comment by mrodozov** [comment]
yes it is. can be closed
