### ISSUE TITLE
Duplicate versions of HcalHBHEMuonSimAnalyzer

### ISSUE THREAD

**Issue by Dr15Jones** [cms-sw/cmssw#33896]
The module HcalHBHEMuonSimAnalyzer appears in both 
- Calibration/HcalCalibAlgos/test/HcalHBHEMuonSimAnalyzer.cc
- Calibration/IsolatedParticles/plugins/HcalHBHEMuonSimAnalyzer.cc

From a cursory glance, they appear to be identical.

**Comment by qliphy** [comment]
assign alca

**Comment by qliphy** [comment]
@bsunanda   Would you please have a check?   It seems that you added Calibration/HcalCalibAlgos/test/HcalHBHEMuonSimAnalyzer.cc  recently in https://github.com/cms-sw/cmssw/pull/33810/

**Comment by smuzaffar** [comment]
https://github.com/cms-sw/cmssw/pull/33915 fixes this issue.
