### ISSUE TITLE
python problems in TSAN builds 

### ISSUE THREAD

**Issue by dan131riley** [cms-sw/cmssw#33936]
TSAN builds are currently completely broken.  The basic problem is that builds of any data format library fail at the `edmCheckClassVersion` step:
```
>> Checking EDM Class Version for src/DataFormats/Provenance/src/classes_def.xml in libDataFormatsProvenance.so
/data/cmsbld/jenkins/workspace/build-any-ib/w/tmp/BUILDROOT/aeb109d03d440fd5d60c478dd2b1dba5/opt/cmssw/slc7_amd64_gcc900/cms/cmssw/CMSSW_12_0_TSAN_X_2021-05-28-2300/src/FWCore/Utilities/scripts/edmCheckClassVersion -l libDataFormatsProvenance.so -x /data/cmsbld/jenkins/workspace/build-any-ib/w/tmp/BUILDROOT/aeb109d03d440fd5d60c478dd2b1dba5/opt/cmssw/slc7_amd64_gcc900/cms/cmssw/CMSSW_12_0_TSAN_X_2021-05-28-2300/src/DataFormats/Provenance/src/classes_def.xml
cling::DynamicLibraryManager::loadLibrary(): /data/cmsbld/jenkins/workspace/build-any-ib/w/slc7_amd64_gcc900/external/gcc/9.3.0/lib64/libtsan.so.0: cannot allocate memory in static TLS block
Traceback (most recent call last):
  File "/data/cmsbld/jenkins/workspace/build-any-ib/w/tmp/BUILDROOT/aeb109d03d440fd5d60c478dd2b1dba5/opt/cmssw/slc7_amd64_gcc900/cms/cmssw/CMSSW_12_0_TSAN_X_2021-05-28-2300/src/FWCore/Utilities/scripts/edmCheckClassVersion", line 182, in <module>
    raise RuntimeError("failed to load library '"+options.library+"'")
RuntimeError: failed to load library 'libDataFormatsProvenance.so'
```
The issue looks to be essentially the same as this:

https://gcc.gnu.org/bugzilla/show_bug.cgi?id=81493

Our python build is not built with the address sanitizer, so libtsan doesn't get loaded until edmCheckClassVersion tries to dlopen() a library that was, and loading libtsan late in a process has problems.  It looks like we would either need to build python with TSAN enabled, or else change the TLS model.

**Comment by makortel** [comment]
assign core

**Comment by Dr15Jones** [comment]
@dan131riley what about using LD_PRELOAD?

**Comment by dan131riley** [comment]
> @dan131riley what about using LD_PRELOAD?

Segmentation fault during startup, apparently while processing library binding for `dlsym`:
```
     84163:	symbol=dlsym;  lookup in file=python [0]
     84163:	symbol=dlsym;  lookup in file=/cvmfs/cms-ib.cern.ch/nweek-02682/slc7_amd64_gcc900/external/gcc/9.3.0/lib64/libtsan.so.0 [0]
     84163:	symbol=dlsym;  lookup in file=/cvmfs/cms-ib.cern.ch/week0/slc7_amd64_gcc900/cms/cmssw/CMSSW_12_0_TSAN_X_2021-05-28-2300/external/slc7_amd64_gcc900/lib/libpython2.7.so.1.0 [0]
     84163:	symbol=dlsym;  lookup in file=/lib64/libpthread.so.0 [0]
     84163:	symbol=dlsym;  lookup in file=/lib64/libdl.so.2 [0]
     84163:	binding file /cvmfs/cms-ib.cern.ch/nweek-02682/slc7_amd64_gcc900/external/gcc/9.3.0/lib64/libtsan.so.0 [0] to /lib64/libdl.so.2 [0]: normal symbol `dlsym' [GLIBC_2.2.5]
Segmentation fault
```

**Comment by dan131riley** [comment]
While LD_PRELOAD of libtsan doesn't work, it looks like it mostly works to do an LD_PRELOAD of the current plugin target, something like
```
LD_PRELOAD=$(@F) $(EDM_TOOLS_PREFIX) $(EDM_CHECK_CLASS_VERSION_SCRIPT) -l $(@F) -x $(LOCALTOP)/$$x)
```
I get a couple of warnings but it returns success:
```
>> Checking EDM Class Version for src/DataFormats/Provenance/src/classes_def.xml in libDataFormatsProvenance.so
ERROR in cling::CIFactory::createCI(): cannot extract standard library include paths!
Invoking:
  LC_ALL=C g++  -O3 -DNDEBUG -xc++ -E -v /dev/null 2>&1 | sed -n -e '/^.include/,${' -e '/^ \/.*++/p' -e '}'
Results was:
With exit code 0
@@@@ ----> OK  EDM Class Version 
>> Checking EDM Class Transients in libDataFormatsProvenance.so
ERROR in cling::CIFactory::createCI(): cannot extract standard library include paths!
Invoking:
  LC_ALL=C g++  -O3 -DNDEBUG -xc++ -E -v /dev/null 2>&1 | sed -n -e '/^.include/,${' -e '/^ \/.*++/p' -e '}'
Results was:
With exit code 0
@@@@ ----> OK  EDM Class Transients 
Leaving library rule at DataFormats/Provenance
```
I've only tried it so far on libDataFormatsProvenance.so, so won't guarantee it will work on a target with more dependencies, but it seems reasonable that preloading the target would get it fully resolved for the python script to dlopen().

**Comment by dan131riley** [comment]
I did a full rebuild [with this diff](https://github.com/dan131riley/cmssw-config/commit/4096bcd6a6ffb7b6ec7c2af6fa78683ae34ccefa).  @smuzaffar do you have any suggestions for cleaning this up or making it effective for just the TSAN builds (although it should be in general harmless to preload the plugin).

**Comment by smuzaffar** [comment]
`scram b` should set `LD_PRELOAD=$(GCC_CXXCOMPILER_BASE)/lib64/libtsan.so` before running these edm tools , let me check why itis not working

**Comment by smuzaffar** [comment]
ah there was a typo introduced during PERL to PYTHON SCRAM migration . This is fixed now https://github.com/cms-sw/cmssw-config/commit/229fca01867107f8dcdbed23b36bd2bde569c34e#diff-3e9a48949cfadd3ba1749276c06334910c0478305c1d8554a72001f7dbb15c7b . I will start a TSAN build with the change

**Comment by smuzaffar** [comment]
LD_PRELOAD=lintsan.so also did not fix the issue . This used to be working in past. I am now trying to build a TSAN release with SCRAM V2 to make sure it has nothing to do with build rules changes. I am afraid it might be linked to root llvm 9 update

**Comment by smuzaffar** [comment]
simple command like
```
LD_PRELOAD="/cvmfs/cms-ib.cern.ch/nweek-02683/slc7_amd64_gcc900/external/gcc/9.3.0/lib64/libtsan.so" python -V
Segmentation fault (core dumped)
```
fails.

**Comment by smuzaffar** [comment]
libtsan from gcc 8 works but not from gcc 9. 
```
> source /cvmfs/cms-ib.cern.ch/latest/slc7_amd64_gcc820/external/gcc/8.2.0-pafccj/etc/profile.d/init.sh
LD_PRELOAD=$GCC_ROOT/lib64/libtsan.so ls
> source /cvmfs/cms-ib.cern.ch/latest/slc7_amd64_gcc900/external/gcc/9.3.0/etc/profile.d/init.sh
LD_PRELOAD=$GCC_ROOT/lib64/libtsan.so ls
Segmentation fault
```
so issue is with GCC 9.3. I do remember that we had TSAN IBs with GCC 9.3 working. May be something changed on OS side which now breaks gcc 9 lintsan

**Comment by dan131riley** [comment]
It works in gcc10 as well, but not in 9.0.0, 9.2.1 and 9.3.0.  gcc9 also fails in a cc7:amd64-d20200608 singularity container.  With a cc8 container, gcc9 also segfaults, while gcc8 works.

**Comment by smuzaffar** [comment]
I would suggest to move to GCC 10 for these specail `*SAN` IBs,  any objections ?

**Comment by makortel** [comment]
Sounds good to me.

**Comment by smuzaffar** [comment]
closing it as TSAN builds have been disabled
