### ISSUE TITLE
potentially incorrect python syntax in trigTools.py

### ISSUE THREAD

**Issue by davidlange6** [cms-sw/cmssw#33967]
I noticed that our python3 builds generate this warning - the result of these checks is potentially not what was intended.

 if not path is '':
/cvmfs/cms-ib.cern.ch/week1/slc7_amd64_gcc900/cms/cmssw/CMSSW_12_0_X_2021-06-02-2300/python/PhysicsTools/PatAlgos/tools/trigTools.py:174: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if outputModule is not '':
/cvmfs/cms-ib.cern.ch/week1/slc7_amd64_gcc900/cms/cmssw/CMSSW_12_0_X_2021-06-02-2300/python/PhysicsTools/PatAlgos/tools/trigTools.py:263: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if not path is '':
/cvmfs/cms-ib.cern.ch/week1/slc7_amd64_gcc900/cms/cmssw/CMSSW_12_0_X_2021-06-02-2300/python/PhysicsTools/PatAlgos/tools/trigTools.py:276: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if outputModule is not '':
/cvmfs/cms-ib.cern.ch/week1/slc7_amd64_gcc900/cms/cmssw/CMSSW_12_0_X_2021-06-02-2300/python/PhysicsTools/PatAlgos/tools/trigTools.py:414: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if outputModule is not '':
/cvmfs/cms-ib.cern.ch/week1/slc7_amd64_gcc900/cms/cmssw/CMSSW_12_0_X_2021-06-02-2300/python/PhysicsTools/PatAlgos/tools/trigTools.py:530: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if outputModule is not '':
/cvmfs/cms-ib.cern.ch/week1/slc7_amd64_gcc900/cms/cmssw/CMSSW_12_0_X_2021-06-02-2300/python/PhysicsTools/PatAlgos/tools/trigTools.py:742: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if outputModule is not '':

**Comment by makortel** [comment]
assign reconstruction

**Comment by slava77** [comment]
assign xpog

the errors point to code introduced in 2010; it's in the part that reco has not really followed
https://github.com/cms-sw/cmssw/commit/da6366989febfca880d9219bad43cbd212d5755a

**Comment by slava77** [comment]
+reconstruction

via #34253

**Comment by mariadalfonso** [comment]
+xpog
