### ISSUE TITLE
SiStripGainsPCL MRH ASAN error, EventSetup product in dqmEndJob

### ISSUE THREAD

**Issue by pieterdavid** [cms-sw/cmssw#33960]
@mmusich noticed a failure in the address sanitizer IBs for the SiStripGainsPCLHarvester [here](https://cmssdt.cern.ch/SDT/cgi-bin/logreader/slc7_amd64_gcc900/CMSSW_12_0_ASAN_X_2021-05-31-2300/unitTestLogs/CalibTracker/SiStripChannelGain#/458).
The only pointer around in [`APVGain::subdetectorPlane`](https://github.com/cms-sw/cmssw/blob/master/CalibTracker/SiStripChannelGain/src/APVGainHelpers.cc#L119-L131) is one to the `TrackerTopology`, which is retrieved by the SiStripGainsPCLHarvester at the `BeginRun` transition ([L52](https://github.com/cms-sw/cmssw/blob/master/CalibTracker/SiStripChannelGain/src/SiStripGainsPCLHarvester.cc#L52) and [L619-623](https://github.com/cms-sw/cmssw/blob/master/CalibTracker/SiStripChannelGain/src/SiStripGainsPCLHarvester.cc)).
I didn't fully think this through when migrating the harvester to esConsumes in https://github.com/cms-sw/cmssw/pull/31826 , but based on the ASAN information my hypothesis is that the `TrackerTopology` is deleted before `dqmEndJob` is called (from `endProcessBlockProduce`) - the bad address from ASAN is inside `[tTopo_, tTopo_+sizeof(TrackerTopology)[`.
Is that correct? How should we get the `TrackerTopology` such that it can be used from `dqmEndJob`?
Thanks in advance!

**Comment by mmusich** [comment]
For the record I can reproduce in `CMSSW_12_0_ASAN_X_2021-06-02-2300`
```
cmsrel CMSSW_12_0_ASAN_X_2021-06-02-2300
cd CMSSW_12_0_ASAN_X_2021-06-02-2300/
git cms-addpkg CalibTracker/SiStripChannelGain
scram build -j 20
setenv CMS_PATH /cvmfs/cms-ib.cern.ch
curl https://raw.githubusercontent.com/cms-sw/cms-bot/master/das-utils/das_client > bin/slc7_amd64_gcc900/dasgoclient
chmod +x bin/slc7_amd64_gcc900/dasgoclient
cd src/
cmsenv
voms-proxy-init -voms cms
scramv1 b runtests
```

despite the [ASAN logs](https://cmssdt.cern.ch/SDT/cgi-bin/showBuildLogs.py/slc7_amd64_gcc900/www/wed/12.0.ASAN-wed-23/CMSSW_12_0_ASAN_X_2021-06-02-2300)s say otherwise...

**Comment by makortel** [comment]
assign alca

**Comment by makortel** [comment]
> I didn't fully think this through when migrating the harvester to esConsumes in #31826 , but based on the ASAN information my hypothesis is that the `TrackerTopology` is deleted before `dqmEndJob` is called (from `endProcessBlockProduce`) - the bad address from ASAN is inside `[tTopo_, tTopo_+sizeof(TrackerTopology)[`.
> Is that correct? 

It is correct that EventSetup products must not be accessed in `endProcessBlockProduce()` or `endJob()`. The IOV of the record/product ends (at latest) in endRun, and framework is free to delete all EventSetup products whose IOV has ended.

> How should we get the `TrackerTopology` such that it can be used from `dqmEndJob`?

The least bad workaround is to either extract the necessary information from `TrackerTopology` or make a copy of the full object. The endRun transition is likely the best place to do that.

**Comment by pieterdavid** [comment]
> It is correct that EventSetup products must not be accessed in `endProcessBlockProduce()` or `endJob()`. The IOV of the record/product ends (at latest) in endRun, and framework is free to delete all EventSetup products whose IOV has ended.

Thanks for clarifying @makortel !
 
> > How should we get the `TrackerTopology` such that it can be used from `dqmEndJob`?
> 
> The least bad workaround is to either extract the necessary information from `TrackerTopology` or make a copy of the full object. The endRun transition is likely the best place to do that.

I implemented the workaround (full copy in endRun, `TrackerTopology` is not that big, and we need to call its member methods), which fixes the problem indeed. I found a few more modules that may have the same problem (two SiStripQuality-related, and one possible case in the pixel code), I'll fix them together.
Would there be any way to automatically check or protect against this (e.g. storing an ESHandle instead of a raw pointer, in case that throws an exception or becomes `nullptr` after the object is destructed)?

**Comment by makortel** [comment]
> Would there be any way to automatically check or protect against this (e.g. storing an ESHandle instead of a raw pointer, in case that throws an exception or becomes `nullptr` after the object is destructed)?

Unfortunately no, there is no mechanism for that. In this respect `ESHandle` behaves like a raw pointer.

From the framework point of view already storing a raw pointer (or an `ESHandle`) to an ESProduct into a module member variable is a sign of possible problems towards accessing the product outside of its life time (e.g. storing a pointer only in beginRun for a product whose IOV changes between LuminosityBlocks in the middle of a Run).
