### ISSUE TITLE
A lot of warning/error message of LCTQualityControl: CSCTriggerPrimitivesProducer:simCscTriggerPrimitiveDigis

### ISSUE THREAD

**Issue by srimanob** [cms-sw/cmssw#33993]
Trying to run Phase2 wfs with 12_0_0_pre2, I found a lot of message of LCTQualityControl. However, the job can run until the end.

%MSG-e LCTQualityControl:   CSCTriggerPrimitivesProducer:simCscTriggerPrimitiveDigis  07-Jun-2021 06:01:19 CEST Run: 1 Event: 4
CSCALCTDigi with invalid quality: 4; allowed [0, 3]
%MSG
%MSG-e LCTQualityControl:   CSCTriggerPrimitivesProducer:simCscTriggerPrimitiveDigis  07-Jun-2021 06:01:19 CEST Run: 1 Event: 4
Invalid stub in  E:2 S:2 R:1 C:1 L:0 (1 errors):
CSC ALCT #1: Valid = 1 Quality = 4 Accel. = 0 PatternB = 0 Key wire group = 11 BX = 6 HMT = 65535
%MSG

Here are cmsDriver I use,
cmsDriver.py MinBias_14TeV_pythia8_TuneCP5_cfi --conditions auto:phase2_realistic_T21 -n 100 --era Phase2C11I13M9 --eventcontent FEVTDEBUG -s GEN,SIM --datatier GEN-SIM --beamspot HLLHC14TeV --geometry Extended2026D76 --python MinBias_14TeV_pythia8_TuneCP5_2026D76_GenSimHLBeamSpot14.py --customise SLHCUpgradeSimulations/Configuration/aging.customise_aging_1000 --no_exec --fileout file:minbias.root --nThreads 8 --mc

cmsDriver.py TTbar_14TeV_TuneCP5_cfi --conditions auto:phase2_realistic_T21 -n 10 --era Phase2C11I13M9 --eventcontent FEVTDEBUG -s GEN,SIM --datatier GEN-SIM --beamspot HLLHC14TeV --geometry Extended2026D76 --python TTbar_14TeV_TuneCP5_2026D76_GenSimHLBeamSpot14.py --customise SLHCUpgradeSimulations/Configuration/aging.customise_aging_1000 --no_exec --fileout file:ttbar.root --nThreads 8 --mc

cmsDriver.py step2 --conditions auto:phase2_realistic_T21 --pileup_input file:minbias.root -n 10 --era Phase2C11I13M9 --eventcontent FEVTDEBUGHLT -s DIGI:pdigi_valid,L1TrackTrigger,L1,DIGI2RAW,HLT:@fake2 --datatier GEN-SIM-DIGI-RAW --pileup AVE_200_BX_25ns --geometry Extended2026D76 --io DigiTriggerPU_2026D76PU.io --python DigiTriggerPU_2026D76PU.py --customise SLHCUpgradeSimulations/Configuration/aging.customise_aging_1000 --no_exec --filein file:ttbar.root --fileout file:step2.root --nThreads 8 --nStreams 1 --mc

Ping @ptcox @dildick by email.
This report is to keep the information, in case we can ignore or can wait for some fixes.

**Comment by makortel** [comment]
assign l1

**Comment by dildick** [comment]
https://github.com/cms-sw/cmssw/pull/34002

**Comment by srimanob** [comment]
I believe this issue is solved. @cms-sw/l1-l2 Could you please consider and sign this ticket? Thanks All.
