### ISSUE TITLE
Inaccessiable EventSetup in ExternalGeneratorFilter

### ISSUE THREAD

**Issue by colizz** [cms-sw/cmssw#34117]
Hi experts,

An error occurs running the GEN step with `ExternalGeneratorFilter`, which acts on `Pythia8GeneratorFilter` with `Tauola` set as the external decayer:

```

----- Begin Fatal Exception 14-Jun-2021 18:15:07 CEST-----------------------
An exception of category 'NoRecord' occurred while
   [0] Processing global begin LuminosityBlock run: 1 luminosityBlock: 1
   [1] Calling method for module Pythia8GeneratorFilter/'generator'
Exception Message:
No "PDTRecord" record found in the EventSetup.n
 Please add an ESSource or ESProducer that delivers such a record.
----- End Fatal Exception -------------------------------------------------
caught exception
An exception of category 'NoRecord' occurred while
   [0] Processing global begin LuminosityBlock run: 1 luminosityBlock: 1
   [1] Calling method for module Pythia8GeneratorFilter/'generator'
Exception Message:
No "PDTRecord" record found in the EventSetup.n
 Please add an ESSource or ESProducer that delivers such a record.

----- Begin Fatal Exception 14-Jun-2021 18:16:07 CEST-----------------------
An exception of category 'ExternalFailed' occurred while
   [0] Processing global begin LuminosityBlock run: 1 luminosityBlock: 1
   [1] Calling method for module ExternalGeneratorFilter/'generator'
Exception Message:
failed waiting for external process. Timed out after 60 seconds.
----- End Fatal Exception -------------------------------------------------

```

By a rough check, the reason may be related to the transfer of EventSetup between the worker and controller instance. A quick example is to run on the process [TAU-RunIISummer19UL16GEN-00003](https://cms-pdmv.cern.ch/mcm/requests?page=0&prepid=TAU-RunIISummer19UL16GEN-00003&shown=127) with `ExternalGeneratorFilter`, shown as follows:

```
export SCRAM_ARCH=slc7_amd64_gcc900
cmsrel CMSSW_12_0_X_2021-06-14-1100
cd CMSSW_12_0_X_2021-06-14-1100/src
cmsenv

curl -s -k https://cms-pdmv.cern.ch/mcm/public/restapi/requests/get_fragment/TAU-RunIISummer19UL16GEN-00003 --retry 3 --create-dirs -o Configuration/GenProduction/python/TAU-RunIISummer19UL16GEN-00003-fragment.py
scram b -j4
cd ../..

cmsDriver.py Configuration/GenProduction/python/TAU-RunIISummer19UL16GEN-00003-fragment.py --python_filename TAU-RunIISummer19UL16GEN-00003_1_cfg.py --eventcontent RAWSIM --customise Configuration/DataProcessing/Utils.addMonitoring --datatier GEN --fileout file:TAU-RunIISummer19UL16GEN-00003.root --conditions 112X_mcRun2_asymptotic_v2 --beamspot Realistic25ns13TeV2016Collision \
 --customise_commands='from GeneratorInterface.Core.ExternalGeneratorFilter import ExternalGeneratorFilter; process.generator = ExternalGeneratorFilter(process.generator)' \
 --step GEN --geometry DB:Extended --era Run2_2016 --no_exec --mc -n 1000

cmsRun TAU-RunIISummer19UL16GEN-00003_1_cfg.py
```

Many thanks for your investigation into this.

**Comment by makortel** [comment]
assign core, generators

**Comment by agrohsje** [comment]
Hi @mkirsano @SiewYan , are you available to follow-up? The problem appears when running tauola as external decayer, there is no problem with evtgen.

**Comment by Dr15Jones** [comment]
The ExternalGeneratorFilter would need a way to pass the configuration of the needed ES modules to the external processes. That is, ES data is not passed from the main process to the worker processes, each worker process would have their own copies of the ES modules. 

The main idea would be to extend the following string to contain the configuration info for the needed ES modules

https://github.com/cms-sw/cmssw/blob/7b669017b222e845be4d2455658a150b2991b704/GeneratorInterface/Core/plugins/ExternalGeneratorFilter.cc#L239-L243

That would probably be done by adding additional special parameters to 

https://github.com/cms-sw/cmssw/blob/master/GeneratorInterface/Core/python/ExternalGeneratorFilter.py

**Comment by colizz** [comment]
Thanks Chris! While studying the implementation of the external cmsRun instance, our concern is that whether the `TestProcessor` that the "external cmsRun" is based on is different from the default cmsRun. As we are not familiar with the TestProcessor, not sure if EventSetup was loaded smoothly in this event routine (the EventSetup part looks pretty at the core and we haven't figured out how it interplays with the event processing). Would you mind helping with the fix if available?

Many thanks;-) Also adding @PhyM73 who was studying the code.

> The ExternalGeneratorFilter would need a way to pass the configuration of the needed ES modules to the external processes. That is, ES data is not passed from the main process to the worker processes, each worker process would have their own copies of the ES modules.
> 
> The main idea would be to extend the following string to contain the configuration info for the needed ES modules
> 
> https://github.com/cms-sw/cmssw/blob/7b669017b222e845be4d2455658a150b2991b704/GeneratorInterface/Core/plugins/ExternalGeneratorFilter.cc#L239-L243
> 
> That would probably be done by adding additional special parameters to
> 
> https://github.com/cms-sw/cmssw/blob/master/GeneratorInterface/Core/python/ExternalGeneratorFilter.py

**Comment by Dr15Jones** [comment]
The documentation on the TestProcessor can be found here
https://github.com/cms-sw/cmssw/tree/master/FWCore/TestProcessor

**Comment by colizz** [comment]
Ok thanks Chris! With your previous comments, do you mean we can send in the ES module name manually (i.e. for this above case we specify 'PDTRecord' manually and somehow pass it to the code block you just show)? If I understand your points correctly then it can be a nice fix.

**Comment by PhyM73** [comment]
> The ExternalGeneratorFilter would need a way to pass the configuration of the needed ES modules to the external processes. That is, ES data is not passed from the main process to the worker processes, each worker process would have their own copies of the ES modules.
> 
> The main idea would be to extend the following string to contain the configuration info for the needed ES modules
> 
> https://github.com/cms-sw/cmssw/blob/7b669017b222e845be4d2455658a150b2991b704/GeneratorInterface/Core/plugins/ExternalGeneratorFilter.cc#L239-L243
> 
> That would probably be done by adding additional special parameters to
> 
> https://github.com/cms-sw/cmssw/blob/master/GeneratorInterface/Core/python/ExternalGeneratorFilter.py

I have found a [discussion](https://hypernews.cern.ch/HyperNews/CMS/get/physTools/1240/2.html) on hypernews about adding empty ESSource. I have tried to add such a patch in `ExternalGeneratorFilter.cc` in a similar way as this discussion:

```cpp
  std::string config = R"_(from FWCore.TestProcessor.TestProcess import *
process = TestProcess()
)_";
  config += "process."s + label + "=" + config_ + "\n";
  std::string emptypdtrecord = R"_(process.PDTRecord = cms.ESSource('EmptyESSource',
    recordName = cms.string('PDTRecord'),
    iovIsRunNotTime = cms.bool(True),
    firstValid = cms.vuint32(1)
)
)_";
  config += emptypdtrecord ;
  config += "process.moduleToTest(process."s + label + ")\n";
  config += R"_(
process.add_(cms.Service("InitRootHandlers", UnloadRootSigHandler=cms.untracked.bool(True)))
  )_";
```

However, this still does not work. But it does take some effects, as the error message changed to the below:

```bash
----- Begin Fatal Exception 15-Jun-2021 18:20:51 CEST-----------------------
An exception of category 'NoProxyException' occurred while
   [0] Processing global begin LuminosityBlock run: 1 luminosityBlock: 1
   [1] Calling method for module Pythia8GeneratorFilter/'generator'
Exception Message:
No data of type "HepPDT::ParticleDataTable" with label "" in record "PDTRecord"
 Please add an ESSource or ESProducer to your job which can deliver this data.
----- End Fatal Exception -------------------------------------------------
globalWaitTask waitted
exception in gloobalWaitTask
caught exception
An exception of category 'NoProxyException' occurred while
   [0] Processing global begin LuminosityBlock run: 1 luminosityBlock: 1
   [1] Calling method for module Pythia8GeneratorFilter/'generator'
Exception Message:
No data of type "HepPDT::ParticleDataTable" with label "" in record "PDTRecord"
 Please add an ESSource or ESProducer to your job which can deliver this data.

0 waiting FAILED
----- Begin Fatal Exception 15-Jun-2021 18:21:46 CEST-----------------------
An exception of category 'ExternalFailed' occurred while
   [0] Processing global begin LuminosityBlock run: 1 luminosityBlock: 1
   [1] Calling method for module ExternalGeneratorFilter/'generator'
Exception Message:
failed waiting for external process
----- End Fatal Exception -------------------------------------------------
```

**Comment by Dr15Jones** [comment]
> Ok thanks @Dr15Jones ! With your previous comments, do you mean we can send in the ES module name manually (i.e. for this above case we specify 'PDTRecord' manually and somehow pass it to the code block you just show)? If I understand your points correctly then it can be a nice fix.

I'm afraid it isn't just the name, you need to specify the configuration for the module just as you would for the Process, e.g.
```python
HepPDTESSource = cms.ESSource("HepPDTESSource",
       pdtFileName = cms.FileInPath('SimGeneral/HepPDTESSource/data/pythiaparticle.tbl')
)
```

**Comment by Dr15Jones** [comment]
@PhyM73 please try using the `HepPDTESSource` example instead of `EmptyESSource`. I'm not sure which file is actually needed for this case.

**Comment by colizz** [comment]
So we eventually make the case run by adding 
```
  config += R"_(
process.add_(cms.Service("InitRootHandlers", UnloadRootSigHandler=cms.untracked.bool(True)))
  )_";
```
Parsing the cfg it looks like HepPDTESSource is the only ESSource relevant to the GEN step.
@PhyM73 will help to finalise on the fix. Thanks so much to @Dr15Jones for the helpful instruction:)

**Comment by Dr15Jones** [comment]
I think it might be possible to modify ExternalGeneratorFilter.py so that one could specify the names of ES modules to use and then during the conversion of python to C++ it would lookup the configuration and pass it to C++.

**Comment by Dr15Jones** [comment]
See #34146. It would be great if someone could test to be sure this change will work for the presently failing case.

**Comment by colizz** [comment]
Many thanks for the fix! Yes the idea is to let users decide which ES modules to pass in (and more broadly, any type of configs can be sent in). We will test the failing case based on #34146.

**Comment by PhyM73** [comment]
> See #34146. It would be great if someone could test to be sure this change will work for the presently failing case.

This is a nice fix ! It works for the present issue by adding the module below
```python
from GeneratorInterface.Core.ExternalGeneratorFilter import ExternalGeneratorFilter
process.generator = ExternalGeneratorFilter(process.generator,
        _external_process_esModules_=cms.vstring("HepPDTESSource"))
```

**Comment by agrohsje** [comment]
@colizz 34146 and this are all ok and tested if I understand you correctly? please confirm. thanks!

**Comment by colizz** [comment]
> @colizz 34146 and this are all ok and tested if I understand you correctly? please confirm. thanks!

Yes they are all tested. We can move forward to merge them:-) 
(#34173 works together with #34146 and they are all well tested)

**Comment by agrohsje** [comment]
+generators

**Comment by makortel** [comment]
+1
