### ISSUE TITLE
Unit Failure in 12_X IB from TauAnalysis/MCEmbeddingTools 

### ISSUE THREAD

**Issue by qliphy** [cms-sw/cmssw#34112]
Since CMSSW_12_0_X_2021-06-13-2300, we have a unit failure from TauAnalysis/MCEmbeddingTools 

https://cmssdt.cern.ch/SDT/cgi-bin/logreader/slc7_amd64_gcc900/CMSSW_12_0_X_2021-06-13-2300/unitTestLogs/TauAnalysis/MCEmbeddingTools#/654-654

>> Tests for package SimTracker/TrackerHitAssociation ran.
....

----- Begin Fatal Exception 14-Jun-2021 01:13:37 CEST-----------------------
An exception of category 'ProductNotFound' occurred while
   [0] Processing  Event run: 274199 lumi: 125 event: 245779397 stream: 0
   [1] Running path 'MINIAODSIMoutput_step'
   [2] Prefetching for module PoolOutputModule/'MINIAODSIMoutput'
   [3] Calling method for module PackedCandidateGenAssociationProducer/'lostTracksToGenAssociation'
Exception Message:
Principal::getByToken: Found zero products matching all criteria
Looking for type: edm::Association<std::vector<reco::GenParticle> >
Looking for module label: prunedGenParticles
Looking for productInstanceName: 

   Additional Info:
      [a] If you wish to continue processing events after a ProductNotFound exception,
add "SkipEvent = cms.untracked.vstring('ProductNotFound')" to the "options" PSet in the configuration.

**Comment by qliphy** [comment]
@elusian    possibly due to https://github.com/cms-sw/cmssw/pull/33774

**Comment by elusian** [comment]
@smuzaffar 
I tried running the test locally to understand precisely what is happening but I cannot find the required input at /store/user/swayand/Emmbeddingfiles/Emmbedding_testInput3.root. Is there a specific configuration I need to use?

**Comment by mmusich** [comment]
@swayand please notice that the input file of the tau embedding unit test might need to be change due to PR https://github.com/cms-sw/cmssw/pull/33774.

@kandrosov @roger-wolf FYI

**Comment by mrodozov** [comment]
hm, if this test was running so far - how it worked in first place and if it did - how this file was read from this private eos area
I'll get it if it was available

**Comment by mmusich** [comment]
@mrodozov I think that's done with the usual trick of changing the eos address at the level of DAS query.
I see that this file exists:
```
/store/user/cmsbuild/store/user/swayand/Emmbeddingfiles/Emmbedding_testInput3.root
```

**Comment by mrodozov** [comment]
thanks @mmusich, took me some time to figure whats going on
@elusian if you want to get/copy the file do (on lxplus !)
`cp /eos/cms/store/user/cmsbuild/store/user/swayand/Emmbeddingfiles/Emmbedding_testInput3.root .`
although I think the file itself has to be recreated

**Comment by elusian** [comment]
@mmusich @mrodozov, thank you.

By reading the config files produced during the test, I believe I have found the issue: since the MERGE_PAT.py file is created with `eventContent MINIAODSIM` the new steps from #33774 are enabled, but by using  `--data` in the invocation the `prunedGenParticles` collection is removed from the tasks. 

The solution is to add the associations to the collections to be removed in https://github.com/cms-sw/cmssw/blob/master/PhysicsTools/PatAlgos/python/tools/coreTools.py.
I'm running some tests, but the PR will come soon.
