### ISSUE TITLE
curl in cmssw-cc6 singularity container is too old

### ISSUE THREAD

**Issue by belforte** [cms-sw/cmssw#34122]
I am moving CRAB to use s3.cern.ch as temporary storage for sandboxes.
For this we upload/download files to/from https://s3.cern.ch using so called PreSigned URLs which require no authentication, so hopefully maximum portability.
But something is wrong with curl on cmssw-cc6 container in SSL/TLS area [1]

Can this be solved ? I presume that it is a matter of curl version. 
Note that e.g. wget works finely [2]

This example [1] uses this URL which will be valid for next 30 days
https://s3.cern.ch/crabcache_preprod/belforte/210615_081425%3Abelforte_crab_20210615_101419/clientlog?AWSAccessKeyId=ab00fcc889f248c495d2875f15a3badb&Expires=1626337148&Signature=wd6mlcl9gWOuWtiHP4Rf6s3%2FRC8%3D

While I can easily use wget for download, I only know how to use curl to do a POST, or at least, I'd like to have same code in all cases. When running new version of CRAB in this container, if fails to POST to
s3.cern.ch (of course) with error [3] which is very similar to [1]. So I presume that if you can fix [1], it will all work.

To give context, I plan to move CRAB to use S3 as part of making CRABClient not depend on
WMCore anymore, so that WMCore will be free to evolve to a python3-only code base, while I
try to keep CRABClient bare-bones enough to run in both python2 and python3.

That plan was mentioned a few time already and @smuzaffar already agreed that using bare `curl` to replace WMCore `pycurl_manager` was a sensible path.

Since I talk about CRAB in cmssw-cc6, I can't help mentioning again that CRAB relies on myproxy-* commands which are not available in that container. There is a workaround (the `--proxy` option in [3]) but of course having myproxy-* in the container would be ideal.

Thanks

[1]

Singularity> curl  "https://s3.cern.ch/crabcache_preprod/belforte/210615_081425%3Abelforte_crab_20210615_101419/clientlog?AWSAccessKeyId=ab00fcc889f248c495d2875f15a3badb&Expires=1626337148&Signature=wd6mlcl9gWOuWtiHP4Rf6s3%2FRC8%3D"
curl: (35) error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version
Singularity> 

[2]
Singularity> wget "https://s3.cern.ch/crabcache_preprod/belforte/210615_081425%3Abelforte_crab_20210615_101419/clientlog?AWSAccessKeyId=ab00fcc889f248c495d2875f15a3badb&Expires=1626337148&Signature=wd6mlcl9gWOuWtiHP4Rf6s3%2FRC8%3D"
--2021-06-15 08:20:55--  https://s3.cern.ch/crabcache_preprod/belforte/210615_081425%3Abelforte_crab_20210615_101419/clientlog?AWSAccessKeyId=ab00fcc889f248c495d2875f15a3badb&Expires=1626337148&Signature=wd6mlcl9gWOuWtiHP4Rf6s3%2FRC8%3D
Resolving s3.cern.ch... 2001:1458:d00:e::100:8, 2001:1458:d00:c::100:7c, 2001:1458:d00:e::100:16c, ...
Connecting to s3.cern.ch|2001:1458:d00:e::100:8|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 16802 (16K) [binary/octet-stream]
Saving to: `clientlog?AWSAccessKeyId=ab00fcc889f248c495d2875f15a3badb&Expires=1626337148&Signature=wd6mlcl9gWOuWtiHP4Rf6s3%2FRC8=.2'

100%[=============================================================================>] 16,802      --.-K/s   in 0s      

2021-06-15 08:20:55 (109 MB/s) - `clientlog?AWSAccessKeyId=ab00fcc889f248c495d2875f15a3badb&Expires=1626337148&Signature=wd6mlcl9gWOuWtiHP4Rf6s3%2FRC8=.2' saved [16802/16802]

Singularity> 

[3]
Singularity> crab submit --proxy=/tmp/x509up_u8516
Will use CRAB configuration file crabConfig.py
Importing CMSSW configuration demoanalyzer.py
Finished importing CMSSW configuration demoanalyzer.py
Impossible to upload the sandbox tarball.
Error message: ('Upload to S3 failed\n%s', 'Failed to upload file. Stderr is:\n* About to connect() to s3.cern.ch port 443 (#0)\n*   Trying 2001:1458:d00:b::100:2fa...\n  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current\n                                 Dload  Upload   Total   Spent    Left  Speed\n\r  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0* connected\n* Connected to s3.cern.ch (2001:1458:d00:b::100:2fa) port 443 (#0)\n* successfully set certificate verify locations:\n*   CAfile: /etc/pki/tls/certs/ca-bundle.crt\n  CApath: none\n* SSLv3, TLS handshake, Client hello (1):\n} [data not shown]\n* error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version\n* Closing connection #0\ncurl: (35) error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version\n').
More details can be found in /afs/cern.ch/work/b/belforte/CRAB3/TC3/crab_20210615_082531/crab.log
Singularity>

**Comment by belforte** [comment]
should you be interested, the command which I use to upload to S3 is like this (as per S3 instructions) which is at least for me, not trivial to recast into a wget equivalent.

```
curl -f -v -X POST  -H "User-Agent: CRAB" -F "key=belforte/sandboxes/afbc3ac91d0644eb32b8b3b361289b9a85cf0cd773e09c1b10e2cdcc0ee9ebe7.tar.gz" -F "AWSAccessKeyId=ab00fcc889f248c495d2875f15a3badb" -F "policy=eyJjb25kaXRpb25zIjogW3siYnVja2V0IjogImNyYWJjYWNoZV9wcmVwcm9kIn0sIHsia2V5IjogImJlbGZvcnRlL3NhbmRib3hlcy9hZmJjM2FjOTFkMDY0NGViMzJiOGIzYjM2MTI4OWI5YTg1Y2YwY2Q3NzNlMDljMWIxMGUyY2RjYzBlZTllYmU3LnRhci5neiJ9XSwgImV4cGlyYXRpb24iOiAiMjAyMS0wNi0xNVQwOToyNTozMloifQ==" -F "signature=l134xk5J3PZ9iORLZR2bueRAh0M=" -F "file=@/afs/cern.ch/work/b/belforte/CRAB3/TC3/crab_20210615_082531/inputs/a9ed3d6d-4bb4-470b-a8fd-c15332fdf227default.tgz" "https://s3.cern.ch/crabcache_preprod"
```
p.s. the signature/policy above was only valid for 1h.

**Comment by belforte** [comment]
Remembering a trick posted some time ago by Bockjo, this works
```
Singularity> source /cvmfs/cms.cern.ch/slc6_amd64_gcc700/external/curl/7.59.0/etc/profile.d/init.sh 
Singularity>  curl "https://s3.cern.ch/crabcache_preprod/belforte/210615_081425%3Abelforte_crab_20210615_101419/clientlog?AWSAccessKeyId=ab00fcc889f248c495d2875f15a3badb&Expires=1626337148&Signature=wd6mlcl9gWOuWtiHP4Rf6s3%2FRC8%3D"
DEBUG 2021-06-15 08:14:18.981 UTC: 	 CRAB Client version: v3.210610
....
```
as @davidlange6 pointed out that source leaves a broken scram environment, but inside a suprocess only used to run curl, should be OK.
Shall I assume that you can not/will not update curl in slc6_amd64_gcc481 but the one in slc6_amd64_gcc700 will stay available in CVMFS as long as there are SL6 CMSSW releases ?

I verified that curl in slc6_amd64_gcc700 works for the POST which I need as well https://github.com/cms-sw/cmssw/issues/34122#issuecomment-861303332

**Comment by smuzaffar** [comment]
@belforte , as we can not change curl in the existsing releases so I would suggest to just create a wrapper script which sources /cvmfs/cms.cern.ch/slc6_amd64_gcc700/external/curl/7.59.0/etc/profile.d/init.sh` and runs your curl command. As this will be done ina subshell so itwill not break the parent scram environmnet,

**Comment by belforte** [comment]
OK. just keep  /cvmfs/cms.cern.ch/slc6_amd64_gcc700/external/curl/7.59.0 around :-)

**Comment by smuzaffar** [comment]
sure, we will keep it around
