### ISSUE TITLE
Profiling for NanoAOD

### ISSUE THREAD

**Issue by silviodonato** [cms-sw/cmssw#34136]
XPOG would like to extend the profiling tests in the PR tests for the NanoAOD.
The main feature to add would be the comparison of the NanoAOD size.

It looks like we have to add step5 in 
in the edmEventSize
https://github.com/cms-sw/cms-bot/blob/master/pr_testing/run-pr-profiling.sh#L44-L48
and here (for IB)
https://github.com/cms-sw/cms-bot/blob/master/run-ib-igprof#L36

@gouskos suggested also to change the cmsDriver command from `--eventcontent NANOEDMAODSIM` to `--eventcontent NANOAODSIM`.

(btw. I see the wf are defined https://github.com/cms-sw/cms-bot/blob/master/cmssw-pr-test-config#L3)

@smuzaffar do you have any suggestion about how to test these changes that we want to implement?

cc @cms-sw/reconstruction-l2

**Comment by silviodonato** [comment]
assign xpog

**Comment by silviodonato** [comment]
I'm trying to add step5 in the file size comparison (cms-sw/cms-bot#1567)
The test is in https://github.com/cms-sw/cmssw/pull/33097

**Comment by mariadalfonso** [comment]
CPU profiling used in some PR already https://github.com/cms-sw/cmssw/pull/34590#issuecomment-886250590

**Comment by mariadalfonso** [comment]
+xpog

**Comment by perrotta** [comment]
already approved by xpog, as nano checks are now also added in the release profiling
