### ISSUE TITLE
Crash in Phase2OTValidateTrackingRecHit in IB

### ISSUE THREAD

**Issue by Dr15Jones** [cms-sw/cmssw#34177]
In this RelVal test

https://cmssdt.cern.ch/SDT/cgi-bin/logreader/cc8_amd64_gcc9/CMSSW_12_0_X_2021-06-17-2300/pyRelValMatrixLogs/run/23234.9_TTbar_14TeV+2026D49_vectorHits+TTbar_14TeV_TuneCP5_GenSimHLBeamSpot14INPUT+DigiTrigger+RecoGlobal+HARVESTGlobal/step3_TTbar_14TeV+2026D49_vectorHits+TTbar_14TeV_TuneCP5_GenSimHLBeamSpot14INPUT+DigiTrigger+RecoGlobal+HARVESTGlobal.log#/82-82

We get a crash with the trace back

```
#4  <signal handler called>
#5  0x00002abd84455a5d in __cxxabiv1::__dynamic_cast (src_ptr=0x0, src_type=0x2abd90fc78e0 <typeinfo for TrackingRecHit>, dst_type=0x2abdae5f5fb8 <typeinfo for SiTrackerMultiRecHit>, src2dst=0) at ../../../../libstdc++-v3/libsupc++/dyncast.cc:50
#6  0x00002abdde5fba22 in TrackerHitAssociator::associateHitId(TrackingRecHit const&, std::vector<std::pair<unsigned int, EncodedEventId>, std::allocator<std::pair<unsigned int, EncodedEventId> > >&, std::vector<std::pair<unsigned int, unsigned int>, std::allocator<std::pair<unsigned int, unsigned int> > >*) const () from /cvmfs/cms-ib.cern.ch/nweek-02685/cc8_amd64_gcc9/cms/cmssw/CMSSW_12_0_X_2021-06-17-2300/lib/cc8_amd64_gcc9/libSimTrackerTrackerHitAssociation.so
#7  0x00002abdde5fcb4c in TrackerHitAssociator::associateHitId(TrackingRecHit const&) const () from /cvmfs/cms-ib.cern.ch/nweek-02685/cc8_amd64_gcc9/cms/cmssw/CMSSW_12_0_X_2021-06-17-2300/lib/cc8_amd64_gcc9/libSimTrackerTrackerHitAssociation.so
#8  0x00002abde7e82939 in Phase2OTValidateTrackingRecHit::fillOTHistos(edm::Event const&, TrackerHitAssociator const&, std::vector<edm::Handle<std::vector<PSimHit, std::allocator<PSimHit> > >, std::allocator<edm::Handle<std::vector<PSimHit, std::allocator<PSimHit> > > > > const&, std::map<unsigned int, SimTrack, std::less<unsigned int>, std::allocator<std::pair<unsigned int const, SimTrack> > > const&) () from /cvmfs/cms-ib.cern.ch/nweek-02685/cc8_amd64_gcc9/cms/cmssw/CMSSW_12_0_X_2021-06-17-2300/lib/cc8_amd64_gcc9/pluginValidationSiTrackerPhase2VAuto.so
#9  0x00002abde7e83b0d in Phase2OTValidateTrackingRecHit::analyze(edm::Event const&, edm::EventSetup const&) () from /cvmfs/cms-ib.cern.ch/nweek-02685/cc8_amd64_gcc9/cms/cmssw/CMSSW_12_0_X_2021-06-17-2300/lib/cc8_amd64_gcc9/pluginValidationSiTrackerPhase2VAuto.so 
```

it crashes while trying to do a dynamic cast

https://github.com/cms-sw/cmssw/blob/6d2f66057131baacc2fcbdd203588c41c885b42c/SimTracker/TrackerHitAssociation/src/TrackerHitAssociator.cc#L343

The cast is being done to the address of a reference type. In C++ it is illegal for a reference to be null so the compiler is allowed to optimize away such checks. From the trace back it looks like the address passed was 0. That address comes from here:

https://github.com/cms-sw/cmssw/blob/72459f6cd02aebe4db1b9ecd5ec33ccddcf3c455/Validation/SiTrackerPhase2V/plugins/Phase2OTValidateTrackingRecHit.cc#L160

I believe this cast failed and then a reference to a nullptr is being passed into the function.

**Comment by qliphy** [comment]
A fix has been provided here:  https://github.com/cms-sw/cmssw/pull/34175

**Comment by makortel** [comment]
assign dqm

(I believe the explanation of the crash in the description is useful also in light of the workaround in #34175).
