### ISSUE TITLE
Failing in L1Trigger/TrackFindingTracklet/src/MatchCalculator.cc

### ISSUE THREAD

**Issue by srimanob** [cms-sw/cmssw#34196]
From the production of Phase-2 using 11_3 release, there seems to be a rare failure coming from
`assert(stub->z() * tracklet->t() > 0.0);`
in https://github.com/cms-sw/cmssw/blob/master/L1Trigger/TrackFindingTracklet/src/MatchCalculator.cc#L350

Actually, I am not sure that you use assert just to debug thing, or want to terminate the CMSSW. I assume if it fails from whatever reasons, it should continue to the next event.

This failure is shown in 
https://cms-unified.web.cern.ch/cms-unified/joblogs/pdmvserv_task_TRK-Phase2D76Spring21GS-00001__v1_T_210614_161715_351/134/TRK-Phase2Spring21DRMiniAOD-00001_0/a3bdae02-7df9-41a7-b282-6ac43179ae51-20-3-logArchive/job/WMTaskSpace/cmsRun1/cmsRun1-stdout.log.trunc.txt

```
Begin processing the 934th record. Run 1, Event 68938, LumiSection 69 on stream 0 at 15-Jun-2021 16:51:45.074 MSK
WARNING dphi and/or dphiapprox too large : -0.262573 0.0517004dphi -0.262573 Seed / ISeed 10
WARNING dphi and/or dphiapprox too large : -0.259616 0.0493037dphi -0.259616 Seed / ISeed 10
cmsRun: /build/cmsbld/jenkins/workspace/auto-builds/CMSSW_11_3_1-slc7_amd64_gcc900/build/CMSSW_11_3_1-build/tmp/BUILDROOT/ebcff69f73237d0d563ea1e7c33f2d83/opt/cmssw/slc7_amd64_gcc900/cms/cmssw/CMSSW_11_3_1/src/L1Trigger/TrackFindingTracklet/src/MatchCalculator.cc:350: void trklet::MatchCalculator::execute(): Assertion `stub->z() * tracklet->t() > 0.0' failed.


A fatal system signal has occurred: abort signal
The following is the call stack containing the origin of the signal.
```

The clone of log is in `/afs/cern.ch/user/s/srimanob/public/ForPhase2SW/11_3_Production/L1TriggerTrackFindingTracklet/`

**Comment by srimanob** [comment]
FYI @skinnari @cecilecaillol @mmusich

**Comment by makortel** [comment]
assign l1

**Comment by srimanob** [comment]
To reproduce the error:

CMSSW_11_3_1_patch1 with cmsDriver

`cmsDriver.py --python_filename test_cfg.py --eventcontent FEVTDEBUGHLT --pileup NoPileUp --customise SLHCUpgradeSimulations/Configuration/aging.customise_aging_1000 --datatier FEVTDEBUGHLT --fileout file:test.root --conditions 113X_mcRun4_realistic_v7 --step DIGI:pdigi_valid,L1TrackTrigger,L1,DIGI2RAW,HLT:@fake2 --nThreads 8 --geometry Extended2026D76 --nStreams 1 --filein "file:/eos/cms/store/user/srimanob/Phase2SW/11_3_Production/L1T/b769e9d8-2c90-40c5-9d7b-acd26d8ef32b.root" --era Phase2C11I13M9 --no_exec --mc -n -1 --customise_commands "process.source.lumisToProcess = cms.untracked.VLuminosityBlockRange('1:69-1:69') \n process.source.eventsToProcess = cms.untracked.VEventRange('1:68930-1:68939')"`

This is the same input as in production.

**Comment by skinnari** [comment]
hi @srimanob , apologies for not addressing this sooner. I have tried to have a look but cannot reproduce it. This is not an issue we have observed before. Is this still an issue?

**Comment by cecilecaillol** [comment]
@srimanob Is it still an issue or can we close it?

**Comment by cecilecaillol** [comment]
+l1

**Comment by qliphy** [comment]
@srimanob   Any comment?

**Comment by srimanob** [comment]
@qliphy 
Sorry, I will not have a chance to look on it until next week. I will close and re-open if I still see issue.
