### ISSUE TITLE
Build SIM geometry from DB

### ISSUE THREAD

**Issue by civanch** [cms-sw/cmssw#34206]
It is necessary to establish build of SIM geometry from DB without use of DDD components and DB records, which are obsolete. Start of the discussion was in #34167

**Comment by civanch** [comment]
+geometry

**Comment by civanch** [comment]
core+

**Comment by civanch** [comment]
assign geometry core

**Comment by civanch** [comment]
assign geometry

**Comment by civanch** [comment]
assign core

**Comment by makortel** [comment]
@cvuosalo, replying here to https://github.com/cms-sw/cmssw/pull/34167#issuecomment-865347335. Thanks for trying out. After further thought I think the following would be (also conceptually) a better version of https://github.com/cms-sw/cmssw/pull/34167#issuecomment-865051930
```py
                    if self.geometryDBLabel:
                        self.executeAndRemember('if hasattr(process, "XMLFromDBSource): process.XMLFromDBSource.label="%s"'%(self.geometryDBLabel))
                        self.executeAndRemember('if hasattr(process, "DDDetectorESProducerFromDB"): process.DDDetectorESProducerFromDB.label="%s"'%(self.geometryDBLabel))
```

**Comment by cvuosalo** [comment]
@makortel Thanks, your new version works, at least so far. There is more to be fixed (see next comment).

**Comment by cvuosalo** [comment]
Request for advice: It looks to me like `Configuration/Geometry/python/GeometryDB_cff.py` needs to be changed to include DDD and DD4hep options. Currently, it contains:
```
from Configuration.Geometry.GeometryRecoDB_cff import *
from Configuration.Geometry.GeometrySimDB_cff import *
```
Those `cff` files currently contain DDD-specific code.

I think `GeometryDB_cff.py` should contain a DDD section and a DD4hep section. In pseudo-code, it might look something like this:
```
from Configuration.ProcessModifiers.dd4hep_cff import dd4hep

# DDD only
from Configuration.Geometry.GeometryRecoDB_cff import *
from Configuration.Geometry.GeometrySimDB_cff import *
# DD4hep only
from Configuration.Geometry.GeometryRecoDBDD4hep_cff import *
from Configuration.Geometry.GeometrySimDBDD4hep_cff import *
```
I think that the `dd4hep.toReplaceWith` syntax could be used to make this choice. Is `GeometryDB_cff.py` the right location to branch between DDD and DD4hep configs?

**Comment by makortel** [comment]
The `dd4hep.toReplaceWith()` should be used for cases where the meaning of a module label is re-defined with another module of the same type (e.g. replace ESProducer with a different ESProducer). The replacement should be done in the (cfi) file that defines the module.

Different sets of cfi/cff files can be loaded into the Process along what I described in https://github.com/cms-sw/cmssw/pull/34167#issuecomment-864333933. Even then I'd recommend to load as small configuration fragments at a time as possible (e.g. I'm a bit concerned that full `GeometryRecoDB_cff` could be too complex). In the end it really depends how many module labels are the same between DDD and DD4Hep setups, and how many are different (as in https://github.com/cms-sw/cmssw/pull/34167#issuecomment-864333933).

**Comment by cvuosalo** [comment]
@makortel Here's what I am trying in `GeometrySimDB_cff.py` (and similarly in `GeometryRecoDB_cff.py`):
```
from Configuration.ProcessModifiers.dd4hep_cff import dd4hep

def _loadGeometryDBDDD(process) :
    process.load('Configuration.Geometry.GeometryDDDSimDB_cff')

def _loadGeometryDBDD4hep(process) :
    process.load('Configuration.Geometry.GeometryDD4hepSimDB_cff')

modifyGeometryConfiguration = (~dd4hep).makeProcessModifier(_loadGeometryDBDDD)
modifyGeometryConfiguration_dd4hep = dd4hep.makeProcessModifier(_loadGeometryDBDD4hep)
```
The cff files that are loaded are about 20 lines long. Is that too complex?

**Comment by cvuosalo** [comment]
Draft PR #34219 submitted for discussion.

**Comment by cvuosalo** [comment]
I have created a possible config for DD4hep sim from the DB. However, it fails with this exception:
```
Running EventSetup component DDCompactViewESProducer/'
Exception Message:
No data of type "DDDetector" with label "" in record "IdealGeometryRecord"
 Please add an ESSource or ESProducer to your job which can deliver this data.
```
It is puzzling, because the configs do contain the needed producers (below). What is missing?
```
process.DDCompactViewESProducer = cms.ESProducer("DDCompactViewESProducer",
    appendToDataLabel = cms.string('')
)
process.DDDetectorESProducerFromDB = cms.ESSource("DDDetectorESProducer",
    appendToDataLabel = cms.string(''),
    fromDB = cms.bool(True),
    label = cms.string('Extended'),
    rootDDName = cms.string('cms:OCMS')
)
```

**Comment by cvuosalo** [comment]
This issue has been resolved. DD4hep workflow 11634.912 reads DD4hep geometry from the DB.

**Comment by cvuosalo** [comment]
+1

**Comment by tvami** [comment]
@cms-sw/core-l2 please sign this issue, since it's been resolved. Thanks!

**Comment by makortel** [comment]
+core
