### ISSUE TITLE
restrict usePF2PAT to load modules already on existing sequences or tasks

### ISSUE THREAD

**Issue by slava77** [cms-sw/cmssw#34254]
currently usePF2PAT loads all modules accessible in `patSequences_cff` to `patAlgoToolsTask` (+pre/post-fix)

https://github.com/cms-sw/cmssw/blob/96b6501ba97b688cbf3559f7322c67976da337de/PhysicsTools/PatAlgos/python/tools/pfTools.py#L407-L421

this may become impossible to maintain if some modules can run only with a specific era or process modifier

One solution could be to restrict the module picked up in https://github.com/cms-sw/cmssw/blob/96b6501ba97b688cbf3559f7322c67976da337de/PhysicsTools/PatAlgos/python/tools/helpers.py#L61-L90 to just the ones already attached to sequences or tasks; perhaps traversing `patDefaultSequence` is enough with `NodeVisitor` 
https://mattermost.web.cern.ch/cms-o-and-c/pl/pi94usrjcp8n5mqzd33d5zmkdc

**Comment by slava77** [comment]
assign reconstruction,xpog

**Comment by vlimant** [comment]
why didn't we move this forward @slava77 ?

**Comment by slava77** [comment]
> why didn't we move this forward @slava77 ?

I don't recall the details.
It could be that reco was waiting for xpog to follow up.

**Comment by slava77** [comment]
> > why didn't we move this forward @slava77 ?
> 
> I don't recall the details. It could be that reco was waiting for xpog to follow up.

apparently initially the context was related to the PAT unit tests 
https://github.com/cms-sw/cmssw/pull/33928#issuecomment-868786345

**Comment by vlimant** [comment]
thanks

**Comment by vlimant** [comment]
please close
