### ISSUE TITLE
Excessive output from DTTSPhi in WF 11634.0

### ISSUE THREAD

**Issue by dildick** [cms-sw/cmssw#34272]
This class https://github.com/cms-sw/cmssw/blob/master/L1Trigger/DTTriggerServerPhi/src/DTTSPhi.cc seems to be producing excessive output through std::cout in WF 11634.0 and other WFs
```
DTTSPhi::addTracoT: preview not present in TRACO trigger or its code=0  trigger not added!
```
Probably should be replaced by edm type log messages.

**Comment by Dr15Jones** [comment]
assign l1

**Comment by dildick** [comment]
That class could probably use a good clean-up. I see pointers that could be replaced by smart pointers

**Comment by davidlange6** [comment]
duplicates #21620 (and possibly others...)

**Comment by smuzaffar** [comment]
duplicate
