### ISSUE TITLE
Crash in Geant4 during early end of job

### ISSUE THREAD

**Issue by Dr15Jones** [cms-sw/cmssw#34271]
In the ARM IBs, we have jobs that end early due to an exception happening at begin run:
e.g. https://cmssdt.cern.ch/SDT/cgi-bin/logreader/slc7_ppc64le_gcc9/CMSSW_12_0_X_2021-06-27-0000/pyRelValMatrixLogs/run/1361.17_GluGluHToZZTo4L_M125_Pow_py8_Evt_13UP17+GluGluHToZZTo4L_M125_Pow_py8_Evt_13UP17+DIGIUP17+RECOUP17+HARVESTUP17+NANOUP17/step1_GluGluHToZZTo4L_M125_Pow_py8_Evt_13UP17+GluGluHToZZTo4L_M125_Pow_py8_Evt_13UP17+DIGIUP17+RECOUP17+HARVESTUP17+NANOUP17.log#/193-193

Those jobs are failing with an segmentation fault in the destructor of a Geant4 object when the job is cleaning up at the end.

**Comment by makortel** [comment]
assign core, simulation

**Comment by Dr15Jones** [comment]
The relevant stack trace is:
```
#3  0x00001000086e8aac in sig_dostack_then_abort () from /cvmfs/cms-ib.cern.ch/week1/slc7_ppc64le_gcc9/cms/cmssw/CMSSW_12_0_X_2021-06-27-0000/lib/slc7_ppc64le_gcc9/pluginFWCoreServicesPlugins.so
#4  <signal handler called>
#5  0x0000100839026c28 in G4VModularPhysicsList::~G4VModularPhysicsList() () from /cvmfs/cms-ib.cern.ch/week1/slc7_ppc64le_gcc9/cms/cmssw/CMSSW_12_0_X_2021-06-27-0000/biglib/slc7_ppc64le_gcc9/pluginSimulation.so
#6  0x0000100838733d04 in PhysicsList::~PhysicsList() () from /cvmfs/cms-ib.cern.ch/week1/slc7_ppc64le_gcc9/cms/cmssw/CMSSW_12_0_X_2021-06-27-0000/biglib/slc7_ppc64le_gcc9/pluginSimulation.so
#7  0x0000100838776e24 in FTFPCMS_BERT_EMM::~FTFPCMS_BERT_EMM() () from /cvmfs/cms-ib.cern.ch/week1/slc7_ppc64le_gcc9/cms/cmssw/CMSSW_12_0_X_2021-06-27-0000/biglib/slc7_ppc64le_gcc9/pluginSimulation.so
#8  0x0000100838645a00 in RunManagerMT::~RunManagerMT() () from /cvmfs/cms-ib.cern.ch/week1/slc7_ppc64le_gcc9/cms/cmssw/CMSSW_12_0_X_2021-06-27-0000/biglib/slc7_ppc64le_gcc9/pluginSimulation.so
#9  0x000010083866259c in std::_Sp_counted_ptr_inplace<RunManagerMT, std::allocator<RunManagerMT>, (__gnu_cxx::_Lock_policy)2>::_M_dispose() () from /cvmfs/cms-ib.cern.ch/week1/slc7_ppc64le_gcc9/cms/cmssw/CMSSW_12_0_X_2021-06-27-0000/biglib/slc7_ppc64le_gcc9/pluginSimulation.so
#10 0x000010083863e878 in OscarMTMasterThread::stopThread() () from /cvmfs/cms-ib.cern.ch/week1/slc7_ppc64le_gcc9/cms/cmssw/CMSSW_12_0_X_2021-06-27-0000/biglib/slc7_ppc64le_gcc9/pluginSimulation.so
#11 0x000010083866909c in OscarMTProducer::globalEndJob(OscarMTMasterThread*) () from /cvmfs/cms-ib.cern.ch/week1/slc7_ppc64le_gcc9/cms/cmssw/CMSSW_12_0_X_2021-06-27-0000/biglib/slc7_ppc64le_gcc9/pluginSimulation.so
```

I believe the problem is here:
https://github.com/cms-externals/geant4/blob/0f6c7dd7bcf054e57fdc34da9b4696fce5c6ac90/source/run/src/G4VModularPhysicsList.cc#L65-L73

there is no guarantee that the value associated with `G4MT_physicsVector` is actually not nullptr as that value is not being set in the constructor. So a simple `if(G4MT_physicsVector)` around the code should solve the crash.

**Comment by civanch** [comment]
@Dr15Jones , you analysis seems to be correct. I can make a patch for Geant4 10.7p02, which is used currently inside GEANT4 IBs but not yet in the master, because is not yet validated. Also will make bug report to Geant4. Would it be fine to you? In that case, the master will not have the fix for some time.

**Comment by Dr15Jones** [comment]
@civanch sounds fine to me.

**Comment by VinInn** [comment]
I would remove the clear before the delete as well....

**Comment by civanch** [comment]
sure!

**Comment by VinInn** [comment]
and whatever syntax is used would be better to align to the code at line 97

**Comment by civanch** [comment]
The fix is merged to Geant4 repository and merged to cms-externals/geant4 in the v10.7.2 branch.

**Comment by civanch** [comment]
+1

**Comment by makortel** [comment]
+core
