### ISSUE TITLE
[Low priority] Change cout to LogTrace in HcalLayerDepthMap.cc

### ISSUE THREAD

**Issue by cvuosalo** [cms-sw/cmssw#34294]
`Geometry/​HcalCommonData/​src/​HcalLayerDepthMap.cc` has `cout` statements in its `EDM_ML_DEBUG` sections. It would be better to use `LogTrace` or `LogVerbatim` so these debug messages could be better controlled.

Also, the `getDepth16` and `getDepthMax` debug messages can look like errors to the non-expert. The message content should make clear they are reporting expected conditions.

This issue is not urgent. It is low priority, to be resolved when an opportunity arises.

**Comment by cvuosalo** [comment]
assign geometry

**Comment by civanch** [comment]
@bsunanda , this likely was fixed?

**Comment by bsunanda** [comment]
Hi Vladimir

I just submitted a PR #36372 to fix this. I overlooked that report. Regards

Sunanda
________________________________

**Comment by cvuosalo** [comment]
Resolved by #36372.

**Comment by cvuosalo** [comment]
+1
