### ISSUE TITLE
Flood of L1T warnings in wf 138.2

### ISSUE THREAD

**Issue by mmusich** [cms-sw/cmssw#34309]
I noticed that in the IB logs for [wf 138.2](https://cmssdt.cern.ch/SDT/cgi-bin/buildlogs/slc7_amd64_gcc900/CMSSW_12_0_X_2021-06-30-1100/pyRelValMatrixLogs/run/138.2_RunCosmics2020+RunCosmics2020+RECOCOSDEXPRUN3+ALCACOSDEXPRUN3+HARVESTDCEXPRUN3/step2_RunCosmics2020+RunCosmics2020+RECOCOSDEXPRUN3+ALCACOSDEXPRUN3+HARVESTDCEXPRUN3.log) (MWGR 2020 cosmics with Run3 era), there is a flood of warnings coming from the L1TRawToDigi:

```
%MSG-w L1T:  L1TRawToDigi:caloLayer1Digis 01-Jul-2021 17:40:28 CEST  Run: 338714 Event: 2787853
CaloLayer1Setup: unexpected CTP7 firmware ID, will try unpacking with default unpacker anyway
%MSG
```

**Comment by makortel** [comment]
assign l1

**Comment by mmusich** [comment]
wondering if in the last 25 days anything has been checked. Seems the flood is still [there](https://cmssdt.cern.ch/SDT/cgi-bin/buildlogs/slc7_amd64_gcc10/CMSSW_12_0_X_2021-07-26-2300/pyRelValMatrixLogs/run/138.2_RunCosmics2020+RunCosmics2020+RECOCOSDEXPRUN3+ALCACOSDEXPRUN3+HARVESTDCEXPRUN3/step2_RunCosmics2020+RunCosmics2020+RECOCOSDEXPRUN3+ALCACOSDEXPRUN3+HARVESTDCEXPRUN3.log)

**Comment by boudoul** [comment]
Hi @rekovic,@cecilecaillol - reconstructing/working on the CRUZET data is really painful due to this flood of these warning messages. Could you please take action ? 
Also adding  @dinyar , @bundocka, @varuns23  in case they can help here. Thank you .

**Comment by dinyar** [comment]
Hi! 

The offending line [1] seems to be more than two years old, so I'm wondering if the firmware changed recently and is causing this issue.

Cheers,
Dinyar

[1] https://github.com/cms-sw/cmssw/blame/master/EventFilter/L1TRawToDigi/plugins/implementations_stage2/CaloLayer1Setup.cc#L82

**Comment by mmusich** [comment]
in addition, there is also a staggering amount of:
```
%MSG-w L1T:  L1TRawToDigi:emtfStage2Digis 13-Aug-2021 03:44:19 CEST  Run: 343498 Event: 18785284
EMTF unpacked duplicate GEM digis: BX 4, endcap 1, station 1, neighbor 0, ring 1, chamber 5, roll 7, pad 511
%MSG
```

**Comment by dinyar** [comment]
> in addition, there is also a staggering amount of:
> 
> ```
> %MSG-w L1T:  L1TRawToDigi:emtfStage2Digis 13-Aug-2021 03:44:19 CEST  Run: 343498 Event: 18785284
> EMTF unpacked duplicate GEM digis: BX 4, endcap 1, station 1, neighbor 0, ring 1, chamber 5, roll 7, pad 511
> %MSG
> ```

Maybe @eyigitba or @dildick can comment on or fix this.

**Comment by eyigitba** [comment]
> in addition, there is also a staggering amount of:
> 
> ```
> %MSG-w L1T:  L1TRawToDigi:emtfStage2Digis 13-Aug-2021 03:44:19 CEST  Run: 343498 Event: 18785284
> EMTF unpacked duplicate GEM digis: BX 4, endcap 1, station 1, neighbor 0, ring 1, chamber 5, roll 7, pad 511
> %MSG
> ```

This warning is due to the EMTF unpacker. Unfortunately there are still some problems with the GEM TPs we receive at EMTF. We need to debug this some time after we confirm that we are getting the correct data format on correct links from GEMs. The duplicates are being discarded correctly at the unpacker so it shouldn't create problems downstream. For now, we can disable this warning, but there is nothing else we can do.

**Comment by mmusich** [comment]
> We can disable this warning if you prefer.

That'd be highly desirable to avoid clogging the logs. I think there are ways to avoid having to print always the same message at all events, but just few times and collect the total at the end of the job.

**Comment by mmusich** [comment]
> so I'm wondering if the firmware changed recently and is causing this issue.

Who can investigate that?

**Comment by dinyar** [comment]
I think @varuns23 is the right person.

**Comment by tvami** [comment]
Hi @varuns23 have you had the chance to look into this?

**Comment by tvami** [comment]
Hi @qliphy @perrotta since L1 is not very responsive here (might be due to August being holiday season), could this be discussed at the ORP meeting tomorrow? Would be nice to get this fixed for a possible CRUZET ReRECO. Thanks!

**Comment by qliphy** [comment]
> Hi @qliphy @perrotta since L1 is not very responsive here (might be due to August being holiday season), could this be discussed at the ORP meeting tomorrow? Would be nice to get this fixed for a possible CRUZET ReRECO. Thanks!

Sure,  added to the google spreadsheet

**Comment by francescobrivio** [comment]
>  We can disable this warning if you prefer, but there is nothing else we can do for now.

@eyigitba Since this seems the preferred solution for the moment, who is it going to actually implement the suggestion from Marco in https://github.com/cms-sw/cmssw/issues/34309#issuecomment-898433435 ?

**Comment by eyigitba** [comment]
I'm still on vacation, but I'll see if I can do it by the end of this week.

**Comment by tvami** [comment]
Hi @eyigitba I think here is an example for the SiStrips where they are doing something similar that you need, i.e. collect the warning and have a summary in the end: 
https://github.com/cms-sw/cmssw/blob/master/EventFilter/SiStripRawToDigi/plugins/WarningSummary.cc

If you could implement something similar by next Monday, then that would still fit into the deadline.

**Comment by tvami** [comment]
Hi @eyigitba I think the online machines are about to install 12_0_X as a preparation for CRAFT. So this is becoming urgent again. Do you maybe have an update on the final solution to this issue, to be included in the 12_0_X release?

**Comment by eyigitba** [comment]
Hi @tvami , I don't have a final solution at this moment. I looked into the solution you posted, but implementing something similar to that (end of run/stream warning summary) is not trivial apparently. I brought this up in the L1T offline software meeting and maybe they will implement something like that for the entire L1TRawToDigi package.

**Comment by tvami** [comment]
Ok, do you think that this development is feasible in about the next 10 days? If not we should do the comment out solution to 12_0_X

**Comment by eyigitba** [comment]
I'm not sure, but I doubt it will be done in 10 days. @rekovic can maybe comment on this. If it can't be done soon I can submit a backport PR to 12_0_X as well.

**Comment by tvami** [comment]
Hi @eyigitba what is the status of this issue? Has the source of the problem been resolved for test beam data? If not, have you had the chance to work out the proper solution (in the end I remembered this not 10 days later but 21 days later :P ) ? If not to that too, we should just submit the dirty solution of the commenting out the code asap...

**Comment by tvami** [comment]
assign alca
 * so that I dont forget about this

**Comment by eyigitba** [comment]
Hi @tvami , I forgot to follow up on this. To my knowledge the situation is not fixed on the firmware side yet and since I haven't heard back from L1T offline software I doubt a permanent solution is already implemented in L1T unpackers. Should I submit a backport with the "dirty" solution for now?

**Comment by tvami** [comment]
> To my knowledge the situation is not fixed on the firmware side yet and since I haven't heard back from L1T offline software I doubt a permanent solution is already implemented in L1T unpackers. 

:( 

> Should I submit a backport with the "dirty" solution for now?

Yes please, thank you!

**Comment by eyigitba** [comment]
The backport will be to 12_0_X, right?

**Comment by tvami** [comment]
unassign alca
 * now all the possible releases around (11_3, 12_0, 12_1, and future) have the dirty fix for this
 * we proposed a solution for long term in https://github.com/cms-sw/cmssw/issues/34309#issuecomment-908437144 about a month ago
 * from this on, there is no other AlCa interest in here, thanks @eyigitba for your responses and fixes

**Comment by perrotta** [comment]
@mmusich after merging of #35940 in the master and #35877 in CMSSW_12_0_X I think this can be closed

**Comment by mmusich** [comment]
@perrotta what about 12.1.x? Isn't there a plan to process global run data with that?

**Comment by perrotta** [comment]
> @perrotta what about 12.1.x? Isn't there a plan to process global run data with that?

Uhm... maybe not, but it costs nothing backporting #35940 (from @BenjaminRS) to CMSSW_12_1_X
I have prepared #35980, identical to the PR in master: it can be merged as soon as the tests finish, and therefore enter the forthcoming CMSSW_12_1_0

**Comment by mmusich** [comment]
Thanks
