### ISSUE TITLE
uploadConditions.py is broken in recent IBs

### ISSUE THREAD

**Issue by mmusich** [cms-sw/cmssw#34349]
```
$ uploadConditions.py SiPixelGainCalibration_2021_v0_full.db
Traceback (most recent call last):
  File "/cvmfs/cms-ib.cern.ch/nweek-02688/slc7_amd64_gcc900/cms/cmssw/CMSSW_12_0_X_2021-07-06-0300/bin/slc7_amd64_gcc900/uploadConditions.py", line 25, in <module>
    import cx_Oracle
ImportError: No module named cx_Oracle
```

related to py3 migration?

**Comment by davidlange6** [comment]
looks like it. I gather there is no unit test coverage for this script..

**Comment by mmusich** [comment]
>  I gather there is no unit test coverage for this script..

looks like not. 
OTOH, I presume one doesn't want to actually upload to DB every time the test is exercised.

**Comment by davidlange6** [comment]
Could you change /usr/bin/env python to /usr/bin/env python3 and confirm that it works?

**Comment by smuzaffar** [comment]
correct `cx_Oracle` is available for python3 only, so try using python3

**Comment by smuzaffar** [comment]
@ggovi also reported the same issue for `conddb --db oradev -a /build/gg list runinfo_31X_mc` but this was only in `CMSSW_12_0_X_2021-07-01-2300` IB where condb was using `#!/usr/bin/env python`

**Comment by davidlange6** [comment]
I’ll make a PR changing all the scripts in CondCore

**Comment by mmusich** [comment]
> Could you change /usr/bin/env python to /usr/bin/env python3 and confirm that it works?

it doesn't.
With:
```diff
diff --git a/CondCore/Utilities/scripts/uploadConditions.py b/CondCore/Utilities/scripts/uploadConditions.py
index 25f57d30c27..73b0bc2ff06 100755
--- a/CondCore/Utilities/scripts/uploadConditions.py
+++ b/CondCore/Utilities/scripts/uploadConditions.py
@@ -1,4 +1,4 @@
-#!/usr/bin/env python
+#!/usr/bin/env python3
 '''Script that uploads to the new CMS conditions uploader.
 Adapted to the new infrastructure from v6 of the upload.py script for the DropBox from Miguel Ojeda.
 '''
```
I get

```
$ uploadConditions.py SiPixelGainCalibration_2021_v0_full.db                                                                                                                          Traceback (most recent call last):
  File "/tmp/musich/vanilla/CMSSW_12_0_X_2021-07-06-1100/bin/slc7_amd64_gcc900/uploadConditions.py", line 46, in <module>
    import cStringIO
ModuleNotFoundError: No module named 'cStringIO'
```

**Comment by davidlange6** [comment]
One doesn’t have to upload to a db that persists for more than the length of the test or do you?  But indeed if there is no support for uploading to some file based or otherwise fake db , it would mean having a bit of infrastructure behind..

**Comment by davidlange6** [comment]
Yea, cStringIO is gone in python3.  You probably need

```from io import StringIO```

**Comment by mmusich** [comment]
>   But indeed if there is no support for uploading to some file based or otherwise fake db , it would mean having a bit of infrastructure behind..

at the moment I think one can just either upload to the production or to the preparation db, I am not totally sure uploading to a local sqlite file would test all the functionalities. For sure one can make a simple test just running the wizard in order to spot wrong includes or something like that.
I let @ggovi to comment more.

**Comment by ggovi** [comment]
@davidlange6  thanks ,a PR is almost ready, i'm about to submit it...

**Comment by davidlange6** [comment]
Sorry, 
```from io import StringIO as cStringIO```

If you don’t want to change code below

**Comment by davidlange6** [comment]
Funny, I thought I fixed these things years ago.. Seems I missed these

raw_input is also gone in python3. 

answer = input(prompt)

Is likely sufficient.

**Comment by davidlange6** [comment]
> On Jul 6, 2021, at 3:04 PM, David Lange ***@***.***> wrote:
> 
> 
> Funny, I thought I fixed these things years ago.. Seems I missed these 

Correction, I obviously didn’t actually fix cStringIO or raw_input in CMSSW.  I’m rather surprised that none of the users of cStringIO are found in the PY3 unit tests

**Comment by smuzaffar** [comment]
@davidlange6 , I think unit tests are py3 compatible. This `uploadConditions.py` is part of `scripts` directory and is never run during IB tests

**Comment by mmusich** [comment]
> Is likely sufficient.

It does work (sort of), for some reason the wizard doesn't recognize yet the internal list of tags present in the input sqlite file, but if it's prompted by the user it does work....

**Comment by davidlange6** [comment]
Yes, bad luck it seems.

**Comment by davidlange6** [comment]
Is that something done via the cx-oracle package or something in cmssw?

**Comment by mmusich** [comment]
> Is that something done via the cx-oracle package or something in cmssw?

I am chairing a meeting now, I'll investigate later.
I am tagging also @MuhammadHasib and @Dres90 in case they more readily know

**Comment by ggovi** [comment]
@mmusich @davidlange6 as I said  i have a fix for that issue, i'm currently working to migrate the pycurl related code...

**Comment by ggovi** [comment]
@mmusich hasib left CMS more than one year ago...

**Comment by mmusich** [comment]
@ggovi he just wrote me he has a py3 version of the script in skype chat :)

**Comment by ggovi** [comment]
addressed by https://github.com/cms-sw/cmssw/pull/34373

**Comment by tvami** [comment]
assign alca

**Comment by tvami** [comment]
+alca

**Comment by mmusich** [comment]
I think it should be actually assigned db...

**Comment by qliphy** [comment]
https://github.com/cms-sw/cmssw/issues/34349#issuecomment-875448535
@ggovi  is for db, so should be fine to close this issue.

**Comment by mmusich** [comment]
@qliphy there is still the question of the unit test PR at https://github.com/cms-sw/cmssw/pull/34379 which is not signed by db...

**Comment by qliphy** [comment]
> @qliphy there is still the question of the unit test PR at #34379 which is not signed by db...

Sorry for missing this.

**Comment by qliphy** [comment]
assign db

**Comment by ggovi** [comment]
+1

**Comment by qliphy** [comment]
> #34379

@cms-sw/db-l2  Would you please check #34379 ?
