### ISSUE TITLE
HLT validation tests

### ISSUE THREAD

**Issue by smuzaffar** [cms-sw/cmssw#34387]
HLT validation results on IB page are now marked failed if bot finds any tests exiting with non-zero status (
As reported https://github.com/cms-sw/cmssw/pull/34231#issuecomment-874499308 ). 

@Martin-Grunewald we are running HLT tests for all IBs (5.3.X to latest 12.0.X) and it is failing in few of the release cycles e.g. `5.3.X, 7.1.X, 8.0.X and 10.6.X`. Can we stop it for old release cycles?

**Comment by smuzaffar** [comment]
assign hlt

**Comment by fwyzard** [comment]
For what release cycles do we expect to run step2 / step3 MC production in the future ?

**Comment by Martin-Grunewald** [comment]
What happened, the link to the "HLT Validation Tests" has disappeared from the IB pages: 
https://cmssdt.cern.ch/SDT/html/showIB.html 
??

**Comment by makortel** [comment]
> What happened, the link to the "HLT Validation Tests" has disappeared from the IB pages:
> https://cmssdt.cern.ch/SDT/html/showIB.html

That is the (very) old version of the IB pages. The HLT tests are shown in the current IB pages https://cmssdt.cern.ch/SDT/html/cmssdt-ib under the name "HLT" (and it is currently showing failure that is different from https://github.com/cms-sw/cmssw/pull/34231#issuecomment-874789622)

@smuzaffar Should we think of removing the old IB pages to avoid confusion?

**Comment by smuzaffar** [comment]
yes it is time to get rid of old page (which is not maintained any more). I will announce it to HN and set a apache redirection to go to the new Ib pages

**Comment by Martin-Grunewald** [comment]
OK, I'll have a look and submit PRs where needed.

**Comment by Martin-Grunewald** [comment]
Partial fix for 80X: https://github.com/cms-sw/cmssw/pull/34484
(Other problems in 80X seem to be genuine, need to investigate)

**Comment by smuzaffar** [comment]
@Martin-Grunewald , HLT tests run for all release cycles. Can we stop runing these tests for old release cycles e.g. 5.3.X up to 10.X?

**Comment by Martin-Grunewald** [comment]
Hmm, why? Any specific reason? 
(I'd like keep them alive for all open releases with IBs - but am always in favor of closing releases!)

**Comment by smuzaffar** [comment]
Takes a lot of build resources (e.g. over 3 hours per IB on a 24 core machine). Although we do not build older release cycles every day but on Sunday (when we force build all IBs) it slows down the builds.

**Comment by Martin-Grunewald** [comment]
Well, I would be in favor of closing more currently active CMSSW releases to lighten the load, but if it helps then ok, stop the tests for old releases but keep them for 11 and up.

**Comment by smuzaffar** [comment]
Coming back to this, last week during [Core SW meeting](https://indico.cern.ch/event/1226629/) we discussed this again and would like to stop HLT tests for CMSSW 5.X till 10.X release cycles. This will still leave 10 releases cycles (11.0.X up to 13.0.X) for which we will run HLT tests. By the way, in old release cycles this test was taking 2-3 hours on 24 code nodes but now it takes [7 to 8 hours on 32 core HTCondor nodes](https://es-cmssdt.cern.ch/kibana/app/kibana#/discover?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:now-8w,to:now))&_a=(columns:!(parameter_RELEASE_QUEUE,parameter_ARCHITECTURE,slave_node,build_duration),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!f,index:'3fc29390-88a1-11ea-8096-bf2a4db063ef',key:job_name,negate:!f,params:(query:ib-run-HLT),type:phrase,value:ib-run-HLT),query:(match:(job_name:(query:ib-run-HLT,type:phrase))))),index:'3fc29390-88a1-11ea-8096-bf2a4db063ef',interval:auto,query:(language:kuery,query:''),sort:!('@timestamp',desc))) . Are we sure all these HLT tests are properly utilizing the resources and are running in parallel ?

**Comment by Martin-Grunewald** [comment]
Hmm, I see your point but would rather we close some old(er) CMSSW release cycles for good! Has this option been looked at? Once could always re-activate them in case of need (and then with HLT tests still there to make sure things work).

**Comment by Martin-Grunewald** [comment]
Hmm, we'd need to keep for all the releases used in data taking, and for which MC production is run, ie, in the end all releases which are kept alive (assuming that's the reason we keep releases alive?).

**Comment by smuzaffar** [comment]
closing this
- many IBs were disabled
- IB build frequency for old release cycles were reduced
- HLT tests now take 3-4 hours after https://github.com/cms-sw/cmssw/issues/42988
