### ISSUE TITLE
Upper bin edge included when evaluating JEC when using non-linear lookup

### ISSUE THREAD

**Issue by kirschen** [cms-sw/cmssw#34381]
Discovered an inconsistency between the current non-linear lookup of bin indices and both

1. the previous "legacy" linear index search JetCorrectorParameters::binIndex()
2. the correctionlib implementation for interpreting the JSON files 

It seems like this boils down to including the upper bin edge in the non-linear search
https://github.com/cms-sw/cmssw/blob/a59283f45c8b5becca6cff5e643687c6241343a3/CondFormats/JetMETObjects/src/JetCorrectorParametersHelper.cc#L135
vs. excluding it in the linear search and correctionlib
https://github.com/cms-sw/cmssw/blob/a59283f45c8b5becca6cff5e643687c6241343a3/CondFormats/JetMETObjects/src/JetCorrectorParameters.cc#L190

@aperloff : Can you confirm? Will put in a tiny PR fixing the inclusion of the upper bin edge it but would be good to get your confirmation.

**Comment by kirschen** [comment]
And just for reference: This really only affects the outermost upper bin edge (e.g. for eta-binned corrections usually eta=5.191), so just a nuance, but better to fix if it's easily fixable (which it is).
FYI: @juska @tankit @camclean @lathomas @nsmith-

**Comment by makortel** [comment]
assign db

FYI @cms-sw/reconstruction-l2 (not sure who else should be made aware)

**Comment by ggovi** [comment]
addressed by https://github.com/cms-sw/cmssw/pull/34382 ?

**Comment by perrotta** [comment]
@kirschen please confirm that the issue is solved by #34382, and close this github issue if so

**Comment by kirschen** [comment]
Indeed solved by #34382. Closing...
