### ISSUE TITLE
Confusion in sequence when neither "--data" nor "--mc" is used

### ISSUE THREAD

**Issue by srimanob** [cms-sw/cmssw#34443]
We started to spot the issue when neither "--data" nor "--mc" is used. CMSSW normally guess using
https://github.com/srimanob/cmssw/blob/master/Configuration/Applications/python/cmsDriverOptions.py#L214-L235

The issue happened when it guesses as a data workflow, however, nothing (e.g. isData) is set after that. When we make a workflow with, i.e.
`cmsDriver.py RECO --conditions 106X_dataRun2_v35 --customise Configuration/DataProcessing/Utils.addMonitoring --datatier NANOAOD --era Run2_2018,run2_nanoAOD_106Xv2 --eventcontent NANOEDMAOD --filein placeholder.root --fileout file:ReReco-Run2018C-JetHT-UL2018_MiniAODv2_NanoAODv9_pilot-00001.root --nThreads 2 --no_exec --python_filename ReReco-Run2018C-JetHT-UL2018_MiniAODv2_NanoAODv9_pilot-00001_0_cfg.py --scenario pp --step NANO`
it will guess it is data workflow, but pick up MC customization. The issue is not only on NanoAOD, Mini will be the same.

The PR https://github.com/cms-sw/cmssw/pull/34302 introduces a fix. 

However, when we start to set isData properly, we start to see a failure in IB test. The issue come from DQM validation sequence, as reported in https://github.com/cms-sw/cmssw/issues/34438
In short, the validation sequence try to run
`cmsDriver.py step3 --conditions auto:run2_data -s VALIDATION --process DUMMY --eventcontent DQM --datatier DQMIO --customise_commands 'process.Tracer = cms.Service("Tracer")' --filein file:/eos/cms/store/data/Run2018A/EGamma/RAW/v1/000/315/489/00000/004D960A-EA4C-E811-A908-FA163ED1F481.root -n 10 --python_filename cmssw_cfg.py --no_exec`
which is data workflow. However, MC sequence is picked including pileup replay. Config can be dumped, but it does not make sense. The dump step will fail when "--data" or "isData" is used.

It seems the test of DQM sequence should be reviewed first to avoid broken in data workflow. Then we can apply  https://github.com/cms-sw/cmssw/pull/34302 again, to make mini/nano data workflow properly when it comes from CMSSW guess.

**Comment by qliphy** [comment]
assign dqm,xpog

**Comment by jfernan2** [comment]
@srimanob I have been looking into this but my knowledge of the PdmV configs from cmsDriver is limited.
Nevertheless, enabling your PR #34302 and doing a print before the processing of the 10 sequences crashing in:
https://github.com/cms-sw/cmssw/blob/master/DQMOffline/Configuration/scripts/cmsswSequenceInfo.py#L530

after scram b runtests_TestDQMOfflineConfiguration_110

I get:

Config file cmssw_cfg.py created
[Sequence(seqname='@miniAODValidation', step='VALIDATION', era='Phase2C11I13T25M9', scenario='', mc=False, data=False, fast=False), Sequence(seqname='@miniAODValidation', step='VALIDATION', era='Phase2C11I13T26M9', scenario='', mc=False, data=False, fast=False), Sequence(seqname='@miniAODValidation', step='VALIDATION', era='Phase2C9', scenario='', mc=False, data=False, fast=False), Sequence(seqname='@miniAODValidation', step='VALIDATION', era='Run2_2016', scenario='', mc=False, data=False, fast=False), Sequence(seqname='@miniAODValidation', step='VALIDATION', era='Run2_2016', scenario='pp', mc=True, data=False, fast=False), Sequence(seqname='@miniAODValidation', step='VALIDATION', era='Run2_2016,run2_miniAOD_80XLegacy', scenario='pp', mc=True, data=False, fast=False), Sequence(seqname='@miniAODValidation', step='VALIDATION', era='Run2_2016_HIPM', scenario='', mc=False, data=False, fast=False), Sequence(seqname='@miniAODValidation', step='VALIDATION', era='Run2_2016_HIPM', scenario='pp', mc=True, data=False, fast=False), Sequence(seqname='@miniAODValidation', step='VALIDATION', era='Run2_2016_trackingLowPU', scenario='', mc=False, data=False, fast=False), Sequence(seqname='@miniAODValidation', step='VALIDATION', era='Run2_2017', scenario='', mc=False, data=False, fast=False)]
Analyzing 10 seqs...

So, it looks like there are several sequences with mc=False and data=False at the same time...Is this expected?

**Comment by srimanob** [comment]
Hi @jfernan2 
I don't have an idea why it is not set properly. Do you know how these workflows have been selected? 

However, the clues I have include
1. The input and GT used in DQM sequence validation is just a dummy. Since we don't work on physics result with it. 
2. With validation sequence only, CMSSW will guess it is a data workflow. However, it will pick up MC sequence because isData is not set after the guess.
3. miniaodAalidation will not work with data. Current things work because of (2).

The fix I propose in https://github.com/cms-sw/cmssw/pull/34452 include

1. Assign properly "isData" when it is data workflow
2. Removing mixing reply when the workflow is data
3. Add miniaodValdiation and Phase2 as a "temporary" check for MC. This I can disable when I know how to access the test workflow of DQM, and define properly what the workflow should be.

**Comment by jfernan2** [comment]
Your solution seems fine to me, thanks!

I would not consider them selected workflows but module/sequences coming from a full runTheMatrix inspection. They are part of the UnitTests under DQMOffline/Configuration/test which just grabs any DQM,Validation module/sequence to check its validity:

https://github.com/cms-sw/cmssw/blob/master/DQMOffline/Configuration/test/runtests.sh#L23

Legacy modules are stripped and then the full list of sequences is splitted in chuncks to run them
https://github.com/cms-sw/cmssw/blob/master/DQMOffline/Configuration/test/BuildFile.xml

**Comment by srimanob** [comment]
@cms-sw/dqm-l2 

Could you please confirm the statement in
https://github.com/cms-sw/cmssw/pull/34452#discussion_r668763406 ?

For step:
- VALIDATION => MC
- VALIDATION + DQM => MC
- DQM => Data
?

Thanks in advance.

**Comment by mariadalfonso** [comment]
type jet

**Comment by mariadalfonso** [comment]
This explicit --data and  --mc is only needed by the MET sequence.

Suggest to review the METcode such that like ANY other object doesn't rely on external switches

**Comment by vlimant** [comment]
+1
we took note of the MET configuration that needs cleaning
