### ISSUE TITLE
RelMon PR comparisons different from before

### ISSUE THREAD

**Issue by makortel** [cms-sw/cmssw#34445]
It seems to me that there is still something fishy with the RelMon PR comparisons (following https://github.com/cms-sw/cmssw/pull/34440 and https://github.com/cms-sw/cmssw/pull/34338#issuecomment-877651086).

E.g. in https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_12_0_X_2021-07-11-2300+5c6882/44008/validateJR.html following link to 4.22 brings a page https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_12_0_X_2021-07-11-2300+5c6882/44008/4.22_RunCosmics2011A+RunCosmics2011A+RECOCOSD+ALCACOSD+SKIMCOSD+HARVESTDC/
that shows the "Run 160960". Following that link shows that there are differences in `DQM/TimerService`. Have we perhaps filtered out those differences?

Here is an example from an earlier test
https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_12_0_X_2021-07-08-1100+5c6882/43941/validateJR.html
https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_12_0_X_2021-07-11-2300+5c6882/44008/4.22_RunCosmics2011A+RunCosmics2011A+RECOCOSD+ALCACOSD+SKIMCOSD+HARVESTDC/Run%20160960_DQM_TimerService.html

**Comment by makortel** [comment]
assign core

**Comment by smuzaffar** [comment]
yes after droping ROOT python for py2 , we noticed ( https://github.com/cms-sw/cmssw/pull/34338#issuecomment-877651086 ) that Relmon is broken and not running any comparison. https://github.com/cms-sw/cmssw/pull/34440 was opened to fix the Relmon i.e. to use py3. Though now comparison job does not fail ( due to missing ROOT) but now it is not skiping the Timing Services related variables. @davidlange6 is looking in to it

**Comment by smuzaffar** [comment]
One can reproduce the error by running [a].  @davidlange6 is looking in to it and here is what he wrote

>A fix is
>-B DQM/TimerService@4
>Instead of
>-B DQM/TimerService@3
>As with the meta argument, the histogram names have
>Run 160960/DQM/Run summary/TimerService/event allocated
>And without it
>DQM/Run summary/TimerService/event allocated
> But let me see if I can understand why that extra field is suddenly added to the histogram name

[a]
```
scram p CMSSW_12_0_X_2021-07-12-1400
cd CMSSW_12_0_X_2021-07-12-1400
git cms-addpkg Utilities/RelMon
scram b -j 8
cmsenv
cp /afs/cern.ch/user/m/muzaffar/public/pr-comp/*.root .
mkdir 4.22
compare_using_files.py -B DQM/TimerService@3 rel.root pr.root -o 4.22 --metas " CMSSW_12_0_X_2021-07-12-1400 @@@ CMSSW_12_0_X_2021-07-12-1400 + d3baa7 " --use_black_file -C -R -p --no_successes -s b2b -t 0.999999999999 --standalone
```

**Comment by smuzaffar** [comment]
In `12.0.0.pre3 and pre4` , I get
```
We have a Blacklist:
 o Directory TimerService at level 3
++++++++++++++++++++++++++++++
Output Directory will be  4.22
Studying directory Info, 1/20
 ->Appending Info... Appended.
Studying directory EcalPreshower, 2/20
 ->Appending EcalPreshower... Appended.
Studying directory FED, 3/20
 ->Appending FED... Appended.
Studying directory Tracking, 4/20
 ->Appending Tracking... Appended.
Studying directory Castor, 5/20
 ->Appending Castor... Appended.
Studying directory SiStrip, 6/20
 ->Appending SiStrip... Appended.
Studying directory Ecal, 7/20
 ->Appending Ecal... Appended.
Studying directory EcalEndcap, 8/20
 ->Appending EcalEndcap... Appended.
Studying directory MessageLogger, 9/20
 ->Appending MessageLogger... Appended.
Studying directory HLT, 10/20
 ->Appending HLT... Appended.
Studying directory CSC, 11/20
 ->Appending CSC... Appended.
Studying directory EcalBarrel, 12/20
 ->Appending EcalBarrel... Appended.
Studying directory DT, 13/20
 ->Appending DT... Appended.
Studying directory RPC, 14/20
 ->Appending RPC... Appended.
Studying directory DQM, 15/20
Studying directory Hcal, 16/20
 ->Appending Hcal... Appended.
Studying directory Muons, 17/20
 ->Appending Muons... Appended.
Studying directory Egamma, 18/20
 ->Appending Egamma... Appended.
Studying directory JetMET, 19/20
 ->Appending JetMET... Appended.
Studying directory Pixel, 20/20
  Skipping Pixel/Run summary/averageDigiOccupancy
  Skipping Pixel/Run summary/AdditionalPixelErrors/byLumiErrors
 ->Appending Pixel... Appended.
```

while in IB I get
```
++++++++++++++++++++++++++++++
Output Directory will be  4.22

Rundir not there: Is this a generic rootfile?

Setting run number to 0
Studying directory Run 160960, 1/1
```
so it starts with directory "Run 160960`

**Comment by smuzaffar** [comment]
https://github.com/cms-sw/cmssw/pull/34464 should fix this issue
