### ISSUE TITLE
imp module is deprecated in python3

### ISSUE THREAD

**Issue by sroychow** [cms-sw/cmssw#34489]
While using ```edmConfigDump``` the following warning is seen.
```
Warning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
```
A  fix that I tried is this :-
```
import importlib.machinery
loader = importlib.machinery.SourceFileLoader("pycfg", options.filename)
cfo = loader.load_module()
```
Other script which has this is ```edmConfigSplit```. There are ~10 other configs where this module is used.

**Comment by makortel** [comment]
assign core

**Comment by makortel** [comment]
I see `edmConfigDump` and `edmConfigSplit` were addressed in https://github.com/cms-sw/cmssw/pull/42650.

I also see the following files still having `import imp`
https://github.com/cms-sw/cmssw/blob/393dfc8c101a1cb66d516875657023569c8277bb/Alignment/HIPAlignmentAlgorithm/scripts/batchHippy.py#L5
https://github.com/cms-sw/cmssw/blob/393dfc8c101a1cb66d516875657023569c8277bb/CalibMuon/DTCalibration/python/Workflow/Crabtools/crabFunctions.py#L11
https://github.com/cms-sw/cmssw/blob/393dfc8c101a1cb66d516875657023569c8277bb/PhysicsTools/Heppy/python/utils/cmsswPreprocessor.py#L5
https://github.com/cms-sw/cmssw/blob/393dfc8c101a1cb66d516875657023569c8277bb/PhysicsTools/Heppy/test/crab/heppy_crab_script.py#L25
https://github.com/cms-sw/cmssw/blob/393dfc8c101a1cb66d516875657023569c8277bb/PhysicsTools/HeppyCore/python/framework/heppy_loop.py#L11
https://github.com/cms-sw/cmssw/blob/393dfc8c101a1cb66d516875657023569c8277bb/PhysicsTools/HeppyCore/python/framework/looper.py#L9
https://github.com/cms-sw/cmssw/blob/393dfc8c101a1cb66d516875657023569c8277bb/PhysicsTools/HeppyCore/scripts/heppy_batch.py#L6

----

Given that none of the files above are in `core` managed packages, I think we can close the issue (and maybe open a new one for those files)

**Comment by makortel** [comment]
+core
