### ISSUE TITLE
"To the DQM GUI..." link doesn't work in RelMon Summary pages

### ISSUE THREAD

**Issue by tvami** [cms-sw/cmssw#34482]
"To the DQM GUI..." link doesn't work in RelMon Summary pages created by the Jenkins tests

For example
https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_12_0_X_2021-07-12-2300+b4fe37/44050/11634.0_TTbar_14TeV+2021+TTbar_14TeV_TuneCP5_GenSim+Digi+Reco+HARVEST+ALCA/RelMonSummary.html

on the top of the page if I click to "To the DQM GUI..." link it leads to 
"500 Internal Server Error Incorrect run parameter"

**Comment by smuzaffar** [comment]
@tvami , can you please try again? looks like there was a glitch with front-end

**Comment by tvami** [comment]
Hi @smuzaffar I tried again, and it leads to the same problem. I asked @malbouis to try too and she had the same outcome.

**Comment by smuzaffar** [comment]
strange, it works for me

**Comment by smuzaffar** [comment]
@tvami , can you access https://cmssdt.cern.ch/SDT/ ?

**Comment by tvami** [comment]
> @tvami , can you access https://cmssdt.cern.ch/SDT/ ?

Yes, I can

**Comment by tvami** [comment]
@smuzaffar just to clarify I have the issue with this link
https://cmsweb.cern.ch/dqm/relval/start?runnr=-1;dataset=/Sample/%20CMSSW_12_0_X_2021-07-12-2300%20/DQMIO;sampletype=offline_data;filter=all;referencepos=on-side;referenceshow=all;referencenorm=True;referenceobj1=other:-1:/Sample/%20CMSSW_12_0_X_2021-07-12-2300%20+%20b4fe37%20/DQMIO:;referenceobj2=none;referenceobj3=none;referenceobj4=none;search=;striptype=object;stripruns=;stripaxis=run;stripomit=none;workspace=Everything;size=M;focus=;zoom=no;

**Comment by smuzaffar** [comment]
ah, I think, that link was always broken . If you need to access "DQM Bin by bin"  comparison results then from the PR summary page ( e.g. https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-d0d64e/16791/summary.html ) follow the link "DQM bin by bin comparison" link there you will have various https://cmsweb.cern.ch/dqm links

**Comment by smuzaffar** [comment]
"To the DQM GUI" link is not valid for jenkins jobs as we do not upload any thing to dqm server. I will update the bot jobs to remove this link for PR tests

**Comment by tvami** [comment]
> "To the DQM GUI" link is not valid for jenkins jobs as we do not upload any thing to dqm server. 

I understand

> I will update the bot jobs to remove this link for PR tests

Thanks @smuzaffar !

**Comment by smuzaffar** [comment]
link has been removed.
