### ISSUE TITLE
Unit failure on SimTracker/TrackerMaterialAnalysis 

### ISSUE THREAD

**Issue by qliphy** [cms-sw/cmssw#34587]
https://cmssdt.cern.ch/SDT/cgi-bin/logreader/slc7_amd64_gcc900/CMSSW_12_0_X_2021-07-21-2300/unitTestLogs/SimTracker/TrackerMaterialAnalysis#/

This seems to come from:
https://github.com/cms-sw/cmssw/pull/34521 

Local test shows:

cmsRun trackingMaterialProducer10GeVNeutrino_ForPhaseII.py

An exception of category 'NoRecord' occurred while
   [0] Processing  stream begin Run run: 1 stream: 0
   [1] Calling method for module OscarMTProducer/'trackingMaterialProducer'
Exception Message:
No "HcalRecNumberingRecord" record found in the EventSetup.n
 Please add an ESSource or ESProducer that delivers such a record.
----- End Fatal Exception ---

**Comment by qliphy** [comment]
assign simulation

**Comment by qliphy** [comment]
@bsunanda

**Comment by bsunanda** [comment]
I shall investigate this. I am revising all SD classes and that will have impact on many scripts.

**Comment by bsunanda** [comment]
Please check with #34596

**Comment by qliphy** [comment]
closed by #34596
