### ISSUE TITLE
Unit failure on Validation/Geometry 

### ISSUE THREAD

**Issue by qliphy** [cms-sw/cmssw#34601]
**https://cmssdt.cern.ch/SDT/cgi-bin/logreader/slc7_amd64_gcc900/CMSSW_12_0_X_2021-07-22-2300/unitTestLogs/Validation/Geometry#/16-16** 

+ python3 /data/cmsbld/jenkins/workspace/ib-run-qa/CMSSW_12_0_X_2021-07-22-2300/src/Validation/Geometry/test/runP_HGCal_cfg.py geom=Extended2026D76 label=HGCal
/data/cmsbld/jenkins/workspace/ib-run-qa/CMSSW_12_0_X_2021-07-22-2300/src/Validation/Geometry/test/genHGCalPlots.sh: line 14:   689 Segmentation fault      ${python_cmd} ${VGEO_DIR}/test/runP_HGCal_cfg.py geom=${geom} label=HGCal > $TEST_DIR/runP_HGCal_cfg_${geom}.log 2>&1

---> test materialBudgetHGCalPlots had ERRORS
TestTime:164
^^^^ End Test materialBudgetHGCalPlots ^^^^

 python3 /data/cmsbld/jenkins/workspace/ib-run-qa/CMSSW_12_0_X_2021-07-22-2300/src/Validation/Geometry/test/runP_Tracker.py geom=Extended2015 label=Tracker
/data/cmsbld/jenkins/workspace/ib-run-qa/CMSSW_12_0_X_2021-07-22-2300/src/Validation/Geometry/test/genTrackerPlots.sh: line 14:   936 Segmentation fault      ${python_cmd} ${VGEO_DIR}/test/runP_Tracker.py geom=$geom label=Tracker > $TEST_DIR/runP_Tracker_cfg.log 2>&1

**Local tests show the following:**

python3 runP_HGCal_cfg.py geom=Extended2026D76 label=HGCal
Loading FW Lite setup.
WARNING: AutoLibraryloader::enable() and AutoLibraryLoader.h are deprecated.
Use FWLiteEnabler::enable() and FWLiteEnabler.h instead
Traceback (most recent call last):
  File "runP_HGCal_cfg.py", line 139, in <module>
    cmsRun = CmsRun(process)
  File "/cvmfs/cms-ib.cern.ch/week0/slc7_amd64_gcc900/cms/cmssw/CMSSW_12_0_X_2021-07-21-2300/python/FWCore/PythonFramework/CmsRun.py", line 10, in __init__
    self._cppProcessor = _pf.PythonEventProcessor(procDesc)
RuntimeError: An exception of category 'PluginManagerReconfigured' occurred.

python3 runP_Tracker.py geom=Extended2015 label=Tracker
Loading FW Lite setup.
WARNING: AutoLibraryloader::enable() and AutoLibraryLoader.h are deprecated.
Use FWLiteEnabler::enable() and FWLiteEnabler.h instead
Traceback (most recent call last):
  File "runP_Tracker.py", line 140, in <module>
    cmsRun = CmsRun(process)
  File "/cvmfs/cms-ib.cern.ch/week0/slc7_amd64_gcc900/cms/cmssw/CMSSW_12_0_X_2021-07-21-2300/python/FWCore/PythonFramework/CmsRun.py", line 10, in __init__
    self._cppProcessor = _pf.PythonEventProcessor(procDesc)
RuntimeError: An exception of category 'PluginManagerReconfigured' occurred.

**Comment by qliphy** [comment]
assign geometry,dqm

**Comment by qliphy** [comment]
@cms-sw/geometry-l2 @cms-sw/dqm-l2  Would you please have a look at this issue pending in IB?

**Comment by cvuosalo** [comment]
@qliphy Could you please give some background information about this problem? How did it get into the IBs? What PR started the problem? Is it because of Python3?

**Comment by cvuosalo** [comment]
@civanch Do these unit test failures have something to do with the recent changes in `OscarMTProducer`?
```
===== Test "materialBudgetTrackerPlots" ====                                                                                                                                                                                                                                                        
+ python3 /build/cvuosalo/CMSSW_12_0_X_2021-07-25-0000_vgUnitTest/src/Validation/Geometry/test/runP_Tracker.py geom=Extended2015 label=Tracker                              
/build/cvuosalo/CMSSW_12_0_X_2021-07-25-0000_vgUnitTest/src/Validation/Geometry/test/genTrackerPlots.sh: line 14: 14309 Segmentation fault      ${python_cmd} ${VGEO_DIR}/test/runP_Tracker.py geom=$geom label=Tracker > $TEST_DIR/runP_Tracker_cfg.log 2>&1                                                                 

   [1] Calling method for module OscarMTProducer/'g4SimHits'
Exception Message:
No "HcalRecNumberingRecord" record found in the EventSetup.n
 Please add an ESSource or ESProducer that delivers such a record.
```

**Comment by bsunanda** [comment]
Hi Carl, Yes they are. Let me take a look to cure this. Earlier there were unit test failures for SimTracker which is fixed.
________________________________

**Comment by bsunanda** [comment]
I shall cure the cfg's after integration of #34589

**Comment by cvuosalo** [comment]
Fixed by #34622.

**Comment by cvuosalo** [comment]
+1

**Comment by jfernan2** [comment]
+1
For the records
