### ISSUE TITLE
gdb is not working

### ISSUE THREAD

**Issue by makortel** [cms-sw/cmssw#34632]
`gdb` in CMSSW_12_0_X_2021-07-26-1100 gives me
```
/cvmfs/cms-ib.cern.ch/week1/slc7_amd64_gcc900/cms/cmssw-patch/CMSSW_12_0_X_2021-07-26-1100/external/slc7_amd64_gcc900/bin/gdb: line 2:  6285 Segmentation fault      PYTHONHOME=/cvmfs/cms-ib.cern.ch/nweek-02691/slc7_amd64_gcc900/external/python3/3.9.6-3f1d9f1604df11a32a0dbcfe625d011c gdb-9.2 "$@"
```

**Comment by makortel** [comment]
assign core

**Comment by smuzaffar** [comment]
There was issue with gdb 9.1 and python 3.9 ( https://bugzilla.redhat.com/show_bug.cgi?id=1829702 ) but it should have been fixed for gdb 9.2. Let me try gdb 10.2

**Comment by smuzaffar** [comment]
GDB 10.2 seems to work fine with python 3.9. https://github.com/cms-sw/cmsdist/pull/7169 should fix this issue

**Comment by makortel** [comment]
Thanks!

**Comment by makortel** [comment]
+1
