### ISSUE TITLE
[DD4hep] code review is needed

### ISSUE THREAD

**Issue by ianna** [cms-sw/cmssw#34663]
@makortel, @cvuosalo, @civanch - IMHO we need to review the CMSSW DD4hep related code. On many occasions the code was rushed and comments ignored.

**Comment by civanch** [comment]
+geometry

**Comment by civanch** [comment]
assign geometry, simulation

**Comment by civanch** [comment]
assign core

**Comment by makortel** [comment]
Given that the "code was rushed" was driven by the (tight) schedule for Run 3, a good moment for more thorough review could be after the Run 3 geometry rush is over. @cvuosalo when could that be (approximately)?

**Comment by civanch** [comment]
@ianna , thank you for collecting problems in one issue.

@makortel , I think, we need to address majority of these problems in 12_1_0, first of all, resolve wrong unnecessary dependencies, fix main design problems, and remaining warnings. 
 
Likely some prioritization will be required.

**Comment by ianna** [comment]
@bsunanda and @civanch - Please, review the issues referenced here and open a new issue if it is still relevant. Thanks!
