### ISSUE TITLE
convert LowPtGsfElectronSeedProducer model from xml to root

### ISSUE THREAD

**Issue by slava77** [cms-sw/cmssw#34707]
https://github.com/cms-sw/cmssw/issues/34633#issuecomment-889698425

The StreamSchedule constructor is mostly about constructing EDModules 118 s
Some that stand out : 

`LowPtGsfElectronSeedProducer` 35 s https://mkortela.web.cern.ch/mkortela/cgi-bin/navigator/CMSSW_12_0_X_2021-07-28-2300/test_11725.0_step3_06_perf/127
    * Mostly about reading GBRForest XML https://mkortela.web.cern.ch/mkortela/cgi-bin/navigator/CMSSW_12_0_X_2021-07-28-2300/test_11725.0_step3_06_perf/65

This arises from reading 
RecoEgamma/ElectronIdentification/data/LowPtElectrons/
RunII_Autumn18_LowPtElectrons_unbiased.xml.gz and RunII_Autumn18_LowPtElectrons_displaced_pt_eta_biased.xml.gz

The proposal to resolve this issue is to convert the xml model to .root format

@bainbrid

**Comment by makortel** [comment]
assign reconstruction

**Comment by bainbrid** [comment]
@slava77 please can we close this issue? (no urgency, I'm just checking through issues/PRs related to low pT ele.)

**Comment by slava77** [comment]
+reconstruction
