### ISSUE TITLE
Update to DQM onlinebeammonitor

### ISSUE THREAD

**Issue by francescobrivio** [cms-sw/cmssw#34717]
In order to properly monitor the updates of the BeamSpotOnline tags at lumisection level the configuration of the client
[onlinebeammonitor_dqm_sourceclient-live_cfg.py](https://github.com/cms-sw/cmssw/blob/master/DQM/Integration/python/clients/onlinebeammonitor_dqm_sourceclient-live_cfg.py) needs to be updated to include the `refreshTime` parameter.
This change only affects the **monitoring** of the BeamSpotOnline updates on the DQM side. 

The fix is rather simple (just adding a `toGet` to customize the process.GlobalTag is enough) and it has been tested already in the HLT menu live at P5 (see http://cmsonline.cern.ch/cms-elog/1121707).
I will prepare PRs for 11_3, 12_0 and 12_1 by today. 

@perrotta @qliphy @silviodonato This is just to let you know that it would be nice to include this in the new build for CRUZET (not sure whether is this already planned or if the issues with HCAL GPU code still do not have a solution).

FYI
@gennai @ggovi 
@amassiro @boudoul 
@cms-sw/dqm-l2

**Comment by jfernan2** [comment]
+1
Fixed in the PRs above
