### ISSUE TITLE
Header files from `non-interface` sub-directory included

### ISSUE THREAD

**Issue by smuzaffar** [cms-sw/cmssw#34718]
I am trying to update build rules to not allow including headers from `non-interface` directory of a package (6.3:  http://cms-sw.github.io/cms_coding_rules.html#6--packaging-rules-1 ). Currently there are over 100 such header files [a] whcih are used. Can we please go through [a] and check if these header files provide public interface then move to `interface` directory or cleanup their usage ( if these are not public headers)? 

You can use https://cmssdt.cern.ch/lxr/search to find out where these headers are used/included

[a]
```
      4 src/CalibCalorimetry/CaloTPG/src/CaloTPGTranscoderULUT.h
      1 src/CalibMuon/DTDigiSync/src/DTTTrigSyncFromDB.h
      1 src/CalibMuon/DTDigiSync/src/DTTTrigSyncT0Only.h
      1 src/CalibMuon/DTDigiSync/src/DTTTrigSyncTOFCorr.h
      1 src/CommonTools/RecoAlgos/src/TrackToRefCandidate.h
     51 src/CommonTools/Utils/src/ExpressionBase.h
     51 src/CommonTools/Utils/src/ExpressionPtr.h
      6 src/CommonTools/Utils/src/Grammar.h
    115 src/CommonTools/Utils/src/SelectorBase.h
     51 src/CommonTools/Utils/src/SelectorPtr.h
      1 src/CommonTools/Utils/src/returnType.h
      2 src/CondCore/CondDB/src/DbCore.h
      1 src/CondCore/CondDB/src/IOVSchema.cc
      2 src/CondFormats/EcalObjects/src/classes.h
      2 src/DQM/Physics/src/EwkDQM.h
      3 src/DQMServices/Core/src/ROOTFilePB.pb.h
      2 src/DataFormats/FEDRawData/src/fed_header.h
      2 src/DataFormats/FEDRawData/src/fed_trailer.h
      1 src/DataFormats/MuonDetId/src/DTWireId.cc
      2 src/DetectorDescription/Core/src/Box.h
      2 src/DetectorDescription/Core/src/Cons.h
      2 src/DetectorDescription/Core/src/CutTubs.h
      2 src/DetectorDescription/Core/src/EllipticalTube.h
      2 src/DetectorDescription/Core/src/ExtrudedPolygon.h
      5 src/DetectorDescription/Core/src/LogicalPart.h
      6 src/DetectorDescription/Core/src/Material.h
      2 src/DetectorDescription/Core/src/Polycone.h
      2 src/DetectorDescription/Core/src/Polyhedra.h
      1 src/DetectorDescription/Core/src/PseudoTrap.h
     18 src/DetectorDescription/Core/src/Solid.h
      4 src/DetectorDescription/Core/src/Specific.h
      2 src/DetectorDescription/Core/src/Sphere.h
      2 src/DetectorDescription/Core/src/Torus.h
      2 src/DetectorDescription/Core/src/Trap.h
      1 src/DetectorDescription/Core/src/TruncTubs.h
      2 src/DetectorDescription/Core/src/Tubs.h
      1 src/EventFilter/GctRawToDigi/plugins/GctRawToDigi.h
      1 src/EventFilter/HcalRawToDigi/plugins/HcalRawToDigi.h
      1 src/EventFilter/Utilities/plugins/RecoEventWriterForFU.h
      1 src/FWCore/Framework/src/EventSetupsController.h
   2040 src/FWCore/Framework/src/Factory.h
      2 src/FWCore/Framework/src/ModuleRegistry.h
      9 src/FWCore/Framework/src/Path.h
     17 src/FWCore/Framework/src/PreallocationConfiguration.h
      2 src/FWCore/Framework/src/PrincipalCache.h
      1 src/FWCore/Framework/src/ProductPutterBase.h
      3 src/FWCore/Framework/src/SharedResourcesRegistry.h
      5 src/FWCore/Framework/src/SignallingProductRegistry.h
      5 src/FWCore/Framework/src/TransitionInfoTypes.h
    187 src/FWCore/Framework/src/Worker.h
      1 src/FWCore/Framework/src/globalTransitionAsync.h
      1 src/FWCore/Framework/src/streamTransitionAsync.h
      4 src/FWCore/Services/src/SiteLocalConfigService.h
      1 src/FWCore/Utilities/src/Guid.h
      1 src/Fireworks/Core/src/CmsShowMain.h
      4 src/Fireworks/Core/src/CmsShowTaskExecutor.h
      1 src/Fireworks/Core/src/FWDialogBuilder.h
      1 src/Fireworks/Core/src/FWItemSingleAccessor.h
     15 src/Fireworks/TableWidget/src/FWTabularWidget.h
      1 src/GeneratorInterface/Herwig6Interface/src/hwudat.f
      6 src/Geometry/CSCGeometry/src/CSCWireGroupPackage.h
      1 src/Geometry/CSCGeometryBuilder/src/CSCGeometryParsFromDD.h
      1 src/Geometry/DTGeometryBuilder/src/DTGeometryParsFromDD.h
      3 src/Geometry/ForwardGeometry/src/ZdcHardcodeGeometryData.h
      1 src/Geometry/GEMGeometryBuilder/src/GEMGeometryParsFromDD.h
      1 src/Geometry/GEMGeometryBuilder/src/ME0GeometryParsFromDD.h
      1 src/Geometry/RPCGeometryBuilder/src/RPCGeometryParsFromDD.h
      1 src/HeterogeneousCore/CUDAUtilities/src/CachingDeviceAllocator.h
      1 src/HeterogeneousCore/CUDAUtilities/src/CachingHostAllocator.h
      2 src/HeterogeneousCore/CUDAUtilities/src/getCachingDeviceAllocator.h
      1 src/HeterogeneousCore/CUDAUtilities/src/getCachingHostAllocator.h
      3 src/IOMC/RandomEngine/src/TRandomAdaptor.h
      2 src/IORawData/DTCommissioning/plugins/RawFile.h
      2 src/L1Trigger/CSCTrackFinder/src/CSCTFDTReceiver.h
      1 src/L1Trigger/DTTrackFinder/src/L1MuDTTFConfig.h
      6 src/L1Trigger/TextToDigi/src/SourceCardRouting.h
      2 src/MagneticField/Layers/src/MagBinFinders.h
      1 src/MagneticField/ParametrizedEngine/src/OAEParametrizedMagneticField.h
      1 src/PhysicsTools/RecoAlgos/plugins/KalmanVertexFitter.h
      2 src/RecoJets/JetProducers/plugins/CastorJetIDProducer.h
      2 src/RecoJets/JetProducers/plugins/VirtualJetProducer.h
      1 src/RecoLocalCalo/HGCalRecProducers/plugins/KernelManagerHGCalCellPositions.h
      1 src/RecoLocalMuon/DTSegment/src/DTHitPairForFit.h
      1 src/RecoLocalMuon/DTSegment/src/DTSegmentCand.h
      1 src/RecoLocalMuon/DTSegment/src/DTSegmentCleaner.h
      1 src/RecoLocalMuon/DTSegment/src/DTSegmentUpdator.h
      1 src/RecoLocalTracker/SiPixelClusterizer/plugins/SiPixelRawToClusterGPUKernel.h
      1 src/RecoPixelVertexing/PixelTriplets/plugins/ThirdHitCorrection.h
      1 src/RecoPixelVertexing/PixelTriplets/plugins/ThirdHitRZPrediction.h
      1 src/RecoTracker/FinalTrackSelectors/plugins/getBestVertex.h
      1 src/RecoTracker/FinalTrackSelectors/src/TrackCollectionCloner.cc
      1 src/RecoTracker/MeasurementDet/src/TkMeasurementDetSet.h
      2 src/RecoTracker/TkHitPairs/src/InnerDeltaPhi.h
      4 src/RecoTracker/TkTrackingRegions/plugins/GlobalTrackingRegionProducerFromBeamSpot.h
      1 src/RecoTracker/TrackProducer/plugins/TrackProducer.h
      2 src/SimCalorimetry/EcalSelectiveReadoutAlgos/src/EcalSelectiveReadout.h
      4 src/SimDataFormats/GeneratorProducts/data/hepev4.inc
      4 src/SimDataFormats/GeneratorProducts/data/stdhep.inc
      1 src/SimMuon/DTDigitizer/test/Histograms.h
      4 src/SimTracker/SiPhase2Digitizer/plugins/Phase2TrackerDigitizerFwd.h
      3 src/SimTracker/TrackAssociation/plugins/CosmicParametersDefinerForTPESProducer.h
      4 src/SimTracker/TrackAssociation/plugins/ParametersDefinerForTPESProducer.h
      4 src/TrackingTools/DetLayers/src/DetLessZ.h
      1 src/Utilities/XrdAdaptor/src/XrdStatistics.h
```

**Comment by kpedro88** [comment]
@smuzaffar does this include .h files in the plugins directory that are only included by other files in the plugins directory? This has been allowed in some cases in the past.

**Comment by smuzaffar** [comment]
@kpedro88 , no. Including a `.h` file from same directory (plugins, src or test) is allowed. Only thing which is not allowed is including `.h` from another package's `non-interface` directory

**Comment by Dr15Jones** [comment]
@smuzaffar some of these are to allow unit testing. I think we need to distinguish against headers used as part of the 'public' interface of a module and those meant for 'private' (i.e. meant to only be used by code in subdirectories of the given package like /src /test, etc).

**Comment by smuzaffar** [comment]
@Dr15Jones , using private headers (i.e files in `non-interface` dirs) in `non-interface` dirs of the  same package is fine but unit test of packageA should not use private headers of PackageB.

**Comment by agrohsje** [comment]
@theofil @Dominic-Stafford : Is one of you available to handle: 
https://github.com/cms-sw/cmssw/tree/master/GeneratorInterface/Herwig6Interface
Does it still make sense to keep this? @qliphy: what do you think ?

**Comment by theofil** [comment]
@agrohsje 
as far as I can see it is only 2 files that use this old fortran header [https://cmssdt.cern.ch/lxr/source/GeneratorInterface/Herwig6Interface/src/hwudat.f](https://cmssdt.cern.ch/lxr/source/GeneratorInterface/Herwig6Interface/src/hwudat.f)

- [https://cmssdt.cern.ch/lxr/source/GeneratorInterface/PomwigInterface/plugins/hwudat.F](https://cmssdt.cern.ch/lxr/source/GeneratorInterface/PomwigInterface/plugins/hwudat.F)
- [https://cmssdt.cern.ch/lxr/source/GeneratorInterface/Herwig6Interface/plugins/hwudat.F](https://cmssdt.cern.ch/lxr/source/GeneratorInterface/Herwig6Interface/plugins/hwudat.F)

 unless there is any shortcoming that I am not aware, I can take care them and move the `hwudat.f` into `/interafce` and update the corresponding plugins.

**Comment by smuzaffar** [comment]
@theofil , please also create GeneratorInterface/Herwig6Interface/src/hwudat.F with following contents
```
#include "GeneratorInterface/Herwig6Interface/interface/hwudat.f"
```

this will allow to scram compile `hwudat.F` for `Herwig6Interface` package too

**Comment by Dominic-Stafford** [comment]
On the question of whether it makes sense to keep this, Herwig 7 is advertised as a direct replacement to Herwig 6, whereas Herwig++ didn't implement all of the old functionality, so arguably the reason to keep Herwig 6 no longer exists. Of course if people still use it we can continue supporting it.

**Comment by agrohsje** [comment]
hi @smuzaffar in fact the file is already there we just need to update. @theofil @Dominic-Stafford : let's make the corresponding pr with the modification and then discuss removing obsolete files. there seem more that we can remove. let's centrally coordinate.

**Comment by smuzaffar** [comment]
I think we can allow `packages/test` sub-dirs to use files from other `packages/test` sub-dirs. e.g. `Utilities/StorageFactory/test/Test.h` is utility test header which is only used by other tests.

**Comment by jfernan2** [comment]
+1
From #34773

**Comment by theofil** [comment]
@smuzaffar @Dominic-Stafford @agrohsje 
please check #34792, it should be implementing the wished

**Comment by smuzaffar** [comment]
thanks @theofil ,  #34792 looks good

**Comment by agrohsje** [comment]
+generators

**Comment by alja** [comment]
+1

**Comment by smuzaffar** [comment]
@Dr15Jones , can we also cleanup

```
    28 src/FWCore/Framework/src/EventSetupRecordIOVQueue.h
    28 src/FWCore/Framework/src/EventSetupRecordIOVQueue.h
      8 src/FWCore/Framework/src/SubProcess.h
```
these are included by public header ( e.g FWCore/Framework/interface/EventSetupsController.h and FWCore/Framework/interface/*TransitionAsync.h). I think moving these to FWCore/Framework/interface should be enought

**Comment by smuzaffar** [comment]
@fwyzard , we still have couple of private headers of CUDAUtilities which are used by https://cmssdt.cern.ch/lxr/source/HeterogeneousCore/CUDAServices/src/CUDAService.cc
```
      4 src/HeterogeneousCore/CUDAUtilities/src/getCachingDeviceAllocator.h
      2 src/HeterogeneousCore/CUDAUtilities/src/getCachingHostAllocator.h
```
Any objections on moving these to `HeterogeneousCore/CUDAUtilities/interface` ?

**Comment by makortel** [comment]
> @fwyzard , we still have couple of private headers of CUDAUtilities which are used by https://cmssdt.cern.ch/lxr/source/HeterogeneousCore/CUDAServices/src/CUDAService.cc
> 
> ```
>       4 src/HeterogeneousCore/CUDAUtilities/src/getCachingDeviceAllocator.h
>       2 src/HeterogeneousCore/CUDAUtilities/src/getCachingHostAllocator.h
> ```
> 
> Any objections on moving these to `HeterogeneousCore/CUDAUtilities/interface` ?

I'd like to take care of that, can do today.

**Comment by makortel** [comment]
> > we still have couple of private headers of CUDAUtilities which are used by https://cmssdt.cern.ch/lxr/source/HeterogeneousCore/CUDAServices/src/CUDAService.cc
> > ```
> >       4 src/HeterogeneousCore/CUDAUtilities/src/getCachingDeviceAllocator.h
> >       2 src/HeterogeneousCore/CUDAUtilities/src/getCachingHostAllocator.h
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Any objections on moving these to `HeterogeneousCore/CUDAUtilities/interface` ?
> 
> I'd like to take care of that, can do today.

Done in https://github.com/cms-sw/cmssw/pull/34958.

**Comment by smuzaffar** [comment]
#34895 ,  #34898 and  #34977 are the last 3 PRs to fix this issue. Once these are merged then all the private header usage should be clean and I can enable the build rule to fail the build if someone use a private header

**Comment by tvami** [comment]
+alca

* AlCa part was done in
https://github.com/cms-sw/cmssw/pull/34761
https://github.com/cms-sw/cmssw/pull/34762

**Comment by tvami** [comment]
> #34895 , #34898 and #34977 are the last 3 PRs to fix this issue. Once these are merged then all the private header usage should be clean and I can enable the build rule to fail the build if someone use a private header

Hi @smuzaffar since the PRs above are merged, should this issue be closed?
