### ISSUE TITLE
Unknown PDG id code 9010221 to GenParticleProducer

### ISSUE THREAD

**Issue by perrotta** [cms-sw/cmssw#34753]
Since some while the following error message appears in (e.g.) wf 4007.0 QCD_Pt_30_80_BCtoE_8TeV

```
----- Begin Fatal Exception 04-Aug-2021 03:06:17 CEST-----------------------
An exception of category 'LogicError' occurred while
   [0] Processing  Event run: 1 lumi: 1 event: 5 stream: 2
   [1] Running path 'simulation_step'
   [2] Calling method for module GenParticleProducer/'genParticlesForFilter'
Exception Message:
invalid PDG id: 9010221
----- End Fatal Exception -------------------------------------------------
```

9020221 seems to be a legitimate id code for eta(1475), see https://pdg.lbl.gov/2007/reviews/montecarlorpp.pdf

Would it be possible to make somehow our `GenParticleProducer` aware of it, so that we can get rid of that crash?

**Comment by perrotta** [comment]
assign generators

**Comment by iarspider** [comment]
Possibly the same as #34586

**Comment by perrotta** [comment]
> Possibly the same as #34586

Indeed, thank you: I did not notice it

**Comment by perrotta** [comment]
Closing as replica of #34586
