### ISSUE TITLE
Bugs to be fixed in DQM/L1TMonitor

### ISSUE THREAD

**Issue by perrotta** [cms-sw/cmssw#34795]
The static analyzer points out a few dead assignmets or increments in the package.

A few trivial ones were cured in #34794. While doing so, a rather obvious bug was spotted in DQM/L1TMonitor/src/L1TBPTX.cc, see https://github.com/cms-sw/cmssw/pull/34794#pullrequestreview-723439833. That pull request provides a fix for it.

However, there are a few more static analyzer reports that point out some quite evident bug, whose solution being less obvious should be rather left to the responsibles of the code.

- Line 495 of DQM/L1TMonitor/src/L1TRate.cc: the dead assignment to the bool variable `foundFit,` followed by a break which moves out of the loop, indicates that the logic currently implemented in that fit is wrong

- Line 769 of DQM/L1TMonitor/src/L1TGT.cc, with the dead assignment of `pfsIndicesPerLs` to "1" makes me suspect that the method `countPfsIndicesPerLs` cannot return a correct counter. My impression is that the initialization at Line 751 should be moved before the loop; but I did not investigate further

Please have a look and either provide a fix, or remove whatever is obsolete from that area (so that people won't have to spend time in updating and adjusting them any further)

**Comment by perrotta** [comment]
assign dqm

**Comment by jfernan2** [comment]
L1T DQM Contacts:
@abrinke1 @apana @chadfreer @pgianneios @gkaratha @panoskatsoulis @benkrikler @aloeliger @vukasinmilosevic @dinyar @thomreis @rekovic @stahlleiton @hftsoi @mzarucki

Could you please have a look? Thanks

**Comment by thomreis** [comment]
These are modules from the legacy L1. Are they still used somewhere these days?

**Comment by jfernan2** [comment]
that is the question @thomreis 
Some findings posted here:
https://github.com/cms-sw/cmssw/pull/34794#issuecomment-898497617

**Comment by jfernan2** [comment]
ping @vukasinmilosevic

**Comment by vukasinmilosevic** [comment]
Similar to the other issue :), we have someone taking a look into this. He is currently getting up to speed and will update us soon.

**Comment by jfernan2** [comment]
+1
Then I understand this issue can be closed
