### ISSUE TITLE
Non-reproducibility in ticlTracksters_ticlSimTracksters reco comparisons

### ISSUE THREAD

**Issue by makortel** [cms-sw/cmssw#34901]
Many unrelated PRs (e.g. https://github.com/cms-sw/cmssw/pull/34891#issuecomment-899682842) are showing differences in `all_OldVSNew_*_ticlTracksters_ticlSimTracksters__RECO_obj_ticlIteration.png` in workflows 23234.0, 28234.0, 34634.0, and 34834.999. Below is an example from 23234.0
![image](https://user-images.githubusercontent.com/33993/129639490-04e835b4-c6bb-4b7d-9039-51f360cc0e8c.png)

**Comment by makortel** [comment]
assign reconstruction, upgrade

**Comment by srimanob** [comment]
assign hgcal-dpg

**Comment by qliphy** [comment]
https://github.com/cms-sw/cmssw/pull/34800#issuecomment-899607995  should be related.

**Comment by slava77** [comment]
this is fixed in 
#34858

**Comment by rovere** [comment]
should we close this?
