### ISSUE TITLE
[UBSAN] Undefined behavior in FastSimulation/CaloGeometryTools 

### ISSUE THREAD

**Issue by mrodozov** [cms-sw/cmssw#35006]
UBSAN reports a runtime error:

```

FastSimulation/CaloGeometryTools/interface/CaloPoint.h:17:7: 
runtime error: load of value 1071181578, which is not a valid value for type 'CaloDirection'
```
https://github.com/cms-sw/cmssw/blob/master/FastSimulation/CaloGeometryTools/interface/CaloPoint.h#L17

in multiple relvals, example:
5.6 step1
https://cmssdt.cern.ch/SDT/cgi-bin/buildlogs/raw/slc7_amd64_gcc10/CMSSW_12_1_UBSAN_X_2021-08-20-2300/pyRelValMatrixLogs/run/5.7_H130GGgluonfusion+H130GGgluonfusionFS+HARVESTFS/step1_H130GGgluonfusion+H130GGgluonfusionFS+HARVESTFS.log
25409.0 step1

Reference:
https://cmssdt.cern.ch/SDT/html/cmssdt-ib/#/relVal/CMSSW_12_1/2021-08-20-2300?selectedArchs=slc7_amd64_gcc10&selectedFlavors=UBSAN_X

**Comment by mrodozov** [comment]
assign fastsim

**Comment by makortel** [comment]
This probably means that `CaloDirection` (which is a an `enum`) member
https://github.com/cms-sw/cmssw/blob/3a5e558609b0e6f30f9001479d3038ec773a016e/FastSimulation/CaloGeometryTools/interface/CaloPoint.h#L64
is not initialized by some of the constructors of `CaloPoint`.
