### ISSUE TITLE
"ECAL Interpolated Laser correction <0" msg in rerecoing cosmics (2020 MWGR / 2021 CRUZET)

### ISSUE THREAD

**Issue by tvami** [cms-sw/cmssw#35014]
When rerecoing CRUZET runs we see 
"%MSG-e EcalLaserDbService:  EcalDQMonitorTask:ecalMonitorTask  29-Jul-2021 01:46:21 CEST Run: 343175 Event: 382226
Interpolated Laser correction <0 for detid 838888175
%MSG
%MSG-e EcalLaserDbService:  EcalDQMonitorTask:ecalMonitorTask  29-Jul-2021 01:46:21 CEST Run: 343175 Event: 382226
"
a lot! This was present in the MWGRs in 2020 too, but still present in the current CRUZET.

Recipe to reproduce

```
cmsrel CMSSW_11_3_4
cd CMSSW_11_3_4/src
cmsenv
cmsDriver.py step2 --conditions auto:run3_data_prompt --customise Configuration/DataProcessing/RecoTLR.customisePrompt,Configuration/DataProcessing/RecoTLR.customiseCosmicData --data --datatier RECO,DQMIO --era Run3 --eventcontent RECO,DQM --filein /store/express/Commissioning2020/ExpressCosmics/FEVT/Express-v1/000/338/714/00000/000D25B4-AE2B-ED4D-A539-F6EF7CDD527E.root --fileout "file:step2.root" --nThreads 8 --no_exec --number 1 --process reRECO --python_filename step_2_cfg.py --scenario cosmics --step RAW2DIGI,L1Reco,RECO,DQM
```
or for 2021 CRUZET
```
cmsDriver.py step2 --conditions auto:run3_data_prompt --customise Configuration/DataProcessing/RecoTLR.customisePrompt,Configuration/DataProcessing/RecoTLR.customiseCosmicData --data --datatier RECO,DQMIO --era Run3 --eventcontent RECO,DQM --filein /store/express/Commissioning2021/ExpressCosmics/FEVT/Express-v1/000/344/518/00000/0147726b-df3d-467c-b802-17f26ff1ae92.root --fileout "file:step2.root" --nThreads 8 --no_exec --number 1 --process reRECO --python_filename step_2_cfg.py --scenario cosmics --step RAW2DIGI,L1Reco,RECO,DQM
```

**Comment by tvami** [comment]
assign alca

**Comment by tvami** [comment]
ECAL experts  (@cms-sw/ecal-dpg-l2 ) already working on this, but I wanted it to be more visible when speaking about it at different coordination meetings.

**Comment by thomreis** [comment]
Who exactly is working on this?

**Comment by tvami** [comment]
Hi @thomreis , I'm in contact with Marco Cipriani. But I added you to the Mattermost channel where we chatted about this so far.

**Comment by fcouderc** [comment]
Hi @tvami 

I investigate a bit more this issue. Rather than the corrections which look ok, this seems to be due to the timestamp of the event. It may be only a problem in the Ecal DQM in fact, does the error show up in the standard reco?

For instance here is just an extended dump of the error message
%MSG-e EcalLaserDbService:  EcalDQMonitorTask:ecalMonitorTask  06-Sep-2021 14:45:33 CEST Run: 338714 Event: 2799251
Interpolated Laser correction <0 for detid 838904326 tf = 6896959553087209472 t_i = 6896956636804415488 t_laser = 0 t = 0 t3 = 6896965720660246528  -- p_f = 0.899799 p_i = 0.899597  -- p2 =0.899799 p1/p2 = 0.999776 p3/p2 = 0.999947
%MSG

as one can see t_laser = t = 0 and t is the timestamp used as argument of the laser service function, so this is set incorrectly in DQM most likely.

Ecal DQM team has been notified.

Fabrice

**Comment by tvami** [comment]
I have run 
```
cmsDriver.py step2 --conditions auto:run3_data_prompt --customise Configuration/DataProcessing/RecoTLR.customisePrompt,Configuration/DataProcessing/RecoTLR.customiseCosmicData --data --datatier RECO --era Run3 --eventcontent RECO --filein /store/express/Commissioning2021/ExpressCosmics/FEVT/Express-v1/000/344/518/00000/0147726b-df3d-467c-b802-17f26ff1ae92.root --fileout "file:step2.root" --nThreads 8 --no_exec --number 1 --process reRECO --python_filename step_2_cfg.py --scenario cosmics --step RAW2DIGI,L1Reco,RECO
```
and indeed I dont see the warning anymore

**Comment by tvami** [comment]
assign dqm

**Comment by abhih1** [comment]
Ecal DQM is taking a look at this.

-Abhirami

**Comment by abhih1** [comment]
Hi @tvami It was indeed an error with DQM. I have created a PR to the master https://github.com/cms-sw/cmssw/pull/35163 to rectify this. Would you like to have a backport PR to CMSSW_11_3_X as well?

**Comment by tvami** [comment]
> Hi @tvami It was indeed an error with DQM. I have created a PR to the master #35163 to rectify this. Would you like to have a backport PR to CMSSW_11_3_X as well?

Yes please do the backport to 11_3_X, thanks!

**Comment by abhih1** [comment]
> > Hi @tvami It was indeed an error with DQM. I have created a PR to the master #35163 to rectify this. Would you like to have a backport PR to CMSSW_11_3_X as well?
> 
> Yes please do the backport to 11_3_X, thanks!

The backport is done here: https://github.com/cms-sw/cmssw/pull/35164.

**Comment by tvami** [comment]
Thanks a lot for the quick response @abhih1 !

**Comment by tvami** [comment]
Oh @abhih1 since `12_0_X` will be used for CRAFT and test beams, would you please submit a backport there as well? Thanks again! (this is less urgent btw, the `CMSSW_11_3_X `was the urgent one)

**Comment by abhih1** [comment]
Sure! Here is the backport to `12_0_X` https://github.com/cms-sw/cmssw/pull/35171

**Comment by tvami** [comment]
Hi @smuzaffar I'm wondering why this issue is not auto-closed, I did this
https://github.com/cms-sw/cmssw/pull/35164#issuecomment-913704020
I thought when I do the `resolves xxxxx` it would close automatically.
(of course in this very specific case, I opened the issue, so I can very easily close it too, but I want to understand why the bot didnt do it) 
Thanks!

**Comment by tvami** [comment]
+alca
 * master PR: https://github.com/cms-sw/cmssw/pull/35163
 * backport PR to 11_3_X: https://github.com/cms-sw/cmssw/pull/35164
 * backport PR to 12_0_X: https://github.com/cms-sw/cmssw/pull/35171

**Comment by makortel** [comment]
> I'm wondering why this issue is not auto-closed, I did this
> [#35164 (comment)](https://github.com/cms-sw/cmssw/pull/35164#issuecomment-913704020)
> I thought when I do the `resolves xxxxx` it would close automatically.

The "resolves xxxxx" needs to be in the PR description.

**Comment by tvami** [comment]
> > I'm wondering why this issue is not auto-closed, I did this
> > [#35164 (comment)](https://github.com/cms-sw/cmssw/pull/35164#issuecomment-913704020)
> > I thought when I do the `resolves xxxxx` it would close automatically.
> 
> The "resolves xxxxx" needs to be in the PR description.

Ahh I see, thanks for the info! Maybe it would be beneficial if it could be done in the comments as well? Similarly like how it is done for the `backport of ...` command (that works from the comments as well)?

**Comment by makortel** [comment]
> > > I'm wondering why this issue is not auto-closed, I did this
> > > [#35164 (comment)](https://github.com/cms-sw/cmssw/pull/35164#issuecomment-913704020)
> > > I thought when I do the `resolves xxxxx` it would close automatically.
> > 
> > 
> > The "resolves xxxxx" needs to be in the PR description.
> 
> Ahh I see, thanks for the info! Maybe it would be beneficial if it could be done in the comments as well? 

The "resolves xxxxx" is a feature of GitHub, see https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue

> Similarly like how it is done for the `backport of ...` command (that works from the comments as well)?

The `backport`, on the other hand, is a feature of cms-bot. I leave it to @smuzaffar to comment how feasible extending cms-bot into that direction would be.

**Comment by smuzaffar** [comment]
@tvami , as @makortel mentioned , `resolves ...` is github feature and I would not like to change its behavior  with cms-bot
