### ISSUE TITLE
RPDetDigitizer of PPS requires correct use of EventSetup

### ISSUE THREAD

**Issue by civanch** [cms-sw/cmssw#35094]
During migration to the new schema of access to EventSetup  it was found that RPDetDigitizer needs update (see there more details at #34989).

**Comment by civanch** [comment]
assign simulation core

**Comment by civanch** [comment]
assign core

**Comment by civanch** [comment]
assign simulation

**Comment by civanch** [comment]
@fabferro , @clemencia , is there progress?

**Comment by clemencia** [comment]
I have a branch http://github.com/clemencia/cmssw/tree/RPDigiProducer_esConsumes that compiles but I have difficulties testing that it runs correctly (related to 2016 configuration). I get the exception ProductNotFound ( and I think it is because I don't have g4SimHits in the totem strips.)

```
Exception Message:
Principal::getByToken: Found zero products matching all criteria
Looking for type: CrossingFrame<PSimHit>
Looking for module label: mix
Looking for productInstanceName: g4SimHitsTotemHitsRP
Looking for process:
 
```

**Comment by tvami** [comment]
I think this was resolved in
https://github.com/cms-sw/cmssw/pull/39699
right?

**Comment by makortel** [comment]
+core

**Comment by tvami** [comment]
@cmsbuild , please close
