### ISSUE TITLE
Unit failure in Geometry/TrackerGeometryBuilder

### ISSUE THREAD

**Issue by qliphy** [cms-sw/cmssw#35118]
https://cmssdt.cern.ch/SDT/cgi-bin/logreader/slc7_amd64_gcc900/CMSSW_12_1_X_2021-09-01-1100/unitTestLogs/Geometry/TrackerGeometryBuilder#/61-61

===== Test "cmsRun /build/cmsbld/jenkins/workspace/ib-run-qa/CMSSW_12_1_X_2021-09-01-1100/src/Geometry/TrackerGeometryBuilder/test/python/testTrackerHierarchy_cfg.py " ====
Begin processing the 1st record. Run 1, Event 1, LumiSection 1 on stream 0 at 01-Sep-2021 19:30:18.747 CEST
----- Begin Fatal Exception 01-Sep-2021 19:30:24 CEST-----------------------
An exception of category 'NoRecord' occurred while
   [0] Processing  Event run: 1 lumi: 1 event: 1 stream: 0
   [1] Running path 'p1'
   [2] Calling method for module GeoHierarchy/'prod'
   [3] Using EventSetup component TrackerDigiGeometryESModule/'trackerGeometry' to make data TrackerGeometry/'' in record TrackerDigiGeometryRecord
   [4] Running EventSetup component TrackerDigiGeometryESModule/'trackerGeometry
   [5] While getting dependent Record from Record TrackerDigiGeometryRecord
Exception Message:
No "GlobalPositionRcd" record found in the EventSetup.n
 The Record is delivered by an ESSource or ESProducer but there is no valid IOV for the synchronizatio value.
 Please check 
   a) if the synchronization value is reasonable and report to the hypernews if it is not.
   b) else check that all ESSources have been properly configured. 
----- End Fatal Exception -------------------------------------------------

**Comment by qliphy** [comment]
This seems to be due to https://github.com/cms-sw/cmssw/pull/35092

CMSSW_12_1_X_2021-08-31-2300 is fine.
CMSSW_12_1_X_2021-08-31-2300 + #35092 gives the error.

**Comment by qliphy** [comment]
assign @cms-sw/geometry-l2 

@srimanob

**Comment by srimanob** [comment]
Adding fake alignment will make things work.

```
process.load("Alignment.CommonAlignmentProducer.FakeAlignmentSource_cfi")
process.preferFakeAlign = cms.ESPrefer("FakeAlignmentSource") 
```

Here is the PR https://github.com/cms-sw/cmssw/pull/35119

**Comment by civanch** [comment]
Likely the issue fixed?

**Comment by srimanob** [comment]
Hi @civanch 
Yes, the issue is solved.

**Comment by civanch** [comment]
+1
