### ISSUE TITLE
Is dmtcp package used?

### ISSUE THREAD

**Issue by iarspider** [cms-sw/cmssw#35249]
We are cleaning unused cmsdist (externals) specs, and since there are no references to dmtcp (Distributed MultiThreaded CheckPointing) in cmssw repository, it is a candidate for removal.

**Comment by makortel** [comment]
Do we know who asked it to be included (i.e. who to ask if it is still needed)?

**Comment by davidlange6** [comment]
My inbox suggests that this came in from some r&d on checkpointing on opportunistic resources (eg, the HLT farm during interfile). At least that original use case didn't work out.

**Comment by smuzaffar** [comment]
I think it was @bbockelm who was working on checkpointing and xrootd had issues restoring the opened connection.

**Comment by davidlange6** [comment]
What I know about involved DavidA, DavidC and some external folks.

**Comment by bbockelm** [comment]
I'm not entirely sure I was doing much work here-- but last I could find in my inbox, this line of work dried up in 2015.

**Comment by smuzaffar** [comment]
@iarspider , looks like we can remove it from distribution. I would suggest to remove it from cmssw deps but keep the spec under cmsdist/archive directory.
