### ISSUE TITLE
`CkfTrackCandidateMaker` lacks `fillDescriptions` method

### ISSUE THREAD

**Issue by missirol** [cms-sw/cmssw#35344]
It was noted in #35309 that the plugin `CkfTrackCandidateMaker` is currently lacking a `fillDescriptions` method (see [comment](https://github.com/cms-sw/cmssw/pull/35309#discussion_r712333199)).

I was wondering if (tracking?) experts could have a look.

**Comment by slava77** [comment]
@mtosi @vmariani @mmusich 
please check and perhaps assign to someone in TRK POG.
Thank you.

**Comment by mmusich** [comment]
@slava77 @missirol 
At the moment there's no manpower available for this in the POG.
If it's urgent please feel free to implement it - we'll review.
Thanks

**Comment by mmusich** [comment]
@slava77 @missirol 
I came up with https://github.com/cms-sw/cmssw/pull/35385 in the spare time. It's completely un-validated at this point, but feel free to comment if that's what you need (in the meanwhile I'll run privately integration tests).

**Comment by missirol** [comment]
Thanks, Marco. I'll try to see if this can help with #35309.

**Comment by missirol** [comment]
I think #36459 and #36658 addressed this issue (and tested okay in IBs), so I'm closing this.
