### ISSUE TITLE
EtaExtendedElectrons to be allowed in PF in 12_4_X

### ISSUE THREAD

**Issue by swagata87** [cms-sw/cmssw#35374]
We are trying to put in EtaExtendedElectrons in 12_1_X. 
Relevant PR https://github.com/cms-sw/cmssw/pull/35309
But these new EtaExtendedElectrons will not have appropriate PF ID and suitable energy regression. 

So in 12_1_X, we will not allow them into particle flow. They stay only in GED electron collection.

It is done via the following switch in `RecoParticleFlow/PFProducer/python/particleFlow_cff.py`
```
particleFlowTmp.PFEGammaFiltersParameters.allowEEEinPF = cms.bool(False)
```

The plan is that we will train PF ID and regression including EtaExtendedElectrons using 12_1_X MC samples.
Then, in 12_2_X, we will allow EtaExtendedElectrons to particle flow, with appropriate ID and energy regression.

The above mentioned switch need to flip to `True` in 12_2_X. 
EGM POG will take care of it.

I'm creating this issue, as suggested by Joosep here
https://github.com/cms-sw/cmssw/pull/35309#discussion_r712951571

**Comment by makortel** [comment]
assign reconstruction

**Comment by jpata** [comment]
@swagata87 I forgot about this in the mean time

looks like it's still disabled:
https://github.com/cms-sw/cmssw/blob/e7954c10be88467f956edb66149926366d9dbcbf/RecoParticleFlow/PFProducer/python/particleFlow_cff.py#L15

is this on the timeline for 12_3_X (last open March 8)?

**Comment by swagata87** [comment]
Hi Joosep,

The overall plan has changed a bit since then. 
The EtaExtendedElectrons are in the release now, but the MC samples that contain these electrons are not yet produced. They are going to be produced soon using 12_2_X release (0.5 B POG sample). Using those MC samples, we will retrain our energy regression and PF Egamma ID, including these high eta electrons. We can then allow these electrons to PF, and we target 12_4_X to do this. Note that the big MC sample production for POG/PAG will also happen using 12_4_X, according to current plan. So, the big MC production will have everything from our side. 

Thanks,
Swagata.

**Comment by jpata** [comment]
thanks for the clarifications. would you mind updating the title to reflect the new timeline (12_4_X)?

**Comment by jpata** [comment]
type egamma

**Comment by swagata87** [comment]
this issue is addressed in this PR: https://github.com/cms-sw/cmssw/pull/37880

**Comment by jpata** [comment]
+reconstruction

**Comment by jpata** [comment]
@cmsbuild please close
