### ISSUE TITLE
Relvals failures in DBG IBs 

### ISSUE THREAD

**Issue by smuzaffar** [cms-sw/cmssw#35398]
Nearly all the relvals are failing [a] in DBG IBs (https://cmssdt.cern.ch/SDT/html/cmssdt-ib/#/relVal/CMSSW_12_1/2021-09-23-2300?selectedArchs=slc7_amd64_gcc900&selectedFlavors=DBG_X&selectedStatus=failed ) . Looks like error is generated at https://github.com/cms-sw/cmssw/blob/master/TrackingTools/TrackFitters/interface/DebugHelpers.h#L84 

[a]
```
HcalGeometry::getGeometry for (HE 20,23,2)  0 2995 0x2b6cf1f5b130
%MSG-eHcalGeometry::getGeometry for  BasicSingleTrajectoryState:  (HE 20,24,2)  0 GoodSeedProducer:trackerDrivenElectronSeeds 3023 0x2b6cf1f5c7f0
 HcalGeometry::getGeometry for (HE 20,25,2)  0 24-Sep-2021 10:48:29 CEST 3031 Run: 138924 Event: 50000x2b6cf1f5ce70

asking for componenets to a SingleTrajectoryStateHcalGeometry::getGeometry for (HE 20,26,2)  0 
%MSG3059 
cmsRun: TrackingTools/TrajectoryState/src/BasicTrajectoryState.cc:248: virtual const Components& BasicSingleTrajectoryState::components() const: Assertion `false' failed.
0x2b6cf1f5e530
HcalGeometry::getGeometry for (HE 20,27,2)  0 3067 0x2b6cf1f5ebb0
```

**Comment by smuzaffar** [comment]
assign reconstruction

**Comment by slava77** [comment]
this looks like a duplicate of #34097 

please post a note there and let's close this issue

**Comment by smuzaffar** [comment]
closing as it is duplicate of #34097.
