### ISSUE TITLE
Failure in 12_1_0_pre2 release validation for ROOT624

### ISSUE THREAD

**Issue by kskovpen** [cms-sw/cmssw#35453]
Hello,

We see the failures of this sort:

```
Fatal Exception (Exit code: 8022)
An exception of category 'FatalRootError' occurred while
[0] Calling InputSource::readRun_
Additional Info:
[a] Fatal Root Error: @SUB=TH1Merger::CheckForDuplicateLabels
Histogram effic_EGamma_HLT_Ele12_CaloIdL_TrackIdL_IsoVL_PFJet30_v18 
has duplicate labels in the x axis. Bin contents will be merged in a 
single bin
```

happening at the DQMIO step during the 12_1_0_pre2 release validation. More info: https://cms-unified.web.cern.ch/cms-unified/showlog/?search=CMSSW_12_1_0_pre2_ROOT624__fullsim_noPU_2021_14TeV-QCD_Pt_1800_2400_14-00001

@jfernan2 has already pointed out that it might be related to these lines: https://github.com/cms-sw/cmssw/blob/6d2f66057131baacc2fcbdd203588c41c885b42c/DQMOffline/Trigger/plugins/HLTFiltersDQMonitor.cc#L214-L222

Any help would be highly appreciated on how to resolve this!

Thanks a lot in advance,

PdmV 

FYI: @rappoccio @kmaeshima @bbilin @jmartinb @mdmorris @cms-sw/dqm-l2

**Comment by makortel** [comment]
assign dqm

**Comment by makortel** [comment]
Here are some earlier incarnations of a similar problem https://github.com/cms-sw/cmssw/issues/27472, https://github.com/cms-sw/cmssw/issues/32142

**Comment by perrotta** [comment]
@davidlange6

**Comment by Dr15Jones** [comment]
So the x labels appear to be the module labels in a path
https://github.com/cms-sw/cmssw/blob/6d2f66057131baacc2fcbdd203588c41c885b42c/DQMOffline/Trigger/plugins/HLTFiltersDQMonitor.cc#L198-L208

I have definitely seen that when people build Paths, they have the same module appear multiple times within a Path (the framework will only run it the first time in the path).

**Comment by jfernan2** [comment]
Adding  Egamma HLT DQM And Validation Code Developer(s):
@sushilchauhan @gomber @arunhep @swagata87 @lfinco @swagata87 
@archiron @beaudett @cmkuo @nancymarinelli @guitargeek

**Comment by nancymarinelli** [comment]
Hello
and what the failure would be ??
You talk about HLS and Validation code. Can you restrict the field ?

It would be possibly helpful .......
Nancy


________________________________________
Nancy Marinelli
Research Professor
University of Notre Dame, IN, US
CERN, Bdg 40/3-A01, 1211 Geneva
SWITZERLAND
Phone +41-22-76-70809
fax +41-22-76-78940

**Comment by jfernan2** [comment]
@nancymarinelli please read the thread above in github, not in the email

**Comment by swagata87** [comment]
trying to tag the other EGM-HLT convenor @ram1123

**Comment by makortel** [comment]
(following the discussion in core sw meeting) One difference wrt. the earlier cases (that were caught in IBs) is that earlier the failing workflow was 137.8 on 2018 data, whose last step is HARVESTING that merges two DQMIO files.

**Comment by missirol** [comment]
> I have definitely seen that when people build Paths, they have the same module appear multiple times within a Path (the framework will only run it the first time in the path).

Thanks for the hints. Indeed, I overlooked this when I wrote that piece of DQM. I tried to implement a fix in https://github.com/cms-sw/cmssw/pull/35467.

**Comment by jfernan2** [comment]
+1
For the records
