### ISSUE TITLE
Empty Trajectory exception in HLT step in many workflows

### ISSUE THREAD

**Issue by makortel** [cms-sw/cmssw#35488]
(At least) 5 workflows fail in the HLT step with exception like below
```
----- Begin Fatal Exception 30-Sep-2021 12:39:12 CEST-----------------------
An exception of category 'TrackingTools/PatternTools' occurred while
   [0] Processing  Event run: 1 lumi: 60 event: 2951 stream: 1
   [1] Running path 'HLT_DoubleTrkMu_16_6_NoFiltersNoVtx_v1'
   [2] Calling method for module CkfTrackCandidateMaker/'hltIterL3OITrackCandidatesNoVtx'
Exception Message:
Trajectory::check() - information requested from empty Trajectory 
----- End Fatal Exception -------------------------------------------------
```
* 11630.0: path `HLT_DoubleTrkMu_16_6_NoFiltersNoVtx_v1` module `HLT_DoubleTrkMu_16_6_NoFiltersNoVtx_v1` ([log](http://cmssdt.cern.ch/SDT/cgi-bin/logreader/slc7_amd64_gcc900/CMSSW_12_1_X_2021-09-30-1100/pyRelValMatrixLogs/run/11630.0_QCD_Pt_3000_3500_14TeV+2021+QCD_Pt_3000_3500_14TeV_TuneCUETP8M1_GenSimINPUT+Digi+Reco+HARVEST+ALCA/step2_QCD_Pt_3000_3500_14TeV+2021+QCD_Pt_3000_3500_14TeV_TuneCUETP8M1_GenSimINPUT+Digi+Reco+HARVEST+ALCA.log))
* 11650.911 path `HLT_DoubleTrkMu_16_6_NoFiltersNoVtx_v1` module `hltIterL3OITrackCandidatesNoVtx` ([log](https://cmssdt.cern.ch/SDT/cgi-bin/logreader/slc7_amd64_gcc900/CMSSW_12_1_X_2021-09-30-1100/pyRelValMatrixLogs/run/11650.911_ZMM_14+2021_DD4hep+ZMM_14TeV_TuneCP5_GenSim+Digi+Reco+HARVEST+ALCA/step2_ZMM_14+2021_DD4hep+ZMM_14TeV_TuneCP5_GenSim+Digi+Reco+HARVEST+ALCA.log#/))
* 11723.17 path `HLT_DoubleTrkMu_16_6_NoFiltersNoVtx_v1` module `hltIterL3OITrackCandidatesNoVtx` ([log](https://cmssdt.cern.ch/SDT/cgi-bin/logreader/slc7_amd64_gcc900/CMSSW_12_1_X_2021-09-30-1100/pyRelValMatrixLogs/run/11723.17_QCD_Pt_1800_2400_14+2021_seedingDeepCore+QCD_Pt_1800_2400_14TeV_TuneCP5_GenSimINPUT+Digi+Reco+HARVEST/step2_QCD_Pt_1800_2400_14+2021_seedingDeepCore+QCD_Pt_1800_2400_14TeV_TuneCP5_GenSimINPUT+Digi+Reco+HARVEST.log#/))
* 13034.0 path `HLT_TrkMu6NoFiltersNoVtx_v1` module `hltIterL3OITrackCandidatesNoVtx` ([log](https://cmssdt.cern.ch/SDT/cgi-bin/logreader/slc7_amd64_gcc900/CMSSW_12_1_X_2021-09-30-1100/pyRelValMatrixLogs/run/13034.0_TTbar_14TeV+2024PU+TTbar_14TeV_TuneCP5_GenSimINPUT+DigiPU+RecoPU+HARVESTPU+Nano/step2_TTbar_14TeV+2024PU+TTbar_14TeV_TuneCP5_GenSimINPUT+DigiPU+RecoPU+HARVESTPU+Nano.log#/))
* 13034.99 path `HLT_OldMu100_v3` module `hltL3TrackCandidateFromL2OIState` ([log](https://cmssdt.cern.ch/SDT/cgi-bin/logreader/slc7_amd64_gcc900/CMSSW_12_1_X_2021-09-30-1100/pyRelValMatrixLogs/run/13034.99_TTbar_14TeV+2024PU_PMXS1S2+TTbar_14TeV_TuneCP5_GenSimINPUT+PREMIX_PremixPU+DigiPU+RecoPU+HARVESTPU+Nano/step3_TTbar_14TeV+2024PU_PMXS1S2+TTbar_14TeV_TuneCP5_GenSimINPUT+PREMIX_PremixPU+DigiPU+RecoPU+HARVESTPU+Nano.log#/))

**Comment by makortel** [comment]
assign hlt, reconstruction

**Comment by makortel** [comment]
https://github.com/cms-sw/cmssw/pull/35309 looks like a likely cause

**Comment by missirol** [comment]
FYI @swagata87 (in case she has a guess on what the right fix is)

**Comment by swagata87** [comment]
I am running `runTheMatrix.py -l 11630.0` to see if I can reproduce the issue, 

I think I should have put a check like `if (!t.empty())` in 
TrackingTools/TrajectoryFiltering/interface/MinHitsTrajectoryFilter.h before accessing `t.lastMeasurement()`

this is what I suspect.. checking..

**Comment by swagata87** [comment]
I could reproduce the issue in `11630.0`, 
applied a fix in `TrackingTools/TrajectoryFiltering/interface/MinHitsTrajectoryFilter.h`, 
and reran `11630.0` w/o any problem this time

I'll check with other workflows reported here also (`11650.911, 11723.17, 13034.0, 13034.99`), and if all of them run fine then I will submit a bugfix PR with the fix. 

The WFs are taking a long time to run, but I think I will manage to submit the PR by tonight..

Sorry about the problems caused by my earlier PR

**Comment by slava77** [comment]
@vmariani @mmusich 
this may be of interest to you

IIUC, @swagata87 is available to check the fit. Thank you.

**Comment by makortel** [comment]
> (But unless any of the experts agrees, please proceed with your current plan.)

I could agree with that.

**Comment by VinInn** [comment]
How this could ever be happened?
HLT is essentially broken. This kind of issue should be caught before merging!

**Comment by jpata** [comment]
Is there a test we can add in the short matrix to catch this early? As I understand, some of the short matrix wfs run HLT, so it's not clear to me why the tests fail.

**Comment by jpata** [comment]
Noting here that the culprit PR was signed by HLT. I'm happy to hear the suggestions of experts how we can improve test coverage to catch this early.

**Comment by Martin-Grunewald** [comment]
PR tests did not catch this bug, plain and simple. Some bugs are only uncovered by IB tests as they involve many more workflows/statistics.

**Comment by makortel** [comment]
The list of failing workflows over IBs also suggests that there is some randomness there, possibly caused by running the DIGI step multithreaded (the DIGI step random number sequence for a given SIM event can change according to the EDM stream the SIM event gets processed by in the DIGI step, and that "stream assignment" can be affected e.g. my machine load).

**Comment by makortel** [comment]
Anyway, the fix has been merged, so closing the issue.
