### ISSUE TITLE
Duplication of clusterizers for bricked pixels

### ISSUE THREAD

**Issue by jpata** [cms-sw/cmssw#35519]
The following files were duplicated with minor modifications in https://github.com/cms-sw/cmssw/pull/35441.

- RecoLocalTracker/SiPixelClusterizer
  - plugins/PixelThresholdClusterizer.h -> plugins/PixelThresholdClusterizerForBricked.h
  - plugins/PixelThresholdClusterizer.cc -> pluginsPixelThresholdClusterizerForBricked.cc
- RecoLocalTracker/SiPixelRecHits
  - interface/PixelCPEGeneric.h -> interface/PixelCPEGenericForBricked.h
  - src/PixelCPEGeneric.cc -> src/PixelCPEGenericForBricked.cc

Per the comments https://github.com/cms-sw/cmssw/pull/35441#issuecomment-931370526, the duplication should be reviewed as soon as the studies with bricked pixels are done, and subsequently removed from the codebase (or otherwise rewritten to avoid duplication).

**Comment by jpata** [comment]
assign reconstruction

**Comment by jpata** [comment]
@franzglessgen can you let us know if there's any update on this? Are the studies concluded?

**Comment by franzglessgen** [comment]
Hi ! I do not think the studies are over yet, @emiglior might be more up to date about the latest development.

**Comment by emiglior** [comment]
Studies on Tracker geometries featuring bricked pixels are not done yet (ETA: end of January 2022)

**Comment by jpata** [comment]
a kind ping on this issue.

**Comment by jpata** [comment]
@franzglessgen @emiglior a kind ping on this issue

**Comment by jpata** [comment]
type trk

**Comment by jpata** [comment]
@emiglior @franzglessgen any news?

**Comment by mmusich** [comment]
The last bricked pixel geometry in cmssw is removed at https://github.com/cms-sw/cmssw/pull/38061. 
I guess that after that is merged support for a special local reco could be dropped afterwards, thus addressing this issue.

**Comment by emiglior** [comment]
Indeed the plan is to drop the special local reco for bricked pixels

The question is if removing the classes below is enough
    RecoLocalTracker/SiPixelClusterizer
       plugins/PixelThresholdClusterizerForBricked.h
       pluginsPixelThresholdClusterizerForBricked.cc
    RecoLocalTracker/SiPixelRecHits
        interface/PixelCPEGenericForBricked.h
        src/PixelCPEGenericForBricked.cc

or if you want to revert changes in the base classes as well

Few examples:
- remove the generic_position_formula_y_bricked in [SiPixelUtils.h](https://github.com/cms-sw/cmssw/pull/35441/files#diff-6823d93155cca138ad5e7c91d4226f7ef00b94deba85bfd0b2862bfb914c581fR22-R40l)
- revert from protected to private in [PixelThresholdClusterizer.h](https://github.com/cms-sw/cmssw/pull/35441/files#diff-269664a93bee1595ab9836c5186eb242fd3bc44666ea7257089e95b2863e0c1bL80)

@franzglessgen

**Comment by mmusich** [comment]
@jpata @cms-sw/reconstruction-l2 

can you give your opinion on https://github.com/cms-sw/cmssw/issues/35519#issuecomment-1137095662

**Comment by jpata** [comment]
The changes introduced in https://github.com/cms-sw/cmssw/pull/35441 that only support the bricked pixels and won't be tested/used/supported in the future should be removed.

Changes that were introduced in that PR that generally support code reuse in pixel local reco could stay.

**Comment by franzglessgen** [comment]
@emiglior I can remove those classes. Did I understand correctly that this should wait until this PR is merged ? Let me know when I can go ahead with the removal.
@jpata so the additional functions that were implemented within already existing classes can stay right ?

**Comment by jpata** [comment]
> so the additional functions that were implemented within already existing classes can stay right ?

I would say so, but I don't have an overview in front of me now, so you can exercise some judgement. My main point was that code that becomes unused and thus untested should be removed. Thanks for taking care of this!

**Comment by emiglior** [comment]
@franzglessgen yes, you have to wait that PR#38061 is merged

**Comment by franzglessgen** [comment]
Thanks for the notification, I am going on holiday this week so I'll start to clean up the code mid July if that's okay.

**Comment by tvami** [comment]
@franzglessgen please note https://github.com/cms-sw/cmssw/pull/38529

**Comment by franzglessgen** [comment]
Oh it has been done already, thanks for the info!

**Comment by jpata** [comment]
+reconstruction
- solved in https://github.com/cms-sw/cmssw/pull/38529
