### ISSUE TITLE
CSCDigiValidation leads to an exception in TF1::AddToGlobalList

### ISSUE THREAD

**Issue by makortel** [cms-sw/cmssw#35529]
Workflow 5.3 step 1 failed in CMSSW_12_1_X_2021-10-04-1300 with
```
Begin processing the 5th record. Run 1, Event 5, LumiSection 1 on stream 2 at 04-Oct-2021 17:33:59.822 CEST
----- Begin Fatal Exception 04-Oct-2021 17:33:59 CEST-----------------------
An exception of category 'FatalRootError' occurred while
   [0] Processing  Event run: 1 lumi: 1 event: 1 stream: 0
   [1] Running path 'validation_step'
   [2] Calling method for module CSCDigiValidation/'cscDigiValidation'
   Additional Info:
      [a] Fatal Root Error: @SUB=TF1::AddToGlobalList
Function is supposed to be in the global list but it is not present

----- End Fatal Exception -------------------------------------------------
```
https://cmssdt.cern.ch/SDT/cgi-bin/logreader/slc7_amd64_gcc900/CMSSW_12_1_X_2021-10-04-1300/pyRelValMatrixLogs/run/5.3_SingleMuPt100+SingleMuPt100FS+HARVESTFS/step1_SingleMuPt100+SingleMuPt100FS+HARVESTFS.log#/

**Comment by makortel** [comment]
assign dqm

**Comment by makortel** [comment]
In earlier IB's I saw this
* CMSSW_12_1_X_2021-10-04-1100 workflows 135.2, 2018.9
* CMSSW_12_1_X_2021-10-03-2300 workflows 45.0, 250406.0
* CMSSW_12_1_X_2021-10-03-0000 workflows 1361.181, 1366.0, 25406.0
* CMSSW_12_1_X_2021-10-02-1100 workflow 30.0

**Comment by makortel** [comment]
It is not immediately clear to me which of PRs merged in CMSSW_12_1_X_2021-10-02-1100 could have caused this error.

**Comment by dan131riley** [comment]
Discussed in https://github.com/cms-sw/cmssw/pull/35329#issuecomment-932760674
PR https://github.com/cms-sw/cmssw/pull/35528

**Comment by jfernan2** [comment]
+1
Solved in https://github.com/cms-sw/cmssw/pull/35528
