### ISSUE TITLE
cmsDriver with same options twice (e.g. procModifiers)

### ISSUE THREAD

**Issue by srimanob** [cms-sw/cmssw#35520]
Hi,

Could someone please remind if we have a discussion on using the same option more than one time in cmsDriver. For example, using `--procModifiers` twice,
`cmsDriver.py step3  -s RAW2DIGI:RawToDigi_pixelOnly,RECO:reconstruction_pixelTrackingOnly,VALIDATION:@pixelTrackingOnlyValidation,DQM:@pixelTrackingOnlyDQM --conditions auto:phase1_2021_dd4hep --datatier GEN-SIM-RECO,DQMIO -n 10 --eventcontent RECOSIM,DQM --procModifiers dd4hep --procModifiers pixelNtupletFit,gpu --geometry DB:Extended --era Run3 --customise RecoPixelVertexing/Configuration/customizePixelTracksForTriplets.customizePixelTracksForTriplets --io Reco_Patatrack_PixelOnlyTripletsGPU_2021.io --python Reco_Patatrack_PixelOnlyTripletsGPU_2021.py --no_exec --filein  file:step2.root  --fileout file:step3.root  --nThreads 8`
, this will pick the last procModifiers. 

I wonder if I should 

- make a check everywhere, i.e. in https://github.com/cms-sw/cmssw/blob/master/Configuration/PyReleaseValidation/python/upgradeWorkflowComponents.py
then extend it if exists

or 

- we should allow cmsDriver to accept the same option more than one time. However, one may need to update `upgradeWorkflowComponents.py` anyway on the workflows which use procModifiers. I think currently, it will overwrite.

I am looking forward if we will migrate DD4hep to the default workflow, what is the technical issue we need to pass. Thanks in advance.

**Comment by davidlange6** [comment]
> On Oct 4, 2021, at 9:29 AM, Phat Srimanobhas ***@***.***> wrote:
> 
> 
> Hi,
> 
> Could someone please remind if we have a discussion on using the same option more than one time in cmsDriver. For example,
> cmsDriver.py step3 -s ***@***.******@***.*** --conditions auto:phase1_2021_dd4hep --datatier GEN-SIM-RECO,DQMIO -n 10 --eventcontent RECOSIM,DQM --procModifiers dd4hep --procModifiers pixelNtupletFit,gpu --geometry DB:Extended --era Run3 --customise RecoPixelVertexing/Configuration/customizePixelTracksForTriplets.customizePixelTracksForTriplets --io Reco_Patatrack_PixelOnlyTripletsGPU_2021.io --python Reco_Patatrack_PixelOnlyTripletsGPU_2021.py --no_exec --filein file:step2.root --fileout file:step3.root --nThreads 8
> , this will pick the last procModifiers.
> 
> I wonder if I should
> 
> 	• make a check everywhere, i.e. in https://github.com/cms-sw/cmssw/blob/master/Configuration/PyReleaseValidation/python/upgradeWorkflowComponents.py
> then extend it if exists
> or
> 
> 	• we should allow cmsDriver to accept the same option more than one time. However, one may need to update upgradeWorkflowComponents.py anyway on the workflows which use procModifiers. I think currently, it will overwrite.

Multiple occurrences of an option are supported by the parser used by cmsDriver to parse the command line options. Eg, 

https://github.com/cms-sw/cmssw/blob/master/Configuration/Applications/python/Options.py#L123

So if you want the same option being specified more than once to track all occurrences, then the option parsing can do that.

**Comment by srimanob** [comment]
Thanks @davidlange6 
That is my point if we are OK to make `--procModifiers` in that way, or we see cons to make it.

**Comment by srimanob** [comment]
I make a draft PR, in case of discussion
https://github.com/cms-sw/cmssw/pull/35523

**Comment by makortel** [comment]
assign operations

**Comment by srimanob** [comment]
To complete the info before closing the issue, the following PR makes `--procModifier` to be a list.
https://github.com/cms-sw/cmssw/pull/35523
