### ISSUE TITLE
runTheMatrix.py `--command` option broken

### ISSUE THREAD

**Issue by smuzaffar** [cms-sw/cmssw#35565]
Looks like https://github.com/cms-sw/cmssw/pull/35263 change broke the `--command` option e.g the igprof jobs for 12.1.X are failing with error
```
runTheMatrix.py -w upgrade -l 23434.21 --command '-n 10 --profile pp'
usage: usage: runTheMatrix.py --show -s  [-h] [-b BATCHNAME] [-m MEMORYOFFSET]
                                         [--addMemPerCore MEMPERCORE]
....
                                         [--force-cuda-runtime-version CUDARUNTIMEVERSION]
usage: runTheMatrix.py --show -s : error: argument --command: expected one argument
```

Strange thing is that the following works

- `runTheMatrix.py -w upgrade -l 23434.21 --command ' -n 10 --profile pp'`
  which shows that `opt.command` is ` -n 10 --profile pp` 

- `runTheMatrix.py -w upgrade -l 23434.21 --command='-n 10 --profile pp'`
  which shows that `opt.command` is `-n 10 --profile pp` 

I will update the bot to add the extra `space` for igprof tests. I do not know if there is any fix to avoid this.

**Comment by smuzaffar** [comment]
FYI @srimanob

**Comment by smuzaffar** [comment]
FYI @ddaina

**Comment by smuzaffar** [comment]
I think issue is with `argparse` ( https://github.com/cms-sw/cmssw/pull/35263/files#diff-d025624692806aeb382410b51b6bb2e5c5e783710d03f4c3f41400e6cce40310R107 )

**Comment by kpedro88** [comment]
@smuzaffar yes, the recommended practice for nesting arguments with argparse is the syntax with the `=` sign.

**Comment by smuzaffar** [comment]
closing this issue. bot has been fixed to avoid this issue.
