### ISSUE TITLE
Default python version in CMSSW_12_X

### ISSUE THREAD

**Issue by hqucms** [cms-sw/cmssw#35574]
As I understand, from CMSSW_12_X the python2 support has been dropped. However, it seems that if one just runs `python` after setting up CMSSW, it still points to python2.7 instead of python3 (at least in `CMSSW_12_1_X_2021-10-05-2300` that I tried). Wouldn't it make more sense to make the default python to be python3?

**Comment by makortel** [comment]
assign core

**Comment by davidlange6** [comment]
I guess the master branch of cmssw no soon longer define "python" (this is already true in the devel branch). Then the question becomes if we want cmssw to behave differently than the os. Personally I don't think cmssw should behave differently than standards

At least on the cern systems:

On centos7: python->python2
On centos8: python -> nothing.

**Comment by smuzaffar** [comment]
> My feeling is that the current situation in CMSSW_12_X, i.e., having `python` pointing to `python2` which is not really supported in the release, actually breaks more things because pretty much any import of an external package (e.g., `import ROOT`) will fail. This is particularly inconvenient for python scripts starting with `#!/bin/env python` -- one widely used example is the [haddnano.py](https://github.com/cms-nanoAOD/nanoAOD-tools/blob/master/scripts/haddnano.py) from nanoAOD-tools -- it is py2/py3 compatible, but in the current situation it has to be modified to use `#!/bin/env python3` for CMSSW_12_X and kept to `#!/bin/env python` for older releases...

in this case, one is using cms provided tools/externals (and as we only support python3 for 12.1.X) so they should migrate to python3 or follow the trick david mentioned to above.

**Comment by makortel** [comment]
+core
