### ISSUE TITLE
Issues with ALCA and DQM modules on the MC express stream

### ISSUE THREAD

**Issue by jpata** [cms-sw/cmssw#35586]
As discussed in the Joint PPD/TRG/O&C Ops Meeting last week and today: https://indico.cern.ch/event/1083099/, there was a request to establish a throughput estimate for the express stream.
However, we are not successful in running the express configuration on MC, it looks like a problem with ALCA and DQM.

## Attempt 1
Taking the ALCA modules from https://github.com/dmwm/T0/blob/master/etc/ProdOfflineConfiguration.py#L226

Generating the express configuration as follows:
```python3
python3 src/Configuration/DataProcessing/test/RunExpressProcessing.py --nThreads 8 --scenario ppEra_Run3 --global-tag 121X_mcRun3_2021_realistic_v2 --lfn file:./5bb5b9a5-b9df-4d0f-8f80-7eca70d6264e.root --fevt --dqmio --alcarecos SiStripPCLHistos+SiStripCalZeroBias+SiStripCalMinBias+SiStripCalMinBiasAAG+TkAlMinBias+LumiPixelsMinBias+SiPixelCalZeroBias+PromptCalibProd+PromptCalibProdSiStrip+PromptCalibProdSiPixelAli+PromptCalibProdSiStripGains+PromptCalibProdSiStripGainsAAG+PromptCalibProdSiPixel
```
Running on the MC sample https://cmsweb.cern.ch/das/request?input=dataset%3D%2FRelValNuGun%2FCMSSW_12_1_0_pre3-121X_mcRun3_2021_realistic_v2-v1%2FGEN-SIM-DIGI-RAW 

we get a crash at
```
----- Begin Fatal Exception 07-Oct-2021 10:58:37 CEST-----------------------
An exception of category 'Configuration' occurred while
   [0] Processing  Event run: 1 lumi: 1 event: 3 stream: 2
   [1] Running path 'pathALCARECOSiStripCalMinBiasAAG'
   [2] Calling method for module HLTHighLevel/'ALCARECOSiStripCalMinBiasAAGHLT'
Exception Message:
 HLTHighLevel [instance: ALCARECOSiStripCalMinBiasAAGHLT - path: pathALCARECOSiStripCalMinBiasAAG]: No triggerList with key SiStripCalMinBiasAAG in AlCaRecoTriggerBitsRcd
----- End Fatal Exception -------------------------------------------------
```

## Attempt 2:
Removing most of the ALCA modules:
```
python3 src/Configuration/DataProcessing/test/RunExpressProcessing.py --nThreads 8 --scenario ppEra_Run3 --global-tag 121X_mcRun3_2021_realistic_v2 --lfn file:./5bb5b9a5-b9df-4d0f-8f80-7eca70d6264e.root --fevt --dqmio --alcarecos TkAlMinBias+SiStripCalMinBias
```

We now get a DQM crash at
```
----- Begin Fatal Exception 07-Oct-2021 11:02:31 CEST-----------------------
An exception of category 'ProductNotFound' occurred while
   [0] Processing  Event run: 1 lumi: 1 event: 3 stream: 3
   [1] Running path 'dqmoffline_step'
   [2] Calling method for module BTagPerformanceAnalyzerOnData/'bTagAnalysis'
Exception Message:
Principal::getByToken: Found zero products matching all criteria
Looking for type: reco::JetCorrector
Looking for module label: ak4PFCHSL1FastL2L3Corrector
Looking for productInstanceName: 

   Additional Info:
      [a] If you wish to continue processing events after a ProductNotFound exception,
add "SkipEvent = cms.untracked.vstring('ProductNotFound')" to the "options" PSet in the configuration.

----- End Fatal Exception -------------------------------------------------
```

**Comment by mmusich** [comment]
The issue with AlCa is just lack of the Express AlCaRecoTriggerBits in MC. That's a combination that was  never contemplated before.

**Comment by tvami** [comment]
Hi All,

We've created a new GT: 121X_mcRun3_2021_realistic_forpp900GeV_v2
I tested it with the recipe from above and now I only see the DQM problem.
More info in 
https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/4485/2/1/1.html

**Comment by tvami** [comment]
+alca
 * I believe this is resolved from the AlCa point of view, let us know if you need further action from our side

**Comment by jpata** [comment]
Thanks @tvami, ALCA seems fixed. Trying now on CMSSW_12_0_2, there is still a DQM error. @cms-sw/dqm-l2 for my understanding is this something that should work, or is this not supported?

Config:
```
python3 src/Configuration/DataProcessing/test/RunExpressProcessing.py --nThreads 8 \
  --scenario ppEra_Run3 \
  --global-tag 121X_mcRun3_2021_realistic_forpp900GeV_v2 file:./12d0db89-7974-4418-bb7e-1e2fbb548d2e.root \
  --fevt --dqmio \
  --alcarecos SiStripPCLHistos+SiStripCalZeroBias+SiStripCalMinBias+SiStripCalMinBiasAAG+TkAlMinBias+LumiPixelsMinBias+SiPixelCalZeroBias+PromptCalibProd+PromptCalibProdSiStrip+PromptCalibProdSiPixelAli+PromptCalibProdSiStripGains+PromptCalibProdSiStripGainsAAG+PromptCalibProdSiPixel
```

Exception:
```
----- Begin Fatal Exception 14-Oct-2021 15:16:14 CEST-----------------------
An exception of category 'ProductNotFound' occurred while
   [0] Processing  Event run: 1 lumi: 724 event: 72308 stream: 4
   [1] Running path 'dqmoffline_step'
   [2] Calling method for module BTagPerformanceAnalyzerOnData/'bTagAnalysis'
Exception Message:
Principal::getByToken: Found zero products matching all criteria
Looking for type: reco::JetCorrector
Looking for module label: ak4PFCHSL1FastL2L3Corrector
Looking for productInstanceName: 

   Additional Info:
      [a] If you wish to continue processing events after a ProductNotFound exception,
add "SkipEvent = cms.untracked.vstring('ProductNotFound')" to the "options" PSet in the configuration.

----- End Fatal Exception -------------------------------------------------
```

Input file:
```
xrdcp root://cms-xrd-global.cern.ch//store/relval/CMSSW_12_0_2_patch1/RelValMinBias_14TeV/GEN-SIM-DIGI-RAW/121X_mcRun3_2021_realistic_forpp900GeV_v1_JIRA137EraRun3-v2/10000/12d0db89-7974-4418-bb7e-1e2fbb548d2e.root ./
```

**Comment by mmusich** [comment]
> @standardDQM is chosen by default....

for my education what's wrong with it? 
I see this configuration has been run in the past many times (grepping for cmssw issues https://github.com/cms-sw/cmssw/search?q=RunExpressProcessing&type=issues), though usually on data and not on MC

> So at least you should set:
> DQM:@express

I am not sure `Configuration/DataProcessing` scripts  allow to do that (even though one might presume yes if Tier-0 is able to).

**Comment by jfernan2** [comment]
BTW: (I believe that) related to this issue and without aiming to justify DQM configurations, we have been trying to know what DOES EXACTLY Tier0 run in this JIRA ticket without success for more than two years

https://its.cern.ch/jira/browse/CMSTZ-427

If this test config file is a good aproximation it can be a perfectly fine starting point

**Comment by jfernan2** [comment]
Yes, I confirm @mmusich explanation: @express is more for RelVals while the default DQM sequence in CMSSW is @standardDQM

**Comment by jfernan2** [comment]
No, Tier0 configs are driven in this file:
https://github.com/dmwm/T0/blob/master/etc/ProdOfflineConfiguration.py
as you know. However, if no explicit sequence is set, default is @standardDQM 
However, as it has been discussed in this thread, it won't work for AlCa due to missing products
Do we need to set a default sequence which works for every stream?
Thanks

**Comment by tvami** [comment]
Is there any news on this?

**Comment by mmusich** [comment]
> DQM is fine with moving `@standardDQM` to `@express` for the Tie0 Express configuration

I suspect that the current CMSSW setup doesn't allow to do that to unless one applies the patch at https://github.com/cms-sw/cmssw/issues/35586#issuecomment-943536648

**Comment by jfernan2** [comment]
Yes, of course, with the patch in, otherwise there is no option, Sorry that I was not explicit enough. I can make the PR unless someone else prefers to take care of it

**Comment by tvami** [comment]
> 

Yes, I think so!

**Comment by jfernan2** [comment]
So, I guess I should close too the PR I made for fixing this issue which was put on hold:
https://github.com/cms-sw/cmssw/pull/35850

**Comment by tvami** [comment]
Let me double document that I created new GTs 
* for HI: 121X_mcRun3_2021_realistic_HI_forExpressRateStudies
diff: https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/121X_mcRun3_2021_realistic_HI_v15/121X_mcRun3_2021_realistic_HI_forExpressRateStudies
(also has relevance zero material changes, can be ignored)
* for cosmics: 121X_mcRun3_2021cosmics_realistic_deco_forExpressRateStudies
diff: https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/121X_mcRun3_2021cosmics_realistic_deco_v15/121X_mcRun3_2021cosmics_realistic_deco_forExpressRateStudies
(same conclusion)

For completeness, the pp GT was called
121X_mcRun3_2021_realistic_v11Based_forExpressRateStudies
as announced earlier https://github.com/cms-sw/cmssw/issues/35586#issuecomment-938957276

**Comment by jfernan2** [comment]
+1
