### ISSUE TITLE
[UBSAN] 'value' may be used uninitialized in GBRForestTools.cc

### ISSUE THREAD

**Issue by iarspider** [cms-sw/cmssw#35607]
[UBSAN](https://cmssdt.cern.ch/SDT/cgi-bin/buildlogs/slc7_amd64_gcc10/CMSSW_12_1_UBSAN_X_2021-10-08-2300/CommonTools/MVAUtils)

```
src/CommonTools/MVAUtils/src/GBRForestTools.cc: In function 'std::unique_ptr<GBRForest> {anonymous}::init(const string&, std::vector<std::__cxx11::basic_string<char> >&)':
  src/CommonTools/MVAUtils/src/GBRForestTools.cc:163:18: warning: 'value' may be used uninitialized in this function [-Wmaybe-uninitialized]
   163 |       info[name] = value;
```

[source](https://github.com/cms-sw/cmssw/blob/master/CommonTools/MVAUtils/src/GBRForestTools.cc#L159-L163)

Maybe check return values of all `QueryFooAttribute` calls - just in case the XML format changes?

**Comment by iarspider** [comment]
assign reconstruction

**Comment by jpata** [comment]
I no longer see GBRForestTools.cc in the [UBSAN list](https://cmssdt.cern.ch/SDT/jenkins-artifacts/ubsan_logs/CMSSW_12_5_X_2022-08-24-1100/).

Looking in the history, I think it was addressed here: https://github.com/cms-sw/cmssw/pull/35705

**Comment by jpata** [comment]
@cmsbuild please close
