### ISSUE TITLE
Crash in `visualization` DQM clients during SPLASH test

### ISSUE THREAD

**Issue by francescobrivio** [cms-sw/cmssw#35634]
A crash in the vizualization DQM clients was reported by @pmandrik during the SPLASH test. The clients crashing are:
[visualization-live_cfg.py](https://github.com/cms-sw/cmssw/blob/master/DQM/Integration/python/clients/visualization-live_cfg.py)
[visualization-live-secondInstance_cfg.py](https://github.com/cms-sw/cmssw/blob/master/DQM/Integration/python/clients/visualization-live-secondInstance_cfg.py)
And the crash error is:
```
----- Begin Fatal Exception 12-Oct-2021 16:07:52 CEST-----------------------
An exception of category 'NoRecord' occurred while
   [0] Processing  Event run: 345570 lumi: 1 event: 4035 stream: 2
   [1] Running path 'FEVToutput_step'
   [2] Prefetching for module JsonWritingTimeoutPoolOutputModule/'FEVToutput'
   [3] Prefetching for module ReducedRecHitCollectionProducer/'reducedEcalRecHitsEB'
   [4] Prefetching for module InterestingDetIdCollectionProducer/'interestingEcalDetIdPFEB'
   [5] Prefetching for module PFECALSuperClusterProducer/'particleFlowSuperClusterECAL'
   [6] Calling method for module BeamSpotOnlineProducer/'offlineBeamSpot'
Exception Message:
No "BeamSpotTransientObjectsRcd" record found in the EventSetup.n
 Please add an ESSource or ESProducer that delivers such a record.
----- End Fatal Exception -------------------------------------------------
```
The crash can be easily riproduced by running the unitTest:
```
cmsrel CMSSW_12_0_2_patch1
cd CMSSW_12_0_2_patch1/src
cmsenv
git cms-addpkg DQM/Integration
cmsRun DQM/Integration/python/clients/visualization-live_cfg.py unitTest=True
```
DQM online experts can also reproduce the crash in their playback system at P5.

This crash happens **only** when running with the scenario `ppEra_Run3` and **don't crash** when running with scenario `cosmicsEra_Run3`. 
IIUC this is because the reco requence in the two cases is different and in in the `pp` case the beamspot is required.
Looking into the configuration I can see that the offlineBeamSpot has been swapped with the onlineBeamSpot:
```
(Pdb) process.offlineBeamSpot
cms.EDProducer("BeamSpotOnlineProducer",
    changeToCMSCoordinates = cms.bool(False),
    gtEvmLabel = cms.InputTag("gtEvmDigis"),
    maxRadius = cms.double(2),
    maxZ = cms.double(40),
    setSigmaZ = cms.double(-1),
    src = cms.InputTag("scalersRawToDigi"),
    useTransientRecord = cms.bool(True)
)
``` 
and the only place this swapping happens is in: https://github.com/cms-sw/cmssw/blob/922a36d28f367fe6a5a7feb4f000d7e460b5c43a/Configuration/DataProcessing/python/RecoTLR.py#L7-L15
which is used to customize the express processing. So now the sequence will look for a `BeamSpotTransientObjectsRcd` but apparently that is not provided by any Source and this is not clear to me because the express customization automatically adds the BeamSpotESProducer.

A quick solution would then be to add the ESProducer to the DQM clients:
```
process.load("CondCore.CondDB.CondDB_cfi")
process.BeamSpotESProducer = cms.ESProducer("OnlineBeamSpotESProducer")
```
But I'm not sure if that is the correct way of doing it or if it's better to understand how the customization of the `visualizationProcessing` works and eventually modify it?

[EDIT]
The quick solution to add the ESProducer to the DQM clients was already somehow used in https://github.com/cms-sw/cmssw/pull/35373

**Comment by mmusich** [comment]
@francescobrivio 
I think the customization in `Configuration/DataProcessing/python/RecoTLR.py` only takes care of explicitly customized workflows (such as 138.2)
For the general case, something is missing here:

https://github.com/cms-sw/cmssw/blob/df9a14409e2b2b6cb80832d0129c4890968f1202/RecoVertex/BeamSpotProducer/python/BeamSpot_cfi.py#L7-L9

see please https://github.com/cms-sw/cmssw/pull/35639.

I managed to (almost) run your recipe above with it:

```console
cmsrel CMSSW_12_0_2_patch1
cd CMSSW_12_0_2_patch1/src
cmsenv
git cms-addpkg DQM/Integration
cmsRun DQM/Integration/python/clients/visualization-live_cfg.py unitTest=True
```

though now it crashes differently with:

```
----- Begin Fatal Exception 13-Oct-2021 10:41:57 CEST-----------------------
An exception of category 'NoProxyException' occurred while
   [0] Processing  Event run: 334393 lumi: 1 event: 16188 stream: 0
   [1] Running path 'FEVToutput_step'
   [2] Prefetching for module JsonWritingTimeoutPoolOutputModule/'FEVToutput'
   [3] Prefetching for module ReducedRecHitCollectionProducer/'reducedEcalRecHitsEB'
   [4] Prefetching for module EleIsoDetIdCollectionProducer/'interestingGedEleIsoDetIdEB'
   [5] Calling method for module GEDGsfElectronFinalizer/'gedGsfElectrons'
Exception Message:
No data of type "GBRForestD" with label "electron_eb_ecalOnly_1To300_0p2To2_mean" in record "GBRDWrapperRcd"
 Please add an ESSource or ESProducer to your job which can deliver this data.
----- End Fatal Exception -------------------------------------------------
```

somewhat consistently with this comment:

https://github.com/cms-sw/cmssw/blob/df9a14409e2b2b6cb80832d0129c4890968f1202/DQM/Integration/test/BuildFile.xml#L32-L34

what's @cms-sw/alca-l2 plan to fix that?

**Comment by francescobrivio** [comment]
@pmandrik could you run again the playback including PR https://github.com/cms-sw/cmssw/pull/35653 (backport to 120X kindly provided by @mmusich) ?

**Comment by pmandrik** [comment]
Hello, we checked that Event Display clients run fine with this PR for ppEra_Run3 scenario at the playback, thanks
