### ISSUE TITLE
[UBSAN] warning: '<anonymous>' may be used uninitialized in this function (L1TriggerConfig/GMTConfigProducers/interface/RecordHelper.h)

### ISSUE THREAD

**Issue by iarspider** [cms-sw/cmssw#35706]
[Log example](https://cmssdt.cern.ch/SDT/cgi-bin/buildlogs/slc7_amd64_gcc10/CMSSW_12_1_UBSAN_X_2021-10-15-2300/L1TriggerConfig/GMTConfigProducers)

```
In file included from  src/L1TriggerConfig/GMTConfigProducers/src/L1MuGMTParametersOnlineProducer.cc:21:
 src/L1TriggerConfig/GMTConfigProducers/interface/RecordHelper.h: In member function 'void ASCIIBoolFieldHandler<TOutput, FalseCharacter>::extractValue(const AttributeList&, TOutput&) [with TOutput = L1MuGMTParameters; char FalseCharacter = '0']':
   src/L1TriggerConfig/GMTConfigProducers/interface/RecordHelper.h:105:21: warning: '<anonymous>' may be used uninitialized in this function [-Wmaybe-uninitialized]
   105 |     ((dest).*(this->setter_))(value != FalseCharacter);
      |              ~~~~~~~^~~~~~~~
```

**Comment by makortel** [comment]
From a quick visual inspection it is not really clear why the compilation with UBSAN complains about that. The only constructor of the class
https://github.com/cms-sw/cmssw/blob/2625240908ff0eb2ef39fb795d76c8a1a9b91973/L1TriggerConfig/GMTConfigProducers/interface/RecordHelper.h#L96-L97
forwards the `setter` to the base class
https://github.com/cms-sw/cmssw/blob/2625240908ff0eb2ef39fb795d76c8a1a9b91973/L1TriggerConfig/GMTConfigProducers/interface/RecordHelper.h#L64-L65
which always initializes the `setter_` member.

Given that UBSAN compilation does not complain about the similar use of `setter_` in the base class
https://github.com/cms-sw/cmssw/blob/2625240908ff0eb2ef39fb795d76c8a1a9b91973/L1TriggerConfig/GMTConfigProducers/interface/RecordHelper.h#L74
perhaps abstracting the `setter_` call in the base class along
```cpp
protected:
  void set(TOutput& dest, TCField value) {
    std::invoke(setter_, &dest, value);
  }
```
would work around the warning? (in principle it would provide also a better encapsulation by restricting what the deriving classes can do, see also the general recommendation on `protected` member data in C++ Core Guidelines https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#Rh-protected)

**Comment by smuzaffar** [comment]
closing this as we do not see this warning any more for UBSAN IBs
