### ISSUE TITLE
Using debug jemalloc version with CMSSW_12_0_2

### ISSUE THREAD

**Issue by smorovic** [cms-sw/cmssw#35729]
Hello,

I would like to retool CMSSW to a debug jemalloc version to investigate memory corruption issues seen during 15-17 Oct in HLT (although crashes have, as of now, disappeared after Monday morning after appearing all wekend). Crashes are possibly related to condition data, since there have been coinciding with network issues, but we are not certain about it. Still we'd like to have tools ready to debug in case they appear again.

It was suggested by frontier experts, which helped with investigation since many crashes appeared in frontier client code, to turn on debugging in allocator.

I see that CMSSW 12_0_2 (slc7_amd64_gcc900) currently installs jemalloc v5.2.1, but also a debug version 4.5.0:
external+jemalloc+5.2.1-cms
external+jemalloc-debug+4.5.0-cms

Are debug builds suitable for inspecting memory corruption issues, for example is the thread caching disabled (`MALLOC_CONF=tcache:false`) as described here?:
https://github.com/jemalloc/jemalloc/wiki/Use-Case%3A-Find-a-memory-corruption-bug

Since debug version is older, can it be user in place of 5.2.1? If this is not the case, I would like to ask for a debug build of 5.2.1.

Regarding how to switch the allocator, is it sufficient to just do modifications in xml file `config/toolbox/slc7_amd64_gcc900/tools/selected/jemalloc.xml` + scram setup or is it more involved?

Best regards,
Srecko Morovic

**Comment by smuzaffar** [comment]
@smorovic , regard your question about using jemalloc-debug , yes updating config/toolbox/slc7_amd64_gcc900/tools/selected/jemalloc.xml ( just update the JEMALLOC_BASE to point to jemalloc-debug install location) and scram setup + cmsenv is enough to for cmsRun to start using jemalloc debug

**Comment by smorovic** [comment]
Thank you, @smuzaffar for sorting this out.
I will then close the issue.
