### ISSUE TITLE
review and possibly disable looper reconstruction for HeavyIons pp_on_* 

### ISSUE THREAD

**Issue by slava77** [cms-sw/cmssw#35758]
This is a follow up to https://github.com/cms-sw/cmssw/pull/35721#discussion_r732195821

in that PR the looper reconstruction was disabled for pp starting from Run-2.

To reduce divergence in the configuration and perhaps even improve the HI tracking, including getting somewhat faster tracking, 
the proposal for the software is to drop removal of `trackingNoLoopers` in  the HI `pp_on_*` eras. 

@abaty @mandrenguyen

@cms-sw/tracking-pog-l2

**Comment by slava77** [comment]
assign reconstruction

**Comment by mmusich** [comment]
addressed at #37833

**Comment by mmusich** [comment]
type tracking

**Comment by jpata** [comment]
It was discussed here: https://github.com/cms-sw/cmssw/pull/38288 that looper reco will be disabled for Run2_2018 and Run3.

In the future, it might be good to investigate other periods of Run2 for a consistent setup.

**Comment by mandrenguyen** [comment]
+reconstruction
Loopers were disabled in pp_on_* as the PR title says.
I don't think it makes sense to revisit earlier ion running periods than 2018

**Comment by mandrenguyen** [comment]
Closed #35758 as completed.

**Comment by mmusich** [comment]
please close 
   * see https://github.com/cms-sw/cmssw/issues/35758#issuecomment-1330850189
