### ISSUE TITLE
PFCluster depth 0.9999 instead of 1.0 in hltParticleFlowClusterHBHE

### ISSUE THREAD

**Issue by silviodonato** [cms-sw/cmssw#35923]
We have found the origin of the differences GPU/CPU related to HCAL. These differences appeared only in PFJets, while there was a perfect CPU/GPU match in CaloJets.

The problem is in the `depth` variable, that is an `int` in `PFRecHit` and a `double` in `PFCluster`. 
In the HLT menu we have:

`hltParticleFlowRecHitHBHE` [`PFRecHitProducer`] -> 
`hltParticleFlowClusterHBHE` [`PFClusterProducer`] -> 
`hltParticleFlowClusterHCAL` -> [`PFMultiDepthClusterProducer`]

The problem is in the `hltParticleFlowClusterHBHE` which gives  0.99999 instead of 1.0 for some PFClusters.
As a result, `hltParticleFlowClusterHCAL` will consider the PFCluster in the category [0-1] instead of [1-2].

You can find the HLT configuration at  `/afs/cern.ch/work/s/sdonato/public/HCalGPUevent/hlt_Patatrack_HCalOnlyGPU.py` which runs on Run2 data.

The differences can be resolved by using directly `hltParticleFlowRecHitHBHE` [`PFRecHitProducer`] ->  `hltParticleFlowClusterHCAL` -> [`PFMultiDepthClusterProducer`]

or using this temporary patch https://github.com/silviodonato/cmssw/commit/1895dd23c3f5e480035eb497df64218eea4b1b7f
I let @cms-sw/reconstruction-l2 @cms-sw/pf-l2 @cms-sw/hcal-dpg-l2 open a PR to fix this issue.

```
process.hltParticleFlowClusterHCAL = cms.EDProducer("PFMultiDepthClusterProducer",
    clustersSource = cms.InputTag("hltParticleFlowClusterHBHE"),
    energyCorrector = cms.PSet(

    ),
    pfClusterBuilder = cms.PSet(
        algoName = cms.string('PFMultiDepthClusterizer'),
        allCellsPositionCalc = cms.PSet(
            algoName = cms.string('Basic2DGenericPFlowPositionCalc'),
            logWeightDenominatorByDetector = cms.VPSet(
                cms.PSet(
                    depths = cms.vint32(1, 2, 3, 4),
                    detector = cms.string('HCAL_BARREL1'),
                    logWeightDenominator = cms.vdouble(0.8, 0.8, 0.8, 0.8)
                ),
                cms.PSet(
                    depths = cms.vint32(
                        1, 2, 3, 4, 5,
                        6, 7
                    ),
                    detector = cms.string('HCAL_ENDCAP'),
                    logWeightDenominator = cms.vdouble(
                        0.1, 0.2, 0.2, 0.2, 0.2,
                        0.2, 0.2
                    )
                )
            ),
            minAllowedNormalization = cms.double(1e-09),
            minFractionInCalc = cms.double(1e-09),
            posCalcNCrystals = cms.int32(-1)
        ),
        minFractionToKeep = cms.double(1e-07),
        nSigmaEta = cms.double(2.0),
        nSigmaPhi = cms.double(2.0)
    ),
    positionReCalc = cms.PSet(

    )
)
```

**Comment by silviodonato** [comment]
cc @cms-sw/heterogeneous-l2

**Comment by fwyzard** [comment]
assign reconstruction pf hcal-dpg heterogeneous

**Comment by fwyzard** [comment]
assign reconstruction

**Comment by fwyzard** [comment]
assign pf

**Comment by fwyzard** [comment]
assign hcal-dpg

**Comment by fwyzard** [comment]
assign heterogeneous

**Comment by silviodonato** [comment]
I made a printout of the `depth()` of the `hltParticleFlowClusterHBHE` for both CPU and GPU.
The problem appears in both cases. So I strongly suspect that also our current CPU reconstruction is bugged.
```
GPU vs CPU
3.9999999999999996 4.0
3.9999999999999996 4.0
2.0 2.0
2.0 2.0
2.9999999469579657 3.000000017680678
2.0 2.0
2.0 1.9999999999999998
2.0 2.0
2.0 2.0
2.0 2.0
2.0 2.0
2.0 2.0
2.0 2.0
2.0 2.0
2.0 2.0
1.9999999999999998 1.9999999999999998
2.0 2.0
2.0 2.0
2.0 2.0
2.0 2.0
1.9999999999999998 2.0
2.0 1.9999999999999998

```

**Comment by fwyzard** [comment]
> The problem is in the `depth` variable, that is an `int` in `PFRecHit` and a `double` in `PFCluster`.

If I read the code correctly, for the rechits the depth comes from a single "segment", while for the clusters it is the weighted average of the input rechits.

Could you dump the depth of the rechits ?

**Comment by silviodonato** [comment]
> > The problem is in the `depth` variable, that is an `int` in `PFRecHit` and a `double` in `PFCluster`.
> 
> If I read the code correctly, for the rechits the depth comes from a single "segment", while for the clusters it is the weighted average of the input rechits.
> 
> Could you dump the depth of the rechits ?

The PFRecHits are all **integer** numbers between 1 and 7.
They start with 155 times `1`, then 15 times `2`, then again 167 time `1` and so on.
Note that there is no `0`.
In some PFClusters I got some `0.9999999999999999`, so it must be the floating point approximation.

You can find the reconstructed objects in `/afs/cern.ch/work/s/sdonato/public/HCalGPUevent/output_HCAL_GPU.root` and ..CPU.root

**Comment by hatakeyamak** [comment]
HLT's `hltParticleFlowClusterHBHE` or offline's `particleFlowClusterHBHE` are supposedly layer-wise clusters, where we don't intend to mix different depths. Probably somebody can look at constituent rechits and their depth to get insight what's going on in these cases.

**Comment by fwyzard** [comment]
> > > The problem is in the `depth` variable, that is an `int` in `PFRecHit` and a `double` in `PFCluster`.
> > 
> > 
> > If I read the code correctly, for the rechits the depth comes from a single "segment", while for the clusters it is the weighted average of the input rechits.
> > Could you dump the depth of the rechits ?
> 
> The PFRecHits are all **integer** numbers between 1 and 7. 

Obviously, because each rechit can only belong to any one specific segment, so they have an **integer** value for the depth.

> They start with 155 times `1`, then 15 times `2`, then again 167 time `1` and so on. Note that there is no `0`. 

Which makes sense.
My question was whether on CPU and on GPU we have the same exact number of rechits, and if they have the same integer depth, or not.

> In some PFClusters I got some `0.9999999999999999`, so it must be the floating point approximation.

I agree. I am simply wondering why the results of the floating point approximations are different; since the code (and the compiled binary) is the same, there must be some difference in the _inputs_ : either the number of rechits, or their energy (and thus the weights used in the computation), or the depths (which is unlilely, since each rechit should know exactly where it comes from).

The question is orthogonal to the more general issue of the floating point approximation being used here, which as you wrote is likely causing some bugs already in the original cpu-only configuration.

**Comment by fwyzard** [comment]
> HLT's `hltParticleFlowClusterHBHE` or offline's `particleFlowClusterHBHE` are supposedly layer-wise clusters, where we don't intend to mix different depths.

Ah, understood. Maybe a more robust implementation would be to just assign the depth based on the integer value, instead of computing the weighted average.

**Comment by silviodonato** [comment]
> I agree. I am simply wondering why the results of the floating point approximations are different; since the code (and the compiled binary) is the same, there must be some difference in the _inputs_ : either the number of rechits, or their energy (and thus the weights used in the computation), or the depths (which is unlilely, since each rechit should know exactly where it comes from).

Yes, there is some tiny difference in the energy at the level of 10^-5/10^-6 in hltParticleFlowClusterHBHE this might explain the different value offline.

@cms-sw/reconstruction-l2

**Comment by VinInn** [comment]
if the issue is limited to rounding of integers I suggest to change the limit of ```category [0-1]  [1-2]``` etc to [0-1.1] [1.01-2.01] etc

**Comment by fwyzard** [comment]
or even `[0-1.5]`, `[1.5-2.5]`, etc ...

or use `std::round()` for the depth ...

**Comment by silviodonato** [comment]
I though the thresholds were set by
```
                    depths = cms.vint32(1, 2, 3, 4),
```
but I was wrong, they come from `RecoParticleFlow/PFClusterProducer/plugins/PFMultiDepthClusterizer.cc` (eg. https://github.com/cms-sw/cmssw/blob/master/RecoParticleFlow/PFClusterProducer/plugins/PFMultiDepthClusterizer.cc#L178-L182)

I checked that https://github.com/silviodonato/cmssw/commit/2077cfd519ed174a887bf762f18f2ff0d4053405 solves the problem as well, while replacing `dz < 0.0f` with `dz < -0.001f` seems not sufficient.

Anyhow, I think it is better to fix the problem directly in the PFCluster, so I've made https://github.com/cms-sw/cmssw/pull/35937

**Comment by mariadalfonso** [comment]
> HLT's `hltParticleFlowClusterHBHE` or offline's `particleFlowClusterHBHE` are supposedly layer-wise clusters, where we don't intend to mix different depths. (hltParticleFlowClusterHCAL`or offline's`particleFlowClusterHCAL` are multi-depth clusters.) Probably somebody can look at constituent rechits and their depth to get insight what's going on in these cases.

@hatakeyamak 
The HCAL-readout-depth numbering (color in the figure well defined integer) is different than the "deepness" of a PFcluster. see the cartoon for HE.
So a cluster can have rechits in different HCAL-depth even if the rechits have the same z position.
Where this conversion is handled ?
![HE](https://user-images.githubusercontent.com/5656714/139672797-1c3ad242-3988-4a17-8b4b-2c8775b8d219.png)

**Comment by slava77** [comment]
@laurenhay @marksan87 
just in case you have not noticed this already for PF

**Comment by silviodonato** [comment]
@cms-sw/pf-l2 
I think you should check and fix all the selections based on `dz` and `0`
Example 1. `if (dz < 0.0f` in https://github.com/cms-sw/cmssw/blob/master/RecoParticleFlow/PFClusterProducer/plugins/PFMultiDepthClusterizer.cc#L178-L182

Example 2. https://github.com/cms-sw/cmssw/blob/master/RecoParticleFlow/PFClusterProducer/plugins/PFMultiDepthClusterizer.cc#L220-L224
which is equivalent to
```
if (link1.dZ() < link2.dZ()) [...]
else if (link1.dZ() > link2.dZ()) [...]
else if (link1.dZ() == link2.dZ())  [...]
```

**Comment by silviodonato** [comment]
@cms-sw/pf-l2 @cms-sw/reconstruction-l2 do you know if anybody is working on this?
This change will affects the physics results and we definitely need this fix in CMSSW_12_2_0 (last open pre-release [2021/11/09](https://twiki.cern.ch/twiki/bin/view/CMS/CMSSW_12_2_0))

**Comment by kdlong** [comment]
Yes @silviodonato we are looking at it with @hatakeyamak and @marksan87

**Comment by Martin-Grunewald** [comment]
Ping: would appreciate a 12_2 PR asap! Thanks!

**Comment by marksan87** [comment]
> Ping: would appreciate a 12_2 PR asap! Thanks!

There is a PR coming soon. Apologies for the delay!

**Comment by hatakeyamak** [comment]
@marksan87 Thank you. Is it explicitly tested that this will indeed solve the CPU vs GPU PFJet differences?

**Comment by hatakeyamak** [comment]
> > HLT's `hltParticleFlowClusterHBHE` or offline's `particleFlowClusterHBHE` are supposedly layer-wise clusters, where we don't intend to mix different depths. (hltParticleFlowClusterHCAL`or offline's`particleFlowClusterHCAL` are multi-depth clusters.) Probably somebody can look at constituent rechits and their depth to get insight what's going on in these cases.
> 
> @hatakeyamak The HCAL-readout-depth numbering (color in the figure well defined integer) is different than the "deepness" of a PFcluster. see the cartoon for HE. So a cluster can have rechits in different HCAL-depth even if the rechits have the same z position. Where this conversion is handled ? ![HE](https://user-images.githubusercontent.com/5656714/139672797-1c3ad242-3988-4a17-8b4b-2c8775b8d219.png)

@mariadalfonso I am aware of this complication, but it's not clear how to handle the transition of depth segmentation vs ieta, so currently the layer-wise clusters are done based on depth, and the assumption is that this is ok as long as we connect clusters from different depth in 3D clusters.

**Comment by mariadalfonso** [comment]
> > > HLT's `hltParticleFlowClusterHBHE` or offline's `particleFlowClusterHBHE` are supposedly layer-wise clusters, where we don't intend to mix different depths. (hltParticleFlowClusterHCAL`or offline's`particleFlowClusterHCAL` are multi-depth clusters.) Probably somebody can look at constituent rechits and their depth to get insight what's going on in these cases.
> > 
> > 
> > @hatakeyamak The HCAL-readout-depth numbering (color in the figure well defined integer) is different than the "deepness" of a PFcluster. see the cartoon for HE. So a cluster can have rechits in different HCAL-depth even if the rechits have the same z position. Where this conversion is handled ? ![HE](https://user-images.githubusercontent.com/5656714/139672797-1c3ad242-3988-4a17-8b4b-2c8775b8d219.png)
> 
> @mariadalfonso I am aware of this complication, but it's not clear how to handle the transition of depth segmentation vs ieta, so currently the layer-wise clusters are done based on integer depth, and the assumption is that this is ok as long as we connect clusters from different depth in 3D clusters.

ok, as soon as you do the 3D clusters and not mix the eta when doing the "layer wise cluster" energy weighted as discussed here.
so the  layer-wise clusters at transitions can mix the depth ?

**Comment by hatakeyamak** [comment]
The layer-wise clusters don't mix the depth, but multi-depth clustering steps mix the depths.

**Comment by hatakeyamak** [comment]
> > @mariadalfonso I am aware of this complication, but it's not clear how to handle the transition of depth segmentation vs ieta, so currently the layer-wise clusters are done based on integer depth, and the assumption is that this is ok as long as we connect clusters from different depth in 3D clusters.
> 
> ok, as soon as you do the 3D clusters and not mix the eta when doing the "layer wise cluster" energy weighted as discussed here. so the layer-wise clusters at transitions can mix the depth ?

The layer-wise cluster don't mix the depths, but multi-depth clusters mix the depths.

**Comment by fwyzard** [comment]
> The layer-wise cluster don't mix the depths

Based on the actual depth, or on the layer index ?

For example, looking at the picture I would naively say that "layer 4" for towers 18-25 (pink) should go together with "layer 5" for towers 26-28 (yellow), not "layer 4".

**Comment by silviodonato** [comment]
For the record, Ganesh from TSG confirmed that #36088  solved the problem of the GPU/CPU differences in PF in HCAL
(see https://docs.google.com/spreadsheets/d/1MOAzxYSRKRjqDvkQKUd6a9SAT0mNO--_3Zc3w9JCtQ0/edit#gid=853920917 )
Closing this issue
