### ISSUE TITLE
PPSAssociationCuts causes EventSetupConflict 

### ISSUE THREAD

**Issue by srimanob** [cms-sw/cmssw#35927]
Looking on the PR test of https://github.com/cms-sw/cmssw/pull/35925
It shows the EventSetupConflict from the PPSAssociationCuts

It seems to relate to the new GT which include PPS Association cuts, for example,
https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/121X_mcRun2_asymptotic_l1stage1_v8
https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/4507/1.html

FYI @cms-sw/ctpps-dpg-l2 @cms-sw/alca-l2

**Comment by srimanob** [comment]
assign alca, ctpps-dpg-l2

**Comment by qliphy** [comment]
The fix has been merged (https://github.com/cms-sw/cmssw/pull/35766#issuecomment-955694738), let's wait for the new IB test results

**Comment by srimanob** [comment]
Thx @qliphy

**Comment by tvami** [comment]
+alca
 * resolved already in https://github.com/cms-sw/cmssw/pull/35766

**Comment by srimanob** [comment]
Thx, PR passes the test now with https://github.com/cms-sw/cmssw/pull/35766
