### ISSUE TITLE
[HIN MC] MixingModule error

### ISSUE THREAD

**Issue by jordan-martins** [cms-sw/cmssw#35959]
Hi all,

We have a very old HIN MC campaign that has been used in the past (by what I can fetch in McM, successfully) and we resumed this by HIN request that is throwing the error listed in [1]. I place a JIRA ticket in [2] for further x-checks. I would like to ask for advice on how to proceed since I never saw this error message.

Thanks,
Jordan

[1] 
Fatal Exception (Exit code: 8026)
An exception of category 'NotFound' occurred while
[0] Processing run: 1 lumi: 463 event: 110632085
[1] Running path 'digitisation_step'
[2] Calling event method for module MixingModule/'mix'
Exception Message:
RootEmbeddedFileSequence::readOneSpecified(): Secondary Input files do not contain specified event:
run: 1 lumi: 32929 event: 3292828

[2] 
https://its.cern.ch/jira/browse/CMSCOMPPR-21567

**Comment by makortel** [comment]
assign core, simulation

**Comment by makortel** [comment]
I see from the log that the workflow was run on CMSSW_8_0_30. I don't understand why `RootEmbeddedFileSequence` would throw this kind of exception in case of mixing.

One thing that may be worth to note is that the number of pileup files is enormous (DAS shows 5660 files for the pileup dataset, I did not check if the job configuration lists them all).

**Comment by makortel** [comment]
The lumi 32929 is in the file `/store/himc/pPb816Spring16GS/ReggeGribovPartonMC_EposLHC_pPb_4080_4080_DataBS/GEN-SIM/MB_80X_mcRun2_pA_v4-v2/90000/6657FD55-5D08-E711-9A5E-00237DF28460.root`, but that file does not contain event 3292828. In that sense the error is correct.

Next I wonder where this combination of lumi and event numbers came from.

**Comment by makortel** [comment]
The MixingModule is being run in the playback mode. It was run also in the GEN step.

**Comment by jordan-martins** [comment]
Hi @makortel , thanks!
Indeed this is right. GS uses a HiMixGEN with one PU as input. Then, DIGI step uses another PU as input.

GS: https://cmsweb.cern.ch/das/request?input=/ReggeGribovPartonMC_EposLHC_pPb_4080_4080/pPb816Spring16GS-80X_mcRun2_asymptotic_v17-v1/GEN-SIM

DIGI: https://cmsweb.cern.ch/das/request?input=/ReggeGribovPartonMC_EposLHC_PbP_4080_4080_DataBS/pPb816Spring16GS-MB_80X_mcRun2_pA_v4-v2/GEN-SIM

**Comment by makortel** [comment]
> GS: https://cmsweb.cern.ch/das/request?input=/ReggeGribovPartonMC_EposLHC_pPb_4080_4080/pPb816Spring16GS-80X_mcRun2_asymptotic_v17-v1/GEN-SIM

In this dataset lumi 32929 is in file `/store/himc/pPb816Spring16GS/ReggeGribovPartonMC_EposLHC_pPb_4080_4080/GEN-SIM/80X_mcRun2_asymptotic_v17-v1/90000/E088194D-5E71-E611-A2CC-0025905C9740.root` and there event 3292828 is in that lumi.

Visually the overlap in event numbers in the lumi 32929 between these two datasets looks to be zero.

What I recall the MixingModule's playback mode is intended to play back exactly the same pileup files. Using two different pileup datasets for the two steps is not going to work with playback mode. What is the relation of these two datasets?

I have a vague recollection of participating in discussion of using MixingModule in both GEN and DIGI steps, but I'm unable to find that issue now. Adding @mandrenguyen in case he would remember better :)

**Comment by makortel** [comment]
unassign core

**Comment by mandrenguyen** [comment]
@makortel MixingModule is invoked in the HI event overlay workflows in both GEN and DIGI in order to match the sim vertex of the foreground and background events.  The same file needs to be available in both steps.

**Comment by makortel** [comment]
Thanks @mandrenguyen. But in https://github.com/cms-sw/cmssw/issues/35959#issuecomment-958145802 the datasets (and therefore files) are different for GEN and DIGI.

**Comment by mandrenguyen** [comment]
Yeah, that's why it crashes.  I'm missing the context.  Why would one want to do this?

**Comment by jordan-martins** [comment]
@makortel and @mandrenguyen thanks a lot for this info! Checking McM it seems that the DR campaign had its last update in 2017 (even before I came to CMS :) ) I think the problem is solved and the conclusion is that the campaign has this wrong configuration in it on our side. I will assess which should be the correct PU (my guess says that should be the one with pA in the name). 

Thank u again,
Jordan
