### ISSUE TITLE
[HIN DATA] BasicSingleVertexState::could not invert error matrix

### ISSUE THREAD

**Issue by jordan-martins** [cms-sw/cmssw#35960]
Hi all,

HIN Colleagues requested a ReRECO described in this JIRA [1]. However, we are seeing several failures in the reconstruction step listed in [2]. Computing JIRAS can be checked in [3]. Could you kindly advise action to be taken in order to turn around this issue, please?

Thanks,
Jordan

[1] https://its.cern.ch/jira/browse/PDMVRERECO-37
[2]
Fatal Exception (Exit code: 8002)
An exception of category 'StdException' occurred while
[0] Processing run: 263234 lumi: 435 event: 19022232
[1] Running path 'reconstruction_step'
[2] Calling event method for module PrimaryVertexProducer/'unsortedOfflinePrimaryVertices'
Exception Message:
A std::exception was thrown.
BasicSingleVertexState::could not invert error matrix

Fatal Exception (Exit code: 8002)
An exception of category 'StdException' occurred while
[0] Processing run: 263234 lumi: 218 event: 9754619
[1] Running path 'reconstruction_step'
[2] Calling event method for module PrimaryVertexProducer/'unsortedOfflinePrimaryVertices'
Exception Message:
A std::exception was thrown.
BasicSingleVertexState::could not invert weight matrix

[3]
https://its.cern.ch/jira/browse/CMSCOMPPR-21532
https://its.cern.ch/jira/browse/CMSCOMPPR-21433
https://its.cern.ch/jira/browse/CMSCOMPPR-21430
https://its.cern.ch/jira/browse/CMSCOMPPR-21435
https://its.cern.ch/jira/browse/CMSCOMPPR-21432
https://its.cern.ch/jira/browse/CMSCOMPPR-21434

**Comment by makortel** [comment]
assign reconstruction

**Comment by slava77** [comment]
IIUC, this is for CMSSW_7_5_8_patch7

It looks like 3 jobs out of 50 failed
https://cms-unified.web.cern.ch/cms-unified/showlog/?search=ReReco-HIRun2015-HIMinimumBias2-29Jul2021-00001

I'm proposing not to fix this old release, and as a mitigation propose for the comp ops to mask out the lumi-sections (or event events) and rerun.

@jordan-martins please clarify if it is possible to run recovery with a mask on the lumisections.

**Comment by slava77** [comment]
@mandrenguyen 
please take a note (although I think that we discussed this already in a JIRA)

**Comment by slava77** [comment]
Just counting the 8002 errors:
- 6 out of 95 in https://cms-unified.web.cern.ch/cms-unified/showlog/?search=ReReco-HIRun2015-HIMinimumBias1-29Jul2021-00001
- 3 out of 50 in https://cms-unified.web.cern.ch/cms-unified/showlog/?search=ReReco-HIRun2015-HIMinimumBias2-29Jul2021-00001
- 1 out of 51 in https://cms-unified.web.cern.ch/cms-unified/showlog/?search=ReReco-HIRun2015-HIMinimumBias3-29Jul2021-00001
- 3 out of 52 in https://cms-unified.web.cern.ch/cms-unified/showlog/?search=ReReco-HIRun2015-HIMinimumBias4-29Jul2021-00001
- 5 out of 127 in https://cms-unified.web.cern.ch/cms-unified/showlog/?search=ReReco-HIRun2015-HIMinimumBias5-29Jul2021-00001
- 5 out of 125 in https://cms-unified.web.cern.ch/cms-unified/showlog/?search=ReReco-HIRun2015-HIMinimumBias6-29Jul2021-00001
- 5 out of 126 in https://cms-unified.web.cern.ch/cms-unified/showlog/?search=ReReco-HIRun2015-HIMinimumBias7-29Jul2021-00001

total: 28 out of 626 (4.5%)

**Comment by slava77** [comment]
it looks like this is used for LUM-20-002
@cms-sw/lumi-pog-l2 
please check/clarify if "will not fix" is an acceptable solution for the 4.5% of the jobs in this reprocessing

**Comment by gkrintir** [comment]
hi @slava77 that's an acceptable solution, many thx

**Comment by jordan-martins** [comment]
Hi @slava77 , thanks a lot! Indeed, the concern was if acceptable to take the lost in stats. We will ask for a bypass. 
FYI @gkrintir

**Comment by jordan-martins** [comment]
Please, close this issue. Thanks a lot!
