### ISSUE TITLE
IB Failure with workflow 23234.103

### ISSUE THREAD

**Issue by qliphy** [cms-sw/cmssw#35979]
It appeared firstly from IB CMSSW_12_2 2021-10-31-2300, and persists up to most recent IB.

Previously we thought it is due to #35744 ,  and  #35941 may fix this as a byproduct  
https://github.com/cms-sw/cmssw/pull/35744#issuecomment-955963491
The PR test with #35941 enabled with multithreading worked well with 23234.103
https://github.com/cms-sw/cmssw/pull/35941#issuecomment-958147557

However, after merging #35941 the issue persists up to most recent IB.   We may need to wait to see the next IB results.

Let's open a thread here to track this issue.  

Adding @drankincms

p.s.  I tried several local tests and they work well with
   runTheMatrix.py -l 23234.103 --job-reports -t -4 --ibeos

**Comment by qliphy** [comment]
assign dqm,l1

**Comment by Dr15Jones** [comment]
I believe I've traced down the problem to a thread safety issue in ROOT.

The call to `QuantilesX` does

https://github.com/root-project/root/blob/de7bcdff077be4ec08892c1d8349d9f8e62dd420/hist/hist/src/TH2.cxx#L2460-L2463

and in `DoQuantiles` there is a call to `DoProjection` which uses the histogram name "tmp".
https://github.com/root-project/root/blob/de7bcdff077be4ec08892c1d8349d9f8e62dd420/hist/hist/src/TH2.cxx#L2531

It then checks `gROOT` if that histogram name already exists and then attempts to re-use it
https://github.com/root-project/root/blob/de7bcdff077be4ec08892c1d8349d9f8e62dd420/hist/hist/src/TH2.cxx#L2189-L2199

So if any other module is calling another ROOT function which also uses the "tmp" histogram then the histogram could be reset right as the call to `ComputeIntegral` happens.

The upshot is it is not safe to call `QuantilesX` or `QuantilesY` and you will have to find another way to fill the histograms.

FYI @pcanal.

**Comment by Dr15Jones** [comment]
NOTE: It appears `ProjectionX` and `ProjectionY` have a similar problem if one is not careful to pass in unique names to the functions.

**Comment by drankincms** [comment]
@Dr15Jones thanks a lot for tracking this down! Ok, I will go ahead and implement `QuantilesX()` by hand. @qliphy I will go ahead and submit a PR to fix this once it's ready.

**Comment by Dr15Jones** [comment]
@drankincms it looks like if you first set ROOT to a unique new directory it will place the "tmp" into that directory which should isolate you from any other threads.

**Comment by drankincms** [comment]
@Dr15Jones Thanks a bunch for the tip, your TContext trick seems to fix this.

**Comment by jfernan2** [comment]
+1
I believe this issue is being fixed by https://github.com/cms-sw/cmssw/pull/36067

**Comment by perrotta** [comment]
@qliphy I think we can close this (please reopen if I'm wrong)
