### ISSUE TITLE
Unable to find plugin 'EcalBarrelGeometryEPdd4hep' in category 'CMS EDM Framework ParameterSet Description'

### ISSUE THREAD

**Issue by qliphy** [cms-sw/cmssw#36029]
There are issues in IB since CMSSW_12_2_X_2021-11-07-0000   

**On the workflows 11634.911 and 11650.911**
https://cmssdt.cern.ch/SDT/cgi-bin/logreader/slc7_amd64_gcc900/CMSSW_12_2_X_2021-11-07-2300/pyRelValMatrixLogs/run/11634.911_TTbar_14TeV+2021_DD4hep+TTbar_14TeV_TuneCP5_GenSim+Digi+Reco+HARVEST+ALCA/step1_TTbar_14TeV+2021_DD4hep+TTbar_14TeV_TuneCP5_GenSim+Digi+Reco+HARVEST+ALCA.log#/

----- Begin Fatal Exception 08-Nov-2021 00:54:58 CET-----------------------
An exception of category 'PluginNotFound' occurred while
   [0] Constructing the EventProcessor
Exception Message:
Unable to find plugin 'EcalBarrelGeometryEPdd4hep' in category 'CMS EDM Framework ParameterSet Description'. Please check spelling of name.
----- End Fatal Exception -------------------------------------------------

**And on the unit test Geometry/TrackerGeometryBuilder :**
https://cmssdt.cern.ch/SDT/cgi-bin/logreader/slc7_amd64_gcc900/CMSSW_12_2_X_2021-11-07-2300/unitTestLogs/Geometry/TrackerGeometryBuilder#/37468-37468

idealForDigi' IGNORING alignment labels 'fakeForIdeal'.
----- Begin Fatal Exception 08-Nov-2021 01:04:11 CET-----------------------
An exception of category 'PluginNotFound' occurred while
   [0] Constructing the EventProcessor
Exception Message:
Unable to find plugin 'EcalBarrelGeometryEPdd4hep' in category 'CMS EDM Framework ParameterSet Description'. Please check spelling of name.
----- End Fatal Exception -------------------------------------------------
Failure using cmsRun /data/cmsbld/jenkins/workspace/ib-run-qa/CMSSW_12_2_X_2021-11-07-2300/src/Geometry/TrackerGeometryBuilder/test/python/testTrackerParametersFromDD4hep_cfg.py: status 65
status = 16640

**Comment by qliphy** [comment]
- Note CMSSW_12_2_X_2021-11-06-1100  has no such issue,
- CMSSW_12_2_X_2021-11-07-0000 reports issues on the workflows 11634.911 and 11650.911,
- CMSSW_12_2_X_2021-11-07-2300 reports further the issue on the unit test Geometry/TrackerGeometryBuilder

Between CMSSW_12_2_X_2021-11-06-1100 and CMSSW_12_2_X_2021-11-07-0000  there is only one new PR #35912 merged which should not be related to the issue.

**Comment by qliphy** [comment]
assign geometry

**Comment by civanch** [comment]
@ianna , @cvuosalo , this is a side effect of the names clean-up. Can you, please, fix.

**Comment by ianna** [comment]
@civanch - can we do the final cleanup after the second PR is merged? Thanks

**Comment by tvami** [comment]
I think https://github.com/cms-sw/cmssw/pull/36021 is the resolution to this issue already, no?

**Comment by cvuosalo** [comment]
+1
