### ISSUE TITLE
esConsume migration for CondTools/Geometry/test/GeometryTester.cc

### ISSUE THREAD

**Issue by cvuosalo** [cms-sw/cmssw#36043]
The file CondTools/Geometry/test/GeometryTester.cc requires esConsume migration. It has many occurrences of EventSetup::get() warnings:

https://cmssdt.cern.ch/SDT/cgi-bin/buildlogs/slc7_amd64_gcc900/CMSSW_12_2_CMSDEPRECATED_X_2021-11-03-2300/CondTools/Geometry

**Comment by cvuosalo** [comment]
assign db,geometry

**Comment by cvuosalo** [comment]
Resolved in PR #36107.

**Comment by tvami** [comment]
+db
 * resolved in https://github.com/cms-sw/cmssw/pull/36107

**Comment by cvuosalo** [comment]
+1

**Comment by cvuosalo** [comment]
#36107 has been merged.
