### ISSUE TITLE
[ASAN] TestDQMServicesDemo tries to allocate 15 TB of RAM

### ISSUE THREAD

**Issue by iarspider** [cms-sw/cmssw#36063]
Log file: https://cmssdt.cern.ch/SDT/cgi-bin/logreader/slc7_amd64_gcc10/CMSSW_12_2_ASAN_X_2021-11-08-2300/unitTestLogs/DQMServices/Demo#/5920-5920

Error message:
```
+ cmsRun .../src/DQMServices/Demo/test/run_analyzers_cfg.py outfile=huge.root numberEventsInRun=300 numberEventsInLuminosityBlock=100 nEvents=600 nThreads=10 nConcurrent=2 howmany=1000 nolegacy=True
==20036==ERROR: AddressSanitizer failed to allocate 0xdfff0001000 (15392894357504) bytes at address 2008fff7000 (errno: 12)
```

**Comment by iarspider** [comment]
assign dqm

**Comment by jfernan2** [comment]
Thanks @iarspider 
I am not able to reproduce it, could you remind me of what should I set apart from using CMSSW_12_2_ASAN_X_2021-11-08-2300 ?

The error looks related to the setting ulimit -v 4000000   in:
https://github.com/cms-sw/cmssw/blob/master/DQMServices/Demo/test/runtests.sh#L85

Could you advise a better value which may work for ASAN?
Thank you

**Comment by jfernan2** [comment]
@iarspider removing the ulimit makes the test working, would this be acceptable for ASAN and non-ASAN releases? Thanks

**Comment by iarspider** [comment]
The entire test suite was originally added in 27dd907088652012ffdcec14599446561c334331 by @schneiml , maybe he can comment?

**Comment by jfernan2** [comment]
I am afraid @schneiml is not working on CMS since more than a year
My question is more related to the way ASAN works, which I completely ignore. Has something changed in the ASAN side to produced this error in a script which was working previously?
Thanks

**Comment by jfernan2** [comment]
@iarspider I have created this PR to fix this crash and other UnitTest crashes in ASAN: https://github.com/cms-sw/cmssw/pull/36269

**Comment by iarspider** [comment]
@jfernan2 thanks!

**Comment by jfernan2** [comment]
+1
Fixed in https://github.com/cms-sw/cmssw/pull/36269
