### ISSUE TITLE
testCalibrationTkAlCaRecoProducers fails occasionally

### ISSUE THREAD

**Issue by makortel** [cms-sw/cmssw#36175]
The unit test `testCalibrationTkAlCaRecoProducers` in `Calibration/TkAlCaRecoProducers` appears to fail occasionally along
```
DQMFileSaver::globalEndRun()
SQLiteStatement::finalize 5 database is locked Error SQLiteStatement::finalize 5 database is locked
SQLiteStatement::execute 5 database is locked Error SQLiteStatement::execute 5 database is locked
----- Begin Fatal Exception 19-Nov-2021 00:48:15 CET-----------------------
An exception of category 'StdException' occurred while
   [0] Calling endJob
Exception Message:
A std::exception was thrown.
database is locked ( CORAL : "SQLiteStatement::execute" from "CORAL/RelationalPlugins/sqlite" )
----- End Fatal Exception -------------------------------------------------
```
https://cmssdt.cern.ch/SDT/cgi-bin/logreader/slc7_amd64_gcc10/CMSSW_12_2_X_2021-11-18-2300/unitTestLogs/Calibration/TkAlCaRecoProducers#/

The log above is from CMSSW_12_2_X_2021-11-18-2300 slc7_amd64_gcc10.

I saw the same failure in
* CMSSW_12_2_X_2021-11-15-1100 slc7_amd64_gcc11 https://cmssdt.cern.ch/SDT/cgi-bin/logreader/slc7_amd64_gcc11/CMSSW_12_2_X_2021-11-15-1100/unitTestLogs/Calibration/TkAlCaRecoProducers#/
* CMSSW_12_2_ROOT6_X_2021-11-14-2300 slc7_amd64_gcc900 https://cmssdt.cern.ch/SDT/cgi-bin/logreader/slc7_amd64_gcc900/CMSSW_12_2_ROOT6_X_2021-11-14-2300/unitTestLogs/Calibration/TkAlCaRecoProducers#/
* CMSSW_12_2_DEVEL_X_2021-11-12-2300 slc7_amd64_gcc900 https://cmssdt.cern.ch/SDT/cgi-bin/logreader/slc7_amd64_gcc900/CMSSW_12_2_DEVEL_X_2021-11-12-2300/unitTestLogs/Calibration/TkAlCaRecoProducers#/
* CMSSW_12_2_DEVEL_X_2021-11-11-2300 slc7_amd64_gcc900 https://cmssdt.cern.ch/SDT/cgi-bin/logreader/slc7_amd64_gcc900/CMSSW_12_2_DEVEL_X_2021-11-11-2300/unitTestLogs/Calibration/TkAlCaRecoProducers#/

**Comment by makortel** [comment]
assign alca

**Comment by tvami** [comment]
assign db

**Comment by tvami** [comment]
Reading here
https://stackoverflow.com/questions/3172929/operationalerror-database-is-locked
it seems to be due to concurency.
I thought the PCL harvester is single threaded tho

**Comment by francescobrivio** [comment]
I cannot reproduce the crash with:
```
cmsrel CMSSW_12_2_X_2021-11-18-2300
cd CMSSW_12_2_X_2021-11-18-2300/src
cmsenv
scram b -j 8
cd Calibration/TkAlCaRecoProducers/test
cmsRun -e testPCLAlCaHarvesting.py
```
but looking at old issues I found: https://github.com/cms-sw/cmssw/issues/26741
maybe @smuzaffar or @ggovi can help us out?

**Comment by makortel** [comment]
Another occurrence in CMSSW_12_2_X_2021-11-22-1100 slc7_amd64_gcc900

**Comment by makortel** [comment]
In #26741 the problem was that multiple tests were writing to the same SQLite file. Could the same be happening here?

**Comment by smuzaffar** [comment]
it might be due to `promptCalibConditions.db` https://github.com/cms-sw/cmssw/search?q=promptCalibConditions

**Comment by mmusich** [comment]
> it might be due to promptCalibConditions.db https://github.com/cms-sw/cmssw/search?q=promptCalibConditions

aren't those files written in different folders?

>  Also this tests asked for FW job report and generats FrameworkJobReport.xml , I think this is also very common name and multiple tests can be writing in same FW job report file.

how does one change that?

**Comment by smuzaffar** [comment]
> aren't those files written in different folders?

depends on each tests, scram starts all the tests from the top level cmssw dev directory. Some tests create sub-directories but most unit tests just create file in cmssw top level dir.

**Comment by mmusich** [comment]
> depends on each tests, scram starts all the tests from the top level cmssw dev directory. Some tests create sub-directories but most unit tests just create file in cmssw top level dir.

I think the ones you were pointing to actually write within the folders of each relval wf.

**Comment by smuzaffar** [comment]
@mmusich , to change the FW job report name use `-j OutFilename.xml`

**Comment by smuzaffar** [comment]
@mmusich , I think any unit test loading `AlCaHarvesting_cff` (e.g https://github.com/cms-sw/cmssw/search?q=AlCaHarvesting_cff ) might create `promptCalibConditions.db` in the cmssw top-level directory

**Comment by mmusich** [comment]
> I  think any unit test loading AlCaHarvesting_cff (e.g https://github.com/cms-sw/cmssw/search?q=AlCaHarvesting_cff ) might create promptCalibConditions.db in the cmssw top-level directory

the point being, I am not sure there is any. But fine let's try to change it together with the output framework job report.

**Comment by mmusich** [comment]
see https://github.com/cms-sw/cmssw/pull/36210

**Comment by tvami** [comment]
+1 
 * just for the records
