### ISSUE TITLE
IB issues: TPTask::Collection HcalTrigPrimDigiCollection isn't available: valHcalTriggerPrimitiveDigis 

### ISSUE THREAD

**Issue by qliphy** [cms-sw/cmssw#36188]
Appearing in many workflows 136.XXX

https://cmssdt.cern.ch/SDT/cgi-bin/logreader/slc7_amd64_gcc900/CMSSW_12_2_X_2021-11-19-2300/pyRelValMatrixLogs/run/136.761_RunJetHT2016E+RunJetHT2016E+HLTDR2_2016+RECODR2_2016reHLT_skimJetHT_HIPM+HARVESTDR2_skimJetHT/step3_RunJetHT2016E+RunJetHT2016E+HLTDR2_2016+RECODR2_2016reHLT_skimJetHT_HIPM+HARVESTDR2_skimJetHT.log#/120-120

An exception of category 'HCALDQM' occurred while
   [0] Processing  Event run: 277069 lumi: 91 event: 54448390 stream: 3
   [1] Running path 'dqmoffline_1_step'
   [2] Calling method for module TPTask/'tpTask'
Exception Message:
TPTask::Collection HcalTrigPrimDigiCollection isn't available: valHcalTriggerPrimitiveDigis

**Comment by qliphy** [comment]
Related to https://github.com/cms-sw/cmssw/pull/35678

@kskovpen

**Comment by qliphy** [comment]
assign dqm

**Comment by perrotta** [comment]
Quite likely related: a few of those 136.XXX workflows (e.g. 136.829, 136.886, 136.8861, 136.8862) now fail in step4 with a segmentation violation. Before that, the step4 logs are flooded with messages like
```
%MSG-w DTMonitorModule:   DTResolutionAnalysisTest:dtResolutionAnalysisTest@endProcessBlock  20-Nov-2021 03:10:10 CET post-events
[DTResolutionAnalysisTask] Histo: DT/02-Segments/Wheel-2/Sector3/Station1/hResDist_W-2_St1_Sec3_SL1 not found
```
This is also specific of the latest CMSSW_12_2 2021-11-19-2300 IB

**Comment by perrotta** [comment]
By looking at its log outputs I can notice that #36194 fixes both the exceptions/segm_violations and the flooding of messages from the DTMonitorModule that were reported [above](https://github.com/cms-sw/cmssw/issues/36188#issuecomment-974610181)

**Comment by jfernan2** [comment]
+1
