### ISSUE TITLE
Fatal exception from SimWatcher since CMSSW_12_2_X_2021-11-25-1100

### ISSUE THREAD

**Issue by perrotta** [cms-sw/cmssw#36256]
Since CMSSW_12_2_X_2021-11-25-1100 workflows 101 and 102 started showing the following Fatal Exception errors:
```
----- Begin Fatal Exception 25-Nov-2021 19:24:53 CET-----------------------
An exception of category 'Configuration' occurred while
   [0] Constructing the EventProcessor
   [1] Constructing module: class=OscarMTProducer label='g4SimHits'
Exception Message:
RunManagerMTWorker::createWatchers: Unable to use Watcher EcalSimHitsValidProducer if number of threads > 1
----- End Fatal Exception -------------------------------------------------
```

In that IB was merged
#36229 (SimWatcher thread safe interface)
which is obviously the natural suspect for it

A fix is needed

@civanch

**Comment by perrotta** [comment]
assign simulation, core

**Comment by makortel** [comment]
So that was the reason why 101 and 102 were run with single thread. I suppose the quickest fix would be to change that back. @smuzaffar

**Comment by smuzaffar** [comment]
https://github.com/cms-sw/cms-bot/pull/1666 has reverted the bot change. 101 and 102 are now run with 1 thread

**Comment by perrotta** [comment]
Great! Thank you @makortel and @smuzaffar 
Let wait for the nex IBs and then we can close this issue

**Comment by civanch** [comment]
@makortel , @perrotta , @smuzaffar , please, give me time until Monday, do not revert - I know that the problem is simple and will try to fix, already started. I think there is no urgency with 101 and 102 but if we revert other work with watchers will be stopped.

**Comment by perrotta** [comment]
> @makortel , @perrotta , @smuzaffar , please, give me time until Monday, do not revert - I know that the problem is simple and will try to fix, already started. I think there is no urgency with 101 and 102 but if we revert other work with watchers will be stopped.

@civanch the solution implemented by Shahzad was not to revert this PR, but to run single thread the workflows 101 and 102.
Of course, if you have a solution that allows those two workflows running multithread, it is welcome, and feel free to implement it in another PR

**Comment by civanch** [comment]
+1

#36297 was merged.

**Comment by perrotta** [comment]
#36297 finally fixed the issue, and wfs 101 and 102 were brought back to run multithread
