### ISSUE TITLE
add tracking in StaticAnalyzer of `if (cfg.exists`  or `existsAs<Type` for psets 

### ISSUE THREAD

**Issue by slava77** [cms-sw/cmssw#36261]
one of the pset coding requirements is to not use `if (cfg.exists`  or `existsAs<Type`. 

Here I'm proposing to encode this rule in the StaticAnalyzer so that the issues in the existing code can be found easily.

following https://mattermost.web.cern.ch/cms-o-and-c/pl/q9jr346jrj8xida17iaoywbqbc

**Comment by slava77** [comment]
@jpata 
we talked about this earlier; this is now formalized as an issue

**Comment by makortel** [comment]
assign core

**Comment by gartung** [comment]
https://github.com/cms-sw/cmssw/pull/36424

**Comment by makortel** [comment]
In CMSSW_12_3_X_2021-12-10-1100 the checker shows 4406 calls
https://cmssdt.cern.ch/SDT/jenkins-artifacts/ib-static-analysis/CMSSW_12_3_X_2021-12-10-1100/slc7_amd64_gcc900/llvm-analysis/index.html

**Comment by makortel** [comment]
+1
