### ISSUE TITLE
Placement of phase1PixelTopology.h

### ISSUE THREAD

**Issue by makortel** [cms-sw/cmssw#36302]
From discussion in https://github.com/cms-sw/cmssw/pull/36215#discussion_r758694554. Currently `phase1PixelTopology.h` is located in `Geometry/TrackerGeometryBuilder` and used (e.g.) in `CUDADataFormats`. The header file itself depends only on standard headers (#36215 brings in a weak dependence on CUDA-capable compiler that is handled with `#ifdef`).

Classes intended to be persisted that use `phase1PixelTopology.h` should be placed in `DataFormats`, at which point the dependence on `Geometry/TrackerGeometryBuilder` becomes too heavy in terms of dependencies that would add to the current dependencies of `DataFormats`. Therefore `phase1PixelTopology.h` should be moved to some other package whose dependencies would be acceptable for DataFormats (preferably a package already in the set of allowed dependencies).

Currently these Geometry packages are depended on in DataFormats
* `Geometry/CaloGeometry`
* `Geometry/CommonDetUnit`
and these Geometry packages are in [FWLite build set](https://github.com/cms-sw/cmsdist/blob/IB/CMSSW_12_2_X/master/fwlite_build_set.file) in addition to the two above
* `Geometry/CommonTopologies`
* `Geometry/GEMGeometry`

**Comment by makortel** [comment]
assign geometry,heterogeneous,reconstruction

**Comment by makortel** [comment]
FYI @cms-sw/trk-dpg-l2 @cms-sw/tracking-pog-l2

**Comment by mmusich** [comment]
would `Geometry/CommonTopologies` be acceptable?

**Comment by mmusich** [comment]
(incidentally I would let the dust settle over https://github.com/cms-sw/cmssw/pull/36235 before doing anything)

**Comment by mmusich** [comment]
as I didn't receive feedback, to get things moving I started #36773

**Comment by makortel** [comment]
+heterogeneous

Thanks @mmusich!
