### ISSUE TITLE
`ecalDevel` workflow 28234.61 step3 fails in 12_2_0_pre3

### ISSUE THREAD

**Issue by thomreis** [cms-sw/cmssw#36415]
The `ecalDevel` matrix WF 28234.61 2026D60_ecalDevel+TTbar_14TeV_TuneCP5_GenSimHLBeamSpot14+DigiTrigger+RecoGlobal+HARVESTGlobal fails at step3 in CMSSW_12_2_0_pre3 with the exception message:

```
----- Begin Fatal Exception 08-Dec-2021 13:47:58 CET-----------------------
An exception of category 'ProductNotFound' occurred while
   [0] Processing  Event run: 1 lumi: 1 event: 1 stream: 0
   [1] Running path 'dqmofflineOnPAT_1_step'
   [2] Prefetching for module SingleTopTChannelLeptonDQM_miniAOD/'singleTopElectronMediumDQM_miniAOD'
   [3] Prefetching for module PATMuonSlimmer/'slimmedMuons'
   [4] Prefetching for module PATMuonSelector/'selectedPatMuons'
   [5] Prefetching for module PATMuonProducer/'patMuons'
   [6] Prefetching for module MuonProducer/'muons'
   [7] Prefetching for module MuonIdProducer/'muons1stStep'
   [8] Prefetching for module HBHEPhase1Reconstructor/'hbhereco@cpu'
   [9] Calling method for module HcalRawToDigi/'hcalDigis'
Exception Message:
Principal::getByToken: Found zero products matching all criteria
Looking for type: FEDRawDataCollection
Looking for module label: rawDataCollector
Looking for productInstanceName: 

   Additional Info:
      [a] If you wish to continue processing events after a ProductNotFound exception,
add "SkipEvent = cms.untracked.vstring('ProductNotFound')" to the "options" PSet in the configuration.

----- End Fatal Exception -------------------------------------------------
```

Is this a known issue?

**Comment by makortel** [comment]
assign reconstruction, upgrade

**Comment by makortel** [comment]
FYI @cms-sw/ecal-dpg-l2 @cms-sw/hcal-dpg-l2

**Comment by makortel** [comment]
Is any `ecalDevel` workflow being run in IBs (i.e. part of full runTheMatrix)?

**Comment by thomreis** [comment]
A comparison with `28234.0` that runs fine shows only the `phase2_ecal_devel` modifier is given in addition on step3. That alone does not seem to be responsible for the exception. However, step2 of `28234.0` has also the `digi2raw_step` which might be needed to produce the seemingly missing `FEDRawDataCollection`.

**Comment by thomreis** [comment]
> Is any `ecalDevel` workflow being run in IBs (i.e. part of full runTheMatrix)?

I do not know but I do not think so. In fact I wanted to set up a configuration that could become a WF to be run in IBs. 28234.61 seemed a good starting point.

**Comment by thomreis** [comment]
The WF was introduced by @kpedro88 a bit over a year ago as part of #31726. Has it ever been tested?

**Comment by kpedro88** [comment]
I introduced this workflow to facilitate the ongoing development by @argiro and @dariosol - they should comment further.

**Comment by thomreis** [comment]
Thanks. I will follow up with them about this and close the issue here.
