### ISSUE TITLE
Master (next IB) is broken (two inconsistent PR were merged independently)

### ISSUE THREAD

**Issue by VinInn** [cms-sw/cmssw#36433]
Somehow the master is broken due to DQM/L1TMonitor #36396 which, in its own PR was fine. BUT not with #35627 .
Please revert one of the two.

**Comment by perrotta** [comment]
Fixed by #36435

**Comment by perrotta** [comment]
The fix restores the accessors `sector()` and `endcap()` of  RegionalMuonShower

For the record, the two accessors were used in 
- https://github.com/cms-sw/cmssw/pull/36396/files#diff-881ff4a5b7f865747240faa761540efae46b58c1007078bcda43fbfe6f250f6bR62
and another line farther below
- https://github.com/cms-sw/cmssw/pull/36018/files#diff-a2194e73035b8a64c72a7363af81ce438a545aca33b67ce5f616ff6ed98b4d0cR15 
and another line farther below

If those two methods want to be removed, those four lines must be adapted accordingly.

If those two methods want to be kept, as in #36435, then one should revert to use them in DQM/L1TMonitor/src/L1TStage2Shower.cc , see https://github.com/cms-sw/cmssw/pull/35627/files#diff-36be1ac5253fe760c0624c85ca8ff03e64fd0c204314226186b2ce4d692ea13bR169 and another line farther below
