### ISSUE TITLE
Remaining points to be fixed in SimpleFlatTableProducer (PhysicsTools/NanoAOD)

### ISSUE THREAD

**Issue by perrotta** [cms-sw/cmssw#36461]
Once concluded the review of #34169 several remarks remained unanswered, because they were supposedly already as such in the original code from which the modifications implemented in that PR were derived. While the PR is going to get merged as such, all those issues discovered during the review should be now addressed and fixed.
They are listed here below, please @makortel verify if I missed or misunderstood any (the references are for the additions implemented in that PR, but clearly all other related classes in the same file must be fixed):

- Why `mayConsumes()` at line https://github.com/cms-sw/cmssw/pull/34169/files#diff-547287940a3af84a5318501edd2e5be3e523260011da7b17b9f515bc7ebd6e52R286
- Move non templated classes outside the SimpleFlatTableProducerBaseLumi , see line https://github.com/cms-sw/cmssw/pull/34169/files#diff-547287940a3af84a5318501edd2e5be3e523260011da7b17b9f515bc7ebd6e52R341
- Pass the vector by reference, instead of by value, in order to avoid the copy in line https://github.com/cms-sw/cmssw/pull/34169/files#diff-547287940a3af84a5318501edd2e5be3e523260011da7b17b9f515bc7ebd6e52R359

Additional points

- Would it be possible to provide a `fillDescriptions` method?
- Try to remove the now deprecated check for existsAs for the configuration parameters
- See also comments below ([first](https://github.com/cms-sw/cmssw/issues/36461#issuecomment-991681400) and [second](https://github.com/cms-sw/cmssw/issues/36461#issuecomment-991703968l) one) about the possible advantages from trasforming it into a `global` module

@mzarucki

**Comment by perrotta** [comment]
assign xpog

**Comment by Dr15Jones** [comment]
The module could become a `edm::global` module which would be much more efficient than `edm::one`. To do this, the code would need to change
```C++
std::vector<std::unique_ptr<Variable>> vars_;
```

to
```C++
std::vector<std::vector<std::unique_ptr<Variable>>> varsPerLumi_;
```

and then size the new `std::vector<>` to be equal to the number of concurrent Lumis to be used in the job. This can be determined by overriding
```C++
void preallocLumis(unsigned int);
```

Then in `fillTable` the code we be changed to 
```C++
  std::unique_ptr<nanoaod::FlatTable> fillTable(const edm::LuminosityBlock & iLumi,
                                                 const edm::Handle<T> &prod) const override {
     auto out = std::make_unique<nanoaod::FlatTable>(1, this->name_, true, this->extension_);
     std::vector<const T *> selobjs(1, prod.product());
     for (const auto &var : this->varsPerLumi_[iLumi.index()])
       var->fill(selobjs, *out);
     return out;
   }
```

As each concurrent LuminosityBlock is assigned a unique monotonically increasing index value.

**Comment by Dr15Jones** [comment]
On further consideration, if this module is only ever scheduled using cms.Task than being a `edm::one` module isn't as bad since the Event level `produce` function will never be called and therefore begin a `edm::one` will not hinder the parallel processing of Events. 

A `edm::one` module doesn't have a very large impact on performance if it is only ever called during LuminosityBlock processing. So changing to a `edm::global` would only be a minor improvement rather than a major one.

If, on the other hand, this module will be used with a `cms.Path`, then it really should be converted to a `edm::global`.

**Comment by perrotta** [comment]
Thank you @Dr15Jones for your hints!

**Comment by vlimant** [comment]
@perrotta : can I please ask you to list up the remaining of the remaining items, so that we can pick this up efficiently ?

**Comment by vlimant** [comment]
please close
looks like everything was addressed here.
