### ISSUE TITLE
HLT issue in IB 

### ISSUE THREAD

**Issue by qliphy** [cms-sw/cmssw#36514]
Since IB, HLT is shown in RED.

The error message can be found in:

https://cmssdt.cern.ch/SDT/jenkins-artifacts/HLT-Validation/CMSSW_12_3_X_2021-12-15-2300/slc7_amd64_gcc10/RelVal_RECO_GRun_MC.log

%MSG-w METMonitor:  METMonitor:PFMET110_PFMHT110_IDTight_METmonitoring  16-Dec-2021 01:24:25 UTC Run: 1 Event: 55
skipping events because the collection pfMetEI is not available
%MSG
----- Begin Fatal Exception 16-Dec-2021 01:24:27 UTC-----------------------
An exception of category 'ProductNotFound' occurred while
   [0] Processing  Event run: 1 lumi: 2 event: 55 stream: 1
   [1] Running path 'dqmoffline_step'
   [2] Calling method for module MuonMonitor/'TrkMu12_DoubleTrkMu5NoFiltersNoVtx_monitoring'
Exception Message:
Principal::getByToken: Found zero products matching all criteria
Looking for type: std::vector<reco::PFMET>
Looking for module label: pfMetEI
Looking for productInstanceName: 

   Additional Info:
      [a] If you wish to continue processing events after a ProductNotFound exception,
add "SkipEvent = cms.untracked.vstring('ProductNotFound')" to the "options" PSet in the configuration.

----- End Fatal Exception -------------------------------------------------
----- Begin Fatal Exception 16-Dec-2021 01:24:28 UTC-----------------------
An exception of category 'ProductNotFound' occurred while
   [0] Processing  Event run: 1 lumi: 2 event: 54 stream: 2
   [1] Running path 'dqmoffline_step'
   [2] Calling method for module MuonMonitor/'TrkMu12_DoubleTrkMu5NoFiltersNoVtx_monitoring'
Exception Message:
Principal::getByToken: Found zero products matching all criteria
Looking for type: std::vector<reco::PFMET>
Looking for module label: pfMetEI
Looking for productInstanceName:

**Comment by qliphy** [comment]
assign hlt

**Comment by qliphy** [comment]
Could it be related to https://github.com/cms-sw/cmssw/pull/36494 ?

@Martin-Grunewald

**Comment by Martin-Grunewald** [comment]
Yes, likely.
I think it requires https://github.com/cms-sw/cmssw/pull/36465 as well which does the EI removal elsewhere!

**Comment by perrotta** [comment]
Yes, it seems I was to fast in merging #36494...
Since we want to cut pre2 by today, could I suggest to revert #36494 now, and add that simple commit into #36465?
@jfernan2

**Comment by Martin-Grunewald** [comment]
Where is the revert button now?

**Comment by missirol** [comment]
> Where is the revert button now?

I see one next to "View details", bottom-right corner of the screenshot
![tmp](https://user-images.githubusercontent.com/5320055/146329606-3908d9b2-3a67-4ec3-9d08-4edac956f54c.png)
.

**Comment by Martin-Grunewald** [comment]
Reverted by hand here: https://github.com/cms-sw/cmssw/pull/36515

**Comment by perrotta** [comment]
Thank you Martin.
Indeed what proposed by @missirol  also works (thank you Marino, indeed I forgot it...)

**Comment by Martin-Grunewald** [comment]
Thanks, @missirol

**Comment by missirol** [comment]
+hlt

**Comment by perrotta** [comment]
Fixed by #36515
