### ISSUE TITLE
L1T warning of overwriting muon data in the packer

### ISSUE THREAD

**Issue by srimanob** [cms-sw/cmssw#36596]
While running private Phase-2 MC GEN-SIM-DIGI-HLT(Fake) steps with CMSSW_12_3_X_2021-12-25-1100 (not try on other releases yet), I see a lot of warnings said that

%MSG-e L1T:  L1TDigiToRaw:gmtStage2Raw 27-Dec-2021 10:50:54 CET Run: 1 Event: 2
Check constants for RegionalMuonShower fields! It looks like we're in danger of overwriting muon data in the packer!

Are we in a good position of Phase-2 L1T?

Here are the cmsDriver(s) I use:

GEN-SIM
cmsDriver.py TTbar_14TeV_TuneCP5_cfi  -s GEN,SIM -n 20 --conditions auto:phase2_realistic_T27 --beamspot HLLHC14TeV --datatier GEN-SIM --eventcontent FEVTDEBUG --geometry Extended2026D89 --era Phase2C11I13T27M9 --python 2026D89_TTbar_GS.py --no_exec --fileout file:step1.root  --nThreads 8 --customise Configuration/DataProcessing/Utils.addMonitoring --customise_commands "from IOMC.RandomEngine.RandomServiceHelper import RandomNumberServiceHelper ; randSvc = RandomNumberServiceHelper(process.RandomNumberGeneratorService) ; randSvc.populate() \n process.source.firstLuminosityBlock = cms.untracked.uint32(555)"

DIGI-HLT
cmsDriver.py step2  -s DIGI:pdigi_valid,L1TrackTrigger,L1,DIGI2RAW,HLT:@fake2 --conditions auto:phase2_realistic_T27 --datatier GEN-SIM-DIGI-RAW -n -1 --eventcontent FEVTDEBUGHLT --geometry Extended2026D89 --era Phase2C11I13T27M9 --pileup AVE_200_BX_25ns --python 2026D89_TTbar_DIGIHLT.py --no_exec --filein  file:step1.root  --fileout file:step2.root  --nThreads 8 --nStreams 2 --customise Configuration/DataProcessing/Utils.addMonitoring --customise_commands "from IOMC.RandomEngine.RandomServiceHelper import RandomNumberServiceHelper ; randSvc = RandomNumberServiceHelper(process.RandomNumberGeneratorService) ; randSvc.populate()" --pileup_input "/store/group/dpg_tracker_upgrade/D89D90/2026D89_MinBias/2026D89_MinBias_101.root, /store/group/dpg_tracker_upgrade/D89D90/2026D89_MinBias/2026D89_MinBias_102.root,"

**Comment by Dr15Jones** [comment]
Assign l1

**Comment by cecilecaillol** [comment]
I dont see warnings anymore, I think this issue can be closed.

**Comment by cecilecaillol** [comment]
+l1
