### ISSUE TITLE
consider cleanup in RecoEGamma/Examples

### ISSUE THREAD

**Issue by slava77** [cms-sw/cmssw#36590]
in a follow up to 
https://github.com/cms-sw/cmssw/pull/36577#issuecomment-999841333

there are modules missing Event consumes calls and therefore they have not functioned for all of Run 2. It would probably be good to review them for removal from CMSSW.

@wrtabb @SohamBhattacharya

**Comment by slava77** [comment]
assign reconstruction,egamma-pog

**Comment by mandrenguyen** [comment]
+reconstruction
#38026 addressed this issue

**Comment by mandrenguyen** [comment]
Closed #36590 as completed.

**Comment by mandrenguyen** [comment]
please close
