### ISSUE TITLE
review current use cases of RecoFP420

### ISSUE THREAD

**Issue by slava77** [cms-sw/cmssw#36612]
The code in RecoFP420 seems to only be used in /test.
A somewhat limited spot-check also suggests that the code had no functional updates for a long time (10 years).

@cms-sw/hcal-dpg-l2  please comment or suggest/tag relevant experts who may clarify 
- if there is any raw data that may need to be reconstructed with this code
- is there some expectation for some future developments

One of the purpose of the review is to see if the code is still needed in CMSSW.

**Comment by slava77** [comment]
One of the purpose of the review is to see if the code is still needed in CMSSW.

**Comment by mseidel42** [comment]
Hi Slava, I think this has nothing to do with HCAL:

> We present the FP420 R&D project, which has been studying the key aspects of the development and installation of a silicon tracker and fast-timing detectors in the LHC tunnel at 420 m from the interaction points of the ATLAS and CMS experiments.

https://arxiv.org/abs/0806.0302

Contact persons: Brian.Cox@manchester.ac.uk, Albert.de.Roeck@cern.ch. Not sure if they are on github, probably best to write them a mail!

**Comment by slava77** [comment]
@mseidel42 
thanks for the pointers. My guess about ZDC connection was wrong, so, no HCAL relationship.
We still need a DPG or POG to be responsible for the reco software.

Now, looking at https://arxiv.org/abs/0806.0302, and more recent activities in PPS, I'm curious if the FP420 R&D project is somehow more closely connected to the PPS DPG or PRO POG. 
@cms-sw/ctpps-dpg-l2 @cms-sw/proton-pog-l2 please clarify.

**Comment by fabferro** [comment]
I think that this code can be removed from master not to have to maintain it. If anybody will revive the project of having detectors at 420m (eg in HL-LHC) we'll see if it will be of some use.

**Comment by fabferro** [comment]
Actually I can see that there is much more FP420 code in cmssw than RecoFP420 (eg in DataFormats). Probably removing only RecoFP420 doesn't make much sense, does it? Then, if we want to get rid of all FP420 code, it would probably be better to find someone responsible for it or that knows why it was written and with which perspective. I can only say that neither PPS nor TOTEM are interested in it.

**Comment by jpata** [comment]
@cms-sw/proton-pog-l2 are you interested in maintaining the FP420 code? From the reco side, we are talking about the following packages:

- DataFormats/FP420Cluster
- DataFormats/FP420Digi
- RecoRomanPot/RecoFP420

**Comment by jpata** [comment]
> Hello
> Thanks for your message
> I don't think there is any reason to keep the code. 
> (FP420 developments have been stopped ~ 10 years ago…)
> cheers,  Albert

I got the following response to an email. So we can clean up this code. I will do so from the reco side, while I leave the simulation-related changes for someone else.

**Comment by jpata** [comment]
assign simulation

(as there is also FP420 code in Sim, so it's not a purely reco issue)

**Comment by jpata** [comment]
+reconstruction
- addressed both reco and sim in #37983

**Comment by civanch** [comment]
+1
