### ISSUE TITLE
Possible bug in Validation/RecoVertex/src/BeamSpotHistogramMaker.cc

### ISSUE THREAD

**Issue by perrotta** [cms-sw/cmssw#36650]
As pointed out by the static analyzer, the value stored in `currdir` at L29 of Validation/RecoVertex/src/BeamSpotHistogramMaker.cc in the `BeamSpotHistogramMaker::book` method is never read.

Shouldn't that line be written as
```C++
    _currdir = &(tfserv->tFileDirectory());
```
instead? (With `_currdir` instead of `currdir`)

**Comment by perrotta** [comment]
assign dqm

**Comment by jfernan2** [comment]
Thanks @perrotta 
I believe you are totally right, of course.
I have fixed it in:
https://github.com/cms-sw/cmssw/pull/36656

**Comment by perrotta** [comment]
Fixed by #36656, thank you @jfernan2

**Comment by jfernan2** [comment]
+1
For the records
