### ISSUE TITLE
Failures in workflow 39434.501 and 39434.502  since CMSSW_12_3_X_2022-01-09-0000

### ISSUE THREAD

**Issue by qliphy** [cms-sw/cmssw#36661]
https://cmssdt.cern.ch/SDT/cgi-bin/logreader/slc7_amd64_gcc10/CMSSW_12_3_X_2022-01-09-2300/pyRelValMatrixLogs/run/39434.501_TTbar_14TeV+2026D88_Patatrack_PixelOnlyCPU+TTbar_14TeV_TuneCP5_GenSimHLBeamSpot14+DigiTrigger+RecoGlobal+HARVESTGlobal/step3_TTbar_14TeV+2026D88_Patatrack_PixelOnlyCPU+TTbar_14TeV_TuneCP5_GenSimHLBeamSpot14+DigiTrigger+RecoGlobal+HARVESTGlobal.log#/36-36

Module: SiPixelRecHitSoAFromLegacy:siPixelRecHitsPreSplitting@cpu (crashed)cmsRun: /pool/condor/dir_200019/jenkins/workspace/build-any-ib/w/tmp/BUILDROOT/607f690c93b913c651b04bdea22355e8/opt/cmssw/slc7_amd64_gcc10/cms/cmssw/CMSSW_12_3_X_2022-01-09-0000/src/RecoLocalTracker/SiPixelRecHits/plugins/SiPixelRecHitSoAFromLegacy.cc:144: virtual void SiPixelRecHitSoAFromLegacy::produce(edm::StreamID, edm::Event&, const edm::EventSetup&) const: Assertion `gind < nMaxModules' failed.

https://cmssdt.cern.ch/SDT/cgi-bin/logreader/slc7_amd64_gcc10/CMSSW_12_3_X_2022-01-09-2300/pyRelValMatrixLogs/run/39434.502_TTbar_14TeV+2026D88_Patatrack_PixelOnlyGPU+TTbar_14TeV_TuneCP5_GenSimHLBeamSpot14+DigiTrigger+RecoGlobal+HARVESTGlobal/step3_TTbar_14TeV+2026D88_Patatrack_PixelOnlyGPU+TTbar_14TeV_TuneCP5_GenSimHLBeamSpot14+DigiTrigger+RecoGlobal+HARVESTGlobal.log#/135-135

Current Modules:

Module: SiPixelRecHitSoAFromLegacy:siPixelRecHitsPreSplittingSoA (crashed)
Module: SiPixelRecHitSoAFromLegacy:siPixelRecHitsPreSplittingSoA
Module: SiPixelRecHitSoAFromLegacy:siPixelRecHitsPreSplittingSoA
Module: SiPixelRecHitSoAFromLegacy:siPixelRecHitsPreSplittingSoA
Module: SiPixelRecHitSoAFromLegacy:siPixelRecHitsPreSplittingSoA

A fatal system signal has occurred: abort signal

**Comment by qliphy** [comment]
related to https://github.com/cms-sw/cmssw/pull/36529
@AdrianoDee

**Comment by AdrianoDee** [comment]
@qliphy thanks, let me have a look at it.

**Comment by makortel** [comment]
assign reconstruction, heterogeneous

**Comment by qliphy** [comment]
> @qliphy thanks, let me have a look at it.

@AdrianoDee  Any news on this?  The issues are still there in recent IBs.

**Comment by AdrianoDee** [comment]
@qliphy opened https://github.com/cms-sw/cmssw/pull/36714, sorry for the delay. I wanted to include it in a general clean-up PR: not a great idea!

**Comment by perrotta** [comment]
Fixed by #36714, this can be closed
