### ISSUE TITLE
Issue with predefined decay (charged exotic case)

### ISSUE THREAD

**Issue by shedprog** [cms-sw/cmssw#36706]
The following issue is related to this hypernews thread: https://hypernews.cern.ch/HyperNews/CMS/get/simDevelopment/1997/1/1/1.html

I will demonstrate bug on the example of long-lived stau decaying to tau, which is hadronized in pythia. stau->tau->hadrons/leptons (1000015 -> 15)

In the function, https://github.com/cms-sw/cmssw/blob/22f1b2d464d0b95e3dedc0b8fabce5f4357b6be8/SimG4Core/Generators/src/Generator.cc#L112

If the particle is detectable exotic https://github.com/cms-sw/cmssw/blob/22f1b2d464d0b95e3dedc0b8fabce5f4357b6be8/SimG4Core/Generators/src/Generator.cc#L159-L166
Its status will be changed to 2 and then the following function is called https://github.com/cms-sw/cmssw/blob/22f1b2d464d0b95e3dedc0b8fabce5f4357b6be8/SimG4Core/Generators/src/Generator.cc#L395-L397 so, if I understood correctly, the children will be assigned as daughter (15) of its G4PrimaryParticle-mother (1000015) (`SetDaughter`) and they both will be assigned to the same PrimaryVertex. The children of tau (15) also can be added as children of the G4PrimaryParticle (tau) daughters only in the case if the status of the tau is equal to 2: https://github.com/cms-sw/cmssw/blob/22f1b2d464d0b95e3dedc0b8fabce5f4357b6be8/SimG4Core/Generators/src/Generator.cc#L476-L482

Let’s consider the following decay chain generated by pythia:
![stau_decay](https://user-images.githubusercontent.com/31743376/149521986-f7c2790e-67e9-4995-8988-d0c0c5d0a4ef.png)

The first copy of the 15 will be assigned as a daughter of 1000015 and then recursive calls of `particleAssignDaughters` will be stopped and the real final copy of the tau will be assigned to the new G4PrimaryVertex. 

As the result, geant will decay this tau with status 23 itself in addition to the existing preliminary decayed (by pythia) tau status=2 which assigned to other primary vertex, and we observe the duplication of the decay, sometimes one of these decay is reset to prompt because geant does’t know how to propagate its exotic mother (when does not use these setups https://github.com/cms-sw/cmssw/blob/master/SimG4Core/CustomPhysics/python/Exotica_HSCP_SIM_cfi.py).
![sim](https://user-images.githubusercontent.com/31743376/149522001-10e5f9b8-0f73-405a-9828-ba8c59db2ce5.png)

The similar effect can be observed for any exotic dataset because of presence of intermediate copy in Pythia generator. What would be a correct way to fix it not to damage other analyses? Probably adding all decay chain with this intermediate tau with status=23? e.g: adding optionally other status here:
https://github.com/cms-sw/cmssw/blob/22f1b2d464d0b95e3dedc0b8fabce5f4357b6be8/SimG4Core/Generators/src/Generator.cc#L476

**Comment by shedprog** [comment]
Dear @civanch, can I ask for the help with this issue. Thank you in advance!

**Comment by makortel** [comment]
assign simulation

**Comment by civanch** [comment]
@shedprog , please, try locally to add a logic with code 23 and first be sure that it is fine to your use case. If your solution will work you make a PR for the master branch and we will discuss it. After fix of the master branch the PR may be backported to CMSSW_10_6_X.

**Comment by shedprog** [comment]
> @shedprog , please, try locally to add a logic with code 23 and first be sure that it is fine to your use case. If your solution will work you make a PR for the master branch and we will discuss it. After fix of the master branch the PR may be backported to CMSSW_10_6_X.

@civanch, can I ask for a minor clarification: if the complex decay chain have particle in the middle with isLastCopy()==false (in my case it is particle with status=23) then this decay chain will not be assigned to single G4PrimaryVertex but two, but in the first chain decay will not be finished, won't geant always try to finish the decay of the first? So, don't we need to add any particle with isLastCopy()==false to https://github.com/shedprog/cmssw/blob/df76a09aa010097fbc0a2356e6933ddd01070a3a/SimG4Core/Generators/src/Generator.cc#L481 ?

**Comment by perrotta** [comment]
@shedprog @civanch : given the merging of #36772 in master, can this issue get closed now?
