### ISSUE TITLE
Clean up and unify Phase2 tracker geometry handling code

### ISSUE THREAD

**Issue by jpata** [cms-sw/cmssw#36761]
In #36660, a new Phase2 tracker geometry is being proposed, with the urgency of the development resulting in much of the code being duplicated from existing tracker code (in a few cases, in significant amounts and verbatim). https://github.com/cms-sw/cmssw/pull/36660#issuecomment-1017585984

This pattern is not optimal, and there is a commitment from the tracking POG to clean this up in the timescale of early February 2022: https://github.com/cms-sw/cmssw/pull/36660#issuecomment-1017609118

(this is a common development pattern in CMS, and there is a danger of temporary things becoming permanent, hence this issue as a reminder)

**Comment by jpata** [comment]
assign reconstruction

**Comment by mmusich** [comment]
@jpata please clarify if this is still relevant after the follow-up of review of  PR https://github.com/cms-sw/cmssw/pull/36660

**Comment by jpata** [comment]
Good question, I was wondering the same. In the Phase2 modules, the following functions may be something to look at
- `Phase2EndcapRing::computeCrossings` vs. `TIDRing::computeCrossings`
- `Phase2EndcapRing::searchNeighbors` vs. `TIDRing::searchNeighbors`
On the other hand, to some extent this is already the case for Phase1 modules, so perhaps it's fine.
