### ISSUE TITLE
Implement Concurrent Runs

### ISSUE THREAD

**Issue by wddgit** [cms-sw/cmssw#36774]
Implement Concurrent Runs. We can document discussions related to concurrent runs here before the PR is submitted.

@Dr15Jones @makortel

**Comment by makortel** [comment]
assign core

**Comment by wddgit** [comment]
How much trouble is it going to cause if the order of stream begin run and global begin lumi changes? Currently, all streams complete their begin run transitions before global begin lumi begins.  In the case of multiple runs in flight that ordering will be no longer possible. Those transitions might run concurrently or with either order.

With the current version in my working area even for single thread jobs the order is reversed and it is not trivial to change. I am wondering if I need to do the extra work to force the old ordering for the special case with 1 concurrent run configured. I could make global begin lumi  wait for stream begin run to complete for at least one stream. But the only reason I can think of to do that is backward compatibility, just in case something depends on that order (and I don't know about anything now).

At the moment, I am noticing this because some unit tests compare to reference files with Tracer output. I could just update the reference files to the new order.

**Comment by Dr15Jones** [comment]
@wddgit here is what I wrote about transitions

https://twiki.cern.ch/twiki/bin/view/CMSPublic/FWMultithreadedFrameworkTransitions#Transitions

So it is extremely important that all 'streams' see the non-event transitions in the same order and in the order they would expect from the original (pre-Run2) framework.

**Comment by Dr15Jones** [comment]
In the writeup for which I gave the link, there is one part that is incorrect

>Also, a Stream will only see a LuminosityBlock based transitions for LuminosityBlocks corresponding to Events that a Stream processes.

That is NOT the case (as I could never make that work correctly). Instead, ALL streams see ALL LuminosityBlocks even if that stream never processes an Event in that LuminosityBlock.

This means we do have a strict ordering in which a new LuminosityBlock can not be started until the last event in the previous LuminosityBlock has started on a stream.

Following that logic, a new Run can not be started until the last stream end LuminosityBlock of the previous Run has started on a stream.

**Comment by wddgit** [comment]
Stream transitions. Yes, I agree.

Global transitions. No. And in particular I am asking about global begin lumi. If there are multiple runs in flight, if a stream moves ahead to another run it cannot wait for a different stream on the previous run to complete stream begin run. It must continue on to Events.

**Comment by wddgit** [comment]
I think on the web page you referenced, global begin lumi is only waiting on global begin run to complete.

**Comment by wddgit** [comment]
Do you mind if I also fix the TWIKI to state all streams see all luminosity blocks and runs? I think we left it that way because we thought we might actually change the code to behave that way. I think we are no longer planning to do that so we might as well change the TWIKI from the original plan to the actual behavior.

**Comment by Dr15Jones** [comment]
So lets take the case of two runs each with one lumi and no events, then the time line should be

Order in Source
```
Run:(1), Lumi:(1,1) Run:(2), Lumi:(2,1)
```

Transition order assuming an infinite number of threads. Time progresses along the x axis. A transition begins on its first letter and ends on its last letter or until the start of the next transition on the same line (specifically for stream transitions).
```
globalBeginRun(1) globalBeginLumi(1,1)                                              globalEndLumi(1,1)                                                                
           streamBeginRun(1)          streamBeginLumi(1,1) streamEndLumi(1,1) streamEndRun(1)            streamBeginRun(2)      streamBeginLumi(2,1) streamEndLumi(2,1)    streamEndRun(2)     
           streamBeginRun(1)              streamBeginLumi(1,1)    streamEndLumi(1,1)   streamEndRun(1)   streamBeginRun(2)      streamBeginLumi(2,1) streamEndLumi(2,1)    streamEndRun(2)
                                                                                                      globalEndRun(1)
                                                                                        globalBeginRun(2)  globalBeginLumi(2,1)                                        globalEndLum(2,1)  globalEndRun(2)
```

So the `globalBeginRun(2)` should not start until the last stream processes its `streamEndRun(1)`. That guarantees that it is impossible for a `streamBeginRun(2)` to fire before the `streamEndRun(1)` is run.

**Comment by wddgit** [comment]
Hmmmmm. This is different than what I thought. I thought we wanted to be able to process an event from run 1 and a different event or events from run 2 concurrently on different streams. So if the last event in run 1 took a very long time we continue  on other streams into run 2, not waiting until streamEndRun(1) is started for all streams. That is what I implemented and would give a better performance benefit.

**Comment by wddgit** [comment]
Note that the original ordering issue I mentioned is not the result of intentional design or an explicit wait. Both tasks are likely spawned and it is just the TBB algorithm which picks which task to run first. I understand correctly, the last spawned is run first. It's nontrivial to modify the order because along each execution path there is a series of tasks that spawn other tasks...

**Comment by wddgit** [comment]
Note the stream  transitions are ordered properly in the new code using the Stream SerialQueues. That is how I guarantee  streamBeginRun(2) does not fire before streamEndRun(1) within a single stream. I insert tasks into the Stream SerialQueues in the correct order.

**Comment by wddgit** [comment]
This question would be so much easier to discuss with a whiteboard in person... I am quitting now for the weekend. We can continue on Monday...

**Comment by wddgit** [comment]
A couple comments about the question I brought up Friday.

First, most of the code changes in my "concurrent runs" working area will have no effect on anything if the number of concurrent runs is set to 1. But the ordering I mentioned changes even when the number of concurrent runs is set to 1. That is why I brought it up and was worried about it.

Second, maybe a way to answer this question is to survey modules and see how many implement streamBeginRun and globalBeginLumi. If the answer is none, then maybe this is OK. If the number is small, I'll manually check them and if it is large, maybe I should change how I implemented this.

Note that in the diagram, globalBeginLumi and streamBeginRun are vertically aligned with no indication of a dependence.

https://twiki.cern.ch/twiki/bin/view/CMSPublic/FWMultithreadedFrameworkTransitions#Transitions

And if I've misunderstood what "concurrent runs" meant, we should discuss that. Possibly, I've implemented something different than you and Matti expected.

**Comment by wddgit** [comment]
Following Chris's suggestion in our discussion, I found a way to restore the previous ordering by changing the order of spawning tasks. It took a while to find it, but in the end a 1 line change. Thanks.

**Comment by makortel** [comment]
This feature was completed in https://github.com/cms-sw/cmssw/pull/39673

**Comment by makortel** [comment]
+core

**Comment by makortel** [comment]
@cmsbuild, please close
