### ISSUE TITLE
[HGCAL] Add CloseByPGun sample to the list of RelVals run at IB level

### ISSUE THREAD

**Issue by rovere** [cms-sw/cmssw#36832]
Given the recent crash (#36800) related to the `CloseByPGun` event generator, and taking into account its paramount importance in performing the release validation for HGCAL, it would be wise to add a couple of CloseByPGun workflows in the set of RelVals that are run at every IB integration.

**Comment by rovere** [comment]
assign upgrade

**Comment by srimanob** [comment]
I would need comments from @smuzaffar @perrotta @qliphy on the resource used for the short matrix.

Here is the list of the short matrix,
https://github.com/cms-sw/cmssw/blob/master/Configuration/PyReleaseValidation/scripts/runTheMatrix.py#L60-L103

I think we will need to find a balance between used resources as the test will be done in all PRs including Run-3 and usefulness for groups. I don't have a strong opinion on this. Adding a small NoPU workflow should not be a big deal, but we can't always add fail things to the PR test also.

**Comment by rovere** [comment]
Ciao @srimanob let's hear from @smuzaffar @perrotta  and @qliphy about resource usage and availability.
At the same time, I currently count 5 Upgrade workflows over a total of ~40 (I'm not including your #36833): bringing it so 6 (with a very fast workflow, as `CloseByPGun` is, without PU), would not represent a huge deal, IMHO.
Having said that, I'd be happy as well if the `CloseByPGun` is tested during the `IB` Relval testing, and not at each and every PR testing, if resources would not allow that (that was, in fact, my original proposal). Let's see.

**Comment by smuzaffar** [comment]
@rovere , any idea of the resources (cpu, memory) these workflows need? We do have good machines (16 cores with over 128GB memory) so if there is not a huge resource requirement ( and new workflows run in reasonable time e.g. under an hour/workflow) then I have no objections adding these for IB validations.

**Comment by rovere** [comment]
Ciao @smuzaffar I do not have numbers, but this specific workflow should be much less demanding than any other _real_ `PhaseII` workflow, since it's a single particle one, usually shot immediately in front of (or in between) `HGCAL`.

**Comment by srimanob** [comment]
Hi @smuzaffar @rovere 
OK, I will include the new workflow in my PR, and put the number for the reference. It is single particle, it should take less than ttbar NoPU. Do you have preference @rovere 

- 39493.0 2026D88+CloseByParticle_Photon_ERZRanges_GenSimHLBeamSpotHGCALCloseBy+DigiTrigger+RecoGlobal+HARVESTGlobal 
- 39494.0 2026D88+CE_E_Front_300um_GenSimHLBeamSpotHGCALCloseBy+DigiTrigger+RecoGlobal+HARVESTGlobal 
- 39494.201 2026D88_ticl_clue3D+CE_E_Front_300um_GenSimHLBeamSpotHGCALCloseBy+DigiTrigger+RecoGlobal+HARVESTGlobal 
- 39494.202 2026D88_ticl_FastJet+CE_E_Front_300um_GenSimHLBeamSpotHGCALCloseBy+DigiTrigger+RecoGlobal+HARVESTGlobal 
- 39495.0 2026D88+CE_E_Front_200um_GenSimHLBeamSpotHGCALCloseBy+DigiTrigger+RecoGlobal+HARVESTGlobal 
- 39495.201 2026D88_ticl_clue3D+CE_E_Front_200um_GenSimHLBeamSpotHGCALCloseBy+DigiTrigger+RecoGlobal+HARVESTGlobal 
- 39495.202 2026D88_ticl_FastJet+CE_E_Front_200um_GenSimHLBeamSpotHGCALCloseBy+DigiTrigger+RecoGlobal+HARVESTGlobal 
- 39496.0 2026D88+CE_E_Front_120um_GenSimHLBeamSpotHGCALCloseBy+DigiTrigger+RecoGlobal+HARVESTGlobal 
- 39496.201 2026D88_ticl_clue3D+CE_E_Front_120um_GenSimHLBeamSpotHGCALCloseBy+DigiTrigger+RecoGlobal+HARVESTGlobal 
- 39496.202 2026D88_ticl_FastJet+CE_E_Front_120um_GenSimHLBeamSpotHGCALCloseBy+DigiTrigger+RecoGlobal+HARVESTGlobal 
- 39497.0 2026D88+CE_H_Fine_300um_GenSimHLBeamSpotHGCALCloseBy+DigiTrigger+RecoGlobal+HARVESTGlobal 
- 39497.201 2026D88_ticl_clue3D+CE_H_Fine_300um_GenSimHLBeamSpotHGCALCloseBy+DigiTrigger+RecoGlobal+HARVESTGlobal 
- 39497.202 2026D88_ticl_FastJet+CE_H_Fine_300um_GenSimHLBeamSpotHGCALCloseBy+DigiTrigger+RecoGlobal+HARVESTGlobal 
- 39498.0 2026D88+CE_H_Fine_200um_GenSimHLBeamSpotHGCALCloseBy+DigiTrigger+RecoGlobal+HARVESTGlobal 
- 39498.201 2026D88_ticl_clue3D+CE_H_Fine_200um_GenSimHLBeamSpotHGCALCloseBy+DigiTrigger+RecoGlobal+HARVESTGlobal 
- 39498.202 2026D88_ticl_FastJet+CE_H_Fine_200um_GenSimHLBeamSpotHGCALCloseBy+DigiTrigger+RecoGlobal+HARVESTGlobal 
- 39499.0 2026D88+CE_H_Fine_120um_GenSimHLBeamSpotHGCALCloseBy+DigiTrigger+RecoGlobal+HARVESTGlobal 
- 39499.201 2026D88_ticl_clue3D+CE_H_Fine_120um_GenSimHLBeamSpotHGCALCloseBy+DigiTrigger+RecoGlobal+HARVESTGlobal 
- 39499.202 2026D88_ticl_FastJet+CE_H_Fine_120um_GenSimHLBeamSpotHGCALCloseBy+DigiTrigger+RecoGlobal+HARVESTGlobal 
- 39500.0 2026D88+CE_H_Coarse_Scint_GenSimHLBeamSpotHGCALCloseBy+DigiTrigger+RecoGlobal+HARVESTGlobal 
- 39500.201 2026D88_ticl_clue3D+CE_H_Coarse_Scint_GenSimHLBeamSpotHGCALCloseBy+DigiTrigger+RecoGlobal+HARVESTGlobal 
- 39500.202 2026D88_ticl_FastJet+CE_H_Coarse_Scint_GenSimHLBeamSpotHGCALCloseBy+DigiTrigger+RecoGlobal+HARVESTGlobal 
- 39501.0 2026D88+CE_H_Coarse_300um_GenSimHLBeamSpotHGCALCloseBy+DigiTrigger+RecoGlobal+HARVESTGlobal 
- 39501.201 2026D88_ticl_clue3D+CE_H_Coarse_300um_GenSimHLBeamSpotHGCALCloseBy+DigiTrigger+RecoGlobal+HARVESTGlobal 
- 39501.202 2026D88_ticl_FastJet+CE_H_Coarse_300um_GenSimHLBeamSpotHGCALCloseBy+DigiTrigger+RecoGlobal+HARVESTGlobal 

Note to myself that I should update also https://github.com/cms-sw/cmssw/blob/master/Configuration/PyReleaseValidation/README.md in the PR, to add .201, .202

**Comment by apsallid** [comment]
@rovere @srimanob @cseez @pfs 
If we were allowed for one more I would also propose a scintillator workflow (`39500.0` apart from `39496.0`).

**Comment by srimanob** [comment]
Hi @rovere 
To clarify, you propose the additional workflow to be added in the short matrix (tested with every PR), or IB. From the title, it seems the latter, but from the discussion, I talked about the former. Thanks.

**Comment by rovere** [comment]
Ciao @srimanob 
my proposal was to add them to the IB. Since, though, the `CloseByPGun` is very fast, I'd not mind **also** the _short matrix_ option.

**Comment by srimanob** [comment]
OK, then I propose to have them in both places for HGCAL development. @smuzaffar Could you please help for IB? Thanks.

**Comment by srimanob** [comment]
+Upgrade

Two CloseByPGun wfs are running in IB now as they are in relvals_2026. I think the issue can be closed.

**Comment by rovere** [comment]
Thanks to everyone that helped!
