### ISSUE TITLE
TrackerGeometricDetESModule issue in Phase2 D88 DD4hep (step1, GEN-SIM)

### ISSUE THREAD

**Issue by srimanob** [cms-sw/cmssw#36849]
Hi,

In parallel with https://github.com/cms-sw/cmssw/issues/36837

Running out-of-box driver from
CMSSW_12_3_X_2022-01-31-2300 with https://github.com/cms-sw/cmssw/pull/36836
`runTheMatrix.py --what upgrade -l 39434.911 --wm init`

I found
```
----- Begin Fatal Exception 01-Feb-2022 14:13:59 CET-----------------------
An exception of category 'EventSetupConflict' occurred while
   [0] Calling beginJob
Exception Message:
two EventSetup Producers want to deliver type="GeometricDet" label=""
 from record IdealGeometryRecord. The two providers are 
1) type="TrackerGeometricDetESModule" label="trackerNumberingGeometry"
2) type="TrackerGeometricDetESModule" label="trackerNumberingGeometryDB"
Please either
   remove one of these Producers
   or find a way of configuring one of them so it does not deliver this data
   or use an es_prefer statement in the configuration to choose one.
----- End Fatal Exception -------------------------------------------------
```
The issue was not there with D77, as we tested in https://github.com/cms-sw/cmssw/issues/36837.

FYI @mmusich @emiglior

**Comment by srimanob** [comment]
assign geometry tracker-dpg

**Comment by mmusich** [comment]
-1

The D88 geometry was introduced by the geometry group in https://github.com/cms-sw/cmssw/pull/36264 (@bsunanda FYI)

**Comment by srimanob** [comment]
OK, understand that @mmusich 
Just in case you have a quick idea on how things can be double load. If not, no problem. Thanks.

**Comment by mmusich** [comment]
> Just in case you have a quick idea on how things can be double load. If not, no problem. 

I guess copying what is done for D77 if that still works?

**Comment by srimanob** [comment]
Ah, I think I know now.
We miss definition of dd4hep of D86,D88 in 
https://github.com/cms-sw/cmssw/blob/master/Configuration/StandardSequences/python/GeometryConf.py
so, that is why cmsDriver pick the default one which is 
`process.load('Configuration.StandardSequences.GeometryRecoDB_cff')`

**Comment by bsunanda** [comment]
Please note Phase2 cannot operate with DB. It has to work with XML versions till we have the detector geometry in DB.
________________________________

**Comment by srimanob** [comment]
Thanks @bsunanda 

Fix in https://github.com/cms-sw/cmssw/pull/36851 to allow to load properly.
