### ISSUE TITLE
EGM Run3 regression issue 

### ISSUE THREAD

**Issue by swagata87** [cms-sw/cmssw#36886]
We had recently updated electron, photon and supercluster regression in global tag. It went into CMSSW_12_3_0_pre3 via this autoCond update https://github.com/cms-sw/cmssw/pull/36710, and one of the relevant GT is 123X_mcRun3_2021_realistic_v3 (https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/123X_mcRun3_2021_realistic_v3/123X_mcRun3_2021_realistic_v2).

It was backported to 12_2, https://github.com/cms-sw/cmssw/pull/36719, and went into CMSSW_12_2_0_patch1. 

During release validation of CMSSW_12_3_0_pre2 vs CMSSW_12_3_0_pre3, an issue was found and it looks like coming from EGM regression. 

An example response plot of electron is here, where one can see the issue: 
https://cms-egamma.web.cern.ch/validation/Electrons/Releases/index.php?action=/12_3_0_pre3_2021_DQM_std/FullvsFull_CMSSW_12_3_0_pre2/RECO-RECO_ZEE_14#EoEtrue_barrel_new
(Red is CMSSW_12_3_0_pre3 and blue is CMSSW_12_3_0_pre2).

Investigation is ongoing within EGM POG, and from preliminary check it looks like something went wrong while making .db file (from .root file). As a result, the energy correction factors that were presented in and approved by EGM POG, did not land up in GT. We are trying to fix it as soon as possible.

**Comment by tvami** [comment]
assign alca

**Comment by swagata87** [comment]
Some updates from our side. 
To remind, we have 5 kinds of regression: electron, photon, mustache supercluster, saturated electron and saturated photon. We have now solved the issue for first 3. I attach here some example plots where once can see the fix.

The checks were made using a candidate GT `123X_mcRun3_2021_realistic_Candidate_2022_02_08_08_42_19`. We produced AODs/miniAODs using this new GT from available pre3 `GEN-SIM-DIGI-RAW` files. In the following plots it is tagged as `pre3 new GT`; while `pre2`/`pre3 old GT` is centrally produced pre2/ pre3 relVals.  

1) Electron regression (Z->EE) [plotted from miniAOD]
![compare_ZEE_Response_EcalOnly_Barrel](https://user-images.githubusercontent.com/5052706/153193837-293d2a06-40b6-4a28-9e26-bf4bd4d66a35.png)

2) Photon regression (Higgs to Gamma Gamma) [plotted from miniAOD]
![compare_HGG_Response_EcalOnly_Endcap](https://user-images.githubusercontent.com/5052706/153194052-d7f8dd03-c6cf-475a-879b-3cf262196cf8.png)

3) Mustache supercluster regression (Z->EE) [plotted from AOD]
![compare_mustache_ZEE_Response_Barrel](https://user-images.githubusercontent.com/5052706/153194230-a442cff9-b6f6-4fc2-9ef4-10c790ca82d0.png)

Saturated electron regression, relevant only for very high pT electrons, is not fixed yet. We are investigating.

**Comment by tvami** [comment]
+alca
 * although the saturated electron regression tags should be fixed as soon as possible
 * I'd also appreciate that the code that creates these DB files in ported to CMSSW, so we can make sure it's always up to date

**Comment by swagata87** [comment]
>Saturated electron regression, relevant only for very high pT electrons, is not fixed yet. We are investigating.

Now the issue is found and fixed :
![compare_Saturated_ZPrimeEE_Response_EcalOnly_Barrel](https://user-images.githubusercontent.com/5052706/155959451-bf21efbc-0388-4cbc-ac9a-e7d3f1cc3821.png)

Apart from GT update, a small change in CMSSW config file is also needed to fix the saturated regression problem. We will make the PR and GT update request soon.

**Comment by tvami** [comment]
Hi @swagata87 thanks, this is great! Shall I add you to the AlCaDB agenda for next Monday (March 7) to discuss this further?

**Comment by swagata87** [comment]
You can add it in agenda, but most probably Saumya will be the speaker (will confirm later).
So I was preparing the PR for master (12_3_X).
I understand that we have missed the deadline for 12_2_X, so a backport to 12_2_X is not possible anymore, as the MC production has started. Is that correct? Or do we still have time to get this into 12_2_X?

**Comment by tvami** [comment]
I added you to the agenda: https://indico.cern.ch/event/1134353/#21-egm-saturated-regression-fo

Yes, the MC production has started, thus there is no point in a backport unfortunately.

**Comment by francescobrivio** [comment]
Thanks @swagata87!

> a small change in CMSSW config file is also needed to fix the saturated regression problem

Has the PR been made already? Is it needed to consume the new saturated regression conditions?

**Comment by swagata87** [comment]
The PR is not made yet, 
some final sanity checks are running, if all goes fine I am planning to make the PR in a few hours. 
The PR and the GT update needs to go together in a release, because w/o the PR, the GT update will not give meaningful results. So yes, the PR is needed to properly consume the regression conditions.

**Comment by francescobrivio** [comment]
> The PR is not made yet, some final sanity checks are running, if all goes fine I am planning to make the PR in a few hours. The PR and the GT update needs to go together in a release, because w/o the PR, the GT update will not give meaningful results. So yes, the PR is needed to properly consume the regression conditions.

Ok great! thanks for the explanation! keep us informed on the developments then!

**Comment by tvami** [comment]
I understand that the PR will touch on the `reco` signature, so let me alert @cms-sw/reconstruction-l2 so they are aware of the urgency of this coming PR
