### ISSUE TITLE
Can you build xrootd 5.4 for the TLS?

### ISSUE THREAD

**Issue by bockjoo** [cms-sw/cmssw#36915]
I am testing CMSSW_12_3_0_pre4 to read files with root protocol with the TLS configured on the xrootd server side.
This CMSSW has xrootd 5.3.1 and XrdAdaptor shows this error:
----- Begin Fatal Exception 08-Feb-2022 12:54:24 EST-----------------------
An exception of category 'FileOpenError' occurred while
   [0] Constructing the EventProcessor
   [1] Constructing input source of type PoolSource
   [2] Calling XrdFile::readv()
   [3] XrdAdaptor::ClientRequest::HandleResponse() failure while running connection recovery
   [4] In XrdAdaptor::RequestManager::requestFailure()
Exception Message:
XrdAdaptor::RequestManager::requestFailure Open(name='root://cmsio2.rc.ufl.edu//store/mc/RunIIAutumn18MiniAOD/ZToMuMu_NNPDF31_13TeV-powheg_M_4500_6000/MINIAODSIM/102X_upgrade2018_realistic_v15-v2/120000/CFAA5B09-4746-594F-9B1C-5F415F673C4E_Florida.root', flags=0x10, permissions=0660, old source=cmsio2.rc.ufl.edu:1094 (site T2_US_Florida), new source=cmsio2.rc.ufl.edu:1094 (site T2_US_Florida)) => Xrootd server returned an excluded source
   Additional Info:
      [a] Original error: '[ERROR] Socket timeout' (errno=0, code=103, source=cmsio2.rc.ufl.edu:1094 (site T2_US_Florida)).
      [b] Disabled source: cmsio2.rc.ufl.edu:1094
      [c] Active source: cmsio2.rc.ufl.edu:1094 (site T2_US_Florida)
----- End Fatal Exception -------------------------------------------------
The cmsRun gets stuck like so:
%MSG-w XrdAdaptorInternal:  AfterFile 08-Feb-2022 12:51:22 EST pre-events
Bockjoo readv IOPosBuffer before readv_result.first.get()  0
%MSG
[2022-02-08 12:54:23.117531 -0500][Error  ][XRootD            ][2571135] [cmsio2.rc.ufl.edu:1094] Unable to get the response to request kXR_readv (handle: 0x00000000, chunks: 2, total size: 224380)

If I turn off the TLS, there is no problem.
There was no such issue with earlier root ( xrootd < 5.0).
xrootd 5.4 is the newest and seems reliable.
Can you build xrootd 5.4 as the new cmssw external?
Thanks,
Bockjoo

**Comment by makortel** [comment]
assign core

**Comment by davidlange6** [comment]
Hi-

5.4 "seems reliable" means it was tested with your server?

**Comment by bockjoo** [comment]
My server is running 5.4. With 5.3.1 xrdcp in the CMSSW_12_3_0_pre4, I get this:
[bockjoo@cms runAnalysis]$ which xrdcp
/opt/cms/services/aaa/CMSSWTokenTest/CMSSW_12_3_0_pre3/external/slc7_amd64_gcc10/bin/xrdcp
[bockjoo@cms runAnalysis]$ xrdcp -d 1 -f root://cmsio2.rc.ufl.edu//store/mc/RunIIAutumn18MiniAOD/ZToMuMu_NNPDF31_13TeV-powheg_M_4500_6000/MINIAODSIM/102X_upgrade2018_realistic_v15-v2/120000/CFAA5B09-4746-594F-9B1C-5F415F673C4E_Florida.root /dev/null
[2022-02-08 13:44:14.515483 -0500][Info   ][AsyncSock         ] [cmsio2.rc.ufl.edu:1094.0] TLS hand-shake done.
[104MB/378.8MB][ 27%][=============>                                    ][104MB/s][378.8MB/378.8MB][100%][==================================================][378.8MB/s]  [2022-02-08 13:44:15.518714 -0500][Error  ][PostMaster        ] Unable to get transport handler for file protocol
[378.8MB/378.8MB][100%][==================================================][378.8MB/s]  

But there is no PostMaster error with 5.4 xrdcp:
[bockjoo@cms ~]$ xrdcp -d 1 -f root://cmsio2.rc.ufl.edu//store/mc/RunIIAutumn18MiniAOD/ZToMuMu_NNPDF31_13TeV-powheg_M_4500_6000/MINIAODSIM/102X_upgrade2018_realistic_v15-v2/120000/CFAA5B09-4746-594F-9B1C-5F415F673C4E_Florida.root /dev/null
[2022-02-08 13:45:48.077101 -0500][Info   ][AsyncSock         ] [cmsio2.rc.ufl.edu:1094.0] TLS hand-shake done.
[378.8MB/378.8MB][100%][==================================================][378.[378.8MB/378.8MB][100%][==================================================][378.8MB/s]  

Since I have no idea what's the issue with the socket timeout with 5.3.1, I am just praying if 5.4 will do OK with the TLS.

**Comment by bockjoo** [comment]
I built the xrootd out of xrootd github to use it as the CMSSW_12_3_0_pre4 external.
With this one, cmssw read an xrootd file worked fine with the x509 and the token.
So 5.3.1 has the problem with TLS.

**Comment by smuzaffar** [comment]
@bockjoo , xrootd 5.4.0 is now available in CMSSW_12_3_DEVEL_X IBs. Can you please try that and let us know if that looks good?

**Comment by bockjoo** [comment]
@smuzaffar Will test it and let you know.

**Comment by bockjoo** [comment]
It fails the token authorization. It does not look it goes through the token at all:
-bash-4.2$ ( export BEARER_TOKEN=$BEARER_TOKEN ; unset X509_USER_PROXY ; cmsRun cmssw_cfg_token.py )
%MSG-w CondDBESSource:  (NoModuleName) 25-Feb-2022 16:57:17 CET pre-events
Plugin for Record PGeometricDetExtraRcd has not been found.
%MSG
25-Feb-2022 16:57:17 CET  Initiating request to open file root://cmsio2.rc.ufl.edu//store/mc/RunIIAutumn18MiniAOD/ZToMuMu_NNPDF31_13TeV-powheg_M_4500_6000/MINIAODSIM/102X_upgrade2018_realistic_v15-v2/120000/CFAA5B09-4746-594F-9B1C-5F415F673C4E_Florida.root
%MSG-w XrdAdaptorInternal:  file_open 25-Feb-2022 16:57:18 CET pre-events
Bockjoo trying to open new_filename root://cmsio2.rc.ufl.edu//store/mc/RunIIAutumn18MiniAOD/ZToMuMu_NNPDF31_13TeV-powheg_M_4500_6000/MINIAODSIM/102X_upgrade2018_realistic_v15-v2/120000/CFAA5B09-4746-594F-9B1C-5F415F673C4E_Florida.root?authz=Bearer%20eyJraWQiOiJyc2ExIiwiYWxnIjoiUlMyNTYifQ.eyJ3bGNnLnZlciI6IjEuMCIsInN1YiI6ImU1ZmJlYzg5LTQzN2YtNDViOC1hODUyLThkMjY5MGQ4NWZlZiIsImF1ZCI6Imh0dHBzOlwvXC93bGNnLmNlcm4uY2hcL2p3dFwvdjFcL2FueSIsIm5iZiI6MTY0NTgwNDEyMywic2NvcGUiOiJzdG9yYWdlLmNyZWF0ZTpcLyBvZmZsaW5lX2FjY2VzcyBzdG9yYWdlLnJlYWQ6XC8gc3RvcmFnZS5tb2RpZnk6XC8iLCJpc3MiOiJodHRwczpcL1wvY21zLWF1dGgud2ViLmNlcm4uY2hcLyIsImV4cCI6MTY0NTgwNzcyMywiaWF0IjoxNjQ1ODA0MTIzLCJqdGkiOiIxNmY3MDgxZi0wZTExLTRhNjktOGIxMC1lNjBlZmViZjRlYjIiLCJjbGllbnRfaWQiOiI1ZTNhNjc3NS03N2Y0LTQ1MjQtYTI1OC0wNDFmM2MwNzI4MGYifQ.aAP919PMOUnKMWkCULNOvr_uLT8qXsobID6f1wX8JbK_B3jsMU3Is2-xGvQfeJc-3jl310KF19vd1KUX7Nd0v_jqXzBWmuHGfswhYu9qWdCPnPbzenl-P2kabOuSR5I-LrxO0iuIMIexzTPvhXxnoH8AbI9-Ztt6QpE7xhycYHw BEARER_TOKEN eyJraWQiOiJyc2ExIiwiYWxnIjoiUlMyNTYifQ.eyJ3bGNnLnZlciI6IjEuMCIsInN1YiI6ImU1ZmJlYzg5LTQzN2YtNDViOC1hODUyLThkMjY5MGQ4NWZlZiIsImF1ZCI6Imh0dHBzOlwvXC93bGNnLmNlcm4uY2hcL2p3dFwvdjFcL2FueSIsIm5iZiI6MTY0NTgwNDEyMywic2NvcGUiOiJzdG9yYWdlLmNyZWF0ZTpcLyBvZmZsaW5lX2FjY2VzcyBzdG9yYWdlLnJlYWQ6XC8gc3RvcmFnZS5tb2RpZnk6XC8iLCJpc3MiOiJodHRwczpcL1wvY21zLWF1dGgud2ViLmNlcm4uY2hcLyIsImV4cCI6MTY0NTgwNzcyMywiaWF0IjoxNjQ1ODA0MTIzLCJqdGkiOiIxNmY3MDgxZi0wZTExLTRhNjktOGIxMC1lNjBlZmViZjRlYjIiLCJjbGllbnRfaWQiOiI1ZTNhNjc3NS03N2Y0LTQ1MjQtYTI1OC0wNDFmM2MwNzI4MGYifQ.aAP919PMOUnKMWkCULNOvr_uLT8qXsobID6f1wX8JbK_B3jsMU3Is2-xGvQfeJc-3jl310KF19vd1KUX7Nd0v_jqXzBWmuHGfswhYu9qWdCPnPbzenl-P2kabOuSR5I-LrxO0iuIMIexzTPvhXxnoH8AbI9-Ztt6QpE7xhycYHw.
%MSG
220225 16:57:20 11868 cryptossl_X509CreateProxy: EEC certificate has expired
[2022-02-25 16:57:20.492321 +0100][Error  ][XRootDTransport   ][11689] [cmsio2.rc.ufl.edu:1094.0] No protocols left to try
[2022-02-25 16:57:20.492480 +0100][Error  ][AsyncSock         ][11689] [cmsio2.rc.ufl.edu:1094.0] Socket error while handshaking: [FATAL] Auth failed


-bash-4.2$  which cmsRun
/cvmfs/cms-ib.cern.ch/nweek-02721/slc7_amd64_gcc10/cms/cmssw/CMSSW_12_3_DEVEL_X_2022-02-24-2300/bin/slc7_amd64_gcc10/cmsRun

xrdcp also fails:
-bash-4.2$ ( export BEARER_TOKEN=$BEARER_TOKEN ; unset X509_USER_PROXY ; xrdcp -d 1 -f root://cmsio2.rc.ufl.edu//store/user/bockjoo/sitedb.list?authz=Bearer%20$BEARER_TOKEN $(pwd)/sitedb.list )
[2022-02-25 16:59:49.379856 +0100][Info   ][AsyncSock         ] [cmsio2.rc.ufl.edu:1094.0] TLS hand-shake done.
220225 16:59:50 12655 cryptossl_X509CreateProxy: EEC certificate has expired
[2022-02-25 16:59:50.458164 +0100][Error  ][XRootDTransport   ] [cmsio2.rc.ufl.edu:1094.0] No protocols left to try
[2022-02-25 16:59:50.458236 +0100][Error  ][AsyncSock         ] [cmsio2.rc.ufl.edu:1094.0] Socket error while handshaking: [FATAL] Auth failed

On the other hand, the same token works fine with the local xrootd 5.4.0 client:
[bockjoo@cms ~]$ ( export BEARER_TOKEN=$BEARER_TOKEN ; unset X509_USER_PROXY ; xrdcp -d 1 -f root://cmsio2.rc.ufl.edu//store/user/bockjoo/sitedb.list?authz=Bearer%20$BEARER_TOKEN $(pwd)/sitedb.list )
[2022-02-25 11:01:06.510968 -0500][Info   ][AsyncSock         ] [cmsio2.rc.ufl.edu:1094.0] TLS hand-shake done.
[26.51kB/26.51kB][100%][==================================================][26.5[26.51kB/26.51kB][100%][==================================================][26.51kB/s]  

I will check more.

**Comment by bockjoo** [comment]
@smuzaffar I asked the xrootd-l if there is a way to check the reason.
But this xrootd 5.4.0 seems to be not woking. 
Perhaps, try the latest release 5.4.1?

**Comment by smuzaffar** [comment]
@bockjoo , you mentioned that you were able to use 5.4 with TLS, how did you built it? Did you use any special flags? Currently we use https://github.com/cms-sw/cmsdist/blob/IB/CMSSW_12_3_X/devel/xrootd.spec#L29 to build xrootd, let me know if I need to modify any build flags.

**Comment by bockjoo** [comment]
This is what I did to build it:
[ -d ~/bin ] || mkdir ~/bin
ln -s /usr/bin/cmake3 ~/bin/cmake
[ -d /opt/cms/services ] || mkdir -p /opt/cms/services
git clone https://github.com/xrootd/xrootd.git
mkdir -p /opt/cms/services/xroot_build
# USE CMSSW_12_3_0_pre4 
source /cvmfs/cms.cern.ch/cmsset_default.sh
cd /cvmfs/cms.cern.ch/slc7_amd64_gcc10/cms/cmssw/CMSSW_12_3_0_pre4/src
eval `scram runtime -sh`
cd /opt/cms/services/xroot_build
cmake /opt/cms/services/xrootd -DCMAKE_INSTALL_PREFIX=/opt/cms/xrootd -DENABLE_PERL=FALSE
make
make install

**Comment by smuzaffar** [comment]
humm, so you did not build with scitokens-cpp , so may be that is the reason. Anyway,  I am testing 5.4.1 here https://github.com/cms-sw/cmsdist/pull/7651

**Comment by bockjoo** [comment]
Yeah, I think there is some difference.

Here is the server log created by the client which can do the xrdcp with the token:
220225 15:35:49 26362 Xrd_Inet: Accepted connection on port 1094 from [34@cms.rc.ufl.edu](mailto:34@cms.rc.ufl.edu)
220225 15:35:49 26362 Xrd_ProtLoad: matched port 1094 protocol xroot
220225 15:35:49 26362 [anon.0:34@cms.rc.ufl.edu](mailto:anon.0:34@cms.rc.ufl.edu) Xrd_Poll: FD 34 attached to poller 0; num=1
220225 15:35:49 26362 [anon.0:34@cms.rc.ufl.edu](mailto:anon.0:34@cms.rc.ufl.edu) TLS_Accept: Accepting a TLS connection...
220225 15:35:49 26362 XrdLinkXeq: [anon.0:34@cms.rc.ufl.edu](mailto:anon.0:34@cms.rc.ufl.edu) connection upgraded to TLSv1.2
220225 15:35:49 26362 [anon.0:34@cms.rc.ufl.edu](mailto:anon.0:34@cms.rc.ufl.edu) TLS_Read: 24 out of 24 bytes.
220225 15:35:49 26362 [anon.0:34@cms.rc.ufl.edu](mailto:anon.0:34@cms.rc.ufl.edu) TLS_Read: 85 out of 85 bytes.
220225 15:35:49 26362 [bockjoo.2777317:34@cms.rc.ufl.edu](mailto:bockjoo.2777317:34@cms.rc.ufl.edu) TLS_Write: 8 out of 8 bytes.
220225 15:35:49 26362 [bockjoo.2777317:34@cms.rc.ufl.edu](mailto:bockjoo.2777317:34@cms.rc.ufl.edu) TLS_Write: 16 out of 16 bytes.
220225 15:35:49 26362 [bockjoo.2777317:34@cms.rc.ufl.edu](mailto:bockjoo.2777317:34@cms.rc.ufl.edu) TLS_Write: 59 out of 59 bytes.
220225 15:35:49 26421 Xrd_Sched: running monitor fstat inq=0
220225 15:35:49 26421 Xrd_Sched: scheduling monitor fstat in 60 seconds
220225 15:35:49 26340 Xrd_Sched: Now have 5 workers
220225 15:35:49 26340 Xrd_Sched: running monitor window clock inq=0
220225 15:35:49 26340 Xrd_Sched: scheduling monitor window clock in 5 seconds
220225 15:35:50 26362 [bockjoo.2777317:34@cms.rc.ufl.edu](mailto:bockjoo.2777317:34@cms.rc.ufl.edu) TLS_Read: 24 out of 24 bytes.
220225 15:35:50 26362 [bockjoo.2777317:34@cms.rc.ufl.edu](mailto:bockjoo.2777317:34@cms.rc.ufl.edu) TLS_Read: 722 out of 722 bytes.
220225 15:35:50 26421 Xrd_Sched: running stats reporter inq=0
220225 15:35:50 26421 Xrd_Sched: scheduling stats reporter in 60 seconds
220225 15:35:53 26362 [bockjoo.2777317:34@cms.rc.ufl.edu](mailto:bockjoo.2777317:34@cms.rc.ufl.edu) TLS_Write: 8 out of 8 bytes.
220225 15:35:53 26362 XrootdXeq: [bockjoo.2777317:34@cms.rc.ufl.edu](mailto:bockjoo.2777317:34@cms.rc.ufl.edu) pub IPv4 TLSv1.2 login as e5fbec89-437f-45b8-a852-8d2690d85fef
220225 15:35:53 26362 multiuser_UserSentry: Failed to lookup UID for username e5fbec89-437f-45b8-a852-8d2690d85fef Success
220225 15:35:53 26362 [bockjoo.2777317:34@cms.rc.ufl.edu](mailto:bockjoo.2777317:34@cms.rc.ufl.edu) TLS_Read: 24 out of 24 bytes.
220225 15:35:53 26362 [bockjoo.2777317:34@cms.rc.ufl.edu](mailto:bockjoo.2777317:34@cms.rc.ufl.edu) TLS_Read: 756 out of 756 bytes.
220225 15:35:53 26362 scitokens_Reconfig: Parsing configuration file: /etc/xrootd/scitokens.cfg
220225 15:35:53 26362 scitokens_Reconfig: Successfully parsed SciTokens mapfile: /etc/xrootd/scitokens-map.json
220225 15:35:53 26362 scitokens_Reconfig: Successfully parsed SciTokens mapfile: /etc/xrootd/scitokens-map.json
220225 15:35:53 26362 multiuser_UserSentry: Switching FS uid for user bockjoo
220225 15:35:53 26362 multiuser_Open: Will not create checksum
220225 15:35:53 26362 [bockjoo.2777317:34@cms.rc.ufl.edu](mailto:bockjoo.2777317:34@cms.rc.ufl.edu) TLS_Write: 8 out of 8 bytes.
220225 15:35:53 26362 [bockjoo.2777317:34@cms.rc.ufl.edu](mailto:bockjoo.2777317:34@cms.rc.ufl.edu) TLS_Write: 12 out of 12 bytes.
220225 15:35:53 26362 [bockjoo.2777317:34@cms.rc.ufl.edu](mailto:bockjoo.2777317:34@cms.rc.ufl.edu) TLS_Write: 82 out of 82

.....



Here's the log created by the client that fails to use the ztn protocol:

220225 15:34:38 26340 Xrd_Inet: Accepted connection on port 1094 from [34@lxplus722.cern.ch](mailto:34@lxplus722.cern.ch)
220225 15:34:38 26340 Xrd_ProtLoad: matched port 1094 protocol xroot
220225 15:34:38 26340 [anon.0:34@lxplus722.cern.ch](mailto:anon.0:34@lxplus722.cern.ch) Xrd_Poll: FD 34 attached to poller 0; num=1
220225 15:34:38 26340 [anon.0:34@lxplus722.cern.ch](mailto:anon.0:34@lxplus722.cern.ch) TLS_Accept: Accepting a TLS connection...
220225 15:34:39 26340 XrdLinkXeq: [anon.0:34@lxplus722.cern.ch](mailto:anon.0:34@lxplus722.cern.ch) connection upgraded to TLSv1.2
220225 15:34:39 26340 [anon.0:34@lxplus722.cern.ch](mailto:anon.0:34@lxplus722.cern.ch) TLS_Read: 24 out of 24 bytes.
220225 15:34:39 26340 [anon.0:34@lxplus722.cern.ch](mailto:anon.0:34@lxplus722.cern.ch) TLS_Read: 93 out of 93 bytes.
220225 15:34:39 26340 [bockjoo.467:34@lxplus722.cern.ch](mailto:bockjoo.467:34@lxplus722.cern.ch) TLS_Write: 8 out of 8 bytes.
220225 15:34:39 26340 [bockjoo.467:34@lxplus722.cern.ch](mailto:bockjoo.467:34@lxplus722.cern.ch) TLS_Write: 16 out of 16 bytes.
220225 15:34:39 26340 [bockjoo.467:34@lxplus722.cern.ch](mailto:bockjoo.467:34@lxplus722.cern.ch) TLS_Write: 59 out of 59 bytes.
220225 15:34:39 26340 XrdTLS: [bockjoo.467:34@lxplus722.cern.ch](mailto:bockjoo.467:34@lxplus722.cern.ch) TLS error rc=0 ec=6 (zero_return) errno=0.
220225 15:34:39 26340 [bockjoo.467:34@lxplus722.cern.ch](mailto:bockjoo.467:34@lxplus722.cern.ch) TLS_Shutdown: Doing fast shutdown.
220225 15:34:39 26340 XrootdXeq: [bockjoo.467:34@lxplus722.cern.ch](mailto:bockjoo.467:34@lxplus722.cern.ch) disc 0:00:01
220225 15:34:39 26340 multiuser_UserSentry: Anonymous client; no user set, cannot change FS UIDs
220225 15:34:39 26340 [bockjoo.467:34@lxplus722.cern.ch](mailto:bockjoo.467:34@lxplus722.cern.ch) Xrd_Poll: Poller 0 removing FD 34
220225 15:34:39 26340 [bockjoo.467:34@lxplus722.cern.ch](mailto:bockjoo.467:34@lxplus722.cern.ch) Xrd_Poll: FD 34 detached from poller 0; num=0
220225 15:34:39 26339 Xrd_Sched: running monitor window clock inq=0
220225 15:34:39 26339 Xrd_Sched: scheduling monitor window clock in 5 seconds
220225 15:34:39 26362 Xrd_Sched: running main accept inq=0
220225 15:34:40 26421 Xrd_Inet: Accepted connection on port 1094 from [37@lxplus722.cern.ch](mailto:37@lxplus722.cern.ch)
220225 15:34:40 26421 Xrd_ProtLoad: matched port 1094 protocol xroot
220225 15:34:40 26421 [anon.0:37@lxplus722.cern.ch](mailto:anon.0:37@lxplus722.cern.ch) Xrd_Poll: FD 37 attached to poller 0; num=1
220225 15:34:40 26421 [anon.0:37@lxplus722.cern.ch](mailto:anon.0:37@lxplus722.cern.ch) TLS_Accept: Accepting a TLS connection...
220225 15:34:40 26421 XrdLinkXeq: [anon.0:37@lxplus722.cern.ch](mailto:anon.0:37@lxplus722.cern.ch) connection upgraded to TLSv1.2
220225 15:34:40 26421 [anon.0:37@lxplus722.cern.ch](mailto:anon.0:37@lxplus722.cern.ch) TLS_Read: 24 out of 24 bytes.
220225 15:34:40 26421 [anon.0:37@lxplus722.cern.ch](mailto:anon.0:37@lxplus722.cern.ch) TLS_Read: 93 out of 93 bytes.
220225 15:34:40 26421 [bockjoo.467:37@lxplus722.cern.ch](mailto:bockjoo.467:37@lxplus722.cern.ch) TLS_Write: 8 out of 8 bytes.
220225 15:34:40 26421 [bockjoo.467:37@lxplus722.cern.ch](mailto:bockjoo.467:37@lxplus722.cern.ch) TLS_Write: 16 out of 16 bytes.
220225 15:34:40 26421 [bockjoo.467:37@lxplus722.cern.ch](mailto:bockjoo.467:37@lxplus722.cern.ch) TLS_Write: 59 out of 59 bytes.
220225 15:34:40 26421 XrdTLS: [bockjoo.467:37@lxplus722.cern.ch](mailto:bockjoo.467:37@lxplus722.cern.ch) TLS error rc=0 ec=6 (zero_return) errno=0.
220225 15:34:40 26421 [bockjoo.467:37@lxplus722.cern.ch](mailto:bockjoo.467:37@lxplus722.cern.ch) TLS_Shutdown: Doing fast shutdown.
220225 15:34:40 26421 XrootdXeq: [bockjoo.467:37@lxplus722.cern.ch](mailto:bockjoo.467:37@lxplus722.cern.ch) disc 0:00:00
220225 15:34:40 26421 multiuser_UserSentry: Anonymous client; no user set, cannot change FS UIDs
220225 15:34:40 26421 [bockjoo.467:37@lxplus722.cern.ch](mailto:bockjoo.467:37@lxplus722.cern.ch) Xrd_Poll: Poller 0 removing FD 37
220225 15:34:40 26421 [bockjoo.467:37@lxplus722.cern.ch](mailto:bockjoo.467:37@lxplus722.cern.ch) Xrd_Poll: FD 37 detached from poller 0; num=0


Here's the log created by the IB built client that fails to use the ztn protocol:
220225 15:34:38 26340 Xrd_Inet: Accepted connection on port 1094 from [34@lxplus722.cern.ch](mailto:34@lxplus722.cern.ch)
220225 15:34:38 26340 Xrd_ProtLoad: matched port 1094 protocol xroot
220225 15:34:38 26340 [anon.0:34@lxplus722.cern.ch](mailto:anon.0:34@lxplus722.cern.ch) Xrd_Poll: FD 34 attached to poller 0; num=1
220225 15:34:38 26340 [anon.0:34@lxplus722.cern.ch](mailto:anon.0:34@lxplus722.cern.ch) TLS_Accept: Accepting a TLS connection...
220225 15:34:39 26340 XrdLinkXeq: [anon.0:34@lxplus722.cern.ch](mailto:anon.0:34@lxplus722.cern.ch) connection upgraded to TLSv1.2
220225 15:34:39 26340 [anon.0:34@lxplus722.cern.ch](mailto:anon.0:34@lxplus722.cern.ch) TLS_Read: 24 out of 24 bytes.
220225 15:34:39 26340 [anon.0:34@lxplus722.cern.ch](mailto:anon.0:34@lxplus722.cern.ch) TLS_Read: 93 out of 93 bytes.
220225 15:34:39 26340 [bockjoo.467:34@lxplus722.cern.ch](mailto:bockjoo.467:34@lxplus722.cern.ch) TLS_Write: 8 out of 8 bytes.
220225 15:34:39 26340 [bockjoo.467:34@lxplus722.cern.ch](mailto:bockjoo.467:34@lxplus722.cern.ch) TLS_Write: 16 out of 16 bytes.
220225 15:34:39 26340 [bockjoo.467:34@lxplus722.cern.ch](mailto:bockjoo.467:34@lxplus722.cern.ch) TLS_Write: 59 out of 59 bytes.
220225 15:34:39 26340 XrdTLS: [bockjoo.467:34@lxplus722.cern.ch](mailto:bockjoo.467:34@lxplus722.cern.ch) TLS error rc=0 ec=6 (zero_return) errno=0.
220225 15:34:39 26340 [bockjoo.467:34@lxplus722.cern.ch](mailto:bockjoo.467:34@lxplus722.cern.ch) TLS_Shutdown: Doing fast shutdown.
220225 15:34:39 26340 XrootdXeq: [bockjoo.467:34@lxplus722.cern.ch](mailto:bockjoo.467:34@lxplus722.cern.ch) disc 0:00:01
220225 15:34:39 26340 multiuser_UserSentry: Anonymous client; no user set, cannot change FS UIDs
220225 15:34:39 26340 [bockjoo.467:34@lxplus722.cern.ch](mailto:bockjoo.467:34@lxplus722.cern.ch) Xrd_Poll: Poller 0 removing FD 34
220225 15:34:39 26340 [bockjoo.467:34@lxplus722.cern.ch](mailto:bockjoo.467:34@lxplus722.cern.ch) Xrd_Poll: FD 34 detached from poller 0; num=0
220225 15:34:39 26339 Xrd_Sched: running monitor window clock inq=0
220225 15:34:39 26339 Xrd_Sched: scheduling monitor window clock in 5 seconds
220225 15:34:39 26362 Xrd_Sched: running main accept inq=0
220225 15:34:40 26421 Xrd_Inet: Accepted connection on port 1094 from [37@lxplus722.cern.ch](mailto:37@lxplus722.cern.ch)
220225 15:34:40 26421 Xrd_ProtLoad: matched port 1094 protocol xroot
220225 15:34:40 26421 [anon.0:37@lxplus722.cern.ch](mailto:anon.0:37@lxplus722.cern.ch) Xrd_Poll: FD 37 attached to poller 0; num=1
220225 15:34:40 26421 [anon.0:37@lxplus722.cern.ch](mailto:anon.0:37@lxplus722.cern.ch) TLS_Accept: Accepting a TLS connection...
220225 15:34:40 26421 XrdLinkXeq: [anon.0:37@lxplus722.cern.ch](mailto:anon.0:37@lxplus722.cern.ch) connection upgraded to TLSv1.2
220225 15:34:40 26421 [anon.0:37@lxplus722.cern.ch](mailto:anon.0:37@lxplus722.cern.ch) TLS_Read: 24 out of 24 bytes.
220225 15:34:40 26421 [anon.0:37@lxplus722.cern.ch](mailto:anon.0:37@lxplus722.cern.ch) TLS_Read: 93 out of 93 bytes.
220225 15:34:40 26421 [bockjoo.467:37@lxplus722.cern.ch](mailto:bockjoo.467:37@lxplus722.cern.ch) TLS_Write: 8 out of 8 bytes.
220225 15:34:40 26421 [bockjoo.467:37@lxplus722.cern.ch](mailto:bockjoo.467:37@lxplus722.cern.ch) TLS_Write: 16 out of 16 bytes.
220225 15:34:40 26421 [bockjoo.467:37@lxplus722.cern.ch](mailto:bockjoo.467:37@lxplus722.cern.ch) TLS_Write: 59 out of 59 bytes.
220225 15:34:40 26421 XrdTLS: [bockjoo.467:37@lxplus722.cern.ch](mailto:bockjoo.467:37@lxplus722.cern.ch) TLS error rc=0 ec=6 (zero_return) errno=0.
220225 15:34:40 26421 [bockjoo.467:37@lxplus722.cern.ch](mailto:bockjoo.467:37@lxplus722.cern.ch) TLS_Shutdown: Doing fast shutdown.
220225 15:34:40 26421 XrootdXeq: [bockjoo.467:37@lxplus722.cern.ch](mailto:bockjoo.467:37@lxplus722.cern.ch) disc 0:00:00
220225 15:34:40 26421 multiuser_UserSentry: Anonymous client; no user set, cannot change FS UIDs
220225 15:34:40 26421 [bockjoo.467:37@lxplus722.cern.ch](mailto:bockjoo.467:37@lxplus722.cern.ch) Xrd_Poll: Poller 0 removing FD 37
220225 15:34:40 26421 [bockjoo.467:37@lxplus722.cern.ch](mailto:bockjoo.467:37@lxplus722.cern.ch) Xrd_Poll: FD 37 detached from poller 0; num=0

You can see one is reading the scitoken config but the other is not.
So, locally I am using:
[bockjoo@cms ~]$ rpm -ql scitokens-cpp-0.6.2-1.osg35.el7.x86_64
/usr/lib64/libSciTokens.so.0
/usr/lib64/libSciTokens.so.0.0.2

**Comment by bockjoo** [comment]
I am sorry I was wrong.
I forgot that I set XrdSecPROTOCOL=gsi,unix which prevented the client from using the ztn protocol.
The IB build works fine.
So, this issue can be closed.
Thanks!

**Comment by smuzaffar** [comment]
+core
xrootd 5.4.1 is now available in 12.3.X IBs.
