### ISSUE TITLE
Request to include requests[socks] in the python packages

### ISSUE THREAD

**Issue by Sam-Harper** [cms-sw/cmssw#36917]
Dear CMSSW maintainers,

It would be useful for me if we could include requests[socks] in the default CMSSW python packages.

This would greatly assist in the situation where we have a machine with no external internet access and we need to proxy over a ssh tunnel.  

It is a bit of a chicken and egg situation as well, as if if requests[socks] was already installed, it would be trivial install it locally via pip. But when its missing, pip also can not prox .  So in the case you have no internet access requests[socks] seems to be a prerequisite for installing requests[socks]. Catch22 in action. 

The workaround is to manually copy over the package from another machine but if its possible to have it preinstalled, it would make things a bit easier. Its not a critical request, just makes life easier.

Thanks,
Sam

**Comment by makortel** [comment]
assign core

**Comment by Sam-Harper** [comment]
ping

any chance of this? Or should we continue with work arounds for machines without direct access to the internet?

**Comment by Sam-Harper** [comment]
@Dr15Jones , @smuzaffar , @makortel , any chance of this?

I now have a convenient workaround for my specific issue but it would be nice if we could get this.

**Comment by smuzaffar** [comment]
@Sam-Harper , according to https://pypi.org/project/requesocks/#description `requests[socks] `  is already bundled in `requests` package which is available in cmssw env. So what else are we missing in cmssw?

**Comment by Sam-Harper** [comment]
Hi @smuzaffar 

Are you sure requests[socks] is actually installed?  I testedin CMSSW_12_5_0_pre1

![image](https://user-images.githubusercontent.com/5021403/172792660-ca4ac7e0-e55d-4121-9856-0470e1db955a.png)

I can resolve this easily by simply doing 

```
pip3 install requests[socks]
```

which unfortunately is only possible on a machine with direct connection to the internet

**Comment by smuzaffar** [comment]
ah right , our `requests` package is not installed with `socks` support. Can you please check if installing `PySocks3.9==2.0` locally works?

**Comment by smuzaffar** [comment]
@Sam-Harper, can you please check if installing `pysocks` works with proxy?

**Comment by smuzaffar** [comment]
great, I will include it in cmssw software stack then

**Comment by Sam-Harper** [comment]
thank you so much, this life much easier on restricted network machines!
