### ISSUE TITLE
ROOT issue in RECO-only workflows

### ISSUE THREAD

**Issue by kskovpen** [cms-sw/cmssw#37013]
We are observing the following issue in one of the wf running in CMSSW_12_3_0_pre5: https://cms-unified.web.cern.ch/cms-unified/showlog/?search=CMSSW_12_3_0_pre5__fullsim_PU_2021_14TeV_RECOonly-TTbar_14TeV-00001

[a] Fatal Root Error: @SUB=TBufferFile::CheckByteCount
object of class vector read too many bytes: 29704 instead of 12296

This wf runs the RECO step on top of a dataset that was produced in CMSSW_12_3_0_pre3 - its the only feature that probably can be highlighted here. The strange thing is that similar wfs (e.g. noPU) finished successfully.

The issue can be reproduced locally by starting from the following configuration:

cmsDriver.py step2 --conditions auto:phase1_2021_realistic --datatier GEN-SIM-RECO,MINIAODSIM,NANOAODSIM,DQMIO --era Run3 --eventcontent RECOSIM,MINIAODSIM,NANOEDMAODSIM,DQM --filein "/store/relval/CMSSW_12_3_0_pre3/RelValTTbar_14TeV/GEN-SIM-DIGI-RAW/PU_123X_mcRun3_2021_realistic_v3-v2/10000/4bd0daf8-f188-4e9a-a376-182b4fb53a82.root" --fileout "file:step2.root" --geometry DB:Extended --nStreams 2 --nThreads 8 --no_exec --number 10 --python_filename step_2_cfg.py --step RAW2DIGI,L1Reco,RECO,RECOSIM,PAT,NANO,VALIDATION:@standardValidation+@miniAODValidation,DQM:@standardDQM+@ExtraHLT+@miniAODDQM+@nanoAODDQM

@bbilin @jordan-martins

**Comment by Dr15Jones** [comment]
Giving more context to the failure
```
An exception of category 'FileReadError' occurred while
[0] Processing Event run: 1 lumi: 1 event: 1 stream: 1
[1] Running path 'dqmofflineOnPAT_2_step'
...
[171] Processing Event run: 1 lumi: 1 event: 1 stream: 1
[172] Running path 'RECOSIMoutput_step'
[173] Prefetching for module PoolOutputModule/'RECOSIMoutput'
[174] While reading from source std::vector hltScoutingPFPacker '' HLT
[175] Reading branch Run3ScoutingParticles_hltScoutingPFPacker__HLT.
Additional Info:
[a] Fatal Root Error: @SUB=TBufferFile::CheckByteCount
object of class vector read too many bytes: 29704 instead of 12296
```

**Comment by makortel** [comment]
Adding @dan131riley and @pcanal since the problem appears to be the same as mentioned in https://github.com/cms-sw/cmssw/issues/36908#issuecomment-1040749111

**Comment by makortel** [comment]
> This wf runs the RECO step on top of a dataset that was produced in CMSSW_12_3_0_pre3 - its the only feature that probably can be highlighted here

This detail implies that the condition is the same mentioned in https://github.com/cms-sw/cmssw/issues/36908#issuecomment-1043035696, i.e. the file was written with ROOT 6.22 (here it is being read with 6.24).

**Comment by makortel** [comment]
Just to note here, #35685 (or any other resolution of https://github.com/cms-sw/cmssw/issues/32219, that should come "soon") would break reading of existing Run 3 scouting data formats (by construction).

**Comment by makortel** [comment]
As a workaround. dropping the offending product on input, i.e. adding `--inputCommands="keep *,drop Run3ScoutingParticles_hltScoutingPFPacker__HLT"` to the `cmsDriver.py` recipe in the description, allows the job to run. It's not a very good solution though as the product in question will be lost, so it would be good for us to understand what caused the problem.

Regarding https://github.com/cms-sw/cmssw/pull/35685 / https://github.com/cms-sw/cmssw/issues/32219, I made some tests and it seems to me that at least that specific job would be able to run even if we'd drop the current dependence on `DataFormats/TrackReco` from `DataFormats/Scouting`. So apparently ROOT's schema evolution would be able to handle that change without completely breaking it (the HitPattern part would be lost).

**Comment by makortel** [comment]
@kskovpen Out of curiosity, I noticed the example job in the description had `--nStreams 2 --nThreads 8`. Was 2 streams with 8 threads intentional?

**Comment by kskovpen** [comment]
Hi @makortel , many thanks for looking into this issue. There is indeed no specific reason to run the RECO step with 2 streams and 8 threads. It somehow was inherited from PU relval wfs in e.g. the DIGI step where such configuration is used when producing validation samples. This is most likely not optimal.

**Comment by makortel** [comment]
Nothing to be updated here

**Comment by makortel** [comment]
+core

**Comment by makortel** [comment]
@cmsbuild, please close
