### ISSUE TITLE
ECAL GPU validation DQM follow up actions after PR #36742

### ISSUE THREAD

**Issue by thomreis** [cms-sw/cmssw#37025]
In order to merge the ECAL GPU validation DQM PR #36742 a couple of tasks have been postponed to be done in follow up PRs.

- [x] Add 2D comparison histograms (https://github.com/cms-sw/cmssw/pull/36742#issuecomment-1022029553)
- [x] Add a matrix workflow that executes the ECAL GPU validation
- [x] Remove type from modifier configuration (https://github.com/cms-sw/cmssw/pull/36742#pullrequestreview-889552505) 

@alejands @fwyzard @jfernan2

**Comment by makortel** [comment]
assign dqm

**Comment by fwyzard** [comment]
assign ecal-dpg

**Comment by fwyzard** [comment]
assign dqm

**Comment by fwyzard** [comment]
assign heterogeneous

**Comment by thomreis** [comment]
2D histograms addressed in PR #38427

**Comment by thomreis** [comment]
+ecal-dpg

**Comment by thomreis** [comment]
+1

**Comment by thomreis** [comment]
Hi @smuzaffar why did signing with +ecal-dpg not work here?

**Comment by fwyzard** [comment]
+heterogeneous

**Comment by smuzaffar** [comment]
> Hi @smuzaffar why did signing with +ecal-dpg not work here?

@thomreis , bot was not recognizing `-` char in the category name. This has been fixed now ( https://github.com/cms-sw/cms-bot/commit/1f3006fefcf25b1773cb68f592d283438d66bcfa )

**Comment by thomreis** [comment]
Thanks @smuzaffar

**Comment by emanueleusai** [comment]
+1
