### ISSUE TITLE
Comparison of DDD and DD4hep in Phase-2 Worflow

### ISSUE THREAD

**Issue by srimanob** [cms-sw/cmssw#37087]
This issue is to follow up on difference, warning, error of DD4hep phase-2 workflows. Currently, the DD4hep can run on D88 (and other wfs. with M10). All remaining showstopper mentioned in https://github.com/cms-sw/cmssw/issues/36837 seems to be solved using 3 PRs (https://github.com/cms-sw/cmssw/pull/37005, https://github.com/cms-sw/cmssw/pull/37078, https://github.com/cms-sw/cmssw/pull/37079)

Some code review, clean up, debugging may take sometimes. However, the workflow can run until finish using [1]. 

Current issue (as of 28 Feb)

(1) Warning/Error message of HCAL in all events
Message in DIGI step:
```
%MSG-e HcalDigitizer:  MixingModule:mix 27-Feb-2022 11:23:14 CET Run: 1 Event: 3
bad hcal id found in digitizer. Skipping 1161838639 (HE -16,47,4)
%MSG
```
Message in RECO step:
```
%MSG-w HcalDetId:  HcalDigisValidation:AllHcalDigisValidation  27-Feb-2022 11:30:04 CET Run: 1 Event: 9
HcalDetID(SimHit) presents conflicting information. Depth: 4, iphi: 53, ieta: 16. Max depth from geometry is: 0. TestNumber = 1
%MSG
```

(2) Difference shows up in HGCAL DQM, e.g.
	• [SimClusters/ticlSimTracksters](https://tinyurl.com/yddbf4ge)
	• [HitCalibration](https://tinyurl.com/ycfz6fkw)
![overlay](https://user-images.githubusercontent.com/4701449/156006786-0a53a1e5-f32d-49dc-bdab-9357d30a96f8.png)
where
   .Black: D88 DDD Private
   .Blue: D88 DD4hep Private
   .Orange: DDD D77 central (12_3_0_pre5) <<== maybe it does not make sense to compare D77 here, just to make complete picture
   .Red: DDD D88 central (12_3_0_pre5)
Note: This is done with private production. The agreement can be seen between DDD D88 official (red) and private (black).

DQM comparison for all is at [https://tinyurl.com/ycg33avb](https://tinyurl.com/ycg33avb)

[1]
```
cmsrel CMSSW_12_3_X_2022-02-26-1100
cd CMSSW_12_3_X_2022-02-26-1100/src/
cmsenv
git cms-merge-topic srimanob:123_L1TDD4HepWf
git cms-merge-topic srimanob:123_FixPhase2DTSpecsFilter
scram b -j 8
runTheMatrix.py --what upgrade -l 39434.911 -t 8 --wm init
```

**Comment by makortel** [comment]
assign geometry,upgrade

**Comment by srimanob** [comment]
@cms-sw/hcal-dpg-l2 
(Parallel with email, sorry. I just realize that I never ping you on git before)

**Comment by srimanob** [comment]
Seem the issue of HCAL DetID is fixed in https://github.com/cms-sw/cmssw/pull/39967
