### ISSUE TITLE
Getting line numbers in UBSAN

### ISSUE THREAD

**Issue by Dr15Jones** [cms-sw/cmssw#37131]
The UBSAN logs are not showing line numbers in the tracebacks. I tried doing
```
setenv USER_CXXFLAGS '-O0 -g'
```

and rebuilding. That does pass the correct flags to the builds but I still am not seeing line numbers. Any suggestions?

**Comment by Dr15Jones** [comment]
assign core

**Comment by Dr15Jones** [comment]
@smuzaffar thoughts?

**Comment by smuzaffar** [comment]
`setenv USER_CXXFLAGS '-O0 -g'` works for ASAN so, I guess it would work for UBSAN too. Did you `git cms-addpkg` the cmssw package before running `scram build`? Note that setting `setenv USER_CXXFLAGS '-O0 -g'` is not going to rebuild if you already have build, you need `scram build clean`

**Comment by Dr15Jones** [comment]
I can also see that it is picking up my libraries as the libraries full file name (including its path) shows it comes from my work area.

**Comment by Dr15Jones** [comment]
Another item of note, the line numbers do appear for the FWCore libraries, but do not seem to appear for any of the dynamically loaded plugins.

**Comment by smuzaffar** [comment]
looking at https://cmssdt.cern.ch/SDT/cgi-bin/logreader/slc7_amd64_gcc11/CMSSW_12_3_UBSAN_X_2022-03-02-1100/pyRelValMatrixLogs/run/136.887_RunDoubleMuon2018D+RunDoubleMuon2018D+HLTDR2_2018+RECODR2_2018reHLT_Prompt+HARVEST2018_Prompt/step3_RunDoubleMuon2018D+RunDoubleMuon2018D+HLTDR2_2018+RECODR2_2018reHLT_Prompt+HARVEST2018_Prompt.log#/ , I see that it did print out line number for `IOPool/TFileAdaptor/src/TFileAdaptor.cc` which should have been loaded via edm plugin

**Comment by Dr15Jones** [comment]
If I use `addr2line` I am able to find out the line numbers given the address and the shared library, e.g.
```
> addr2line -C -f -a 0x561495 -e lib/slc7_amd64_gcc11/libRecoTrackerMkFitCore.so
0x0000000000561495
mkfit::MatriplexErrParPackerSlurpIn<mkfit::Hit, float>::MatriplexErrParPackerSlurpIn(mkfit::Hit const&)
/uscms_data/d2/cdj/build/temp/ubsan/CMSSW_12_3_UBSAN_X_2022-03-02-1100/src/RecoTracker/MkFitCore/src/MatriplexPackers.h:73

```

So the info is there but the UBSAN dump isn't showing it for some reason.

**Comment by smuzaffar** [comment]
+core 
UBSAN logs now print the line number [a] 

[a] https://cmssdt.cern.ch/SDT/cgi-bin/buildlogs/raw/el8_amd64_gcc12/CMSSW_14_2_UBSAN_X_2024-10-14-2300/pyRelValMatrixLogs/run/24034.0_TTbar_14TeV+2026D96/step3_TTbar_14TeV+2026D96.log
```
src/DQM/GEM/plugins/GEMDAQStatusSource.cc:559:58: runtime error: shift exponent 39 is too large for 32-bit type 'int'
    #0 0x14c6618d41e6 in GEMDAQStatusSource::analyze(edm::Event const&, edm::EventSetup const&) src/DQM/GEM/plugins/GEMDAQStatusSource.cc:559
    #1 0x14c787ad6fa3 in edm::stream::EDProducerAdaptorBase::doEvent(edm::EventTransitionInfo const&, edm::ActivityRegistry*, edm::ModuleCallingContext const*) src/FWCore/Framework/src/stream/EDProducerAdaptorBase.cc:83
    #2 0x14c78791fee8 in edm::WorkerT<edm::stream::EDProducerAdaptorBase>::implDo(edm::EventTransitionInfo const&, edm::ModuleCallingContext const*) src/FWCore/Framework/src/WorkerT.cc:202
    #3 0x14c786f57f3f in edm::workerhelper::CallImpl<edm::OccurrenceTraits<edm::EventPrincipal, (edm::BranchActionType)1> >::call(edm::Worker*, edm::StreamID, edm::EventTransitionInfo const&, edm::ActivityRegistry*, edm::ModuleCallingContext const*, edm::StreamContext const*) src/FWCore/Framework/interface/maker/Worker.h:699
```
