### ISSUE TITLE
add of the --procModifiers option for 9_4_X release 

### ISSUE THREAD

**Issue by jordan-martins** [cms-sw/cmssw#37155]
Dear all,

We need to produce some FastSim preLegacy MC for SUSY on 9_4_X in which includes a procModifier that fixes BSM particles simulation (--procModifiers fastSimFixLongLivedBug). Nevertheless, this option is not available on the 9_4_X release as one can check in here: https://github.com/cms-sw/cmssw/blob/CMSSW_9_4_X/Configuration/Applications/python/Options.py . Ideally, after checking with Release Managers, perhaps a backport of this (https://github.com/cms-sw/cmssw/pull/21272) could be enough. 

Thanks,
Jordan

**Comment by srimanob** [comment]
Should you just go with customization, i.e.
process.fastSimProducer.fixLongLivedBug = cms.bool(True) ?

**Comment by jordan-martins** [comment]
Hi @srimanob,
yeah, I do agree. Nevertheless, I am trying to let this as homogenous as possible with respect to the other configurations. If this is too convoluted to backport, we shall go this way.

Thanks,
Jordan

**Comment by makortel** [comment]
assign operations, fastsim

**Comment by makortel** [comment]
> But to make a backport or not, I will let @cms-sw/core-l2 to give comments.

Why core? `Configuration/Applications` is under @cms-sw/operations-l2.

**Comment by srimanob** [comment]
> > But to make a backport or not, I will let @cms-sw/core-l2 to give comments.
> 
> Why core? `Configuration/Applications` is under @cms-sw/operations-l2.

Sure, Sorry.

**Comment by jordan-martins** [comment]
Hi all,
I am closing this issue. We decided to move with the customise solution as Phat indicated before.
Thanks,
Jordan
