### ISSUE TITLE
HLT menu does not map correctly in PAT when negated filters are present 

### ISSUE THREAD

**Issue by perrotta** [cms-sw/cmssw#37157]
After the integration of the HLT menu development for 12_3_X (as coded in PR #37152) several warning messages from `PATTriggerObjectStandAloneSlimmer` suggest that the slimmer cannot handle the cases where a tilde is added in front of a filter, in order to negate its boolean outcome, in any of the HLT paths.

The message reported in the step3 logs of the workflows run by bot while testing the PR is the following:
```
%MSG-w TriggerObjectStandAlone::packFilterLabels():   PATTriggerObjectStandAloneSlimmer:slimmedPatTrigger 06-Mar-2022 14:09:27 CET  Run: 1 Event: 3
Warning: can't resolve 'hltL3fDimuonL1f0ppL2NV2Chaf10L3NVf0Veto1Prompt' to a label index. idx: 3
%MSG
%MSG-w TriggerObjectStandAlone::packFilterLabels():   PATTriggerObjectStandAloneSlimmer:slimmedPatTrigger 06-Mar-2022 14:09:27 CET  Run: 1 Event: 3
Warning: can't resolve 'hltL3fDimuonL1f0ppL2NV2Chaf10L3NVf0Veto1Prompt' to a label index. idx: 1
%MSG
```

@missirol verified that it was indeed the tilde in front of the filter that originated that warning, as reported in https://github.com/cms-sw/cmssw/pull/37152#issuecomment-1060064525:
"
To confirm: I tested wf `11634.0`, reproduced the additional warning, then verified that modifying the GRun menu as follows
```diff
+ [..] + hltL3fDimuonL1f0ppL2NV2Chaf10L3NVf0Veto1Prompt
- [..] + ~hltL3fDimuonL1f0ppL2NV2Chaf10L3NVf0Veto1Prompt
```
makes the warning disappear (to be clear: this was just a test, the tilde needs to remain in place in the new GRun menu).
This is consistent with `PATTriggerObjectStandAloneSlimmer` somehow not being able to handle the presence of the tilde operator.
"

PR #37152 is now merged anyhow, to ease further HLT trigger developments for Run3.
But obviously having one HLT path wrongly mirrored in PAT is a bug that must be fixed before that miniAOD starts being used for the analyses.

The fix must be applied quite likely in PhysicsTools/PatAlgos/plugins/PATTriggerObjectStandAloneSlimmer.cc, but of course some expert must take care of it in order to implemen it correctly

**Comment by perrotta** [comment]
assign hlt,xpog

**Comment by Martin-Grunewald** [comment]
Who is currently maintaining the PAT trigger code? I believe the developer Volker Adler did so in the past, originated it,  but it seems he has left CMS years ago, and there has not been any development since then (apart of technical changes).

**Comment by vlimant** [comment]
@missirol : I think it's better to close this issue and open a specific one for https://github.com/cms-sw/cmssw/pull/37181#issuecomment-1063149619 so that it gets assigned properly without ambiguity.

**Comment by vlimant** [comment]
please close

**Comment by missirol** [comment]
+hlt
