### ISSUE TITLE
AK4 CHS jets pT cut for Run3

### ISSUE THREAD

**Issue by clacaputo** [cms-sw/cmssw#37167]
This issues is intended as a reminder for @cms-sw/reconstruction-l2 , @cms-sw/xpog-l2 and @cms-sw/jetmet-pog-l2, about the discussion we had in https://github.com/cms-sw/cmssw/pull/36890.

**Context**
Switching from `AK4 CHS` to `AK4 PUPPI` jet for Run3 as recommended jet collection. 
The PR https://github.com/cms-sw/cmssw/pull/36890 is decreasing the `AK4 PUPPI` jet `pT` cut from `15` to `10`. This effect the AOD event size. Three possible scenarios:

1. keeping AK4 CHS jets pT cut at `10`, leads to an MiniAOD event size **increase** of `0.37%`
2. increasing AK4 CHS jets pT cut at `15`, leads to an MiniAOD event size **decrease** of `1.0%`
3. keeping AK4 CHS jets pT cut at `10`, but slimming down the collection, not yet investigated.

Scenario `1` is favoured by xpog and jmet so we could recalibration of the type1MET with both collections, without invalidating pfMET (https://github.com/cms-sw/cmssw/pull/36890#issuecomment-1054648685). 

This is a solution just until the end of 2022. To be revised with either scenario `2` or `3`

NOTA: potential decrease in MiniAOD event size ~1%

**Comment by clacaputo** [comment]
assign xpog

**Comment by jpata** [comment]
type jetmet

**Comment by vlimant** [comment]
@kirschen : is the need for keeping CHS AK4 Jets at `>10` still justified ? am I getting this correctly that such CHS Jets are needed to allow one to use pfMET (by allowing for type1 jet correction to be propagated to it) ?

**Comment by kirschen** [comment]
Hi @vlimant, good to bring this up. Yes, the "solution 1" was chosen for maximum flexibility during startup, and being able to do type-1 jet corrections "with CHS jets" is one aspect. I will bring it up for discussion within JME again.

**Comment by kirschen** [comment]
> Hi @vlimant, good to bring this up. Yes, the "solution 1" was chosen for maximum flexibility during startup, and being able to do type-1 jet corrections "with CHS jets" is one aspect. I will bring it up for discussion within JME again.

Pinging  @alkaloge @miquork @cms-sw/jetmet-pog-l2 , cf. coordination chat post in December to wrap this up.

**Comment by vlimant** [comment]
can we close this, eventually ?

**Comment by nurfikri89** [comment]
@vlimant This is on my to do list. I am looking into doing option (2) and (3) at the same time.

**Comment by nurfikri89** [comment]
I have made more studies with a TTto4Q Run3Summer23DRPremix inputs. Here are the event size reduction for the various options.

1. AK4 CHS jet `pt > 15 GeV`:  -1.5% 
2. AK4 CHS jet `pt > 15 GeV`, remove PileupID & QGL: -1.6%
3. AK4 CHS jet`pt > 15 GeV`, remove PileupID, QGL & DeepCSV: -1.8%
4. AK4 CHS jet `pt > 15 GeV`, remove PileupID, QGL, DeepCSV & DeepJet: -2.0%.

If the JetMET convenors can agree on an option, I can make a PR for this ASAP.

cc JetMET convenors (@abenecke, @alkaloge, @gagarwal, @dsavoiu, @fiemmi, @rkogler, @wajidalikhan)

**Comment by nurfikri89** [comment]
This is now resolved and merged in `14_1_X` and `14_0_X`.

**Comment by vlimant** [comment]
please close
