### ISSUE TITLE
Spurious failing comparisons entries in PR tests for MuonCSCDigisV/CSCDigiTask/CLCT

### ISSUE THREAD

**Issue by perrotta** [cms-sw/cmssw#37268]
Since some while, spurious failing comparisons entries show up in PR tests for MuonCSCDigisV/CSCDigiTask/CLCT.
They are not reproducible (repeated tests may show different comparisons).
A few examples can be seen in the comparisons of PRs  #37260 (for wf 10042), #37263 (for wf 1330), ...

In all plots that I have inspected the visible bins looks identical. and therefore the difference could be in the overflow/underflow bins (just guessing, since the number of entries in those plots are larger than the number of entries in the visible bins).

Looking at the recently merged PRs, #37188 ("Make both ME1a and ME1b LCT (A/CLCT) sorted into ring 1") could be the origin of the issue, even if I can't see why. Let me point out that  #37188 was also merged in 12_2 and 12_3: if any fix is needed, it should also get backported there.

@sifuluo @jfernan2 could you please have a look?

**Comment by perrotta** [comment]
assign dqm

**Comment by jfernan2** [comment]
@barvic   please also have a look as CSC Validation developer. Thanks

**Comment by sifuluo** [comment]
I've found the direct cause for this issue. And we will have a discussion to pick a solution to it asap.

**Comment by perrotta** [comment]
Supposedly fi*ed by #37282.
Let see if really the failing comparisons disappear from forthcoming PR tests before finally closing this issue

**Comment by perrotta** [comment]
If the fix works as expected, two backports to 12_3_X and 12_2_X should also be prepared, because the bug is also present in those two release cycles

**Comment by jfernan2** [comment]
@sifuluo could you please make the backports? Thanks

**Comment by perrotta** [comment]
@sifuluo @jfernan2 I am observing that in some PR tests based on CMSSW_12_4_X_2022-03-22-1100, which already includes https://github.com/cms-sw/cmssw/pull/37282, the spurious differences in the DQM comparisons for MuonCSCDigisV/CSCDigiTask/CLCT are still there, see for example wf [10042.0](https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_12_4_X_2022-03-22-1100+cadc83/49072/10042.0_ZMM_13+2017+ZMM_13TeV_TuneCUETP8M1_GenSim+Digi+RecoFakeHLT+HARVESTFakeHLT+ALCA+Nano) in https://github.com/cms-sw/cmssw/pull/37265#issuecomment-1075798407

**Comment by sifuluo** [comment]
Let's see if this one solves it

**Comment by perrotta** [comment]
Ok, https://github.com/cms-sw/cmssw/pull/37319 looks like it has fixed the issue, or at least I did not see those failing comparisons any more in the PR tests since it was merged in master in CMSSW_12_4_X_2022-03-24-1100

Now backports of the combined fix, #37282 + #37319, should be prepared for:
- CMSSW_12_2_X (to fix the bug introduced with #37179)
- CMSSW_12_3_X (to fix the bug introduced with #37217)
- 
 because the bug is also present in those two release cycles

@sifuluo could you please take care of it? Please notice that a new 12_2_X release is expected to be built in short, and it would be a pity not to include these fixes in it.

**Comment by perrotta** [comment]
+1
- Fixed by https://github.com/cms-sw/cmssw/pull/37282
 and https://github.com/cms-sw/cmssw/pull/37319, and their backports to 12_2_X and 12_3_X
