### ISSUE TITLE
On demand generation of baseline for pull requests relvals comparison jobs

### ISSUE THREAD

**Issue by smuzaffar** [cms-sw/cmssw#37289]
Hi @cms-sw/all-l2 ,
  FYI, https://github.com/cms-sw/cms-bot/pull/1728 pull request changes the way we generate IB baseline for pull requests relvals comparison jobs. Idea is to stop generating baseline for all IBs and only generate when a PR needs it. First PR to test against an IB will trigger the generation of baseline. As both PR tests and baseline generation run in parallel so PR test results should not take any extra time.

Other improvements of this change are
- Generation of baseline for extra workflows tested by the PR e.g. `please test workflow 100.0,1003.0` will generate baseline for `100.0,1003.0` workflows too
- Added `high_stats` relval tests (https://github.com/cms-sw/cms-bot/issues/937) and automatic  generation of baseline for `high_stats` workflows. Currently this only runs workflow `35034.0` with 500 events
- Saves build and disk resources as baseline is only generated when used by PR tests. This means we will not generate a baseline for old release cycles where there is no PR to test ( e.g. 5.3.X, 8.0.X, 9.4.X  etc.).
- PR tests now do not wait for comparison results to be available before using it for tests. PR tests can start as soon as IB is available on cvmfs.

**Comment by smuzaffar** [comment]
type improvements

**Comment by tvami** [comment]
type performance-improvements
