### ISSUE TITLE
Duplication of PropagateToMuon class in MuonAnalysis/MuonAssociators and HLTriggerOffline/Muon

### ISSUE THREAD

**Issue by JanFSchulte** [cms-sw/cmssw#37290]
The code to propagate muon tracks from the IP to the second muon station is duplicated in two packages, see https://github.com/cms-sw/cmssw/blob/master/HLTriggerOffline/Muon/interface/PropagateToMuon.h and https://github.com/cms-sw/cmssw/blob/master/MuonAnalysis/MuonAssociators/interface/PropagateToMuon.h 

As they are diverging more and more, with the code in MuonAnalysis/MuonAssociators being developed while the one in HLTriggerOffline/Muon is not, this duplication needs to be resolved. 

This issue is mostly a To-Do for myself, as discussed in #37180

**Comment by perrotta** [comment]
[Here](https://github.com/cms-sw/cmssw/pull/37180#issuecomment-1073793899) is the link to the start of the discussion in the PR mentioned in the main description of this github issue

**Comment by makortel** [comment]
assign dqm, analysis

**Comment by JanFSchulte** [comment]
Addressed in #37348
