### ISSUE TITLE
crab does not automatically recognise output file if defined as cms.FinalPath

### ISSUE THREAD

**Issue by sarafiorendi** [cms-sw/cmssw#37301]
Hi,
I noticed that when defining an output module PoolOutputModule as cms.FinalPath, instead of the usual cms.EndPath, crab does not automatically recognise the output file to be transferred (and, if not explicitly set, does not consider it)

There is indeed this error message at submission time:
"
Warning: CRAB could not detect any output file in the CMSSW configuration nor was any explicitly specified in the CRAB configuration. Hence CRAB will not collect any output file from this task.
"

It was suggested that I create an issue here to make you aware of the issue
@silviodonato

**Comment by silviodonato** [comment]
Even though this problem is probably related to CRAB itself, let me tag @cms-sw/core-l2 @dpiparo

**Comment by makortel** [comment]
Adding @belforte

**Comment by belforte** [comment]
OK. let me review how CRAB obtains the list of output files and we can discuss if there's a robust way to get it from the pset which can avoid depending on "possibly changing" internals of the framework. If the latter, I'd rather deprecate than change.

**Comment by makortel** [comment]
Just to clarify, in this case the `cms.FinalPath` was added to the configuration language. The `cms.EndPath` stays, and is the preferred place for OutputModules for nearly all offline use cases.

**Comment by belforte** [comment]
yeah, that's what I guessed too. I am not happy about CRAB chasing after CMSSW forever, that's all.

**Comment by belforte** [comment]
thanks  @silviodonato   @Dr15Jones and @makortel  
Here's the code which CRAB uses, untouched since 8 years, and which I did not write, do not understand, am scared of breaking etc. etc.
https://github.com/dmwm/CRABClient/blob/37caaf2fbfdec47cecc7c9a5820f14e3252ca11e/src/python/CRABClient/JobType/CMSSWConfig.py#L183-L236
Can you suggest how it should be changed, or even better replaced with a call to a python function in CMSSW ? Thanks a lot !

P.S. since this is CRABClient, it is executed inside CMSSW environment, so with the env of the release the user choosed.

**Comment by makortel** [comment]
Thanks @belforte. In principle it would be straightforward to extend the fragment to support `FinalPath` (in a way that works also in earlier CMSSW releases) with something along
```diff
         #determine all modules on EndPaths
         modulesOnEndPaths = set()
         for m in process.endpaths_().itervalues():
             if len(pathsToRun)==0 or m.label() in pathsToRun:
                 for n in m.moduleNames():
                     modulesOnEndPaths.add(n)

+        # add modules in FinalPaths if available
+        if hasattr(process, "finalpaths_"):
+            for m in process.finalpaths_().itervalues():
+                if len(pathsToRun)==0 or m.label() in pathsToRun:
+                    for n in m.moduleNames():
+                        modulesOnEndPaths.add(n)
+
         outputModules = set()
```

Stefano, do you take it from here, or would you prefer e.g. me to make a PR to CRABClient? (in the latter case, how could I test it? the diff above is completely untested)

**Comment by belforte** [comment]
I can take from here. But I need a functional example PSET to test with. @sarafiorendi

**Comment by belforte** [comment]
@sarafiorendi preferred way is that you add the example to the CRABClient issue referred above, thanks

**Comment by belforte** [comment]
thanks @makortel , your fix works. I will create new CRAB Client release, you can close this.

**Comment by makortel** [comment]
Thanks @belforte!

**Comment by makortel** [comment]
assign core

**Comment by makortel** [comment]
+1
