### ISSUE TITLE
G4Exception in Run3Winter22 MC samples

### ISSUE THREAD

**Issue by mmusich** [cms-sw/cmssw#37373]
Dear all,
we've been observing a G4-related exception in the GS step for the creation of samples for Tracking POG studies within the Run3Winter22 MC campaign in `CMSSW_12_2_1`.
This has prevented the completion of about 1/3 of the needed statistics (see [PmP)](https://cms-pdmv.cern.ch/pmp/historical?r=TRK-Run3Winter22GS-00001,TRK-Run3Winter22GS-00004,TRK-Run3Winter22wmLHEGS-00002,TRK-Run3Winter22GS-00003,TRK-Run3Winter22wmLHEGS-00001))

The exception is:
```
-------- EEEE -------- G4Exception-END --------- EEEE -------

Fatal Exception (Exit code: 8016)
An exception of category 'EventCorruption' occurred while
[0] Processing Event run: 1 lumi: 180 event: 129350 stream: 3
[1] Running path 'RAWSIMoutput_step'
[2] Prefetching for module PoolOutputModule/'RAWSIMoutput'
[3] Calling method for module OscarMTProducer/'g4SimHits'
Exception Message:
SimG4CoreApplication exception in generation of event run: 1 lumi: 180 event: 129350 in stream 3

-------- EEEE ------- G4Exception-START -------- EEEE -------
*** G4Exception : GeomNav0003
issued by : G4Navigator::ComputeStep()
Stuck Track: potential geometry or navigation problem.
Track stuck, not moving for 25 steps.
Current phys volume: 'esalgo:SFFA_1'
- at position : (-6.979772838622108,330.9460160994352,-2991.913840829375)
in direction: (0.2907796754884473,-0.9553747709253678,-0.05202141291943463)
(local position: (6.979772838623029,330.9460160994354,29.91384082937475))
(local direction: (-0.2907796754884473,-0.9553747709253678,0.05202141291943444)).
Previous phys volume: 'esalgo:SF_1'

Likely geometry overlap - else navigation problem !
Track *abandoned* due to excessive number of Zero steps. Event aborted.


TrackID=37303 ParentID=37297 gamma; Ekin(MeV)=0.163873; time(ns)=13.639; status=0
position(mm): (-6.97977,330.946,-2991.91); direction: (0.29078,-0.955375,-0.0520214)
PhysicalVolume: esalgo:SFFA_1; material: materials:E_Aluminium
stepNumber=59; stepLength(mm)=1e-07; weight=1; creatorProcess: eBrem; modelID=-1

-------- EEEE -------- G4Exception-END --------- EEEE -------
```

Logs are available at [unified](https://cms-unified.web.cern.ch/cms-unified/showlog/?search=task_TRK-Run3Winter22GS-00001)

**Comment by mmusich** [comment]
@kskovpen @vmariani FYI

**Comment by mmusich** [comment]
assign simulation

**Comment by civanch** [comment]
This problem is known and there is fix/work around. Should it be backported to 12_2_X now or it is too late?

**Comment by mmusich** [comment]
> This problem is known and there is fix/work around. Should it be backported to 12_2_X now or it is too late?

I would let PPD decide.
@rappoccio FYI

**Comment by mmusich** [comment]
> This problem is known and there is fix/work around.

@civanch for my education, what is the concerned PR in master?

**Comment by qliphy** [comment]
In the meantime, @civanch  Please make a backport PR the sooner the better which may still be able to be included if the timeline is allowed.

**Comment by civanch** [comment]
Improved handling of low-energy tracks which stack in geometry. Main part of the fix is even in 12_2_X but recently we faced that the back trace is corrupted and  the track is not necessary killed by Geant4. The most recent updated was not propagated to previous releases.

**Comment by kmaeshima** [comment]
> > This problem is known and there is fix/work around. Should it be backported to 12_2_X now or it is too late?
> 
> I would let PPD decide. @rappoccio FYI

yes, please backport to 12_2_X asap.  We are planning to build it this week, with other fixes.   thanks.  Sal & Kaori

**Comment by civanch** [comment]
PRs #37375 and #37381 should significantly reduce number of fatal exceptions and provide more correct treatment of exceptions.

**Comment by civanch** [comment]
+1
