### ISSUE TITLE
GEN and SIM cannot split in Run-3 due to missing edmHepMCProduct_LHCTransport output from GEN

### ISSUE THREAD

**Issue by srimanob** [cms-sw/cmssw#37469]
For Run3, splitting between GEN and SIM will create a failure in SIM step due to the missing of
`edm::HepMCProduct                     "LHCTransport"              ""            "GEN"`
This product is transient as far as I see the GEN Eventcontent defined in 
https://github.com/cms-sw/cmssw/blob/master/GeneratorInterface/Configuration/python/GeneratorInterface_EventContent_cff.py#L13-L25
Is this expected behavior?

This product is used for PPS transport which activated in Run-3, defined in `g4SimHits`.

The setup of GEN and SIM separately is used in, e.g.
- Run-2 Ultra-Legacy with 10_6
- Private sample to validate simulation (I mainly use it to validate Phase2 with different geometry version)

This splitting works for Phase-2 because we do not use the `LHCTransport` as set in
https://github.com/cms-sw/cmssw/blob/master/SimG4Core/Application/python/g4SimHits_cfi.py#L678-L684

Should I add customization for `GeneratorInterfaceRAW` for Run-3? @civanch @mundim ?

(*)
```
----- Begin Fatal Exception 05-Apr-2022 16:55:37 CEST-----------------------
An exception of category 'ProductNotFound' occurred while
   [0] Processing  Event run: 1 lumi: 1 event: 1 stream: 6
   [1] Running path 'FEVTDEBUGHLToutput_step'
   [2] Prefetching for module PoolOutputModule/'FEVTDEBUGHLToutput'
   [3] Calling method for module OscarMTProducer/'g4SimHits'
Exception Message:
Principal::getByToken: Found zero products matching all criteria
Looking for type: edm::HepMCProduct
Looking for module label: LHCTransport
Looking for productInstanceName: 

   Additional Info:
      [a] If you wish to continue processing events after a ProductNotFound exception,
add "SkipEvent = cms.untracked.vstring('ProductNotFound')" to the "options" PSet in the configuration.

----- End Fatal Exception -------------------------------------------------
```

(**)
`cmsDriver.py TTbar_14TeV_TuneCP5_cfi  -s GEN -n 10 --conditions auto:phase1_2021_realistic --beamspot Run3RoundOptics25ns13TeVLowSigmaZ --datatier GEN --eventcontent FEVTDEBUG --geometry DB:Extended --era Run3 --python step1_TTbar_14TeV_GEN.py --no_exec --fileout file:step1.root  --nThreads 8`

`cmsDriver.py step2  -s SIM,DIGI:pdigi_valid,L1,DIGI2RAW,HLT:@relval2021 --conditions auto:phase1_2021_realistic --datatier GEN-SIM-DIGI-RAW -n -1 --eventcontent FEVTDEBUGHLT --geometry DB:Extended --era Run3 --python step2_SIMDIGIHLT_2021.py --no_exec --filein  file:step1.root  --fileout file:step2.root  --nThreads 8`

**Comment by srimanob** [comment]
assign simulation

**Comment by civanch** [comment]
+1
