### ISSUE TITLE
cpu features discovery on power ( and arm ) architecture 

### ISSUE THREAD

**Issue by spigad** [cms-sw/cmssw#37488]
While debugging the monitoring info for Marconi 100 jobs we realized that CPU features are not propagated back from the job itself. 

David pointed me to the code that does the proc/cpuinfo parsing. It cannot work on Power arch ( https://cmsdoc.cern.ch/~spiga/m100-proc) cause it is lookig for "model_name" but on ppc there is just "model".  We also checked arm on lxplus8-arm and it is still differnt. 

Finally, I suspect this is already known but as I've been pointed at this https://github.com/google/cpu_features I'm sharing it. Not sure if it could be of any interest.. 

Daniele

**Comment by makortel** [comment]
Taking a snippet from https://cmsdoc.cern.ch/~spiga/m100-proc
```
processor	: 0
cpu		: POWER9, altivec supported
clock		: 3800.000000MHz
revision	: 2.1 (pvr 004e 1201)
```

`lxplus8-arm` shows
```
processor       : 0
BogoMIPS        : 50.00
Features        : fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics fphp asimdhp cpuid asimdrdm lrcpc dcpop asimddp ssbs
CPU implementer : 0x41
CPU architecture: 8
CPU variant     : 0x3
CPU part        : 0xd0c
CPU revision    : 1
```
which is even more cryptic for this use case.

While searching about this topic I came across https://www.cnx-software.com/2018/02/14/human-readable-decoding-of-proc-cpuinfo-for-arm-processors/ that suggested `lscpu`. On quick try on a few x86 machines and `lxplus8-arm` that gave meaningful output (e.g. `Model name:          Neoverse-N1` on `lxplus8-arm`).

@spigad Would you be able to check if M100 has `lscpu`, and if it has, what is it's output?

By quick look https://github.com/google/cpu_features would also look feasible (and would not require running another program for the output). `lscpu` appears to be part of util-linux package. @smuzaffar would you have any preference between the two? Do we already require util-linux?

**Comment by makortel** [comment]
adding @dan131riley

**Comment by makortel** [comment]
@dan131riley @Dr15Jones Any thoughts?

**Comment by VinInn** [comment]
I use this csh script
``` touch /tmp/a.i ; c++ -v -march=native -s /tmp/a.i -o /dev/null | & grep cc1plus | sed 's/^.*march=//' | cut -f1 -d ' '; rm /tmp/a.i```

a bit compiler oriented I shall agree.


on  lxplus8-arm produces
```armv8.2-a+crypto+fp16+rcpc+dotprod```

do not have access to a power node

**Comment by smuzaffar** [comment]
on openlab olarm-202 , it produces `armv8.1-a+crypto` . On openlab power machine it complains 
```
c++: error: unrecognized command-line option '-march=native'; did you mean '-mcpu=native'?
```
and then using `-mcpu=native` , it produces `power8`.

**Comment by makortel** [comment]
@smuzaffar After discussion we decided to go with https://github.com/google/cpu_features library. Could you add an external for it?

@spigad I assume this improvement would need to be backported from 12_4_X. Which release was used in the Marconi 100 tests?

**Comment by spigad** [comment]
@makortel the latest RelVal  samples  were produced with CMSSW_11_2_0 .

**Comment by smuzaffar** [comment]
@makortel , https://github.com/cms-sw/cmsdist/pull/7781 adds `cpu_features. Looks like you need to include different headers fro x86, arm and ppc. Can you please try to add a simple unit test which can run on all archs?

**Comment by makortel** [comment]
@dan131riley Do you have preference?

**Comment by dan131riley** [comment]
Hi @smuzaffar lets get it into an IB and I’ll add unit tests

**Comment by makortel** [comment]
@spigad The improvement to CPU feature parsing with `cpu_features` library was done in #40050 that was merged in 12_6_X. Would this be sufficient for the needs, or are backports needed? (if yes, to which release cycles?)

**Comment by spigad** [comment]
@makortel I think that there is no neeed for backporting. THanks for taking care for the improvement.

**Comment by makortel** [comment]
Thanks @spigad, we can close the issue then.

**Comment by makortel** [comment]
+core

**Comment by makortel** [comment]
@cmsbuild, please close
