### ISSUE TITLE
L1REPACK:uGT is broken

### ISSUE THREAD

**Issue by silviodonato** [cms-sw/cmssw#37482]
Running in `CMSSW_12_4_0_pre2` on real data
```
hltGetConfiguration /dev/CMSSW_12_3_0/GRun/V61 \
    --globaltag auto:run3_hlt \
    --data \
    --unprescale \
    --eras Run2_2018 \
    --output minimal \
    --max-events 100 \
    --l1-emulator uGT --l1 L1Menu_Collisions2022_v1_0_0_xml \
    --customise HLTrigger/Configuration/customizeHLTforCMSSW.customiseFor2018Input,HLTrigger/Configuration/customizeHLTforPatatrack.customizeHLTforPatatrackTriplets \
    --input file:/eos/cms/store/data/Run2018D/EphemeralHLTPhysics2/RAW/v1/000/323/775/00000/17ADD12B-52E2-8C4C-B375-8AF943A24212.root \
    > hltData.py
```

which is equivalent adding
```
# run the Full L1T emulator, then repack the data into a new RAW collection, to be used by the HLT
from HLTrigger.Configuration.CustomConfigs import L1REPACK
process = L1REPACK(process,"uGT")
```
to the HLT configuration
crashes giving
```
----- Begin Fatal Exception 07-Apr-2022 10:30:43 CEST-----------------------
An exception of category 'ProductNotFound' occurred while
   [0] Processing  Event run: 323775 lumi: 138 event: 179365231 stream: 2
   [1] Running path 'HLTAnalyzerEndpath'
   [2] Prefetching for module L1TRawToDigi/'hltGtStage2Digis'
   [3] Prefetching for module RawDataCollectorByLabel/'rawDataCollector'
   [4] Calling method for module L1TDigiToRaw/'packGtStage2'
Exception Message:
Principal::getByToken: Found zero products matching all criteria
Looking for type: BXVector<l1t::MuonShower>
Looking for module label: simGmtShowerDigis
Looking for productInstanceName: 

   Additional Info:
      [a] If you wish to continue processing events after a ProductNotFound exception,
add "SkipEvent = cms.untracked.vstring('ProductNotFound')" to the "options" PSet in the configuration.

----- End Fatal Exception -------------------------------------------------
```

It is clear that `simGmtShowerDigis` does not exist in data.

@missirol do you remember what is the first release giving this error?

**Comment by silviodonato** [comment]
assign @cms-sw/l1-l2

**Comment by Martin-Grunewald** [comment]
```l1t::MuonShower```s are new L1T objects, not available in Run2 data. So I suppose one should run ```--l1-emulator Full``` rather than just ```uGT``` when processing Run2 data.

**Comment by dinyar** [comment]
Hi,

Yeah, I agreed with @Martin-Grunewald, using the full repack should fix this. That said, I *thought* I had successfully worked around the case when the shower digis aren't available, so I'll have a look. Can you let me know how urgent this is so I can schedule it appropriately?

Cheers,
Dinyar

**Comment by missirol** [comment]
Thanks, @dinyar .

> using the full repack should fix this.

Yes, it does (that's what we already suggest in the HLT twiki instructions, in case anybody is wondering).

The question is whether the `uGT`-only emulation is supported in recent releases. For example, I think the same failure occurs in 12_3_X if one tries to re-emulate the uGT on 2018 data with the 2018 menu [*].

> Can you let me know how urgent this is so I can schedule it appropriately?

I'll leave this to others. I would not call it urgent since we can use `Full`, but it does look to me like a fix is needed. The next 12_4_X pre-release is expected for Apr-19.

--------

[*]
```bash
# in CMSSW_12_3_X_2022-04-06-2300
hltGetConfiguration /dev/CMSSW_12_3_0/GRun/V55  --globaltag auto:run3_hlt --data --unprescale --eras Run2_2018 \
 --output minimal --max-events 100 --l1-emulator uGT --l1 L1Menu_Collisions2018_v2_1_0-d1_xml \
 --customise HLTrigger/Configuration/customizeHLTforCMSSW.customiseFor2018Input,HLTrigger/Configuration/customizeHLTforPatatrack.customizeHLTforPatatrackTriplets \
 --input /store/data/Run2018D/EphemeralHLTPhysics2/RAW/v1/000/323/775/00000/17ADD12B-52E2-8C4C-B375-8AF943A24212.root > hltData.py
cmsRun hltData.py &> hltData.log
```

**Comment by makortel** [comment]
assign l1

**Comment by missirol** [comment]
As a side comment: the 2018 example I gave in https://github.com/cms-sw/cmssw/issues/37482#issuecomment-1091677413 is not really a good one, as `hltGetConfiguration` itself does not support the L1T re-emulation for older eras ([here](https://github.com/cms-sw/cmssw/blob/70e484dafd1dc4f4179b66bb0581570686fe0add/HLTrigger/Configuration/python/CustomConfigs.py#L126), for recent releases, the `Run3` era is hard-coded for the `L1REPACK` sequences loaded via `hltGetConfiguration`). Nevertheless, I think the problem stands; one gets the same error running on 2021 data [*].

[*]
```bash
hltGetConfiguration /dev/CMSSW_12_3_0/GRun/V61 --globaltag auto:run3_hlt --data --unprescale --eras Run3 \
 --output minimal --max-events 100 --l1-emulator uGT --l1 L1Menu_Collisions2022_v1_0_0_xml \
 --input root://eoscms.cern.ch//eos/cms/store/group/dpg_trigger/comm_trigger/TriggerStudiesGroup/STORM/RAW/Commissioning2021_MinimumBias1_run346304/0949cd03-66a6-4034-a630-b9fef4dde3d2.root \
 > hltData.py
cmsRun hltData.py &> hltData.log
```

**Comment by Martin-Grunewald** [comment]
See above PRs fixing the issue: the uGT repacker uses the unchanged, unpacked digi collections of the low-level L1T objects, by overriding the corresponding inputtags for the unpacker and the packer. The newly added  input tag describing the new MuonShower collection had to be added for both.

**Comment by missirol** [comment]
assign hlt

(mainly for bookkeeping purposes)

**Comment by missirol** [comment]
+hlt

 - fixed in https://github.com/cms-sw/cmssw/pull/37502 and #37503 (fix is already available in 12_3_0)
