### ISSUE TITLE
std::filesystem::directory_iterator infinite loop

### ISSUE THREAD

**Issue by pmandrik** [cms-sw/cmssw#37484]
After the migration of DQM P5 machine to OS version CentOS 7.9 OS and kernel version (7.9.2009, 3.10.0-1160.53.1.el7) following issue has been observed: there is a probability for a job of a random DQM client to stuck during the execution. The freeze is not related to the executed client type and not triggered by end of the run condition. Version of CMSSW is 12_2_3_patch1. We found the stuck clients to be not able to exit following loop [0]:
```
directory_iterator dend;
for (directory_iterator di(runPath); di != dend; ++di) { 
  const std::string filename = di->path().filename().string();
  ...
```
the values of `filename` are repeated. The directory_iterator loop is used to detect new files to process in the folder. Files in the `runPath` could be removed or created during the execution of directory_iterator by another process. Also the `runPath` points to the mounted volume. At the moment we bypass this by checking for duplicates filenames withing the loop like:
```
  if( first_filename ==  di->path().filename().string() ) break;
```
Indeed, if directory_iterator is broken than the behavior is not defined and we can miss some files etc. 
Is there any other build-in way withing CMSSW for safety iteration over files in folder? Any other suggestions?

[0] https://github.com/cms-sw/cmssw/blob/6d2f66057131baacc2fcbdd203588c41c885b42c/DQMServices/StreamerIO/plugins/DQMFileIterator.cc#L235

**Comment by davidlange6** [comment]
this doesn't strike me as correct code:
```
      directory_iterator dend;
      for (directory_iterator di(runPath); di != dend; ++di) {
```

the intent is to iterate over all directories in runPath, is that correct?

**Comment by pmandrik** [comment]
Hello, @davidlange6 ,
yes, all entries in runPath. If the directory_iterator reports an error or is advanced past the last directory entry, it should become equal to the default-constructed iterator, this code has been running for years without any detected problems. Also, issue reproduced with modern one approach:
`for (auto const & di : std::filesystem::directory_iterator{ runPath }) {`

**Comment by davidlange6** [comment]
ok - indeed, that loop is correct as it is now that I read more the docs.

**Comment by makortel** [comment]
assign dqm

**Comment by makortel** [comment]
Looking [N4659](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2017/n4659.pdf) (i.e. last draft of C++17)
> **30.10 File systems**
> ...
> **30.10.2.3 File system race behavior**
> Behavior is undefined if calls to functions provided by this subclause introduce a file system race (30.10.4.5).
> ...
> **30.10.4.5 file system race**
> The condition that occurs when multiple threads, processes, or computers interleave access and modification of the same object within a file system.

(ok, cppreference mentions that also [here](https://en.cppreference.com/w/cpp/filesystem))

Isn't

> The directory_iterator loop is used to detect new files to process in the folder. Files in the runPath could be removed or created during the execution of directory_iterator by another process.

a file system race (many processes access or modify the directory)?

Quick search also pointed to https://stackoverflow.com/questions/66609601/why-abort-method-is-called-sometimes-when-i-iterate-over-directory-using-std

**Comment by dan131riley** [comment]
As the stackoverflow answers point out, the underlying libc `readdir()` has the same issues, so I guess you'll need some kind of inter-process mutex to do this safely, e.g. https://www.boost.org/doc/libs/1_78_0/doc/html/boost/interprocess/file_lock.html

**Comment by pmandrik** [comment]
Dear all, thank you for the comments and discussion, we fixed this changing the design of how files are cleared at DQM^2 side, tested at P5 playback machines, no changes to the CMSSW are required.
