### ISSUE TITLE
cmsLHEtoEOSManager.py python3 vs python2 in 8_0_X builder  

### ISSUE THREAD

**Issue by jordan-martins** [cms-sw/cmssw#37512]
Dear all,

We have an issue with our pLHE requests that use the CMSSW_8_0_31 when we try to create the pSet at the injection time from McM. The bulk of the error can be found in [1]. 

We are using ConfigBuilder.py from here:
/cvmfs/cms.cern.ch/slc6_amd64_gcc530/cms/cmssw/CMSSW_8_0_31/python/Configuration/Applications/ConfigBuilder.py

Line 420 does:
textOfFiles=os.popen('cmsLHEtoEOSManager.py -l '+article)

Which calls a shared-across-all-releases script here:
/cvmfs/cms.cern.ch/share/overrides/bin/cmsLHEtoEOSManager.py

That has:
#! /usr/bin/env python3

And CMSSW 8 does not seem to have python3 as we get an error:
/usr/bin/env: python3: No such file or directory

I tried using python 2 to manually run the script and it seems to work:
python /cvmfs/cms.cern.ch/share/overrides/bin/cmsLHEtoEOSManager.py -l 19738

Could you kindly provide the fix, please?

Thanks,
Jordan

[1]
`LHE input from article 19738

Error:
WARNING: In non-interactive mode release checks e.g. deprecated releases, production architectures are disabled.
/usr/bin/env: python3: No such file or directory
Traceback (most recent call last):
File "/cvmfs/[cms.cern.ch/slc6_amd64_gcc530/cms/cmssw/CMSSW_8_0_31/bin/slc6_amd64_gcc530/cmsDriver.py](http://cms.cern.ch/slc6_amd64_gcc530/cms/cmssw/CMSSW_8_0_31/bin/slc6_amd64_gcc530/cmsDriver.py)", line 55, in <module>
run()
File "/cvmfs/[cms.cern.ch/slc6_amd64_gcc530/cms/cmssw/CMSSW_8_0_31/bin/slc6_amd64_gcc530/cmsDriver.py](http://cms.cern.ch/slc6_amd64_gcc530/cms/cmssw/CMSSW_8_0_31/bin/slc6_amd64_gcc530/cmsDriver.py)", line 27, in run
configBuilder.prepare()
File "/cvmfs/[cms.cern.ch/slc6_amd64_gcc530/cms/cmssw/CMSSW_8_0_31/python/Configuration/Applications/ConfigBuilder.py](http://cms.cern.ch/slc6_amd64_gcc530/cms/cmssw/CMSSW_8_0_31/python/Configuration/Applications/ConfigBuilder.py)", line 2060, in prepare
self.addSource()
File "/cvmfs/[cms.cern.ch/slc6_amd64_gcc530/cms/cmssw/CMSSW_8_0_31/python/Configuration/Applications/ConfigBuilder.py](http://cms.cern.ch/slc6_amd64_gcc530/cms/cmssw/CMSSW_8_0_31/python/Configuration/Applications/ConfigBuilder.py)", line 425, in addSource
if len(line)<2:
UnboundLocalError: local variable 'line' referenced before assignment`

**Comment by davidlange6** [comment]
assign gen

(But this script is not part of cmssw I guess, so this may be the wrong place to file an issue against it)

**Comment by davidlange6** [comment]
assign generators

**Comment by smuzaffar** [comment]
A simple fix would be to fix https://github.com/cms-sw/cmssw/blob/master/GeneratorInterface/LHEInterface/scripts/cmsLHEtoEOSManager.py by adding [a]  and integrate it in cmssw 12.4.X. This will then automatically deploy under `/cvmfs/cms.cern.ch/share/overrides/bin/cmsLHEtoEOSManager.py` for all releases to use. We have done this for few other common tools used by all release e.g. https://github.com/cms-sw/cmssw-wm-tools/tree/master/bin

[a]
```
""":"

python_cmd="python"
python3 -c "from FWCore.PythonFramework.CmsRun import CmsRun" 2>/dev/null && python_cmd="python3"
exec ${python_cmd} $0 ${1+"$@"}

"""
```

**Comment by jordan-martins** [comment]
Hi @smuzaffar , thanks for this! However, we are still getting the same error while trying to submit the request. Could you kindly tell us if any further action is needed, please? I understood that since it is an x-shared file that it would need any further action and that updates would be ready.
Thanks,
Jordan
FYI @perrotta @qliphy

**Comment by smuzaffar** [comment]
ah this is because it is not yet deployed under /cvmfs/cms.cern.ch  . let me force install it.

**Comment by smuzaffar** [comment]
@jordan-martins update `cmsLHEtoEOSManager.py` is now available on /cvmfs

**Comment by jordan-martins** [comment]
thanks @smuzaffar ! this is now working properly. :)

**Comment by subehera** [comment]
Hi @smuzaffar, @bbilin,

It seems the pLHE step is done. I tried to validate locally the GS step but the validation job exited due to the segmentation violation in the GS step. Could you please kindly investigate the issue?

Thanks, Subash

**Comment by makortel** [comment]
@subehera Crashes in GEN-SIM are likely more for @cms-sw/generators-l2 or @cms-sw/simulation-l2 to investigate. Could you give the stack trace (or full log) of the crash and/or recipe to reproduce?

**Comment by subehera** [comment]
![Segfault](https://user-images.githubusercontent.com/43812112/167080967-1b2cca4f-9d3c-4b64-8041-b055c40c6c41.png)
Hi @makortel, pls take a look at the error message in the local test. 
As the pLHE step is already done I just ran the get-test command[1]for pLHE in lxplus and then I ran the get-test command for the GS step and you can see the cmsRun crash due to the seg-fault.

[1] : https://cms-pdmv.cern.ch/mcm/public/restapi/requests/get_test/HIN-pPb816Spring16pLHE-00016
[2] : https://cms-pdmv.cern.ch/mcm/public/restapi/requests/get_test/HIN-pPb816Spring16GS-00194

Kind regards, Subash

**Comment by makortel** [comment]
@subehera Could you give the full log? The screen shot above misses the relevant part of the stack trace.

**Comment by subehera** [comment]
hi @makortel, I have attached all the screenshots now. Pls have a look at it. Thank you
![ss1](https://user-images.githubusercontent.com/43812112/167244619-e2162a41-e7bd-4e80-8c57-11ac88895d82.png)
![ss2](https://user-images.githubusercontent.com/43812112/167244621-5178fc34-f6d8-4a48-a3e7-0243ad59fb79.png)
![ss3](https://user-images.githubusercontent.com/43812112/167244622-4f8239d7-af6f-40fd-a009-ddcadfdb8ca8.png)
![ss4](https://user-images.githubusercontent.com/43812112/167244626-ef2eb1aa-14a1-4248-abc7-5b2e755a9161.png)
!

**Comment by makortel** [comment]
Thanks @subehera (next time copy-pasted text would be easier to deal with than screen shots).

So the crash happens in `Pythia8::Rndm::flat()` with the call stack of
```
Pythia8::ProcessContainer::constructDecays()
Pythia8::ProcessLevel::nextLHAdec()
Pythia8::Pythia::next()
```
called from
https://github.com/cms-sw/cmssw/blob/38c1e9d73ae9029169a6043cf3b7bcbdc61e66f7/GeneratorInterface/Pythia8Interface/plugins/Pythia8Hadronizer.cc#L819

This looks like something for @cms-sw/generators-l2 to investigate

**Comment by menglu21** [comment]
Hi all, i had a test on [HIN-pPb816Spring16GS-00194](https://cms-pdmv.cern.ch/mcm/requests?prepid=HIN-pPb816Spring16GS-00194), i can reproduce the error, and i found after setting the nThreads explicitly the error is gone, i tried nThreads=1/4/8 and all work fine. I remember this could be set by manually in the past but now it seems not the case. 
btw, i haven't checked what happened when using default cmsdriver setup.
