### ISSUE TITLE
Phase-2 performance degradation due to printing of log messages

### ISSUE THREAD

**Issue by dpiparo** [cms-sw/cmssw#37527]
When looking at [this igprof report](http://cms-reco-profiling.web.cern.ch/cms-reco-profiling/cgi-bin/igprof-navigator/releases/CMSSW_12_4_0_pre1/35234.21/step3/cpu_endjob/385) it seems that because of the attempt of using [LogVerbatim to print GlobalPoints](https://github.com/cms-sw/cmssw/blob/6d2f66057131baacc2fcbdd203588c41c885b42c/RecoLocalMuon/GEMSegment/plugins/GE0SegAlgoRU.cc#L389) some 0.3% of the total reconstruction time is spent manipulating strings.

**Comment by makortel** [comment]
assign reconstruction

**Comment by jpata** [comment]
Looks like this has been similar since at least 12_0_0: http://cms-reco-profiling.web.cern.ch/cms-reco-profiling/cgi-bin/igprof-navigator/releases/CMSSW_12_0_0/34834.21/step3/cpu_endjob/436

It's a good moment to optimize it.

@jshlee @watson-ij @cms-sw/gem-dpg-l2 could you please take a look?

**Comment by jpata** [comment]
type performance-improvements

**Comment by watson-ij** [comment]
Hi @jpata, I made a PR which changes the LogVerbatim calls to LogDebug, which by my understanding should fix this issue  #37571. I wasn't sure how to check that the changes with the igprof tool though. If this is something I should check myself, do you have a twiki page I can follow to do this?

**Comment by jpata** [comment]
Thanks a lot for the quick action! If you open a PR, we can run the profiling directly via the bot.
LogDebug is compiled away, so I expect it will decrease the runtime (it cannot increase it by construction).

**Comment by clacaputo** [comment]
+reconstruction

- addressed in #37571 https://github.com/cms-sw/cmssw/pull/37571#issuecomment-1104930750
