### ISSUE TITLE
Potential simplification (and speedup) of Vavilov implementation

### ISSUE THREAD

**Issue by dpiparo** [cms-sw/cmssw#37529]
The construction of the [VVIObjF object](https://github.com/cms-sw/cmssw/blob/6d2f66057131baacc2fcbdd203588c41c885b42c/RecoLocalTracker/SiPixelRecHits/src/VVIObjF.cc#L41) is responsible for [2.5% of the Phase-2 reconstruction](http://cms-reco-profiling.web.cern.ch/cms-reco-profiling/cgi-bin/igprof-navigator/releases/CMSSW_12_4_0_pre1/35234.21/step3/cpu_endjob/109), despite the advanced performance optimizations implemented in the past.
However, it seems that in our code, a simplified version of the constructor could be invoked, with the [beta2 and mode parameters set to 1](https://github.com/cms-sw/cmssw/blob/6d2f66057131baacc2fcbdd203588c41c885b42c/RecoLocalTracker/SiPixelRecHits/src/SiPixelTemplateReco.cc#L1184).

**Comment by makortel** [comment]
type performance-improvements

**Comment by mmusich** [comment]
@dpiparo is  #37533 along the lines of what you had in mind?
