### ISSUE TITLE
Failed to find GEMEtaPartition for ID  Re -1 Ri 1 St 2 La 1 Ch 2 Et 1

### ISSUE THREAD

**Issue by silviodonato** [cms-sw/cmssw#37556]
After having migrated the HLT cosmics menu to 12_3_0 and synchronized with the offline menu, I'm getting many warnings such as
```
%MSG-e BadDigiInput:  GEMRecHitProducer:hltGemRecHits 13-Apr-2022 19:25:07 CEST  Run: 350294 Event: 1452857311
Failed to find GEMEtaPartition for ID  Re -1 Ri 1 St 2 La 1 Ch 2 Et 1 
%MSG
```
Please note that until now the GEM reconstruction was not used by the HLT at P5 during the cosmics.
The GEM reco was added to the HLT menu by https://its.cern.ch/jira/browse/CMSHLT-2200.

You can reproduce the error using from lxplus and running on a recent overnight run:
```
hltGetConfiguration adg:/cdaq/test/sdonato/2022Jan/CRAFT/HLT --online --no-output --data --process MYHLT --input file:/eos/cms/tier0/store/data/Commissioning2022/Cosmics/RAW/v1/000/350/294/00000/60b8c8f3-9314-472b-85ef-a5e9ca70a829.root --globaltag 123X_dataRun3_HLT_v7  > hlt.py
cmsRun hlt.py
```

@cms-sw/gem-dpg-l2

**Comment by silviodonato** [comment]
cc @cms-sw/alca-l2

**Comment by tvami** [comment]
> cc @cms-sw/alca-l2

To me it seems to be more a reco problem. But I contacted @hyunyong about it.

**Comment by tvami** [comment]
assign reconstruction

**Comment by jshlee** [comment]
hi @silviodonato, this is looking for ge21 which is not yet installed.
Currently, only a demonstrator chamber is installed, but it shouldn't be used for hlt. 
This chamber should be present in the geometry, but there shouldn't be any data for it for now since we don't unpack it.

@watson-ij can you look into this.

**Comment by jpata** [comment]
> To me it seems to be more a reco problem.

Wouldn't this be HLT then? Reco can't really test HLT stuff AFAIK.

**Comment by tvami** [comment]
> Wouldn't this be HLT then? Reco can't really test HLT stuff AFAIK.

Yes, you are right. Given that HLT reported it, I was a bit reluctant to `assign hlt` to the thread haha and it was about rechits...

**Comment by tvami** [comment]
unassign reconstruction

**Comment by Martin-Grunewald** [comment]
So we should switch off GEM completely?

**Comment by missirol** [comment]
Attn: @JanFSchulte @khaosmos93 (MUO-HLT)

**Comment by watson-ij** [comment]
@Martin-Grunewald in the config, the ge21Off should be set to True to skip unpacking the GE2/1 digis, this is something we added recently to account for the GE2/1 demonstrator.
Also, I would guess useDBEmap should be True, based on our current offline run3 setup:
https://github.com/cms-sw/cmssw/blob/master/EventFilter/GEMRawToDigi/python/muonGEMDigis_cfi.py

**Comment by Martin-Grunewald** [comment]
Thanks @watson-ij I can conform that these changes to the two bools get rid of the BadDigiInput messages!

**Comment by silviodonato** [comment]
As you can see in the PR description, I found this error at `13-Apr-2022 19:25:07` and you have already provided me a solution in time for the daily run meeting. Thanks a lot to everybody for the very prompt reaction!! :-)

**Comment by missirol** [comment]
+hlt

for the record
