### ISSUE TITLE
Problems after renaming parent folder of a CMSSW working area

### ISSUE THREAD

**Issue by ferencek** [cms-sw/cmssw#37567]
After renaming the parent folder of a CMSSW working area, I ran the project rename command as can be seen below
```
[ferencek@titan src]$ scram b -j 4
**** ERROR: You have moved/renamed this project area "/users/ferencek/PixelOffline/DuplicatePixels/CMSSW_12_4_0_pre2" from "/users/ferencek/PixelOffline/AddDuplicatePixels/CMSSW_12_4_0_pre2"
config/SCRAM/GMake/Makefile.rules:1413: *** Please first run \"scramv1 b ProjectRename\".  Stop.
gmake: *** [There are compilation/build errors. Please see the detail log above.] Error 2
[ferencek@titan src]$ scramv1 b ProjectRename
Done: ProjectRename
```
However, later on when I wanted to check out an additional package, I encountered the following error
```
[ferencek@titan src]$ git cms-addpkg DataFormats/SiPixelCluster
mkdir: cannot create directory '/users/ferencek/PixelOffline/AddDuplicatePixels/CMSSW_12_4_0_pre2/src': No such file or directory
```
which I would not expect to see after a successful project rename.

There was another possibly related issue with code format checks in the context of https://github.com/cms-sw/cmssw/pull/37559 which perhaps failed because of renaming the project.

**Comment by makortel** [comment]
assign core

**Comment by smuzaffar** [comment]
@ferencek , have you run `cmsenv` after in the new directory? `git-cms-addpkg` uses `$CMSSW_BASE/src`  to check out package, so if you have not reset the env in new area then it will try to checkout package in old path

**Comment by ferencek** [comment]
> @ferencek , have you run `cmsenv` in the new directory? `git-cms-addpkg` uses `$CMSSW_BASE/src` to check out package, so if you have not reset the env in new area then it will try to checkout package in old path

Hmm, I honestly cannot recall now but I managed to reproduce the problem by renaming the parent folder and not calling `cmsenv` afterwards so it looks like I called `cmsenv` only once, before renaming the folder. Thanks for the pointer in the right direction and sorry for the noise.
