### ISSUE TITLE
TestDQMOnlineClient-l1tstage2_dqm_sourceclient test fails

### ISSUE THREAD

**Issue by makortel** [cms-sw/cmssw#37584]
The `TestDQMOnlineClient-l1tstage2_dqm_sourceclient` test fails in CMSSW_12_4_X_2022-04-15-1100
```
----- Begin Fatal Exception 15-Apr-2022 15:47:14 CEST-----------------------
An exception of category 'ProductNotFound' occurred while
   [0] Processing  Event run: 344518 lumi: 2 event: 31571 stream: 0
   [1] Running path 'l1tMonitorPath'
   [2] Calling method for module L1TStage2RegionalShower/'l1tStage2RegionalShower'
Exception Message:
Principal::getByToken: Found zero products matching all criteria
Looking for type: MuonDigiCollection<CSCDetId,CSCShowerDigi>
Looking for module label: muonCSCDigis
Looking for productInstanceName: MuonCSCShowerDigi

   Additional Info:
      [a] If you wish to continue processing events after a ProductNotFound exception,
add "SkipEvent = cms.untracked.vstring('ProductNotFound')" to the "options" PSet in the configuration.

----- End Fatal Exception -------------------------------------------------
```
https://cmssdt.cern.ch/SDT/cgi-bin/logreader/slc7_amd64_gcc10/CMSSW_12_4_X_2022-04-15-1100/unitTestLogs/DQM/Integration#/

**Comment by makortel** [comment]
assign dqm

**Comment by makortel** [comment]
https://github.com/cms-sw/cmssw/pull/37544 looks like potential culprit

**Comment by makortel** [comment]
assign l1

**Comment by qliphy** [comment]
@zuoxunwu  As this issue seems to be related to your recent PR: https://github.com/cms-sw/cmssw/pull/37544   Would you please have a look?

**Comment by missirol** [comment]
If it helps, removing/commenting [this line](https://github.com/cms-sw/cmssw/blob/c84c56e0057e517b714e65c0306377bacc82c0eb/DQM/Integration/python/clients/l1tstage2_dqm_sourceclient-live_cfg.py#L58) will make the unit test pass. I don't know if that is the correct fix, though.

**Comment by qliphy** [comment]
> If it helps, removing/commenting [this line](https://github.com/cms-sw/cmssw/blob/c84c56e0057e517b714e65c0306377bacc82c0eb/DQM/Integration/python/clients/l1tstage2_dqm_sourceclient-live_cfg.py#L58) will make the unit test pass. I don't know if that is the correct fix, though.

@zuoxunwu @cms-sw/csc-dpg-l2 @cms-sw/l1-l2 would you please have a look?

**Comment by zuoxunwu** [comment]
Sorry for the late turn-around. Just got time to look at this.
The MuonCSCShowerDigi are not available in data because the firmware is not yet implemented. I thought it would recreate an empty collection and do not break the sequence. It seems not. 
I will make a fix shortly.

**Comment by zuoxunwu** [comment]
> If it helps, removing/commenting [this line](https://github.com/cms-sw/cmssw/blob/c84c56e0057e517b714e65c0306377bacc82c0eb/DQM/Integration/python/clients/l1tstage2_dqm_sourceclient-live_cfg.py#L58) will make the unit test pass. I don't know if that is the correct fix, though.

Indeed this is a correct (not sure yet if it is preferred) fix. 
There is an empty MuonCSCShowerDigi collection in muonCSCDigis. And one only need to call the unpacker to make it work.
Another (possibly preferred) way to fix it is to move the CSCShower DQM module from the L1T sequence to the CSC sequence. I will discuss this with relevant L1T and DQM experts and make a decision.

**Comment by zuoxunwu** [comment]
Hi @qliphy ,
I see. I have made a [PR for the temporary fix](https://github.com/cms-sw/cmssw/pull/37634). Should be good for the release.

After a discussion with L1T SW experts, I think there are 3 options:
1. Enable CSC unpacker in L1T DQM sequence, as in the temporary fix. 
Pros: Easy to implement. CSC shower plots and EMTF shower plots stays side-by-side in DQM, better comparison for users.
Cons: Not sure if there are CMSSW or DQM rules/preferences against unpacking CSC digis in L1T DQM sequence.

2. Call CSC unpacker in situ in the shower DQM module, like what is done [here](https://github.com/cms-sw/cmssw/blob/06c31021863c900811092cdd8f21e02d6c9940c3/DQM/L1TMonitor/python/L1TCSCTPG_cff.py#L48)
Pros: same as option 1.
Cons: same as option 1.

3. Move the CSC shower DQM module from L1T DQM to CSC DQM.
Pros: Good with CMSSW rules/preferences.
Cons: CSC shower plots and EMTF shower plots in different folders, a little harder for comparison. 
Remark: In this case would the CSC shower DQM module be maintained by CSC DQM experts and not EMTF DQM experts in the future? 

@eyigitba @epalencia @cecilecaillol  @vukasinmilosevic for more comments.

**Comment by cecilecaillol** [comment]
The fix to this issue has been merged: https://github.com/cms-sw/cmssw/pull/37634

**Comment by cecilecaillol** [comment]
+l1

**Comment by jfernan2** [comment]
+1
