### ISSUE TITLE
autoSKIM for Run-3

### ISSUE THREAD

**Issue by srimanob** [cms-sw/cmssw#37656]
I just open a PR to update a monopole physics skim for Run-3,
https://github.com/cms-sw/cmssw/pull/37655

However, I wonder if we should clone existing `autoSkim` to `autoSkimRunII` as we did for Run-1. And then we start review `autoSkim` when Run-3 dataset names available.

**Comment by makortel** [comment]
assign pdmv

**Comment by kskovpen** [comment]
@srimanob I think it is a good idea to move the existing scheme to RunII collection and start building up the Run3 alternative.
