### ISSUE TITLE
ProductNotFound exception in AlcaPCCIntegrator in workflow 1001.2

### ISSUE THREAD

**Issue by makortel** [cms-sw/cmssw#37685]
Workflow 1001.2 step 2 is failing in CMSSW_12_4_X_2022-04-26-1100 with
```
----- Begin Fatal Exception 26-Apr-2022 13:15:01 CEST-----------------------
An exception of category 'ProductNotFound' occurred while
   [0] Processing  Event run: 305064 lumi: 2 event: 1783800 stream: 0
   [1] Running path 'pathALCARECOAlCaPCCRandom'
   [2] Calling method for module AlcaPCCIntegrator/'alcaPCCIntegratorRandom'
Exception Message:
Principal::getByToken: Found zero products matching all criteria
Looking for type: reco::PixelClusterCountsInEvent
Looking for module label: hltAlcaPixelClusterCounts
Looking for productInstanceName: alcaPCCEvent

   Additional Info:
      [a] If you wish to continue processing events after a ProductNotFound exception,
add "SkipEvent = cms.untracked.vstring('ProductNotFound')" to the "options" PSet in the configuration.

----- End Fatal Exception -------------------------------------------------
```
https://cmssdt.cern.ch/SDT/cgi-bin/logreader/slc7_amd64_gcc10/CMSSW_12_4_X_2022-04-26-1100/pyRelValMatrixLogs/run/1001.2_RunZeroBias2017F+RunZeroBias2017F+TIER0EXPRUN2+ALCAEXPRUN2+ALCAHARVDSIPIXELCAL+ALCAHARVDSIPIXELCALLA/step2_RunZeroBias2017F+RunZeroBias2017F+TIER0EXPRUN2+ALCAEXPRUN2+ALCAHARVDSIPIXELCAL+ALCAHARVDSIPIXELCALLA.log#/

**Comment by makortel** [comment]
assign alca

**Comment by tvami** [comment]
> #37590 looks like a potential candidate for the cause

Yes, but I think the solution is not really to modify the content of https://github.com/cms-sw/cmssw/pull/37590
but to modify the wf 1001.2 

Right now it uses 2017 data
https://github.com/cms-sw/cmssw/blob/master/Configuration/PyReleaseValidation/python/relval_production.py#L15
but I think that should be moved to use the 2021 data.

**Comment by tvami** [comment]
assign pdmv

**Comment by tvami** [comment]
Surprisingly the test in 12_3_X passed for this wf:
https://github.com/cms-sw/cmssw/pull/37671#issuecomment-1110110702

is this somehow connected to multi-threading?

**Comment by mmusich** [comment]
Sorry what's the plan to fix this?
If the PCC workflow is not appropriate for 2017 can't it just be removed? 
Or even better, why is it not customized for different inputs as a function of the era?

**Comment by tvami** [comment]
In the end I resolved it inside the AlCa jurisdiction by not adding this stream to the allForExpress

**Comment by mmusich** [comment]
@tvami I think https://github.com/cms-sw/cmssw/pull/37712 might be also a viable solution, allowing you to remain with one list for all eras.

**Comment by tvami** [comment]
Yes, that's nice, thanks Marco!

**Comment by tvami** [comment]
unassing pdmv

**Comment by tvami** [comment]
+alca 
 * for the record
