### ISSUE TITLE
AMPT generator failing on ARM processor

### ISSUE THREAD

**Issue by Dr15Jones** [cms-sw/cmssw#37799]
The workflow 575.0 is failing under el8_aarch64_gcc10

https://cmssdt.cern.ch/SDT/cgi-bin/logreader/el8_aarch64_gcc10/CMSSW_12_4_X_2022-05-03-2300/pyRelValMatrixLogs/run/575.0_AMPT_PPb_5020GeV_MinimumBias_ExtGen+AMPT_PPb_5020GeV_MinimumBias_ExtGen+HARVESTGEN/step1_AMPT_PPb_5020GeV_MinimumBias_ExtGen+AMPT_PPb_5020GeV_MinimumBias_ExtGen+HARVESTGEN.log#/

The generator is being run under the ExternalGenerator and we are seeing a time out that appears to be because FORTRAN is calling `STOP`.

**Comment by Dr15Jones** [comment]
The log messages are
```
%MSG-i ThreadStreamSetup:  (NoModuleName) 04-May-2022 12:11:00 CEST pre-events
setting # threads 4
setting # streams 4
%MSG
%MSG-s ExternalProcess:  ExternalGeneratorFilter:generator@beginStream  04-May-2022 12:11:12 CEST pre-events
2 starting external process 

%MSG
%MSG-s ExternalProcess:  ExternalGeneratorFilter:generator@beginStream  04-May-2022 12:11:12 CEST pre-events
1 starting external process 

%MSG
%MSG-s ExternalProcess:  ExternalGeneratorFilter:generator@beginStream  04-May-2022 12:11:12 CEST pre-events
0 starting external process 

%MSG
%MSG-s ExternalProcess:  ExternalGeneratorFilter:generator@beginStream  04-May-2022 12:11:12 CEST BeforeEvents
3 starting external process 

%MSG
1099153_3 process: initializing 
1099153_1 process: initializing 
1099153_2 process: initializing 
1099153_0 process: initializing 
...
early exit called: unlock
 
           ##################################################
           #      AMPT (A Multi-Phase Transport) model      #
           #          Version 1.26t5 (Default)              #
           #                4/06/2015                       #
           ##################################################
            


          **************************************************
          *     |      |       _______      /  ------/     *
          *   ----- ------     |_____|     /_/     /       *
          *    |||    /        |_____|      /    / |       *
          *    /| |  /_/       /_______    /_  /    |      *
          *   / |     / /     /  /  / |        -------     *
          *     |    / /|       /  /  |     /     |        *
          *     |   / /  |     /  /  _|    /   -------     *
          *                                                *
          **************************************************
                                HIJING                      
                 Heavy Ion Jet INteraction Generator        
                                  by                        
                      X. N. Wang  and  M. Gyulassy           
                       Lawrence Berkeley Laboratory           


 P�20wrong or unavailable targ name
----- Begin Fatal Exception 04-May-2022 12:16:17 CEST-----------------------
An exception of category 'ExternalFailed' occurred while
   [0] Processing global begin LuminosityBlock run: 1 luminosityBlock: 1
   [1] Calling method for module ExternalGeneratorFilter/'generator'
Exception Message:
failed waiting for external process. Timed out after 300 seconds.
----- End Fatal Exception -------------------------------------------------
```

The telling message was
```
 P�20wrong or unavailable targ name
```
searching for that message in CMSSW found this
https://github.com/cms-sw/cmssw/blob/ed9e032abc305dfe67bcdf6afa590189e5555ee8/GeneratorInterface/AMPTInterface/src/hijing1.383_ampt.f#L1932-L1951

Now FORTRAN uses a different way to 'terminate' strings than C++. I'm guessing that the code was trying to pass `P` to FORTRAN but the calling conventions on ARM might be different than x86 and the adaptor code isn't working properly.

**Comment by Dr15Jones** [comment]
assign generator

**Comment by Dr15Jones** [comment]
In fact, TARG is defined as a `CHARACTER` with exactly 4 chars
https://github.com/cms-sw/cmssw/blob/ed9e032abc305dfe67bcdf6afa590189e5555ee8/GeneratorInterface/AMPTInterface/src/hijing1.383_ampt.f#L1882-L1883

Based on the printout, it looks like the last 3 chars in the variable were not properly set to null.

**Comment by Dr15Jones** [comment]
So here appears to be the call, and it is not passing strings properly to fortran

https://github.com/cms-sw/cmssw/blob/ed9e032abc305dfe67bcdf6afa590189e5555ee8/GeneratorInterface/HijingInterface/src/HijingHadronizer.cc#L242-L249

**Comment by smuzaffar** [comment]
@Dr15Jones , coult it be that `targ` https://github.com/cms-sw/cmssw/blob/6d2f66057131baacc2fcbdd203588c41c885b42c/Configuration/Generator/python/Hijing_PPb_MinimumBias_cfi.py#L6 is more than 4 chars long here?

**Comment by Dr15Jones** [comment]
@smuzaffar that could be as well. I'd say the length should be enforced on the C++ side, not done on the python side.

**Comment by Dr15Jones** [comment]
assign generator

**Comment by makortel** [comment]
assign generators
