### ISSUE TITLE
Support alpaka-based libraries, plug-ins and executables in CMSSW 

### ISSUE THREAD

**Issue by fwyzard** [cms-sw/cmssw#37790]
This issue will try to collect, describe and keep track of all changes to the configuration, externals, build rules, _etc._ needed to support alpaka-based libraries, plug-ins and executables in CMSSW

The initial list is likely incomplete and not fully specified; we expect it to evolve and become more clear as we make progress and gain further experience.

### General issues
  - [ ] build multiple libraries out of a single package: scram supports building multiple plug-ins from a single directory with the `<library file="..." name="...">` syntax; we would need a similar approach also for libraries and data formats;
    - [ ] build a single `.cc` file for multiple backends can be done
        - including the same file multiple times
        - using the   `<library file="..." name="...">` syntax
        - automatically, for files in a specific directory, _e.g._ `Subsystem/Package/plugins/alpaka/*.cc` or `Subsystem/Package/src/alpaka/*.cc`
    - [ ] if done automatically
        - how do we specify if a file should be built only for a subset of the available back-ends ?
        - how do we specify what flags to use ?
    - [ ] separate files to be built with the host compiler (_e.g._ `alpaka/*.cc` or `alpaka/*.host.cc`) and the device compiler (_e.g._ `alpaka/*.acc` or `alpaka/*.dev.cc`)

  - [ ] define the dependencies between executables, plugins and other libraries on alpaka-based libraries
    - here is a possible dependency matrix:
        ↓ this depends on → | standard library | alpaka-based library<br/>(single backend) | alpaka-based library<br/>(all backends)
        -- | -- | -- | --
        standard library | ✔️ default | 🈸 explicit | 🈸 explicit
        alpaka-based library<br/>(single backend) | ✔️ default | ✔️ default | ❌ no
        standard plugin | ✔️ default | 🈸 explicit | 🈸 explicit
        alpaka-based plugin<br/>(single backend) | ✔️ default | ✔️ default | ❌ no
        standard executable | ✔️ default | 🈸 explicit | 🈸 explicit
        alpaka-based executable<br/>(single backend) | ✔️ default | ✔️ default | ❌ no

    - a non alpaka-based library, plug-in, or executable by default will ignore alpaka-based libraries, _e.g._
      `<use name="Subsystem/Package"/>`
      will only depend on and link to the standard library built from `Subsystem/Package/src/*.cc`;
    - a non alpaka-based library, plug-in, or executable _could_ declare a dependency on _all_ alpaka-based libraries, _e.g._
      `<use name="Subsystem/Package" backend="*"/>`
      will depend on the libraries for all back-ends built from `Subsystem/Package/src/alpaka/*.cc`;
    - I don't have a use case for it, but in principle we could also let a library use only one or more specific back-ends ? _e.g._
      `<use name="Subsystem/Package" backend="cuda"/>`
      will depend on the libraries for the "cuda" back-end built from `Subsystem/Package/src/alpaka/*.cc`;
    - an alpaka-based library, plugin, or executable by default will depend on both the default library, and the alpaka-based library for the same back-end as itself, _e.g._
      `<use name="Subsystem/Package"/>`
      will depend on and link to the standard library built from `Subsystem/Package/src/*.cc`, and the alpaka-based library built from `Subsystem/Package/src/alpaka/*.cc` for the same back-end as the it is being compiled for itself.

  - [ ] allow back-end specific dependencies
    - an alpaka-based  library, plugin, or executable may have a dependency on an other package or external only for back-ends;
    - for example, `AlpakaService` may depend on `CUDAService` only when it is being built for the CUDA backend, and it may depend on some `ROCmService` when being built for the HIP/ROCm backend.

  - [ ] some modules may be built only for a subset of the back-ends
    - for example, a module responsible for copying data from a "device" to the host CPU would not make sense for the CPU serial backend, because the "host" and "device" use the same memory space
    - in #37716 this is achieved by wrapping the whole source in an `#ifdef`, but maybe there is a better way ?
    - the special case of building a module only for the CPU serial backend can be handled by moving the module out of the `.../alpaka/` directory into the traditional `src` or `plugin` directories 

### Back-end specific issues
  - [ ] build `.cc` files with `nvcc` in "CUDA mode": as all alpaka-based source files use the standard `.cc` extension, we need a way to tell scram to build `.cc` files in "CUDA mode", for example with `nvcc -x cu` and using all the flags normally used by CUDA files.
  - [ ] build `.cc` files with `hipcc` in "ROCm mode": as all alpaka-based source files use the standard `.cc` extension, we need a way to tell scram to build `.cc` files in "ROCm mode", for example with `hipcc` and using all the flags normally used by ROCm files.

**Comment by fwyzard** [comment]
assign core

**Comment by fwyzard** [comment]
assign heterogeneous

**Comment by fwyzard** [comment]
@smuzaffar , do you have any idea how SCRAM could be extended to support these two points ?

> * build `.cc` files with `nvcc` in "CUDA mode": as all alpaka-based source files use the standard `.cc` extension, we need a way to tell scram to build `.cc` files in "CUDA mode", for example with `nvcc -x cu` and using all the flags normally used by CUDA files.
> * build `.cc` files with `hipcc` in "ROCm mode": as all alpaka-based source files use the standard `.cc` extension, we need a way to tell scram to build `.cc` files in "ROCm mode", for example with `hipcc` and using all the flags normally used by ROCm files.

So far we have relied on the file extension to choose between the default C++ compilation (for `.cc` files) or the CUDA compilation (for `.cu` files).
With Alpaka (and also with native HIP/ROCm) that doesn't work, because they don't use different file extensions for device code.

Here are some ideas, none of which seems particularly good :-(
  - Specify the compilation type in the `BuildFile.xml`, adding it to the `library` tag:
    ```
    <library file="..." name="..." type="...">`
        ...
    </library>
    ```
    The problem is that we do want to mix files compiled by the host compiler (g++) and the device compiler (`nvcc`/`hipcc`) in the same library.

  - Specify the compilation type in the `BuildFile.xml`, adding the flag for each source file:
    ```
    <library file="..." name="...">
        <file name="..." type="..."/>
        <file name="..." type="..."/>
        ...
    </library>
    ```
    The problem is that this will require a lot of work to introduce and maintain, as files are added, renamed or removed.

  - Define arbitrary file types, like `*.cuda.cc`, `*.rocm.cc`, _etc._.
    It doesn't seem very elegant, but I don't see any technical downside ?

**Comment by smuzaffar** [comment]
@fwyzard , one can add `<flags COMPILER="compiler"/>`  in BuildFile.xml which allows scram to use different compiler . Only requirement is that one should have `compiler-cxxcompiler.xml` tools available. We can make use of this feature and add `(cuda|hipcc)-cxxcompiler.xml` tools.

By the way, are we talking about same set of files to be build twice (once with hipcc and once with nvcc) ? If yes then we need to  extent scram support for that e.g. 
```
<library name="..." file="*.cc">
  <flag ALPAKA_MODES="cuda rocm">
</library/>
```

OR 
```
<library name="..." file="*.cc">
  <flag ALPAKA_MODE="1">
</library/>

and
config/BuildFile.xml
<flags ALPAKA_MODES="cuda rocm"/>
```

**Comment by fwyzard** [comment]
> @fwyzard , one can add `<flags COMPILER="compiler"/>` in BuildFile.xml which allows scram to use different compiler . Only requirement is that one should have `compiler-cxxcompiler.xml` tools available. We can make use of this feature and add `(cuda|hipcc)-cxxcompiler.xml` tools.

Mhm, I think there would be two problems with this approach:
1. we want to mix the compiler the we use within the same library.
    For example, in a plug-in we can have:
      - `Algorithm.h`
      - `Algorithm.cu` (or `Algorithm.cuda.cc`)
      - `Producer.cc`
    ```
    where we want to build `Algorithm.cu` with `nvcc -x cu`, but `Producer.cc` with the standard `g++`.
2. for CUDA builds we have the extra link step(s) for device code, and I don't know if the `COMPILER` flag supports that ?


> By the way, are we talking about same set of files to be build twice (once with hipcc and once with nvcc) ?

For prototyping, the approach I'm using in https://github.com/cms-sw/cmssw/pull/37716 is to do this multiple compilation "by hand".
But yes, eventually we need a scram-based solution for this.

> If yes then we need to extend scram support for that e.g.
> 
> ```
> <library name="..." file="*.cc">
>   <flag ALPAKA_MODES="cuda rocm">
> </library/>
> ```
> 
> OR
> 
> ```
> <library name="..." file="*.cc">
>   <flag ALPAKA_MODE="1">
> </library/>
> 
> and
> config/BuildFile.xml
> <flags ALPAKA_MODES="cuda rocm"/>
> ```

Both approaches look good.

Some random ideas ...

After some initial brainstorming with Matti, we think it would be best to keep the files to be compiled multiple times with different alpaka flags in a subdirectory like `src/alpaka` and `plugins/alpaka`.
Can we do something like
```xml
<library name="..." file="alpaka/*.cc">
</library>
```
?
Or would it be better to put the `BuildFile.xml` directly in the subdirectory, like  `src/alpaka/BuildFile.xml` and `plugins/alpaka/BuildFile.xml` ?


We may need to make the list of modes conditional on some other flags, like `<iftool name="cuda-gcc-support">` or `<architecture ...>`.
Can we use those in `config/BuildFile.xml` ?
Can we split the flag like for the `CXXFLAGS` and let scram put it back together, like
```xml
<flags ALPAKA_MODES="serial"/>
<iftool name="cuda-gcc-support">
    <flags ALPAKA_MODES="cuda"/>
</iftool>
<architecture name="amd64">
    <flags ALPAKA_MODES="rocm"/>
</iftool>
```
?


As for the case of native CUDA and ROCm, we think it may be better to compile some files with the host compiler, and some with the device compiler (though I'm not 100% sure, and I haven't done it neither in `pixeltrack-standalone` nor in https://github.com/cms-sw/cmssw/pull/37716, yet).
So we could have
```c
src/*.cc               # compiled by g++, once 
src/alpaka/*.cc        # compiled by g++, N times, one for each alpaka backend
src/alpaka/*.dev.cc    #compiled by various device compilers, one for each alpaka backend
```

**Comment by smuzaffar** [comment]
correct `<flags COMPILER="compiler"/>` is not suitable for this use case. I think file types e.g `*.cuda.cc, *.rocm.cc` are simple to maintain for both developers and build system

> We may need to make the list of modes conditional on some other flags, like <iftool name="cuda-gcc-support"> or <architecture ...>.
> Can we use those in config/BuildFile.xml ?

Yes

> Can we split the flag like for the CXXFLAGS and let scram put it back together, like

Yes

I would suggest to not add `<library name="..." file="alpaka/*.cc"></library>`  type fragments in `Package/Buildfile.xml` but use `<flags ALPAKA_MODES/BACKEND="values|1"/>` to let scram automatically build multiple shared libs out of `Package/src` tree   e.g `libPackage.so and one for each libPackage_<backend>.so`. 

If I understand correctly,
- object files from src/*.cc  should be used to build libPackage.so
- object files from src/alpaka/*.cc + src/alpaka/*.dev.cc should be used to to generate share lib for each backend
is this correct?

For `Package/{plugins,bin,test}` directories `<library name="..." file="alpaka/*.cc"></library>` should work. e.g.
```
<library name="PluginName" file="*.cc">
</library>
<library name="PluginName" file="alpaka/*.cc">
  <flags ALPAKA_MODES/BACKEND="values|1"/>
</library>

OR
<library name="PluginName" file="*.cc alpaka/*.cc">
  <flags ALPAKA_MODES/BACKEND="values|1"/>
</library>
```
and let scram build `pluginPluginName.so` (using cc files which are not under alpaka dir) and `pluginPluginName_<backend>.so` for each selected backend (using alpaka/*.cc files)

**Comment by fwyzard** [comment]
> If I understand correctly,
>   * object files from src/*.cc  should be used to build libPackage.so
>   * object files from src/alpaka/\*.cc + src/alpaka/\*.dev.cc should be used to to generate share lib for each backend
>
> is this correct?

Yes, correct:
  - files from `Package/src/*.cc` are used to build `libPackage.so`
  - files from `Package/src/alpaka/*.cc` and `Package/src/alpaka/*.dev.cc` are used to build `libPackageCpuSerial.so`, `libPackageCudaAsync.so`, `libPackageHipAsync.so`, _etc_

and `libPackageCpuSerial.so`, `libPackageCudaAsync.so`, `libPackageHipAsync.so`, _etc._ would automatically depend on and link with `libPackage.so`

**Comment by fwyzard** [comment]
I've edited the issue to add few points discussed during the Core Software meeting:
  - building modules for a subset of the back-ends (even just the host)
  - allow back-end specific dependencies

**Comment by VinInn** [comment]
Just a side note: although the backend is "rocm" the interface is "hip" (that in principle can be compiled for cuda backend as well). In general hip files have extension ".hip.cc" (even ".hip.h").
btw clang (and even gcc) can natively compile cuda and hip code if instructed to do so.

**Comment by fwyzard** [comment]
> Just a side note: although the backend is "rocm" the interface is "hip" (that in principle can be compiled for cuda backend as well).

Thanks for the clarification.

And since we are proposing to use the extension to define the _backend_ to compile for (_i.e._ CUDA or ROCm) I think `*.rocm.cc` is more appropriate here.

However we could certainly introduce support to generic HIP files using the same approach as we plan for Alpaka: `*.hip.cc` files would then be built for both CUDA _and_ ROCm backends. If there is interest, we can open a separate issue to track this ?

**Comment by fwyzard** [comment]
> btw clang (and even gcc) can natively compile cuda and hip code if instructed to do so.

Well, `hipcc` is just a wrapper around `clang` anyway.

And at some point we should definitely revive the effort to try using `clang` as an alternative to `nvcc`.

**Comment by fwyzard** [comment]
+heterogeneous

**Comment by makortel** [comment]
+core

**Comment by makortel** [comment]
I suppose we can close this
