### ISSUE TITLE
WF 39434.501 step 3: Assertion failure in SiPixelRecHitSoAFromLegacy::produce

### ISSUE THREAD

**Issue by iarspider** [cms-sw/cmssw#37810]
Workflow 39434.501 failed with the following error:

```
cmsRun: (...)/CMSSW_12_4_X_2022-05-04-2300/src/RecoLocalTracker/SiPixelRecHits/plugins/SiPixelRecHitSoAFromLegacy.cc:144: virtual void SiPixelRecHitSoAFromLegacy::produce(edm::StreamID, edm::Event&, const edm::EventSetup&) const: Assertion `gind < nMaxModules' failed.
```

Full log: [link](https://cmssdt.cern.ch/SDT/cgi-bin/logreader/slc7_amd64_gcc10/CMSSW_12_4_X_2022-05-04-2300/pyRelValMatrixLogs/run/39434.501_TTbar_14TeV+2026D88_Patatrack_PixelOnlyCPU+TTbar_14TeV_TuneCP5_GenSimHLBeamSpot14INPUT+DigiTrigger+RecoGlobal+HARVESTGlobal/step3_TTbar_14TeV+2026D88_Patatrack_PixelOnlyCPU+TTbar_14TeV_TuneCP5_GenSimHLBeamSpot14INPUT+DigiTrigger+RecoGlobal+HARVESTGlobal.log#/108-108)

**Comment by iarspider** [comment]
assign reconstruction

**Comment by qliphy** [comment]
This should be related to https://github.com/cms-sw/cmssw/pull/37617/
and a fix https://github.com/cms-sw/cmssw/pull/37798

**Comment by mmusich** [comment]
in CMSSW_12_4 2022-05-12-2300 (containing https://github.com/cms-sw/cmssw/pull/37798) [wf 39434.501 step3](https://cmssdt.cern.ch/SDT/cgi-bin/logreader/slc7_amd64_gcc10/CMSSW_12_4_X_2022-05-12-2300/pyRelValMatrixLogs/run/39434.501_TTbar_14TeV+2026D88_Patatrack_PixelOnlyCPU+TTbar_14TeV_TuneCP5_GenSimHLBeamSpot14INPUT+DigiTrigger+RecoGlobal+HARVESTGlobal/step3_TTbar_14TeV+2026D88_Patatrack_PixelOnlyCPU+TTbar_14TeV_TuneCP5_GenSimHLBeamSpot14INPUT+DigiTrigger+RecoGlobal+HARVESTGlobal.log#/) passes.
This issue can be closed.

**Comment by jpata** [comment]
+reconstruction

**Comment by jpata** [comment]
@cmsbuild please close
