### ISSUE TITLE
unrunnable configuration file obtained with `edmConfigDump`

### ISSUE THREAD

**Issue by mmusich** [cms-sw/cmssw#37837]
In the process of debugging https://github.com/cms-sw/cmssw/issues/37738 I went:
```console
cmsrel CMSSW_12_4_X_2022-05-05-2300/
cd CMSSW_12_4_X_2022-05-05-2300/src/
cmsenv
runTheMatrix.py -l 10804.31 -j 0
cd 10804.31_SingleGammaPt10+2018_photonDRN+SingleGammaPt10_pythia8_GenSim+Digi+RecoFakeHLT+HARVESTFakeHLT+ALCA+Nano/
edmConfigDump step3_RAW2DIGI_L1Reco_RECO_RECOSIM_PAT_VALIDATION_DQM.py > dump.py
cmsRun dump.py
```
this ends in:
```
----- Begin Fatal Exception 06-May-2022 14:55:05 CEST-----------------------
An exception of category 'ConfigFileReadError' occurred while
   [0] Processing the python configuration file named dump.py
Exception Message:
 unknown python problem occurred.
SyntaxError: ('invalid syntax', ('dump.py', 671446, 33, 'FNeutralHadronsBoosted, process.tauMatchBoosted, process.tmpPFCandCollPtrNoHF, process.type0PFMEtCorrectionPFCandToVertexAssociationTask, process.updatedPatJetsSlimmedAK8DeepTags, process.updatedPatJetsSlimmedDeepFlavour, process.updatedPatJetsTransientCorrectedSlimmedAK8DeepTags, process.updatedPatJetsTransientCorrectedSlimmedDeepFlavour])\n'))
----- End Fatal Exception -------------------------------------------------
```

Also I would like to draw to the attention to the fact that if the `edmConfigDump` command is executed on a machine without GPUs I get this warning:
```
sh: nvidia-smi: command not found
```

while it it's done on a machine with a GPU the file is spoiled by a long warning about:
```
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
WARNING:

You should always run with libnvidia-ml.so that is installed with your
NVIDIA Display Driver.
..

```

**Comment by Dr15Jones** [comment]
assign core

**Comment by makortel** [comment]
Unfortunately indeed any printouts from "running" the configuration (these are not the first ones, nor the last ones) get mixed with the actual dump of the configuration. Maybe we should add a parameter, e.g. `-o`, for the `edmConfigDump` to write the dump directly to a file.

**Comment by makortel** [comment]
> Unfortunately indeed any printouts from "running" the configuration (these are not the first ones, nor the last ones) get mixed with the actual dump of the configuration. Maybe we should add a parameter, e.g. `-o`, for the `edmConfigDump` to write the dump directly to a file.

Added in https://github.com/cms-sw/cmssw/pull/37844.

**Comment by makortel** [comment]
Adding @kpedro88 in case there is anything in these particular printouts that would need to be addressed.

**Comment by kpedro88** [comment]
These printouts could be suppressed if they are causing issues like this one, but #37844 seems like a more general solution.

**Comment by makortel** [comment]
+core

**Comment by mmusich** [comment]
@makortel thanks for the new option, but the proposed solution at https://github.com/cms-sw/cmssw/pull/37844 does not solve the issue, that persists with `CMSSW_12_4_X_2022-05-08-2300`.
with:

```console
cmsrel CMSSW_12_4_X_2022-05-08-2300
cd CMSSW_12_4_X_2022-05-08-2300/src/
cmsenv
runTheMatrix.py -l 10804.31 -j 0
cd 10804.31_SingleGammaPt10+2018_photonDRN+SingleGammaPt10_pythia8_GenSim+Digi+RecoFakeHLT+HARVESTFakeHLT+ALCA+Nano/
edmConfigDump step3_RAW2DIGI_L1Reco_RECO_RECOSIM_PAT_VALIDATION_DQM.py -o dump.py
cmsRun dump.py
```
I still get:

```
----- Begin Fatal Exception 09-May-2022 09:10:02 CEST-----------------------
An exception of category 'ConfigFileReadError' occurred while
   [0] Processing the python configuration file named dump.py
Exception Message:
 unknown python problem occurred.
SyntaxError: ('invalid syntax', ('dump.py', 671448, 33, 'FNeutralHadronsBoosted, process.tauMatchBoosted, process.tmpPFCandCollPtrNoHF, process.type0PFMEtCorrectionPFCandToVertexAssociationTask, process.updatedPatJetsSlimmedAK8DeepTags, process.updatedPatJetsSlimmedDeepFlavour, process.updatedPatJetsTransientCorrectedSlimmedAK8DeepTags, process.updatedPatJetsTransientCorrectedSlimmedDeepFlavour])\n'))
----- End Fatal Exception -------------------------------------------------
```

**Comment by makortel** [comment]
@smuzaffar, could you reopen this issue?

**Comment by makortel** [comment]
Thanks @mmusich for reporting, I found the bug causing that error.

On a side note, the dumped configuration is ~21 MB, ~675k lines. That is quite big. On a quick look about 21 % of the lines come from top-level PSets and VPSets, which I'd think to be largely not necessary. So some level of general cleanup would be beneficial, but that is far beyond the scope of this issue.

**Comment by makortel** [comment]
> I found the bug causing that error.

This is now fixed in https://github.com/cms-sw/cmssw/pull/37872 (I tested that the dump from recipe https://github.com/cms-sw/cmssw/issues/37837#issuecomment-1120726574 passes `python3`).
