### ISSUE TITLE
Backports for bugfixes to 2018 PbPb reMiniAOD in 11_2_X

### ISSUE THREAD

**Issue by mandrenguyen** [cms-sw/cmssw#37841]
The HIN PAG identified a couple of bugs in the 11_2_X PbPb miniAOD, that would motivate a partial reprocessing, which amounts to two primary datasets and a few MC datasets (i.e., only a small  fraction of the total PbPb data). 
To fix these datasets we would need to backport the following two bugfixes to 11_2
#36489 #37262

If there are no objections, I would propose that @FHead and @ttrk make the respective backports.

**Comment by jpata** [comment]
Please go ahead. Note that the backports, in case they change physics, need to be protected with a modifier.

**Comment by mandrenguyen** [comment]
The two PRs have been made and are visible above.  Both are only active for the heavy ion eras.

**Comment by jpata** [comment]
+reconstruction
