### ISSUE TITLE
DD4Hep Geometry building takes a lot of time

### ISSUE THREAD

**Issue by Dr15Jones** [cms-sw/cmssw#37864]
When looking at the timing for the NANO step for workflow 11834.21, the vast majority of time is spent in building the volumetric MagneticField.

https://cmssdt.cern.ch/SDT/cgi-bin/igprof-navigator/CMSSW_12_4_X_2022-05-08-2300/slc7_amd64_gcc10/pp/11834.21_TTbar_14TeV+2021PU_ProdLike+TTbar_14TeV_TuneCP5_GenSim+DigiPU+RecoNanoPU+MiniAODPU+NanoPU/step5___b6ff2d761a23670d9b27095006d0e928___10_EndOfJob/59

The underlying issue is we use DD4Hep as a geometry _description_ system, but under the hood DD4Hep uses ROOT's TGeo system which is meant to be a geometry _traversal_ system. When we tell DD4Hep to close the geometry, ROOT goes and voxelizes the entire geometry, which is EXTREMELY time consuming. We do not even use the results of voxelization for the majority of our applications.

We should work with DD4Hep/ROOT to find a way to avoid this overhead.

**Correction** the time is primarily in looking up what nodes are already attached to a parent.

**Comment by Dr15Jones** [comment]
assign geometry

**Comment by civanch** [comment]
@cvuosalo , @ianna , @bsunanda , I think this is urgent. Does voxelization is triggered by DD4hep or by CMSSW code? Are there options?

**Comment by cvuosalo** [comment]
I will ask Markus Frank about the efficiency of the `dd4hep::Converter`.

**Comment by Dr15Jones** [comment]
I _think_ the timing is all in our code at the two calls to `parent->GetNode` here

https://github.com/cms-sw/cmssw/blob/master/DetectorDescription/DDCMS/plugins/dd4hep/DDDefinitions2Objects.cc#L1008-L1020

it somewhat matches the calls in the function assuming the compiler has done a bunch of inlining and/or return value optimizations which change the look of the callback stack.

**Comment by Dr15Jones** [comment]
After changes in #37895 the voxelization is now taking ~50% of the time for building the geometry.

**Comment by ianna** [comment]
> After changes in #37895 the voxelization is now taking ~50% of the time for building the geometry.

Yep, voxelization is slow. I have tried to drop it at some point, but it did not work. I do not remember the details. It may have been related to building Géant4 geometry by DD4hep. It may have changed now. Perhaps, it should be a configurable - if not at all invoked?
