### ISSUE TITLE
std::bad_alloc in CondTools/SiStrip test SiStripDAQ_O2O_test

### ISSUE THREAD

**Issue by iarspider** [cms-sw/cmssw#37888]
CondTools/SiStrip is failing with `std::bad_alloc` during `SiStripDAQ_O2O_test` test:
```
std::bad_alloc exception
----- Begin Fatal Exception 10-May-2022 12:39:11 CEST-----------------------
An exception of category 'BadAlloc' occurred while
   [0] Processing  Event run: 1 lumi: 1 event: 1 stream: 0
   [1] Running path 'p'
   [2] Calling method for module SiStripO2OBadStrip/'siStripO2O'
Exception Message:
A std::bad_alloc exception was thrown.
The job has probably exhausted the virtual memory available to the process.
----- End Fatal Exception -------------------------------------------------
```

Full log: [link](https://cmssdt.cern.ch/SDT/cgi-bin/logreader/slc7_amd64_gcc10/CMSSW_12_4_X_2022-05-10-1100/unitTestLogs/CondTools/SiStrip#/133)

Could it be caused by [database connection error](https://cmssdt.cern.ch/SDT/cgi-bin/logreader/slc7_amd64_gcc10/CMSSW_12_4_X_2022-05-10-1100/unitTestLogs/CondTools/SiStrip#/23-26)?
```
%MSG-e SiStripConfigDb:  (NoModuleName) 10-May-2022 12:39:10 CEST pre-events
 Caught oracle::occi::SQLException in method usingDatabase with message: 
ORA-12545: Connect failed because target host or object does not exist
Additional info: Failed to connect to database using parameters 'cms_trk_r/******@cms_omds_tunnel' and partitions 'TI_27-JAN-2010_2:TM_09-JUN-2009_1:TO_30-JUN-2009_1:TP_09-JUN-2009_1'
```

**Comment by iarspider** [comment]
assign db

**Comment by smuzaffar** [comment]
This unit test is still failing. I think it is related to DB connection issue [a].  @ggovi,@francescobrivio,@malbouis,@tvami  , any idea if this is linked to CMSONR migration?

[a]
```
[SiStripConfigDb::usingDatabase] Overriding TNS_ADMIN value using cfg file!
  Original value : "/etc"!
  New value      : "/etc"!
%MSG-e SiStripConfigDb:  (NoModuleName) 12-May-2022 10:41:46 CEST pre-events
 Caught oracle::occi::SQLException in method usingDatabase with message: 
ORA-12170: TNS:Connect timeout occurred
Additional info: Failed to connect to database using parameters 'cms_trk_r/******@cms_omds_tunnel' and partitions 'TI_27-JAN-2010_2:TM_09-JUN-2009_1:TO_30-JUN-2009_1:TP_09-JUN-2009_1'

```

**Comment by ggovi** [comment]
@smuzaffar 
It seems that the re-installation of cmsonr at P5 has broken some tunnel connections required in these test. I'll investigate with the P5 sysadmins+the DBAs

**Comment by smuzaffar** [comment]
@ggovi , looks like our temporary solution to use `cmstracker035` tunnel is not working any more ( unit test is failing again). Can @cms-sw/db-l2 team setup a stable tunnel to be used by IBs/PRs tests?

**Comment by smuzaffar** [comment]
thanks to `Alessandro Giassi` , the tunnel to online DB is working again but we need to comeup with a stable solution. For now I have opened a SNOW ticket to ask for `cmsusr` cluster access for cmsbot. I guess we can setup a small 2 cores node in CMS SDT openstack project to setup this tunnel

**Comment by smuzaffar** [comment]
https://github.com/cms-sw/cmssw/pull/38434 should fix this issue. `cms_omds_adg` which is already part of CERN tnsnames.ora is now used to coonect to online DB.
