### ISSUE TITLE
Outdated muon code to be removed

### ISSUE THREAD

**Issue by jpata** [cms-sw/cmssw#37973]
These modules are not able to run due to using deprecated functionality, and don't seem to be used anywhere in production
```
RecoMuon/TrackerSeedGenerator:
  TSGForOI
RecoMuon/TrackingTools:
  MuonErrorMatrixAdjuster
```

@cms-sw/muon-pog-l2 @CeliaFernandez @trocino could you please look into it?

**Comment by jpata** [comment]
assign reconstruction

**Comment by jpata** [comment]
type muon

**Comment by andrea21z** [comment]
Both PRs (#39724 and #39726 ) have been merged, so this issue is solved.

**Comment by clacaputo** [comment]
+reconstruction 

- see https://github.com/cms-sw/cmssw/issues/37973#issuecomment-1288913104

**Comment by mandrenguyen** [comment]
please close
