### ISSUE TITLE
Phi wraparound bug in PFDisplacedVertexCandidateFinder? 

### ISSUE THREAD

**Issue by rappoccio** [cms-sw/cmssw#38068]
Hi, 

I think there is a phi wraparound bug in this line of PFDisplacedVertexCandidateFinder:

https://github.com/cms-sw/cmssw/blob/6d2f66057131baacc2fcbdd203588c41c885b42c/RecoParticleFlow/PFTracking/src/PFDisplacedVertexCandidateFinder.cc#L194

```
std::abs(phi1 - phi2) > 1
```

should be

```
math::deltaPhi(phi1,phi2) > 1
```

This may be related to the issue reported [here](https://github.com/cms-sw/cmssw/issues/31158). Can someone confirm? We can fix it (and hopefully the other issue as well) if this is wrong as I expect. 

@jpata @clacaputo @laurenhay

**Comment by makortel** [comment]
assign reconstruction

**Comment by jpata** [comment]
cc @cms-sw/pf-l2

**Comment by jpata** [comment]
type pf

**Comment by jpata** [comment]
Digging through the code, it looks like Maxime was the original author. I don't know if he's on github, but I shot him an email.

**Comment by juska** [comment]
Isn't v1.DeltaPhi(v2) equivalent to abs(v1.Phi() - v2.Phi()) ?

**Comment by perrotta** [comment]
> Isn't v1.DeltaPhi(v2) equivalent to abs(v1.Phi() - v2.Phi()) ?

Not if phi1 is 359 degrees and phi2 is 1 degree (e.g.)

**Comment by mmusich** [comment]
> This may be related to the issue reported https://github.com/cms-sw/cmssw/issues/31158. Can someone confirm? We can fix it (and hopefully the other issue as well) if this is wrong as I expect.

I'd propose to make the PR and check the performance....

**Comment by mmusich** [comment]
> I'd propose to make the PR and check the performance....

here it is: https://github.com/cms-sw/cmssw/pull/38080

**Comment by jpata** [comment]
+reconstruction
- the physics bug was solved by https://github.com/cms-sw/cmssw/pull/38080
- this had no effect on computational performance as far as we saw
