### ISSUE TITLE
 RootEmbeddedFileSequence no input files specified for secondary input source

### ISSUE THREAD

**Issue by qliphy** [cms-sw/cmssw#38192]
Appear in recent IB:

https://cmssdt.cern.ch/SDT/cgi-bin/logreader/el8_amd64_gcc10/CMSSW_12_5_X_2022-06-01-2300/pyRelValMatrixLogs/run/500202.0_TTbar_13+TTbar_13INPUT+DIGIPRMXUP15_PU50+RECOPRMXUP15_PU50+HARVESTUP15_PU50/step2_TTbar_13+TTbar_13INPUT+DIGIPRMXUP15_PU50+RECOPRMXUP15_PU50+HARVESTUP15_PU50.log#/27-27

Step: DIGI Spec: ['pdigi_valid']
Step: DATAMIX Spec: 
the query is file dataset = /RelValPREMIXUP15_PU50/CMSSW_10_4_0_pre1-PU50ns_103X_mcRun2_startup_v1-v1/PREMIX
DAS succeeded after 1 attempts 0
found files:  []
Step: L1 Spec: 
Step: DIGI2RAW Spec: 
Step: HLT Spec: ['@relval50ns']
Step: ENDJOB Spec: 
customising the process with customiseWithTimeMemorySummary from Validation/Performance/TimeMemorySummary
customising the process with customizeHLTforMC from HLTrigger/Configuration/customizeHLTforMC
Starting python2 /data/cmsbld/jenkins/workspace/ib-run-relvals/cms-bot/monitor_workflow.py timeout --signal SIGTERM 9000  cmsRun -j JobReport2.xml  step2_DIGI_DATAMIX_L1_DIGI2RAW_HLT.py
%MSG-i ThreadStreamSetup:  (NoModuleName) 02-Jun-2022 06:29:21 CEST pre-events
setting # threads 4
setting # streams 4
%MSG
02-Jun-2022 06:29:33 CEST  Initiating request to open file root://eoscms.cern.ch//eos/cms/store/user/cmsbuild/store/relval/CMSSW_10_6_0/RelValTTbar_13/GEN-SIM/106X_mcRun2_asymptotic_v3-v1/10000/402EC6D2-FB00-C848-BEC8-4B9D79EBE558.root
%MSG-w XrdAdaptor:  file_open 02-Jun-2022 06:29:35 CEST pre-events
Data is served from cern.ch instead of original site eoscms
%MSG
02-Jun-2022 06:29:37 CEST  Successfully opened file root://eoscms.cern.ch//eos/cms/store/user/cmsbuild/store/relval/CMSSW_10_6_0/RelValTTbar_13/GEN-SIM/106X_mcRun2_asymptotic_v3-v1/10000/402EC6D2-FB00-C848-BEC8-4B9D79EBE558.root
02-Jun-2022 06:29:40 CEST  Closed file root://eoscms.cern.ch//eos/cms/store/user/cmsbuild/store/relval/CMSSW_10_6_0/RelValTTbar_13/GEN-SIM/106X_mcRun2_asymptotic_v3-v1/10000/402EC6D2-FB00-C848-BEC8-4B9D79EBE558.root
----- Begin Fatal Exception 02-Jun-2022 06:29:40 CEST-----------------------
An exception of category 'NoSecondaryFiles' occurred while
   [0] Constructing the EventProcessor
   [1] Constructing module: class=PreMixingModule label='mixData'
Exception Message:
RootEmbeddedFileSequence no input files specified for secondary input source.
----- End Fatal Exception -------------------------------------------------

**Comment by qliphy** [comment]
https://cmsweb.cern.ch/das/request?view=list&limit=50&instance=prod%2Fglobal&input=%2FRelValPREMIXUP15_PU50%2FCMSSW_10_4_0_pre1-PU50ns_103X_mcRun2_startup_v1-v1%2FPREMIX

It seems  /RelValMinBias_13/CMSSW_10_6_0-106X_mcRun2_asymptotic_v3-v1/GEN-SIM is deleted.

**Comment by qliphy** [comment]
assign pdmv

**Comment by smuzaffar** [comment]
@qliphy , though dataset has been deleted but we have cached the results. I can run `runTheMatrix.py -i all -l 25200.0 --command ' -n 1 ' -t 4 ` locally using ibeos cache. there might be a glitch with github due to which some tests failed to get the das cached results from github.

**Comment by qliphy** [comment]
thanks @smuzaffar
