### ISSUE TITLE
Remove StandAlone muon duplicates

### ISSUE THREAD

**Issue by CeliaFernandez** [cms-sw/cmssw#38201]
There are few cases of StandAlone muons reconstructed in the proximity of Global Muons with different outer track, but very similar parameters. In most of these cases, the number of hits of both outer tracks of Global and StandAlone muons coincide, which suggests that these secondary StandAlone muons are indeed duplicates of the StandAlone muon that seeded the Global muon reconstruction. The presence of such duplicates was reported in eta ~ 0 and high eta values. 

The origin of such duplication seems to come from a disambiguation logic in `GlobalMuonProducer` where both `standAloneMuons:UpdatedAtVtx` and `standAloneMuons` tracks are used to seed the global muon reconstruction. The `standAloneMuons:UpdatedAtVtx` track is always used unless it is not available or has a change in the sign of eta with respect to the original `standAloneMuons` track (see [L134 of GlobalMuonProducer](https://github.com/cms-sw/cmssw/blob/13c379cfd9d7e26f8a2a012815466852a27d59d6/RecoMuon/GlobalMuonProducer/src/GlobalMuonProducer.cc#L134)).

However, when StandAlone, Global and Tracker muons are combined in `MuonIdProducer`, only `standAloneMuons:UpdatedAtVtx` tracks are used to fill the `muons1stStep` collection. In cases where there is a Global muon seeded by a track from `standAloneMuons`, the comparison between the outer tracks fails (as they are different) and the partner `standAloneMuons:UpdatedAtVtx` track is saved as a new muon.

This disambiguation may also introduce cases of `standAloneMuons` tracks where the beamspot constraint fails and no `standAloneMuons:UpdatedAtVtx` track is created. These muons would be lost unless they seed a Global muon.

The impact of these two effects was reported to be negligible as it happens very infrequently. Groups measuring global muon reconstruction solve the disambiguation by means of TrackExtra information present in AOD samples.

Created issue to track these effects while we study different solutions.

More information can be found in: 
[1] [https://cms-talk.web.cern.ch/t/unbiased-standalone-muon-collection/7970](https://mmm.cern.ch/owa/redir.aspx?C=ZngTaMylM9oTGe7xU_PbJNiF2a-tOsSfXMUdJejL_XDiDbDbpUTaCA..&URL=https%3a%2f%2fcms-talk.web.cern.ch%2ft%2funbiased-standalone-muon-collection%2f7970)
[2] [https://indico.cern.ch/event/1142174/contributions/4796534/attachments/2412340/4128209/muonReco-Mar22-2022.pdf](https://mmm.cern.ch/owa/redir.aspx?C=eohVCE6oEVav3ardvA484QjttYjCFLfxuk5HQfsteXjiDbDbpUTaCA..&URL=https%3a%2f%2findico.cern.ch%2fevent%2f1142174%2fcontributions%2f4796534%2fattachments%2f2412340%2f4128209%2fmuonReco-Mar22-2022.pdf)

**Comment by makortel** [comment]
assign reconstruction

**Comment by mandrenguyen** [comment]
+1

**Comment by mandrenguyen** [comment]
Closed #38201 as completed.

**Comment by mandrenguyen** [comment]
please close
