### ISSUE TITLE
Issues with wfs 25040X in IB tests

### ISSUE THREAD

**Issue by qliphy** [cms-sw/cmssw#38229]
https://cmssdt.cern.ch/SDT/cgi-bin/logreader/el8_amd64_gcc11/CMSSW_12_5_X_2022-06-03-1100/pyRelValMatrixLogs/run/250400.18_ZEE_13+FS_ZEE_13_PRMXUP18_PU50+HARVESTUP18FS+MINIAODMCUP18FS/step1_ZEE_13+FS_ZEE_13_PRMXUP18_PU50+HARVESTUP18FS+MINIAODMCUP18FS.log#/

  File "/cvmfs/cms-ib.cern.ch/nweek-02735/el8_amd64_gcc11/cms/cmssw-patch/CMSSW_12_5_X_2022-06-03-1100/src/SimGeneral/PreMixingModule/python/mixOne_premix_on_sim_cfi.py", line 324, in <module>
    (runDependentForPixel & premix_stage2).toModify(mixData.workers.pixel,
AttributeError: 'PSet' object has no attribute 'pixel'

**Comment by qliphy** [comment]
Seem to be Related to https://github.com/cms-sw/cmssw/pull/37823

**Comment by qliphy** [comment]
assign simulations

**Comment by mmusich** [comment]
I propose a fix here: https://github.com/cms-sw/cmssw/pull/38236
