### ISSUE TITLE
GCC12 build error: Address of object will never be NULL

### ISSUE THREAD

**Issue by smuzaffar** [cms-sw/cmssw#38223]
For GCC 12 IBs, we get few [build errors](https://cmssdt.cern.ch/SDT/cgi-bin/buildlogs/el8_amd64_gcc12/CMSSW_12_5_X_2022-06-01-1600/TopQuarkAnalysis/TopKinFitter) like [a]. This is coing from https://github.com/cms-sw/cmssw/blob/master/TopQuarkAnalysis/TopKinFitter/interface/CovarianceMatrix.h#L101 . Shouldn't this code be changed to
```
- if (dynamic_cast<const reco::Jet*>(&object))
+ if (dynamic_cast<const reco::Jet*>(object.originalObject()) != nullptr)
```

[a]  
```
  /pool/condor/dir_17081/jenkins/workspace/build-any-ib/w/tmp/BUILDROOT/da326a5a4352c27bf65de0cea57a28e0/opt/cmssw/el8_amd64_gcc12/cms/cmssw/CMSSW_12_5_X_2022-06-01-1600/src/TopQuarkAnalysis/TopKinFitter/interface/CovarianceMatrix.h:101:13: error: the address of 'pat::PATObject<reco::Jet>::<anonymous>' will never be NULL [-Werror=address]
   101 |         if (dynamic_cast<const reco::Jet*>(&object))
```

**Comment by makortel** [comment]
assign analysis

(if this even works anymore)

**Comment by makortel** [comment]
So `pat::PATObject<T>` inherits from `T`, so the compiler complains that `dynamic_cast<T const*>()` always succeeds for `pat::PATObject<T> const*`. I think the code could be changed to something along
```cpp
if constexpr (std::is_same_v<T, reco::Jet>) {
```
as well.

**Comment by smuzaffar** [comment]
thanks @makortel for the suggestion. https://github.com/cms-sw/cmssw/pull/38263 should fix this issue
