### ISSUE TITLE
process.dumpPython() in cmsRun config 12_4_0_pre3 creates config with syntax error in some cases

### ISSUE THREAD

**Issue by adewit** [cms-sw/cmssw#38289]
Aplogies if this has already been reported/fixed, but I noticed that in CMSSW 12_4_0_pre3 calling process.dumpPython() at the end of a cmsRun config (to extract the full configuration), produces a configuration that won't run, at least for my use case.

The problem is that it prints `process.patAlgosToolsTask = cms.{}(*[...` instead of `process.patAlgosToolsTask=cms.Task(*[...`.  It's easy enough to fix manually in my config, but in the long run it would be great if that weren't necessary. Since I'm not sure exactly which bit of the code is responsible for this and how to fix it, I hope that someone here knows.

**Comment by mmusich** [comment]
duplicate of https://github.com/cms-sw/cmssw/issues/37837?

**Comment by adewit** [comment]
It is indeed! I should have scrolled further back :-) thanks for pointing it out - good to hear that it's already been addressed and apologies for the noise.
