### ISSUE TITLE
L1T PF developments need to be fixed and cleaned

### ISSUE THREAD

**Issue by perrotta** [cms-sw/cmssw#38409]
The L1T Phase2 PR #38230 was merged even if it still needed some additional fix and cleanings. That was considered the more practical way to merge all the code included in that huge PR, deferring the needed adjustments to some more agile follow-up PR.

In fact, one or two fix PRs were supposed to be prepared shortly after that merge, see https://github.com/cms-sw/cmssw/pull/38230#issuecomment-1151550378

Since a PR which includes those fixes is not yet in sight after 8 days, let open this github issue to keep track of it till the resolution.

@cecilecaillol @drankincms

**Comment by perrotta** [comment]
assign l1, upgrade

**Comment by davidlange6** [comment]
to add to whatever the existing list is, why was this needed?

https://github.com/cms-sw/cmssw/blob/master/DataFormats/L1TParticleFlow/interface/datatypes.h#L4
(line 4-11)

I had hoped we were done adding such constructs to cmssw....

**Comment by cecilecaillol** [comment]
https://github.com/cms-sw/cmssw/pull/38442 addresses both the issue of the obsolete files and of the DQM. It needs HLT changes to pass the tests

**Comment by cecilecaillol** [comment]
+l1

**Comment by srimanob** [comment]
+upgrade

**Comment by srimanob** [comment]
please close
