### ISSUE TITLE
Fast&Full Simulation Performance Optimisation

### ISSUE THREAD

**Issue by ianna** [cms-sw/cmssw#38480]
@bsunanda @civanch  @sbein - as a follow up of the [Simulation meeting](https://indico.cern.ch/event/1172072/) performance results analysis, please,  find the following recommendations.

**CPU improvement estimate is ~5%.** 

Please, note that resolving the last two items would eliminate the calls that are quite high in [the MEM_TOTAL report](https://nhoerman.web.cern.ch/nhoerman/cgi-bin/igprof-navigator/FastSim/CMSSW_12_4_0_pre3_SLC7/TimeMemory/14TeV_GEN_SIM_2021_1_500_fastsim_conf/igprofMEM_MEM_TOTAL_TTbar) (**accounting for ~30%**).
 
- [ ] Pre-compute the numbers from a base number name to avoid expensive string operation on every G4Step:

auto [num1](https://cmssdt.cern.ch/lxr/ident?v=CMSSW_12_5_X_2022-06-17-2300&_i=num1) = [numbers](https://cmssdt.cern.ch/lxr/ident?v=CMSSW_12_5_X_2022-06-17-2300&_i=numbers)([baseNumber](https://cmssdt.cern.ch/lxr/ident?v=CMSSW_12_5_X_2022-06-17-2300&_i=baseNumber).[getLevelName](https://cmssdt.cern.ch/lxr/ident?v=CMSSW_12_5_X_2022-06-17-2300&_i=getLevelName)(3 + [off](https://cmssdt.cern.ch/lxr/ident?v=CMSSW_12_5_X_2022-06-17-2300&_i=off)));

<img width="1259" alt="Screenshot 2022-06-23 at 08 50 50" src="https://user-images.githubusercontent.com/1390682/175234130-912fbeb1-fd71-45b3-b3d7-d3a9b4ea733a.png">

- [ ] Pick up serialisable `HcalSimulationParameters` from a GT:

#include "[CondFormats](https://cmssdt.cern.ch/lxr/source/CondFormats/?v=CMSSW_12_5_X_2022-06-17-2300)/[Serialization](https://cmssdt.cern.ch/lxr/source/CondFormats/Serialization/?v=CMSSW_12_5_X_2022-06-17-2300)/[interface](https://cmssdt.cern.ch/lxr/source/CondFormats/Serialization/interface/?v=CMSSW_12_5_X_2022-06-17-2300)/[Serializable.h](https://cmssdt.cern.ch/lxr/source/CondFormats/Serialization/interface/Serializable.h?v=CMSSW_12_5_X_2022-06-17-2300)"
0005 
0006 class [HcalSimulationParameters](https://cmssdt.cern.ch/lxr/ident?v=CMSSW_12_5_X_2022-06-17-2300&_i=HcalSimulationParameters) {
0007 public:
0008   [HcalSimulationParameters](https://cmssdt.cern.ch/lxr/ident?v=CMSSW_12_5_X_2022-06-17-2300&_i=HcalSimulationParameters)(void) {}
0009   ~HcalSimulationParameters(void) {}
0010 
0011   [std](https://cmssdt.cern.ch/lxr/ident?v=CMSSW_12_5_X_2022-06-17-2300&_i=std)::[vector](https://cmssdt.cern.ch/lxr/ident?v=CMSSW_12_5_X_2022-06-17-2300&_i=vector)<double> attenuationLength_;
0012   [std](https://cmssdt.cern.ch/lxr/ident?v=CMSSW_12_5_X_2022-06-17-2300&_i=std)::[vector](https://cmssdt.cern.ch/lxr/ident?v=CMSSW_12_5_X_2022-06-17-2300&_i=vector)<int> lambdaLimits_;
0013   [std](https://cmssdt.cern.ch/lxr/ident?v=CMSSW_12_5_X_2022-06-17-2300&_i=std)::[vector](https://cmssdt.cern.ch/lxr/ident?v=CMSSW_12_5_X_2022-06-17-2300&_i=vector)<double> shortFiberLength_;
0014   [std](https://cmssdt.cern.ch/lxr/ident?v=CMSSW_12_5_X_2022-06-17-2300&_i=std)::[vector](https://cmssdt.cern.ch/lxr/ident?v=CMSSW_12_5_X_2022-06-17-2300&_i=vector)<double> longFiberLength_;
0015 
0016   [std](https://cmssdt.cern.ch/lxr/ident?v=CMSSW_12_5_X_2022-06-17-2300&_i=std)::[vector](https://cmssdt.cern.ch/lxr/ident?v=CMSSW_12_5_X_2022-06-17-2300&_i=vector)<int> pmtRight_;
0017   [std](https://cmssdt.cern.ch/lxr/ident?v=CMSSW_12_5_X_2022-06-17-2300&_i=std)::[vector](https://cmssdt.cern.ch/lxr/ident?v=CMSSW_12_5_X_2022-06-17-2300&_i=vector)<int> pmtFiberRight_;
0018   [std](https://cmssdt.cern.ch/lxr/ident?v=CMSSW_12_5_X_2022-06-17-2300&_i=std)::[vector](https://cmssdt.cern.ch/lxr/ident?v=CMSSW_12_5_X_2022-06-17-2300&_i=vector)<int> pmtLeft_;
0019   [std](https://cmssdt.cern.ch/lxr/ident?v=CMSSW_12_5_X_2022-06-17-2300&_i=std)::[vector](https://cmssdt.cern.ch/lxr/ident?v=CMSSW_12_5_X_2022-06-17-2300&_i=vector)<int> pmtFiberLeft_;
0020 
0021   [std](https://cmssdt.cern.ch/lxr/ident?v=CMSSW_12_5_X_2022-06-17-2300&_i=std)::[vector](https://cmssdt.cern.ch/lxr/ident?v=CMSSW_12_5_X_2022-06-17-2300&_i=vector)<int> [hfLevels_](https://cmssdt.cern.ch/lxr/ident?v=CMSSW_12_5_X_2022-06-17-2300&_i=hfLevels_);
0022   [std](https://cmssdt.cern.ch/lxr/ident?v=CMSSW_12_5_X_2022-06-17-2300&_i=std)::[vector](https://cmssdt.cern.ch/lxr/ident?v=CMSSW_12_5_X_2022-06-17-2300&_i=vector)<[std](https://cmssdt.cern.ch/lxr/ident?v=CMSSW_12_5_X_2022-06-17-2300&_i=std)::[string](https://cmssdt.cern.ch/lxr/ident?v=CMSSW_12_5_X_2022-06-17-2300&_i=string)> [hfNames_](https://cmssdt.cern.ch/lxr/ident?v=CMSSW_12_5_X_2022-06-17-2300&_i=hfNames_);
0023   [std](https://cmssdt.cern.ch/lxr/ident?v=CMSSW_12_5_X_2022-06-17-2300&_i=std)::[vector](https://cmssdt.cern.ch/lxr/ident?v=CMSSW_12_5_X_2022-06-17-2300&_i=vector)<[std](https://cmssdt.cern.ch/lxr/ident?v=CMSSW_12_5_X_2022-06-17-2300&_i=std)::[string](https://cmssdt.cern.ch/lxr/ident?v=CMSSW_12_5_X_2022-06-17-2300&_i=string)> hfFibreNames_;
0024   [std](https://cmssdt.cern.ch/lxr/ident?v=CMSSW_12_5_X_2022-06-17-2300&_i=std)::[vector](https://cmssdt.cern.ch/lxr/ident?v=CMSSW_12_5_X_2022-06-17-2300&_i=vector)<[std](https://cmssdt.cern.ch/lxr/ident?v=CMSSW_12_5_X_2022-06-17-2300&_i=std)::[string](https://cmssdt.cern.ch/lxr/ident?v=CMSSW_12_5_X_2022-06-17-2300&_i=string)> hfPMTNames_;
0025   [std](https://cmssdt.cern.ch/lxr/ident?v=CMSSW_12_5_X_2022-06-17-2300&_i=std)::[vector](https://cmssdt.cern.ch/lxr/ident?v=CMSSW_12_5_X_2022-06-17-2300&_i=vector)<[std](https://cmssdt.cern.ch/lxr/ident?v=CMSSW_12_5_X_2022-06-17-2300&_i=std)::[string](https://cmssdt.cern.ch/lxr/ident?v=CMSSW_12_5_X_2022-06-17-2300&_i=string)> hfFibreStraightNames_;
0026   [std](https://cmssdt.cern.ch/lxr/ident?v=CMSSW_12_5_X_2022-06-17-2300&_i=std)::[vector](https://cmssdt.cern.ch/lxr/ident?v=CMSSW_12_5_X_2022-06-17-2300&_i=vector)<[std](https://cmssdt.cern.ch/lxr/ident?v=CMSSW_12_5_X_2022-06-17-2300&_i=std)::[string](https://cmssdt.cern.ch/lxr/ident?v=CMSSW_12_5_X_2022-06-17-2300&_i=string)> hfFibreConicalNames_;
0027   [std](https://cmssdt.cern.ch/lxr/ident?v=CMSSW_12_5_X_2022-06-17-2300&_i=std)::[vector](https://cmssdt.cern.ch/lxr/ident?v=CMSSW_12_5_X_2022-06-17-2300&_i=vector)<[std](https://cmssdt.cern.ch/lxr/ident?v=CMSSW_12_5_X_2022-06-17-2300&_i=std)::[string](https://cmssdt.cern.ch/lxr/ident?v=CMSSW_12_5_X_2022-06-17-2300&_i=string)> hcalMaterialNames_;
0028 
0029   [COND_SERIALIZABLE](https://cmssdt.cern.ch/lxr/ident?v=CMSSW_12_5_X_2022-06-17-2300&_i=COND_SERIALIZABLE);
0030 };

<img width="1272" alt="Screenshot 2022-06-23 at 09 24 45" src="https://user-images.githubusercontent.com/1390682/175240656-85e98cb1-fc3e-4223-afd3-ed86d617f382.png">

- [ ] Pick up serialisable `MuonOffsetMap` from a GT:

class [MuonOffsetMap](https://cmssdt.cern.ch/lxr/ident?v=CMSSW_12_5_X_2022-06-17-2300&_i=MuonOffsetMap) {
0010 public:
0011   [MuonOffsetMap](https://cmssdt.cern.ch/lxr/ident?v=CMSSW_12_5_X_2022-06-17-2300&_i=MuonOffsetMap)() = default;
0012   ~MuonOffsetMap() = default;
0013 
0014   [std](https://cmssdt.cern.ch/lxr/ident?v=CMSSW_12_5_X_2022-06-17-2300&_i=std)::unordered_map<[std](https://cmssdt.cern.ch/lxr/ident?v=CMSSW_12_5_X_2022-06-17-2300&_i=std)::[string](https://cmssdt.cern.ch/lxr/ident?v=CMSSW_12_5_X_2022-06-17-2300&_i=string), [std](https://cmssdt.cern.ch/lxr/ident?v=CMSSW_12_5_X_2022-06-17-2300&_i=std)::[pair](https://cmssdt.cern.ch/lxr/ident?v=CMSSW_12_5_X_2022-06-17-2300&_i=pair)<int, int> > muonMap_;
0015 
0016   [COND_SERIALIZABLE](https://cmssdt.cern.ch/lxr/ident?v=CMSSW_12_5_X_2022-06-17-2300&_i=COND_SERIALIZABLE);
0017 };

<img width="1309" alt="Screenshot 2022-06-23 at 09 22 28" src="https://user-images.githubusercontent.com/1390682/175240171-8d3650bf-e2ed-4cb5-b7db-40f25fec126f.png">

**Comment by civanch** [comment]
assign geometry

**Comment by civanch** [comment]
@ianna , @bsunanda , is HcalSimulationParameters filled once per run in only one thread or it filled many times?

**Comment by ianna** [comment]
@bsunanda and @civanch - Please, open a new issue if it is still relevant. Thanks!
