### ISSUE TITLE
mis-assignment of log messages to unrelated modules

### ISSUE THREAD

**Issue by slava77** [cms-sw/cmssw#38724]
I observed the following in CMSSW_12_5_0_pre3:
after adding LogWarnings in a module `TrackClusterRemoverPhase2` as in https://github.com/cms-sw/cmssw/compare/CMSSW_12_5_0_pre3...slava77:cmssw:CMSSW_12_5_0_pre3/debugPh2CluRM

For a job based on wf 35234.21 `cmsDriver.py step3  -s RAW2DIGI,L1Reco,RECO,RECOSIM --conditions auto:phase2_realistic_T21 --datatier AODSIM -n 1 --eventcontent AODSIM --geometry Extended2026D77 --era Phase2C11I13M9 --filein  root://eoscms.cern.ch//eos/cms/store/user/cmsbuild/profiling/data/CMSSW_12_5_0_pre3/el8_amd64_gcc10/35234.21/step2.root  --fileout file:step3.root --no_exec`

I see in the log file (just the first message, there are more)
```
%MSG-w MYDEBUG:  MuonGeometryConstantsESModule:muonGeometryConstants  13-Jul-2022 15:48:19 CEST Run: 1 Event: 1
Good track 0 nh 10 0.658941 -1.46985 -3.08523
```
The message clearly has nothing to do with `MuonGeometryConstantsESModule`

Curiously, after enabling the tracer `process.Tracer = cms.Service("Tracer", printTimestamps = cms.untracked.bool(True))` the message attribution seems correct

```
%MSG-w MYDEBUG:  TrackClusterRemoverPhase2:highPtTripletStepClusters  13-Jul-2022 16:00:19 CEST Run: 1 Event: 1
Good track 0 nh 10 0.658941 -1.46985 -3.08523
```

**Comment by makortel** [comment]
Could you give a pointer to full log with `Tracer`?

**Comment by slava77** [comment]
without tracer
cmsdev34:/build/slava77/reltest/CMSSW_12_5_0_pre3-ph2Nt/35234.21_TTbar_14TeV+2026D77PU_ProdLike/test1.log

with tracer
cmsdev34:/build/slava77/reltest/CMSSW_12_5_0_pre3-ph2Nt/35234.21_TTbar_14TeV+2026D77PU_ProdLike/test2.log

**Comment by makortel** [comment]
+1
