### ISSUE TITLE
G4e refitter configuration broken by dd4hep

### ISSUE THREAD

**Issue by mmusich** [cms-sw/cmssw#38739]
Since there are widespread plans of using the G4e refitting technology for both the muon momentum scale calibration for the W mass analysis and for the global tracker alignment procedure, it's important that we start testing it.
Unfortunately the current setup is broken, possibly from the dd4hep updates in the configuration.
Running the setup put together at PR https://github.com/cms-sw/cmssw/pull/38738 results in:
```console
----- Begin Fatal Exception 14-Jul-2022 14:06:57 CEST-----------------------
An exception of category 'Configuration' occurred while
   [0] Constructing the EventProcessor
   [1] Constructing module: class=GeometryProducer label='geopro'
Exception Message:
MissingParameter: Parameter 'g4GeometryDD4hepSource' not found.
----- End Fatal Exception -------------------------------------------------
```
This was also reported quite some time ago at https://cms-talk.web.cern.ch/t/help-with-running-g4-refit-in-12-4-x/10294 but no replies so far.

**Comment by mmusich** [comment]
assign geometry, simulation

**Comment by VinInn** [comment]
made progress.
try to create geom in beginRun

now I get
----- Begin Fatal Exception 26-Jul-2022 11:39:10 CEST-----------------------
An exception of category 'DetectorDescriptionFault' occurred while
   [0] Processing global begin Run run: 1
   [1] Calling method for module GeometryProducer/'geopro'
Exception Message:
DDG4SolidConverter::convert: conversion failed for s=ebalgo:ESPM   ShapelessSolid:  shapeless
 solid.shape()=ShapelessSolid
----- End Fatal Exception -------------------------------------------------

**Comment by VinInn** [comment]
more progress
with
```
process.GlobalTag = GlobalTag(process.GlobalTag, 'auto:run1_mc', '')
```
seems to work (in wf 20.0)

at least
```
cmsRun Geant4e_example_cfg.py
````

does not crash

**Comment by tvami** [comment]
This is an issue that's marked `urgent` and I think already resolved, can it be closed?

**Comment by mmusich** [comment]
It needs to be signed by the respective L2s

**Comment by civanch** [comment]
+1

**Comment by mmusich** [comment]
closing as resolved in https://github.com/cms-sw/cmssw/pull/38864
