### ISSUE TITLE
DQM Offline GUI indexing problem in StreamExpress__Run2022C-PromptCalibProdSiStripHitEff dataset

### ISSUE THREAD

**Issue by rvenditti** [cms-sw/cmssw#38814]
The dataset /StreamExpress/Run2022C-PromptCalibProdSiStripHitEff-Express-v1/ALCAPROMPT (run numbers 355807-355942) is not registered in the Offline DQM GUI. We found that the rootfiles are available on DQM machines (see https://cmsweb.cern.ch/dqm/offline/data/browse/ROOT/OfflineData/Run2022/StreamExpress/0003559xx/ ) but they have not been registered in the DQM Offline GUI database. From log files, we found that the registration failed with following error:

/data/srv/state/dqmgui/offline/data/OfflineData/Run2022/StreamExpress/0003558xx/DQM_V0001_R000355869__StreamExpress__Run2022C-PromptCalibProdSiStripHitEff-Express-v1__ALCAPROMPT.root: error reading file: DQMStore: Monitor element path name 'TEC+1: Map of missing hits' uses unacceptable characters
2022-07-20 01:19:31.380953 [visDQMImportDaemon/2757] imported /data/srv/state/dqmgui/offline/data/OfflineData/Run2022/StreamExpress/0003558xx/DQM_V0001_R000355869__StreamExpress__Run2022C-PromptCalibProdSiStripHitEff-Ex\
press-v1__ALCAPROMPT.root with status 256 in 0.566s
2022-07-20 01:19:31.381240 [visDQMImportDaemon/2757] command failed with exit code 256

It has been suggested that this can be due to:  https://github.com/cms-sw/cmssw/blob/master/CalibTracker/SiStripHitEfficiency/interface/SiStripHitEfficiencyHelpers.h#L56-L69

@cms-sw/alca-l2  @mmusich @cms-sw/dqm-l2 @pmandrik

**Comment by makortel** [comment]
assign dqm

**Comment by tvami** [comment]
FYI @mmusich

**Comment by jfernan2** [comment]
Hi @mmusich 
The problem is in the semicoon ":", not in the sign:
Valid characters:
https://github.com/cms-DQM/dqmgui_prod/blob/af0a388e8f57c60e51111585d298aeeea943367f/src/cpp/DQM/DQMStore.cc#L56

The check:
https://github.com/cms-DQM/dqmgui_prod/blob/af0a388e8f57c60e51111585d298aeeea943367f/src/cpp/DQM/DQMStore.cc#L1893-L1898

**Comment by mmusich** [comment]
@jfernan2,
thanks

> The check:

does it apply only to the histogram names or also to the titles, labels, etc?

**Comment by jfernan2** [comment]
MEs names and paths, not titles or labels.

DQMStore: Monitor element path name 'TEC+1: Map of missing hits' uses unacceptable characters

**Comment by makortel** [comment]
Is the validity of the histogram name not checked at the time of booking? If not, could the check be added there?

**Comment by mmusich** [comment]
> Is the validity of the histogram name not checked at the time of booking? If not, could the check be added there?

apparently it's not because running the workflow locally creates valid root files that can be inspected with `TBrowser` just fine.
The issue appears only in streaming the files on the DQM GUI.

**Comment by jfernan2** [comment]
Right, it is the index which has troubles with special characters, due to DB constraints

**Comment by mmusich** [comment]
see a possible fix at https://github.com/cms-sw/cmssw/pull/38823. I profited to rename the histograms a bit.

**Comment by makortel** [comment]
Could a check for valid histogram names be added to histogram booking in order to catch these kinds of problems early?

**Comment by mmusich** [comment]
> Could a check for valid histogram names be added to histogram booking in order to catch these kinds of problems early?

 What about here:

https://github.com/cms-sw/cmssw/blob/106b43f50a61de1e7497a2a5aec8b30727d99c82/DQMServices/Core/src/DQMStore.cc#L63-L68

**Comment by jfernan2** [comment]
I leave it up to @emanueleusai to decide, I believe it may be useful, yes

**Comment by mmusich** [comment]
> I believe it may be useful, yes

OK, I've opened https://github.com/cms-sw/cmssw/pull/38831 for review. It can be merged in case it's deemed useful by the DQM core team.
