### ISSUE TITLE
Assertion !assertLegacySafe_ failed in DQMStore

### ISSUE THREAD

**Issue by jfernan2** [cms-sw/cmssw#38820]
Despite the fix nicely implemented here https://github.com/cms-sw/cmssw/pull/35756 and discussed here https://github.com/cms-sw/cmssw/issues/35726, it seems we are facing a similar problem:
https://cms-talk.web.cern.ch/t/paused-jobs-for-promptreco-ephemeralhltphysics-0-19/13134/3
in this file (and other similar ones with almost no events and LSs...)

The file producing the crash has 28LS but 20 only events: /eos/cms/tier0/store/data/Run2022C/EphemeralHLTPhysics1/RAW/v1/000/355/831/00000/0a258b68-9081-4f92-9a10-9d44d3d6792e.root

Crash details:
cmsRun: /data/cmsbld/jenkins/workspace/auto-builds/CMSSW_12_4_3-el8_amd64_gcc10/build/CMSSW_12_4_3-build/tmp/BUILDROOT/b39a009dc423fccb634d18d504543fd3/opt/cmssw/el8_amd64_gcc10/cms/cmssw/CMSSW_12_4_3/src/DQMServices/Core/src/DQMStore.cc:433: void dqm::implementation::DQMStore::initLumi(edm::RunNumber_t, edm::LuminosityBlockNumber_t, uint64_t): Assertion !assertLegacySafe_' failed.

The tarball with PSet.py can be found here:
/afs/cern.ch/user/c/cmst0/public/PausedJobs/Tarballs/job_96131/vocms013.cern.ch-96131-3-log.tar.gz

FYI @cms-sw/dqm-l2 @makortel @Dr15Jones

**Comment by jfernan2** [comment]
assign dqm

**Comment by makortel** [comment]
I see the `PSet.py` in the tarball has
```
process.DQMStore = cms.Service("DQMStore")
```
and `DQMStore` by default sets `assertLegacySafe_` to `true`
https://github.com/cms-sw/cmssw/blob/5984a2e3640ac76b88939cfba90cee1bac051d65/DQMServices/Core/src/DQMStore.cc#L741

https://github.com/cms-sw/cmssw/pull/34366 set the `assertLegacySafe = False` only in `DQMStore_cfi.py`, so this does not end up being used in this (these?) T0 jobs. Maybe the aforementioned line in `DQMStore.cc` should be changed to `false` as well.

(I'm actually a bit surprised this assertion failure has not been encountered earlier with this configuration of `DQMStore`)

**Comment by jfernan2** [comment]
Thank you @makortel !!
Your solution works perfect, as usual.
I have created PRs for master and 12_4_X
https://github.com/cms-sw/cmssw/pull/38821
https://github.com/cms-sw/cmssw/pull/38822

The reason why this may have not been probably seen before is because the crashing PD has acombination of LSs with no events and has not dqm_sequence defined, hence the DQMStore class is used from the class template and not from DQMStore_cfi.py

Thank you!
