### ISSUE TITLE
[G4VECGEOM_X] IB reports compiler errors for both gcc10 and gcc11.

### ISSUE THREAD

**Issue by aandvalenzuela** [cms-sw/cmssw#38935]
Hello,

IB `G4VECGEOM_X` is reporting compiler errors leading to failures in tests and relvals. See failures at [CMSSW_12_5_G4VECGEOM_X_2022-08-01-2300](https://cmssdt.cern.ch/SDT/cgi-bin/showBuildLogs.py/el8_amd64_gcc10/www/mon/12.5.G4VECGEOM-mon-23/CMSSW_12_5_G4VECGEOM_X_2022-08-01-2300).

We think it could be broken because of [#38329](https://github.com/cms-sw/cmssw/pull/38329).

In addition, the `G4` version of `G4VECGEOM_X` is 11.0.6 and in `12_5_X` is 10.7.2. Could it be because function `PrintInfo` was marked "obsolete" in 10.7.2  (https://github.com/cms-externals/geant4/blob/cms/v10.7.2/source/processes/electromagnetic/utils/include/G4VEmProcess.hh) and it was removed in 11.0.6?

Many thanks,
Andrea.

**Comment by makortel** [comment]
@aandvalenzuela Your link points to CXXMODULE IB, could you fix that?
