### ISSUE TITLE
[UBSAN] Runtime errors in `DQMOffline/Configuration`

### ISSUE THREAD

**Issue by aandvalenzuela** [cms-sw/cmssw#38944]
Hello,

There are some runtime errors of the following type in UBSAN IB, Unit test `TestDQMOfflineConfiguration_0` in `DQMOffline/Configuration` although the test itself suceeds :
```
/data/cmsbld/jenkins/workspace/build-any-ib/w/el8_amd64_gcc10/external/hls/2019.08-80454731218d87c9edf8f512cb8429f9/include/etc/ap_private.h:3397:46:
runtime error: left shift of 47669215288941 by 63 places cannot be represented in type 'long int'
```

See full [stack trace](https://cmssdt.cern.ch/SDT/cgi-bin/logreader/el8_amd64_gcc10/CMSSW_12_5_UBSAN_X_2022-08-01-1100/unitTestLogs/DQMOffline/Configuration#/186397-186397)

I have also reproduced those runtime errors locally with the last UBSAN IB [CMSSW_12_5_UBSAN_X_2022-08-01-1100](https://cmssdt.cern.ch/SDT/cgi-bin/showBuildLogs.py/el8_amd64_gcc10/www/mon/12.5.UBSAN-mon-11/CMSSW_12_5_UBSAN_X_2022-08-01-1100?utests).

Many thanks,
Andrea.

**Comment by makortel** [comment]
assign l1, upgrade

**Comment by makortel** [comment]
These errors come from `hls` external that was requested by L1 track trigger group. They are issued at dynamic library load time, that hints towards problem being in the `ap_*` classes rather than how they are used in CMSSW.

**Comment by makortel** [comment]
Looking more carefully, the global (constant) variable that is being loaded is
```
 #9 0x2b5ae8da24ba in __static_initialization_and_destruction_0 /data/cmsbld/jenkins/workspace/build-any-ib/w/tmp/BUILDROOT/951c41830a3a1981e906823024098032/opt/cmssw/el8_amd64_gcc10/cms/cmssw/CMSSW_12_5_UBSAN_X_2022-08-01-1100/src/DataFormats/L1TParticleFlow/interface/gt_datatypes.h:255
```
i.e.
https://github.com/cms-sw/cmssw/blob/2609b2988d91668897ed2112ec77c1ab876e25bb/DataFormats/L1TParticleFlow/interface/gt_datatypes.h#L255
The `etaphi_sf_t` is defined in
https://github.com/cms-sw/cmssw/blob/2609b2988d91668897ed2112ec77c1ab876e25bb/DataFormats/L1TParticleFlow/interface/gt_datatypes.h#L252
where the `AP_RND_CONV` is defined as
```cpp
enum ap_q_mode {
  AP_RND,         //< rounding to plus infinity
  AP_RND_ZERO,    //< rounding to zero
  AP_RND_MIN_INF, //< rounding to minus infinity
  AP_RND_INF,     //< rounding to infinity
  AP_RND_CONV,    //< convergent rounding
  AP_TRN,         //< truncation
  AP_TRN_ZERO,    //< truncation to zero
};
```
in https://github.com/Xilinx/HLS_arbitrary_Precision_Types/blob/200a9aecaadf471592558540dc5a88256cbf880f/include/ap_decl.h#L66-L74 and presumably has a value of 4, and the `AP_SAT` is defined as
```cpp
enum ap_o_mode {
  AP_SAT,      //< saturation
  AP_SAT_ZERO, //< saturation to zero
  AP_SAT_SYM,  //< symmetrical saturation
  AP_WRAP,     //< wrap-around (*)
  AP_WRAP_SM,  //< sign magnitude wrap-around (*)
};
```
https://github.com/Xilinx/HLS_arbitrary_Precision_Types/blob/200a9aecaadf471592558540dc5a88256cbf880f/include/ap_decl.h#L88-L94 and presumably has a value of 0. This is consistent with this line of the stack trace
```
#8 0x2b5ae8da24ba in ap_fixed<18, 5, (ap_q_mode)4, (ap_o_mode)0, 0>::ap_fixed(float) /data/cmsbld/jenkins/workspace/build-any-ib/w/el8_amd64_gcc10/external/hls/2019.08-80454731218d87c9edf8f512cb8429f9/include/ap_fixed.h:150
```
I did not trace how exactly that ends up being
```
#0 0x2b5ae8eb9c87 in ap_private<65, true, false>::clearUnusedBits() volatile /data/cmsbld/jenkins/workspace/build-any-ib/w/el8_amd64_gcc10/external/hls/2019.08-80454731218d87c9edf8f512cb8429f9/include/etc/ap_private.h:3397
```
but the definition of `ap_private::clearUnusedBits()`
```cpp
  INLINE void clearUnusedBits(void) volatile
// just for clang compiler
#if defined(__clang__) && !defined(__CLANG_3_1__)
      __attribute__((no_sanitize("undefined")))
#endif
  {
    pVal[_AP_N - 1] =
        _AP_S ? ((((int64_t)pVal[_AP_N - 1]) << (excess_bits)) >> excess_bits)
              : (excess_bits
                     ? ((pVal[_AP_N - 1]) << (excess_bits)) >> (excess_bits)
                     : pVal[_AP_N - 1]);
  }
```
https://github.com/Xilinx/HLS_arbitrary_Precision_Types/blob/200a9aecaadf471592558540dc5a88256cbf880f/include/etc/ap_private.h#L3390-L3401 shows potential for undefined behavior by casting the value to signed `int64_t` before the left shift. (oh, and apparently the UBSAN is turned off for this function for clang)

**Comment by cecilecaillol** [comment]
This seems related to ap_* classes rather than CMSSW so I dont think there is anything we can do from the l1 side

**Comment by cecilecaillol** [comment]
+l1
