### ISSUE TITLE
Consumes migration to fix for tk alignment Zmumu validation

### ISSUE THREAD

**Issue by venturana** [cms-sw/cmssw#38958]
Hello, 

An exception of category 'GetByLabelWithoutRegistration' occurred while running the zmumu validation with CMSSW_12_4_3.
`Exception Message:::getByLabel without corresponding call to consumes or mayConsumes for this module.`
For more info about this error check [1]

I've been told that there is a consumes migration to fix, therefore I open this ticket in this regard.
Thank you very much.

[1]:https://twiki.cern.ch/twiki/bin/view/CMSPublic/CMSTrackerAligmnentTroubleShooting#Issues_with_Zmumu_validation

**Comment by mmusich** [comment]
assign alca

**Comment by mmusich** [comment]
@venturana please post a minimal configuration file to reproduce the issue

**Comment by venturana** [comment]
[zmumu:ZMuMuValidation]
maxevents = -1
dataset = Dataset_Validation_DoubleMuon_Run2022C
etaminneg = -2.4
etamaxneg = 2.4
etaminpos = -2.4
etamaxpos = 2.4
ttrhbuilder = WithAngleAndTemplate
#minpt = 200
#maxpt = 1000
multiIOV = false

[plots:zmumu]
customrighttitle = pp collisions (2022) 13.6 TeV
resonance = Z
switchONfit = false
rebinphi = 4
rebinetadiff = 2
rebineta = 2
rebinpt = 8

[validation]
zmumu ZMuMuValidation - PCL_alignment:

**Comment by mmusich** [comment]
@venturana, the `ini` file from the all-in-one tool is of little use to non expert, please post a link to the cmssw configuration file that is leading to the failures

**Comment by venturana** [comment]
this https://github.com/cms-sw/cmssw/releases/tag/CMSSW_12_4_3

**Comment by tvami** [comment]
@venturana Marco ment like a line-by-line recipe that we can copy paste and leads to the error. Thanks

**Comment by venturana** [comment]
import FWCore.ParameterSet.Config as cms

process = cms.Process("ONLYHISTOS")

process.load("Alignment.OfflineValidation.Dataset_Validation_DoubleMuon_Run2022C_cff")
process.maxEvents = cms.untracked.PSet(
    input = cms.untracked.int32(int(-1 / 1))
)
process.source.skipEvents=cms.untracked.uint32(int(0*-1/1))

process.options = cms.untracked.PSet(
   wantSummary = cms.untracked.bool(False),
   Rethrow = cms.untracked.vstring("ProductNotFound"), # make this exception fatal
   fileMode  =  cms.untracked.string('NOMERGE') # no ordering needed, but calls endRun/beginRun etc. at file boundaries
)

process.load("FWCore.MessageLogger.MessageLogger_cfi")
process.MessageLogger.cerr.FwkReport.reportEvery = 1000
process.MessageLogger.cout.enableStatistics = cms.untracked.bool(True)


process.load("RecoVertex.BeamSpotProducer.BeamSpot_cff")
process.load("Configuration.Geometry.GeometryDB_cff")
process.load('Configuration.StandardSequences.Services_cff')
process.load("Configuration.StandardSequences.MagneticField_cff")

process.load("RecoMuon.DetLayers.muonDetLayerGeometry_cfi")
process.load("Geometry.MuonNumbering.muonNumberingInitialization_cfi")
process.load("RecoMuon.TrackingTools.MuonServiceProxy_cff")
process.load("Configuration.StandardSequences.Reconstruction_cff")


process.load("RecoTracker.TrackProducer.TrackRefitters_cff")
process.TrackRefitter.src = "ALCARECOTkAlZMuMu"
process.TrackRefitter.TTRHBuilder = "WithAngleAndTemplate"
process.TrackRefitter.NavigationSchool = ""


#Global tag
process.load("Configuration.StandardSequences.FrontierConditions_GlobalTag_cff")
from Configuration.AlCa.GlobalTag import GlobalTag
process.GlobalTag = GlobalTag(process.GlobalTag,"124X_dataRun3_Express_v4")


import CalibTracker.Configuration.Common.PoolDBESSource_cfi

process.conditionsInTrackerAlignmentRcd = CalibTracker.Configuration.Common.PoolDBESSource_cfi.poolDBESSource.clone(
     connect = cms.string('frontier://FrontierProd/CMS_CONDITIONS'),
     toGet = cms.VPSet(cms.PSet(record = cms.string('TrackerAlignmentRcd'),
                               tag = cms.string('TrackerAlignment_HGPCL_ForComparison2022_v1')
                               )
                      )
    )
process.prefer_conditionsInTrackerAlignmentRcd = cms.ESPrefer("PoolDBESSource", "conditionsInTrackerAlignmentRcd")


compressionSettings = 207
###### MuSclFit SETTINGS  ##############################################

### MuScleFit specific configuration

process.looper = cms.Looper(
    "MuScleFit",
    # Only used when reading events from a root tree
    MaxEventsFromRootTree = cms.int32(-1),

    # Specify a file if you want to read events from a root tree in a local file.
    # In this case the input source should be an empty source with 0 events.

    InputRootTreeFileName = cms.string(""),

    # Specify the file name where you want to save a root tree with the muon pairs.
    # Leave empty if no file should be written.

    OutputRootTreeFileName = cms.string(""),


    # Choose the kind of muons you want to run on
    # -------------------------------------------
    MuonLabel = cms.InputTag("TrackRefitter"),


    #MuonType = cms.int32(11),
    MuonType = cms.int32(5),

    # This line allows to switch to PAT muons. Default is false.
    # Note that the onia selection works only with onia patTuples.
    PATmuons = cms.untracked.bool(False),

    # ---------------- #
    # Select resonance #
    # ---------------- #
    # The resonances are to be specified in this order:
    # Z0, Y(3S), Y(2S), Y(1S), Psi(2S), J/Psi
    # -------------------------------------------------
    resfind = cms.vint32(
      int("Z" == "Z"),
      int("Z" == "Y3S"),
      int("Z" == "Y2S"),
      int("Z" == "Y1S"),
      int("Z" == "Psi2S"),
      int("Z" == "JPsi")
    ),

    # Likelihood settings
    # -------------------
    maxLoopNumber = cms.untracked.int32(1),
    # Select which fits to do in which loop (0 = do not, 1 = do)
    doResolFit =        cms.vint32(0),
    doScaleFit =        cms.vint32(0),
    doBackgroundFit =   cms.vint32(0),
    doCrossSectionFit = cms.vint32(0),

    # Use the probability file or not. If not it will perform a simpler selection taking the muon pair with
    # invariant mass closer to the pdf value and will crash if some fit is attempted.
    UseProbsFile = cms.untracked.bool(False),

    # False = use also MC information
    speedup = cms.bool(True),
    # Set this to false if you do not want to use simTracks.
    # (Note that this is skipped anyway if speedup == True).
    compareToSimTracks = cms.bool(False),

    # Output settings
    # ---------------
    # Use compressions settings of TFile
    # see https://root.cern.ch/root/html534/TFile.html#TFile:SetCompressionSettings
    # settings = 100 * algorithm + level
    # level is from 1 (small) to 9 (large compression)
    # algo: 1 (ZLIB), 2 (LMZA)
    # see more about compression & performance: https://root.cern.ch/root/html534/guides/users-guide/InputOutput.html#compression-and-performance

    OutputFileName = cms.untracked.string("zmumuHisto.root"),
    compressionSettings = cms.untracked.int32(compressionSettings), 

    # BiasType=0 means no bias to muon momenta
    # ----------------------------------------
    BiasType = cms.int32(0),
    parBias = cms.vdouble(),

    # SmearType=0 means no smearing applied to muon momenta
    # -----------------------------------------------------
    SmearType = cms.int32(0),
    parSmear = cms.vdouble(),

    ### taken from J/Psi #########################
#    ResolFitType = cms.int32(14),
#    parResol = cms.vdouble(0.007,0.015, -0.00077, 0.0063, 0.0018, 0.0164),
#    parResolFix = cms.vint32(0, 0, 0,0, 0,0),
#    parResolOrder = cms.vint32(0, 0, 0, 0, 0, 0),
    ResolFitType = cms.int32(0),
    parResol = cms.vdouble(0),
    parResolFix = cms.vint32(0),
    parResolOrder = cms.vint32(0),


    # -------------------- #
    # Scale fit parameters #
    # -------------------- #

    # -----------------------------------------------------------------------------------
#    ScaleFitType = cms.int32(18),
#    parScaleOrder = cms.vint32(0, 0, 0, 0),
#    parScaleFix =   cms.vint32(0, 0, 0, 0),
#    parScale = cms.vdouble(1, 1, 1, 1),
    ScaleFitType = cms.int32(0),
    parScaleOrder = cms.vint32(0),
    parScaleFix =   cms.vint32(0),
    parScale = cms.vdouble(0),



    # ---------------------------- #
    # Cross section fit parameters #
    # ---------------------------- #
    # Note that the cross section fit works differently than the others, it
    # fits ratios of parameters. Fix and Order should not be used as is, they
    # are there mainly for compatibility.
    parCrossSectionOrder = cms.vint32(0, 0, 0, 0, 0, 0),
    parCrossSectionFix =   cms.vint32(0, 0, 0, 0, 0, 0),
    parCrossSection = cms.vdouble(1.233, 2.07, 6.33, 13.9, 2.169, 127.2),

    # ------------------------- #
    # Background fit parameters #
    # ------------------------- #

    # Window factors for: Z, Upsilons and (J/Psi,Psi2S) regions
    LeftWindowBorder  = cms.vdouble(70., 8., 1.391495),
    RightWindowBorder = cms.vdouble(110., 12., 5.391495),

    # The two parameters of BgrFitType=2 are respectively:
    # bgr fraction, (negative of) bgr exp. slope, bgr constant
    # --------------------------------------------------------
    # The function types for resonances in a region must be the same
    BgrFitType = cms.vint32(2, 2, 2), # regions
    # These empty parameters should be used when there is no background
    parBgr = cms.vdouble(0., 0.,   0., 0.,   0., 0.,
                         0., 0.,   0., 0.,   0., 0.,   0.,0.,   0.,0.,   0.,0.),
    parBgrFix = cms.vint32(0, 0,   0, 0,   0, 0,
                           # The rest of the parameters is used for the resonance regions. They are automatically fixed in the code
                           # because they are never used to fit the background, but only after the rescaling.
                           1, 1,   1, 1,   1, 1,   1, 1,   1, 1,   1, 1),
    parBgrOrder = cms.vint32(0, 0,   0, 0,   0, 0,
                             0, 0,   0, 0,   0, 0,   0, 0,   0, 0,   0, 0),


    # ----------------------- #

    # Set Minuit fit strategy
    FitStrategy = cms.int32(1),


    # Fit accuracy and debug parameters
    StartWithSimplex = cms.bool(True),
    ComputeMinosErrors = cms.bool(False),
    MinimumShapePlots = cms.bool(True),

    ########## TO BE ENABLED ################################
    # Set the cuts on muons to be used in the fit
    MinMuonPt = cms.untracked.double(0.),
    MaxMuonPt = cms.untracked.double(1000.),
    MinMuonEtaFirstRange = cms.untracked.double(-2.4),
    MaxMuonEtaFirstRange = cms.untracked.double(2.4),
    MinMuonEtaSecondRange = cms.untracked.double(-2.4),
    MaxMuonEtaSecondRange = cms.untracked.double(2.4),
    PileUpSummaryInfo = cms.untracked.InputTag("addPileupInfo"),
    PrimaryVertexCollection = cms.untracked.InputTag("offlinePrimaryVertices"),

    # The following parameters can be used to filter events
    TriggerResultsLabel = cms.untracked.string("TriggerResults"),
    TriggerResultsProcess = cms.untracked.string("HLT"),
    TriggerPath = cms.untracked.vstring(""),
    # Negate the result of the trigger
    NegateTrigger = cms.untracked.bool(False),
    debug = cms.untracked.int32(0),
)





process.p = cms.Path(
    process.offlineBeamSpot*process.TrackRefitter
    )


print("Done")

**Comment by mmusich** [comment]
@venturana the configuration  you posted is not easily readable, please wrap it in triple quotes ````

**Comment by Dr15Jones** [comment]
@venturana please post the full exception message from the job. In general, when posting about a failure which involves an exception, it is best to include the entire message.

**Comment by venturana** [comment]
```----- Begin Fatal Exception 03-Aug-2022 15:04:26 CEST-----------------------
An exception of category 'GetByLabelWithoutRegistration' occurred while
   [0] Calling the 'duringLoop' method of a looper
Exception Message:
::getByLabel without corresponding call to consumes or mayConsumes for this module.
  type: std::vector<reco::Track>
  module label: TrackRefitter
  product instance name: ''
  process name: ''
----- End Fatal Exception -------------------------------------------------```

**Comment by Dr15Jones** [comment]
@venturana thanks for the full exception.

**Comment by Dr15Jones** [comment]
@makortel do we have consumes for loopers?

**Comment by makortel** [comment]
I see the `MuScleFit` EDLooper makes four calls to `getByLabel()`
https://github.com/cms-sw/cmssw/blob/762155bff5a6e9155a8d71ef49f95ed5dda51302/MuonAnalysis/MomentumScaleCalibration/plugins/MuScleFit.cc#L789-L790
https://github.com/cms-sw/cmssw/blob/762155bff5a6e9155a8d71ef49f95ed5dda51302/MuonAnalysis/MomentumScaleCalibration/plugins/MuScleFit.cc#L920-L921
https://github.com/cms-sw/cmssw/blob/762155bff5a6e9155a8d71ef49f95ed5dda51302/MuonAnalysis/MomentumScaleCalibration/plugins/MuScleFit.cc#L933-L934
https://github.com/cms-sw/cmssw/blob/762155bff5a6e9155a8d71ef49f95ed5dda51302/MuonAnalysis/MomentumScaleCalibration/plugins/MuScleFit.cc#L951-L952
and there are no calls to `consumes()`. These would need to be migrated to `consumes()` and `getByToken()` as described in
https://twiki.cern.ch/twiki/bin/view/CMSPublic/SWGuideEDMGetDataFromEvent#consumes
and https://twiki.cern.ch/twiki/bin/view/CMSPublic/SWGuideEDMGetDataFromEvent#get_ByToken

**Comment by mmusich** [comment]
I suspect the one that is triggering the crash is actually here:
https://github.com/cms-sw/cmssw/blob/762155bff5a6e9155a8d71ef49f95ed5dda51302/MuonAnalysis/MomentumScaleCalibration/plugins/MuScleFitMuonSelector.cc#L217-L221

called from here

https://github.com/cms-sw/cmssw/blob/762155bff5a6e9155a8d71ef49f95ed5dda51302/MuonAnalysis/MomentumScaleCalibration/plugins/MuScleFit.cc#L849

**Comment by mmusich** [comment]
assign tracker-dpg

**Comment by mmusich** [comment]
@venturana, so here is a possible solution: https://github.com/cms-sw/cmssw/pull/39029 (master) and https://github.com/cms-sw/cmssw/pull/39030 (12_4_X)

**Comment by tvami** [comment]
@venturana can you please add in the issue title that this is for the tk alignment Zmumu validation? As of now this issue title is very general, thanks

**Comment by mmusich** [comment]
+1 
   * solved at https://github.com/cms-sw/cmssw/pull/39029 (master) and https://github.com/cms-sw/cmssw/pull/39030 (12_4_X)
