### ISSUE TITLE
Anonymous namespace in CTPPSPixelIndices.h

### ISSUE THREAD

**Issue by makortel** [cms-sw/cmssw#38977]
I noticed an anonymous namespace being used in a header included in several places
https://github.com/cms-sw/cmssw/blob/eb2d3a59a3aa2a722da88f97059810aa841d35c1/CondFormats/PPSObjects/interface/CTPPSPixelIndices.h#L55-L72
The C++ core guidelines recommend against that http://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#Rs-unnamed

It would be better to enclose these constants in a named namespace.

**Comment by makortel** [comment]
assign alca

**Comment by makortel** [comment]
FYI @cms-sw/ctpps-dpg-l2

**Comment by tvami** [comment]
@grzanka @ChrisMisan can you please fix this? Thanks

**Comment by fabferro** [comment]
PR #38985 should solve this issue.

**Comment by tvami** [comment]
+alca
 * being resolved in https://github.com/cms-sw/cmssw/pull/38985

**Comment by makortel** [comment]
> Hi @makortel this came up in #39274 Could we update the CMS coding rules to include this? Thanks!

We've tried to not to replicate C++ code guidelines (much) into our coding rules in order to keep them concise. If anonymous namespaces in headers becomes a widespread problem, sure, we could consider adding something about them.
