### ISSUE TITLE
Investigation on multi-threading in repack jobs

### ISSUE THREAD

**Issue by germanfgv** [cms-sw/cmssw#38997]
After recent changes in Repack, T0 is now using LZMA-4 to compress RAW data. Due to this change, the duration of T0 jobs has increased considerably. While we are mostly able to repack in reasonable times, some jobs dealing with particularly large files may pose a problem.

Usually, Repack jobs are run in a single core, so we tried to explore the possibility of running multicore repack jobs for largs lumis. We found that there is little reduction on processing time, even when using 4 cores. We would like to understand why this is the case and see if something can be done to improve parallelization.

Here we have an example of a repack job that took 15h to be completed in production that can be use to debug the issue:
```
/afs/cern.ch/user/c/cmst0/public/LongExecution/RepackRun2022C/Run356945/job_1598682
```

**Comment by makortel** [comment]
assign core

**Comment by makortel** [comment]
An earlier discussion in https://mattermost.web.cern.ch/cms-o-and-c/pl/om99iu1dmfrdjf855beum7387w suggested that given the multiple output modules one could see improvement with 2 (or even 3) threads. I think it would be useful to investigate (at least a bit of) what exactly happens in the current repack jobs.

**Comment by Dr15Jones** [comment]
Looking at the job log in the directory given, the job is using 1 thread but is only 39% CPU efficient (CPU time is  21365.2 while the wallclock time is 54837.6). So even at 1 thread, the job is completely IO limited. Using more threads isn't going to help much.

**Comment by davidlange6** [comment]
Nothing here should be io limited:) it should be compression cpu limited

**Comment by davidlange6** [comment]
There are lots of stalls - eg, Here it spent 2 hours..

Begin processing the 2712th record. Run 356993, Event 2537640, LumiSection 145 on stream 0 at 08-Aug-2022 00:05:13.389 CEST
Begin processing the 2713th record. Run 356993, Event 2539460, LumiSection 145 on stream 0 at 08-Aug-2022 00:07:06.644 CEST

**Comment by makortel** [comment]
> There are lots of stalls - eg, Here it spent 2 hours.. 
> Begin processing the 2712th record. Run 356993, Event 2537640, LumiSection 145 on stream 0 at 08-Aug-2022 00:05:13.389 CEST 
> Begin processing the 2713th record. Run 356993, Event 2539460, LumiSection 145 on stream 0 at 08-Aug-2022 00:07:06.644 CEST

Umm, that is two minutes, no? (although still much longer than ideally)

**Comment by davidlange6** [comment]
Whoops:)

Anyway, that 2 minutes does not reproduce.

**Comment by davidlange6** [comment]
Anyway, seems this job would take O(200) minutes on an otherwise busy cern node - maybe input files need to be copied locally to improve the cpu efficiency?

**Comment by Dr15Jones** [comment]
So I took a look at the IO accounting in the framework job report. Nothing caught my eye there. But then I remembered that the input to this job is a Streamer file and the streamer code does not doing any IO accounting.

The Streamer source was not written for remote reads (such as EOS) in mind. It does simple Posix calls for each event, that means separate IO request round-trips each time a new event is requested. This is probably the cause of the very, very slow job.

**Comment by davidlange6** [comment]
Thats good to know! Thanks Chris. 

@germanfgv - Does the tier0 have the hardware to copy inputs locally for repack?

**Comment by makortel** [comment]
Just to check some of our assumptions, I ran the repack job with the first streamer file copied locally with IgProf (in this setup I got throughput of 4.2 events/s on cmsdev32 wrt. 0.9 events/s in the log). Here is the full profile https://mkortela.web.cern.ch/mkortela/cgi-bin/navigator/issue38997/run356993_ls0145/perf . Of the total of 1418 s
* `edm::PoolOutputModule::write()` took 1374 s (97 %) https://mkortela.web.cern.ch/mkortela/cgi-bin/navigator/issue38997/run356993_ls0145/perf/27 (it's all LZMA compression as one would expect)
* `edm::StreamerInputSource::deserializeEvent()` took 21 s (1.5 %) https://mkortela.web.cern.ch/mkortela/cgi-bin/navigator/issue38997/run356993_ls0145/perf/77 (still apparently using zlib)

**Comment by davidlange6** [comment]
and if the goal is jobs that run in a shorter amount of time, one can also use fewer lumis..

**Comment by makortel** [comment]
I continued with the first-lumi job, and got
* with 1 thread: 4.35 events/s throughput, >99 % efficient
* with 2 threads: 4.89 events/s throughput, 53 % efficient

The job has 5 OutputModules
* `write_Cosmics_RAW`, wrote 97 % of events
* `write_HLTPhysics_RAW`, wrote 0.9 % of events
* `write_HcalNZS_RAW`, wrote 0.01 % of events
* `write_MinimumBias_RAW`, wrote 3.6 % of events
* `write_NoBPTX_RAW`, wrote 26 % of events

and their load seems quite imbalanced.

I ran the stall monitor with 2 threads and 100 events, and it basically told that `write_Cosmics_RAW` is ~always stalled in the job (i.e. there just isn't enough concurrent work for 2 threads).

**Comment by makortel** [comment]
I made a distribution of the time differences between subsequent `Begin processing` printouts from the log of the original job (notice logarithmic y axis)
![repack_times](https://user-images.githubusercontent.com/33993/183505454-d9803d06-cde9-4f0a-b06c-39761bf45dbd.png)

and some quantile numbers
* `< 0.1 s`: 93.4 % of events
* `0.1 .. 1 s`: 3.5 % of events
* `1 .. 25 s`: 2.5 % of events
* `> 25 s`: 0.6 % of events

**Comment by davidlange6** [comment]
I guess there is some variation in Eos read performance then... I tried rerunning my job with local files and see essentially no difference (eg, 10s of seconds improvement over the job).  There is a low rate of events taking >1 second in my tests. Some correspond to output module activity (or at least memory increases) or are reproducible (eg, event 657)

**Comment by drkovalskyi** [comment]
Please keep in mind that even if local input helps, we have no space to copy the streamer file on a worker node - we have limited amount of space per core and blocking many cores is very inefficient.

**Comment by drkovalskyi** [comment]
On the other hand, our biggest problem is that all these slow jobs create manual work for operators. If we have a procedure to retry that has a better success rate that would help. At the moment we have two options for retries:

1. Relax compression
2. Use two cores

Do you see any other options that may help?

**Comment by jeyserma** [comment]
A few weeks ago I did some timing/efficiency studies for repacking as a function of the #threads, comparing the old and new compression algorithms. See the plots below for reference, it's in line with the expectations: 1) LZMA takes much longer, and 2) we don't benefit much from switching to multithreading. So when switching to 2 cores we won't increase the time considerably. 

![raw_timing](https://user-images.githubusercontent.com/6769946/183872838-02a45095-5ddc-42b8-9c5c-333d10922878.png)
![raw_eff](https://user-images.githubusercontent.com/6769946/183872844-8b6b7b3f-a924-4c62-8207-4e44196ec13c.png)

**Comment by dpiparo** [comment]
The above figures are interesting. We switched to LZMA to save tape, disk and network obtaining 10-15% smaller RAW. This came at a cost, the CPU needed is more to get to these smaller sizes. 
Now, it's unclear to me if we are facing an inefficiency of the computing infrastructure (e.g. EOS or network performance) causing much longer jobs than expected or we are looking to quicker repack jobs in general.
If we consider the first case, something which can be done is to make the remote reading of streamer files lighter. As @Dr15Jones pointed out, it seems we are reading events in streamer files one by one https://github.com/cms-sw/cmssw/blob/master/IOPool/Streamer/src/StreamerInputFile.cc#L114 . This is rather inefficient: we are paying a latency per event as well as loading the tier-0 network and EOS with sparse traffic. It would be much more desirable to have fewer and bigger read requests over the network, to reduce the aforementioned load. Perhaps something as simple as a StreamerInputFile new data member acting as a buffer of configurable size could be enough.

**Comment by davidlange6** [comment]
Could you elaborate? An 8 core prompt reading from Eos takes much less than the vo card local disk requested by cms so there is extra disk around on average. Or do we not allocate disk  in pilots in the same way we can allocate memory?

**Comment by dpiparo** [comment]
I think we schedule on # cores, memory and accelerators and not (yet?) on scratch space. It is true that with 20-30 GB we could think there is enough room on the local disk to copy streamer files locally but we ought to be sure of that this will not result under any circumstances in random storm of failing jobs b/c of lack of storage on the device, no?

**Comment by drkovalskyi** [comment]
Danilo summarized it well. We were always using cores as a proxy for the scratch space assuming we have 20GB/core.

**Comment by davidlange6** [comment]
Ok, so scratch is handled differently than memory. Thats unfortunate.  But so how did this work in 2018? We allocated two cores for each repack?

**Comment by drkovalskyi** [comment]
We compute how much memory we need and then based on that request how many cores we require. This was introducing significant inefficiency in repacking since the second core was mostly idling. Now we revised the calculation dropping the requirement to have extra space for a local input and we are back to reasonable efficiency now.

**Comment by makortel** [comment]
It turns out that the example job is using `lazy-download` via
```py
process.SiteLocalConfigService = cms.Service("SiteLocalConfigService",
    overrideSourceCacheHintDir = cms.untracked.string('lazy-download')
)
```
and the `XrdFile` gets 128 MB read requests that it splits into 8 MB reads downstream.

**Comment by aperezca** [comment]
Hi, just to comment that in HTCondor, given that we are using partitionable slots in our pools, one can request number of CPU cores, memory and disk independently. See in
https://htcondor.readthedocs.io/en/latest/man-pages/condor_submit.html

sections concerning request_cpus, request_disk and request_memory.

I would say we have simply not paid much attention to disk in the past in terms of workload scheduling, as CPU cores and memory were the main constraints.

**Comment by makortel** [comment]
I analyzed a bit more the timestamps from the example log. The plot below shows the event processing progress as a function of time since the timestamp of the first event for the first 5k event.

![repack_cumulative](https://user-images.githubusercontent.com/33993/183989196-cecf593f-98c8-424b-8e6e-fd788a417c5d.png)

Notice how the processing (increasing line) and stalls (flat line) alternate (the same continues throughout the job, except for the last ~4k events). The time differences between the first events after the stall are around 3 minutes, below is a distribution of those
![repack_stalls_start](https://user-images.githubusercontent.com/33993/183990709-1c9aeecc-f5f8-4505-a808-e928e1a9cb8f.png)


My first thought would be the stalls would be related to reading input, but in my local test the first read by `XrdFile` after the job start was after event 813, and here the stalls around that are between events 435..436, and 845..846.

**Comment by smorovic** [comment]
Hi @dpiparo.
Streamer file reading could indeed benefit from read-ahead.
`StreamerInputFile::readEventMessage()` now does two reads per event, once for event header (which contains payload size) and then the payload.
It could instead read a larger fixed size (configurable amount), and then read again only when this is exhausted, with some care to handle correctly header and payload at the buffer boundary.
I will try to improve it next week (when I'm back).

**Comment by dpiparo** [comment]
@makortel thanks for pointing out that the XrdFile is handling the bunched requests behind the scenes: it escaped my attention while following the calling sequence.
I have two, mabe naive, questions:
 - Do you see the same stalls if reading from the local disk?
 - Do you see a different "stall pattern" if you modify the size of the chunks from 8 MB to a smaller or larger value?

**Comment by makortel** [comment]
> * Do you see the same stalls if reading from the local disk?

To clarify, the pattern in https://github.com/cms-sw/cmssw/issues/38997#issuecomment-1211110190 is from the log from T0 itself. I have not seen such stalls when running myself with either local disk input or input from EOS (which, I believe, is consistent what @davidlange6 wrote in https://github.com/cms-sw/cmssw/issues/38997#issuecomment-1209188591).

I'm running more tests to try to understand the behavior in the first place. Naively looking the stalls in https://github.com/cms-sw/cmssw/issues/38997#issuecomment-1211110190 do not coincide with the moments where `LocalCacheFile` issues the 128 MB read to `XrdFile`, and `XrdFile` issues the split 8 MB reads downstream, but I could be fooled by some things being asynchronous.

**Comment by davidlange6** [comment]
Right. I did make a graphic showing event-to-event correlations here (I don't think this is the right way to look at the data, but it shows that the two tests I did (with and without copying the data) have little spread compared to my test vs the t0 one)

![d1do](https://user-images.githubusercontent.com/5042883/184221158-0981b95e-8d16-481b-9190-0e66483940c6.png)
![d1d2](https://user-images.githubusercontent.com/5042883/184221171-2afece11-e2e0-473f-90bc-61a3b3f55e75.png)

**Comment by makortel** [comment]
Here is one correlation I observed between the log from T0 and my local tests (reading the streamer remotely). The Tier0 log had a total of 287 stalls (of longer than 25 s). Of these, 272 correlate to Events for which some OutputModule actually compresses+writes the data out. I did the correlation with `StallMonitor` as follows, assuming the behavior of OutputModules themselves would be reproducible between my tests and T0:
* an OutputModule runs for Event `N` for a "long time" (I took > 200 ms, in practice the time was 5-8 seconds), and
* the Tier0 log shows > 25 between the beginning of Event `N` and Event `N+1`

15 of the stalls in the T0 log did not correlate to OutputModule "writes". Vast majority of OutputModule "writes" (1553 in total with my definition of above) did not correlate to stalls in T0 log.

Is this an accidental correlation? Or could it possibly be a sign of a smoking gun?

**Comment by makortel** [comment]
I took a look of the reads (as seen by `XrdFile`, i.e. issued by `LocalCacheFile`) as well in the T0 log. There are total of 64 of them. 4 of the 64 reads coincide with a stall (i.e. the read is between events for which there is >25 s pause in processing). 2 of 4 coincide with a stall coinciding with an OutputModule write (as defined in https://github.com/cms-sw/cmssw/issues/38997#issuecomment-1212550020)., and the other 2 with a stall that does not coincide with a write.

I'm tempted to conclude that the input is not causing the stalls (unless there is some really strange asynchronous activity going on, as far as I can tell both `LocalCacheFile` and `StreamerFileReader` expect synchronous I/O calls.

@germanfgv Do you have any information about the node where this job was run? Like
* Is there any virtualization layer between the job and the bare metal? (if yes, is there any chance for the bare metal machine to get oversubscribed?)
* Is the job's working directory on a local disk? (that is really part of the bare metal) Same for `/tmp` (even if it looks that input would not be the problem)?

**Comment by smorovic** [comment]
In #39088 I implemented prebuffering in the streamer source, with a configurable parameter (100 MB could be a reasonable value to try).
I suggest to try it out and see what impact it has on Tier0 jobs.

**Comment by makortel** [comment]
@germanfgv Would you happen to have more examples of troublesome repack jobs?

**Comment by germanfgv** [comment]
Let me look for some recent examples.

**Comment by makortel** [comment]
I tried out #39088 in local test with 128 MB buffer size and without the `lazy-download`. As expected, the `XrdFile` saw the same read requests as currently with `lazy-download`. I'd think in the leading order the #39088 would not help towards EOS read issues (but those do not seem to be the cause here anyway), but it would help in reducing the local(?) disk use (in terms of both disk space and number of operations),

**Comment by germanfgv** [comment]
Recent repack jobs have finished in less that 6h. Here is one example:
It took 5.25h, with a 93.7% CPU efficient
```
/afs/cern.ch/user/c/cmst0/public/LongExecution/RepackRun2022D/Run357637/job_82932
```

**Comment by makortel** [comment]
Thanks @germanfgv. I analysed the job in similar way. Here is first the distribution of the timestamp differences between adjacent events
![repack_times](https://user-images.githubusercontent.com/33993/185488655-ebd710dc-edde-44b6-86ac-52882942996a.png)
and quantiles
* `< 0.1 s` : 40549
* `0.1 .. 1 s` : 1520
* `1 .. 25 s` : 1378
* `>= 25 s` : 97

Here is the event processing progress plot (event number vs time from the first event) for the first 5k events
![repack_cumulative](https://user-images.githubusercontent.com/33993/185489176-2adaa81b-c888-47d6-a27f-e9cc134f1cf0.png)

To me these plots and numbers tell that while the stalls are not nearly as bad as in the first job, they are still there.

I examined the 97 ">= 25 s" stalls in more detail, and 96 of them coincide to an event where an OutputModule is writing to disk. The other 1 event coincided with an `XrdFile` reading data from EOS. (I re-ran the full job to see where `XrdFile` reads and OutputModules write).

**Comment by makortel** [comment]
One way to get further confirmation that the OutputModule writes would be (part of) the culprit would be to add the `StallMonitor` service to the repack jobs, and investigate the log file it produces. In the two example jobs the log size of the full job has been O(10 MB). This could be done with e.g.
```py
process.add_(cms.Service("StallMonitor", fileName = cms.untracked.string("stallMonitor.log")))
```
and collecting the `stallMonitor.log` file among other log files.

But I don't know how feasible this setup would be from the Tier0 point of view. Maybe we could learn something already from one or two repack replays?

**Comment by makortel** [comment]
#39088 is part of 12_5_0_pre5. @germanfgv Is the pre-release something Tier0 could test? I'd suggest to start with 128 MB buffer on the source with
```py
process.source.prefetchMBytes = cms.untracked.uint32(128)
```
to match with the behavior of `lazy-download`, and disable the `lazy-download` for the test.

**Comment by germanfgv** [comment]
We cannot add this parameter in a regular replay test, but we can create a single job to test it.

**Comment by makortel** [comment]
I suppose there is nothing to add to this issue. For new slow-down cases at Tier0 a new issue would be better, and in case there would be interest to revive the tests suggested in the last messages, we can re-open this issue.

**Comment by makortel** [comment]
+core

**Comment by makortel** [comment]
@cmsbuild, please test

**Comment by smuzaffar** [comment]
closign it as it looks complete
