### ISSUE TITLE
Fatal Exception: Requested UserInt pileupJetId:fullId not available when using custom_jme_cff.py in CMSSW_10_6_X

### ISSUE THREAD

**Issue by y19y19** [cms-sw/cmssw#39086]
Hi,

I want to privately produce NanoAOD with PuppiAK4 jets for RunII UL2018 analysis, so I want to find a way of customizing the jet collections. I tried the cmsDriver.py with customized commands:
`
from PhysicsTools.NanoAOD.custom_jme_cff import PrepJMECustomNanoAOD_MC
process = PrepJMECustomNanoAOD_MC(process)
`
The full cmsDriver command is shown at the end (with DYJets dataset as example), and when I use cmsRun to run some events, it generates the error:

----- Begin Fatal Exception 16-Aug-2022 14:26:23 CDT-----------------------
An exception of category 'UnknownUserInt' occurred while
   [0] Processing  Event run: 1 lumi: 121119 event: 327260883 stream: 7
   [1] Running path 'nanoAOD_step'
   [2] Calling method for module SimpleCandidateFlatTableProducer/'jetTable'
Exception Message:
Requested UserInt pileupJetId:fullId is not available! Possible UserInts are: 
hfadjacentEtaStripsSize hfcentralEtaStripSize leptonPdgId puId106XUL16APVId puId106XUL16Id puId106XUL17Id puId106XUL18Id puId80XfullId puId_nCharged qgl_mult tightId tightIdLepVeto vtxNtrk 
----- End Fatal Exception -------------------------------------------------

It seems that it cannot find the correct pileup ID to use. I tried to debug but I am not familiar enough with NanoAOD. It also shows a warning message that it cannot find jet energy corrections.

%MSG-w L3Absolute not found:  PATJetUpdater:updatedPatJetsAK4PFCHSFinal  16-Aug-2022 14:26:05 CDT Run: 1 Event: 327260854
L2L3Residual and L3Absolute are not part of the jetCorrFactors
of module patJetCorrFactorsAK4PFCHSFinal. Jets will remain uncorrected.
%MSG

Please let me know if there is a way to add ak4puppi into NanoAOD with CMSSW_10_6_X.

`
cmsDriver.py --python_filename DYJetsToLL_M-50_RunIISummer20UL18_NanoAOD_1_cfg.py --eventcontent NANOAODSIM --customise Configuration/DataProcessing/Utils.addMonitoring --datatier NANOAODSIM --fileout file:nano.root --conditions 106X_upgrade2018_realistic_v15_L1v1 --step NANO --filein dbs:/DYJetsToLL_M-50_TuneCP5_13TeV-amcatnloFXFX-pythia8/RunIISummer20UL18MiniAOD-106X_upgrade2018_realistic_v11_L1v1-v1/MINIAODSIM --era Run2_2018,run2_nanoAOD_106Xv1 --no_exec --mc -n 50 --nThread 8 --customise_commands="process.add_(cms.Service('InitRootHandlers', EnableIMT = cms.untracked.bool(False)))\nfrom PhysicsTools.NanoAOD.custom_jme_cff import PrepJMECustomNanoAOD_MC\nprocess = PrepJMECustomNanoAOD_MC(process)\n"
`

**Comment by makortel** [comment]
assign xpog

**Comment by vlimant** [comment]
@y19y19 where did you get the instructions for constructing your configuration from ?
what release did you use?

**Comment by vlimant** [comment]
please close

**Comment by smuzaffar** [comment]
let me reopen this as I want to check why bot did not recognize https://github.com/cms-sw/cmssw/issues/39086#issuecomment-1299781991 comment

**Comment by smuzaffar** [comment]
@vlimant , looks like bot is working properly. It could be that webhook about your [comment](https://github.com/cms-sw/cmssw/issues/39086#issuecomment-1299781991) did not reach bot, in such cases just commenting again should work
