### ISSUE TITLE
LLVM 14: bitwise-instead-of-logical warnings

### ISSUE THREAD

**Issue by smuzaffar** [cms-sw/cmssw#39105]
[LLVM 14 tests](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-53867e/26901/build-logs/) shows a lot (over 30K) `bitwise-instead-of-logical` warning types . Some of these are in [a]. @VinInn mentioned [here](https://github.com/cms-sw/cmssw/pull/3742#issuecomment-42571454) that some time using bitwise if faster then logical operation. 

What should we do with these warnings? should we replace all bitwise operators to logical or disabled the warning for selected cases and fix the rest by using logical operators? 

[a]
```
grep ': warning:' build.log | grep CMSSW_12_5_CLANG_X_2022-08-17-2300/src/ | sort | uniq  | grep -v 'bitwise-instead-of-logical' |wc -l
215
   1050 DataFormats/GeometrySurface/interface/SimpleDiskBounds.h:21:13: warning: use of bitwise '&' with boolean operands [-Wbitwise-instead-of-logical]
   1050 DataFormats/GeometrySurface/interface/SimpleDiskBounds.h:22:13: warning: use of bitwise '&' with boolean operands [-Wbitwise-instead-of-logical]
   1578 DataFormats/TrackerRecHit2D/interface/trackerHitRTTI.h:30:13: warning: use of bitwise '|' with boolean operands [-Wbitwise-instead-of-logical]
   1581 DataFormats/TrackerRecHit2D/interface/trackerHitRTTI.h:31:12: warning: use of bitwise '|' with boolean operands [-Wbitwise-instead-of-logical]
   1581 DataFormats/TrackerRecHit2D/interface/trackerHitRTTI.h:35:64: warning: use of bitwise '&' with boolean operands [-Wbitwise-instead-of-logical]
   1581 DataFormats/TrackerRecHit2D/interface/trackerHitRTTI.h:36:62: warning: use of bitwise '|' with boolean operands [-Wbitwise-instead-of-logical]
   1581 DataFormats/TrackerRecHit2D/interface/trackerHitRTTI.h:37:58: warning: use of bitwise '&' with boolean operands [-Wbitwise-instead-of-logical]
   1581 DataFormats/TrackerRecHit2D/interface/trackerHitRTTI.h:39:14: warning: use of bitwise '&' with boolean operands [-Wbitwise-instead-of-logical]
   1584 DataFormats/TrackerRecHit2D/interface/trackerHitRTTI.h:36:63: warning: use of bitwise '&' with boolean operands [-Wbitwise-instead-of-logical]
   1584 DataFormats/TrackerRecHit2D/interface/trackerHitRTTI.h:39:13: warning: use of bitwise '|' with boolean operands [-Wbitwise-instead-of-logical]
  12924 DataFormats/GeometrySurface/interface/GloballyPositioned.h:157:9: warning: use of bitwise '&' with boolean operands [-Wbitwise-instead-of-logical]
```

**Comment by smuzaffar** [comment]
assign core

**Comment by makortel** [comment]
A quick search suggests either the use of logical operations, or explicit cast to (unsigned) int for either operand to silence the warning (for the cases where the behavior of bitwise operation is desired).

The performance impact is really a question of tradeoff between the cost of a branch (logical operation) vs the cost of always executing the right-hand side (bitwise operation).

By quick look on those three files, the use of bitwise operations _could_ be legitimate (at least the boolean expressions do not contain any side effects).

**Comment by Dr15Jones** [comment]
@makortel did you check in godbolt what the optimizer does? I'd bet it does the same operations for bool used for & or &&.

**Comment by Dr15Jones** [comment]
> did you check in godbolt what the optimizer does? I'd bet it does the same operations for bool used for & or &&.

Indeed, they are the same

https://godbolt.org/z/qc3hcqPnT

**Comment by makortel** [comment]
Seems that things have improved in ~10 years :) I remember seeing (in kd-tree implementation) a noticeable impact on performance back then. Going back with godbolt I see gcc 4.6 still emits a branch with `&&`, whereas gcc 4.7 results in equal code. (for clang I see the same between versions 3.6 and 3.7)

On the other hand, a bit more complicated with comparison expressions still shows a branch with `&&` https://godbolt.org/z/cqdvsTr7P

**Comment by VinInn** [comment]
again:
The use of bitwise operators IS intentional!
logical operators force the compiler to evaluate them in sequence as the following maybe ill formed if previous fails
(for instance ``` p&&(*p).ok()```) and introduce branches while bitwise operators can be evaluated in any order (even in parallel) and do not require branches.
I'm very sorry for llvm.

**Comment by smuzaffar** [comment]
+core
this was fixed, we have disabled the warnings
