### ISSUE TITLE
Compilation failure in HOCalibAnalyzer

### ISSUE THREAD

**Issue by makortel** [cms-sw/cmssw#39134]
The `el8_ppc64le_gcc10` and `el8_aarch64_gcc10` builds if CMSSW_12_5_X_2022-08-21-2300 showed compilation errors in `Calibration/HcalCalibAlgos/plugins/HOCalibAnalyzer.cc`
```
/data/cmsbuild/jenkins_b/workspace/build-any-ib/w/tmp/BUILDROOT/cf36689df96eed60adf535aa20985b0f/opt/cmssw/el8_aarch64_gcc10/cms/cmssw/CMSSW_12_5_X_2022-08-21-2300/src/Calibration/HcalCalibAlgos/plugins/HOCalibAnalyzer.cc: In member function 'virtual void HOCalibAnalyzer::analyze(const edm::Event&, const edm::EventSetup&)':
  /data/cmsbuild/jenkins_b/workspace/build-any-ib/w/tmp/BUILDROOT/cf36689df96eed60adf535aa20985b0f/opt/cmssw/el8_aarch64_gcc10/cms/cmssw/CMSSW_12_5_X_2022-08-21-2300/src/Calibration/HcalCalibAlgos/plugins/HOCalibAnalyzer.cc:457:59: error: call of overloaded 'Max(double, int)' is ambiguous
   457 |       double elos = 1.0 / TMath::Max(0.1, abs(1.0 * hoang));
      |                                                           ^
```
https://cmssdt.cern.ch/SDT/cgi-bin/buildlogs/el8_aarch64_gcc10/CMSSW_12_5_X_2022-08-21-2300/Calibration/HcalCalibAlgos

The ambiguity is caused by `0.1` being `double`, and non-qualified `abs()` returning `int` (`hoang` itself is declared as `float`).

**Comment by makortel** [comment]
assign alca

**Comment by makortel** [comment]
I can't tell why we see this issue only now. https://github.com/cms-sw/cmssw/pull/39089 was merged since the previous successful `ppc64le` / `aarch64` builds (CMSSW_12_5_X_2022-08-19-2300), but as far as I can tell it does not touch anything related to the offending line.

**Comment by makortel** [comment]
Is the conversion to `int` intentional in `abs(1.0 * hoang)`? If not, the line could be changed to
```cpp
double elos = 1.0 / std::max(0.1, static_cast<double>(std::abs(hoang)));
```
(not sure if the explicit cast to `double` is really needed)

**Comment by smuzaffar** [comment]
I think the removal of `using namespace std;` [here[(https://github.com/cms-sw/cmssw/pull/39089/files#diff-8b78e30bb2687c39aaf6693591f93460d0873b31ce5a451c9736d093d3345a56L55) caused this. just use `sdt::abs` should fix this

**Comment by makortel** [comment]
Good catch! I would nevertheless recommend replacing `TMath::Max()` with `std::max()`.

**Comment by tvami** [comment]
@bsunanda please fix this, thanks!

**Comment by tvami** [comment]
+alca 
 * resolved in https://github.com/cms-sw/cmssw/pull/39142
