### ISSUE TITLE
FWLite build errors 

### ISSUE THREAD

**Issue by smuzaffar** [cms-sw/cmssw#39212]
@cecilecaillol @cms-sw/orp-l2 , Looks like https://github.com/cms-sw/cmssw/pull/38442 broke [fwlite builds](https://cmssdt.cern.ch/SDT/cgi-bin/showBuildLogs.py/fwlite/el8_amd64_gcc10/www/thu/12.5-thu-23/CMSSW_12_5_X_2022-08-25-2300) as it added dependency on [L1Trigger/Phase2L1GMT/interface/Constants.h](https://github.com/cms-sw/cmssw/blob/master/L1Trigger/Phase2L1GMT/interface/Constants.h) for `DataFormats/L1TMuonPhase2`

I can fixed it by updating [FWLite configuration](https://github.com/cms-sw/cmsdist/blob/IB/CMSSW_12_5_X/master/fwlite_build_set.file) to include `L1Trigger/Phase2L1GMT/interface/Constants.h` too but please check if L1Trigger/Phase2L1GMT/interface/Constants.h is really required

**Comment by smuzaffar** [comment]
please note that fwlite releases are build using a limited number of cmssw packages. List of what is included in fwlite release is defined in https://github.com/cms-sw/cmsdist/blob/IB/CMSSW_12_5_X/master/fwlite_build_set.file. As L1Trigger/Phase2L1GMT package is not part of fwlite distribution that is why build fails complaining about missing header.  There are couple ways to fix this issue

1. As it is just a source level dependency , so we can just update `fwlite_build_set.file`  and include missing header there
2. This header is only used in packages [a], so may be we can just move it in to `DataFormats/L1TMuonPhase2` itself

I would prefer (2)

[a]
```
./DQMOffline/L1Trigger/src/L1TPhase2MuonOffline.cc:#include "L1Trigger/Phase2L1GMT/interface/Constants.h"
./DataFormats/L1TMuonPhase2/interface/SAMuon.h:#include "L1Trigger/Phase2L1GMT/interface/Constants.h"
./DataFormats/L1TMuonPhase2/interface/TrackerMuon.h:#include "L1Trigger/Phase2L1GMT/interface/Constants.h"
./L1Trigger/Phase2L1GMT/interface/PreTrackMatchedMuon.h:#include "L1Trigger/Phase2L1GMT/interface/Constants.h"
./L1Trigger/Phase2L1GMT/interface/MuonROI.h:#include "L1Trigger/Phase2L1GMT/interface/Constants.h"
./L1Trigger/Phase2L1GMT/interface/TopologicalAlgorithm.h:#include "L1Trigger/Phase2L1GMT/interface/Constants.h"
./L1Trigger/Phase2L1GMT/interface/TrackMuonMatchAlgorithm.h:#include "L1Trigger/Phase2L1GMT/interface/Constants.h"
./L1Trigger/Phase2L1GMT/interface/ConvertedTTTrack.h:#include "L1Trigger/Phase2L1GMT/interface/Constants.h"
./L1Trigger/Phase2L1GMT/plugins/Phase2L1TGMTSAMuonProducer.cc:#include "L1Trigger/Phase2L1GMT/interface/Constants.h"

```

**Comment by smuzaffar** [comment]
I opened https://github.com/cms-sw/cmssw/pull/39213 to move move the header into dataformat package.

**Comment by perrotta** [comment]
> I opened #39213 to move move the header into dataformat package.

Thank you Shahzad!
That seems to be the best option

**Comment by perrotta** [comment]
assign @cms-sw/l1-l2

**Comment by perrotta** [comment]
@cbotta

**Comment by makortel** [comment]
> > I opened #39213 to move move the header into dataformat package.
> 
> Thank you Shahzad! That seems to be the best option

I agree, even outside of FWLite a DataFormat package should not depend a package under L1Trigger.

**Comment by perrotta** [comment]
FWLITE build is succesfull in CMSSW_12_5_X_2022-08-26-2300 after https://github.com/cms-sw/cmssw/pull/39213: thank you @smuzaffar 
I think that this issue can be closed now

**Comment by smuzaffar** [comment]
agree , closing it now

**Comment by davidlange6** [comment]
> On Aug 26, 2022, at 11:48 AM, Malik Shahzad Muzaffar ***@***.***> wrote:
> 
> 
> @cecilecaillol @cms-sw/orp-l2 , Looks like #38442 broke fwlite builds as it added dependency on L1Trigger/Phase2L1GMT/interface/Constants.h for DataFormats/L1TMuonPhase2
> 
> I can fixed it by updating FWLite configuration to include L1Trigger/Phase2L1GMT/interface/Constants.h too but please check if L1Trigger/Phase2L1GMT/interface/Constants.h is really required

Please don't . DataFormats should not depend on L1Trigger.. (not sure why this is repeatedly a problem - I guess the build system needs a script to catch this at PR time)
