### ISSUE TITLE
Fail comparison of the empty simPVZ (MTD vertices) in PR test

### ISSUE THREAD

**Issue by srimanob** [cms-sw/cmssw#39214]
This issue is to follow the issue of always fail comparison of the empty simPVZ histogram under MTD vertices.

FYI @fabiocos @perrotta I think we did have a short discussion on this before but I can't find it. We can close this issue if already open.

<img width="261" alt="Screen Shot 2565-08-26 at 19 22 05" src="https://user-images.githubusercontent.com/4701449/186902741-ade6500d-a228-4d7c-b6f2-b7b1a977fd98.png">

**Comment by tvami** [comment]
assign upgrade

**Comment by perrotta** [comment]
assign @cms-sw/mtd-dpg-l2 @cms-sw/dqm-integration-developers

**Comment by perrotta** [comment]
assign l1 mtd-dpg

**Comment by makortel** [comment]
assign dqm, mtd-dpg

**Comment by fabiocos** [comment]
I am busy with other issues on the short term, but I am aware of this problem, and I'll come back to this asap.

**Comment by perrotta** [comment]
It look like that after the merging of https://github.com/cms-sw/cmssw/pull/39490 there are no more failing comparisons in the tests for the MTD vertices. 
This issue can be closed then

**Comment by srimanob** [comment]
+upgrade

**Comment by makortel** [comment]
These symptoms occurred again in https://github.com/cms-sw/cmssw/pull/41309#issuecomment-1503817220 for workflows 39496.0 and 39500.0
![image](https://user-images.githubusercontent.com/33993/231517155-9be0470e-1b93-4667-9863-373a49786a23.png)

**Comment by slava77** [comment]
differences in empty plots are probably from NaNs

**Comment by fabiocos** [comment]
the fix for this issue was merged in CMSSW_12_6_0_pre3 , see https://cmssdt.cern.ch/SDT/ReleaseNotes/CMSSW_12/CMSSW_12_6_0_pre3.html
The latest problem appears to happen in CMSSW_12_5_X integration, where the fix was not yet merged.

**Comment by makortel** [comment]
> The latest problem appears to happen in CMSSW_12_5_X integration, where the fix was not yet merged.

Thanks, good point. So the issue is kind of expected, but possibly not worth of addressing.
