### ISSUE TITLE
UBSAN issue in TrackListMerger

### ISSUE THREAD

**Issue by smuzaffar** [cms-sw/cmssw#39229]
As a follow up on https://github.com/cms-sw/cmssw/pull/37384 , the suggested change https://github.com/cms-sw/cmssw/pull/37384#issuecomment-1095361635 [a] by @mmusich works for me. Workflow `2323.4.0` did not fail [b] and ubsan issue about `RecoTracker/FinalTrackSelectors/plugins/TrackListMerger.cc:451:45: runtime error: variable length array bound evaluates to non-positive value 0` is also fixed.  May be we can also move https://github.com/cms-sw/cmssw/blob/master/RecoTracker/FinalTrackSelectors/plugins/TrackListMerger.cc#L364 after the check [a]

@cms-sw/reconstruction-l2  what do you suggest?

[a]
``` 
+  if (ngood == 0) {
+    // output empty collections and early return
+    this->returnEmptyCollections(e);
+    return;
+  }
```

[b]
```
23234.0_TTbar_14TeV+2026D49+TTbar_14TeV_TuneCP5_GenSimHLBeamSpot14INPUT+DigiTrigger+RecoGlobal+HARVESTGlobal Step0-PASSED Step1-PASSED Step2-PASSED Step3-PASSED  - time date Mon Aug 29 12:01:40 2022-date Mon Aug 29 11:32:36 2022; exit: 0 0 0 0
1 1 1 1 tests passed, 0 0 0 0 failed
```

**Comment by smuzaffar** [comment]
assign reconstruction

**Comment by mmusich** [comment]
I've created https://github.com/cms-sw/cmssw/pull/39233 with my original suggestion (not yet tested in the last IB), to start the discussion.
