### ISSUE TITLE
Random comparison failures in L1 phase 2 muon histograms

### ISSUE THREAD

**Issue by makortel** [cms-sw/cmssw#39236]
Phase2 workflows show randomly differences in PR tests (of completely unrelated changes) in `L1T/L1TPhase2/Muons/{SAMuon,TkMuon}/efficiencies/globalEfficiencies` histograms, like
![image](https://user-images.githubusercontent.com/33993/187005584-55544952-902a-4900-abf4-1b5ade6ee877.png)

**Comment by makortel** [comment]
assign dqm, l1

**Comment by cecilecaillol** [comment]
@folguera Any idea?

**Comment by makortel** [comment]
I observed these first in https://github.com/cms-sw/cmssw/pull/39156#issuecomment-1229047386 that were run on top of CMSSW_12_5_X_2022-08-25-2300.

I've also seen these in https://github.com/cms-sw/cmssw/pull/38983#issuecomment-1229124725

**Comment by makortel** [comment]
Ah, also part of #39194 now, so we can close this issue.
