### ISSUE TITLE
[LTO][GCC11] Uninitialized warnings

### ISSUE THREAD

**Issue by smuzaffar** [cms-sw/cmssw#39242]
Hi,
  there are 3 warning like [a] generated from `RecoPixelVertexing/PixelTrackFitting` package. Looking at https://github.com/cms-sw/cmssw/blob/master/RecoPixelVertexing/PixelTrackFitting/interface/RZLine.h#L29-L46 , I think variables are correctly initialized. Any idea why compiler is complaining in this case?

[a] https://cmssdt.cern.ch/SDT/cgi-bin/buildlogs/el8_amd64_gcc11/CMSSW_12_6_LTO_X_2022-08-28-2300/RecoPixelVertexing/PixelTrackFitting
```
In member function 'calculate',
    inlined from '__ct ' at RecoPixelVertexing/PixelTrackFitting/interface/RZLine.h:45:14,
    inlined from 'run' at RecoPixelVertexing/PixelTrackFitting/src/PixelFitterByHelixProjections.cc:159:43:
  RecoPixelVertexing/PixelTrackFitting/interface/RZLine.h:100:14: warning: 'r_storage.26_571' may be used uninitialized [-Wmaybe-uninitialized]
   100 |     linearFit(r.data(), z.data(), n, errZ2.data(), cotTheta_, intercept_, covss_, covii_, covsi_);
      |              ^
RecoPixelVertexing/PixelTrackFitting/src/PixelFitterByHelixProjections.cc: In member function 'run':
CommonTools/Statistics/interface/LinearFit.h:29:6: note: by argument 1 of type 'const float *' to 'linearFit' declared here
   29 | void linearFit(T const* __restrict__ x,
      |      ^
```

**Comment by makortel** [comment]
assign reconstruction

**Comment by mandrenguyen** [comment]
@smuzaffar 
Sorry, this caught us right in the convener transition period.  Is this compiler warning still happening?

**Comment by smuzaffar** [comment]
yes @mandrenguyen , I tried to fix these here https://github.com/cms-sw/cmssw/pull/40214 but looks like clang does not allow initialization of variable length arrays.

**Comment by makortel** [comment]
Another attempt in https://github.com/cms-sw/cmssw/pull/40498

**Comment by smuzaffar** [comment]
This has been fixed , so I am closing this issue
