### ISSUE TITLE
chaining toReplaceWith

### ISSUE THREAD

**Issue by vlimant** [cms-sw/cmssw#39335]
I was wondering if there is a major issue with allowing

`(Modifier_A | Modifier_B).toReplaceWith(something, something_else).toReplaceWith(something_dfiferent, something_else_different)`

instead of

`(Modifier_A | Modifier_B).toReplaceWith(something, something_else)
(Modifier_A | Modifier_B).toReplaceWith(something_dfiferent, something_else_different)`

and for other modifier functions

**Comment by makortel** [comment]
assign core

**Comment by makortel** [comment]
Thanks for the suggestion, the chaining of `toModify()` and `toReplaceWith()` function calls is implemented in https://github.com/cms-sw/cmssw/pull/39342

**Comment by vlimant** [comment]
awesome !

**Comment by makortel** [comment]
+core
