### ISSUE TITLE
HLT Validation tests fail in all (12_3/4/5/6) IBs since 2022-09-07-1100 IBs

### ISSUE THREAD

**Issue by Martin-Grunewald** [cms-sw/cmssw#39345]
HLT Validation tests fail in all (12_3/12_4/12_5/12_6) IBs since 2022-09-07-1100 IBs.

(For other CMSSW releases, there are so far no IBs made after 2022-09-06-2300)

Has anything changed in the environment in which these jobs are executed?

The error message is:
```
Traceback (most recent call last):
  File "/pool/condor/dir_9286/jenkins/workspace/ib-run-HLT/CMSSW_12_6_X_2022-09-07-2300/bin/el8_amd64_gcc10/hltListPaths", line 190, in <module>
    paths = getPathList(config)
  File "/pool/condor/dir_9286/jenkins/workspace/ib-run-HLT/CMSSW_12_6_X_2022-09-07-2300/bin/el8_amd64_gcc10/hltListPaths", line 32, in getPathList
    raise Exception(f'query did not return a valid HLT menu:\n query="{cmdline}"')
Exception: query did not return a valid HLT menu:
 query="hltConfigFromDB --run3 --v3 --configName /dev/CMSSW_12_4_0/GRun/V110 --noedsources --noes --noservices"
```

ie, the execution of the command:
```
hltConfigFromDB --run3 --v3 --configName /dev/CMSSW_12_4_0/GRun/V110 --noedsources --noes --noservices
```
in a CMSSW environment!

I can not reproduce this failure offline in a standard CMSSW developer environment.

**Comment by Martin-Grunewald** [comment]
@smuzaffar

**Comment by Martin-Grunewald** [comment]
assign hlt

**Comment by Martin-Grunewald** [comment]
Hmm, I do not see this ```confdb``` directory on vocms006:
```
 cd ${CMSSW_BASE}/tmp/confdb
/data/user/gruen/126/CMSSW_12_6_X_2022-09-07-2300/tmp/confdb: No such file or directory.
```
?

**Comment by missirol** [comment]
I also don't see it on a normal local CMSSW installation on `lxplus`. I don't know by heart how and when it is generated, I'll have to dig a bit to find out. Maybe https://github.com/cms-sw/cmssw/issues/39345#issuecomment-1240343074 does not explain the IB issues, but it seems unlikely that the two things are unrelated (getting configs via `--dbproxy` outside CERN worked well in the recent past).

**Comment by missirol** [comment]
Right now, what was described in https://github.com/cms-sw/cmssw/issues/39345#issuecomment-1240343074 (downloading a HLT config from outside CERN with the `--dbproxy` option) works normally again, and indeed the `tmp/confdb` directory looks healthy.
```
ls -l ${CMSSW_BASE}/tmp/confdb/v3/
  576603 Sep  8 17:57 cmssw-evf-confdb-converter.jar
     168 Sep  8 17:57 confdb.version
 5257174 Sep  8 17:57 ojdbc8.jar
```
The logic that leads to `${CMSSW_BASE}/tmp/confdb/v3/` is in 
https://github.com/cms-sw/cmssw/blob/435424d670ea3c864b7757527d96b8156b594b60/HLTrigger/Configuration/python/Tools/confdbOfflineConverter.py#L116

We rely on a directory on AFS, and elsewhere fall back to a local download of the `.jar` files of `ConfDB`.

If this download somehow fails (and in the last 24h, it looks like it often did), the output configurations can create the error messages discussed here and in #37598.

Do the machines running IB tests have access to `/afs/cern.ch/user`?

Would anybody have suggestions on how to make this more robust?

**Comment by missirol** [comment]
@smuzaffar 

> Do the machines running IB tests have access to `/afs/cern.ch/user`?

Could you please answer this question? (it's just for my understanding)

**Comment by smuzaffar** [comment]
@missirol , we do not mount AFS on build nodes so no we do not have access to `/afs/cern.ch/user`

**Comment by missirol** [comment]
> Would anybody have suggestions on how to make this more robust?

Giving myself one suggestion: in principle, we do not need any of these downloads to test the menus in IBs, as the menus in question are already part of the CMSSW release. In practise, the issue is that some HLT utilities (e.g. `hltIntegrationTests`) only work by downloading the menu from the DB; it might be worth extending these scripts to (also) read python configs directly, and that could be a step towards solving this issue and #37598.

**Comment by missirol** [comment]
Regarding https://github.com/cms-sw/cmssw/issues/39345#issuecomment-1240929822, I realised only today, thanks to others, that the path `/afs/cern.ch/user/c/confdb/www/` is actually a sym-link to `/eos/home-c/confdb/www`.

@smuzaffar , do the machines running IB tests have access to `/eos/home-c/confdb/www`?

(If they do, we could maybe avoid the extra downloads during IBs by changing `/afs/cern.ch/user/c/confdb/www/` to `/eos/home-c/confdb/www` in `confdb.py` of CMSSW.)

**Comment by smuzaffar** [comment]
@missirol , no we do not have access to afs or eos

**Comment by missirol** [comment]
+hlt

See https://github.com/cms-sw/cmssw/issues/37598#issuecomment-1326628334 (I'm assuming that the root cause behind this issue and #37598 is the same).

**Comment by makortel** [comment]
@cmsbuild, please close
