### ISSUE TITLE
Integrate part of NANO test in cmsbot commands

### ISSUE THREAD

**Issue by vlimant** [cms-sw/cmssw#39452]
copying here from https://github.com/cms-sw/cms-bot/issues/1823 on @smuzaffar 's request.

I am opening this issue to collect advice on how to best integrate some of the tests that are ran by xpog as part of the integration of NANO release. There is a gitlab workflow (that I learning the rope of ATM) https://gitlab.cern.ch/cms-nanoAOD/nanoAOD-integration/-/blob/master/.gitlab-ci.yml and it seems that 90% of it is a duplicate/repcursor of what cmsbot is doing with PR, with a NANOAOD cherry on top.
As part of cleaning legacy tests, I think it would be beneficial to include most tests under cmsbot.

**Comment by smuzaffar** [comment]
I had a face-to-face discussion with @vlimant  and looks like nano-AOD tests are simple workflows for which bot just needs to run relvals + comparison jobs ( plus may be some additional checks). This is identical to what we do for GPU or high-stats PR tests. I think the first step is to add those workflow to cmssw RelVals (runTheMatrix.py) so that we regularly run them for IBs. Once nano-AOD workflows are part of cmssw then it will be easy to support `enable nanoAOD` type tests.

**Comment by makortel** [comment]
assign core,xpog

**Comment by vlimant** [comment]
@smuzaffar : do I have to add the harvesting step in order for the cmsbot test to be able to later compare DQM output ?
is there anything special I need to do to enable the fwk job report in xml ?

**Comment by smuzaffar** [comment]
@vlimant , I think yes you need the harvesting step for comparison. FW job reports are already enabled , so nothing special to do for that. FW job reports for each workflow will be available via the PR summary page e.g. https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-f97616/27734/runTheMatrix-results/4.22_RunCosmics2011A+RunCosmics2011A+RECOCOSD+ALCACOSD+SKIMCOSD+HARVESTDC/

**Comment by vlimant** [comment]
passed #39472 , there are a two scripts that are ran on the workflows outputs:

- branch size summary using `$CMSSW_BASE/src/PhysicsTools/NanoAOD/test/inspectNanoFile.py step2.root -j branchsize.json`
- runtime summary using `get_timing_from_jobreport.py fwk_jobreport.xml timing_report.json` with https://gitlab.cern.ch/cms-nanoAOD/nanoAOD-integration/-/blob/master/scripts/get_timing_from_jobreport.py 

then three comparisons are done:
- dqm file comparison : which I believe is already in cmsbot's hands
- branch size and time comparison using `compare_sizes_json.py -H -f md ${JOBLIST} >> size_report.md` with https://gitlab.cern.ch/cms-nanoAOD/nanoAOD-integration/-/blob/master/scripts/compare_sizes_json.py

what is the best way @smuzaffar to get these integrated ? i.e location of the scripts and reusing maybe other existing scripts (for timing and branch size comparison)

**Comment by smuzaffar** [comment]
@vlimant , I would suggest to integrate these `https://gitlab.cern.ch/cms-nanoAOD/nanoAOD-integration` scripts in to cmssw first ( may be in to [PhysicsTools/NanoAOD/scripts](https://github.com/cms-sw/cmssw/tree/master/PhysicsTools/NanoAOD/scripts) directory ). Once these are available in the cmssw Ibs then we can update bot to run extra `nano` workflows (on demand) and run these scripts on `nano` workflows output.

**Comment by vlimant** [comment]
modifying the branch to branch comparison script to cope with pure-root output and finding all edm flat table automatically https://github.com/cms-sw/cms-bot/pull/1872

**Comment by vlimant** [comment]
I think we are good here

**Comment by vlimant** [comment]
many thanks @smuzaffar @slava77 for the help
