### ISSUE TITLE
Insufficient error handling in TkHistoMap::fillFromAscii

### ISSUE THREAD

**Issue by Dr15Jones** [cms-sw/cmssw#39455]
In various pull request tests we are seeing segmentation faults originating from `TkHistoMap::fillFromAscii`. Looking at the implementation, there is an error case which could be causing this if there is a problem reading the file. See below for details.

**Comment by makortel** [comment]
FYI @cms-sw/trk-dpg-l2

**Comment by mmusich** [comment]
https://github.com/cms-sw/cmssw/pull/39469 should solve.
