### ISSUE TITLE
Special branch and tests for compression developments in #39554

### ISSUE THREAD

**Issue by rappoccio** [cms-sw/cmssw#39695]
At the ORP meeting 11-October-2022, there was a request to make a branch off of CMSSW_12_6_0_pre3 with only the commits from PR #39554 in place. This was done [here](https://github.com/cms-sw/cmssw/tree/CMSSW_12_6_0_pre3_CompressionBranch). 

A summary of actions to be done is [here](https://github.com/cms-sw/cmssw/pull/39554#issuecomment-1274929751). 

Proposed actions: 

* Create full release titled "CMSSW_12_6_0_pre3_LossyCompression" (or similar). 
* RelVal campaign should be created to test with high statistics. 
* Once satisfied, will merge to main CMSSW_12_6_X branch and possibly include for pre4.

**Comment by rappoccio** [comment]
Creating a build prototype [here](https://github.com/cms-sw/cmssw/issues/39697). Once we get signoff from RECO and CORE we can start the build process.

**Comment by slava77** [comment]
> Creating a build prototype [here](https://github.com/cms-sw/cmssw/issues/39697). Once we get signoff from RECO and CORE we can start the build process.

I'm curious of the process of the signoff. There are no labels for this issue. Should @cms-sw/reconstruction-l2 and @cms-sw/core-l2  post an explicit message "go ahead" or smth in this thread?

**Comment by makortel** [comment]
@rappoccio The labels need to be set with the `assign core,reconstruction` syntax, otherwise the bot will remove them (like happened above).

> This was done [here](https://github.com/cms-sw/cmssw/tree/CMSSW_12_6_0_pre3_CompressionBranch).

From core point of view the branch above looks good.

The only thing I wonder is from https://github.com/cms-sw/cmssw/issues/39449#issuecomment-1258301160
> > > We could start with no-PU validation using samples of the same type as in a recent tracking validation https://its.cern.ch/jira/browse/PDMVRELVALS-158
> > 
> > 
> > If the plots are made during RECO then they would not reflect the change in precision since that only appears for later steps reading the data.
> 
> good point, we need to split the request to run PAT/miniAOD in a separate step from the RECO step.

Is the splitting of PAT/miniAOD into a separate step from RECO something that can/will be done at the RelVal submission time? (i.e. would not need changes in the release)

**Comment by rappoccio** [comment]
assign core,reconstruction

**Comment by rappoccio** [comment]
Thanks @makortel , yes, I think this can be done at relval submission time.

**Comment by makortel** [comment]
+core

**Comment by mandrenguyen** [comment]
+reconstruction
I think this branch was created long ago already, even though we neglected to sign

**Comment by makortel** [comment]
@cmsbuild, please close
