### ISSUE TITLE
Issue in matching between HLT object and L1 object

### ISSUE THREAD

**Issue by jaimeleonh** [cms-sw/cmssw#39809]
When running the nanoAOD production, in https://github.com/cms-sw/cmssw/blob/master/PhysicsTools/NanoAOD/plugins/TriggerObjectTableProducer.cc#L252-L255 there's a loop that tries to find the L1 object that best matches (in dR) with the desired HLT object. However, the `best` value is not getting updated, so the last L1object from the collection whose dR with the HLT object is smaller than `sel.l1DR2` (which to be true I'm not sure what is), is the one getting stored, even if there's a previous one with an smaller dR. Is this behaviour intended?

**Comment by makortel** [comment]
assign xpog

**Comment by swertz** [comment]
Thanks for reporting @jaimeleonh , this looks like a bug indeed. I will make a PR to fix it and backport it to 124X. However we are planning to change the way trigger object info is stored in nano as this is not the only issue with the TriggerObjectTableProducer...

**Comment by perrotta** [comment]
This looks like having been fixed in master by #39893
Also the backport in 12_4 is available, #39932, while the one in 12_5_X is still missing: I suggest to keep this issue open until also the backport in the intermediate release is available

**Comment by perrotta** [comment]
urgent
