### ISSUE TITLE
Review and optimize Fractional Prescale GlobalBoard loops

### ISSUE THREAD

**Issue by rappoccio** [cms-sw/cmssw#39817]
In #39464, there is an open issue that was decided to resolve at a later time (https://github.com/cms-sw/cmssw/pull/39464/files#r979213382). 

Suggestions: 

* From @fwyzard [here](https://github.com/cms-sw/cmssw/pull/39464/files#r992536291)
* From @perrotta [here](https://github.com/cms-sw/cmssw/pull/39464/files#r983523251)

**Comment by makortel** [comment]
assign l1

**Comment by missirol** [comment]
https://github.com/cms-sw/cmssw/pull/39832 potentially solves this issue. It's under review.

**Comment by missirol** [comment]
#39832 is now merged, and I think it addresses the follow-ups asked in #39464.

**Comment by cecilecaillol** [comment]
+l1

**Comment by missirol** [comment]
please close
