### ISSUE TITLE
range_check error in HydjetGeneratorFilter

### ISSUE THREAD

**Issue by iarspider** [cms-sw/cmssw#39865]
In CMSSW_12_6_X_2022-10-26-1100 relval [159.03](https://cmssdt.cern.ch/SDT/cgi-bin/logreader/el8_amd64_gcc11/CMSSW_12_6_X_2022-10-26-1100/pyRelValMatrixLogs/run/159.03_HydjetQ_MinBias_5020GeV_2021_ppReco+HydjetQ_MinBias_5020GeV_2021_ppReco+DIGIHI2021PPRECO+RAWPRIMESIMHI18+RECOHI2022PROD+MINIHI2022PROD/step1_HydjetQ_MinBias_5020GeV_2021_ppReco+HydjetQ_MinBias_5020GeV_2021_ppReco+DIGIHI2021PPRECO+RAWPRIMESIMHI18+RECOHI2022PROD+MINIHI2022PROD.log#/269-269) failed with `std::exception`:
```
----- Begin Fatal Exception 26-Oct-2022 13:45:02 CEST-----------------------
An exception of category 'StdException' occurred while
   [0] Processing  Event run: 1 lumi: 1 event: 1 stream: 3
   [1] Running path 'simulation_step'
   [2] Calling method for module HydjetGeneratorFilter/'generator'
Exception Message:
A std::exception was thrown.
vector::_M_range_check: __n (which is 86315) >= this->size() (which is 86315)
----- End Fatal Exception -------------------------------------------------
```

**Comment by iarspider** [comment]
assign generators

**Comment by perrotta** [comment]
See ongoing discussion in https://github.com/cms-sw/cmssw/pull/39784 with @Dr15Jones @wouf

**Comment by perrotta** [comment]
urgent
(marking urgent the issues affecting relvals in the IBs)

**Comment by perrotta** [comment]
close
