### ISSUE TITLE
ProductNotFound exception in workflow  20834.501

### ISSUE THREAD

**Issue by makortel** [cms-sw/cmssw#39911]
Workflow 20834.501 step 5 fails in CMSSW_12_6_X_2022-10-28-1100 with
```
----- Begin Fatal Exception 28-Oct-2022 16:06:45 CEST-----------------------
An exception of category 'ProductNotFound' occurred while
   [0] Processing  Event run: 1 lumi: 2 event: 103 stream: 2
   [1] Running path 'pathALCARECOEcalESAlign'
   [2] Calling method for module TrackSelector/'esSelectedTracks'
Exception Message:
Principal::getByToken: Found zero products matching all criteria
Looking for type: std::vector<reco::Track>
Looking for module label: generalTracks
Looking for productInstanceName: 

   Additional Info:
      [a] If you wish to continue processing events after a ProductNotFound exception,
add "SkipEvent = cms.untracked.vstring('ProductNotFound')" to the "options" PSet in the configuration.

----- End Fatal Exception -------------------------------------------------
```
https://cmssdt.cern.ch/SDT/cgi-bin/logreader/el8_amd64_gcc10/CMSSW_12_6_X_2022-10-28-1100/pyRelValMatrixLogs/run/20834.501_TTbar_14TeV+2026D88_Patatrack_PixelOnlyCPU+TTbar_14TeV_TuneCP5_GenSimHLBeamSpot14INPUT+DigiTrigger+RecoGlobal+HARVESTGlobal+ALCAPhase2/step5_TTbar_14TeV+2026D88_Patatrack_PixelOnlyCPU+TTbar_14TeV_TuneCP5_GenSimHLBeamSpot14INPUT+DigiTrigger+RecoGlobal+HARVESTGlobal+ALCAPhase2.log#/

**Comment by makortel** [comment]
assign alca

FYI @mmusich

**Comment by mmusich** [comment]
assign @cms-sw/upgrade-l2

**Comment by mmusich** [comment]
I would have naively though that this 

https://github.com/cms-sw/cmssw/blob/d296a53eef0dca4c0579e0f3625b74cb5272c0cf/Configuration/PyReleaseValidation/python/upgradeWorkflowComponents.py#L658-L660

would have protected the workflow, but certainly I am missing something.

**Comment by mmusich** [comment]
OK
```diff
diff --git a/Configuration/PyReleaseValidation/python/upgradeWorkflowComponents.py b/Configuration/PyReleaseValidation/python/upgradeWorkflowComponents.py
index 54db5bf1522..06033728cb9 100644
--- a/Configuration/PyReleaseValidation/python/upgradeWorkflowComponents.py
+++ b/Configuration/PyReleaseValidation/python/upgradeWorkflowComponents.py
@@ -630,6 +630,7 @@ class PatatrackWorkflow(UpgradeWorkflow):
                 'HARVESTNano',
                 'Nano',
                 'ALCA',
+                'ALCAPhase2'
             ],
             PU = [],
             **kwargs)
```

solves.
PR will come in a minute.

**Comment by mmusich** [comment]
see https://github.com/cms-sw/cmssw/pull/39917

**Comment by makortel** [comment]
The same exception occurs also in 20834.21, 20834.5, and 20834.502 (the list might not be exhaustive as the tests are still being run)

**Comment by mmusich** [comment]
> The same exception occurs also in 20834.21, 20834.5, and 20834.502 

PR https://github.com/cms-sw/cmssw/pull/39917 has been updated accordingly

> (the list might not be exhaustive as the tests are still being run)

I will update it as more appear (if any)
