### ISSUE TITLE
gemChamberVFATBX0GENeg11 with duplicate labels makes T0 crash on 12_5 reply 

### ISSUE THREAD

**Issue by rvenditti** [cms-sw/cmssw#39936]
As pointed in https://github.com/dmwm/T0/pull/4774, the reply on 12_5_1 failed (at merging DQMIO step?) because of duplicate labels in gemChamberVFATBX0GENeg11 histogram.
Error:
----- Begin Fatal Exception 31-Oct-2022 15:01:26 CET-----------------------
An exception of category 'FatalRootError' occurred while
   [0] Calling InputSource::readRun_
   Additional Info:
      [a] Fatal Root Error: @SUB=TH1Merger::CheckForDuplicateLabels
Histogram gemChamberVFATBX0GEPos11 has duplicate labels in the x axis. Bin contents will be merged in a single bin

----- End Fatal Exception -------------------------------------------------

Files to reproduce the error are in: /afs/cern.ch/user/c/cmst0/public/PausedJobs/HIReplay2022/job_244/job/WMTaskSpace/cmsRun1

**Comment by rvenditti** [comment]
can @cms-sw/gem-dpg-l2  kindly have a look?

**Comment by makortel** [comment]
assign dqm

**Comment by mmusich** [comment]
Looks like the problematic ME is actually in the L1T stack:

https://github.com/cms-sw/cmssw/blob/7f0cfadc07fa1c3e66d44c55b2138b8a91fd471a/DQM/L1TMonitor/src/L1TStage2EMTF.cc#L403-L427

adding to the discussion the original author @nickh2000 of PR https://github.com/cms-sw/cmssw/pull/38818 (@eyigitba FYI)

**Comment by eyigitba** [comment]
@mmusich , thanks for notifying me. Does this crash happen in the merging jobs? Could it be due to a missing line such as this one not being set for that one histogram?
```
gemHitTimingFrac[hist]->getTH2F()->GetXaxis()->SetCanExtend(false)
```

**Comment by mmusich** [comment]
hi @eyigitba 

>  Does this crash happen in the merging jobs? Could it be due to a missing line such as this one not being set for that one histogram?

as far as I understand the underlying ROOT version in 12.5.X really doesn't like to have a histogram with two bin labels containing the same name (for reasons that admittedly I don't understand , and @cms-sw/core-l2 might shed some light upon).
You can see similar occurence of this problem fixed here: https://github.com/cms-sw/cmssw/pull/39853

**Comment by nickh2000** [comment]
Hi @mmusich, 

If you agree, we can proceed by changing these duplicate labels and submitting a backported PR. 

How do you suggest we test this change?

(fyi @eyigitba )

**Comment by mmusich** [comment]
> If you agree, we can proceed by changing these duplicate labels and submitting a backported PR.

yes, sure.

> How do you suggest we test this change?

in the [issue description](https://github.com/cms-sw/cmssw/issues/39936#issue-1430043983) there's a pointer to the failing job from tier-0: `/afs/cern.ch/user/c/cmst0/public/PausedJobs/HIReplay2022/job_244/job/WMTaskSpace/cmsRun1`.
If you run `PSet.py` that you can find in that folder, you should be able to test the fix (without it crashes).

**Comment by nickh2000** [comment]
HI @mmusich,

Thank you for your advice. How do I recreate new DQMIO files for the merging process?

**Comment by mmusich** [comment]
>  How do I recreate new DQMIO files for the merging process?

something like:
```bash
cmsrel CMSSW_12_5_1 
cd CMSSW_12_5_1/src
cmsenv 
git cms-addpkg Configuration/DataProcessing
python3 Configuration/DataProcessing/test/RunExpressProcessing.py --nThreads 8 --scenario ppEra_Run3 --global-tag 124X_dataRun3_Express_v6  --lfn  <here put some input RAW data> --fevt --dqmio 
```

should create the DQMIO files.
Notice that I haven't looked to where to find the RAW data for inputing the wf, but I guess @rvenditti or @francescobrivio @germanfgv  can help you with that.

**Comment by francescobrivio** [comment]
@cms-sw/orp-l2 this is the issue that needs to be fixed in DQM before deploying 12_5_X in Tier0

**Comment by mmusich** [comment]
A possibile solution is proposed in https://github.com/cms-sw/cmssw/pull/39952

**Comment by perrotta** [comment]
urgent
(marking urgent the issues affecting T0 replays)

**Comment by emanueleusai** [comment]
+dqm

**Comment by mmusich** [comment]
please close
