### ISSUE TITLE
Addition of the CPU ID info

### ISSUE THREAD

**Issue by silviodonato** [cms-sw/cmssw#39982]
Dear @cms-sw/core-l2 ,
do we have somewhere the information about which CPU has been used to run CMSSW?

In https://its.cern.ch/jira/browse/CMSHLT-2257 we realized that there are sizable differences between Intel and AMD (at least at the HLT), related to the -Ofast flag.
In https://its.cern.ch/jira/browse/PDMVRELVALS-159 we are planning to run an offline validation AMD vs Intel, but it seems difficult to submit jobs selecting the CPU family. So we are going to submit the jobs on T2_CH_CERN (which is made of mainly AMD) and T2_CH_CERN_HLT which is only Intel.
Therefore, I'd like to know if there is a possibility to know if an event has been processed by Intel or AMD.

Thank you,
Silvio.

**Comment by makortel** [comment]
assign core

**Comment by makortel** [comment]
> do we have somewhere the information about which CPU has been used to run CMSSW?

The framework job report should contain the CPU model if the `CPU` service is in the Process, and its `reportCPUProperties` parameter is set to `True` (default is `False`).

As part of https://github.com/cms-sw/cmssw/issues/30044 we are going to store the CPU model (among other information) in the data files such that it can be obtained programmatically, but this development will still take quite some time.

In the mean time, if the job report and any other computing-side monitoring are not sufficient, a quick&dirty way would be to store the CPU model string e.g. as a data product in LuminosityBlock.

**Comment by silviodonato** [comment]
Thank you Matti, I'm closing this ticket as it is a kind of duplicate of https://github.com/cms-sw/cmssw/issues/30044
