### ISSUE TITLE
Phase-2: DAQ sources from muonGEMDigis are not found

### ISSUE THREAD

**Issue by srimanob** [cms-sw/cmssw#39984]
After testing CMSSW_12_6_0_pre4 with https://github.com/cms-sw/cmssw/pull/39967, I see a warning message which does not show up in Phase-2 DDD workflow, and it was appear in the first-try Phase-2 DD4hep reported in https://github.com/cms-sw/cmssw/issues/37087. Seem to be new.

```
%MSG-w GEMDAQStatusSource:  GEMDAQStatusSource:GEMDAQStatusSource  03-Nov-2022 15:14:08 CET Run: 1 Event: 1
DAQ sources from muonGEMDigis are not found
%MSG
```

Workflow to test: 20834.911

**Comment by perrotta** [comment]
If it showed up in 12_6_0_pre4, a possible origin is in https://github.com/cms-sw/cmssw/pull/39487
@yeckang @jshlee @quark2 could you please have a look and check the origin of the message reported in this issue?

**Comment by perrotta** [comment]
assign daq, gem-dpg

**Comment by srimanob** [comment]
Hi @watson-ij @jshlee @smorovic @emeschi 
Do you have a chance to have a look. It seems I was wrong. The issue happen also in DDD, see [example](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-710490/29394/runTheMatrix-results/20834.0_TTbar_14TeV+2026D88+TTbar_14TeV_TuneCP5_GenSimHLBeamSpot14+DigiTrigger+RecoGlobal+HARVESTGlobal+ALCAPhase2/step3_TTbar_14TeV+2026D88+TTbar_14TeV_TuneCP5_GenSimHLBeamSpot14+DigiTrigger+RecoGlobal+HARVESTGlobal+ALCAPhase2.log) from the PR test.

```
%MSG-w GEMDAQStatusSource:  GEMDAQStatusSource:GEMDAQStatusSource  01-Dec-2022 15:27:04 CET Run: 1 Event: 1
DAQ sources from muonGEMDigis are not found
%MSG
```

**Comment by smorovic** [comment]
Hi @srimanob,
I think that this issue is related to GEM DAQ, not Central-DAQ.

I had a look at the module anyway:
https://github.com/cms-sw/cmssw/blob/master/DQM/GEM/plugins/GEMDAQStatusSource.cc#L300-L313

The module doesn't find some of the products: `GEMVFATStatusCollection`, `GEMOHStatusCollection`, `GEMAMCStatusCollection` or `GEMAMC13StatusCollection`.
Probably some GEM EDProducers are missing from the chain or there is an issue with them.

**Comment by srimanob** [comment]
Thanks @smorovic 
@watson-ij , @jshlee is this on you? Or I should follow up with another person/group? Thx.

**Comment by jshlee** [comment]
@srimanob yes, we will take a look at it.

**Comment by srimanob** [comment]
This issue has been solved by https://github.com/cms-sw/cmssw/pull/40368
