### ISSUE TITLE
function to get module name from PSet without "decorations"

### ISSUE THREAD

**Issue by missirol** [cms-sw/cmssw#40007]
#37181 (which fixed #37157) required adding a check to strip the name of a module in the global PSet from its "decorations" (e.g. `!` for "not", `-` for "ignore").

A question from @makortel there remained unanswered, i.e. https://github.com/cms-sw/cmssw/pull/37181#issuecomment-1063149619.

It's about the use of a "central" function to obtain the bare name of a module without any "decorations".

**Comment by makortel** [comment]
assign core

**Comment by makortel** [comment]
Such a function is now implemented in https://github.com/cms-sw/cmssw/pull/40425

**Comment by missirol** [comment]
#40428 introduces the new method in `pat::TriggerObjectStandAlone`, to close the discussion started in #37157 (even though the real question from that issue, https://github.com/cms-sw/cmssw/issues/37157#issuecomment-1060395954, remains unanswered).

**Comment by makortel** [comment]
+core

**Comment by makortel** [comment]
@cmsbuild, please close
