### ISSUE TITLE
Unit test OnlineDB/Oracle/test_occi_std_length fails everywhere

### ISSUE THREAD

**Issue by iarspider** [cms-sw/cmssw#40014]
Log: [link](https://cmssdt.cern.ch/SDT/cgi-bin/logreader/el8_amd64_gcc10/CMSSW_12_6_X_2022-11-07-1100/unitTestLogs/OnlineDB/Oracle#/)

Error message:
```
terminate called after throwing an instance of 'oracle::occi::SQLException'
  what():  ORA-12541: TNS:no listener
```

Failing since CMSSW_12_6_X_2022-11-07-1100 .

**Comment by iarspider** [comment]
assign db

**Comment by makortel** [comment]
I don't see it failing anymore (in 13_0_X or 12_6_X), so maybe it was a transient error or got fixed somehow?

**Comment by smuzaffar** [comment]
This test was introduced to make sure we have the correct Oracle OCCI lib ( build with gcc 5+ i.e with new GCC C++11 ABI). We have not changed Oracle or test code itself. So no idea why it failed. May be bad tnsname.ora on system. Any way, look like this has been fixed ( no idea how ) :-)

There is no need to keep this issue any more, I am closing it now

**Comment by tvami** [comment]
+db
 * for there record
