### ISSUE TITLE
EGM Related Modules Increase in Timing since `CMSSW_12_6_0_pre2`

### ISSUE THREAD

**Issue by AdrianoDee** [cms-sw/cmssw#40068]
This issue is to document the fact that for Phase2 RECO wfs we see an increase in timing after `12_6_0_pre1` ([here](https://cms-reco-profiling.web.cern.ch/cms-reco-profiling/circles/piechart.php?local=false&dataset=CMSSW_12_6_0_pre1%2Fel8_amd64_gcc10%2F39634.21%2Fstep3_circles&resource=time_real&colours=default&groups=reco_PhaseII&threshold=0)).

This is seen since  `12_6_0_pre2`([here](https://cms-reco-profiling.web.cern.ch/cms-reco-profiling/circles/piechart.php?local=false&dataset=CMSSW_12_6_0_pre2%2Fel8_amd64_gcc10%39634.21%2Fstep3_circles&resource=time_real&colours=default&groups=reco_PhaseII&threshold=0))  and persists in `12_6_0_pre4`([here](https://cms-reco-profiling.web.cern.ch/cms-reco-profiling/circles/piechart.php?local=false&dataset=CMSSW_12_6_0_pre4%2Fel8_amd64_gcc10%2F21034.21%2Fstep3_circles&resource=time_real&colours=default&groups=reco_PhaseII&threshold=0)). The major offenders there seems 

- `GsfTracking` category has risen from 1.3 to 4.3 s
- `EgammaElectronProducers` category has risen from 2.3 to 5.1 s;

that basically account for all the increase from `pre1` to `pre4` and seems to be related to EGM reconstruction.

Previously we had wrongly suspected most of this increase could come from a mismatch between TICL and the EGM producers (https://github.com/cms-sw/cmssw/issues/39482) that was solved in https://github.com/cms-sw/cmssw/pull/39810 and, while being an improvement, did not help as much as expected.

**Comment by AdrianoDee** [comment]
assign upgrade, reco

**Comment by swagata87** [comment]
type egamma

**Comment by missirol** [comment]
assign reconstruction

(assignment based on https://github.com/cms-sw/cmssw/issues/40068#issuecomment-1315119524)

A naive look at [releases/CMSSW_12_6_0_pre2](https://github.com/cms-sw/cmssw/releases/CMSSW_12_6_0_pre2) points to one PR explicitly related to GSF tracking: #39256. Could that PR be related to this timing increase? That PR was mainly done for the Run-3 HLT; I don't remember if its impact on CPU timing was checked (for Phase-2, or even for the Run-3 HLT).

**Comment by swagata87** [comment]
>Previously we had wrongly suspected most of this increase could come from a mismatch between TICL and the EGM producers (https://github.com/cms-sw/cmssw/issues/39482) that was solved in https://github.com/cms-sw/cmssw/pull/39810 and, while being an improvement, did not help as much as expected.

https://github.com/cms-sw/cmssw/pull/39810 did not enter pre4 (thanks to @SohamBhattacharya  for spotting it).
It will go in pre5 and EGM timing reduction is expected to happen.

**Comment by AdrianoDee** [comment]
Indeed, it was merged immediately after `pre4` came out. Just a a double check find here 100 events for the 39634.21 workflow run:

- [CMSSW_12_6_0_pre4](https://adiflori.web.cern.ch/adiflori/circles/web/piechart.php?local=false&dataset=39634.21_CMSSW_12_6_0_pre4&resource=time_real&colours=default&groups=reco_PhaseII&threshold=0) 
- [Latest IB](https://adiflori.web.cern.ch/adiflori/circles/web/piechart.php?local=false&dataset=39634.21_CMSSW_12_6_X_2022-11-15-1100&resource=time_real&colours=default&groups=reco_PhaseII&threshold=0)

This is an `Intel Xeon Gold`, so not the one used for the usual profiling, but it can be seen how we are back on track.
