### ISSUE TITLE
Remove deprecated `exists` API in favor of `fillDescriptions` in `CalibTracker/SiPixelESProducers/plugins/SiPixelQualityESProducer.cc`

### ISSUE THREAD

**Issue by francescobrivio** [cms-sw/cmssw#40077]
Title says it all: as detailed in https://github.com/cms-sw/cmssw/pull/40061#discussion_r1021789687 the deprecated `exists` API in `CalibTracker/SiPixelESProducers/plugins/SiPixelQualityESProducer.cc` should be replaced by `fillDescriptions`.

**Comment by francescobrivio** [comment]
assign trk-dpg

**Comment by tvami** [comment]
assign alca

**Comment by mmusich** [comment]
please close
   * resolved in https://github.com/cms-sw/cmssw/pull/40135

**Comment by tvami** [comment]
+alca
