### ISSUE TITLE
-Ofast and CPU reco timing

### ISSUE THREAD

**Issue by silviodonato** [cms-sw/cmssw#40089]
In the study of the CPU-GPU differences, we found out (again) that `-Ofast` creates differences between AMD and Intel in the electron reconstruction [1] (~1-2% of events passing the single electron trigger).
We asked PdmV to perform studies on the offline side [2].

Whatever will be the outcome of [2], I think we need to quantify the gain of -Ofast in the offline reconstruction, so we should measure the CPU timing of the reconstruction with and without the -Ofast flag (just deleting the lines with the flag in the BuildFile.xml, see [3]).

What does @cms-sw/reconstruction-l2 think about this? Can you perform this kind of study? 
 
Thank you,
Silvio.

[1] https://its.cern.ch/jira/browse/PDMVRELVALS-159
[2] https://its.cern.ch/jira/browse/CMSHLT-2257
[3] https://cmssdt.cern.ch/lxr/search?%21v=CMSSW_12_5_X_2022-06-07-2300&_filestring=&_string=ofast-flag

cc @cms-sw/hlt-l2 @sanuvarghese

**Comment by makortel** [comment]
assign reconstruction

**Comment by clacaputo** [comment]
Hi @silviodonato , I've performed this check beginning of July 2022. 
Removing the `-Ofast` compiler option increase the reconstruction time by ~1% percent.

I’ve tested the effect in `CMSSW_12_4_1_patch1`, on vocms011 (Intel(R) Xeon(R) Silver 4216 CPU @ 2.10GHz), both on production-like workflow 11834.21 and T0-like workflow 136.889:

- wf `11834.21`: **increase** in reconstruction time of `~1.2%`
- wf `136.889`:  **increase** in reconstruction time of `~1.1%`

20 independent measurements were performed.

Do you need the same study in another 124X release?

**Comment by sanuvarghese** [comment]
This maybe a naive question : If the increase in reconstruction time is only ~1%  and the removal of Ofast removes all the CPU-CPU differences, why is it still there?

**Comment by mandrenguyen** [comment]
@sanuvarghese  A 1% increase in reconstruction time is not insignificant.   
We're talking about the cost of an extra 1% of CPU not only for prompt and data reprocessing, but also all of the MC production.  That has a real cost in terms of resources, which are under increased pressure these days.
We can certainly have a discussion about whether a 1% CPU-GPU difference is more or less important than a 1% difference in reconstruction time, but it's not as obvious as you seem to be implying. 

Following discussion at the RECO meeting last Friday, I understand the nature of certain GPU algorithms makes them inherently unreproducible to some level, meaning even GPU-GPU comparisons will not be exact. 
If we are going to have to live with these fluctuations anyway, it may not make sense to remove this compiler flag. 
I'm not making the case either way, just trying to provide some extra info.

**Comment by makortel** [comment]
I'm curious if the "1-2 % differences in electron reconstruction" between AMD and Intel look like random differences or if they show any systematic effect?

**Comment by srlantz** [comment]
@sanuvarghese  I certainly can't speak for reconstruction as a whole, but considering just the mkFit algorithm for Si strip tracking (which is what I've been involved with), certain parts of `-Ofast` are necessary to enable autovectorization of math functions (sin/cos) with gcc, and this can make a big difference to mkFit, since it is designed to maximize SIMD parallelism. For example, in recent tests on AMD Milan, when `-Ofast` is specified, I obtain ~25% faster single-core performance in the initial step that finds most of the tracks.*

However, in the case of mkFit, `-Ofast` is really overkill; we just need `-O3 -ffast-math`, or to be even more focused, `-O3 -fno-math-errno -ffinite-math-only -fno-rounding-math -funsafe-math-optimization`, which is the part that unlocks math vectorization via libmvec. In other words, mkFit's performance benefits from a subset of what is included in the `-ffast-math` umbrella option, which is itself a subset of `-Ofast`. I find that using the focused subset, as above, gives essentially identical performance to using `-Ofast` or `-O3 -ffast-math`. Note that this is all based on a generic AVX2 build that specifies `-mavx2 -mfma`.

So, maybe numerical differences between CPUs could be minimized by using a more focused set of options in place of `-Ofast`.

*Note: for testing purposes, I use a special standalone build of mkFit. Full physics validation is not performed, but I can confirm that expected numbers of tracks are being built.

**Comment by silviodonato** [comment]
@makortel from the latest [measurements](https://docs.google.com/spreadsheets/d/1ozM9aFWyBbv6gjJ5maVOBPDSlacHDFtA9wedBy4yUZk/edit#gid=306749943)  we see up to 8% difference for double electrons. Yes, I'm worried that there might be a systematic effect. This is something should be checked by [PDMVRELVALS-159](https://its.cern.ch/jira/browse/PDMVRELVALS-159) , which is somehow related to #30044   (even though it is not strictly necessary)

**Comment by silviodonato** [comment]
@srlantz thanks for the info, so we could try to make a comparison between
1) `-Ofast` 
2) `-O3 -ffast-math`
3) `-O3 -fno-math-errno -ffinite-math-only -fno-rounding-math -funsafe-math-optimization`
4) nothing

In this previous [test](https://docs.google.com/spreadsheets/d/1K_IVfPC7NnRFEAhfT7SNE5LbnE6gBNMpPtGfvcTEpuA/edit#gid=0) made by Riccardo S, we see that 4) eliminated the AMD/Intel differences. Please note that are differences both in AMD 1) vs  AMD 4) and   in Intel 1) vs  Intel 4)
For the record, I see that `ofast-flag` was defined [here](https://github.com/cms-sw/cmsdist/pull/4438/files) and should be equivalent to `-Ofast`

**Comment by srlantz** [comment]
@silviodonato Yes, I think tests with more limited sets of compiler options compared to `-Ofast` would be relatively easy to do and might help to determine what specific loosening of arithmetic is affecting the numerical agreement.The full effects of `-ffast-math` are detailed [here](https://gcc.gnu.org/wiki/FloatingPointMath). The possibility of hardware dependence is mentioned: "`-ffast-math` also may disable some features of the hardware IEEE implementation such as the support for denormals or flush-to-zero behavior."

Even the reduced set of options that I have suggested could still cause issues. For example, `-ffinite-math-only` means that the optimizer does not allow for the possibility of NaN results, so the `isnan()` C function always returns `false` ([ref](https://simonbyrne.github.io/notes/fastmath/)). My own [quick C++ test at godbolt.org](https://gcc.godbolt.org/z/WEEc13qfP) shows that `std::isnan()` and the common check `x == x` don't work either; they always return `false` and `true`, respectively. This could affect the results of codes that depend on such checks internally.

**Comment by srlantz** [comment]
One additional remark is that for C++, `-Ofast` is equivalent to `-O3 -ffast-math`, according to the gcc man page. A couple of other switches are enabled by `-Ofast`, but they only pertain to Fortran code. (Sorry for neglecting to point this out previously.)

**Comment by srlantz** [comment]
A little [further research](https://gcc.gnu.org/onlinedocs/gcc/Optimize-Options.html) shows that `-Ofast` also includes `-fallow-store-data-races` and `-fno-semantic-interposition`. From the description of the first switch, it seems a little scary in that it allows code to become slightly thread-unsafe for the sake of optimization; hardware effects cannot be ruled out with that, I think. The second makes a safer assumption (dynamically linked symbols will all behave as expected), but this allows the compiler to make more interprocedural optimizations, and it's hard to say if any of those optimizations would be hardware dependent. So I guess I can't really say that `-Ofast` is equivalent to `-O3 -ffast-math`.

**Comment by silviodonato** [comment]
Thanks @srlantz for the clarification

> Even the reduced set of options that I have suggested could still cause issues. For example, -ffinite-math-only means that the optimizer does not allow for the possibility of NaN results, so the isnan() C function always returns false ([ref](https://simonbyrne.github.io/notes/fastmath/)). My own [quick C++ test at godbolt.org](https://gcc.godbolt.org/z/WEEc13qfP) shows that std::isnan() and the common check x == x don't work either; they always return false and true, respectively. This could affect the results of codes that depend on such checks internally.

> it allows code to become slightly thread-unsafe for the sake of optimization

these two things are indeed scaring... 
Does anyone (@cms-sw/core-l2) know if we can check the usage of `std::isnan()` in the [packages](https://cmssdt.cern.ch/lxr/search?%21v=CMSSW_13_0_X_2022-12-11-2300&_filestring=&_string=ofast-flag) using Ofast?

**Comment by srlantz** [comment]
@gparida Yes, unfortunately this seems to be true for mkFit as well, though at an extremely low level. When I reduce the flags to the minimum needed by gcc for vectorized math, then run the exact same executable (standalone) on AMD vs. Intel hardware, the number of built candidates differs by ~0.003%. When the flags are removed, AMD and Intel produce the same number of built candidates; this number is less than the number(s) found by fully vectorized version by ~0.01%. Obviously I'm using an extremely crude metric of physics performance, but I guess it is sufficient to make the point that changing low-level hardware behavior through compiler options has the potential to change some tiny fraction of the results.

**Comment by gparida** [comment]
Hi @srlantz , thank you for the info. Out of curiosity, then the possible solution would be to avoid the flag altogether even if it might cost ~1% in reconstruction time as you mentioned earlier or there could be a different workaround.

**Comment by makortel** [comment]
> Such a check is already part of the static analyzer, see e.g. https://cmssdt.cern.ch/SDT/jenkins-artifacts/ib-static-analysis/CMSSW_13_0_X_2022-12-11-2300/el8_amd64_gcc11/llvm-analysis/index.html and look for
> 
> > std::isnan / std::isinf does not work when fast-math is used. Please use edm::isNotFinite from 'FWCore/Utilities/interface/isFinite.h'
> 
> (although I'm now a bit confused of the report, see #40292)

Actually I might have understood the purpose of that checker incorrectly, and its purpose would be to flag all `std::isnan()` and `std::isinf()` calls. The code of the checker looks like that would be the intention, but for some reason it doesn't flag all the calls to those functions.

(on a historical note I also came across with the HyperNews thread from the time the impact of `-Ofast` on reproducibility was discussed last time https://hypernews.cern.ch/HyperNews/CMS/get/recoDevelopment/1288.html)

One could also argue that could the algorithm(s) in question (which have not really been localized yet, right?) be unstable in general, and if so, could the numerical stability of those algorithms be improved?

**Comment by mandrenguyen** [comment]
+reconstruction
Solved by https://github.com/cms-sw/cmsdist/pull/8280

**Comment by makortel** [comment]
@cmsbuild, please close

**Comment by makortel** [comment]
People interested in this topic might want to take a look of https://github.com/cms-sw/cmsdist/pull/10267
