### ISSUE TITLE
Migrate away from consumesMany()

### ISSUE THREAD

**Issue by makortel** [cms-sw/cmssw#40167]
In https://github.com/cms-sw/cmssw/pull/40136#issuecomment-1329359653 I noticed the consumes information from `consumesMany()` calls was not propagated to the dump by `Tracer` service. The `consumesMany()` implementation includes some trickery, and could be replaced with the [`edm::GetterOfProducts()`](https://twiki.cern.ch/twiki/bin/view/CMSPublic/SWGuideEDMGetDataFromEvent#GetterOfProducts) (or directly with the `callWhenNewProductsRegistered()`). The purpose of this issue is to list the remaining cases of `consumesMany()` and track the progress of migration.

Note that while we expect to do the migration centrally by the `core` team (on low priority), any help from domain experts is welcome.

Based on a simple `git grep consumesMany` below are files that call (or refer to in comments) the file, in decreasing order of priority

Production code (or potential such)
- [x] `PhysicsTools/NanoAOD/plugins/NanoAODDQM.cc` done in https://github.com/cms-sw/cmssw/pull/40169
- [x] `RecoEgamma/EgammaHLTProducers/plugins/EgammaHLTExtraProducer.cc` done in https://github.com/cms-sw/cmssw/pull/40629

Validation code
- [x] `Validation/GlobalHits/src/GlobalHitsAnalyzer.cc` done in https://github.com/cms-sw/cmssw/pull/40770
- [x] `Validation/GlobalRecHits/src/GlobalRecHitsAnalyzer.cc` done in https://github.com/cms-sw/cmssw/pull/40923

.

Used in DQM core code to guarantee proper ordering
- [x] Done in https://github.com/cms-sw/cmssw/pull/40958
```
DQMServices/Components/plugins/MEtoEDMConverter.cc
DQMServices/FileIO/plugins/DQMFileSaverBase.cc
```
- [x] .Done in https://github.com/cms-sw/cmssw/pull/41460
```
DQMServices/FwkIO/plugins/DQMRootOutputModule.cc
```

Non-framework test code
- [x] `DataFormats/HcalDigi/test/HcalDigiDump.cc` done in https://github.com/cms-sw/cmssw/pull/41109
- [x] `L1Trigger/CSCTriggerPrimitives/test/deprecated/CSCTriggerPrimitivesReader.cc` removed in https://github.com/cms-sw/cmssw/pull/40388

.

- [x] Framework support and test code https://github.com/cms-sw/cmssw/pull/42058
```
FWCore/Framework/interface/ConsumesCollector.h
FWCore/Framework/interface/EDConsumerBase.h
FWCore/Framework/src/EDConsumerBase.cc
FWCore/Framework/src/Principal.cc
FWCore/Framework/src/StreamSchedule.cc
FWCore/Framework/test/edconsumerbase_t.cppunit.cc
FWCore/Framework/test/stubs/TestFilterModule.cc
FWCore/Framework/test/stubs/TestTriggerNames.cc
FWCore/Framework/test/stubs/ToyIntProducers.cc
FWCore/ServiceRegistry/interface/ConsumesInfo.h
FWCore/ServiceRegistry/interface/PathsAndConsumesOfModulesBase.h
```

**Comment by makortel** [comment]
assign core,reconstruction,xpog,dqm,l1

(although other than `core` are more FYI)

**Comment by makortel** [comment]
@cms-sw/l1-l2 @dildick 

I see the file
> ```
> L1Trigger/CSCTriggerPrimitives/test/deprecated/CSCTriggerPrimitivesReader.cc
> ```
was moved from `plugins` as part of deprecation work in https://github.com/cms-sw/cmssw/pull/33582. Is this file something that could perhaps be removed now?

**Comment by vlimant** [comment]
for what concerns `NanoAODDQM`, all the `FlatTable` products are retrieved and later post-selected based on `FlatTable::name()` which is different that the what the `InputTag` would be. 

As an example the producer of the "Muon" table is https://github.com/cms-sw/cmssw/blob/master/PhysicsTools/NanoAOD/python/muons_cff.py muonTable but the `NanoAODDQM` module configuration only refers to "Muon" (which might actually refer to multiple `EDProducer` producing a `FlatTable` label "Muon" ... )

It looks impossible to have a proper `consumes` statement from the module configuration.

**Comment by wddgit** [comment]
I have not looked at this case in detail but my recollection from 2012 is that GetterOfProducts can do anything that getManyByType can do, but is more general. It always selects products by type. Optionally, it can also select on any information in the BranchDescription using a predicate (or only select by type). TWIKI documentation is here:

https://twiki.cern.ch/twiki/bin/view/CMSPublic/SWGuideEDMGetDataFromEvent#GetterOfProductsGetterOfProducts 

It uses callWhenNewProductsRegistered(). It internally makes the proper individual consumes calls and it does not use consumesMany. Client code does not need to directly call consumes at all. We only kept getManyByType for backward compatibility to keep existing code working because we didn't have time to migrate all uses. Also we were worried that some code outside the repository might be broken.

All of these are items are on my to do list now. If no one else gets to it first, I'll give this one a try. Possibly you are right and I will be surprised and find some roadblock that makes it impossible when I look at the details. If someone else wants to try this one, then please let me know and I'll not spend time on it.

**Comment by swertz** [comment]
Thanks for the pointers. I tried implementing `GetterOfProducts` in the `NanoAODDQM` as I was working on something else there and it seems to work. I can make a PR soon.

**Comment by vlimant** [comment]
+xpog

**Comment by cecilecaillol** [comment]
L1T file removed in https://github.com/cms-sw/cmssw/pull/40388

**Comment by cecilecaillol** [comment]
+l1

**Comment by emanueleusai** [comment]
+1

**Comment by makortel** [comment]
> +1

@emanueleusai Umm, as far as I can tell, all the uses in DQM and validation code are still there. Am I missing something?

**Comment by missirol** [comment]
assign hlt

Because of `RecoEgamma/EgammaHLTProducers`. This is being addressed in #40629.

> Production code (or potential such)

I don't think `EgammaHLTExtraProducer.cc` is used anywhere in production, so 'potential such'.

**Comment by missirol** [comment]
+hlt

HLT part done in https://github.com/cms-sw/cmssw/pull/40629 (thanks @jeongeun).

**Comment by wddgit** [comment]
I'm going to start working on HcalDigiDump.cc unless someone else is already working on it.

**Comment by makortel** [comment]
+core

`consumesMany()` functionality was removed in https://github.com/cms-sw/cmssw/pull/42058
