### ISSUE TITLE
Weirdness in HFShowerLibrary handling of run 2 file

### ISSUE THREAD

**Issue by Dr15Jones** [cms-sw/cmssw#40218]
While doing some refactoring of the HFShowerLibrary code, I came across this handling of the hadronic particles

https://github.com/cms-sw/cmssw/blob/e0f38a318f32aa6f92ec665531961ec643f70c2a/SimG4CMS/Calo/src/HFShowerLibrary.cc#L362

this is used with the file 

SimG4CMS/Calo/data/HFShowerLibrary_npmt_noatt_eta4_16en_v4.root

which has separate `emParticles` and `hadParticles` branches therefore there is no reason to offset the start value for the `hadParticles`. I believe this was due to a cut-n-paste of the previous handling of `hadParticles` seen in the lines above

https://github.com/cms-sw/cmssw/blob/e0f38a318f32aa6f92ec665531961ec643f70c2a/SimG4CMS/Calo/src/HFShowerLibrary.cc#L356-L357

In addition, the configuration used when reading that file
https://github.com/cms-sw/cmssw/blob/d8a49b979b5ed82b5bb79296713fb485ce9b2344/Geometry/HcalSimData/python/HFParameters_cff.py#L29

causes the `totEvents` to be the hardcoded value of `5000*16=8000`. 
https://github.com/cms-sw/cmssw/blob/e0f38a318f32aa6f92ec665531961ec643f70c2a/SimG4CMS/Calo/src/HFShowerLibrary.cc#L426-L428

The problem with that is the file contains `159881` entries in each of the TBranches which means for large record numbers the hadronic call could ask for data beyond the end of the TBranch.

Looking at the file contents, I see that the TBranch `hadParticles` has empty elements up until entry 79882. The `emParticles` is opposite, where it is always empty after 79880. So the offset is only needed because the file was written in a weird way.

So it looks like there is lots of wasted space in the file and still the possibility of reading off the end.

**Comment by Dr15Jones** [comment]
Assign simulation

**Comment by civanch** [comment]
[abdoulline](https://github.com/abdoulline), can you, please, comment.

**Comment by abdoulline** [comment]
@civanch  @Dr15Jones 
Thanks for bringing this issue to our (HCAL) attention. 
I take the liberty to include @bsunanda in the thread. 
And will alert the actual HFShowerLibrary code maintainer/developer Lev Kheyn.

**Comment by bsunanda** [comment]
I believe the earlier version had a fixed # of events (5000) for each momentum bin. Now it does not have. In this case I would prefer if the exact # of events for each momentum bin for EM and Hadron parts be there and used. This will avoid going beyongthe limit and control the size of the file.

**Comment by abdoulline** [comment]
Sorry, if I'll add even more confusion...
 
If I remember it right,  the aforementioned HFShowerLibrary_npmt_noatt_eta4_16en_v4.root 
has been produced 6 years ago by reformatting the previous ("original/initial")  v3 version  to get better CPU performance: 
https://github.com/cms-sw/cmssw/pull/16049 
(and the code which reads it was modified back then as well).

**Comment by Dr15Jones** [comment]
So there are three files in 
`/cvmfs/cms.cern.ch/el8_amd64_gcc10/cms/cmssw/CMSSW_12_6_0_pre5/external/el8_amd64_gcc10/data/SimG4CMS/Calo/data/`

```
-rw-r--r-- 1 cvmfs cvmfs  343223032 Nov 28  2021 HFShowerLibrary_npmt_noatt_eta4_16en_v4.root
-rw-r--r-- 1 cvmfs cvmfs  190776418 Nov 28  2021 HFShowerLibrary_oldpmt_noatt_eta4_16en_v3.root
-rw-r--r-- 1 cvmfs cvmfs 1249815228 Nov 28  2021 HFShowerLibrary_run3_v6.root
```

It seems they correspond to Run 1 (v3), Run2 (v4) and Run3 (v6). The number of entries in each file's TTree are
```
v3 : 160,000 entries (hadParticles is empty up until entry 80,000 but emParticles has non-empty entries even beyond 80,000
v4 : 159,881 entries (hadParticles is empty up until entry 79,882 but emParticles has non-empty entries even beyond that 79,882
v6 : 159,999 entries (both hadParticles and emParticles have non-empty entries starting at 0)
```

**Comment by kheyn** [comment]
Halves of brunches in RUN2 library are empty, namely, the second half of Em brunch and the first half
of Had brunch (for Had that looks like offset). That happens because, in a usual mode, the whole tree
is read. That is avoided in RUN3 library, where Em and Had brunches are read separately. 

Because of emptiness of one half of brunches, the sizes of brunches in RUN2 library should be
16*2*5000=160000. While looking at library in TBrowser I see 159881 entries for each brunch. But when
I check content of library for each energy, I see exactly 5000 showers for every energy.  

The reasons of that contradiction are under study now.

**Comment by kheyn** [comment]
Sorry, the sizes of brunches in RUN2 library should be 16*2*5000=160000.

**Comment by kheyn** [comment]
It looks that the sign of multiplication is not reproduced correctly. 16x2x5000=160000.

**Comment by kheyn** [comment]
There is really deficit of 119 entries in RUN2 library.

I reformatted the library. Now it has exactly 8000 entries in each brunch, no offset, and improved performance.

**Comment by abdoulline** [comment]
@kheyn  you mean  80,000 entries in each _separate_ (in new version) branch. 
 
 Probably it's worth adding that all missing (119) entries are for the energy point e=7 GeV.
 And that when the actual Run2 library is used, starting from 7 GeV 
  - the energy interpolation algo effectively "borrows" these 119 entries from the next energy point.
  - returns 0 photoelectrons for the last missing (1 TeV) chunk...
  
So that when @kheyn compares average HF response (photoelectrons per GeV) both for electrons and pions (separately in Long as Short fibers) in two cases: 
  (1)  newly generated (aforementioned) library vs (2)  actual HFShowerLibrary_npmt_noatt_eta4_16en_v4.root 
Then the overall (mean) difference is rather small ( max ~119/5000) 

ELECTRONS:
[Nphot_toe_deflib-fillbranch_ls_e16.pdf](https://github.com/cms-sw/cmssw/files/10226288/Nphot_toe_deflib-fillbranch_ls_e16.pdf)
    
PIONS:
[Nphot_toe_deflib-fillbranch_ls_pi16.pdf](https://github.com/cms-sw/cmssw/files/10226292/Nphot_toe_deflib-fillbranch_ls_pi16.pdf)

**Comment by abdoulline** [comment]
Hi @Dr15Jones @civanch  

I guess that there are following ways/option to proceed:

 (0)  do nothing = preserving reproducibility of Run2 HF results 
       there is already (as small) Run2 MC reproducibility break due to the fix https://github.com/cms-sw/cmssw/pull/39967
       (which changes GEANT history) 

(1)  apply an "ugly patch" [1] to get meaningful results with actual library v4,
       requires only minimal code update

(2)  replace v4 by v5 (+ "fileVersion=1") with recovered 119 entries for point e=7 GeV 
       and containing separate branches for electrons and pions - generated by @kheyn, as he reported earlier today,  
      requires (i) request for adding new library to CMSSW SDT repository,
                   (ii) small code (HFShoweLibrary.cc)  + config changes 

(3)  replace Run2 v4 by actual Run3 v6 
      means to backport Run3 library usage to Run2 (some ~2-5% difference may be expected in global variables).
      requires small config change 
                  
------------------------------------------------------------------------

[1]
Ugly patch: replacing 
https://github.com/cms-sw/cmssw/blob/master/SimG4CMS/Calo/src/HFShowerLibrary.cc#L593-#L600

/*
        if (j == nMomBin_ - 2) {
          irc[1] = int(evtPerBin_ * 0.5 * r);
        } else {
          irc[1] = int(evtPerBin_ * r);
        }
        irc[1] += (j + 1) * evtPerBin_ + 1;
        r = G4UniformRand();
        irc[0] = int(evtPerBin_ * r) + 1 + j * evtPerBin_;
*/

With: 

const int shift_patch = 119; //  in .h

        for (int k = 0; k < 2; ++k) {
           int jk = j + k;
           int ir = jk * evtPerBin_ + 1;
           if (fileVersion_>= 2) {
              ir += int(evtPerBin_ * r);
           } else {
              if (jk < 3) {
                 ir += int(evtPerBin_ * r);
              } elseif (jk == 3) {
                 ir += int((evtPerBin_ - shift_patch) * r); 
              } else { 
                 ir += int(evtPerBin_ * r) - shift_patch;
              }
          }
          irc[k] = ir;
        }

**Comment by kheyn** [comment]
The deficit in 199 entries, happening at 7 GeV, results in shift of entries in branches at higher energies. That shift  mostly influences the last energy in branch. That is, while requesting entry for electron or hadron of 1 TeV, call to missing entry could happen. No crash appears in that case, the result is returned zero number of photons. I attach distribution of number of photons in long fibers for electron of 1 TeV.
[nphot_distr2_long_el.pdf](https://github.com/cms-sw/cmssw/files/10226845/nphot_distr2_long_el.pdf)

**Comment by civanch** [comment]
@Dr15Jones , @abdoulline , @kheyn , it is good that the situation is understood. What to do next? For me there are only 2 optimal options : 

1) "do nothing", because huge number of MC events are already produced
2) make modification proposed by Salavat as (1) "exclude 119 entries"- it would be fine if it would be possible to apply this code by flag, we will introduce a modifier, which will enable the flag by customisation

In contrary, if it is possible further improve the library/code for the Run3, we should do the best. In 2023 I would expect change of simulation, so a new library file and updated software would be fine.

**Comment by abdoulline** [comment]
@civanch   I'm not sure I understand your 
     _if it is possible further improve the library/code for the Run3_ 
Run3 HFSgowerLibary (as was presented in July-September 2021 in Simulation meetings) has
 - twice the statistics (wrt Run2); 
 - full and separate branches for electrons and pions; 
 - very good CPU performance. 
 I believe, Chris has just polished HFShowerLibrary code per se.     
 
 About your second preferred (optimal?) option:  it does **not** keep HF response intact (anyway).

**Comment by civanch** [comment]
@abdoulline , I may be was imprecise. I mean that if any new improvement will be proposed for Run3 we can integrate without a problem. Concerning Run2 whatever we do we change SIM history. In that case, we will be asked to provide a modifier for the legacy release. Such modifier will not be needed for current master, so if we run Run2 simulation in the current master or later we will use improved library or code.

**Comment by abdoulline** [comment]
@civanch  
I've put together a branch with the option (1) "ugly patch"
https://github.com/cms-sw/cmssw/compare/master...abdoulline:cmssw:HF_patch_Run2

so that the patch can be applied by 
process.HFLibraryFileBlock.ApplyLibFix = True

**Comment by civanch** [comment]
@abdoulline , this is a safe approach, let us do this PR. I would guess it should be backported to 10_6_X, please, check if codes of modified classes were changed from 10_6 to 13_0. I do not think we need any other backport.

**Comment by abdoulline** [comment]
@civanch    I'm personally not a big fan of this "ugly patch"...   
@bsunanda is in favor of full-fledge fix, if I understand him correctly
https://github.com/cms-sw/cmssw/issues/40218#issuecomment-1334894972
Not sure our framework colleagues are big fans of this kind of "hacking"...
  
And about 10_6_X  - why so much back?  
There's *a lot of changes* since then in all the HFShowerLibrary code/configs...

**Comment by abdoulline** [comment]
@civanch  (cc @Dr15Jones) 
may I suggest that this issue and its possible fixing options 
https://github.com/cms-sw/cmssw/issues/40218#issuecomment-1350742388
be discussed not just in between you, Vladimir, and me, but in a broader circle, like Software release meeting or Simulation development forum?  To have an insight from the framework colleagues, for instance?

**Comment by civanch** [comment]
Let us discuss at Friday meeting 15:30 CET. There will be limited number of peoples, it is equivalent of chat between us. We may put this as an item at the end or at the beginning of the meeting or discuss within News. For me the fixed new library file for Run2 would be also a good solution.

10_6_X is the Run2 legacy MC production release, whatever is needed for Run2 analysis should be backported there.

**Comment by abdoulline** [comment]
OK,  let me put together several slides for Friday, summarizing what's listed/shown in the posts here.

**Comment by abdoulline** [comment]
Undertaken action: https://github.com/cms-sw/cmssw/pull/40357

**Comment by civanch** [comment]
@abdoulline , may be it is needed to backport https://github.com/cms-sw/cmssw/pull/40357 to 10_6_X

**Comment by abdoulline** [comment]
@civanch  there was completely different configuration (yet separately for FullSim and FastSim) back then,  no any Run3 library, 
its unpacking/reading code was completely different.  And I suppose that all what we've implemented (with Lev and Sunanda) last year in 12_X is hardly compatible with the old release.   
So, it's not about backporting per se, but rather about re-implementing (+ adapting) of new Run3 stuff  back to 10_6_X. And I'm afraid I'm not available for doing this in the near future.    

For 10_6_X the least-intrusive (= transparent) option would be the aforementioned (1) "ugly patch" (adapted to 10_6_X  FastSim and FullSim configs and code)  https://github.com/cms-sw/cmssw/issues/40218#issuecomment-1352722374

**Comment by civanch** [comment]
@abdoulline , Thanks for detailed answer. it seems backport is possible but heavy task. Let us stop at this point.

**Comment by civanch** [comment]
+1

**Comment by civanch** [comment]
Now Lev provide a new file for Run3 HFShowerLibrary_run3_v7.root, request to add it to CMSDIST:
https://github.com/cms-sw/cmsdist/issues/8288

**Comment by makortel** [comment]
@cmsbuild, please close
