### ISSUE TITLE
Fatal Root Error in step2 when FastTimerService is added to 11834.21 workflow

### ISSUE THREAD

**Issue by gartung** [cms-sw/cmssw#40299]
I changed the profiling scripts to run the FastTimerService on all of the steps in the workflow profiled. However I get this error running on step2 of  workflow 11834.21
```
----- Begin Fatal Exception 10-Dec-2022 12:40:02 CET-----------------------
An exception of category 'LogicError' occurred while
   [0] Constructing the EventProcessor
   [1] Constructing module: class=FastTimerServiceClient label='fastTimerServiceClient'
Exception Message:
Unexpected branch type ProcessBlock
Please contact a Framework developer
----- End Fatal Exception -------------------------------------------------
```
The config file is generated with this  command 
```
cmsDriver.py step2 -s DIGI,L1,DIGI2RAW,HLT:@relval2022 --conditions auto:phase1_2022_realistic --datatier GEN-SIM-RAW -n 10 --eventcontent RAWSIM --geometry DB:Extended --era Run3 --pileup Run3_Flat55To75_PoissonOOTPU --pileup_input das:/RelValMinBias_14TeV/CMSSW_12_5_0_pre4-124X_mcRun3_2022_realistic_v10_BS2022-v1/GEN-SIM --number=20 --nThreads=1 --no_exec --filein file:step1.root --fileout file:step2.root --customise=HLTrigger/Timer/FastTimer.customise_timer_service_singlejob --customise_commands process.FastTimerService.writeJSONSummary = cms.untracked.bool(True);process.FastTimerService.jsonFileName = cms.untracked.string('step2_DIGI_L1TrackTrigger_L1_DIGI2RAW_HLT_PU.resources.json');process.options.numberOfConcurrentLuminosityBlocks = 1 --python_filename=step2_fasttimer.py
```
This error does not appear in the other workflows tested for profiling: 136.889, 39634.21 or 21034.21.

Discussion on O&C Mattermost Core Software channel

Andrea Bocci:
the constructor of the `FastTimerServiceClient` does not do anything that could trigger that exception, it just reads the configuration from the `ParameterSet` input: 
```c++
MEPSet FastTimerServiceClient::getHistoPSet(const edm::ParameterSet& pset) {
  return MEPSet{
      pset.getParameter<std::string>("folder"),
      pset.getParameter<std::string>("name"),
      pset.getParameter<int>("nbins"),
      pset.getParameter<double>("xmin"),
      pset.getParameter<double>("xmax"),
  };
}

FastTimerServiceClient::FastTimerServiceClient(edm::ParameterSet const& config)
    : dqm_path_(config.getUntrackedParameter<std::string>("dqmPath")),
      doPlotsVsOnlineLumi_(config.getParameter<bool>("doPlotsVsOnlineLumi")),
      doPlotsVsPixelLumi_(config.getParameter<bool>("doPlotsVsPixelLumi")),
      doPlotsVsPU_(config.getParameter<bool>("doPlotsVsPU")),
      onlineLumiMEPSet_(doPlotsVsOnlineLumi_ ? getHistoPSet(config.getParameter<edm::ParameterSet>("onlineLumiME"))
                                             : MEPSet{}),
      pixelLumiMEPSet_(doPlotsVsPixelLumi_ ? getHistoPSet(config.getParameter<edm::ParameterSet>("pixelLumiME"))
                                           : MEPSet{}),
      puMEPSet_(doPlotsVsPU_ ? getHistoPSet(config.getParameter<edm::ParameterSet>("puME")) : MEPSet{}),
      fillEveryLumiSection_(config.getParameter<bool>("fillEveryLumiSection")) {}
```
however, the `FastTimerServiceClient` inherits from `DQMEDHarvester`
and those usually do not run in `step2`
maybe _that_ class is unhappy about the  `ProcessBlock` branch ?

Patrick Gartung:
The exception comes from the GenericConsumer constructor

[cms-sw/cmssw/FWCore/Modules/src/GenericConsumer.cc](https://github.com/cms-sw/cmssw/blob/6d2f66057131baacc2fcbdd203588c41c885b42c/FWCore/Modules/src/GenericConsumer.cc#L77)
```cc

        default:
          throw Exception(errors::LogicError)
              << "Unexpected branch type " << branch.branchType() << "\nPlease contact a Framework developer\n";
      }
    });
  }
```

Matti Kortelainen:

Right, and because the exception is thrown from `callWhenNewProductsRegistered()` callback, the situation is likely thatthe `GenericConsumer` is constructed before any DQM modules, and `FastTimerServiceClient` is the first  DQM module constructed in the job (that register a production of a branch in `ProcessBlock`) that then triggers the callback to be called. In this way the exception gets "attributed" to `FastTimerServiceClient`.

**Comment by gartung** [comment]
@makortel

**Comment by makortel** [comment]
assign core

**Comment by gartung** [comment]
The FastTimerServiceClient appears to be coming from `commonFakeHLT` in `DQMOffline/Configuration/python/autoDQM.py`
https://github.com/cms-sw/cmssw/blob/806c56e6101b15980b2c6f0f1d3a258fb46d917f/DQMOffline/Configuration/python/autoDQM.py#L13
