### ISSUE TITLE
Few issues with static analyzer

### ISSUE THREAD

**Issue by makortel** [cms-sw/cmssw#40292]
I'm looking at the static analyzer report https://cmssdt.cern.ch/SDT/jenkins-artifacts/ib-static-analysis/CMSSW_13_0_X_2022-12-11-2300/el8_amd64_gcc11/llvm-analysis/index.html with only the "fast math plugin" checks enabled, and I see
![image](https://user-images.githubusercontent.com/33993/207074567-91e445e7-6df8-48d9-89fc-006af7dcd086.png)

which makes me wonder a couple of things
1. How does `DataFormats/PatCandidates/src/PackedCandidate.cc` get flagged? As far as I can tell, [`DataFormats/PatCandidates/BuildFile.xml`](https://github.com/cms-sw/cmssw/blob/master/DataFormats/PatCandidates/BuildFile.xml) does not declare fast math to be used
2. I see five reports with numbers in "Bug Group" and "Bug Type". Clicking to the "View Report" link shows that all are `edm::ParameterSet::existsAs<>()`. Could there be something that causes these not to be collected under "Function edm::ParameterSet::exists() or edm::ParameterSet::existsAs<>() called" type?
3. I checked a few of the first analyzer failure reports, and they pointed to an assertion failure (caused by `nullptr`) in `clangcms::ConstCastAwayChecker::checkPreStmt()` along
```
clang++: /cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02763/el8_amd64_gcc11/external/llvm/12.0.1-476112d9475f69ecba350f77e3ec4975/include/llvm/Support/Casting.h:104: static bool llvm::isa_impl_cl<To, const From*>::doit(const From*) [with To = clang::AttributedStmt; From = clang::Stmt]: Assertion `Val && "isa<> used on a null pointer"' failed.

...

1.	<eof> parser at end of file
2.	While analyzing stack: 
	#0 Calling HcalQIESample::HcalQIESample at line 19
	#1 Calling CastorNominalCoderTemplate::process at line 30
	#2 Calling CastorNominalCoder::fC2adc
3.	/pool/condor/dir_35136/jenkins/workspace/ib-run-static-checks/CMSSW_13_0_X_2022-12-11-2300/src/DataFormats/HcalDigi/interface/HcalQIESample.h:37:19: Error evaluating statement
4.	/pool/condor/dir_35136/jenkins/workspace/ib-run-static-checks/CMSSW_13_0_X_2022-12-11-2300/src/DataFormats/HcalDigi/interface/HcalQIESample.h:37:19: Error evaluating statement
 #0 0x00002b12fd51975e llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02763/el8_amd64_gcc11/external/llvm/12.0.1-476112d9475f69ecba350f77e3ec4975/bin/../lib64/libLLVM-12.so+0xa0175e)
 #1 0x00002b12fd5174f4 llvm::sys::RunSignalHandlers() (/cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02763/el8_amd64_gcc11/external/llvm/12.0.1-476112d9475f69ecba350f77e3ec4975/bin/../lib64/libLLVM-12.so+0x9ff4f4)
 #2 0x00002b12fd51765d SignalHandler(int) (/cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02763/el8_amd64_gcc11/external/llvm/12.0.1-476112d9475f69ecba350f77e3ec4975/bin/../lib64/libLLVM-12.so+0x9ff65d)
 #3 0x00002b12f931bcf0 __restore_rt (/lib64/libpthread.so.0+0x12cf0)
 #4 0x00002b1301371aff raise (/lib64/libc.so.6+0x4eaff)
 #5 0x00002b1301344ea5 abort (/lib64/libc.so.6+0x21ea5)
 #6 0x00002b1301344d79 _nl_load_domain.cold.0 (/lib64/libc.so.6+0x21d79)
 #7 0x00002b130136a456 (/lib64/libc.so.6+0x47456)
 #8 0x00002b12f91c0006 clangcms::ConstCastAwayChecker::checkPreStmt(clang::ExplicitCastExpr const*, clang::ento::CheckerContext&) const (/pool/condor/dir_35136/jenkins/workspace/ib-run-static-checks/CMSSW_13_0_X_2022-12-11-2300/lib/el8_amd64_gcc11/libUtilitiesStaticAnalyzers.so+0x3b006)
 #9 0x00002b12fbc1958d clang::ento::CheckerManager::runCheckersForStmt(bool, clang::ento::ExplodedNodeSet&, clang::ento::ExplodedNodeSet const&, clang::Stmt const*, clang::ento::ExprEngine&, bool) (/cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02763/el8_amd64_gcc11/external/llvm/12.0.1-476112d9475f69ecba350f77e3ec4975/bin/../lib64/libclang-cpp.so.12+0x26f058d)
```

**Comment by makortel** [comment]
assign core

**Comment by makortel** [comment]
@gartung

**Comment by gartung** [comment]
1. I didn't write this one but this is what I understand: the check is a warning if `std::isnan` is used. It does not check that the `-fast-math` flag is used.
https://github.com/cms-sw/cmssw/blob/547b357c4a6b16df03a47f1afec6fd3425891c94/Utilities/StaticAnalyzers/src/FiniteMathChecker.cc#L30

**Comment by gartung** [comment]
2. The links for the crashes point to the wrong file. This is a bug in `scan-build` that has been there for a few versions.

**Comment by gartung** [comment]
3. I will have to look at the code I added to add a `null-ptr` guard.

**Comment by gartung** [comment]
The bug in `scan-build` is that it includes empty links in the full report. This can be accessed by changing index.html to index-full.html in the url.

I am unsure where the `existsAs<>` check is coming from since not category is assigned.

**Comment by gartung** [comment]
It comes from the PsetExistsChecker which is an abandoned checker that is usually not run
https://github.com/cms-sw/cmssw/blob/547b357c4a6b16df03a47f1afec6fd3425891c94/Utilities/StaticAnalyzers/src/PsetExistsFCallChecker.cpp#L103

**Comment by gartung** [comment]
However it is still some sort of bug in `scan-build` that creates entries, possibly duplicates, with no category.

**Comment by gartung** [comment]
The lines with no category occurs when there is a line wrap for lines longer than the width of the box.

**Comment by gartung** [comment]
> > It comes from the PsetExistsChecker which is an abandoned checker that is usually not run
> 
> Isn't it run? The report in the link above reports 3645 cases under "CMS code rules" / "Function edm::ParameterSet::exists() or edm::ParameterSet::existsAs<>() called".

I was mistaken. It is run. These entries are from line wrap.

**Comment by makortel** [comment]
Maybe I've misunderstood the "fastmath plugin" check. Maybe its intention is to flag all `std::isnan()` and `std::isinf()` calls, because in general any code compiled with `-ffast-math` could produce floating point numbers that are used elsewhere. I wasn't able to find any information of the intended behavior of the checker from core software meeting agendas around the time the checker was introduced (3ea6560a3f4) or from HyperNews.

But then I really wonder why it doesn't flag more `std::isnan()` and `std::isinf()` calls.
