### ISSUE TITLE
Failure in 2022 data promptNano (L1)

### ISSUE THREAD

**Issue by kskovpen** [cms-sw/cmssw#40494]
We have spotted the following failure in the 2022 data promptNano production, presumably connected to L1 trigger:

https://cms-unified.web.cern.ch/cms-unified/report/cmsunified_ACDC0_Run2022G_MinimumBias_PromptNanoAODv10_v1_221229_092537_1876

The crash info:

```
Fatal Exception (Exit code: 8002) 
An exception of category 'StdException' occurred while
[0] Processing Event run: 362859 lumi: 1 event: 8887 stream: 1
[1] Running path 'NANOEDMAODoutput_step'
[2] Prefetching for module PoolOutputModule/'NANOEDMAODoutput'
[3] Calling method for module L1TriggerResultsConverter/'l1bits'
Exception Message:
A std::exception was thrown.
vector::_M_range_check: __n (which is 0) >= this->size() (which is 0)
```

The problem is reproducible at different sites.

PdmV

**Comment by perrotta** [comment]
assign l1, xpog

**Comment by cecilecaillol** [comment]
How can I reproduce this locally?

**Comment by swertz** [comment]
@kskovpen what CMSSW version is that? If it's prompt NanoV10 I suppose it's 12_4_X?

I changed a `[]` to `.at()` vector access in https://github.com/cms-sw/cmssw/pull/39689 ([here](https://github.com/cms-sw/cmssw/blob/master/PhysicsTools/NanoAOD/plugins/L1TriggerResultsConverter.cc#L153)), which could result in that exception, but this was in 12_6_X only.

**Comment by kskovpen** [comment]
> @kskovpen what CMSSW version is that? If it's prompt NanoV10 I suppose it's 12_4_X?
> 
> I changed a `[]` to `.at()` vector access in #39689 ([here](https://github.com/cms-sw/cmssw/blob/master/PhysicsTools/NanoAOD/plugins/L1TriggerResultsConverter.cc#L153)), which could result in that exception, but this was in 12_6_X only.

It's CMSSW_12_4_10

**Comment by kskovpen** [comment]
> How can I reproduce this locally?

It can be reproduced by running the following configuration https://cms-pdmv.cern.ch/rereco/api/requests/get_cmsdriver/ReReco-Run2022G-MinimumBias-PromptNanoAODv10_v1-00001 on /MinimumBias/Run2022G-PromptReco-v1/MINIAOD and looking for "Processing Event run: 362859 lumi: 1 event: 8887". At least this is what we can see in the logs.

**Comment by missirol** [comment]
I think the issue is at
https://github.com/cms-sw/cmssw/blob/CMSSW_12_4_10/PhysicsTools/NanoAOD/plugins/L1TriggerResultsConverter.cc#L134
, and comes from the lack of a "size > 0" check (see what is done for `handleExtResults` a few lines below).

The size is 0 likely because the L1T uGT FED (1404) was not included in that run (see [OMS](https://cmsoms.cern.ch/cms/runs/report/fullscreen/4637?cms_run=362859&cms_run_sequence=GLOBAL-RUN)).

**Comment by vlimant** [comment]
nice catch @missirol.

is there a PR already started to fix this ?

**Comment by missirol** [comment]
Nope..

**Comment by vlimant** [comment]
can anyone please verify with #40527 ?

**Comment by missirol** [comment]
#40528 is a possible solution. The question is whether this should be backported down to `12_4_X` or not.

**Comment by swertz** [comment]
Hi @missirol , thanks for the backport to 12_6_X, if a new patch release is made available this would make sure the bug doesn't appear for the ongoing NanoAODv11 production. :+1:

As for the prompt NanoAODv10 in 12_4_X, you're welcome to make another backport there as well.

**Comment by missirol** [comment]
The backport to `12_5_X` (`12_4_X`) is #40650 (#40651).

**Comment by swertz** [comment]
Thanks @missirol !

**Comment by vlimant** [comment]
+1

**Comment by vlimant** [comment]
please close
