### ISSUE TITLE
PIxelTemplate should be created in a EsProducer (and consumed as ESProduct)

### ISSUE THREAD

**Issue by VinInn** [cms-sw/cmssw#40544]
currently the "transient" PixelTemplate is constructed in each client EDProducer from the corresponding "dbobject' through the "push file" method.
This is a huge waste of resources in particular with many threads (MT as been introduced mainly to share conditions).
I suggest to create it in a ESProducer and consume its product instead of the "raw" database object.

Affected EDProducer:
https://cmssdt.cern.ch/dxr/CMSSW/search?q=pushfile&case=true&redirect=true

**Comment by mmusich** [comment]
assign trk-dpg

**Comment by mmusich** [comment]
assign reconstruction, db

**Comment by mmusich** [comment]
type trk

**Comment by Dr15Jones** [comment]
@VinInn Thanks for the heads up on the SiPixelTemplate and 'const' ness.

**Comment by Dr15Jones** [comment]
@VinInn I had noticed that SiPixelTemplateStore was used in a `const` fashion. I have written and ESProducer which just handles the `std::vector<SiPixelTemplateStore>`.

**Comment by VinInn** [comment]
ok.
that should be enough.
otherwise just add a method to return it const& from
https://cmssdt.cern.ch/dxr/CMSSW/source/RecoLocalTracker/SiPixelRecHits/interface/PixelCPETemplateReco.h#77
and consume it.

**Comment by VinInn** [comment]
In DQM was bad. Still would be better to check that the same identical ```std::vector<SiPixelTemplateStore>``` is not stored in multiple PixelCPE for the same job.

**Comment by VinInn** [comment]
in rereco config there are all those CPE
```
process.PixelCPEFastESProducer = cms.ESProducer("PixelCPEFastESProducer",
process.PixelCPEGenericESProducer = cms.ESProducer("PixelCPEGenericESProducer",
process.hltESPPixelCPEGeneric = cms.ESProducer("PixelCPEGenericESProducer",
process.hltESPPixelCPETemplateReco = cms.ESProducer("PixelCPETemplateRecoESProducer",
process.templates = cms.ESProducer("PixelCPETemplateRecoESProducer",
process.templates2 = cms.ESProducer("PixelCPEClusterRepairESProducer",
```

and in a way or another they all consume the same DBObject and instantiate the same ```TemplateStore```

**Comment by VinInn** [comment]
by ```hltESPTTRHBuilderAngleAndTemplate``` and generic companion who is not referenced anywhere.
Why in the rereco config?

**Comment by mmusich** [comment]
>  Why in the rereco config?

likely some cascade of includes, but at the end of the day no-one should consume the products, so I would assume they don't produce anything.

**Comment by makortel** [comment]
> > Why in the rereco config?
> 
> likely some cascade of includes, 

I'd bet the `hltESPTTRHBuilderAngleAndTemplate` originates from
https://github.com/cms-sw/cmssw/blob/2e956e433ecee876155e346ca9c9870cab7ec3b7/DQMOffline/Trigger/python/SiStrip_OfflineMonitoring_cff.py#L100

> but at the end of the day no-one should consume the products, so I would assume they don't produce anything.

The ESProducer modules are nevertheless constructed, so they take some (small?) amount of memory even if they wouldn't produce anything.

**Comment by makortel** [comment]
> > I'd bet the hltESPTTRHBuilderAngleAndTemplate originates from
> 
> one can avoid the include by using an appropriate DQM sequence that doesn't bring in the offline trigger monitoring. What's the driver command used for the re-reco?

If I dag it up right, the steps would be `--step RAW2DIGI,L1Reco,RECO,PAT,ALCA:@JetMET,SKIM:@JetMET,DQM:@rerecoCommon+@hcal2`. However, the import chain seems to be
https://github.com/cms-sw/cmssw/blob/2e956e433ecee876155e346ca9c9870cab7ec3b7/DQMOffline/Trigger/python/DQMOffline_Trigger_cff.py#L57
https://github.com/cms-sw/cmssw/blob/2e956e433ecee876155e346ca9c9870cab7ec3b7/DQMOffline/Configuration/python/DQMOffline_cff.py#L119
I'd bet the DQM sequence specification does not impact (or impacts very little) on the configuration fragment file that s loaded into the process.

(if we would have the habit of [placing the ESModules into Tasks](https://twiki.cern.ch/twiki/bin/view/CMSPublic/SWGuideAboutPythonConfigFile#Behavior_when_an_ESProducer_ESSo), the sequence specification would impact also the availability of ESProducers in a job)

**Comment by mmusich** [comment]
> I'd bet the DQM sequence specification does not impact (or impacts very little) on the configuration fragment file that s loaded into the process.

Point in case, I think the DQMOffline better not include the HLT monitoring, unless specified. 

> they take some (small?) amount of memory even if they wouldn't produce anything.

Is this even relevant at all in the grand scheme of things?

**Comment by makortel** [comment]
The template store was moved to an ESProduct in https://github.com/cms-sw/cmssw/pull/42514, so this issue could be closed now

**Comment by tvami** [comment]
+db
 * resolved in https://github.com/cms-sw/cmssw/pull/42514

**Comment by tvami** [comment]
@cmsbuild , please close
