### ISSUE TITLE
Decrease number of event for GeneralTrackAnalyser unit test

### ISSUE THREAD

**Issue by aandvalenzuela** [cms-sw/cmssw#40566]
Hello,

We have noticed in the IBs that test `GeneralTrackAnalyser` (`Alignment/OfflineValidation`) is taking more than 1h in running. In concrete, the first subtest https://github.com/cms-sw/cmssw/blob/master/Alignment/OfflineValidation/test/test_unitGeneralTrackAnalyser.sh#L6 is taking already around an hour, probably because it is analysing 2600 events (https://github.com/cms-sw/cmssw/blob/master/Alignment/OfflineValidation/test/test_all_cfg.py#L35).

Could it be possible to reduce the number of events to 200-500 events?
In this range, execution times on the same machine are from 10 to 25 min.

Thanks,
Andrea.

**Comment by aandvalenzuela** [comment]
assign alca

**Comment by francescobrivio** [comment]
@cms-sw/tracking-pog-l2 @cms-sw/trk-dpg-l2 would it be fine for you to decrese the number of analyzed events as proposed in the Issue description? (In case yes we can take care of making the PR of course.)

**Comment by tvami** [comment]
+alca
 * resolved in https://github.com/cms-sw/cmssw/pull/40567
