### ISSUE TITLE
[GPU_X] Multiple RelVal failures (10824.x, 11634.x, 11650.x)

### ISSUE THREAD

**Issue by iarspider** [cms-sw/cmssw#40714]
Multiple RelVals (10824.x, 11634.x, 11650.x) failed in CMSSW_13_0/2023-02-06-2300 IB:

https://cmssdt.cern.ch/SDT/html/cmssdt-ib/#/relVal/CMSSW_13_0/2023-02-06-2300?selectedArchs=el8_amd64_gcc11&selectedFlavors=GPU_X&selectedStatus=failed

The failures are a mix of missing `gpu-nvidia` accelerator, `CUDAService is disabled` and `std::bad_alloc`s (notice: logs for some relvals also mention `std:bad_alloc`, but without a stacktrace).

**Comment by makortel** [comment]
All symptoms are consistent with the GPU setup of the worker node being dysfunctional. Could be e.g. the card itself, drivers, some incompatibility between the drivers and our container. Maybe it's best to wait for the next round of GPU tests to see if the failures reproduce, or were transient.

**Comment by makortel** [comment]
https://github.com/cms-sw/cmsdist/pull/7648#issuecomment-1420377536 shows also PR unit test failures with similar symptoms.

**Comment by smuzaffar** [comment]
GPU relvals failed as they ran on `lxplus8-gpu` node (which we recently added in jenkins). The test [a] we run to check for GPU was not successful that is why it was using the cuda stub library from our distribution. No idea if it is the configuration of the lxplus8-gpu node which is causing issue or if the GPU [b] available on this node is not supported?

[a]
```
/cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02771/el8_amd64_gcc11/external/cuda-compatible-runtime/1.0-c494f8374f9c5297a98f1d2cb2c28cdf/test/cuda-compatible-runtime -k
```

[b] 
```
nvidia-smi 
Tue Feb  7 16:27:24 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 520.61.05    Driver Version: 520.61.05    CUDA Version: 11.8     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA A100-PCI...  Off  | 00000000:06:00.0 Off |                    0 |
| N/A   34C    P0    36W / 250W |      0MiB / 40960MiB |     41%      Default |
|                               |                      |             Disabled |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
```

**Comment by makortel** [comment]
Cool, the node has A100. We don't explicitly compile for it (would need to add `80` to
https://github.com/cms-sw/cmsdist/blob/72ac2b557b680ee4724a714374abfc3b05d59ed7/cuda-flags.file#L6
), but I had the impression the JIT should have allowed the jobs to run?

**Comment by fwyzard** [comment]
OK, I can reproduce that setting up `cmsenv` on `lxplus8-gpu` breaks the CUDA environment... let me investigate.

**Comment by fwyzard** [comment]
The problem seems unrelated to SCRAM or CMSSW, the local CUDA examples also fail:
```
fwyzard@lxplus8s05:~$ /usr/local/cuda/extras/demo_suite/deviceQuery 
/usr/local/cuda/extras/demo_suite/deviceQuery Starting...

 CUDA Device Query (Runtime API) version (CUDART static linking)

cudaGetDeviceCount returned 999
-> unknown error
Result = FAIL
```

**Comment by iarspider** [comment]
`lxplus8s05` was fixed, closing the issue.

**Comment by makortel** [comment]
+heterogeneous
