### ISSUE TITLE
Warning on TInterpreter::ReadRootmapFile

### ISSUE THREAD

**Issue by srimanob** [cms-sw/cmssw#40844]
Not sure if this is reported git issue or somewhere before.

I see the following warnings [1] in PR tests. It seems to be safe, but may need some clean up.

[1]
```
Warning in <TInterpreter::ReadRootmapFile>: class  PortableHostCollection<portabletest::TestSoALayout<128,false> > found in libDataFormatsPortableTestObjectsSerialSync.so  is already in libDataFormatsPortableTestObjects.so 
Warning in <TInterpreter::ReadRootmapFile>: class  PortableHostCollection<portabletest::TestSoALayout<128ul,false> > found in libDataFormatsPortableTestObjectsSerialSync.so  is already in libDataFormatsPortableTestObjects.so 
Warning in <TInterpreter::ReadRootmapFile>: class  edm::Wrapper<PortableHostCollection<portabletest::TestSoALayout<128,false> > > found in libDataFormatsPortableTestObjectsSerialSync.so  is already in libDataFormatsPortableTestObjects.so 
Warning in <TInterpreter::ReadRootmapFile>: class  edm::Wrapper<PortableHostCollection<portabletest::TestSoALayout<128ul,false> > > found in libDataFormatsPortableTestObjectsSerialSync.so  is already in libDataFormatsPortableTestObjects.so 
Warning in <TInterpreter::ReadRootmapFile>: class  edm::Wrapper<portabletest::TestHostCollection> found in libDataFormatsPortableTestObjectsSerialSync.so  is already in libDataFormatsPortableTestObjects.so 
Warning in <TInterpreter::ReadRootmapFile>: class  portabletest::TestHostCollection found in libDataFormatsPortableTestObjectsSerialSync.so  is already in libDataFormatsPortableTestObjects.so
```

**Comment by makortel** [comment]
assign heterogeneous

**Comment by makortel** [comment]
The warnings are caused by https://github.com/cms-sw/cmssw/pull/40792, and were mentioned in https://github.com/cms-sw/cmssw/pull/40792#issuecomment-1438675167. The dictionaries seem duplicated because the builds after #40792 was merged have been mostly patch builds, and the issue should get fixed with full builds. Actually CMSSW_13_1_ROOT626_X_2023-02-21-2300 is a full build, and indeed does not show the unit test failures that are caused by the same dictionary duplication in other IB flavors.

**Comment by makortel** [comment]
Written that, I have a feeling that the "poisoned" library setup (which, IIUC, should prevent at least  the unit test failures) would not be working properly in a patch build where a package's `BuildFile.xml` was changed to not compile the package for one/some of Alpaka backend(s). @smuzaffar Could you take a look?

**Comment by makortel** [comment]
assign core

**Comment by makortel** [comment]
The warnings have disappeared in the recent 13_1_X IBs (after first full builds since the merge #40792).

**Comment by makortel** [comment]
+1

**Comment by makortel** [comment]
@cmsbuild, please close
