### ISSUE TITLE
Interplay of LCG_DICT_HEADER and LCG_DICT_XML with ALPAKA_BACKENDS

### ISSUE THREAD

**Issue by makortel** [cms-sw/cmssw#40846]
It seems that if a data format package `BuildFile.xml` specifies explicitly the `classes.h` headers and the `classes_def.xml` selection XML files like here
https://github.com/cms-sw/cmssw/blob/c56dd8abcf2fea3b2ad8037028d8bdb4b58587a5/DataFormats/ParticleFlowReco/BuildFile.xml#L20-L21
and one enables the Alpaka backend compilation with `<flags ALPAKA_BACKENDS="1"/>`, the `src/alpaka/classes_<backend>.h` and `src/alpaka/classes_<backend>.def.xml` files are not being considered.

**Comment by makortel** [comment]
assign core,heterogeneous

**Comment by makortel** [comment]
@smuzaffar Just as a guess we tried
```xml
 <flags LCG_DICT_HEADER="classes_1.h classes_2.h alpaka/classes_serial.h alpaka/classes_cuda.h"/> 
 <flags LCG_DICT_XML="classes_def_1.xml classes_def_2.xml alpaka/classes_serial_def.xml alpaka/classes_cuda_def.xml"/> 
```
but that didn't work either. I'm not sure if that would even be a good way to declare the `classes*` files inside the `alpaka` subdirectory.

**Comment by smuzaffar** [comment]
@makortel , yes this is known issue with the build rules. I already have my to do list to fix it but did not realized that we will hit it this soon :-)
Currently, alpaka backend rules do not support multiple HEADER/XML files. I will update the rules to not consider `LCG_DICT_HEADER/XML` for alpaka backend and use default `classes_(serial|cuda).h` files for backend. If we need to support multiple header/def files for each alpaka backend too then I guess we can support something like
```
 <flags LCG_DICT_HEADER="classes_1.h classes_2.h"/> 
 <flags LCG_DICT_XML="classes_def_1.xml classes_def_2.xml"/> 
 <flags ALPAKA_SERIAL_LCG_DICT_HEADER="classes_serial_1.h classes_serial_2.h"/> 
 <flags ALPAKA_SERIAL_LCG_DICT_XML="classes_serial_def_1.xml classes_def_serial_2.xml"/> 
 <flags ALPAKA_CUDA_LCG_DICT_HEADER="classes_cuda_1.h classes_cuda_2.h"/> 
 <flags ALPAKA_CUDA_LCG_DICT_XML="classes_cuda_def_1.xml classes_def_cuda_2.xml"/> 
```

**Comment by makortel** [comment]
In this specific case the Alpaka backend's did not need to be split in multiple files. I'd also expect that in the near-to-medium term we would not really need the ability (but for long term it could be useful). The problem was that already the presence of `LCG_DICT_HEADER` and `LCG_DICT_XML` (or because they had two elements?) seemed to prevent the generation of dictionaries for each Alpaka backend.

As a quick workaround we merged the `classes_{1,2}.h` and `classes_def_{1,2}.xml` in the developers area so that he was able to continue his work.

**Comment by smuzaffar** [comment]
yes presence of `LCG_DICT_HEADER/XML` was feeding the wrong information to alpaka backend rules. One reason we had split these files was to avoid long rootcling/compilation times. Multiple files allowed the build system to run rootcling and compilation in parallel.

**Comment by makortel** [comment]
@smuzaffar Could you remind me if this issue was fixed?

**Comment by smuzaffar** [comment]
No, not yet @makortel

**Comment by makortel** [comment]
Ok. There is now a PR merging two `classes_def_<N>.xml` files together to work around the problem https://github.com/cms-sw/cmssw/pull/42807 .

**Comment by smuzaffar** [comment]
@makortel , https://github.com/cms-sw/cmsdist/pull/8705 addresses this issue. It should allow multiple header/xml files for alpaka backend too.
