### ISSUE TITLE
[AARCH64] Unit test DQM/HLTEvF/testTriggerMonitors fails with FileOpenError

### ISSUE THREAD

**Issue by iarspider** [cms-sw/cmssw#40904]
Log file: [link](https://cmssdt.cern.ch/SDT/cgi-bin/logreader/el8_aarch64_gcc11/CMSSW_13_1_X_2023-02-28-2300/unitTestLogs/DQM/HLTEvF#/279-279)

Error message:
```
%MSG
----- Begin Fatal Exception 01-Mar-2023 03:54:42 CET-----------------------
An exception of category 'FileOpenError' occurred while
   [0] Calling InputSource::readFile_
   [1] Opening DQM Root file
Exception Message:

Input file file:DQMIO.root was not found, could not be opened, or is corrupted.
   Additional Info:
      [a] Fatal Root Error: @SUB=TStorageFactoryFile::Init
file DQMIO.root probably not closed, trying to recover

----- End Fatal Exception -------------------------------------------------

Failure running testTriggerMonitors_harvesting_cfg.py: status 84

---> test testTriggerMonitors had ERRORS
```

**Comment by iarspider** [comment]
assign dqm

**Comment by Dr15Jones** [comment]
@iarspider @smuzaffar 
It looks like several tests write a file named DQMIO.root. When running the tests, where do these files actually appear? It is possible that another tests was in the process of writing a DQMIO.root file while the test that failed is trying to read it.

**Comment by smuzaffar** [comment]
@Dr15Jones , by default all the files are generated in top level `CMSSW_BASE` directory ( unless unit test creates it own sub directory). There is good chance that multiple tests might be writing same output file and as arm nodes has a lot of CPUs so there is more chance of hit such issues for aarch64

**Comment by Dr15Jones** [comment]
The test `DQMOffline/Trigger/test/testHLTFiltersDQMonitor_cfg.py` also writes a DQMIO.root file.

**Comment by smuzaffar** [comment]
I am running now all the unit tests (in serial mode) to see what type of files each test generate :-)

**Comment by missirol** [comment]
> The test `DQMOffline/Trigger/test/testHLTFiltersDQMonitor_cfg.py` also writes a `DQMIO.root` file.

I think that's caused by some unit tests I introduced (https://github.com/cms-sw/cmssw/pull/40334, https://github.com/cms-sw/cmssw/pull/40426), my bad. I tried to fix this in #40928. Thanks for finding the issue, @Dr15Jones.

**Comment by perrotta** [comment]
@iarspider I think this issue can get closed now: isn't it?

**Comment by iarspider** [comment]
@perrotta I agree.
