### ISSUE TITLE
FedRawDataInputSource: warning: 'newChunk' may be used uninitialized in this function

### ISSUE THREAD

**Issue by iarspider** [cms-sw/cmssw#40946]
A warning is issued in DBG_X IB CMSSW_13_1_DBG_X_2023-03-02-2300:

```
.../src/EventFilter/Utilities/src/FedRawDataInputSource.cc: In member function 'readSupervisor':
  .../src/EventFilter/Utilities/interface/FedRawDataInputSource.h:202:13: warning: 'newChunk' may be used uninitialized in this function [-Wmaybe-uninitialized]
   202 |     offset_ = newOffset;
      |             ^
.../src/EventFilter/Utilities/src/FedRawDataInputSource.cc:1205:21: note: 'newChunk' was declared here
 1205 |         InputChunk* newChunk;
      |                     ^
```

Full log: [link](https://cmssdt.cern.ch/SDT/cgi-bin/buildlogs/el8_amd64_gcc11/CMSSW_13_1_DBG_X_2023-03-02-2300/EventFilter/Utilities)

**Comment by makortel** [comment]
assign daq

**Comment by smorovic** [comment]
This is in the single-buffer mode that we don't use (and in fact will go away in the new input source for run3+phase2 that is in development).
I will prepare a patch to intialize variable and add checks to to avoid potential crash here.

**Comment by makortel** [comment]
Fixed in https://github.com/cms-sw/cmssw/pull/40953

**Comment by makortel** [comment]
I suppose this issue could be closed now. @smorovic could you sign it?

**Comment by smorovic** [comment]
+1
yes, it was merged.

**Comment by makortel** [comment]
@cmsbuild, please close
