### ISSUE TITLE
Issue in 2018 HI data reprocessing

### ISSUE THREAD

**Issue by kskovpen** [cms-sw/cmssw#40979]
We see a presumably tau reconstruction related crash in a few reprocessing [wfs](https://its.cern.ch/jira/browse/CMSCOMPPR-26700) of HI data of 2018. Here is the error message:

```
Begin processing the 379th record. Run 326722, Event 318304854, LumiSection 824 on stream 1 at 22-Feb-2023 19:45:26.903 CET
----- Begin Fatal Exception 22-Feb-2023 19:45:26 CET-----------------------
An exception of category 'ProductNotFound' occurred while
   [0] Processing  Event run: 326722 lumi: 824 event: 318302545 stream: 0
   [1] Running path 'MINIAODoutput_step'
   [2] Prefetching for module PoolOutputModule/'MINIAODoutput'
   [3] Prefetching for module PATMETSlimmer/'slimmedMETs'
   [4] Prefetching for module CorrectedPATMETProducer/'patPFMetT1TauEnUp'
   [5] Prefetching for module ShiftedParticleMETcorrInputProducer/'shiftedPatMETCorrTauEnUp'
   [6] Prefetching for module PATTauRefSelector/'pfTaus'
   [7] Prefetching for module PATTauSelector/'selectedPatTaus'
   [8] Prefetching for module PATTauProducer/'patTaus'
   [9] Prefetching for module RecoTauPiZeroUnembedder/'hpsPFTauProducer'
   [10] Prefetching for module RecoTauCleaner/'hpsPFTauProducerSansRefs'
   [11] Prefetching for module RecoTauProducer/'combinatoricRecoTaus'
   [12] Calling method for module PFRecoTauChargedHadronProducer/'ak4PFJetsRecoTauChargedHadrons'
Exception Message:
RefCore: A request to resolve a reference to a product of type 'reco::Candidate' with ProductID '3:1449'
can not be satisfied because the product cannot be found.
Probably the branch containing the product is not stored in the input file.
   Additional Info:
      [a] If you wish to continue processing events after a ProductNotFound exception,
add "SkipEvent = cms.untracked.vstring('ProductNotFound')" to the "options" PSet in the configuration.
```

The full log can be downloaded [here](https://homepage.iihe.ac.be/~kskovpen/ppd/log.txt).

**Comment by mandrenguyen** [comment]
Thanks @kskovpen 
I'm not aware of this reprocessing.  Can you give me some context? 
I was not immediately able to find it from the JIRA.
We intentionally exclude lots of stuff related to taus in the heavy ion reconstruction.

**Comment by kskovpen** [comment]
Hi @mandrenguyen , [here](https://cms-pdmv.cern.ch/rereco/subcampaigns?prepid=MiniAODHI18Data-Winter2021&shown=127&page=0&limit=50) you can find a few links pointing to some documentation about this campaign.

**Comment by mandrenguyen** [comment]
You mean my own presentation?  :-)
I was under the impression that we had closed the 2018 PbPb re-miniAOD campaign long ago. 
I'll look into it.  Thanks!

**Comment by kskovpen** [comment]
Exactly :)
Yes, this wf is one of the last remnants of that production. This is just to report in case it points to some issue/bug in the software. For the production itself, if no objections, we will close this wf at 99%.

**Comment by mandrenguyen** [comment]
After investigation this is the same crash as reported in issue #33564
A fix was merged in PR #33928 but never backported to 11_2_X.
@kskovpen What fraction of data is being lost, not only for this PD, but for the others?
 If they're all at 99ish% I propose we just wrap this reminiAOD campaign.  The problem will not occur again in newer releases.

**Comment by kskovpen** [comment]
Hi @mandrenguyen , yes, these were the very last bits of data. Good to know that it is already fixed and won't happen in the future.

**Comment by mandrenguyen** [comment]
+reconstruction

**Comment by makortel** [comment]
@cmsbuild, please close
