### ISSUE TITLE
Renaming `RecoPixelVertexing/PixelTriplets` Package

### ISSUE THREAD

**Issue by AdrianoDee** [cms-sw/cmssw#41020]
This is trivial and not that important but I find odd that we still call this package `PixelTriplets`. Something like `PixelNTuplets` or `PixelSeeds` seems more reasonable.

**Comment by AdrianoDee** [comment]
type tracking

**Comment by AdrianoDee** [comment]
assign reconstruction

**Comment by slava77** [comment]
while on the subject, `RecoPixelVertexing` is not the most clear name/location for a package that contains essentially just tracking code.
Also, if CA gets extended to strips/OT, it's not just pixel anymore.
should we move it to `RecoTracker`?

**Comment by mmusich** [comment]
what about `RecoTracker/SeedNTuplets` ?

**Comment by AdrianoDee** [comment]
> what about RecoTracker/SeedNTuplets ?

Would make sense. And since we are here. Also `PixelTrackFitting` seems not totally in the right place (still under `RecoPixelVertexing`). Either: 
- `RecoPixelVertexing` could be `RecoPixel` or `RecoPixelTracker`;
- or `PixelTrackFitting` could go somewhere else.

**Comment by slava77** [comment]
perhaps
```diff
+RecoPixel/TrackFitting  
+RecoPixel/VertexFinding
+RecoPixel/LowPtUtilities  
```
OTOH, we have pixel detectors in PPS as well and simply "RecoPixel" could be more confusing. So, RecoTracker seems still like a slightly better location

**Comment by mmusich** [comment]
a proposal at https://github.com/cms-sw/cmssw/pull/41058
