### ISSUE TITLE
SA reporting non-const variable problem when registering PayloadInspector plugins

### ISSUE THREAD

**Issue by tvami** [cms-sw/cmssw#41107]
This came up most recently in 
https://github.com/cms-sw/cmssw/pull/40855#issuecomment-1474611620

The SA reports that the line https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-40d5f3/31388/llvm-analysis/report-076a83.html#EndPath
```
// Register the classes as boost python plugin
PAYLOAD_INSPECTOR_MODULE(EcalSimComponentShape) { PAYLOAD_INSPECTOR_CLASS(EcalSimComponentShapeProfile); }
````
has the problem
```
Non-const variable '::pybind11::class module_::module_def pybind11_module_def_pluginEcalSimComponentShape_PayloadInspector' is static and might be thread-unsafe
```

This was not a problem earlier, and still might be a false-positive from the SA. I'm opening this PR to have feedback from the framework experts.

**Comment by tvami** [comment]
assign core

**Comment by makortel** [comment]
The static analyzer warning seems to come from the expansion of `PYBIND11_MODULE` macro, which is defined here
https://github.com/pybind/pybind11/blob/8dcced29ae4c7654c25bc50742a72556ee3ae36c/include/pybind11/detail/common.h#L458-L460

and it indeed defines a non-`const` global object. The pybind11 documentation https://pybind11.readthedocs.io/en/stable/advanced/misc.html#global-interpreter-lock-gil basically says that any use of the pybind11 needs to be protected by GIL.

Maybe the pybind11 stuff is something we would not need to track with our static analyzer (pybind11 use is limited, and needs "expert attention" anyway). The `PYBIND11_MODULE` macro is quite complex, and even if right now it would look like `CMS_SA_ALLOW` attribute could be used, I'm concerned the setup would be fragile. So maybe the way would to go instead would be to instruct static analyzer to ignore file-`static` objects of type `::pybind11::module_::module_def`.

@Dr15Jones @dan131riley What do you think?

**Comment by Dr15Jones** [comment]
I think the static analyzer should be told to ignore that file. We only run pybind11 stuff at the very beginning of cmsRun when we only have 1 thread so it is safe.

**Comment by tvami** [comment]
Thanks! @shane-breeze can you make that change in the SA?

**Comment by makortel** [comment]
> Thanks! @smuzaffar can you make that change in the SA?

That would really be for @gartung to take a look.

**Comment by gartung** [comment]
I will add it to the list.

**Comment by makortel** [comment]
+core
