### ISSUE TITLE
Unit test Alignment/TrackerAlignment/test_CreateRandomMisalignment fails quetly

### ISSUE THREAD

**Issue by iarspider** [cms-sw/cmssw#41280]
The test, which was introduced in https://github.com/cms-sw/cmssw/pull/41129, uses databases located on AFS. AFS is not available on build nodes, so the test fails quietly, see e.g. [this link](https://cmssdt.cern.ch/SDT/cgi-bin/logreader/el8_amd64_gcc11/CMSSW_13_1_X_2023-04-04-2300/unitTestLogs/Alignment/TrackerAlignment#/37). Maybe these databases should be probably be put into cmsdata repository? 

Pinging @mmusich

**Comment by iarspider** [comment]
assign alca

**Comment by tvami** [comment]
+alca
 * resolved in https://github.com/cms-sw/cmssw/pull/41281
