### ISSUE TITLE
Add BeamSpotOnline tags to the Prompt GT

### ISSUE THREAD

**Issue by francescobrivio** [cms-sw/cmssw#41459]
## Description

As reported in [Issue#41456](https://github.com/cms-sw/cmssw/issues/41456), the `BeamSpotFromDB` is one of the main offenders concerning the LogErrors and LogWarning emitted during Prompt reco.

## Solution
As nicely debugged by @mmusich in https://github.com/cms-sw/cmssw/issues/41456#issuecomment-1527708665, and after some private discussion, it was decided that the best way to fix this is to include the BeamSpotOnline tags (which are already present in the HLT/Express GTs) in the Prompt GT:
 - [BeamSpotOnlineHLT](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/tags/BeamSpotOnlineHLT), Rcd: `BeamSpotOnlineHLTObjectsRcd`
 - [BeamSpotOnlineLegacy](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/tags/BeamSpotOnlineLegacy), Rcd: `BeamSpotOnlineLegacyObjectsRcd`
 
 FYI @gennai @dzuolo

**Comment by tvami** [comment]
It's a bit counterintuitive to add HLT tags to the Prompt GT. Was this decided so there is no need for code changes (which I guess would be the more intuitive solution)?

**Comment by mmusich** [comment]
> Was this decided so there is no need for code changes 

The need of adding the HLT tags originates from the need of monitoring in prompt the difference between the online  and offline beamspots. 
When in Run2 the online BS was saved in the scalers RAW data, there was no need for that.  Now that the arbitration mechanism at HLT uses the online tags that's the only reliable way to get the information *as consumed online*.
The alternative of course is dropping the monitoring (which I am not super keen about) or find a different mechanism to save post-facto the onlineBS (suggestions are welcome).

**Comment by francescobrivio** [comment]
> The need of adding the HLT tags originates from the need of monitoring in prompt the difference between the online and offline beamspots. When in Run2 the online BS was saved in the scalers RAW data, there was no need for that. Now that the arbitration mechanism at HLT uses the online tags that's the only reliable way to get the information _as consumed online_. The alternative of course is dropping the monitoring (which I am not super keen about) or find a different mechanism to save post-facto the onlineBS (suggestions are welcome).

Thanks Marco, in the description I forgot to mention that this will restore the possibility to monitor in prompt the difference between online and PCL/offline.

**Comment by mmusich** [comment]
being tested in https://github.com/dmwm/T0/pull/4817

**Comment by mmusich** [comment]
This issue is ready to be signed (and closed).
  * #41609 provides the needed conditions in the master release 
  * https://github.com/dmwm/T0/pull/4820 updated the Tier-0 production configuration accordingly

**Comment by francescobrivio** [comment]
+1

- see https://github.com/cms-sw/cmssw/issues/41459#issuecomment-1546285561
