### ISSUE TITLE
ReReco: 2022 data, Nano, L1 trigger issue

### ISSUE THREAD

**Issue by kskovpen** [cms-sw/cmssw#41684]
Failures are observed in nano reprocessing of 2022 data, presumably connected to L1 trigger. The full log can be found [here](https://cms-unified.web.cern.ch/cms-unified/joblogs/pdmvserv_Run2022G_MinimumBias_PromptNanoAODv11_v1_221221_083310_6723/8002/DataProcessing/55300b4d-e88f-4e43-9f3f-f1c9f473c0f4-105-3-logArchive/job/WMTaskSpace/cmsRun1/cmsRun1-stdout.log). The error message is:
```
An exception of category 'StdException' occurred while
   [0] Processing  Event run: 362873 lumi: 43 event: 28456884 stream: 1
   [1] Running path 'NANOEDMAODoutput_step'
   [2] Prefetching for module PoolOutputModule/'NANOEDMAODoutput'
   [3] Calling method for module L1TriggerResultsConverter/'l1bits'
Exception Message:
A std::exception was thrown.
vector::_M_range_check: __n (which is 0) >= this->size() (which is 0)
```
@sunilUIET @bbilin

**Comment by makortel** [comment]
assign xpog, l1

**Comment by simonepigazzini** [comment]
would it be possible to have few more details? Release, cmsDriver , etc?

**Comment by aloeliger** [comment]
@kskovpen could we have a short recipe for recreating this please?

**Comment by kskovpen** [comment]
@simonepigazzini @aloeliger sorry for not providing it in advance. Here is the [configuration](https://cms-unified.web.cern.ch/cms-unified/joblogs/pdmvserv_Run2022G_MinimumBias_PromptNanoAODv11_v1_221221_083310_6723/8002/DataProcessing/55300b4d-e88f-4e43-9f3f-f1c9f473c0f4-105-3-logArchive/job/WMTaskSpace/cmsRun1/) used; the input files can be seen in the log file mentioned above. The CMSSW release is CMSSW_12_6_0_patch1.
