### ISSUE TITLE
ReReco: UL data, AOD, ROOT TBasket issue

### ISSUE THREAD

**Issue by kskovpen** [cms-sw/cmssw#41686]
This issue has been around for a while now, and it is a showstopper for a number of cases in data reprocessing. The full log for the failed job can be found [here](https://cms-unified.web.cern.ch/cms-unified/joblogs/cmsunified_ACDC2_Run2017B_SingleMuon_UL2017_MiniAODv2_GT36_230514_184654_9547/8021/DataProcessing/a07221ee-a030-4fae-a819-466c3622a20f-0-1-logArchive/job/WMTaskSpace/cmsRun1/cmsRun1-stdout.log).

The error message:
```
Fatal Root Error: @SUB=TBasket::ReadBasketBuffers
fNbytes = 552, fKeylen = 135, fObjlen = 735, noutot = 0, nout=0, nin=417, nbuf=735
```
@sunilUIET @bbilin

**Comment by makortel** [comment]
The log has
```
R__unzipLZMA: error 9 in lzma_code
```
right before the exceptions, suggesting the data is corrupt. Whether the data got corrupted during the transport, or if the stored file itself is corrupt, is hard to say by the log alone.

**Comment by kskovpen** [comment]
Thanks @makortel and @Dr15Jones , a good catch. Yes, it fails on the same event on multiple attempts. This [one](https://cms-unified.web.cern.ch/cms-unified/joblogs/pdmvserv_Run2017B_SingleMuon_UL2017_MiniAODv2_GT36_230424_192446_5526/8021/DataProcessing/62bae24e-6458-47c3-b6a3-724b2cfec519-45-3-logArchive/job/WMTaskSpace/cmsRun1/cmsRun1-stdout.log) is the previous try for recovery. In this case, this issue can be closed.

**Comment by makortel** [comment]
+core

**Comment by makortel** [comment]
@cmsbuild, please close
