### ISSUE TITLE
Static analyzer report shrunk with LLVM update

### ISSUE THREAD

**Issue by makortel** [cms-sw/cmssw#41828]
The static analyzer reports in 13_0_X about 39k issues (https://cmssdt.cern.ch/SDT/jenkins-artifacts/ib-static-analysis/CMSSW_13_0_X_2023-05-30-2300/el8_amd64_gcc11/llvm-analysis/index.html), whereas in 13_2_X it reports only about 4k issues (https://cmssdt.cern.ch/SDT/jenkins-artifacts/ib-static-analysis/CMSSW_13_2_X_2023-05-30-2300/el8_amd64_gcc11/llvm-analysis/index.html). In 13_0_X we had LLVM 12, and in 13_2_X LLVM 16. Likely something in the static analyzer got borken with the LLVM update.

**Comment by gartung** [comment]
The biggest decrease is for the mutable member checker. I will start there.

**Comment by gartung** [comment]
It looks like LLVM is removing duplicate reports. The post processing script  does this for older versions of llvm/clang. Comparing the filtered pages the number of mutable member entries is 450 for CMSSW_13_0_X  and 355 for CMSSW_13_2_X. So the difference is orders of magnitude smaller compared to the unfiltered count of 23534 for CMSSW_13_0_X and 368 for CMSSW_13_2_X. The filtered vs unfiltered for CMSSW_13_2_X is only 368 vs 355.

**Comment by gartung** [comment]
@makortel I can dig deeper into the 450 vs 355 difference if you think it is worth the effort.

**Comment by gartung** [comment]
The unfiltered scan-build report has multiple entries per file which account for some difference with the filtered scan-build report. The unfiltered report is again sortable. The filtered report being unresponsive to sorting was reported previously in #37982

**Comment by makortel** [comment]
> It looks like LLVM is removing duplicate reports.

Could you check some other bug category as well if the same happens there? (probably does)

> I can dig deeper into the 450 vs 355 difference if you think it is worth the effort.

I think one step deeper inspection could be useful. A difference of hundred feels large (although if genuine, very welcome!)

**Comment by gartung** [comment]
These two are no longer tagged
https://github.com/cms-sw/cmssw/blob/43a0885be526cea4d3d0080409b66213ba58d072/Utilities/StorageFactory/bin/anycp.cpp#L177

**Comment by makortel** [comment]
> These two are no longer tagged
> 
> https://github.com/cms-sw/cmssw/blob/43a0885be526cea4d3d0080409b66213ba58d072/Utilities/StorageFactory/bin/anycp.cpp#L177

Ok, that makes sense.

**Comment by gartung** [comment]
The change happened with the change to llvm/clang 14
https://cmssdt.cern.ch/SDT/jenkins-artifacts/ib-static-analysis/CMSSW_13_1_X_2023-06-01-1100/el8_amd64_gcc11/llvm-analysis/index.html

**Comment by makortel** [comment]
> These two variables of the same name but different class are tagged.

Was the link correct?

**Comment by gartung** [comment]
Yes

**Comment by gartung** [comment]
I looked at the output of the FunctionDumper for the three versions of clang, 12, 14, and 16. The correct number of mutables are reported for anycp.cpp in all three cases. I will have to check what I did differently for mutables in FunctionDumper

**Comment by gartung** [comment]
Correction, the output files for ConstCastChecker, ConstCastAwayChecker and MutableMemberChecker are all sorted unique to produce const-checker.txt. The difference between clang 12 and clang 16 is 
```
 diff llvm12/const-checker.txt llvm16/const-checker.txt 
5a6
> flagged class 'AlignableStackDet' const_cast used 
455a457,459
> flagged class 'hgcal::HGCalFrameGenerator' mutable member 'hgcal::HGCalFrameGenerator::emul_
> flagged class 'hgcal::HGCalFrameGenerator' mutable member 'hgcal::HGCalFrameGenerator::last_emul_event_
> flagged class 'hgcal::HGCalFrameGenerator' mutable member 'hgcal::HGCalFrameGenerator::last_slink_emul_info_
```
This is easily explained by changes in 132x relative to 130x.

**Comment by gartung** [comment]
The difference must be in how BugReporter is handling multiple reports of the same variable name from different classes in the same compilation unit.

**Comment by gartung** [comment]
For "Dead nested assignment" the difference in unique reports between clang 12 - 130X and clang 16 - 132x is attributable to changes in the code
```
diff nested_keys_130x.txt nested_keys_132x.txt 
10c10
< <td class="DESC">Dead nested assignment</td><td>/IOPool/TFileAdaptor/src/TStorageFactoryFile.cc</td><td class="DESC">WriteBuffer</td><td class="Q">491</td>
---
> <td class="DESC">Dead nested assignment</td><td>/IOPool/TFileAdaptor/src/TStorageFactoryFile.cc</td><td class="DESC">WriteBuffer</td><td class="Q">495</td>
21d20
< <td class="DESC">Dead nested assignment</td><td>/cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02787/el8_amd64_gcc11/external/geant4/10.7.2-0a5e38613906bb5debc9753e0e1d40b3/include/Geant4/G4DataVector.icc</td><td class="DESC">index</td><td class="Q">59</td>
```

**Comment by makortel** [comment]
> Correction, the output files for ConstCastChecker, ConstCastAwayChecker and MutableMemberChecker are all sorted unique to produce const-checker.txt. The difference between clang 12 and clang 16 is
> 
> ```
>  diff llvm12/const-checker.txt llvm16/const-checker.txt 
> 5a6
> > flagged class 'AlignableStackDet' const_cast used 
> 455a457,459
> > flagged class 'hgcal::HGCalFrameGenerator' mutable member 'hgcal::HGCalFrameGenerator::emul_
> > flagged class 'hgcal::HGCalFrameGenerator' mutable member 'hgcal::HGCalFrameGenerator::last_emul_event_
> > flagged class 'hgcal::HGCalFrameGenerator' mutable member 'hgcal::HGCalFrameGenerator::last_slink_emul_info_
> ```
> 
> This is easily explained by changes in 132x relative to 130x.

These flagged cases all look suspicious (i.e. good to be flagged). But do I understand correctly that they are flagged in llvm16 but not in llvm12? (i.e. would not explain the cases reported in 12 but not in 16)

**Comment by gartung** [comment]
> > This is easily explained by changes in 132x relative to 130x.
> 
> These flagged cases all look suspicious (i.e. good to be flagged). But do I understand correctly that they are flagged in llvm16 but not in llvm12? (i.e. would not explain the cases reported in 12 but not in 16)

Yes. I am still trying to determine why some bug reports are missing. The text output is written to file bypassing the BugReporter.

**Comment by gartung** [comment]
I have a possible solution, art least for the missing reports for mutable members with the same name in different classes. There may be other cases.
https://github.com/cms-externals/llvm-project/pull/12

**Comment by makortel** [comment]
+core

I think this has been addressed
