### ISSUE TITLE
Porting of NanoAOD-tools to CMSSW

### ISSUE THREAD

**Issue by lenzip** [cms-sw/cmssw#41839]
[NanoAOD-tools](https://github.com/cms-nanoAOD/nanoAOD-tools/) is a set of tools originally developed by M. Peruzzi and collaborators for looping over NanoAOD files with PyROOT. It consists of a "framework" part handling the event loop and I/O and a set of correction modules. It is virtually unsupported since several years, but it still is a favorite among analyzers, with several hundred forks, which flourished as the "central" support decreased.

Following a [discussion](https://indico.cern.ch/event/1227893/) in December 2022,  Common Analysis Tools (CAT, @lenzip and @clelange are the L2s) has decided to revamp support of nanoAOD-tools, which is going to be supported within the CAT-DPROC L3 area (@andrzejnovak and @ttedesch are the L3s). 
The way forward was further discussed in [this talk](https://indico.cern.ch/event/1277996/#2-nanoaod-tools-a-way-forward), with @namapane proposing to port to CMSSW, under a new package with proposed name PhysicsTools/NanoAOD-tools, the "framework" part, which is very stable, and keep in a separate repository the correction part (this will be handled by CAT in a UserCode-type repository). A prototype [here](https://github.com/namapane/cmssw/tree/NanoAODTools-dev/PhysicsTools/NanoAODTools) is already available.

We would like to proceed to include this new package in CMSSW in the current release cycle, and then backport to the relevant releases, in particular 10_6_X for NanoAODv9 and 12_6_X for NanoAODv11.

I am tagging also the XPOG conveners @vlimant and @simonepigazzini for their information

**Comment by makortel** [comment]
> The way forward was further discussed in [this talk](https://indico.cern.ch/event/1277996/#2-nanoaod-tools-a-way-forward), with @namapane proposing to port to CMSSW, under a new package with proposed name PhysicsTools/NanoAOD-tools

Do I understand correctly from the talk and the [ptototype](https://github.com/namapane/cmssw/tree/NanoAODTools-dev/PhysicsTools/NanoAODTools) that the proposed package name is actually `PhysicsTools/NanoAODTools`?

> revamp support of nanoAOD-tools, which is going to be supported within the CAT-DPROC L3 area

Who would take the maintenance ownership (i.e. reviews PRs, be first responder for any problems) of the new package? XPOG? CAT-DPROC L3?

Are the users expected to use this code within CMSSW developer area (i.e. starting with `cmsrel`), or as a "standalone" package that just happens to be part of CMSSW (i.e. starting with `git clone`)?

**Comment by makortel** [comment]
assign xpog, orp

(I'm not fully sure who exactly to assign to)

**Comment by lenzip** [comment]
On 01/06/23 16:09, Matti Kortelainen wrote:
>
>     The way forward was further discussed in this talk
>     <https://indico.cern.ch/event/1277996/#2-nanoaod-tools-a-way-forward>,
>     with @namapane <https://github.com/namapane> proposing to port to
>     CMSSW, under a new package with proposed name
>     PhysicsTools/NanoAOD-tools
>
> Do I understand correctly from the talk and the ptototype 
> <https://github.com/namapane/cmssw/tree/NanoAODTools-dev/PhysicsTools/NanoAODTools> 
> that the proposed package name is actually |PhysicsTools/NanoAODTools|?
>
Yes, sorry.
>
>     revamp support of nanoAOD-tools, which is going to be supported
>     within the CAT-DPROC L3 area
>
> Who would take the maintenance ownership (i.e. reviews PRs, be first 
> responder for any problems) of the new package? XPOG? CAT-DPROC L3?
>
CAT-DPROC L3s
>
> Are the users expected to use this code within CMSSW developer area 
> (i.e. starting with |cmsrel|), or as a "standalone" package that just 
> happens to be part of CMSSW (i.e. starting with |git clone|)?
>
Mainly within CMSSW, but we will try to make standalone use possible, as 
it used to be before. Most users used to use it in CMSSW anyways.

**Comment by simonepigazzini** [comment]
as xpog we support the idea of a new signature category.

**Comment by lenzip** [comment]
Hello, I just wanted to know if there is anything to do from our side to move this forward.

**Comment by namapane** [comment]
Hi @lenzip, I can make a PR as soon as I find some time to fix the standalone setup scripts and doc

**Comment by lenzip** [comment]
Sorry I got lost in the signature discussion. Is there anything missing for this PR?

**Comment by antoniovilela** [comment]
https://github.com/cms-sw/cmssw/pull/42323#issuecomment-1743818163

**Comment by makortel** [comment]
Can this issue be closed now?

**Comment by antoniovilela** [comment]
> Can this issue be closed now?

Yes

**Comment by mandrenguyen** [comment]
+1
