### ISSUE TITLE
Unknown exception from TotemDAQMappingESSourceXML

### ISSUE THREAD

**Issue by makortel** [cms-sw/cmssw#41846]
Workflow 136.772 step 3 failed in CMSSW_13_2_X_2023-05-31-2300 on el8_amd64_gcc11 with
```
----- Begin Fatal Exception 01-Jun-2023 05:29:06 CEST-----------------------
An exception of category 'Unknown' occurred while
   [0] Processing  Event run: 283877 lumi: 23 event: 39245914 stream: 1
   [1] Running path 'dqmoffline_6_step'
   [2] Prefetching for module LogMessageMonitor/'TrackFinderLogMessageMonCommon'
   [3] Prefetching for module LogErrorHarvester/'logErrorHarvester'
   [4] Prefetching for module CTPPSLocalTrackLiteProducer/'ctppsLocalTrackLiteProducer'
   [5] Prefetching for module TotemRPLocalTrackFitter/'totemRPLocalTrackFitter'
   [6] Prefetching for module TotemRPUVPatternFinder/'totemRPUVPatternFinder'
   [7] Prefetching for module TotemRPRecHitProducer/'totemRPRecHitProducer'
   [8] Prefetching for module TotemRPClusterProducer/'totemRPClusterProducer'
   [9] Prefetching for module TotemVFATRawToDigi/'totemRPRawToDigi'
   [10] Calling method for EventSetup module TotemDAQMappingESSourceXML/'totemDAQMappingESSourceXML_TrackingStrip'
Exception Message:
An exception of unknown type was thrown.
----- End Fatal Exception -------------------------------------------------
```
https://cmssdt.cern.ch/SDT/cgi-bin/logreader/el8_amd64_gcc11/CMSSW_13_2_X_2023-05-31-2300/pyRelValMatrixLogs/run/136.772_RunJetHT2016H/step3_RunJetHT2016H.log#/

**Comment by makortel** [comment]
assign alca

FYI @cms-sw/ctpps-dpg-l2

**Comment by makortel** [comment]
Seems that https://github.com/cms-sw/cmssw/pull/41329 was not enough

**Comment by grzanka** [comment]
> 283877

Is it some relval which runs on 2016 data ?
Another question - does it fail on all architectures ? Last time we've seen an exception on aarch64 only (https://github.com/cms-sw/cmssw/pull/41329#issuecomment-1505907036)

**Comment by iarspider** [comment]
It only failed on AMD64 this time

**Comment by grzanka** [comment]
> It only failed on AMD64 this time

Does it fail in a repeatable manner (i.e. if you run the test again) ?

**Comment by iarspider** [comment]
> > It only failed on AMD64 this time
> 
> Does it fail in a repeatable manner (i.e. if you run the test again) ?

It fails randomly, unfortunately.

**Comment by grzanka** [comment]
> > > It only failed on AMD64 this time
> > 
> > 
> > Does it fail in a repeatable manner (i.e. if you run the test again) ?
> 
> It fails randomly, unfortunately.

Is there any way to run these cms-build jobs with more verbosity (like DEBUG level logging or via valgrind) ?
I don't see anything obvious in the code which can cause such bug

**Comment by makortel** [comment]
Let's see if https://github.com/cms-sw/cmssw/pull/41852 makes the actual error visible. I noticed the code uses `XercesDOMParser` so I'd imagine the parsing errors reported as `DOMException` exception.

**Comment by makortel** [comment]
> Is there any way to run these cms-build jobs with more verbosity (like DEBUG level logging or via valgrind) ?

Do you mean in the IB system, or by yourself? The latter is certainly possible to do (and often done, although not very easy for rare problems).

The former is, unfortunately, not really feasible as the IB tests are already resource-constrained (to some degree). We have DBG_X IB that runs everything with `EDM_ML_DEBUG` macro defined, but I'm pretty sure the MessageLogger configuration is not tuned to print the debug messages. I'm also not sure if we could handle the huge log files, and increased run time of the tests. The slowdown by valgrind would certainly be unmanageable in the IBs.
