### ISSUE TITLE
`TrackerGeometry` default copy constructor is unsafe

### ISSUE THREAD

**Issue by fwyzard** [cms-sw/cmssw#41895]
`TrackerGeometry` manages the ownership of the `GeomDetType`s and the `GeomDet`s:

```c++
  ...
  DetTypeContainer theDetTypes;  // owns the DetTypes
  ...
  DetContainer theDets;          // owns *ONLY* the GeomDet * corresponding to GluedDets.
  ...
```

The destructor does delete them:
```c++
TrackerGeometry::~TrackerGeometry() {
  for (auto d : theDets)
    delete const_cast<GeomDet*>(d);
  for (auto d : theDetTypes)
    delete const_cast<GeomDetType*>(d);
}
```

but the default copy constructor and copy assignment operator makes only a shallow copy of the pointers, it does not make a copy of the pointed objects.

This causes undefined behaviour (double delete, usually leading to a crash) if a copy is actually made, and then deleted.

**Comment by fwyzard** [comment]
The easiest fix seem to be to `delete` the copy constructor and assignment operator, and `default` the move constructor and assignment operator:
```c++
  // deleted copy constructor and copy assignment operators
  TrackerGeometry(TrackerGeometry const&) = delete;
  TrackerGeometry& operator=(TrackerGeometry const&) = delete;

  // defaulted move constructor and move assignment operators
  TrackerGeometry(TrackerGeometry &&) = default;
  TrackerGeometry& operator=(TrackerGeometry &&) = default;
```

**Comment by fwyzard** [comment]
This causes compilation errors in `Alignment/CommonAlignmentMonitor/plugins/AlignmentStats.cc`, line 91:
```c++
  if (!trackerGeometry_) {
    trackerGeometry_ = std::make_unique<TrackerGeometry>(iSetup.getData(esTokenTkGeo_));
  }
```
and in `CondTools/SiPhase2Tracker/plugins/SiPhase2BadStripChannelBuilder.cc`, line 50:
```c++
    if (!tTopo_) {
      tTopo_ = std::make_unique<TrackerTopology>(es.getData(topoToken_));
      tGeom_ = std::make_unique<TrackerGeometry>(es.getData(geomToken_));
    }
```

`SiPhase2BadStripChannelBuilder` works around the shallow copy issue by leaking the copy at the end of `SiPhase2BadStripChannelBuilder::getNewObject()`, instead of deleting it:
```c++
std::unique_ptr<SiStripBadStrip> SiPhase2BadStripChannelBuilder::getNewObject() {
  ...

  tGeom_.release();
  return obj;
}
```

**Comment by mmusich** [comment]
type trk

**Comment by francescobrivio** [comment]
+alca

 - see https://github.com/cms-sw/cmssw/issues/41895#issuecomment-1607179398
 - thanks Marco for the ping!

**Comment by civanch** [comment]
+1

**Comment by makortel** [comment]
@cmsbuild, please close
