### ISSUE TITLE
DQM bin-by-bin comparisons broken in last PRs?

### ISSUE THREAD

**Issue by mmusich** [cms-sw/cmssw#42050]
Title says it all, I wanted to check the outcome of the comparisons in a few PR-s but despite the counts of differences being non-zero they look empty.
Examples:
   * https://github.com/cms-sw/cmssw/pull/41815 ([link](https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_13_2_X_2023-06-21-2300+e01bcc/57623/dqm-histo-comparison-summary.html))
   * https://github.com/cms-sw/cmssw/pull/42031 ([link](https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_13_2_X_2023-06-20-1100+1393bb/57606/dqm-histo-comparison-summary.html))
   
In other PRs it seems to work:
   * https://github.com/cms-sw/cmssw/pull/42010 ([link](https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_13_2_X_2023-06-18-2300+f1fda3/57565/dqm-histo-comparison-summary.html))

**Comment by makortel** [comment]
assign dqm,core

**Comment by mmusich** [comment]
@cms-sw/dqm-l2 any update (or acknowledgement on this)?

**Comment by emanueleusai** [comment]
Hello,

We’re looking into it. In the meantime the link to “comparisons failed” contains essentially the same plots and they do not appear empty, see e.g.:
https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_13_2_X_2023-06-22-2300+e01bcc/57647/140.58_RunHI2018/Tracking_TrackParameters_generalTracks_SeedMon_pixelLessStep_TrackBuilding.html

**Comment by perrotta** [comment]
So, in CMSSW_13_2_X_2023-06-18-2300 the bin by bin comparison worked correctly, while in CMSSW_13_2_X_2023-06-20-1100 it did not (according to the issue description).
The only PR merged in the meanwhile that smells as a possible culprit is #41986: could it be the origin of it?

**Comment by emanueleusai** [comment]
Hmm that is a very good lead. On the other hand, last year we had a similar problem and it was caused by a corrupted database. We had to delete it and recreate it.

**Comment by mmusich** [comment]
>  In the meantime the link to “comparisons failed” contains essentially the same plots and they do not appear empty, see e.g.:

This doesn't seem to be completely correct.
At least for example in the "comparisons failed for the last round of tests of PR https://github.com/cms-sw/cmssw/pull/41815 I see


![Screenshot from 2023-06-26 10-36-22](https://github.com/cms-sw/cmssw/assets/5082376/028a68c8-b4cf-4f0a-b971-8e56772ad0c9)

while in the DQM bin-by-bin comparisons of the same PR I see more workflows with changes:
![Screenshot from 2023-06-26 10-36-38](https://github.com/cms-sw/cmssw/assets/5082376/f6013c57-dfef-4771-abab-f03a30882dbc)


perhaps something to be investigated in another issue?

**Comment by emanueleusai** [comment]
Yes the two comparison methods have always shown differences. It might have to do with the different thresholds the two methods use to define what’s different/failed, but is was never really investigated (not even by previous DQM people afaik).
I support opening a separate issue for this.

I usually check both and I found out that actual differences in dqm plots show up in both. I believe “Bin-to-bin” tends to be more noisy (or sensitive) and pick up stuff that is not a real discrepancy.

**Comment by emanueleusai** [comment]
Btw it looks like the indexing db is broken. Last time it was fixed by deleting and recreating the index file but we were strongly advised against doing that by SW experts, so we are looking for other solutions .

**Comment by syuvivida** [comment]
Hello, 
The indexing of the development DQMGUI server vocms0731 is now back. One will start seeing output of comparison plots from the DQM bin-by-bin tools from the PR request.

**Comment by mmusich** [comment]
> The indexing of the development DQMGUI server vocms0731 is now back. One will start seeing output of comparison plots from the DQM bin-by-bin tools from the PR request.

OK, thanks I will close this issue for the time being.
