### ISSUE TITLE
Uninitialized member calib in p2eg::Cluster::calib

### ISSUE THREAD

**Issue by makortel** [cms-sw/cmssw#42094]
The CMSSW_13_2_NONLTO_X_2023-06-24-1100 IB reports a compilation warning
```
In file included from /data/cmsbld/jenkins/workspace/build-any-ib/w/tmp/BUILDROOT/3a90595df44bc94278b0469c0f46ff54/opt/cmssw/el8_amd64_gcc11/cms/cmssw-patch/CMSSW_13_2_NONLTO_X_2023-06-24-1100/src/L1Trigger/L1CaloTrigger/plugins/Phase2L1CaloEGammaEmulator.cc:54:
In member function 'p2eg::Cluster& p2eg::Cluster::operator=(const p2eg::Cluster&)',
    inlined from 'void p2eg::stitchClusterOverRegionBoundary(std::vector<p2eg::Cluster>&, int, int, int)' at /data/cmsbld/jenkins/workspace/build-any-ib/w/tmp/BUILDROOT/3a90595df44bc94278b0469c0f46ff54/opt/cmssw/el8_amd64_gcc11/cms/cmssw-patch/CMSSW_13_2_NONLTO_X_2023-06-24-1100/src/L1Trigger/L1CaloTrigger/interface/Phase2L1RCT.h:1563:48:
  /data/cmsbld/jenkins/workspace/build-any-ib/w/tmp/BUILDROOT/3a90595df44bc94278b0469c0f46ff54/opt/cmssw/el8_amd64_gcc11/cms/cmssw-patch/CMSSW_13_2_NONLTO_X_2023-06-24-1100/src/L1Trigger/L1CaloTrigger/interface/Phase2L1CaloEGammaUtils.h:857:19: warning: '<anonymous>.p2eg::Cluster::calib' may be used uninitialized [-Wmaybe-uninitialized]
   857 |       calib = rhs.calib;
      |               ~~~~^~~~~
In file included from /data/cmsbld/jenkins/workspace/build-any-ib/w/tmp/BUILDROOT/3a90595df44bc94278b0469c0f46ff54/opt/cmssw/el8_amd64_gcc11/cms/cmssw-patch/CMSSW_13_2_NONLTO_X_2023-06-24-1100/src/L1Trigger/L1CaloTrigger/plugins/Phase2L1CaloEGammaEmulator.cc:55:
/data/cmsbld/jenkins/workspace/build-any-ib/w/tmp/BUILDROOT/3a90595df44bc94278b0469c0f46ff54/opt/cmssw/el8_amd64_gcc11/cms/cmssw-patch/CMSSW_13_2_NONLTO_X_2023-06-24-1100/src/L1Trigger/L1CaloTrigger/interface/Phase2L1RCT.h: In function 'void p2eg::stitchClusterOverRegionBoundary(std::vector<p2eg::Cluster>&, int, int, int)':
/data/cmsbld/jenkins/workspace/build-any-ib/w/tmp/BUILDROOT/3a90595df44bc94278b0469c0f46ff54/opt/cmssw/el8_amd64_gcc11/cms/cmssw-patch/CMSSW_13_2_NONLTO_X_2023-06-24-1100/src/L1Trigger/L1CaloTrigger/interface/Phase2L1RCT.h:1563:48: note: '<anonymous>' declared here
 1563 |                                     c1.region());
      |                                                ^
```
https://cmssdt.cern.ch/SDT/cgi-bin/buildlogs/el8_amd64_gcc11/CMSSW_13_2_NONLTO_X_2023-06-24-1100/L1Trigger/L1CaloTrigger

**Comment by makortel** [comment]
assign l1

**Comment by makortel** [comment]
assign upgrade

**Comment by makortel** [comment]
The warning is emitted from the line
https://github.com/cms-sw/cmssw/blob/27ea50baba0a766fe0806d4961fbcd9759267aa0/L1Trigger/L1CaloTrigger/interface/Phase2L1CaloEGammaUtils.h#L857
in case the `Cluster` is constructed via
https://github.com/cms-sw/cmssw/blob/27ea50baba0a766fe0806d4961fbcd9759267aa0/L1Trigger/L1CaloTrigger/interface/Phase2L1CaloEGammaUtils.h#L829-L852
which indeed does not initialize `calib`.

As far as I can tell, the `calib` is only ever initialized by the default constructor
https://github.com/cms-sw/cmssw/blob/27ea50baba0a766fe0806d4961fbcd9759267aa0/L1Trigger/L1CaloTrigger/interface/Phase2L1CaloEGammaUtils.h#L816-L827
(even if it has an accessor
https://github.com/cms-sw/cmssw/blob/27ea50baba0a766fe0806d4961fbcd9759267aa0/L1Trigger/L1CaloTrigger/interface/Phase2L1CaloEGammaUtils.h#L882
).

**Comment by aloeliger** [comment]
@ekauffma Welcome to the crew. When you're ready this is your first job. Please contact @skkwan about what the initialization should be. I guess this will also get you experienced making PRs to CMSSW.

**Comment by aloeliger** [comment]
@makortel This should be closed by https://github.com/cms-sw/cmssw/pull/42111

**Comment by aloeliger** [comment]
+l1
