### ISSUE TITLE
Improve data-integrity check in ECAL GPU unpacker

### ISSUE THREAD

**Issue by missirol** [cms-sw/cmssw#42090]
#41977 was integrated in `13_2_X` as a potential solution to #39568 (and it was also backported to `13_0_X` and `13_1_X`).

Even after #41977, the treatment of integrity errors in the ECAL GPU unpacker is not yet identical to one in the ECAL CPU unpacker (see https://github.com/cms-sw/cmssw/pull/41977#issuecomment-1593827335 and replies), and this should be improved.

Attn: @cms-sw/ecal-dpg-l2

**Comment by missirol** [comment]
assign hlt

(Not strictly an HLT issue, but relevant to HLT.)

**Comment by makortel** [comment]
assign reconstruction, heterogeneous

**Comment by thomreis** [comment]
type ecal

**Comment by thomreis** [comment]
An improved version can be found in PR https://github.com/cms-sw/cmssw/pull/42301.

**Comment by missirol** [comment]
+hlt

Addressed in #42301 (which will be included in `13_3_0_pre1`), and backported down to the `13_0_X` cycle (#42394, #42406, #42395).

**Comment by missirol** [comment]
please close

Closing this issue. @cms-sw/heterogeneous-l2 and @cms-sw/reconstruction-l2 already signed the corresponding PR, so I assume they agree.
