### ISSUE TITLE
Question on GSF track to track association for low pt electrons

### ISSUE THREAD

**Issue by ArturAkh** [cms-sw/cmssw#42110]
Dear Egamma experts,

During my studies to fix [tau embedding](https://github.com/KIT-CMS/cmssw/tree/embedding_update_for_run3)
 for central CMS production, I've had a closer look into low pt electron reconstruction, in particular into:
 
 https://github.com/cms-sw/cmssw/blob/master/RecoEgamma/EgammaElectronProducers/plugins/LowPtGSFToTrackLinker.cc
 
 This producer performs GSF track to track association by making use of a common track reference. To do that, it checks for the right electron seed index in `preid` vector indexed by electron seeds, and acesses the trackRef of the PreId. I wonder why this indirect access to track references is required, where a much more direct access is possible,

using 

```cpp
gref->seedRef().castTo<reco::ElectronSeedRef>()->ctfTrack()
``` 

instead of

```cpp
preid->at(gref->seedRef().castTo<reco::ElectronSeedRef>().index()).trackRef()
```
Introducing the following line:

```cpp
std::cout << "Considering GSF track no. " << igsf << " with seed reference CTF track (id, index): (" << gref->seedRef().castTo<reco::ElectronSeedRef>()->ctfTrack().id() << ", " << gref->seedRef().castTo<reco::ElectronSeedRef>()->ctfTrack().index() << "), determined track ref (id, index) from preid: (" << trk.id() << ", " << trk.index() << ")" << std::endl;
```

after [LowPtGSFToTrackLinker.cc#L57](https://github.com/cms-sw/cmssw/blob/master/RecoEgamma/EgammaElectronProducers/plugins/LowPtGSFToTrackLinker.cc#L57)

results in the following output, when running on an example input file:

```bash
Begin processing the 11th record. Run 320823, Event 169761289, LumiSection 113 on stream 0 at 27-Jun-2023 14:36:38.789 CEST
Considering GSF track no. 0 with seed reference CTF track (id, index): (9:1653, 0), determined track ref (id, index) from preid: (9:1653, 0)                                                                                                                                   
Considering GSF track no. 1 with seed reference CTF track (id, index): (9:1653, 1), determined track ref (id, index) from preid: (9:1653, 1)                                                                                                                                   
Begin processing the 12th record. Run 320823, Event 169393937, LumiSection 113 on stream 0 at 27-Jun-2023 14:36:39.414 CEST
Considering GSF track no. 0 with seed reference CTF track (id, index): (9:1653, 0), determined track ref (id, index) from preid: (9:1653, 0)                                                                                                                                   
Begin processing the 13th record. Run 320823, Event 170028693, LumiSection 113 on stream 0 at 27-Jun-2023 14:36:40.214 CEST
Considering GSF track no. 0 with seed reference CTF track (id, index): (9:1653, 1), determined track ref (id, index) from preid: (9:1653, 1) 
```

So all in all, both accesses to the track reference are equivalent in terms of `id()` and `index()`.

Is there something I'm missing about `preid`, like backward-compatibility, or some kind of a corner case?

Cheers,

Artur

**Comment by makortel** [comment]
assign reconstruction

@cms-sw/egamma-pog-l2

**Comment by swagata87** [comment]
tagging developer of low-pT electron reco @bainbrid

**Comment by bainbrid** [comment]
Hi @ArturAkh please go ahead if you feel the code is an improvement.

**Comment by ArturAkh** [comment]
Thanks @bainbrid,

Corresponding PR is created: https://github.com/cms-sw/cmssw/pull/42690

**Comment by mandrenguyen** [comment]
+reconstruction
Issue seems resolved by https://github.com/cms-sw/cmssw/pull/42690

**Comment by makortel** [comment]
@cmsbuild, please close
