### ISSUE TITLE
Unit test RunInfoStart_O2O_test failing: exceeded simultaneous SESSIONS_PER_USER limit 

### ISSUE THREAD

**Issue by iarspider** [cms-sw/cmssw#42160]
This unit test started failing in CMSSW_13_2_X_2023-06-28-2300, failures also seen in PR tests:

```
%MSG
ORA-02391: exceeded simultaneous SESSIONS_PER_USER limit (authenticating) Error ORA-02391: exceeded simultaneous SESSIONS_PER_USER limit (authenticating)
ORA-02391: exceeded simultaneous SESSIONS_PER_USER limit (authenticating) Error ORA-02391: exceeded simultaneous SESSIONS_PER_USER limit (authenticating)
ORA-02391: exceeded simultaneous SESSIONS_PER_USER limit (authenticating) Error ORA-02391: exceeded simultaneous SESSIONS_PER_USER limit (authenticating)
ORA-02391: exceeded simultaneous SESSIONS_PER_USER limit (authenticating) Error ORA-02391: exceeded simultaneous SESSIONS_PER_USER limit (authenticating)
ORA-02391: exceeded simultaneous SESSIONS_PER_USER limit (authenticating) Error ORA-02391: exceeded simultaneous SESSIONS_PER_USER limit (authenticating)
ORA-02391: exceeded simultaneous SESSIONS_PER_USER limit (authenticating) Error ORA-02391: exceeded simultaneous SESSIONS_PER_USER limit (authenticating)
ORA-02391: exceeded simultaneous SESSIONS_PER_USER limit (authenticating) Error ORA-02391: exceeded simultaneous SESSIONS_PER_USER limit (authenticating)
----- Begin Fatal Exception 29-Jun-2023 13:17:25 CEST-----------------------
An exception of category 'StdException' occurred while
   [0] Calling endJob for module RunInfoPopConAnalyzer/'popConRunInfo'
Exception Message:
A std::exception was thrown.
Connection on "oracle://cms_omds_adg/CMS_RUNINFO_R" cannot be established ( CORAL : "ConnectionPool::getSessionFromNewConnection" from "CORAL/Services/ConnectionService" )
----- End Fatal Exception -------------------------------------------------
```

Should we ask CERN IT to raise the limit, or should we reduce the number of IBs we build?

**Comment by iarspider** [comment]
assign core,db

**Comment by francescobrivio** [comment]
Hi @iarspider,
> ORA-02391: exceeded simultaneous SESSIONS_PER_USER limit (authenticating) Error ORA-02391: exceeded simultaneous SESSIONS_PER_USER limit (authenticating)

What is the user exceeding the number of connections?
I just want to make sure that this does not affect the production RunInfo O2O....

About
> Should we ask CERN IT to raise the limit, or should we reduce the number of IBs we build?

Are we currently building more IBs than in the past?
I don't recall seeing this issue in the past...but my experience might be limited in time...

**Comment by iarspider** [comment]
@francescobrivio unfortunately there is no additional information about a user who is connecting too much


> Are we currently building more IBs than in the past?

It was a bit of a wild guess from my side. Yes, we have recently (last week) added 4 more IBs, but maybe it's just a coincidence.

**Comment by iarspider** [comment]
It seems that this was a glitch or an issue on DB side. Let's close it now.
