### ISSUE TITLE
FileReadError exception leading to 8001 exit code instead of 8021

### ISSUE THREAD

**Issue by makortel** [cms-sw/cmssw#42179]
A log file analyzed in https://github.com/cms-sw/cmssw/issues/40437#issuecomment-1618883032 shows a case where FileReadError exception lead to 8001 exit code instead of 8021. The job used CMSSW_12_4_14_patch1. Based on the exception message, it seems to me the exception in question is thrown here
https://github.com/cms-sw/cmssw/blob/b517d9f7d28fb3806cc93e9adbaeb4c85352cbdb/IOPool/Input/src/RootTree.cc#L383-L394

**Comment by makortel** [comment]
assign core

**Comment by makortel** [comment]
Another case was reported in https://cms-talk.web.cern.ch/t/corrupted-files/32728, in CMSSW_13_0_15.

**Comment by makortel** [comment]
Could we have a `catch (cms::Exception e)` somewhere that slices the caught exception? That could explain the message to be passed, but the return code to become the generic 8001 that `cms::Exception` returns.

**Comment by makortel** [comment]
I didn't find any slicing `catch ()` in the framework with `git grep`. I also didn't find anything suspicious by visual inspection in `ProductResolver.cc` and `Path.cc` (looking places that added context to the exception message).

@wddgit Could you look into this? I'd hope the problem would be reproducible by just throwing the `edm::Exception` in place of the `try`-`catch` I pointed to in the issue description.

**Comment by belforte** [comment]
having the correct exit code will facilitate automated reporting, checking and fixing of corrupted files a topic which has now reached near the top of the queue for DataTransfer Ops https://indico.cern.ch/event/1356295/

**Comment by belforte** [comment]
We surely have plenty of examples of 
```
== CMSSW:       [a] Fatal Root Error: @SUB=TBasket::ReadBasketBuffers
== CMSSW: fNbytes = 236064, fKeylen = 143, fObjlen = 4399508, noutot = 0, nout=0, nin=235921, nbuf=4399508
```
which exit with 8021. I did not check in those cases if there's a lzma report as well, it seemed enough to trigger a file checksum verification to me. 
Let me know if you like some examples.

**Comment by makortel** [comment]
> We surely have plenty of examples of
> 
> ```
> == CMSSW:       [a] Fatal Root Error: @SUB=TBasket::ReadBasketBuffers
> == CMSSW: fNbytes = 236064, fKeylen = 143, fObjlen = 4399508, noutot = 0, nout=0, nin=235921, nbuf=4399508
> ```
> 
> which exit with 8021.

Could you give a pointer to the log of this case, or paste the full CMSSW exception message here?

**Comment by wddgit** [comment]
I'll start looking at this after lunch.

**Comment by belforte** [comment]
here's one such job:
https://cmsweb.cern.ch:8443/scheddmon/0119/jgomespi/231205_134936:jgomespi_crab_DYJetsToLL_M-50_postVFP/job_out.808.16.txt

**Comment by makortel** [comment]
> here's one such job:
> https://cmsweb.cern.ch:8443/scheddmon/0119/jgomespi/231205_134936:jgomespi_crab_DYJetsToLL_M-50_postVFP/job_out.808.16.txt

Thanks. This job used CMSSW_10_6_26. The context line 0 is added in
https://github.com/cms-sw/cmssw/blob/d884dab09c6356b62a4ba31970a461da049698c7/IOPool/Input/src/RootDelayedReader.cc#L80-L84

The exception handling in this class was changed in https://github.com/cms-sw/cmssw/pull/36743, that was merged in 12_3_X.

@belforte I'm becoming more interested in various examples in either way (correct vs. incorrect exit code).

**Comment by wddgit** [comment]
This looks suspicious. I have not verified this or looked carefully yet but this looks suspicious like it might slice. I just noticed it. Possibly unrelated...

https://cmssdt.cern.ch/dxr/CMSSW/source/FWCore/Framework/src/ProductResolvers.cc#302

I'll continue working on this.

**Comment by wddgit** [comment]
Only one match for this:

```
Singularity> git grep --cached "reading from source"
FWCore/Framework/src/ProductResolvers.cc:      e.addContext(std::string("While reading from source ") + bd.className() + " " + bd.moduleLabel() + " '" +
```

And this points to ProductResolvers.cc in extendException. There are four places where that is used. One is line 302 and there are 3 other similar spots in the same file. I have not succeeded in reproducing this or that proving my fix gets rid of the problem, but the fix is obvious. I could just submit a PR with the fix and then if the problem does not go away we revisit this.

Change:
```
throw extendException(e, branchDescription(), mcc);
```
to:
```
extendException(e, branchDescription(), mcc);
throw;
```

**Comment by makortel** [comment]
Good catch! The problem is that e.g. in
```cpp
try {
  ...
} catch(cms::Exception& e) {
  throw e;
}
```
the `e` is sliced to `cms::Exception`, while plain `throw;` would re-throw the actual object, right?

This is how I interpret https://en.cppreference.com/w/cpp/language/throw
> First, copy-initializes the exception object from expression

vs

>  Rethrows the currently handled exception.

**Comment by wddgit** [comment]
For the moment, I'll continue to try to figure out how to reproduce the problem. Simply throwing at the location you suggested yields the correct error code so there is more to it than that...

**Comment by wddgit** [comment]
Yes to your comment.

**Comment by makortel** [comment]
The `extendException()` function, and throwing its return value, was added in https://github.com/cms-sw/cmssw/pull/36739, that was merged in 12_3_X. This is consistent with 10_6_X job giving the correct exit code, but 12_4_X and 13_0_X jobs not (although the sample size is way too small to draw real conclusions from there).

**Comment by wddgit** [comment]
I reproduced the error and verified the fix works. At first I was throwing on every getEntry, but the first one is for EventAuxiliary which is not a delayed read. If you wait for some product read by a module then the problem reproduces and the fix makes it go away. I submit a PR soon.

**Comment by makortel** [comment]
Thanks @wddgit ! I think the fix needs to be backported to

- [ ]  13_3_X
- [ ]  13_2_X
- [ ]  13_1_X
- [ ]  13_0_X
- [ ]  12_6_X
- [ ]  12_4_X

but let's get the 14_0_X PR in first.

**Comment by makortel** [comment]
> I'm becoming more interested in various examples in either way (correct vs. incorrect exit code).

@belforte I think I won't need more examples anymore.

**Comment by wddgit** [comment]
Just submitted #43579 which fixes the problem is 14_0_X and adds a unit test.

**Comment by makortel** [comment]
@wddgit The master PR was merged. Could you look into backporting it to the release cycles listed in https://github.com/cms-sw/cmssw/issues/42179#issuecomment-1856872377 ?

**Comment by wddgit** [comment]
I'll start on that this afternoon.

**Comment by wddgit** [comment]
All the backport pull requests are submitted now.

**Comment by makortel** [comment]
+core

All backport PRs have been merged
