### ISSUE TITLE
Issue with HGCHitsEE in DD4hep in 13_2

### ISSUE THREAD

**Issue by srimanob** [cms-sw/cmssw#42224]
To record the current issue reported from phase-2 DD4Hep-DDD validation. The full report can be found from SIM meeting by S. Banerjee on ([7 July](https://indico.cern.ch/event/1303716/))

EGamma reports discrepancy in |eta| > 3. The discrepancy also seen in HGCAL. See plots attached. Looking closely, it seems we may have an issue with SimHits of HGCHitsEE in DD4hep. Their is a significant file size difference shown up in g4SimHits_HGCHitsEE collection,
+ DDD: PCaloHits_g4SimHits_HGCHitsEE_SIM. 312457 73636
+ DD4hep: PCaloHits_g4SimHits_HGCHitsEE_SIM. 217273 50472.4
(single electron sample, no pu, with 2.8 < |eta| < 3.5)

Adapting Validation/HGCalValidation/test/python/runHGCHitAnalyzer_cfg.py, it can be seen clearly that we have more hits from DDD. Log file can be found in
`/afs/[cern.ch/user/s/srimanob/public/ForD98DD4hep/`

<img width="800" alt="ZEE_EffvsGenPt_Electron" src="https://github.com/cms-sw/cmssw/assets/4701449/702248c0-43b6-45ad-9311-ef2f3cbd4891">

<img width="800" alt="ZEE_PvsEta_Electron" src="https://github.com/cms-sw/cmssw/assets/4701449/4ca7cee0-1544-4602-a78a-2ffdc2231fe5">

<img width="800" alt="ZEE_HGCALSimCluster" src="https://github.com/cms-sw/cmssw/assets/4701449/9cec30ca-70b9-4bec-aef8-75f684988e26">

**Comment by makortel** [comment]
assign geometry,upgrade

**Comment by srimanob** [comment]
Report in https://indico.cern.ch/event/1313529/
Fix: https://github.com/cms-sw/cmssw/pull/42442

Will keep this topic opens until validation results come.
