### ISSUE TITLE
Missing RelVal Setup for 2023D

### ISSUE THREAD

**Issue by mmusich** [cms-sw/cmssw#42340]
Having a 2023D run -based RelVal setup that does re-HLT might be very beneficial for offline tracking (and other) studies for the recovery of the BPix Layer3/4mS7 driven inefficiency (see [details here](https://indico.cern.ch/event/1307608/contributions/5500387/attachments/2687593/4663675/Tracking_POG_PPD_meeting_20Jul_2023.pdf)). 
Ideally this workflow should include re-HLT.
Could please PdmV have a look and add this to the matrix?
Thanks

**Comment by mmusich** [comment]
assign pdmv

**Comment by sunilUIET** [comment]
@mmusich we will work on it

**Comment by sunilUIET** [comment]
Relevant PR along with backports are in place

**Comment by sunilUIET** [comment]
+pdmv

**Comment by makortel** [comment]
@cmsbuild, please close
