### ISSUE TITLE
[GPU] Unit test `testEigenGPUNoFit_t` failing when testing inverse 5x5

### ISSUE THREAD

**Issue by aandvalenzuela** [cms-sw/cmssw#42460]
Hello,

Unit test `testEigenGPUNoFit_t` (module `RecoTracker/PixelTrackFitting`) is failing when running `TEST INVERSE 5x5` with:
```
===== Test "testEigenGPUNoFit_t" ====
TEST EIGENVALUES
TEST INVERSE 3x3
TEST INVERSE 4x4
TEST INVERSE 5x5
testEigenGPUNoFit_t: /tmp/avalenzu/CMSSW_13_3_GPU_X_2023-08-02-2300/src/RecoTracker/PixelTrackFitting/test/test_common.h:24: bool isEqualFuzzy(C1, C2, double) [with C1 = Eigen::Matrix<double, 5, 5>; C2 = Eigen::Matrix<double, 5, 5>]: Assertion `std::abs(a(i, j) - b(i, j)) < std::min(std::abs(a(i, j)), std::abs(b(i, j))) * epsilon' failed.
/bin/sh: line 1: 1044014 Aborted                 (core dumped) sh -c 'testEigenGPUNoFit_t '

---> test testEigenGPUNoFit_t had ERRORS
TestTime:4
^^^^ End Test testEigenGPUNoFit_t ^^^^                                         
```

We already had a similar issue when testing the 5x5 inverse in this unit test (See https://github.com/cms-sw/cmssw/issues/33797).

I can reproduce it in lxplus-gpu nodes.

**Comment by makortel** [comment]
assign reconstruction, heterogeneous

FYI @cms-sw/tracking-pog-l2 @VinInn

**Comment by fwyzard** [comment]
> Unit test `testEigenGPUNoFit_t` (module `RecoTracker/PixelTrackFitting`) is failing when running `TEST INVERSE 5x5`

When did it start to fail ?

**Comment by aandvalenzuela** [comment]
It failed yesterday for the first time [CMSSW_13_3_GPU_X_2023-08-01-2300](https://cmssdt.cern.ch/SDT/cgi-bin/showBuildLogs.py/el8_amd64_gcc11/www/tue/13.3.GPU-tue-23/CMSSW_13_3_GPU_X_2023-08-01-2300?utests) and today again [CMSSW_13_3_GPU_X_2023-08-02-2300](https://cmssdt.cern.ch/SDT/cgi-bin/showBuildLogs.py/el8_amd64_gcc11/www/wed/13.3.GPU-wed-23/CMSSW_13_3_GPU_X_2023-08-02-2300?utests)

**Comment by iarspider** [comment]
@fwyzard are there any steps that we (externals) need to do to help triage this?

**Comment by iarspider** [comment]
@fwyzard yes: https://cmssdt.cern.ch/SDT/cgi-bin/logreader/el8_amd64_gcc11/CMSSW_13_3_GPU_X_2023-10-01-2300/unitTestLogs/RecoTracker/PixelTrackFitting#/471-471

**Comment by fwyzard** [comment]
OK.

I will try to set aside some time to look into it.

**Comment by fwyzard** [comment]
Fixed by https://github.com/cms-sw/cmsdist/pull/8782 .
