### ISSUE TITLE
Request to build `CMSSW_13_2_1`

### ISSUE THREAD

**Issue by missirol** [cms-sw/cmssw#42569]
(Since there is likely no ORP meeting, I'm asking this via a GitHub issue, which is maybe better than email to involve all interested parties.)

HLT would like to have a new release of `CMSSW_13_2_X`. That would be `CMSSW_13_2_1`, afaik.

 - [#42489](https://github.com/cms-sw/cmssw/pull/42489) (merged) is needed to build the 2023 HIon menu in `ConfDB`.
 - TSG is also requesting to include [#42559](https://github.com/cms-sw/cmssw/pull/42559) (which depends on [cmsdist#8646](https://github.com/cms-sw/cmsdist/pull/8646)) in this next `13_2_X` release, for GPU-related developments for HLT.
 - (A few other PRs relevant to HLT and/or HIon have also been merged already in `CMSSW_13_2_X` since `CMSSW_13_2_0`.)

Other groups can list here their needs for `CMSSW_13_2_1`.

Preferred timeline: by the end of this week.

FYI: @cms-sw/hlt-l2 @fwyzard @silviodonato @mmusich

---

List of PRs targeting `CMSSW_13_2_1`:
 - [x] [#42559](https://github.com/cms-sw/cmssw/pull/42559) (which depends on [cmsdist#8646](https://github.com/cms-sw/cmsdist/pull/8646))
 - [x] [#42481](https://github.com/cms-sw/cmssw/pull/42481) ([#42569 (comment)](https://github.com/cms-sw/cmssw/issues/42569#issuecomment-1678842015))
 - [x] [#42545](https://github.com/cms-sw/cmssw/pull/42545) ([#42569 (comment)](https://github.com/cms-sw/cmssw/issues/42569#issuecomment-1679017619))
 - [x] [#42583](https://github.com/cms-sw/cmssw/pull/42583) ([#42569 (comment)](https://github.com/cms-sw/cmssw/issues/42569#issuecomment-1680612855))
 - [x] [#42585](https://github.com/cms-sw/cmssw/pull/42585) ([#42569 (comment)](https://github.com/cms-sw/cmssw/issues/42569#issuecomment-1680553936))

Type of non-standard builds:
 - SKYLAKEAVX512 ([#42569 (comment)](https://github.com/cms-sw/cmssw/issues/42569#issuecomment-1678842015))

**Comment by missirol** [comment]
assign orp

**Comment by missirol** [comment]
The "fully signed" part was not intended. :)

**Comment by fwyzard** [comment]
If possible, let me add two requests:
  - can we include #42481 in 13.2.1 ?
  - can we make also a SKYLAKEAVX512 build for 13.2.1 ?

**Comment by mmusich** [comment]
Might be convenient to wait also for https://github.com/cms-sw/cmssw/pull/42545

**Comment by missirol** [comment]
The PRs mentioned so far for `13_2_1` are merged (I left a list at the bottom of the description). I don't see other urgent PRs in the `13_2_X` queue, so from my point of view things are ready.

**Comment by Martin-Grunewald** [comment]
Apparently one more PR needed before building (to fix an issue similar to #42489 )

**Comment by perrotta** [comment]
> Apparently one more PR needed before building (to fix an issue similar to #42489 )

And the PR number is? When it is expected?

**Comment by Martin-Grunewald** [comment]
Sorry, not available yet (mentioned in TSG meeting today).

**Comment by mmusich** [comment]
if we are to wait, I would be glad if we could throw in https://github.com/cms-sw/cmssw/pull/42583 as well.

**Comment by missirol** [comment]
I added #42583 and "backport of #42584" to the list. Hopefully these can be ready by tomorrow.

**Comment by mmusich** [comment]
"backport of https://github.com/cms-sw/cmssw/pull/42584" is https://github.com/cms-sw/cmssw/pull/42585

**Comment by antoniovilela** [comment]
Started 13_2_1 build (#42596). Will wait for this to finish to build the SKYLAKEAVX.

**Comment by missirol** [comment]
Thanks, @cms-sw/orp-l2 @antoniovilela !

**Comment by perrotta** [comment]
The CMSSW_13_2_1 release is ready with all the requested PRs: https://github.com/cms-sw/cmssw/releases/tag/CMSSW_13_2_1
As soon as also the SKYLAKEAVX512 build will become available this issue can get closed

**Comment by perrotta** [comment]
Also the SKYLAKEAVX512 was built, see https://github.com/cms-sw/cmssw/releases/tag/CMSSW_13_2_1_SKYLAKEAVX512 @fwyzard

**Comment by perrotta** [comment]
+orp

**Comment by missirol** [comment]
please close

(For the record, the bot got confused in https://github.com/cms-sw/cmssw/issues/42569#issuecomment-1678667296, and this should maybe be improved.)

**Comment by perrotta** [comment]
> (For the record, the bot got confused in [#42569 (comment)](https://github.com/cms-sw/cmssw/issues/42569#issuecomment-1678667296), and this should maybe be improved.)

Well, in any case it was an action required for orp, then the assignment was not even too wrong :-)

**Comment by mmusich** [comment]
>  in any case it was an action required for orp, then the assignment was not even too wrong :-)

I think the problem here is that (afaiu) the bot couples `orp-pending` with the `fully-signed` labels which is generally suitable in ordinary PRs (since no PR is purely under ORP), but not OK here, since there was no action pending from other groups.
