### ISSUE TITLE
Alpaka plugins does not build when put in src folder

### ISSUE THREAD

**Issue by kakwok** [cms-sw/cmssw#42695]
Some packages, such as `RecoLocalCalo/HcalRecProducers`, are defined as an `EDM_PLUGIN`, but the source files are put in a `src` folder instead of `plugin` folders:
https://github.com/cms-sw/cmssw/blob/master/RecoLocalCalo/HcalRecProducers/BuildFile.xml

When I tried to add an Alpaka plugin to the package with:
```
<flags EDM_PLUGIN="1"/>
<flags ALPAKA_BACKENDS="1"/>
```
I get:
```
~/GPU/CMSSW_13_0_6/src/RecoLocalCalo/HcalRecProducers > scram b -j 8
****ERROR: Plugin name should be same as the library name. Please fix the "src/RecoLocalCalo/HcalRecProducers/BuildFile.xml" file and replace "RecoLocalCaloHcalRecProducers" with "RecoLocalCaloHcalRecProducersCudaAsync"
           Please fix the above error otherwise library "RecoLocalCaloHcalRecProducersCudaAsync" will not be registered as plugin.
Please fix the above error first.
```

Is Alpaka plugins under `src` folder supported?

**Comment by makortel** [comment]
assign core, heterogeneous

**Comment by makortel** [comment]
@smuzaffar Any thoughts?

(mostly for the record, we had also an earlier corner case misbehavior related to `ALPAKA_BACKENDS` in https://github.com/cms-sw/cmssw/issues/40846)

**Comment by fwyzard** [comment]
I vote to move all plug-ins under `plugins` anyway.

**Comment by makortel** [comment]
> I vote to move all plug-ins under `plugins` anyway.

Let's say then this is the way to go (which is anyway written in our code rules).

**Comment by makortel** [comment]
+1

**Comment by makortel** [comment]
@cmsbuild, please close
