### ISSUE TITLE
DAS QL ERROR in Alignment/OfflineValidation/* and Configuration/PyReleaseValidation/test-das-selected-lumis tests

### ISSUE THREAD

**Issue by iarspider** [cms-sw/cmssw#42729]
We are observing DAS QL ERRORs in 4 unit tests for some platforms since CMSSW_13_3_X_2023-09-05-1100. Some examples:

### CMSSW_13_3_X_2023-09-05-2300/el9_amd64_gcc11

* [Configuration/PyReleaseValidation/test-das-selected-lumis](https://cmssdt.cern.ch/SDT/cgi-bin/logreader/el9_amd64_gcc11/CMSSW_13_3_X_2023-09-05-2300/unitTestLogs/Configuration/PyReleaseValidation#/11-11) 
* [Alignment/OfflineValidation/SubmitPVrbr](https://cmssdt.cern.ch/SDT/cgi-bin/logreader/el9_amd64_gcc11/CMSSW_13_3_X_2023-09-05-2300/unitTestLogs/Alignment/OfflineValidation#/2838-2838)
* [Alignment/OfflineValidation/SubmitPVsplit](https://cmssdt.cern.ch/SDT/cgi-bin/logreader/el9_amd64_gcc11/CMSSW_13_3_X_2023-09-05-2300/unitTestLogs/Alignment/OfflineValidation#/2879-2879)
* [PhysicsTools/Utilities/test_edmPickEvents](https://cmssdt.cern.ch/SDT/cgi-bin/logreader/el9_amd64_gcc11/CMSSW_13_3_X_2023-09-05-2300/unitTestLogs/PhysicsTools/Utilities#/1565-1565)

### CMSSW_13_3_CLANG_X_2023-09-05-2300/el8_amd64_gcc11

* [Configuration/PyReleaseValidation/test-das-selected-lumis](https://cmssdt.cern.ch/SDT/cgi-bin/logreader/el8_amd64_gcc11/CMSSW_13_3_CLANG_X_2023-09-05-2300/unitTestLogs/Configuration/PyReleaseValidation#/11-11) 
* [Alignment/OfflineValidation/SubmitPVrbr](https://cmssdt.cern.ch/SDT/cgi-bin/logreader/el8_amd64_gcc11/CMSSW_13_3_CLANG_X_2023-09-05-2300/unitTestLogs/Alignment/OfflineValidation#/2839-2839) 
* [Alignment/OfflineValidation/SubmitPVsplit](https://cmssdt.cern.ch/SDT/cgi-bin/logreader/el8_amd64_gcc11/CMSSW_13_3_CLANG_X_2023-09-05-2300/unitTestLogs/Alignment/OfflineValidation#/2880-2880)
* [PhysicsTools/Utilities/test_edmPickEvents](https://cmssdt.cern.ch/SDT/cgi-bin/logreader/el8_amd64_gcc11/CMSSW_13_3_CLANG_X_2023-09-05-2300/unitTestLogs/PhysicsTools/Utilities#/1565-1565)

### CMSSW_13_3_NONLTO_X_2023-09-05-1100/el8_amd64_gcc11

* [Configuration/PyReleaseValidation/test-das-selected-lumis](https://cmssdt.cern.ch/SDT/cgi-bin/logreader/el8_amd64_gcc11/CMSSW_13_3_NONLTO_X_2023-09-05-1100/unitTestLogs/Configuration/PyReleaseValidation#/11-11) 
* [Alignment/OfflineValidation/SubmitPVrbr](https://cmssdt.cern.ch/SDT/cgi-bin/logreader/el8_amd64_gcc11/CMSSW_13_3_NONLTO_X_2023-09-05-1100/unitTestLogs/Alignment/OfflineValidation#/2836-2836)
* [Alignment/OfflineValidation/SubmitPVsplit](https://cmssdt.cern.ch/SDT/cgi-bin/logreader/el8_amd64_gcc11/CMSSW_13_3_NONLTO_X_2023-09-05-1100/unitTestLogs/Alignment/OfflineValidation#/2877-2877)
* [PhysicsTools/Utilities/test_edmPickEvents](https://cmssdt.cern.ch/SDT/cgi-bin/logreader/el8_amd64_gcc11/CMSSW_13_3_NONLTO_X_2023-09-05-1100/unitTestLogs/PhysicsTools/Utilities#/1565-1565)

**Comment by makortel** [comment]
@vkuznet Would you have any thoughts?

**Comment by vkuznet** [comment]
@makortel , DAS server is stable and did not change for a long time. Moreover, using [Configuration/PyReleaseValidation/test-das-selected-lumis](https://cmssdt.cern.ch/SDT/cgi-bin/logreader/el9_amd64_gcc11/CMSSW_13_3_X_2023-09-05-2300/unitTestLogs/Configuration/PyReleaseValidation#/11-11) test I see it complains about the following:
```
+ QUERY='lumi,file dataset=/HIHardProbes/HIRun2018A-v1/RAW run=326479'
+ dasgoclient --limit 0 --query 'lumi,file dataset=/HIHardProbes/HIRun2018A-v1/RAW run=326479' --format json
+ das-selected-lumis.py 1,23
+ grep '^/store/'
2023/09/06 03:3[6:](https://cmssdt.cern.ch/SDT/cgi-bin/logreader/el9_amd64_gcc11/CMSSW_13_3_X_2023-09-05-2300/unitTestLogs/Configuration/PyReleaseValidation#/6)53 ERROR DAS QL ERROR, query=lumi , file dataset = /HIHardProbes/HIRun2018A-v1/RAW run = 326479, idx=2, msg=unable to parse DAS query
```

But if I run the query on lxplus it works just fine, see
```
dasgoclient --limit 0 --query 'lumi,file dataset=/HIHardProbes/HIRun2018A-v1/RAW run=326479' --format json
{"status":"ok", "ecode":"", "mongo_query":{"query":"lumi,file dataset=/HIHardProbes/HIRun2018A-v1/RAW run=326479","hash":"6e4d3c0eb37cb387fdc3f507656ef7fb","spec":{"dataset":"/HIHardProbes/HIRun2018A-v1/RAW","run":"326479"},"fields":["lumi","file"],"pipe":"","instance":"prod/global","detail":true,"system":"","filters":{},"aggregators":[],"error":"","tstamp":1694008068}, "nresults":4, "timestamp":1694008069, "ctime":1, "data":[
{"das":{"expire":1694008069,"instance":"prod/global","primary_key":"file.name","record":1,"services":["dbs3:file_lumi4dataset"]},"file":[{"name":"/store/hidata/HIRun2018A/HIHardProbes/RAW/v1/000/326/479/00000/45001EBC-B4D4-9043-A276-8F3AF621C64A.root"}],"lumi":[{"number":[11,13,12,14]}]} ,
{"das":{"expire":1694008069,"instance":"prod/global","primary_key":"file.name","record":1,"services":["dbs3:file_lumi4dataset"]},"file":[{"name":"/store/hidata/HIRun2018A/HIHardProbes/RAW/v1/000/326/479/00000/0E2CC5D5-9D87-7348-9219-B00CD718C847.root"}],"lumi":[{"number":[7,9,10,8]}]} ,
{"das":{"expire":1694008069,"instance":"prod/global","primary_key":"file.name","record":1,"services":["dbs3:file_lumi4dataset"]},"file":[{"name":"/store/hidata/HIRun2018A/HIHardProbes/RAW/v1/000/326/479/00000/853DBE29-53BA-9A44-9FDD-58E4E9064EB1.root"}],"lumi":[{"number":[2,3,4,6,5]}]} ,
{"das":{"expire":1694008069,"instance":"prod/global","primary_key":"file.name","record":1,"services":["dbs3:file_lumi4dataset"]},"file":[{"name":"/store/hidata/HIRun2018A/HIHardProbes/RAW/v1/000/326/479/00000/7B3F72ED-E183-3F4B-9FE4-DAE6D911403E.root"}],"lumi":[{"number":[18,16,19,17,15]}]}
]
}
```

So, my conclusion is to check for either extra spaces or non printed characters, like newline in query passed to DAS, and make sure there are none of them. For instance, I've seen people use their tools to cut and paste queries, which may contain some hidden characters. I suggest that you add validator for DAS query you pass to the dasgoclient to avoid empty spaces and any other special characters. 

And, I did checked that if I use empty spaces on lxplus everything works like expected, i.e. all queries below produce the same result:
```
dasgoclient --limit 0 --query 'lumi,file dataset=/HIHardProbes/HIRun2018A-v1/RAW run=326479' --format json
dasgoclient --limit 0 --query 'lumi ,file dataset=/HIHardProbes/HIRun2018A-v1/RAW run=326479' --format json
dasgoclient --limit 0 --query 'lumi , file dataset = /HIHardProbes/HIRun2018A-v1/RAW run=326479' --format json
```

I also advise you to check `das-selected-lumis.py` which is used in combination with dasgoclient to get some other stuff from the query and instead rely on dasgoclient filters, like `grep` to get the info you need, e.g.

```
dasgoclient --limit 0 --query 'lumi , file dataset = /HIHardProbes/HIRun2018A-v1/RAW run=326479 | grep file.name'
/store/hidata/HIRun2018A/HIHardProbes/RAW/v1/000/326/479/00000/853DBE29-53BA-9A44-9FDD-58E4E9064EB1.root
/store/hidata/HIRun2018A/HIHardProbes/RAW/v1/000/326/479/00000/7B3F72ED-E183-3F4B-9FE4-DAE6D911403E.root
/store/hidata/HIRun2018A/HIHardProbes/RAW/v1/000/326/479/00000/45001EBC-B4D4-9043-A276-8F3AF621C64A.root
/store/hidata/HIRun2018A/HIHardProbes/RAW/v1/000/326/479/00000/0E2CC5D5-9D87-7348-9219-B00CD718C847.root
```
or
```
dasgoclient --limit 0 --query 'lumi , file dataset = /HIHardProbes/HIRun2018A-v1/RAW run=326479 | grep lumi.number'
[2,3,4,6,5]
[18,16,19,17,15]
[11,13,12,14]
[7,9,10,8]
```

**Comment by makortel** [comment]
Thanks @vkuznet for checking. I wonder though if the problem would be only in the queries, how could they start to fail only sporadically?

**Comment by vkuznet** [comment]
@makortel I can't answer this question. It is a possibility that DAS server may had hickup at the time of the query, but this should be checked on k8s clusters where we run DAS to match timestamp of the test queries. If you need to do such studies you may contact CMSWEB team. Said that, DAS server (as any other) on k8s are set in auto-mode, i.e. if DAS service hickup or experience problem it will be restarted based on specific requirements defined for it in k8s manifest file. Apart from that I can't say much. The log output only suggest that it was DAS QL error which happen either from the following conditions:
- provided query is wrong or malformed
- DAS server does not have query map (which may occur if during its update cycle github does not respond to provide new map), but if I recall the cached map should be used in this case.
- if there is an issue with DAS server itself, e.g. it was busy processing other queries (trust me we have user who abuse DAS using large number of concurrent queries, we have seen the load which imitate DDoS). In other words, it is concurrency issue which some user may create at any time. If this is the case we can increase number of DAS instances to mitigate the load.

Any of these conditions can lead to problem you saw, and most likely it can be first or third.

**Comment by makortel** [comment]
There were no failures of this kind in CMSSW_13_3_X_2023-09-06-1100 and 
CMSSW_13_3_X_2023-09-06-2300.

**Comment by iarspider** [comment]
Was probably a network or das server hiccup. Closing.
