### ISSUE TITLE
[PPC64] TestConfigDP times out

### ISSUE THREAD

**Issue by iarspider** [cms-sw/cmssw#42747]
Recent occurrences: [1](https://cmssdt.cern.ch/SDT/cgi-bin/logreader/el8_ppc64le_gcc11/CMSSW_13_3_X_2023-09-04-2300/unitTestLogs/Configuration/DataProcessing#/1357-1357), [2](https://cmssdt.cern.ch/SDT/cgi-bin/logreader/el8_ppc64le_gcc11/CMSSW_13_3_X_2023-09-05-2300/unitTestLogs/Configuration/DataProcessing#/1167-1167), [3](https://cmssdt.cern.ch/SDT/cgi-bin/logreader/el8_ppc64le_gcc11/CMSSW_13_3_X_2023-09-06-2300/unitTestLogs/Configuration/DataProcessing#/803-803), [4](https://cmssdt.cern.ch/SDT/cgi-bin/logreader/el8_ppc64le_gcc11/CMSSW_13_3_X_2023-09-07-2300/unitTestLogs/Configuration/DataProcessing#/1164-1164), [5](https://cmssdt.cern.ch/SDT/cgi-bin/logreader/el8_ppc64le_gcc11/CMSSW_13_3_X_2023-09-08-2300/unitTestLogs/Configuration/DataProcessing#/1415-1415). First failure seem to be on 2023-08-23

The point at which the unit test fails seems random.

**Comment by iarspider** [comment]
assign operations

**Comment by dan131riley** [comment]
The ones I looked at all had
```
TestTime:5400
```
which likely means it took too long and exceeded the test execution timeout.  Random locations might mean everything in that test is taking longer than expected?

**Comment by smuzaffar** [comment]
https://github.com/cms-sw/cmssw/blob/master/Configuration/DataProcessing/test/run_CfgTest.sh runs too many tests.  I would suggest to split it in multiple tests
