### ISSUE TITLE
GCC 12 validation

### ISSUE THREAD

**Issue by smuzaffar** [cms-sw/cmssw#42842]
Hi,
  Though I do not see any GCC12 campaign under https://cms-pdmv-prod.web.cern.ch/valdb/ but the [RelMon results for gcc12 vs gcc11 in 13.3.0.pre2](https://cms-pdmv-prod.web.cern.ch/relmon/?q=gcc12 ) look good to me. GCC12 vs GCC11 RelMon has higher success rate as compare to GCC11 vs GCC10 (https://cms-pdmv-prod.web.cern.ch/valdb/campaigns/search/gcc11 ). I this good enough to make gcc12 default for 13.3.X or should we wait for the Pdmv validation campaign results?

**Comment by makortel** [comment]
assign core

**Comment by makortel** [comment]
I'd generally wait for the validators actually take a look and report. Also, do we want to switch in 13_3_X or in 14_0_X? (I had been thinking latter as the goal)

**Comment by smuzaffar** [comment]
Initial idea was to switch to gcc12 for 13.4.X and ROOT 6.30 in 14.0.X. If 13.3.X is going to become 13.4.X then I think we can move to gcc12 in 13.3.X too

**Comment by smuzaffar** [comment]
+core
