### ISSUE TITLE
Add nanoaod and miniaod PR type label

### ISSUE THREAD

**Issue by simonepigazzini** [cms-sw/cmssw#42854]
We (xpog) would like to add "nanoaod" and "miniaod" labels to flag PRs. It would allow a simpler bookkeeping of changes from one release to another.

Can anyone point us to where request for the appropriate changes to the cms-bot and whatever else needs changes?

Thanks

**Comment by makortel** [comment]
assign core

**Comment by makortel** [comment]
I suppose this is a good-enough place to ask. The actual change goes to somewhere in https://github.com/cms-sw/cms-bot/ . @smuzaffar ?

**Comment by smuzaffar** [comment]
we need to update https://github.com/cms-sw/cms-bot/blob/master/categories.py#L164 to allow these extra labels. These are the labels which one can add to github PRs/issues by adding `type nanoaod` or `type miniaod` comment.
