### ISSUE TITLE
Create repository SimCalorimetry/EcalEBTrigPrimProducers

### ISSUE THREAD

**Issue by smuzaffar** [cms-sw/cmssw#42866]

**Comment by smuzaffar** [comment]
please do not assign any manual categories to this issue. let the bot take care of the assignment

**Comment by smuzaffar** [comment]
@epalencia,@AdrianoDee,@srimanob,@aloeliger , we need to create this data repository for https://github.com/cms-sw/cmssw/pull/42633 . Once you have signed it then bot can create it

**Comment by srimanob** [comment]
+Upgrade

**Comment by epalencia** [comment]
+l1
