### ISSUE TITLE
Reverting the Phase-2 HLT menu to not use `Tasks`

### ISSUE THREAD

**Issue by mmusich** [cms-sw/cmssw#42940]
In https://github.com/cms-sw/cmssw/pull/42934#issuecomment-1745076992 it was suggested to consider reverting the Phase-2 HLT menu to not use `Tasks` to avoid triggering undesired unscheduled execution of `EDProducer`s.
The 14_0_X cycle was agreed to be a reasonable target to achieve this (see https://github.com/cms-sw/cmssw/pull/42934#issuecomment-1745082823).

**Comment by mmusich** [comment]
assign hlt

**Comment by mmusich** [comment]
@rovere @SohamBhattacharya FYI

**Comment by makortel** [comment]
Just to bring up one option (now that I have some brain bandwidth again), following the discussion in https://github.com/cms-sw/cmssw/issues/36938, a `ConditionalTask` was added in the configuration system. It is similar to `Task` that it is an unordered collection of EDProducers, but differs such that the `ConditionalTask` adds the modules in the `ConditionalTask` to the associated `Path` in the proper order based on consumes/produces calls of the modules in the `Path` and in the `ConditionalTask`. Those modules will then behave as if they were part of the scheduled system (well, in a sense they are), i.e. their execution is dictated only by the EDFilters preceding them in the `Path`.

There is one caveat though: the modules in `ConditionalTask` that are not consumed by any other module in the `Path`, or in the `ConditionalTask`s associated with the `Path`, are treated as unscheduled modules (i.e. any other module consuming their data products will cause them to run). Changing the behavior such that those modules would not get run (e.g. by removing them from the job, as is done for any non-consumed unscheduled module already) is in our radar, but we wanted to see first how the `ConditionalTask` gets used in the HLT (especially if it is still needed after moving from "`SwitchProducer` with CUDA+legacy modules" towards "module type resolver with Alpaka modules").

If organizing the modules in `Task`-like way would still be beneficial, maybe it would be worth of trying out `ConditionalTask`?

**Comment by makortel** [comment]
https://github.com/cms-sw/cmssw/pull/43296 implements the printout of ConditionalTask modules that are not consumed by any module in any of the Paths the ConditionalTask (in question) is associated with, as discussed with some of the HLT folks.

**Comment by mmusich** [comment]
IIUC https://github.com/cms-sw/cmssw/pull/44025 starts to implement things in this direction.

**Comment by mmusich** [comment]
https://github.com/cms-sw/cmssw/pull/44604 completes the migration of the phase-2 HLT menu to use sequences.

**Comment by mmusich** [comment]
+hlt
   * done via https://github.com/cms-sw/cmssw/pull/44025 + https://github.com/cms-sw/cmssw/pull/44604
   * tested in IBs wih no (visible) side effects.

**Comment by makortel** [comment]
@cmsbuild, please close
