### ISSUE TITLE
ID DNN score not properly filled for photons

### ISSUE THREAD

**Issue by swagata87** [cms-sw/cmssw#42949]
Photon PF ID DNN score is not accessible via this getter function. 

https://github.com/cms-sw/cmssw/blob/49f9d492487635641d9286ac3f77e0ab7830f90c/DataFormats/EgammaCandidates/interface/Photon.h#L578

The electron ones are working fine:
https://github.com/cms-sw/cmssw/blob/49f9d492487635641d9286ac3f77e0ab7830f90c/DataFormats/EgammaCandidates/interface/GsfElectron.h#L745

This is a simple code to reproduce the issue:
https://swmukher.web.cern.ch/swmukher/exampleDnnScore.py 
If we run it like this:
`python3  exampleDnnScore.py  Any_Recent_MiniAOD.root`
we see that photon DNN score is always `pf DNN =  -1000000000.0`; but the electron one returns meaningful value.

If the photon DNN getter function can be fixed, that would be great.

**Comment by makortel** [comment]
assign reconstruction,xpog

FYI @cms-sw/egamma-pog-l2

**Comment by vlimant** [comment]
can you please put a root file and it's origin somewhere under the same web space ?

**Comment by swagata87** [comment]
```
python3  exampleDnnScore.py /eos/cms/store/relval/CMSSW_13_3_0_pre1/RelValH125GGgluonfusion_14/MINIAODSIM/131X_mcRun3_2023_realistic_v9-v1/2580000/2e98fffe-2d6a-4cad-9713-996c89e6de54.root
```

**Comment by swagata87** [comment]
some more background information, in case useful, 
it seems this is where the dnn score is filled for photons:

https://github.com/cms-sw/cmssw/blob/acc34c73ee9e6c79ba0f9a4f6c0af0a52d96c91a/RecoEgamma/EgammaPhotonProducers/src/GEDPhotonProducer.cc#L1027-L1040
(and i'm not sure what went wrong..)

This DNN ID, which is a part of PF EGamma Filter/ID, was introduced in the beginning of Run3 via this PR: https://github.com/cms-sw/cmssw/pull/35403

**Comment by swagata87** [comment]
its enabled via era, as it is meant to work only for run 3.

https://github.com/cms-sw/cmssw/blob/aca7593194f3f57ea0b3ac0c82100d11b098d708/RecoEgamma/EgammaPhotonProducers/python/gedPhotonSequence_cff.py#L58-L62

**Comment by swagata87** [comment]
ok found the bug,
will make a PR soon

```diff
diff --git a/DataFormats/EgammaCandidates/src/Photon.cc b/DataFormats/EgammaCandidates/src/Photon.cc
index cf060b60c4e..6129609edcb 100644
--- a/DataFormats/EgammaCandidates/src/Photon.cc
+++ b/DataFormats/EgammaCandidates/src/Photon.cc
@@ -24,6 +24,7 @@ Photon::Photon(const Photon& rhs)
       eCorrections_(rhs.eCorrections_),
       mipVariableBlock_(rhs.mipVariableBlock_),
       pfIsolation_(rhs.pfIsolation_),
+      pfID_(rhs.pfID_),
       haloTaggerMVAVal_(rhs.haloTaggerMVAVal_) {}

```
with this, photon DNN is filled fine. Checked with `12434.0_TTbar_14TeV+2023`

**Comment by vlimant** [comment]
please close
