### ISSUE TITLE
CMSSW tests fails with Fatal Root Error: @SUB=Minuit2

### ISSUE THREAD

**Issue by smuzaffar** [cms-sw/cmssw#42979]
We updated ROOT master commit for CMSSW ROOT6 IBs to [744dcdea97](https://github.com/root-project/root/commit/744dcdea97) but it caused many tests in cmssw to fail with error [a]. Tests with ROOT commit [5df0ef8bfa](https://github.com/root-project/root/commit/5df0ef8bfa) worked fine. The ROOT change set in question is https://github.com/root-project/root/compare/5df0ef8bfa...744dcdea97 . I see there are some changes in root's `Minuit2` code (e.g [Minuit2 is now the default minimizer](https://github.com/root-project/root/pull/13661) ). Is it something we need to update in cmssw to accommodate new root `Minuit2` changes?

[a]
```
----- Begin Fatal Exception 11-Oct-2023 00:42:39 CEST-----------------------
An exception of category 'FatalRootError' occurred while
   [0] Processing global end Run run: 1
   [1] Calling method for module DQMGenericClient/'postProcessorTrack'
   Additional Info:
      [a] Fatal Root Error: @SUB=Minuit2
VariableMetricBuilder Initial matrix not pos.def.

----- End Fatal Exception -------------------------------------------------
```

**Comment by smuzaffar** [comment]
FYI @guitargeek

**Comment by smuzaffar** [comment]
Do we need a fix like https://github.com/cms-sw/cmssw/pull/38687 ( https://github.com/cms-sw/cmssw/blob/master/DQM/BeamMonitor/plugins/Vx3DHLTAnalyzer.cc#L423-L432 ) to add a protection for `Minuit2 Fatal Root Error`?

**Comment by smuzaffar** [comment]
assign dqm

**Comment by smuzaffar** [comment]
@guitargeek , you can reproduce it using following on lxplus8
```
> ssh lxplus8
> cd /tmp/$(whoami)
> /cvmfs/cms.cern.ch/common/scram p CMSSW_13_3_ROOT6_X_2023-10-10-2300
> cd CMSSW_13_3_ROOT6_X_2023-10-10-2300
> eval `/cvmfs/cms.cern.ch/common/scram run -sh`
> cmsRun ~/public/root6/36.0/step4_HARVESTING.py
```

**Comment by guitargeek** [comment]
Hi @smuzaffar, thanks for this, I can reproduce it!

But I'm still at a loss of what actually happens. Is it possible to make cmsRun rethrow the exception to I can actually get a stacktrace?

**Comment by guitargeek** [comment]
I tried this in the process options:
```Python
Rethrow = cms.untracked.vstring("ProductNotFound", "FatalRootError"),
```
But it didn't change the behavior. CMSSW is just carrying on after the fatal exception.

**Comment by makortel** [comment]
What do you mean with "rethrow"? When the framework catches an exception, it works to shut down. Do you mean rethrowing the exception toe caught by the C++ runtime? We don't have facility to do that.

In order to get a stack trace of the exception, you could run `cmsTraceExceptions cmsRun .../step4_HARVESTING.py` (which is just a wrapper for `gdb`).

**Comment by guitargeek** [comment]
Perfect! Thanks, yes that was exactly what I needed

**Comment by guitargeek** [comment]
I could extract the relevant histogram and opened an upstream issue. We'll work on this with high priority.

**Comment by smuzaffar** [comment]
https://github.com/cms-sw/cmssw/pull/43106 fixes the issue by using `likelihood` fit instead of `chi-square` but this change does show many [differences in dqm/reco comparison](https://github.com/cms-sw/cmssw/pull/43106#issuecomment-1779902053)
