### ISSUE TITLE
Unit test of `hltPrintMenuVersions` fails in AArch64 and PowerPC IBs

### ISSUE THREAD

**Issue by missirol** [cms-sw/cmssw#42975]
As reported in https://github.com/cms-sw/cmssw/pull/42967#issuecomment-1755516365, one of the unit tests introduced in #42967 fails in AArch64 and PowerPC IBs.

The error seems related to the use of the python module `cx_Oracle`. The following simplified example reproduces a similar error on `lxplus-arm` with `CMSSW_13_3_X_2023-10-09-2300` and `SCRAM_ARCH=el8_aarch64_gcc11`.

```bash
> python3 
Python 3.9.14 (main, Jun 21 2023, 11:40:31) 
[GCC 11.4.1 20230601] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import cx_Oracle
>>> cx_Oracle.version
'8.3.0'
>>> cx_Oracle.init_oracle_client()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
cx_Oracle.DatabaseError: DPI-1072: the Oracle Client library version is unsupported

```

**Comment by mmusich** [comment]
just for the record:

```diff
diff --git a/HLTrigger/Configuration/test/test_hltPrintMenuVersions.sh b/HLTrigger/Configuration/test/test_hltPrintMenuVersions.sh
index c87d59a5d66..ac49dc004f9 100755
--- a/HLTrigger/Configuration/test/test_hltPrintMenuVersions.sh
+++ b/HLTrigger/Configuration/test/test_hltPrintMenuVersions.sh
@@ -11,6 +11,12 @@ function die {
   exit $2
 }
 
+arch=`uname -m`
+if [[ ${arch} == aarch64 || ${arch} == ppc64le ]] ; then
+    echo "hltPrintMenuVersions unit test not supported for ${arch}"
+    exit 0
+fi
+
 # run test job
 test_hltPrintMenuVersions_1="hltPrintMenuVersions /dev/CMSSW_13_0_0/Fake2"
 

```

it's a possible implementation of the proposal at https://github.com/cms-sw/cmssw/pull/42967#issuecomment-1755554791 .
Of course if there's a better way to support `cx_Oracle` in these builds...

**Comment by makortel** [comment]
We might prefer a `BuildFile.xml`-based solution along
```xml
<ifarchitecture name="!_amd64_">
  <!-- test script hltPrintMenuVersions -->
  <test name="test_hltPrintMenuVersions" command="test_hltPrintMenuVersions.sh"/>
</ifarchitecture>
```
but I let @smuzaffar to correct me.

**Comment by missirol** [comment]
I followed the suggestion to disable the test in #42976.

Just for my own understanding, what is the root cause of the issue with the `cx_Oracle` module in non-`x86-64` builds ?

**Comment by smuzaffar** [comment]
https://github.com/cms-sw/cmssw/pull/42976 looks good ( and use the right tag to test the architecture). 

As I mentioned during the core sw meeting, we do not have oracle client distributed for non-x86_64 archs (https://github.com/cms-sw/cmsdist/blob/IB/CMSSW_13_3_X/master/cmssw-tool-conf.spec#L159-L172) . Though oracle client is available for aarch64 and ppc64le but the oracle occi library used by cmssw (https://github.com/search?q=repo%3Acms-sw%2Fcmssw+oracleocci+language%3AXML&type=code&l=XML ) for non-x86_64 is still built with old GCC ABI which does not work for us.

**Comment by missirol** [comment]
@smuzaffar , thanks for the clarification (and for checking #42976).

**Comment by missirol** [comment]
assign hlt

Just for bookkeeping purposes.

**Comment by mmusich** [comment]
+hlt 
  * issue is formally addressed at  https://github.com/cms-sw/cmssw/pull/42976 see https://github.com/cms-sw/cmssw/pull/42976#issuecomment-1756212973
  * see https://github.com/cms-sw/cmssw/issues/42975#issuecomment-1756156157 for a more thorough explanation of the incompatibility.
