### ISSUE TITLE
Phase-2 only detector SIM collection in Run-3 workflows 

### ISSUE THREAD

**Issue by srimanob** [cms-sw/cmssw#42986]
As discussed https://github.com/cms-sw/cmssw/pull/42961, the Phase-2 only SIM collections appears in Run-3 workflow. This issue is to follow up in case we would like to implement a switch to turn-off collections, to avoid confusion.

**Comment by srimanob** [comment]
assign simulation,geometry,upgrade

**Comment by antoniovilela** [comment]
Comment by Matti:
https://github.com/cms-sw/cmssw/pull/42982#issuecomment-1758428355

**Comment by bsunanda** [comment]
We also have detectors for simulating test beam scenarios. Maybe a solution to have special sets of qualifiers in the EventContent definition which will accept collections of one type of simulation: legacy, run2, run3, run4, TB, etc rather than accepting all collections from g4SimHits
________________________________

**Comment by civanch** [comment]
For me legacy==run2, would you agree?

**Comment by antoniovilela** [comment]
Thanks Sunanda, Vladimir.

One question is would it be feasible to add a flag in the OscarProducer indicating run1/2/3/4, or as you said legacy, run3 and run4, so you customize what you call by these periods?

**Comment by srimanob** [comment]
Will era or modifier work to identify all cases? I have no clue if testbeam need something special. I assume we don't have specific era/modifier for test beam.

**Comment by makortel** [comment]
Would it be feasible to make the sensitive detector builder classes that inherit from `SensitiveDetectorMakerBase` (that already call the `esConsumes`()/`consumes()`) to call the `produces()` for those data product types the corresponding sensitive detector produces the products? Then the set of data product branches would be correct automatically without any configuration changes.

The framework provides `edm::ProducesCollector` helper class (via `producesCollector()` function) that can be used analogously to `edm::ConsumesCollector` to collect the `produces()` information from helper classes.

**Comment by bsunanda** [comment]
Hi Matti, that may be a good solution. We can try it out.
________________________________

**Comment by civanch** [comment]
+1

**Comment by civanch** [comment]
@srimanob , this is already done and the issue may be closed.

**Comment by srimanob** [comment]
+Upgrade
