### ISSUE TITLE
Remove the use of deprecated std::iterator

### ISSUE THREAD

**Issue by makortel** [cms-sw/cmssw#43009]
The `std::iterator` was deprecated in C++17. A quick `git grep` shows it is being used in

- [x] `CondCore/CondDB/interface/GTProxy.h` done in https://github.com/cms-sw/cmssw/pull/43010
- [x] `CondCore/CondDB/interface/IOVProxy.h` done in https://github.com/cms-sw/cmssw/pull/43010
- [x] `CondCore/CondDB/interface/RunInfoProxy.h` done in https://github.com/cms-sw/cmssw/pull/43010
- [x] `CondCore/CondDB/src/DbCore.h` done in https://github.com/cms-sw/cmssw/pull/43010
- [x] `MagneticField/Interpolation/src/bstream_iterator.h` done (file removed as unused) in https://github.com/cms-sw/cmssw/pull/43044

(plus in 4 headers in `DataFormats/Common`, but those are effectively tracked in https://github.com/cms-sw/cmssw/issues/43002)

For example here https://www.fluentcpp.com/2018/05/08/std-iterator-deprecated/ is some description of the deprecation itself, and instructions what to do instead of using `std::iterator`.

**Comment by makortel** [comment]
assign db, geometry, l1, reconstruction, core

**Comment by aloeliger** [comment]
@makortel 

Looking at the L1 usage, I find this in `L1Trigger/L1TMuonEndCap/src/helper.h`:

https://github.com/cms-sw/cmssw/blob/c88bc2efcfc2fc5f0ea31176f6833388ace2d8b8/L1Trigger/L1TMuonEndCap/src/helper.h#L148-L153

And

https://github.com/cms-sw/cmssw/blob/c88bc2efcfc2fc5f0ea31176f6833388ace2d8b8/L1Trigger/L1TMuonEndCap/src/helper.h#L201-L206

Which are the only mentions of `std::iterator(_traits)` in this code.

It is my understanding that `std::iterator_traits` remains un-deprecated. Could you comment then on whether any changes are actually needed from L1 in this case?

**Comment by makortel** [comment]
Thanks @aloeliger, I missed some of those indeed use the `std::iterator_traits` that continues to be non-deprecated. I now cleaned the description to contain only the cases where `std::iterator` itself is used.

**Comment by makortel** [comment]
unassign l1,geometry

**Comment by makortel** [comment]
unassign core

**Comment by francescobrivio** [comment]
+db

 - done in https://github.com/cms-sw/cmssw/pull/43010

**Comment by smuzaffar** [comment]
assign CondCore/CondDB,MagneticField/Interpolation

testing new bot feature to assign issue based on package name

**Comment by smuzaffar** [comment]
unassign DataFormats/Common

**Comment by makortel** [comment]
Fixes have been merged (thanks!)

**Comment by jfernan2** [comment]
+reconstruction
