### ISSUE TITLE
GCC 12  std::iterator deprecated warnings in Relvals/Unittests

### ISSUE THREAD

**Issue by smuzaffar** [cms-sw/cmssw#43002]
With GCC12 , I see warnings [a] in Relvals and unit tests logs. I guess these are generate when root try to parse headers for dictionaries.

[a]
https://cmssdt.cern.ch/SDT/cgi-bin/buildlogs/raw/el8_amd64_gcc12/CMSSW_13_3_X_2023-10-11-2300/unitTestLogs/Alignment/CommonAlignmentMonitor
https://cmssdt.cern.ch/SDT/cgi-bin/logreader/el8_amd64_gcc12/CMSSW_13_3_X_2023-10-11-2300/pyRelValMatrixLogs/run/4.22_RunCosmics2011A/step2_RunCosmics2011A.log#/

```
12-Oct-2023 03:38:36 CEST  Initiating request to open file root://eoscms.cern.ch//eos/cms/store/user/cmsbuild/store/relval/CMSSW_12_5_0_pre5/RelValTTbar_14TeV/GEN-SIM-RECO/PU_125X_mcRun3_2022_realistic_v3-v1/10000/0136c33f-3ff9-4602-8578-906ae6e0160b.root
12-Oct-2023 03:38:44 CEST  Successfully opened file root://eoscms.cern.ch//eos/cms/store/user/cmsbuild/store/relval/CMSSW_12_5_0_pre5/RelValTTbar_14TeV/GEN-SIM-RECO/PU_125X_mcRun3_2022_realistic_v3-v1/10000/0136c33f-3ff9-4602-8578-906ae6e0160b.root
In file included from DataFormatsBTauReco_xr dictionary payload:71:
In file included from /data/cmsbld/jenkins/workspace/ib-run-qa/CMSSW_13_3_X_2023-10-11-2300/src/DataFormats/Common/interface/AssociationMap.h:34:
In file included from /data/cmsbld/jenkins/workspace/ib-run-qa/CMSSW_13_3_X_2023-10-11-2300/src/DataFormats/Common/interface/RefVector.h:18:
/data/cmsbld/jenkins/workspace/ib-run-qa/CMSSW_13_3_X_2023-10-11-2300/src/DataFormats/Common/interface/RefVectorIterator.h:20:41: warning: 'iterator<std::random_access_iterator_tag, edm::Ref<std::vector<reco::PFRecTrack, std::allocator<reco::PFRecTrack> >, reco::PFRecTrack, edm::refhelper::FindUsingAdvance<std::vector<reco::PFRecTrack, std::allocator<reco::PFRecTrack> >, reco::PFRecTrack> >, long, edm::Ref<std::vector<reco::PFRecTrack, std::allocator<reco::PFRecTrack> >, reco::PFRecTrack, edm::refhelper::FindUsingAdvance<std::vector<reco::PFRecTrack, std::allocator<reco::PFRecTrack> >, reco::PFRecTrack> > *, edm::Ref<std::vector<reco::PFRecTrack, std::allocator<reco::PFRecTrack> >, reco::PFRecTrack, edm::refhelper::FindUsingAdvance<std::vector<reco::PFRecTrack, std::allocator<reco::PFRecTrack> >, reco::PFRecTrack> > &>' is deprecated [-Wdeprecated-declarations]
  class RefVectorIterator : public std::iterator<std::random_access_iterator_tag, Ref<C, T, F> > {
                                        ^
/data/cmsbld/jenkins/workspace/ib-run-qa/CMSSW_13_3_X_2023-10-11-2300/src/DataFormats/ParticleFlowReco/interface/PFNuclearInteraction.h:35:25: note: in instantiation of template class 'edm::RefVectorIterator<std::vector<reco::PFRecTrack, std::allocator<reco::PFRecTrack> >, reco::PFRecTrack, edm::refhelper::FindUsingAdvance<std::vector<reco::PFRecTrack, std::allocator<reco::PFRecTrack> >, reco::PFRecTrack> >' requested here
    pfTrackref_iterator secPFRecTracks_begin() const { return pfSecTracks_.begin(); }
                        ^
/cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02806/el8_amd64_gcc12/external/gcc/12.3.1-40d504be6370b5a30e3947a6e575ca28/bin/../lib/gcc/x86_64-redhat-linux-gnu/12.3.1/../../../../include/c++/12.3.1/bits/stl_iterator_base_types.h:127:12: note: 'iterator<std::random_access_iterator_tag, edm::Ref<std::vector<reco::PFRecTrack, std::allocator<reco::PFRecTrack> >, reco::PFRecTrack, edm::refhelper::FindUsingAdvance<std::vector<reco::PFRecTrack, std::allocator<reco::PFRecTrack> >, reco::PFRecTrack> >, long, edm::Ref<std::vector<reco::PFRecTrack, std::allocator<reco::PFRecTrack> >, reco::PFRecTrack, edm::refhelper::FindUsingAdvance<std::vector<reco::PFRecTrack, std::allocator<reco::PFRecTrack> >, reco::PFRecTrack> > *, edm::Ref<std::vector<reco::PFRecTrack, std::allocator<reco::PFRecTrack> >, reco::PFRecTrack, edm::refhelper::FindUsingAdvance<std::vector<reco::PFRecTrack, std::allocator<reco::PFRecTrack> >, reco::PFRecTrack> > &>' has been explicitly marked deprecated here
    struct _GLIBCXX17_DEPRECATED iterator
           ^
/cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02806/el8_amd64_gcc12/external/gcc/12.3.1-40d504be6370b5a30e3947a6e575ca28/bin/../lib/gcc/x86_64-redhat-linux-gnu/12.3.1/../../../../include/c++/12.3.1/x86_64-redhat-linux-gnu/bits/c++config.h:119:34: note: expanded from macro '_GLIBCXX17_DEPRECATED'
# define _GLIBCXX17_DEPRECATED [[__deprecated__]]
```

**Comment by smuzaffar** [comment]
assign core

**Comment by smuzaffar** [comment]
@vgvassilev , do you have any idea why we get this warning? do we need to pass any extra cpp flags to rootcling e.g. `-std=c++17` ?

**Comment by vgvassilev** [comment]
`std::iterator` is deprecated. We should fix `RefVectorIterator` to not inherit from `std::iterator`.

**Comment by makortel** [comment]
With @Dr15Jones we were wondering why these deprecation warnings are shown only from ROOT header parsing, and not as part of our builds. I'd guess the deprecation warnings get ignored by
https://github.com/cms-sw/cmsdist/blob/286418d0faf4848c8e9f7338a33e5547e9652843/scram-tools.file/tools/gcc/gcc-cxxcompiler.xml#L14
Maybe it would make sense to enable the deprecation warnings at least in select IBs so that we would see them earlier?

**Comment by makortel** [comment]
I opened another issue https://github.com/cms-sw/cmssw/issues/43009 about the uses of `std::iterator` outside of `DataFormats/Common`.

**Comment by smuzaffar** [comment]
> With @Dr15Jones we were wondering why these deprecation warnings are shown only from ROOT header parsing, and not as part of our builds. I'd guess the deprecation warnings get ignored by https://github.com/cms-sw/cmsdist/blob/286418d0faf4848c8e9f7338a33e5547e9652843/scram-tools.file/tools/gcc/gcc-cxxcompiler.xml#L14 Maybe it would make sense to enable the deprecation warnings at least in select IBs so that we would see them earlier?

@makortel , yes for normal build the warning was not shown due to `-Wno-deprecated` flag in `gcc-cxxcompiler.xml`. We can drop it for DEVEL IBs

**Comment by makortel** [comment]
I would fix the warnings (on a very and limited look they seem to be indication of "violations" of rule of five, and addressing those would make the code also more clear).

**Comment by smuzaffar** [comment]
+core

https://github.com/cms-sw/cmssw/pull/43029 has been merged and Relval/Unittests logs[a] are now clean ( no more `deprecated` warnings message).

[a]
https://cmssdt.cern.ch/SDT/cgi-bin/logreader/el8_amd64_gcc12/CMSSW_13_3_X_2023-10-19-2300/pyRelValMatrixLogs/run/4.22_RunCosmics2011A/step2_RunCosmics2011A.log#/

**Comment by makortel** [comment]
@cmsbuild, please close
