### ISSUE TITLE
Exception of category `CSCTriggerNumbering::InvalidInput` in unit test `testCSCTriggerMapping`

### ISSUE THREAD

**Issue by aandvalenzuela** [cms-sw/cmssw#43031]
Hello,

Unit test `testCSCTriggerMapping` (module `CondFormats/CSCObjects`) is failing in LTO since [CMSSW_13_3_NONLTO_X_2023-10-12-1100](https://cmssdt.cern.ch/SDT/cgi-bin/showBuildLogs.py/el8_amd64_gcc12/www/thu/13.3.NONLTO-thu-11/CMSSW_13_3_NONLTO_X_2023-10-12-1100?utests) with an exception of category `CSCTriggerNumbering::InvalidInput`:
```
===== Test "testCSCTriggerMapping" ====
Running .testCSCTriggerMapping: --- t e s t C S C T r i g g e r M a p p i n g  ---
start --------------------------------------------------------------------------------------------------------
CSCTriggerMappingFromFile: opened file containing mapping, /data/cmsbld/jenkins/workspace/ib-run-qa/CMSSW_13_3_NONLTO_X_2023-10-16-2300/src/CondFormats/CSCObjects/test/csc_trigger_test_map.txt
E

##Failure Location unknown## : Error
Test name: testCSCTriggerMapping::testRead
uncaught exception of type std::exception (or derived).
- An exception of category 'CSCTriggerNumbering::InvalidInput' occurred.
Exception Message:
CSCTriggerNumbering::ringFromTriggerLabels(): Station: 3 TriggerCSCID: 0 is not
 a valid set of labels. Cannot Convert!!


Failures !!!
Run: 1   Failure total: 1   Failures: 0   Errors: 1

---> test testCSCTriggerMapping had ERRORS
```

Yesterday it also failed in DEFAULT IBs for `el8_ppc64le_gcc12` ([CMSSW_13_3_X_2023-10-15-2300](https://cmssdt.cern.ch/SDT/cgi-bin/logreader/el8_ppc64le_gcc12/CMSSW_13_3_X_2023-10-15-2300/unitTestLogs/CondFormats/CSCObjects#/)).

I can reproduce it locally.

Thanks,
Andrea

**Comment by makortel** [comment]
assign alca, db

FYI @cms-sw/csc-dpg-l2

**Comment by iarspider** [comment]
Failed again in [CMSSW_13_3_NONLTO_X_2023-10-18-1100](https://cmssdt.cern.ch/SDT/cgi-bin/logreader/el8_amd64_gcc12/CMSSW_13_3_NONLTO_X_2023-10-18-1100/unitTestLogs/CondFormats/CSCObjects#/2519-2519)

**Comment by ptcox** [comment]
I have no idea what is going on but it seems to relate to accessing an input file from either 'data' (works) or 'test' (fails).
I just did a quick test on lxplus in 13_2_6 and of course everything works, just as everything always has. So what has changed in these integration builds?

In the above logs, 
testCSCMapping works - accesses input file from
/data/cmsbld/jenkins/workspace/ib-run-qa/CMSSW_13_3_NONLTO_X_2023-10-19-2300/src/CondFormats/CSCObjects/data/csc_slice_test_map.txt

testCSCTriggerMapping fails - attempts to access input file from
/data/cmsbld/jenkins/workspace/ib-run-qa/CMSSW_13_3_NONLTO_X_2023-10-19-2300/src/CondFormats/CSCObjects/test/csc_trigger_test_map.txt

and fails. So why has this stopped working?

**Comment by aandvalenzuela** [comment]
Hello @ptcox,

It seems it fails due to this condition here:
https://github.com/cms-sw/cmssw/blob/bca672bc5e1a954fbd1aaa8ffdabafb64a51463a/DataFormats/MuonDetId/src/CSCTriggerNumbering.cc#L5-L11

that throws the exception of type `CSCTriggerNumbering::InvalidInput`.

I have checked and the file is there (and it has not been modified recently https://github.com/cms-sw/cmssw/blob/master/CondFormats/CSCObjects/test/csc_trigger_test_map.txt).

In `13_3`, the test that access data in `/data/csc_slice_test_map.txt` also works (unit test `testCSCMapping`), but the one on `/test/csc_trigger_test_map.txt` doesn't (unit tests `testCSCTriggerMapping`). I see you tried `13_2_6`, does it also work for you in any `13_3_X`?

**Comment by rsreds** [comment]
If I'm not mistaken the two tests access the files differently.
testCSCMapping uses edm::FileInPath to get the path
https://github.com/cms-sw/cmssw/blob/bca672bc5e1a954fbd1aaa8ffdabafb64a51463a/CondFormats/CSCObjects/test/testCSCMapping.cpp#L57-L64

while testCSCTriggerMapping does it manually with:
https://github.com/cms-sw/cmssw/blob/bca672bc5e1a954fbd1aaa8ffdabafb64a51463a/CondFormats/CSCObjects/test/testCSCTriggerMapping.cpp#L16-L17
https://github.com/cms-sw/cmssw/blob/bca672bc5e1a954fbd1aaa8ffdabafb64a51463a/CondFormats/CSCObjects/test/testCSCTriggerMapping.cpp#L52-L54

It's maybe worth it to look into that.

**Comment by aandvalenzuela** [comment]
Hello, this issue is still present in the new release cycle [CMSSW_14_0_NONLTO_X_2023-11-13-2300](https://cmssdt.cern.ch/SDT/cgi-bin/logreader/el8_amd64_gcc12/CMSSW_14_0_NONLTO_X_2023-11-13-2300/unitTestLogs/CondFormats/CSCObjects#/)

**Comment by smuzaffar** [comment]
https://github.com/cms-sw/cmssw/pull/43269 should fix this issue.
