### ISSUE TITLE
Does DQMStore need to see begin/endLumi transitions for each stream?

### ISSUE THREAD

**Issue by makortel** [cms-sw/cmssw#43105]
Currently framework guarantees that each stream sees the beginLumi and endLumi transitions for each Lumi, and all streams see the Lumis in the same order. In order to address https://github.com/cms-sw/cmssw/issues/42931 (issue 2 there) we are considering to change framework's behavior a bit, namely to allow some streams to not see a Lumi at all (in case that Lumi would not have any Events to process anymore when the stream would be to start beginLumi transition). (This possible new behavior is actually already shown in the description of the framework transitions in
https://twiki.cern.ch/twiki/bin/view/CMSPublic/FWMultithreadedFrameworkTransitions#Transitions
)

Our question to DQM is if DQMStore currently needs to see the beginLumi and endLumi transitions for each stream, or would it be fine for DQMStore if it would look like some streams would not process some Lumis at all?

**Comment by makortel** [comment]
assign core,dqm

**Comment by makortel** [comment]
@cms-sw/dqm-l2 Any thoughts?

**Comment by jfernan2** [comment]
Hi, despite I am not in DQM since some years ago, I may give some light on this.
I believe DQMStore itself CANNOT handle not seeing begin/endLumi transitions, this constructor here:

https://github.com/cms-sw/cmssw/blob/7d99d3006f443078e47ff140f5ee7d4962298135/DQMServices/Core/src/DQMStore.cc#L778-L820

was needed for all DQM module types: it handles creating and deleting global MEs as needed, which has to happen even if a module does not see lumi transitions, so not just for DQMOneLumiEDAnalyzer which is a must when begin/end lumi transitions are needed, blocking concurrent lumisections.

I guess that if the lumi does not conatin any event, some MEs may work but others which take into account LSs would lose the accounting of that LS

HTH

**Comment by makortel** [comment]
Thanks @jfernan2. Under the proposal, the DQMStore would continue to see the **global** begin/endLumi transitions (for which the callbacks are registered in the DQMStore constructor).

The question is more about if (taking the `DQMEDAnalyzer` that is an `edm::stream` module as an example) omitting the **stream** begin/endLumi calls
https://github.com/cms-sw/cmssw/blob/7d99d3006f443078e47ff140f5ee7d4962298135/DQMServices/Core/interface/DQMEDAnalyzer.h#L95-L98
https://github.com/cms-sw/cmssw/blob/7d99d3006f443078e47ff140f5ee7d4962298135/DQMServices/Core/interface/DQMEDAnalyzer.h#L102-L104

for some stream instance(s) of the module, while the other stream instance(s) of the module would continue to see the begin/endLumi calls, would cause problems for DQMStore bookkeeping?

**Comment by jfernan2** [comment]
It is difficult for me to give a general veredict as I tried to explain in my previous answer: my understanding is that DQMStore itself may not complain (it will think it is in the present LS), but some DQM modules working with MEs depending on LS may get confused if some LSs are not declared even if they don't contain events

**Comment by makortel** [comment]
I took a deep dive in `DQMEDAnalyzer` and what exactly happens in the `DQMStore` `initLumi()`, `enterLumi()`, and `leaveLumi()` functions. As far as I can tell
* `initLumi()` is about making sure there exists a "global `MonitorElement` object" corresponding to every "local `MonitorElement` object" of that module for that LuminosityBlock
  * The stream instances of a `DQMEDAnalyzer` should have the same "local `MonitorElement` objects (from the `bookHistograms()` that is called at `beginRun` transition), right?
  * Assuming "yes", it is sufficient that one stream calls `initLumi()` (before any stream calls `enterLumi()`)
* `enterLumi()` is about making the "local `MonitorElement`" to share the `MonitorElementData` held by the corresponding "global `MonitorElement`"
* `leaveLumi()` is about releasing the shared ownership of the `MonitorElementData` from the "local `MonitorElement`"

If I understood the code correctly, `DQMEDAnalyzer` + `DQMStore` would be fine if some streams would skip a LuminosityBlock in case all Events of the LuminosityBlock have been processed already by other streams, as long as at least one stream will process the LuminosityBlock and its Events (or just the LuminosityBlock if it has no Events).

**Comment by makortel** [comment]
+core

**Comment by makortel** [comment]
@cms-sw/dqm-l2 I'm going to close this issue, but if you find anything wrong in my assessment https://github.com/cms-sw/cmssw/issues/43105#issuecomment-1861317614, please let us know as soon as possible.
