### ISSUE TITLE
CPP20: cudafe++ killed with signal 9

### ISSUE THREAD

**Issue by iarspider** [cms-sw/cmssw#43117]
We observe compilation failures of HeterogeneousX packages in CPP20 IBs:

* [HeterogeneousCore/AlpakaInterface](https://cmssdt.cern.ch/SDT/cgi-bin/buildlogs/el8_amd64_gcc12/CMSSW_13_3_CPP20_X_2023-10-20-1100/HeterogeneousCore/AlpakaInterface)
* [HeterogeneousTest/CUDADevice](https://cmssdt.cern.ch/SDT/cgi-bin/buildlogs/el8_amd64_gcc12/CMSSW_13_3_CPP20_X_2023-10-20-1100/HeterogeneousTest/CUDADevice)
* [HeterogeneousTest/CUDAKernel](https://cmssdt.cern.ch/SDT/cgi-bin/buildlogs/el8_amd64_gcc12/CMSSW_13_3_CPP20_X_2023-10-20-1100/HeterogeneousTest/CUDAKernel)

All three failures are due to `nvcc error   : 'cudafe++' died due to signal 9 (Kill signal)`.

**Comment by iarspider** [comment]
assign heterogeneous

**Comment by dan131riley** [comment]
Signal 9 likely means the system ran out of virtual memory and killed nvcc as the primary memory hog--so look at memory usage for those compilation steps?

**Comment by fwyzard** [comment]
@iarspider can you confirm if these issues are fixed in the latest 12.4 CUDA release ?

**Comment by iarspider** [comment]
> @iarspider can you confirm if these issues are fixed in the latest 12.4 CUDA release ?

Yes. Thanks, @fwyzard !

**Comment by fwyzard** [comment]
+heterogeneous
