### ISSUE TITLE
EnableIMT for flat nano production

### ISSUE THREAD

**Issue by kpedro88** [cms-sw/cmssw#43123]
Currently, the following setting is included in [Configuration/DataProcessing/python/Merge.py](https://github.com/cms-sw/cmssw/blob/master/Configuration/DataProcessing/python/Merge.py) and recommended to users producing flat nanoAOD files (i.e. `--eventcontent NANOAODSIM` rather than `NANOEDMAODSIM`):
```python
process.add_(Service("InitRootHandlers", EnableIMT = CfgTypes.untracked.bool(False)))
```

The stated reason is "to avoid segfault errors in the output module when producing flat ntuples".

This may now be unnecessary after #34030. It should be checked whether the segfault still occurs.

If this setting is still necessary, it should be added to `cmsDriver.py` as an automatic setting whenever `--eventcontent NANOAODSIM`, to simplify instructions and reduce the chance of mistakes.

**Comment by makortel** [comment]
assign xpog

**Comment by dan131riley** [comment]
If this setting is still necessary, we'd like to understand why and fix it.  IMT should be a significant efficiency improvement for NANO production.

**Comment by ram1123** [comment]
A piece of information:

Last week, I generated private nanoAOD (v9). I did not add the line:

```python
process.add_(Service("InitRootHandlers", EnableIMT = CfgTypes.untracked.bool(False)))
```

Once I got the output files, I used `haddnano` as well as my nanoAOD skimmer. And I don't see any seg fault.

**Comment by vlimant** [comment]
+1

**Comment by makortel** [comment]
@cmsbuild, please close
