### ISSUE TITLE
[DBG_X] DTMuonMillepede: array subscript ... is outside outside array bounds 

### ISSUE THREAD

**Issue by iarspider** [cms-sw/cmssw#43135]
In the recent [DBG_X IB](https://cmssdt.cern.ch/SDT/cgi-bin/buildlogs/el8_amd64_gcc12/CMSSW_13_3_DBG_X_2023-10-26-2300/Alignment/MuonAlignmentAlgorithms), the compiler emits warnings about accessing array elements outside it's bounds:
```
.../src/Alignment/MuonAlignmentAlgorithms/src/DTMuonMillepede.cc: In member function 'getCqcMatrix':
  .../src/Alignment/MuonAlignmentAlgorithms/src/DTMuonMillepede.cc:582:44: warning: array subscript 5 is outside array bounds of 'void[40]' [-Warray-bounds]
   582 |             Eta[counterLayer][counterLayer2] = -1.0 / (4.0);
      |                                            ^
.../src/Alignment/MuonAlignmentAlgorithms/src/DTMuonMillepede.cc:574:39: note: at offset 40 into object of size 40 allocated by 'operator new []'
  574 |       Eta[counterLayer] = new double[5];
      |                                       ^
  .../src/Alignment/MuonAlignmentAlgorithms/src/DTMuonMillepede.cc:582:44: warning: array subscript 5 is outside array bounds of 'void[40]' [-Warray-bounds]
   582 |             Eta[counterLayer][counterLayer2] = -1.0 / (4.0);
      |                                            ^
.../src/Alignment/MuonAlignmentAlgorithms/src/DTMuonMillepede.cc:574:39: note: at offset 40 into object of size 40 allocated by 'operator new []'
  574 |       Eta[counterLayer] = new double[5];
      |                                       ^
  .../src/Alignment/MuonAlignmentAlgorithms/src/DTMuonMillepede.cc:582:44: warning: array subscript 6 is outside array bounds of 'void[40]' [-Warray-bounds]
   582 |             Eta[counterLayer][counterLayer2] = -1.0 / (4.0);
      |                                            ^
.../src/Alignment/MuonAlignmentAlgorithms/src/DTMuonMillepede.cc:574:39: note: at offset 48 into object of size 40 allocated by 'operator new []'
  574 |       Eta[counterLayer] = new double[5];
      |                                       ^
  .../src/Alignment/MuonAlignmentAlgorithms/src/DTMuonMillepede.cc:580:44: warning: array subscript 5 is outside array bounds of 'void[40]' [-Warray-bounds]
   580 |             Eta[counterLayer][counterLayer2] = 3.0 / (4.0);
      |                                            ^
.../src/Alignment/MuonAlignmentAlgorithms/src/DTMuonMillepede.cc:574:39: note: at offset 40 into object of size 40 allocated by 'operator new []'
  574 |       Eta[counterLayer] = new double[5];
      |                                       ^
  .../src/Alignment/MuonAlignmentAlgorithms/src/DTMuonMillepede.cc:582:44: warning: array subscript 6 is outside array bounds of 'void[40]' [-Warray-bounds]
   582 |             Eta[counterLayer][counterLayer2] = -1.0 / (4.0);
      |                                            ^
.../src/Alignment/MuonAlignmentAlgorithms/src/DTMuonMillepede.cc:574:39: note: at offset 48 into object of size 40 allocated by 'operator new []'
  574 |       Eta[counterLayer] = new double[5];
      |                                       ^
(... etc ...)
```
(54 warnings total)

I think these warnings are valid: the `Eta` array is defined as `double[12][5]`:
https://github.com/cms-sw/cmssw/blob/a05e5a462c054b985d6bd9e9d85b02e725f3ee1e/Alignment/MuonAlignmentAlgorithms/src/DTMuonMillepede.cc#L570

https://github.com/cms-sw/cmssw/blob/a05e5a462c054b985d6bd9e9d85b02e725f3ee1e/Alignment/MuonAlignmentAlgorithms/src/DTMuonMillepede.cc#L574

however the `counterLayer2` index goes from 0 to 11 - https://github.com/cms-sw/cmssw/blob/a05e5a462c054b985d6bd9e9d85b02e725f3ee1e/Alignment/MuonAlignmentAlgorithms/src/DTMuonMillepede.cc#L575

So we should either change Eta to be 11x11, or change the `counterLayer2` loop.

**Comment by iarspider** [comment]
assign Alignment/MuonAlignmentAlgorithms

**Comment by rsreds** [comment]
By changing
https://github.com/cms-sw/cmssw/blob/a05e5a462c054b985d6bd9e9d85b02e725f3ee1e/Alignment/MuonAlignmentAlgorithms/src/DTMuonMillepede.cc#L574-L575
https://github.com/cms-sw/cmssw/blob/a05e5a462c054b985d6bd9e9d85b02e725f3ee1e/Alignment/MuonAlignmentAlgorithms/src/DTMuonMillepede.cc#L675-L676
either with
```c++
Eta[counterLayer] = new double[12];
```
or
```c++
`for (int counterLayer2 = 0; counterLayer2 < 5; counterLayer2++) {`
```
the warning will be gone (tested on CMSSW_13_3_DBG_X_2023-10-26-2300).

I would also suggest to improve the code to follow the [guidelines](https://cms-sw.github.io/cms_coding_rules.html#7--design-and-coding-guidelines-1). In particular:
Do not use magic numbers.
Avoid use of C-style arrays in favour of STL containers.

I can work a quick PR if I get some input on which one of the two solution is preferred.

**Comment by perrotta** [comment]
By looking at the other lines in the code, the correct solution among those proposed in https://github.com/cms-sw/cmssw/issues/43135#issuecomment-1792681873 should be
```C++
      Eta[counterLayer] = new double[12];
```

Given this bug, however, I wonder whether this code was ever used in cmssw. Perhaps, instead of uselessly maintaining some dead code it could be prefarable to clean it up once for all.

**Comment by battibass** [comment]
Hi @perrotta,
formally, muon alignment is not a DT DPG responsibility.

I add in copy @hyunyong (responsible for software-based muon alignment within the Muon DPGO) and @bnoemi (working, among other things, on hardware alignment).

Of course the fix is trivial and DT DPG could take care of it if no one replies, but we don't know whether the code is (or could be) useful and should be preserved.

**Comment by battibass** [comment]
@hyunyong, no objections from me, you are the expert!
You may briefly ask Teruki in case he recalls something from earlier than the last 4 years.
