### ISSUE TITLE
Allow manual override to PR test results

### ISSUE THREAD

**Issue by Dr15Jones** [cms-sw/cmssw#43143]
Often the PR test results show a failure that have nothing to do with the pull request and are caused by external factors such as a unit test failing in the IB. Right now, we add comments to the PR stating this is the case and hope the release managers notice the comments and do the merge anyway.

I believe it would be better if we had a manual way to override the test failure label. I'd suggest adding a new command something like `@test-manual-override`, `@test-ib-failure` or `@test-manual-approved` which would replace the `test-rejected` label with a new label based on which command name is chosen. This would then document in the label system what decisions were made.

**Comment by Dr15Jones** [comment]
assign core

**Comment by smuzaffar** [comment]
sounds good @Dr15Jones . What will be the difference between  `@test-manual-override` and `@test-manual-approved` ?
By the way, I will avoid using `@` for the comment as it is special char to mention a github user/team.

**Comment by Dr15Jones** [comment]
@smuzaffar sorry for being unclear. The different names weren't meant to be for different things, they were just different possible tags we might want to use for this feature. Naming can be hard :).

**Comment by iarspider** [comment]
@Dr15Jones @smuzaffar do we want to allow automatic merging of PRs with overridden tests?

**Comment by smuzaffar** [comment]
No, merging should be done by L1/ORP signatures. override tests should only remove the `test-rejected` label and add the `test-(ib-failure|manual-approved)` label

**Comment by smuzaffar** [comment]
yes for this context, it should be tests-approved . I think replacing `tests-rejected` with `tests-approved` + `test-(ib-failure|manual-approved)` will do the trick.

**Comment by smuzaffar** [comment]
@iarspider , can you please summarize the bot feature implemented via https://github.com/cms-sw/cms-bot/pull/2096

**Comment by iarspider** [comment]
I have added a new command to cmsbuild: `please ignore [with] reason <reason>`, where `<reason>` can be one of the following: 

* `manual-override`: the commenter acknowledges the test failure but claims that it is not related to the PR
* `ib-failure`: the commenter claims that the test failure is not related to the PR, but also happens in IBs
* `external-failure`: the commenter claims that the test failure is not related to the PR, and is caused by external factor

This command can only be used if unit test(s) of relval(s) failed (i.e. the PR has `tests-rejected` label), and replaces the `tests-rejected` label with `tests-approved`, plus adds a `tests-<reason>` label.

**Comment by smuzaffar** [comment]
thanks @iarspider 
I think you meant `[please] ignore [with] <reason>` ? right?

**Comment by iarspider** [comment]
> thanks @iarspider I think you meant `[please] ignore [with] <reason>` ? right?

yes.

**Comment by smuzaffar** [comment]
I would like to see `test` keyword in the comment too :-)
@Dr15Jones , what do you think?

**Comment by iarspider** [comment]
> I would like to see `test` keyword in the comment too :-) @Dr15Jones , what do you think?

E.g. `please ignore [test] [with] <reason>`?

**Comment by iarspider** [comment]
Or `please ignore <test name|relval id> [with] <reason>`?

**Comment by iarspider** [comment]
> I have added a new command to cmsbuild: `please ignore [with] <reason>`, where `<reason>` can be one of the following:
> 
>     * `manual-override`: the commenter acknowledges the test failure but claims that it is not related to the PR
> 
>     * `ib-failure`: the commenter claims that the test failure is not related to the PR, but also happens in IBs
> 
>     * `external-failure`: the commenter claims that the test failure is not related to the PR, and is caused by external factor
> 
> 
> This command can only be used if unit test(s) of relval(s) failed (i.e. the PR has `tests-rejected` label), and replaces the `tests-rejected` label with `tests-approved`, plus adds a `tests-<reason>` label.

@smuzaffar the permissions for this command are the same as for `please test` one.

**Comment by Dr15Jones** [comment]
@smuzaffar  wrote
>I would like to see test keyword in the comment too :-)

I agree, although I think we should use `tests` to be more consistent with he label. So the command I'd rather see is
```
please ignore tests [with] <reason>
```
where `tests` is mandatory as it was the `tests-rejected` that we are trying to override. With that in mind, it might be even better to do

```
please ignore tests-rejected [with] <reason>
```
to be even clearer.

@iarspider write
> Or please ignore <test name|relval id> [with] <reason>?

I'm not a fan of the `<test name|relval id>` as we could easily have multiple ones that are failing (which is more often the case). I think the simpler `please ignore test-rejected` covers more cases and would be easier to use.

**Comment by smuzaffar** [comment]
+core
this is complete now
