### ISSUE TITLE
Add Source::getNextType callbacks to ActivityRegistry

### ISSUE THREAD

**Issue by Dr15Jones** [cms-sw/cmssw#43179]
The only Source calls not seen by the ActivityRegistry are from getNextType.

**Comment by Dr15Jones** [comment]
assign core

**Comment by makortel** [comment]
Done in https://github.com/cms-sw/cmssw/pull/43208

**Comment by makortel** [comment]
+core

**Comment by makortel** [comment]
@cmsbuild, please close
