### ISSUE TITLE
ROOT 6.30 validation

### ISSUE THREAD

**Issue by smuzaffar** [cms-sw/cmssw#43199]
Hi @cms-sw/orp-l2,
 
   Though ROOT 6.30 is not tagged yet but last pending CMS issue should be fixed once we get https://github.com/cms-sw/cmssw/pull/43170 merged. @cms-sw/core-l2 would like to request the validation of ROOT 6.30 as soon as possible. We have following options in mind

- merge #43170 in 13.3.X and build 13_3_0_pre6 and 13_3_0_pre6_ROOT630 releases to start the validation
- merge  #43170 in 14.0.X (soon to be open) and build 14_0_0_pre0 and 14_0_0_pre0_ROOT630 releases

Please let us know how should we proceed with this validation.

**Comment by smuzaffar** [comment]
@cms-sw/orp-l2  please suggest how should we proceed with ROOT 6.30 validation. #43170 (required for ROOT 6.30) is merged in 13.3.X now so we can either go with special 13.3.0.pre6 or 14.0.0.pre0 release for this validation.

**Comment by antoniovilela** [comment]
@smuzaffar @cms-sw/orp-l2 @cms-sw/ppd-l2
Hi Shahzad,
Looks like it would be better to run the validation on 14_0_0_pre0/1 (+ ROOT630), but I let others comment as well.
Thanks.

**Comment by smuzaffar** [comment]
I am fine with this validation in 14.0.0.preX release.

**Comment by antoniovilela** [comment]
All good then.

**Comment by smuzaffar** [comment]
@cms-sw/orp-l2 , as 14.0.x is open now, can you please start the special CMSSW_4_0_0_pre1 and CMSSW_4_0_0_pre1_ROOT630 pre-releases .

**Comment by antoniovilela** [comment]
The 14_0_0_pre0 build is ongoing: https://github.com/cms-sw/cmssw/issues/43224

**Comment by antoniovilela** [comment]
@smuzaffar @cms-sw/orp-l2 
Hi Shahzad, for the ROOT 6.30 build, I can issue "Build CMSSW_14_0_0_pre0_ROOT630" with parameter: "CMSSW_COMMIT: CMSSW_14_0_0_pre0" ?

**Comment by smuzaffar** [comment]
yes @antoniovilela , `CMSSW_COMMIT: CMSSW_14_0_0_pre0` is the correct parameters for this release. I have start the process https://github.com/cms-sw/cmssw/issues/43231

**Comment by smuzaffar** [comment]
CMSSW_4_0_0_pre1_ROOT630 is available now (https://github.com/cms-sw/cmssw/issues/43231) . I will open a ticket for its  validation now

**Comment by smuzaffar** [comment]
Release validation ticket:  https://its.cern.ch/jira/browse/PDMVRELVALS-221

**Comment by smuzaffar** [comment]
For ref: ROOT 6.30 Relval campaign https://cms-pdmv-prod.web.cern.ch/valdb/campaigns/search/root630

**Comment by smuzaffar** [comment]
closing this issue as we have already moved to ROOT 6.30
