### ISSUE TITLE
Unit test `testHeterogeneousCoreAlpakaTestModulesROCm` failing in aarch64 with Assert exception

### ISSUE THREAD

**Issue by aandvalenzuela** [cms-sw/cmssw#43258]
Hello,

Since the merge of https://github.com/cms-sw/cmssw/pull/43204, new unit test `testHeterogeneousCoreAlpakaTestModulesROCm` is failing for `aarch64` with the following exception when running with the `rocm_async` backend:
```
AlpakaServiceSerialSync succesfully initialised.
Found 1 device:
  - <unknown: CPU>
%MSG
Begin processing the 1st record. Run 1, Event 1, LumiSection 1 on stream 0 at 13-Nov-2023 15:10:03.355 CET
----- Begin Fatal Exception 13-Nov-2023 15:10:03 CET-----------------------
An exception of category 'Assert' occurred while
   [0] Processing  Event run: 1 lumi: 1 event: 1 stream: 0
   [1] Running path 'p'
   [2] Calling method for module TestAlpakaAnalyzer/'alpakaStreamInstanceConsumer'
Exception Message:
Expected input collection size 216, got 6
----- End Fatal Exception -------------------------------------------------
Failed cmsRun testAlpakaModules_cfg.py --expectBackend=rocm_async: status 65
```
The assertion happens in https://github.com/cms-sw/cmssw/blob/master/HeterogeneousCore/AlpakaTest/test/testAlpakaModules_cfg.py#L136 when the input collection size does not match the expected one.

I think even when only CPU available the test should either skip (as when rocm is not enabled) or run.
I can reproduce the error locally.
Thanks,

Andrea

FYI, @makortel

**Comment by makortel** [comment]
assign core, heterogeneous

**Comment by makortel** [comment]
The `testHeterogeneousCoreAlpakaTestModulesROCm` is already intended to be set up in a way that it gets run only when AMD GPUs are present
https://github.com/cms-sw/cmssw/blob/92957fee5d01ccef529a274e614af273046da378/HeterogeneousCore/AlpakaTest/test/BuildFile.xml#L12-L15

So why this setup doesn't work on ARM (and Power)?

**Comment by makortel** [comment]
I checked on `lxplus8-arm` and CMSSW_14_0_X_2023-11-12-2300 that `cudaIsEnabled` returns 2, and `rocmIsEnabled` returns 1. I'd expect that to lead to scram to not run the `rocm`-depending tests.

**Comment by makortel** [comment]
Still on `lxplus8-arm`, when running `scram b runtest`, I see
```
****WARNING: Invalid tool rocm. Please fix src/HeterogeneousCore/AlpakaTest/test/BuildFile.xml file.
```
Could this lead to scram not to recognize the special treatment of `rocm`-depending tests?

**Comment by smuzaffar** [comment]
yes it might, I am look in to this

**Comment by fwyzard** [comment]
ROCm is not available for ARM (and Power).

**Comment by smuzaffar** [comment]
scram was only considerfing the valid backends and for aarch64 the valid backends are `cuda serial` that is why it was ignoring `rocm` dep and running the test for aarch64. https://github.com/cms-sw/cmssw-config/pull/97 should fix this issue. with https://github.com/cms-sw/cmssw-config/pull/97 scram considers all selected backend and disable the test if `<backend>IsEnabled` command is either not available or fails

**Comment by smuzaffar** [comment]
+core
https://github.com/cms-sw/cmssw-config/pull/97 fixed the unit tests issue for aarch64/ppc64le. Tests are now properly skipped for these archs

**Comment by fwyzard** [comment]
+heterogeneous
