### ISSUE TITLE
Get rid of caloTowers in PF codebase

### ISSUE THREAD

**Issue by swagata87** [cms-sw/cmssw#43264]
It seems that caloTowers are not well-supported / well-maintained anymore. From recent discussions in a PR, it seems that the HCAL thresholds of caloTower are not updated (https://github.com/cms-sw/cmssw/pull/43025#discussion_r1372998593 , https://github.com/cms-sw/cmssw/pull/43025#discussion_r1373115396 , https://github.com/cms-sw/cmssw/pull/43025#discussion_r1375441309). 

Since HCAL has been asking to move away from caloTowers for a while now, it would be nice if PF reco can get rid of caloTowers. There is probably just one instance in PF code base where caloTower is used. It is in the supercluster importer where a H/E cut is needed. 

See here
https://github.com/cms-sw/cmssw/blob/cb482a702b817ada8aa414bc3379bfa63a02658c/RecoParticleFlow/PFProducer/plugins/importers/SuperClusterImporter.cc#L75-L78

Apart from this, I don't see any other place in PF where caloTowers are used. It would be nice to update this code and make PF independent of caloTowers.

**Comment by swagata87** [comment]
FYI @bellan @laurenhay

**Comment by makortel** [comment]
assign pf, reconstruction

FYI @cms-sw/hcal-dpg-l2

**Comment by swagata87** [comment]
type pf

**Comment by swagata87** [comment]
Done in https://github.com/cms-sw/cmssw/pull/43612 (and follow up https://github.com/cms-sw/cmssw/pull/43681)

**Comment by swagata87** [comment]
+1

**Comment by makortel** [comment]
@cmsbuild, please close
