### ISSUE TITLE
Electron inefficiency in phi=-1 using high beta star modifier

### ISSUE THREAD

**Issue by stahlleiton** [cms-sw/cmssw#43375]
While preparing the re-reco settings for the 2023 PbPb Forward PD, including the high beta star modifier (to access lower pT  tracks), I found a larger inefficiency in the reconstructed electrons localized at azimuth angle phi = -1 between -1.4 < eta < 0.4 when compared to the standard pp reco (--era Run3_2023).

<img width="772" alt="Screenshot 2023-11-23 at 15 28 44" src="https://github.com/cms-sw/cmssw/assets/14130873/731eee5f-05fd-423d-9f66-b47d55ff09c4">

More details are can be found in the [slides](https://docs.google.com/presentation/d/1nK3r-i3EwV0YvkpJQb--lPLivD1NCmBTG-XZr__Xr0o/edit?usp=sharing) (slide 3).

After testing several parameters, I identified the increase in inefficiency to originate from the parameter:
pixelPairStepTrackingRegions.RegionPSet.originRadius
which is set in the high beta star modifier to 0.2  .
Changing the originRadius back to the standard pp reco value of 0.015 improved the efficiency.

I also tested setting useFoundVertices = False, but it did not change the outcome.

The settings I used to test this were:

```
cmsrel CMSSW_13_2_8
cd CMSSW_13_2_8/src
cmsenv

cmsDriver.py Configuration/Generator/python/DoubleElectronPt10Extended_pythia8_cfi.py --customise_commands "process.generator.PGunParameters.MinPhi = -1.2; process.generator.PGunParameters.MaxPhi = -1.0; process.generator.PGunParameters.MinEta = -1.2; process.generator.PGunParameters.MaxEta = -0.8" --mc --nThreads 16 --eventcontent RAWSIM --datatier GEN-SIM --conditions 130X_mcRun3_2023_realistic_HI_v16 --beamspot Realistic2023PbPbCollision --step GEN,SIM --scenario HeavyIons —geometry DB:Extended --era Run3_pp_on_PbPb -n 1000

cmsDriver.py step2 --filein file:DoubleElectronPt10Extended_pythia8_cfi_py_GEN_SIM.root --mc --nThreads 16 --eventcontent RAWSIM --pileup HiMixNoPU --datatier GEN-SIM-DIGI-RAW --conditions 132X_mcRun3_2023_realistic_HI_v5 --step DIGI:pdigi_hi_nogen,L1,DIGI2RAW,HLT:@fake2 --geometry DB:Extended --era Run3_pp_on_PbPb -n -1

# Reco without high beta star
cmsDriver.py  step3  --filein file:step2_DIGI_L1_DIGI2RAW_HLT_PU.root  --mc --nThreads 16 --eventcontent AODSIM --datatier AODSIM --conditions 132X_mcRun3_2023_realistic_HI_v5 --step RAW2DIGI,L1Reco,RECO --era Run3_2023 -n -1

# Reco including high beta star
cmsDriver.py  step3_HBS  --filein file:step2_DIGI_L1_DIGI2RAW_HLT_PU.root  --mc --nThreads 16 --eventcontent AODSIM --datatier AODSIM --conditions 132X_mcRun3_2023_realistic_HI_v5 --step RAW2DIGI,L1Reco,RECO --era Run3_2023,highBetaStar_2018 -n -1
```

The file of step2 can be found in : /eos/cms/store/group/phys_heavyions/anstahll/CERN/PbPb2023/ERA/step2_DIGI_L1_DIGI2RAW_HLT_PU.root

**Comment by slava77** [comment]
type tracking

**Comment by slava77** [comment]
as mentioned in skype, it would be nice to have the step2 root file already in place.
Is this for regular RAW? (no repacking HI steps necessary)

**Comment by stahlleiton** [comment]
yes, it is for regular RAW.
