### ISSUE TITLE
Move RelVal from RECO content to AOD?

### ISSUE THREAD

**Issue by mandrenguyen** [cms-sw/cmssw#43432]
We (reco) have been having some issues with profiling lately. 
One, but not all of the issues, is the large output size of the real data workflows.
An aspect that escaped our attention until now is that all of the real data wfs (e.g., 136.889, which we use in our profiling) write RECO event content, which is only rarely done in real production. 
From the reco side, we would like to profile a workflow which more closely resembles what is done in  prompt reco or in a reprocessing campaign. 
One imagines that moving the majority of relval workflows to AOD would be beneficial to disk load of release validation. 
As the primary responsible of these workflows, we brought this up with @cms-sw/pdmv-l2
They tend to agree that it doesn't make sense to have all real data wfs write RECO (it's not the case for MC), but suggested we bring the issue to a wider audience, hence this issue. 
Does anyone see a reason to continue to run all these wfs with RECO?  Or do we need a more limited test of this heavy event content?

**Comment by mmusich** [comment]
>  Does anyone see a reason to continue to run all these wfs with RECO? Or do we need a more limited test of this heavy event content?

two quick comments (without having given so much though about it)
   * IF there is still some workflow that creates ALCARECO out of the RECO step, these of course become useless if the step before produces only AOD
   * relvals are a cheap source of RECO data-tier for DPGs / POGs to make development down to the level of the most basic objects (clusters, etc.). I agree that for release validation this might not be so useful, but then PPD or someone else should provide another source of RECO events fairly frequently (and please do NOT mention McM production because that has the inertia of nuclear icebreaker).

**Comment by mmusich** [comment]
assign alca

**Comment by mmusich** [comment]
@cms-sw/ppd-l2 FYI

**Comment by mandrenguyen** [comment]
Thank you for the quick feedback @mmusich 
Indeed it appears there are some workflows that run an ALCARECO step, although this is not the case for the series of workflows that we have been using for profiling.
In this case, perhaps we could move to AOD only for certain workflows.  I don't know if that would satisfy the other concern you have about the availability of some workflows with heavier content for punctual low-level investigations.

**Comment by slava77** [comment]
I recall that while making a choice for profiling on data we were trying to represent the heaviest available T0 job. 
The goal was to monitor something that's more likely to lead to operational problems.

**Comment by slava77** [comment]
> > I recall that while making a choice for profiling on data we were trying to represent the heaviest available T0 job. The goal was to monitor something that's more likely to lead to operational problems.
> 
> Thanks, Slava, but is this still realistic? AFAIK, we're not running RECO at T0 anymore and there are no plans to. At the moment, it's one of the factors making profiling very difficult (the other being the lack of igprof support)

OK, sounds good for the `write_reco=False`.

I'd still suggest to check that the profiling is still representative of a PD which has  the longest/heaviest relevant skim/alca config.

**Comment by makortel** [comment]
`core`'s standpoint is that we should be testing (especially in IBs) workflows as they are being run in production (or as closely as possible). Of course that does not preclude testing of additional workflows.

**Comment by slava77** [comment]
> `core`'s standpoint is that we should be testing (especially in IBs) workflows as they are being run in production (or as closely as possible). Of course that does not preclude testing of additional workflows.

curiously enough, 136.889 is from 2018 (run 320822) and we didn't write RECO even back then, based on the [t0 config](https://cmsweb.cern.ch/t0wmadatasvc/prod/reco_config?run=320822)

**Comment by mandrenguyen** [comment]
> > `core`'s standpoint is that we should be testing (especially in IBs) workflows as they are being run in production (or as closely as possible). Of course that does not preclude testing of additional workflows.
> 
> curiously enough, 136.889 is from 2018 (run 320822) and we didn't write RECO even back then, based on the [t0 config](https://cmsweb.cern.ch/t0wmadatasvc/prod/reco_config?run=320822)

Indeed.  We are thinking of switching to the Run 3 equivalent 141.044 for our baseline profiling, which is configured in exactly the same way.
We should have done so earlier.

**Comment by slava77** [comment]
BTW, what about the express jobs? Aren't they writing FEVT? I don't recall memory issues in the express jobs though (but I didn't pay as much attention during Run3)

**Comment by slava77** [comment]
> BTW, what about the express jobs? Aren't they writing FEVT? I don't recall memory issues in the express jobs though (but I didn't pay as much attention during Run3)

... I mean the normal pp jobs; there were some cases with bad data lumis (huge rates or detector noise)

**Comment by mandrenguyen** [comment]
Fair point, but then FEVT is even larger than RECO.  If we really want to emulate that wouldn't we want a dedicated express-like workflow?  Possibly using streamers with the mix of events one has in express, rather than those in the physics PDs?  Maybe such a wf already exists, I didn't check.

**Comment by makortel** [comment]
> If we really want to emulate that wouldn't we want a dedicated express-like workflow? Possibly using streamers with the mix of events one has in express, rather than those in the physics PDs?

I'm in favor of separate workflow(s) to test the express setup.

**Comment by jfernan2** [comment]
Hi, I have created this PR doing the change for Run3 RelVal Data wfs: https://github.com/cms-sw/cmssw/pull/43478

**Comment by mandrenguyen** [comment]
+1
https://github.com/cms-sw/cmssw/pull/43478 is merged now.
