### ISSUE TITLE
ProductNotFound error in module MultiTrackValidator/'trackValidatorJetCoreSeedingTrackingOnly'

### ISSUE THREAD

**Issue by iarspider** [cms-sw/cmssw#43495]
In CMSSW_14_0_X_2023-12-04-2300, RelVals 2017.13, 2018.13, 10024.3 fail with ProductNotFound exception:

```
----- Begin Fatal Exception 05-Dec-2023 07:19:29 CET-----------------------
An exception of category 'ProductNotFound' occurred while
   [0] Processing  Event run: 1 lumi: 1 event: 6 stream: 0
   [1] Running path 'prevalidation_step'
   [2] Calling method for module MultiTrackValidator/'trackValidatorJetCoreSeedingTrackingOnly'
Exception Message:
Principal::getByToken: Found zero products matching all criteria
Looking for a container with elements of type: reco::Track
Looking for module label: seedTracksjetCoreRegionalStepSeedsBarrel
Looking for productInstanceName: 

   Additional Info:
      [a] If you wish to continue processing events after a ProductNotFound exception,
add "TryToContinue = cms.untracked.vstring('ProductNotFound')" to the "options" PSet in the configuration.

----- End Fatal Exception -------------------------------------------------
```

Examples of logs: [1](https://cmssdt.cern.ch/SDT/cgi-bin/logreader/el8_amd64_gcc12/CMSSW_14_0_X_2023-12-04-2300/pyRelValMatrixLogs/run/2017.13_TTbarFS_13_UP17/step1_TTbarFS_13_UP17.log#/1141-1141), [2](https://cmssdt.cern.ch/SDT/cgi-bin/logreader/el8_amd64_gcc12/CMSSW_14_0_X_2023-12-04-2300/pyRelValMatrixLogs/run/2018.13_TTbarFS_13_UP18/step1_TTbarFS_13_UP18.log#/1141-1141), [3](https://cmssdt.cern.ch/SDT/cgi-bin/logreader/el8_amd64_gcc12/CMSSW_14_0_X_2023-12-04-2300/pyRelValMatrixLogs/run/10024.3_TTbar_13+2017_trackingOnlyRun2/step3_TTbar_13+2017_trackingOnlyRun2.log#/92-92), [4](https://cmssdt.cern.ch/SDT/cgi-bin/logreader/el8_amd64_gcc12/CMSSW_14_0_X_2023-12-04-2300/pyRelValMatrixLogs/run/10024.4_TTbar_13+2017_trackingLowPU/step3_TTbar_13+2017_trackingLowPU.log#/75-75).

**Comment by iarspider** [comment]
assign Validation/RecoTrack

**Comment by mmusich** [comment]
this certainly comes from https://github.com/cms-sw/cmssw/pull/43472 @cms-sw/tracking-pog-l2 FYI

**Comment by iarspider** [comment]
@cms-sw/tracking-pog-l2 gentle ping

**Comment by slava77** [comment]
type tracking

**Comment by slava77** [comment]
> assign Validation/RecoTrack

@iarspider @smuzaffar 
can this command also automatically assign non-blocking labels? (so that a manual `type tracking` is not necessary anymore)

**Comment by smuzaffar** [comment]
@slava77 , sure we will update bot to apply non-blocking labels for such comments

**Comment by slava77** [comment]
> @cms-sw/tracking-pog-l2 gentle ping

I missed this issue until the ORP meeting today.
