### ISSUE TITLE
hltIterL3OISeedsFromL2Muons has long startup time for first event in HLT

### ISSUE THREAD

**Issue by Dr15Jones** [cms-sw/cmssw#43504]
The module labeled hltIterL3OISeedsFromL2Muons (which is of type TSGForOIDNN) was found to have greater than 1 second startup times for the first events on most streams. Using VTune, we found that the issue was the module shares the same tensorflow session across all streams and that session holds several locks for a long time which prohibits work from being done on other threads.

**Comment by Dr15Jones** [comment]
assign RecoMuon/TrackerSeedGenerator

**Comment by Dr15Jones** [comment]
Using the log tracer viewer, the issue can be seen clearly.

Here is the original timing for that module for the beginning of event processing:
<img width="1248" alt="hlt_24x18_original" src="https://github.com/cms-sw/cmssw/assets/3757616/6477a4ab-ec78-4f09-adcc-c4edab382a21">

(where the orange is the time spent prefetching for this module and the yellow is the time the module is running. The white box is the longest running module time and has its full information at the bottom of the picture)

Compared to modifying the module so only one stream at a time will run the module
<img width="1248" alt="hlt_24x18_limited" src="https://github.com/cms-sw/cmssw/assets/3757616/d9743082-4bc1-42ec-9a65-eb93dddd7a42">

The original startup took 1.35s and many streams are 'running' at the same time (they are actually being blocked on the mutex). The case where only one stream at a time interacts with the module shows the startup time being 0.5s with all other module runs taking a fraction of that time.

This appears to point to some sort of one-time initialization that needs to be done and once that is finished, the module runs very fast.

So the question is, could the one time initialization be done before the start of event processing?

**Comment by Dr15Jones** [comment]
@fwyzard FYI

**Comment by makortel** [comment]
Let's tag @cms-sw/hlt-l2 too

**Comment by makortel** [comment]
Here is a screenshot from the VTune threading analysis highlighting 3 futexes waited on within Tensorflow

<img width="1236" alt="image" src="https://github.com/cms-sw/cmssw/assets/33993/3e0fcc0f-6b55-47c7-bf1d-cadbaee396da">

when focused to the region of time where event processing has started, but the CPU is utilized quite poorly (the job was ran with 12 threads and 9 streams)
<img width="1209" alt="image" src="https://github.com/cms-sw/cmssw/assets/33993/206cad88-5052-4afd-8e80-0a575e70adec">

Digging into the Tensorflow code I found these from `Run()`
https://github.com/cms-externals/tensorflow/blob/e70be3b6ad18855a4f69dcac2f085d20f8cfe66b/tensorflow/core/common_runtime/direct_session.cc#L865-L868
and `RunInternal()`
https://github.com/cms-externals/tensorflow/blob/e70be3b6ad18855a4f69dcac2f085d20f8cfe66b/tensorflow/core/common_runtime/direct_session.cc#L734-L745
https://github.com/cms-externals/tensorflow/blob/e70be3b6ad18855a4f69dcac2f085d20f8cfe66b/tensorflow/core/common_runtime/direct_session.cc#L793-L802

**Comment by Dr15Jones** [comment]
I added a dummy initialization call to tensorflow at the beginJob in the module. This substantially improved the module timing:
<img width="1453" alt="hlt_24x18_initialize" src="https://github.com/cms-sw/cmssw/assets/3757616/b863baef-0952-4bca-b4a9-7fdf37af7065">

**Comment by Dr15Jones** [comment]
See https://github.com/cms-sw/cmssw/pull/43507

**Comment by mmusich** [comment]
as https://github.com/cms-sw/cmssw/pull/43507 is merged, I would assume this could be signed and closed (@cms-sw/reconstruction-l2 ).

**Comment by makortel** [comment]
@cmsbuild, please close
