### ISSUE TITLE
Unrunnable schedule exception on a small subset of HLT menu

### ISSUE THREAD

**Issue by makortel** [cms-sw/cmssw#43517]
While investigating something else, I found that a certain small subset of the HLT menu leads to an unrunnable schedule. Recipe to reproduce is e.g.
```sh
cmsrel CMSSW_14_0_X_2023-12-06-1100
cd CMSSW_14_0_X_2023-12-06-1100/src
cmsenv
addOnTests.py
cd addOnTests/hlt_data_GRun
cat <<EOF >>RelVal_HLT_RAW2DIGI_L1Reco_RECO.py
process.schedule = cms.Schedule(
    process.DST_HLTMuon_Run3_PFScoutingPixelTracking_v22,
    process.Dataset_Muon0,
    process.Dataset_Muon1,
    process.HLT_DoubleMu43NoFiltersNoVtx_v10
)
EOF
cmsRun RelVal_HLT_RAW2DIGI_L1Reco_RECO.py
```
that results in
```
----- Begin Fatal Exception 06-Dec-2023 21:51:12 CET-----------------------
An exception of category 'ScheduleExecutionFailure' occurred while
   [0] Calling beginJob
Exception Message:
Unrunnable schedule
The Path/EndPath configuration could cause the job to deadlock
  module 'hltMuonTriggerResultsFilter' is on path 'DST_HLTMuon_Run3_PFScoutingPixelTracking_v22' and depends on module 'Dataset_Muon0'
  module 'Dataset_Muon0' is on path 'Dataset_Muon0' and follows module 'hltDatasetMuon' on the path
  module 'hltDatasetMuon' is on path 'Dataset_Muon0' and depends on module 'HLT_DoubleMu43NoFiltersNoVtx_v10'
  module 'HLT_DoubleMu43NoFiltersNoVtx_v10' is on path 'HLT_DoubleMu43NoFiltersNoVtx_v10' and follows module 'hltL3fDimuonL1f0L2NVf16L3NoFiltersNoVtxFiltered43' on the path
  module 'hltL3fDimuonL1f0L2NVf16L3NoFiltersNoVtxFiltered43' is on path 'HLT_DoubleMu43NoFiltersNoVtx_v10' and depends on module 'hltL3MuonsIterL3Links'
  module 'hltL3MuonsIterL3Links' is on path 'DST_HLTMuon_Run3_PFScoutingPixelTracking_v22' and follows module 'hltMuonTriggerResultsFilter' on the path
----- End Fatal Exception -------------------------------------------------
```
**Is this expected?**

(I'm still looking into what exactly in the full(er) menu allows the schedule to become runnable, in particular because placing `hltBoolFalse` in a specific place in one Sequence leads the job get stuck because of becoming starved from tasks, which is something we'd much want the framework to catch early)

---

In addition, the following piece in the configuration of `hltL3fDimuonL1f0L2NVf16L3NoFiltersNoVtxFiltered43` caught my eye
```py
process.hltL3fDimuonL1f0L2NVf16L3NoFiltersNoVtxFiltered43 = cms.EDFilter("HLTMuonL3PreFilter",
...
    InputLinks = cms.InputTag("hltL3MuonsIterL3Links"),
    L1CandTag = cms.InputTag(""),
...
    inputMuonCollection = cms.InputTag(""),
...
```

The `hltL3fDimuonL1f0L2NVf16L3NoFiltersNoVtxFiltered43` modules in the `HLT_DoubleMu43NoFiltersNoVtx_v10` Path, but the `hltL3MuonsIterL3Links` is not in the same Path, but in `DST_HLTMuon_Run3_PFScoutingPixelTracking_v22`. **Is this expected?** (I recall HLT policy would be to have each Path self contained)

The `L1CandTag` and `inputMuonCollection`, that have empty `InputTag`s, are consumed unconditionally
https://github.com/cms-sw/cmssw/blob/754d4fbc8bf3e05df6de16937fe6f4d30f5d8699/HLTrigger/Muon/plugins/HLTMuonL3PreFilter.cc#L45-L48
(which is technically ok as far as the framework is concerned)

Getting the `L1CandTag` collection from the Event is protected with
https://github.com/cms-sw/cmssw/blob/754d4fbc8bf3e05df6de16937fe6f4d30f5d8699/HLTrigger/Muon/plugins/HLTMuonL3PreFilter.cc#L232-L236
(it would be better to not call `consumes()` if it is known at the module construction time that the data product is not consumed)

The `inputMuonCollection` is, however, gotten from the Event unconditionally, but presumably the `MuonToL3s` container is always empty in that module so that the de-referencing of the `Handle` does not throw `ProductNotFound` exception
https://github.com/cms-sw/cmssw/blob/754d4fbc8bf3e05df6de16937fe6f4d30f5d8699/HLTrigger/Muon/plugins/HLTMuonL3PreFilter.cc#L270-L274

I'm wondering **if this behavior is expected for this module?**

**Comment by makortel** [comment]
assign hlt

**Comment by Martin-Grunewald** [comment]
Concerning the ```process.schedule``` issue, why is the framework complaining? It should run just fine like this:

Path HLT_DoubleMu43NoFiltersNoVtx_v10 should execute. Then the Dataset_Muon0/1 paths can run as they need, in filter hltDatasetMuon, the results of muon triggers including HLT_DoubleMu43NoFiltersNoVtx_v10. 

And then path DST_HLTMuon_Run3_PFScoutingPixelTracking_v22 can run, depending on a filter also used in Dataset_Muon0/1.

So (unfortunately) these paths depend on each other and need to run in this order.

It used to be that HLT paths should be independent of each other, but this is now violated two-fold by introducing 1) the concept of Dataset_XXX paths which are used to define primary datasets (and are based on normal HLT paths and thus should run after them), and 2) the scouting DST_*** paths running on top of events collected by Dataset_ paths.

**Comment by Martin-Grunewald** [comment]
For the bug in the configuration of ```HLT_DoubleMu43NoFiltersNoVtx_v10```, I created the CMSHLT Jira ticket https://its.cern.ch/jira/browse/CMSHLT-2975 .

**Comment by makortel** [comment]
Thanks @Martin-Grunewald. I'm still wondering if the `hltL3fDimuonL1f0L2NVf16L3NoFiltersNoVtxFiltered43. inputMuonCollection` being an empty `InputTag` is intentional?

(if it is, it would be clearer if the `HLTMuonL3PreFilter` would explicitly handle that special case)

**Comment by missirol** [comment]
Based on one very simple check [*], I see that `hltL3fDimuonL1f0L2NVf16L3NoFiltersNoVtxFiltered43` always ends up having `useL3MTS == true` ([here](https://github.com/cms-sw/cmssw/blob/bb13ad112cad04ae2bcf5a11ec1362dda00c3fb9/HLTrigger/Muon/plugins/HLTMuonL3PreFilter.cc#L178)). As a consequence, the collections consumed via `InputLinks` and `L1CandTag` are never accessed/used. Another consequence, in turn, is that the `std::map` named `MuonToL3s` remains empty (as already noted in the description of this issue), and so the collection consumed via `inputMuonCollection` is never accessed/used (in other words, the value of `hltL3fDimuonL1f0L2NVf16L3NoFiltersNoVtxFiltered43.inputMuonCollection` is unconsequential for what concerns the outputs of this plugin).

Looks like the simpler solution is to set
```
hltL3fDimuonL1f0L2NVf16L3NoFiltersNoVtxFiltered43.InputLinks = cms.InputTag( "" )
```

It should also be possible to improve the implementation of `HLTMuonL3PreFilter` such that `InputLinks`, `L1CandTag` and `inputMuonCollection` are not consumed unnecessarily in this case (this, too, was already mentioned in previous comments).

[*]
```bash
#!/bin/bash

hltGetConfiguration /dev/CMSSW_13_3_0/GRun \
   --globaltag auto:phase1_2024_realistic \
   --mc \
   --unprescale \
   --output minimal \
   --max-events 100 \
   --input /store/relval/CMSSW_13_3_0_pre4/RelValTTbar_14TeV/GEN-SIM-DIGI-RAW/133X_mcRun3_2023_realistic_v1_Standard_13_3_0_pre4-v1/2590000/4c47f6d7-9938-4c87-b795-ece3aa6d3d22.root \
   --eras Run3 --l1-emulator FullMC --l1 L1Menu_Collisions2023_v1_3_0_xml \
   > hlt.py
cat <<@EOF >> hlt.py
process.options.numberOfThreads = 1
process.options.numberOfStreams = 0
@EOF
cmsRun hlt.py &> hlt.log
```
```diff
diff --git a/HLTrigger/Muon/plugins/HLTMuonL3PreFilter.cc b/HLTrigger/Muon/plugins/HLTMuonL3PreFilter.cc
index 7fdd2b79c54..aa0c9cf93de 100644
--- a/HLTrigger/Muon/plugins/HLTMuonL3PreFilter.cc
+++ b/HLTrigger/Muon/plugins/HLTMuonL3PreFilter.cc
@@ -174,6 +174,8 @@ bool HLTMuonL3PreFilter::hltFilter(Event& iEvent,
     useL3MTS = a != nullptr;
   }
 
+  edm::LogPrint("HLTMuonL3PreFilter") << "XXX " << moduleDescription().moduleLabel() << " useL3MTS=" << useL3MTS;
+
   // If we can use L3MuonTrajectory seeds run the older code:
   if (useL3MTS) {
     LogDebug("HLTMuonL3PreFilter") << "HLTMuonL3PreFilter::hltFilter is in mode: useL3MTS";
```

**Comment by Martin-Grunewald** [comment]
From your test I gather we can set ALL three InputTags in question to an empty InputTag for ALL instances of ```HLTMuonL3PreFilter``` currently in use in the HLT menus. But I wonder whether this is somehow implied from the module configuration.

**Comment by Martin-Grunewald** [comment]
@makortel 

General question on the explicit general treatment of potentially empty InputTags in code like this:
```
l1CandTag_(iConfig.getParameter<InputTag>("L1CandTag")), l1CandToken_(consumes<trigger::TriggerFilterObjectWithRefs>(l1CandTag_)), 
```
i.e., if ```L1Candtag``` is an empty InputTag : shouldn't that be handled by the consumes call which gets to see the actual InputTag, ```l1CandTag_``` in this case? Otherwise I would think ince there are many constructs like the above in CMSSW code where the InputTag could be empty, they would need to get changed everywhere to explicitly check on InputTag.encode() being an empty string.

**Comment by mmusich** [comment]
> Looks like the simpler solution is to set
> `hltL3fDimuonL1f0L2NVf16L3NoFiltersNoVtxFiltered43.InputLinks = cms.InputTag( "" )`

just to confirm that technically with this change:

```diff
diff --git a/HLTrigger/Configuration/python/HLT_GRun_cff.py b/HLTrigger/Configuration/python/HLT_GRun_cff.py
index 85ec1b54796..d58a97373e1 100644
--- a/HLTrigger/Configuration/python/HLT_GRun_cff.py
+++ b/HLTrigger/Configuration/python/HLT_GRun_cff.py
@@ -51375,7 +51375,7 @@ fragment.hltL3fDimuonL1f0L2NVf16L3NoFiltersNoVtxFiltered43 = cms.EDFilter( "HLTM
     trkMuonId = cms.uint32( 0 ),
     L1MatchingdR = cms.double( 0.3 ),
     MatchToPreviousCand = cms.bool( True ),
-    InputLinks = cms.InputTag( "hltL3MuonsIterL3Links" ),
+    InputLinks = cms.InputTag( "" ),
     useSimpleGeometry = cms.bool( True ),
     useStation2 = cms.bool( True ),
     fallbackToME1 = cms.bool( False ),
```

**which of course needs to be applied in confDB first** (!) the schedule become runnable. 
In order for the recipe posted at https://github.com/cms-sw/cmssw/issues/43517#issue-2029399678 by @makortel to not crash immediately thereafter one needs to add this line
```
process.hltDatasetMuon.throw = False
``` 

to `RelVal_HLT_RAW2DIGI_L1Reco_RECO.py` which is due to the fact that the originally suggested configuration doesn't include all the paths of `Dataset_Muon*` (I suppose for simplicity of illustration).
In any case I guess we can go ahead first with the change of the combined table to close this issue with the minimal fix, while we develop an improvement of `HLTMuonL3PreFilter` according to https://github.com/cms-sw/cmssw/issues/43517#issuecomment-1849455057.

**Comment by mmusich** [comment]
> One possibility to improve the implementation of `HLTMuonL3PreFilter` is to add a boolean parameter to the plugin (say, `requireL3MuonTrajectorySeed`) which, if true, would make the plugin throw an exception if [this cast](https://github.com/cms-sw/cmssw/blob/bb13ad112cad04ae2bcf5a11ec1362dda00c3fb9/HLTrigger/Muon/plugins/HLTMuonL3PreFilter.cc#L173) fails. In the constructor, one could then call consumes on `InputLinks`, `L1CandTag` and `inputMuonCollection` only if `requireL3MuonTrajectorySeed == false` ([something like this (random example)](https://github.com/cms-sw/cmssw/blob/bb13ad112cad04ae2bcf5a11ec1362dda00c3fb9/DQM/HLTEvF/plugins/LumiMonitor.cc#L98-L100)). The parameter `requireL3MuonTrajectorySeed` would be false by default, but in the case of `hltL3fDimuonL1f0L2NVf16L3NoFiltersNoVtxFiltered43 `(and maybe other modules), we could set it to true.

I followed this up at https://github.com/cms-sw/cmssw/pull/43549. Once integrated we can relinquish the useless consume by flipping the configuration of selected modules directly in ConfDB and port in `cmssw` as per usual HLT development.

**Comment by mmusich** [comment]
+hlt
   * this issue is gone after the integration in confDB of https://its.cern.ch/jira/browse/CMSHLT-2975
   * integrated in cmssw at https://github.com/cms-sw/cmssw/pull/43788
   
This can be verified using the following script:

```bash
cmsrel CMSSW_14_0_X_2024-01-30-2300 
cd CMSSW_14_0_X_2024-01-30-2300/src
cmsenv
addOnTests.py --tests=hlt_data_GRun 
cd addOnTests/hlt_data_GRun
cat <<EOF >>RelVal_HLT_RAW2DIGI_L1Reco_RECO.py
process.schedule = cms.Schedule(
    process.DST_HLTMuon_Run3_PFScoutingPixelTracking_v22,
    process.Dataset_Muon0,
    process.Dataset_Muon1,
    process.HLT_DoubleMu43NoFiltersNoVtx_v10
)
process.hltDatasetMuon.throw = False
EOF
cmsRun RelVal_HLT_RAW2DIGI_L1Reco_RECO.py
```
