### ISSUE TITLE
About possibility of cleanup of unused code 

### ISSUE THREAD

**Issue by swagata87** [cms-sw/cmssw#43527]
It seems that the following pieces of code are not used anymore. Maybe we can consider removing them to avoid the maintenance burden.

```
RecoEgamma/EgammaIsolationAlgos/plugins/EgammaEcalRecHitIsolationProducer.cc
RecoParticleFlow/PFProducer/src/PhotonSelectorAlgo.cc
RecoParticleFlow/PFProducer/plugins/importers/EGPhotonImporter.cc
```

PS:
also this one looks like unused code:
```
RecoParticleFlow/PFProducer/plugins/PFPhotonTranslator.cc
```

**Comment by swagata87** [comment]
type egamma, pf

**Comment by swagata87** [comment]
addressed in https://github.com/cms-sw/cmssw/pull/43714 ; so may be the issue can be closed

**Comment by jfernan2** [comment]
+1

**Comment by makortel** [comment]
@cmsbuild, please close
