### ISSUE TITLE
CMSSW non-x86_64 containers for grid jobs

### ISSUE THREAD

**Issue by smuzaffar** [cms-sw/cmssw#43578]
@mmascher , In order to support non-x86_64 archs, we are now building and deploying `cmssw/cms:rhelN-$(uname m)` containers [a] under `/cvmfs/singularity.opensciencegrid.org/cmssw`.  How can we make sure that CMS grid jobs start using these new arch based containers instead of old `cmssw/cms:rhel[7-9]` ?

[a]
- cmssw/cms:rhel[7-9]-x84_64   ( identical to existing cmssw/cms:rhel[7-9] containers)
- cmssw/cms:rhel[7-9]-aarch64
- cmssw/cms:rhel[7-9]-ppc64le

**Comment by makortel** [comment]
assign core

**Comment by smuzaffar** [comment]
there is JIRA ticket open for this https://its.cern.ch/jira/browse/CMSSI-88

**Comment by smuzaffar** [comment]
+core

new container are in production use now
