### ISSUE TITLE
EndPathStatus should not be produced in merge jobs

### ISSUE THREAD

**Issue by makortel** [cms-sw/cmssw#43619]
@Dr15Jones and I investigated (again) assertion failures reported in https://cms-talk.web.cern.ch/t/getting-error-readeventsucceeded-failed-when-running-cmsrun/29893/14
```
cmsRun: /.../CMSSW_12_4_11/src/IOPool/Input/src/PoolSource.cc:238: virtual void edm::PoolSource::readEvent_(edm::EventPrincipal&): Assertion `readEventSucceeded’ failed.
```

Earlier (around end of September) @wddgit discovered that a simple job with an `EndPath` and an `OutputModule` adds `EndPathStatus` to the ProductRegistry, and that leads to `BranchListIndexes` to have additional entries for Merge jobs, that can lead to the aforementioned assertion to fail.

Currently the `EndPathStatus` seems to be used only for `FinalPath` within the framework code (in addition of tests).

Injecting the `EndPathStatus` data products in the job only if something consumes the `EndPathStatus` would seem the most robust way to avoid adding `EndPathStatus` to the ProductRegistry in Merge jobs.

**Comment by makortel** [comment]
assign core

**Comment by makortel** [comment]
Just for the record, the reason for why a Merge job that adds the `EndPathStatus` into the ProductRegistry does not cause additional entry in the `ProcessHistory` is in
https://github.com/cms-sw/cmssw/blob/deaac86743f80cda845f794c9335ba27a4d50417/DataFormats/Provenance/src/ProductRegistry.cc#L327-L329
i.e. job that produces only transient data products gets ignored in the `ProcessHistory`.

**Comment by wddgit** [comment]
Just for reference, the documentation we wrote after the discussions in September 2023 is here:

https://twiki.cern.ch/twiki/bin/view/CMSPublic/SWGuidePoolInputSources#Example_5_Merging_files_with_dif

**Comment by makortel** [comment]
Fixed (minimally) in https://github.com/cms-sw/cmssw/pull/43683

**Comment by makortel** [comment]
+core
