### ISSUE TITLE
build CMSSW_14_0_0_pre2_SKYLAKEAVX512 release

### ISSUE THREAD

**Issue by fwyzard** [cms-sw/cmssw#43654]
@smuzaffar, would it be possible to build `CMSSW_14_0_0_pre2_SKYLAKEAVX512`, for `el8_amd64_gcc12` and `el9_amd64_gcc12` architectures ?

I would like to re-evaluate the impact on the HLT using AVX-2 (on AMD Milan on RHEL8) and AVX-512 (on AMD Genoa on RHEL 9) after the switch to GCC 12.

**Comment by fwyzard** [comment]
assign core

**Comment by smuzaffar** [comment]
@fwyzard , I have started the build via https://github.com/cms-sw/cmssw/issues/43674 . I am not sure if el9 build will finish properly as we have not build el9 SKYLAKEAVX512 IBs

**Comment by fwyzard** [comment]
Thank you 👍🏻

**Comment by fwyzard** [comment]
Thanks @smuzaffar , I've installed CMSSW_14_0_0_pre2_SKYLAKEAVX512 on a RHEL8 and a RHEL9 machine, and will start playing with it.
