### ISSUE TITLE
SimG4CMS/Forward/src/ZdcSD.cc DBG compilation failure

### ISSUE THREAD

**Issue by dan131riley** [cms-sw/cmssw#43666]
#43576 breaks DBG builds.  This line https://github.com/cms-sw/cmssw/blob/9fca027cd9b380c6d9f4244b56f3e2c9ef2899db/SimG4CMS/Forward/src/ZdcSD.cc#L218-L223 fails to compile with the error

```
SimG4CMS/Forward/src/ZdcSD.cc:219:59: error: 'nameVolume' was not declared in this scope; did you mean 'EVolume'?
   219 |                                  << "  preStepPoint: " << nameVolume << "," << stepL << "," << stepE << "," << beta
      |                                                           ^~~~~~~~~~
      |                                                           EVolume
```

because `nameVolume` was removed in https://github.com/cms-sw/cmssw/pull/43576/commits/c67f1d3a946ea67b7706fc95e3df04bdddd68c97

**Comment by makortel** [comment]
assign simulation

**Comment by civanch** [comment]
+1

It seems that #43672 resolve the issue

**Comment by civanch** [comment]
@dan131riley , it it is fixed, please, close the issue.

**Comment by makortel** [comment]
@civanch You can also ask the bot to close with `please close`.
