### ISSUE TITLE
Issues with (Char_t) seediEtaOriX in Nanov11 onwards

### ISSUE THREAD

**Issue by a-kapoor** [cms-sw/cmssw#43699]
The PR https://github.com/cms-sw/cmssw/pull/40327 added iEta,iPhi (for barrel) and iX,iY(for endcaps) to NanoAOD for photons and electrons. These are useful to veto the EE+ leak region at analysis level. 

These variables were added as int8, it is not clear why **_seediEtaOriX** ends of as **Char_t** in the NanoAOD.
See [docs](https://cms-nanoaod-integration.web.cern.ch/autoDoc/NanoAODv11/2022postEE/doc_WZ_TuneCP5_13p6TeV_pythia8_Run3Summer22EENanoAODv11-126X_mcRun3_2022_realistic_postEE_v1-v1.html)
![image](https://github.com/cms-sw/cmssw/assets/8407736/e2ad5429-030a-4c29-8773-fe226d936128)
Same issue for electrons too. 

The consequence is that when one reads these values, the **_seediEtaOriX** dumps some junk values:
![image](https://github.com/cms-sw/cmssw/assets/8407736/bec7d65d-4092-4ddb-9396-b56a6f94b10a)

Happens for both photons and electrons. The reason might be that [ROOT interprets int8 as char](https://root.cern/root/html534/TTree.html). Although it is not clear why it only happens for _seediEtaOriX and not **_seediPhiOriY**

A workaround for analyzers might be to force ROOT to tree it as an integer, like this:
![image](https://github.com/cms-sw/cmssw/assets/8407736/ca827233-ff8c-43c0-bd53-36a752a7f7a2)

Note how I forced the type conversion by adding a zero.

Yet a permanent solution for future versions could be to change the type of this variable from int8 to int16.

This is not an isolated issue, and my student has seen other issues in new NanoAODs with these kind of datatypes:
https://cms-talk.web.cern.ch/t/uchar-short-and-char-variables-in-nanoaod-v12-inconsistent-results-using-root/33208

Will target a fix for EGM variable in Nano v14.

@RSalvatico @swagata87 @Prasant1993

**Comment by a-kapoor** [comment]
type egamma, root

**Comment by a-kapoor** [comment]
assign egamma-pog, xpog

**Comment by makortel** [comment]
The definitions (as added by https://github.com/cms-sw/cmssw/pull/40327)
https://github.com/cms-sw/cmssw/blob/f5cbbf1ab5806ffc54ccaab6a77201f35d63fca7/PhysicsTools/NanoAOD/python/electrons_cff.py#L353-L354
have
* `seediEtaOriX` with type `"int8"`
* `seediPhiOriY` with type `int`

that seems explain why the first one is stored as `Char_t` and the second as `Int_t`.

**Comment by vlimant** [comment]
indeed, the new types were introduced with #40478 and this end up with leaves of questionable type in ROOT
`root [27] Events->GetLeaf("Photon_seediEtaOriX")->GetTypeName()
(const char *) "Char_t"
root [28] Events->GetLeaf("Photon_seediPhiOriY")->GetTypeName()
(const char *) "Int_t"`

so int8 (and uint8) are messed up when transferred to plain ROOT, as was already noticed by @swertz (not CMS anymore).

**Comment by makortel** [comment]
Otherwise the behavior looks like expected. `int8_t` is (likely) a type alias to `signed char`, and out of the box that gets interpreted as a character (rather than integer) when printing out.

**Comment by makortel** [comment]
type -root

I don't think this is an issue to be addressed by ROOT.

**Comment by vlimant** [comment]
@makortel  : where do I find the real meaning of "int8_t" and can we change this to what it means ?

**Comment by a-kapoor** [comment]
@vlimant Shall I change the "int8" to int as done for seediPhiOriY if there are no central nano issues with this? It will solve the problem for these variables at least. What do you think?

**Comment by swertz** [comment]
Hi there, if you want to avoid that pesky ROOT formatting issue with `int8`, just change it to `int16` (see indeed description in https://github.com/cms-sw/cmssw/pull/40478). 

`uint8` should be fine but that is not what you want here.

**Comment by vlimant** [comment]
because of the fundamental type and how it ends up stored in root, I think we need to centrally roll back and ban usage of int8, unit8, and maybe others from the nano table code to avoid dubious interpretation in root.
unless there is a smarter way to tell root to interpret signed char as integer number automatically

**Comment by swertz** [comment]
See the discussion here: https://root-forum.cern.ch/t/draw-short-integers-as-numbers-not-characters/52530/24

`int8` should be fine, it's really only `uint8` that's making a mess.

**Comment by a-kapoor** [comment]
Hi @swertz as you can see in my description, in this specific case, it is "int8" that's making the mess

**Comment by swertz** [comment]
Sorry that was a typo, I meant to say that `uint8` should be fine but `int8` should be avoided and `int16` used instead.

**Comment by vlimant** [comment]
uint8 (used for PV_npvs for example) give issues with pyroot  https://cms-talk.web.cern.ch/t/issues-with-uint8-t-variables-in-nanoaodv12/31598

**Comment by vlimant** [comment]
parallel to rolling back int8 in nano (and then uint8), how do we go about having this "fixed" at the ROOT level ?

**Comment by vlimant** [comment]
https://github.com/root-project/root/issues/14361 for reference

**Comment by vlimant** [comment]
+1

**Comment by vlimant** [comment]
please close
