### ISSUE TITLE
Triton model versioning

### ISSUE THREAD

**Issue by kpedro88** [cms-sw/cmssw#43695]
The enforcement of model versioning in Triton for SONIC will require a series of PRs. This issue exists to keep track of those PRs and for discussion of any pertinent details.

1. cms-data: add model checksums
    - [x] https://github.com/cms-data/HeterogeneousCore-SonicTriton/pull/3
    - [x] https://github.com/cms-data/RecoBTag-Combined/pull/54
    - [x] https://github.com/cms-data/RecoEcal-EgammaClusterProducers/pull/5
    - [x] https://github.com/cms-data/RecoEgamma-EgammaPhotonProducers/pull/5
    - [x] https://github.com/cms-data/RecoMET-METPUSubtraction/pull/7
    - [x] https://github.com/cms-data/RecoTauTag-TrainingFiles/pull/13
2. cmsdist: related external updates, update cms-data tags after 1.
    - [x] https://github.com/cms-sw/cmsdist/pull/8943
    - [x] https://github.com/cms-sw/cmsdist/pull/8947
    - [x] https://github.com/cms-sw/cmsdist/pull/8963
    - [x] https://github.com/cms-sw/cmsdist/pull/8964
    - [x] https://github.com/cms-sw/cmsdist/pull/8965
    - [x] https://github.com/cms-sw/cmsdist/pull/8966
    - [x] https://github.com/cms-sw/cmsdist/pull/8967
    - [x] https://github.com/cms-sw/cmsdist/pull/8982
3. cmssw: add config tool, versioning check in TritonClient, unit test for all cms-data
    - [x] https://github.com/cms-sw/cmssw/pull/43696
4. cmssw: various bug fixes
    - [x] https://github.com/cms-sw/cmssw/pull/43814
5. cms-data: test PR with wrong checksum to ensure unit test functions properly
    - [x] https://github.com/cms-data/HeterogeneousCore-SonicTriton/pull/4

**Comment by makortel** [comment]
assign heterogeneous, ml
