### ISSUE TITLE
Drop no-deprecated build flags

### ISSUE THREAD

**Issue by smuzaffar** [cms-sw/cmssw#43740]
@cms-sw/all-l2 , as `CMSSW 14.0.X DEVEL` IBs are now clean if `deprecated` warnings, we propose that we remove the `-Wno-deprecated-copy -Wno-deprecated` flags from the default configuration of CMSSW 14.0.X. Let us know if you have any objections.

**Comment by smuzaffar** [comment]
By the way, as we still have [std::autoptr](https://github.com/cms-sw/cmssw/blob/master/SimDataFormats/GeneratorProducts/src/classes_def.xml#L105) for [reading old root file](https://github.com/cms-sw/cmssw/issues/43422) so after dropping these flags we do get compilation warnings during root dictionary generation [a]. Also we get many warnings coming from externals/gcc ( see https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-4cfead/36902/build-logs/ for over 400 ignored warnings). Although we ignore these warnings and those are not shown as warnings via IB page but developers will see them when they build cmssw.

[a] https://cmssdt.cern.ch/SDT/cgi-bin/buildlogs/el8_amd64_gcc12/CMSSW_14_0_DEVEL_X_2024-01-16-2300/SimDataFormats/GeneratorProducts

```
SimDataFormatsGeneratorProducts/a/SimDataFormatsGeneratorProducts_xr.cc: In function 'ROOT::TGenericClassInfo* ROOT::GenerateInitInstanceLocal(const std::auto_ptr<gen::PdfInfo>*)':
  SimDataFormatsGeneratorProducts/a/SimDataFormatsGeneratorProducts_xr.cc:236:7: warning: 'template<class> class std::auto_ptr' is deprecated: use 'std::unique_ptr' instead [-Wdeprecated-declarations]
   236 |       auto_ptr<gen::PdfInfo> *ptr = nullptr;
      |       ^~~~~~~~
.../gcc/12.3.1-40d504be6370b5a30e3947a6e575ca28/include/c++/12.3.1/bits/unique_ptr.h:64:28: note: declared here
   64 |   template<typename> class auto_ptr;
      |                            ^~~~~~~~
  SimDataFormatsGeneratorProducts/a/SimDataFormatsGeneratorProducts_xr.cc:237:69: warning: 'template<class> class std::auto_ptr' is deprecated: use 'std::unique_ptr' instead [-Wdeprecated-declarations]
   237 |       static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(auto_ptr<gen::PdfInfo>));
      |                                                                     ^~~~~~~~
.../gcc/12.3.1-40d504be6370b5a30e3947a6e575ca28/include/c++/12.3.1/bits/unique_ptr.h:64:28: note: declared here
   64 |   template<typename> class auto_ptr;
      |                            ^~~~~~~~
  SimDataFormatsGeneratorProducts/a/SimDataFormatsGeneratorProducts_xr.cc:240:26: warning: 'template<class> class std::auto_ptr' is deprecated: use 'std::unique_ptr' instead [-Wdeprecated-declarations]
   240 |                   typeid(auto_ptr<gen::PdfInfo>), ::ROOT::Internal::DefineBehavior(ptr, ptr),
```

**Comment by makortel** [comment]
Given that we are close to the last open pre-release of 14_0_X, how about we would remove the `-Wno-deprecated-copy -Wno-deprecated` flags in early 14_1_X? Then users of 14_0_X would not have get annoyed by the warning messages. I'm also hopeful we'd be able to address the https://github.com/cms-sw/cmssw/issues/43422 soon (but likely in 14_1_X).

**Comment by fwyzard** [comment]
Would it make sense to drop the flags globally, and add them back only in `SimDataFormats/GeneratorProducts/BuildFile.xml` ?
