### ISSUE TITLE
Update TestRun3ScoutingFormats unit test after 14_0_0_pre3

### ISSUE THREAD

**Issue by makortel** [cms-sw/cmssw#43755]
This issue is to remind that the `TestRun3ScoutingFormats` unit test needs to be updated using the 14_0_0_pre3 following the merge of https://github.com/cms-sw/cmssw/pull/43744. For more details what needs to be done see https://github.com/cms-sw/cmssw/pull/43744#issuecomment-1900539053 and/or https://github.com/cms-sw/cmssw/blob/master/DataFormats/Scouting/README.md .

**Comment by makortel** [comment]
assign core, hlt

**Comment by makortel** [comment]
@arsahasransu Can you take care of updating the unit test?

**Comment by makortel** [comment]
https://github.com/cms-sw/cmssw/pull/43758 updates scouting data formats as well. A single update of `TestRun3ScoutingFormats` encompassing all the scouting data format changes for 2024 would be sufficient.

**Comment by mmusich** [comment]
> Can you take care of updating the unit test?

I can take care of updating the external. Just to be sure I understand the procedure.
One should follow these instructions:

https://github.com/cms-sw/cmssw/blob/9b2ab85ed1bde269fdf90744fcc7644984f657b2/DataFormats/Scouting/test/TestRun3ScoutingFormats.sh#L11-L47

create the new file, upload it to https://github.com/cms-data/DataFormats-Scouting/ and then modify `TestRun3ScoutingFormats.sh` by adding a new section for the new file ?
I couldn't find in the instructions what does the `v3_v5_v3_v4_v5_v3_v5_v3_v3` string in the renamed file `testRun3Scouting_v3_v5_v3_v4_v5_v3_v5_v3_v3_CMSSW_12_4_0.root` stands for. 
Are these version of the classes as ordered in the `BuildFile.xml`? 
```xml
  <class name="Run3ScoutingCaloJet" ClassVersion="3">
  <class name="Run3ScoutingElectron" ClassVersion="6">
  <class name="Run3ScoutingHitPatternPOD" ClassVersion="3">
  <class name="Run3ScoutingMuon" ClassVersion="4">
  <class name="Run3ScoutingParticle" ClassVersion="5">
  <class name="Run3ScoutingPFJet" ClassVersion="3">
  <class name="Run3ScoutingPhoton" ClassVersion="5">
  <class name="Run3ScoutingTrack" ClassVersion="3">
  <class name="Run3ScoutingVertex" ClassVersion="3">
```
The pattern does not seem to fully match because the second entry (assuming it's for `Run3ScoutingElectron`) should be `v6`, but the file instead contains `v5`. Is it a typo?

**Comment by makortel** [comment]
> I can take care of updating the external.

Thanks!

> One should follow these instructions:
> create the new file, upload it to https://github.com/cms-data/DataFormats-Scouting/ and then modify `TestRun3ScoutingFormats.sh` by adding a new section for the new file ?

Correct. But I would hold off until all the scouting data format updates for 14_0_X have been done (we really want the class versions used in the data taking to be tested, intermediate steps are not needed as long as no persistent data was written with those, and the data format updates seem to be coming close in time now).

> I couldn't find in the instructions what does the `v3_v5_v3_v4_v5_v3_v5_v3_v3` string in the renamed file `testRun3Scouting_v3_v5_v3_v4_v5_v3_v5_v3_v3_CMSSW_12_4_0.root` stand for.
> Are these version of the classes as ordered in the `BuildFile.xml`?

Correct. The order is documented in [`DataFormats/Scouting/README.md`](https://github.com/cms-sw/cmssw/blob/master/DataFormats/Scouting/README.md):
> The file name should contain the version numbers of the data format classes (from classes_def.xml) in alphabetical order (they are in this alphabetical order already in classes_def.xml) and the release or pre-release with which it was written.


> The pattern does not seem to fully match because the second entry (assuming it's for `Run3ScoutingElectron`) should be `v6`, but the file instead contains `v5`. Is it a typo?

The `Run3ScoutingElectron` had version 5 in CMSSW_12_4_0. The class had an update for 13_0_X, increasing the version number to 6, and that is used in the 13_0_3 test file `testRun3Scouting_v3_v6_v3_v4_v5_v3_v5_v3_v3_CMSSW_13_0_3.root`.

**Comment by makortel** [comment]
Let me tag @wddgit in case he would have anything to add or correct me.

**Comment by mmusich** [comment]
> The Run3ScoutingElectron had version 5 in CMSSW_12_4_0. The class had an update for 13_0_X, increasing the version number to 6, and that is used in the 13_0_3 test file testRun3Scouting_v3_v6_v3_v4_v5_v3_v5_v3_v3_CMSSW_13_0_3.root.

why it wasn't updated in the tests?

**Comment by mmusich** [comment]
> why it wasn't updated in the tests?

ah OK, somewhat counter-intuitively it goes from older to newer (not newest format on top). Sorry for the noise.

**Comment by wddgit** [comment]
Everything said above is correct. If you need help with this let me know.

Feel free to swap the order in the .sh file if that is more intuitive.

I'll add a couple more comments here, maybe this is obvious already... TestWriteRun3Scouting.cc is already in the repository so you will not need to cherry pick commits this time. It is already there in the release. You will need to edit both TestWriteRun3Scouting.cc and TestReadRun3Scouting.cc to reflect whatever changes were made in the data format.

The test just writes some meaningless made-up values on the write and verifies the expected values are read from data file. So if new data members are added they need to be written. If I'm remembering correctly, the write module needs to only write the current version, but the read module needs to be able to handle reading all the old versions for the tests. The configuration files might also need some changes.

**Comment by makortel** [comment]
Given https://github.com/cms-sw/cmssw/pull/43758#issuecomment-1910493874, it would be sufficient to update test for the updates in
* `Run3ScoutingElectron`
* `Run3ScoutingPhoton`
* `Run3ScoutingVertex`

using 14_0_0_pre3 to produce the new test file.

**Comment by mmusich** [comment]
Now that CMSSW_14_0_0_pre3 is available, the corresponding updates have been made:
   * https://github.com/cms-sw/cmssw/pull/43856
   * https://github.com/cms-data/DataFormats-Scouting/pull/3

**Comment by mmusich** [comment]
+hlt
   * done at https://github.com/cms-sw/cmssw/pull/43856 + https://github.com/cms-data/DataFormats-Scouting/pull/3

**Comment by makortel** [comment]
+core
