### ISSUE TITLE
About the incorrect usage given in tutorial-proxy: git config --global socks.proxy "localhost:1080"

### ISSUE THREAD

**Issue by hongyi-zhao** [cms-sw/cmssw#43777]
I noticed the following usage about git proxy setting [here](http://cms-sw.github.io/tutorial-proxy.html#how-to-connect-to-a-git-repository-using-the-git-protocol):

> git config --global socks.proxy "localhost:1080"

This usage seems to be an error and doesn't appear in the official git manual anywhere.

Regards,
Zhao

**Comment by makortel** [comment]
assign core

**Comment by makortel** [comment]
@smuzaffar Any thoughts?

@fwyzard If I'm not mistaken, you wrote the proxy tutorial originally, any thoughts?

**Comment by fwyzard** [comment]
As [the documentation](https://cms-sw.github.io/tutorial-proxy.html#how-to-connect-to-a-git-repository-using-the-git-protocol) says, `git-proxy` is something specific to CMS:

> If the remote has a format like
> ```
> git://github.com/cms-sw/cmssw.git
> ```
> then you are connecting to the git server using the [GIT protocol](https://cms-sw.github.io/git-scm.com/book/en/Git-on-the-Server-The-Protocols#The-Git-Protocol).
> 
> In this case, it is possible to use a helper command to connect through any kind of proxy. A simple script is included with CMSSW, to connect through a SOCKS5 proxy: `git-proxy`. You can configure git to use it with
> ```
> git config --global core.gitproxy "git-proxy"
> git config --global socks.proxy "localhost:1080"
> ```
> For more information, see `git-proxy --help`.

That said, it looks like `git-proxy` is present in the [cms-git-tools repository](https://github.com/cms-sw/cms-git-tools), but is not included in the CMSSW installations:
```
$ ls -1 /cvmfs/cms.cern.ch/common/git*
/cvmfs/cms.cern.ch/common/git-cms-addpkg
/cvmfs/cms.cern.ch/common/git-cms-checkdeps
/cvmfs/cms.cern.ch/common/git-cms-checkout-topic
/cvmfs/cms.cern.ch/common/git-cms-cherry-pick-pr
/cvmfs/cms.cern.ch/common/git-cms-cvs-history
/cvmfs/cms.cern.ch/common/git-cms-fetch-pr
/cvmfs/cms.cern.ch/common/git-cms-import-tagset
/cvmfs/cms.cern.ch/common/git-cms-init
/cvmfs/cms.cern.ch/common/git-cms-merge-topic
/cvmfs/cms.cern.ch/common/git-cms-rebase-topic
/cvmfs/cms.cern.ch/common/git-cms-remote
/cvmfs/cms.cern.ch/common/git-cms-rmpkg
/cvmfs/cms.cern.ch/common/git-cms-show-pr
/cvmfs/cms.cern.ch/common/git-cms-showtags
/cvmfs/cms.cern.ch/common/git-cms-sparse-checkout
/cvmfs/cms.cern.ch/common/git-cms-squash-topic
```

By now everybody uses either the `https` method (_e.g._ `https://github.com/cms-sw/cmssw.git`) or the `ssh` method (_e.g._ `git@github.com:cms-sw/cmssw.git`).

In fact, I don't think GitHub supports the old `git` protocol (_e.g._ `git://github.com/cms-sw/cmssw.git`) any more.

**Comment by hongyi-zhao** [comment]
@fwyzard

Got it. Thank you very much for your reply.
 
>That said, it looks like git-proxy is present in the [cms-git-tools repository](https://github.com/cms-sw/cms-git-tools)

The script is located [here](https://github.com/cms-sw/cms-git-tools/blob/master/git-proxy).

The `socks.proxy` is a customized git option used by the above script.

**Comment by smuzaffar** [comment]
though this tool is part of cms-got-tools but we only deploy [git-cms-* scripts](https://github.com/cms-sw/cmsdist/blob/IB/CMSSW_14_0_X/master/cms-git-tools.spec#L22) thatis why `git-proxy` is not available in cms env. If `git-proxy` is needed then we should rename it to `git-cms-proxy`
