### ISSUE TITLE
unhelpful assertion failure reading new files with older releases

### ISSUE THREAD

**Issue by dan131riley** [cms-sw/cmssw#43807]
From (this cmstalk thread)[https://cms-talk.web.cern.ch/t/crab-fails-on-the-pre-jobs-0-1-2-3-4-5/33675/2], user attempts to open a 13_3_0 output file with an older release, which fails with
```
/mnt/data1/dsr/tmp/CMSSW_12_6_4/src/FWCore/ParameterSet/src/Entry.cc:394: void edm::Entry::validate() const: Assertion `"Invalid type code" == nullptr' failed.
```
It's failing on 'Z' encoded strings from #42742.  This should be more informative--at the very least the "should never happen" assertion should be changed to throw a format incompatibility.

**Comment by makortel** [comment]
assign core

**Comment by makortel** [comment]
This was addressed in 

- 14_1_X (for the future) https://github.com/cms-sw/cmssw/pull/43894
- 13_2_X https://github.com/cms-sw/cmssw/pull/43896
- 13_1_X https://github.com/cms-sw/cmssw/pull/43897
- 13_0_X https://github.com/cms-sw/cmssw/pull/43898
- 12_6_X https://github.com/cms-sw/cmssw/pull/43895
- 12_4_X https://github.com/cms-sw/cmssw/pull/43899
- 10_6_X https://github.com/cms-sw/cmssw/pull/43902

**Comment by makortel** [comment]
+core

**Comment by makortel** [comment]
@cmsbuild, please close
