### ISSUE TITLE
Squashing Pull requests and preserving signatures

### ISSUE THREAD

**Issue by smuzaffar** [cms-sw/cmssw#43845]
Hi @cms-sw/all-l2 ,
   On Monday 5th Feb, we are going to merge https://github.com/cms-sw/cms-bot/pull/2144 which allows `cms-bot` to recognize squashed pull requests without resetting the L2's signatures. This change allow us to

- Not reset L2's signatures as long as the changes proposed by a force update are identical to changes before the force push. This includes
  - squashing multiple commits (`c1, c2, c3, ..., cn`) in to one (or more) new commit(s) (`cx`)
  - force pushing a different set of commits which have overall identical changes

- Reset L2's signatures if commit(s) dated earlier than the L2's signature are added to PR. This could happen when a user created two sets of changes e.g. branch `B1` with commits `c1,c2` and branch `B2` with commits `c1, c2, c3` and then opened a PR using branch `B1` which is then signed `Sn` by L2 and then user pushed `B2` to `B1`. Currently bot does not reset the signatures as timestamp of commits `c3` is earlier than `Sn` but with cms-sw/cms-bot#2144 bot should be able to catch such changes and properly reset signatures.

- Warn user about large number of commits in a PR. As Github API only allows us to process max of 250 commits, so in order to avoid  missing any changes
  - bot will issue a soft warning if PR's commit count is over `150` and will not process such PRs. If a L2 thinks that it is worth to have over `150` commits in PR then he/she can add `+commit-count` comment to override this.
  - bot will issue a hard warning if PR's commit count is over `240` and will not process such PRs unless some of the commits are squashed.

Note that squashing PR commits creates a new commit so the Pull request's status checks will be reset. But bot will automatically re-run code-checks and PR tests (if any L2 has already signed the changes before the squash).

Please let us know if you have any questions/concerns/suggestions

Squashing CMSSW PRs was discussed in detail [here](https://github.com/cms-sw/cms-bot/issues/2080)

**Comment by makortel** [comment]
type documentation

**Comment by smuzaffar** [comment]
closing this issue. This was just for info/doc

**Comment by smuzaffar** [comment]
> The changes were not identical: [before](https://github.com/cms-sw/cmssw/compare/87f3f24501aefe75d4e0be6f3f624e890b8a621d...1532a8d5e88477a1613d8a063962aaa08b0f9f05#diff-5ada35958f5fceb1401a6c598a97452b0cee26cca7cd4612e2fa0dea23d7b575) and [after](https://github.com/cms-sw/cmssw/compare/87f3f24501aefe75d4e0be6f3f624e890b8a621d...4c8434cf1594cdc109b4b5c5cd78eefece651d29#diff-5ada35958f5fceb1401a6c598a97452b0cee26cca7cd4612e2fa0dea23d7b575) squash.

@iarspider , although changes are not identical but the only diff is really in one file [a]
```
-8c18a4340e6c85ae07498580ed962960d6cb36fc DataFormats/TestObjects/src/classes_def.xml
+c963193dd8ada6978233fd71c07897ace79a0e77 DataFormats/TestObjects/src/classes_def.xml
```

I guess we can improve the logic and assume that commits are squashed and new state only has the changed file ?

**Comment by smuzaffar** [comment]
thanks to @iarspider , https://github.com/cms-sw/cms-bot/pull/2403 change should now properly reset signatures for only those files which changed with respect to previous changes
