### ISSUE TITLE
Create repository Geometry/HGCalMapping in cms-data

### ISSUE THREAD

**Issue by pfs** [cms-sw/cmssw#43851]
Following the recommendations of #43751 we would like to kindly request the creation of this repository to hold files which will be used to fill the information on the electronics mapping for HGCAL.

The files will be the following https://github.com/CMS-HGCAL/cmssw/tree/hgcalelectronicsmapping_CMSSW_14_0_0_pre2/Geometry/HGCalMapping/data

Many thanks,
@pfs @kerstinlovisa

**Comment by srimanob** [comment]
+Upgrade

**Comment by civanch** [comment]
+1

**Comment by smuzaffar** [comment]
@iarspider , any idea why bot reset the `upgrade` label here?
