### ISSUE TITLE
Read errors in opening ROOT 6.30 files in earlier ROOT versions

### ISSUE THREAD

**Issue by makortel** [cms-sw/cmssw#43882]
It turned out that files written in ROOT 6.30 (or later) are not readable in earlier ROOT versions "out of the box". The problem has been fixed for ROOT 6.28 in https://github.com/root-project/root/pull/12845 . The error is along
```
      [d] Fatal Root Error: @SUB=TList::Clear
A list is accessing an object (0x154e2060ea40) already deleted (list name = TList)
```

This issue is for us to track what ROOT fixes we need to backport to which CMSSW release cycles.

The problem was observed e.g. in https://github.com/cms-sw/cmssw/pull/43827#issuecomment-1930210666

**Comment by makortel** [comment]
assign core

**Comment by makortel** [comment]
type root

**Comment by makortel** [comment]
For the purpose of potentially running the HLT step in a future Run 3 Ultra Legacy MC production in a similar way as in Run 2 Ultra Legacy production, we'd need the ROOT fix backported down to 12_4_X, which used ROOT 6.24.

If the "reading newer files with older ROOTs" would be needed for something else, we might have backport to even earlier releases.

FYI @cms-sw/upgrade-l2

**Comment by srimanob** [comment]
Thanks @makortel for following up on this.

I see on the ROOT PR that you ask if there will be a backport down to 6.24.

**Comment by makortel** [comment]
@smuzaffar According to Philippe the fix has been backported down to 6.14, but not tagged yet in all release series. Do you want to wait for the tags, or could we update ROOT already now in all release cycles down to CMSSW_12_4_X?

**Comment by smuzaffar** [comment]
@makortel , we do not need root tag but for CMSSW 12.4.X we are using root 6.24 and [these](https://github.com/root-project/root/compare/3c21b04...v6-24-00-patches) which root has on top of what we are using in 12.4.X. Do you think it is save to get all these root updates in 12.4? I prefer to just cherry pick the fix on top of cms root branch

**Comment by smuzaffar** [comment]
https://github.com/root-project/root/compare/5858905487...v6-26-00-patches are the root 6.26-patches branch (used in CMSSW 13 release cycle) changes

**Comment by makortel** [comment]
> we do not need root tag but for CMSSW 12.4.X we are using root 6.24 and [these](https://github.com/root-project/root/compare/3c21b04...v6-24-00-patches) are the changes which root has on top of what we are using in 12.4.X. Do you think it is safe to get all these root updates in 12.4? I prefer to just cherry pick the fix on top of cms root branch

On a quick look the list of commits looked like there were some fixes that sounded useful, and some that could warrant more thorough testing for a "closed" release cycle. I'd be fine with just cherry-picking the fix.

One commit that caught my eye was from https://github.com/root-project/root/pull/10641 that you had asked to be backported to 6.24 https://github.com/root-project/root/pull/10576#issuecomment-1135541775 :)

**Comment by makortel** [comment]
The ROOT has been updated with
* https://github.com/cms-sw/cmsdist/pull/9020
* https://github.com/cms-sw/cmsdist/pull/9019
* https://github.com/cms-sw/cmsdist/pull/9018
* https://github.com/cms-sw/cmsdist/pull/9017
* https://github.com/cms-sw/cmsdist/pull/9009
* https://github.com/cms-sw/cmsdist/pull/9007

**Comment by makortel** [comment]
+core
