### ISSUE TITLE
Do we use PROOF?

### ISSUE THREAD

**Issue by iarspider** [cms-sw/cmssw#43975]
In https://github.com/root-project/root/pull/14513, PROOF was made optional (off by default), causing test failures when testing new ROOT master version: [link](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-8df347/37399/unitTests/src/FWCore/TFWLiteSelector/test/TestRunnerFWCoreTFWLiteSelector/testing.log). 

However, it is only used by two tests:
[FWCore/TFWLiteSelector/test/proof_thing_sel.C](https://github.com/cms-sw/cmssw/blob/master/FWCore/TFWLiteSelector/test/proof_thing_sel.C) and [FWCore/TFWLiteSelector/test/proof_thing2_sel.C](https://github.com/cms-sw/cmssw/blob/master/FWCore/TFWLiteSelector/test/proof_thing2_sel.C).

Should we explicitly enable PROOF, or should we drop these two tests?

**Comment by iarspider** [comment]
assign core

**Comment by iarspider** [comment]
type root

**Comment by Dr15Jones** [comment]
I'm OK with dropping PROOF support. I don't know of anyone who ever used our extra code built on top of PROOF.

**Comment by dan131riley** [comment]
I agree with dropping it, I think PROOF has been passed by in favor of other developments.

**Comment by makortel** [comment]
I'm fine with dropping it, but maybe we should announce it somewhere?

**Comment by smuzaffar** [comment]
> I'm fine with dropping it, but maybe we should announce it somewhere? (just to make sure)

agree. Is announcing it on [SW development forum](https://cms-talk.web.cern.ch/c/offcomp/coresw/swdev/215) enough?

**Comment by makortel** [comment]
> > I'm fine with dropping it, but maybe we should announce it somewhere? (just to make sure)
> 
> agree. Is announcing it on [SW development forum](https://cms-talk.web.cern.ch/c/offcomp/coresw/swdev/215) enough?

We could hope so :) (i.e. I don't have a better forum to suggest)

**Comment by makortel** [comment]
PROOF tests were removed inhttps://github.com/cms-sw/cmssw/pull/43996

**Comment by makortel** [comment]
The removal was announced in https://cms-talk.web.cern.ch/t/removal-of-roots-proof-in-the-future/34915

**Comment by makortel** [comment]
Do we already have a cmsdist PR that drops the PROOF from ROOT?

**Comment by makortel** [comment]
No, I think the cmsdist PR of ROOT update (where they changed the default) does the job (and follows what your announcement message). I just wanted to record the cmsdist PR here.

**Comment by makortel** [comment]
+core

**Comment by makortel** [comment]
@cmsbuild, please close
