### ISSUE TITLE
missing cvs-history for EgammaAnalysis/ElectronTools

### ISSUE THREAD

**Issue by ikrav** [cms-sw/cmssw#4398]
Dear experts,

The old CVS tags for the CMSSW package EgammaAnalysis/ElectronTools 
appear missing in GitHub. We need those tags for several recipes Egamma 
recipes that people are still using to analyze 8 TeV data. 

The problem can be seen by running:

git cms-cvs-history tags EgammaAnalysis/ElectronTools

which results in the following messages:
>
>Enter passphrase for key '/afs/cern.ch/user/i/ikrav/.ssh/id_rsa':
>Enter passphrase for key '/afs/cern.ch/user/i/ikrav/.ssh/id_rsa':
>Could not fetch info for package package EgammaAnalysis-ElectronTools.
>ERROR: Repository not found.
>fatal: Could not read from remote repository.
>
>Please make sure you have the correct access rights
>and the repository exists.
>ERROR: Repository not found.
>fatal: Could not read from remote repository.
>
>Please make sure you have the correct access rights
>and the repository exists.

Specifically, we need at least the tags V00-00-08 and V00-00-09, but better all of them from the old CVS. Naturally, the attempt to check out one of these tags fails, and with the same error. The command attempted was:

git cms-cvs-history import V00-00-09 EgammaAnalysis/ElectronTools

Can this be fixed? I expect this should be possible given that the old CVS is still around with read-only access, so all the tags info should be available.

Thank you,
Ilya

**Comment by degano** [comment]
@ikrav Has this been fixed elsewhere? If so can I close this issue?

**Comment by ridhichawla** [comment]
Hi,

I think this has been fixed (it was long time back). You can close the issue.

Thank you
Ridhi
________________________________

**Comment by ikrav** [comment]
Yes, I think this is long in the past now.

Ilya

**Comment by davidlt** [comment]
Closing as issues is now fixed.
