### ISSUE TITLE
Can we build CMSSW_14_0_0_MUTIARCHS ?

### ISSUE THREAD

**Issue by fwyzard** [cms-sw/cmssw#44010]
Hi,
would it be possible to build the "multiarchs" variant of CMSSW 14.0.0 ?

.A

**Comment by fwyzard** [comment]
assign core

**Comment by fwyzard** [comment]
@iarspider @aandvalenzuela

**Comment by fwyzard** [comment]
For a release: `CMSSW_14_0_0_MULTIARCHS` .

**Comment by iarspider** [comment]
@fwyzard I can try ...

**Comment by iarspider** [comment]
@fwyzard nope, only ORPs ( @sextonkennedy, @rappoccio, @antoniovilela) can trigger release build. The parameters in #44011 should, as far as I understand, work.

**Comment by antoniovilela** [comment]
Are the settings correct here:
https://github.com/cms-sw/cmssw/issues/44012

**Comment by antoniovilela** [comment]
The builds are now uploaded:
https://github.com/cms-sw/cmssw/issues/44012

**Comment by fwyzard** [comment]
Thanks !
