### ISSUE TITLE
coverage of 2024 wfs in runTheMatrix, PR tests, IBs

### ISSUE THREAD

**Issue by Martin-Grunewald** [cms-sw/cmssw#44028]
Same as https://github.com/cms-sw/cmssw/issues/41410 but for 2024!
Affects 14_0 and 14_1.

**Comment by Martin-Grunewald** [comment]
In 14_0/14_1 we need to finally remove the 2023 frozen menu (relval2023 => 2023v12) and replace it by Fake2, as done in previous years. In turn we'd like to have (more) relvals, also in the short matrix and IB testing, using the relval2024 2024 HLT menu.

**Comment by Martin-Grunewald** [comment]
assign pdmv

**Comment by mmusich** [comment]
urgent

**Comment by Martin-Grunewald** [comment]
@missirol FYI

**Comment by Martin-Grunewald** [comment]
@fwyzard FYI

**Comment by AdrianoDee** [comment]
See https://github.com/cms-sw/cmssw/pull/44076 and https://github.com/cms-sw/cmssw/pull/44076

**Comment by AdrianoDee** [comment]
+pdmv
solved by https://github.com/cms-sw/cmssw/pull/44075 and  https://github.com/cms-sw/cmssw/pull/44076

**Comment by makortel** [comment]
@cmsbuild, please close
