### ISSUE TITLE
`maxIterGPU` assert failure in `alpaka_serial_sync::pixelClustering::FindClus`

### ISSUE THREAD

**Issue by missirol** [cms-sw/cmssw#44077]
Running a recent HLT menu with [`customizeHLTforAlpaka`](https://github.com/cms-sw/cmssw/blob/CMSSW_14_0_0/HLTrigger/Configuration/python/customizeHLTforAlpaka.py#L895) in `CMSSW_14_0_0` as in [1] leads to a runtime error.

```
cmsRun: src/RecoLocalTracker/SiPixelClusterizer/plugins/alpaka/PixelClustering.h:302:
void alpaka_serial_sync::pixelClustering::FindClus<TrackerTraits>::operator()
(const TAcc&, SiPixelDigisSoAView, SiPixelClustersSoAView, unsigned int) const
[with TAcc = alpaka::AccCpuSerial<std::integral_constant<long unsigned int, 1>, unsigned int>;
TrackerTraits = pixelTopology::Phase1;
SiPixelDigisSoAView = SiPixelDigisLayout<>::ViewTemplateFreeParams<128, false, true, false>;
SiPixelClustersSoAView = SiPixelClustersLayout<>::ViewTemplateFreeParams<128, false, true, false>]:
Assertion `(hist.size() / blockDimension) < maxIterGPU' failed.
```

The full stack trace from running [1] can be found in [pixel_findclus_cpu.log](https://github.com/cms-sw/cmssw/files/14395628/pixel_findclus_cpu.log). Note that [1] forces the job to run on CPU only.

A similar crash occurs also on GPU (stack track in [pixel_findclus_gpu.log](https://github.com/cms-sw/cmssw/files/14395629/pixel_findclus_gpu.log)), but a GPU is not needed to reproduce the issue.

There is no runtime error if the Alpaka customisation is not used.

Could experts please have a look ?

FYI: @AdrianoDee @borzari @fwyzard @cms-sw/hlt-l2

[1]
```bash
#!/bin/bash

# CMSSW_14_0_0

hltGetConfiguration \
  /dev/CMSSW_14_0_0/GRun/V33 \
  --globaltag 140X_dataRun3_HLT_v1 \
  --max-events -1 \
  --input foo.root \
  --no-output \
  --no-prescale \
  --customise HLTrigger/Configuration/customizeHLTforAlpaka.customizeHLTforAlpaka \
  > hlt.py

cat <<@EOF >> hlt.py

del process.MessageLogger
process.load('FWCore.MessageLogger.MessageLogger_cfi')

process.options.numberOfThreads = 1
process.options.numberOfStreams = 0

process.source.fileNames = [
    '/store/data/Run2023D/EphemeralHLTPhysics0/RAW/v1/000/370/293/00000/303b0104-65f3-4518-8b32-8de062eb9713.root',
]

process.options.accelerators = ['cpu']

process.source.skipEvents = cms.untracked.uint32(109)
@EOF

edmConfigDump hlt.py > hlt_dump.py

cmsRun hlt.py &> hlt.log
```

PS. Just for my own reference, I encountered this crash while testing a recent HLT menu in 14_0_X on one of the HiLTON nodes as described [here](https://codimd.web.cern.ch/3BPGMDcwSN6kS8FNStBzPA).

**Comment by mmusich** [comment]
assign heterogeneous, reconstruction, hlt

@cms-sw/trk-dpg-l2 FYI

**Comment by fwyzard** [comment]
The assertion fails because in `RecoLocalTracker/SiPixelClusterizer/plugins/alpaka/PixelClustering.h` we end up with
```
hist.size(): 4529
block elements: 256
```
that require 17 iterations, while `maxIterGPU` is 16... so `17 < 16` fails.

In the CUDA version the block size is 384 (to accommodate for `TrackerTraits::maxPixInModule` which is 6000, divided by 16 and round up by 128).
In the alpaka version the block size is 256 (which seems arbitrary).

**Comment by fwyzard** [comment]
Should be fixed by #44081 and #44082.

**Comment by mmusich** [comment]
+hlt

explicitly tested with:

```console
cmsrel CMSSW_14_0_0
cd CMSSW_14_0_0/src/
git cms-merge-topic 44082
scram b -j 20
```

and then following the recipe at https://github.com/cms-sw/cmssw/issues/44077#issue-2152647187

**Comment by fwyzard** [comment]
+heterogeneous
