### ISSUE TITLE
Alpaka package fails to compile for ROCm when it has only .dev.cc files

### ISSUE THREAD

**Issue by makortel** [cms-sw/cmssw#44506]
From https://mattermost.web.cern.ch/cms-o-and-c/pl/5dncb3ojnfgyxdd93113z6bsdw

A package with
```
`-- HeterogeneousCore
    `-- AlpakaTest
        |-- BuildFile.xml
        |-- interface
        |   `-- alpaka
        |       |-- AlpakaESTestData.h
        |       `-- TestAlgo.h
        `-- src
            `-- alpaka
                `-- TestAlgo.dev.cc
```
fails to compile `HeterogeneousCore/AlpakaTest/src/alpaka/TestAlgo.dev.cc` for ROCm backend
```
Unknow target tmp/el8_amd64_gcc12/src/HeterogeneousCore/AlpakaTest/src/alpaka/HeterogeneousCoreAlpakaTestROCmAsync/TestAlgo.dev.cc.o
```

**Comment by makortel** [comment]
assign core, heterogeneous

**Comment by ariostas** [comment]
Just to add a bit more context (since I think the title is a bit misleading), the issue happens when building a library with any `.dev.cc` files. Currently, the Alpaka libraries that are built only compile `.cc` files, which is why this issue hasn't come up before.

**Comment by makortel** [comment]
> Just to add a bit more context (since I think the title is a bit misleading), the issue happens when building a library with any `.dev.cc` files. Currently, the Alpaka libraries that are built only compile `.cc` files, which is why this issue hasn't come up before.

Thanks, I updated the title.

**Comment by makortel** [comment]
+1

**Comment by fwyzard** [comment]
@smuzaffar, do you know if this fix entered CMSSW_14_1_0_pre2 or only afterwards ?

**Comment by smuzaffar** [comment]
@fwyzard 
CMSSW_14_1_0_pre2:  No, fix was merged after pre2
CMSSW_14_0_4 : Yes, fix is part of this release

**Comment by fwyzard** [comment]
OK, thanks.
