### ISSUE TITLE
HLT Validation of `x86-64-v3`

### ISSUE THREAD

**Issue by missirol** [cms-sw/cmssw#44550]
In 2024, HLT would like to run online using the `x86-64-v3` micro-architecture level in CMSSW (see https://github.com/cms-sw/cmssw/issues/43652, [PDMVRELVALS-230](https://its.cern.ch/jira/browse/PDMVRELVALS-230) for more info). This is expected to bring an increase of 2.5% in the Run-3 HLT throughput, which is significant (see measurements by @fwyzard [here](https://docs.google.com/document/d/12yKjVVQD4B0TDE3XXV0gxDjV_eUTCZVGBsX67RgyO6c/edit#heading=h.y76sukte4rlo)).

The validation of this technical change is in progress. It is based on `CMSSW_14_0_0_pre3`.
 - Reference = `CMSSW_14_0_0_pre3`.
 - Target = `CMSSW_14_0_0_pre3_MULTIARCHS` (for target, one has to make sure that the machine in use supports `x86-64-v3`).

The POGs (and some PAGs) filed their validation reports, and they gave their greenlight ([link](https://cms-talk.web.cern.ch/t/valdb-14-0-0-pre3-multiarchs-run3-campaign-notification/36215)).

TSG/STEAM (@sanuvarghese) compared HLT rates on 2023 data for `CMSSW_14_0_0_pre3` vs `CMSSW_14_0_0_pre3_MULTIARCHS` ([link](https://docs.google.com/spreadsheets/d/1AL-wGMngWMw2PcSQa5OWEVKSSmuuG9Jc5pEK3ocDAm8/edit?pli=1#gid=1281305241)), and found differences below 1% for most triggers, but several cases where differences in trigger decisions (considering also intermediate filters) exceeded 1%. This triggered further checks, which are being discussed in [CMSHLT-3124](https://its.cern.ch/jira/browse/CMSHLT-3124) (worth reading, currently not long).

It was noticed that triggers using GSF tracks are amongst the ones showing the larger changes in trigger decisions (order of a few %). Some checks on a handful of events showed clear and reproducible differences in GSF tracks between `CMSSW_14_0_0_pre3` vs `CMSSW_14_0_0_pre3_MULTIARCHS`. One reproducer showing differences for GSF tracks can be found in [CMSHLT-3124 (comment)](https://its.cern.ch/jira/browse/CMSHLT-3124?focusedId=6322019&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-6322019).

I'm opening this issue to try and get more feedback from sw and reco experts. Two generic questions below.
 - Are these discrepancies something which is reasonable to expect, or has been seen before, with this kind of update ?
 - Are there any suggestions on software changes that could reduce these differences ?

Attn: @cms-sw/egamma-pog-l2 @cms-sw/tracking-pog-l2
FYI: @cms-sw/hlt-l2 @goys @silviodonato

**Comment by makortel** [comment]
assign hlt, reconstruction

**Comment by mmusich** [comment]
type egamma, tracking

**Comment by slava77** [comment]
I'm guessing that similar to the intel-vs-AMD case in [cms-sw/cmssw#40089](https://github.com/cms-sw/cmssw/issues/40089) and related [cms-sw/cmsdist#8280](https://github.com/cms-sw/cmsdist/pull/8280) there will be a connection to compilation flags especially in the fast-math related subset.

It would be nice if @cms-sw/core-l2 could provide some accounting between SSE3 and other GCC defaults compared to what it implies for x86-64-v3.

 @missirol @sanuvarghese please clarify if the tests you made were done on the same hardware (what kind of hardware was it?)

**Comment by missirol** [comment]
> please clarify if the tests you made were done on the same hardware (what kind of hardware was it?)

Yes, I tested the reproducer in [CMSHLT-3124 (comment)](https://its.cern.ch/jira/browse/CMSHLT-3124?focusedId=6322019&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-6322019) on `lxplus806` (running with `14_0_0_pre3` and `14_0_0_pre3_MULTIARCHS` on that same machine), and with this I see a difference in the trigger results of `HLT_Ele30_WPTight_Gsf_v*` between the two releases.
```bash
[lxplus806] > lscpu 
Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
CPU(s):              10
On-line CPU(s) list: 0-9
Thread(s) per core:  1
Core(s) per socket:  1
Socket(s):           10
NUMA node(s):        1
Vendor ID:           GenuineIntel
CPU family:          6
Model:               85
Model name:          Intel Xeon Processor (Cascadelake)
Stepping:            6
CPU MHz:             2095.076
BogoMIPS:            4190.15
Virtualization:      VT-x
Hypervisor vendor:   KVM
Virtualization type: full
L1d cache:           32K
L1i cache:           32K
L2 cache:            4096K
L3 cache:            16384K
NUMA node0 CPU(s):   0-9
Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl xtopology cpuid tsc_known_freq pni pclmulqdq vmx ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch cpuid_fault invpcid_single ssbd ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid avx512f avx512dq rdseed adx smap clflushopt clwb avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 arat pku ospke avx512_vnni md_clear arch_capabilities
```

**Comment by fwyzard** [comment]
> It would be nice if @cms-sw/core-l2 could provide some accounting between SSE3 and other GCC defaults compared to what it implies for x86-64-v3.

By memory, the only difference in GCC flags is replacing `-msse3` with `-march=x86-64-v3` .

This enables instructions like SSE4.2, AVX, AVX2 and FMA.

**Comment by VinInn** [comment]
and the only reasonable reason is FMA.
If is FMA one cannot state that one is correct and the other wrong: they are two different approximations.

**Comment by VinInn** [comment]
An easy messy test is to copy the "standard" libraries for GSF.... into the x86-64-v3 directory and see if the difference fades away.

**Comment by VinInn** [comment]
a bit of Frankenstein :
cmsrel CMSSW_14_0_0_pre3_MULTIARCHS
cd CMSSW_14_0_0_pre3_MULTIARCHS/
cmsenv
git cms-addpkg TrackingTools/GsfTracking
scram b clean
 scram b -j 8
 edmPluginRefresh
 edmPluginDump -f | grep innnocent
 cd ../lib/el8_amd64_gcc12/
"#copy see lib in avx2 dir...."
cp * scram_x86-64-v3/.
 
and then the comparison shows no difference

**Comment by makortel** [comment]
> > It would be nice if @cms-sw/core-l2 could provide some accounting between SSE3 and other GCC defaults compared to what it implies for x86-64-v3.
> 
> By memory, the only difference in GCC flags is replacing `-msse3` with `-march=x86-64-v3` .

@smuzaffar Probably more for future reference, where exactly are these specified? (I tried to look a little bit, but didn't find)

I'd argue FMA leading to ~3x difference in momentum is an indication of the algorithm(s) being (very) unstable. In a way the AMD vs Intel difference https://github.com/cms-sw/cmssw/issues/40089 was also a sign of such instabilities, but there the problem was removed by disabling the particular optimization. I guess in this case disabling the FMA would defeat the purpose though. In principle specific options such as `-ffp-contract=off` (e.g. https://stackoverflow.com/questions/42132260/generic-way-of-handling-fused-multiply-add-floating-point-inaccuracies and links therein) could be tested, but I'm not sure if that would really be worth of the effort.

**Comment by VinInn** [comment]
``` -ffp-contract=off```  will de-facto remove FMA defeating the purpose of the upgrade to AVX2.
(it would require to manually introduce calls to "fma" everywhere is deemed useful).

GSF is unstable indeed in some corner of the phase space in particular for fake electrons and it is not proved at all that the more inaccurate answer is the one with FMA...

**Comment by VinInn** [comment]
btw I tested it on ARM that generates fma instructions (checked with objdump) and at least for that event it reproduces the trigger results of SSE not AVX2.
We can check in all three cases the details of the GSF reconstruction

**Comment by VinInn** [comment]
TO BE FULLY VERIFIED!!!!

```
[innocent@patatrack01 src]$ git diff
diff --git a/DataFormats/Math/interface/SIMDVec.h b/DataFormats/Math/interface/SIMDVec.h
index e4c52cc301d..d2abc01b306 100644
--- a/DataFormats/Math/interface/SIMDVec.h
+++ b/DataFormats/Math/interface/SIMDVec.h
@@ -3,12 +3,8 @@

 #if (defined(__CLING__) || defined(__MIC__) || defined(__NVCC__)) || (__BIGGEST_ALIGNMENT__ < 16)
 #elif defined(__GNUC__) || defined(__clang__) || defined(__INTEL_COMPILER)
-#if defined(__x86_64__) && defined(__SSE__)
-#define USE_SSEVECT
-#else
 #define USE_EXTVECT
 #endif
-#endif

 // to be moved elsewhere
 namespace mathSSE {
```
remove the difference between x86-64-v3 and sse3

1) contraction is different
2) there is a bug in the AVX2 implementation of the mathSSE

Do not remember why we kept the SSE/AVX2 implementation when the EXT one was introduced and validated

**Comment by smuzaffar** [comment]
> > > It would be nice if @cms-sw/core-l2 could provide some accounting between SSE3 and other GCC defaults compared to what it implies for x86-64-v3.
> > 
> > By memory, the only difference in GCC flags is replacing `-msse3` with `-march=x86-64-v3` .
> 
> @smuzaffar Probably more for future reference, where exactly are these specified? (I tried to look a little bit, but didn't find)

@makortel , these flags are defined in [cmsdist](https://github.com/cms-sw/cmsdist/blob/IB/CMSSW_14_1_X/master/vectorization/cmsdist_packages.py) . Default vectorization flag is [sse3](https://github.com/cms-sw/cmsdist/blob/IB/CMSSW_14_1_X/master/vectorization/cmsdist_packages.py#L5) and then for selected packages it is [replaced by the correct vectorization](https://github.com/cms-sw/cmsdist/blob/IB/CMSSW_14_1_X/master/vectorization/cmsdist_packages.py#L60-L65) flags

**Comment by VinInn** [comment]
I run on all 23 events on ARM as well and it is different from all x86_64 versions I tested above.

**Comment by VinInn** [comment]
So, incredibly only after few hours of work I manage to make GSF working with SMatrix using __f128
https://github.com/cms-sw/cmssw/compare/master...VinInn:cmssw:GSF128?expand=1
(had also to patch root to allow type conversion in SMatrix an SVector)

for the 28 events above the results comparing see, avx2 and f128 are:
```
[innocent@patatrack01 hlt]$ hltDiff -o see.root -n avx.root
Found 23 matching events, out of which 19 have different HLT results
      Events    Accepted      Gained        Lost       Other  Trigger
          23          16          +7         -12           -  HLT_Ele30_WPTight_Gsf_v8
[innocent@patatrack01 hlt]$ hltDiff -o see.root -n f128.root
Found 23 matching events, out of which 18 have different HLT results
          23          16          +7         -11           -  HLT_Ele30_WPTight_Gsf_v8
[innocent@patatrack01 hlt]$ hltDiff -o avx.root -n f128.root
Found 23 matching events, out of which 1 have different HLT results
      Events    Accepted      Gained        Lost       Other  Trigger
          23          11          +1           -           -  HLT_Ele30_WPTight_Gsf_v8
```

under the assumption that f128 produces th most accurate results, my conclusion is that AVX2 (aka FMA) is more accurate than SSE.
(some more unit tests can be made for some specific matrices)

**Comment by VinInn** [comment]
Before anybody asks:
f128 is not an option for production:
this is the timing
```
[innocent@patatrack01 hlt]$ grep hltEgammaGsfTracks *ori.log | grep Time
hlt8AVXori.log:TimeReport   0.008999     0.008999  hltEgammaGsfTracks
hlt8SSEori.log:TimeReport   0.010413     0.010413  hltEgammaGsfTracks
hlt8f128.log:TimeReport   0.385862     0.385862  hltEgammaGsfTracks
```
yes 40 times slower

**Comment by mmusich** [comment]
+hlt
   * deployed online via `CMSSW_14_0_6_MULTIARCHS` (intermediate patches were not used online) together with HLT menu GRun 2024 V1.1. The first stable-beams run `CMSSW_14_0_6_MULTIARCHS`, using the "v1.1.X" HLT menu (see [CMSHLT-3164](https://its.cern.ch/jira/browse/CMSHLT-3164)), was [run-380306](https://cmsoms.cern.ch/cms/runs/report?cms_run=380306&cms_run_sequence=GLOBAL-RUN) (Run2024D). No issues were spotted.
   * An executive summary of the deployment history after validation can be found in https://its.cern.ch/jira/browse/CMSHLT-3170.

**Comment by jfernan2** [comment]
+1

**Comment by makortel** [comment]
@cmsbuild, please close
