### ISSUE TITLE
Error from `TExMap::Remove()` in DQMIO merge job in Tier0

### ISSUE THREAD

**Issue by makortel** [cms-sw/cmssw#44559]
https://cms-talk.web.cern.ch/t/paused-prompt-job-for-cosmics-run378374-with-fatalrooterror/37731 reports a DQMIO merge job (that reads one DQMIO file and writes another DQMIO file) failed with
```
----- Begin Fatal Exception 27-Mar-2024 03:51:36 CET-----------------------
An exception of category 'FatalRootError' occurred while
   [0] Calling InputSource::readRun_
   [1] failed while reading PixelPhase1/Phase1_MechanicalView/PXForward/HalfCylinder_mO/PXRing_1/PXDisk_-1/num_digis_per_PXPanel_SignedBlade_-4
   Additional Info:
      [a] Fatal Root Error: @SUB=TExMap::Remove
key 16777216 not found at 7495

----- End Fatal Exception -------------------------------------------------
```
The Source in question is `DQMRootSource`.

**Comment by makortel** [comment]
assign dqm

**Comment by makortel** [comment]
type root

**Comment by makortel** [comment]
@pcanal Any thoughts what could be going on here?

**Comment by Dr15Jones** [comment]
@makortel My guess is it is a corrupted input file. Would be good to know if reading the same file repeats the same problem.

**Comment by pcanal** [comment]
It would also be my guess that it is a corrupted file.

**Comment by makortel** [comment]
Repeating the job few times reproduces the failure every time.

**Comment by makortel** [comment]
@pcanal Is there any other check that could confirm the file to be corrupt?

**Comment by pcanal** [comment]
One could simply attempt to read the input file in bare ROOT (and iterate through the entries).  Alternatively one could try to skip the basket/entries that lead to the crash.

**Comment by makortel** [comment]
```
root [4] for (int i=0; i<TProfiles->GetEntries(); ++i) { TProfiles->GetEntry(i); }
Error in <TExMap::Remove>: key 16777216 not found at 7495
Warning in <TBufferFile::CheckObject>: reference to object of unavailable class THashList, offset=16777216 pointer will be 0
Error in <TBufferFile::CheckByteCount>: object of class TAxis read too many bytes: 195 instead of 115
Warning in <TBufferFile::CheckByteCount>: TAxis::Streamer() not in sync with data on file 58A98977-DC81-4CEC-B91C-C7C509BC1530.root, fix Streamer()
```

**Comment by pcanal** [comment]
Still looks corrupted.  The last check is to see which version of ROOT was used to write the file `file->GetVersion()` and try to read it with that version.

**Comment by makortel** [comment]
> Still looks corrupted. The last check is to see which version of ROOT was used to write the file `file->GetVersion()` and try to read it with that version.

I should be reading the file with the same binary as it was written (`_file0->GetVersion()` gives `63003`, and the version of my interactive ROOT is `6.30/03`).

**Comment by pcanal** [comment]
Ok.  Then it is a on-disk file corruption (and/or the file was written wrong).

**Comment by makortel** [comment]
Thanks, we can close the issue then.
