### ISSUE TITLE
[GCC13] Missing intrinsics 2

### ISSUE THREAD

**Issue by iarspider** [cms-sw/cmssw#44645]
When [testing](https://github.com/cms-sw/cmssw/pull/44632) fixes for gcc13, two more cases of `identifier "__builtin_ia32_cmpccxadd" is undefined` were detected:

```
>> Compiling alpaka/cuda src/RecoParticleFlow/PFClusterProducer/plugins/alpaka/PFClusterSoAProducerKernel.dev.cc
/cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02831/el9_amd64_gcc13/external/gcc/13.2.0-1b0a3367d04f48f01ad3ccf40e55475c/lib/gcc/x86_64-redhat-linux-gnu/13.2.0/include/cmpccxaddintrin.h(63): error: identifier "__builtin_ia32_cmpccxadd" is undefined
    return __builtin_ia32_cmpccxadd (__A, __B, __C, __D);
           ^

/cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02831/el9_amd64_gcc13/external/gcc/13.2.0-1b0a3367d04f48f01ad3ccf40e55475c/lib/gcc/x86_64-redhat-linux-gnu/13.2.0/include/cmpccxaddintrin.h(71): error: identifier "__builtin_ia32_cmpccxadd64" is undefined
    return __builtin_ia32_cmpccxadd64 (__A, __B, __C, __D);
           ^

2 errors detected in the compilation of "src/RecoParticleFlow/PFClusterProducer/plugins/alpaka/PFClusterSoAProducerKernel.dev.cc".
```

and

```
>> Compiling alpaka/cuda edm plugin src/RecoParticleFlow/PFRecHitProducer/plugins/alpaka/PFRecHitTopologyESProducer.cc
/cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02831/el9_amd64_gcc13/external/gcc/13.2.0-1b0a3367d04f48f01ad3ccf40e55475c/lib/gcc/x86_64-redhat-linux-gnu/13.2.0/include/cmpccxaddintrin.h(63): error: identifier "__builtin_ia32_cmpccxadd" is undefined
    return __builtin_ia32_cmpccxadd (__A, __B, __C, __D);
           ^

/cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02831/el9_amd64_gcc13/external/gcc/13.2.0-1b0a3367d04f48f01ad3ccf40e55475c/lib/gcc/x86_64-redhat-linux-gnu/13.2.0/include/cmpccxaddintrin.h(71): error: identifier "__builtin_ia32_cmpccxadd64" is undefined
    return __builtin_ia32_cmpccxadd64 (__A, __B, __C, __D);
           ^

2 errors detected in the compilation of "src/RecoParticleFlow/PFRecHitProducer/plugins/alpaka/PFRecHitProducerKernel.dev.cc".
```

Similar problem was fixed in https://github.com/cms-sw/cmssw/pull/44595 by @makortel and @dan131riley .

**Comment by iarspider** [comment]
assign heterogeneous,core

**Comment by fwyzard** [comment]
According to [the release notes](https://docs.nvidia.com/cuda/cuda-toolkit-release-notes/index.html#id3), `__builtin_ia32_cmpccxadd` and `__builtin_ia32_cmpccxadd64` should now be supported by CUDA 12.4.1 .

**Comment by fwyzard** [comment]
See https://github.com/cms-sw/cmsdist/pull/9126 .

**Comment by iarspider** [comment]
@fwyzard thanks! 

In case that doesn't fix the issue, here is include chain that leads to tbb:

```
RecoParticleFlow/PFClusterProducer/plugins/alpaka/PFClusterSoAProducerKernel.dev.cc
RecoParticleFlow/PFClusterProducer/plugins/alpaka/PFClusterSoAProducerKernel.h
RecoParticleFlow/PFRecHitProducer/interface/PFRecHitTopologyRecord.h
Geometry/Records/interface/CaloGeometryRecord.h
FWCore/Framework/interface/EventSetupRecordImplementation.h
FWCore/Framework/interface/EventSetupRecord.h
FWCore/Framework/interface/EventSetupRecordImpl.h
FWCore/Concurrency/interface/WaitingTaskHolder.h
oneapi/tbb/task_group.h
```

**Comment by fwyzard** [comment]
thanks @iarspider, we should probably try to fix the include chain anyway.

**Comment by iarspider** [comment]
> Moving
> 
> ```c++
> #include "RecoParticleFlow/PFRecHitProducer/interface/PFRecHitTopologyRecord.h"
> ```
> 
> from `RecoParticleFlow/PFClusterProducer/plugins/alpaka/PFClusterSoAProducerKernel.h` to `RecoParticleFlow/PFClusterProducer/plugins/alpaka/PFClusterSoAProducer.cc` should fix the issue.

Thanks! Could you please open a PR with this change?

**Comment by iarspider** [comment]
@fwyzard looks like there are more cases like this: [1](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-421502/38683/build-logs/RecoLocalTracker/SiStripClusterizer/log.html), [2](https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-421502/38683/build-logs/RecoParticleFlow/PFRecHitProducer/log.html)

**Comment by fwyzard** [comment]
@makortel , if we want to avoid compiling (some of) the framework headers with `nvcc`, would it make sense to add something like
```c++
#ifdef __NVCC__
#error Framework headers should not be compiled by the device compiler
#endif
```
to `FWCore/Concurrency/interface/WaitingTaskHolder.h` and similar headers ?

**Comment by iarspider** [comment]
For `RecoParticleFlow/PFRecHitProducer/plugins/alpaka/PFRecHitTopologyESProducer.cc`: [list](https://gist.github.com/iarspider/92c35157bc85cdb0be22cf2044116327) - a bit long this time, since I've traced all paths (but can also be not 10)% accurate if some includes are guarded with `#ifdef`).

**Comment by iarspider** [comment]
For `RecoLocalTracker/SiStripClusterizer/plugins/SiStripRawToClusterGPUKernel.cu`: 
```
RecoLocalTracker/SiStripClusterizer/plugins/SiStripRawToClusterGPUKernel.cu -> RecoLocalTracker/SiStripClusterizer/plugins/SiStripRawToClusterGPUKernel.h -> CalibFormats/SiStripObjects/interface/SiStripClusterizerConditionsGPU.h -> HeterogeneousCore/CUDACore/interface/ESProduct.h -> HeterogeneousCore/CUDAUtilities/interface/EventCache.h -> FWCore/Utilities/interface/ReusableObjectHolder.h -> oneapi/tbb/concurrent_queue.h
RecoLocalTracker/SiStripClusterizer/plugins/SiStripRawToClusterGPUKernel.cu -> CalibFormats/SiStripObjects/interface/SiStripClusterizerConditionsGPU.h -> HeterogeneousCore/CUDACore/interface/ESProduct.h -> HeterogeneousCore/CUDAUtilities/interface/EventCache.h -> FWCore/Utilities/interface/ReusableObjectHolder.h -> oneapi/tbb/concurrent_queue.h
```

**Comment by fwyzard** [comment]
> For `RecoParticleFlow/PFRecHitProducer/plugins/alpaka/PFRecHitTopologyESProducer.cc`: [list](https://gist.github.com/iarspider/92c35157bc85cdb0be22cf2044116327) - a bit long this time, since I've traced all paths (but can also be not 100% accurate if some includes are guarded with `#ifdef`).

`RecoParticleFlow/PFRecHitProducer/plugins/alpaka/PFRecHitTopologyESProducer.cc` should not be compiled by `nvcc`.

**Comment by fwyzard** [comment]
> For `RecoLocalTracker/SiStripClusterizer/plugins/SiStripRawToClusterGPUKernel.cu`:
> 
> ```
> RecoLocalTracker/SiStripClusterizer/plugins/SiStripRawToClusterGPUKernel.cu -> RecoLocalTracker/SiStripClusterizer/plugins/SiStripRawToClusterGPUKernel.h -> CalibFormats/SiStripObjects/interface/SiStripClusterizerConditionsGPU.h -> HeterogeneousCore/CUDACore/interface/ESProduct.h -> HeterogeneousCore/CUDAUtilities/interface/EventCache.h -> FWCore/Utilities/interface/ReusableObjectHolder.h -> oneapi/tbb/concurrent_queue.h
> RecoLocalTracker/SiStripClusterizer/plugins/SiStripRawToClusterGPUKernel.cu -> CalibFormats/SiStripObjects/interface/SiStripClusterizerConditionsGPU.h -> HeterogeneousCore/CUDACore/interface/ESProduct.h -> HeterogeneousCore/CUDAUtilities/interface/EventCache.h -> FWCore/Utilities/interface/ReusableObjectHolder.h -> oneapi/tbb/concurrent_queue.h
> ```
> 
> (this is the only tbb header used by this file, the `PFRecHitTopologyESProducer.cc` referenced several other tbb headers)

Unfortunately this does not seem trivial to disentangle.

**Comment by iarspider** [comment]
I have just realized that I have processed wrong file, sorry.

**Comment by iarspider** [comment]
Corrected dependency chain for `PFRecHitProducerKernel.dev.cc`: https://gist.github.com/iarspider/f655770228e41eebbf38618f836870bd .  All chains stem from `RecoParticleFlow/PFRecHitProducer/interface/PFRecHitTopologyRecord.h` and `RecoParticleFlow/PFRecHitProducer/interface/PFRecHitParamsRecord.h`

**Comment by fwyzard** [comment]
Can you try to edit `RecoParticleFlow/PFRecHitProducer/plugins/alpaka/CalorimeterDefinitions.h` and replace the include of the differente `Record`s with forward declarations ?

**Comment by dan131riley** [comment]
> @makortel , if we want to avoid compiling (some of) the framework headers with `nvcc`, would it make sense to add something like
> 
> ```c++
> #ifdef __NVCC__
> #error Framework headers should not be compiled by the device compiler
> #endif
> ```
> 
> to `FWCore/Concurrency/interface/WaitingTaskHolder.h` and similar headers ?

Trying this in 14_1_0_pre2, I get hits in
```
                 from src/RecoLocalCalo/HcalRecProducers/src/MahiGPU.cu:11:
                 from src/RecoParticleFlow/PFRecHitProducer/plugins/alpaka/PFRecHitProducerKernel.dev.cc:8:
                 from src/RecoParticleFlow/PFClusterProducer/plugins/alpaka/PFClusterSoAProducerKernel.dev.cc:9:
```
Full chains:
```
                 from /mnt/data1/dsr/tmp/CMSSW_14_1_0_pre2/src/FWCore/Framework/interface/DependentRecordImplementation.h:26,
                 from /mnt/data1/dsr/tmp/CMSSW_14_1_0_pre2/src/CondFormats/DataRecord/interface/HcalPedestalWidthsRcd.h:5,
                 from /mnt/data1/dsr/tmp/CMSSW_14_1_0_pre2/src/CondFormats/DataRecord/interface/HcalCombinedRecordsGPU.h:4,
                 from src/RecoLocalCalo/HcalRecProducers/src/DeclsForKernels.h:11,
                 from src/RecoLocalCalo/HcalRecProducers/src/SimpleAlgoGPU.h:4,
                 from src/RecoLocalCalo/HcalRecProducers/src/MahiGPU.cu:11:

                 from /mnt/data1/dsr/tmp/CMSSW_14_1_0_pre2/src/RecoParticleFlow/PFRecHitProducer/interface/PFRecHitParamsRecord.h:4,
                 from src/RecoParticleFlow/PFRecHitProducer/plugins/alpaka/CalorimeterDefinitions.h:12,
                 from src/RecoParticleFlow/PFRecHitProducer/plugins/alpaka/PFRecHitProducerKernel.h:6,
                 from src/RecoParticleFlow/PFRecHitProducer/plugins/alpaka/PFRecHitProducerKernel.dev.cc:8:

                 from /mnt/data1/dsr/tmp/CMSSW_14_1_0_pre2/src/FWCore/Framework/interface/DependentRecordImplementation.h:26,
                 from /mnt/data1/dsr/tmp/CMSSW_14_1_0_pre2/src/RecoParticleFlow/PFRecHitProducer/interface/PFRecHitTopologyRecord.h:4,
                 from /mnt/data1/dsr/tmp/CMSSW_14_1_0_pre2/src/RecoParticleFlow/PFClusterProducer/plugins/alpaka/PFClusterSoAProducerKernel.h:11,
                 from src/RecoParticleFlow/PFClusterProducer/plugins/alpaka/PFClusterSoAProducerKernel.dev.cc:9:
```

**Comment by fwyzard** [comment]
https://github.com/cms-sw/cmssw/pull/44828 should take care of the alpaka ParticleFlow ones.

**Comment by iarspider** [comment]
@cmsbuild please close
