### ISSUE TITLE
RelVals 2500.{325,403} failing in ROOT6_X (wrong type of arguments)

### ISSUE THREAD

**Issue by iarspider** [cms-sw/cmssw#44670]
Full logs: [1](https://cmssdt.cern.ch/SDT/cgi-bin/logreader/el8_amd64_gcc12/CMSSW_14_1_ROOT6_X_2024-04-08-2300/pyRelValMatrixLogs/run/2500.325_BTVNANO_data13.0/step2_BTVNANO_data13.0.log#/123-123), [2](https://cmssdt.cern.ch/SDT/cgi-bin/logreader/el8_amd64_gcc12/CMSSW_14_1_ROOT6_X_2024-04-08-2300/pyRelValMatrixLogs/run/2500.403_BTVNANO_mc13.2/step2_BTVNANO_mc13.2.log#/209-209)

```
----- Begin Fatal Exception 09-Apr-2024 02:58:12 CEST-----------------------
An exception of category 'StdException' occurred while
   [0] Processing  Event run: 367771 lumi: 5 event: 9075325 stream: 0
   [1] Running path 'NANOAODoutput_step'
   [2] Prefetching for module NanoAODOutputModule/'NANOAODoutput'
   [3] Calling method for module SimpleCandidateFlatTableProducer/'customJetExtTable'
Exception Message:
A std::exception was thrown.
method named "get" for type "reco::TaggingVariableList" was passed the wrong types of arguments.
----- End Fatal Exception -------------------------------------------------
```

Possible cause: https://github.com/cms-sw/cmssw/pull/43485

**Comment by iarspider** [comment]
assign xpog,reconstruction

**Comment by iarspider** [comment]
> what's an IB we can look at this in ?

The failures are in ROOT6_X IB: [RelVal 2500.325](https://cmssdt.cern.ch/SDT/cgi-bin/logreader/el8_amd64_gcc12/CMSSW_14_1_ROOT6_X_2024-04-08-2300/pyRelValMatrixLogs/run/2500.325_BTVNANO_data13.0/step2_BTVNANO_data13.0.log#/), [RelVal 2500.403](https://cmssdt.cern.ch/SDT/cgi-bin/logreader/el8_amd64_gcc12/CMSSW_14_1_ROOT6_X_2024-04-08-2300/pyRelValMatrixLogs/run/2500.403_BTVNANO_mc13.2/step2_BTVNANO_mc13.2.log#/)

They don't appear in other IB flavors

**Comment by Dr15Jones** [comment]
I took a look a quick look at the problem. It seems `customJetExtTable` passes enum values to the cut parser (which passes them to `reco::TaggingVariableList::get`) as strings. That is supposed to work. What happens internally is the cut parser asks ROOT what are the function arguments for the function in question (here `reco::TaggingVariableList::get`) and then tries to see if it can convert the value passed to the parser (either an int, float or a string) to the type needed by the function. If the function argument is an Enum, the parser asks ROOT for the names of all the enums and then compares them to the string passed to the cut parser. If there is no match, one will get that exception message.

So it is probably that enum handling in ROOT 6 has changed and that is causing this problem.

**Comment by Dr15Jones** [comment]
assign root

**Comment by Dr15Jones** [comment]
@pcanal this problem happened right when we moved to the head of ROOT's master branch.

https://github.com/cms-sw/cmsdist/pull/9127

**Comment by makortel** [comment]
type root

**Comment by pcanal** [comment]
@Dr15Jones So far, I can not see any commit that would have changed the behavior.

**Comment by iarspider** [comment]
Happened in CMSSW_14_1_ROOT632_X_2024-04-29-2300 [link](https://cmssdt.cern.ch/SDT/cgi-bin/logreader/el8_amd64_gcc12/CMSSW_14_1_ROOT632_X_2024-04-29-2300/pyRelValMatrixLogs/run/2500.325_BTVNANO_data13.0/step2_BTVNANO_data13.0.log#/)

```
----- Begin Fatal Exception 30-Apr-2024 08:35:37 CEST-----------------------
An exception of category 'Configuration' occurred while
   [0] Constructing the EventProcessor
   [1] Constructing module: class=SimplePATJetFlatTableProducer label='customJetExtTable'
Exception Message:
Expression parser error:method named "get" for type "reco::TaggingVariableList" was passed the wrong types of arguments. (char 38)
----- End Fatal Exception -------------------------------------------------

```

**Comment by Dr15Jones** [comment]
A trivial reproducer is

```python
import FWCore.ParameterSet.Config as cms

process = cms.Process("TEST")

process.source = cms.Source("EmptySource")

process.maxEvents.input = 1

process.test = cms.EDProducer("SimplePATJetFlatTableProducer",
    cut = cms.string(''),
    doc = cms.string('slimmedJetsPuppi, i.e. ak4 PFJets Puppi with JECs applied, after basic selection (pt > 15)'),
    extension = cms.bool(True),
    name = cms.string('Jet'),
    singleton = cms.bool(False),
    src = cms.InputTag("linkedObjects","jets"),
    variables = cms.PSet(
        DeepCSV_flightDistance2dSig = cms.PSet(
            doc = cms.string('transverse distance significance between primary and secondary vertex'),
            expr = cms.string("tagInfo(\'pfDeepCSV\').taggingVariables.get(\'flightDistance2dSig\', -999)"),
            lazyEval = cms.untracked.bool(False),
            precision = cms.int32(10),
            type = cms.string('float')
        )
                )
        )

process.p = cms.Path(process.test)
```

**Comment by Dr15Jones** [comment]
So I took a look and the function being called in 
https://github.com/cms-sw/cmssw/blob/ba9555476c7fd25132e09ddb91ad66b70b3444d3/DataFormats/BTauReco/interface/TaggingVariable.h#L235

Where the first argument is 

https://github.com/cms-sw/cmssw/blob/ba9555476c7fd25132e09ddb91ad66b70b3444d3/DataFormats/BTauReco/interface/TaggingVariable.h#L30

which is the namespace `reco::btau`

However, there is a `using` done here
https://github.com/cms-sw/cmssw/blob/ba9555476c7fd25132e09ddb91ad66b70b3444d3/DataFormats/BTauReco/interface/TaggingVariable.h#L170

which moves those enums into the `reco` namespace. I believe this is causing the problem.

In pure root.exe I do

```
root [0] auto c = TClass::GetClass("reco::TaggingVariableList")
root [1] auto m = c->GetListOfMethods()
root [2] for( auto i: *m) { std::cout << static_cast<TMethod*>(i)->GetName()<<std::endl; for (auto j: *static_cast<TMethod*>(i)->GetListOfMethodArgs()) { std::cout << "  "<<static_cast<TMethodArg*>(j)->GetTypeName()<<std::endl;}}
TaggingVariableList
TaggingVariableList
  reco::TaggingVariableList
operator=
  reco::TaggingVariableList
size
begin
end
push_back
  reco::TaggingVariable
~TaggingVariableList
checkTag
  reco::TaggingVariableName
insert
  reco::TaggingVariable
  bool
insert
  reco::TaggingVariableList
insert
  reco::TaggingVariableName
  reco::TaggingValue
  bool
insert
  reco::TaggingVariableName
  vector<reco::TaggingValue>
  bool
finalize
get
  reco::TaggingVariableName
get
  reco::TaggingVariableName
  reco::TaggingValue
getList
  reco::TaggingVariableName
  bool
getRange
  reco::TaggingVariableName
operator[]
  reco::TaggingVariableName
root [20] auto c2 = TClass::GetClass("reco::TaggingVariableName")
(TClass *) nullptr
root [21] auto c2 = TEnum::GetEnum("reco::TaggingVariableName")
(TEnum *) nullptr
root [22] auto c2 = TEnum::GetEnum("reco::btau::TaggingVariableName")
(TEnum *) 0x4f163f0
root [23] auto c2 = TEnum::GetEnum("reco::btau::TaggingVariableName")
(TEnum *) 0x4f163f0
```

So the name `reco::TaggingVariableName` is unknown to ROOT, but `reco::btau::TaggingVariableName` is know.

If I run the exact same code in our standard release, the member data types are the full namespaced versions:

In CMSSW_14_1_X_2024-04-24-1100
```
root [2] for( auto i: *m) { std::cout << static_cast<TMethod*>(i)->GetName()<<std::endl; for (auto j: *static_cast<TMethod*>(i)->GetListOfMethodArgs()) { std::cout << "  "<<static_cast<TMethodArg*>(j)->GetTypeName()<<std::endl;}}
TaggingVariableList
TaggingVariableList
  reco::TaggingVariableList
operator=
  reco::TaggingVariableList
size
begin
end
push_back
  reco::TaggingVariable
~TaggingVariableList
checkTag
  reco::btau::TaggingVariableName
insert
  reco::TaggingVariable
  bool
insert
  reco::TaggingVariableList
insert
  reco::btau::TaggingVariableName
  reco::TaggingValue
  bool
insert
  reco::btau::TaggingVariableName
  vector<reco::TaggingValue>
  bool
finalize
get
  reco::btau::TaggingVariableName
get
  reco::btau::TaggingVariableName
  reco::TaggingValue
getList
  reco::btau::TaggingVariableName
  bool
getRange
  reco::btau::TaggingVariableName
operator[]
  reco::btau::TaggingVariableName
```

**Comment by Dr15Jones** [comment]
@pcanal what changed in ROOT 6.30 that caused TMethodArg to now give the type of the enum as the `using` version rather than the declared namespace?

**Comment by pcanal** [comment]
> @pcanal what changed in ROOT 6.33/01 that caused TMethodArg to now give the type of the enum as the `using` version rather than the declared namespace?

I am not sure.  I am looking into it.

**Comment by pcanal** [comment]
This change introduced by [fa278745f2141ea02d40ed27af986ac8729dee2b](https://github.com/root-project/root/commit/fa278745f2141ea02d40ed27af986ac8729dee2b).   This makes `TMethodArg::GetTypeName` now returns the intended type (ie. the way it was "spelt").  To retrieve the underlying type, use `TMethodArg::GetTypeNormalizedName`.

Related, the fact that we have:
```
auto c2 = TEnum::GetEnum("reco::TaggingVariableName")
```
is an issue which is now recorded at https://github.com/root-project/root/issues/15406
