### ISSUE TITLE
RelMon Piecharts Not Working Anymore

### ISSUE THREAD

**Issue by AdrianoDee** [cms-sw/cmssw#44711]
Since a few days, we don't see anymore the piecharts in the RelMon reports pages. As a reference, this is how it was:

![](https://twiki.cern.ch/twiki/pub/CMSPublic/RelMon/_img3b9056f4c930e445f941d8f5864baca5.png)

this is how it is:

<img width="1624" alt="image" src="https://github.com/cms-sw/cmssw/assets/16901146/c2a627d6-eed5-4d32-aa79-e68752aff722">

This is due to the fact that those piecharts are built with:

https://github.com/cms-sw/cmssw/blob/1471374377d3423894ee8a8d29b95041c9cfeb38/Utilities/RelMon/python/dirstructure.py#L170-L179

that relies on [chart.googleapis.com](https://chart.googleapis.com) API that is no more alive. Fun fact: technically the API was [discontinued in 2012](https://killedby.tech/google/google-chart-api/) just a few months after the first commit introducing the RelMon machinery. But for some reason it was kept alive unmaintained until few days ago (so for 12 years). [A pictorial representation of what happened.](https://www.explainxkcd.com/wiki/index.php/2347:_Dependency).

**Comment by AdrianoDee** [comment]
assign pdmv

**Comment by makortel** [comment]
Just curious, is there a plan to address this?

**Comment by AdrianoDee** [comment]
Here a possible solution https://github.com/cms-sw/cmssw/pull/44977

**Comment by AdrianoDee** [comment]
+pdmv

**Comment by AdrianoDee** [comment]
please close
