### ISSUE TITLE
GeneratorInterface/Pythia8Interface: Found zero products matching all criteria

### ISSUE THREAD

**Issue by iarspider** [cms-sw/cmssw#44721]
Starting with CMSSW_14_1_X_2024-04-11-1100, unit test `TestGeneratorInterfacePythia8ConcurrentGeneratorFilter` is failing for all platforms and flavors with `ProductNotFound` exception:

```
----- Begin Fatal Exception 11-Apr-2024 21:29:25 CEST-----------------------
An exception of category 'ProductNotFound' occurred while
   [0] Processing  Event run: 1 lumi: 1 event: 1 stream: 2
   [1] Running path 'generation_step'
   [2] Calling method for module BetafuncEvtVtxGenerator/'VtxSmeared'
Exception Message:
Principal::getByToken: Found zero products matching all criteria
Looking for type: edm::HepMCProduct
Looking for module label: generator
Looking for productInstanceName: unsmeared

   Additional Info:
      [a] If you wish to continue processing events after a ProductNotFound exception,
add "TryToContinue = cms.untracked.vstring('ProductNotFound')" to the "options" PSet in the configuration.

----- End Fatal Exception -------------------------------------------------
```

[full log](https://cmssdt.cern.ch/SDT/cgi-bin/logreader/el8_amd64_gcc12/CMSSW_14_1_X_2024-04-11-1100/unitTestLogs/GeneratorInterface/Pythia8Interface#/130-130)

The only PR merged in that IB was updating CUDA, but I don't think this test uses CUDA.

**Comment by iarspider** [comment]
assign generators

**Comment by antoniovilela** [comment]
It also started failing for other branches. It is not related to any PR.

**Comment by iarspider** [comment]
Root cause: `https://cms-pdmv-prod.web.cern.ch/mcm/public/restapi/requests/get_fragment/BTV-RunIISummer20UL17GEN-00002 ` returns `Internal server error` instead of expected fragment.

**Comment by iarspider** [comment]
@cms-sw/pdmv-l2

**Comment by iarspider** [comment]
assign pdmv
