### ISSUE TITLE
HLT farm crash in Run 379530

### ISSUE THREAD

**Issue by trtomei** [cms-sw/cmssw#44759]
Reporting a crash in Run 379530

Here's the recipe how to reproduce the crashes (tested with CMSSW_14_0_5_patch1 on lxplus8-gpu):

```
cmsrel CMSSW_14_0_5_patch1
cd CMSSW_14_0_5_patch1/src
cmsenv
```
the
n prepare the reproducer as:

```
#!/bin/bash -ex

# CMSSW_14_0_5_patch1

hltGetConfiguration run:379530 \
  --globaltag 140X_dataRun3_HLT_v3 \
  --data \
  --no-prescale \
  --no-output \
  --max-events -1 \
  --input /store/group/tsg/FOG/debug/2024-04-17_run379530/run379530_ls0556.root  > hlt.py
  
cat <<@EOF >> hlt.py
process.options.wantSummary = True

process.options.numberOfThreads = 1
process.options.numberOfStreams = 0
@EOF

cmsRun hlt.py &> hlt.log
```

In the log, we will find the following message:
```
----- Begin Fatal Exception 17-Apr-2024 12:13:39 CEST-----------------------
An exception of category 'StdException' occurred while
   [0] Processing  Event run: 379530 lumi: 556 event: 1073222806 stream: 0
   [1] Running path 'DST_PFScouting_DoubleMuon_v1'
   [2] Calling method for module MuonHLTEcalPFClusterIsolationProducer/'hltMuonEcalMFPFClusterIsoForMuons'
Exception Message:
A std::exception was thrown.
vector::_M_range_check: __n (which is 18446744073709551615) >= this->size() (which is 2)
----- End Fatal Exception -------------------------------------------------
```

@cms-sw/hlt-l2 FYI
@cms-sw/muon-pog-l2 FYI (sorry, tagged the DPG by mistake)

**Comment by mmusich** [comment]
assign hlt

**Comment by mmusich** [comment]
the affected module actually resides in e/gamma package https://github.com/cms-sw/cmssw/blob/6e82cc8aa6fff019b94eb34a5b5297c2eaa62573/RecoEgamma/EgammaHLTProducers/plugins/HLTEcalPFClusterIsolationProducer.cc#L193

**Comment by mmusich** [comment]
@cms-sw/egamma-pog-l2 FYI

**Comment by mmusich** [comment]
So this happens because we have a `edm::Ref<reco::RecoChargedCandidate>` with eta exactly equal to 0. 
In this loop:

https://github.com/cms-sw/cmssw/blob/6e82cc8aa6fff019b94eb34a5b5297c2eaa62573/RecoEgamma/EgammaHLTProducers/plugins/HLTEcalPFClusterIsolationProducer.cc#L173-L181

we start with `iEA = -1` and since `cEta` is exactly equal to 0, this condition `if (cEta > absEtaLowEdges_.at(bIt))` is never verified and `iEA` stays `-1` when hitting this:

https://github.com/cms-sw/cmssw/blob/6e82cc8aa6fff019b94eb34a5b5297c2eaa62573/RecoEgamma/EgammaHLTProducers/plugins/HLTEcalPFClusterIsolationProducer.cc#L183

resulting in the bound-check failure for `effectiveAreas_`.

I tested that this simple change:

```
diff --git a/RecoEgamma/EgammaHLTProducers/plugins/HLTEcalPFClusterIsolationProducer.cc b/RecoEgamma/EgammaHLTProducers/plugins/HLTEcalPFClusterIsolationProducer.cc
index b4c4c8b9ff7..8c878698508 100644
--- a/RecoEgamma/EgammaHLTProducers/plugins/HLTEcalPFClusterIsolationProducer.cc
+++ b/RecoEgamma/EgammaHLTProducers/plugins/HLTEcalPFClusterIsolationProducer.cc
@@ -174,7 +174,7 @@ void HLTEcalPFClusterIsolationProducer<T1>::produce(edm::Event& iEvent, const ed
       int iEA = -1;
       auto cEta = std::abs(candRef->eta());
       for (int bIt = absEtaLowEdges_.size() - 1; bIt > -1; bIt--) {
-        if (cEta > absEtaLowEdges_.at(bIt)) {
+        if (cEta >= absEtaLowEdges_.at(bIt)) {^M
           iEA = bIt;
           break;
         }
diff --git a/RecoEgamma/EgammaHLTProducers/plugins/HLTHcalPFClusterIsolationProducer.cc b/RecoEgamma/EgammaHLTProducers/plugins/HLTHcalPFClusterIsolationProducer.cc
index 0b195f62b7a..b23763c10a3 100644
--- a/RecoEgamma/EgammaHLTProducers/plugins/HLTHcalPFClusterIsolationProducer.cc
+++ b/RecoEgamma/EgammaHLTProducers/plugins/HLTHcalPFClusterIsolationProducer.cc
@@ -200,7 +200,7 @@ void HLTHcalPFClusterIsolationProducer<T1>::produce(edm::StreamID sid,
       int iEA = -1;
       auto cEta = std::abs(candRef->eta());
       for (int bIt = absEtaLowEdges_.size() - 1; bIt > -1; bIt--) {
-        if (cEta > absEtaLowEdges_.at(bIt)) {
+        if (cEta >= absEtaLowEdges_.at(bIt)) {
           iEA = bIt;
           break;
         }
```

prevents the crash.

**Comment by mmusich** [comment]
assign reconstruction

**Comment by mmusich** [comment]
Incidentally I am wondering if we might shave off some (probably tiny) reconstruction time by using the `[]` operator instead that the slower variant  `.at()` it he same classes.

**Comment by mandrenguyen** [comment]
@mmusich The proposed solution makes sense.  Would you like reco to make a PR or you'll take care of it?

**Comment by swagata87** [comment]
> So this happens because we have a edm::Ref<reco::RecoChargedCandidate> with eta exactly equal to 0.

thanks for finding this, Marco. As egamma modules are written in similar fashion, similar unprotected codes are there as well.. so while fixing it maybe one can fix other such unprotected cases as well, if possible..

like for example
https://github.com/cms-sw/cmssw/blob/6e82cc8aa6fff019b94eb34a5b5297c2eaa62573/RecoEgamma/EgammaHLTProducers/plugins/EgammaHLTHcalVarProducerFromRecHit.cc#L232

https://github.com/cms-sw/cmssw/blob/6e82cc8aa6fff019b94eb34a5b5297c2eaa62573/RecoEgamma/EgammaHLTProducers/plugins/HLTHcalPFClusterIsolationProducer.cc#L203

**Comment by mmusich** [comment]
>  Would you like reco to make a PR or you'll take care of it?

feel free to make the PR (provided @cms-sw/egamma-pog-l2 agrees). I am wondering though - since these classes were not touched in a long time, if the triggering factor (candidate eta=0) is just a matter of chance or there is some other underlying problem upstream.

**Comment by mandrenguyen** [comment]
> > Would you like reco to make a PR or you'll take care of it?
> 
> feel free to make the PR (provided @cms-sw/egamma-pog-l2 agrees). I am wondering though - since these classes were not touched in a long time, if the triggering factor (candidate eta=0) is just a matter of chance or there is some other underlying problem upstream.

Ok, since (current and former) egamma experts are reacting in this thread, I'll leave it in their hands, unless someone asks me to do something :-)

**Comment by swagata87** [comment]
i mean since Marco have it set up already, may be he can do. 
Since its created a crash I'm assuming its urgent, so immediate fix can go in; 
while 
> since these classes were not touched in a long time, if the triggering factor (candidate eta=0) is just a matter of chance or there is some other underlying problem upstream.

this needs some more thinking probably.. this is a good point

**Comment by mmusich** [comment]
unassign reconstruction
   * I realize now that the code is actually only within HLT purview - sorry for the noise @mandrenguyen

**Comment by mmusich** [comment]
proposed fixes:
   * https://github.com/cms-sw/cmssw/pull/44764 (master, `CMSSW_14_1_X`)
   * https://github.com/cms-sw/cmssw/pull/44768 (backport, `CMSSW_14_0_X`)

**Comment by VinInn** [comment]
A binary-search may even be faster and safer

**Comment by mmusich** [comment]
+hlt
   * issue fixed by https://github.com/cms-sw/cmssw/pull/44768 included in [CMSSW_14_0_5_patch2](https://cmssdt.cern.ch/SDT/ReleaseNotes/CMSSW_14/CMSSW_14_0_5_patch2.html)
   * deployed online via `CMSSW_14_0_6_MULTIARCHS` (intermediate patches were not used online) together with HLT menu GRun 2024 V1.1. The first stable-beams run `CMSSW_14_0_6_MULTIARCHS`, using the "v1.1.X" HLT menu (see [CMSHLT-3164](https://its.cern.ch/jira/browse/CMSHLT-3164)), was [run-380306](https://cmsoms.cern.ch/cms/runs/report?cms_run=380306&cms_run_sequence=GLOBAL-RUN) (Run2024D). No further issues were spotted.
