### ISSUE TITLE
ALCARECOStreamLumiPixelsMinBias refers to a non-existent Path in workflow 1001.0

### ISSUE THREAD

**Issue by makortel** [cms-sw/cmssw#44780]
The tests in https://github.com/cms-sw/cmssw/pull/44767#issuecomment-2062760679 showed that the `ALCARECOStreamLumiPixelsMinBias` in workflow 1001.0 step 3 refers to a non-existent path. The `edmConfigDump` of the step3 configuration shows
```
process.ALCARECOStreamLumiPixelsMinBias = cms.OutputModule("PoolOutputModule",
    SelectEvents = cms.untracked.PSet(
        SelectEvents = cms.vstring('pathALCARECOLumiPixelsMinBias:RECO')
    ),
    dataset = cms.untracked.PSet(
        dataTier = cms.untracked.string('ALCARECO'),
        filterName = cms.untracked.string('LumiPixelsMinBias')
    ),
    eventAutoFlushCompressedSize = cms.untracked.int32(5242880),
    fileName = cms.untracked.string('LumiPixelsMinBias.root'),
    outputCommands = cms.untracked.vstring(
        'drop *',
        'keep *_siPixelClusters_*_*',
        'keep *_TriggerResults_*_HLT',
        'keep L1AcceptBunchCrossings_*_*_*',
        'keep L1GlobalTriggerReadoutRecord_gtDigis_*_*',
        'keep *_TriggerResults_*_HLT',
        'keep *_offlinePrimaryVertices_*_*'
    )
)
```

The Path `pathALCARECOLumiPixelsMinBias` is defined in the step2 (`RECO`), but the path is not part the the `process.schedule`.

I _guess_ the `pathALCARECOLumiPixelsMinBias` would need to be added to the Schedule in step2, but I wasn't able to quickly figure out what would the right way to do that. The step2 `cmsDriver.py`'s `-s` argument had `ALCAPRODUCER:@allForExpress+AlCaPCCZeroBiasFromRECO+AlCaPCCRandomFromRECO` if that has any relevance.

**Comment by makortel** [comment]
assign alca

**Comment by perrotta** [comment]
Thank you Matti for reporting.

`allForExpress` in cmsDriver step2 refers to the current alcaRecoMatrix, see [1].
But `LumiPixelsMinBias` and `AlCaPCCZeroBiasFromRECO` were removed from it in Apr 2022 [2].
Therefore, I think that also LumiPixelsMinBias should be added to the step 2 of cmsDriver, analogously to what is done for AlCaPCCZeroBiasFromRECO, as Matti correctly already suggests.

[1] https://github.com/cms-sw/cmssw/blob/master/Configuration/AlCa/python/autoAlca.py#L54
[2] See note in https://twiki.cern.ch/twiki/bin/viewauth/CMS/AlCaRecoMatrix

**Comment by makortel** [comment]
> Therefore, I think that also LumiPixelsMinBias should be added to the step 2 of cmsDriver, analogously to what is done for AlCaPCCZeroBiasFromRECO, as Matti correctly already suggests.

Thanks @perrotta for the diagnosis. Just to make sure, would AlCa follow up with your suggestion above?

**Comment by perrotta** [comment]
> Thanks @perrotta for the diagnosis. Just to make sure, would AlCa follow up with your suggestion above?

@makortel have a look at #44787

**Comment by makortel** [comment]
Thanks!

**Comment by perrotta** [comment]
+alca
- https://github.com/cms-sw/cmssw/pull/44787 just merged
