### ISSUE TITLE
'Conditions not found' in RelVals 180.1, 181.1

### ISSUE THREAD

**Issue by iarspider** [cms-sw/cmssw#44866]
In non-default IBs (CLANG_X, CUDART_X, DEVEL_X, etc) RelVals 180.1 and/or 181.1 are failing with 'Conditions not found' exception:

```
----- Begin Fatal Exception 29-Apr-2024 08:12:22 CEST-----------------------
An exception of category 'Conditions not found' occurred while
   [0] Processing  Event run: 1 lumi: 1 event: 4 stream: 2
   [1] Running path 'HLTAnalyzerEndpath'
   [2] Prefetching for module L1TRawToDigi/'hltGtStage2Digis'
   [3] Prefetching for module RawDataCollectorByLabel/'rawDataCollector'
   [4] Prefetching for module SiStripDigiToRawModule/'SiStripDigiToRaw'
   [5] Calling method for module MixingModule/'mix'
Exception Message:
Unavailable Conditions of type HcalMCParams for cell (0x54000140) (Det 5:5 subdet 2:2 ZDC+ UNKNOWN 0,0)
----- End Fatal Exception -------------------------------------------------
```

Example log: [link](https://cmssdt.cern.ch/SDT/cgi-bin/logreader/el8_amd64_gcc12/CMSSW_14_1_ROOT6_X_2024-04-28-2300/pyRelValMatrixLogs/run/180.1_Starlight_DoubleDiffraction_5360_HI_2023/step2_Starlight_DoubleDiffraction_5360_HI_2023.log#/1103-1103)

**Comment by iarspider** [comment]
assign generators,pdmv,upgrade

**Comment by mmusich** [comment]
related to https://github.com/cms-sw/cmssw/issues/43582

**Comment by perrotta** [comment]
assign hcal-dpg

**Comment by perrotta** [comment]
unassign generator

**Comment by perrotta** [comment]
@cms-sw/hcal-dpg-l2 this error is showing up also in the pre-production of the premix samples for the 2024 MC in CMSSW_14_0_X, see https://gitlab.cern.ch/groups/cms-ppd/-/epics/10#note_8516802

This is clearly due to the (still) missing conditions for the ZDC geometry. But as far as I understood a fix was supposed to the be implemented for the releases in which such ZDC geometry was not supposed to be backported, i.e. CMSSW_14_0_X (always, if I understood it correctly).

Could you please review and provide a solution or a fix, so that the pre-production for 2024 MC can finally start?

**Comment by perrotta** [comment]
assign alca

**Comment by abdoulline** [comment]
> This is clearly due to the (still) missing conditions for the ZDC geometry. But as far as I understood a fix was supposed to the be implemented for the releases in which such ZDC geometry was not supposed to be backported, i.e. CMSSW_14_0_X (always, if I understood it correctly).

It's not conditions per se, but an appearance of the **illegal** ("corrupted")  ZDCDetId... 
cell (0x54000140) (Det 5:5 subdet 2:2 ZDC+ UNKNOWN 0,0)
I must admit I have no idea where it comes from ....
May be @bsunanda has?

**Comment by perrotta** [comment]
Thank you @abdoulline 
I did not notice (even if I already contributed there myself a couple of weeks ago...) that there was also another github issue on the same topic, with some more recent updates, in https://github.com/cms-sw/cmssw/issues/43582
Maybe @iarspider we can close this one and continue the discussion in https://github.com/cms-sw/cmssw/issues/43582 ?

**Comment by iarspider** [comment]
Closing in favor of #43582
