### ISSUE TITLE
RelVals 180.1, 181.1: crash on non-default architectures

### ISSUE THREAD

**Issue by iarspider** [cms-sw/cmssw#44863]
RelVals 180.1, 181.1, modified in https://github.com/cms-sw/cmssw/pull/44671, are failing on for non-default architectures (e.g. [slc7_amd64_gcc12](https://cmssdt.cern.ch/SDT/cgi-bin/logreader/slc7_amd64_gcc12/CMSSW_14_1_X_2024-04-28-0000/pyRelValMatrixLogs/run/181.1_Starlight_DoubleDiffraction_5360_HI_2024/step1_Starlight_DoubleDiffraction_5360_HI_2024.log#/114)). 

This is expected, since these relvals use gridpacks, which are only available for default architecture. 
Should we add these two RelVals to the list of "known failures"?

**Comment by iarspider** [comment]
assign core,generators,pdmv,upgrade

**Comment by Dr15Jones** [comment]
On el9 release areas it fails because it can't find a shared library:
```
/data/cmsbld/jenkins/workspace/ib-run-relvals/CMSSW_14_1_X_2024-04-26-2300/pyRelval/180.1_Starlight_DoubleDiffraction_5360_HI_2023/thread2/lheevent/macros/convert_SL2LHE: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory
convert_SL2LHE error: exit code not 0
----- Begin Fatal Exception 27-Apr-2024 03:17:01 CEST-----------------------
An exception of category 'ExternalLHEProducer' occurred while
   [0] Processing global begin Run run: 1
   [1] Calling method for module ExternalLHEProducer/'externalLHEProducer'
Exception Message:
Child failed with exit code 1.
----- End Fatal Exception -------------------------------------------------
```

It appears to me like we need to consider changing the running of gridpacks to be done within containers in order to avoid OS incompatibilities.

**Comment by stahlleiton** [comment]
Here is a possible implementation of using singularity for running gridpacks:
https://github.com/cms-sw/cmssw/compare/master...stahlleiton:cmssw:Gridpack_Singularity?expand=1

If fine, I can go ahead and open a PR

**Comment by stahlleiton** [comment]
This issue should now be solved with https://github.com/cms-sw/cmssw/pull/44900 .
Were there any further issues in the IBs after merging this PR and also fixing the scram for slc6?
If not, then  I think we can close this issue

**Comment by makortel** [comment]
I'm not seeing these problems anymore. Thanks!

**Comment by makortel** [comment]
+core

**Comment by srimanob** [comment]
+Upgrade

**Comment by AdrianoDee** [comment]
+pdmv

**Comment by bbilin** [comment]
+1
