### ISSUE TITLE
Mark functions called by  WorkerInPath::runWorkerAsync() as noexcept

### ISSUE THREAD

**Issue by makortel** [cms-sw/cmssw#44881]
Spinoff from https://github.com/cms-sw/cmssw/pull/44767/files#r1586330343

This would be mostly relevant for all the `*Async()` functions called from there. We could do one pass to add the `noexcept`, that would help to identify problematic places, and another pass to carefully evaluate how to fix any of the problems found.

**Comment by makortel** [comment]
From the review of https://github.com/cms-sw/cmssw/pull/44902, a few functions that should be checked next
* `ESSourceProductResolverBase::prefetchAsyncImplTemplate()`
* `NoProcessProductResolver::tryPrefetchResolverAsync()`
* `Principal:: getProductResolverByIndex()` (probably just mark it as `noexcept`)

**Comment by Dr15Jones** [comment]
> From the review of https://github.com/cms-sw/cmssw/pull/44902, a few functions that should be checked next

See https://github.com/cms-sw/cmssw/pull/44902

**Comment by makortel** [comment]
Done in https://github.com/cms-sw/cmssw/pull/44902 and https://github.com/cms-sw/cmssw/pull/44950

**Comment by makortel** [comment]
+core
