### ISSUE TITLE
ProductNotFound exception in workflow 142.0

### ISSUE THREAD

**Issue by makortel** [cms-sw/cmssw#44899]
Workflow 142.0 step 3 fails with
```
----- Begin Fatal Exception 03-May-2024 08:02:39 CEST-----------------------
An exception of category 'ProductNotFound' occurred while
   [0] Processing  Event run: 375491 lumi: 100 event: 98282466 stream: 1
   [1] Running path 'dqmoffline_step'
   [2] Prefetching for module TopMonitor/'BTagMu_AK8Jet300_Mu5'
   [3] Prefetching for module BTagProbabilityToDiscriminator/'pfMassDecorrelatedParticleNetDiscriminatorsJetTags'
   [4] Prefetching for module BoostedJetONNXJetTagsProducer/'pfMassDecorrelatedParticleNetJetTags'
   [5] Calling method for module DeepBoostedJetTagInfoProducer/'pfParticleNetTagInfos'
Exception Message:
Principal::getByToken: Found zero products matching all criteria
Looking for a container with elements of type: reco::Jet
Looking for module label: ak8PFJetsPuppi
Looking for productInstanceName: 

   Additional Info:
      [a] If you wish to continue processing events after a ProductNotFound exception,
add "TryToContinue = cms.untracked.vstring('ProductNotFound')" to the "options" PSet in the configuration.

----- End Fatal Exception -------------------------------------------------
```
https://cmssdt.cern.ch/SDT/cgi-bin/logreader/el8_amd64_gcc12/CMSSW_14_1_X_2024-05-02-2300/pyRelValMatrixLogs/run/142.0_RunHIPhysicsRawPrime2023A/step3_RunHIPhysicsRawPrime2023A.log#/

since CMSSW_14_1_X_2024-05-01-2300

**Comment by makortel** [comment]
assign reconstruction

**Comment by makortel** [comment]
Seems like caused by https://github.com/cms-sw/cmssw/pull/44754

**Comment by mmusich** [comment]
Narrowing down the issue, seems to come from https://github.com/cms-sw/cmssw/pull/44754/commits/a6b333b39a71ba38dcad1d0132f8b121d108da0e

**Comment by mmusich** [comment]
so technically this

```diff
diff --git a/DQMOffline/Trigger/python/BTaggingMonitoring_cff.py b/DQMOffline/Trigger/python/BTaggingMonitoring_cff.py
index f432dce60d2..eb331722710 100644
--- a/DQMOffline/Trigger/python/BTaggingMonitoring_cff.py
+++ b/DQMOffline/Trigger/python/BTaggingMonitoring_cff.py
@@ -283,6 +283,10 @@ btagMonitorHLT = cms.Sequence(
   + BTagMu_AK8Jet300_Mu5
 )
 
+# in the case of PbPb remove the following paths as that requires pfMassDecorrelatedParticleNetDiscriminatorsJetTags
+from Configuration.Eras.Modifier_pp_on_PbPb_run3_cff import pp_on_PbPb_run3
+pp_on_PbPb_run3.toReplaceWith(btagMonitorHLT,btagMonitorHLT.copyAndExclude([BTagMu_AK8DiJet170_Mu5,BTagMu_AK8Jet300_Mu5,BTagMu_AK8Jet170_DoubleMu5,BTagMonitor_AK8PFJet40]))
+
 btvHLTDQMSourceExtra = cms.Sequence(
     BTagMonitor_PFJet40
   + BTagMonitor_PFJet40_DeepJet
```

makes 142.0 run to completion after https://github.com/cms-sw/cmssw/pull/44754.
I would appreciate if @aniketkhanal @cms-sw/btv-pog-l2 could comment if that's appropriate for HLT BTV monitoring during PbPb runs.
Let me tag also @mandrenguyen in case he wants to forward to HI BTV and HI HLT people.

**Comment by mandrenguyen** [comment]
Thanks @mmusich
We don't use b-tagging at HLT in PbPb, we should bypass/disable this. 
There are plans to use b-tagging at HLT for the pp reference run, but that's a different story.

**Comment by mmusich** [comment]
>  We don't use b-tagging at HLT in PbPb, we should bypass/disable this.

OK, so let's move on with the proposal at https://github.com/cms-sw/cmssw/pull/44926

**Comment by mmusich** [comment]
type btv

**Comment by SWuchterl** [comment]
> so technically this
> 
> ```diff
> diff --git a/DQMOffline/Trigger/python/BTaggingMonitoring_cff.py b/DQMOffline/Trigger/python/BTaggingMonitoring_cff.py
> index f432dce60d2..eb331722710 100644
> --- a/DQMOffline/Trigger/python/BTaggingMonitoring_cff.py
> +++ b/DQMOffline/Trigger/python/BTaggingMonitoring_cff.py
> @@ -283,6 +283,10 @@ btagMonitorHLT = cms.Sequence(
>    + BTagMu_AK8Jet300_Mu5
>  )
>  
> +# in the case of PbPb remove the following paths as that requires pfMassDecorrelatedParticleNetDiscriminatorsJetTags
> +from Configuration.Eras.Modifier_pp_on_PbPb_run3_cff import pp_on_PbPb_run3
> +pp_on_PbPb_run3.toReplaceWith(btagMonitorHLT,btagMonitorHLT.copyAndExclude([BTagMu_AK8DiJet170_Mu5,BTagMu_AK8Jet300_Mu5,BTagMu_AK8Jet170_DoubleMu5,BTagMonitor_AK8PFJet40]))
> +
>  btvHLTDQMSourceExtra = cms.Sequence(
>      BTagMonitor_PFJet40
>    + BTagMonitor_PFJet40_DeepJet
> ```
> 
> makes 142.0 run to completion after #44754. I would appreciate if @aniketkhanal @cms-sw/btv-pog-l2 could comment if that's appropriate for HLT BTV monitoring during PbPb runs. Let me tag also @mandrenguyen in case he wants to forward to HI BTV and HI HLT people.

We confirm that this behavior is unintentional and we can go ahead as @mandrenguyen suggested. Thanks @mmusich for opening the PR.
