### ISSUE TITLE
Very noisy BrokenTowers:  L1NNCaloTauEmulator:l1tNNCaloTauEmulator

### ISSUE THREAD

**Issue by srimanob** [cms-sw/cmssw#44922]
While trying to debug another issue, I found that it is very noisy output of Phase-2 workflow by
```
%MSG-w BrokenTowers:  L1NNCaloTauProducer:l1tNNCaloTauProducer  07-May-2024 17:14:59 CEST Run: 1 Event: 4
 ** WARNING : FOUND 1681 TOWERS WITH towerIeta=-1016 AND towerIphi=-962
%MSG
%MSG-w BrokenTowers:  L1NNCaloTauEmulator:l1tNNCaloTauEmulator  07-May-2024 17:14:59 CEST Run: 1 Event: 4
 ** WARNING : FOUND 1681 TOWERS WITH towerIeta=-1016 AND towerIphi=-962
%MSG
```

To reproduce: running using config dumpped from
`runTheMatrix.py --what upgrade -l 29643.0 -t 8 --nStreams 2 --wm init`

`cmsDriver.py QCDForPF_14TeV_TuneCP5_cfi  -s GEN,SIM -n 200 --conditions auto:phase2_realistic_T33 --beamspot HLLHC14TeV --datatier GEN-SIM --eventcontent FEVTDEBUG --geometry Extended2026D110 --era Phase2C17I13M9 --python step1.py --no_exec --fileout file:step1.root  --nThreads 8 --nStreams 2`
 
`cmsDriver.py step2  -s DIGI:pdigi_valid,L1TrackTrigger,L1,DIGI2RAW,HLT:@relval2026 --conditions auto:phase2_realistic_T33 --datatier GEN-SIM-DIGI-RAW -n -1 --eventcontent FEVTDEBUGHLT --geometry Extended2026D110 --era Phase2C17I13M9 --python step2.py --no_exec --filein  file:step1.root  --fileout file:step2.root  --nThreads 8 --nStreams 2`

**Comment by srimanob** [comment]
assign l1,upgrade

**Comment by makortel** [comment]
Looks like a duplicate of https://github.com/cms-sw/cmssw/issues/44766 ?

**Comment by srimanob** [comment]
Thanks Matti, so I close this one.
