### ISSUE TITLE
`USER_SCRAM_TARGET` does not work in a development area

### ISSUE THREAD

**Issue by fwyzard** [cms-sw/cmssw#44947]
Setting `USER_SCRAM_TARGET=x86-64-v3` works if used directly within an IB, but it does not work if used with a development area.

#### base IB
```bash
$ cd /cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02836/el9_amd64_gcc12/cms/cmssw/CMSSW_14_1_X_2024-05-09-2300
$ export USER_SCRAM_TARGET=x86-64-v3
$ cmsenv
IMPORTANT: Setting CMSSW environment to use 'x86-64-v3' target.
$ echo $LD_LIBRARY_PATH | tr : \\n | grep x86-64-v3
/cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02836/el9_amd64_gcc12/cms/cmssw/CMSSW_14_1_X_2024-05-09-2300/biglib/el9_amd64_gcc12/scram_x86-64-v3
/cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02836/el9_amd64_gcc12/cms/cmssw/CMSSW_14_1_X_2024-05-09-2300/lib/el9_amd64_gcc12/scram_x86-64-v3
/cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02836/el9_amd64_gcc12/cms/cmssw/CMSSW_14_1_X_2024-05-09-2300/external/el9_amd64_gcc12/lib/scram_x86-64-v3
```

#### development area
```bash
$ cmsrel CMSSW_14_1_X_2024-05-09-2300
WARNING: Developer's area is created for non-production architecture el9_amd64_gcc12. Production architecture for this release is el8_amd64_gcc12
$ cd CMSSW_14_1_X_2024-05-09-2300/
$ export USER_SCRAM_TARGET=x86-64-v3
$ cmsenv
$ echo $LD_LIBRARY_PATH | tr : \\n | grep x86-64-v3
```

`x86-64-v3` does not show up.

**Comment by fwyzard** [comment]
assign core

**Comment by fwyzard** [comment]
FYI @VinInn

**Comment by smuzaffar** [comment]
@fwyzard , CMSSW_14_1_X IBs are configured to not change the micro-archs in dev area. As mentioned in the [core sw meeting](https://indico.cern.ch/event/1412029/contributions/5935013/attachments/2846986/4979443/CMSSDT-CoreSW-240430.pdf), you need to run the following to force change this behaviour
```
scram b enable-multi-targets
export USER_SCRAM_TARGET=auto cmsenv
OR
export USER_SCRAM_TARGET=x86-64-v3 cmsenv
```

In `CMSSW_14_1_MULTIARCHS_X` dev area setting `export USER_SCRAM_TARGET=x86-64-v3` should be enough to use `x86-64-v3`

**Comment by fwyzard** [comment]
I see, thanks.

Why do we need to do both
```
scram b enable-multi-targets
```
and
```
export USER_SCRAM_TARGET=auto cmsenv
```
?

Can we make the first imply the second ?

**Comment by smuzaffar** [comment]
> Can we make the first imply the second ?

just to not have user accidently pick up x86-64-v3 micro-arch when switching between dev areas (MULTIARCHS and Default IBs's dev area). Note that `scram b enable-multi-targets` makes persistent changes in the dev area.

**Comment by fwyzard** [comment]
> just to not have user accidently pick up x86-64-v3 micro-arch when switching between dev areas (MULTIARCHS and Default IBs's dev area).

Sure.

What I meant is, can we make `scram b enable-multi-targets` also change the default target to `auto` ?

**Comment by makortel** [comment]
> What I meant is, can we make `scram b enable-multi-targets` also change the default target to `auto` ?

As verified in https://github.com/cms-sw/cmssw/issues/45596#issuecomment-2267609082 the `scram b enable-multi-targets` now sets the default target to `auto`, so I believe we can close this issue.

**Comment by makortel** [comment]
+core

**Comment by makortel** [comment]
@cmsbuild, please close
