### ISSUE TITLE
Deprecated google chart service: DQM comparison images are broken

### ISSUE THREAD

**Issue by smuzaffar** [cms-sw/cmssw#44969]
Looks like we are using [https://chart.googleapis.com ](https://github.com/search?q=repo%3Acms-sw%2Fcmssw%20https%3A%2F%2Fchart.googleapis.com&type=code) to generate dynamic images for DQM comparison . This service was deprecated a long time ago and now it has stop working ( e.g [DQM comparison for PR tests](https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_14_1_X_2024-05-13-1100+68e900/62764/141.046_RunEGamma2023D/HLT.html) ). 

@cms-sw/dqm-l2 , can you please look in to this and find a replacement?

**Comment by smuzaffar** [comment]
assign dqm

**Comment by davidlange6** [comment]
duplicate of #44711 perhaps?

**Comment by smuzaffar** [comment]
ah right, yes it is duplicate of https://github.com/cms-sw/cmssw/issues/44711. Closing it in favor of https://github.com/cms-sw/cmssw/issues/44711
