### ISSUE TITLE
[14.1.X] DataFormatsExtVec_t and DataFormatsSSEVec_t  unit tests failing

### ISSUE THREAD

**Issue by smuzaffar** [cms-sw/cmssw#45004]
@VinInn , two unit tests `DataFormatsExtVec_t` and `DataFormatsSSEVec_t ` start failing for 14.1.X IB. These tests start failing for `CMSSW_14_1_X_2024-05-19-0000` IB but there was no CMSSW or external change which went in to this IB. I think the reason for this failure is that full IB was built on a node with `x86-64-v4` support. These tests run fine for other flavors e.g. ROOT632, ROOT6 , GEANT4, CPP20 etc. and these flavors were build on node with  `x86-64-v3`.

For now, I have triggered a full build of 11h00 IB on  `x86-64-v3` node to see if it was issue building on  `x86-64-v4`.

**Comment by VinInn** [comment]
I think that there is a mistake in the BuildFile as a ```-march=native``` was left from early local tests when multi-arch was not available for tests

**Comment by jfernan2** [comment]
assign reconstruction
