### ISSUE TITLE
IBs with --as-needed flag and CondFormatsDataRecord

### ISSUE THREAD

**Issue by smuzaffar** [cms-sw/cmssw#45331]
Hi,
  Yesterday we have built an IB where we pass `-Wl,--as-needed` linker flag to not link any libraries which are not explicitly needed. IB itself has built without any build/link errors but all relvals/unit-tests failed due to errors like [a]. Looks like in this case `libCondFormatsDataRecord.so` was needed . `LD_PRELOAD=libCondFormatsDataRecord.so` or force linking this library[b] to CondCore/BeamSpotPlugins fixed the `testReadWriteBSFromDB` unit test. 

One way of fixing this is to add a BuildFile flag to let scram force link (not implementaed yet) a library e.g. `<use name="System/Package" force_link="1"/>` and then scram can change `-lSystemPackage` to `-Wl,--no-as-needed -lSystemPackage -Wl,-as-needed` and we have to fix all BuildFiles where this is needed. 

For `CondFormatsDataRecord` which is needed by many plugins,  can we add some symbol which is used by all plugins (which depend on it) and compiler do not drop this dependency?

[a] https://cmssdt.cern.ch/SDT/cgi-bin/logreader/el8_amd64_gcc12/CMSSW_14_1_ASNEEDED_X_2024-06-26-1200/unitTestLogs/RecoVertex/BeamSpotProducer#/26-26
```
----- Begin Fatal Exception 26-Jun-2024 22:28:34 CEST-----------------------
An exception of category 'NoRecord' occurred while
   [0] Processing  Event run: 1 lumi: 1 event: 1 stream: 0
   [1] Running path 'p'
   [2] Calling method for module BeamSpotFromDB/'beamspot'
Exception Message:
No "BeamSpotObjectsRcd" record found in the EventSetup.

 Please add an ESSource or ESProducer that delivers such a record.
----- End Fatal Exception -------------------------------------------------
```

[b]
```
diff --git a/CondCore/BeamSpotPlugins/BuildFile.xml b/CondCore/BeamSpotPlugins/BuildFile.xml
index 75062988214..041cf41ff8f 100644
--- a/CondCore/BeamSpotPlugins/BuildFile.xml
+++ b/CondCore/BeamSpotPlugins/BuildFile.xml
@@ -1,4 +1,5 @@
 <use name="CondFormats/BeamSpotObjects"/>
 <use name="CondFormats/DataRecord"/>
 <use name="CondCore/ESSources"/>
+<flags LDFLAGS="-Wl,--no-as-needed -lCondFormatsDataRecord -Wl,-as-needed"/>
 <flags EDM_PLUGIN="1"/>
```

**Comment by smuzaffar** [comment]
assign core

**Comment by VinInn** [comment]
I think one should avoid this type of "indirect?" dependency.

**Comment by smuzaffar** [comment]
I think all plugins under [CondCore](https://github.com/search?q=repo%3Acms-sw%2Fcmssw+CondFormats%2FDataRecord+language%3Axml+path%3A%2F%5ECondCore%5C%2F%2F&type=code&p=1) requires this dependency

**Comment by VinInn** [comment]
They all seems to depend on "CondCore/ESSources
so one can link (include?) CondFormats/DataRecord in it.

**Comment by VinInn** [comment]
In my opinion the each  record should go in the corresponding CondObject Package, not in such single "catch-them-all" one.

**Comment by makortel** [comment]
I think generally we should allow the Record to be defined independently of the ES data products (because they are independent, and any Record can hold any number of ES data product types). We need to think a bit of various options forward.

**Comment by makortel** [comment]
@Dr15Jones and I took a deeper look and found a decent way for `CondDBESSource` to depend on the Records at the link level: https://github.com/cms-sw/cmssw/pull/45433 .

**Comment by makortel** [comment]
+core
