### ISSUE TITLE
Nano step crashing on 2023 data due to geometry change

### ISSUE THREAD

**Issue by kandrosov** [cms-sw/cmssw#45392]
CMSSW crashes when processing MiniAOD -> NanoAOD with the following message:
```
%MSG-e MagneticField:   DD4hep_VolumeBasedMagneticFieldESProducerFromDB:VolumeBasedMagneticFieldESProducer@callESModule  05-Jul-2024 17:23:13 CEST Run: 370749 Event: 3138303640
MF Geometry needs to be re-created since current changed (cached: 90322 requested: 160812), which is not supported by dd4hep
%MSG


A fatal system signal has occurred: segmentation violation
The following is the call stack containing the origin of the signal.
```

Observed in CMSSW_14_0_6_patch1 and CMSSW_14_1_0_pre5 releases.

How to reproduce:
```
cmsDriver.py nano --filein /store/data/Run2023D/Muon0/MINIAOD/22Sep2023_v2-v1/2530000/3991afe1-006d-4eb2-ac7a-ff3080981409.root --fileout file:nano.root --eventcontent NANOAOD --datatier NANOAOD --step NANO --nThreads 1 --conditions auto:run3_data --era Run3 -n -1
```

**Comment by makortel** [comment]
assign package MagneticField/GeomBuilder

**Comment by makortel** [comment]
assign geometry, xpog

**Comment by vlimant** [comment]
crossing the run `370616` to `370749` is triggering this segfault

**Comment by makortel** [comment]
For reference, earlier issues on similar topic https://github.com/cms-sw/cmssw/issues/38624 https://github.com/cms-sw/cmssw/issues/38669

**Comment by vlimant** [comment]
Thanks @makortel for bringing previous issue into light. 
It looks like previous attempts at fixing this did not fully succeed

**Comment by vlimant** [comment]
type tracking

**Comment by vlimant** [comment]
type tau

**Comment by vlimant** [comment]
would changing `TransientTrackBuilder` to hold an `edm::ESHandle<MagneticField>` instead work ?

**Comment by vlimant** [comment]
this https://github.com/vlimant/cmssw/commit/8a03d7c79f4c4dc4fa7b209a5e99de85e8bbecc8 does not seem to do the trick (maybe worth doing anyways?)

**Comment by makortel** [comment]
> would changing `TransientTrackBuilder` to hold an `edm::ESHandle<MagneticField>` instead work ?

No, there is no practical difference compared to raw pointer.

Fundamentally the job encounters an IOV change in a way that one component is not able to deal with.

**Comment by makortel** [comment]
> There's something very fundamentally wrong happening here. The current value, that is taken from RunInfo, makes no sense:
> 
> > %MSG-e MagneticField:   DD4hep_VolumeBasedMagneticFieldESProducerFromDB:VolumeBasedMagneticFieldESProducer@callESModule  05-Jul-2024 17:23:13 CEST Run: 370749 Event: 3138303640
> > MF Geometry needs to be re-created since current changed (cached: 90322 requested: 160812), which is not supported by dd4hep
> 
> Our magnet runs at 18 kA. It seems that RunInfo is reporting 90 kA or even 160 kA, which are ridiculous numbers. We should first of all figure out what is going wrong with these erratic inputs. I can have a look later today.

@namapane The numbers in the printout
https://github.com/cms-sw/cmssw/blob/db3008eb3d4c124e744f367439512a527e84156b/MagneticField/GeomBuilder/plugins/dd4hep/DD4hep_VolumeBasedMagneticFieldESProducerFromDB.cc#L188-L193
are the `MagFieldConfig::geometryVersion`. Do those numbers correspond to the current directly?

**Comment by namapane** [comment]
> > There's something very fundamentally wrong happening here. The current value, that is taken from RunInfo, makes no sense:
> > > %MSG-e MagneticField:   DD4hep_VolumeBasedMagneticFieldESProducerFromDB:VolumeBasedMagneticFieldESProducer@callESModule  05-Jul-2024 17:23:13 CEST Run: 370749 Event: 3138303640
> > > MF Geometry needs to be re-created since current changed (cached: 90322 requested: 160812), which is not supported by dd4hep
> > 
> > 
> > Our magnet runs at 18 kA. It seems that RunInfo is reporting 90 kA or even 160 kA, which are ridiculous numbers. We should first of all figure out what is going wrong with these erratic inputs. I can have a look later today.
> 
> @namapane The numbers in the printout
> 
> https://github.com/cms-sw/cmssw/blob/db3008eb3d4c124e744f367439512a527e84156b/MagneticField/GeomBuilder/plugins/dd4hep/DD4hep_VolumeBasedMagneticFieldESProducerFromDB.cc#L188-L193
> 
> are the `MagFieldConfig::geometryVersion`. Do those numbers correspond to the current directly?

Ahhh yes you are right - I answered too quickly.
Still, there is apparently a change of the magnet current among events in this file. This should not happen in physics runs. Do you have any idea of why this is happening? Is this data taken during a ramp and is there a reason to process it in one single piece? If the current is not at the nominal working point, the data is useless for physics anyhow.

**Comment by slava77** [comment]
> crossing the run `370616` to `370749` is triggering this segfault

in OMS apparently the field changes from 2T to 3.8T.
The first run is not even in the [DCS json ](https://cms-service-dqmdc.web.cern.ch/CAF/certification/Collisions23/DCSOnly_JSONS/Cert_Collisions2023_369803_370790_eraD_13p6TeV_DCSOnly_TkPx.json)

While for academic purpose this may be interesting, can the `370616` just be removed from processing?

**Comment by slava77** [comment]
> Observed in CMSSW_14_0_6_patch1 and CMSSW_14_1_0_pre5 releases.

@kandrosov 
is this private processing or some central production/development?
Would DCS json application to the job be acceptable?

**Comment by namapane** [comment]
Adding some background: switching from 2T to 3.8T requires rebuilding the MF geometry because the 2T model is only available from a rather old MF FEM model. While with DDD it was possible to discard the existing geometry and re-make it within a job, with dd4hep this is not possible. As discussed at the time](https://github.com/cms-sw/cmssw/issues/38624#issuecomment-1179105719), we would have to have a strong requirement to ask for this use case to be supported.

**Comment by kandrosov** [comment]
> @kandrosov is this private processing or some central production/development? Would DCS json application to the job be acceptable?

It was observed during private processing. Applying DCS JSON could be an option. Thank you for finding the reason for the issue and suggesting a workaround. However, it is somehow inconvenient that a single miniAOD file can't be processed in one job without applying masking...

**Comment by vlimant** [comment]
This was indeed a private production, but doing NANO from MINI is also something that we want to be able to do centrally.
The production of `/Muon0/Run2023D-22Sep2023_v2-v1/MINIAOD` (and all 22Sep2023_v2 dataset) should have included masking in the first place to avoid run `370616`  , IMO.
Don't we change era or PD when running at non standard Bfield values  ?
FYI @cms-sw/ppd-l2

**Comment by vlimant** [comment]
I don't find anything actionable here for cmssw and I think we can close the issue

**Comment by slava77** [comment]
> Don't we change era or PD when running at non standard Bfield values ?

I don't think this happens for very short term issues.
I agree that rereco should apply DCS json.

**Comment by civanch** [comment]
Dear all,

I am very surprise that magnetic field somehow depend on geometry. At SIM step we only use global magnetic field, which is defined in global coordinates and not attached to any geometry. I would guess that the same should be for RECO. So, it should not depend on DDD or DD4hep geometry descriptions. May be historically names of objects includes "VolumeMagneticField" tittle in one or another place but in the reality field boundary do not coincide with any real geometry boundary. in SIM we have zero outside area of field definition, which is a bit larger than central detector and non-zero inside.

**Comment by civanch** [comment]
@bsunanda , do you remember why there is DD4hep_VolumeBasedMagneticFieldESProducerFromDB:VolumeBasedMagneticFieldESProducer if the field is not volume based and what is the relation between DD4hep and field?

**Comment by Dr15Jones** [comment]
@civanch I believe, the magnetic field 'geometry' is not associated with the detector geometry, per se, it has its own volumetric information. The geometry volume associates a field gradient with a particular volume in space which we need in order to do proper tracking of particles through the magnetic field changes (especially out to the muon detector). As such the magnetic field 'geometry' does not have corresponds with the detector 'geometry'.

**Comment by namapane** [comment]
Exactly. The MF "geometry" is used to define volumes that correspond to the FEM model used for the computation. We use dd4hep to obtain a representation of these volumes, that are needed to set up interpolation of the FEM data. As such this "geometry" is a detail of implementation of a specific model, and it is fully independent of the detector geometry.
