### ISSUE TITLE
Unit test `TestDQMOfflineConfigurationGotAll` failing due to extra sequences

### ISSUE THREAD

**Issue by aandvalenzuela** [cms-sw/cmssw#45486]
Hello,

Since [CMSSW_14_1_X_2024-07-16-2300](https://cmssdt.cern.ch/SDT/cgi-bin/showBuildLogs.py/el8_amd64_gcc12/www/tue/14.1-tue-23/CMSSW_14_1_X_2024-07-16-2300?utests), unit test `TestDQMOfflineConfigurationGotAll` module (`DQMOffline/Configuration`) is failing with:
```
+ echo 'Sequences run by final DQMOfflineConfiguration: 9'
Sequences run by final DQMOfflineConfiguration: 9
+ '[' 9 -gt 0 ']'
+ echo 'Final DQMOfflineConfiguration should not run any sequences.'
Final DQMOfflineConfiguration should not run any sequences.
+ echo 'Please update parameters for TestDQMOfflineConfiguration unittest to run the extra sequences.'
Please update parameters for TestDQMOfflineConfiguration unittest to run the extra sequences.
+ exit 1

---> test TestDQMOfflineConfigurationGotAll had ERRORS
```

I do not see any recent merges that could have caused the appearance of these extra sequences, but I am tagging @mmusich since we had a similar issue three weeks ago (fixed in https://github.com/cms-sw/cmssw/pull/45287). Should we just increase the number of sequences as well?

Thanks,
Andrea

**Comment by mmusich** [comment]
> Should we just increase the number of sequences as well?

That will silence the failure. It's up to @cms-sw/dqm-l2 to clarify if the increase in the number of sequences is justified.

**Comment by makortel** [comment]
assign dqm

**Comment by iarspider** [comment]
@cmsbuild please close
Fixed by https://github.com/cms-sw/cmssw/pull/45507
