### ISSUE TITLE
DAS queries of workflows 29696.0 and  29700.0 fail

### ISSUE THREAD

**Issue by makortel** [cms-sw/cmssw#45532]
Workflows 29696.0 and  29700.0 fail in PR and IB tests with DAS error (since a long time).

**Comment by makortel** [comment]
assign pdmv, upgrade

**Comment by iarspider** [comment]
Duplicate of https://github.com/cms-sw/cmssw/issues/45371

**Comment by makortel** [comment]
Tbanks

**Comment by srimanob** [comment]
+Upgrade

**Comment by AdrianoDee** [comment]
+pdmv
