### ISSUE TITLE
Create a CMSSW_14_1_0_pre6_ROOT6 release

### ISSUE THREAD

**Issue by Dr15Jones** [cms-sw/cmssw#45585]
The ROOT RNTuple developers would like an easy way to do performance measurements using MiniAOD data. To that end, creating a log lived build of CMSSW_14_1_0_pre6 with our most recent ROOT6 master branch would be a great help.

**Comment by Dr15Jones** [comment]
assign core

**Comment by smuzaffar** [comment]
@cms-sw/orp-l2 @Dr15Jones , https://github.com/cms-sw/cmssw/issues/45592 should take care of this special pre-release

**Comment by Dr15Jones** [comment]
Thanks!

**Comment by smuzaffar** [comment]
CMSSW_14_1_0_pre6_ROOT6 is available now

**Comment by hahnjo** [comment]
Hi @smuzaffar, it seems unfortunately that `CMSSW_14_1_0_pre6_ROOT6` is built with ROOT 6.30/09 :cry:

**Comment by smuzaffar** [comment]
you are right @hahnjo , I will fix with by may be building CMSSW_14_1_0_pre6_ROOT633

**Comment by smuzaffar** [comment]
@hahnjo , CMSSW_14_1_0_pre6_ROOT633 is available now

**Comment by smuzaffar** [comment]
+core

closing it as CMSSW_14_1_0_pre6_ROOT633 is available
