### ISSUE TITLE
HLT crash in run 384069: MultiTrajectoryState mixes states with different signs of local p_z

### ISSUE THREAD

**Issue by mmusich** [cms-sw/cmssw#45639]
In [run384069](https://cmsoms.cern.ch/cms/runs/report?cms_run=384069): (pp collisions, era 2024G, release `CMSSW_14_0_13_MULTIARCHS`) we got this crash at the HLT farrm:

```
----- Begin Fatal Exception 04-Aug-2024 23:32:15 CEST-----------------------
An exception of category 'LogicError' occurred while
   [0] Processing  Event run: 384069 lumi: 689 event: 1585214172 stream: 19
   [1] Running path 'DST_PFScouting_DoubleMuon_v5'
   [2] Calling method for module GsfTrackProducer/'hltEgammaGsfTracksUnseeded'
Exception Message:
MultiTrajectoryState mixes states with different signs of local p_z
----- End Fatal Exception -------------------------------------------------
```

maybe related to old [issues-35929](https://github.com/cms-sw/cmssw/issues/35929) (2021).

I am attaching the full log of the crash [old_hlt_run384069_pid2378323.log](https://github.com/user-attachments/files/16495677/old_hlt_run384069_pid2378323.log)

This could be reproduced using the following recipe (e.g. on `lxplus8-gpu.cern.ch`:

```bash
#!/bin/bash -ex

# CMSSW_14_0_13_MULTIARCHS

hltGetConfiguration run:384069 \
--globaltag 140X_dataRun3_HLT_v3 \
--data \
--no-prescale \
--no-output \
--max-events -1 \
--input '/store/group/tsg/FOG/error_stream_root/run384069/run384069_ls0689_index000033_fu-c2b04-35-01_pid2378323.root,/store/group/tsg/FOG/error_stream_root/run384069/run384069_ls0689_index000067_fu-c2b0
4-35-01_pid2378323.root' > hlt.py

cat <<@EOF >> hlt.py
del process.MessageLogger
process.load('FWCore.MessageService.MessageLogger_cfi')  
process.options.wantSummary = True
process.options.numberOfThreads = 1
process.options.numberOfStreams = 0
@EOF

cmsRun hlt.py &> hlt.log
```

Cc: @cms-sw/hlt-l2 @trocino @trtomei @vince502

**Comment by mmusich** [comment]
@cms-sw/egamma-pog-l2 FYI.
Allow me to tag @swagata87 as in the past we tackled similar issues.

**Comment by mmusich** [comment]
on top of this, allow me to point out that analyzing the log of the job preceding the crash, the e/gamma reconstruction is quite noisy:

```bash
grep '%MSG-e' old_hlt_run384069_pid2378323.log | awk '{key = $2 " " $3; count[key]++} END {for (k in count) print count[k], k}' | sort -n
1 FailedPropagation: TrackProducer:hltIter0PFlowCtfWithMaterialTracks
1 PosteriorWeightsCalculator: GsfTrackProducer:hltEgammaGsfTracks
1 TooManySeeds: CkfTrackCandidateMaker:hltDisplacedhltIter4PFlowCkfTrackCandidates
1 TooManySeeds: CkfTrackCandidateMaker:hltDoubletRecoveryPFlowCkfTrackCandidates
1 TrajectoryNotPosDef: TrackProducer:hltIterL3OIGlbDisplacedMuonCtfWithMaterialTracks
1 TrajectoryNotPosDef: TrackProducer:hltIterL3OIMuCtfWithMaterialTracksOpenMu
1 TrajectoryNotPosDef: TrackProducer:hltL3NoFiltersTkTracksFromL2OIHitNoVtx
1 TrajectoryNotPosDef: TrackProducer:hltL3TkTracksFromL2OIStateNoVtx
3 TrajectoryNotPosDef: TrackProducer:hltIter3IterL3FromL1MuonCtfWithMaterialTracksSerialSync
4 PosteriorWeightsCalculator: GsfTrackProducer:hltEgammaGsfTracksUnseeded
5 TrajectoryNotPosDef: TrackProducer:hltIterL3OIMuCtfWithMaterialTracks
6 TrajectoryNotPosDef: TrackProducer:hltIterL3OIMuCtfWithMaterialTracksNoVtx
24 CTPPSPixelDataFormatter: CTPPSPixelRawToDigi:hltCTPPSPixelDigis
24 CTPPSPixelDataFormatter: CTPPSPixelRawToDigi:hltCTPPSPixelDigis@endStream
124 TrajectoryNotPosDef: TrackProducer:hltDoubletRecoveryPFlowCtfWithMaterialTracksSerialSync
235 TrajectoryNotPosDef: TrackProducer:hltIter3IterL3FromL1MuonCtfWithMaterialTracks
1779 InvalidState: GsfTrackProducer:hltEgammaGsfTracks
1807 GsfMultiStateUpdator: GsfTrackProducer:hltEgammaGsfTracks
5495 TrajectoryNotPosDef: TrackProducer:hltL3NoFiltersTkTracksFromL2IOHitNoVtx
5582 TrajectoryNotPosDef: TrackProducer:hltDoubletRecoveryPFlowCtfWithMaterialTracks
6452 InvalidState: GsfTrackProducer:hltEgammaGsfTracksUnseeded
6534 GsfMultiStateUpdator: GsfTrackProducer:hltEgammaGsfTracksUnseeded
```

**Comment by makortel** [comment]
assign reconstruction, hlt

**Comment by swagata87** [comment]
How about this [1]? This solves the crash 

[1]
```diff
--- a/TrackingTools/GsfTools/src/MultiTrajectoryStateAssembler.cc
+++ b/TrackingTools/GsfTools/src/MultiTrajectoryStateAssembler.cc
@@ -197,7 +197,7 @@ void MultiTrajectoryStateAssembler::removeWrongPz() {
   MultiTSOS oldStates(theStates);
   theStates.clear();
   for (auto const &is : oldStates) {
-    if (meanPz * is.localParameters().pzSign() >= 0.) {
+    if (meanPz * is.localParameters().pzSign() > 0.) {
       theValidWeightSum += is.weight();
       theStates.push_back(is);
     } else {
```

**Comment by mmusich** [comment]
> How about this [1]? This solves the crash

FWIW I confirm this removes the crash. 
Just as an additional note by adding this:

```diff
diff --git a/TrackingTools/GsfTools/src/MultiTrajectoryStateAssembler.cc b/TrackingTools/GsfTools/src/MultiTrajectoryStateAssembler.cc
index 5c99aa336d0..45a3efa015f 100644
--- a/TrackingTools/GsfTools/src/MultiTrajectoryStateAssembler.cc
+++ b/TrackingTools/GsfTools/src/MultiTrajectoryStateAssembler.cc
@@ -187,9 +187,20 @@ void MultiTrajectoryStateAssembler::removeWrongPz() {
   // Calculate average pz
   //
   double meanPz(0.);
-  for (auto const &is : theStates)
+  int counter{0};
+  for (auto const &is : theStates) {
+    counter++;
     meanPz += is.weight() * is.localParameters().pzSign();
+    edm::LogPrint("MultiTrajectoryStateAssembler")
+        << " state " << counter << " meanPz " << meanPz << " weight: " << is.weight()
+        << " pzSign:" << is.localParameters().pzSign() << std::endl;
+  }
   meanPz /= theValidWeightSum;
+
+  if (meanPz == 0) {
+    edm::LogError("MultiTrajectoryStateAssembler") << "multistate has meanPz == 0 " << std::endl;
+  }
+
   //
   // Now keep only states compatible with the average pz
   //
@@ -197,7 +208,11 @@ void MultiTrajectoryStateAssembler::removeWrongPz() {
   MultiTSOS oldStates(theStates);
   theStates.clear();
   for (auto const &is : oldStates) {
-    if (meanPz * is.localParameters().pzSign() >= 0.) {
+    if (is.localParameters().pzSign() == 0.) {
+      edm::LogError("MultiTrajectoryStateAssembler") << "found state with pZsign = 0 " << is << std::endl;
+    }
+
+    if (meanPz * is.localParameters().pzSign() > 0.) {
       theValidWeightSum += is.weight();
       theStates.push_back(is);
     } else {
``` 

I see for the problematic event:

```
...
 state 1 meanPz 0.106587 weight: 0.106587 pzSign:1
 state 2 meanPz 0.152154 weight: 0.0455673 pzSign:1
 state 3 meanPz 0.195878 weight: 0.043724 pzSign:1
 state 4 meanPz 0.237915 weight: 0.042037 pzSign:1
 state 5 meanPz 0.28997 weight: 0.0520546 pzSign:1
 state 6 meanPz 0.5 weight: 0.21003 pzSign:1
 state 7 meanPz 0.393413 weight: 0.106587 pzSign:-1
 state 8 meanPz 0.347846 weight: 0.0455673 pzSign:-1
 state 9 meanPz 0.304122 weight: 0.043724 pzSign:-1
 state 10 meanPz 0.262085 weight: 0.042037 pzSign:-1
 state 11 meanPz 0.21003 weight: 0.0520546 pzSign:-1
 state 12 meanPz 0 weight: 0.21003 pzSign:-1
%MSG-e MultiTrajectoryStateAssembler:   GsfTrackProducer:hltEgammaGsfTracksUnseeded 06-Aug-2024 09:40:26 CEST  Run: 384069 Event: 1585214172
multistate has meanPz == 0 
%MSG
```

so it really looks like the mean is becoming by accident 0. How's that special (i.e. why does it trigger the failure)?

**Comment by swagata87** [comment]
thank you for checking this. 
my understanding is the following:

we are trying to add many states [1], by calling `MultiTrajectoryStateAssembler::addState()`, which in turn calls `MultiTrajectoryStateAssembler::addStateVector(..)`.

In this event, some states have positive pz-sign, and some states have negative pz-sign, which is a problem. 
The algo takes note of the problem here [3]. 

Then, `GsfMultiStateUpdator.cc` calls `MultiTrajectoryStateAssembler::combinedState()` [2], which in turn calls `MultiTrajectoryStateAssembler::prepareCombinedState()`. At this stage, the algo tries to fix the problem by calling `removeWrongPz()` [4]. 

In most cases, `removeWrongPz` will solve the issue. 
In one special case , where `meanPz=0`,  it will not be able to solve the issue and it will let the charged-flipped states pass which will create the crash later on[5], where there is another check of pz-sign [6]. 

`meanPz` is supposed to be a positive number (when most of the states are with positive pz-sign), or a negative number (when most of the states are with negative pz-sign). In that case, if the value 
meanPz * is.localParameters().pzSign() is negative then its likely that there was a charge flip. If the value is positive then its likely that there is no charge flip. But 0 is a very special case where meanPz could not capture the information of pz-sign of the majority of the states.

[1] https://github.com/cms-sw/cmssw/blob/CMSSW_14_0_X/TrackingTools/GsfTracking/src/GsfMultiStateUpdator.cc#L45
[2] https://github.com/cms-sw/cmssw/blob/CMSSW_14_0_X/TrackingTools/GsfTracking/src/GsfMultiStateUpdator.cc#L57
[3] https://github.com/cms-sw/cmssw/blob/6a0edc71628d6a41108d536ee48978425e901c2a/TrackingTools/GsfTools/src/MultiTrajectoryStateAssembler.cc#L56
[4] https://github.com/cms-sw/cmssw/blob/6a0edc71628d6a41108d536ee48978425e901c2a/TrackingTools/GsfTools/src/MultiTrajectoryStateAssembler.cc#L182
[5] https://github.com/cms-sw/cmssw/blob/6a0edc71628d6a41108d536ee48978425e901c2a/TrackingTools/GsfTools/src/MultiTrajectoryStateAssembler.cc#L86
[6] https://github.com/cms-sw/cmssw/blob/CMSSW_14_0_X/TrackingTools/GsfTools/src/BasicMultiTrajectoryState.cc

**Comment by swagata87** [comment]
that sounds good to me. 
you may proceed with the PR (I will be mostly away today due to other commitments)

**Comment by mmusich** [comment]
It's worth noting that the reproducer doesn't crash in a regular `CMSSW_14_0_13`, so it looks like the `MULTIARCHS` variant (hence `x86-64-v3` micro-architecture) is triggering the problem in the first place (see also https://github.com/cms-sw/cmssw/issues/44550).

**Comment by mmusich** [comment]
>  you may proceed with the PR (I will be mostly away today due to other commitments)

Proposed solutions:
   * https://github.com/cms-sw/cmssw/pull/45646 (master)
   * https://github.com/cms-sw/cmssw/pull/45647 (14_0_X)

**Comment by slava77** [comment]
> thanks for the analysis:
> 
> > In one special case , where meanPz=0, it will not be able to solve the issue and it will let the charged-flipped states pass which will create the crash later on[5], where there is another check of pz-sign [6].
> 
> shall we then explicitly log an error when this happens, clear the states vector and then do an early return?

this seems just like a rare case of a double precision value falling exactly on some specific value. Shouldn't a solution be to just assign that case to one of the branches instead of accumulating LogErrors

**Comment by mmusich** [comment]
>  Shouldn't a solution be to just assign that case to one of the branches instead of accumulating LogErrors

I think that's debatable. Already the fact to have 50% of sign flipped states is suspicious to me and justifies logging an error. Also since we never had an offline crash in 2024 and just one crash at HLT (due to the different micro-architecture), I think this would not be very noisy.

**Comment by mmusich** [comment]
+hlt
   * see https://github.com/cms-sw/cmssw/issues/45639#issuecomment-2270924715

**Comment by mmusich** [comment]
@cms-sw/reconstruction-l2  please consider signing this if there is no other follow up from your area, such that we could close this issue.

**Comment by mandrenguyen** [comment]
+reconstruction
