### ISSUE TITLE
Stop Building old CMSSW releases

### ISSUE THREAD

**Issue by smuzaffar** [cms-sw/cmssw#45763]
Hi,
  As discussed during the [ORP meeting on 20th Aug](https://indico.cern.ch/event/1447628/) , @cms-sw/core-l2 would like to stop building IBs for some old releases e.g.

- CMSSW_12_6_X: Development release, also for a possible re-miniAOD in EOY 2022 
- CMSSW_13_3_X: General Software updates aiming for 2024. Nano v13 and possibly Mini v4. Last release to include major changes from Simulation

@cms-sw/ppd-l2 , do you have any objection on stopping the above mentioned IB/releases?

**Comment by Martin-Grunewald** [comment]
CMSSW_7_1 was also mentioned as a candidate to be stopped!

**Comment by smuzaffar** [comment]
yes,  `CMSSW_7_1` was also mentioned due to failure in reading input files. I think we can fix the input file reading issue but still if there is no need to keep `CMSSW_7_1` alive then we will be happy to stop it.

**Comment by makortel** [comment]
assign core

**Comment by makortel** [comment]
I think it was mentioned yesterday that 7_1_X was resurrected. Do we have a record of what was the reason? I see the original purpose of the release cycle was "Development release for first half 2013, used for MWGR & startup GEN-SIM".

**Comment by smuzaffar** [comment]
7_1_X was re-enabled late last year to get the https://github.com/cms-sw/cmssw/pull/43173 fix for pre-legcay 2016 top pag analysis

**Comment by antoniovilela** [comment]
ping @cms-sw/ppd-l2

**Comment by malbouis** [comment]
Hi @smuzaffar ,

Sorry for the late reply!

> * CMSSW_12_6_X: Development release, also for a possible re-miniAOD in EOY 2022

No objections.

> * CMSSW_13_3_X: General Software updates aiming for 2024. Nano v13 and possibly Mini v4. Last release to include major changes from Simulation

While not objecting, let me point out that this is the release used for Winter24 MC production that is still an Open Campaign and for which we are still eventually producing a few samples. So there is a very slim chance that we would eventually need a new release of this cycle, although chance are rather low. I just thought I would mention it.

In any case it is always possible to reopen it in case it's needed, right?

Thanks,
PPD.

**Comment by makortel** [comment]
Thanks @malbouis.

> > * CMSSW_13_3_X: General Software updates aiming for 2024. Nano v13 and possibly Mini v4. Last release to include major changes from Simulation
> 
> While not objecting, let me point out that this is the release used for Winter24 MC production that is still an Open Campaign and for which we are still eventually producing a few samples. So there is a very slim chance that we would eventually need a new release of this cycle, although chance are rather low. I just thought I would mention it.

I'd keep the cycle open then. It would be good to document this detail in https://twiki.cern.ch/twiki/bin/view/CMS/ReleaseSchedule. Is "Winter24 MC" the same as "2023 Run3 MC production" that is listed as the purpose of 13_1_X? 

(just to note that at some point the need to keep 13_1_X and 13_2_X open will come as well, we didn't bring them explicitly up on this round because of their "2023 Run3 MC production" and "HI data taking last year" purposes)

> In any case it is always possible to reopen it in case it's needed, right?

It is, but to me it would be clearest if we'd keep the release cycles that are being actively used in production open. Re-opening an already closed release cycle would open questions like "which necessary-to-run-in-production technical updates that need to be backported to all earlier cycles we skipped that cycle because it was closed".

**Comment by malbouis** [comment]
Hi @makortel ,

> Is "Winter24 MC" the same as "2023 Run3 MC production" that is listed as the purpose of 13_1_X?

Winter24 MC Campaign is the one used for the Preparations for the 2024 data taking. We produced all the samples for TSG studies with that Campaign and also all the samples needed by the POGs to derive the calibrations for the 2024 data-taking. Some of the POGs are still using the Winter24 samples for data to MC comparisons, as we have not yet launched the 2024 MC production. So in short, no, Winter24 MC is not the same as 2023 Run3 MC production.

As a matter of fact, the "2023 Run3 MC Production" is in 13_0_X and not 13_1_X. What we have in 13_1_X, afaik, is the MC production for Trigger Phase2.

Below is a short summary of the release cycles for 2023.

Releases purposes:
13_0: promptRECO of 2023 + MC for PAGs + Nano v12
13_1: MC for Trigger Phase2
13_2: HI DATA taking + HI MC
13_3: 2024 preparation + MC for TSG, PF and POGs
14_0: promptRECO of 2024 + MC for PAGs

**Comment by antoniovilela** [comment]
And 7_1_X, does it need to remain open?

And 8_0_X and 9_4_X?

**Comment by malbouis** [comment]
> And 7_1_X, does it need to remain open?
> 
> And 8_0_X and 9_4_X?

I think all those can be closed. Thanks, @antoniovilela !

**Comment by makortel** [comment]
> And 8_0_X and 9_4_X?

Aren't these used for the HLT step in the upcoming 2022+2023 MC production?

**Comment by malbouis** [comment]
> > And 8_0_X and 9_4_X?
> 
> Aren't these used for the HLT step in the upcoming 2022+2023 MC production?
Hi @makortel ,

I think the ones used for the HLT step in the upcoming 22+23 production are 12_4_X and 13_0_X, which are the same as the data taking release of 22 and 23 respectively. But please feel free to correct me if I'm wrong.

**Comment by makortel** [comment]
> > > And 8_0_X and 9_4_X?
> > 
> > 
> > Aren't these used for the HLT step in the upcoming 2022+2023 MC production?
> 
> I think the ones used for the HLT step in the upcoming 22+23 production are 12_4_X and 13_0_X, which are the same as the data taking release of 22 and 23 respectively. But please feel free to correct me if I'm wrong.

Sigh, I was trying to write "the HLT step in the Run 2 UL MC" (corresponding to the 2016 and 2017 data taking years). Is this activity something that is ramping down such that a risk for needing technical updates there is becoming negligible?

**Comment by malbouis** [comment]
> > > > And 8_0_X and 9_4_X?
> > > 
> > > 
> > > Aren't these used for the HLT step in the upcoming 2022+2023 MC production?
> > 
> > 
> > I think the ones used for the HLT step in the upcoming 22+23 production are 12_4_X and 13_0_X, which are the same as the data taking release of 22 and 23 respectively. But please feel free to correct me if I'm wrong.
> 
> Sigh, I was trying to write "the HLT step in the Run 2 UL MC" (corresponding to the 2016 and 2017 data taking years). Is this activity something that is ramping down such that a risk for needing technical updates there is becoming negligible?

I think the risk is low, indeed, but thanks for pointing that out. If possible, let's keep these ones open then for now.

Thanks, @makortel !

**Comment by antoniovilela** [comment]
@cms-sw/core-l2
So we stop building 12_6 and 7_1, correct?

**Comment by smuzaffar** [comment]
> @cms-sw/core-l2 So we stop building 12_6 and 7_1, correct?

correct, we will stop these IBs

**Comment by smuzaffar** [comment]
both `CMSSW_12_6_X and CMSSW_7_1_X`  are stopped now

**Comment by makortel** [comment]
+core

I think we can close this issue now

**Comment by makortel** [comment]
@cmsbuild, please close
