### ISSUE TITLE
[LLVM analyzer] Assigned value is garbage or undefined in TopQuarkAnalysis/TopKinFitter/src/TtFullLepKinSolver.cc

### ISSUE THREAD

**Issue by iarspider** [cms-sw/cmssw#46021]
LLVM [reports](https://cmssdt.cern.ch/SDT/jenkins-artifacts/ib-static-analysis/CMSSW_14_2_X_2024-09-16-1100/el8_amd64_gcc12/llvm-analysis/report-3a51b4.html#EndPath) that value assigned to z [here](https://github.com/cms-sw/cmssw/blob/master/TopQuarkAnalysis/TopKinFitter/src/TtFullLepKinSolver.cc#L338) is undefined.

This will happen if [this branch](https://github.com/cms-sw/cmssw/blob/master/TopQuarkAnalysis/TopKinFitter/src/TtFullLepKinSolver.cc#L444) of `cubic` is executed. Can we return `0` if `cubic` returns 0?

**Comment by iarspider** [comment]
assign TopQuarkAnalysis/TopKinFitter

**Comment by tvami** [comment]
I'll have a look, this seems quite easy to fix

**Comment by tvami** [comment]
+1
 * resolved in https://github.com/cms-sw/cmssw/pull/46117
