### ISSUE TITLE
git push change?

### ISSUE THREAD

**Issue by Martin-Grunewald** [cms-sw/cmssw#46023]
In the past I used to be able to do:

git push my-cmssw HEAD:newbranch

to push to a new branch in my own repo cloned from cmssw (my-cmssw seemed to have been pre-defined)

This no longer works - what is the replacement?

**Comment by smuzaffar** [comment]
@Martin-Grunewald  `git push my-cmssw HEAD:newbranch` works for me ( at least in 14.2.X) . Can you share how to reproduce it and the error you get?

**Comment by makortel** [comment]
assign core

**Comment by Martin-Grunewald** [comment]
```
git push my-cmssw HEAD:CandPtrSelector
fatal: 'my-cmssw' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by Dr15Jones** [comment]
@Martin-Grunewald how did you clone your repo?

**Comment by smuzaffar** [comment]
Please check your src/.git/config` file. It should have something like [a]. Note that `my-cmssw` is added by `git cms-*` tools so if you have cloned/checkout cmssw packages using non `git cms-*` then you can not use `my-cmssw`.

[a]
```
[remote "my-cmssw"]
        url = https://github.com/smuzaffar/cmssw.git
        fetch = +refs/heads/*:refs/remotes/my-cmssw/*
        pushurl = git@github.com:smuzaffar/cmssw.git
```

**Comment by Martin-Grunewald** [comment]
As for remote, I have:
```
[remote "cms-tsg-storm"]
        url = https://github.com/cms-tsg-storm/cmssw.git
        fetch = +refs/heads/*:refs/remotes/cms-tsg-storm/*
        pushurl = git@github.com:cms-tsg-storm/cmssw.git
```
but this part is unchanged since 2022 so never had a section ```my-cmssw``` though that still used to work...

**Comment by Martin-Grunewald** [comment]
I do not remember how I cloned it, it was many years age when we started to move to git.

**Comment by smuzaffar** [comment]
as I wrote, it still works if you use `git cms-*` tools to clone.
For now you can run `git remote add my-cmssw git@github.com:Martin-Grunewald/cmssw.git` and then `git push my-cmssw HEAD:newbranch` should work.

**Comment by Martin-Grunewald** [comment]
Sorry, I do not understand. I am using cmsrel to get the developer area, and then git cms-addpkg to get the package to modify. Then git add & git commit before trying git push.

**Comment by smuzaffar** [comment]
Does `git push my-cmssw HEAD:newbranch` fail if you do `cmsrel, cmsenv, git cms-addpkg, modify code, git commit` in fresh dev area?

May be you have copied your `src` from some old path where you had not use `git cms-addpkg` ?

**Comment by Martin-Grunewald** [comment]
Thanks! Redoing from scratch, it works now. I must have messed up earlier, sorry for the noise!

**Comment by smuzaffar** [comment]
+core
