### ISSUE TITLE
New modifier(s) for NanoAOD v15?

### ISSUE THREAD

**Issue by mbluj** [cms-sw/cmssw#46038]
Hello
I am working on moving production of some tau-related features/products from nanoAOD sequences to miniAOD ones for planned full Run-3 (&2) production sometimes called NanoAOD v15 production. It is to have those products in miniAOD event content for benefit of miniAOD users and (hypothetical) future NanoAOD versions. However, moving those products to miniAOD will made production of NanoAOD v15 from current miniAOD (e.g. Summer23 with 130X, Winter24 with 133X and possible Summer/Fall24 with 140X) impossible due to missing products. This issue probably applies also to JME and BTV products (e.g. new puppi tune, unified-jet-taggers). Therefore, I would like to ask if it is planned to add one or more new nanoAOD modifier(s) similar to `run3_nanoAOD_122` and `run3_nanoAOD_124`?
@cms-sw/xpog-l2

**Comment by mbluj** [comment]
Yes, I know the plan, but I suppose that there can other use cases of the "v15 Nano at pre-15X mini" than unit tests. I mean, e.g. "private" pre-production for POG tests. Of course those can be performed with unofficial CMSSW patches...

What concerns tau products to be added/moved to mini sequences/contents the list is as follows:
* hybrid pat-tau collection merging tau candidates recostructed with HPS algorithm and jets tagged as tau-like, but not reconstructed by HPS (production being moved nano->mini),
* deepTauID for boosted taus (being implemented, production at mini),
* life-time variables (production to be moved nano->mini).

The letter is the most complicated case as it requires re-keying and has lowest priority. 

Finally, a specific related question: is it expected to store verticesWithBS in the new 15X miniAOD also in run-2 samples as it is done in run-3 samples? If so, we would like to build time-life variables with the PVwithBS also in run-2 samples instead of using custom refitted PV. It could also require a proper treatment of eras.

**Comment by hqucms** [comment]
> Yes, I know the plan, but I suppose that there can other use cases of the "v15 Nano at pre-15X mini" than unit tests. I mean, e.g. "private" pre-production for POG tests. Of course those can be performed with unofficial CMSSW patches...
> 
> What concerns tau products to be added/moved to mini sequences/contents the list is as follows:
> 
> * hybrid pat-tau collection merging tau candidates recostructed with HPS algorithm and jets tagged as tau-like, but not reconstructed by HPS (production being moved nano->mini),
> * deepTauID for boosted taus (being implemented, production at mini),
> * life-time variables (production to be moved nano->mini).
> 
> The letter is the most complicated case as it requires re-keying and has lowest priority.

OK I see. The first two would be nice indeed. 
We could introduce a `run3_nanoAOD_pre15X` modifier to facilitate the development. Would that be sufficient?

> Finally, a specific related question: is it expected to store verticesWithBS in the new 15X miniAOD also in run-2 samples as it is done in run-3 samples? If so, we would like to build time-life variables with the PVwithBS also in run-2 samples instead of using custom refitted PV. It could also require a proper treatment of eras.

Are you referring to this collection?
```
vector<reco::Vertex>                  "offlineSlimmedPrimaryVerticesWithBS"   ""                "PAT"                                   
```
It will be available in the Run2 Re-MINI samples. You can test it with e.g., `2500.024` (UL18 reMini+NANO mc) or `2500.034` (UL18 reMini+NANO data).

**Comment by mbluj** [comment]
> > Yes, I know the plan, but I suppose that there can other use cases of the "v15 Nano at pre-15X mini" than unit tests. I mean, e.g. "private" pre-production for POG tests. Of course those can be performed with unofficial CMSSW patches...
> > What concerns tau products to be added/moved to mini sequences/contents the list is as follows:
> > 
> > * hybrid pat-tau collection merging tau candidates recostructed with HPS algorithm and jets tagged as tau-like, but not reconstructed by HPS (production being moved nano->mini),
> > * deepTauID for boosted taus (being implemented, production at mini),
> > * life-time variables (production to be moved nano->mini).
> > 
> > The letter is the most complicated case as it requires re-keying and has lowest priority.
> 
> OK I see. The first two would be nice indeed. We could introduce a `run3_nanoAOD_pre15X` modifier to facilitate the development. Would that be sufficient?

Yes, I think it will be sufficient, thank you. Should I prepare a PR adding this era or you will do so?

> 
> > Finally, a specific related question: is it expected to store verticesWithBS in the new 15X miniAOD also in run-2 samples as it is done in run-3 samples? If so, we would like to build time-life variables with the PVwithBS also in run-2 samples instead of using custom refitted PV. It could also require a proper treatment of eras.
> 
> Are you referring to this collection?
> 
> ```
> vector<reco::Vertex>                  "offlineSlimmedPrimaryVerticesWithBS"   ""                "PAT"                                   
> ```
> 
> It will be available in the Run2 Re-MINI samples. You can test it with e.g., `2500.024` (UL18 reMini+NANO mc) or `2500.034` (UL18 reMini+NANO data).

Yes, I refer to this vertices collection. I will try this wf.

**Comment by hqucms** [comment]
> Yes, I think it will be sufficient, thank you. Should I prepare a PR adding this era or you will do so?
> 
I will do it later today.

**Comment by hqucms** [comment]
@mbluj Here is the PR: https://github.com/cms-sw/cmssw/pull/46066
