### ISSUE TITLE
Fatal Root Error: @SUB=\nstart + fGapSize - 1 < fCapacity violated

### ISSUE THREAD

**Issue by bockjoo** [cms-sw/cmssw#46041]
Hi,
I am seeing this error from the production jobs:

`
 Fatal Root Error: @SUB=\nstart + fGapSize - 1 < fCapacity violated at line 293 of `/data/cmsbld/jenkins/workspace/auto-builds/CMSSW_10_6_14_Pyt8240BugFix-slc7_amd64_gcc700/build/CMSSW_10_6_14_Pyt8240BugFix-build/BUILD/slc7_amd64_gcc700/lcg/root/6.14.09-pafccj5/root-6.14.09/core/cont/src/TOrdCollection.cxx
`

with this file 

`
root://cmsxrootd.fnal.gov//store/mc/RunIISummer20ULPrePremix/Neutrino_E-10_gun/PREMIX/UL16_106X_mcRun2_asymptotic_v13-v1/270003/27AFBB73-9635-AC4B-9ACB-0217BFE08D07.root
`

This is the output from the opensearch production job monitoring:

[opensearch.json](https://github.com/user-attachments/files/17048781/opensearch.json)

I am not sure if this is a significant issue, though.
Can you check?
Thanks,
Bockjoo

**Comment by makortel** [comment]
assign core

**Comment by makortel** [comment]
@pcanal What can you tell from the error message?

**Comment by makortel** [comment]
type root

**Comment by pcanal** [comment]
This is an internal consistency checks.  Most likely than not some memory (and/or file?) has been corrupted before that point.

**Comment by makortel** [comment]
I think we can leave this to the "probable file (or memory( corruption" at this stage. In any case fixes/workarounds to CMSSW_10_6_X would be highly unlikely unless these errors would become widespread.

**Comment by makortel** [comment]
+core

**Comment by makortel** [comment]
@cmsbuild, please close

**Comment by pcanal** [comment]
> What can you tell from the error message?

Not much ...

> "probable file (or memory( corruption"

Most likely indeed.
