### ISSUE TITLE
`test_dumpRecoGeometry` test should be split into multiple scripts

### ISSUE THREAD

**Issue by makortel** [cms-sw/cmssw#46053]
The `test_dumpRecoGeometry` test script runs many `cmsRun` jobs and can time out in PR tests (see e.g. https://github.com/cms-sw/cmssw/pull/45999#issuecomment-2353723360). It would be good to split the script so that (at least some) these jobs could be run in parallel.

**Comment by makortel** [comment]
assign Fireworks/Geometry

**Comment by alja** [comment]
A simple fix would be to split the test for each tag in https://github.com/cms-sw/cmssw/blob/master/Fireworks/Geometry/test/test_dumpRecoGeometry.sh#L11 in a new script.

Let me know if there is any more sophisticated solution.
