### ISSUE TITLE
[LLVM Analyzer] Called C++ object pointer is null in JetResolution::parameterEtaEval

### ISSUE THREAD

**Issue by iarspider** [cms-sw/cmssw#46071]
LLVM analyzer [reports](https://cmssdt.cern.ch/SDT/jenkins-artifacts/ib-static-analysis/CMSSW_14_2_X_2024-09-16-1100/el8_amd64_gcc12/llvm-analysis/report-670103.html#EndPath).

If parameter is not found, besides printing error on [L182-184](https://github.com/cms-sw/cmssw/blob/master/CondFormats/JetMETObjects/src/JetResolution.cc#L183-L184), should the function return some special value or should the execution terminate?

**Comment by iarspider** [comment]
assign CondFormats/JetMETObjects

**Comment by perrotta** [comment]
> If parameter is not found, besides printing error on [L182-184](https://github.com/cms-sw/cmssw/blob/master/CondFormats/JetMETObjects/src/JetResolution.cc#L183-L184), should the function return some special value or should the execution terminate?

@iarspider taking into account that, as far as I remember, such an error never showed up it will quite likely change nothing.
In any case, I think that the logic should be that if the `func` is not found, one should terminate (maybe with an assert, if you want to get rid of the warning in the LLVM analyzer. 
The alternative of putting a default return value (1., for 100% resolution as default?) is leading in my opinion to potential mistakes and unneeded processing of wrong configs if the LogError message remains unnoticed.

**Comment by Dr15Jones** [comment]
How about throwing an exception?
