### ISSUE TITLE
UnknownUserFloat exception: Requested UserFloat pileupJetIdPuppi:fullDiscriminant is not available

### ISSUE THREAD

**Issue by iarspider** [cms-sw/cmssw#46221]
Several RelVals in CMSSW_14_2_X_2024-10-02-2300 failed with `UnknownUserFloat exception`:

```
----- Begin Fatal Exception 03-Oct-2024 08:01:25 CEST-----------------------
An exception of category 'UnknownUserFloat' occurred while
   [0] Processing  Event run: 1 lumi: 23 event: 2202 stream: 0
   [1] Running path 'dqmoffline_2_step'
   [2] Prefetching for module NanoAODDQM/'nanoDQMMC'
   [3] Calling method for module SimplePATJetFlatTableProducer/'jetPuppiTable'
Exception Message:
Requested UserFloat pileupJetIdPuppi:fullDiscriminant is not available! Possible UserFloats are: 
hfsigmaEtaEta hfsigmaPhiPhi muonSubtrRawPt puId_beta puId_dR2Mean puId_frac01 puId_frac02 puId_frac03 puId_frac04 puId_jetR puId_jetRchg puId_majW puId_minW puId_ptD puId_pull qgl_axis2 qgl_ptD 
----- End Fatal Exception -------------------------------------------------
```

Example of logs: [10224.15](http://cmssdt.cern.ch/SDT/cgi-bin/logreader/el9_amd64_gcc12/CMSSW_14_2_X_2024-10-02-2300/pyRelValMatrixLogs/run/10224.15_TTbar_13+2017PU_JMENano/step5_TTbar_13+2017PU_JMENano.log), [11024.15](http://cmssdt.cern.ch/SDT/cgi-bin/logreader/el9_amd64_gcc12/CMSSW_14_2_X_2024-10-02-2300/pyRelValMatrixLogs/run/11024.15_TTbar_13+2018PU_JMENano/step5_TTbar_13+2018PU_JMENano.log), [11634.15](http://cmssdt.cern.ch/SDT/cgi-bin/logreader/el9_amd64_gcc12/CMSSW_14_2_X_2024-10-02-2300/pyRelValMatrixLogs/run/11634.15_TTbar_14TeV+2021_JMENano/step3_TTbar_14TeV+2021_JMENano.log), [25202.15](http://cmssdt.cern.ch/SDT/cgi-bin/logreader/el9_amd64_gcc12/CMSSW_14_2_X_2024-10-02-2300/pyRelValMatrixLogs/run/25202.15_TTbar_13/step5_TTbar_13.log)

Most likely caused by https://github.com/cms-sw/cmssw/pull/46191 - reverting it resolves the issue.

**Comment by iarspider** [comment]
assign xpog, reconstruction

**Comment by jfernan2** [comment]
assign dqm

**Comment by hqucms** [comment]
@nurfikri89 Could you please have a look? Thanks!

**Comment by nurfikri89** [comment]
@hqucms My apologies. I will look into this.

**Comment by nurfikri89** [comment]
@iarspider @hqucms I have fixed the issue. I will submit a PR later in the day after my local tests are done.

**Comment by hqucms** [comment]
> @iarspider @hqucms I have fixed the issue. I will submit a PR later in the day after my local tests are done.

Thanks a lot @nurfikri89 !

**Comment by iarspider** [comment]
Thanks @nurfikri89

**Comment by hqucms** [comment]
+1

fixed by https://github.com/cms-sw/cmssw/pull/46244

**Comment by hqucms** [comment]
please close
