### ISSUE TITLE
[DBG_X] Multiple relvals failing due to "looking for SiStripNoises for a strip out of range: strip 0"

### ISSUE THREAD

**Issue by iarspider** [cms-sw/cmssw#46250]
In CMSSW_14_2_DBG_X_2024-10-03-2300, multiple RelVals failed with 

```
----- Begin Fatal Exception 04-Oct-2024 06:21:16 CEST-----------------------
An exception of category 'CorruptedData' occurred while
   [0] Processing  Event run: 1 lumi: 1 event: 1 stream: 0
   [1] Running path 'HLTAnalyzerEndpath'
   [2] Prefetching for module L1TRawToDigi/'hltGtStage2Digis'
   [3] Prefetching for module RawDataCollectorByLabel/'rawDataCollector'
   [4] Prefetching for module SiStripDigiToRawModule/'SiStripDigiToRaw'
   [5] Calling method for module MixingModule/'mix'
Exception Message:
[SiStripNoises::getNoise] looking for SiStripNoises for a strip out of range: strip 0
----- End Fatal Exception -------------------------------------------------
```

Full log: [link](https://cmssdt.cern.ch/SDT/cgi-bin/logreader/el8_amd64_gcc12/CMSSW_14_2_DBG_X_2024-10-03-2300/pyRelValMatrixLogs/run/11601.0_SingleElectronPt10+2021/step2_SingleElectronPt10+2021.log#/37-37)

**Comment by iarspider** [comment]
assign reconstruction

**Comment by mmusich** [comment]
> [SiStripNoises::getNoise] looking for SiStripNoises for a strip out of range: strip 0

this in all likelyhood is coming from the GT updates in https://github.com/cms-sw/cmssw/pull/46184

**Comment by makortel** [comment]
assign simulation, alca

**Comment by makortel** [comment]
unassign reconstruction

MixingModule is not part of reconstruction

**Comment by iarspider** [comment]
@cms-sw/alca-l2 @cms-sw/simulation-l2 This is still happening - see e.g. [11601.0](https://cmssdt.cern.ch/SDT/cgi-bin/logreader/el8_amd64_gcc12/CMSSW_14_2_DBG_X_2024-10-10-2300/pyRelValMatrixLogs/run/11601.0_SingleElectronPt10+2021/step2_SingleElectronPt10+2021.log#/37-37)

```
----- Begin Fatal Exception 11-Oct-2024 08:39:03 CEST-----------------------
An exception of category 'CorruptedData' occurred while
   [0] Processing  Event run: 1 lumi: 1 event: 1 stream: 0
   [1] Running path 'HLTAnalyzerEndpath'
   [2] Prefetching for module L1TRawToDigi/'hltGtStage2Digis'
   [3] Prefetching for module RawDataCollectorByLabel/'rawDataCollector'
   [4] Prefetching for module SiStripDigiToRawModule/'SiStripDigiToRaw'
   [5] Calling method for module MixingModule/'mix'
Exception Message:
[SiStripNoises::getNoise] looking for SiStripNoises for a strip out of range: strip 0
----- End Fatal Exception -------------------------------------------------
```

**Comment by perrotta** [comment]
> [SiStripNoises::getNoise] looking for SiStripNoises for a strip out of range: strip 0
> 
> this in all likelihood is coming from the GT updates in #46184

More likely #46124, which included the latest GT updates for 2022MC used in 11601.0 (even though the `SiStripNoises`, tag was untouched in it)

@iarspider , maybe a naive question: the fact that it only shows up in the DBG_X builds couldn't point out to some wrong memory management in some Debug part of the code?

**Comment by mmusich** [comment]
>  the fact that it only shows up in the DBG_X builds couldn't point out to some wrong memory management in some Debug part of the code?

Nope:

https://github.com/cms-sw/cmssw/blob/6da11027b7ec7b8220f266521178030faccc3d71/CondFormats/SiStripObjects/interface/SiStripNoises.h#L72-L77

https://github.com/cms-sw/cmssw/blob/6da11027b7ec7b8220f266521178030faccc3d71/CondFormats/SiStripObjects/src/SiStripNoises.cc#L61-L65

`verify` - which is throwing now, is executed only in debug mode (because it's very time consuming)

**Comment by mmusich** [comment]
>  (even though the SiStripNoises, tag was untouched in it)

comparing the two versions of the GTs updated in PR https://github.com/cms-sw/cmssw/pull/46124, I see:

```
conddb diff 140X_mcRun3_2022_realistic_v9 140X_mcRun3_2022_realistic_v3 | grep SiStrip
[2024-10-11 13:15:56,066] INFO: Connecting to pro [frontier://PromptProd/cms_conditions]
SiStripBadChannelRcd                 -               SiStripBadComponents_realisticMC_for2022_pre_EE_v0_mc            SiStripBadComponents_realisticMC_for2022_v2_mc            
```

IF `SiStripBadComponents_realisticMC_for2022_pre_EE_v0_mc` unmasked a strip that was otherwise masked before, it might have uncovered an underlying issue with the existing SiStripNoise tag.

**Comment by mmusich** [comment]
> That range is computed in [CondTools/SiStrip/plugins/SiStripNoisesAndBadCompsChecker.cc](https://github.com/cms-sw/cmssw/blob/6da11027b7ec7b8220f266521178030faccc3d71/CondTools/SiStrip/plugins/SiStripNoisesAndBadCompsChecker.cc#L68)

again no. This is just a utility to fix the payloads exactly for these use case (making sure that the noise and bad components are covering the same sets of strips).

**Comment by mmusich** [comment]
> If we want to search the origin of it in the GT update, then the tag for SiStripBadChannel was updated in them

this is exactly the content of https://github.com/cms-sw/cmssw/issues/46250#issuecomment-2407194567 I guess messages crossing...

**Comment by mmusich** [comment]
Something looks **very** wrong with `SiStripBadComponents_realisticMC_for2022_pre_EE_v0_mc`.
It's not masking a lot of channel that should be masked.

![image](https://github.com/user-attachments/assets/5f0d6110-2d29-4bec-9513-8ede58d42ac2)

see difference w.r.t the previous tag `SiStripBadComponents_realisticMC_for2022_v2_mc`

![image](https://github.com/user-attachments/assets/e1a465ae-7107-4ee9-960c-0ae0b93efc82)

@perrotta @cms-sw/alca-l2 why was this payload admitted to the queue?

**Comment by mmusich** [comment]
As far as I understand https://github.com/cms-sw/cmssw/pull/46379 will fix this issue.

**Comment by mmusich** [comment]
Looks like https://github.com/cms-sw/cmssw/pull/46379 (as expected) fixed the problem, see e.g. [log of wf11601.0](https://cmssdt.cern.ch/SDT/cgi-bin/logreader/el8_amd64_gcc12/CMSSW_14_2_DBG_X_2024-10-17-2300/pyRelValMatrixLogs/run/11601.0_SingleElectronPt10+2021/step3_SingleElectronPt10+2021.log#/) in `CMSSW_14_2_DBG_X_2024-10-17-2300`, thus this issue could be signed and closed.
