### ISSUE TITLE
Recipe for using XML geometries from cmsDriver 

### ISSUE THREAD

**Issue by bsunanda** [cms-sw/cmssw#46291]
The standard way of choosing geometry always utilizes geometry from DB. Is there a cmsDriver option to choose geometry from XML files?

**Comment by makortel** [comment]
assign geometry

**Comment by makortel** [comment]
assign Configuration/Applications

**Comment by makortel** [comment]
Looking from the IB dashboard, I see e.g. workflow 23634.0 uses `--geometry Extended2026D95` command line argument for `cmsDriver.py`.

**Comment by bsunanda** [comment]
As pointed out by Matti, this option has already been there as a part of cmsDriver.py script. So this is no longer an issue. We can close this.
