### ISSUE TITLE
CMS Jenkins service not responding

### ISSUE THREAD

**Issue by smuzaffar** [cms-sw/cmssw#46337]
There is some infrastructure issues and our CMS Jenkins instance is not working properly since 12:35 Geneva time. I have asked IT service to look in to the issue. Meanwhile PR tests or IB jobs are not working

**Comment by smuzaffar** [comment]
ping cms-bot

**Comment by smuzaffar** [comment]
@cms-sw/all-l2 , I have tried to replace the old jenkins instance with a new one but it still did not work. Looks like memory usage has been increased and system start killing jenkins process. I am now building a bigger instance ( 16 cores/32GBinstead of old 8 core/s16GB)

**Comment by makortel** [comment]
type documentation

**Comment by smuzaffar** [comment]
New jenkins seem stable now. I have restarted all PR jobs which were pending but if you still see any PR for which tests are now running then please let me know

**Comment by makortel** [comment]
A report of the incident was given in the Core Software meeting earlier today, see https://indico.cern.ch/event/1468091/#17-recent-incident-with-jenkin .

@smuzaffar I suppose we could close the issue now?
