### ISSUE TITLE
Building CMSSW_9_4 release

### ISSUE THREAD

**Issue by smuzaffar** [cms-sw/cmssw#46400]
@cms-sw/orp-l2 , we discussed during last ORP, there was a request to build CMSSW_9_4 with slc7 as production arch. I see that last 9.4 release was `CMSSW_9_4_21_patch1` and after that we have integrated https://github.com/cms-sw/cmssw/compare/CMSSW_9_4_21_patch1...CMSSW_9_4_X but have not built any release. I propose to build

- CMSSW_9_4_22: To get the latest CMSSW_9_4_X changes.
- CMSSW_9_4_22_UL: Build only for slc7 as production arch

FYI @makortel @missirol , this includes your PR merged in 9_4_X IBs but not yet released.

**Comment by mseidel42** [comment]
Good for us to have our production with a new 9_4_22(_UL), thank you! 👍

**Comment by smuzaffar** [comment]
@cms-sw/orp-l2 , sorry I forgot to mention this during ORP. I think every thing is ready to build this release ... right? Feel free to start the build

**Comment by smuzaffar** [comment]
closing this issue as we now have CMSSW_9_4_22 and CMSSW_9_4_22_UL releases
