### ISSUE TITLE
Special CMSSW_14_2 ROOT633 release for RNTuple

### ISSUE THREAD

**Issue by smuzaffar** [cms-sw/cmssw#46415]
@cms-sw/orp-l2 , @cms-sw/core-l2 would like to build a special CMSSW_14_2 ROOT633 release measure the properties of RNTuple. The changes needed for this have been integrated in CMSSW_14_2_ROOT6_X IBs.  We propose to build `CMSSW_14_2_0_pre2_50ecb2c_ROOT633` which should use 

- CMSSW tag CMSSW_14_2_ROOT6_X_2024-10-16-2300 or commit 50ecb2c
- Latest IB/CMSSW_14_2_0/rootmaster cmsdist changes

If no objections then I can open the build issue to start building the release for `el8_amd64_gcc12` arch only.

**Comment by smuzaffar** [comment]
assign orp

**Comment by Dr15Jones** [comment]
@makortel and I double checked and the commits we need are in that version of the ROOT branch.

**Comment by smuzaffar** [comment]
@antoniovilela, @mandrenguyen let me know if I can start this build

**Comment by smuzaffar** [comment]
thanks @antoniovilela , I have opened https://github.com/cms-sw/cmssw/issues/46424

**Comment by Dr15Jones** [comment]
The most recent required fix in ROOT's master branch is now available

https://github.com/root-project/root/pull/16712

**Comment by Dr15Jones** [comment]
I can confirm that our version of ROOT now does have the needed fix for reading back RNTuple code. I'll do a few more tests to be confident we can make a special release.

**Comment by Dr15Jones** [comment]
@smuzaffar I have tried reading back an RNTuple file in the new release and it seems to work just fine. With that, I think we are clear to create the special release based on our most recent ROOT6 IBs.

**Comment by smuzaffar** [comment]
@Dr15Jones , as 14.2.0.pre3 is scheduled for this week, so may be we should wait few more days and then build CMSSW_14_2_0_pre3_ROOT633

**Comment by Dr15Jones** [comment]
I agree that waiting for pre3 makes sense. Thanks.

**Comment by Dr15Jones** [comment]
Even though the latest version of ROOT master didn't solve my read-back problem, I think we should go ahead with the CMSSW_14_2_0_pre3_ROOT633.

**Comment by makortel** [comment]
I guess this issue could be closed now?

**Comment by smuzaffar** [comment]
We have not built this release yet. @Dr15Jones wanted https://github.com/root-project/root/pull/16810 to be part of stable release and this was only included in last night (2024-11-12-2300) IB ROOT6. As 14.2.0.pre4 is schedule for this week so I will wait for pre4 and then build a stable ROOT635 release based on pre4

**Comment by Dr15Jones** [comment]
@smuzaffar I am not aware of any very recent RNTuple that we need.

**Comment by Dr15Jones** [comment]
A 14_2_0_pre4_ROOT635 would be very helpful.

**Comment by smuzaffar** [comment]
started via https://github.com/cms-sw/cmssw/issues/46745

**Comment by smuzaffar** [comment]
closing this issue as CMSSW_14_2_0_pre4_ROOT635 is available now
