### ISSUE TITLE
[Run3 PromptReco] GsfElectronProducer and GEDPhotonProducer duplicate TF sessions across streams

### ISSUE THREAD

**Issue by makortel** [cms-sw/cmssw#46494]
I noticed in https://github.com/cms-sw/cmssw/issues/46040#issuecomment-2420384665 that the `GsfElectronProducer` and `GEDPhotonProducer` duplicate the Tensorflow sessions across streams, specifically here
https://github.com/cms-sw/cmssw/blob/55fd97727507dd74a4020c9264f5f66118409151/RecoEgamma/EgammaPhotonProducers/src/GEDPhotonProducer.cc#L481
https://github.com/cms-sw/cmssw/blob/55fd97727507dd74a4020c9264f5f66118409151/RecoEgamma/EgammaElectronProducers/plugins/GsfElectronProducer.cc#L577

The `tensorflow::Session` has been thread safe for a while, so the `Session`s could be moved to be part of the `GlobalCache`s. While the total cost of these is modest (0.95 MB / stream), it would still be something, and by quick look I think the code would become simpler.

**Comment by makortel** [comment]
assign RecoEgamma/EgammaPhotonProducers, RecoEgamma/EgammaElectronProducers

**Comment by makortel** [comment]
assign ml

**Comment by makortel** [comment]
type performance-improvements

**Comment by valsdav** [comment]
Hi @makortel,  I wrote this code a while ago.. as the session handling is more indirect in this code, probably we forgot to migrate it when sessions became thread-safe.  I can take care of this.

**Comment by makortel** [comment]
Thanks!

**Comment by makortel** [comment]
This was addressed in https://github.com/cms-sw/cmssw/pull/46655
