### ISSUE TITLE
ROOT6 CMSSW_14_2 IB build with ROOT build with debugging

### ISSUE THREAD

**Issue by Dr15Jones** [cms-sw/cmssw#46518]
We have a request from the ROOT developers to make a CMSSW IB using a debug version of ROOT.

**Comment by Dr15Jones** [comment]
assign core

**Comment by Dr15Jones** [comment]
@jblomer FYI

**Comment by smuzaffar** [comment]
https://github.com/cms-sw/cms-bot/pull/2362 should build root in debug mode for ROOT6 IBs. CMSSW_14_2_ROOT6_X_2024-10-28-1100 is in build phase now and it shouldhave root build in debug mode

**Comment by makortel** [comment]
I guess we could close this issue now?

**Comment by smuzaffar** [comment]
+core

> PPD technical meeting sounds reasonable place to discuss/present this.

yes.

Note that ROOT6 IBs are non-debug again now. @Dr15Jones only wanted to have one ROOT6 IB build with root debug
