### ISSUE TITLE
High memory usage for PromptReco `HIZeroBias0,1,2` in Run 387326

### ISSUE THREAD

**Issue by mmusich** [cms-sw/cmssw#46526]
This is a mirror of the report at [cmsTalk](https://cms-talk.web.cern.ch/t/high-memory-usage-for-promptreco-hizerobias0-1-2-in-run-387326/57018).

Tier0 reports 55 paused Reco jobs due to unusually high memory usage for the following workflows:
`PromptReco_Run387326_HIZeroBias0`, `PromptReco_Run387326_HIZeroBias1`, `PromptReco_Run387326_HIZeroBias2`.
The run [387326](https://cmsoms.cern.ch/cms/runs/report?cms_run=387326) mentioned was taken with unstable PbPb collisions and tracker OFF.

The jobs were killed with error messages like the following:

```
PerformanceError
PerformanceKill (Exit Code: 50660)
Error in CMSSW step cmsRun1
Number of Cores: 8
Job has exceeded maxPSS: 16000 MB
Job has PSS: 16084 MB
```

One of the Logs and tarballs is accessible here: `/eos/user/c/cmst0/public/PausedJobs/Run2024J/maxMemory/PromptReco_Run387326_HIZeroBias0` (more can be prepared upon request).
Cc: @mpresill @mandrenguyen

**Comment by makortel** [comment]
> /eos/user/c/cmst0/public/PausedJobs/Run2024J/maxMemory/PromptReco_Run387326_HIZeroBias0

Something hoards memory
![image](https://github.com/user-attachments/assets/055d0d6f-88e9-4e46-a971-e041cce78fa2)

The 10 GB over 168552 events is about 60 kB/event, so sounds like https://github.com/cms-sw/cmssw/issues/42995

**Comment by makortel** [comment]
assign DQM/BeamMonitor

**Comment by mmusich** [comment]
> The 10 GB over 168552 events is about 60 kB/event, so sounds like https://github.com/cms-sw/cmssw/issues/42995

so, https://github.com/cms-sw/cmssw/pull/46465 (which entered [CMSSW_14_1_4](https://github.com/cms-sw/cmssw/releases/tag/CMSSW_14_1_4), note the run was processed in `CMSSW_14_1_4_patch1`, see [Tier0 API](https://cmsweb.cern.ch/t0wmadatasvc/prod/reco_config?run=387326)) was not enough.

**Comment by mmusich** [comment]
> DQM/BeamMonitor

mmmh, but in that run both Pixel and Strips were OFF

![Screenshot from 2024-10-28 14-18-08](https://github.com/user-attachments/assets/8c2eba10-12dd-442e-b608-2fcde7dcac1c)

what exactly are we hoarding?

**Comment by slava77** [comment]
it looks like 387326 LS12 has 175K events; is it 7.6 kHz.
I recall that in the past jobs on similar inputs were also running out of memory

**Comment by mmusich** [comment]
> it looks like 387326 LS12 has 175K events (/store/data/Run2024J/HIZeroBias0/RAW/v1/000/387/326/00000/e6fffe55-0f84-4c1d-b062-b41b82c36989.root); is it 7.6 kHz.

just for the record, there rest of the run doesn't look any different:

![Screenshot from 2024-10-28 15-06-31](https://github.com/user-attachments/assets/ca9fe10d-e0f0-4b3e-a190-fb1cdb1215d8)

**Comment by mmusich** [comment]
From the [TSG / FOG notes of the week](https://docs.google.com/document/d/1k3Tx1iWpuvXGEygr4yBPaJorMgeEzzjWtQiO5yzQaz0/edit?tab=t.0#heading=h.uok84hekvlf0):

![Screenshot from 2024-10-28 15-13-17](https://github.com/user-attachments/assets/62cf678f-462b-402d-bacc-a482fda333b2)

so it's indeed *NOT* typical, though would be good to understand what drives the hoarding.

**Comment by makortel** [comment]
> what exactly are we hoarding?

I can give IgProf a try to see if there is something else too.

**Comment by mmusich** [comment]
unassign db

**Comment by mmusich** [comment]
assign reco
   * based on likelihood

**Comment by makortel** [comment]
Ok, with IgProf the culprit is clear, and not in reconstruction but L1T code (details follow)

**Comment by makortel** [comment]
unassing reconstruction, dqm

**Comment by makortel** [comment]
assign l1

**Comment by makortel** [comment]
Comparing profiles after [100 events](https://mkortela.web.cern.ch/mkortela/cgi-bin/navigator/issue46526/test_07.100_live/1509) to [1000 events](https://mkortela.web.cern.ch/mkortela/cgi-bin/navigator/issue46526/test_07.1000_live/369) shows `L1TCaloSummary<ap_uint<10>, ap_ufixed<16, 8, (ap_q_mode)4, (ap_o_mode)0, 0> >::produce()` to hoard or leak 50912  bytes per event, divided into
* 512 bytes in `UCTSummaryCard::process()`
* 50400 bytes in `UCTSummaryCard::processRegion()`

Looking at the code I see many objects being constructed with `new` in these functions, but no corresponding `delete`s. These are
https://github.com/cms-sw/cmssw/blob/52219c0c2d0e662e26e724435dd8698a7b8e3b5e/L1Trigger/L1TCaloLayer1/src/UCTSummaryCard.cc#L129-L132
https://github.com/cms-sw/cmssw/blob/52219c0c2d0e662e26e724435dd8698a7b8e3b5e/L1Trigger/L1TCaloLayer1/src/UCTSummaryCard.cc#L367-L373
https://github.com/cms-sw/cmssw/blob/52219c0c2d0e662e26e724435dd8698a7b8e3b5e/L1Trigger/L1TCaloLayer1/src/UCTSummaryCard.cc#L421-L428
https://github.com/cms-sw/cmssw/blob/52219c0c2d0e662e26e724435dd8698a7b8e3b5e/L1Trigger/L1TCaloLayer1/src/UCTSummaryCard.cc#L477-L483

The `clearEvent()` doesn't do any attempt to `delete` these objects
https://github.com/cms-sw/cmssw/blob/52219c0c2d0e662e26e724435dd8698a7b8e3b5e/L1Trigger/L1TCaloLayer1/src/UCTSummaryCard.cc#L491-L500

Also the handling of `regions` member data is very unclear. The contained objects are deleted in `UCTSummaryCard` destructor
https://github.com/cms-sw/cmssw/blob/52219c0c2d0e662e26e724435dd8698a7b8e3b5e/L1Trigger/L1TCaloLayer1/src/UCTSummaryCard.cc#L43C18-L48
that hints the `regions` would own those objects, but `clearRegions()`
https://github.com/cms-sw/cmssw/blob/52219c0c2d0e662e26e724435dd8698a7b8e3b5e/L1Trigger/L1TCaloLayer1/src/UCTSummaryCard.cc#L502-L505
leaks anything that was set before. The `regions` member is set in
https://github.com/cms-sw/cmssw/blob/52219c0c2d0e662e26e724435dd8698a7b8e3b5e/L1Trigger/L1TCaloLayer1/src/UCTSummaryCard.cc#L534-L539
where the possible transfer of ownership is very unclear.

At minimum these should be changed to use a smart pointer `std::unique_ptr`, but I'd suggest to seriously consider if the pointers could be replaced with just objects along `std::vector<UCTRegion>`.

**Comment by mmusich** [comment]
unassign reconstruction, dqm

**Comment by mmusich** [comment]
type -tracking

**Comment by aloeliger** [comment]
What a mess. A lot of this was Calo L1 infrastructure that went unused until the CICADA project decided to try and use the summary card and started using summary card emulation. 

Any chance there were secret plans to switch CMSSW to Rust or something else shiny and new and memory safe that I was unaware of ?

I can untangle this (I think) but it will take a while. Is this urgent on the scale of 8 hours, a few days, end of the week, or when I get to it?

**Comment by mmusich** [comment]
> I can untangle this (I think) but it will take a while. Is this urgent on the scale of 8 hours, a few days, end of the week, or when I get to it?

While the input rate of the run in which the problem manifested itself was unusually high, I cannot exclude it will happen again in the next week(s) of Heavy Ion data-taking. So far in pp and ppRef data-taking we didn't have operational issues (that I know of) due to this, though I think  a fix is needed as soon as possible.

**Comment by aloeliger** [comment]
Okay. I'll take a look at this and see what I can come up with. I'll try to report back by the end of day and/or have some (partial) fixes.

**Comment by mmusich** [comment]
As reported at [cmsTalk](https://cms-talk.web.cern.ch/t/high-memory-usage-for-promptreco-hizerobias0-1-2-in-run-387326/57018/4) we have now another 27 new paused jobs at Tier0 in run [387456](https://cmsoms.cern.ch/cms/runs/report?cms_run=387456) (`hi_collisions` key ). 
All of them are for `PromptReco_Run387456_HIZeroBiasX` ,`X=0,1,2`, compatible with this issue.

**Comment by aloeliger** [comment]
Calo L1 fixes for the memory leak issue have now been merged

**Comment by makortel** [comment]
Thanks! @aloeliger Could you sign the issue?

**Comment by mmusich** [comment]
proposed solutions:
   * https://github.com/cms-sw/cmssw/pull/46543 (master, 14_2_X)
   * https://github.com/cms-sw/cmssw/pull/46567 (backport, 14_1_X)
   
A new release (`CMSSW_14_1_5`) containing the backport is expected to be built in time for the 2024 PbPb run. I'll close this issue once it's deployed in Tier0.

**Comment by aloeliger** [comment]
@mmusich Has this been deployed at tier 0? Any issues? Can this issue be closed?

**Comment by mmusich** [comment]
> Has this been deployed at tier 0? Any issues? Can this issue be closed?

The update at  https://github.com/cms-sw/cmssw/issues/46526#issuecomment-2451586802 ultimately got tested in a Tier0 replay of `CMSSW_14_1_4_patch5`, including the problematic run  387326 in subject. The test was successful ([cms-talk post](https://cms-talk.web.cern.ch/t/replay-for-cmssw-14-1-4-patch4/58204/5)). 
Tier0 switched to that release on the morning of Nov-4 but there hasn't been any physics fill since. 
I think this issue is ready to be signed / closed.

**Comment by aloeliger** [comment]
+l1
