### ISSUE TITLE
DAS failures for workflows 2024.*

### ISSUE THREAD

**Issue by mandrenguyen** [cms-sw/cmssw#46555]
Tests are systematically failing with DAS errors for the workflows you can find in the snippet below. 

`12:59:29 2024.000001_RunJetMET02024D_10k Step0-DAS_ERROR Step1-NOTRUN Step2-NOTRUN Step3-NOTRUN  - time date Wed Oct 30 12:47:55 2024-date Wed Oct 30 12:47:54 2024; exit: 1 0 0 0
12:59:29 2024.001001_RunZeroBias2024D_10k Step0-DAS_ERROR Step1-NOTRUN Step2-NOTRUN Step3-NOTRUN  - time date Wed Oct 30 12:47:58 2024-date Wed Oct 30 12:47:56 2024; exit: 1 0 0 0
12:59:29 2024.100001_RunJetMET02024C_10k Step0-DAS_ERROR Step1-NOTRUN Step2-NOTRUN Step3-NOTRUN  - time date Wed Oct 30 12:48:00 2024-date Wed Oct 30 12:47:59 2024; exit: 1 0 0 0
12:59:29 2024.101001_RunZeroBias2024C_10k Step0-DAS_ERROR Step1-NOTRUN Step2-NOTRUN Step3-NOTRUN  - time date Wed Oct 30 12:48:02 2024-date Wed Oct 30 12:48:00 2024; exit: 1 0 0 0`

**Comment by mandrenguyen** [comment]
assign pdmv

**Comment by mandrenguyen** [comment]
Here's an example:
https://github.com/cms-sw/cmssw/pull/46543#issuecomment-2447703283

**Comment by makortel** [comment]
The error is
```
Traceback (most recent call last):
  File "/cvmfs/cms-ci.cern.ch/week1/cms-sw/cmssw/46543/42471/CMSSW_14_2_X_2024-10-30-1100/bin/el8_amd64_gcc12/das-up-to-nevents.py", line 138, in <module>
    json_list = [[cc for cc in c.split(" ") if cc.startswith("Cert_C") and cc.endswith("json")][0] for c in json_list]
  File "/cvmfs/cms-ci.cern.ch/week1/cms-sw/cmssw/46543/42471/CMSSW_14_2_X_2024-10-30-1100/bin/el8_amd64_gcc12/das-up-to-nevents.py", line 138, in <listcomp>
    json_list = [[cc for cc in c.split(" ") if cc.startswith("Cert_C") and cc.endswith("json")][0] for c in json_list]
IndexError: list index out of range
```

**Comment by AdrianoDee** [comment]
The problem is that the naming of the DQM json certification changed schema since ... yesterday.

Fixes for 
- 14_2_X in https://github.com/cms-sw/cmssw/pull/46559
- 14_1_X in https://github.com/cms-sw/cmssw/pull/46560

Not needed for 14_0_X since the 2024.* wfs were not yet included in that cycle.

**Comment by AdrianoDee** [comment]
+pdmv

**Comment by makortel** [comment]
@cmsbuild, please close
