### ISSUE TITLE
Lack of relval testing for PbPb skims 

### ISSUE THREAD

**Issue by mmusich** [cms-sw/cmssw#46586]
Recently a  new release (`CMSSW_14_1_4_patch4`) [1] was made available to fix few issues observed during the 2024 Heavy Ion setup runs and  to introduce new / modify physics skims for the PbPb run, including `PbPbZMu` (see PR [2]).
A Tier 0 replay [3] was started in order to test the new release before putting in production and failure was observed in one of PbPb physics skims (PbPbZMu, details at [3] and https://github.com/cms-sw/cmssw/pull/46458#discussion_r1826519949).
As discussed in the tentative fix PR (https://github.com/cms-sw/cmssw/pull/46584#issuecomment-2452915473) it appears there's no appropriate set of PbPb relvals to test the Heavy Ion skims.
It would be appropriate to add them to spot issues when changes are made in release, *before* leading to a crash in Tier0.

-----
[1] [Production Release CMSSW_14_1_4_patch4 Available Now](https://cms-talk.web.cern.ch/t/production-release-cmssw-14-1-4-patch4-available-now/58361)
[2] https://github.com/cms-sw/cmssw/pull/46458
[3] [Replay for CMSSW_14_1_4_patch4](https://cms-talk.web.cern.ch/t/replay-for-cmssw-14-1-4-patch4/58204)
[4] [Replay for CMSSW_14_1_4_patch4 - #3](https://cms-talk.web.cern.ch/t/replay-for-cmssw-14-1-4-patch4/58204/3)

**Comment by mmusich** [comment]
assign pdvm

**Comment by mmusich** [comment]
@youyingli @mandrenguyen FYI

**Comment by youyingli** [comment]
> @youyingli @mandrenguyen FYI

These new PbPb skims have new triggers from 2024. There is no RAW data for test. But for the ```PbPbZMu``` skim with the same trigger as 2023, I can quickly make a PR to build a workflow for this skim with 2023 RAW data.

**Comment by mmusich** [comment]
> These new PbPb skims have new triggers from 2024. There is no RAW data for test.

what about MC? The new menu is available in release since last week (see https://github.com/cms-sw/cmssw/pull/46508). 
Also there are a couple of PbPb setup runs that can be used taken during the week (e.g. [387456](https://cmsoms.cern.ch/cms/runs/report?cms_run=387456), which is the run in which the Tier0 replay failed)

**Comment by youyingli** [comment]
> > These new PbPb skims have new triggers from 2024. There is no RAW data for test.
> 
> what about MC? The new menu is available in release since last week (see #46508). Also there are a couple of PbPb setup runs that can be used taken during the week (e.g. [387456](https://cmsoms.cern.ch/cms/runs/report?cms_run=387456), which is the run in which the Tier0 replay failed)

As I find out the following are DISK available, I could use these files temporarily to make a PR for the test. 

```/HIForward10/Tier0_HIREPLAY_2024-v1194758/RAW```
```/HIPhysicsRawPrime1/Tier0_HIREPLAY_2024-v1194758/RAW```

**Comment by AdrianoDee** [comment]
> what about MC?

I was thinking the same thing. What is preventing us from testing the SKIMs on MC?

**Comment by mmusich** [comment]
> I could use these files temporarily to make a PR for the test.

I'd rather NOT depend on the products of a Tier0 replay for relval tests

**Comment by mandrenguyen** [comment]
> > what about MC?
> 
> I was thinking the same thing. What is preventing us from testing the SKIMs on MC?
> 
> Edit: in general, also for pp.

We don't have the 2024 trigger menu yet in MC.

**Comment by mmusich** [comment]
> We don't have the 2024 trigger menu yet in MC.

how come? can't you just generate some in relvals? As mentioned the menu is in release...

**Comment by AdrianoDee** [comment]
+pdmv
(solved by https://github.com/cms-sw/cmssw/pull/46589)
