### ISSUE TITLE
Run profiling on baseline release and save root output for comparison of RECO process for PRs

### ISSUE THREAD

**Issue by gartung** [cms-sw/cmssw#46602]
I need to set the number of events to 100 and I wanted to avoid running that many for every IB.

Step 1 and step 2 are run for each job so technically the input for step3 RECO is different. On average the results should be the same but not with the limited stats of 10 events.

Saving the output root files and json files from the two workflows used in profiling would allow profiling the PR with the same RECO input as the baseline.

**Comment by gartung** [comment]
https://github.com/cms-sw/cms-bot/pull/2366

**Comment by gartung** [comment]
Using the same input step2.root for the RECO step still results in larger differences in module timing than expected. 
Perhaps taking  difference of  the fraction of the total time would be a better metric.

**Comment by makortel** [comment]
Are the step1 and/or step2 run with multiple threads in the profiling workflow? On a single thread their output should be exactly the same (which is verified in PR test comparisons).

**Comment by gartung** [comment]
All jobs are run single threaded.

**Comment by gartung** [comment]
The differences in total job time might be caused by running on different VMs. I am modifying the PR profiling script to run both IB and IB+PR profiling on the same VM.
