### ISSUE TITLE
Dropping __future__ from cmssw

### ISSUE THREAD

**Issue by smuzaffar** [cms-sw/cmssw#46762]
We have many python files (over 900) with statements like [a] which we had added for python2/3 compatibility. As CMSSW only supports python3, so I suggest to remove all these lines.

We will open PRs (one per category) to remove these statements.

[a]
```
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function
```

**Comment by makortel** [comment]
assign core

**Comment by kpedro88** [comment]
@smuzaffar according to https://docs.python.org/3/library/__future__.html#module-contents, I do not think `from __future__ import annotations` should be dropped in this cleanup. This is a python3-specific feature. (`generator_stop` is also on the list of newer python3-only `__future__` features, but that one does not currently appear to be used anywhere in CMSSW.)

**Comment by smuzaffar** [comment]
thanks @kpedro88 , you are right `annotations` will be default in python 4 so yes `from __future__ import annotations` should not be removed. Luckily we only have one place where it is used. I have updated the PR to reintroduce it.

**Comment by smuzaffar** [comment]
+core
closing this as all `__future__` statements except one `from __future__ import annotations` from https://github.com/cms-sw/cmssw/blob/master/RecoLocalMuon/GEMCSCSegment/test/plotGEMCSCCoincidenceRate.py#L2 are removed from cmssw
