### ISSUE TITLE
Phase 2 RelVal samples are produced with 35 average PU per bunch crossing instead of the usual 200

### ISSUE THREAD

**Issue by Parsifal-2045** [cms-sw/cmssw#46839]
The PU option for Phase 2 workflows defaults to `AVE_35_BX_25ns` instead of the previous `AVE_200_BX_25ns`. I've solved the issue locally by changing `2026` to `Run4` in [Configuration/PyReleaseValidation/python/relval_steps.py](https://github.com/cms-sw/cmssw/blob/3be60c77df03988f0c0936911c48eeb6635116be/Configuration/PyReleaseValidation/python/relval_steps.py#L4436). 
This produces the correct cmsDriver command and should have no other repercussions.

**Comment by Parsifal-2045** [comment]
@AdrianoDee @mmusich

**Comment by mmusich** [comment]
assign pdmv

**Comment by mmusich** [comment]
assign upgrade

**Comment by mmusich** [comment]
@srimanob FYI

**Comment by AdrianoDee** [comment]
Thanks @Parsifal-2045 for spotting this, I've opened:
- https://github.com/cms-sw/cmssw/pull/46841
- https://github.com/cms-sw/cmssw/pull/46842
to fix this. 

For `14_2_0_pre4` pre-release Phase2 PU RelVal production we will just have to change that by hand.

**Comment by Parsifal-2045** [comment]
Unfortunately it also appears that the pileup input file is wrong when this change is implemented.

```bash
An exception of category 'NoSecondaryFiles' occurred while
   [0] Constructing the EventProcessor
   [1] Constructing module: class=MixingModule label='mix'
Exception Message:
RootEmbeddedFileSequence no input files specified for secondary input source.
```

 I haven't yet found how it should be changed

**Comment by mmusich** [comment]
> unfortunately it also appears that the pileup input file is wrong when this change is implemented.

from the error message it looks like you're just not getting the input files fro the PU mixing. Try to run `voms-proxy-init -voms cms` before (or use the `--ibeos` runTheMatrix option).

**Comment by Parsifal-2045** [comment]
> > unfortunately it also appears that the pileup input file is wrong when this change is implemented.
> 
> from the error message it looks like you're just not getting the input files for the PU mixing. Try to run `voms-proxy-init -voms cms` before (or use the `--ibeos` runTheMatrix option).

My bad, it looks like I run on a different lxplus instance from what I was using before 😅
