### ISSUE TITLE
ParameterSet/python/Config.py does not allow full release imports

### ISSUE THREAD

**Issue by smuzaffar** [cms-sw/cmssw#46937]
@makortel , https://github.com/cms-sw/cmssw-config/commit/91e7bf620361fad2a8427d018e8839c50c183263 change was using the realpath of imported python package. This was done so that edm class check script can import `FWCore.Reflection.ClassesDefXmlUtils` during the build phase of patch release. This change broke `TestIntegrationParameterSet` unit test. Here is what python directory looks like in patch release

- If FWCore is not part of patch release then we create symlink `cmssw-patch/python/FWCore` pointing to full release 
```
cmssw-patch/python/FWCore  -- symlink to --> cmssw/python/FWCore
```

- if FWCore is part of patch release then we create `cmssw-patch/python/FWCore` directory and create symlink for Integration
```
cmssw-patch/python/FWCore/Integration  -- symlink to --> cmssw/python/FWCore/Integration
```

After the cmssw-config update for python imports, in patch releases , imported python module path starts with

- CMSSW_FULL_RELEASE_BASE: If package is not part of patch release
- CMSSW_RELEASE_BASE: If package is part of patch release
- CMSSW_BASE: In devel area, if patch was locally checkout

The reason unit test https://cmssdt.cern.ch/SDT/cgi-bin/logreader/el8_amd64_gcc12/CMSSW_15_0_X_2024-12-13-1100/unitTestLogs/FWCore/Integration#/3356-3356 start failing was that https://github.com/cms-sw/cmssw/blob/master/FWCore/ParameterSet/python/Config.py#L55  only allows CMSSW_RELEASE_BASE and CMSSW_BASE. For now I have reverted the cmssw-config change. But do you think we should update https://github.com/cms-sw/cmssw/blob/master/FWCore/ParameterSet/python/Config.py#L55 and also allow CMSSW_FULL_RELEASE_BASE ?

**Comment by smuzaffar** [comment]
assign core

**Comment by makortel** [comment]
> But do you think we should update https://github.com/cms-sw/cmssw/blob/master/FWCore/ParameterSet/python/Config.py#L55 and also allow CMSSW_FULL_RELEASE_BASE ?

I think `CMSSW_FULL_RELEASE_BASE` can be added there. It also seems to me the `checkImportPermission()` is not used for anything besides those tests.

**Comment by makortel** [comment]
+core
