### ISSUE TITLE
[DAS] Relval 13240.303 failing with DAS Error

### ISSUE THREAD

**Issue by iarspider** [cms-sw/cmssw#46957]
Title says it all. No error is reported in the log: [link](https://cmssdt.cern.ch/SDT/cgi-bin/logreader/el8_amd64_gcc12/CMSSW_15_0_X_2024-12-15-2300/pyRelValMatrixLogs/run/13240.303_MinBias_14TeV+2022FS_Run3FSMBMixing/step1_dasquery.log), but relval fails.

**Comment by smuzaffar** [comment]
In 14.2.X, this workflow is using `dataset=/RelValMinBias_14TeV/CMSSW_12_4_13-124X_mcRun3_2022_realistic_v12_2021_FastSim-v1/GEN` while in 15.0.X this workflow is searching for `dataset=/RelValMinBias_14TeV/CMSSW_14_0_18-140X_mcRun3_2022_realistic_v12_2022_FastSim_Run3_FastSim-v1/GEN` . So it this new dataset available?

**Comment by smuzaffar** [comment]
@AdrianoDee , could this is side effect of https://github.com/cms-sw/cmssw/pull/46793 change ?

**Comment by iarspider** [comment]
assign pdmv

**Comment by AdrianoDee** [comment]
Producing the missing sample

**Comment by AdrianoDee** [comment]
I don't see it anymore, right?

**Comment by iarspider** [comment]
Yes, fixed since CMSSW_15_0_X_2024-12-17-1100. Thanks!

**Comment by iarspider** [comment]
@cmsbuild please close

**Comment by AdrianoDee** [comment]
+pdmv
