### ISSUE TITLE
Allow tests to declare a dependence to a library built in the same BuildFile.xml

### ISSUE THREAD

**Issue by makortel** [cms-sw/cmssw#47027]
E.g. here
https://github.com/cms-sw/cmssw/blob/a89b1d2f79d6da07554ed94cac9de4d0395cd38c/IOPool/Input/test/BuildFile.xml#L16-L27

The `TestIOPoolInputSchemaEvolution` test configuration uses plugins defined in `SchemaEvolutionTest` library target. In order for parallel `scram b runtests` to guarantee building the library before running the test, it would be useful to be able to declare the dependence e.g. along
```xml
<test name="TestIOPoolInputSchemaEvolution" command="testSchemaEvolution.sh">
  <use name="SchemaEvolutionTest"/>
<test/>
```

**Comment by makortel** [comment]
assign core

**Comment by makortel** [comment]
@smuzaffar I remember us discussing about this in some issue or PR (I wasn't able to find it anymore), but I don't remember (and wasn't able to quickly find) if you already addressed it, so I opened a dedicated issue.

**Comment by smuzaffar** [comment]
@makortel , for `<test ....> </test>` you can just use `<lib name="Name"/>` to add the dependency e.g. in this case
```
<test name="TestIOPoolInputSchemaEvolution" command="testSchemaEvolution.sh">
  <lib name="SchemaEvolutionTest"/>
<test/>
```

this will makes sure that `SchemaEvolutionTest` is built before running the unit test `TestIOPoolInputSchemaEvolution`. Note that this will only work for `<test> </test>` type unit tests. For `<bin ...></bin>` it will not work as scram will try to link against `SchemaEvolutionTest` (which will fail if `SchemaEvolutionTest` is a plugin).

If this is confusing the I can add a new flag e.g. `<flag PRE_BUILD="SchemaEvolutionTest"/>` to make sure `SchemaEvolutionTest` (whatever it is) is built before the unit tests

**Comment by makortel** [comment]
@smuzaffar Ah, the syntax was `<lib name="..."/>`. I can live with that (even if I would have found `<use name="..."/>` more intuitive, but I can see that could be confusing as well because the `<test>` is not linked against those dependencies). In a way I personally like more specifying the dependencies for each `<test>` separately rather than "these libraries need to be built before any tests".

**Comment by makortel** [comment]
+core

**Comment by makortel** [comment]
type documentation
