### ISSUE TITLE
Removal from the list of AlCa managers

### ISSUE THREAD

**Issue by rcastello** [cms-sw/cmssw#7356]
@degano @ktf : given I step down from my AlCa convenorship at the end of December 2014, could you please remove me from the list of people signing PR concerning AlCa CMSSW packages?

Thanks in advance,
Roberto

**Comment by ktf** [comment]
@degano can you take care of this?

**Comment by degano** [comment]
@ktf I'm on it.

**Comment by degano** [comment]
@rcastello done and merged in: https://github.com/cms-sw/cms-bot/pull/305.
Closig this issue.

**Comment by rcastello** [comment]
thanks!
