### ISSUE TITLE
cannot clone repository (almost first usage of git)

### ISSUE THREAD

**Issue by albertobelloni** [cms-sw/cmssw#8182]
Hello,
I am trying to clone the genproductions repository on github. The suggested command is:

git clone git@github.com:<your_account>/genproductions.git genproductions

I tried using both my github account name (which definitely seems the most likely to work option) and my CERN username; in either case, I get the following message:

Initialized empty Git repository in /afs/cern.ch/work/a/abelloni/genproductions/.git/
Permission denied (publickey).
fatal: The remote end hung up unexpectedly

I tried renaming my .ssh directory, in case some curd there were working against me, but the result is the same. I suspect I am missing something very trivial. Would you have any suggestion? Thanks a lot! Best,

Alberto

**Comment by albertobelloni** [comment]
Hello,

I think I had some mix up with the ssh keys. The next error is clear, but I wonder where I can get an update. I see:

git clone -v git@github.com:albertobelloni/genproductions.git genproductions
Initialized empty Git repository in /afs/cern.ch/work/a/abelloni/genproductions/.git/
Enter passphrase for key '/afs/cern.ch/user/a/abelloni/.ssh/id_rsa':
ERROR: Repository not found.
fatal: The remote end hung up unexpectedly

which rather clearly points at the repository not existing. I will try changing the repository name a bit, but I wonder if there were a list of *.git repositories in cms-sw where one could unequivocally identify the string to use to clone them. Thanks for any suggestion! Best,

Alberto

**Comment by slava77** [comment]
would this work:

git clone https://github.com/cms-sw/genproductions.git genproductions

?

the path has to include the account (cms-sw) as well



On 3/10/15 8:24 PM, albertobelloni wrote:
> Hello,
> I am trying to clone the genproductions repository on github. The
> suggested command is:
> 
> git clone git@github.com <mailto:git@github.com>:/genproductions.git
> genproductions
> 
> I tried using both my github account name (which definitely seems the
> most likely to work option) and my CERN username; in either case, I get
> the following message:
> 
> Initialized empty Git repository in
> /afs/cern.ch/work/a/abelloni/genproductions/.git/
> Permission denied (publickey).
> fatal: The remote end hung up unexpectedly
> 
> I tried renaming my .ssh directory, in case some curd there were working
> against me, but the result is the same. I suspect I am missing something
> very trivial. Would you have any suggestion? Thanks a lot! Best,
> 
> Alberto
> 
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cms-sw/cmssw/issues/8182>.
> 

-- 
***********************************************************************
 Vyacheslav (Slava) Krutelyov
 TAMU: Physics Dept Texas A&M MS4242, College Station, TX 77843-4242
 CERN: 42-R-027
 AIM/Skype: siava16              googleTalk: slava77@gmail.com
 (630) 291-5128  Cell (US)       +41 76 275 7116 Cell (CERN)

-----------------------------------------------------------------------

**Comment by albertobelloni** [comment]
Hi Slava,

indeed, that worked. I followed the instructions presented in:

https://twiki.cern.ch/twiki/bin/viewauth/CMS/GitRepositoryForGenProduction<https://twiki.cern.ch/twiki/bin/viewauth/CMS/GitRepositoryForGenProduction#One_time_setup>#One_time_setup<https://twiki.cern.ch/twiki/bin/viewauth/CMS/GitRepositoryForGenProduction>

and they seem to skip the https part. Thanks a lot! Best,

Alberto
