### ISSUE TITLE
Add CMSSW_6_2_SLHCDEV_X IB

### ISSUE THREAD

**Issue by ktf** [cms-sw/cmssw#8587]
@nclopezo Can you please setup an IB called CMSSW_6_2_SLHCDEV_X, using a branch which is derived from the current HEAD of  CMSSW_6_2_X_SLHC and which gets automatic merges from it?

@davidlange6 @mark-grimes

**Comment by nclopezo** [comment]
I did it here: https://github.com/cms-sw/cms-bot/pull/416

**Comment by ktf** [comment]
Can you start an IB, just to check everything is fine?

**Comment by nclopezo** [comment]
CMSSW_6_2_SLHCDEV_X_2015-03-30-1600
Is available now for slc6_amd64_gcc472 I will check why it is not showing in the IB pages

**Comment by nclopezo** [comment]
The IB is now there and it is in the [IB pages](https://cmssdt.cern.ch/SDT/html/showIB.html#CMSSW_6_2_SLHCDEV_X)
