### ISSUE TITLE
edm::EventSetup::tryToGet not working

### ISSUE THREAD

**Issue by mverzett** [cms-sw/cmssw#8772]
Dear experts,

I am having troubles compiling my code, which attempt to use edm::EventSetup::tryToGet. It seems that there is no right combination of types in input and output.

From my understanding the issue is here:
https://github.com/cms-sw/cmssw/blob/CMSSW_7_5_X/FWCore/Framework/interface/EventSetup.h#L73

where there should not be a * in front of value.

Best,

Mauro

**Comment by Dr15Jones** [comment]
Should be fixed in #8802 
Thanks for reporting the problem.
