### ISSUE TITLE
PR integration race condition?

### ISSUE THREAD

**Issue by davidlange6** [cms-sw/cmssw#8871]
The CMSSW_7_5_X_2015-04-23-2300 build appears to have picked up only part of #8833, causing some run time problems. I guess there is a race condition either on our side or on the git hub side that brought in only part of a commit. The repo is consistent now, so it was a transient effect.

Anything that we can do about this beyond not accepting PRs at 10:59:59.99999?

@ktf, @smuzaffar, @nclopezo @degano

**Comment by davidlt** [comment]
Git itself cannot have inconsistent state. Maybe its -x ours? That is merge conflict, and -x ours made a mess out of it.

**Comment by nclopezo** [comment]
It seems that it was caused by the porting of https://github.com/cms-sw/cmssw/pull/8805/ which contains https://github.com/cms-sw/cmssw/commit/7be30ee4f98efae95aa35bb14e28dd6588eb0d01

**Comment by davidlange6** [comment]
> On Apr 24, 2015, at 1:55 PM, davidlt <notifications@github.com> wrote:
> 
> Git itself cannot have inconsistent state. Maybe its -x ours? That is merge conflict, and -x ours made a mess out of it.

to be clear - the state of the repo is now fully consistent. - just not at the moment that the IB was triggered.
