### ISSUE TITLE
git cms-addpkg issue fatal: destination path '/gpfs22/home/janjamrk/CMSSW_7_4_0_pre8/src' already exists and is not an empty directory.

### ISSUE THREAD

**Issue by ravijanjam** [cms-sw/cmssw#8963]
I am trying to do 
git cms-addpkg RecoTracker/TrackProducer, I get the fatal destination path error. 
git cms-addpkg issue fatal: destination path '/gpfs22/home/janjamrk/CMSSW_7_4_0_pre8/src' already exists and is not an empty directory.

What can I do to sort this error out?

**Comment by davidlange6** [comment]
As suggested by the error message - remove everything from your src area. git needs a clean working directory when creating a repository (e.g., when checking out a package)

**Comment by ravijanjam** [comment]
Thanks, it worked !!
