### ISSUE TITLE
watcher for DQM/RPCMonitorDigi and DQM/RPCMonitorClient

### ISSUE THREAD

**Issue by acimmino** [cms-sw/cmssw#9275]
Could I, please, be added as a watcher for these two packages: DQM/RPCMonitorDigi and DQM/RPCMonitorClient ? 
Thank you,
Anna

**Comment by degano** [comment]
@acimmino Sorry for not answering to this earlier. Is this still requested?

**Comment by acimmino** [comment]
Dear Alessandro,

Yes, the request is still needed. Thank you.

Thanks.
Anna

________________________________

**Comment by davidlt** [comment]
Done

https://github.com/cms-sw/cms-bot/commit/a114aba8c92c2c9b988a7aaedbcf208987918f09

Apologies for the delay.
