### ISSUE TITLE
Read-only CVS access

### ISSUE THREAD

**Issue by dfehling** [cms-sw/cmssw#9304]
I tried to follow the instructions on the page to access an old package that didn't make the transition to CVS. However, I get an error that I can't seem to get around.

 setenv CVSROOT ":ext:dfehling@lxplus6.cern.ch:/afs/cern.ch/user/c/cvscmssw/public/CMSSW"
setenv CVS_RSH ssh

cvs co RecoTracker/PixelStubs
The authenticity of host 'lxplus6.cern.ch (188.184.69.204)' can't be established.
RSA key fingerprint is a4:9f:57:6b:d5:4e:4d:56:85:ba:99:db:8c:2a:8e:b7.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added 'lxplus6.cern.ch,188.184.69.204' (RSA) to the list of known hosts.
Password: 
cvs checkout: Updating RecoTracker/PixelStubs
cvs checkout: failed to create lock directory for `/afs/cern.ch/user/c/cvscmssw/public/CMSSW/CMSSW/RecoTracker/PixelStubs' (/afs/cern.ch/cms/sdt/cvslocks/CMSSW/RecoTracker/PixelStubs/#cvs.lock): Disk quota exceeded
cvs checkout: failed to obtain dir lock in repository `/afs/cern.ch/user/c/cvscmssw/public/CMSSW/CMSSW/RecoTracker/PixelStubs'
cvs [checkout aborted]: read lock failed - giving up

Is there another way to get this code from CVS and into git? The package doesn't appear to be in the imported-cvs-head branch either.

**Comment by davidlange6** [comment]
https://hypernews.cern.ch/HyperNews/CMS/get/sw-develtools/2289/2.html

**Comment by dfehling** [comment]
Thank you! I didn't know that this had already been taken care of.
