### ISSUE TITLE
[CMSSW_7_5_X] unused selection rules in dictionaries

### ISSUE THREAD

**Issue by davidlt** [cms-sw/cmssw#9374]
Below you can find a full list on unused selection rules for packages in CMSSW based on CMSSW_7_5_DEVEL_X_2015-05-23-2300.

- [x] `AnalysisDataFormats/Egamma 				Warning - unused class rule: edm::KeyVal<*>`
- [x] `AnalysisDataFormats/TrackInfo 			Warning - unused class rule: reco::TrackingStateInfo`
- [x] `CondFormats/Alignment 					Warning - unused class rule: uint32_t`
- [x] `DataFormats/EgammaReco 					Warning - unused class rule: edm::KeyVal<*>`
- [x] `DataFormats/Math 						Warning - unused class rule: ROOT::Math::Polar3D<*>`
- [x] `DataFormats/PatCandidates 				Warning - unused class rule: std::iterator<std::random_access_iterator_tag,edm::Ref<std::vector<pat::TriggerAlgorithm>,pat::TriggerAlgorithm,edm::refhelper::FindUsingAdvance<std::vector<pat::TriggerAlgorithm>,pat::TriggerAlgorithm> >,*,edm::Ref<std::vector<pat::TriggerAlgorithm>,pat::TriggerAlgorithm,edm::refhelper::FindUsingAdvance<std::vector<pat::TriggerAlgorithm>,pat::TriggerAlgorithm> >*,edm::Ref<std::vector<pat::TriggerAlgorithm>,pat::TriggerAlgorithm,edm::refhelper::FindUsingAdvance<std::vector<pat::TriggerAlgorithm>,pat::TriggerAlgorithm> >&amp;amp;>`
- [x] `DataFormats/PatCandidates 				Warning - unused class rule: std::iterator<std::random_access_iterator_tag,edm::Ref<std::vector<pat::TriggerCondition>,pat::TriggerCondition,edm::refhelper::FindUsingAdvance<std::vector<pat::TriggerCondition>,pat::TriggerCondition> >,*,edm::Ref<std::vector<pat::TriggerCondition>,pat::TriggerCondition,edm::refhelper::FindUsingAdvance<std::vector<pat::TriggerCondition>,pat::TriggerCondition> >*,edm::Ref<std::vector<pat::TriggerCondition>,pat::TriggerCondition,edm::refhelper::FindUsingAdvance<std::vector<pat::TriggerCondition>,pat::TriggerCondition> >&amp;amp;>`
- [x] `DataFormats/PatCandidates 				Warning - unused class rule: std::iterator<std::random_access_iterator_tag,edm::Ref<std::vector<pat::TriggerObject>,pat::TriggerObject,edm::refhelper::FindUsingAdvance<std::vector<pat::TriggerObject>,pat::TriggerObject> >,*,edm::Ref<std::vector<pat::TriggerObject>,pat::TriggerObject,edm::refhelper::FindUsingAdvance<std::vector<pat::TriggerObject>,pat::TriggerObject> >*,edm::Ref<std::vector<pat::TriggerObject>,pat::TriggerObject,edm::refhelper::FindUsingAdvance<std::vector<pat::TriggerObject>,pat::TriggerObject> >&amp;amp;>`
- [x] `DataFormats/PatCandidates 				Warning - unused class rule: std::iterator<std::random_access_iterator_tag,edm::Ref<std::vector<pat::TriggerFilter>,pat::TriggerFilter,edm::refhelper::FindUsingAdvance<std::vector<pat::TriggerFilter>,pat::TriggerFilter> >,*,edm::Ref<std::vector<pat::TriggerFilter>,pat::TriggerFilter,edm::refhelper::FindUsingAdvance<std::vector<pat::TriggerFilter>,pat::TriggerFilter> >*,edm::Ref<std::vector<pat::TriggerFilter>,pat::TriggerFilter,edm::refhelper::FindUsingAdvance<std::vector<pat::TriggerFilter>,pat::TriggerFilter> >&amp;amp;>`
- [x] `DataFormats/PatCandidates 				Warning - unused class rule: std::iterator<std::random_access_iterator_tag,edm::Ref<std::vector<pat::TriggerObjectStandAlone>,pat::TriggerObjectStandAlone,edm::refhelper::FindUsingAdvance<std::vector<pat::TriggerObjectStandAlone>,pat::TriggerObjectStandAlone> >,*,edm::Ref<std::vector<pat::TriggerObjectStandAlone>,pat::TriggerObjectStandAlone,edm::refhelper::FindUsingAdvance<std::vector<pat::TriggerObjectStandAlone>,pat::TriggerObjectStandAlone> >*,edm::Ref<std::vector<pat::TriggerObjectStandAlone>,pat::TriggerObjectStandAlone,edm::refhelper::FindUsingAdvance<std::vector<pat::TriggerObjectStandAlone>,pat::TriggerObjectStandAlone> >&amp;amp;>`
- [x] `DataFormats/PatCandidates 				Warning - unused class rule: std::iterator<std::random_access_iterator_tag,edm::Ref<std::vector<pat::TriggerPath>,pat::TriggerPath,edm::refhelper::FindUsingAdvance<std::vector<pat::TriggerPath>,pat::TriggerPath> >,*,edm::Ref<std::vector<pat::TriggerPath>,pat::TriggerPath,edm::refhelper::FindUsingAdvance<std::vector<pat::TriggerPath>,pat::TriggerPath> >*,edm::Ref<std::vector<pat::TriggerPath>,pat::TriggerPath,edm::refhelper::FindUsingAdvance<std::vector<pat::TriggerPath>,pat::TriggerPath> >&amp;amp;>`
- [x] `DataFormats/RecoCandidate 				Warning - unused class rule: edm::RefVector<edm::AssociationMap<*>`
- [x] `DataFormats/RecoCandidate 				Warning - unused class rule: edm::RefProd<edm::AssociationMap<*>`
- [x] `DataFormats/RecoCandidate 				Warning - unused class rule: edm::Ref<edm::AssociationMap<*>`
- [x] `DataFormats/RecoCandidate 				Warning - unused class rule: edm::KeyVal<*>`
- [x] `DataFormats/TrackCandidate 				Warning - unused class rule: edm::KeyVal<*>`
- [x] `DataFormats/TrackReco 					Warning - unused class rule: edm::RefVector<edm::AssociationMap<*>`
- [x] `DataFormats/TrackReco 					Warning - unused class rule: edm::RefProd<edm::AssociationMap<*>`
- [x] `DataFormats/TrackReco 					Warning - unused class rule: edm::Ref<edm::AssociationMap<*>`
- [x] `DataFormats/TrackReco 					Warning - unused class rule: edm::KeyVal<*>`
- [x] `SimDataFormats/TrackingAnalysis 		Warning - unused class rule: edm::Wrapper<edm::RefVector<std::vector<TrackingParticle>,*> >`
- [x] `SimDataFormats/TrackingAnalysis 		Warning - unused class rule: edm::RefVector< std::vector<HepMC::GenVertex>,*>`
- [x] `SimDataFormats/TrackingAnalysis 		Warning - unused class rule: edm::Ref< std::vector<HepMC::GenVertex>,*>`
- [x] `SimDataFormats/TrackingAnalysis 		Warning - unused class rule: edm::RefVector<std::vector<TrackingParticle>,*>`
- [x] `SimDataFormats/TrackingAnalysis 		Warning - unused class rule: edm::Ref<std::vector<TrackingParticle>,*>`
- [x] `SimDataFormats/TrackingAnalysis 		Warning - unused class rule: edm::RefVector<std::vector<TrackingVertex>,*>`
- [x] `SimDataFormats/TrackingAnalysis 		Warning - unused class rule: edm::Ref<std::vector<TrackingVertex>,*>`
- [x] `SimDataFormats/Vertex 					Warning - unused class rule: edm::RefVector<std::vector<SimVertex>,*>`
- [x] `SimDataFormats/Vertex 					Warning - unused class rule: edm::Ref<std::vector<SimVertex>,*>`
- [x] `TrackingTools/PatternTools 				Warning - unused class rule: edm::KeyVal<*>`
- [x] `TrackingTools/TrajectoryState 			Warning - unused class rule: edm::Wrapper<edm::AssociationMap<edm::OneToOne<reco::TrackCollection,std::vector<TrackParamConstraint> > >`
```
AnalysisDataFormats/Egamma 				Warning - unused class rule: edm::KeyVal<*>
AnalysisDataFormats/TrackInfo 			Warning - unused class rule: reco::TrackingStateInfo
CondFormats/Alignment 					Warning - unused class rule: uint32_t
DataFormats/EgammaReco 					Warning - unused class rule: edm::KeyVal<*>
DataFormats/Math 						Warning - unused class rule: ROOT::Math::Polar3D<*>
DataFormats/PatCandidates 				Warning - unused class rule: std::iterator<std::random_access_iterator_tag,edm::Ref<std::vector<pat::TriggerAlgorithm>,pat::TriggerAlgorithm,edm::refhelper::FindUsingAdvance<std::vector<pat::TriggerAlgorithm>,pat::TriggerAlgorithm> >,*,edm::Ref<std::vector<pat::TriggerAlgorithm>,pat::TriggerAlgorithm,edm::refhelper::FindUsingAdvance<std::vector<pat::TriggerAlgorithm>,pat::TriggerAlgorithm> >*,edm::Ref<std::vector<pat::TriggerAlgorithm>,pat::TriggerAlgorithm,edm::refhelper::FindUsingAdvance<std::vector<pat::TriggerAlgorithm>,pat::TriggerAlgorithm> >&amp;amp;>
DataFormats/PatCandidates 				Warning - unused class rule: std::iterator<std::random_access_iterator_tag,edm::Ref<std::vector<pat::TriggerCondition>,pat::TriggerCondition,edm::refhelper::FindUsingAdvance<std::vector<pat::TriggerCondition>,pat::TriggerCondition> >,*,edm::Ref<std::vector<pat::TriggerCondition>,pat::TriggerCondition,edm::refhelper::FindUsingAdvance<std::vector<pat::TriggerCondition>,pat::TriggerCondition> >*,edm::Ref<std::vector<pat::TriggerCondition>,pat::TriggerCondition,edm::refhelper::FindUsingAdvance<std::vector<pat::TriggerCondition>,pat::TriggerCondition> >&amp;amp;>
DataFormats/PatCandidates 				Warning - unused class rule: std::iterator<std::random_access_iterator_tag,edm::Ref<std::vector<pat::TriggerObject>,pat::TriggerObject,edm::refhelper::FindUsingAdvance<std::vector<pat::TriggerObject>,pat::TriggerObject> >,*,edm::Ref<std::vector<pat::TriggerObject>,pat::TriggerObject,edm::refhelper::FindUsingAdvance<std::vector<pat::TriggerObject>,pat::TriggerObject> >*,edm::Ref<std::vector<pat::TriggerObject>,pat::TriggerObject,edm::refhelper::FindUsingAdvance<std::vector<pat::TriggerObject>,pat::TriggerObject> >&amp;amp;>
DataFormats/PatCandidates 				Warning - unused class rule: std::iterator<std::random_access_iterator_tag,edm::Ref<std::vector<pat::TriggerFilter>,pat::TriggerFilter,edm::refhelper::FindUsingAdvance<std::vector<pat::TriggerFilter>,pat::TriggerFilter> >,*,edm::Ref<std::vector<pat::TriggerFilter>,pat::TriggerFilter,edm::refhelper::FindUsingAdvance<std::vector<pat::TriggerFilter>,pat::TriggerFilter> >*,edm::Ref<std::vector<pat::TriggerFilter>,pat::TriggerFilter,edm::refhelper::FindUsingAdvance<std::vector<pat::TriggerFilter>,pat::TriggerFilter> >&amp;amp;>
DataFormats/PatCandidates 				Warning - unused class rule: std::iterator<std::random_access_iterator_tag,edm::Ref<std::vector<pat::TriggerObjectStandAlone>,pat::TriggerObjectStandAlone,edm::refhelper::FindUsingAdvance<std::vector<pat::TriggerObjectStandAlone>,pat::TriggerObjectStandAlone> >,*,edm::Ref<std::vector<pat::TriggerObjectStandAlone>,pat::TriggerObjectStandAlone,edm::refhelper::FindUsingAdvance<std::vector<pat::TriggerObjectStandAlone>,pat::TriggerObjectStandAlone> >*,edm::Ref<std::vector<pat::TriggerObjectStandAlone>,pat::TriggerObjectStandAlone,edm::refhelper::FindUsingAdvance<std::vector<pat::TriggerObjectStandAlone>,pat::TriggerObjectStandAlone> >&amp;amp;>
DataFormats/PatCandidates 				Warning - unused class rule: std::iterator<std::random_access_iterator_tag,edm::Ref<std::vector<pat::TriggerPath>,pat::TriggerPath,edm::refhelper::FindUsingAdvance<std::vector<pat::TriggerPath>,pat::TriggerPath> >,*,edm::Ref<std::vector<pat::TriggerPath>,pat::TriggerPath,edm::refhelper::FindUsingAdvance<std::vector<pat::TriggerPath>,pat::TriggerPath> >*,edm::Ref<std::vector<pat::TriggerPath>,pat::TriggerPath,edm::refhelper::FindUsingAdvance<std::vector<pat::TriggerPath>,pat::TriggerPath> >&amp;amp;>
DataFormats/RecoCandidate 				Warning - unused class rule: edm::RefVector<edm::AssociationMap<*>
DataFormats/RecoCandidate 				Warning - unused class rule: edm::RefProd<edm::AssociationMap<*>
DataFormats/RecoCandidate 				Warning - unused class rule: edm::Ref<edm::AssociationMap<*>
DataFormats/RecoCandidate 				Warning - unused class rule: edm::KeyVal<*>
DataFormats/TrackCandidate 				Warning - unused class rule: edm::KeyVal<*>
DataFormats/TrackReco 					Warning - unused class rule: edm::RefVector<edm::AssociationMap<*>
DataFormats/TrackReco 					Warning - unused class rule: edm::RefProd<edm::AssociationMap<*>
DataFormats/TrackReco 					Warning - unused class rule: edm::Ref<edm::AssociationMap<*>
DataFormats/TrackReco 					Warning - unused class rule: edm::KeyVal<*>
SimDataFormats/TrackingAnalysis 		Warning - unused class rule: edm::Wrapper<edm::RefVector<std::vector<TrackingParticle>,*> >
SimDataFormats/TrackingAnalysis 		Warning - unused class rule: edm::RefVector< std::vector<HepMC::GenVertex>,*>
SimDataFormats/TrackingAnalysis 		Warning - unused class rule: edm::Ref< std::vector<HepMC::GenVertex>,*>
SimDataFormats/TrackingAnalysis 		Warning - unused class rule: edm::RefVector<std::vector<TrackingParticle>,*>
SimDataFormats/TrackingAnalysis 		Warning - unused class rule: edm::Ref<std::vector<TrackingParticle>,*>
SimDataFormats/TrackingAnalysis 		Warning - unused class rule: edm::RefVector<std::vector<TrackingVertex>,*>
SimDataFormats/TrackingAnalysis 		Warning - unused class rule: edm::Ref<std::vector<TrackingVertex>,*>
SimDataFormats/Vertex 					Warning - unused class rule: edm::RefVector<std::vector<SimVertex>,*>
SimDataFormats/Vertex 					Warning - unused class rule: edm::Ref<std::vector<SimVertex>,*>
TrackingTools/PatternTools 				Warning - unused class rule: edm::KeyVal<*>
TrackingTools/TrajectoryState 			Warning - unused class rule: edm::Wrapper<edm::AssociationMap<edm::OneToOne<reco::TrackCollection,std::vector<TrackParamConstraint> > >
```

They are unused because there are no definitions in translation unit.

**Comment by davidlange6** [comment]
@wmtan

**Comment by davidlt** [comment]
This is a tracking ticket, thus adding two references to PRs: #9495 and #9492

**Comment by davidlt** [comment]
Another one: #9497

**Comment by davidlt** [comment]
Another two #9501 and #9403

**Comment by davidlt** [comment]
Adding more: #9505

**Comment by davidlt** [comment]
The last bit was #9578 (`std::iterator` 6 selection rules removed from selection file as discussed in ROOT planning meeting). These are not in IO rules and only needed for ROOT5 to have them available in the interpreter. Removed only in `CMSSW_7_5_ROOT64_X`.

Closing the issue.
