### ISSUE TITLE
PyReleaseValidation must check das_client status

### ISSUE THREAD

**Issue by vkuznet** [cms-sw/cmssw#9540]
While working on issue https://github.com/dmwm/DAS/issues/4234 I inspected the PyReleaseValidation code on how it uses das_client tool, see [1]. Unfortunately it is done in a wrong way. The code should check the status of das_client response before using its results. DAS systems has no guarantee that it will deliver data upon request due to possible failures from underlying CMS data-services, cache hits, etc. The success of the query will be provided with status=ok, otherwise client can initiate the query again. The code in [1] does not take this into account. The status as well as full output of results is available in JSON format when das_client.py called with --format=JSON option. I would advise release validation team to re-evaluate usage of the tool and properly use it in a code.
Best,
Valentin.

[1] https://github.com/cms-sw/cmssw/blob/CMSSW_7_5_X/Configuration/PyReleaseValidation/python/relval_steps.py#L58

**Comment by davidlange6** [comment]
Hi Valentin

Since we tend to get failures in bunches, how would you suggest the re-try be implemented?

Thanks
David

**Comment by vkuznet** [comment]
David to answer this question I need to know how upper code calls relval_steps:das function. Could you please point me in a right direction. It seems to me that you're spawning UNIX process. Instead you need to use das_client.py get_data API. It is python and it returns json dictionary. Once I'll see upper caller I can suggest re-try status check and re-try approach.

**Comment by davidlange6** [comment]
Hi Valentin

Its essentially running

runTheMatrix.py -l 1306 -i all

(for many workflows)

- so yes, spawning unix processes.

**Comment by vkuznet** [comment]
David,
I was interested in actual code which invokes das client call. My understanding
that it is done here:

https://github.com/cms-sw/cmssw/blob/CMSSW_7_5_X/Configuration/PyReleaseValidation/python/WorkFlowRunner.py#L191

Please confirm.

In this case I would suggest the following.
- write independent python function which will call das_client get_data API,
  e.g.

```
def dascall(*args): # here I'll assume you'll pass necessary parameters
    from das_client import get_data
    data = get_data(host, query, idx, limit, debug, thr, ckey, cert)
    if  isinstance(data, dict):
        jsondict = data
    else:
        jsondict = json.loads(data)
    status = jsondict.get('status', None)
    reason = jsondict.get('reason', None)
    nres   = jsondict.get('nresults', None)
    tstm   = jsondict.get('timestamp', 0)
    data   = jsondict.get('data')
    # put logic here to check status and nres
    # put another logic here to extract data you're interested in, e.g.
    # out = []
    # for key, val in data.items(): if key=='file': out.append(val)
    # return out
```

- you can either put retry inside dascall function, e.g. check for status and it is not 'ok'
  you sleep and invoke again (up to some attempts) or you can adjust WorkFlowRunner.py to do this step

- you may invoke dascall via multiprocess.Process python call which will mimic UNIX shell call.

One caveat though for this procedure. You'll need to know how to extract relevant data from
DAS json dict. DAS aggregates results from multiple CMS data-services and stores them as
list of dicts. Here is an example of (sub)-structure of data returned by get_data DAS client API
(I took output from file dataset=/a/b/c query and stripped off unnecessary bits):

```
{"status": "ok", ..., "nresults": 7, ...,
 "data": [{"das_id": ["557846ef9f6f25843f3622ee", "557846ef9f6f25843f3622ed"],
           "qhash": "f4e6ef509e38e5320b1910af61c71acd",
           "cache_id": ["557846ef9f6f25843f3622f1", "557846ef9f6f25843f3622f7"],
           "file": [{"adler32": "eb5450c4",
             "name": "/store/mc/Summer11/02ACAA1A-9F32-E111-BB31-0002C90B743A.root",
             "checksum": 2684046953, "creation_time": "2011-12-30 18:23:24",
             "replica": {..., "site": "T2_UK_London_Brunel", ..., "se": "dc2-grid-64.brunel.ac.uk"},
             "original_node": "", "id": 48796695, "size": 2063019163},
             .... other file dict entries
           ]}]
}
```

If you don't want to deal with such complexity, you may borrow the code I use
in das_client.py itself, see line
https://github.com/dmwm/DAS/blob/master/src/python/DAS/tools/das_client.py#L392
which received data and then lines (463-480)
https://github.com/dmwm/DAS/blob/master/src/python/DAS/tools/das_client.py#L463
which shows how to extract primary key values, i.e. the one requested in DAS query.
It can be done in generic way since DAS output records everything, input DAS query,
keys, status, data, etc.

I wish I was asked for this before by release validation team rather blindly use the tool
without understanding complexity behind it.

Another approach would be for me to modify das_client tool and return UNIX
status code to indicate status of DAS query look-up. And, of course, the best
way is to fix these issues with DAS server reported by Slava (I made progress
on it and I think I know the reason and the fix).  But regardless of them, DAS
cannot guarantee results since it does not hold the data and received them in
real-time from CMS data-services (therefore any issues with them will be blamed
on DAS).  Due to this nature users of das_client must check the status before
claiming that it does not work. If DAS returns fail status its jsondict will
contains the actual error.

I hope this helps and I'll try to provide a fix with DAS server issues asap.
Best,
Valentin.

**Comment by davidlt** [comment]
You cannot do `from das_client import get_data` as `das_client.py` is not in `PYTHONPATH`, which could fix very fast.

**Comment by davidlange6** [comment]
Hi Valentin

There is the one you found and this bit of code

def das(self, das_options):
        if len(self.run) is not 0:
            command = ";".join(["das_client.py %s --query '%s'" % (das_options, query) for query in self.queries()])
            command = "({0})".format(command)
        else:
            command = "das_client.py %s --query '%s'" % (das_options, self.queries()[0])
       

https://github.com/cms-sw/cmssw/blob/CMSSW_7_5_X/Configuration/PyReleaseValidation/python/relval_steps.py

**Comment by slava77** [comment]
It's a combination of
ConfigBuilder::filesFromDASQuery
https://github.com/cms-sw/cmssw/blob/13f1a1c1d532f4c345867ece12287505ffbb3647/Configuration/Applications/python/ConfigBuilder.py#L124

and
InputInfo::das
https://github.com/cms-sw/cmssw/blob/4ef6d5981dd81341ca2b3bc3d8b0239c1de3d421/Configuration/PyReleaseValidation/python/relval_steps.py

The latter is the main one, the former is used to get the minbias inputs
for pileup mixing.






On 6/10/15 8:02 AM, David Lange wrote:
> Hi Valentin
> 
> Its essentially running
> 
> runTheMatrix.py -l 1306 -i all
> 
> (for many workflows)
> 
> - so yes, spawning unix processes.
> 
>> On Jun 10, 2015, at 2:53 PM, Valentin Kuznetsov <notifications@github.com> wrote:
>> 
>> David to answer this question I need to know how upper code calls relval_steps:das function. Could you please point me in a right direction. It seems to me that you're spawning UNIX process. Instead you need to use das_client.py get_data API. It is python and it returns json dictionary. Once I'll see upper caller I can suggest re-try status check and re-try approach.
>> 
>> —
>> Reply to this email directly or view it on GitHub.
>> 
> 
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cms-sw/cmssw/issues/9540#issuecomment-110742736>.
> 

-- 
***********************************************************************
 Vyacheslav (Slava) Krutelyov
 TAMU: Physics Dept Texas A&M MS4242, College Station, TX 77843-4242
 CERN: 42-R-027
 AIM/Skype: siava16              googleTalk: slava77@gmail.com
 (630) 291-5128  Cell (US)       +41 76 275 7116 Cell (CERN)

-----------------------------------------------------------------------

**Comment by vkuznet** [comment]
David,
this one just construct das command, but its execution is passed to
WorkFlowRunner as far as I can tell. I think I provided a function which will
replace *das* function, but you'll need to work on *doCmd* to use
multiprocessing.Process instead of delegating das call into UNIX shell.
Valentin.

**Comment by smuzaffar** [comment]
@vkuznet , is this still a valid issue?  can we close it?

**Comment by vkuznet** [comment]
Not valid anymore
