### ISSUE TITLE
reset the list of packages I am subscribed to

### ISSUE THREAD

**Issue by venturia** [cms-sw/cmssw#9985]
I would like to reset the list of packages I am subscribed to. I would like to be subscribed ONLY to:
DPGAnalysis/SiStripTools
Validation/RecoVertex
DQM/SiStripMonitorSummary
DQM/SiStripMonitorClient
CommonTools/TrackerMap
Geometry/TrackerNumberingBuilder
Geometry/TrackerGeometryBuilder
Geometry/TrackerCommonData

Thanks

**Comment by smuzaffar** [comment]
please make a pull request for cms-sw/cms-bot  with update in watchers.yaml

**Comment by venturia** [comment]
done
